### ISSUE TITLE
[Panel] Use SVG for checkerboard pattern

### ISSUE THREAD

**Issue by paulrobertlloyd** [getkirby/kirby#10]
I noticed you’re using an image for the transparent checkerboard pattern. Small thing, but you could generate this background using a CSS gradient: https://lea.verou.me/css3patterns/#checkerboard

This would require one less file request, and would be easier to customise/theme, going forward. (Tiny, tiny improvement, but worth noting!)

**Comment by jenstornell** [comment]
It's a bit buggy. I'm using Chrome. Do you see the 45 degrees line?

![image](https://user-images.githubusercontent.com/927011/32230402-61cb8390-be53-11e7-8fa8-3f1a190f65c3.png)

In one of my plugins I use and SVG instead, which worked better:

https://github.com/jenstornell/kirby-bricks-ui/blob/master/bricks/main/style.scss#L14

```text
background-color: #eee;
background-image: url("data:image/svg+xml,%3Csvg width='42' height='44' viewBox='0 0 42 44' xmlns='http://www.w3.org/2000/svg'%3E%3Cg id='Page-1' fill='none' fill-rule='evenodd'%3E%3Cg id='brick-wall' fill='%23b0b0b0' fill-opacity='0.4'%3E%3Cpath d='M0 0h42v44H0V0zm1 1h40v20H1V1zM0 23h20v20H0V23zm22 0h20v20H22V23z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
```

**Comment by paulrobertlloyd** [comment]
Ah, CSS gradients work better in Safari, but not so great in Chrome! So yes, maybe using an SVG is the better approach. (Just remember to remove those unneeded attributes!)

**Comment by bastianallgeier** [comment]
✅
