### ISSUE TITLE
[Panel] Helptext of structure field also showing as helptext of its fields

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1000]
When adding a `help: text` to a structure field, this text also shows up as helptext on every field inside the structure.

Explicitly setting a help on the fields inside the structure overwrites it.

![bildschirmfoto von 2018-09-20 22-34-53](https://user-images.githubusercontent.com/2584674/45878036-fd2f8600-bd9f-11e8-9398-6a278ad59c52.png)

**Comment by bastianallgeier** [comment]
✅
