### ISSUE TITLE
[Panel] Structure field edit 

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1004]
There is a strange border around the updated edit view of structure fields. Looks like a CSS issue.

![bildschirmfoto von 2018-09-21 18-22-32](https://user-images.githubusercontent.com/2584674/45904237-c0d64700-bdec-11e8-9f32-a7b0a436e644.png)

**Comment by bastianallgeier** [comment]
Super weird? Which browser?

**Comment by REHvision** [comment]
Firefox 61.0.1

**Comment by REHvision** [comment]
It is the `outline: 2px solid rgba(0,0,0,.05);` on the `<section class="k-structure-form">` but I don't know why it spans all the way to the left screen edge and I cannot spot the source (rule or element) in the dev-tools causing this behavior.

**Comment by bastianallgeier** [comment]
I had a similar but not quite the same effect in Firefox here. Super strange. I switched to a box shadow which actually looks a bit nicer anyway. I hope this will fix it for you as well.
