### ISSUE TITLE
Escape fields by default in templates

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1006]
As discussed with @bastianallgeier on Slack.

**Comment by bnomei** [comment]
how will you “escape” the fields? which php method? why is it severe?

**Comment by bastianallgeier** [comment]
I also don't get why it's severe :) But we were thinking about escaping any field content in templates by default and you could switch that off if needed. That would be a more secure default for those devs who don't really think about escaping potentially risky content.

**Comment by bnomei** [comment]
so its `strip_tags()` somewhere or just `$field->toString()` equals `$field->html()`?

**Comment by bastianallgeier** [comment]
It would encode all htmlentities. Just like ->html(). The positive side effect would be that you would never have to call the html method again.

**Comment by bastianallgeier** [comment]
I'm closing this. It's a step that would be too drastic. If you want this kind of behavior an engine like Twig is probably the better choice.
