### ISSUE TITLE
[Ui] Multiline notification in dialog causes dialog footer to be misplaced

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1007]
In a dialog with a multi-line notification, the dialog footer is moved out of the dialog box’s borders. This could probably be solved by using flexbox to automatically determine the height of the dialog body instead of setting it explicitly.

<img width="491" alt="bildschirmfoto 2018-09-22 um 14 17 13" src="https://user-images.githubusercontent.com/1512805/45917282-e9555400-be73-11e8-92d6-f38d650d3b2f.png">

**Comment by bastianallgeier** [comment]
✅
