### ISSUE TITLE
semi-colon character in url is invalid html

### ISSUE THREAD

**Issue by desgnl** [getkirby/kirby#101]
when we use tags inside kirby the url is like this : 

    http://mysite.com/the/page/tag:mytag

when an url like this is called from the page it gives an error in the w3c html validator: 
 
    attribute href on element a: Illegal character in path segment: not a URL code point.

Is it possible to use a more classical url structure like this one ?

    http://mysite.com/the/page?tag=mytag1

and maybe we could imagine to make more complexe url like this: 

    http://mysite.com/the/page?tags=mytag1,mytag2&anotherparam=myparamvalue

**Comment by labo-css** [comment]
I have issues with this on windows (xampp), is any "fix" can work now? Or a way to modify the pagination object without breaking it with updates? Thanx.
