### ISSUE TITLE
Site in subdirectory: Two session cookies with/without trailing slash

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1010]
_Originally posted by @johannahoerrmann in https://github.com/k-next/kirby/issues/472#issuecomment-422796060_

---

I was logged out again and encountered a strange error when trying to log back in today: my login wasn't accepted. No errors were displayed in the interface, but there was this in the network responses:

```json
{
	"status":"error",
	"exception":"Exception",
	"message":"Unauthenticated",
	"file":"by\/config\/api\/authentication.php",
	"line":8,
	"code":500
}
```

There was a short flickering in the interface that looked like a system message (with a tiny red warning triangle), but the login form was reloaded instantly.

I later noticed that I had two sessions in the browser for the same site:

<img width="1321" alt="bildschirmfoto 2018-09-19 um 14 52 20" src="https://user-images.githubusercontent.com/149678/45754786-e44a9780-bc1c-11e8-9cfe-af07966d32db.png">

Deleting those two entries allowed me to log in again.
Might this be related?

**Comment by lukasbestle** [comment]
@johannahoerrmann The difference between the two cookies is the `path` setting. One cookie has a trailing slash, one doesn't. That makes the browser consider them as two separate cookies even though the name is identical.

The issue is now that the browser will send any one or maybe even both of those cookies depending on the path you are requesting, which will confuse Kirby. So what we need to ensure is that Kirby will only ever set one cookie.

The question is why there are two cookies in the first place. From the screenshot I assume that the root of your site is at `http://projekte.hananils.de/plant/`. I quickly tested that URL and found out that `http://projekte.hananils.de/plant` (*without* trailing slash) redirects to `http://projekte.hananils.de/plant/` (*with* trailing slash) as it should, so all future requests should be based on that URL *with* trailing slash.

How old is that site (meaning: which was the first beta/nightly build you have run this site on)? Maybe the cookie without trailing slash is from an old Kirby build as we [currently enforce a trailing slash for the cookie path](https://github.com/k-next/kirby/blob/3.0.0-beta-5/src/Session/Session.php#L465).

I will keep this issue open in case it happens again, but to me it looks like something that shouldn't occur again with the current code state.

**Comment by johannahoerrmann** [comment]
@lukasbestle Sorry for being imprecise in my first comment. I did see the differences in the cookies and figured that must be the problem.

> which was the first beta/nightly build you have run this site on

I am not entirely sure to be honest. Alpha 7 or 5 maybe?

**Comment by bastianallgeier** [comment]
@johannahoerrmann if you really still use the alpha, you need to update to the latest beta / nightly build. Otherwise we can't fully validate if it's really still happening.

**Comment by johannahoerrmann** [comment]
@bastianallgeier Wait a minute. @lukasbestle asked what the first build was we used for this site – *that* was alpha 5 or 7. We have since been pretty much constantly updating to the newest Kirby version  available (last updated today). The problem I described above happened shortly after running a Kirby update on September 18.

**Comment by bastianallgeier** [comment]
@johannahoerrmann sorry, I totally misread that one. Ok, then we need to keep on investigating :(

**Comment by johannahoerrmann** [comment]
@bastianallgeier That would have been the easy way out! No wonder you misread it. Thanks for all the hard work! :)

**Comment by bastianallgeier** [comment]
I just started a little poll on Slack. It seems to happen so randomly and only to a very limited group of people - at least from what I hear. Maybe a bit more input from others can help to find out what it is.

**Comment by lukasbestle** [comment]
I think we are mixing together two issues that are unrelated. This one seems to have happened only once after a Kirby update. I'm pretty sure that's because the old version didn't set a trailing slash and the new version does. So the behavior changed and the transition between the two versions caused an issue.

That's why I wrote in my first post above that *this* issue shouldn't occur again, so we should much rather focus on #472, which seems to happen to a lot more users.

**Comment by bastianallgeier** [comment]
@johannahoerrmann is this still happening?

**Comment by johannahoerrmann** [comment]
No, it hasn't happened again.
