### ISSUE TITLE
[Panel] Hide drag handle for pages section if num: zero

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1011]
You can see this in the »Testimonials« page in the Starterkit: The pages cannot be sorted manually, but the drag handle is still visible in the pages section.

Seems to happen only with `num: zero`.

<img width="382" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/45926822-2b8c9d00-bf29-11e8-841f-cca9e89fb449.png">

**Comment by bastianallgeier** [comment]
✅
