### ISSUE TITLE
[Panel] Changing the page status results in error when blueprint contains info section

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1012]
According to the documentation, the `info` field can also be a standalone section:
https://nnnnext.getkirby.com/docs/guide/blueprints/sections#section-types

When I add an info section to the project.yml in the Starterkit like this:
```
sidebar:
  info:
    headline: How to do something
    type: info
    theme: info
    text: This is an info section, here's some stuff to keep in mind.

  cover:
    ...
```

And then change the status of the page, I get this error:
<img width="1055" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/45927318-db660880-bf31-11e8-9284-8d0b2e1102e2.png">

**Comment by bastianallgeier** [comment]
✅
