### ISSUE TITLE
[Panel] Changing status from draft to public results in two folders with same sorting number

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1013]
I used the latest Plainkit and Kirby nightly build:

Steps to reproduce in the Plainkit:
1. Add a page called »Page 1«, set the status to public and the position to 1.
2. Add a page called »Page 2«, set the status to public and the position again to 1.

The content folder should now look like this, with two pages having the same sorting number:

<img width="712" alt="screenshot-1" src="https://user-images.githubusercontent.com/15672385/45928935-669fc800-bf4b-11e8-9a38-02f7fa532cbb.png">

If you add more pages the same way, it seems that this only affects the last sorting number.
If you change the position of a page that is already public, the sorting numbers are corrected.

<img width="772" alt="screenshot-2" src="https://user-images.githubusercontent.com/15672385/45928957-a5ce1900-bf4b-11e8-81d9-24118dfc3ee8.png">

**Comment by bastianallgeier** [comment]
Hm, I can't really reproduce this. No matter how I sort them, the folders end up correct. Which version / browser do you use?

**Comment by SebastianEberlein** [comment]
I used the plainkit from the Beta 5 and the kirby nightly build from 21.09.2018.

I can reproduce this in Chrome, Safari and Firefox on my local vagrant server and our webserver, both PHP 7.2

Here’s a (large) gif:

![pages](https://user-images.githubusercontent.com/15672385/45959641-ab466480-c01a-11e8-9844-fc8509931154.gif)

**Comment by bastianallgeier** [comment]
Huh, I just double-checked on the first level and it seems that it only happens there.

**Comment by bastianallgeier** [comment]
✅ Stupid bug! Sorry for that. I'm uploading a new nightly build in a minute.
