### ISSUE TITLE
[Panel] New structure editor

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1017]
The new table layout of the structure field is great but switching from the overview to the editor view makes you think you just dismissed all exiting entries.

Starting here:

![bildschirmfoto am 2018-09-24 um 09 21 07](https://user-images.githubusercontent.com/25466/45940814-664f0d80-bfdb-11e8-916c-60c0ca33be91.png)

Continuing with an "Oh, wait, shit!" moment:

![bildschirmfoto am 2018-09-24 um 09 21 13](https://user-images.githubusercontent.com/25466/45940828-7b2ba100-bfdb-11e8-998b-f696641241fe.png)

Personally, I really like the inline editor the structure field offered before but I understand it might feel convoluted when using extra field hidden in the overview. Still the current layout is problematic.

**Comment by bastianallgeier** [comment]
My favorite would still be a huge/almost full-screen modal to be honest. I know 90% of all Kirby users (totally made up stat) hate modals but I think it would work better than either solution. The inline thing has its advantages but to me it never felt really that much clearer and in a long table it's just annoying in my opinion.

**Comment by nilshoerrmann** [comment]
Count me in for the 90 % of users hating modals, but this makes more sense to me than the current solution :) The problem with a modal in this case is that you don't know where you add the new entry and may loose visual context when saving. That's where inline editing shines: summary and edit form are always in the right place.

I've been working on the UI of [Symphony CMS](https://github.com/symphonycms/symphony-2) as a core designer for a few years. We had a component called Duplicator that you could expand and collapse row-based. I always liked this concept and maybe that's just why I'm used to it:

![bildschirmfoto am 2018-09-24 um 10 49 52](https://user-images.githubusercontent.com/25466/45943750-de233500-bfe7-11e8-9a8d-f8cccb127ca6.png)

**Comment by nilshoerrmann** [comment]
One advantage is that you can open multiple items simultaneously, too.

**Comment by bastianallgeier** [comment]
I still think this can get pretty massive and convoluted. Especially if you have a bigger form with more and especially more complex fields. 

I was just thinking that it might be cool to switch to a mail app style interface, when editing entries. The first column would be used as the title in the sidebar and you could easily navigate through entries that way and never loose track. 

Here's a quick mockup. 

![structure](https://user-images.githubusercontent.com/24532/45945299-5b04dd80-bfed-11e8-84d9-0e2257f42d5c.png)

**Comment by nilshoerrmann** [comment]
I like it! It's a good compromise.

The funny thing is that I was looking for a screenshot right now of an alternative version of the aforementioned Duplicator that never made it into a public release that looks exactly like this. That interface allowed the selection of multiple items in the list by holding down the `cmd` key which resulted in multiple form underneath each other in the right column.

**Comment by agloeckner** [comment]
Love the Mail app style view 👍🏻

**Comment by christianschley** [comment]
Dito! This view looks great

**Comment by sylvainjule** [comment]
I also like this solution!

But how would it behave with really long structure fields, if I click on structure entry 35 to edit it ? The right pane would stick on top and always be in view ?

**Comment by bastianallgeier** [comment]
@sylvainjule good point. I would need to test that. My first suggestion would probably be to use pagination in that case to keep the list short.

**Comment by sylvainjule** [comment]
Sounds good. I'm a bit afraid that content / scroll jumping might be confusing when opening or closing the edit view (as both scroll position + displayed architecture would change), but I may be overthinking this.

**Comment by bastianallgeier** [comment]
@sylvainjule I will definitely give it a try and see how it feels.

**Comment by sylvainjule** [comment]
Have to add I might be a bit biased as modals allowed me to implement solutions for clients (like [those pins](https://github.com/sylvainjule/kirby-image-annotator) or [content sync](https://github.com/sylvainjule/kirby-subtitler)) relying on structure fields without having to go back and forth between visual representations and stored inputs everytime a new structure entry gets triggered. 

So I'm pretty conservative in that way (and within the few not-hating-modals kirby users), but it might just be my usage of the structure field.

**Comment by louiswalch** [comment]
I like the idea of a larger modal window. The way it is now feels a little odd - taking over the entire area, also a modal window allows for much larger support in custom layouts.

And also to interject, it might be nice to place the "Ok" button in a more traditional place. Many of my clients are novice and non-technical. Usability concerns me a little when moving away from norms.

**Comment by nilshoerrmann** [comment]
Yesterday, I've been editing a few hundred structure entries and the current interface is really unhelpful in cases where you need to compare or contextualise values because all other entries are hidden. I really prefered the inline editor that was previously available.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#110](https://github.com/k-next/ideas/issues/110).
