### ISSUE TITLE
[Panel] Navigating to parent page: First tab of current page is activated before parent page is loaded

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1020]
I added two tabs to the `project.yml` blueprint from the starterkit. When the second tab is active and I go back to the parent page, the first tab of the current page is activated before the parent page is loaded.

This only happens for page-depth > 1.

Here's a gif. I simulated a slow 3G connection so that Giphy could capture the bug:

![back](https://user-images.githubusercontent.com/15672385/45955676-d4fa8e00-c010-11e8-9453-55be1ce4f72c.gif)

**Comment by bastianallgeier** [comment]
✅
