### ISSUE TITLE
Better handling of unwritable folders

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1021]
If permissions for the assets and media folder are not set correctly (no write permission), when trying to access the panel for example it will flip in a loop between panel/login and panel/installation. Perhaps it would be  better to check for r/w permissions and error instead of getting stuck in a loop.

**Comment by bastianallgeier** [comment]
Going to fix that asap

**Comment by bastianallgeier** [comment]
✅ Will be in today's nightly build.
