### ISSUE TITLE
[Panel] Erratic scroll behavior when structure editor is open

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1023]
**On Chrome (69) and Safari (11.1.2):**

On click on a structure entry close to the top of the viewport, the editor opens with its action buttons out of view (it should probably scroll to the top of the editor?).

<img width="1279" alt="capture d ecran 2018-09-25 a 11 46 01" src="https://user-images.githubusercontent.com/14079751/46006850-c8ca0b80-c0b8-11e8-901a-3f4ea518d95e.png">

The main issue when this happens, is that scroll / mousewheel events seem to be disabled outside of the editor. So if I try to scroll up while hovering the editor, it's all good, but anywhere else I can't get it to scroll up. And if I feel stuck and try to use the scrollbar, it closes the editor.

Here is a video of the behaviour (when my cursor's not moving while the editor is open, it's me trying to scroll up): https://cl.ly/625412c247ae

**On Firefox 62.0.2:**
Scroll works.

**Comment by bastianallgeier** [comment]
✅
