### ISSUE TITLE
Add a helper method to Kirby\Cms to determine if a specific collection is available

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1026]
In Kirby\Cms there are `HasXXX` methods for Children, Methods, etc, but there is not one for a Collection (i.e. `HasCollection`). Can you consider adding one.

**Comment by bastianallgeier** [comment]
Could you describe a use case. I'm not entirely sure yet what you mean. Sorry!

**Comment by bnomei** [comment]
@omz13 it depends on what `kirby()->collection('doesnotexist')` returns now and if it can be differentiated well enough from an empty collection, right?

**Comment by omz13** [comment]
> @omz13 it depends on what `kirby()->collection('doesnotexist')` returns now and if it can be differentiated well enough from an empty collection, right?

@bnomei Currently it throws `Kirby\Exception\NotFoundException` which is not as easy to work with as simply returning e.g. `null`.

**Comment by bastianallgeier** [comment]
Ah, ok. That would be an easy fix and makes a lot of sense.

**Comment by omz13** [comment]
> Could you describe a use case. I'm not entirely sure yet what you mean. Sorry!

@bastianallgeier Use case:

I'm developing a plugin to serve syndication feeds, and routing `/feeds/<category>/rss` to `collection('<category>')`... because `kirby()->collection( $category )` throws `Kirby\Exception\NotFoundException` if the category is not found, my code is rather ugly (and in one place I end up retrieving a large collection just to check if it exists)... so I would rather do a guard to check if `HasCategory($category)` before calling `kirby()->collection( $category )` later.

**Comment by bastianallgeier** [comment]
✅ 

The collection method will now return null if a collection does not exist and you have a new method to check for existing methods without actually loading them: 

```php
$kirby->collections()->has('myCollection');
```
