### ISSUE TITLE
[Panel] Discard new empty structure items

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1028]
I'm sure this was reported already, but I cannot find it anywhere:

If I create a new structure item and discard it without ever adding any content I have to confirm this action in a modal:

> Do you want to discard the new item? 

This is really annoying: of course, I'd like to discard the item because it never had any content. 
So I'd expect Kirby to dismiss these kind of items directly.

In general, I'd prefer Kirby not to ask whether to perform an action or not but to just perform the action and offer an undo option later. Following this concept, the interface wouldn't interrupt desired actions but still offer a way to prevent data loss in case of a mistake.

**Comment by bastianallgeier** [comment]
✅ The discard window is gone. If the form is empty, the row will just be deleted.
