### ISSUE TITLE
[Panel] Structure field pagination

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1029]
The latest structure field shows a pagination without actually paginating items: 
In my case it states `1–10 / 15` while displaying all 15 items.

![bildschirmfoto am 2018-09-27 um 12 35 46](https://user-images.githubusercontent.com/25466/46140611-e1215e00-c251-11e8-96a8-bafc3d2d44bc.png)

**Comment by bastianallgeier** [comment]
✅
