### ISSUE TITLE
Default Controller?

### ISSUE THREAD

**Issue by jakobploens** [getkirby/kirby#103]
This would be another great addition to kirby: the ability to have a default controller which would be taken if no "template"-controller is available. As an example I'll take the templates from the getkirby.com. If I just need for example to start a session and take a value on every single page, I'd do it with a controller. But it would not make much sense to create 27 single controllers with the same code. Would be great if it would be the same behavior as with blueprints and templates (you can have more blueprints than templates), if the template-controller is available take it, if not take the default one.

**Comment by jemware** [comment]
+1

**Comment by distantnative** [comment]
Started an implementation. My current concern: How do we name the default controller file? I started with `site/controllers/default.php` – but what if we actually want a controller for the default template that should not be applied for any other template?

**Comment by texnixe** [comment]
Why not call it `site.php`, I don't think that would interfere with anything?

**Comment by distantnative** [comment]
Ha, brilliant! :laughing: :+1:

**Comment by lukasbestle** [comment]
Or what about something like `_base.php`? I think `site.php` could be a bit confusing because there is no site template but a `site.txt`.

**Comment by texnixe** [comment]
Or `standard.php`.

**Comment by distantnative** [comment]
I like `site.php` since it actually mirrors the `site.txt` which exactly is not linked to any single template, but rather a global thing. And the default controller would kind of be that.

**Comment by lukasbestle** [comment]
That's true, I fully agree.

**Comment by distantnative** [comment]
> I thought it could be potentially confusing as well, on the other hand we talk about site images, and site settings, so somehow it can mean site-wide stuff.

Yea. And then, I guess the default controller will be something that people won't start with. It's something people discover once they get a little more familiar with Kirby. When they search the docs. And it's the closest we got from the existing Kirby name conventions. `standard.php` or `_base.php` would be probably as confusing since they introduce completely new names to the Kirby universe (so to say).

**Comment by texnixe** [comment]
Yes, I agree, people would not normally create a controller for the default template. I'd say, while it has to be there, nobody would ever use it in a project other than maybe for redirecting pages in a one-pager setup.

I still have a certain preference for `site.php`, though
