### ISSUE TITLE
[Panel] Disabled-status indicator.

### ISSUE THREAD

**Issue by louiswalch** [getkirby/kirby#1030]
I understand that the icon was chosen to indicate that you are not able to toggle the page status - but every time I look at the "No Allowed" symbol used here it makes me think that something is wrong with the page. This icon inherently has negative or "you shouldn't be doing that" connotations.

I feel it would be wise to swap this out for something else. Perhaps just a circle with border.

Thanks.

![site___kirby_kitchensink](https://user-images.githubusercontent.com/286013/46157152-1c6b5f00-c249-11e8-89f6-27f1a77cd012.png)

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#109](https://github.com/k-next/ideas/issues/109).
