### ISSUE TITLE
[Darkroom] Don't create thumb if the original file is smaller

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1033]
If the original image file happens to be well-optimized, the thumb can sometimes be larger in size if it's not also optimized. We should detect this and copy over the original file to the `media` directory instead of the thumb. Important: That must only happen if the image is neither cropped nor blurred nor grayscaled.

*See PR 655 in the getkirby/kirby repo (not linked to avoid leaking the v3 repo).*

**Comment by bastianallgeier** [comment]
✅
