### ISSUE TITLE
[Panel] Date field does not support years prior to 2008

### ISSUE THREAD

**Issue by louiswalch** [getkirby/kirby#1035]
Currently the year in a date field is assigned via a dropdown, however this doesn't include years prior to 2008. It would be nice if this were a standard field for greater flexibility.

I came across this while experimenting with migrating one of my clients to the new Kirby. They however have a large archive of searchable exhibitions dating much older then 2008.

**Comment by distantnative** [comment]
That should already work, setting the `min` and/or `max` option accordingly (to a date).

**Comment by bastianallgeier** [comment]
The default is an interval of 10 years into the future and 10 years into the past.

**Comment by louiswalch** [comment]
Thanks guys. Do you need any assistance filling out the docs? Happy to help.
