### ISSUE TITLE
[Panel] Display modal differently when there's not enough space at the bottom

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#1036]
Definitely a suggestion and not a bug.
Right now the small dropdown for the images is always displayed below the thumbnail no matter what.
As a result the modal can either go below the status bar as shown in the screen attached or make the entire screen jump up and down because the screen height increases/decreases based on the visibility of the dropdown.

A simple solution could be to add extra padding at the bottom to accomodate the height of the modal/dropdown.

![screen shot 2018-09-29 at 10 27 01 am](https://user-images.githubusercontent.com/1738077/46243245-629ffa00-c3d2-11e8-8fa5-c0304012c3b2.png)

**Comment by bastianallgeier** [comment]
✅
