### ISSUE TITLE
[Panel] Idea: Allow for editing file fields through a simpler modal view.

### ISSUE THREAD

**Issue by louiswalch** [getkirby/kirby#1039]
Mock up included below. The full page edit screen for files sometimes offers more then someone needs. For files that have only a few fields, it would be nice to edit in a modal view. This allows the user to feel they are still in the process of editing the page and not taken away from it. Can be a bit strange to have to navigate back to the page you were editing through header breadcrumb.

![image_modal](https://user-images.githubusercontent.com/286013/46248217-a7349100-c3e4-11e8-9ea2-963ef461eff4.png)

**Comment by eighthday** [comment]
@louiswalch agreed, can be pretty confusing ending up on the file info page.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#108](https://github.com/k-next/ideas/issues/108).
