### ISSUE TITLE
Is (:alpha) a correct pattern name?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#1040]
https://github.com/jenstornell/kirby-secrets/blob/master/docs/routing.md

I saw this:

```text
'(:alpha)' => '([a-zA-Z]+)',
```

It matches all letters but no numbers. Then I read this: 
https://english.stackexchange.com/questions/108311/is-there-a-word-for-numbers-and-letters-but-not-punctuation-etc

>An alphanumeric character is one which is either alphabetic or numeric — that is, either a letter or a digit.

So maybe that name is more fitting for something that matches both letters and numbers?

Then I found another router that also uses `alpha`:

https://github.com/anandkunal/ToroPHP/blob/master/src/Toro.php#L31

>':alpha'  => '([a-zA-Z0-9-_]+)'

It matches both letters and numbers. The pattern for only letters is called `:string` in that case.

**Comment by lukasbestle** [comment]
> Is (:alpha) a correct pattern name?

Yes, `:alpha` means `alphabetic`.

I don't really like `:string` because a string in the "variable type" sense can contain any kind of characters. But maybe we should introduce a character class `:alphanum`.

**Comment by jenstornell** [comment]
I see. That pattern is also used here in another context:

https://github.com/JBZoo/Utils

>// Return only alpha chars
>Filter::alpha($value)
>
>// Return only alpha and digits chars
>Filter::alphanum($value)

**Comment by bastianallgeier** [comment]
✅ I just added the :alphanum pattern
