### ISSUE TITLE
[Panel] Add page field filtering and card layout 

### ISSUE THREAD

**Issue by eighthday** [getkirby/kirby#1043]
The new page field would benefit greatly from:

- being able to filter the navigation list by template or parent page. 
- A card layout 
- changing the add new text
- same drag drop style as elsewhere

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#50](https://github.com/k-next/ideas/issues/50).
