### ISSUE TITLE
Bug in Panel-Login (beta6)

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1045]
When i try to log in my credentials are rejected. Clicking on "Login" once more with the same username/password works afterwards.

I testet that several times.

**Comment by SebastianEberlein** [comment]
Happens for me, too.

But if you log out and then log in once again, it works as expected.

**Comment by sylvainjule** [comment]
Happens to me too.

On first try, the form shakes and rejects the request, but I am logged in. If I refresh the page, I end up on the panel homepage.

Here's the associated error :

<img width="936" alt="capture d ecran 2018-10-05 a 00 10 49" src="https://user-images.githubusercontent.com/14079751/46506114-8ed4d400-c833-11e8-8082-7b2aad2ff61a.png">

**Comment by bastianallgeier** [comment]
I couldn't reproduce this, but I think I fixed it. Can you try again after tonight's nightly build? Feel free to reopen, if it still fails.

**Comment by SebastianEberlein** [comment]
Still happens for me with the latest nightly build when I start a new session in a new browser tab.

Error message:

<img width="1330" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/46619412-52022900-cb22-11e8-9d68-04a1f551cae1.png">

**Comment by christianschley** [comment]
Yep, still there for me as well.

Tested in Google Chrome and Safari

**Comment by nilshoerrmann** [comment]
Same in Firefox.

**Comment by bastianallgeier** [comment]
I just realized that this bug is only happening with the dist version and not with my local one. I think I really fixed it this time :)
