### ISSUE TITLE
Structure sometimes not displayed correctly

### ISSUE THREAD

**Issue by pju-** [getkirby/kirby#1046]
I'm not quite sure yet what triggers it, but structure sections sometimes get messed up (it might only happen once there were changes in the blueprint, but I can't reliable reproduce the issue):

<img width="1386" alt="bildschirmfoto 2018-10-04 um 17 16 30" src="https://user-images.githubusercontent.com/5202770/46484355-e9e9d500-c7f9-11e8-84e7-97cee4e64b84.png">

The save bar also shows up, even if there were no changes.
After a save the content is back to normal.

The problem seems to be that the vue components is passed the content as a string instead of a formatted array:
<img width="698" alt="bildschirmfoto 2018-10-04 um 17 17 07" src="https://user-images.githubusercontent.com/5202770/46484457-1f8ebe00-c7fa-11e8-8272-aff8a7f804a7.png">

**Comment by REHvision** [comment]
This happened to me a few times, too when I was developing/changing a blueprint setup and reloaded the panel to check for the results... I then clicked either "Save" or "Revert" and the contents became normal again

**Comment by bastianallgeier** [comment]
✅
