### ISSUE TITLE
setlocale(): Customizable category

### ISSUE THREAD

**Issue by jakobploens** [getkirby/kirby#105]
Today it took me quite some time to find a mistake which is not really Kirby's problem but comes directly with PHP, but maybe you rewrite the localize() function in the Kirby-class. If locale is set to 'de' (due to language configurations), floats are using commas as decimal separator, and the number_format won't work anymore. Especially if you work on a multilang site and you have to use numbers (I'm building a shop), this is really annoying and not handy. I've manually edited the function that numbers always use english localization, but maybe you could add an advance function that an update won't break the site in future… might not be that important, and my solution works for the moment, but just to let you know!

**Comment by bastianallgeier** [comment]
This is now available in 2.1
