### ISSUE TITLE
[Cms] Leading zeros in sorting numbers don't work

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1050]
If a page has leading zeros in its sorting number (e.g. `01-projects`), the content of that page is not read correctly.

As such a sorting number scheme is pretty common for v2 sites that don't use the Panel, we should either support this scheme in Kirby 3 as well or migrate the sorting numbers in the `System::upgradeContent()` method by removing the leading zero.

**Comment by bastianallgeier** [comment]
✅
