### ISSUE TITLE
[Cms] Respect content type headers set from templates/snippets

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1051]
This issue is a spin-off from #399, which seems to be too complex for 3.0 and will therefore come later. In this issue I want to boil it down to the part that is essential for 3.0.

---

If a template manually sets the content type header using the `header()` function, the content type is later [overridden by the content type of the content representation](https://github.com/k-next/kirby/blob/3.0.0-beta-6/src/Cms/Page.php#L1072), which is often `text/html`. This means that Kirby 3 won't allow any other content types in templates that are not of a content representation.

I noticed this issue when I used the [Kirby 3 Feed plugin](https://github.com/bnomei/kirby3-feed) by @bnomei. It sets the content type in the [template](https://github.com/bnomei/kirby3-feed/blob/v1.0.2/snippets/feed/rss.php#L5) and then again when [building the response](https://github.com/bnomei/kirby3-feed/blob/v1.0.2/config.php#L21). But still the content type that is returned to the browser is `text/html`, which won't work.

Here's a hackish solution that could be inside `Page::render()` and would work automagically, although not reliably and would still have the caching issues of #978:

```php
// grab the content type header if it has been manually set
// in the template or a snippet
$headers = headers_list();
foreach ($headers as $header) {
    if (preg_match('/^Content-Type: ?([^ ;]+)/i', $header, $matches) === 1) {
        $contentType = $matches[1];
    }
}
```

---

I think we should first fix #978 and then build something like the above on top of that improved rendering implementation. Then we should be pretty good to go for 3.0.

**Comment by bastianallgeier** [comment]
✅
