### ISSUE TITLE
Thumbnail creation flips aspect ratio on images with auto orientation

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1056]
creating thumbnails with auto orientation rotates the image correctly, but resizes the image without rotating the aspect ratio.

Example: the image here

![20180914_164236](https://user-images.githubusercontent.com/6684137/46586949-b6bb7600-ca85-11e8-97a0-ad73b7ac36db.jpg)

is resized like this:

![20180914-164236-100x75-q90](https://user-images.githubusercontent.com/6684137/46586950-b8853980-ca85-11e8-805b-ca7d80cba681.jpg)

**Comment by bastianallgeier** [comment]
I looked at this ticket a couple times and to be honest I always think that the behavior is correct like that. What would you expect as the result? Maybe I'm a bit slow here.

**Comment by sylvainjule** [comment]
I wouldn't agree about this being correct. 

If I have a 600x400px image that should be vertical, and create a `200px` thumb with auto-orientation. The current behaviour seems to be:

- Get the original file ratio (`3/2`)
- Auto-rotate the image
- Resize with the `3/2` ratio
- I end-up with a `200*133px` thumb, shrinked.

But should be: 

- Auto-rotate the image
- Get the auto-rotated file ratio (which is now `2/3`)
- Resize with the `2/3` ratio
- I end up with a `200*300px` thumb, with good proportions.

**Comment by rasteiner** [comment]
2 results would be acceptable for me:

from the source image above, resizing it to "100px width" I would expect either this:
![image](https://user-images.githubusercontent.com/6684137/49528677-b6d4c800-f8b4-11e8-987b-63c53b7a4ec9.png) (better)

or this:
![image](https://user-images.githubusercontent.com/6684137/49528935-44181c80-f8b5-11e8-9a5f-c5bfeb417d83.png) (also acceptable). 

What is imho incorrect is stretching the image (current behavior):
![image](https://user-images.githubusercontent.com/6684137/49528892-2f3b8900-f8b5-11e8-967d-f5da8bd50c02.png)

@sylvainjule 
IMHO you should end up with an image that is 200x300px - since you requested a 200px width thumb.

**Comment by sylvainjule** [comment]
@rasteiner yep sorry, wrote it too quickly but that was my thought ;)

**Comment by bastianallgeier** [comment]
Ahhh, I didn't see that the image is stretched. It's funny because after seeing the stretched one a couple times, your "better" example looks stretched in the opposite direction for me :) I will check that again.

**Comment by bastianallgeier** [comment]
Ha, I finally found what caused it. SimpleImage wants to resize first before auto-orienting the image. A bit weird, but ok. Now it works.
