### ISSUE TITLE
[Panel] this.$v is null

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1059]
On some page we get the following error message:

![bildschirmfoto am 2018-10-08 um 18 36 58](https://user-images.githubusercontent.com/25466/46622020-731a4800-cb29-11e8-91af-66e27782de97.png)

The console logs:

- `TypeError: "this.value.split is not a function"`
- `TypeError: "t.selected is undefined"`
- `TypeError: "this.$v is null"`

We've got a tag field with two items on the erroneous pages – perhaps that's related?

**Comment by bastianallgeier** [comment]
I think I fixed it. Let me know after tomorrow's nightly build.
