### ISSUE TITLE
[Panel] Routing issues

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1060]
We accidentially tried to acces a panel page by adding `panel/pages/` to a project page URL and it actually worked: `http://localhost:8888/branchplant.k3/panel/pages/projects/babypoint`

The correct panel URL would be `http://localhost:8888/branchplant.k3/panel/pages/projects+babypoint` though (notice the slash versus the plus).

Nothing looks suspicious until you submit any changes with the wrong slash-based URL. It results in the following error message:

<img width="596" alt="bildschirmfoto 2018-10-02 um 23 37 53" src="https://user-images.githubusercontent.com/149678/46378741-e4c34380-c69c-11e8-8e3c-ed23e56f95d8.png">

### Expected behaviour

The slash-based URL should throw an error page.

**Comment by bastianallgeier** [comment]
✅
