### ISSUE TITLE
$image->watermark() method

### ISSUE THREAD

**Issue by carstengrimm** [getkirby/kirby#1063]
Reaching out to suggest the feature to be able to use a 

```$image->watermark()``` method.

Since claviska\SimpleImage is already included to kirby, which features a few methods to manipulate images and adding a watermark, i'd really love to see kirby featuring a method to watermark images out of the box which then is working with all objects such as thumbs and images, as well as to chain methods together - such as:

```
// Pseudo
$image->resize(1500)->watermark($page->parent()->image('watermark.png'))->url() 
```

In the past there has been a few users who already had the use for watermarking images in v2:

https://forum.getkirby.com/t/new-kirby-watermark-plugin/3695
https://forum.getkirby.com/t/extend-image-with-image-overlay-or-image-watermark/7985
https://forum.getkirby.com/t/adding-a-watermark-on-pages-images/3459

So i guess that would be a nice addition to all those other methods (bw, resize, crop, blur etc.pp)

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#51](https://github.com/k-next/ideas/issues/51).
