### ISSUE TITLE
[Panel] 5 colums

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1064]
https://nnnnext.getkirby.com/docs/guide/ui-kit/layout/column

any reason not to have `1/5`, `2/5`, `3/5`, `4/5`?

**Comment by iskrisis** [comment]
Fifths are impossible to do in 12 col css grid.

But i maybe good idea would be either adding ```1/12```, ```2/12```, ```3/12```...
Or for 12 grid just translate the number to the css grid directly
```
width: 3
.k-column[data-width="3"] {
grid-column-start: span 3;
}
```

```
width: 6
.k-column[data-width="6"] {
grid-column-start: span 6;
}
```

Etc.

This way you have universal flexible way for power users + for anyone who makes fields and one something even as small as 1 col and wants to just use kirby native clases.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#52](https://github.com/k-next/ideas/issues/52).
