### ISSUE TITLE
Published pages cannot be made unlisted

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1065]
In the Starterkit, when trying to change the status of a published article to unlisted (in review), I get a message that the status has been changed but the status remains the same.

Also, a listed page cannot be published.

And while a listed or published article can be moved into drafts, it keeps the visibility flag (in case of a formerly published page), don't know if this is intended behaviour or not.

Tested with the fresh 6.2 nightly.

**Comment by bastianallgeier** [comment]
I know what it is. Will be fixed tomorrow.

**Comment by bastianallgeier** [comment]
✅
