### ISSUE TITLE
Call to undefined function Kirby\Image\exif_read_data()

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#1067]
This happened to me in my docker arch linux container where `php7-exif` module wasn't installed, so it's not really a kirby thing. I would definitely add it to the docs https://nnnnext.getkirby.com/docs/guide/installation-and-updates/requirements 

```
Error: Call to undefined function Kirby\Image\exif_read_data() in file /var/www/localhost/htdocs/vendor/getkirby/cms/src/Image/Exif.php on line 211
```

**Comment by bastianallgeier** [comment]
We should probably throw a good exception, if you're trying to read the exif data and the extension is missing.

**Comment by bastianallgeier** [comment]
✅
