### ISSUE TITLE
Panel: Search problem

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1068]
I have this strange issue with the search function:

What happens: I enter the title of the page `Head in the clouds`, but the page isn't listed in the search results. It *is* listed when I search for `head`, `clouds`, `head clouds` or other related information, though.

![screenshot_2018-10-10 roxborough garden two plant architect inc](https://user-images.githubusercontent.com/149678/46732456-d58c5900-cc8d-11e8-97a9-464f15e6abb6.png)

![screenshot_2018-10-10 roxborough garden two plant architect inc 2](https://user-images.githubusercontent.com/149678/46732462-d91fe000-cc8d-11e8-95e9-6d8989419409.png)

![screenshot_2018-10-10 projects plant architect inc](https://user-images.githubusercontent.com/149678/46732695-809d1280-cc8e-11e8-8dc6-2f7c284fc553.png)

![screenshot_2018-10-10 roxborough garden two plant architect inc 1](https://user-images.githubusercontent.com/149678/46732461-d7561c80-cc8d-11e8-9027-4084fea92d72.png)

**Comment by bastianallgeier** [comment]
✅ I improved the search algo and also made the search result limit configurable. 

In site/config/config.php set

```php
return [
    'panel' => [
        'search' => [
            'limit' => 20
        ]
    ]
];
```

**Comment by johannahoerrmann** [comment]
Now this is awesome. Thanks!
