### ISSUE TITLE
[Panel + i18n] Panel only shows translated after browser reload

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1069]
Since each panel user can select his/her preferred language (also in single language setups), it is expected that the Panel then always shows up in this language.

But the language is being ignored and the panel always shows up in English after login, although a user has selected e.g. German as his language.

The correct language only shows up after reloading the panel page or by changing the language in the users account explicitly again.

The panel stays in the correct language until next login.

**Comment by bastianallgeier** [comment]
✅
