### ISSUE TITLE
Panel: user id/email not displayed

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#107]
Now with user role blueprints, it is not guaranteed anymore that on the UserView the id/email is displayed anywhere (not ideal).

Maybe handle similar to page slug: https://github.com/k-next/starterkit/issues/8

**Comment by bastianallgeier** [comment]
The idea to use the slug for page breadcrumbs and the role + email for user breadcrumbs is pretty cool!

**Comment by bastianallgeier** [comment]
So it would be 

`projects / project-a`

and 

`role: admin / nico@getkirby.com`

**Comment by bastianallgeier** [comment]
This is now solved with the latest commit
