### ISSUE TITLE
Allow storing of serialized PHP objects in the session

### ISSUE THREAD

**Issue by mzur** [getkirby/kirby#1070]
Users of Uniform [have found](https://github.com/mzur/kirby-uniform/issues/162), that storing of PHP objects is no longer possible with the new session implementation. As the new implementation stores the session as JSON, it is only possible to store arrays, strings and numbers.

I propose to use `serialize` and `unserialize` instead of JSON for the session. Frameworks like Laravel, which use their own session implementation, [do this, too](https://github.com/laravel/framework/blob/196c51841a53b6175ff5e1f8288a797c3743e8f9/src/Illuminate/Session/Store.php#L129). This way there would not be such restrictions on what can be stored in the session.

**Comment by lukasbestle** [comment]
Great idea! From the top of my head I'd say it should be doable. I will take a look at it soon.

In the issue you wrote that:

> I'm not very happy with their new session implementation to be honest.

Why is that? Anything we can improve? :)
Testing should work, after all the whole session codebase is unit-tested with nearly 100 % code coverage. If I remember correctly, we had a discussion about this a while ago, but I can't remember where.

**Comment by mzur** [comment]
Yeah, apart from the serialization issue, the testability is my main concern. In our discussion, we concluded that we didn't really know why the tests work for the Kirby codebase and didn't for my case. I spent quite some time on this issue but couldn't make it work. Eventually I gave up and developed [kirby-defuse-session](https://github.com/mzur/kirby-defuse-session) as workaround.

I wanted to develop an array session store that could replace the file store in tests. But IIRC the problem remained, that the session wanted to set a cookie, which did not play well with the tests. I know, I'm always blabbering about Laravel, but I really like how sessions are implemented there (with easily replacable storage adapters).

**Comment by lukasbestle** [comment]
Ah, right. Now I remember where that discussion was. For reference: https://github.com/mzur/kirby-defuse-session/issues/1

The Laravel implementation was actually a huge inspiration for ours. We also have easily replaceable storage adapters, but that feature isn't exposed to the CMS yet to keep it manageable for now. The feature will become a first-class citizen later.

**Comment by lukasbestle** [comment]
✅
