### ISSUE TITLE
Panel: Fallback if no blueprint exists is not working anymore

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1071]
If you have a page in the panel with no related blueprint the fallback to default.yml is not working anymore.

This error occurs:

![bildschirmfoto 2018-10-11 um 07 39 42](https://user-images.githubusercontent.com/25037153/46783049-02da1500-cd29-11e8-97fc-2b075aa470e7.png)

**Comment by bastianallgeier** [comment]
Already fixed this on my local version. Will be in the nightly build today. I didn't manage to release one yesterday.

**Comment by bastianallgeier** [comment]
✅
