### ISSUE TITLE
[CMS] pages field is missing parent props definition

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1073]
using `parent:` in blueprint does not work.

example: files has it.
https://github.com/k-next/kirby/blob/master/config/fields/files.php#L20

pages does not:
https://github.com/k-next/kirby/blob/master/config/fields/pages.php#L4

**Comment by bastianallgeier** [comment]
I'm closing this in favor of the more complete ticket for page field enhancements: https://github.com/k-next/kirby/issues/1074

**Comment by bnomei** [comment]
reopening because prop with fallback to site object exists in vue. the field config on php side is just missing a few lines of code. this could be done quickly. 

having filter capabilities seems to be another issue imho.

**Comment by bastianallgeier** [comment]
✅
