### ISSUE TITLE
[Panel] Pages field selection

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1074]
Currently, the pages field seems to always display the full site index of pages. This is not very useful in many situations where you'd like the users to reference a certain page type. I'd expect the field to offer two things:

1. A `parent` option that defines the entry point for the displayed pages, like `parent: site.find('projects')`.
2. A `query` option that allows me to define a list of pages to be displayed in the modal, e. g. `query: site.page('projects').children.filterBy('category', 'architecture')` or any kind of collection.

**Comment by nilshoerrmann** [comment]
See also #1073.

**Comment by bnomei** [comment]
currently a query is only possible by overriding the `children` collection with a model.

**Comment by bnomei** [comment]
also would be nice to use custom collections as parent, not just real page objects.

**Comment by bastianallgeier** [comment]
That is definitely on my list, but I can't promise this for 3.0

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#53](https://github.com/k-next/ideas/issues/53).
