### ISSUE TITLE
[Panel] Pages field missing drag handles

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1076]
The pages field doesn't show drag handles on hover. It's not obvious to the user that the list is sortable at all.

**Comment by christianschley** [comment]
The same "problem" exists in the files-field as well

**Comment by bastianallgeier** [comment]
Yep, they should be the same as everywhere else.

**Comment by bastianallgeier** [comment]
✅ I fixed it in all fields (users, files, pages)
