### ISSUE TITLE
[Panel] Create new sibling

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1077]
Say I'm viewing a page in the panel and like to create a new sibling entry, I have to go back to the parent page in the breadcrumb navigation and create a new page from there. It would be nice to have an option to:

- create a new sibling from any page,
- create a new sibling duplicating the content of the current page.

Of course this should only be possible, if the parent page allows the creation of children.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#54](https://github.com/k-next/ideas/issues/54).
