### ISSUE TITLE
[Panel] Prepopulate by URL

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1078]
It would be very convenient if the panel allow the prepopulation of new pages via URL. Say I want to add a link in an info field to offer the user a shortcut to create a page of a certain category:

    /panel/pages/projects/new?category=architecture

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#55](https://github.com/k-next/ideas/issues/55).
