### ISSUE TITLE
[Panel] The revert button does not revert checkboxes

### ISSUE THREAD

**Issue by bezin** [getkirby/kirby#1079]
Hi folks, 

as in the title: the revert button does not revert selections in field checkboxes

To reproduce: 
* Have a checkboxes field
* Select some options
* Hit revert

Expectation: 
* Selected options are unselected again

Reality: 
* Options are still selected

Keep up the amazing work. That new panel? 😍

Cheerio

**Comment by bastianallgeier** [comment]
Thanks for the kind words, Benedict! 😀

I just fixed the bug
