### ISSUE TITLE
[Panel] Tabs do not get refreshed in rare cases

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1080]
blueprints differ in not having tabs at all, having 2 or 3. 

- when using the arrow navigation to move from page to page or
- when drilling down into children

it happens about 1/30 times that the tabs are not refreshed rendering panel inactive. only a browser page refresh helps. 

i will try to take a look at the dev console next time and report back. failed to remember that last time it happened.

**Comment by bastianallgeier** [comment]
✅

**Comment by bnomei** [comment]
@bastianallgeier found the problem or closed since i did not provide more information yet?

**Comment by bastianallgeier** [comment]
99% sure I'm fixed it :)
