### ISSUE TITLE
[Cms] The method "Avatar::isResizable" does not exist

### ISSUE THREAD

**Issue by flokosiol** [getkirby/kirby#1081]
I use (simplified)

```
<?= $kirby->user()->avatar()->crop(240, 240, ['crop' => 'center top'])->url() ?>
``` 

to get the url of a cropped avatar image. It worked until one of the last nightly builds (not sure which one, sorry). Can't avatars be cropped anymore? 

If I role back the updated core files everything works fine again.

I'm using the **devkit**. 

![bildschirmfoto 2018-10-11 um 13 31 13](https://user-images.githubusercontent.com/1224797/46801414-eb1b8480-cd5a-11e8-9ea5-9c50ba0b1ac0.png)

**Comment by bastianallgeier** [comment]
✅
