### ISSUE TITLE
[Panel] Always return file type in files field objects

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1082]
On page load (refresh or first load) / save, here's the content of an item within a `files` field:

<img width="546" alt="capture d ecran 2018-10-11 a 17 26 52" src="https://user-images.githubusercontent.com/14079751/46815344-06968780-cd7b-11e8-8653-004649a2d88a.png">

Here's the same when you're manipulating the field or loading the page dynamically (back-and-forth between pages) :

<img width="548" alt="capture d ecran 2018-10-11 a 17 26 31" src="https://user-images.githubusercontent.com/14079751/46815410-2cbc2780-cd7b-11e8-964b-93e76c14f98a.png">

It'd be awesome if we could always have the `type` attribute available.

**Comment by bastianallgeier** [comment]
✅
