### ISSUE TITLE
[CMS] Preview of draft pages only possible via Panel

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1085]
If a page is a draft it cannot be accessed directly via url (e.g. `https://.../my-draft-page`).
This is correct and expected if nobody is logged in but it's the same if someone is logged in.

Somehow, I would expect it to show the draft page via the designated URL when logged in but instead it only shows the page preview when clicking "open" from within the Panel.

The URL of the preview page then looks like e.g.:
`https://.../my-draft-page?token=1b5fcb35943765ed8714ed72251cf9e9973747a8`.
and is always accessible (if logged out, with sessions and cookies cleared and also from a different browser).

It looks secure since nobody can guess this token but still everybody who knows the URL can review the page (even without panel access what is great!).

With this implementation it is **impossible to preview a draft page without using the Panel**, since you cannot guess or "generate" the token.

**Comment by REHvision** [comment]
related to #241

**Comment by lukasbestle** [comment]
I feel like both methods should work (either to use the "cryptic" link without having to be logged in or to use the direct URL while being logged in). It's probably indeed related to #241 (the implementation was made when we didn't have a state of "being logged in" in the frontend).

You can get the token in the code using `$page->previewUrl()`:

https://github.com/k-next/kirby/blob/3.0.0-beta-6/src/Cms/Page.php#L983-L995

The token itself isn't magical, it is actually generated like this:

https://github.com/k-next/kirby/blob/3.0.0-beta-6/src/Cms/Page.php#L1302-L1311

**Comment by bastianallgeier** [comment]
✅
