### ISSUE TITLE
[CMS] Decouple sorting and status of pages (folder names)

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1086]
### Problem
is that the status and sorting of pages are still intertwined and that seems to be the root of multiple problems:

> [...] Can't just unlisted- & draft-pages be highlighted as that and still be within the sorting flow? They would be ignored anyway when only `->listed()` pages are chosen in a template and the sorting of them stays the same. [...]

_Originally posted by @pju- in https://github.com/k-next/kirby/issues/944#issue-355258841_

> If you define a value for automatic order (such as `num: date`) in the blueprint for a page, the num number is set correctly when you switch the page status to _published_, but lost once you re-save the page.

_Originally posted by @wottpal in https://github.com/k-next/kirby/issues/302#issuecomment-378155531_

> [...] the way sorting in Kirby works is that a number prefix is added to the content folder of the page. This _only applies to published pages_*, this is how Kirby distinguishes between published/unlisted.
> 
> So this is not really a bug, but rather a design/UX problem: For the user it's not necessarily clear that sorting the pages in the panel affects the pages visibility.

_Originally posted by @Targoran in https://github.com/k-next/kirby/issues/393#issue-312581631_

> [...] Regarding the comments to visualize the status and sort logic better, we will have a closer look at this again towards the beta. There are a lot of other issues in that direction already, which I will close this to keep our focus on track. But it is not forgotten.

_Originally posted by @distantnative in https://github.com/k-next/kirby/issues/393#issuecomment-398816617_

### Proposed solution
- **always sort pages!**
  - add a sorting prefix to every page folder (also to unlisted and draft pages)
- **have another character to differentiate listed and unlisted page folders**
  - instead of removing the sorting
  - maybe simply prepend an underscore to unlisted pages (`_20180321_page-slug` or `_0_page-slug`) since this pattern also applies to the drafts folder and deactivated plugins
    - unlisted pages could still correctly sort by this then and show as "unlisted block" visually separated from listed pages in the filesystem
  - or keep the sorting prefix in the beginning and add the status character after it
    - maybe `20180321___page-slug` or `20180321_x_page-slug`
    - this way the unlisted page also stays within the sorting flow within the filesystem
- **move page drafts to the _draft folder**
  - there is no problem with any sorting prefix
  - and no problem with listed/unlisted status (both could be drafts)
  - it also doesn't block future features like a published and draft version of the same page at the same time

**Comment by pju-** [comment]
One thing I would definitely like about this from what I undestand is that when you change the status to listed you would not have to pick the position.
That is one of my least favourite things in the panel UI, it seems confusing to clients and with a lot of pages it can get very very unwieldy.
