### ISSUE TITLE
[Panel] Query page files for selection in files field

### ISSUE THREAD

**Issue by frttbrg** [getkirby/kirby#1087]
I think this is not possible so far but maybe an interesting feature:

In my blueprint I have two or more files sections for the upload of different image files. And I have a two or more files fields so that editors can select one of the previously uploaded images to add them to the website.

Problem: The files field always shows all images of a page, but it would we be nice to query images e.g. by blueprint etc. to preselect the right options.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#56](https://github.com/k-next/ideas/issues/56).
