### ISSUE TITLE
[Cms] Plugin options arrays aren't overriding the default ones

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1088]
I'm adding an array option within a plugin:

```php
Kirby::plugin('sylvainjule/myplugin', array(
  'options' => array(
    'myarray' => ['one', 'two'],
  ),
));
```

If I try to change its value within my `config.php`:

```php
return array(
  'sylvainjule.myplugin.myarray' => ['three']
);
```

Then `option('sylvainjule.myplugin.myarray')` returns `['three', 'two']`.

If I set two elements within the config, then the default is completely rewritten.

In this case, config should be completely overwriting the default array, however long.

**Comment by bastianallgeier** [comment]
✅
