### ISSUE TITLE
[Panel] Changing URL does not work

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1089]
I used the nightly build 2018-10-12:

When I change the url of a page, the folder name is not changed. This also means that I am redirected to a page that does not exist:

<img width="1134" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/46935133-89a92d80-d05a-11e8-8492-ef5c2e918fc1.png">

**Comment by bastianallgeier** [comment]
✅
