### ISSUE TITLE
Uploads from iOS doesn't work

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby/kirby#109]
When uploading images from iOS every image upload has a filename of image.jpg which therefore gets overwritten over and over again, even when selecting multiple images to upload at once, only one gets uploaded which is the last overwrite.

**Comment by bastianallgeier** [comment]
This is finally fixed on the develop branch. The image.jpg filename will now automatically be replaced with a unique filename (i.e image-41jhaskda2.jpg) to avoid this annoying bug.
