### ISSUE TITLE
[Panel] Latest nightly (16/10) breaks plugins api/ routes

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1096]
All my plugins' api/ routes stopped working with the latest build, returning:

```
code: 500
exception: "Exception"
file: "kirby/src/Http/Router.php"
line: 119
message: "No route found for path: "matomo-panel/get-bulk-summary" and request method: "GET""
```

when called like this:

```javascript
created() {
    this.$api('matomo-panel/get-bulk-summary').then(...)
}
```

**Comment by bastianallgeier** [comment]
The plugin routes are injected after the api routes now to make sure the api is not simply screwed up by plugins. But there's something better coming tonight: API ROUTES. Those Api routes are 100% embedded in our REST API and inherit all the good stuff like authentication and other goodies (I need to document)

It goes like this: 

```php
Kirby::plugin('my/plugin', [
    'api' => [
        [
            'pattern' => 'awesome',
            'action'  => function () {
                return 'nice';
            }
        ]
    ]
]);
```

This will then automatically be available at `/api/awesome`. 
The best part about it is, that it will also listen to the api settings, so if the api is moved to a different path it will still be available and the route will also be switched off if the api is switched off

**Comment by sylvainjule** [comment]
Sounds great!
