### ISSUE TITLE
sortBy() doesn't work with mix case

### ISSUE THREAD

**Issue by eighthday** [getkirby/kirby#1098]
sortBy does not work correctly if some of the page titles start with a lowercase letter and some with an uppercase letter 

$pages->find('projects')->children()->sortBy('title', 'asc');

This should provide a list of all projects sorted by title in alphabetical order regardless of capitalization, but the lowercase ones are shown after the uppercase ones.  The same problem is displayed in the panel pages field.

**Comment by lukasbestle** [comment]
Have you tried:

```php
$pages->find('projects')->children()->sortBy('title', 'asc', SORT_STRING | SORT_FLAG_CASE);
```

This flag means case-insensitive sorting. It isn't enabled by default as there are many use-cases where case-sensitivity is wanted.

**Comment by eighthday** [comment]
@lukasbestle thanks! works great.  Is there something similar for displaying pages in the panel ? Also should this not be the default setting?

**Comment by bastianallgeier** [comment]
I agree that it should actually be case insensitive by default. @lukasbestle did we have the same behavior in v2? We just ported the sorting code, so I'm a bit puzzled about this.

**Comment by bastianallgeier** [comment]
I switched to natural and case insensitive sorting by default. In my opinion this is a lot more usable for most cases and you can still use the sort flags to get anything else.

**Comment by lukasbestle** [comment]
Yes, v2 also used "case-sensitive regular sorting". Maybe it makes sense to have case-insensitive sorting as the default though.

Just a quick note: We had issues with *locale string* sorting in v2 (see https://github.com/getkirby/panel/issues/1138). Let's hope natural sorting works more reliably. We need to keep an eye on this.
