### ISSUE TITLE
No field methods to fetch users and files from users/files field

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1099]
These fields always store content in yaml format, even if the `multiple` option is set to false,  rendering the `toUser`and `toFile()` methods almost useless, while a method to fetch all users/files is missing. Guess the same applies to the `toPage()` method, but a `toPages()`method exists.

However, shouldn't those fields just store a simple value (no yaml) if multiple is set to false?

**Comment by bastianallgeier** [comment]
I modified all the methods to work the same way: 

```
Field::toFile
Field::toFiles

Field::toPage
Field::toPages

Field::toUser
Field::toUsers
```

The singular versions return a single object while the plural versions return a collection. This works no matter if there's yaml in the field or just a single filename, email address or page id.
