### ISSUE TITLE
[Panel] Login button improvements

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#11]
I think the login button can be improved.

- It has a really strong icon and a much weaker text. I don't feel the balance between them.
- It's a bit too much space between the icon and the text.
- I perfer to have it positioned to the right.
- It looks more like a link than a button and I miss the edges in this case.

It may not need to look like a traditional button, but with some enhancements, I think it would look more like a solid action than it does now.

**Comment by bastianallgeier** [comment]
✅ at least part of it is implemented now :)
