### ISSUE TITLE
nested structure field run in error

### ISSUE THREAD

**Issue by thomasfahrland** [getkirby/kirby#1100]
Nesting the structure field for a page configuration looks fine in panel:
![bildschirmfoto_2018-10-17_um_19 41 01_720](https://user-images.githubusercontent.com/24317084/47138633-3af9ce80-d2ba-11e8-91a5-ed1c8091aaf2.png)

But while saving, the panel throws these error:
![bildschirmfoto_2018-10-17_um_19 42 31_360](https://user-images.githubusercontent.com/24317084/47138640-40571900-d2ba-11e8-95ad-0d0f63bcac5e.png)

Here is the configuration:
[fields_yml.txt](https://github.com/k-next/kirby/files/2490709/fields_yml.txt)

Testet in K3 Beta 6 in nightly builds:
2018-10-17
2018-10-17

**Comment by bastianallgeier** [comment]
@thomasfahrland super helpful issue description!

**Comment by bastianallgeier** [comment]
✅ will be fixed tonight.
