### ISSUE TITLE
[CMS] Files are not copied to media folder when URL rewrite is used

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1102]
I have a custom file method that adds a hash to the file url. I used it for many Kirby 2 Websites and ported it to the new Kirby 3 plugin syntax:

```php
Kirby::plugin('plugin/revUrl', [
  'fileMethods' => [
    'revUrl' => function() {
      $url = $this->url();
      $hash = substr(md5($this->modified()), 0, 10);
      $pos = strrpos($url, $this->extension());
      return substr_replace($url, '-'. $hash, $pos - 1, 0);
    }
  ]
]);
```

This is the matching Apache rewrite rule (set before the Kirby rewrite rules):

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(media\/.*)-([a-f0-9]{10})\.(jpg|png|svg|mp4|webm)$ $1.$3 [L]
```

Usage:

```php
$page->file('hero.mp4')->revUrl(); // returns https://website.com/media/pages/home/hero-4bcf8b242f.mp4
```

But for some reason the `hero.mp4` is not copied to the `media` folder when it is requested. (This happens also for other file types.)
If the `hero.mp4` is already in the `media` folder, the rewrite works as expected. 

Is this a Kirby bug or just a configuration issue on my side?

...For thumbs, I use the core component plugin `file::url` to add a hash to the thumb filename, so I don’t need a URL rewrite for that. But I suppose I can’t change the filename when a file is [published](https://github.com/k-next/kirby/blob/master/src/Cms/FileActions.php#L180), right?

**Comment by bastianallgeier** [comment]
✅
