### ISSUE TITLE
Official API clients

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1106]
Originally proposed in https://github.com/k-next/plugins/issues/87.

---

To make it easier for third-party devs to access content in a Kirby installation from the outside (apps, other servers, custom admin interface etc.), we could offer API clients for the most common programming languages like JS and PHP. Or we could at least publish a JS reference implementation based on the Panel code that can then be converted to other languages by the community.

**Comment by bnomei** [comment]
for js having a real npm package would be awesome.

**Comment by lukasbestle** [comment]
Yep, that would make sense. We could then also require it from the Panel code to avoid code duplication.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#57](https://github.com/k-next/ideas/issues/57).
