### ISSUE TITLE
[Api] Support for custom API models

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1107]
Originally proposed in https://github.com/k-next/plugins/issues/87#issuecomment-423932907.

---

API models/collections and their views are a very powerful feature of the API. It would make sense to expose that feature to plugins so that plugins can define their own models/collections with their custom views.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#58](https://github.com/k-next/ideas/issues/58).

**Comment by bastianallgeier** [comment]
✅
