### ISSUE TITLE
Opening a modal inside a structure field doesn't display properly

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#1116]
While opening a modal inside a structure field the modal appends inside the structure field and therefore the css "position: fixed" is broken and the modal doesn't display well.
Moreover the page scrolls to the top for no reason.

![capture d ecran 2018-10-22 a 10 21 07](https://user-images.githubusercontent.com/4832038/47283761-e2da0980-d5e4-11e8-9dcb-673633703e57.png)

Many thanks,
T

**Comment by bastianallgeier** [comment]
✅
