### ISSUE TITLE
Panel: Undo for textarea buttons

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#112]
This request just popped up in the v2 repo (Panel issue 1121).

If you click a textarea button, the effect it has (e.g. wrapping text with bold or italic markers) should be possible to undo with Cmd-Z/Ctrl-Z.

**Comment by bastianallgeier** [comment]
This is actually already implemented :)

**Comment by lukasbestle** [comment]
Awesome, even better! :)

**Comment by fabianmichael** [comment]
@bastianallgeier @lukasbestle

The problems still persists in Firefox 84, while it works as expected in Chromium-based browsers.

Please re-open.

**Comment by bastianallgeier** [comment]
It's a Firefox bug that we cannot solve on our end.

**Comment by fabianmichael** [comment]
@bastianallgeier Meh! That’s sad to hear … just tested, and it also affects this textarea on GitHub.
