### ISSUE TITLE
Panel: sorting-handle not correctly aligned

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1122]
The sorting-handle is not correctly aligned in a files field within a structure field

![bildschirmfoto 2018-10-23 um 08 37 36](https://user-images.githubusercontent.com/25037153/47340607-15483d00-d69f-11e8-986c-65543c1c35fc.png)
 
3.0.0-beta-6.8

**Comment by christianschley** [comment]
Related to https://github.com/k-next/kirby/issues/728

**Comment by bastianallgeier** [comment]
✅
