### ISSUE TITLE
[Panel] Kirby checkbox and radio: Native input element still visible on iOS

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1124]
This is just a minor visual bug: On iOS (12), the native `<input>` Element is still visible as a tiny dot:

![ios](https://user-images.githubusercontent.com/15672385/47345710-ba691280-d6ab-11e8-8a6a-54dd4fe55b64.png)

I used the nightly build from 2018-10-22.

**Comment by bastianallgeier** [comment]
✅
