### ISSUE TITLE
Replace umlauts correct

### ISSUE THREAD

**Issue by timoreddig** [getkirby/kirby#1130]
If you create a new page, in my opinion the german umlauts ä, ö, and ü will not be replaced correctly. Instead of a, o an u it should be ae, oe and ue.

## before:
![bildschirmfoto 2018-10-24 um 22 03 20](https://user-images.githubusercontent.com/1371062/47458374-b0453200-d7d9-11e8-93c2-544a990d702c.png)

## after:
![bildschirmfoto 2018-10-24 um 22 03 56](https://user-images.githubusercontent.com/1371062/47458373-b0453200-d7d9-11e8-9f30-37c8ac480f91.png)

**Comment by lukasbestle** [comment]
Thank you for reporting that issue.

We had a similar issue in Kirby 2, but the other way around (see https://github.com/getkirby/panel/issues/773). The same characters that are used as Umlauts in German are also used in other languages (like Turkish) and need to be converted differently there.

Replacing all accented characters with just their base character is therefore probably the safest way for most languages.

However it should be possible to customize that ASCII translation table from plugins and/or the config. In Kirby 2 that was easily possible. However I can't say right now if it is also already possible in Kirby 3.

**Comment by timoreddig** [comment]
@lukasbestle thank your for your information. It´s ok for me. I´ll close the issue.
