### ISSUE TITLE
[Toolkit] Dir::dirs and Dir::files don't work

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1140]
referring to this: https://github.com/k-next/kirby/blob/master/src/Toolkit/Dir.php

Both methods use `Dir::read` to get the initial set of files in a directory. 

`Dir::read` however doesn't return the full path to the subdirectories, but only their name (because that's what scandir does). 
Therefore the subsequent "is_dir" check doesn't find the directories passed to it, unless the passed dir happens to be the current working directory (that's why the test doesn't fail).

**Comment by bastianallgeier** [comment]
✅
