### ISSUE TITLE
New API routes aren't found if 3+ plugins are registering them

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1141]
Took me some time to pin it down, and it sounds kind of weird, but it seems that running 3 plugins or more registering API routes prevents all plugins API routes from being registered.

With the latest nightly (24.10)

- **1 plugin:** API routes are registered.
- **2 plugins:** API routes are registered.
- **3 plugins:** no more API routes for any plugin.

**Comment by bastianallgeier** [comment]
WTF :(

**Comment by sylvainjule** [comment]
Kept trying things because I found it weird... 
Turns out there is no magic number 3, it can also happen with 2 plugins . But my results are inconsistent...

**1. Test plugins** (breaks with 2)

From an empty `plugins` folder. I add this, the route works.

```php
Kirby::plugin('my/first', [
  'api' => [
    'routes' => [
      [
        'pattern' => 'my-first-endpoint',
        'action'  => function () {
          return [
            'plugin' => 'first'
          ];
        }
      ]
    ]
  ]
]);
```

If I add a second plugin, both routes aren't working:

```php
Kirby::plugin('my/second', [
  'api' => [
    'routes' => [
      [
        'pattern' => 'my-second-endpoint',
        'action'  => function () {
          return [
            'plugin' => 'second'
          ];
        }
      ],
    ]
  ]
]);
```

**2. Real plugins** (breaks with 3)

From an empty `plugins` folder. 

- I add my [Matomo plugin](https://github.com/sylvainjule/kirby-matomo) -> routes work.
- I add my [Extractor plugin](https://github.com/sylvainjule/kirby-colorextractor) -> routes work.
- I add my [Subtitler plugin](https://github.com/sylvainjule/kirby-colorextractor) -> no more routes.

**Comment by bastianallgeier** [comment]
I think what might happen is a weird merge conflict when the routes get injected into the other set of routes. array_merge is not always leading to consistent results, when the keys get mixed up.

**Comment by bastianallgeier** [comment]
It was a merge issue indeed.
