### ISSUE TITLE
page.status.listed isn't rendered when changing languages

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1143]
Tested with latest nightly.

![pagestatus 2018-10-27 16_02_32](https://user-images.githubusercontent.com/14079751/47605054-e06f1980-da01-11e8-8522-47979bfef762.gif)

**Comment by sylvainjule** [comment]
Sorry for the confusion, closed it because I got confused and thought it was only caused by the current translations status and a missing language file. Which is what it causing the error, log shows:

```
[27-Oct-2018 15:35:14 Europe/Paris] The translation "fr" could not be loaded
```

But the panel shouldn't try to translate its UI when switching pages languages, so it is indeed a bug.

**Comment by bastianallgeier** [comment]
✅
