### ISSUE TITLE
Deleting a page throws an unexpected error

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1144]
Running the latest beta (build feadd58).

When I try to delete a page, the page is deleted, but the following error is shown.

![screen shot 2018-10-27 at 17 35 03](https://user-images.githubusercontent.com/88007/47606064-35655c80-da0f-11e8-966b-34e683291838.png)

(And, yes, I am already in debug mode).

**Comment by bastianallgeier** [comment]
Same as for the other ticket. The debug output would be super helpful.

**Comment by omz13** [comment]
Hmm... same as for the other.

```PHP Fatal error:  Nesting level too deep - recursive dependency? in .../blancmange/vendor/getkirby/cms/src/Toolkit/Collection.php on line 895```

![screen shot 2018-10-28 at 14 50 33](https://user-images.githubusercontent.com/88007/47616724-eed03a80-dac0-11e8-868e-9017b96b5fb3.png)

**Comment by bastianallgeier** [comment]
Is it the same template?

**Comment by omz13** [comment]
Yes, same template. This was on a test repo and I "borrowed" the templates from DevKit.

**Comment by bastianallgeier** [comment]
✅
