### ISSUE TITLE
Image files with parenthesis in name cause a 'route not found for path' error

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1145]
Due to #1142, I am manually adding image files into my site. This is working well, except when I add a file that has parenthesis in its name. The file is showing in the list of files:

![screen shot 2018-10-27 at 18 08 57](https://user-images.githubusercontent.com/88007/47606402-7e1f1480-da13-11e8-9a15-5ff3ff4cf0d7.png)

But when clicking on "..." to open it, an error happens:

![screen shot 2018-10-27 at 18 09 03](https://user-images.githubusercontent.com/88007/47606409-97c05c00-da13-11e8-8de2-56875f277eb1.png)

(The version without parenthesis - `blancmange_band.jpg` works fine.)

**Comment by bastianallgeier** [comment]
✅
