### ISSUE TITLE
GroupBy no longer works with structures

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#1148]
<pre>
<?php
$pagecontent = $page->pagecontent()->toStructure()->sortBy('category', 'asc')->groupBy('category');
foreach($pagecontent as $category => $items): ?>
</pre>

groupBy causes error.
<pre>
    public function __set(string $id, $props)
    {
        if (is_array($props) !== true) {
            throw new InvalidArgumentException('Please define the structure object props as array');
        }
</pre>

This was working in Nightly Build 6.10

**Comment by bastianallgeier** [comment]
✅
