### ISSUE TITLE
page.create:after hook has no access to page model

### ISSUE THREAD

**Issue by georgobermayr** [getkirby/kirby#1152]
Using a `page.create:after` hook, `$page` in the function is a instance of `Kirby\Cms\Page` instead of the registered page model. 

```
'hooks' => [
    'page.create:after' => function($page) {
       $class = get_class($page); // Kirby\Cms\Page
  }
],
```

A `page.update:after` works fine and is having access to the page model correctly.

**Comment by bastianallgeier** [comment]
✅
