### ISSUE TITLE
[Api] Issues with the CSRF helper & check

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1154]
The recent changes to the CSRF helper and API auth check (https://github.com/k-next/kirby/commit/c58007cc1fc0cea812eb770e8d894e3ba3a8595a and https://github.com/k-next/kirby/commit/a089e3d336ddae28a77d9481d3d9a061bb17b04c) have introduced a few issues:

- [x] [`hash_equals()`](https://github.com/k-next/kirby/blob/a089e3d336ddae28a77d9481d3d9a061bb17b04c/config/helpers.php#L68) is a good enhancement to the helper, but there needs to be a check if the session contains a `csrf` token before calling `hash_equals()`, otherwise it will fail with `hash_equals(): Expected user_string to be a string, null given`. Can be fixed by adding `&& is_string($session->get('csrf')) === true` in the `if` above.
- [x] `hash_equals()` expects the known string to be the first param and the string provided by the user to be the second param. At the moment it's flipped. The order *does* actually matter according to the PHP docs. We need to verify where else we may have flipped the order.
- [x] I think we should switch from two separate `if`s to an `if`/`elseif`/`else` structure while we are at it. [The code since this change](https://github.com/k-next/kirby/commit/a089e3d336ddae28a77d9481d3d9a061bb17b04c#diff-a0445846e2a248990a882cba02e8b1e7) isn't immediately clear when reading it.
- [x] It looks like the CSRF token is [only validated if Basic auth is *disabled completely*](https://github.com/k-next/kirby/commit/c58007cc1fc0cea812eb770e8d894e3ba3a8595a#diff-c77cbf48e9ee35f37d1ca9786cb0cfbe). However it should also be checked if Basic auth is generally enabled but the current request uses session auth. So it shouldn't depend on the config but on the type of request.

---

*Also see [this thread in Slack](https://getkirby.slack.com/messages/CBN859614/convo/CBN859614-1541008372.140100/).*

**Comment by bastianallgeier** [comment]
✅
