### ISSUE TITLE
[Panel] Current language is lost on page refresh

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1155]
**Describe the bug**
On a multi-language setup, the current edited language is lost on page refresh. In-app navigation works fine. This can not only become tedious, but also very risky if the user / client doesn't pay attention to the current language they're in after a refresh.

**Expected behavior**
Some kind of persistence. Maybe storing the language in `localStorage` or, probably better, with something like [vuex-persist](https://github.com/championswimmer/vuex-persist).

**Kirby Version**
All latest nightlies.

**Comment by bastianallgeier** [comment]
✅
