### ISSUE TITLE
Snippet / Variable Undefined

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1157]
**Describe the bug**
Variables passed to snippets gets undefined in snippet file.
```
<?php snippet('menu', [
        'test' => $site->header_menu(),
        'ohcrap' => $site->header_active(),
        'areyousuresir' => 'Hell yeah',
    ]); ?>
```

**Kirby Version**
3.0.0-beta-6.13

**Comment by texnixe** [comment]
I can't reproduce this. I tested you code in the header of the starter kit

**Comment by H-i-red** [comment]
Sorry my bad, it works...
