### ISSUE TITLE
When publishing a date numbered page and the date is missing, Kirby prepends a zero

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1158]
**To Reproduce**
1. Go to an article page in panel
2. Make page draft
3. Remove date entry
4. Publish page again
5. Inspect folder in file tree

**Expected behavior**
In Kirby 2, the current date was used if the date field is empty. Don't know if that is the best solution, but the current one isn't useful either.

**Screenshots**

**Kirby Version**
Beta 3.16

**Comment by bastianallgeier** [comment]
Should be easy to turn it back to the v2 way of handling it. To be honest I'm also not sure what's better. The zero is a bit more logical from a dev standpoint, but the current date is probably more practical.

**Comment by movingwater** [comment]
If `'date.handler' => 'strftime'` is set, it also prepends a zero instead of the date.

**Comment by bastianallgeier** [comment]
✅
