### ISSUE TITLE
Blocking translation of Structures does not work

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1159]
**Describe the bug**
Using `translate: false` has no effect on Structures. Data is copied to the language meta file.

**To Reproduce**
add `translate: false` in blueprint to a structure.

**Expected behavior**
I expected the non translatable Structure to only exist in default language.

**Kirby Version**
d899843d81cdb720e654ec466ddcb33694560737

**Desktop:**
 - OS: macOS, Apache via MAMPPro
 - Browser: Firefox dev
 - Version: 64

**Comment by bastianallgeier** [comment]
✅
