### ISSUE TITLE
[Panel] Trying to translate Urls changes slug

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1160]
**Describe the bug**
Switching the language to non default in the panel and changing the url does not translate the url but changes the slug for all languages.

**Expected behavior**
Problem is that i associated "change url" setting of page to be aware to changed language.
I expected the `URL-Key` data to appear in the meta file of the translated language. Just like this would be done when editing the txt file manually.
https://nnnnext.getkirby.com/docs/guide/multi-language/translating-url

**Kirby Version**
d899843

**Desktop**
macos, apache via mamppro 4, firefox dev 64

**Comment by bastianallgeier** [comment]
✅
