### ISSUE TITLE
Using Url-Key does not change URL

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1161]
**Describe the bug**
Using `Url-Key` in meta data file does not change the slug yielded by `$page->url()`.

**To Reproduce**
https://nnnnext.getkirby.com/docs/guide/multi-language/translating-urls

1. default language has `url` to `/`. create additional language 'jp'. 
2. new page object with slug `awesome`
3. switch language to jp and save (to make sure meta file exists)
4. set `Url-Key: osoreooi` in editor for `content/awesome/default.jp.txt`

**Expected behavior**
```php
site()->visit('awesome')->url();
// http://example.com/awesome
site()->visit('awesome', 'jp')->url();
// http://example.com/jp/osoreooi
```

**Desktop:**
macos mojave, mamppro 4 apache, firefox dev 64

**Comment by texnixe** [comment]
Currently, you have to use a field called `slug`, I think a fallback to use `URL-Key` will be implemented before launch (personally, I always disliked the URL-Key field name because I never knew how to spell it correctly, so I'm glad this has been changed).

**Comment by bnomei** [comment]
@texnixe thanks for explaining. thats not in the docs yet.

is there any way to set a different slug for each language of a page object in the panel? i mean using the gui not via the meta file? since "change url" does not work like that.
https://github.com/k-next/kirby/issues/1160

do i have to create a custom text-field called `slug` in the blueprint? will that work? how to set proper validation?

**Comment by texnixe** [comment]
Yes, that works like in Kirby 2 with a custom field called slug. I know it's not in the docs yet, because when I wanted to document it, I ran into the same issue and haven't had the time to add it yet.

**Comment by bastianallgeier** [comment]
✅
