### ISSUE TITLE
allow TLS in addition to SSL for emails

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1162]
**Describe the bug**
email does not allow `tls` (only ssl) even though phpmailer could do it.
`($this->transport()['ssl'] ?? true) ? 'ssl': null` does not allow any other value than `null` or `ssl`. 
https://github.com/k-next/kirby/blob/develop/src/Email/PHPMailer.php#L66

**To Reproduce**
https://nnnnext.getkirby.com/docs/guide/emails#transport-configuration
```
return [
  'email' => [
    'transport' => [
      'type' => 'smtp',
      'host' => 'smtp.company.com',
      'port' => 465,
      'ssl' => 'tls', // <-- instead of boolean
    ]
  ]
];
```

**Expected behavior**
`tls` should have been used

**Kirby Version**
current nighlty

**Comment by bnomei** [comment]
@rasteiner did ask that on slack.

**Comment by rasteiner** [comment]
related and alternative solution https://github.com/k-next/ideas/issues/121 :)

**Comment by lukasbestle** [comment]
Maybe we should rename the option to `security`:

```php
return [
  'email' => [
    'transport' => [
      'type' => 'smtp',
      'host' => 'smtp.company.com',
      'port' => 465,
      'security' => 'ssl|tls', // <--
    ]
  ]
];
```

**Comment by bastianallgeier** [comment]
✅ The security option is a much better fit!
