### ISSUE TITLE
Language loop affected by $page->url() output

### ISSUE THREAD

**Issue by tobystokes** [getkirby/kirby#1163]
Not sure this is the definitive way to reproduce the issue, but for me, this only affects top-level pages. Homepage and grandchildren pages are not affected.

**To Reproduce**

Using the [Switch B ](https://nnnnext.getkirby.com/docs/guide/multi-language/switching-languages) example template:

```
  <ul>
    <?php foreach($kirby->languages() as $language): ?>
    <li<?php e($kirby->language() == $language, ' class="active"') ?>>
      <a href="<?= $page->url($language->code()) ?>">
        <?= html($language->name()) ?>
      </a>
    </li>
    <?php endforeach ?>
  </ul>
```
The foreach loop only outputs the default language on certain pages.
If I remove  `<?= $page->url($language->code()) ?>` from the loop (href value), it outputs both as expected.
If _before_ the loop, I add `<?= $page->url() ?>`, it also outputs both languages.
In all situations, `<?php dump($kirby->languages()); ?>` always returns both languages,  
The site was created via devkit, pretty much unmodified from there except to add the language nav in default template. All top-level pages of any type seem to exhibit this, but children of those pages behave as normal.

**Version**
Kirby 3.0.0-beta-6
PHP 7.2.1

**Comment by bastianallgeier** [comment]
✅
