### ISSUE TITLE
2 sections with different template from same parent messes up manual sorting in panel

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1164]
**Describe the bug**
Having 2 sections with `different template` from `same parent` messes up manual sorting in panel :

**To Reproduce**

You have to drag the pages back and forth a couple of times to make them sort.

**Kirby Version**
3.0.0-beta-6.14

**Desktop (please complete the following information):**
 - macOS
 - chrome
 - latest

**Comment by H-i-red** [comment]
**Use case:** Have a parent page called `blog` with the children templates `post` and `categories`.
Then have one section with `posts` and another section with `categories`.

**Comment by texnixe** [comment]
Alternative: Instead of using two sections, the [Pagetable plugin](https://getkirby.com/plugins/sylvainjule/pagetable) could be used to filter pages.
