### ISSUE TITLE
Panel: Date selector in calendar widget is off-center(Firefox)

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1167]
In Firefox (63), the date selector circle is off-center in the calendar widget of the date field.

<img width="319" alt="bildschirmfoto 2018-11-06 um 10 57 00" src="https://user-images.githubusercontent.com/149678/48059177-bc0cfd00-e1b8-11e8-9609-2cd85724d418.png">

In Safari, it looks just fine.

I'm running Kirby Version 3.0.0-beta-6.14.

**Comment by bastianallgeier** [comment]
✅
