### ISSUE TITLE
Panel: Day is not selected anymore when changing year in calendar widget

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1168]
When I want to change the year of an existing date entry in the calendar widget, the day is not selected anymore and I need to click the day once more to actually save the date. If I don't, the date is not changed.

I would expect to be able to simply select a new year, without the need of re-selecting the day.

<img width="539" alt="bildschirmfoto 2018-11-06 um 12 59 06" src="https://user-images.githubusercontent.com/149678/48063087-3f801b80-e1c4-11e8-9db7-21992a18bca1.png">

When I use the select box to change the year, it works as expected – but as I can't access older years this way or simply enter the correct year, I currently need the calendar work-around.

This happens both in Firefox (63) and Safari (12). I'm running Kirby Version 3.0.0-beta-6.14.

**Comment by bastianallgeier** [comment]
I just thought about this again and then removed the bug label. I think this is a question of expectations. For me it's more clear when you have to make a conscious choice by selecting a specific date. That's also the behavior of the native date input in Chrome for example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by johannahoerrmann** [comment]
I don't understand your point – when I try to reproduce the same action (changing the year of a date only) with the calendar widget on the site you linked, I get the expected behavior I outlined above:

<img width="312" alt="bildschirmfoto 2018-11-08 um 12 10 05" src="https://user-images.githubusercontent.com/149678/48195262-70408c00-e34f-11e8-811a-1cf2bb7fcc70.png">

<img width="321" alt="bildschirmfoto 2018-11-08 um 12 10 32" src="https://user-images.githubusercontent.com/149678/48195276-78003080-e34f-11e8-9021-f4134b35ecd6.png">

<img width="306" alt="bildschirmfoto 2018-11-08 um 12 10 15" src="https://user-images.githubusercontent.com/149678/48195279-7b93b780-e34f-11e8-8daa-f3f75d8aeecb.png">

Am I missing something?

**Comment by johannahoerrmann** [comment]
Edit: I overread your specific "Chrome" example! I tried this in Firefox and got the behavior above. Hm – maybe it would be an idea to ditch the calendar widget and use the browser's native date input?

**Comment by distantnative** [comment]
For me the suggested behavior by Johanna really breaks as soon as you think about how this would work for months. Cause then the arrow navigation to a new month would also change the value already. But what happens when I had the 31 January and moving to February? Here I feel the value should really only be updated when actively choosing a date by selecting it, not just browsing around in the calendar?

**Comment by nilshoerrmann** [comment]
The underlying issue is that you have to change the year in the calendar to make the year dropdown inside the text field display a different range.

So, in order to switch the year to 2001 for instance, you have to use the calendar to make this year selectable at all. And in the context of this workaround the current behaviour doesn't make a lot of sense.

The main issue is the general behaviour of the date field.

> Hm – maybe it would be an idea to ditch the calendar widget and use the browser's native date input?

I agree that this would solve a lot of issues (edge cases handled by the browser, user expectations based on OS and browser context).

**Comment by johannahoerrmann** [comment]
@distantnative The thing is – when using the select boxes to change day, month or year, I do not need to re-select the other values. (And in your example, the 31 is automatically set to 28.) I would simply expect both possible ways to change the date to work the same.

I understand your point about "browsing" though. Hm, so how does this fit in with using the date field to *set a date*? Maybe I'm indeed just thrown off because this is the **only** way for me to change the date to a correct year right now?

**Comment by distantnative** [comment]
@johannahoerrmann @nilshoerrmann Is this still an issue? I mean I get your general viewpoint, but still have concerns that browsing in the calendar view would change the value of the field directly.

Why not select the year directly from the select input (the field's one, not in the calendar dropdown)? What am I missing?

**Comment by nilshoerrmann** [comment]
Yes, this is still an issue but I understand your objections.

The initial problem is the limitation of the year list in the input‘s select boxes. If you are not dealing with the given date range the input is useless (the biggest usability issue being not able to type). From that point expectations defer:

You are describing the calendar as a date browser, Johanna is using it as a tool to change the available date range available in the input. Combined with different browser defaults (see above) the current behavior feels buggy and against the Firefox user‘s expectations.

But the real issue isn’t the calendar but the input UI.

**Comment by distantnative** [comment]
So defining the range in the blueprint isn’t sufficient?

**Comment by distantnative** [comment]
We will close this for now. The issue here seems as you said rather the input UI for you. We would need a good concept for a user-friendly alternative.
