### ISSUE TITLE
$page->urlForLanguage() causes 500 when called for default language

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1169]
Calling $page->[urlForLanguage](https://nnnnext.getkirby.com/docs/cheatsheet/page/url-for-language)( $languageCode ) works :-)

But if it is called - and the page is the homepage - and the language code is the same as the default language for the site - then:

```
Stacktrace
Call to a member function url() on null ... getkirby/cms/src/Cms/Site.php on line 610
                                        ... getkirby/cms/src/Cms/Page.php:1448
```

(At the moment I can work around this by having a test `if $languageCode == kirby()->language()->code()` and call `$page->url()`instead, but its an extra layer of complexity.)

**Comment by bastianallgeier** [comment]
Probably related: https://github.com/k-next/kirby/issues/1163

**Comment by bastianallgeier** [comment]
✅
