### ISSUE TITLE
invalid 'home' in config does 500

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1172]
kirby 3.0.0-beta-6.15

In `config.php`, setting `home` to a non-existent page results in a `500` 😞 

e.g. `'home' => 'nosuchpage',` yields:

```
Error: Call to a member function url() on null in file .../vendor/getkirby/cms/config/routes.php on line 109
Stack trace:
  1. Error-&gt;() .../vendor/getkirby/cms/config/routes.php:109
  2. Kirby\Http\Route-&gt;{closure}() [internal]:0
  3. Closure-&gt;call() .../vendor/getkirby/cms/src/Cms/App.php:203
  4. Kirby\Cms\App-&gt;call() /.../vendor/getkirby/cms/src/Cms/App.php:613
  5. Kirby\Cms\App-&gt;render() /.../public/index.php:9
```

**Comment by bastianallgeier** [comment]
I have no idea how we could solve this. It's basically a configuration error.

**Comment by texnixe** [comment]
And since the home folder is automatically undeleteable and the slug cannot be changed either in the Panel, this is no error that should ever happen to a user.

**Comment by omz13** [comment]
@bastianallgeier, I was expecting it to throw an error rather than a generic `500`... as this is the homepage, its quite important to trap such mis-configurations, so would it be worth adding a check to ensure that the page exists?
