### ISSUE TITLE
Sorting in files field creates duplicate page

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1175]
i created a "references" page which contains multiple references as subpages. in the references-blueprint i set the template for its children to "referenz". Within the child-blueprint is a files field for an image gallery.

So when i change the sorting in the files field and save these changes, there is another page created with the same name but +1 numbering of the original one. But the images are not duplicated. just the txt-file and the folder.

You can see it in this small gif:
![1](https://user-images.githubusercontent.com/25037153/48250218-db489c00-e3fd-11e8-8c81-2b9c2f749ae1.gif)

Here are the blueprint-files of the parent and the child-page:
[blueprints.zip](https://github.com/k-next/kirby/files/2565063/blueprints.zip)

Im using the latest nightly 3.0.0-beta-6.15 but it happened already in older nightlys.

**Comment by bastianallgeier** [comment]
Unfortunately I can't reproduce this. Do you use any plugins?

**Comment by christianschley** [comment]
Hmm, no there are no plugins in use.

Can i give you any more infos to help finding the problem? The blueprints are correct, are'nt they?

**Comment by bastianallgeier** [comment]
Yes, the blueprints are fine. If you can send me a zip of the full site on Slack it would be best to debug this.

**Comment by christianschley** [comment]
This was obviously a local issue with my Mamp-settings. Could't find the exact problem yet, but my explained issue doesn't exist in other environments. Strange :)

So i'll close the issue. Thanks @bastianallgeier for your help!
