### ISSUE TITLE
Panel: Mime type invaild for css

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#1177]
Getting 'Invalid mime type ' when trying to use mime: text/css in files blueprint

**Comment by bastianallgeier** [comment]
✅

**Comment by texnixe** [comment]
This still doesn't seem to work with the latest nightly, at least not reliably. It sometimes works, sometimes not, even with the same file.

At the same time I get a bad request error message regarding the `files` endpoint.

**Comment by bastianallgeier** [comment]
I fixed it again to also detect css files from text/plain

**Comment by nilshoerrmann** [comment]
> I fixed it again to also detect css files from text/plain

Is this still supposed to work in current Kirby versions or has file treatment changed in the meantime? 
I've got a simple files section:

```yaml
sections:
  styles:
    type: files
    label: Styles
```

But when I try to upload a CSS file, I get this error message:

![Bildschirmfoto am 2022-07-18 um 13 50 31](https://user-images.githubusercontent.com/25466/179505289-f640b724-b184-4e83-8777-bb5079598c04.png)

This is happening locally on macOS where CSS files are regarded as `text/plain` and not `text/css`.

**Comment by distantnative** [comment]
@nilshoerrmann please open a new issue. replying to an issue that's been closed for 4 years, it's just too easy to overlook for us as a team.
