### ISSUE TITLE
[Panel] Pages fields adds parent page when adding child

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1178]
**Describe the bug**
Pages fields adds parent when selecting child.

**To Reproduce**
1. in pages field select ">" to drill down to child
2. select a child and press ok button
3. child and parent have been added

**Expected behavior**
Only child should have been added.

**Screenshots**
![pagesfield-parent-bug](https://user-images.githubusercontent.com/3265642/48301085-11fae100-e4e8-11e8-9e54-e11504b0c2a4.gif)

**Kirby Version**
current nightly 6221a6b
multilang setup, devkit

**Desktop :**
macos mojave, mamppro apache php 7.2, firefox dev 64

**Comment by bastianallgeier** [comment]
✅
