### ISSUE TITLE
Background colour

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1181]
**Describe the bug**
Something is wrong with the background colours:

![bildschirmfoto am 2018-11-12 um 12 45 59-fullpage](https://user-images.githubusercontent.com/25466/48345691-04289580-e679-11e8-80b9-943084ff3f88.png)

The text is unreadable.

**Expected behavior**
Being able to read the error message: "The panel cannot connect to the API 😭".

**Kirby Version**
Latest `develop` branch, latest Firefox on macOS Mojave.

**Comment by bastianallgeier** [comment]
Then you are not on the latest develop branch. This has been fixed quite a long time ago.

**Comment by nilshoerrmann** [comment]
Oh, I'm sorry. I mixed up the project server with my localhost.
