### ISSUE TITLE
[Panel] Small Firefox Bug: Mousecursor disappears

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1184]
I just found a very small bug in the Panel with Mozilla Firefox (Mac & Win).

The input caret/cursor (dont know the exact name of that *G*) disappears after dragging a file into a textarea. You can go on typing, but its quite hard without the caret.

After klicking somewhere else in the page and clicking back into the textarea, its back again!

**Comment by afbora** [comment]
I think it's a browser native bug that i found many similar issues:

**Firefox bugs tracker**

- https://bugzilla.mozilla.org/show_bug.cgi?id=1020973
- https://bugzilla.mozilla.org/show_bug.cgi?id=1327834
- https://bugzilla.mozilla.org/show_bug.cgi?id=1327919
- https://bugzilla.mozilla.org/show_bug.cgi?id=240416
- https://bugzilla.mozilla.org/show_bug.cgi?id=428129

**Repository bug**
- https://github.com/ProseMirror/prosemirror/issues/583

**You can test the bug online**

https://sticky-ferret.glitch.me/

**Comment by distantnative** [comment]
I think so too from what I have read. Will close it therefore.
