### ISSUE TITLE
[panel] Unsaved changes in one language can overwrite another language

### ISSUE THREAD

**Issue by tobystokes** [getkirby/kirby#1186]
**To Reproduce**
Go to any page on multilingual site.
Make an edit, but do not save changes.
Switch language.
Note that the unsaved changes from the previous language choice have been maintained, and can be used to overwrite the new language choice.

![ezgif-5-c20dcac9d021](https://user-images.githubusercontent.com/109024/48501275-ca9c8980-e834-11e8-859e-ee7b3ab49959.gif)

**Expected behavior**
Any unsaved changes will only apply to the language they were destined for.

**Kirby Version**
3.0.0-beta-6

**Comment by bastianallgeier** [comment]
✅
