### ISSUE TITLE
Translations duplication

### ISSUE THREAD

**Issue by fourpixels** [getkirby/kirby#1187]
While translating the pairs I found these two, which I find the same:

`120. Please enter a value greater than {min}`
**Key**
`error\.validation\.min`

`123. Please enter a greater value than {min}`
**Key**
`error\.validation\.more`

**Comment by rasteiner** [comment]
The two validators do different things.

`min` is valid if the value is equal or greater than *x*.
`more` is only valid if the value is greater than *x*.

The same concept applies to `error.validation.max` and `error.validation.less`

In Italian, I translated those strings accordingly

**Comment by bastianallgeier** [comment]
✅ I fixed this in the original translation.
