### ISSUE TITLE
[Panel] Add a i18n fallback to English for plugin's translated string

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1188]
I know you're probably fed up with languages stuff, but 🙊

**Describe the bug**
Missing translations in a plugin don't fallback to a default language, instead the string's key is shown ([illustrated here](https://github.com/sylvainjule/kirby-locator/issues/5#issuecomment-439059299)).

**Expected behavior**
Could we have a global `Vue.i18n.fallback('en')`? Would imply for plugin devs to always provide an english translation, but it'll prevent dealing with this on a per-field basis.

**Comment by bastianallgeier** [comment]
✅
