### ISSUE TITLE
Breadcrumb link in topbar rendering issue

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1189]
**Describe the bug**
The background of `<a>` tags in the `k-topbar-crumbs` overflows the bar by a pixel (or a subpixel). 

**To Reproduce**
Open panel and go to a subpage (there has to be a breadcrumb)

**Screenshots**
![image](https://user-images.githubusercontent.com/6684137/48572752-94c9d480-e90a-11e8-9037-59c125f6fd97.png)

**Kirby Version**
2a6e217479a72a2ea7d5b04cef3fee690c61fa90

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version: 70.0.3538.77

**Additional context**
A simple fix would be to remove the background color from here:
https://github.com/k-next/kirby/blob/master/panel/src/components/Navigation/Topbar.vue#L230

**Comment by bastianallgeier** [comment]
✅
