### ISSUE TITLE
[Panel] Empty select field still shows savebar

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1193]
**Describe the bug**
If I change an empty select field to a value, the savebar appears. If I change it back to the `null` option, the savebar does not disappear.

**Expected behavior**
Savebar should disappear since no changes exist.

**Screenshots**

**Kirby Version**
https://github.com/k-next/kirby/commit/440c4d0c31692617af6682156b876a3a1700bc19

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome

**Comment by bastianallgeier** [comment]
✅
