### ISSUE TITLE
`$user->avatar()`returns false true, pointing to a standard profile.jpg

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1198]
**Describe the bug**
`$user->avatar()` returns false true when using this code

```
if($avatar = $user->avatar()) {
  echo $avatar->url();
}
```

The if statement returns true and an URL is printed. However, the URL that points to a default profile.jpg image that doesn't exist in the media folder (nor anywhere).

**Expected behavior**
The if statement should return false if no user avatar is uploaded.

**Screenshots**

**Kirby Version**

Version
3.0.0-beta-6.20

**Comment by bastianallgeier** [comment]
✅
