### ISSUE TITLE
HTML minification

### ISSUE THREAD

**Issue by Flobin** [getkirby/kirby#120]
Currently, Kirby's HTML output is not minified, which is fine, but it might still be nice to have HTML minification as an option out of the box.

[Jimmyrittenborg posted about it in the Kirby forums](http://getkirby.com/forum/general/20141029/cache-and-minify).

Any thoughts on this?

**Comment by iksi** [comment]
I use this `preg_replace` for minifying Kirby’s output: https://gist.github.com/iksi/5866974c800c01ff2bdc

Haven’t found a way yet to make it modular (this of course breaks when you update Kirby). It’s up to @bastianallgeier to decide whether he wants to implement any such feature.

**Comment by lukasbestle** [comment]
In the first pre-alpha versions of Kirby 2, there was a callback mechanism that you could use to modify stuff from plugins directly without modifying the Kirby source. @bastianallgeier, was this removed or has the way it works changed?

**Comment by iksi** [comment]
Using a `site.php` file instead of editing the `index.php` file (as mentioned in http://getkirby.com/docs/advanced/customized-folder-setup) is probably a better approach for now as it doesn’t mess around with Kirby’s core files. You’d only have to echo the output with `exit()` or `die()` to prevent the last echo in `index.php`. Hooks are scheduled for Kirby 2.1 I believe.

**Comment by ian-cox** [comment]
Is anyone using this preg_replace solution with success?
I'd also be very curious to find a place to plugin the code that wont break when kirby is updated.

**Comment by lukasbestle** [comment]
As I said, there were and potentially will be hooks so that plugins can request to modify the output or other data from within their plugin file. @bastianallgeier, have you planned to re-add this feature again?

**Comment by iksi** [comment]
I use it with success but directly in index.php. A hook on the output would be great indeed.

**Comment by ian-cox** [comment]
Had some issues with regex breaking a few things. Specifically, a weird space in the nav of the kirby starter kit. Certainly not unfixable but I'm looking into other more robust solutions.

Stephen Clay's open source minify class working well for me:
https://code.google.com/p/minify/source/browse/min/lib/Minify/HTML.php

Until we have hooks, I'm using a less than perfect solution to avoid editing the Kirby core.

I'm abusing ``site.php`` in the root of my project as @iksi mentioned above.

I've also added a new directory ``sites/library`` to house my new php class.

My setup and files can be found here:
https://gist.github.com/ian-cox/1dfa456489d2b2927a1c

**Comment by iksi** [comment]
You could make a plugin an couple the minify function to `ob_start()`. In the example below you can replace the `preg_replace` with your own minify approache like you mention above.

```PHP
function minifyhtml($buffer)
{
    return preg_replace(
        '/(?>[^\S ]\s*|\s{2,})(?=(?:(?:[^<]++|<(?!\/?(?:textarea|pre)\b))*+)
        (?:<(?>textarea|pre)\b|\z))/Six', '', $buffer
    );
}

ob_start('minifyhtml');
```

**Comment by lukasbestle** [comment]
Hm, I'm not sure if this is reliable. Kirby uses the output buffer internally as well, so adding another handler layer might break the output in some edge-cases.

**Comment by ian-cox** [comment]
Thanks @iksi and @lukasbestle for all your feedback. 
I created the plugin as suggested. If you try it, let me know how it works!

https://github.com/ian-cox/Kirby-MinifyHTML

**Comment by shoesforindustry** [comment]
Thanks Ian, I dropped it into the project I was working on, no real testing, but it appeared to work, so neat! I like the idea of the plugin but appreciate hooks might be a better way to go.
One thought was to have a config file variable e.g.
```
c::set('Kirby-MinifyHTML', 'TRUE');
```
to turn it on. That way you can have it on/off for different config files e.g. dev, deploy, production?

**Comment by ian-cox** [comment]
Thanks @shoesforindustry, I just added config options to minify based on the current environment.
The plugin defaults to TRUE so modifying your config file is not required for MinifyHTML to work.

https://github.com/ian-cox/Kirby-MinifyHTML

**Comment by shoesforindustry** [comment]
Thanks @ian-cox, a default to on is a better idea and it works quite well into the first few test sites I've dropped it into. Thank you for taking the time to share.

**Comment by bastianallgeier** [comment]
I'm late to this as always :) @ian-cox the plugin looks good and works fine. Since the output buffer is gone again since a couple versions, I don't see any issues at the moment unless another plugin adds their own layer and introduces issues that way. But of course this needs some more elegant solving on Kirby's site. I'm actually planning to add a hook system for a very long time and this might be the final reason to start it.

**Comment by bastianallgeier** [comment]
I'll close this for now as it is working. @ian-cox you should really consider to submit this to http://getkirby-plugins.com

**Comment by ian-cox** [comment]
One thing to note,

Using `$file->download()` or `f::download()` will not work when the current version of the minify plugin is installed. The files themselves are being minified before getting downloaded which is creating corrupted files.

Hooks should fix this. :+1:

**Comment by JonasDoebertin** [comment]
Just to let you know, I just added the plugin to [getkirby-plugins.com](http://getkirby-plugins.com/).

:smiley:

**Comment by bastianallgeier** [comment]
@JonasDoebertin Awesome! This one is another great candidate: https://github.com/getkirby/kirby/issues/157#issuecomment-75153879

**Comment by JonasDoebertin** [comment]
@bastianallgeier Thanks for pointing me to that discussion. Somehow his submissions didn't make it through.
