### ISSUE TITLE
[Panel] Sortable: false on pages section doesn't hide the sort handle

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1205]
**Describe the bug**
As the issue title says: setting `sortable: false` on a pages section disables sorting correctly but the sort handles are still visible.

**Kirby Version**
3.0.0-beta-6.20

**Desktop (please complete the following information):**
 - Ubuntu 17.10
 - Firefox 61.0.1 and Opera 56

**Comment by bastianallgeier** [comment]
✅
