### ISSUE TITLE
Blueprint layout cards small subpages number = huge images

### ISSUE THREAD

**Issue by seb-celinedesign** [getkirby/kirby#1208]
**Describe the bug**
In pages with a layout cards blueprint, when there's only one or two subpages, their images are huge

**Expected behavior**
Set a max-width for each subpage, or at least their images.
Or add a blueprint option to set up a number of column parameter, like the field width option, eg 1/3, 1/4, etc.

**Screenshots**
![capture d ecran 2018-11-23 a 09 03 06](https://user-images.githubusercontent.com/6225064/48933269-f76d3280-eeff-11e8-859a-fd56688cabe2.png)

**Kirby Version**
3.0.0-beta-6.21

**Desktop (please complete the following information):**
 - macOS
 - Safari
 - Version 12.0.1

**Comment by SebastianEberlein** [comment]
A few nightly build ago, Bastian added the `size` option to pages sections:

https://nnnnext.getkirby.com/docs/cheatsheet/sections/pages#options

So you can use this to make the cards smaller:

```
layout: cards
size: tiny
```

**Comment by seb-celinedesign** [comment]
That's sound perfect to me !
