### ISSUE TITLE
Localized metafile gets not removed on file removal

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#1210]
on file removal not all (localized) metafiles are removed which leads to invisibility of the whole page in the panel. it seems as the metafile of default language gets properly removed in all cases but the one of the secondary language stays in the folder.

**To Reproduce**

1. create a file blueprint with some additional fields like `alt`, `caption` 
2. upload a file of that type
3. fill out some metadata (in both languages)
4. filename.de|en.txt exists now

5. remove the file in the panel (which locale doesnt matter)
6. The file and the metafile (of the current panel locale) are deleted in the folder, the other one stays.

**Expected behavior**
both metafiles should be removed

**Comment by bastianallgeier** [comment]
✅ I don't know why I missed that but the solution was actually pretty obvious. Sorry that it took so long!
