### ISSUE TITLE
[Panel] Drafts folder is not deleted after changing page status to unlisted or listed

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1211]
**Describe the bug**
The `_drafts` folder is not deleted after changing the page status to listed or unlisted, although it is empty.

**Steps to reproduce**
1. Add page in Starterkit.
2. Change page status to listed or unlisted.
3. In the `content` folder should be an empty `_drafts` folder.

**Expected behavior**
The `_drafts` folder should be deleted. (?) At least this was the behaviour in the previous Betas / Nightly Builds from a couple of weeks ago.

**Kirby Version**
3.0.0-beta-6.21

**Comment by bastianallgeier** [comment]
✅
