### ISSUE TITLE
[Panel] e.avatar is null

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1212]
After updating Kirby to `develop`@https://github.com/k-next/kirby/commit/24ceace41acd419a0a6a83eca92703c80be899e6 we are having trouble accessing the users list:

- we updated all user accounts to the new file scheme
- we built the latest panel assets
- the panel displays "e.avatar is null" when visiting `/panel/users`

The rest of the panel seems to work just fine so far.
There are no messages in the console, Firefox 63 on macOS Mojave.

**Comment by bastianallgeier** [comment]
✅
