### ISSUE TITLE
[Panel] Structure field missing form

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1213]
If I have existing items in a structure field, the form to add new shows up as expected. But if the field is empty, the form won't be displayed: the add button fades away but nothing else happens.

### Expected

The form shows up in both cases.

---

Tested using latest code from `develop` with built assets, latest Firefox on macOS Mojave.

**Comment by REHvision** [comment]
Probably related to #1206

**Comment by bastianallgeier** [comment]
I think you still have the old files hanging around. I already fixed that and cannot reproduce it.
