### ISSUE TITLE
[Panel] Multilanguage. Deleting files ending in '-en.txt' fail.

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1216]
**Describe the bug**
removing file ending in something which is part of multilang id crashed that page object.

**To Reproduce**
1.) create a multilanguage setup for `en` and any other language (like `de`).
2.) create a files section accepting `text/plain` as mimetype
3.) dragndrop upload a files like `mydata-en.txt` and `mydata-de.txt`.
4.) use panel context menu to remove any of the file. 
5.) file will be removed but metadata file will not be removed a crash panel. `mydata-en.txt.en.txt`

**Expected behavior**
remove file even is filename is similar to metadata + language identifier.

**Kirby Version**
current

**Desktop (please complete the following information):**
- apache php 7.2 mamp firefox dev 64

**Comment by bastianallgeier** [comment]
✅ It's not possible to upload text files. They would always create conflicts with Kirby's content files. There was a bug that didn't block those uploads.
