### ISSUE TITLE
[Panel] Inconsistent shortkey and save bar behaviour (CMD+S reverts changes in structure item)

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1217]
**Describe the bug**
1. Besides the issues #1206 and #1213 the save-revert bar doesn't show up when changing anything inside a structure item.

2. **CMD + S** (the most explicit _"I want to save my changes"_-shortkey) doesn't work in the current structure item form. **It actually removes/reverts everything I might have written in there...**

    So currently I have to press **ESC** or click **OK** to keep my changes before I can save them.
    (Enter only works in some fields - see 3).

Normally, when I change anything in a page or field the bar pops up and I simply press **CMD + S** to save the changes if I want to persist them (very convenient shortkey).

3. In some fields having focus (e.g. a regular text field), **Enter** also directly saves the page.
   This could become problematic (e.g. when a client possibly tries to make a new line here and thereby saves unfinished edits accidentially).
    On the other hand, pressing Enter inside one of such fields in a structure item, it closes the form, keeps the changes and the bar pops up. This is good and I can then decide to revert or save the changes explicitly.

**To Reproduce**
- for 1. change something inside a structure item -> bar doesn't show up
- for 2. change something inside a structure item and press **CMD + S**
- for 3. change the text inside a regular text field and press **Enter**

**Expected behavior**
- **Enter** to not trigger "save" regardless of the focused field (since it's too inconsistent between fields)
- **CMD + S** to always save the changes (also a currently edited structure item).

**Kirby Version**
3.0.0-beta-6.21

**Comment by bastianallgeier** [comment]
✅ I fixed the cmd+s and enter issues. But cmd+s should not trigger a full form save in my opinion. This would be inconsistent with the ok button in the structure form, which is confusing. I think we got this wrong so far.

**Comment by REHvision** [comment]
Allright, thank you :smile::+1:
