### ISSUE TITLE
Page Models in Hook are not working

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1219]
**Describe the bug**
I defined a page model with custom functions in a plugins. same plugin i did setup a hook listening to changes of files. on upload:after of file i called `$file->parent()->mysmodelfunction()` but model was not loaded and function not executed. no error thrown.

**Comment by texnixe** [comment]
`$file->parent()` doesn't return a Page object. 
Try:
```
$file->page()->mysmodelfunction()
```

**Comment by bastianallgeier** [comment]
It took me a while to figure this one out, but you tripped over our docs. It's file.create:after not file.upload:after. Sorry for that.

**Comment by bastianallgeier** [comment]
Ha, it's even correct in the docs :P
