### ISSUE TITLE
[Panel] Don't show "more" tab with 3 tabs

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#1221]
**Describe the bug**

There's a "more" tab instead of the third tab, when there are three tabs and the user is on a mobile device. There would be enough space for the third tab, though.

**To Reproduce**

Add three tabs and resize your browser to less than 700px width.

**Expected behavior**

Show the "more" tab only on four or more tabs.

**Screenshots**

![meta](https://user-images.githubusercontent.com/7975568/49150743-20316580-f30e-11e8-942c-dd7c702fa26a.gif)

**Comment by bastianallgeier** [comment]
✅
