### ISSUE TITLE
Trim BOM in content files

### ISSUE THREAD

**Issue by paulrobertlloyd** [getkirby/kirby#1222]
**Describe the bug**
This is a strange one, and perhaps hard to reproduce, but I will file a bug all the same. I have seen a few cases with the beta (3.0.0-beta-6.22) where certain fields are not recognised until the page is saved using the panel. However, this behaviour is not consistent as other pages sharing the same template _do_ display the correct data. For example, for the following page, the title was not recognised:

```
title: Alderney & Sark
----
country: Channel Islands
----
text: Those who have an opportunity afforded them to visit the little islands of Alderney and Sark…
```

Saving it with the panel produced the following:

```
Title: Alderney & Sark

----

Country: Channel Islands

----

Text: Those who have an opportunity afforded them to visit the little islands of Alderney and Sark…
```

Which meant title was recognised again. BUT! I then edited the file manually, back to its previous state, and the title was recognised. Conceivably, nothing had changed!

***

On another occasion, with the following content:

```
section: 1
----
title: Willesden Junction to Kew
----
company: north-and-south-western-junction
----
text: About one mile beyond [Willesden Junction](/stations/willesden-junction) we cross the Great Western…
```

`section` was not recognised. Updating it to the following (by moving `section` below `title`), it was:

```
title: Willesden Junction to Kew
----
section: 1
----
company: north-and-south-western-junction
----
text: About one mile beyond [Willesden Junction](/stations/willesden-junction) we cross the Great Western
```

Again, this only effects some pages, whereas others show the `section` value. This behaviour is not consistent nor predictable, but very disconcerting. I do not have Kirby caching enabled, and have cleared the cache in my browser. Weird… just, weird! 🤪

**Expected behavior**
Not needing to save/edit pages (i.e. saving via Panel or by reordering field values) for certain values to be recognised.

**Kirby Version**
3.0.0-beta-6.22

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser: N/A

**Comment by paulrobertlloyd** [comment]
This is an example of one of the effected files: https://github.com/bradshawsguide/content/compare/kirby-v3#diff-89af41b9f20f7e6a5af17ab2f9671c6d

It would seem that perhaps there is secret character in there causing issues… the diff doesn’t give anything away. Deleting and re-typing the effected value seems to fix it. Kirby v2 didn’t trip up on whatever this character is, however.

**Comment by REHvision** [comment]
Just guessing here but as far as I know, each field name gets saved to the content file with a capitalized first letter by the Panel (and `_` inside a field name gets converted to `-`).. So e.g. a blueprint field called `my_field` would become `My-field` in the content file. Could be that Kirby automatically reverts those field name changes and struggles if the result doesn't match?! Also the Panel always adds the empty lines (but I don't see a problem with not having those new lines)

**Comment by lukasbestle** [comment]
I just opened one of those not working files in a HEX editor and found out that the not working version has the invisible bytes `EF BB BF` (called the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark)) at the beginning of the file. Kirby 3 apparently does not trim those like Kirby 2 did. So it's actually a bug in Kirby, it should ignore/trim the BOM.

**Comment by paulrobertlloyd** [comment]
@lukasbestle Ah, I hadn’t quite realised it was always effecting the first line of a file! This bug was mainly effecting some of my older files, which may have been created with a different text editor, which could explain the presence of the different invisibles. Good to have my files use consistent BOM now, but as you can imagine dealing with invisibles, this one had me tearing my hair out! Thanks for getting to the bottom of it.

**Comment by bastianallgeier** [comment]
Argh, that was a really stupid bug. I actually had the BOM replacement line in there, but instead of double-quotes wrapped it in single quotes. It's no longer recognized like that. I should have known.
