### ISSUE TITLE
Views plugin not working

### ISSUE THREAD

**Issue by georgobermayr** [getkirby/kirby#1223]
I try to implement a custom panel view plugin (https://nnnnext.getkirby.com/docs/guide/extending-kirby/plugin-types/panel-pages). 

I tested with this code:
```
anel.plugin('test/plugin', {
  views: {
    'workflow': {
      icon: 'tag',
      label: 'Workflow',
      component: {
        template: `
          <k-view class="k-workflow-view">
            <k-headline>Test</k-headline>
          </k-view>
        `
      }
    }
  }
})
```

This creates a link in the top bar menu. However, a click on this link basically redirects to the current page while erasing the top bar content. 

Is there something wrong with my test code?

**Comment by bastianallgeier** [comment]
✅
