### ISSUE TITLE
Invalid csrf token

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1225]
**Describe the bug**
After being inactive in the panel for a while and then navigate to an other page I get the following error on every field saying: 
`Invalid csrf token`. 
If I refresh the panel I get logged out.

**Kirby Version**

3.0.0-beta-6.22

**Desktop (please complete the following information):**
 - macOS
 - Chrome
 - latest

**Comment by lukasbestle** [comment]
Have you logged in using the "keep me logged in" checkbox? If not, that's the intended behavior (well, the error message is not really optimal, but being logged out is intended). If you *did* check the box, then that error should not happen.

**Comment by H-i-red** [comment]
Aha ok cool, I would then suggest you do a nice modal with something a end user / client understands.. Otherwise we all will get a phone call from angry/crying client saying "My site is broken or hacked.."  Something like this perhaps: 

"Oh dear, you have been inactive for quite some time now, for security reasons I have logged you out, please log in again. Best regards / Your computer"

**Comment by lukasbestle** [comment]
That makes sense!

Regarding the implementation (@bastianallgeier): The Panel frontend doesn't really know when the session expires. But I guess it could display such an error once it gets a 403 response from the API (which is a pretty good sign for that) and then redirect to the login page after the user confirms the message.
If you don't want to wait two hours for the session to expire to test this, you could set the `session.durationNormal` config value to something like `10` seconds. ;)

**Comment by bastianallgeier** [comment]
I tested this and in the latest version you are being redirected to the login without the csrf token error.

**Comment by christianschley** [comment]
i had this error message a few times too. Even with beta 25 a few minutes ago but i couldnt figure out how to reproduce it yet.
