### ISSUE TITLE
Hover effect on avatar images is a bit confusing

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1226]
**Describe the bug**
When visiting a user profile in the panel, the avatar image is faded and only becomes full opaque when hovering with the mouse.

**Expected behavior**
This is not really a bug, but it is a bit confusing as it looks like the image is not displayed correctly and also does not play well with touch devices. I would reccommend to make the effect work the other way round: The avatar should be fully opaque by default and should become transparent (or even better: darkened) as the user hovers the picture.

**Screenshots**
![nov -30-2018 10-32-32](https://user-images.githubusercontent.com/395617/49280970-b63eca80-f48b-11e8-8104-713672f96dd5.gif)

**Kirby Version**
Kirby 3.0.0-beta-6.21

**Comment by sylvainjule** [comment]
I don't have this behaviour with Kirby 3.0.0-beta-6.23 on Chrome. (-> no hover effect at all)

**Comment by REHvision** [comment]
I see the same behaviour as you described in 3.0.0-beta-6.23 (Firefox btw) and I also feel that the other way around would be better (now it feels like you can click to show it bigger) :smile:

**Comment by bastianallgeier** [comment]
✅
