### ISSUE TITLE
[Panel] Users view doesn't update after changing a user's name for the first time.

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1227]
**Describe the bug**
In the 'users' page of the Panel, the view doesn't update after changing e.g. a users name.
Although it is saved (the green smilie in the top bar shows) it becomes only visible after a page reload. Not doing a reload and opening the e.g. rename dialog again shows the new name correctly in there and when saving it a second time, the view also updates. That's a little confusing.

As far as I remember, the same was the case for the site view some time ago, so it's probably a minor and should be easy to fix.

**To Reproduce**
1. Go to 'users'
2. Click on 'options' -> 'rename'
3. Click OK or press Enter
4. See user list not reflecting the changes directly
5. Repeat this without a page refresh to see it working the second time or reload the page and see the changes have in fact taken place already.

**Expected behavior**
update the 'users' view after changing a user to instantly reflect the changes.

**Kirby Version**
3.0.0-beta-6.23

**Desktop (please complete the following information):**
 - Ubuntu 17.10
 - Firefox 61

**Comment by bastianallgeier** [comment]
Hm, I can't reproduce this in 6.24.

**Comment by REHvision** [comment]
Thanks, I'll check again with the next nighlty (haven't updated yesterday) and make a screencapture if it still exists. :grin:

**Comment by REHvision** [comment]
Seems to happen in Firefox only - in Opera it doesn't :confused:

**Comment by bastianallgeier** [comment]
I'm sorry, but I can't reproduce this in Firefox either :(
