### ISSUE TITLE
[Panel] UsersFieldPreview in structure doesn't show avatars anymore

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1228]
**Describe the bug**
Since the new updated user files handling to allow more than only a single avatar, the `UserFieldPreview` doesn't show the user's avatar anymore.

It seems that this commit https://github.com/k-next/kirby/commit/177f01dd4893115cdfd967b690be1be94f361255 changed the `avatar()` function which is not using `exists()` and `url()` anymore, but the `UserFieldPreview.vue` still uses those old functions.

**To Reproduce**
1. Add a users field to a structure
2. select one or multiple users with avatar
3. no avatar is shown in the fields preview

**Screenshots**
![bildschirmfoto von 2018-11-30 16-37-26](https://user-images.githubusercontent.com/2584674/49298722-5ca3c380-f4be-11e8-8646-8843e38da711.png)

**Kirby Version**
3.0.0-beta-6.23

**Comment by bastianallgeier** [comment]
✅
