### ISSUE TITLE
Programmatically deleting drafts in hook throws error

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#1232]
**Describe the bug**
Trying to programmatically delete subpage `drafts` within a `page.changeStatus:after` hook, throws the following error: `SyntaxError: Unexpected token T in JSON at position 0`

3/5 pages get deleted, 2/5 (identical) don’t.

Here is the `config.php`

```
'page.changeStatus:after' => function ($newPage, $oldPage) {
            if($newPage->intendedTemplate() == 'project' && $newPage->status() == 'unlisted') {
                foreach($newPage->drafts() as $phase) {
                    try {
                        $phase->delete();
                        echo 'The page has been deleted';
                    } catch(Exception $e) {
                        echo $e->getMessage();
                    }
                }   
            }
        }
```

**To Reproduce**
1. Add subpages to parent page
2. Change status from `listed` to `unlisted` for parent page through the panel
3. See error

**Expected behavior**
All pages should be deleted.

**Kirby Version**
3.0.0-beta-6.22

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 70

**Comment by bastianallgeier** [comment]
There are two issues here. First you shouldn't be echoing anything as this will end up in the response and the json will be broken. 

Second: we have a bit of a problem here with a weird behavior of PHP's iterators. The $page->delete() method unsets the element from the parent collection while you are still looping through it. That way the loop will skip some elements. 

You can avoid this by looping through the original data array instead. 

```
'page.changeStatus:after' => function ($newPage, $oldPage) {
    if($newPage->intendedTemplate() == 'project' && $newPage->status() == 'unlisted') {
        foreach($newPage->drafts()->data() as $phase) {
                $phase->delete();
            }
        }   
    }
}
```

**Comment by bastianallgeier** [comment]
✅
