### ISSUE TITLE
[Panel] The default value of the user field should be the current user but stay empty

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#1234]
**Describe the bug**
Field "users": the documentation say "The default value of the user field is the current user." but the field user stay empty after creating a page. You can test with articles in the starterkit

**To Reproduce**
Steps to reproduce the behavior in the Starterkit:
1. Go to 'Blog'
2. Click on 'Add' (an article)
3. Set a title and save
4. The Users field stay empty

**Expected behavior**
The current user should be set by default as an Author (users field).

**Kirby Version**
3.0.0-beta-6.25

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Comment by bastianallgeier** [comment]
✅
