### ISSUE TITLE
Search flickers on first use / error "Nesting level too deep - recursive dependency?"

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1235]
I've noticed that when using the panel search for the first time in the morning (first time after updating Kirby?), I see a short flickering of the search results `ul`, which then disappears again. The results then only shows up again after searching once more. I checked the console when searching the first time today and saw an error pop up, which I copied and then lost – however, @nilshoerrmann checked and copied the error. Strangely enough, he didn't experience the flickering! So I'm not sure if this is really connected at all, but the error does not show up for me when searching again (and the search results load properly).

**To Reproduce**
1. Go to panel
2. Search for something (for the first time after updating Kirby? not sure about when this happens)
3. See error

**Expected behavior**
I expect the results to show up right after the search was performed.

**Kirby Version**
    3.0.0-beta-6.25

**Console output**
```
{
 “status”: “error”,
 “exception”: “Whoops\\Exception\\ErrorException”,
 “code”: 1,
 “message”: “Nesting level too deep - recursive dependency?“,
 “details”: null,
 “file”: “branchplant.k3/kirby/src/Toolkit/Collection.php”,
 “line”: 895
}
```

**Desktop**
 - macOS Mojave
 - Firefox 63.0.3

**Comment by bnomei** [comment]
@johannahoerrmann maybe this is related to rebuilding the cache of the autoid plugin. at least same error can show up then. i created an [autoid plugin issue](https://github.com/bnomei/kirby3-autoid/issues/17) so you can check the progress of that as well.

**Comment by nilshoerrmann** [comment]
We are not using autoid so it must be a Kirby thing or an more abstract plugin related issue.

**Comment by bnomei** [comment]
@nilshoerrmann thanks for letting me know. i did some testing this morning and it seems to come from `sortBy($acallback)` called on a collection. my guess is that is also called internally by the panel api somewhere, but just a guess.

**Comment by bastianallgeier** [comment]
I will close this here. @johannahoerrmann @nilshoerrmann I'm sure this is a project-specific issue that's related to the other performance issues. It would be great if we could do a private review round of the issues in your project. Let's set something up on Slack as soon as possible.

**Comment by nilshoerrmann** [comment]
That sounds good, thanks Bastian!
