### ISSUE TITLE
Search doesn't find "tête" when searching for "tete"

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1236]
**Describe the bug**
When using the panel search and searching for tete, I don't get results with "tête" part of the page title.

**To Reproduce**
1. Create a page with the title "tête"
2. Search for "tete"
3. Note missing result

**Expected behavior**
I would expect to also find phrases with accents when searching for the same phrase without accents.

**Screenshots**

<img width="519" alt="grafik" src="https://user-images.githubusercontent.com/149678/49505788-c9cba600-f87c-11e8-8ae1-e34a7f1fd676.png">

<img width="535" alt="grafik" src="https://user-images.githubusercontent.com/149678/49505781-c20c0180-f87c-11e8-8832-68203fac6b5a.png">

**Kirby Version**
    3.0.0-beta-6.25

**Desktop**
 - macOS Mojave
 - Firefox 63.0.3

**Comment by bastianallgeier** [comment]
I totally understand your point. Unfortunately this is really tricky to implement and is more like a fuzzy search. So technically it's not a bug, but "just" a strict way of searching. I would suggest to move this to the ideas list to implement a fuzzy search.

**Comment by johannahoerrmann** [comment]
Ok, will do (I also learned a new term, fuzzy search!).
