### ISSUE TITLE
Page params without value

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1238]
**Describe the bug**
A page param without a value, e. g. `tags:`, will result in the error "Undefined offset: 1" on this line:

https://github.com/k-next/kirby/blob/91ffad6f6682e89ae2ea9c44552c2a86f87ce534/src/Http/Params.php#L67

**Expected behavior**
This should not throw an error :)

**Kirby Version**
3.0.0-beta-6.25

**Comment by bastianallgeier** [comment]
✅
