### ISSUE TITLE
Panel: Prepending a number when changing URL

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#124]
After changing the url you get redirected to the new one. This breaks for zero based sorting right now because the panel is replacing the zero.

**Expected**
`/about/0-hunter-s-tomcat` change to `5-hunter-s-tomcat`
`/about/0-5-hunter-s-tomcat`
(or at least what the redirect expects)

**Currently**
`/about/0-hunter-s-tomcat` change to `5-hunter-s-tomcat`
`/about/5-hunter-s-tomcat`

The panel tries to redirect to `/about/5-hunter-s-tomcat` which leads to a missing page object error.
I'm not sure if the redirect needs be changed or the renaming of the folder in this case.

**Comment by distantnative** [comment]
Sounds like in line with several problems we have with the logic from v2, when a page title starts with a number. I'd suggest we try to find a new way, see https://github.com/k-next/starterkit/issues/89

**Comment by bastianallgeier** [comment]
This is finally a thing of the past :D
