### ISSUE TITLE
[Panel] Textarea with long text and scroll lag

### ISSUE THREAD

**Issue by meszarosrob** [getkirby/kirby#1241]
**Describe the bug**
After focusing on a textarea with long text (~20.000 chars) scrolling on the page becomes very slow

**To Reproduce**
1. Create a blueprint with a textarea (with default settings)
2. Create a page with that blueprint and add (copy-paste) aprox. 20.000 chars in it
3. Save the page
4. Reload the browser
5. Focus on the textarea
6. Wait 4secs
7. Scroll the page

**Expected behavior**
Business as usual

**Screenshots**
![image 1](https://user-images.githubusercontent.com/6097856/49590562-e0edbf00-f974-11e8-9f40-b4400382560b.png)

Seeing too many "Scroll Update" (Performance tab). Not sure if this is relevant.

**Kirby Version**
3.0.0-beta-6.26

**Console output**
No errors in the console

**Desktop (please complete the following information):**
 - Device: MacBook Pro (Retina, 13-inch, Late 2013)
 - OS: 10.14.1 (18B75)
 - Browser: Chrome
 - Version: 70.0.3538.110 (Official Build) (64-bit)

**Comment by bastianallgeier** [comment]
✅
