### ISSUE TITLE
`$user->files()` includes index.php

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1245]
**Describe the bug**
When adding a files section to a user blueprint, the section also includes the user's index.php files. The same happens when calling `$user->files()`

**To Reproduce**
1. Add files section in user blueprint
2. Open user in Panel
3. See index.php listed among all other files

**Expected behavior**
PHP files (and probably other files types) should not get listed

**Kirby Version**
3.0.0-beta-6.27

**Comment by bastianallgeier** [comment]
✅
