### ISSUE TITLE
[Panel] Arrow navigation

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1248]
**Describe the bug**
When navigating between pages using the prev and next arrows on the edit view, the Panel behaviour is confusing:

- when I'm viewing a listed page, it links to the next listed page
- but this is only true until I've reached the last listed page, then it links to the first unlisted page
- and when I'm viewing a draft, it always links to the first listed page.

**Expected behavior**
There are two desirable behaviours:

1. When coming from a grouped overview with sections for drafts, listed and unlisted pages, it makes sense to cycle inside these groups only.
2. When there is no such setup, cycling by filename might be best (listed → unlisted → drafts)

The minimum fix would be to make sure drafts navigate to the next draft first and only move to listed pages when the last draft has been reached.
Additionally, and this is the fix I'd wish for, there was a blueprint setting stating if the navigation should cycle the status group only or if it should cycle the full list of pages (something like `cycle: status|all`.

**Kirby Version**
3.0.0-beta-6.27

**Comment by bastianallgeier** [comment]
✅ I think this makes sense. I made it a lot stricter now. The navigation only happens between the same status and same template. I think this will avoid a lot more issues with pages within certain sections.
