### ISSUE TITLE
Allow setting headline buttons individually rather then just headlines in general

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1250]
Currently, you can only allow/disallow headlines, but not set individual headline numbers:

Not possible
```
buttons:
  - headlines
    - h2
    - h3
  
```

**Comment by ralfgoeke** [comment]
See also here: https://github.com/k-next/ideas/issues/131

**Comment by bastianallgeier** [comment]
I'm closing this in favor of the idea ticket
