### ISSUE TITLE
Miss aligned UI in panel for everything sortable..

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1252]
![miss](https://user-images.githubusercontent.com/19476159/49795722-0561e680-fd3b-11e8-9dd8-997b0eb65ab6.png)

3.0.0-beta-6.28
Chrome latest

**Comment by H-i-red** [comment]
Probably related to some scroll top position js stuff..

**Comment by bastianallgeier** [comment]
✅

**Comment by H-i-red** [comment]
Sorting for pages and files works now but you forgot to fix the sorting for pages and files field.

**Comment by H-i-red** [comment]
and for tags..
