### ISSUE TITLE
[Panel] uploading .svg files results in error: imagecreatefromstring(): Data is not recognized format

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1254]
When trying to upload .svg files to the panel, the panel throws an error: `imagecreatefromstring(): Data is not recognized format`

blueprint looks like this:

```
sections:
  images:
    type: files
    layout: list
    template: image
    info: "{{ file.dimensions }}"
```

This happens since updating to the latest nightly build from 2018-12-10.

![error](https://i.imgur.com/HlIxuK0.png)

**Comment by bastianallgeier** [comment]
I cannot reproduce this. Do you have any plugins installed?

**Comment by flokuek** [comment]
Yes I do, just tested it and the issue is caused by the colorextractor plugin by sylvainjule... sorry about that 🙈
