### ISSUE TITLE
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#1255]
**Describe the bug**
Detail page of a _maybe_ badly formatted svg crashes.

**To Reproduce**
1. create a files section
2. upload a svg (with some blueprint with meta fields)
3. try to navigate to the detail page of that file

**Screenshots**
<img width="640" alt="screen shot 2018-12-11 at 15 58 07" src="https://user-images.githubusercontent.com/270540/49808766-977ae680-fd5d-11e8-8e55-72999f5064f0.PNG">

**Kirby Version**
`44e42e49482d29b2ba934e7378f0b2d7b09a3122`

**HTTP Request/Response**
```
http://localhost:5000/api/pages/pagename/files/filename.svg?view=panel
```
```json
{
  "status": "error",
  "exception": "Whoops\\Exception\\ErrorException",
  "message": "simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found",
  "file": "endor\\/getkirby\\/cms\\/src\\/Image\\/Dimensions.php",
  "line": 282,
  "code": 2
}
```

ping me if you like to have the file my client uploaded.

**Comment by bastianallgeier** [comment]
✅
