### ISSUE TITLE
[Panel] Open page interaction

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1256]
The "Open" link for pages in the panel is currently marked up as `<button />` which is resulting in pop-up blockers preventing users to open the page (our clients encountered this with Safari's build-in pop-up handling). 

### Expected behaviour

The "Open" link should actually be using an `<a target="_blank" />` element. It's a link not an action. 

### Kirby version

`3.0.0-beta-6.28`

**Comment by bastianallgeier** [comment]
✅
