### ISSUE TITLE
[Panel] Page jump when closing the structure field with Esc key

### ISSUE THREAD

**Issue by meszarosrob** [getkirby/kirby#1257]
**Describe the bug**
If I close the structure field with the `Esc` it jumps to the top of the page. This is especially frustrating if the field is at the bottom of the page.

Closing it by pressing the "Cancel" button works fine (no jump).

**To Reproduce**
1. Create a structure field
2. Add a new row or edit it
3. Press `Esc` key to close the edit form state

**Expected behavior**
Closes the form without jumping to the top of the page

**Kirby Version**
3.0.0-beta-6.28

**Desktop (please complete the following information):**
- Device: MacBook Pro (Retina, 13-inch, Late 2013)
- OS: 10.14.1 (18B75)
- Browser: Chrome
- Version: 70.0.3538.110 (Official Build) (64-bit)

**Comment by distantnative** [comment]
I just tried to reproduce it, but can't with Chrome on macOS. I believe this has already been fixed up until 3.1.3-rc.1
