### ISSUE TITLE
[Panel] Formatting toolbar

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1259]
I wasn't sure, if I should post here or in the [k-next/ideas](https://github.com/k-next/ideas) repo, but I consider this an accessibility issue that actually needs fixing sooner than later.

### Describe the bug
For unexperienced users, it is totally unclear how to format text inside textarea fields because the formatting toolbar is only visible after selecting some text. Focussing the field alone doesn't help. So you _have to know already_ that selecting will trigger an interface.

### Expected behavior

I consider the flyout menu a pro feature: it's perfect for experienced writers who know Markdown well and who are often writing inside Kirby's panel. We are missing a default for normal users. In my eyes, the default should be a sticky formatting toolbar on top of the toolbar ("Microsoft Word style"). It's important that the users instantly understand that there are formatting options.

There should be a `toolbar` option with `top` as the default and `inline` as a setting for the current style.

**Comment by bastianallgeier** [comment]
✅
