### ISSUE TITLE
Favicon of the panel is squeezed

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1261]
**Describe the bug**
The hexagon shape of the current favicon is too tall and does not resemble the regular Kirby log.

**To Reproduce**
1. Open the panel in any browser that supports favicons (I tested in Firefox and Chrome).
2. Open the new Kirby beta site in another tab and compage the shapes of the 2 icons.

**Expected behavior**
Although the panel icon uses the outline version of the icon, size and shape should match the regular favicon.

**Screenshots**
![bildschirmfoto 2018-12-13 um 17 47 46](https://user-images.githubusercontent.com/395617/49953800-39860480-feff-11e8-8344-da174b66ca62.png)

**Kirby Version**
Nightly Build from December 12, 2018

**Comment by bastianallgeier** [comment]
✅
