### ISSUE TITLE
Page Model Mapping Doesn't Work When Template Name Has Periods in It (Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1263]
**Describe the bug**
In Kirby 2, if I had a template such as `/templates/home.domus.php` and a model file `/models/home.domus.php` (with `class HomeDomusPage extends Page`) the mapping would work correctly.

In Kirby 3, this does not work anymore. If you rename the files to be `home.php` and `class HomePage` then everything works.

**To Reproduce**
1. Create a template file `templates/home.domus.php`
2. Create a model file `models/home.domus.php` with `class HomeDomusPage extends Page`
3. Create a controller file `controllers/home.domus.php` with at least the `$page` parameter
4. In the controller file, do `print_r($page);` to report the class name (alternatively, you could probably just do this in the template file and avoid creating a controller file)
5. Create a content file with the template `home.domus`
6. Load the page

**Expected behavior**
The class of the page object should be `HomeDomusPage`, instead it is simply a Kirby CMS page.

**Kirby Version**
`3.0.0-beta-6.30`

**Comment by bastianallgeier** [comment]
✅
