### ISSUE TITLE
Inconsistencies in number field and float handling

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1264]
**Describe the bug**
If you are using the German translation of the number field, it displays a comma "," as decimal point. After saving the page, the field value is saved to the content file without any transformation. The panel fails to load the decimals from the German content file and just displays a rounded number after saving. If saving again, all decimals are gone from the content file and the rounded value is saved instead. This is problematic, as the english version of the same page would save a differently-formatted value, using a dot "." as separator. If a number field is used within a structure field, the field will also not show the localized decimal point in the table of entries after closing the popup.

This also leaves us with inconsistent content files across different languages and add a potential trap for template/plugin developers, if the field value is meant to be casted to float, as casting a value with a comma as thousands separator will return a rounded number (try `floatval('50.05')` vs. `floatval('50,05')`).

In addition to that, using localization features of PHP will yield different values when casting a float to string, depending on the current locale. This can lead to confusion, when the float value is used in a template for something like image coordinates in percent. On an English site, the template will work fine, but the German version will use a comma again, which will not work for e.g. `<div style="left: <?= $item->x() ?>%; top: <?= $item->y() ?>%;">` or any other scenario, where the value is meant to be machine-readable.

**To Reproduce**
1. Add a number field to any template, with `step` option < 1
2. Edit the page in any language, that does not use a dot as decimal point and save.
3. Look at the content file, the value is saved with a localized decimal point.
4. Save the same page again.
5. Look at the content file again, the field value has been rouned on second save.

**Expected behavior**
Numbers should not be rounded on load/save.

Content files should IMHO save all floats in a language-agnostic matter, using always a dot as decimal point. Or, if this is not suitable for everyone when editing content files by hand, the panel as well as the field methods like `$field->toFloat()` should be able to handle a localized float value. Anyway, I would recommend to add a field method for formatting localized versions and non-localized floats to avoid any confusion.

**Kirby Version**
Kirby 3.0.0-beta-6.30 (Nightly Build from December 12, 2018)

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
Do you handle cases like `1.234,67`, too?
