### ISSUE TITLE
[Panel] Issue when saving custom field value

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1269]
**Describe the bug + To reproduce**
I'm having a hard time debugging [this issue](https://github.com/sylvainjule/kirby-color-palette/issues/3). I don't want to make you debug my plugins but either I've missed some subtlety with the input event validation, or I wonder if there is an issue with it. The panel seems overly picky about when it saves an input or not, and I can't manage to figure out how it could see differences in the value I send (in one case saved, in the other case not).

1. Install [this plugin](https://github.com/sylvainjule/kirby-color-palette)
2. In a blueprint, copy-paste this snippet, it should work fine (value is saved).

```yaml
palette:
  label: Palette
  type: color-palette
  options:
    - '#135fdc'
    - '#f6917e'
```

3. Now simply add the `unset` option (if a color is selected, allows the user to unselect it), setting it to `true`. When clicking on a color, the save-bar still appears, so Kirby detected a change in value. But when I click on save, poof, nothing is saved at all, ever.

```yaml
palette:
  label: Palette
  type: color-palette
  unset: true
  options:
    - '#135fdc'
    - '#f6917e'
```

4. What's puzzling me is that I'm only using once the `unset` prop in my JS (aside from adding / removing a class in my markup), [here](https://github.com/sylvainjule/kirby-color-palette/blob/master/src/components/field/ColorPalette.vue#L160-L171):

```javascript
input(color = false) {
    if(color) {
        if(this.unset && this.isValue(color)) {
            this.value = this.extractor ? ['', this.extracted] : ''
        }
        else {
            this.value = this.extractor ? [color, this.extracted] : color
        }
    }
    this.$emit('input', this.value)
}
```

The only difference between having `unset: true` or `unset: false` happens in L.3 of this snippet (L.162 of the code), when checking `this.unset && this.isValue(color)` (if unset is true, and the color I  just clicked was selected => empty the value).

I could even have the exact same logic within both conditionals, it wouldn't work when `if` (unset is true, the panel never saves anything), but works when `else` (unset is false, the panel saves the color).

```javascript
input(color = false) {
    if(color) {
        if(this.unset && this.isValue(color)) {
            this.value = this.extractor ? [color, this.extracted] : color
        }
        else {
            this.value = this.extractor ? [color, this.extracted] : color
        }
    }
    this.$emit('input', this.value)
}
```

Am I missing something or is there something wrong? 👀

**Expected behavior**
Consistent saving.

**Kirby Version**
3.0.0-beta-6.32

**Console output**
None.

**Desktop (please complete the following information):**
Multi-browsers

**Comment by sylvainjule** [comment]
Duh, should have thought about it, it's the `unset` variable / name itself that is causing the issue because already used by the panel and interfering with whatever.

Could be useful though, if possible, to have a list of forbidden options names.

**Comment by distantnative** [comment]
Maybe we could even check for that list of forbidden names during the plugin registration and throw at least a console warning, @bastianallgeier? (3.0.x)
