### ISSUE TITLE
Panel: Autocomplete tag option isn't selected when clicking on it

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1271]
**Describe the bug**
When working with a tag field and options for autocomplete, the offered suggestions can't be selected to autocomplete what the user started typing using the mouse. This was brought to my attention again last week by my client. If I recall correctly, there was a discussion either here or on slack regarding this matter, but as it looked like a bug to my client and she clearly expected a different behavior, I am reporting it as such.

**To Reproduce**
1. Go to a tag field in the panel
2. Start typing
3. Click on an option
4. See that tag was not selected

**Expected behavior**
I would expect to be able to choose one of the options as my new tag by clicking on one of the offered options. (So I would expect the same behavior as when navigating down/up the list of options with arrow keys and pressing enter, which actually leads to a new tag.)

Also, when limiting the input to the query options, pressing enter could select the first offered option as no free text entries can be entered anyway (I haven't checked wether this maybe works already though).

**Screenshots**
<img width="272" alt="grafik" src="https://user-images.githubusercontent.com/149678/50079986-59614500-01eb-11e9-9421-2f43dc0ec581.png">

**Kirby Version**
3.0.0-beta-6.30

**Desktop:**
 - macOS High Sierra
 - Firefox 64

**Comment by bastianallgeier** [comment]
✅
