### ISSUE TITLE
Multiple fields with field type group not possible

### ISSUE THREAD

**Issue by thomasfahrland** [getkirby/kirby#1273]
Multiple fields with field type group in page.yml file are not possible. The last group overwrites the groups that come before in panel.

A simplified configuration to show the problem:
[page.yml.txt](https://github.com/k-next/kirby/files/2687039/page.yml.txt)

field type group:
https://github.com/k-next/kirby/blob/master/src/Cms/Blueprint.php#L465

**Comment by bastianallgeier** [comment]
✅
