### ISSUE TITLE
hasPrevVisible, hasPrevInvisible, hasNextVisible, hasNextInvisible $page Methods Missing

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1274]
**Describe the bug**
The following $page methods are all missing from Kirby 3. This seems odd, considering other "visible"-termed methods were merely deprecated (like `isVisible()`, or `$pages->visible()`).
- [x] `$page->hasPrevVisible()`
- [x] `$page->hasPrevInvisible()`
- [x] `$page->prevInvisible()`
- [x] `$page->nextInvisible()`
- [x] `$page->hasNextVisible()`
- [x] `$page->hasNextInvisible()`
- [x] `$page->nextVisible()`
- [x] `$page->nextInvisible()`

I would expect that these would just be deprecated aliases to their renamed "listed" replacements.

**Kirby Version**
`3.0.0-RC-1.0`

**Comment by bastianallgeier** [comment]
✅
