### ISSUE TITLE
Page Model Mapping Doesn't Work When Template Name Has Hyphen in It (Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1275]
**Describe the bug**
This is a follow up to a nearly identical bug relating to periods in template names: [Issue 1263](https://github.com/k-next/kirby/issues/1263)

This report is to bring attention to another regression: if a template name has a hyphen, it will not be correctly mapped to the model class name. This was handled appropriately in Kirby 2.

**To Reproduce**
1. Create a template file `templates/sport-section.php`
2. Create a model file `models/sport-section.php` with `class SportSectionPage extends Page`
3. Create a controller file `controllers/sport-section.php` with at least the `$page` parameter
4. In the controller file, do `print_r($page);` to report the class name (alternatively, you could probably just do this in the template file and avoid creating a controller file)
5. Create a content file with the template `sport-section`
6. Load the page

**Expected behavior**
The class of the page object should be `SportSectionPage`, instead it is simply a Kirby CMS page.

**Kirby Version**
`3.0.0-RC-1.0`

**Additional context**
The period/dot version of the bug was resolved with [this commit](https://github.com/k-next/kirby/commit/13c1d7c11880e3950ee3488d73cac5ff6c13322f).

**Comment by bastianallgeier** [comment]
✅ Sorry, it was stupid to miss that. I now covered dots, dashes and underscores in template names. All of those cases have unit tests.
