### ISSUE TITLE
[Panel] Login problem when session over if URL is https://mysite.com/panel/login

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#1278]
**Describe the bug**
When my session is over and try to log-in, if the url is `https://mywebsite.com/panel/login` I can't login to the panel, if I log with the url `https://mywebsite.com/panel/` or if I reload the page manually, it works.

**To Reproduce**
1. Wait the end of a session
2. Try to log in from `https://mywebsite.com/panel/login` > It redirect on the same login page
3. Try to log in from `https://mywebsite.com/panel/login` or from `https://mywebsite.com/panel/login` but previously reload the page > It works
4. If I intentionally logout from the panel and re-log in from `https://mywebsite.com/panel/login` > It works

**Expected behavior**
To be connected to the panel

**Kirby Version**
3.0.0-beta-6.32

**Console output**
If you are working with the panel, please check the browser console for errors and send the output.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser: Firefox
 - Version: 64

**Comment by bastianallgeier** [comment]
Yo are on an old beta. This has been fixed quite a while ago.
