### ISSUE TITLE
[Panel] Cache Invalidation

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1280]
**Describe the bug**
On a site with cache enabled, reordering a section will not flush the storage.

**To Reproduce**
1. enable caching
2. load the frontend
2. sort a section
3. reload the frontend
4. nothing updated

**Expected behavior**
The cache should be invalidated on sort.

**Kirby Version**
RC1

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
Thanks :)
