### ISSUE TITLE
[Panel] Focus is lost in the textarea field after opening a modal

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1282]
**Describe the bug**
Focus is lost on a textarea field after opening a modal. Either inserting a tag or canceling the modal leads to a loss of focus. I have the issue also in a plugin, seems like `this.$refs.input.focus` doesn't work / take over the dialog's closing anymore. (autofocus works, happens only when modals are involved).

**Kirby Version**
3.0.0-RC-1.2

**Desktop (please complete the following information):**
Cross-browser (latest versions)

**Comment by bastianallgeier** [comment]
✅
