### ISSUE TITLE
[Panel] Textarea buttons: Close headlines dropdown on click inside textarea

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1283]
**Describe the bug**
When the headlines dropdown in the textarea toolbar is open, it does not close automatically if I click inside the textarea. Only if I click outside the textarea.

**Expected behavior**
Close the headlines dropdown when the user clicks inside the textarea. And maybe if they start typing (?). 

**Kirby Version**
3.0.0-RC-1.2

**Comment by bastianallgeier** [comment]
✅ This will finally be fixed in 3.1.0
