### ISSUE TITLE
Unknown status types are displayed in page visibility modal

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1284]
**Describe the bug**
If an invalid key for page status is defined in a blueprint, it will shown in the modal. Once the user selects it and tries to save, the modal shows an error.

**To Reproduce**
1. Define a custom page status other than `draft`, `unlisted` and `listed` in a page blueprint.
2. Open a page with that blueprint in the panel and try to change its status.
3. Select the invalid status in the popup and try to save. An error will be thrown.

**Expected behavior**
The panel should either accept a custom status (probably not technically possible at the moment) and be able to save it. Or, the status should just be ignored by the panel and thus not show up in the modal.

**Screenshots**
![bildschirmfoto 2018-12-20 um 09 55 48](https://user-images.githubusercontent.com/395617/50274396-755c2500-043d-11e9-9ffb-73e35a2ee814.png)

**Kirby Version**
3.0.0-RC-1.2

**Comment by bastianallgeier** [comment]
✅
