### ISSUE TITLE
Custom page model for drafts not working in controller

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1285]
**Describe the bug**
Custom page model does not work in a controller when the page is in draft mode.

**To Reproduce**
1. Create a custom page model e.g. `product.php`
2. Create a controller e.g. `product.php`
3. Create a new product and keep `draft` state
3. You could now add some custom methods to the model and try to use them in the controller or change the controller to following:
```php
<?php

return function (ProductPage $page) {
    return [
        //
    ];
};
```

This will throw this Error:
```
TypeError
Argument 1 passed to Kirby\Cms\App::{closure}() must be an instance of ProductPage, instance of Kirby\Cms\Page given
```` 

**Kirby Version**
3.0.0-RC-1.2

**Additional context**
The custom page model works just fine in the template when in draft mode. But not in the controller.

**Comment by bastianallgeier** [comment]
Does your page model extend the Kirby\Cms\Page class?

**Comment by lukaskleinschmidt** [comment]
Yes it does

```php
<?php

class ProductPage extends Page
{
    …
```

**Comment by bastianallgeier** [comment]
I just tried and it works out of the box. Is that model defined in a plugin or in the models folder? If model folder:  what's the name of the file?

**Comment by lukaskleinschmidt** [comment]
It's in the models folder and is named `product.php`. The controller is also defined in the default `controllers` folder.

```php
<?php
// site/models/product.php

class ProductPage extends Page
{
    …
}
```

```php
<?php

// site/controllers/product.php

return function (ProductPage $page) {
    return [
        //
    ];
};
```

**Comment by lukaskleinschmidt** [comment]
Perhaps it has something to do with the custom folder setup. I used the devkit as a start point.

**Comment by bastianallgeier** [comment]
Hm, I tried this now with drafts as well and it works here. Could you check where `$kirby->root('models')` points to and if it's correct?

**Comment by lukaskleinschmidt** [comment]
Yes the path is correct. I also checked that the `ProductPage` extension is avialable. Really strange.

**Comment by bastianallgeier** [comment]
I have absolutely no idea to be honest :(

**Comment by bastianallgeier** [comment]
Could you try if you run into the same thing in the starterkit?

**Comment by lukaskleinschmidt** [comment]
Yeah will try to figure out what is going wrong. Will ping you here when I find something.

**Comment by bastianallgeier** [comment]
I will close this for now. That's just for me to keep a clear head. Feel free to reopen as soon as you run into it again.

**Comment by lukaskleinschmidt** [comment]
@bastianallgeier I think I found the error. 

https://github.com/k-next/kirby/blob/master/src/Cms/HasChildren.php#L104

In a multilang Enviroment the `inventory` method gets called without the important `$mulilang = true` value. Thats why it worked fine on a singel langugage install.

**Comment by bastianallgeier** [comment]
Oh wow, good catch! I just fixed it. Damn multilang stuff :)
