### ISSUE TITLE
[Panel] User settings: Wrong language code is displayed after user language change

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1288]
**Describe the bug**
When I change the user language in the user settings page, the language info next to the user profile image displays the wrong language code.

**To Reproduce**
1. Open the user settings for a user.
2. Change the language

**Expected behavior**
Display the correct language string. 
Maybe display the actual language name instead of just the language code...

**Screenshots**
![vid](https://user-images.githubusercontent.com/15672385/50288732-05fb2b00-0467-11e9-8433-c10294af29df.gif)

**Additional Information**
I disabled
```
  'panel' => [
    'language' => 'de'
  ]
```
in the config.php, but it does not seem to make a difference.

**Kirby Version**
3.0.0-RC-1.2

**Comment by SebastianEberlein** [comment]
Also this happens sometimes:
- Original user language: German
- Change to English
- Reload page: User Interface is now in German again
- Reload page again: User Interface is now in English

**Comment by bastianallgeier** [comment]
Ugh, I cannot reproduce any of this. This is also Chrome, right?

**Comment by SebastianEberlein** [comment]
Yes, Chrome. But also Safari and Firefox. 

To be sure it’s not just my Kirby installation, I upload the RC1 starterkit to our webserver: The language display bug still occurs.

**Comment by bastianallgeier** [comment]
Could you let me know if you still run into the issue with RC2?

**Comment by SebastianEberlein** [comment]
Yes, still happens with RC2. To be extra sure, I disabled any Adblocker and used a different internet connection.

I can also reproduce the issue by changing the user language in the user list view – via the context menu – and then opening the user page.

But if I then go back to the user list and now open the user page again, the language code is displayed correctly.

**Comment by bastianallgeier** [comment]
Is it possible that your localstorage is blocked somehow?

**Comment by SebastianEberlein** [comment]
No, when I make changes to any field, I can see in the dev tools that the localstorage shows a key value pair.

I looked at the fetch request for the user data after I changed the user language: It shows the old language value. (Although the cache is disabled in the dev tools.)

But: I just tested the RC2 starterkit with the built-in PHP server, as described [here](https://nnnnext.getkirby.com/docs/guide/installation-and-updates/requirements#using-php-s-built-in-server). And it works as expected.

So both my local vagrant machine and our webserver seem to cause the problem.

**Comment by SebastianEberlein** [comment]
I just tested it on a different Apache webserver, that has been setup just a few days ago: It works as expected.

Our webserver uses Apache 2 with nginx reverse proxy. My vagrant machine just uses Apache 2.

**Comment by bastianallgeier** [comment]
Seeing more users having similar caching issues and you describing that it works on a different server setup makes me think that it might have something to do with server side caching. Could you check if you have some heavy caching activated?

**Comment by SebastianEberlein** [comment]
My vagrant environment has indeed OPcache enabled. If I set `php_flag opcache.enable Off` in my .htaccess, the language is displayed correctly :)

But I do not know if it is a good idea to disable OPcache performance-wise...

**Comment by SebastianEberlein** [comment]
Setting `php_value opcache.revalidate_freq 0` in my .htaccess also solves the issue. 

The default value is 2. Setting it to 1 does not solve the issue.

**Comment by bastianallgeier** [comment]
Ok, that's at least a fix. We had problems with opcache in v2 as well. It's often too aggressive and doesn't update the response properly.

**Comment by bastianallgeier** [comment]
I'm closing this for now and we will add a note to our troubleshooting guide
