### ISSUE TITLE
[Panel] Date field should only store a time value that can be selected through the UI

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1289]
**Describe the bug**
When selecting a day in a date field with `time: true`, the current time will be saved without rounding minutes to the values which are actually available for selection.

**To Reproduce**
1. Create a new page, where the blueprint has date field wich `time: true`,
2. Select a day at any time (e.g. 17:21) where the actual value for minutes is not selectable from the UI.
3. The date/time picker will show the closest possible option (e.g. 17:20), but the panel will save the odd time (e.g. 17:21).

**Expected behavior**
The panel should round the current time to a value that can actually be selected through the UI, unless the `step` option of the time field is set to `1`. In that case, no rounding is needed.

**Kirby Version**
3.0.0-RC-1.2

**Comment by bastianallgeier** [comment]
✅
