### ISSUE TITLE
Routing documentation update

### ISSUE THREAD

**Issue by Denney** [getkirby/kirby#129]
I've been racking my brain trying to figure out why calling the image Kirby tag via code wasn't working as expected. In my routes I followed the documentation for returning a page.

This can cause some issues as it doesn't set the site page properly. Even though the `$page` object is correct for the template, it's being set to the homepage for a call to the Kirby tag. I found I needed to return a call to `site()->visit('some/page')` rather than `page('some/page')` in my route in order to get it to work as expected.

Maybe an update to the documentation might be appropriate for this?

**Comment by bastianallgeier** [comment]
I moved this to the site issues: https://github.com/getkirby/getkirby.com/issues/146

**Comment by bastianallgeier** [comment]
This will be fixed in the next release and the visit method is no longer required.
