### ISSUE TITLE
(file: ...) tag doesn't work in files

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1293]
**Describe the bug**
The `(file: ....)` kirbytag doesn't work when used inside a text of another file. 

**To Reproduce**
1. Upload 2 files to a page
2. In the metadata of one file link to the other with `(file: otherfile.pdf)`
3. Render this field with `kirbytext()`

**Expected behavior**
Since both files are in the same folder, I would expect this to work without prefixing the file path. (a bit like relative html links)

**Kirby Version**
RC2

**Additional context**
It works when prefixing the file with its path: 
```
(file: my/page/uid/otherfile.pdf)
```

`Kirby\Cms\KirbyTag::file()` could check if `$parent` is a File, and in that case search for the file also in the file's `page`. Something like this:

```diff
    public function file(string $path): ?File
    {
        $parent = $this->parent();

        if (method_exists($parent, 'file') === true && $file = $parent->file($path)) {
            return $file;
        }

+       if (method_exists($parent, 'page') === true && $file = $parent->page()->file($path)) {
+          return $file;
+       }

        return $this->kirby()->file($path, null, true);
    }
```

**Comment by bastianallgeier** [comment]
✅
