### ISSUE TITLE
[Panel] Unable to query blueprints from an extended page section

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1294]
**Describe the bug**
Not a bug exactly, but currently it isn't possible to extend the pages section without rewriting the call made to get the allowed blueprints for subpages, on `create`.
This is the culprit: https://github.com/k-next/kirby/blob/0d24600687e74ed74a9005e80d8ac740400c420b/src/Cms/Site.php#L184

If the condition is needed, could it be made slightly less restrictive? `$section->type()` starts with "page", for example?

```php
if ($section === null || strpos($section->type(), 'page') !== 0) {
  ...
```

**Comment by bastianallgeier** [comment]
I made it a lot less strict. Basically any section type can now define a list of blueprints, that is allowed.

**Comment by sylvainjule** [comment]
Great, thank you!
