### ISSUE TITLE
$pages->not() does not work with collections anymore

### ISSUE THREAD

**Issue by pju-** [getkirby/kirby#1295]
**Describe the bug**
I try to exclude a collection from another collection. In Kirby 2 this was possible from 2.3 upwards:
`$collection1->not($collection2)`
The result is not filtered though. From the source it seems that filtering is only possible by ids now.

**Expected behavior**
The collection should still be filtered according to the docs:
https://nnnnext.getkirby.com/docs/cheatsheet/pages/not
If this is merely an issue with the docs and the functionality really should be gone, this should be a ticket for the docs instead I guess.

**Kirby Version**
RC 1

// edit:
Maybe worth mentioning that there is an easy solution with a bit more complicated syntax so it's not really needed?
`$collection1->not(...$collection2->keys())`

**Comment by bastianallgeier** [comment]
✅ This will land in RC 3 tomorrow.
