### ISSUE TITLE
Response component was removed, what's its replacement?

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1296]
In commit https://github.com/k-next/kirby/commit/caa8cc4f3ddd416c07ca250f77bdcee4d204450f#diff-8d7c29e18533835c1d1e67c54773591c (new response config), the `response` component was removed.

How would I now modify the response from a plugin (e.g. to minify the output)? Also we need to document this as the response component is still in the cheat sheet.

**Comment by bastianallgeier** [comment]
Let's remove it from the docs for now. I think we need a better way to do this in general. It was often misused to compress the output but do that uncached and there was no good way to cache it at all. So I think it needs to be done on page render before the page cache kicks in, but we should probably introduce a hook for that. (page.render:before / page.render:after) and then document it properly.
