### ISSUE TITLE
Panel creates "duplicate"  servername in url when using Browsersync

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1299]
**Describe the bug**
The URL in the Panel when using Browsersync looks like this: http://localhost:3000/localhost:3000/panel/site

On frontend, it is ok.

**To Reproduce**
1. Start up Browsersync
2. Open Panel at the address shown
3. See the duplicate URL

**Kirby Version**
RC3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bvdputte** [comment]
Putting this in the config works around the issue:

```php
return [
  'url' => '/'
];
```

**Comment by bastianallgeier** [comment]
This one has really been nasty to find. Browsersync removes the scheme from the URL for some reason. The base URL for the panel is added to the panel dom with the base tag to make Vue's router work. But when the base url starts like `//localhost:3000` the router thinks it's a path and not a full URL. In that case the path will be added again. 

This sucks, but by removing the host and double leading slash from the base url, the router is happy and everything seems to work fine.
