### ISSUE TITLE
Panel: Download does not download

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#13]
When clicking download on files, it does not download the file. Instead it's loaded in the browser.

I think a header or something is often used to force files to be downloaded.

In the case the files are are not downloaded, at least not the SVG file I tried. I think "Raw" is a better name for it, in case you are **not** making a force download.

**Comment by bastianallgeier** [comment]
Well, this is very much a naming problem at the moment. I think it's better to actually try opening file links in a new tab/window and let the browser decide if it can preview the file or force a download. So the behavior is intended, but the Download label is indeed misleading. What would be a better option? "Show", "Preview", "Open"?

**Comment by jenstornell** [comment]
If you don't like "Raw", I think "Open" is the best word for it. I'm not sure if the icon needs to be changed or not, but I would be fine with a change like below (Open):

![image](https://user-images.githubusercontent.com/927011/32234082-3134be5a-be5c-11e7-8aab-7ff817edff12.png)

**Comment by bastianallgeier** [comment]
I renamed it to open. I agree that it is a bit more easy to understand.
