### ISSUE TITLE
Core: Don't created page folders with random folder name

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#130]
This is an idea, a personal opinion.

When I watched the latest livestream, a part of it was about how to create new pages. If no `slug` was added as parameter, it would take the `title` and make it a `slug` which then becomes the folder name. I think that's fine. It's probably what most people expect.

If `title` and `slug` are **not** added as params, the a page folder is still created, but this time by a random name.

**There are a few reasons why I don't like this approach:**

1. If I by mistake forget to add `title` or `slug`, I will still get a successful created page, which can be a false positive because I would expect an error. Instead I get a page with a random folder name which I probably don't want.
1. If I by mistake forget to add `title` or `slug` and have an infinity loop it could be a disaster. It would create unlimited new random page folders. It would not collide and therefor continue to create more pages.
1. I've never seen a question in the forum about how to create randomly named pages by a function.
1. A very minor issue is that a random name could collide with an already existing page. The chance is really small but exist.
1. The most important of all, if I forget `title` and `slug`, what do I expect? I don't expect to be sucessful and I don't expect a random named page folder to be created. I expect it to throw an error.

So this random folder creation is too much magic for my taste and not something I would expect. If anyone ever needs a random page folder name it's easy to use `rand` in combination with `md5` or similar.

One thing I like about Kirby is the feeling of complete control. Features like random page folder names make me feel less in control.

Maybe you feel different about it, but that's my opinion anyway. =)

**Comment by jenstornell** [comment]
What did the outcome be of this issue? A change or not?

**Comment by bastianallgeier** [comment]
Sorry for closing it without comments. We don’t do it. No pages with random folder names :)
