### ISSUE TITLE
[Panel] Textarea-toolbar not working properly Safari and Firefox

### ISSUE THREAD

**Issue by littlemermaidfromthesea** [getkirby/kirby#1302]
**Bug**
The buttons of the toolbar attached to the textarea field is not working as expected. Whenever the toolbar is in its sticky position, the buttons don't work.

**To reproduce**
Use textarea field.

**Expected behavior**
Buttons should work.

**Kirby Version**
RC3

**Desktop**
 - OS: macOS
 - Browser: Safari (v12) and Firefox (v64)
Chrome is ok.

**Comment by sylvainjule** [comment]
Had the issue on the markdown field as well. `@blur` gets triggered before `@click`. 

But since `@mousedown` is triggered before `@blur`, adding `@mousedown.prevent` on every element triggering a click fixes it. ([found here](https://forum.vuejs.org/t/blur-before-click-only-on-safari/21598/6))

**Comment by bastianallgeier** [comment]
✅
