### ISSUE TITLE
Unable to load SQLite database from location outside of public folder

### ISSUE THREAD

**Issue by paulrobertlloyd** [getkirby/kirby#1303]
**Describe the bug**
I am attempting to load a database stored outside of my public folder.

**Steps to reproduce**
If I use the following config:

```php
'db' => [
    'type' => 'sqlite',
    'database' => 'site.db'
]
```

the database is loaded from my public folder, which is located at `./www/`. However, I want to store my database in my content folder, with is located at `./src/content/`. It was suggested by @bastianallgeier that I use `$kirby->root('content').'/site.db'`, but as `$kirby` is not recognised as a variable within my configuration file, I tried this:

```php
'db' => [
    'type' => 'sqlite',
    'database' => kirby()->root('content').'/site.db'
]
```

But the debugger reports `SQLSTATE[HY000] [14] unable to open database file`. Interestingly, if I use

```php
'db' => [
    'type' => 'sqlite',
    'database' => kirby()->root('content').'site.db' # Note the missing slash
]
```

a file called `contentsite.db` is created in the root directory. This would suggest that `kirby()->root('content')` resolves to `.content` when it should be `./src/content`.

**Kirby Version**
Kirby 3.0.0-RC-3.0, using a composer-based installation.

**Additional context**
You can view my site's directory layout here: <https://github.com/bradshawsguide/website/tree/kirby-v3>. [This is my index.php](https://github.com/bradshawsguide/website/blob/kirby-v3/www/index.php) where my roots have been set.

**Comment by bastianallgeier** [comment]
Well, that's more a problem of Kirby not being fully initialized when you setup the configuration. What happens when you go relatively from your config file? Something like. 

```php
'db' => [
    'type' => 'sqlite',
    'database' => __DIR__ . '/../../content/site.db'
]
```

**Comment by paulrobertlloyd** [comment]
Ah ah! I used `'/../content/site.db'` which worked! Might this need adding to the documentation?

**Comment by bastianallgeier** [comment]
I added a docs issue to the getkirby.com repo.

**Comment by paulrobertlloyd** [comment]
Fantastic. Thanks @bastianallgeier!
