### ISSUE TITLE
isChildOf() method results in an error

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1304]
**Describe the bug**
When using **isChildOf()** method results in an error: _Argument 1 passed to Kirby\Cms\Page::isChildOf() must be an instance of Kirby\Cms\Page, string given, called in_
 
**To Reproduce**
Followed the instruction from the docs
https://nnnnext.getkirby.com/docs/cheatsheet/page/is-child-of

```
<?php if($page->isChildOf('some-parent-page')): ?>
This page is a child of it's parent!
<?php endif ?>
```

**Kirby Version**
3.3.3 or RC3

**Comment by texnixe** [comment]
Isn't this rather a bug in the documentation? If not, and if a string should be possible as argument, that would affect other methods of the `isXX()` category as well?

**Comment by bastianallgeier** [comment]
✅ I fixed this for all those kind of checks
