### ISSUE TITLE
[Panel] Pages field preview doesn't show page title

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1305]
**Describe the bug**
In a structure field, the pages field preview doesn't show the page title. The preview wants to display a [`{{ page.title }}`](https://github.com/k-next/kirby/blob/fdd86f4398379671ebfa42c592a9e030424d02eb/panel/src/ui/components/Forms/Previews/PagesFieldPreview.vue#L8) while the given props has it stored under `{{ page.text }}`.

**Kirby Version**
3.0.0-RC-3.0

**Comment by bastianallgeier** [comment]
✅
