### ISSUE TITLE
[Panel] min/max between pages sections with same parent

### ISSUE THREAD

**Issue by Wemago** [getkirby/kirby#1306]
Using max / min it isn't inherit/read when using pages with sections.

Using starterkit
- Albums.yml add max: 5
- On Home panel "add" disappears (correct behavior)
- On Photography panel drafts still haves "add" action, if you add an album then change status it is added to published albums even with the limit to max 5, 

Using the min / max limits should restrict the user from adding more or using this "workaround" to get more entries.

Version: 3.0.0-RC-3.0

**Comment by texnixe** [comment]
Good catch, but this is a tricky one, I think.

**Comment by Wemago** [comment]
Was thinking about this and I think that isn't hard to fix this.

I don't know anything about Vue.js but I think that to solve this we should count the number of entries of any status (in the collection?) on page load then decide to show add action depending on Min / Max config.

I've noticed that when you don't split entries by section status the Min / Max works as it should. 
Example is in the home panel, it shows all entries of all status and it disables the action button according to the min / max config.

**Edit:** Why not use the same technique used by _Limit_ config? From what I see it as to do in how sections are build up, it will count the $pages variable that is set on config/sections/pages instead of counting everything or am I wrong? I'm also new to Kirby. Good Job BTW :)

**Comment by Wemago** [comment]
Another approach to this would be to disable _Change Status_  depending on the _Min / Max_ config, this way user can add unlimited drafts  but wont be able to change the status for those drafts.

**Comment by bastianallgeier** [comment]
I think we should solve this kind of min/max issue on the individual blueprint level. Every type of page should be able to define how many of them can exist in a folder. Then we can easily check that in the backend. But this needs some more thought and we won't be able to fix this for 3.0

**Comment by Wemago** [comment]
@bastianallgeier that won't solve it because you are already setting it at an individual blueprint. I've been trying to debug this but I'm always coming back to the sections. 

In K2 we do 
```
- pages: 
-- max: 5 
```

Now in K3 you need at least one section, and with only one it works perfect, but if you want to use all the power of K3 you'll split those by status to have better organization.
```
- sections:
-- draft:
--- type: pages
--- status: draft
-- listed:
--- type: pages
--- status: listed
```

Maybe adding another option before sections like
```
- entries:
-- max: 5
- sections:
```
Then before injecting the actions buttons do some calculation like site.find('notes').count and substract from the entries max option.

A small hack that could work right now is doing an dynamic blueprint and calculating before setting the limit to drafts using something like $pages->find('note')->children()->count() (from K2, don't know if we have this in K3).

**Comment by distantnative** [comment]
We won't be able to solve this in Kirby 3, but noted it as an aspect to consider for future developments after that.
