### ISSUE TITLE
t('translation') not working

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#1307]
https://nnnnext.getkirby.com/docs/guide/languages/custom-language-variables#using-language-variables-in-your-template
Custom translations are not working in my setup.
I set translations with an array inside my translation config file like in the doc.

**To Reproduce**

1. Go to 'languages/en.php'
2. Setup translations with 'translations' => ['test' => 'Test']
3. Try echo t('test') 
4. See nothing

**Kirby Version**
RC3

**Comment by sylvainjule** [comment]
To help narrowing it down: seems it can be caused by plugins, see https://github.com/sylvainjule/kirby-markdown-field/issues/44

**Comment by bastianallgeier** [comment]
@tristantbg do you also use @sylvainjule's markdown field? It's happening with the plugin because kirby()->root() is used before Kirby is fully initialized.

**Comment by tristantbg** [comment]
@bastianallgeier No I am not using this plugin and I search for `kirby()->root()` in all my plugin folder and found no occurrence
<img width="320" alt="capture d ecran 2019-01-07 a 16 14 07" src="https://user-images.githubusercontent.com/4832038/50775760-5a8c0c00-1297-11e9-9c1d-b9d6fb7a3590.png">

**Comment by bastianallgeier** [comment]
Which plugins do you use? It can be caused by different scenarios.

**Comment by sylvainjule** [comment]
Oh, crap. Used it in:

- Pagetable
- Imageradio
- Imageboxes
- Markdown field

I'm switching to relative paths.

**Comment by johannschopplich** [comment]
@sylvainjule So it was the plugin after all. 😉❤️

**Comment by sylvainjule** [comment]
I don't know what you mean 😶
Fixed them all.

**Comment by bastianallgeier** [comment]
👍

**Comment by tristantbg** [comment]
> Which plugins do you use? It can be caused by different scenarios.

Indeed, it works when I remove all the plugins...
Here are the plugins used :
https://github.com/tristantbg/ccs_kirby/tree/master/www/site/plugins

**Comment by tristantbg** [comment]
> Which plugins do you use? It can be caused by different scenarios.

It seems to be caused by one of mine... :(

https://github.com/tristantbg/kirby3-imgx

**Comment by tristantbg** [comment]
@bastianallgeier Any idea why this really simple plugin breaks the translation t('')?
https://github.com/tristantbg/kirby3-imgx

Many thanks for your expertise.

**Comment by bastianallgeier** [comment]
@tristantbg yes, the option() method here: https://github.com/tristantbg/kirby3-imgx/blob/master/lib/imgx.php#L7 is loading Kirby's options while Kirby is not initialized yet. The plugin definition with Kirby::plugin() is running before Kirby's instance is ready. This means that if you make a call to something that depends on the Kirby instance in your plugin definition, you create a second instance that is getting in the way of the actual installation.

**Comment by fabianmichael** [comment]
@bastianallgeier Is there any way to get around this? I also need to read some options in one of my plugins at the time the plugin’s config.php is executed.

**Comment by texnixe** [comment]
Looks like this problem keeps surfacing. I think we need a solution or workaround to be able to do things that need Kirby, like the paths, the user roles etc.
https://forum.getkirby.com/t/user-permisions-for-specific-page-and-its-subpages/12943/15

**Comment by distantnative** [comment]
@texnixe have you tried it with the current develop branch. We hoped to fix it

**Comment by texnixe** [comment]
@distantnative Oh, right, completely missed that. Yes, that works with my code snippet and the translation.
