### ISSUE TITLE
[Panel] Textarea in structure field: Spaces are deleted on save.

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/kirby#1308]
**Describe the bug**
(Indenting) spaces (or tabs) at the beginning or the end of a line are deleted on save in textareas within structure fields.

If the textarea is not within a structure field spaces are preserved.

I have this structure field.
```yaml
webComponents:
  type: structure
  fields:
    html:
      label: HTML
      type: textarea
      buttons: false
```

This is my input:
```
<div class="text-box">
  <div class="text-box__heading">
    <h2>Headline</h2>
  </div>
  <div class="text-box__content">
    {{ Content }}
  </div>
</div>
```

This is how it’s saved (`default.txt`)
```text
----

Webcomponents: 

- 
  html: |
    <div class="text-box">
    <div class="text-box__heading">
    <h2>Headline</h2>
    </div>
    <div class="text-box__content">
    {{ Content }}
    </div>
    </div>
```
**Expected behavior**
It should be saved like this:
```txt
----

Webcomponents: 

- 
  html: |
    <div class="text-box">
      <div class="text-box__heading">
        <h2>Headline</h2>
      </div>
      <div class="text-box__content">
        {{ Content }}
      </div>
    </div>
```

**Kirby Version**
3.0.0-RC-3.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.0.2

**Comment by tobiasfabian** [comment]
I did some research and found out that this is a ['bug'](https://github.com/mustangostang/spyc/issues/54) in [spyc](https://github.com/mustangostang/spyc).

[symfony/yaml](https://github.com/symfony/yaml) could be an alternative.

**Comment by jenstornell** [comment]
Or maybe have as a component. Then it can be replaced by any library.

**Comment by bastianallgeier** [comment]
I worked with symfony/yaml at the beginning of v3 and it had many other issues because of being a lot more strict that spyc.

**Comment by Wemago** [comment]
Have you seen / tried [Dipper](https://github.com/secondparty/dipper) ?
The only problem is that it isn't maintained for a while.

**Comment by TimOetting** [comment]
I give a +1 for this one. I have the same problem when I have a textarea inside a block of my [Kirby Builder](https://github.com/TimOetting/kirby-builder) plugin. I am sure that this is related. 

I would like to use the Kirby Builder for different segments in my pages that also contain code samples. Because of this bug these code samples lose their indentation 😕

**Comment by mwheys** [comment]
Just ran into this issue too. Occurs in both textarea and [Markdown](https://github.com/sylvainjule/kirby-markdown-field) fields when they're set as children of structure or Builder fields.

**Comment by webresourcech** [comment]
Same issue here! Glad to see it's on the road for milestone 3.4.0 :-)

**Comment by afbora** [comment]
- **Spyc** supports YAML 1.0
 - **Symfony Yaml Component** supports  YAML 1.2

Since the issue was opened, Symfony Yaml component 2 major (3.x - 4.x) and more than 50 minor versions have been published. I find it worth looking again 👍

**Comment by afbora** [comment]
I've tried the Symfony Yaml component on 3.2.5 instead of Spyc, this issue (spaces are deleted on save) doesn't exist there, it works just fine. Overall I didn't see a problem either. Unit tests can not pass for now, but some parts need to be refactor.

**Comment by bastianallgeier** [comment]
@afbora I agree! Let's keep it for 3.4.0 though. The first RC for 3.3.0 is planned for Tuesday and I don't want to rush this.

**Comment by distantnative** [comment]
Unsolvable with our current library.

Closing this in favor of https://github.com/getkirby/kirby/issues/2452

**Comment by distantnative** [comment]
Reopening this due to unsuccessful attempt at https://github.com/getkirby/kirby/pull/2453#issuecomment-648087004
