### ISSUE TITLE
$pages->findOpen() Method Missing

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1309]
**Describe the bug**
The `$pages->findOpen()` method from [Kirby 2](https://getkirby.com/docs/cheatsheet/pages/find-open) is not present on Kirby 3.

```
$page->children()->findOpen()
```

**Kirby Version**
`3.0.0-RC-3.0`

**Additional context**
The workaround is very simple, but slightly annoying to change if migrating a Kirby 3 site:
```
$page->children()->findBy('isOpen', true)
```

**Comment by bastianallgeier** [comment]
✅
