### ISSUE TITLE
Panel: SimpleMDE as textarea engine?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#131]
I've always been impressed by https://simplemde.com, the markdown editor. To add some great features without pain and time effort, maybe use that instead of your own?

It can be styled and bent to your needs. A great example of this is the https://github.com/medienbaecker/kirby-simplemde. It looks just like the Kirby textarea field that we know.

![](https://user-images.githubusercontent.com/7975568/33186314-de426910-d088-11e7-914a-10e874fd0cef.gif)

Screenshot from https://github.com/medienbaecker/kirby-enhanced-textarea/issues/23

**The advantages I like about SimpleMDE are:**

- The text is formatted. Bold text will be bold, italic will be italic, headlines will be big, code will be styled etc.
- Enter press in lists and quotes will add a new item and double enter will jump out of it, just like Microsoft Word.
- It counts words and lines.
- To get a headline you press the headline icon, To get an h2, press it again. For h3, press again. A clever solution. After h6 it will jump out of it.

**Comment by bastianallgeier** [comment]
It looks nice on first sight, but as with most WYSIWYG has some major downsides. It's based on CodeMirror, which is pretty solid, but also a huge monster. The mobile support is also really not very good.

**Comment by bastianallgeier** [comment]
I'm afraid I have to close this.
