### ISSUE TITLE
$pagination->nextPageURL() Ignores Custom Site Index URL

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1312]
**Describe the bug**
The URLs returned by a pagination object's `nextPageURL()` (and presumably `prevPageURL()`) do not respect a site's custom index URL.

```
$kirby = new Kirby([
    'urls' => [
        'index' => 'https://example.com',
    ],
]);
echo $kirby->render();
```

**To Reproduce**
1. Configure the Kirby object in the public `index.php` to resemble the above
2. Inspect the `nextPageURL()` of some paginated page

**Expected behavior**
The URL should resemble `
https://example.com/news/page:2`. 
Instead the custom URL is completely ignored and resembles `
http://localhost:8080/news/page:2`.

**Screenshots**

**Kirby Version**
`3.0.0-RC-3.0`

**Comment by bastianallgeier** [comment]
✅
