### ISSUE TITLE
template() returns always 'default' template

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1313]
**Describe the bug**
When I try to fetch all listed children of a page and then call the template() method on each listed subpage it always returns the blueprint name **default** even when every child has its own different blueprint. If i do the same procedure with **$site** it works perfectly.

**To Reproduce**
Doesn't work (always returns _default_)
```
<?php foreach ($page->children()->listed() as $p): ?>
  <?= $p->template() ?>">
<?php endforeach ?>
```

Works:
```
<?php foreach ($site->children()->listed() as $p): ?>
  <?= $p->template() ?>">
<?php endforeach ?>
```

**Kirby Version**
RC3

**Comment by texnixe** [comment]
I can't reproduce this in a Starterkit. Do the pages really have a template (not blueprint)? If they don't have their own template, you have to use `intendedTemplate()`.

**Comment by flokuek** [comment]
In my case I'm using the one-pager example which came in an older starterkit (alpha 11). So the subpages don't have a template. 

```
<?php foreach ($page->children()->listed() as $section): ?>
  <section class="section <?= $section->template() ?>">
    <?php snippet(str_replace("one-pager-", "one-pager/", $section->template()), ['section' => $section]) ?>
  </section>
<?php endforeach ?>
```

All

**Comment by texnixe** [comment]
As I said, if the subpages do not have a template, then `template()` will always return `default`. this is normal behavior.

If you put your loop from the first post into a current Starterkit (e.g. the `notes` template, the loop will return `note` correctly for each subpage, because the template exists. This is the method. As you can see, it checks if the intended template exists, if not, it returns the default template.

```
    public function template()
    {
        if ($this->template !== null) {
            return $this->template;
        }

        $intended = $this->intendedTemplate();

        if ($intended->exists() === true) {
            return $this->template = $intended;
        }

        return $this->template = $this->kirby()->template('default');
    }
```

**Comment by flokuek** [comment]
Sorry for the confusion ... it's working now.
