### ISSUE TITLE
KirbyTags No Longer Handle Omitting Initial Value (Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1321]
**Describe the bug**
When using a custom KirbyTag in K2, I could omit the "initial" parameter but have additional parameters that controlled other things. This acted as a convenient "default" value.

For example, consider this full example:
```
(test-tag: foo extra: 1)
```

and an abbreviated version:
```
(test-tag: extra: 1)
```

However, in Kirby 3, this no longer gets parsed correctly. In the abbreviated version, "extra" gets consumed as the "value" and not as the start of an attribute.

**To Reproduce**
1. Create a custom tag that has at least one additional parameter. See below for an example.
2. In a field that will be parsed as KirbyText, add the KirbyTag but omit the initial value but include an additional attribute.

**Expected behavior**
Omitting the initial value should be permitted. I would expect `$tag->value()` to simply return an empty string.

**Kirby Version**
`3.0.0-RC-4.0`

**Additional context**
Here's an example tag that matches the examples above.
```
Kirby::plugin('debugging/test-tag-example', [
    'tags' => [
        'test-tag' => [
            'attr' => [
                'extra',
            ],
            'html' => function($tag) {
                return $tag->value() . "\n" . print_r($tag->attrs(), true);
            },
        ],
    ],
]);
```

`(test-tag: foo extra: 1)`
```
foo
Array
(
[extra] => 1
)
```

`(test-tag: extra: 1)`
```
extra <-- this implies that "extra" has been absorbed as the value, rather than an attribute
Array
(
[0] =>
)
```

**Comment by lukasbestle** [comment]
I think this behavior was never documented and was actually a bug in the old implementation.

The advantage of the new implementation is that the first attribute (the `value`) can now contain colons if not proceeded by an attr name.

Do you have an example for a tag where omitting the first value makes sense?

**Comment by bastianallgeier** [comment]
I think it really is a regression to be honest @lukasbestle. I saw this as well in our link tag when you used it without adding a href, which is a nice shortcut to link to the homepage. I will fix this.

**Comment by lukasbestle** [comment]
Fair point, but the old implementation is quite buggy. If you find a way to do it in an elegant way with the new implementation, that‘s great! Let me know in case I can help you with anything.

**Comment by neildaniels** [comment]
Just to add some more use-case context, our site uses this behavior extensively for three different purposes:
- When we want to include something like a `(buy-block:)` that outputs the HTML that has a "buy" or "sign up" button (and pulls in a link form a panel field).
   - When used without an initial value, it's implied that it should be a buy-block for the current page/product. If an initial value is provided, it's to specific _which_ product the buy block should be used for (used in other places on the site).
- When the tag itself has many options, but none of them really make sense to be the "initial" parameter (and it doesn't really make sense to have separate tags, because you can mix and match parameters).
 - When the tag itself needs no "initial configuration" (such as showing a list of featured articles), and an extra parameter like "columns" would be confusing to make the initial parameter.

**Comment by bastianallgeier** [comment]
@lukasbestle I have to say that I ran into way more issues with the new way of parsing the tags. None of the attributes can be blank, which is not ideal in my opinion. I went back to the old way. I think it's better for the launch to keep it like this.
