### ISSUE TITLE
[Panel] System check does not show reason, config folder check missing.

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1322]
**Describe the bug**
The system check is done whenever a user loads the panel. If the check fails, the panel currently does not give any useful information about how to resolve the issue(s). Tested while debug mode was active.

In addition, the `site/config` folder is not checked for write permissions when the general system check is done, which causes the license registration to fail if that folder is not writable.

**To Reproduce**
1. Make sure that any system folder (e.g. `site/accounts`) is not writable by PHP
2. Go to the panel
3. A modal will show up, saysing `t.requirements is undefined`
4. Make that system folder writable again and remove write permissions on `site/config`
5. Open the panel, it should work now, despite that the config folder is not writable.
6. Try to register the Kirby instance; enter Email and license key and submit. The modal will display an error, that the `site/config/.license` is not writable. This check should also be part of the general system check. 

**Screenshot**
![bildschirmfoto 2019-01-08 um 17 05 20](https://user-images.githubusercontent.com/395617/50842803-c5a51380-1367-11e9-986a-613b01493298.png)

**Kirby Version**
3.0.0-RC4

**Console output**
```
TypeError: "t.requirements is undefined"
	fh https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/app.js:1:203716
	_render https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:31806
	r https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:18747
	get https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:21359
	run https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:22099
	on https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:20309
	pe https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:12152
	ae https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:39:11493
	a https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:28:16551
	D https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:28:16701
	u https://www.mylittlekirby.test/media/panel/79cd7ebcad0629a1600bc22ad89744f6/js/vendor.js:28:32134
 app.js:formatted:16601
```

**Comment by bastianallgeier** [comment]
✅
