### ISSUE TITLE
(link: ) KirbyTag Does Not Support popup Attribute

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1323]
**Describe the bug**
The `(link: )` tag does not support `popup: ` anymore. This still exists in the [documentation](https://nnnnext.getkirby.com/docs/reference/kirbytags/link) though.

**To Reproduce**
1. Include something like `(link: http://wikipedia.org text: Wikipedia popup: yes)` in a text field
2. Echo it out as KirbyText

**Expected behavior**
I would expect the K2 behavior to remain, where it adds the `target="_blank". I think the K2 version also stuck on `rel="noopener"` and maybe `noreferrer` (but I would actually override it to _not_ add `noreferrer` because we wanted referrer traffic to be known).

Currently, K3 assumes that `popup: yes` is part of the text.

**Kirby Version**
`3.0.0-RC-4.0`

**Additional context**
K2 was somewhat forgiving with the exact value of `popup`, accepting `yes`, `true`, and `1`.

**Comment by texnixe** [comment]
True, the examples were probably taken from K2, the attribute itself was removed. It was a duplicate of the `target: _blank` attribute, anyway. The question is if we want to reintroduce it for compatibility's sake or get rid of it.

**Comment by bastianallgeier** [comment]
The popup attribute was introduced for less techie users instead of defining a target. I'm not sure if we should bring it back or not to be honest.

**Comment by texnixe** [comment]
I always found it irritating to have two attributes for the same thing. Also, `target: _blank` should probably be an exception rather than the rule, anyway.

**Comment by neildaniels** [comment]
Totally fair point to avoid having nearly duplicate tags. I haven't tried doing this in Kirby 3 yet, but I'll try to override the existing link tag anyways, so if you decide not to add it back in, I'll just add support myself. (In K2, I overrode the link tag for other reasons anyways.)

I will say, I think it's _much_ more intuitive to writers/authors that making a link open in a new window is `popup: yes` then `target: _blank`.

It's probably worth mentioning in the upgrade notes though if it doesn't remain, otherwise this ends up being a "breaking"/annoying content change.

**Comment by bastianallgeier** [comment]
I think we'll launch without the popup duplicate. It's really easy to fix this if you want to:

```php
<?php

Kirby::plugin('my/popup-link', [
    'tags' => [
        'link' => [
            'attr' => [
                'class',
                'rel',
                'role',
                'target',
                'title',
                'text',
                'popup,
            ],
            'html' => function ($tag) {
                if (V::accepted($tag->popup)) {
                    $tag->target = '_blank';
                }
                
                return Html::a($tag->value, $tag->text, [
                    'rel'    => $tag->rel,
                    'class'  => $tag->class,
                    'role'   => $tag->role,
                    'title'  => $tag->title,
                    'target' => $tag->target,
                ]);
            }
        ],
    ]    
]);
```

If there's massive feedback, we can still bring it back later.
