### ISSUE TITLE
[Panel] Cannot interact with files containing a space

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1324]
**Describe the bug**
We have a section containing images. There is one file with a space in the filename which cannot be opened or interacted with using the context menu.

![bildschirmfoto am 2019-01-09 um 11 30 11](https://user-images.githubusercontent.com/25466/50893898-457fbc00-1402-11e9-9a0d-6f8ddd1b8ed7.png)

(The first one, in case you don't see the space.)

The panel displays and throws this error:

```json
{
  "status": "error",
  "message": "not found",
  "code": 404
}
```

**To Reproduce**
I'm actually not sure, if this file was uploaded using the panel or was manually added to the server. But adding a space should to an existing file should do the trick.

**Expected behavior**
Kirby should find files even with a space in the name.

**Kirby Version**
3.0.0-RC-4.1

**Additional context**
Occured on macOS using Firefox and Safari. Haven't tested any other browsers but this seems to be server related somehow or other.

**Comment by bastianallgeier** [comment]
✅
