### ISSUE TITLE
Panel: Cannot navigate to next/previous in drafts

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1325]
**Describe the bug**
Looking at a page in the panel set to the status "draft", I cannot navigate to the next or previous draft page as the arrow navigation is disabled.

**Expected behavior**
I expect to navigate between these pages just like I can in listed or unlisted pages.

**Screenshots**

<img width="659" alt="grafik" src="https://user-images.githubusercontent.com/149678/50896592-c098a080-1409-11e9-97ed-c9a29bcf64a4.png">

**Kirby Version**
3.0.0-RC-3.0

**Desktop (please complete the following information):**
 - macOS Mojave
 - Firefox 64

**Comment by bastianallgeier** [comment]
✅
