### ISSUE TITLE
[Panel] Pages field loading issues

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1326]
So, we have a site with around 180 public project pages, each containing at least one image. There are also other pages referencing projects, like awards or news. In order to establish these links, we use pages fields in different pages. 

Here is the issue (you guessed it already): 
**selecting related projects is _reeeaaalllly sllllooooow_.** 😭

This is due to the time it takes the panel to display the pages dialog after clicking the `Select` button which might take up to 5 or more seconds to show up.

### What can we do?

Is there anything we can do to speed-up page fetching? Or the other way around: is there anything we should not do in order to not slow down the process?

### What can Kirby do?

Besides being faster at fetching pages in general, there are a few things that would help:

1. Show the dialog immediatelly after clicking `Select` because otherwise there is no indication of panel activity.
2. Kirby should display some kind of loading spinner inside the dialog.
3. Content should be loaded asynchronously, starting with the first 20 pages or so, either chaining the others or fetching them on scroll.
4. Display page content first, load images later.
5. Simplify the page preview markup. I'm actually not sure, if the figure-figcaption relation used here is semantically correct in most situations. 

*Important:* Please don't add a manual pagination to the dialog (page 1 of x)! We noticed during this project how much pagination distracts and irritates users. This is a list and should be a list.

**Comment by johannahoerrmann** [comment]
@bastianallgeier Any help on this? The time it takes to load after clicking is really crazy, I just took the time – 13 seconds! Is there anything we can/shouldn't do to make this better?

**Comment by nilshoerrmann** [comment]
Any news on this?

**Comment by bastianallgeier** [comment]
See my other comment about a private review session.
