### ISSUE TITLE
Accepted mime types are not passed on to extending blueprints

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1327]
**Describe the bug**
It seems that accepted mime types are not passed on to blueprints that extend the original blueprint, hence allowing other file types to be uploaded. We have different file blueprints in our setup, `image.yml` as the main blueprint and `cover.yml` (amongst others) featuring `extends: files/image`.

In `image.yml`, we defined:

```
title: Image
accept:
  mime: image/jpeg, image/png
columns:
  - width: 2/3
    sections:
      info:
        type: fields
        fields:
[…]
```

We reuse this blueprint in other blueprints, such as `cover.yml`, which looks like this:

```
title: Cover
extends: files/image
```

However, I just noticed that I can upload other file types such as gif, pdf and svg as e. g. my cover image. This was totally unexpected – am I missing some logic here? I read up on reusing blueprints in the docs and noticed that reusing file blueprints isn't even mentioned, and also stumbled upon this issue https://github.com/k-next/kirby/issues/1277 – I guess this is a similar case?

**Expected behavior**
I would expect the acceptions to be passed on to extending blueprints.

**Kirby Version**
3.0.0-RC-4.1

**Desktop (please complete the following information):**
- OS Mojave
- Firefox 64

**Comment by bastianallgeier** [comment]
✅
