### ISSUE TITLE
[Panel] Small css bug on headline false

### ISSUE THREAD

**Issue by Wemago** [getkirby/kirby#1328]
Action buttons goes over lists

**To Reproduce**
Set in the blueprint headline to false

**Expected behavior**
Setting the headline to false the margins should be kept to list group.

**Screenshots**
![action_add_error](https://user-images.githubusercontent.com/135612/50902271-f178d580-1409-11e9-93f4-d14e3390c760.jpg)

**Kirby Version**
3.0.0-RC-3.0

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox
 - Version 60.3

**Comment by bastianallgeier** [comment]
✅
