### ISSUE TITLE
[Panel] Structure form buttons overflow field in narrow column widths

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1329]
**Screenshots**
Structure field in a 1/3 column:

<img width="432" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/50906801-327ee300-1426-11e9-945f-7b7f98463ddb.png">

Maybe just hide the structure pagination for 1/3 and 1/4 widths?

**Kirby Version**
3.0.0-RC-4.0

**Comment by bastianallgeier** [comment]
I applied a minor fix, which avoids the ugly wrapping of the pagination details, but there are still issues with such small structure fields. I think I need a more global approach to style narrow fields and sections without element queries, which is a bit tricky. I will take care of it for 3.1
