### ISSUE TITLE
The Register button in the toolbar seems to use the wrong font

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1330]
**Describe the bug**

The `Register` button in the toolbar seems to use the wrong font in Windows (it's set by the "user agent stylesheet" to "Arial").

**To Reproduce**
1. On Windows, open the panel in a not registered installation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6684137/50928743-c4eda980-145b-11e9-87ff-c6d2d9e225f5.png)

**Kirby Version**
RC4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 71

**Comment by bastianallgeier** [comment]
✅
