### ISSUE TITLE
[Panel] Problem with accentuations

### ISSUE THREAD

**Issue by starckio** [getkirby/kirby#1332]
The emphasis does not work in the panel.
yes > title: Note
no > title: Noté

Error returned:
The string did not match the expected pattern.

<img width="358" alt="capture d ecran 2019-01-10 a 00 48 22" src="https://user-images.githubusercontent.com/875858/50936804-7519dd00-1471-11e9-8546-9eb39e9be765.png">

**Comment by bastianallgeier** [comment]
Where does this happen exactly?

**Comment by bastianallgeier** [comment]
I'm closing this because I can't find where this is happening.
