### ISSUE TITLE
Finding Page By URI Fails With Trailing Slash (/)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1333]
**Describe the bug**
Attempting to get a Page object by URI and a trailing slash returns null, but this used to be allowed on Kirby 2.

- `kirby()->site()->find('guides/')`
- `site()->find('guides/')`
- `page('guides/')`

**To Reproduce**
1. In a template file, attempt to access a Page model by using one of the methods listed above, adding a slash `/`

**Expected behavior**
I would expect that the lookup methods ignore a trailing slash, as this was the Kirby 2 behavior. If this intentional, seems like a worthy note in the upgrade docs.

**Kirby Version**
`3.0.0-RC-4.1`

**Comment by bastianallgeier** [comment]
✅
