### ISSUE TITLE
Files field with dash in name isn't saved

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/kirby#1334]
On 3.0.0-RC-4.1:

If I have a hyphen in the blueprint property name of my files field, the content isn't saved.

I could live with the restriction of no dashes allowed in field names, but then the panel should throw an error.

**Comment by texnixe** [comment]
Dashes are not allowed in yaml field names

**Comment by philipmarnef** [comment]
My bad. Checked this on another field but made a dumb mistake getting a false positive.

I now remember this has bit me before and the reason is mostly that a) I have a hard time finding anything about this in the official spec and b) there are plenty of bad examples on the web with hyphens in their keys.

Maybe an idea to make a note in the docs in the blueprints section, I'm guessing I'm not the last to make that mistake.

**Comment by texnixe** [comment]
Yes, it's in the old docs: https://getkirby.com/docs/panel/blueprints/form-fields#field-names

But missing from the new, I'll make a note.
