### ISSUE TITLE
Panel: Cursor in textarea dissapears after dropping an image

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1335]
**Describe the bug**
After I drag and drop an image file to a textarea, the cursor dissapears. Everything still works, but the cursor only reappears after either focussing a different field and then clicking back into the textarea or saving the page.

**To Reproduce**
1. Drag image file into textarea

**Expected behavior**
I would expect the cursor to stay visible.

**Screenshots**
After dropping:

<img width="200" alt="grafik" src="https://user-images.githubusercontent.com/149678/50964026-965ce680-14ce-11e9-8229-98127c305784.png">

After saving the page:

<img width="95" alt="grafik" src="https://user-images.githubusercontent.com/149678/50964058-ab397a00-14ce-11e9-9da0-d18a88af9400.png">

**Kirby Version**
3.0.0-RC-4.1

**Console output**
No errors.

**Desktop (please complete the following information):**
 - macOS Mojave
 - Firefox 64

**Comment by bastianallgeier** [comment]
Duplicate: https://github.com/k-next/kirby/issues/1184

**Comment by johannahoerrmann** [comment]
(Sorry 'bout this!)

**Comment by bastianallgeier** [comment]
No problem :)
