### ISSUE TITLE
prevPageURL() and nextPageUrl() returns the Url without the site name

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1338]
**Describe the bug**
The URLs returned by the pagination object's `nextPageURL()` and `prevPageURL()` do not include the sites name

**To Reproduce**
```
<?php if($pagination->hasPrevPage()): ?>
    <a href="<?= $pagination->prevPageUrl() ?>">
        prev
    </a>
<?php endif ?>
```

```
<?php if($pagination->hasNextPage()): ?>
    <a href="<?= $pagination->nextPageUrl() ?>">
        next
    </a>
<?php endif ?>
```

**Expected behavior**
The URL should be `http://localhost/starterkit/notes/page;2`
Instead the site name is missing inside the URL `http://localhost/notes/page;2` .

**Kirby Version**
`RC4` tested with a clean starterkit

**Comment by bastianallgeier** [comment]
✅ Could you please give it a try after tonight's RC and let me know if it's really fixed for you?

**Comment by flokuek** [comment]
Of course 👍

**Comment by flokuek** [comment]
It works 👍
