### ISSUE TITLE
Trying to override the `drafts()` method in a page model results in blank page

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1346]
**Describe the bug**
While overriding `children()` or `draftsAndChildren()` seems to work fine, as soon as I add a `drafts()` method to the model, the Panel (or the frontend) go blank with an Internal Server error.

**To Reproduce**
1. Create a page model, e.g. notes.php
2. Inside, create a drafts() method that just returns the parent's drafts
3. Open the Panel (or the frontend)

Don't know if this is a bug or just not possible to override this method (but shouldn't it be).

Tested with RC-5.

**Comment by bastianallgeier** [comment]
That's very specific. Let's check this out some more after the launch.

**Comment by texnixe** [comment]
@bastianallgeier Yes, that's what I thought at first, but wouldn't we have to override drafts for content from other sources as well?

**Comment by bastianallgeier** [comment]
How did you implement this? With `$this->parent()->drafts()`? This could already be the problem. The top level pages don't have a parent and that would throw an error and the panel could not be loaded at all.

**Comment by bastianallgeier** [comment]
I just tried with this code: 

```php
<?php

use Kirby\Cms\Pages;

class PhotographyPage extends Page
{
    public function drafts(): Pages
    {
        return new Pages();
    }
}
```

which works fine. But this kind of stuff can break a lot if not implemented right. We need to document such extensions step by step.

**Comment by texnixe** [comment]
Yes, your code works for me as well, even with the filter:

```
<?php 

use Kirby\CMS\Pages;

class NotesPage extends Page {
  
  public function drafts(): Pages
  {
    return parent::drafts()->filter(function($child) {
      if($user = kirby()->user()) {
        return $child->author()->toUser() === $user;
      }        
    });
  }
}
```

**Comment by texnixe** [comment]
@bastianallgeier I assume the above code should generally be applied when overriding these methods, also to the `children()` method etc., even if it doesn't throw an error if done otherwise?

**Comment by bastianallgeier** [comment]
I just removed the Pages return type in the core. It's not really needed and makes more problems here. But when you overwrite the drafts and children methods you have to be aware that Kirby uses this methods internally as well when creating new pages and checking for duplicates etc. So when you overwrite them and you expect the panel to work properly there might be surprises.
