### ISSUE TITLE
[Panel] Files field does not update when file gets deleted in files section

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1347]
**Describe the bug**
When a file selected in a files field gets deleted in the files section, the files field is not updated.

**Kirby Version**
Kirby 3 - RC5

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari

**Comment by bastianallgeier** [comment]
Too risky to fix for 3.0

**Comment by distantnative** [comment]
Totally agree. Issue was intended for later.

**Comment by bastianallgeier** [comment]
✅
