### ISSUE TITLE
Bug with connected Database since RC 4.0

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1348]
bastian posted an example with an connected database recently and its documented here: https://nnnnext.getkirby.com/docs/cookbook/database/pages-from-database

It worked all fine until RC 4.0.

Now there is the following error, because the SQL class accesses a member variable of the database class that can not be accessed

![access protected variable](https://user-images.githubusercontent.com/25037153/51074499-31e18900-1680-11e9-9559-3af1f36d8e12.png)
![protected access code](https://user-images.githubusercontent.com/25037153/51074501-3443e300-1680-11e9-9df2-eb0c926b2ea5.png)

Additional info:

The error happens in a function with the Following comment

`/**
  * Returns a list of tables for a specified database
  * MySQL version
  *
  * @return array
*/`

**Comment by bastianallgeier** [comment]
✅

**Comment by christianschley** [comment]
I'm sorry, the error still exists. i guess you need to edit src/Database/Sql.php in line 699 as well @bastianallgeier

**Comment by bastianallgeier** [comment]
Argh, sorry! I should have added tests yesterday. I fixed it now. Can you confirm with the latest version from master?

**Comment by christianschley** [comment]
Thanks! Yes, issue can be closed now
