### ISSUE TITLE
`toFiles()` method doesn't work with files from other pages

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1350]
The `toFiles()` method only searches for files in the field's parent object. That kind of defeats the purpose of querying files from other pages in the files field.

**Comment by bastianallgeier** [comment]
✅

**Comment by samyouel** [comment]
Sorry to reopen an old thread, but the same thing seems to appear for the `$page->files()` method. Files from fields of this page where the `query:` parameter is set to get files from other pages and a file from another page is selected, won't get returned.
That obviously makes it difficult to receive expected returns...

Or am I missing something...?

**Comment by distantnative** [comment]
The `$page->files()` method always returns all the files from the page itself. It has nothing to do with any fields or what files in a field have been selected.

**Comment by samyouel** [comment]
Right, so more on a Filesystem level? That makes sense. Sad - I thought I could somehow query that.

I created a question in the forum for my specific use case, as it probably hasn't got anything to do with this issue anymore... https://forum.getkirby.com/t/get-files-of-page-that-come-from-other-pages/33744

**Comment by distantnative** [comment]
Yes, all the files of that page = all the files in the page's content folder. Or if you see it from the Panel perspective: all files that were uploaded to this page.
