### ISSUE TITLE
Html::a() Tag Handles rel=noopener in Odd Way (Compared to K2)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1352]
**Describe the bug**
The currently implementation of Html::a() appends `rel="noopener noreferrer"` to every link that opens in a new window, regardless of what `rel` value is set.

If I explicitly set that I want `noopener`, in Kirby 2, that implied that I **did not** want `noreferrer` (which is correct). K2 would only append this automatic rel tag if rel was empty.

Now, it naively makes the full rel tag `noopener noopener noreferrer`, which is silly.

**To Reproduce**
1. Put `(link: https://www.example.com text: Test target: _blank rel: noopener)` in a Kirbytext field
2. Parse Kirbytext 

**Expected behavior**
The tag should resemble:
```
<a href="https://www.example.com" target="_blank" rel="noopener">Test</a>
```

**Kirby Version**
`3.0.0-RC-6.0`

**Additional context**
Our website absolutely needs to to keep referrer information, so I need to work-around Kirby's automatic behavior. The analytics benefit of referrer information greatly outweighs the purported security benefit for ancient browsers. (The `noopener` is totally fine and completely expected.)

**Comment by bastianallgeier** [comment]
✅
