### ISSUE TITLE
Thumbnails are not created in frontend

### ISSUE THREAD

**Issue by caplod** [getkirby/kirby#1355]
**Describe the bug**
thumbnails are not created in frontend, even after reload.

**To Reproduce**
1. Download latest starterkit
2. Start with 'php -S localhost:3001
3. Goto http://localhost:3001
4. No thumbs/images on page

**Expected behavior**
thumbs are rendered

**Screenshots**
![no-thumbs](https://user-images.githubusercontent.com/435070/51164268-b7418500-189c-11e9-97d0-686b2e9e3fdf.png)

**Kirby Version**
- Kirby 3.0.0-RC-6.0

**Desktop:**
 - OS:  macOS Hight Sierra
 - Browser Chrome
 - PHP 7.1.16

**Comment by bastianallgeier** [comment]
We don't recommend PHP's build in server anymore. It's just such a pain in the ass to get regular things running with it. But if you want to use it you have to use our router script in kirby/router.php

**Comment by timpulver** [comment]
Would be good to give a recommendation then (in README.md). I was wondering about this exact same problem as well.
`php -S` was always the easiest method to work with Kirby so far for me.

_Edit_: See [thread in Kirby forum](https://forum.getkirby.com/t/webserver-recommendation-for-local-development-mac/12143).
