### ISSUE TITLE
Panel: Open link leads to /null when page has not fully loaded

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1356]
**Describe the bug**
The "open" link leads to `/null` when the page has not yet fully loaded.

**To Reproduce**
1. Go to a slow-loading page in panel
2. Click on the open link immediately

**Expected behavior**
I would expect the open link to lead to the main directory.

**Kirby Version**
3.0.0-RC-4.1

**Desktop (please complete the following information):**
 - macOS Mojave
 - Firefox 64
 - Safari 12.0.2

**Comment by distantnative** [comment]
Since the page isn't fully loaded, the actual link target is probably not yet available either.
What we could do then is block interaction until the page has fully loaded. But that doesn't sound ideal either.

**Comment by nilshoerrmann** [comment]
If I remember correctly, "not fully loaded" means: everything is there but there is one pages section still fetching its data. I'd expect this to happen asynchronously. So why is it blocking interactions with other areas of the main interface?

**Comment by johannahoerrmann** [comment]
The point during loading I'm talking about looks like this:

<img width="1573" alt="grafik" src="https://user-images.githubusercontent.com/149678/51466653-fa9f6600-1d6a-11e9-9f06-cd1fb6fb6af6.png">

**Comment by bastianallgeier** [comment]
I think this should be solved now.
