### ISSUE TITLE
Lack of info regarding kirby v2

### ISSUE THREAD

**Issue by mogelbrod** [getkirby/kirby#1358]
Our website depends on `getkirby/kirby` and `getkirby/panel` via git submodules. We discovered the release of kirby v3 only by finding out that our deployments stoppped working since these repositories no longer seem to exist. The `kirby` repo appears to have been replaced by this new v3 repo, with no traces of v2 commits. By luck we found https://github.com/getkirby-v2, but there doesn't appear to exist any info regarding this or a migration path going forward.

**Comment by texnixe** [comment]
We will soon post something, I have to close this here because it's not K3 related. Sorry for the inconvenience.

**Comment by trentm** [comment]
We hit this as well, fwiw. The symptom, for our case, looks like this:

```
$ git submodule update --init --recursive
error: Server does not allow request for unadvertised object a2678c41c7f57ef176651e257840861d6c21b653
Fetched in submodule path 'htdocs/kirby', but it did not contain a2678c41c7f57ef176651e257840861d6c21b653. Direct fetching of that commit failed.
```

**Comment by levrik** [comment]
@texnixe Really? Our deployment is broken, this is a paid product, and there is no info at all about v2. Installation via `composer` fails due to replaced repos.

**Comment by mogelbrod** [comment]
Here's the updates I've found regarding this so far:
- https://forum.getkirby.com/t/kirby-3-is-here-faqs-and-more/12309
- https://getkirby.com/v3

For the kirby devs: You probably want to add a link to this thread somewhere visible (kirby v3 readme, the website, github, etc.). I found it on Twitter, which I'd argue isn't the first place most people look.

**Comment by lukasbestle** [comment]
Sorry for the inconvenience. Replacing the `getkirby` repos with Kirby 3 wasn't a good idea in hindsight. We should have created separate `getkirby-v3` repos instead. But unfortunately we didn't anticipate this issue.

@levrik You can find all the Kirby 2 repositories at https://github.com/getkirby-v2. If you replace `getkirby` with `getkirby-v2` in your setup, it should work properly again.

**Edit:** Installation with Composer should actually still work as we have updated the Packagist packages with the new repo URLs.
