### ISSUE TITLE
Different border colours for panel fields

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#1359]
While exploring the new panel I saw a difference in the border colours used for fields.

If you, for example, navigate to /panel/pages/about and check the borders, you will see that the textarea, the input fields and structure field all have different shades of grey. The structure field comes with a box shadow that the other fields don't have.

I see this behaviour in Kirby 3.0.0.

I'm running Kirby in Chrome 71 on Mac OS High Sierra 10.13.6

Other than that congratulations for the update! I can't wait to finally start with two new client projects!

**Comment by distantnative** [comment]
My eyes might be not as great, but to clarify: The only difference is between the structure field and all other fields, right? All other fields share the same (except the structure field).

**Comment by bastianallgeier** [comment]
All fields share the same border color. The structure field has no border, which has been a conscious design decision to clarify that it's not an input but an overview of the contained data. It uses the same drop shadow that is also used by our list item and card components.
