### ISSUE TITLE
switching tab/site in panel results in hidden tab content

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#1361]
**Description**
Switching between site and tab/content results in hidden content page. It seems to be a update problem when u switch between tabs and site content.reloading the page manual fix the problem. see mov/yml in attachment.

**To Reproduce**
1. Load site.yml in your project (site.yml in attachment)
2. Login panel
3. Content of tab Dashboard is visible
4. Click Tab (Dashboard) - > content not visible
5. Click Tab (Einstellungen)
6. Click Tab (Dashboard) -> content visible
7. Same problem when switching from "menubar" icon to tab (video in attachment)

**Screenshots**
<img width="835" alt="a" src="https://user-images.githubusercontent.com/5121132/51253773-92820600-199f-11e9-9216-55fa640a5205.png">
<img width="845" alt="b" src="https://user-images.githubusercontent.com/5121132/51253774-92820600-199f-11e9-982e-d8e725f0ecf5.png">
 
**Kirby Version**
3.0.0-RC-5.0
 
**Desktop (please complete the following information):**
 - OS:Mojave 10.14
 - Chrome: Version 71.0.3578.98 (Offizieller Build) (64-Bit)
 - Server: Vagrant / Scrotchbox, php 7.2 
 
**Attachment**
[files.zip](https://github.com/getkirby/kirby/files/2764446/files.zip)

**Comment by distantnative** [comment]
Please update to the 3.0 (non-RC). This should have been fixed.

**Comment by findthebug** [comment]
problem with tabs also exists on 3.0

**Comment by bastianallgeier** [comment]
@findthebug did you try to delete media/panel and clean the browser cache? I'm pretty sure this should be fixed and I cannot reproduce it here either.

**Comment by findthebug** [comment]
i can reproduce this in safari, chrome and firefox in the starterkit with the provided site.yml. also tested this in MAMP, and custom vagrant installation. cleared all, caches etc...

maybe there is a bug/missconfiguration in the blueprint?

**Comment by bastianallgeier** [comment]
Could you provide the blueprint you used?

**Comment by findthebug** [comment]
[site.yml.zip](https://github.com/getkirby/kirby/files/2803626/site.yml.zip)

**Comment by bastianallgeier** [comment]
Ok, I finally found it and was able to fix it :) Thank you for your help!
