### ISSUE TITLE
`page()` Method No Longer Works with Content Representation Extensions

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1362]
**Describe the bug**
In Kirby 2, the `page()`/`site()->page()` methods would return the expected Page model if a content-representation file extension was appended to the given path.

For example, I have `sitemap.php` and `sitemap.xml.php` template files, with a content file located at `/content/sitemap/sitemap.txt`. Thus, the URLs `/sitemap` and `/sitemap.xml` are accessible URLs.

In Kirby 2, calling `page('sitemap.xml')` would return the Page model for `sitemap`, which was expected. In Kirby 3, `page('sitemap.xml')` returns `null`.

**To Reproduce**
1. Create an additional content representation (such as `.xml`) for an existing template
2. Attempt to fetch the Page model for that extension-suffixed version

**Expected behavior**
I would expect the Page model to be returned.

**Kirby Version**
`3.0.0`

**Additional context**
This specifically came up from an existing route I had in place, that needed to consult a property of a Page model to decide what to do.

Here's is a minimal example that demonstrates the issue when trying to access the `sitemap.xml` version of the page (it goes to an error page).

```php
    [
        'pattern' => '(:all)',
        'action' => function($uri) {
            echo 'uri: [ ' . $uri . ' ]';
            
            $page = page($uri);
            if (!$page) {
                $page = site()->errorPage();
            }
            return site()->visit($page);
        }
    ],
```

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch and will be in the 3.0.3 pre-release tomorrow.
