### ISSUE TITLE
k-draggable events not working

### ISSUE THREAD

**Issue by TimOetting** [getkirby/kirby#1365]
**Describe the bug**
There are currently two problems with the k-draggable component:
- The callback that is triggered by the @start event does not receive an event object as expected
- The :move property does not work at all. According to the Vue.Draggable, this property acts just like an event: https://github.com/SortableJS/Vue.Draggable#move

**To Reproduce**
inside my component
```html
<k-draggable
  @start="onStart"
  :move="onMove"
>
  <li>one</li>
  <li>two</li>
  <li>three</li>
</k-draggable>
```
inside my component's methods block
```javascript
...
onStart(event) {
  console.log(event) // -> undefined
},
onMove(event) {
  console.log(event) // -> never called
}
...

```
**Expected behavior**
- The onStart event parameter should exist. See https://github.com/SortableJS/Vue.Draggable#events
-  The :move property should be handles just like an event. See https://github.com/SortableJS/Vue.Draggable#move

**Kirby Version**
Worked in 3.0.0-beta-6.32, does not work anymore in 3.0.0

**Desktop:**
 - OS: macOS
 - Browser Chrome

**Additional context**
I need this to work for the (Kirby Builder Plugin)[https://github.com/TimOetting/kirby-builder]. I found a workaround for the start event problem, but the missing :move event support breaks the preview when dragging.

**Comment by lukaskleinschmidt** [comment]
You need to use the `@move="onMove"` syntax to attach a event properly. But the `move` event does not exist at all. The `sort` event is the way to go here `@sort="onSort"`.

The missing event data in the `start` (and `end`) events should be fixed by the [PR](https://github.com/lukaskleinschmidt/kirby/commit/ec8ac67705dbb51cecc74453267f1ab517068a54).

**Comment by TimOetting** [comment]
The onMove event exists in the SortableJS library and is - why ever - mapped in Vue.Draggable by the :move property, not the @move event. 

The kirby docs say that the draggable component is just a wrapper for Vue.Draggable and references to the Vue.Draggable docs. It should therefore behave just like Vue.Draggable and support the :move event/prop/whatever you call it. Also, this move event is not the same like the sort event. Unfortunately the sort event does not work in my case.

Also, I can not hand over the list model via v-model anymore. I have to use the :list property instead. This is another case where the k-draggable component behaviour differs from the Vue.Draggable API:

```
// this does does not work anymore
<k-draggable v-model="myList">
  <li>one</li>
  <li>two</li>
  <li>three</li>
</k-draggable>
```
