### ISSUE TITLE
Structure Field 'Min' Option Ignored

### ISSUE THREAD

**Issue by luxlogica** [getkirby/kirby#1368]
**Describe the bug**
Adding `min` option to a structure field has no effect on the interface

**To Reproduce**
1. Setup a structure field and add a `min` option - e.g., `min: 1`
2. In the Panel, start adding entries to your structure field
3. As you reach the `min` number of entries, the delete buttons stay on screen, and you can delete entries, below the minimum number required - ie., `min` is ignored.

**Expected behavior**
It would be expected that once `min` is reached, the delete buttons next to each entry would be hidden.

**Kirby Version**
3 - first official release

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari, Chrome, Firefox
 - Version: latest

**Comment by texnixe** [comment]
Hm, I can reproduce the issue with the `min` button but not with the `max` button which works for me.

**Comment by luxlogica** [comment]
You are right, @texnixe: I was getting an issue with `max` because of browser caching. The issue is only with `min`. Updated the report to reflect that 👍

**Comment by distantnative** [comment]
I have to disagree with the expected behavior.
If you would do this, then you are stuck with the first x entries added. You should always be able to remove those, add others. Only on save it should of course fail if the minimum is not set.

**Comment by luxlogica** [comment]
@distantnative - sorry, but you are absolutely wrong here. There are several situations when you don't want the user to delete something, AT ALL. That is the whole purpose of having a 'minimum' setting. Right now, the system works based on the principle that the user should ALWAYS be able to delete, and that is a VERY MAJOR flaw. There is also no way to stop it from happening programatically - not that I know, but would be very happy to be shown otherwise.

### Use-Case 1
I have a carousel on the site, which requires the user to have at least 3 images. If the user doesn't have at least 3 items, the layout will fail. The section cannot be removed from the page, otherwise the entire page layout will fail. So, the best option would be to set a 'min: 3' on the structure field that collects the data for the carousel images (+ captions, + call-to-action defaults, etc.). Right now, that's not possible, and the user will be able to save a page with 0 images - so we have to add lots of extra code for checking, as well as default images, default settings, etc., for when nothing is entered.

### Use-Case 2
The structure field is used to represent "related products". Each products must have *at least* 2 other 'related products'. Because we cannot set a 'min' that works, we have to allow for 1 or 0 'related products'. Client's staff - who enters data into the site - is lazy, so now they almost NEVER enter 'related products'. Client's sales are down. Client not happy.

### Use-Case 3
Structure field is used to represent 'sections' in a Landing Page. Client should be able to add several sections, if they want, but there has to be at least ONE - ie., 'min: 1'. Because 'min' is not respected, we have to add a 'default section' if none was created - not an elegant solution, which means a page can be published with 'default' info -which will always be invalid, incorrect, and often depends on the client checking the live website to notice.

All of these (and more) could be avoided quite simply, if the system did what it's expected to do: a validity check on the 'min' requirement.

As far as whether the check should be done *only* on 'save', again, I think it's more helpful if the setting is respected at **all times**. The client should always be able to CHANGE the information to whatever they want, but if there is a REQUIREMENT that the information *should* be there, then the interface should always be present - and the client should not be allowed to delete the interface at will.

**Comment by distantnative** [comment]
@bastianallgeier your opinion is needed

**Comment by bastianallgeier** [comment]
I'm a bit confused. Right now the validation is already working correctly. This means that you cannot publish a page with not enough structure entries and you can also not save it anymore once it has been published and you remove entries. So server-side validation is already working as expected and all your client project worries should be taken care of. 

The only problem that we have is the UX while you are working on structures. There's no immediate response that there are not enough entries and I understand that we must fix this. 

Maybe as a first step we should add a counter and show when the item count is not valid. This would make clear that items are missing and the field is not valid, but at the same time you keep the flexibility to move items around and edit them without being too restricted.

**Comment by distantnative** [comment]
@luxlogica's point was to restrict removing any items in the UX as soon as the minimum of items is reached. I agree that this would be too restricted.

I will close this issue in favor of https://github.com/getkirby/kirby/issues/1581 which covers the missing error highlighting of such fields (red outline, counter or whatsoever).
