### ISSUE TITLE
When setting home page to another page, subpages of this page return 404

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1371]
And the same is true for subpages of a home page calle `home`, both end up with a truncated URL, where the `home`/other-page-slug` is missing.
**To Reproduce**
1. In the Starterkit, set home to notes
2. Open website in a browser
3. Click on one of the subpages

**Expected behavior**
The router should redirect to the subpage instead of returning the error page.

**Kirby Version**
3.0.0

**Comment by manuelmoreale** [comment]
@distantnative and/or @bastianallgeier any chance this will be fixed in 3.0.1?

**Comment by bastianallgeier** [comment]
✅
