### ISSUE TITLE
Trying to Load Plugin Assets Throws TypeError

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1375]
**Describe the bug**
When trying to access an asset of plugin, I get a TypeError thrown from `…/src/Toolkit/F.php:327`

> Return value of Kirby\Toolkit\F::link() must be of the type boolean, null returned

**To Reproduce**
1. Download Staterkit
2. Create a folder in the plugins folder called `test`
3. Create the files described below
4. Attempt to load the `foo.js` at `http://localhost/media/plugins/my-test-org/test-plugin/foo.js`

#### site/plugins/test/index.php
```php
<?php

Kirby::plugin('my-test-org/test-plugin', [
]);
```

#### site/plugins/test/assets/foo.js
```
'This is a test JS file';
```

**Expected behavior**
The file should load. Instead, a TypeError is given. See screenshot.

**Kirby Version**
`3.0.0`

<img width="1423" alt="screen shot 2019-01-18 at 1 00 55 pm" src="https://user-images.githubusercontent.com/417182/51412660-1adbe480-1b21-11e9-90c0-1861a55ba1bd.png">

**Comment by bastianallgeier** [comment]
It looks like there's a problem with the symlink function on your system. If I can believe the PHP docs it should return a boolean. Would you be able to give the plain symlink function a try and see if you can get it running? http://php.net/manual/en/function.symlink.php

**Comment by neildaniels** [comment]
Ah, you're very correct. My Docker image disables symlink by default (via php.ini's `disable_functions`). When I whitelist, this works fine.

Can this issue be treated as a feature enhancement then? I was able to easily workaround this issue with the following custom route (note that I had to use `plugins-temp`, because `plugins` get routed before custom routes).

```php
[
    'pattern' => 'media/plugins-temp/(:any)/(:any)/(:all).(css|gif|js|jpg|png|svg|webp|woff2|woff)',
    'action'  => function (string $provider, string $pluginName, string $filename, string $extension) use ($kirby) {
        $plugin = kirby()->plugin($provider . '/' . $pluginName);
        $source = $plugin->root() . '/assets/' . $filename . '.' . $extension;
        return new Response(F::read($source), F::extensionToMime(F::extension($source)));
    }
],
```

This could probably use some more error handling and smarts, but it worked for me and demonstrated that symlink isn't strictly necessary (but I assume makes stuff more efficient).

**Comment by bastianallgeier** [comment]
Sorry for the delay. I don't get proper notifications for issue comments at the moment. 

I think it would be great to check for symlink support and then add yours as a fallback if it's not working. Your solution is not perfect. Routing the assets through PHP will always lead to longer load times. But it's still a good fallback.

**Comment by lukaskleinschmidt** [comment]
I currently ran into issues with symlinks on Windows (10). For local develeopment I use the internal php server. To be able to use the `symlink` function at all I need to [run the server process as administrator](https://stackoverflow.com/a/25112037). But even if I do so the symlink does not seem to work (Broken image error).

**Comment by bastianallgeier** [comment]
I think the problem is that we need a similar check for asset updates as for thumbnails to work around the symlinks. Then we could copy the assets to the media folder and don't worry about symlinks at all. But without that the assets wouldn't update with the current core implementation. I had to move this to the next milestone for now :/ Sorry about that.

**Comment by bastianallgeier** [comment]
I finally got an update for you :) 

The asset resolver does now try to create the symlink and catches all errors if this does not work. In that case, it uses the same technique as @neildaniels solution and simply returns a proper file response. That's slower than the symlinks on repeating calls, but it works. 

It would be fantastic if you could give it a try once the pre-release is out and let me know if it works for you as well.

**Comment by neildaniels** [comment]
This seems to work fine for me on `3.1.0-rc.1`
