### ISSUE TITLE
Files field: default query for site

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#1377]
Using a `files` field on the `site.yml` blueprint results in an error :
The files query does not seem to be correct on site.yml

How to fix :
Add `query: site.files` to the options

**Comment by tristantbg** [comment]
@distantnative The default query of the files field is `page.files` but when you use it in site.yml it is not a $page, it is a $site instance !

**Comment by distantnative** [comment]
Yes, I agree. That's a bug.

**Comment by bastianallgeier** [comment]
✅ This is now fixed on the develop branch.
