### ISSUE TITLE
Review deprecated methods

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1378]
Based on the docs decruft/cleaning, the following methods existed in v2 but aren't there in v3. We should review this list whether any of them still need to be reimplemented:

**Kirby\Cms\File**
base64
create-new-filename
data-uri
dimensions
dir
diruri
download
exif
hash
height
is-landscape
is-portrait
is-readable
is-square
is-websafe
is-writable
mime
name
nice-size
orientation
original
ratio
read
scale
size
textfile
uri
width

**Kirby\Cms\App**
locale
session-language
switch-language
visitor-language

**Kirby\Cms\Language**
default
host
path

**Kirby\Cms\Page**
archives
content-has-field
content-url
document
equals
has-archives
has-next-invisible
has-next-visible
has-prev-invisible
has-prev-visible
hash
headers
hide
intendedTemplateFile
is-deletable
is-parent-of
is-site
is-writable
move
next-invisible
next-visible
prev-invisible
prev-visible
reset
template-data
templateFile
textfile
tinyurl
to-json
touch
url-key
video

**Kirby\Cms\Pagination**
items
num-end
num-start

**Kirby\Cms\Site**
active-page
archives
content-has-field
content-url
diruri
has-archives
has-children()
is-site
reset

**Kirby\Cms\User**
avatar-root
can
cannot
current
data
firstname
gravatar
has-panel-access
has-role
is-current
lastname
permission
textfile

**Comment by mrflix** [comment]
FYI I just ported a zip-all-images-from-a-page-and-download-the-zip route that I once wrote for another page to v3 and had to recreate the following methods:
- `F::download`
- `$files->zip()`
- `$file->download()`
