### ISSUE TITLE
Easiest way to get the current version

### ISSUE THREAD

**Issue by yoanmalie** [getkirby/kirby#1380]
Actually, the `kirby::version()` return a string like 2.5.2 or 3.0.0.

When i was making a simple plugin who support both 2 and 3 version of Kirby, the only way to know the current version used is to use:

```php
<?php
// v2
version_compare(kirby::version(), '2.0.0', '>=') && version_compare(kirby::version(), '3.0.0', '<');
// v3
version_compare(kirby::version(), '3.0.0', '>=');
```

I suggest there would be an alias for that in the Kirby core, to avoid doing that ourself.

**Comment by distantnative** [comment]
I'm not sure I understand your request: `Kirby::version()` returns the version number of your install in the format `3.x.x`. What would you prefer instead?

**Comment by yoanmalie** [comment]
@distantnative Know if i'm the version 2 or 3. So return only the major version number : 2, 3…
Or maybe with a constant and be able to do something like `if(CURRENT_VERSION === 3) { }`.

**Comment by texnixe** [comment]
Maybe it would make sense for your use case, but not in general?

You could use something like
```
str::substr(Kirby::version(),0,1)
```
instead?

**Comment by distantnative** [comment]
@yoanmalie If you are only interested in the major version, easiest could be 
```php
Str::startsWith(Kirby::version(), '3')
```

A check for always the most recent version is currently not possible. Your install of course always thinks it is the most current. It would need to call home (or Github or packagist) to know if there is a newer version out there. That is not supported at this point in time.

**Comment by yoanmalie** [comment]
@texnixe @distantnative Your solutions look better than that i have at first, so yeah, i think we can agree that my suggestion is useless… 😄 
Thanks!

**Comment by lukasbestle** [comment]
But probably use this with a dot at the end:

```php
Str::startsWith(Kirby::version(), '3.')
```

Otherwise you'll have the same problem that was [one reason why there is no Windows 9](https://www.independent.co.uk/life-style/gadgets-and-tech/windows-10-why-microsoft-skipped-windows-9-9769537.html). ;)
