### ISSUE TITLE
Error on saving custom language

### ISSUE THREAD

**Issue by thinkbigger** [getkirby/kirby#1381]
**Describe the bug**
There are several issues on the new language creation option:
- when I create a new language, the introduced code is not respected. If you edit that language, the displayed code is different (at least for the Portuguese case)
- When editing the same language (in this case Portuguese), it returns the not found error.

**To Reproduce**
1. Create a new language 'Português (Europeu)' and put the code 'pt' and locale 'pt_PT'
2. Edit this new language. The first thing to notice is that the code is changed to 'po' instead of the 'pt'. I don't know if this is important, but Portuguese language ISO code is 'pt'. 
3. If you now change for instance the name and try to save it, you get the error message "Not Found" and nothing is done.

**Expected behavior**
1. Change the language properties
2. Assure that portuguese code is 'pt' instead of 'po'?

**Screenshots**
Create the language
![image](https://user-images.githubusercontent.com/7460809/51440894-a5f4e000-1cc3-11e9-8b0c-4a4650af68f6.png)

Edit the name of the language
![image](https://user-images.githubusercontent.com/7460809/51441031-40095800-1cc5-11e9-9367-6a7e11dc4737.png)

**Kirby Version**
Kirby 3.0.0

**Console output**
_app.js:1 PATCH http://v3webster/api/languages/po 404 (Not Found)
request @ app.js:1
post @ app.js:1
patch @ app.js:1
submit @ app.js:1
e @ vendor.js:39
Ne.t.$emit @ vendor.js:39
onSubmit @ app.js:1
submit @ app.js:1
e @ vendor.js:39
t._withTask.t._withTask @ vendor.js:39
submit @ app.js:1
submit @ app.js:1
e @ vendor.js:39
Ne.t.$emit @ vendor.js:39
submit @ app.js:1
e @ vendor.js:39
t._withTask.t._withTask @ vendor.js:39_

_app.js:1 {status: "error", message: "not found", code: 404}code: 404message: "not found"status: "error"__proto__: Object
dm.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
post @ app.js:1
patch @ app.js:1
submit @ app.js:1
e @ vendor.js:39
Ne.t.$emit @ vendor.js:39
onSubmit @ app.js:1
submit @ app.js:1
e @ vendor.js:39
t._withTask.t._withTask @ vendor.js:39
submit @ app.js:1
submit @ app.js:1
e @ vendor.js:39
Ne.t.$emit @ vendor.js:39
submit @ app.js:1
e @ vendor.js:39
t._withTask.t._withTask @ vendor.js:39_

**Desktop:**
 - OS: macOS
 - Browser chrome
 - Version 71.0.3578.98

**Comment by bastianallgeier** [comment]
✅  I just fixed it. It will be in the next nightly build and in 3.0.1

**Comment by bastianallgeier** [comment]
You can download it right now from the develop branch. https://github.com/getkirby/kirby/archive/develop.zip

**Comment by thinkbigger** [comment]
Thanks!

Na(o) terça, 22/01/2019, 15:49, Bastian Allgeier <notifications@github.com>
escreveu:
