### ISSUE TITLE
[Uri] missing slash before params

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1384]
**Describe the bug**
I think this is the source for https://github.com/getkirby/getkirby.com/issues/194

**To Reproduce**
```php
(string)new Kirby\Http\Uri('search', [
    'params' => [
        'page' => 2
    ],
    'query'  => [
        'q' => 'term'
    ],
]);
```

Results in `/searchpage:2?q=page` as string.

**Expected behavior**
Should result in `/search/page:2?q=page`

**Kirby Version**
3.0.0

**Comment by bastianallgeier** [comment]
✅
