### ISSUE TITLE
Basic auth and non-HTTPS in development

### ISSUE THREAD

**Issue by mattlenz** [getkirby/kirby#1386]
We're using Kirby as a headless CMS for a handful of sites in development.

Currently we use basic auth over the API for this, however I have to patch Kirby 3 while developing locally to allow non HTTPS requests.

The workaround boils down to commenting out this conditional;

https://github.com/getkirby/kirby/blob/72f01eac0a7db59360894e0cfb44680276260174/src/Cms/Auth.php#L73-L75

I think it's fairly common to develop locally without HTTPS. I'm aware there are methods (self-signed certificate?). But also wondering if a simple workaround would be to add a config option to disable the SSL requirement?

`/site/config/config.localhost.php` might look like

```php
return [
    'api' => [
        'basicAuth' => true,
        'allowInsecure' => true
    ]
];
```

Happy to fork and suggest a patch.

**Comment by mattlenz** [comment]
https://github.com/getkirby/kirby/compare/master...mattlenz:master

**Comment by lukasbestle** [comment]
There's a similar PR here: #1360

@mattlenz @jonathan-reisdorf Which solution do you prefer personally? An option or having access by default on local machines? The latter could cause issues if the server is in a local environment but not detected by Kirby. So we could have both: Enable it by default on local machines and make it enforceable with an option. But maybe an option alone is enough.

**Comment by jonathan-reisdorf** [comment]
I think the option to enable it via flag is better (more explicit) than how I solved it in the PR :+1:

**Comment by mattlenz** [comment]
Making it explicit sounds good as the developer would have more control.

Open to ideas for how to name the config option? I thought `api.allowInsecure` as it enforces the idea that HTTPS is preferred and otherwise is insecure.

I've added another PR with this approach.

**Comment by jonathan-reisdorf** [comment]
I think `api.allowInsecure` should be renamed because from the wording it sounds like a global setting to allow an insecure api, while we're just allowing insecure connections to the api and only if basicAuth is enabled. On the other hand I don' really have a better naming idea.

**Comment by bastianallgeier** [comment]
Sorry for the delay. I merged the PR with the name of the option. I think the name is quite good and also includes a warning that this option needs to be used cautiously.
