### ISSUE TITLE
[Cms] Locale setting can only be a string

### ISSUE THREAD

**Issue by hrkfdn** [getkirby/kirby#1387]
**Describe the bug**
The documentation mentions, that the 'locale' key can point to an array containing the locale descriptors. However, the method processing this setting expects a string type: https://github.com/getkirby/kirby/blob/6749dd1850fa237c36da0397a913e139e06d343e/src/Cms/Language.php#L373.

This results in a type mismatch exception.

**To Reproduce**
1. Create a language file, e.g. site/languages/de.php
2. Pass array as locale setting, like in the documentation: https://getkirby.com/docs/guide/languages/introduction#detailed-locale-settings
3. Load page.

**Kirby Version**
v3

**Comment by distantnative** [comment]
✅
