### ISSUE TITLE
Panel generates the wrong sorting number

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#1388]
**Describe the bug**
When a draft or an unlisted page has its status changed to listed without providing a position from the dropdown menu in the modal instead of receiving the correct number based on the number of already visible pages (so for example `6_` if there are already 5 visible pages), its sorting number is set to `1_` and the already listed pages get re-numbered accordingly.

**To Reproduce**
1. Create a pages section.
2. Add 2 or 3 listed pages
3. Create a new draft
4. Update the status without selecting a position in the **"Please select a position"** dropdown 

**Expected behavior**
The page sorting number should be set to the highest possible value based on the number of pages already present.

**Kirby Version**
3.0.0

**Forum Discussion**
https://forum.getkirby.com/t/issue-with-auto-generated-sorting-number/12315

**Comment by bastianallgeier** [comment]
✅
