### ISSUE TITLE
Link in tab jumps to first tab before following route

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1389]
When clicking on a link in a tab that is not the first in order, the view jumps to tab one before changing to the intended destination.

**Steps to reproduce the behavior:**
1. Add two tabs to page blueprint
2. Add a pages section to tab two and list some pages
3. Click on a list item
4. See the tabs jump before changing to the destination

**Expected behavior**
Go directly to destination.

**Screenshots**

![tab-jumps](https://user-images.githubusercontent.com/46723734/51491324-50e1c880-1dae-11e9-9b27-213cd3bcd0db.gif)

**Kirby Version**
3.0

**Console output**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition 
 - Version: 65.0b12

**Additional context**
Adding the #anchor for the current tab to the link fixes the problem.

**Comment by bastianallgeier** [comment]
✅

**Comment by mullema** [comment]
@bastianallgeier 3.4.0 re-introduces this issue

**Comment by afbora** [comment]
@mullema Thanks for report again. This is old issue and i created new one about that https://github.com/getkirby/kirby/issues/2742
