### ISSUE TITLE
[Router] Bind the route actions to the route object

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#139]
Given the following route:

```
kirby()->routes([
    [
        'pattern' => 'something',
        'action'  => function() {
            echo $this->pattern(); // something
        }
    ],
]);
```

`$this` should probably be bound to the route object. However we should check if this behavior would break any other use-cases.

See also this forum topic: https://forum.getkirby.com/t/the-official-way-to-get-the-route-pattern/9247?u=lukasbestle

**Comment by bastianallgeier** [comment]
✅
