### ISSUE TITLE
$page->isCacheable() Almost Always Returns False

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1392]
**Describe the bug**
The page cache system does not seem to work for me, except for on the homepage. For all other pages, the `$page->isCacheable()` method returns false.

Specifically, it gets kicked out as false because of this test.
```php
if (in_array($request->method(), ['GET', 'HEAD']) === false || empty($request->data()) === false) {
    return false;
}
```

More specifically, the `$request->data()` is not empty "enough" for the `empty()` function.

In my case, all of the pages (except the homepage) have an entry in that array that the page URI, but not value. 

For example, a page at `http://localhost/guides` has the following `print_r($request-data())`:
```
Array
(
    [/guides] => 
)
```

**To Reproduce**
1. Enable page cache
2. Try to load a page
3. Note how no file is created in the cache directory

**Expected behavior**
The file should be cached and then further requests should use the requested page.

**Kirby Version**
`3.0.0`

**Comment by bastianallgeier** [comment]
Do you use Nginx? I had the same problem but was able to solve this with the following setup in the nginx config: 

```
location /
{
        try_files $uri $uri/ /index.php$is_args$args;
}
```

This will not attach the path to the query, which is weird anyway.

**Comment by neildaniels** [comment]
I do use Nginx. I’ll try that out in the morning.

**Comment by neildaniels** [comment]
That config change did resolve my issue. I'll close this issue.
