### ISSUE TITLE
`isChildOf()` results in error if called on a first level page

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1394]
**Describe the bug**
`$page->isChildOf($somepage)` throws an error if `$page` is a first level page which doesn't seem to have a parent.

Don't know if this is intended but the behavior is different from checking if the page` isDecendantOf()` which can be done without prior checking if the page has any parents at all; and it is also different from the behavior of the same Kirby 2 method.

**Comment by bastianallgeier** [comment]
✅
