### ISSUE TITLE
Panel Should Have Better Error Message if API is Disabled

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1395]
**Describe the bug**
I had disabled the Kirby API in my config file, not realizing that the Panel would be dependent on it being active.

When I went to use the Panel for the first time, I get errors like:

Safari:
> The string did not match the expected pattern. 😭

Chrome:
> Unexpected token < in JSON at position 0 😭

**To Reproduce**
1. Set `'api' => false` in your config.php
2. Attempt to use the Panel

**Expected behavior**
If the Panel is dependent on the API being enabled, it should just say that.

**Kirby Version**
`3.0.0`

**Console output**
Chrome:
```
app.js:1 GET http://localhost/api/system?view=panel 404 (Not Found)
app.js:1 SyntaxError: Unexpected token < in JSON at position 0
```

Safari:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (system, line 0)
[Error] SyntaxError: The string did not match the expected pattern.
	onError (app.js:1:235271)
	(anonymous function) (app.js:1:231397)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (logout, line 0)
[Error] SyntaxError: The string did not match the expected pattern.
	onError (app.js:1:235271)
	(anonymous function) (app.js:1:231397)
	promiseReactionJob
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2 (18C54)
 - Browser: Chrome 71.0.3578.98. Safari 12.0.2 (14606.3.4)

**Additional context**
Removing the `'api' => false` (thus enabling the API) makes this issue go away.

**Comment by bastianallgeier** [comment]
✅
