### ISSUE TITLE
[Panel] "Open" Button opens another tab with the page in the panel

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#1397]
**Describe the bug**
The Open Button prefixes the url given with panel. I've digged into this and wrote about it in #helpdesk
https://getkirby.slack.com/archives/CBN859614/p1547671337657000?thread_ts=1547208608.473600&cid=CBN859614

**Screenshots**
See the difference between `props:to` and `computed:href`

![screen shot 2019-01-24 at 13 20 57](https://user-images.githubusercontent.com/270540/51677790-02654180-1fdb-11e9-9825-ca0ce66c7c98.PNG)

**Kirby Version**
3.0.0

**Comment by bastianallgeier** [comment]
It took a while to understand the problem. Sorry, I'm slow. But now I got it. When you set the URL in your config to `/` the Link.vue component is a bit too smart about it and converts it to a routed panel URL. I fixed this now by also listening to the target and whenever that is set, the link is interpreted as a external link.

**Comment by joernroeder** [comment]
@bastianallgeier no worries!!! 👊
