### ISSUE TITLE
Panel doesn't work when using Valet+

### ISSUE THREAD

**Issue by lumpysimon** [getkirby/kirby#1398]
I use Valet+ for my local development (on MacOS 10.13). I've installed Kirby3 Starterkit. The front-end of the site works perfectly (the URL is `k3.test`), but the panel doesn't work. I get the following errors when visiting `k3.test/panel`:

```
Warning: chdir(): No such file or directory (errno 2) in /Users/myusernamehere/.composer/vendor/weprovide/valet-plus/server.php on line 113

Warning: require(/Users/myusernamehere/www/k3/panel/index.php): failed to open stream: No such file or directory in /Users/myusernamehere/.composer/vendor/weprovide/valet-plus/server.php on line 117

Fatal error: require(): Failed opening required '/Users/myusernamehere/www/k3/panel/index.php' (include_path='.:/usr/local/Cellar/php/7.2.12_2/share/php/pear') in /Users/myusernamehere/.composer/vendor/weprovide/valet-plus/server.php on line 117
```

It seems to be looking for `/panel/index.php`, which doesn't exist.

**Comment by texnixe** [comment]
Have you installed the Kirby driver from Valet (not Valet+)?
https://forum.getkirby.com/t/webserver-recommendation-for-local-development-mac/12143/14?u=distantnative

**Comment by bastianallgeier** [comment]
You are definitely using the old driver. It looks for a panel/index.php which is not there, because we no longer have a panel folder in v3

**Comment by lumpysimon** [comment]
Sorry, it turned out I wasn't using the latest version of Valet Plus - I've just upgraded and now all is good.
