### ISSUE TITLE
Image files in media folder not being created

### ISSUE THREAD

**Issue by florianporada** [getkirby/kirby#1399]
**Describe the bug**
I'm currently trying to port our v2 to v3 but encountered that no image or file is created in the media folder under pages. Projects show up in the folder structure but the only thing that is present in the folder structure is a .job folder with a json file. Is this a Kirby related issue or are there any missing permissions?

**To Reproduce**
1. Clone the starterkit
2. run `php -S localhost:8888`
3. Open localhost:8888

**Screenshots**
[Imgur](https://i.imgur.com/xng8gRO.png)

[Imgur](https://i.imgur.com/IJ9lhmu.png)

**Kirby Version**
3.0.0

**Additional context**
PHP version: 7.1

**Comment by texnixe** [comment]
You have to call the built-in server with Kirby's router:
```
php -S localhost:8000 kirby/router.php
```

**Comment by florianporada** [comment]
works like a charm now, thanks :)
