### ISSUE TITLE
[Panel] Uploading RAW photos results in 0 byte file

### ISSUE THREAD

**Issue by paulrobertlloyd** [getkirby/kirby#14]
Uploading an image via the macOS media browser, results in an 0 byte file being added. This is the meta information shown in the panel UI after uploading:

```
Type: inode/x-empty
URL: /test/fullsizeoutput_106cb.jpeg
Size: 0 B
Dimensions: 0 × 0
```

Here’s what I mean by media browser:

![screen shot 2017-10-31 at 13 51 59](https://user-images.githubusercontent.com/813383/32227269-d0d89ec8-be42-11e7-8fdf-87bc38976070.png)

**Comment by bastianallgeier** [comment]
WTF! I actually never used that before :) Why would it upload the file with a different mime type. I have to investigate that.

**Comment by malvese** [comment]
FWIW, I just tried with several jpegs (including a huge 5300×3500, 14Mb one) and it Worked For Me™. macOS 10.12.6.
@paulrobertlloyd Any chance it is actually a raw file in Photos, or a fancy iOS format with embedded movie?

**Comment by paulrobertlloyd** [comment]
@malvese Ooh, I did select RAW photos. I went back and selected images that I knew were JPEGs, and it worked. I thought macOS would have converted these images to JPEG, but maybe that is the wrong assumption, or requires OS-level integration. Shame. Not sure how much Kirby can do in this regard. Feel free to mark as closed.

**Comment by bastianallgeier** [comment]
I changed the title and would leave it here. It doesn't have a high priority, but of course it would be nice if we could get raw photo upload working as well.

**Comment by malvese** [comment]
I tried to upload a raw file, and it was actually imported! No preview was created though, but I didn't expect one to be generated.
The mime type was `image/tiff`, which seems a little bit suspect, but it shows in the panel with an image icon.

**Comment by bastianallgeier** [comment]
I think I'm going to close this for now. It seems to work well enough for a first version. Real Raw support could be improved later.
