### ISSUE TITLE
Blueprint options are inconsistant?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#140]
https://getkirby.com/docs/panel/blueprints/anatomy-of-a-blueprint

**Look at this:**

```text
deletable: false
options:
  preview: false
files: false
```

First we have some blueprint options, `deletable` in this case. After that we have an `options` wrapper and inside that we have more options. After that there are options like `files`.

I find it inconsistant. Maybe there is a logic choice behind it but maybe wrap all options in `options` or don't wrap any of them? `options` as container is probably "safer" so keep it isolated.

**Comment by bastianallgeier** [comment]
We already took care of making it more consistent. Everything is now organized in the options setting
