### ISSUE TITLE
[Cms] Nested folders for collection() method

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#1400]
Right now the new `$kirby->collection()` method only allows files to be placed inside the main `collections` folder and doesn't support more complex structures like this one for example:

```
collections/
∟ folder/
  ∟ name.php
```

Would be nice to have the ability to do this instead `$kirby->collection('folder/name')` which is something we can already do with snippets for example.

**Comment by bastianallgeier** [comment]
✅
