### ISSUE TITLE
[PagesSection] Cannot use comma in info query

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1402]
**Describe the bug**
Within a `type: pages` section, if I do something like:
```
info: "{{ page.created.toDate('M j, Y') }}"
```
then the comma and everything after it will be missing.

For reference, this is what the `created` field is created as:
```
  created:
    label: Created On
    type:  date
    time:
      interval: 5
    default: now
```

**To Reproduce**
1. Have a pages section in the panel, with the mentioned info field
2. Those pages should have a created (or similarly named filed)

**Expected behavior**
I would expect to see dates in the format of "Jan 24, 2018". Instead, it just shows "Jan 24".

If you change the format to something like `'M, j Y'`, then it will just show "Jan".

**Screenshots**
<img width="399" alt="screen shot 2019-01-24 at 4 46 40 pm" src="https://user-images.githubusercontent.com/417182/51717908-a8bf4000-1ff7-11e9-8702-a2bf05a2727f.png">

**Kirby Version**
`3.0.0`

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: Safari
 - Version: 12.0.3

**Additional context**
Other characters like `;` instead of `,` work fine, but that is a weird way to write dates.

**Comment by texnixe** [comment]
Things that work:

```
info: >
  {{ page.date.toDate("M d, Y") }}
```
or:
```
info: |
  {{ page.date.toDate("M d, Y") }}
```
or:

```
info: "{{ page.date.toDate('M d&#44; Y') }}"
```

**Comment by neildaniels** [comment]
```
info: '{{ page.created.toDate("M j, Y") }}'
```
This works as well. Seems like the comma requires the date string being surrounded by double quotes `"`, and the entire thing must be surrounded by single quotes `'`.

**Comment by bastianallgeier** [comment]
Hm, could be another weirdness of the yaml parser. I have to check that out.

**Comment by texnixe** [comment]
Probably related:

```
pluck('tags', ',') // empty delimiter error
pluck('tags', ",") // works
```

**Comment by distantnative** [comment]
@texnixe @neildaniels Wondering if this might have been solved as well with the new Query refactoring for 3.2.0. Will try to test it in the next days.

**Comment by distantnative** [comment]
@neildaniels any chance you could test this?

**Comment by texnixe** [comment]
@distantnative The original example works in 3.2.2 with single quotes now. I think we can close this.

**Comment by distantnative** [comment]
Thanks, @texnixe.
@neildaniels Please feel free to reopen if you still encounter it somehow, somewhere.
