### ISSUE TITLE
Logged out after exception

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1403]
**Describe the bug**
If a yml file isn't correct (e.g. non existing files for sections) i get logged out of the panel. No matter if i check "keep my logged in".

**To Reproduce**
1. Go to a yml file
2. Change it to be not wellformed
3. Reload panel
5. Refresh the page and see if you are still logged in

**Expected behavior**
Still being logged in.

**Kirby Version**
3.0

**Console output**
```
{status: "error", exception: "Kirby\Exception\NotFoundException", message: "Das Blueprint "tabs/appearancew" konnte nicht geladen werden.", key: "error.blueprint.notFound", file: "kirby/src/Cms/Blueprint.php", …}
code: 404
details: []
exception: "Kirby\Exception\NotFoundException"
file: "kirby/src/Cms/Blueprint.php"
key: "error.blueprint.notFound"
line: 282
message: "Das Blueprint "tabs/appearancew" konnte nicht geladen werden."
status: "error"
__proto__: Object
```

**Desktop (please complete the following information):**
 - macOS Mojave
 - Chrome
 - 71

**Comment by bastianallgeier** [comment]
✅ This is now fixed on the develop branch and will be in 3.0.2
