### ISSUE TITLE
make name of session cookie configurable

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1405]
the cookie has the name `kirby_session`. please make it configurable to avoid detection from pages like https://whatcms.org/ for security reasons.

the `/assets` folder might be another detection criteria but it is already possible to change that.

**Comment by bastianallgeier** [comment]
No need for an issue. That's already possible: https://getkirby.com/docs/reference/system/options/session#cookiename Maybe we just need to change the default name.
