### ISSUE TITLE
[Panel] Paging on sections unusable

### ISSUE THREAD

**Issue by DanielRivers** [getkirby/kirby#1407]
**Describe the bug**
Paging is unusable in the current state, there is up and down arrow but it response instantly, typing a number responds instantly too, so max page can go to is 9

**To Reproduce**
1. Goto section with more than one page of results
2. Click on the page numbers
3. press up arrow
4. Navigates immediately - **Unexpected**
5. Try to goto page 10+

**Expected behavior**
Be able to navigate to whatever relevant page I want

**Screenshots**

![image](https://user-images.githubusercontent.com/1270799/51752593-c64fe080-20af-11e9-9f41-a4611db7d0d2.png)

**Kirby Version**
3.0.0

**Console output**
If you are working with the panel, please check the browser console for errors and send the output.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 71.0.3578.98

**Comment by bastianallgeier** [comment]
I slightly redesigned the dropdown and changed the behavior. You have to either click on the arrow or hit enter after entering a page number.
