### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by abroess** [getkirby/kirby#141]
You cannot use 'Object' as a class name in "kirby/src/Cms/Object.php", because in PHP 7.2.x it is a reserved name.

**Comment by bastianallgeier** [comment]
Yikes. Ok, we will rename those classes. I urgently need to setup our test environment to test against 7.2 as well. Thanks for the ticket.

**Comment by bastianallgeier** [comment]
This is now fixed
