### ISSUE TITLE
Content representations don't work in multilingual installation with default language set to '/'

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1410]
**Describe the bug**
When trying to access a content representation, for example, `https://example.com/about.json` in a multi-lingual setup, Kirby returns the error page.

**To Reproduce**
1. In a Starterkit, enable languages, set up a language and set default language url to `/`.
2. Create a new content representation, e.g. `about.json.php`, empty or with a string or whatever
3. Try to access ``https://example.com/about.json`
4. Be redirect to the error page

The content representation works if we set the `url` to `/languageCode`

**Expected behavior**
The content representation should also work if the root URL without the language code is used.

**Comment by bastianallgeier** [comment]
✅
