### ISSUE TITLE
[Cms] 'Min' option not respected in pages/files sections

### ISSUE THREAD

**Issue by luxlogica** [getkirby/kirby#1411]
When specifying a `min` option in a Pages or Files Section, the `min` setting is ignored, and the user is allowed to keep on deleting pages/files beyond the limit. 

Example: 
1. Setup a Pages or Files Section with a `min:1`
2. Add some pages/files to the section
3. Delete all pages/files - you shouldn't be able to do that, as it should stop you when you have 1 page left

Unfortunately, you can delete ALL pages. You can also _save the page_, even when the count for a section is below the `min` - I would have expected it to warn the user then, too.

This bug seems suspiciously similar to the [Min Bug on Structure Fields](
https://github.com/getkirby/kirby/issues/1368)... Perhaps `min` needs to be checked everywhere it's used.

**Comment by distantnative** [comment]
This one is a bit different than the structure field issue, since with files and pages sections, there is no extra step of saving content. So it might make sense here to disable the remove buttons when the minimum is reached.

**Comment by bastianallgeier** [comment]
✅
