### ISSUE TITLE
Panel: Can't Unset Number Field

### ISSUE THREAD

**Issue by calebgrove** [getkirby/kirby#1412]
**Describe the bug**
When I attempt to unset a number field, on save, the value sets to `0` rather than fulling unsetting. 

**To Reproduce**
1. In a very basic field with `type: number`, without any `default` set, enter any number and save the page.
2. In the same field, now delete the number, leaving the field empty.
3. Save the page again.
4. See error: The value of the field has been transformed to `0`, rather than being empty.

**Expected behavior**
The field to be "unset", with no content.

**Kirby Version**
3.0.0

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Safari 12.0.3

**Comment by calebgrove** [comment]
This may be separate, or the same bug, but I've also noticed that when the number field is set to `0`, deleting it and clearing the field doesn't trigger the "Save" banner to appear at the bottom of the browser.

**Comment by bastianallgeier** [comment]
✅ This will be fixed in 3.0.1
