### ISSUE TITLE
Cropping doesn't work with ImageMagick driver

### ISSUE THREAD

**Issue by Sija** [getkirby/kirby#1413]
**Describe the bug**
While using ImageMagick driver, thumbs are being generated, but not resized or processed in any way.

**To Reproduce**
1. Set `"thumbs" => ["driver" => "im"]` in `site/config/config.php`
2. Clear thumbs cache (`rm -rf media/pages/*`)
3. Load a page with `<?= $image->crop(100, 300) ?>`
4. See that supposedly cropped image has original dimensions

**Expected behavior**
Properly cropped image. There's no such issue with GD driver.

**Kirby Version**
3.0

**Comment by bastianallgeier** [comment]
I just checked and it works for me. You might need to link your imagemagick convert script manually with 

```php
return [
  'thumbs' => [
    'driver' => 'im',
    'bin' => '/usr/local/bin/convert',
  ]
];
```

The `bin` setting depends on your location of the convert script though

**Comment by bastianallgeier** [comment]
Let me know if you were able to fix it.

**Comment by Sija** [comment]
@bastianallgeier Passing `bin` option works perfectly, thank you!

Returning some kind of an error in such case would be informative tho' - sth for the bugfix release maybe?

**Comment by bastianallgeier** [comment]
I just created a ticket for it: https://github.com/getkirby/kirby/issues/1414

**Comment by jaro-io** [comment]
for anyone struggling here who installed imagemagick via homebrew, you need to add the following bin folder instead:

```php
return [
  'thumbs' => [
    'driver' => 'im',
    'bin' => '/opt/homebrew/bin/convert',
  ]
];
```

you can also find your individual imagemagick installation folder by typing `which convert` into your terminal.
