### ISSUE TITLE
[Cms] Replacement for K2 Asset helper

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#1418]
In Kirby 2 we had the `Asset` helper.

In Kirby 3 we can use `Kirby\Image\Image` and `Kirby\Cms\File` and `Darkroom`, but I find it confusing to know which you should use, and how you should use them properly.

This is popping up in the forums regularly, and I'ld need it to work with images that come with virtual pages from an API.

**Comment by luxlogica** [comment]
Another use-case: we often provide 'default' images to a site, in case the user does not upload an image that is required in the page layout - this is a more elegant solution than just making the image 'required'. These default images are stored in 'assets', and we used to be able to easily generate thumbs as needed. Not so easy now...

**Comment by daybugging** [comment]
I'd be interested in a workaround for now ..

**Comment by bastianallgeier** [comment]
I'm on it! Sorry for the delay.

**Comment by bastianallgeier** [comment]
✅ The Asset class is now available again on the develop branch. 

```php
$asset = new Asset('some/path/image.jpg');
```

There's also a new asset() helper.

```php
$asset = asset('some/path/image.jpg');
```

The assets now use the same dynamic image resizing API as the other files 🎉
