### ISSUE TITLE
Locale not set on homepage when default language has `url` set to '/'

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1419]
**Describe the bug**
When creating a language with the URL prefix set to '/', the locale is not set on the homepage, but for all subpages. Tested on a setup with 2 languages, where the default language has no URL prefix.

**To Reproduce**
1. Set the date handler to `strftime` and setup 2 languages. Default language has to be something other than English and its `url` set to `/`.
2. Echo a localized date (e.g. in the `header.php` snippet, so you can compare results between pages easily).
2. Go to the homepage of your installation, the date will appear in English.
3. Go to any subpage, the date will be displayed in its localized form.

**Expected behavior**
The locale should be set on any page of a certain language. A quick test revealed, that the `setlocale()` function is not called on the homepage at all.

**Kirby Version**
3.0.0

**Comment by bastianallgeier** [comment]
✅
