### ISSUE TITLE
Unable to go back to default language if automatic language detection is enabled

### ISSUE THREAD

**Issue by SonicHedgehog** [getkirby/kirby#142]
If I configure multi-language support [as described in the docs](http://getkirby.com/docs/languages/setup) and enable automatic language detection using `language.detect`, I’m unable to switch back to the English version if I previously visited `/de`.

It looks like this is happening because [the session’s language is set when visting `/de`](https://github.com/getkirby/kirby/blob/2.0.5/kirby.php#L603). Upon loading `/` (the English version’s url), [I’m then being redirected](https://github.com/getkirby/kirby/blob/2.0.5/kirby.php#L195). A feasible solution might be to only redirect the user on `/` if the session’s language hasn’t already been set.

**Comment by bastianallgeier** [comment]
This has finally been fixed on the develop branch.

**Comment by SonicHedgehog** [comment]
Thanks. However, while the user can now switch back to the default language, if they load `/` twice within one session (usually because they don’t close the browser in between) they won’t be redirected to `/de` the second time because Kirby thinks the user wants to switch to the default language.

Would adding a GET parameter `lang` to the language switcher’s URLs help so that Kirby can distinguish between these two requests?
