### ISSUE TITLE
[Panel] Users search

### ISSUE THREAD

**Issue by plantalabs** [getkirby/kirby#1420]
**Describe the bug**
search function only return pages. 

**To Reproduce**
1. Login to the panel
2. Click on search icon
3. Start typing any registered username 
4. the dropdown only return pages

**Expected behavior**
to return pages & users like kirby 2

**Screenshots**
![image](https://user-images.githubusercontent.com/11565604/51928404-a2084280-23d4-11e9-9ec8-e96ce2f151b3.png)

**Kirby Version**
kirby 3 

**Console output**
console not showing errors

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome, firefox
 - Version Versión 71.0.3578.98 (Build oficial) (64 bits)

**Comment by texnixe** [comment]
@plantalabs You already created an issue in the ideas repo
https://github.com/getkirby/ideas/issues/174

**Comment by plantalabs** [comment]
hi, but is more a bug than an idea. or i am wrong?
