### ISSUE TITLE
svg() helper does not work with absolute path

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1423]
**Describe the bug**
Including svg's via helper function is not working with absolute paths even though it is mentioned in doc. Absolute path gets treated like a relative path and therefore prefixed with root directory.

**To Reproduce**
1. Create svg
2. Try to include with absolute path via helper eg. `<?= svg("/path/to/file.svg"); ?>`
3. See error

**Expected behavior**
Return end echo out the svg file.

**Kirby Version**
3.0

**Comment by bastianallgeier** [comment]
✅ This is now fixed on the 3.0.2 branch.
