### ISSUE TITLE
Bring back "Create from title" button

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#1427]
As said in the title, its not a bug.

But i really really miss this tiny button "create from title" to change the slug of the page automatically 

![bildschirmfoto 2019-01-31 um 14 10 44](https://user-images.githubusercontent.com/25037153/52067933-ed108a00-257b-11e9-9658-c4ccd0baf10e.png)

Is there a reason why it is gone since kirby2?

**Comment by bastianallgeier** [comment]
It's a bit embarrassing but the only reason is that we forgot about it.

**Comment by bastianallgeier** [comment]
✅ It's now on the 3.0.2 branch
