### ISSUE TITLE
t.language is null after upgrading to 3.0.1-rc1

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#1428]
**Describe the bug**
After updating to `3.0.1-rc1` i'm getting a `TypeError: "t.language is null"` error uppon login into the panel. Im running a multi language setup with `de (default)` and `en`.
I've also removed `media/panel` but this did not have any effect.

**Comment by bastianallgeier** [comment]
Hm, I cannot reproduce this. Do you have something else configured for your installation that could be important? The panel.language option for example?

**Comment by joernroeder** [comment]
i noticed that on my live server only. As i am having a permanent docker environment there (compared to dev) it might has something to do with cookies or sessions created in < 3.0.1. i also checked responses the panel was doing but all of them responded with `200`.

**Comment by bastianallgeier** [comment]
Did it still happen after logging out?

**Comment by joernroeder** [comment]
not sure. will try to replicate it again later this week.

**Comment by bastianallgeier** [comment]
I can't reproduce it and will close it. Feel free to reopen if you are able to replicate it again.
