### ISSUE TITLE
[Panel] Cannot rename file if other file with same name but different file extension already exists

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1432]
**Describe the bug**
I have uploaded two files in the panel:

– image.jpg
– wrongname.png

Now I try to rename the `wrongname.png` to `image.png`. But Kirby does not allow this, because the file supposedly already exists. But this is not true, because the existing file has a different file extension.

**Screenshots**
<img width="1266" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/52163401-c53b3680-26e1-11e9-8a1c-9045882d34ba.png">

**Kirby Version**
3.0.0 and 3.0.1 RC1

**Comment by bastianallgeier** [comment]
✅ I just fixed this on the 3.0.2 branch.
