### ISSUE TITLE
[Router] Route filters / call next handler

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1437]
It’d be really handy to be able to pass the request on to the next handler from within a route handler. 

For example, imagine a website that has quite a few landing pages. In order to keep the file structure as clean as possible, all of these landing pages are children of another page.

```
├── landingpages/
│   ├── landingpage-a/
│   ├── landingpage-b/
│   ├── landingpage-c/
│   └── ...
```

However, this structure should not be represented in the URL, so you might add a custom route in order to achieve a flat URL strucutre:

```php
[
  'pattern' => '/(:any)',
  'action'  => function($slug) {
    if($landingpage = page('landingpages')->find($slug)) {
      return page($landingpage);
    }
    // If there’s no matching landing page, you’d need to duplicate
    // the logic of the default routes here in order to show either
    // another page that matches the given slug or the error page.
  }
]
```

Instead of duplicating all that default logic, passing the next route as a callable/closure to the route handler seems to be a pretty common routing/middleware pattern:

```php
[
  'pattern' => '/(:any)',
  'action'  => function($slug, $next) {
    if($landingpage = page('landingpages')->find($slug)) {
      return page($landingpage);
    }
    // `$next` might be the default route or any other custom route
    // that has been defined after the current route
    $next();
  }
]
```

**Comment by bastianallgeier** [comment]
I wasn't really happy with the filters in v2 and always thought that we need something that is more like the typical next handler. Now we finally got it! 

It only looks slightly different than in @tillprochaska's example: 

```php

return [
    'routes' => [
        [
            'pattern' => '(:any)',
            'action'  => function ($slug) {

                if ($page = page('photography')->find($slug)) {
                    return page($page);
                }

                $this->next();

            }
        ]
    ]
];
```

Works like a charm so far, but please help us test it as soon as it is in the pre-release next tuesday (or even already on the develop branch)
