### ISSUE TITLE
Panel runs out of memory with file blueprints

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/kirby#1443]
**Describe the bug**
Adding a files field to a file blueprint causes one of two errors after pressing the save button, either exhausted memory (i have 256mb allocated) or Maximum function nesting level of ‘256’ reached, aborting!

In my case i'm uploading audio files and want the file field to pick album cover art.

**To Reproduce**
1. Add a files section to a page blueprint
2. Add a file template with a files field in
3. Upload a file and some images
4. Edit the file in the panel
5. Pick image from the files field
6. Click the save button
7. Panel should hang and give a whoops pop up error.

**Expected behavior**
Meta should be saved successfully.

**Kirby Version**
3.0.1-rc.1

**Desktop (please complete the following information):**
 - macOS
 - Opera
 - Laraval Valet
- PHP 7.1

**Additional context**
Theres a forum thread here: https://forum.getkirby.com/t/3-0-1-rc-1-panel-runs-out-of-memory-with-file-blueprints/12646

**Comment by texnixe** [comment]
In my test case, it was an alert window that popped up in the Panel.

**Comment by bastianallgeier** [comment]
✅ This is now fixed on the develop branch
