### ISSUE TITLE
modified broken with datehandler strftime

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1446]
**Describe the bug**
page object modified returns string U with datehandler strftime

**To Reproduce**
1. download plainkit
2. create config and set datehandler to `strftime` https://getkirby.com/docs/reference/system/options/date
3. default.php `<h1><?php echo $page->modified() ?></h1>`

**Expected behavior**
timestamp should be echoed. but it yields string `U`

**Kirby Version**
current plainkit

**Desktop (please complete the following information):**
 - osx firefox dev mamp pro 4 apache

**Comment by bnomei** [comment]
about `low-hanging fruit`... currently my feed plugin is broken for all installations using the strftime datehandler. but maybe i am just missinterpreting the fruit label.
https://github.com/bnomei/kirby3-feed/issues/9

**Comment by bastianallgeier** [comment]
Our low hanging fruit label means that it's a pretty simple fix and can probably done within a couple minutes. In this case I already fixed it on the develop branch.

**Comment by bnomei** [comment]
i would realy appreciate if you would reference the issue in your commit messages. it is as simple as typing #1446. ;-)
