### ISSUE TITLE
`site.yaml` is ignored

### ISSUE THREAD

**Issue by chpio** [getkirby/kirby#1447]
**To Reproduce**
1. fix the YAML file extension from `site.yml` to `site.yaml`.
2. open panel
3. the default fields get displayed

**Expected behavior**
1. kirby should load the `site.yaml` file

**Versions**
kirby@3.0.0

**Comment by distantnative** [comment]
This does not only apply to `site.yaml` but all `.yaml` blueprints.

**Comment by lukasbestle** [comment]
We have an idea issue here: https://github.com/getkirby/ideas/issues/150

**Comment by chpio** [comment]
> If you are updating from an early Kirby 2 version and still use .php files for your blueprints, change the file extension to .yml(or .yaml, if you prefer) and remove the PHP code from the top of the files.
> 
> -- https://getkirby.com/docs/cookbook/migration/sites

**Comment by lukasbestle** [comment]
Oh, hm. How did that end up there? Thanks for letting us know, I've fixed it.
