### ISSUE TITLE
load() helper: Classes to load only supported when lowercase

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1451]
If the `load()` helper is called like this:

```php
load([
  'MyPlugin\\Superfile' => 'src/Superfile.php'
], __DIR__);
```

it won't work, as the helper uses `strtolower()` on the class to load, but not on the keys of the classmap array.

To fix this, the helper should run `strtolower()` on all elements in the classmap before registering the autoloader.

**Comment by bastianallgeier** [comment]
✅
