### ISSUE TITLE
Panel: Background setting of files field are ignored in structure field’s table

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1452]
**Describe the bug**
When using image settings for the preview image of a files field, the `back` property has no effect on the table view of a structure field.

**To Reproduce**
1. Create a blueprint, containing a structure field and a files section. Add a `files` field to the structure’s `fields` property and set the background of the preview to `white`:

```yaml
icon:
  label: Icon
  type: files
  multiple: false
  image:
    back: white
```

2. Upload an image with transparency (svg or png).
3. Add a new entry to the structure field and select the upload image as icon.
4. Save/close the structure field.

**Expected behavior**
The table view should display preview images with the background as set in the `files` field.

**Screenshots**

![bildschirmfoto 2019-02-05 um 18 48 37](https://user-images.githubusercontent.com/395617/52293502-4b23df80-2977-11e9-9b7b-f157ba7d09e1.png)

**Kirby Version**
3.0.1

**Desktop (please complete the following information):**
 - OS: macOs 10.14.2
 - Browser: Firefox 65.0

**Comment by joernroeder** [comment]
this actually works for me with 3.0.2-rc1 but i came across the issue as file previews are not using the image settings provided and `pattern` is [hardcoded](https://github.com/getkirby/kirby/blob/feb17027d22a97249f50663365343b159d4302fe/panel/src/ui/components/Forms/Previews/FilesFieldPreview.vue#L5).

![screen shot 2019-02-18 at 15 40 16](https://user-images.githubusercontent.com/270540/52958145-c2a03880-3393-11e9-9f69-1ac5143a91f7.PNG)

![screen shot 2019-02-18 at 15 40 46](https://user-images.githubusercontent.com/270540/52958149-c469fc00-3393-11e9-8126-309c823285b1.PNG)

![screen shot 2019-02-18 at 15 40 58](https://user-images.githubusercontent.com/270540/52958151-c59b2900-3393-11e9-8bed-47f7342eda2e.PNG)

**Comment by bastianallgeier** [comment]
✅ This is now fixed on the develop branch. You can use back, cover and ratio options for the images / files.
