### ISSUE TITLE
`unlisted` status shouldn't be enabled by default on `page`s

### ISSUE THREAD

**Issue by chpio** [getkirby/kirby#1457]
Hi,

the `unlisted` status can be selected for pages by default. But unlisted pages do not show up on [the `pages` presets by default](https://github.com/getkirby/kirby/blob/d62cc7536a709f8346eb2b1a066db835e0372128/config/presets/pages.php#L37), making them "disappear" if the `unlisted` status is selected by accident.

**Comment by distantnative** [comment]
This doesn't sound like a bug to me. You can disable the unlisted status for these pages in their page blueprint: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
