### ISSUE TITLE
More flexible template/snippet path handling

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1459]
Let's say I'm sending an email using the `$kirby->email()` method, but from a Kirby plugin. If the email template is also stored inside the plugin directory, that's currently not possible as the [`Email` class always expects email templates to be inside `site/templates/emails`](https://github.com/getkirby/kirby/blob/3.0.1/src/Cms/Email.php#L94).

To fix this, Kirby needs support for absolute template and snippet paths, so I could do this in the plugin:

```php
$kirby->email([
  'to' => 'peter@lustig.de',
  'template' => dirname(__DIR__) . '/templates/email.php',
  'data' => [
    'num' => '2'
  ]
]);
```

The following changes would be needed:

- [ ] Add a `Toolkit\Path::isAbsolute($path)`method that would check if the given path starts with a slash.
- [ ] Add a `Toolkit\Path::makeAbsolute($path, $basePath)` method that would:
  - Check if the path is already absolute -> return immediately, ignore base path
  - Combine the path and the base path (which would be something like `$kirby->root('templates') . '/emails'`)
  - Check if there is a directory traversal attack (if the resulting absolute path is outside the base path)
- [ ] Everywhere in the system where we currently expect relative paths as input (like [here](https://github.com/getkirby/kirby/blob/3.0.1/src/Cms/Email.php#L94)), check if the given path is absolute. If so, don't do any modifications like prepending `emails/`.
- [ ] In the `template` and `snippet` components (maybe others as well), run `Path::makeAbsolute()` on the given path and continue with that.

This issue is difficult as implementing this requires changes in a lot of places. So it's definitely something for a `3.x` release.

**Comment by distantnative** [comment]
Why don't we rather handle it like normal snippets/templates?

**Comment by lukasbestle** [comment]
What do you mean exactly? As far as I can tell, we already use the normal template system, but with a hardcoded `emails` prefix.

**Comment by distantnative** [comment]
I am sure I am missing somethig, but my current thoughts are:
- Why not register that template via the plugin (https://getkirby.com/docs/reference/plugins/extensions/templates)
```php
Kirby::plugin('your/plugin', [
    'templates' => [
        'emaisl/email' => __DIR__ . '/templates/email.php'
    ]
]);
```
- And then use it.
```php
$kirby->email([
  'to' => 'peter@lustig.de',
  'template' => 'email',
  'data' => [
    'num' => '2'
  ]
]);
```

Shouldn't that work?

**Comment by texnixe** [comment]
@distantnative: The above does actually work, I just tested it without any problem.

Edit: the only question is how to register a plain text version and an HTML version that way, because I can't pass an array of files to the same template name.

**Comment by lukasbestle** [comment]
Oh, if that worked, it would be a much much better solution.

I'm thinking of something like this:

```php
Kirby::plugin('your/plugin', [
    'templates' => [
        'emails/email.html' => __DIR__ . '/templates/email.html.php',
        'emails/email.text' => __DIR__ . '/templates/email.text.php'
    ]
]);
```

I assume this should work, but I can't test it right now. If it does, we can close this issue.

**Comment by texnixe** [comment]
Yep, that works.
