### ISSUE TITLE
Why is there an `email` root?

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1460]
I just saw that we have an [`email` root in the config](https://github.com/getkirby/kirby/blob/3.0.1/config/roots.php#L59-L61), but it doesn't seem to be used for anything because the email templates are stored in `site/templates/emails` now. @distantnative?

**Comment by distantnative** [comment]
They used to be store in their own root. I think that was changed at some point and forgotten to remove the root.

**Comment by lukasbestle** [comment]
Ah, alright. That's what I was assuming, but I wasn't sure. :)

**Comment by bastianallgeier** [comment]
✅
