### ISSUE TITLE
$field->model() in fieldMethods returns itself, instead of container page / user / site

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1462]
Not sure if it's a problem with the docs or the implementation. The current implementation seems to not have many use cases, so I post this here. 

**Describe the bug**
In a `fieldMethods` function, `$field->model()` returns a pointer to the Field itself and not the containing parent page / user / site / file. 

**To Reproduce**
1. Create a fieldMethod plugin:
```php
<?php

Kirby::plugin('a/b', [
    'fieldMethods' => [
        'test' => function($field) {
            var_dump($field === $field->model());
            exit;
        }
    ]
]);
```
2. Use it:
```php
<?php $page->title()->test() ?>
```

3. The output is `bool(true)`

**Expected behavior**
[According to docs](https://getkirby.com/docs/reference/plugins/extensions/field-methods#the-field-object) `$field->model()` should return the "Parent object: $page, $site, $file or $user"

**Kirby Version**
stable 3.0.1

**Additional context**
`$field->parent()` does what `$field->model()` promises.

**Comment by bastianallgeier** [comment]
✅
