### ISSUE TITLE
Field type for URLs and emails

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1463]
In version 2 link fields could contain mailto-links or URLs. That was very useful, e.g. to allow editors to link a button to create an email OR to a page.

In version 3 there is only an url OR email field.

Are there any best practices / solutions for that?

Thx

**Comment by bastianallgeier** [comment]
Hey! Such questions work better for us if you post them in the forum. 

You should check out this awesome plugin by @medienbaecker https://github.com/texnixe/kirby-plugins/issues/625
