### ISSUE TITLE
Instance caching of the Markdown and SmartyPants classes

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1465]
The `markdown` and `smartypants` components currently cache their class instances using `static $markdown` and `static $smartypants`.

The issue is that the `$options` arrays are only respected for the first calls of those components because of the caching. In the CMS that's not an issue as the options don't change, but for some use-cases (like command line tools that deal with multiple separate Kirby sites) it may be an issue.

One solution would be to create `updateOptions()` methods for those `Kirby\Text\*` instances. The instances know which options they are currently configured with, so if the new options haven't changed, they don't need to do anything. Otherwise they need to reinitialize their parser objects with the new options.

----

**Related issue:** #1464

**Comment by distantnative** [comment]
Could this also be solved in the components setup?

```php
'markdown' => function (App $kirby, string $text = null, array $options = [], bool $inline = false): string {
    static $markdown;
    static $config;
    
    if ($config !== $options) {
        $markdown = new Markdown($options);
        $config   = $options;
    }

    return $markdown->parse($text, $inline);
},
```

**Comment by lukasbestle** [comment]
That's a nice and clean solution!

I'd add a code comment above the `if` though to make it 100 % clear what it's doing. Besides that: LGTM!

**Comment by bastianallgeier** [comment]
✅
