### ISSUE TITLE
Move code from the bootstrap.php to a file that is autoloaded

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1475]
If a user loads Kirby using the Composer autoloader instead of requiring the `bootstrap.php` file, the contents of the `bootstrap.php` won't be autoloaded as that file is not included in the Composer autoloading config.

We do two things inside it apart from loading the Composer autoloader:

- PHP version check
- Set `DS` constant

To ensure compatibility, we should move these two features to a file that is autoloaded by Composer.

**Comment by distantnative** [comment]
✅
