### ISSUE TITLE
Not working with exactly PHP 7.1.0 

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#1484]
Kirby is not working, when the PHP Version is exactly 7.1.0.
Is this the desired behaviour because for some reason 7.1.0 is not sufficient?

Can be fixed line 7 in kirby/bootstrap.php like so otherwise:

```
// old
if (version_compare(PHP_VERSION, '7.1.0', '>') === false) {

// new
if (version_compare(PHP_VERSION, '7.1.0', '>=') === false) {
```

**Comment by ralfgoeke** [comment]
Update: Panel seems to demand 7.1.1 at least as well, not sure where to fix that though. ;)

**Comment by lukasbestle** [comment]
Hm, good question. That's something for @bastianallgeier.

The other place is here BTW:

https://github.com/getkirby/kirby/blob/3.0.1/src/Cms/System.php#L337

**Comment by bastianallgeier** [comment]
Nope, that's not desired but a stupid mistake. I will fix it asap.

**Comment by bastianallgeier** [comment]
✅
