### ISSUE TITLE
[Panel] Blueprint option: don't show "—" in select fields if default

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1487]
Wouldn't it be better if a select field with a default option doesn't show the empty option "—"?

**Comment by distantnative** [comment]
@bastianallgeier This seems an issue that we have moved forwards and backwards quite a bit in K2 already. Still not sure which way is the better one.

**Comment by lukasbestle** [comment]
There are probably use-cases for both, so it should probably be a blueprint option.

**Comment by distantnative** [comment]
Closing in favour of https://github.com/getkirby/kirby/issues/1664
