### ISSUE TITLE
[Panel] Plugin artefacts after removal

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1491]
**Describe the bug**
I had some trouble with @distantnative's [Retour plugin](https://github.com/distantnative/retour-for-kirby) so I decided to uninstall it by removing the submodule. This solved my issue (which was PHP related) but it seems like Kirby did not clean up the assets served for the panel because I still see plugin artefacts in the menu (see the `view.retour` entry):

<img width="149" alt="grafik" src="https://user-images.githubusercontent.com/25466/53091202-a2968380-3511-11e9-8bbe-0d596b0b659e.png">

There is still a `logs` folder inside `/site` which was created by Retour but that shouldn't cause this side effect in my eyes.

**To Reproduce**
1. Install Retour as submodule.
2. Browse to a few invalid URLs on the site to make sure Retour has logged something.
3. Visit the Retour interface in the panel.
4. Uninstall Retour by removing the submodule.
4. Revisit the panel.

**Expected behavior**
After removing the submodule, Kirby should purge the style and script assets of the panel to make sure no artefacts are visible.

**Kirby Version**
3.0.2 and current `develop` branch used on Firefox for Mac (macOS 10.14.3 18D109)

**Comment by bastianallgeier** [comment]
✅
