### ISSUE TITLE
[Panel] Multiselect field returns error with option: "search: false"

### ISSUE THREAD

**Issue by lastloop** [getkirby/kirby#1493]
**Description**
The multiselect field returns a TypeError: "t.$refs.search is undefined" in the panel when the option "search: false" is set in the blueprint.

**To Reproduce**
Add the following options to a page blueprint and try to use the multiselect field in the panel.
```json
fields:
  tags:
    label: Categories
    type: multiselect
    search: false
```

**Expected behavior**
The option "search: false" should disable the search in the multiselect dropdown.

**Kirby Version**
3.0.2

**Console output**
```
 TypeError: "t.$refs.search is undefined"
    open http://localhost/starterkit/media/panel/93541ca844cc8e0766af2148bee73692/js/app.js:1
    pe http://localhost/starterkit/media/panel/93541ca844cc8e0766af2148bee73692/js/vendor.js:39
    ae http://localhost/starterkit/media/panel/93541ca844cc8e0766af2148bee73692/js/vendor.js:39
```

**Desktop**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 66.0b8

**Comment by bastianallgeier** [comment]
✅ Will be fixed in 3.1.0
