### ISSUE TITLE
[Cache] System conflates content from different domains

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1496]
**Describe the bug**
If two or more Kirby installations are running on the same server and they each have the same type of caching mechanism enabled, their caches will start intermingling with each other. This is especially problematic with something like the APCU cache; users of file-based caching can adjust the cache root as a workaround.

**To Reproduce**
1. Enable something like APCU caching in the general `config.php` file or on multiple domain-specific config files.
2. View a page (like the homepage) of something like `dev.example.com`; this should now be captured into the cache.
3. View the "same" page of another domain like `www.example.com`.
4. The page will be displayed from the **dev** cache; content and links will all point to **dev** resources, not the intended _www_ resources.

**Expected behavior**
There should be some sort of automatic cache segmentation by domain, with possible overrides in a config file to express that certain domains _should_ share caches. (Though, I'm not sure why this behavior would be particularly wanted, especially for `pages` cache).

**Kirby Version**
`3.0.2`

**Additional context**
Caching is automatically segmented for multilingual sites; I view this as something very similar to that.

I cannot come up with a convincing scenario where the current behavior would be expected.

There might be some use case specific scenarios where a shared cache might be useful across multiple domains (like caching remote API calls), but I think this shared behavior should be opt-in.

**Comment by neildaniels** [comment]
This is particularly annoying if a plugin enables caching for itself by default.

**Comment by bastianallgeier** [comment]
We have a solution for it that would turn on a auto domain prefix, but I'm not entirely sure if we should put it in a patch release or wait for 3.2.0  

In 3.1.3 we will introduce a generic prefix option for any cache that you can use to fix the problem for yourself in the meantime.

**Comment by lukasbestle** [comment]
✅
