### ISSUE TITLE
[Panel] Page Rename Gets Undone When Saving Pending Content

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1497]
**Describe the bug**
In the Panel, if you have pending content changes on a page, rename the page, then save the pending content changes, the title will actually be saved as the _original_ title and the page header will be disconnected from what is actually saved.

**To Reproduce**
1. Open/create a page in the panel with a text field, assume original title is "Test Page" and content is "Foo"
2. Change text field to "Foo Bar" but **do not** actually save the content
3. Rename the page to "Test Page 2". Click the "Rename" button to commit that change.
4. Save the overall page content (to commit the pending content to disk)
5. Either, reload the page or click on the "Rename" button again.
6. Note how either the reloaded page or the "Rename" modal will show the original title of "Test Page" and not "Test Page 2".

**Expected behavior**
The renamed title of "Test Page 2" should actually persist.

**Screenshots**
![screen recording 2019-02-21 at 4 52 08 pm2](https://user-images.githubusercontent.com/417182/53212703-df8a7500-35fa-11e9-856b-c23d1ab52729.gif)

**Kirby Version**
`3.0.2`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser: Safari
 - Version: 12.0.3 (14606.4.5)

**Comment by bastianallgeier** [comment]
✅ Will be fixed in 3.1.0
