### ISSUE TITLE
[Cms] Content is not kept when programatically creating users

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#1500]
**Describe the bug**
Creating a user with `$kirby->users()->create([..., 'content' => $data])` creates the user.en.txt file in `/accounts/{user-id}/` but this file is empty despite `$data` having fields with values.

**To Reproduce**
1. Create an account with extra fields in `content`:
```php
$kirby->impersonate('kirby');

$user = $kirby->users()->create([
    'email'    => 'toto@liip.ch',
    'name'     => 'Toto',
    'role'     => 'blogger',
    'language' => 'en',
    'content'  => [
      'firstname' => 'to',
      'lastname' => 'to',
    ],
]);
```
2. Open the user account folder
3. An `index.php` exists with the email, language, role, etc. ✅ 
4. A `user.en.txt` exists but is empty ❌
👉 `firstname` and `lastname` have disappeared.

**Expected behavior**
The data passed in `content` during account creation should be saved in the user file.

**Kirby Version**
3.0.2

**Additional context**
PHP 7.2.15

**Comment by bastianallgeier** [comment]
✅
