### ISSUE TITLE
Count Method isn't working anymore

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#1503]
The default Count Method isn't working anymore. In past I’ve used this code and it always works:

```
<?php if ( count($slideshow = $page->slideshow_slides()->toStructure()) ) : ?>
  ...
<?php endif; ?>
```

But since Kirby 3 it throws a error and I have to use this one instead. Not sure if it's a bug ...

```
<?php if ( $slideshow = $page->slideshow_slides()->toStructure()->count() ) : ?>
  ...
<?php endif; ?>
```

**Comment by bastianallgeier** [comment]
I wasn't aware that our collections are no longer countable. That's a bit weird. I have to double check that. But the `->count()` method is definitely the preferred method.

**Comment by texnixe** [comment]
Kirby 2: `class Collection extends I implements Countable {`
Kirby 3: `class Collection extends Iterator`

**Comment by bastianallgeier** [comment]
✅
