### ISSUE TITLE
String "01." creates an ordered list and the rest of the field is the content

### ISSUE THREAD

**Issue by besteansichten** [getkirby/kirby#1504]
I have a structure with a date-field and when the content of the field starts with the string "01." there is an ordered list "ol" created with the rest of the field as content.

For example I have "01. Februar 2019" then the website is showing "Februar 2019" and when I look in the source code there is:
```
<ol>
    <li>Februar 2019</li>
</ol>
```

Here are simplified blueprint(fields)-, content- and template-snippets:
```
label: Events
type: structure
fields:
  date:
    label: Date
    type: text
```
```
Events: 

- 
  date: 01. Februar 2019
```
```
<?php foreach ($page->events()->toStructure() as $event): ?>
    <div class="date">
      <?= $event->date()->kt() ?>
    </div>
<?php endforeach ?>
```
Kirby 3.0.2

**Comment by texnixe** [comment]
That is normal markdown behavior, not a bug. Why do you use `kt()` to output the string? If you use `html()` instead, you'll be fine. Apart from that, why don't you use a date field instead of the text field to ensure that you get a proper date?

**Comment by besteansichten** [comment]
Thank you for the explanation and the tips! I'm relatively new to kirby and sometimes I reuse some snippets, do copy & paste, do some editing for special needs and then I am often happy that everything works. :)

I will try `html()` ... and will have a closer look at the date field.

**Comment by texnixe** [comment]
Whenever you have problems, the best place to come to with questions is our [forum](https://forum.getkirby.com). Helps to keep our issue list clean as well, btw :wink:

**Comment by besteansichten** [comment]
Thanks!
I'm ashame, I know. I'm already a "silent" reader of it ... but here I really thought I found a bug and wanted to prevent: "the best place to come with bugs is Github" ... :) I was really thinking about it!

And moreover I must admit, bug-finding seems to be too "pro" for me. :) When I think again about the problem, even for me it's quite obvious that 01. is the starting point of an ordered list ... unfortunatelly I'm not very used to markdown, but that seems to be a minor task ...

See you in the Forum, which I really like a lot! Very very friendly and human atmosphere! I will freeze my Github-Account till 2021 ... the year I'll be pro enough. :)

**Comment by texnixe** [comment]
@besteansichten Oh, I'm sorry if I sounded rude or as if I was telling you off 🤗. It was just meant as a friendly reminder to join us in the forum, where we can usually sort out stuff very quickly (and then open issues when necessary).

**Comment by lukasbestle** [comment]
@besteansichten That's no issue at all. You as the user often can't know if something is a bug in Kirby or in your own code, it's the same for us when we use software we haven't written ourselves (or sometimes even when we use Kirby). ;)

If you think something is a bug, feel free to post here. If you are not sure, you can always post in the forum. In the end it matters that the bug or problem gets fixed – not on which platform. :)

**Comment by besteansichten** [comment]
@texnixe No worries. There was no rudeness noticable for me! I thought my smilies communicate a little bit between the lines ... and as I said, I honestly like the friendly atmosphere and openness of the whole kirby community. Really!
@lukasbestle Thanks! I feel a little bit encouraged :) ...

**Comment by besteansichten** [comment]
Btw ... I just read my title again and had to laugh ...
The title is the most important part to get the necessary attention! :) Even if it's just because people think: Häh?
