### ISSUE TITLE
[Panel] Slugify.js does not properly convert German Umlauts

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1505]
**Describe the bug**
German umlauts (and probably other foreign characters are not correctly converted to slug. `Bücher` becomes `bucher`instead of `buecher`.

According to their charMap, that's what the library does, but probably not what we want and not in line with behavior in Kirby 2

**To Reproduce**
1. Go to Panel
2. Create a new page with umlaut in title
4. See wrong slug conversion

**Expected behavior**
ä => ae, ü => ue, ö => oe ...

**Comment by lukasbestle** [comment]
It depends on the language. There was a similar issue the other way around for Kirby 2 (e.g. for Turkish it's correct as far as I remember) and also a discussion about the Kirby 3 behavior (but I can't find it 😢).

**Comment by texnixe** [comment]
You probably mean this one: https://github.com/getkirby-v2/panel/issues/773 from Kirby 2, Kirby 3 I don't remember. 

But for German, the current behavior is incorrect. But at least the `slug()` method produces the same result...

https://github.com/getkirby/ideas/issues/118

The idea with custom overrides per language sounds like a good idea.

**Comment by nilshoerrmann** [comment]
Just chiming in to point out that – while the names are identical – we are talking about two different Slugify libraries: [the one mentioned in my ideas post](https://github.com/cocur/slugify) is PHP based and offers language specific transliterations: https://github.com/cocur/slugify/tree/master/Resources/rules

**Comment by distantnative** [comment]
Will close this in favour of https://github.com/getkirby/kirby/issues/1635
