### ISSUE TITLE
[3.0.3 RC-1] Multi Language t() gets wrong language 

### ISSUE THREAD

**Issue by carstengrimm** [getkirby/kirby#1506]
I have a multi language setup and upgraded to 3.0.3 rc-1 and had the issue that some translations are missing even if the key => value pair has been set.

- default language DE
- DE as active language
- Content files show as translated
- echoing t() shows the EN language set.

Rolling back to 3.0.2 seems to work fine.

Translations are stored within 2 different plugins.

**Comment by bastianallgeier** [comment]
✅
