### ISSUE TITLE
[Cache] APCu does not prefix entries w/ bucket name

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1507]
**Describe the bug**
When using multiple APCu [custom] caches, there is a risk that the cache keys collide.

```php
    'cache' => [
        'foo' => [
            'active' => true,
            'type' => 'apcu',
        ],
        'bar' => [
            'active' => true,
            'type' => 'apcu',
        ],
    ],
```

**To Reproduce**
1. Add something to foo cache: `kirby()->cache('foo')->set('my-cache-key', 'This is foo.')`
2. Add something to bar cache with the same key: `kirby()->cache('bar')->set('my-cache-key', 'This is bar.')`
3. Attempt to retrieve the thing from the foo cache: `kirby()->cache('foo')->get('my-cache-key')`

**Expected behavior**
This should return "This is foo." Instead, "This is bar." is returned.

**Kirby Version**
`3.0.2`

**Additional context**
Because APCu only has a single repository of cache keys, it seems appropriate to prefix the cache value keys in the system with the name of the cache bucket.

In this case, the cache keys could resemble something like:
- foo_my-cache-key
- bar_my-cache-key

**Comment by neildaniels** [comment]
It would be super if the APCu cache driver also used `apcu_delete(new APCUIterator('#^myprefix_#'));` instead of `apcu_clear_cache()` to avoid removing cache items from separate buckets.

**Comment by distantnative** [comment]
Related to separting caches across domains: https://github.com/getkirby/kirby/issues/1496

**Comment by bastianallgeier** [comment]
As described in my comment for your other ticket, there's now a prefix option in 3.1.3 that you can use to fix this. We also integrated the iterator.

**Comment by lukasbestle** [comment]
✅
