### ISSUE TITLE
`isEmpty()` and `isNotEmpty()` fails if value is `0`

### ISSUE THREAD

**Issue by olach** [getkirby/kirby#1508]
**Describe the bug**
When using the methods `isEmpty()` and `isNotEmpty()` on a field, they fail to return the correct boolean if the value is `0` .

**To Reproduce**
1. Create a text field in a page blueprint:
```yml
margin_top:
  type: text
  label: Margin top
```
2. In the Panel, enter `0` as the value in the text field.
3. In the corresponding page template, enter this code:
```php
if ($page->margin_top()->isEmpty()):
  echo 'Field is empty';
endif;

if ($page->margin_top()->isNotEmpty()):
  echo 'Field is not empty';
endif;
```
4. The output of this code is incorrectly `Field is empty`.

**Expected behavior**
The template should output `Field is not empty`.

**Kirby Version**
3.0.2

**Additional context**
The methods `isEmpty()` and `isNotEmpty()` is using the PHP method [empty](http://php.net/manual/en/function.empty.php). This method returns false for the value `0`. You should do additional checks, for example if the field has one or more characters, the field should be considered `not empty`.

I have only tested this on the regular text field. When you are fixing this, you should test all other fields too.

**Comment by bastianallgeier** [comment]
✅
