### ISSUE TITLE
[Panel] translate: false ignored for field inside structure field

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1509]
**Describe the bug**
When I add `translate: false` to a field inside a structure field, the field is still editable in all languages.

**To Reproduce**
1. Dowload Starterkit
2. Add languages
3. Open `about.yml` and set a field inside the structure field to `translate: false`.

**Expected behavior**
The field should not be translatable.

**Kirby Version**
3.0.2 and 3.0.3 RC 1

**Screenshots**
The API response for the field contains `translate: false`, but the field is still editable. To make sure it works for regular fields, I also added `translate: false` to the »Email« and »Phone« fields.

<img width="1240" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/53495126-94131380-3a9f-11e9-8fe9-b7b15eb39328.png">

**Comment by bastianallgeier** [comment]
✅
