### ISSUE TITLE
Don't store session id in user.php

### ISSUE THREAD

**Issue by ponychicken** [getkirby/kirby#151]
This is insecure for a lot of reasons. 
* It's not possible to have different permission bit for users being able to change a password vs just login in
* It's now insecure to store a whole website on a public git repo, as you will be leaking possibly still active sessions.

Suggestion: Store the session in a different file with a special extension (.session) and add this type of file to .gitignore.

**Comment by bastianallgeier** [comment]
I moved to a new session architecture, which no longer works with tokens in user files. You can already find it on the develop branch.
