### ISSUE TITLE
[Panel] Fields in RTL not align content correctly

### ISSUE THREAD

**Issue by raoulaudouin** [getkirby/kirby#1510]
**Describe the bug**
When a right-to-left language is selected in the panel, all fields stay left-to-right. This prevents adding a right-to-left content properly.

**Expected behavior**
When a right-to-left language is selected, fields should appear right-to-left by default.
Since right-to-left languages often include left-to-right content, it would also help to be able to define the direction of each field (like `text` and `textarea`) in its blueprint options.

**Kirby Version**
3.0.2

**Comment by distantnative** [comment]
Could it be that at the moment none of our languages is set as RTL in the panel?

Cause if I set `"translation.direction": "rtl"` in `fa.json` it seems to align all fine and fields also fill from right to left.

What Panel translation language have you chosen?

**Comment by distantnative** [comment]
Or do you mean the content language? The one here on the right:
<img width="497" alt="Screenshot 2019-03-19 at 20 24 18" src="https://user-images.githubusercontent.com/3788865/54635671-05cdf400-4a85-11e9-903e-dff8ce547599.png">

In that case, what would be the desired outcome, when switching to an RTL language? The layout stays the same (since the Panel language is still LTR), but the fields fill from RTL?

**Comment by distantnative** [comment]
@raoulaudouin would be great if you have any insights to my questions above. Thanks!

**Comment by SamuelRiversMoore** [comment]
+1 
Panel is absolutely not easy to use for ltr-languages users, such as Farsi or Arabic, because text fields are displaying their content in the wrong direction...
Maybe could it be simply possibe to use the "direction" entry defined inside the /site/languages/*.php files to set every text field's direction in the panel?

**Comment by distantnative** [comment]
@SamuelRiversMoore 
I really would like to get it right. It makes definitely sense to take that information from the language file as you described.

My current thoughts:
- Change the Panel layout only to RTL when the interface language chosen by the Panel user in his user settings is a RTL language. Farsi is the only one we feature at the moment, but I saw that it has the wrong info in the .json file.
- Change the direction of fields/inputs based on the currently selected content language. This way when you edit e.g. English it's LTR, when you switch to edit e.g. Farsi it's RTL. The layout of the Panel (sections etc.) is not affected.

**Comment by SamuelRiversMoore** [comment]
Yeah I think these two improvements would definitely be a good way to handle rtl languages both for the panel interface and for the content editing.
Thank you for the follow-up :-)

**Comment by raoulaudouin** [comment]
@distantnative 
My problem came from the content language, my main language was English and my second was Arabic. When selecting Arabic as content language in the panel, the fields (text and textarea) would stay LTR so I was unable to enter proper Arabic information.
As you mentioned, I think that in this case the general layout of the panel (sections etc.) should not change to RTL when Arabic is selected, only the individual fields should change to RTL and the general layout stay the same.
In general, I think it would already help to add in the blueprints for each field (text, textarea, etc.) a property "direction" that would get the value "ltr" (by default) and "rtl" or something similar. Since Arabic often includes LTR content as well (English names, email addresses, etc.) this feature would be specifically interesting for RTL contents.

In Kirby 2, when working with Arabic content I would simply create custom fields "RTL Text" and "RTL Textarea" that would do all the necessary job.

**Comment by SamuelRiversMoore** [comment]
Hello, I made a small plugin to temporary fix this issue : https://github.com/SamuelRiversMoore/rtl-panel

**Comment by guidoferreyra** [comment]
I second the idea to have a "direction" property for text  and textarea fields, sometimes is needed to have RTL fields in a LTR language. Is there any workaround for have this now?

**Comment by afbora** [comment]
I'm dealing with this issue, but I was unsure about one thing. 
Which one do you think is more useful? 
Only specific inputs or whole pageview except topbar? 🤔 

**RTL Support Only Text, Textarea, Tags Input**

![screen-capture-249-هنالك العديد من الأنواع المتوفرة لنصوص - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/92216741-629eb380-ee9f-11ea-9ece-6a0d53b51ae5.png)

**RTL Support Whole PageView (Excluded Topbar)**

![screen-capture-252-هنالك العديد من الأنواع المتوفرة لنصوص - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/92217000-c1642d00-ee9f-11ea-88bf-c5410508c88a.png)

**Comment by bastianallgeier** [comment]
@afbora good question! I'm very interested in your replies @SamuelRiversMoore @raoulaudouin

**Comment by SamuelRiversMoore** [comment]
Personally I would go for the first proposal : keeping the panel UI direction as LTR so the language swither and other important UI elements remains at the same place when the language is switched.

**Comment by afbora** [comment]
@SamuelRiversMoore Do you think `Text`, `Textarea` and `Tags` inputs are enough for RTL support? By the way, do you think it is important that labels are also RTL?

**Comment by SamuelRiversMoore** [comment]
@afbora I think we should start at least with `Text` and `Textarea` inputs. It would massively improve the user experience for LTR writers in most cases. About the `Tags` field I'm less convinced it is necessary, but why not...
Maybe the `structure` field should also be affected but this case is a bit more complex as it handles multiple types of content. 

No need to change the direction of the labels IMHO as this issue is more related to the ability to _write_ content in LTR languages (which is not really possible yet). 

What do you think?

**Comment by afbora** [comment]
@SamuelRiversMoore I tried to fix on #2810 You can test with [dist.zip](https://github.com/getkirby/kirby/files/5183328/dist.zip).

**Comment by afbora** [comment]
@SamuelRiversMoore Also Persian translation name should be `فارسی` right? Now translated `انگلیسی` mean `English` :))

https://github.com/getkirby/kirby/blob/3.4.2/i18n/translations/fa.json#L376

**Comment by bastianallgeier** [comment]
✅
