### ISSUE TITLE
[Panel] Login View is taller than viewport

### ISSUE THREAD

**Issue by dwd0tcom** [getkirby/kirby#1512]
**Describe the bug**
The panel login screen is taller than the actual viewport. It creates some padding that a scrollbar appears.

**To Reproduce**
1. Go to  /panel
2. Scroll! (works in every browser except Firefox)

**Expected behavior**
The login from does not need to be scrolled, so a scrollbar is not necessary.

**Kirby Version**
3.0.2.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser [all latest] chrome, safari, opera

**Additional context**
It's working when you remove the  `padding-bottom: 6rem;` from the `.k-panel-view`

**Comment by bastianallgeier** [comment]
✅
