### ISSUE TITLE
[Cms] Custom `num` causes `page.changeNum:after` to be fired on every save

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1513]
**Describe the bug**
When using a Query Language-based `num:` attribute in a Blueprint, if you make changes to other fields on the page, it will always cause the `page.changeNum:after` hook to fire.

This does not affect normal `num:` behavior. I have not tested with `num: date` or `num: datetime`.

**Post Blueprint**
```yaml
title: Blog Post

num: '{{ page.created.toDate("YmdHi") }}'

preset: page

fields:
  created:
    label: Published Date
    type: date
    time: true
    default: now
  text:
    label: Text
    type: textarea
```

**Sample Plugin w/ Hooks**
This plugin will cause the plugin to throw errors, but inspecting the response will show the echo statements.
```php
Kirby::plugin('thestreamable/cloudflarecache', [
    'hooks' => [
        'page.changeNum:after' => function ($page, $oldPage) {
            echo '[page.changeNum:after]';
        },
        'page.update:after' => function ($page, $oldPage) {
            echo '[page.update:after]';
        },
    ],
]);
```

**To Reproduce**
1. Open the panel and show a web inspector's network tab to view requests
2. Open an existing, public page with that uses this Page blueprint
3. Make changes to the `text` field
4. Click save
5. You'll get an error, because my sample code is not well crafted, but view the response of the most recent web request

**Expected behavior**
You should just see the statement "[page.update:after]" echoed out. However, you actually see "[page.update:after][page.changeNum:after]".

**Kirby Version**
`3.0.2` and `3.0.3-rc.2`

**Additional context**
In this scenario, the content changes have absolutely no effect on the `num` (which only depends on `created`). The only hook that should be fired is `page.update:after`.

I'm not actually sure what is _supposed_ to happen if you make changes to content that _also_ affects the num field. For example, if you made changes to the "created" date field and clicked save. That should certainly cause a `page.update:after` hook to fire.

I'm not sure if it's supposed to _also_ update the `num` attribute of an already published page.
If the original published num should remain, then there should never be a case where `page.update:after ` and `page.changeNum:after` are fired together.
If the published num should be updated, then that's the only time where both hooks should be fired.

**Comment by bastianallgeier** [comment]
✅
