### ISSUE TITLE
$page->previewUrl() Generates Malformed URLs if URL Already Includes Query Parameters

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1517]
**Describe the bug**
When a page is in draft, if a Blueprint specifies a custom preview URL pattern that also includes query parameters, the `$page->previewUrl()` function will just tack on another `?` (but should be a `&` instead).

```yaml
options:
  preview: "{{ page.url }}?ispreview=1"
```

**To Reproduce**
1. Adjust a Blueprint to have the preview option shown above
2. Create a draft page of that template type
3. Click the open button
4. Browser opens a URL resembling `http://localhost/test-post?ispreview=1?token=123abcdef`

**Expected behavior**
Preview URL should resemble `http://localhost/test-post?ispreview=1&token=123abcdef`

**Kirby Version**
`3.0.3-rc.2`

**Comment by lukasbestle** [comment]
Good point! :)

Until we implement/fix this, you could check for the `token` param in your template – then you don't need the `ispreview` param. The `token` is only passed for previews after all.

**Comment by neildaniels** [comment]
The `token` parameter is _only_ used for full drafts though. I want/need a parameter that's tacked on for all "Open" links from the Panel, even if it's listed/unlisted.

**Comment by lukasbestle** [comment]
Ah, alright. Then a custom param is indeed the only way.

**Comment by bastianallgeier** [comment]
✅
