### ISSUE TITLE
Wrong date saved when field type date is set to time: false

### ISSUE THREAD

**Issue by CydGoblin** [getkirby/kirby#1518]
**Describe the bug**
When you use the field type date with `time: false` it saves the wrong day. I saves the next day to the one you pick.

**To Reproduce**
1. Start with starterkit
2. Edit the blue print for note. In  the field type date, set the property time to false
3. On the panel, change the date to Today and save
4. Open the link to the note you modified. On the panel you see the right one, on the note post you see the next day. The .txt file for the note has the wrong date too.

**Expected behavior**
The note post and .txt file should have the date picked on the panel, not the next day.

**Screenshots**
Date set on panel:
![image](https://user-images.githubusercontent.com/4932347/53592750-296fdf80-3b54-11e9-9b71-2f8750932bdb.png)

On the note post you see the next day
![image](https://user-images.githubusercontent.com/4932347/53592761-312f8400-3b54-11e9-83bd-fcf1b5bdbaf6.png)

Same in the .txt file
![image](https://user-images.githubusercontent.com/4932347/53592831-5d4b0500-3b54-11e9-9a79-20c316fa916f.png)

Blueprint
![image](https://user-images.githubusercontent.com/4932347/53592787-3bea1900-3b54-11e9-9bc2-c74c5bdc5793.png)

**Kirby Version**
3.0.2

**Console output**
No errors in console

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: Firefox
 - Version 60.0.1

**Comment by CydGoblin** [comment]
After more research looks like it was wrong configuration on my MAMP (date.timezone on ini.php) and coincidentally there was some issues on the real server when I tried to use to test it. Seems like It works fine now, but I'll report back if anything else happens.

**Comment by distantnative** [comment]
Please report back if you encounter the porblem again and reopen this issue then. Thank you!
