### ISSUE TITLE
Problem saving floats on Windows

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1519]
**Describe the bug**
I just found out that setting [`setlocale(LC_NUMERIC, 'en_US')`](https://github.com/getkirby/kirby/blob/develop/src/Data/Yaml.php#L32) does not always work. At least on Windows. I tested a bit around and the value `'C'` [seems to work](https://stackoverflow.com/questions/5231620/what-does-set-localelc-ctype-c-actually-do) here (also the initial value on my system). And since `setlocale()` accepts multiple parameters I could resolve the issue by simply adding `'C'` as a fallback `setlocale(LC_NUMERIC, 'en_US', 'C')`.

For some reasons the current implementation `setlocale(LC_NUMERIC, 'en_US')` works on some Windows machines. Guess it depends on the installed locales. I'm also not sure if a Windows-Server is affected by this.

Edit:
Seems like `en-US` instead if `en_US` also works. This locale stuff is weird as hell.
http://codel10n.com/what-is-correct-locale-tag-en_us-vs-en-us/

**Desktop:**
 - Windows 10
 - Local PHP-Server

**Comment by bastianallgeier** [comment]
🙈

**Comment by bastianallgeier** [comment]
It looks like using C as value works on macOS as well. I let travis run over it and if this works, I will include it like that.

**Comment by bastianallgeier** [comment]
yep, it passes. Nice! I consider this closed then.
