### ISSUE TITLE
Missing home content folder results in "Not found"

### ISSUE THREAD

**Issue by BaerMitUmlaut** [getkirby/kirby#1521]
**Describe the bug**
If `/content/home` is missing, Kirby only displays "Not found" without any kind of information what was actually not found, even with `debug` set to `true`. I encountered this problem when migrating a Kirby 2 project.

Additionally, neither the migration guide nor the content docs mention that this folder is essential for Kirby to function.

**To Reproduce**
1. Get the starter kit
2. Delete `/content/home`
3. Go to your kirby root
4. See "Not found"

**Expected behavior**
Any kind of information on what exactly was not found would be helpful, especially with debug enabled.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9693842/53638806-bb94e800-3c27-11e9-82a5-f056d42507d4.png)

**Kirby Version**
`3.0.2`

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Browser: Firefox
 - Version: 65.0

**Additional context:**
This might be the culprit:
https://github.com/getkirby/getkirby.com/blob/c350e206b8fd8806f208e1a760f1dfce35b61fd2/kirby/src/Cms/App.php#L518

**Comment by bastianallgeier** [comment]
✅ This is fixed on the develop branch and will be in 3.1.0

**Comment by BaerMitUmlaut** [comment]
Thanks, that was quick!
