### ISSUE TITLE
blueprint/pages - custom folder for templates

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#1525]
**Folderstructure in blueprint/pages**
I create a new folder under blueprints/pages e.g modules, and put a template in it. this is just to have a nice folder structure under pages. like this:

Folder:
- blueprints
-- files
-- pages
--- modules
---- module-headline.yml
---- module-text.yml

Folder:
- snippets
-- modules
--- module-headline.yml
--- module-text.yml

```
Blueprint:
sections:
  parts:
    ....
    templates:
      - modules/module-headline
      - modules/module-text
```
 
The problem is, Kirby don't like the folder "modules" or what ever folder,  in the blueprint templates list. Without this folder it works like expected, but i really like to use a folder under pages because of keep file pairs in sync. There is no error in the panel, but kirby loads the default.yml file instead of the modules/xxx template. 
 

**Expected behavior**
You can add custom folder structure in blueprint templates

```
    templates:
      - modules/module-headline
```
 
**Screenshots**
<img width="807" alt="bildschirmfoto 2019-03-01 um 19 17 29" src="https://user-images.githubusercontent.com/5121132/53657528-b26f3f80-3c56-11e9-8023-544fcc6a6202.png">
 
**Kirby Version**
3.02
 
**Desktop (please complete the following information):**
 - OS: mojave
 - Browser chrome
 - Version 72.0.3626.119 (Offizieller Build) (64-Bit)

**Comment by lukasbestle** [comment]
I see the use-case, but unfortunately subdirectories for blueprints are not possible as the blueprint name is stored as the file name of the module page's text file (so it would have to be `content/your/page/`**`modules/module-text.txt`**). That's the reason why slashes in blueprint names won't work.

You can however use any other character to separate the "type" of page blueprint from the name. In your example you have already used `module-` as the prefix. That's one way, alternatively you could use `module.` or `module_`. Whatever you prefer. :)
