### ISSUE TITLE
Mægazine-Theme Markdown render have no effect

### ISSUE THREAD

**Issue by ennnnno** [getkirby/kirby#1528]
_Can't add an issue at starterkit, so I drop a minor one here and hope it's ok._

**Describe the bug**
The list & quote Markdown markup at Mægazine-Theme has no effect. Not really a bug, but a design issue for explanations and showcase.

**To Reproduce**
1. (un-)ordered list markups has no effect,
2. greater-than sign markup for a quotation neither

**Expected behavior**
You know, some different than p-tag.

**Screenshots**
![maegazinemarkdown](https://user-images.githubusercontent.com/2668716/53696721-5fb69480-3dca-11e9-96ed-4891025e06a7.png)

![panel](https://user-images.githubusercontent.com/2668716/53696723-63e2b200-3dca-11e9-8c39-90093bce35c3.png)

**Kirby Version**
3.0.2

**Console output**
HTML output (ul, ol & q) is fine. I think it depends on the theme.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Chrome
 - Version 65.0.2, 72.0.3626.119

**Smartphone (please complete the following information):**
 - Device: several [iPhone se and X, iPad]
 - OS: iOS12.1.4
 - Browser firefox, safari

**Comment by texnixe** [comment]
This is not a bug, the theme just doesn't have styles for those elements. The Starterkit is just an example of how to use Kirby and the Panel, not a full fledged theme with all the styles you could possibly need.
