### ISSUE TITLE
Calling `toDate()` on a date field in a structure throws error

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1529]
**Describe the bug**

In an example like this:
```
<?php foreach(page('events')->events()->toStructure() as $event): ?>
  <?= $event->date()->toDate('Y-m-d) ?>
<?php endforeach ?>
```
calling the `toDate()` method throws error "Call to a member function toDate() on integer" whereas ` <?= $event->date('Y-m-d) ?>` works fine.

**To Reproduce**
1. Create a struture field with a date field
2. Call method as in above code snippet

**Expected behavior**
The date field within a structure field should in the same way as a date field outside of a structure field.

**Kirby Version**
3.0.3 rc-3

**Comment by bastianallgeier** [comment]
✅
