### ISSUE TITLE
Config option to set base URL not available

### ISSUE THREAD

**Issue by grahamharper** [getkirby/kirby#153]
I've just installed Kirby 2 for the first time. I'm having a problem with the auto-detection of the site URL. Is it possible to set the base URL manually like you could in the Kirby 1 config?

When my shared hosting provider creates vhosts they prepend the ServerName with "www." for some reason. So when I setup a new host, say, blog.example.com, then the ServerName will be www.blog.example.com. As a result when Kirby builds URLs from the ServerName they're incorrect.

**Comment by bastianallgeier** [comment]
The URL option will be back in the next release. It will not be in the default config, but the option will be enabled again.
