### ISSUE TITLE
[Cms] Collections should dispatch cloned copies

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1533]
**Describe the bug**
When retrieving a collection in multiple places, the _exact_ same collection is distributed. This has the annoying side effect that additions to that collection are not local, but global.

```php
$servicesA = collection('services');
echo 'A:' . $servicesA->count() . '<br>'; // output: 15
$servicesA->add(page('deals'));
echo 'A:' . $servicesA->count() . '<br>'; // output: 16

$servicesB = collection('services');
echo 'B:' . $servicesB->count() . '<br>'; // output: 16 (but 15 expected)
```

**To Reproduce**
1. Set up a collection to do something like: `return $site->find('some/pages')->children()`
2. Retrieve that collection like `collection('services')`
3. Add a page to that collection (that isn't already in it)
4. Re-retrieve that collection from the `collection()` helper

**Expected behavior**
The final `collection()` helper should have returned a collection that _does not_ have the added page.

**Kirby Version**
`3.0.3-rc.3`

**Additional context**
I actually kind of expected the collection callback to be called every time; it seems like it is only executed once (at most) and holds onto that collection. The behavior of invoking the callback once seems fine, but I think right before the collection is returned to the call site, it should be cloned.

**Comment by distantnative** [comment]
Adding another bug to this:

```php
$collections = new Collections([
            'test' => function ($a, $b) {
                return $a . $b;
            }
        ]);

        $result = $collections->get('test', [
            'a' => 'a',
            'b' => 'b'
        ]);

        $this->assertEquals('ab', $result);

        $result = $collections->get('test', [
            'c' => 'c',
            'd' => 'd'
        ]);

        $this->assertEquals('cd', $result);
```

Will fail as the callback result is cached with the first data set and returned, disregarding the different new data set.

**Comment by bastianallgeier** [comment]
✅
