### ISSUE TITLE
[Plugins] Lazy-load more plugin extensions

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1538]

**Comment by distantnative** [comment]
@bastianallgeier Do you have specific ones in mind? I don't at the moment, maybe we should think about this a bit more first and open a new issue when there are specific ideas?

**Comment by bastianallgeier** [comment]
Yep, let's open separate issues! I don't have anything urgent in mind at the moment.

**Comment by distantnative** [comment]
@bastianallgeier maybe I also liked the idea to get the issue count below 50 :P

**Comment by bastianallgeier** [comment]
@distantnative that's definitely a plus, but to be honest I think we've grown wiser with our issues since March and we all know that separate issues work a lot better
