### ISSUE TITLE
[Cms] Changing the slug of a page in the Panel always throws an Exception

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1541]
**Describe the bug**
When changing the slug of any page in the Panel, the console logs an error.

It originates from the function `find()` in `kirby/src/Http/Router.php` which always throws an Exception when called.
https://github.com/getkirby/kirby/blob/9a8409747313b1e8907b4322828a2e724a8dc6fc/src/Http/Router.php#L145

**To Reproduce**
1. Open the console and change the slug of a page in the Panel
2. See error

**Tested Kirby Versions**
3.0.2 + 3.0.3

**Console output**
```
Object {
  status: "error",
  exception: "Exception",
  message: "No route found for path: \"null\" and request method: \"GET\"",
  file: "kirby/src/Http/Router.php",
  line: 120,
  code: 404
} app.js:1:236022
```

**Comment by bastianallgeier** [comment]
Hm, but does changing still work?

**Comment by texnixe** [comment]
Yes, the slug is changed and the new URL updated in the address bar, but console throws the error.

**Comment by distantnative** [comment]
Question is if that error breaks the use case of changing the slug in ` page.changeStatus:before` (https://forum.getkirby.com/t/how-to-redirect-after-slug-changed-in-page-update-after-hook/13173/5). at the moment changing the slug in there will block/prevent the status from being changed as @REHvision reports.

**Comment by bastianallgeier** [comment]
✅
