### ISSUE TITLE
$pages->find() with Multiple Items Returns Collection with Lookup-Breaking Keys

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1544]
**Describe the bug**
If you give `$pages->find()` multiple keys, the resulting collection will use the provided keys to index the resulting Pages object. These keys may break things like `->has()` lookups.

Consider a collection of pages with the following URIs:
```
some/section/page-a
some/section/page-b
some/section/page-c
some/section/page-d
```

Then consider getting these pages like:
```php
$pages = page('some/section')->children();

$matching = $pages->find('page-a', 'page-c');
$matchingReindex = new Pages($matching);
$matchingFilter = $pages->filterBy('uid', 'in', ['page-a', 'page-c']);

$pageC = page('some/section/page-c');
echo 'Matching Has Page C: ' . $matching->has($pageC); // false
echo 'Matching Reindex Has Page C: ' . $matchingReindex->has($pageC); // true
echo 'Matching Filter Has Page C: ' . $matchingFilter->has($pageC); // true
```

**Expected behavior**
All of these methods should return true for checking if Page C exists in the collection.

**Kirby Version**
`3.0.3`

**Additional context**
This is where the `find()` uses the user's input as the resulting key, instead of asking the object for it's `id()` (which would be the URI).
https://github.com/getkirby/kirby/blob/021efeb6692fcee19ee7e4aae5f35d028e1ee875/src/Toolkit/Collection.php#L351

When passing the page object to the `->has()` method, it uses the page ID as the key to check.

Wrapping the resulting collection in another Pages call forces it to be reindexed and works as expected. `new Pages($matching)`

**Comment by distantnative** [comment]
✅ in 3.1.2
