### ISSUE TITLE
[Fields] imply min with required and vice-versa

### ISSUE THREAD

**Issue by AhoyLemon** [getkirby/kirby#1546]
**Describe the bug**
In Kirby 3, I have a cover image with the following set up....

```
cover:
    label: Cover
    type: files
    query: page.images
    max: 1
    required: true
    width: 1/2
    info: "{{ file.dimensions }}"
    help: 600x400
```

Visually, this does create a field with a required asterisk....
![image](https://user-images.githubusercontent.com/3413200/53916856-d650cd80-4028-11e9-84dc-7dda548017dc.png)

However, I'm able to save the file without any feedback of missing a required field. For context, compare the required "Cover" field with the required"Video Slug" field, both blank.

![image](https://user-images.githubusercontent.com/3413200/53916760-94c02280-4028-11e9-9bb9-e03d0f15d3f0.png)

This was doing using version 3.0.3, current as of this GH issue.

**Comment by texnixe** [comment]
It seems to work if you set `required: true` and `min: 1`, but ideally setting required to true would also assume min:1 without having to set this manually.

**Comment by AhoyLemon** [comment]
Agreed on both counts!

Here's what I've got now...

```
cover:
    label: Cover
    type: files
    query: page.images
    max: 1
    required: true
    width: 1/2
    info: "{{ file.dimensions }}"
    help: 600x400
```

This is enough that I'm getting error messages on save, which solves the problem for me. Agreed with required inferring a minimum though.

**Comment by AhoyLemon** [comment]
Also, more "enhancement" than bug, but on a related tip....

![image](https://user-images.githubusercontent.com/3413200/54308278-b3c83280-459b-11e9-8d3b-bc4c47211940.png)

Title, Cover, and URL are all required. Artist isn't. This totally validates correctly on submit, but shouldn't the Cover field have the same red glow effect as the other two requireds?

**Comment by distantnative** [comment]
@AhoyLemon moved your last comment to a separate issue.

**Comment by distantnative** [comment]
In general, I think this goes for all fields with `min` option:
- If `min` is set, `required` should be treated as `true`
- If `required` is set to `true`, `min` should be treated as at least `1`.

**Comment by bastianallgeier** [comment]
✅
