### ISSUE TITLE
Guard against missing user .htpasswd

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1547]
**Describe the bug**
Kirby's API/panel UI does not distinguish between invalid credentials, and the case when `.htpasswd` is missing from the user's `accounts\xxx\` folder (see _Additional context_ for the 🤦‍♂️ that caused this).

**Kirby Version**
3.0.3

**Console output**
```
{status: "error", exception: "Kirby\Exception\InvalidArgumentException", message: "Invalid email or password", key: "0", file: "kirby/config/api/routes/auth.php", …}code: 400details: []exception: "Kirby\Exception\InvalidArgumentException"file: "kirby/config/api/routes/auth.php"key: "0"line: 50message: "Invalid email or password"status: "error"__proto__: Object
Em.config.onError @ app.js:1
(anonymous) @ app.js:1
Promise.catch (async)
request @ app.js:1
post @ app.js:1
login @ app.js:1
login @ app.js:1
(anonymous) @ vendor.js:17
h.dispatch @ vendor.js:17
dispatch @ vendor.js:17
login @ app.js:1
submit @ app.js:1
ie @ vendor.js:39
n @ vendor.js:39
Io.o._wrapper @ vendor.js:39
```

**Additional context**
This can accidentally happen when a (S)FTP upload to a server is a bit overzealous in not transferring dot files... so, yes, entirely self-inflicted, but not so easy to spot.

**Comment by WeTurkstra** [comment]
We found a similair problem. If you create a user in the panel with out  a password. A .htpasswd is created with a hased empty string so <?php password_hash(''); ?> Now this user can login without entering a password.

So the password is for a new user is not validated on creating the user!

**Comment by bastianallgeier** [comment]
@WeTurkstra this is fixed.

**Comment by bastianallgeier** [comment]
✅ Authentication throws more useful exceptions now, when debug mode is switched on.
