### ISSUE TITLE
Options of Select Fields are modified/translated in Panel

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1548]
**Describe the bug**
If you have a select field, some option texts (i load them via api out of a JSON file), not values, are autotranslated in Panel.
For example the String `language` becomes `Sprache`.

**To Reproduce**
```
label: Icon
type: select
options: api
api: data/fontawesome_icons.json
```
```
{
	"lamp": "lamp",
	"landmark": "landmark",
	"landmark-alt": "landmark-alt",
	"language": "language",
	"laptop": "laptop",
	"laptop-code": "laptop-code",
	"laugh": "laugh"
}
```

**Screenshots**
<img width="919" alt="bildschirmfoto 2019-03-07 um 11 33 02" src="https://user-images.githubusercontent.com/17915115/53951111-01412d00-40ce-11e9-9dcb-d63436fad9c8.png">

**Kirby Version**
3.0.3

**Comment by bastianallgeier** [comment]
✅
