### ISSUE TITLE
I can create a user in the panel with out a password.

### ISSUE THREAD

**Issue by WeTurkstra** [getkirby/kirby#1549]
**Describe the bug**
If you create a new user in the panel you can leave the password field blank.
This results in a user being created with an .htpasswd which contains a hash for an empty string. 

This then results in this user to being able to login to the panel without entering a password.

This is what is being sent to the backend:
```{name: "Tester", email: "test@reprovinci.nl", password: "", language: "en", role: "admin"}```

**Expected behavior**
When a user is being created without a password we should either get a validation error. Or the .htpasswd should be empty!

**Kirby Version**
3.0.3

**Comment by bastianallgeier** [comment]
Ugh, this should not happen. We will fix this immediately. 

Creating password-less users is intended. This could be used later to create third-party auth. But those users should definitely not be able to login without password.

**Comment by bastianallgeier** [comment]
✅ I just fixed this on the develop branch. Will be in 3.1.0

**Comment by WeTurkstra** [comment]
@bastianallgeier Thank you very much!
