### ISSUE TITLE
"Select" Blueprint Field Saves Label Value, Not Key Value

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1550]
**Describe the bug**
The following blueprint fields examples do not save the numeric value as expected.

```
ratingValue:
  label: Rating Value
  type: select
  options:
    "1": "★"
    "2": "★★"
    "3": "★★★"
    "4": "★★★★"
    "5": "★★★★★"
```

```
reliability:
  label: Reliability
  type: select
  options:
    '1': Terrible
    '2': Below Average
    '3': Average
    '4': Above Average
    '5': Great
``` 

**To Reproduce**
1. Put these into a blueprint
2. Select "★★★" in the first dropdown, and "Above Average" in the second dropdown
3. Save the page
4. Inspect the saved content file.

**Expected behavior**
The values "3" and "4" should be saved. Instead, literally "★★★" and "Above Average" are saved.

**Screenshots**
<img width="510" alt="screen shot 2019-03-07 at 1 21 05 pm" src="https://user-images.githubusercontent.com/417182/53989914-ea093c00-40db-11e9-89a5-3e3bb11a016b.png">
I would have expected the HTML `value` field to be the numeric version.

**Kirby Version**
`3.0.3`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser: Safari
 - Version: 12.0.3 (14606.4.5)

**Additional context**
I'm pretty sure this is a recent regression.

**Comment by texnixe** [comment]
See the second example in this section on how to deal with numeric keys:
https://getkirby.com/docs/reference/panel/fields/select#example-with-a-single-default-value
