### ISSUE TITLE
Files section with page parent on site blueprint throws error

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1552]
As reported by Nurum in the forum: https://forum.getkirby.com/t/files-section-with-different-parent-does-not-work-on-site-blueprint-in-kirby-3-0-3/13285

**Describe the bug**
The following blueprint worked in 3.0.2, but no in 3.0.3 - it throws:
`" The section “test” could not be loaded: Argument 1 passed to Kirby\Cms\Site::is() must be an instance of Kirby\Cms\Site, instance of Kirby\Cms\Page given, called in C:\starterkit\kirby\config\sections\files.php on line 114"`

**To Reproduce**
Tested it with this site.yml file in the Kirby Starterkit:

```
title: Site

sections:
  test:
    type: files
    parent: site.find('photography')
```

**Introduced**
This change: https://github.com/getkirby/kirby/commit/ac11b1f83008c9013333b2efec6e561c2c12edf1#diff-1783d9cb499184c1976f39fa990440d2R333

**Comment by bastianallgeier** [comment]
✅ Argh, exactly the one test case that wasn't covered :( Sorry!
