### ISSUE TITLE
Unexpected file ordering with "cards" view when limit is used

### ISSUE THREAD

**Issue by differenceclouds** [getkirby/kirby#1553]
In a paginated "cards" layout, when moving an item when on the second "page" of items, then switching to the first page, that item appears in an unexpected place.

In general, if you have a long list of files or children, there's no good way to get an item from one "page" or group of 20 to another, in list or cards view.

**To Reproduce**
1. Add "limit: 4" to "album.yml" in the kirby starterkit. 
2. Move a file to any position. 
3. navigate to the next or previous group of files

The file you moved is, like 75% of the time, now in a seemingly random position in the other "page" that you navigated to.

**Expected behavior**
File stays in position you put it in. In general there needs to be a way to move a file from one paginated group to another (although this bug *does* do that ;)

**Screenshots**
I uploaded a screen recording here:
https://imgur.com/a/dYrEnNO
**Kirby Version**
3.0.2

**Console output**
no errors

**Comment by distantnative** [comment]
> In general, if you have a long list of files or children, there's no good way to get an item from one "page" or group of 20 to another, in list or cards view.

There is an idea issue existing: https://github.com/getkirby/ideas/issues/164
Please add your +1 on it.

That's aside from the actual bug you described.

**Comment by bastianallgeier** [comment]
✅
