### ISSUE TITLE
[Panel] Structure field preview of date field doesn't show time (when time: true)

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1555]
A date field with `time: true` inside a structure field, does not show the time when collapsed.

**To Reproduce**
1. Add a date field with `time: ture` to a structure
2. Add a structure item and click OK
3. See the preview of the date field

**Expected behavior**
When `time: true` is set the time should be visible in the preview, too.

**Screenshots**
![Bildschirmfoto von »2019-03-10 19-04-01«](https://user-images.githubusercontent.com/2584674/54089262-767b5f00-4367-11e9-9081-7854bf319498.png)
![Bildschirmfoto von »2019-03-10 19-04-22«](https://user-images.githubusercontent.com/2584674/54089261-767b5f00-4367-11e9-8525-c18e6ee8d856.png)

**Kirby Version**
3.0.3

**Comment by bastianallgeier** [comment]
✅
