### ISSUE TITLE
Multi-language setup: link tag ignores non-default language

### ISSUE THREAD

**Issue by amanita-citrina** [getkirby/kirby#1558]
**Describe the bug**
(See https://forum.getkirby.com/t/multi-languange-kirby-tag-link-explicit-language-property-needed/13053)
In a multi-language setup, (link:destination text:Some text) ignores the current language.
Non-default languages must be set explicitly. This was not needed in Kirby 2.

**To Reproduce**
1. In site/config/config.php: 'languages' => true

2. In site/languages: create de.php (default) and en.php:
de.php: 'url' => '', 'default' => true etc.
en.php: 'url' => '/en', 'default' => false etc.

3. Create the following structure (German and English site):
1_home:
  home.de.txt
  home.en.txt
2_inhalt:
  inhalt.de.txt
  inhalt.en.txt   (slug: content)

4. LInks in home.en.txt now resolve as follows
  (link:inhalt text:Some text) --> example.tld/inhalt
  (link:inhalt lang:en text:Some text) --> example.tld/en/content
  (link:content text:Some text) --> example.tld/content

**Expected behavior**
Same behaviour as in Kirby 2, where the link in home.en.txt resolved to the current language:
  (link:inhalt text:Some text) => example.tld/en/content

**Kirby Version**
3.0.3

**Desktop (please complete the following information):**
 - macOS 10.11
 - Firefox 65.0.1

**Comment by bastianallgeier** [comment]
✅

**Comment by richardwiggins** [comment]
Has this actually been fixed now? Just downloaded the latest version from here and I'm still getting this issue.

**Comment by texnixe** [comment]
@richardwiggins 

I just tested this and for me, all links in home.en.txt with the above language setup resolve to the same page:

```
(link: inhalt text: Some text) => /en/content
(link: inhalt lang: en text: Some text) => /en/content
(link: content text: Some text) => /en/content
```

While the result from the same links in `home.de.txt` results in this

```
(link: inhalt text: Some text) => /inhalt
(link: inhalt lang: en text: Some text) => /en/content
(link: content text: Some text) => /content
```
Where 1 + 2 work fine and the last one results in an error (but that would be the expected behavior, I guess).

Are you really on 3.1.0 rc.1?

**Comment by richardwiggins** [comment]
@texnixe Hhhmm, maybe not. I'm not using the Panel at all, how would I check?

**Comment by richardwiggins** [comment]
@texnixe Sorry, I wasn't on 3.1.0 rc.1. I am now and working correctly 👍
