### ISSUE TITLE
Router doesn't work on multilanguage site

### ISSUE THREAD

**Issue by acstll** [getkirby/kirby#156]
On a multilanguage site, all router actions (returning a $page or json) throw this:

```

Call to a member function code() on a non-object in /Users/.../starterkit/kirby/kirby.php on line 378
```

I tested the same routes on a single-language site and it works.

**Comment by ponychicken** [comment]
There seems to be a deeper underlying problem:
This route doesn't work, the page displayed is in the default language.
Also site->language seems to be NULL (the cause of the warnings above)

````
  array(
    'pattern' => '([a-z]{2})/(:all)',
    'action'  => function($lang, $path = null) {
      $page = page($path);
      
      if($page->intendedTemplate() == 'category') {
        $path = $page->children()->last()->uri();
      }
      return site()->visit($path, $lang);
    }
  ),
