### ISSUE TITLE
Creating multi-level listed pages programmatically is broken

### ISSUE THREAD

**Issue by chpio** [getkirby/kirby#1560]
**Describe the bug**
```php
$rootPage = ; //...
foreach ($data['pages'] as $p) {
        $importedPage = $rootPage->createChild([
            'slug' => $p['id'],
            'template' => 'mypage',
            'draft' => false,
            'content' => [
                // ...
            ],
        ]);
        $importedPage->changeStatus('listed');

        foreach ($p['subpages'] as $sp) {
            $importedPage->createChild([
                'slug' => $sp['id'],
                'template' => 'mysubpage',
                'draft' => false,
                'content' => [
                    // ...
                ],
            ])
                ->changeStatus('listed');
        }
}
```

The 1. level imported pages are duplicated
1. at expected location with a number prefix
2.
  * if `draft` is set to `true`, then it's created in `_drafts` (also it do not show up in panel, i guess that's because of the duplication in the `_drafts` dir) 
  * if `draft` is set to `false`, then it's created at the expected location, but without a number prefix

The 2. level imported page is created in the drafts dir of the 1. level page (`_drafts/{page_id}` or `{page_id_without_number_prefix}`)

**Kirby Version**
`3.0.2`

**Comment by chpio** [comment]
workaround: place `$importedPage->changeStatus('listed');` after the subpage import

**Comment by distantnative** [comment]
In Kirby 3, page objects are immutable. So all these methods return a modified object of itself to be used then. Which means you should probably do something like:

```php
 $importedPage = $rootPage->createChild(...);
 $importedPage =  $importedPage->changeStatus('listed');
 $subPage = $importedPage->createChild(...);
...
```

Does it work with that?
