### ISSUE TITLE
Mime::toExtension() just returns first matching extension

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1561]
Some MIME types like `image/jpeg` have multiple extensions (here: `.jpg`, `.jpeg`, `.jpe`). Our [`Mime::toExtension()`](https://github.com/getkirby/kirby/blob/3.0.3/src/Toolkit/Mime.php#L233) method stops at the first one though.

For backwards-compatibility, there should probably be another plural `Mime::toExtensions()` method that will return an array of all possible extensions. At the same time, `Mime::toExtension()` (singular) should be deprecated.

**Comment by bastianallgeier** [comment]
That's the intended behaviour of this method. It's used to translate a mime type to a single extension. All extensions should be arranged in a way that the most common extension is returned.

**Comment by lukasbestle** [comment]
But sometimes there are use-cases where all common extensions are needed, like for https://github.com/getkirby/ideas/issues/216 (which was the original reason for this issue). I think we should have both methods then.

**Comment by bastianallgeier** [comment]
I added the Mime::toExtensions() method.

**Comment by lukasbestle** [comment]
Yep, that‘s fine. :)
