### ISSUE TITLE
Impossible to store 00:00 in time field

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1562]
**Describe the bug**
The time field show 00:00 by default, instead of --:-- like in the date time field. Also, it is not possible to store this time value. Only when I set  a different value first, save, and then switch back to 00:00 again, can I store 00:00 as time.

**To Reproduce**
1. Insert time field in blueprint
2. Go to page with that blueprint
3. Try to save value
4. See nothing happening in content file

**Expected behavior**
The field should be empty–i.e. show the dashes if no default time is set. It should be possible to store 00:00 as time value.

**Screenshots**

**Kirby Version**
3.0.3 and latest develop state.

**Console output**
If you are working with the panel, please check the browser console for errors and send the output.

**Desktop (please complete the following information):**
 - macOS]
 - safari

**Comment by bastianallgeier** [comment]
Do you know if this happend before or is this a new bug in 3.0.3?

**Comment by texnixe** [comment]
No, I don't know, only tested with the above.

**Comment by distantnative** [comment]
What should be saved when a date is selected but no time?

**Comment by bastianallgeier** [comment]
✅
