### ISSUE TITLE
Annoyance with a multiselect dropdown at the end of a page

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1563]
**Describe the bug**
An edge case for having a not native dropdown at the end of the page. There are actually 4 items that could be selected but he save bar overlaps the last item.

![bug](https://user-images.githubusercontent.com/10027897/54195545-4646d400-44bf-11e9-9cf4-63d02cc07ab5.png)

**Expected behavior**
Be able to select all items 😉 

**Kirby Version**
3.0.3

**Desktop**
 - Windows 10
 - Firefox 66

**Additional context**
It's not that big of deal. More like an annoyance. The problem also only occurs if you try to add more than one item in one go. Chrome kinda works as the last item is at least visible.

![grafik](https://user-images.githubusercontent.com/10027897/54195739-c2411c00-44bf-11e9-80c8-87f1e5dbd9a7.png)

**Comment by distantnative** [comment]
I guess we have the same problem with the select field. Maybe also tags field with autocomplete.
Small fix would be to raise the z-index above the FormButtons bar.
More  complex fix to restrain the dropdown to the remaining height until the browser window.

**Comment by bastianallgeier** [comment]
✅
