### ISSUE TITLE
Setting header using Remote class

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1567]
**Describe the bug**
I'm trying to connect to an external API using the `Kirby\Http\Remote` class. In this context, I'd like to set the content type of the request:

```php
$remote = Remote::request('https://my-external.api', [
    'method' => 'POST',
    'headers' => [
        'Content-type: application/json'
    ],
    'data' => $myData
]);
```

Nevertheless, the sent headers always look like this:

```
Array (
    [Date] => Wed, 13 Mar 2019 11:03:48 GMT
    [Content-Type] => text/html; charset=UTF-8
    [Connection] => keep-alive
    [Server] => Apache
    [X-Frame-Options] => SAMEORIGIN
    [P3P] => policyref="/w3c/p3p.xml", CP="ALL CURa ADMa DEVa OUR IND UNI COM NAV INT STA PRE"
)
```

**Expected behavior**
The `Content-Type` header should be set to `application/json`.

**Kirby Version**
Kirby 3.0.3 and 3.1.0 RC1.

**Comment by bastianallgeier** [comment]
Hm, I just recently got other headers to work correctly. Maybe it's an issue with the content type header in particular. I have to test that. 

BTW: I love that you write Kirby `3.0.3 and 3.1.0 RC1` That's super helpful to know that it's not a regression in the rc.

**Comment by lukasbestle** [comment]
I just tested your example code but could not reproduce the issue.

For my test, I have cobbled together an endpoint (in a Kirby template) that prints out the list of received request headers like so:

```php
<?php

var_dump($kirby->request()->headers());
```

I then requested that endpoint from another Kirby template like so:

```php
<?php

$remote = Remote::request('http://v3.kirby.test/test', [
    'method' => 'POST',
    'headers' => [
        'Content-type: application/json'
    ]
]);

echo $remote->content();
```

The output is:

```
/<path>/site/templates/test.php:3:
array (size=5)
  'Content-Length' => string '0' (length=1)
  'Content-Type' => string 'application/json' (length=16)
  'Accept-Encoding' => string 'utf-8' (length=5)
  'Accept' => string '*/*' (length=3)
  'Host' => string 'v3.kirby.test' (length=13)
```

What does your setup look like?

**Comment by nilshoerrmann** [comment]
Focus has shifted so we currently don't need this. As you cannot reproduce this issue, I'll close it. If this issue occurs again, I'll reopen with more information.
