### ISSUE TITLE
Search misalignment

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1568]
The select box should align with the rest:

<img width="480" alt="Bildschirmfoto 2019-03-13 um 15 41 50" src="https://user-images.githubusercontent.com/25466/54287760-99e01d00-45a6-11e9-82b9-092aa335140b.png">

This is happening on latest Firefox for Mac.

**Comment by bastianallgeier** [comment]
Oh, that's probably the nice firefox display flex issue in buttons.

**Comment by nilshoerrmann** [comment]
I didn‘t know it‘s “a thing” :D

**Comment by distantnative** [comment]
✅
