### ISSUE TITLE
$kirby->response() Headers Not Automatically Sent on Fatal Error Pages

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1570]
**Describe the bug**
When a fatal PHP error occurs, any headers applied to `$kirby->response()` are not sent. Headers set within a custom `fatal` handler callback are also ignored, which are arguably the most important.

Within the `fatal` handler callback, you can force the headers to be sent with `$response->send()->send();` but this honestly seems unnecessary.

**To Reproduce**
1. Modify your config file to resemble the following
2. In a template file, add some php like `<?php some_missing_func() ?>` to cause a fatal error
3. Load the PHP page to inspect the headers

```php
return [
    'debug' => false,
    'hooks' => [
        'route:before' => function ($route, $path, $method) {
            kirby()->response()
            ->header('X-Frame-Options', 'DENY')
            ->header('X-XSS-Protection', '1; mode=block')
            ->header('X-Content-Type-Options', 'nosniff')
            ;
        }
    ],
    'fatal' => function() {
        $kirby = kirby();
        $response = $kirby->response()
        ->header('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
        ->header('Expires', 'Fri, 01 Jan 1990 00:00:00 GMT')
        ;

        // The following line will force the headers to be sent, but I wouldn't expect this to be necessary
        // $response->send()->send();
        
        include $kirby->root('kirby') . '/views/fatal.php';
    },
];
```
**Expected behavior**
I would expect that existing headers added to the `$kirby->response()` object be sent automatically.

Thus, the following should all be set:
- `X-Frame-Options`
- `X-XSS-Protection`
- `X-Content-Type-Options`
- `Cache-Control`
- `Expires`

However, they are all omitted.

**Kirby Version**
`3.0.3` and `3.1.0-rc.1`

**Additional context**
Standard PHP `header('X-Foo: Bar')` headers are sent.

**Comment by lukasbestle** [comment]
Hm, I don't think the current behavior should be changed as explained in the following:

- Headers that were set before the fatal error occurs are not necessarily relevant to the fatal error page. In your example they are (as they are general headers I assume you want sent on every response), but generally, the headers could just as well be content type headers or similar. Those could be incorrect for the fatal error response. Which means: This part is not a bug in my opinion.
- In the `fatal` callback, you should use the `header()` function as Kirby will immediately exit after the callback to keep complexity low (it would be very bad if there was another error in handling the fatal error). So we won't be able to fix this part.

Your config should therefore look something like this:

```php
return [
    'debug' => false,
    'hooks' => [
        'route:before' => function ($route, $path, $method) {
            kirby()->response()
            ->header('X-Frame-Options', 'DENY')
            ->header('X-XSS-Protection', '1; mode=block')
            ->header('X-Content-Type-Options', 'nosniff')
            ;
        }
    ],
    'fatal' => function() {
        header('X-Frame-Options: DENY');
        header('X-XSS-Protection: 1; mode=block');
        header('X-Content-Type-Options: nosniff');
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Expires: Fri, 01 Jan 1990 00:00:00 GMT');

        include $kirby->root('kirby') . '/views/fatal.php';
    }
];
```

I know: Code duplication isn't optimal, but it's the most robust solution and that's most important in my opinion.

Alternatively, you can configure your webserver to set those "global" headers for you. Then you won't need to set them from Kirby at all.
