### ISSUE TITLE
[Panel] Picker fields missing required error highlighting

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1581]
![image](https://user-images.githubusercontent.com/3413200/54308278-b3c83280-459b-11e9-8d3b-bc4c47211940.png)

Title, Cover, and URL are all required. Artist isn't. This totally validates correctly on submit, but shouldn't the Cover field have the same red glow effect as the other two requireds?

_Originally posted by @AhoyLemon in https://github.com/getkirby/kirby/issues/1546#issuecomment-472569973_

**Comment by distantnative** [comment]
+ StructureField with min/max

**Comment by bastianallgeier** [comment]
✅
