### ISSUE TITLE
t('translation') stopped working with 3.1.0-rc1 with default url pointing to /

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1593]
**Describe the bug**
Every `t('translation')` I have on my website stopped working and are falling back to english when I updated. Happens also without plugins.

**To Reproduce**

- Start a fresh Kirby installation with a default language other than english (well, current language wouldn't be detected either but as it would fallback to english anyway, it'd be harder to debug), french in my case. At this point everything works fine.
- Change the default language url to `/`:

```
return array (
  'code' => 'fr',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'fr_FR',
  'name' => 'Français',
  'url' => '/',
  'translations' => array(
  	'test.string' => 'This would be a french string'
  )
);
```

- `t('test.string')` doesn't work anymore, current language isn't detected and falls back to english. 

**Kirby Version**
3.1.0-rc1

**Comment by distantnative** [comment]
I assume you mean 3.1.0-rc.1?

**Comment by sylvainjule** [comment]
Yes, sorry, juggling with too many versions. I do mean 3.1.0-rc1.

**Comment by bastianallgeier** [comment]
✅

**Comment by sylvainjule** [comment]
Unfortunately the release didn't fix it.

**Still able to reproduce:**

1. Start a fresh starterkit
2. `languages => true` in `config.php`
3. Add `en` as default language in the panel
4. Go to `languages/en.php` and set `'url' => '/'`
5. In home.php, add `<?php var_dump($kirby->languages()->current()) ?>`
6. Go to `/`. The var_dump above returns false.

**Comment by bastianallgeier** [comment]
@sylvainjule in my tests the `t()` method works as expected in 3.1.1 

`$kirby->languages()->current()` cannot work though and is not a regression. You should use `$kirby->language()` instead to get the current language, which also works as expected.
