### ISSUE TITLE
Panel Number Field Strips Negative Sign When Typing -0

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1598]
If you type `-0` into a `number` field, the value gets immediately converted into `0`. This is frustrating if you're trying to type a value like `-0.2`.

Happens on Chrome and Safari.

```yaml
someNumber:
  type: number
  step: .01
```

**To Reproduce**
1. Add the above field to a blueprint
2. Open the Panel
3. Type the following characters: `-` `0` `.` `2`
4. The text field displays `0.2`

**Expected behavior**
The field should have `-0.2`

**Kirby Version**
`3.0.3` and `3.1.0-rc.1`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Chrome 72.0.3626.121
 - Safari 12.0.3 (14606.4.5)

**Additional context**
A workaround is to simply omit the `0` and type `-` `.` `2`.

**Comment by bastianallgeier** [comment]
✅
