### ISSUE TITLE
Panel: remove tag on backspace/delete

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#16]
With tags I can select a tag to make it selected. I tried to press the delete key to delete it but it did not work. It would be nice it that would work.

(This issue also appear in Panel 2 so it's not new)

**Comment by distantnative** [comment]
@jenstornell Out of interest: which browser are you using? I think, I got a fix – just testing is a bit hard as it works for me already in my setup without the fix.

**Comment by jenstornell** [comment]
You changed the title to another issue. You don't have a delete button on Mac, just a backspace? Anyway if I click to select a tab it becomes blue. Pressing delete (not backspace) when selected does nothing.

**Comment by distantnative** [comment]
Oh sorry, I misunderstood you then. However, `fn + backspace` works as `delete` on Mac. In Alpha 1, `fn + backspace` does not remove the tag. Adding the fix https://github.com/k-next/panel/commit/34669e4482f34c9b122d1b517356aae86e50e713 it does remove the tag. So this should be in the next release once merged into the develop branch.

**Comment by distantnative** [comment]
Will be part of the next release.
