### ISSUE TITLE
$page->date() Not Working Properly in PHP 5.3

### ISSUE THREAD

**Issue by CalebGrove** [getkirby/kirby#160]
I'm try to use the `date()` function with a custom field. It works fine on my local environment (MAMP with PHP 5.6.2), but it fails on my server running PHP 5.3.10. This is the code I am using:

    echo $page->date('F jS, Y', 'dateauthored')

The custom field (`dateauthored`) contains the string `1862-09-18`. In my local environment, it correctly echoes out "September 18th, 1862", but on my server it returns nothing.

**Comment by bastianallgeier** [comment]
hey @CalebGrove sorry for the delay. I just double-checked this on PHP 5.3 and I can't reproduce this issue. Do you still have the same glitch on 5.3?

**Comment by ausminternet** [comment]
PHP 5.3 is end of life(!) since about half a year, just saying...

**Comment by CalebGrove** [comment]
@ausminternet I understand, but unfortunately, cannot update my PHP version quite yet. Regardless, Kirby is advertised to work on 5.3 (I'm not saying that it doesn't, either, but that this particular feature doesn't seem to like my server).

@bastianallgeier It still has this glitch for me. FWIW, the exact PHP version number is 5.3.10. Also, this is on Ubuntu 12.04. As long as I'm the only person reporting this problem and you can't duplicate it, don't worry about this issue, as it's not mission-critical for me and is likely due to my server config. Thanks for your hard work on Kirby, I look forward to buying more licenses from you in the future. :)

**Comment by lukasbestle** [comment]
What exactly does it return? An empty string or `false`?

**Comment by CalebGrove** [comment]
@lukasbestle I'm actually not sure (I'm a total noob at PHP). In output HTML, the place where PHP should return the date is simply blank. How can I test this?

**Comment by lukasbestle** [comment]
A simple way to test this is to replace the `echo` with a `var_dump`, like so:

```
var_dump($page->date('F jS, Y', 'dateauthored'))
```

Don't forget the parens, since `var_dump` is a PHP function.

**Comment by bastianallgeier** [comment]
I'm pretty sure the method is reliable. I created tests for it yesterday and let it run on Travis CI on PHP 5.3 without issues.

**Comment by CalebGrove** [comment]
@lukasbestle Thanks for that. It returns `bool(false)` when I use `var_dump()`.

**Comment by lukasbestle** [comment]
This return value should only occur when the field ("dateauthored") does not exist. Have you double-checked that `$page->dateauthored()` returns a value on your server?

**Comment by CalebGrove** [comment]
Yes, I'm already using `$page->date authored()` on each of the pages and it returns the correct value (example: `1862-09-21`).

**Comment by lukasbestle** [comment]
`date authored`? Did you mean `dateauthored`?

**Comment by CalebGrove** [comment]
Yes, I meant `dateauthored()`. Blame autocorrect.

**Comment by lukasbestle** [comment]
Hm, I can't really explain why it doesn't work then. As you said, it works when not passing the second parameter, so this is the only reason why that could fail.

**Comment by CalebGrove** [comment]
Thanks for your help @lukasbestle. At this point, I'm going to simply not worry about it. I'll be updating my server in a month or two to PHP 5.5 and assume that this problem will disappear at that point. And, as I said, it's not mission-critical.

**Comment by ausminternet** [comment]
Just a second note: 5.6 is already stable since half a year, why 5.5? Here is the 12.04 repo: https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6
