### ISSUE TITLE
[Panel] Unescaped input in multiselect and tag fields causes RexEx error

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1601]
**Describe the bug**
Entering RegEx characters like `(`, `\`, `*` or `+` into Multiselect or Tag fields instantly causes an error because the input is used in a RegEx without escaping.

**Expected behavior**
Input of special characters should be possible.

**Screenshots**
<img width="303" alt="Bildschirmfoto 2019-03-19 um 20 12 24" src="https://user-images.githubusercontent.com/18071758/54635158-dcf92f00-4a83-11e9-9ac1-104f7057dab0.png">
<img width="470" alt="Bildschirmfoto 2019-03-19 um 20 12 52" src="https://user-images.githubusercontent.com/18071758/54635208-f1d5c280-4a83-11e9-97fb-7d1eff0b2c37.png">

**Kirby Version**
3.1.0

**Desktop:**
 - OS: macOS
 - Browser: chrome

**Comment by distantnative** [comment]
✅ Will be fixed in 3.1.1
