### ISSUE TITLE
Can’t switch to default language if browser’s preferred language is different.

### ISSUE THREAD

**Issue by frankrausch** [getkirby/kirby#1603]
**Describe the bug**
I have a 3-language setup: DE / EN / JP.

Since 3.1.0, the EN language version cannot be accessed any more in the latest Safari (macOS) if the system language is set to German.

The English version is the default, located at `/`, while German is a `/de` and Japanese is at `/ja`.

```php
return [
  'code' => 'en',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'en_US',
  'name' => 'English',
  'url' => '/',
];
```

**To Reproduce**
1. On macOS, set the system language to German (DE) if necessary. Needs restart.
2. Visit a site that has English set as the default root language.
3. Try switching to English.
4. Kirby shows German instead.

**Expected behavior**
English should be displayed.

**Kirby Version**
3.1.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version 12.0.3

Possibly related to #1593

**Comment by frankrausch** [comment]
Update: I can reproduce this in the latest Opera v58.0.3135.107, too.
Seems to be unrelated to specific browsers.

**Comment by bastianallgeier** [comment]
I just fixed this, added a new set of tests and created a new branch for 3.1.1: https://github.com/getkirby/kirby/tree/release/3.1.1

Could you please give that version a try and let me know if this resolves it for you?

**Comment by frankrausch** [comment]
I can confirm that this version fixes the regression for the site where I found it. Dankeschön!
