### ISSUE TITLE
Return value of the route:after hook is ignored

### ISSUE THREAD

**Issue by dweidner** [getkirby/kirby#1605]
**Describe the bug**
A short section in the guide about Kirby’s Router suggest to use the `route:after` hook to minify the HTML output ([Guide > Routing > route:after](https://getkirby.com/docs/guide/routing#before-and-after-hooks)). Unfortunatly that won't work, as a return value of an event handler will be ignored by the router instance ([./src/Http/Router.php@108](https://github.com/getkirby/kirby/blob/master/src/Http/Router.php#L108)).

**To Reproduce**
Register a custom hook and try to customize the response, as suggested in the guide:

```php
// site/config/config.php

use Kirby\Cms\Page;
use Kirby\Cms\Response;
use voku\helper\HtmlMin;

return [
  'hooks' => [
    'route:after' => function ($route, $path, $method, $result) {
      if (is_a($result, 'Kirby\Cms\Page')) {
        return new Response((new HtmlMinify())->minify($result->render()));
      }
      return $result;
    }
  ],
];
```

**Expected behavior**
The router instance should take the return value of the handler as the new response object. If multiple hooks are registered for the `route:after` hook, each handler should be triggered in sequence and the return value of one handler should be provided as argument to the next handler.

**Kirby Version**
3.0.3

**Comment by lukasbestle** [comment]
@bastianallgeier We would need to use [`$app->apply()`](https://github.com/getkirby/kirby/blob/3.1.2/src/Cms/App.php#L192) here, which currently only supports a single hook argument (the `$value`). However the `route:after` hook has several arguments.

What I could do is to rewrite `$app->apply()` to always expect the `$value` to modify last (which would here be the `$result`). This would still work with the current `kirbytext` hooks that only have one hook argument in the first place, but if we later decide to add hooks where the value to modify is the first argument, that wouldn't work. What do you think?

Also: This feature wouldn't be backwards-compatible with existing hooks that don't return anything. Those would now pass on the value `null`, which will produce an empty response. So maybe we should move this to 3.2.0?

**Comment by lukasbestle** [comment]
✅
