### ISSUE TITLE
Cache System Breaks Kirby Pagination (Always Returns Initial Loaded Page)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1607]
When enabling the Kirby cache system for Pages (either `file` or `apcu`), Kirby pagination becomes broken.

For example, if the Page 1 is loaded:
```
http://localhost/news
```

Then loading Page 2 will return the entire contents of Page 1:
```
http://localhost/news/page:2
```

If you happened to load Page 2 _first_, then trying to load Page 1 or Page 3 will still return Page 2.

**To Reproduce**
1. Enable file/apcu cache for Pages in your config file
2. Go to a page that has pagination, but no query parameter (e.g.: an archive of articles, but not search results).
3. Try loading another page

**Expected behavior**
Ideally: each page of content gets cached separately. Minimally: the cache system should know that further pages of content use the cache.

**Kirby Version**
`3.1.0`

**Additional context**
Because the cache system ignores pages with query parameters, if you tack on something like `?query=test` then the caching system will be skipped and the pages will load correctly.

**Comment by bastianallgeier** [comment]
✅

**Comment by texnixe** [comment]
Would it be possible as a next step to cache pagination pages separately, as suggested by @neildaniels? Should we create a new issue for that in the ideas repo?

**Comment by distantnative** [comment]
@texnixe yes, I think an issue over there would be great
