### ISSUE TITLE
Extended css component is not run on `@auto`

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#1608]
**Describe the bug**
When extending the css component in a plugin, it breaks `@auto` behaviour.

**To Reproduce**
1. install https://github.com/bvdputte/kirby-fingerprint to extend the css component
2. try `<?= css('@auto') ?>` in the `home`-template in a fresh starterkit
3. The replaced css component doesn't run

**Expected behavior**
I expected the replaced component to also have been run on the returned `@auto` url.

**Kirby Version**
Kirby 3.1.0

**Comment by bezin** [comment]
I cannot reproduce this. The component is run on '@auto' as well in my case.

**Comment by distantnative** [comment]
As far as I read the code (https://github.com/getkirby/kirby/blob/master/config/helpers.php#L108-L116), the component should still run with `@auto`, however getting handed over this string instead of the resolved path. So I think it would still better to resolve the path first, then call the component.

**Comment by bvdputte** [comment]
🤔 The home.css file gets fingerprinted in your end? Which kirby version do you use?

In my tests (untouched kirby-starterkit - kirby 3.1):
1. Index.css -> `<link href="http://localhost/assets/css/index.ea0b15243b1ebacb018d4e94fb7989e9.css" rel="stylesheet">`
2. home.css (from `@auto`) -> `<link href="http://localhost/assets/css/templates/home.css" rel="stylesheet">`

**Comment by bezin** [comment]
Yip, I agree this would be better for plugins.

**Comment by bezin** [comment]
While working on a workaround solution in the mentioned kirby-fingerprint plugin, I found out, that there is no way to workaround, except, of course defining custom css() and js() helper methods. 

So it would be great if https://github.com/getkirby/kirby/blob/master/config/helpers.php#L108-L110 and https://github.com/getkirby/kirby/blob/master/config/helpers.php#L112-L116 could be swapped. In the end it does make more sense, as you don't need to call any custom css or js component if there is no template specific asset.

**Comment by distantnative** [comment]
✅ in 3.1.2
