### ISSUE TITLE
Help Text in Files Section Displays Only if Section Not Empty

### ISSUE THREAD

**Issue by luxlogica** [getkirby/kirby#1611]
**Describe the bug**
When we create a new Files Section, and add 'help' text to it in the blueprint, the help text does not display in the Panel, until the section has files in it — that is: the help text does not display when the section is empty, and there are no files.

**To Reproduce**
1. Setup a new 'files' section in a blueprint
2. Make sure to add some 'help:' text to the section section
3. Make sure that the section is set to start out empty - ie., don't set the section up to already start loading up existing files you may have previously uploaded. Start with an empty section

**Expected behavior**
The help text should display below the empty section. But the text does not display, until you add a file to the section.

**Kirby Version**
3.1.0

**Comment by bastianallgeier** [comment]
✅
