### ISSUE TITLE
Green status button doesn't change when changing the status of a page via button in panel

### ISSUE THREAD

**Issue by kgevaert** [getkirby/kirby#1613]
@distantnative 

kirby 3.1

Page is on public status

page update after hook sets the status of the page to unlisted if a toggle field is enabled.

```
 'hooks' => [
   	'page.update:after' => function ($newpage,$oldpage) {
         $kirby = kirby();
         $kirby->impersonate('kirby');
         $template=$newpage->intendedTemplate() ;
         if($template == "invite"){ 
         	if($newpage->status() != "unlisted" && $newpage->denied() == "true"){         		 
         		$newpage->changeStatus("unlisted");
         	}
         }
      },
```
The page is in the content-folder displayed as unlisted, but on the current page in the panel, the green public dot hasn't changed to a blue unlisted button.

<img width="631" alt="Schermafbeelding 2019-03-25 om 13 20 53" src="https://user-images.githubusercontent.com/44861742/54926119-f7159000-4f0f-11e9-9b5a-0726419d2d2b.png">

https://forum.getkirby.com/t/green-status-button-doesnt-change-when-changing-the-status-of-a-page-via-button-in-panel/13471/2

**Comment by distantnative** [comment]
Could you try if it might be working with `page.update:before`?

**Comment by kgevaert** [comment]
No, the same problem with page.update:before...

**Comment by distantnative** [comment]
Solution covered by idea https://github.com/getkirby/ideas/issues/480
