### ISSUE TITLE
Thumbnails return 404 on first load attempt

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1614]
**Describe the bug**
Whenever a thumbnail is requested by the client, it shows a broken image icon and the server returns the 404 page, the first time a thumbnail is requested. This only happens on on of my client's servers.

**To Reproduce**
1. Clear media folder contents
2. Open the panel or any frontend page, that contains thumbnails
3. Thumbnails, that haven’t created yet, will not be shown on first attempt.
4. Reload the page, the thumbnails will load properly.

**Screenshots**

![Bildschirmfoto 2019-03-26 um 12 16 46](https://user-images.githubusercontent.com/395617/54993029-2801cd80-4fc1-11e9-9bda-75081893a248.png)

**Kirby Version**
3.1.1 (happened in earlier versions as well)

**Console output**
`none`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox 65.0.1 / Google Chrome 73.0.3683.86

**Server:**
- OS: Ubuntu 18.04.1
- Apache/2.4.29 (Ubuntu) 
- PHP Version 7.2.15-0ubuntu0.18.04.1

**Additional context**
The server is having issues with file permissions as PHP and the SSH user are not the same. the sysadmin has put them in the same group to mitigate the effects, but some issues persist. However, the panel functions as normal, I can create and update pages and upload files, as I want.

**Comment by bastianallgeier** [comment]
We can't reproduce it without an environment that produces the same behavior. That makes it extremely difficult to debug it. I'm afraid we will have to put it on hold until we find someone who let us test it on a server.

**Comment by distantnative** [comment]
Could you please try this with a Kirby 3.2.2 or 3.2.3-rc.1? I would think we solve this issue in an earlier bug fix release. If the issue remains, please feel free to reopen and please provide  an environment to us (server) where we could test this. AS Bastian stated, otherwise it's near impossible to debug for us.
