### ISSUE TITLE
Opening a routed draft page from the Panel fails with error page

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1615]
**Describe the bug**
When using routes to shorten URLs to child pages, opening such a "routed" draft from the Panel returns the error page

**To Reproduce**
1. Create a new route in the config.php, e.g.
```
[
			'pattern' => '(:any)',
			'action'  => function($uid) {

				$page = page($uid);

				if(!$page) $page = page('about/' . $uid);
				if(!$page) $page = page('releases/' . $uid);
				if(!$page) $page = site()->errorPage();

				return site()->visit($page);

			}
		],
```
2. Go to Panel and create a new draft on the first level
3. Click on the `Open` link
4. See error page

Opening published pages works without any problem.

**Expected behavior**
A routed draft should open without error

**Kirby Version**
Tested with Kirby 3.1.0

**Console output**
No.

**Additional context**
https://forum.getkirby.com/t/draft-preview-giving-error-page/13537

The error can be partly prevented using the new `next()` method, that makes at least the non-routed draft available. The issue then still remains for the routed drafts.

**Comment by distantnative** [comment]
I cannot reproduce this with the `develop` branch anymore. 
Could you please check if it is still happening for you and if so reopen the issue? Thanks.

**Comment by afbora** [comment]
I can reproduce on develop branch.

Here sample: [1615.zip](https://github.com/getkirby/kirby/files/3613579/1615.zip)

john@doe.com - 12345678

Try to open `test` page from panel.

**Comment by texnixe** [comment]
Me too.

**Comment by distantnative** [comment]
Ha! Seems like multilang makes a difference here. Or I did something wrong when testing.

**Comment by texnixe** [comment]
I didn't test in a multilang install. Or do I have to recompile the JS files first?

**Comment by distantnative** [comment]
Ok, I kinda have a solution. The issue is `page($uid)` in your route. It only looks for published pages, not drafts. Since your route intercepts all other routing, there is not a lot the core/Panel could do to prevent this issue. It is on the developer to use the proper route. In this can you should use 

```php
$page = site()->findPageOrDraft($uid);
```

instead.

However, I am wondering whether the `page` helper should be modified to also include drafts.

**Comment by afbora** [comment]
I'm not sure if the `findPageOrDraft()` method is the correct method.
Because ti guess, he problem here is that the admin wants to preview the draft page.
If we change the route as you say, everyone can access that page.
Bıt when remove the custom route, admin can open the draft page from frontend for preview.

**Comment by texnixe** [comment]
Ok, maybe you are right, but using the `findPageOrDraft` method is probably not the right solution. Changing the route to this works as expected:

```
[
    'pattern' => '(:any)',
    'action'  => function($uid) {

        $page = page($uid);

        if(!$page) $page = page('about/' . $uid);
        if(!$page) $page = page('releases/' . $uid);
        if(!$page) $this->next();
              
        return site()->visit($page);

    }
],
```

I don't think the `page()` helper should find drafts...

From my point of view, we can close this issue.

**Comment by distantnative** [comment]
True much better solution.

**Comment by silllli** [comment]
I wanted to add another solution: use `findPageOrDraft()` but check if the user is actually allowed to view the page using `isVerified()` ([Reference](https://getkirby.com/docs/reference/objects/cms/page/is-verified)). Maybe the `isVerified()` method was added in the meantime.

For example:

```php
[
  'pattern' => '(:any)',
  'action' => function($uid) {
    $page = site()->findPageOrDraft($uid);

    // get token from request and verify visit
    if ($page->isVerified(get('token'))) return site()->visit($page);

    $this->next();
  },
],
```
