### ISSUE TITLE
[Panel] Cannot Replace .json File with Another .json File (Only .txt Allowed)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1616]
**Describe the bug**
In the panel, I have a simple `files` section for a page type. I have a `.json` file uploaded, when I use Settings > Replace, the upload form _only_ accepts `.txt` files. It should accept `.json` files.

I suspect, as shown in the screenshot, it uses the Media Type of `text/plain` to determine that only `.txt` is the valid extension. The root cause of this bug might actually be that the media type inference is wrong.

**To Reproduce**
1. Go to a page with a `files` section
2. Upload a file with the extension `.json`
3. Attempt to replace that file with another `.json` file

**Expected behavior**
It should certainly accept another `.json` file. It would be nice if _also_ accepted `.txt` files as well.

**Screenshots**
<img width="850" alt="Screen Shot 2019-03-26 at 10 36 18 AM" src="https://user-images.githubusercontent.com/417182/55020130-7314e400-4fb3-11e9-86c2-07bf5cd6e378.png">

**Kirby Version**
`3.1.0`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Chrome 73.0.3683.86
 - Safari 12.0.3 (14606.4.5)

**Comment by distantnative** [comment]
✅

**Comment by neildaniels** [comment]
@distantnative

Strictly speaking, this is fixed now in `3.1.4-rc.1`. However, I immediately was told by someone on our team that they were surprised that they could no longer use `.txt` file to replace an existing `.json` file.

![2019-05-15 at 10 03 PM copy](https://user-images.githubusercontent.com/417182/57874750-29cc5e00-77c6-11e9-99d3-ca9bd06bb3f1.jpg)

One of our data files needs to be periodically updated, but our source happens to use the extension `.txt`. Now, we have to manually rename the file to `.json` to make the upload succeed.

In Kirby 2, it allowed a `.json` file to replaced with another `.json` file or `.txt` file.
