### ISSUE TITLE
Change single to multilang installation, site.LANG.txt title's missing

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#1617]
**Describe the bug**
Change single to multilang installation, site.txt title is missing. 

**To Reproduce**
1. Setup single installation with one language (no language folder)
2. Set title and custom fields in for site.txt
3. Now add the languages folder and setup 2 languages.
4. The content blueprints will be translated from e.g site.txt to site.fr.txt or site.de.txt...
5. All field will be copied to the site.LANG.txt destination language but the title is missing.
6. e.g the title can now not be added via the panel because the field is missing in the .txt

**Expected behavior**
After adding news languages the title should be copied as well

<img width="1085" alt="Bildschirmfoto 2019-03-27 um 09 00 23" src="https://user-images.githubusercontent.com/5121132/55059270-cef07300-506e-11e9-8db7-ac92813d2b43.png">
 
**Kirby Version**
3.1.0

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.3
 - Browser chrome, safari
 - Version [72.0]
 - Vagrant/Scotchbox

**Comment by bastianallgeier** [comment]
✅
