### ISSUE TITLE
Session garbage collection does not run

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1618]
i have a client with about 4 panel editors. k3 page running for about 3 months. manually cleaned storage/sessions folder today using ftp with about 1k files. maybe kirby could remove sessions past a configurable interval (like 2 months) automatically?

**Comment by lukasbestle** [comment]
Unfortunately, I cannot take a look at the moment, but it would help a lot with debugging if you could keep the session files for now. I will get back to you in two weeks. :)

**Comment by lukasbestle** [comment]
This should now be fixed by #1660.

@bnomei Could you please check if it works with that version on the other server where you haven't yet cleaned the `sessions` folder? The garbage collector only runs every ~100 requests by default. If you don't want to spam the refresh key, you can temporarily set the `gcInterval` option to `1`:

```php
return [
    'session' => [
        'gcInterval' => 1
    ]
];
```

**Comment by bnomei** [comment]
i patched the `kirby/src/Session/FileSessionStore.php` like in the commit, added the setting to the config and hit refresh a few times in frontend and panel. no luck – still 800+ session files. 

`ls` dump of sessions folder...
[storage-sessions_ls.txt](https://github.com/getkirby/kirby/files/3055144/storage-sessions_ls.txt)

**Comment by lukasbestle** [comment]
Thanks for your help!

Do you have CLI access to that server? If so, it would help a lot to get the result of the PHPUnit tests like this:

```
git clone https://github.com/getkirby/kirby.git -b feature/session-gc
cd kirby

composer require phpunit/phpunit ^7
vendor/bin/phpunit --filter Session
```

**Comment by bnomei** [comment]
@lukasbestle sorry for late response. i only have ftp access.
(the ls dump was from Transmit app logging)

**Comment by lukasbestle** [comment]
Hm, OK. That's unfortunate. I don't really know how we can debug this further.

As it works on all machines I have tested it on (with the fixed version of course), it may be that the function didn't actually get called for some reason. Could you please create an empty file called `0.abcdefghijabcdefghij.sess` in the `sessions` directory and then reload a few more times? That file should definitely be deleted then.

**Comment by bnomei** [comment]
it works. it was my fault. i had...

```
'session' => [
        'cookieName' => 'session',
    ],
```

somewhere later in config which overwrote the `gcInterval` section i pasted on top of config.

there are still about 250 sessions for today which seem a lot but maybe client has his own homepage on every employees workstation?

**Comment by lukasbestle** [comment]
Awesome, thanks for checking again. :)

The session implementation is built in a way that the number of session files does not matter a lot (unlike with pages, Kirby does *not* need to read all session files on each request). So 250 active files should be just fine. I have tested 10000 and they were not a huge bottleneck (about 30 ms of garbage collection every 100 requests, but it can be disabled and run manually). Only issue is storage, but as the files are not that large, that's not a huge problem either.
