### ISSUE TITLE
Respect language URL settings when editing languages in Panel

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1619]
**Describe the bug**
By default, when you add languages via the Panel, there is no `url` set in the language files. Having set the URL manually and then editing a language via the Panel, the URL setting is removed from the file.

**To Reproduce**
1. In a multi-language installation, set the URL of the default language to `/` in the default language file
2. Edit the language via the Panel
3. Revisit your language file
4. See URL property gone.

**Expected behavior**
The settings should not be removed. Ideally, Kirby would add the URL property by default (with the default settings) when the language is created, or even better, it should be possible to set the URL in the language creation modal.

**Kirby Version**
3.1.1

**Comment by texnixe** [comment]
Also, the language files are created using the `array()` language construct:

```
<?php

return array (
 // ...
);
```

instead of the short array syntax we use everywhere else:

```
<?php

return [
 // ...
];
```

**Comment by S1SYPHOS** [comment]
Thank you very much!

// Edit: I might add that `translations` property gets removed, too - scary to see heavy multi-language pages without a single translated string :confused:

**Comment by texnixe** [comment]
Better disable language manipulation through the Panel for users until this is fixed.

**Comment by bastianallgeier** [comment]
✅ This was bad. I'm really sorry for it. Url, translations and other custom props in the file are now being preserved when the language is saved.

**Comment by S1SYPHOS** [comment]
Thank you very much, good to hear!
