### ISSUE TITLE
Textarea e-mail button error

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#1620]
**Describe the bug**
When adding an email inside a textarea field if you don't fill the "Link text" field it generates the error `Cannot read property 'length' of null`.

**Expected behavior**
It should return the email itself with <>:
`<email@domain.com>`

**Comment by distantnative** [comment]
Note for later:
Add if check for empty value -  https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Toolbar/EmailDialog.vue#L51

**Comment by distantnative** [comment]
✅
