### ISSUE TITLE
Plugin api.routes => function does not work

### ISSUE THREAD

**Issue by jonathan-reisdorf** [getkirby/kirby#1621]
**Describe the bug**
Within plugin context it is possible to define custom routes as a function rather than just defining an array, which allows for dynamic routes, e.g. based on certain options. This is described here: https://getkirby.com/docs/guide/routing#defining-your-own-routes right at the end of the section.

Unfortunately this does not work for API routes as well, e.g.
```
  'api' => [
    'routes' => function($kirby) {
      return [
          [
              'pattern' => 'something/' . $kirby->option('something'),
              'action' => function () {
                // ...
              }
          ]
      ];
    }
  ]
```
creates the following error:
```
array_merge(): Argument #2 is not an array
```

Not sure if this counts as a bug as it seems more like a non-implemented feature and maybe should go into "ideas"?

**Expected behavior**
I'd expect `routes` and `api.routes` to more or less share the same feature set.

**Kirby Version**
3.1.1

**Console output**
```
{
  code: 2,
  details: null,
  exception: "Whoops\Exception\ErrorException",
  file: "kirby/src/Cms/App.php",
  line: 173,
  message: "array_merge(): Argument #2 is not an array",
  status: "error"
}
```

**Comment by bastianallgeier** [comment]
✅
