### ISSUE TITLE
Closing textarea file select modal with OK when no file selected causes error

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1622]
**Describe the bug**
When accidentally closing the texture's file select modal with `OK` instead of `Cancel`, the Panel throws an "undefined is not an object (evaluating 't[0].dragText')" error.

**To Reproduce**
1. Click on a textarea's paperclip and then choose "Select a file"
2. Do not select a file but click `OK` instead of `Cancel` to close the modal

**Expected behavior**
If nothing is selected and the user clicks `OK`, the modal should be gracefully closed without an error message.

**Kirby Version**
3.1.1

**Comment by distantnative** [comment]
Note for later:
Add if check for `array.length` here: https://github.com/getkirby/kirby/blob/develop/panel/src/components/Forms/Input/TextareaInput.vue#L268

**Comment by distantnative** [comment]
✅
