### ISSUE TITLE
`thumb` presets in dot notation not working

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/kirby#1627]
**Describe the bug**
When using a dot notation, Kirby returns the given image, not a thumb version.

**To Reproduce**
1. Go to `config`:
```php
<?php 

return [
    'thumbs' => [
        'presets' => [
            'my.preset' => ['width' => 960]
        ]
    ]
];
```
2. Use in template:

```php
<?php echo $someImage()->thumb('my.preset'); ?>
```

**Screenshot**
![Peek 2019-03-29 11-20](https://user-images.githubusercontent.com/12161504/55226325-03059880-5215-11e9-8592-f0e4af63e2cc.gif)

**Expected behavior**
Kirby should return a thumb version of given image.

**Kirby Version**
Kirby v3.1.1

**Desktop:**
 - OS: Fedora 28
 - Browser: Firefox v64

**Additional context**
I use dot notation just like [you guys](https://github.com/getkirby/getkirby.com/tree/master/site/snippets), mostly for snippets, but keeping this style throughout my project helps organizing a great deal, so this would be really helpful!

**Comment by S1SYPHOS** [comment]
Anybody here?

**Comment by distantnative** [comment]
@S1SYPHOS Be assured that we have noticed the issue, but as you can see, with 80 others lined up currently, we will need time to review, analyse, reproduce and work through them.

**Comment by S1SYPHOS** [comment]
I was being curious if this was even a 'real issue', and it's a relief to hear you think so, too. I didn't want to be impatient or even pressure you. Thanks for your kind understanding :+1:

**Comment by distantnative** [comment]
I honestly don't know yet without looking into it in detail. I have an assumption where this is coming from (allowing to write options in dot notation as well as nested arrays - so I think it just parses your dotname as another nested array).

**Comment by bastianallgeier** [comment]
✅
