### ISSUE TITLE
Email address is saved lower case, but not checked lower case

### ISSUE THREAD

**Issue by eXpl0it3r** [getkirby/kirby#1628]
**Describe the bug**
The email addresses of users are saved in a lower case format, but when you login as a user the entered email address isn't transformed to lower case, so the `$user->find($email)` fails, because the strings don't match.

**To Reproduce**
1. Sign up/create a new user with an email address like `HansMustermann@Example.com`
2. Logout
3. Try to login with `HansMustermann@Example.com`

**Expected behavior**
- Personally, I wouldn't expect or want my email address to be saved differently than how I entered it. In theory, a mail server can count `HansMustermann@Example.com` and `hansmusterman@example.com` as two different email addresses.
- As for the login, I would expect the login to match my email address against the saved one regardless of letter casing.

**Screenshots**
![image](https://user-images.githubusercontent.com/920861/55274664-e338a800-52da-11e9-83e9-57221e73c4ea.png)
![image](https://user-images.githubusercontent.com/920861/55274669-fea3b300-52da-11e9-883e-9d6b36ea747b.png)

**Kirby Version**
3.1.1

**Console output**
```
POST http://project.local/api/auth/login 400 (Bad Request)
````

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version 73.0.3683.86

**Comment by bastianallgeier** [comment]
✅

**Comment by eXpl0it3r** [comment]
Cool, thanks for the fast fix! 🙂
