### ISSUE TITLE
CalendarInput: Fix month grid creation

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#163]
There is still some bug in the calculation of the month calendar grid:
<img width="402" alt="screen shot 2018-02-20 at 19 46 57" src="https://user-images.githubusercontent.com/3788865/36442703-f05394d8-1676-11e8-9d4c-e209d244b276.png">

I can't wrap my head around it tonight, but will try to hunt down the bug(s) soon.

**Comment by bastianallgeier** [comment]
Yeah, I maybe shouldn't have implemented that myself :D 
We should also port this to the DateTime field

**Comment by distantnative** [comment]
I will make sure that all use the DateInput.dates helper consistently.

**Comment by distantnative** [comment]
Done
