### ISSUE TITLE
Kirbytext breaks with nested unmatched left parenthesis

### ISSUE THREAD

**Issue by kopfnuss** [getkirby/kirby#163]
The following example text will break kirbytext(). Notice the nested parenthesis where the outer left parenthesis is not matched.

    This (text (will break) kirbytext

Tested on Apache 2.4.4 with PHP 5.4.16 using Kirby 2.0.5 and on Nginx 1.1.19 with PHP 5.3.10 using Kirby 2.0.5.

**Comment by bastianallgeier** [comment]
I think I might have a fix for this. It's unfortunately not just a problem of invalid tags. Check out the latest nightly build.

**Comment by bastianallgeier** [comment]
Ok, sad news. I have to revert to the more stable version without nested parenthesis for now. There seems to be no reliable solution to solve nested parenthesis without seriously breaking the entire text when there are non-matching ones. I already moved back to the old regex in the develop branch.

**Comment by DevCharly** [comment]
IMHO the only reliable solution to fix the nested parenthesis problem is escaping, as also used in markdown (http://daringfireball.net/projects/markdown/syntax#backslash).

Maybe you could consider PR #64 ?
