### ISSUE TITLE
[Panel] Plugin page blueprint not in template list

### ISSUE THREAD

**Issue by mauricerenck** [getkirby/kirby#1630]
When registering a page blueprint within a plugin like so:

```
'blueprints' => [
            'pages/podcasterfeed' => __DIR__ . '/blueprints/pages/podcasterfeed.yml'
    ]
```
It does not appear in the list of available templates when creating a new page in then panel. 

You can create a page using the for example the terminal and then be able to open it in the panel to edit it.

**To Reproduce**

1. Install https://github.com/mauricerenck/kirby-podcaster
2. Log into panel
3. Create a new page
4. There should be a Podcaster template, but there isn't

**Expected behavior**
Registering a page blueprint in a plugin should result in displaying it in the list of available templates in the panel when no limitation to the available templates is set.

**Kirby Version**
3.1.1

** See also**
https://forum.getkirby.com/t/plugin-defined-in-blueprint-not-available/

**Comment by bastianallgeier** [comment]
✅
