### ISSUE TITLE
svg() helper not working reliably with OPcache

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1631]
**Describe the bug**
svg's inlined with helper function are cached by OPcache. When using a svg managed through the panel, there is no way to replace an existing svg without manually reseting OPcache.

**Expected behavior**
helper should always inline the current content of the svg file

**Kirby Version**
3.1.1

**Additional context**
I would suggest replacing the following lines with `return file_get_contents($file);` https://github.com/getkirby/kirby/blob/2b0bfd0b47a308e09117bac95ac674fdf50ce36c/config/helpers.php#L714-L717

**Comment by qwerdee** [comment]
The current version has also a security impact, since arbitrary php code injected into the svg gets executed...

**Comment by bastianallgeier** [comment]
Makes sense to switch to file_get_contents. The security impact is very theoretical in my opinion. But I agree that it's another reason to load it that way.

**Comment by bastianallgeier** [comment]
✅
