### ISSUE TITLE
Search field and pagination in pages/files/users field

### ISSUE THREAD

**Issue by mcbrwr** [getkirby/kirby#1632]
It would be great for larger sites to be able to search items with a search field. Preferably with live search like the global panel searchbox.

<img width="521" alt="screenshot 2019-02-21 at 14 03 54" src="https://user-images.githubusercontent.com/1662038/53170899-8d892580-35e1-11e9-8570-01a2baca28c8.png">

**Comment by MathiasGmeiner** [comment]
@bastianallgeier is this something you could do for the file field as well?

**Comment by distantnative** [comment]
@MathiasGmeiner definitely - when it comes to the pages field, it will also come to the files and users fields.

**Comment by afbora** [comment]
Can we also add paging feature with `limit` property?

**Comment by moritzebeling** [comment]
Maybe there could also be the option for the `info` text that we know from the `pages` section. That could add a little more context to just the page name / file name itself.

**Comment by bastianallgeier** [comment]
# Pages Field
- [x] Pagination
- [x] Search 

# Files Field
- [x] Pagination
- [x] Search

# Users Field
- [x] Pagination
- [x] Search

![search](https://user-images.githubusercontent.com/24532/66666603-4ecbdc80-ec51-11e9-9bbe-330e38f93abe.gif)

**Comment by afbora** [comment]
https://github.com/getkirby/kirby/pull/2193 ?
