### ISSUE TITLE
[TextareaField] Add monospace option

### ISSUE THREAD

**Issue by sambaldwin** [getkirby/kirby#1633]
There are some situations where the writing experience in a [textarea field](https://getkirby.com/docs/reference/panel/fields/textarea) could be improved if the text were set in a monospace font (e.g. when writing code).

The blueprint configuration could be something like:

```yaml
styles:
  type: textarea
  buttons: false
  monospace: true
```

I understand this can be achieved by using a [custom stylesheet](https://getkirby.com/docs/reference/system/options/panel#custom-panel-css), but this feels fragile (the blueprint name and CSS selector could easily fall out of sync), and would need to be set up on a project-by-project basis.

Originally raised as [a question on the forum](https://forum.getkirby.com/t/possible-to-specify-a-monospace-font-for-a-textarea-field/13430).

**Comment by bastianallgeier** [comment]
✅
