### ISSUE TITLE
Translatable slugs / Slugify

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1635]
In order to comply with different transliteration schemes for umlauts and accented characters across languages, Kirby could make use of a library like [Slugify](https://github.com/cocur/slugify).

Slugs could be created based on the page language. Additionally, custom overrides could be provided via the config.

See https://getkirby.slack.com/archives/CBN859614/p1540906834120700.

**Comment by bastianallgeier** [comment]
✅
