### ISSUE TITLE
text excerpts display captions

### ISSUE THREAD

**Issue by sashtown** [getkirby/kirby#164]
Stuff like:

```php
<p><?php echo $article->excerpt(300) ?></p>
```

leads to displaying the `<figcaption>`’s content of any `<figure>` element created with Kirbytext within the defined number of chars at the beginning of the field.

**Comment by bastianallgeier** [comment]
Hm, that's super hard to fix, because the strip tag method, which is used here simply removes the html tags without considering their context. You'd need to set rules for all kinds of siuations in which the text should be removed between tags and in which not.

**Comment by AugustMiller** [comment]
This sounds like an opportunity to add a separate field in the Panel/content file for, say, `blurb`…
