### ISSUE TITLE
Query Language: Cannot Use Collection in `not` Operator

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1647]
**Describe the bug**
I'm trying to use the query language with a `tags` field, but having a hard time excluding items from a collection. When I try to `not()` a collection with another collection, I get "Invalid query result data" shown in the Panel.

For example:
```yaml
query: 'kirby.collection("some-collection").not(kirby.collection("excluded-collection"))'
```

**To Reproduce**
1. Create a tags field in a blueprint
2. Set the query to resemble something like above
3. Load that page in the panel

**Expected behavior**
In this example, I should get results from things in `some-collection` that _are not_ in `excluded-collection`.

**Screenshots**
<img width="289" alt="Screen Shot 2019-04-02 at 2 07 07 PM" src="https://user-images.githubusercontent.com/417182/55436246-9d851500-5550-11e9-9efc-95378e8fb26e.png">

**Kirby Version**
`3.1.1` and `3.1.2-rc.1`

**Console output**
None

**Additional context**
```yaml
query: 'kirby.collection("some-collection")
```
A collection by itself works fine.

```yaml
query: 'kirby.collection("some-collection").not("some/page/uri")'
```
Excluding a specific page URI works fine as well.

```yaml
query: 'kirby.collection("some-collection").not(site.find("some/page/uri"))'
```
However, trying to exclude a page by looking it up with `site.find` fails.

**Comment by distantnative** [comment]
I think the crux here is nesting different queries

**Comment by bastianallgeier** [comment]
✅ Another one for the regex wizard @distantnative 🙌
