### ISSUE TITLE
[Panel] Tags Field Won't Suggest Items with Same Text But Different Value

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1648]
**Describe the bug**
If you have some pages that have the same title (or w/e you're using for the `text`), but different values, then once you select one of them, they won't suggest the others.

Imagine you have the following pages that would appear in the `tags` autocomplete:
```
companies/apple
companies/google
fruits/apple
fruits/orange
```

**To Reproduce**
1. Go to a page with the tags field in the Panel
2. Type `a`
3. See how "Apple" is listed twice (because there are two results)
4. Select the first "Apple"
5. Type `a` again

**Expected behavior**
I would expect to see the other "Apple" listed. If I select that one, I would expect the tags field to show two "Apple" entries.

**Kirby Version**
`3.1.1`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Browser: Chrome 73.0.3683.86

**Additional context**
If you specified `text: '{{ page.uri }}'` in the tags blueprint definition, this problem effectively goes away, but then you don't have nice titles.

**Comment by bastianallgeier** [comment]
✅
