### ISSUE TITLE
[Panel] Cannot Paste Multiple Values in Tags Field w/ `accept: options`

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1649]
**Describe the bug**
When I specify on `tags` Panel field that I only want `accept: options` it becomes seemingly impossible to paste in multiple values.

If the `tags` field allows any inputs (by default), then pasting in values like `foo,bar,baz` and saving converts those into the properly matched values such as `[Foo] [Bar] [Baz]`. This seemed to be better handled in Kirby 2; I don't think that even required saving for the values to be upgraded to separated tags.

**To Reproduce**
1. Go to a `tags` field in a Blueprint that has options (listed or from a query)
2. Append `accept: options`
3. Load that page in the panel
4. Paste in a comma-separated of values

**Expected behavior**
This should be accepted and separated as full-fledged options.

**Kirby Version**
`3.1.1`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Browser: Chrome 73.0.3683.86

**Comment by bastianallgeier** [comment]
✅
