### ISSUE TITLE
kirbytext links get parsed two times

### ISSUE THREAD

**Issue by jtByt-Pictures** [getkirby/kirby#165]
I have some issues with links to other websites. I noticed this as some of my links didn´t open in a new tab even though i added "popup: yes".
So if i use the kirbytag link as followed

    (link: http://getkirby.com) text

it gets parsed to:

    <p><a href="http://getkirby.com"><a href="http://getkirby.com">http://getkirby.com</a></a></p>

which is one a-tag too much!

It´s the same with this kirbytag:

    (link: http://getkirby.com popup: yes)

which get´s parsed to this, where the target does not affect the inner link

    <p><a href="http://getkirby.com" target="_blank"><a href="http://getkirby.com">http://getkirby.com</a></a></p>

it only works well if there is some text added to this kirbytag

    (link: http://getkirby.com text: kirby website)

which leads to

    <p><a href="http://getkirby.com">kirby website</a></p>

but only if the text is not the link itself!!! Then it´s the same as above with the two nested links.

I think that is has something to do with the feature that links are parsed as well if they are added in the text without any kind of markup. But in the documentation there are only two methods documented: with the kirbytag and with the link in angle brackets. It seems to be some undocumented feature which leads to this misbehavior.

**Comment by bastianallgeier** [comment]
This is an issue in Parsedown: https://github.com/erusev/parsedown/issues/178
You can avoid this by using 

```
<http://getkirby.com>
```
instead but I really hope this will be fixed soon.

**Comment by bastianallgeier** [comment]
This is fixed in the develop branch and will be in the next release.
