### ISSUE TITLE
$pages->prepend() Inserts Numeric Key, Breaking $pages->has()

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1653]
**Describe the bug**
When using the `$pages->prepend()` method, the Page object is inserted into the data array with a numeric key of `0`, instead of the typical `$page->id()`. This leads to `$pages->has($page)` reporting false, when it should return true.

**To Reproduce**
```php
$pages->prepend($somePage);
echo $pages->has($somePage);
```

**Expected behavior**
The $pages data key should be the page id.

**Kirby Version**
`3.1.1`

**Comment by neildaniels** [comment]
I haven't checked or looked, but I assume other methods like `$pages->append()` are probably affected too.

**Comment by texnixe** [comment]
If you use the methods as explained in the docs example, it works as expected.

https://getkirby.com/docs/reference/objects/pages/append

**Comment by neildaniels** [comment]
Didn't realize this method expects two parameters. Should the key not be inferred from the object itself?

**Comment by texnixe** [comment]
No, it's inherited from the collection method.
