### ISSUE TITLE
$image->srcset() Returns Empty String on Cropped Images

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1654]
**Describe the bug**
I cannot get the `srcset` function to work on cropped images. Works fine if I don't crop it though.

**To Reproduce**
```php
$postImage = $post->featuredImage()->toFile();
$postImage = $postImage->crop(1024, 576); // take out this line and it works
echo Html::tag('img', null, [
    'srcset' => $postImage->srcset([256, 512, 1024]),
]);
```
Outputs:
```html
<img srcset="">
```

**Expected behavior**
The srcset should be generated based on the cropped image.

**Kirby Version**
`3.1.1`

**Additional context**
I'm using the `im` driver.

**Comment by texnixe** [comment]
> $postImage->thumb() works correctly in this situation.

You mean if you call `srcset()` on the thumb it works? I'm pretty sure it doesn't, `srcset()` only works with a File object, not with a FileVersion object, no matter if that is a "standard" thumb or a cropped image. 

So this is not a bug, but a feature request, really, and should probably go into the ideas repo.

**Comment by neildaniels** [comment]
Yes, the following code works fine:
```php
$postImage = $post->featuredImage()->toFile();
$postImage = $postImage->thumb(1024);
echo Html::tag('img', null, [
    'srcset' => $postImage->srcset([256, 512, 1024]),
]);
```

But, `->thumb()` returns a File object—not a FileVersion object for me (which does seem slightly odd).

However, you're correct that `->crop()` returns a FileVersion object.

**Comment by neildaniels** [comment]
You're right. I was mis-using the `thumb()` function. It does _not_ work with that.

I've created an idea entry for [Support Cropping in $image->srcset()](https://github.com/getkirby/ideas/issues/242)
