### ISSUE TITLE
Disabled pages field style and interactivity broken

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1655]
**Describe the bug**
In a multilingual setup, fields get disabled for secondary languages when they are not translatable:

```
translate: false
```

While pages fields get disabled as well, disallowing interactions, the visual style is misleading:

<img width="922" alt="Bildschirmfoto 2019-04-04 um 12 41 58" src="https://user-images.githubusercontent.com/25466/55550015-80c71980-56d7-11e9-9930-d6a730d110b6.png">

In the example, both fields are disabled, but the pages field on the left looks active and even shows buttons that imply interactivity.

**Expected behavior**
The field should be greyed out and the buttons to add and remove pages should be removed.  
_Important: while changes should be prevented, the field should still be clickable to visit the linked page._

**Kirby Version**
3.1.2RC1, not sure about the latest stable release.

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
> Important: while changes should be prevented, the field should still be clickable to visit the linked page.

👆 This is no longer working with the latest fixes.

**Comment by bastianallgeier** [comment]
✅
