### ISSUE TITLE
[Panel] Clicking on checkboxes field randomly scrolls viewport

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1657]
**Describe the bug**
When browser viewport is below the top edge of a checkboxes field, clicking an option scrolls the viewport in a seemingly random way. 

**To Reproduce**
1. Create a checkboxes field
2. Open panel
3. Scroll below the fields beginning
4. Click on one checkbox

**Expected behavior**
Clicking checkboxes should not cause the browser to scroll.

**Screenshots**
![scrolling checkboxes](https://user-images.githubusercontent.com/6684137/55575012-28f7d500-570e-11e9-9fbe-65efee5e553c.gif).

**Kirby Version**
3.1.1 (didn't try 3.1.2 RC)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73

**Comment by bastianallgeier** [comment]
Ah, shit. The focus event is probably causing this.

**Comment by bastianallgeier** [comment]
✅
