### ISSUE TITLE
[Panel] Navigating dropdown items using up/down arrows keys doesn’t work correctly

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1661]
**Describe the bug**
`KDropdown` highlights the active/focused item. When navigating the dropdown using the up/down arrow keys, disabled items won’t be highlighted. However, you still need to press the arrow key multiple times to skip disabled items.

**To Reproduce**
1. Edit the `home` page.
2. Click on the »Settings« dropdown.
3. Press the down arrow key. The first item, »Rename«, is highlighted.
4. Press the arrow key once more. The first item remains highlighted.

**Expected behavior**
The second enabled item (»Change status«) should be highlighted.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1512805/55672477-dba96e00-589b-11e9-9f56-eec1c72ba9d7.gif" width="350" />

**Kirby Version**
`3.1.2-rc.1`

**Console output**
n/a

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser: Chrome
 - Version: 73.0.3683.86

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by bastianallgeier** [comment]
✅
