### ISSUE TITLE
[Panel] Improve dropdown behavior when pressing the tab key

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1662]
**Describe the bug**
If an open `KDropdown` has the focus, pressing the tab key sets the focus to the next enabled dropdown item. If the last enabled dropdown item already has the focus, focus is moved out of the dropdown and the dropdown stays open.

**To Reproduce**
1. Edit the home page.
2. Click the »Settings« dropdown.
3. Press the tab key two times. Focus is moved out of the dropdown and the dropdown stays open.

**Expected behavior**
There are two alternatives:

1. Pressing the tab key closes the dropdown and moves focus to the next focusable element. To navigate the dropdown items, up/down arrow keys can be used. This behavior is implemented in the [WCAG’s dropdown example](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html). It is similar to the behavior of radio button groups.
2. Pressing the tab key moves focus to the next enabled dropdown item. If the last enabled dropdown item is currently focused, focused is moved out of the dropdown to the next focusable element and the dropdown is closed. (This is similar to the current behaviour. However, currently the dropdown stays open even when focus is moved to an element outside of the dropdown.)

**Screenshots**
<img src="https://user-images.githubusercontent.com/1512805/55672819-d6e6b900-589f-11e9-9cb5-211ac353c9d5.gif" width="350" />

**Kirby Version**
`3.1.2-rc.1`

**Console output**
n/a

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser: Chrome
 - Version: 73.0.3683.86

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by distantnative** [comment]
I would opt for closing the dropdown as the focus moves on (so option 1).

**Comment by bastianallgeier** [comment]
✅
