### ISSUE TITLE
[Panel] Sorting across pagination divide

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1663]
I'm revisiting a "complaint" I had back in June, regarding the ability to sort entries in a paginated section, see https://github.com/k-next/kirby/issues/528.

The reason is that this has come up as a question from our client _twice_ since November.

Here's the first time, also mentioned here https://github.com/k-next/kirby/issues/528#issuecomment-440183572:

> Another weird one - [we] had added a bunch of awards in draft, […] and I have re-ordered the ones that I could, but, a few need to be moved to the 21-40 page - how do you do that - you can’t seem to drag it down and trigger the next page to drop it. See screen shot.

We answered this of course and told her to set the position using the status interface, but now we were actually asked _again_ – showing it is just not self-expanatory.

> I would like to move some of the [entries] to their correct places, but how do you do that if it is not the list being displayed in kirby (as only 20 at a time)?

In the issue referenced above, @nilshoerrmann actually proposed this solution:

> This issue could be solved by making the pagination a drop area saying "move to page 21–40". When moving a page to this zone, the panel could load the next page giving the user the option to integrate the selected page in the new context. Quick mockup:

![](https://user-images.githubusercontent.com/25466/48760076-44a19800-eca5-11e8-9876-0888e7daeef5.png)

**Comment by ghost** [comment]
Also need a fix for this 👍

**Comment by nilshoerrmann** [comment]
Besides the more complex drag and drop solution suggested above (I still like the idea), having an UI to change the maximum number of items displayed per page would be an intermediate solution. It would require some thoughts on persistence though: does the limit only change temporarly in the browser or is it stored per section and used across accounts and devices?

**Comment by johannahoerrmann** [comment]
> does the limit only change temporarly in the browser or is it stored per section and used across accounts and devices?

I'm not sure how this could/would be implemented, but I would find it weird to work across accounts. So if storing it per section across devices would mean for all accounts, I'd say no. If it doesn't, sure!

**Comment by nilshoerrmann** [comment]
I don't know how the Panel deals with this kind of stuff but I see a few options:

1. I can change the limit locally, the setting is lost on reload (no storage).
2. I can change the limit locally and it's stored in `localStorage` and is reapplied in my browser after refreshing.
3. I can change the limit and it's stored globally on the server.

I'd prefer 2, maybe with the option to reset the limit to the default setting.

**Comment by johannahoerrmann** [comment]
I also prefer 2.

**Comment by distantnative** [comment]
We currently store e.g. the pagination page via `localstorage`.

**Comment by bastianallgeier** [comment]
Ok, I spent the entire day to try two things 

a) the drop area where you can throw in items to move them to the next page
b) a limit selector for the pagination

I have to admit defeat. I did not manage to build either of them. Too many roadblocks :( 

To add a select box with variable limits to the pagination dropdown is definitively the more straight forward way, but also less intuitive. The roadblock here is to handle the automatically hidden pagination when it's no longer needed. This is a good feature, but when you toggle between limits this is not what you want. 

The roadblock for the droparea is again drop & drag event issues with our sortable library. Pretty much the same as we had with the textareas or drag & drop between sections :( 

I'm afraid I have to move this to a next release again. Fortunately I'm a few steps further now. I also prepared the pagination dropdown to implement the flexible limits there. You will see the changes in 3.3.0

**Comment by nilshoerrmann** [comment]
@bastianallgeier: In case you still have a copy of your experiments, would you mind sharing them in a feature branch so we can experiment with it a bit? Thanks!

**Comment by afbora** [comment]
I tried to implement with simple way that new dropdown action: `Move to Page Number`

What do you think about that? 🤔 

Dropdown Screen

![screen-capture-149-Mægazine-localhost](https://user-images.githubusercontent.com/3393422/87854164-aaca3c80-c918-11ea-927e-f158a5dbd97a.png)

Pagination Dialog

![screen-capture-152-Mægazine-localhost](https://user-images.githubusercontent.com/3393422/87854175-c0d7fd00-c918-11ea-9a30-4f8cd6db6767.png)

**Comment by bastianallgeier** [comment]
I wouldn't use the page as reference tbh. The page could change anytime and seems like a vague reference. I would prefer to rename it "Move to position" or "Sort" or something like that and then find a better interface to sort it manually even with many entries.

**Comment by nilshoerrmann** [comment]
The page number of the current view isn't a good reference in my eyes. While I still think a drag and drop interaction would be helpful, why not reuse the status dialog here?

<img width="480" alt="grafik" src="https://user-images.githubusercontent.com/25466/87918971-6bfec880-ca77-11ea-97d0-0d57d603a6ca.png">

**Comment by bastianallgeier** [comment]
Yes exactly, it would basically be just a reused status dialog. But the select field in that dialog has never be great. It would be cool if we could come up with a better interface for the selection – especially for long lists.

**Comment by nilshoerrmann** [comment]
I have to admit that I always thought this select UI worked quite well. Yes, it could have a better visual style but hey, it's a select field. But it really shows and does what you want: placing a page at the desired spot.

**Comment by bastianallgeier** [comment]
It works well for anything below 20 items in my opinion. But if the options list gets too long it can be quite annoying and slow.

**Comment by distantnative** [comment]
I just thought if I have have seen a good sorting UX for big collections. But I realized I can’t recall any - neither digitally nor analog.

**Comment by distantnative** [comment]
How about we just add a dialog with the same select UI for now?

And think later about the ideal UI.

Cause given the history of this issue we might be thinking about the ideal for a long while.

Let’s put in something working for the meantime.

**Comment by nilshoerrmann** [comment]
I really think that's a good idea and I think this issue can actually be closed after implementing this. The idea of having a drag & drop interaction to sort across the page divide requires a solid drag & drop solution. I don't see this on the horizon and it has been discussed at length in #1281.

Improving the placement UI from the status dialog is a new issue.

**Comment by nilshoerrmann** [comment]
Regarding the placement UI, switching to a [custom virtual/infinite list](https://tangbc.github.io/vue-virtual-scroll-list/#/fixed-size) while keeping the general idea of the interface will be just fine in my eyes. I really like the simplicity of this UI concept.

**Comment by johannahoerrmann** [comment]
Here's an update to my initial issue with another round of client feedback. The same client, who is very much self-contained regarding adding and editing content in the panel, asked _again_ how to move an entry across a pagination divide just today:

> Can you remind me how you moved it – I could move it up only as far as the last list of 20 but could not get it to shift up to the next set of 20.

We gave a quick rundown of the status button on a page and the dialog to select the exact position. Here is where it gets interesting, as the next response was:

> Never noticed that! 

I can now say this is the one functionality and behavior we have gotten the most questions to, and the one where the solution – which is readily available – is forgotten __every single time__. 

Adding this option directly to the section view will hopefully make it more accessible and less likely to be forgotten, but I do want to advocate for our clients working with Kirby to implement a solid drag and drop function as well.

**Comment by nilshoerrmann** [comment]
Just a few thoughts:

- What if, on sorting, the current section becomes an infinite scrolling list? So if I drag beyond the top or bottom boundaries, the section just starts scrolling, dynamically adding the next items so that the page boundaries just magically disappear. There are great libraries for this kind of virtual scrolling, see above.
- If the cognitive model for dragging items is becoming to complicated in general, it would be an idea to introduce separate views: one for usual browsing and editing and another one for sorting and dragging actions (this might also help with interactions between different sections/containers).

I know there are lots of issues and there are losts of microprojects already but I really love how @bastianallgeier created little libraries over the last years to replace bloated common libraries (think of ProseMirror vs. Writer etc.). All this sorting and drag and drop interactions are taken for granted these days, so Kirby would really benefit of a custom-taylored solution that works for those cases Kirby needs.

**Comment by johannahoerrmann** [comment]
> What if, on sorting, the current section becomes an infinite scrolling list? So if I drag beyond the top or bottom boundaries, the section just starts scrolling, dynamically adding the next items so that the page boundaries just magically disappear. There are great libraries for this kind of virtual scrolling, see above.

@nilshoerrmann Interesting! It does pose the question though what to do with the pagination below. Would the page numbers automatically adjust when scrolling into list items that are technically on a new page? Would the pagination be hidden in that case (practically introducing an automatic "seperate view")?

All said, I do second @distantnative's approach:

> Let’s put in something working for the meantime.

**Comment by distantnative** [comment]
I started with an implementation: https://github.com/getkirby/kirby/pull/2874
For pages, this seems to be alright.

For files we have the problem that there aren't really siblings. Or more that files of the same parent can be in two subset and sorted in only those subsets. Which is actually very confusing. Say you have 8 files but in two files sections with each 4 files. Then you would have duplicate 1-4 sorting numbers.

The flexibility of sections still 🤯

**Comment by distantnative** [comment]
Ok, maybe there is a way where I just ignore the mess of flexible sections and deal with it as the manual sorting via drag'n'drop does too.

**Comment by bastianallgeier** [comment]
✅
