### ISSUE TITLE
Two plugins with api routes as functions: only routes of second plugin applied

### ISSUE THREAD

**Issue by jonathan-reisdorf** [getkirby/kirby#1665]
**Describe the bug**
In Kirby 3.1.2-rc.1, when there are two plugins present that both define api routes, and the one loaded last uses the recently introduced feature to define api routes as callback, the api routes of the first plugin are discarded.

**To Reproduce**
Create two plugins:
```php
<?php
// plugins/a/index.php
Kirby::plugin('test/a', [
  'api' => [
    'routes' => [
      [
        'pattern' => 'test/a',
        'action' => function () {
          return ['success' => true, 'plugin' => 'a'];
        }
      ]
    ]
  ]
]);
```
```php
<?php
// plugins/b/index.php
Kirby::plugin('test/b', [
  'api' => [
    'routes' => function () {
      return [
        [
          'pattern' => 'test/b',
          'action' => function () {
            return ['success' => true, 'plugin' => 'b'];
          }
        ]
      ];
    }
  ]
]);
```
Call the `api/test/a` endpoint. The following error is produced: `Call to a member function pattern() on null`

**Expected behavior**
It should not matter what other plugins do.

**Kirby Version**
3.1.2-rc.1

**Comment by bastianallgeier** [comment]
✅
