### ISSUE TITLE
[Panel] Breadcrumb items not reset when navigating to a custom Panel view

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1667]
**Describe the bug**
If there are multiple list items in the breadcrumb navigation, they won’t be reset if the user navigates to a custom Panel view.

**To Reproduce**

1. Add a custom Panel view (see code snippets below).
2. Got to the Users view using top-left menu.
3. Click on the roles dropdown and select *Admin*.
4. Select *Custom View* from the top-left menu.
5. The breadcrumb has two items: *Custom View / Role: Admin*.

**Expected behavior**
The breadcrumb should have a single list item, *Custom View*.

**Screenshots**
![kirby-panel-breadcrumb](https://user-images.githubusercontent.com/1512805/55756195-3506ce00-5a51-11e9-9a27-74097c08aa80.gif)

**Kirby Version**
`3.1.2-rc.1`

**Console output**
n/a

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser: Chrome
 - Version: 73.0.3683.86

**Smartphone (please complete the following information):**
n/a

**Additional context**

`site/plugins/custom-view/index.php`:

```php
Kirby::plugin('tillprochaska/custom-view', []);
```

`site/plugins/custom-view/index.js`:

```js
import CustomView from './components/CustomView/CustomView.vue';

panel.plugin('tillprochaska/custom-view', {
    views: {
    	'custom-view': {
    		label: 'Custom View',
		component: CustomView,
	},
    },
});
```

`site/plugins/custom-view/components/CustomView/CustomView.vue`:

```html
<template>
    <k-view>
        <k-header>
            Hello World!
        </k-header>
    </k-view>
</template>
```

**Comment by bastianallgeier** [comment]
✅
