### ISSUE TITLE
[Panel] Clicking on a paginated structure field item opens wrong item

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1669]
**Describe the bug**
When paginating a structure field and trying to edit an item on any but the first pagination page, the corresponding item on the first page is opened instead of the clicked item. E.g. if you click on the third item on the second page, the third item on the first page is opened etc.

**To Reproduce**
1. Add pagination to a structure field by setting a limit. Add more items than limit.
2. Go to a pagination page other than the first and click on a item.
3. See the item on the first pagination page opening.

**Expected behavior**
The item you click upon should open.

**Screenshots**

**Kirby Version**
Tested with 3.1.2 but existed before.

**Browser**
Safari on Mac

**Comment by distantnative** [comment]
✅

**Comment by texnixe** [comment]
I tested this with the develop branch and still the same issue.

**Comment by bastianallgeier** [comment]
The develop branch still has the old dist files. Unless you build your js yourself you will still run into it.
