### ISSUE TITLE
Feature idea: Different content representations (file type)

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#167]
This is another one of these advanced features that increase complexity by a bit but are quite useful in my opinion.

Let's say you have a blog on your site. The URI of the blog is http://example.com/blog.
You want to publish an automatically generated RSS feed to let people know when you publish another blog post. Right now, you would create a new `feed.php` template and create a new page at http://example.com/feed. Unfortunately, this gets pretty complex and unmaintainable if you happen to have two different blogs at some point in the future, as the feeds are not linked to the blogs.

Following the REST principles, it makes much more sense semantically if the same page (blog) simply had multiple representations, like http://example.com/blog for the HTML version (default) or http://example.com/blog.rss for the feed. Other representations would be possible as well, like a JSON formatted list of articles or a plain text version (for whatever reason).

This could be achieved by creating multiple template files for that one template (or "page type"). The default variant without extension would use the `blog.php` template (which is fully backwards compatible), the RSS variant the `blog.rss.php` template. The same applies to template controllers.

It could be implemented by parsing the extension, changing the template selection method to use the extension and modifying the rendering method to set the correct MIME type based on the extension (or none to allow custom `header()` calls when no extension is used or the extension is unknown).

The only thing that breaks backwards compatibility is that the `.` character won't be valid in page URIs anymore (but that only breaks compatibility with v2, as v1 handled it the same way like it would be after the change: it allowed adding any extension to a page). Maybe this feature should be needed to be activated using a config option, as it's an advanced feature anyway.

What do you think? Is this a useful feature? Or does it add too much complexity?

**Comment by ausminternet** [comment]
+1

**Comment by lukasbestle** [comment]
I don't think it is is complex feature or complicated to implement at all (I guess it can be done in less than 15 lines of code). What I meant is that this feature adds complexity to the Kirby core. Kirby was always meant to be simple and small and not to become a bloated CMS like Wordpress.
It depends on how @bastianallgeier thinks about this feature.

**Comment by bastianallgeier** [comment]
I actually really like the idea as well!! Would be also a great idea to reintroduce the sitemap.xml URL which is no longer possible in Kirby 2.

**Comment by lukasbestle** [comment]
If you want this to be a feature in an upcoming release, I can implement this and send a PR. Shall I?

**Comment by bastianallgeier** [comment]
@lukasbestle absolutely!! Since I'm now using Git flow, a feature branch would be the best way to add this.

**Comment by lukasbestle** [comment]
Since I don't have write access to the repo, I can't create a separate branch. I can only create one in my fork (what I will have to do anyway) and create a PR.

I will have time for this tomorrow afternoon, stay tuned. :)

**Comment by tobiasfabian** [comment]
Why not automatically output `http://example.com/blog.xml` as an xml file. `blog.json` could automatically output a json file with all the structured data.
Maybe you could define the fields to be shown in a `blog.xml.php` template file.

This would be a REST api without any extra programming.

**Comment by lukasbestle** [comment]
I wanted this to be as flexible as possible. A new definition language for fields to be displayed (don't forget children, other related pages etc.) is too much overhead if someone wants to do something more specific or complicated. Just using the simple "create your own template and don't expect any magic" way of Kirby is much more flexible and easier to understand.

The amount of coding required to get this to work is so minimal for most cases that it doesn't really matter IMO.
