### ISSUE TITLE
Multiselect field: don't render all options at once for really long lists of options

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1671]
**Describe the bug**
When using a `multiselect` with nearly ~2300 items, the performance of displaying/filtering results is nearly unusable.

**To Reproduce**
1. Have a multiselect field with like 2000 options in it (either manually or with a query like index)
2. Click on it to display

**Expected behavior**
I would have expected the dialog to display relatively quickly. It currently takes about 3 or 4 seconds.

**Kirby Version**
`3.1.2`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Chrome 73.0.3683.103
 - Safari 12.1 (14607.1.40.1.4)

**Additional context**
The `tags` field is much more performant—it still fills _slightly_ laggy, but is under 1/2 second.

**Comment by distantnative** [comment]
Could be a tricky one. Since all 2300 options are rendered as DOM elements, I would expect it to be as unperformant at the current state. An idea would be if there is any way to implement lazy loading of the options in the dropdown while scrolling through it. But that could be tricky.

**Comment by afbora** [comment]
If we add the following two features, I think it will be useful in terms of performance and usability.

- Minimum search term length
- Limiting display of the search box to large result sets

Reference feature:
https://select2.org/searching#minimum-search-term-length

````
fields:
  categories:
    label: Categories
    type: multiselect
    minSearch: 3
    display: 20
    options:
      ...
      ...
      ...
````

**Comment by bastianallgeier** [comment]
I guess we also should move the options loader to a separate API call and not handle that when loading the fields section. It would probably be wise to do the same for the tags field and maybe even for the regular select box.

**Comment by distantnative** [comment]
Another way could be using https://akryum.github.io/vue-virtual-scroller

**Comment by bastianallgeier** [comment]
✅
