### ISSUE TITLE
Typing a parenthesis permanently breaks the tags field

### ISSUE THREAD

**Issue by Jayshua** [getkirby/kirby#1673]
**Describe the bug**
When typing the "(" character into the tags field this error message completely replaces the field. It requires a page-refresh to bring the field back.

![image](https://user-images.githubusercontent.com/1654103/55994894-9e1c5a80-5c78-11e9-9238-c757421659a6.png)

**To Reproduce**
1. Go to a panel page that uses the tags field.
2. Try entering an opening parenthesis into the the filed.
3. Watch the field disappear as a red info box unexpectedly replaces it. I'm pretty sure the red is the blood shed by the tags field after the info box violently slew it with a Katana. Never trust that info box.

**Expected behavior**
The field shouldn't disappear. Nor should the evil info box be summoned.

**Kirby Version**
3.1.1

**Console output**
```
SyntaxError: "unterminated parenthetical"
    search http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/app.js:1
    type http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/app.js:1
    input http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/app.js:1
    ie http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
    n http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
    _wrapper http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
app.js:1:152920
    errorCaptured http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/app.js:1
    re http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
    ie http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
    n http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
    _wrapper http://localhost:8080/media/panel/d9e15b7599116e38f870d0dc600c08a4/js/vendor.js:39
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 66.0.3

**Comment by distantnative** [comment]
✅
