### ISSUE TITLE
Users field with max: 1

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1674]
**Describe the bug**
A users field with `max: 1` option has two UI/UX issues:

1. While there can only be one user selected at a time, the list displays a sort handle although there is nothing to sort.
2. When a user has been selected, the `Select` button disappears. On the one hand, this is fine because the maximum number of users has been reached. On the other hand, this makes changing the user selection cumbersome: you have to delete the existing user entry first – which will restore the `Select` button – and select a new user afterwards.

**To Reproduce**
Consider this blueprint setup:

```yaml
authors:
  type: users
  label:
    de: Autoren
    en: authors
  required: true
  translate: false
  max: 1
```

**Expected behavior**
1. There shouldn't be a sort handle (unless the handle is for dragging, but I tried dragging to a textarea and that didn't have an effect).
2. In my eyes, keeping the `Select` button in the interface would be appropriate, maybe changing the copy to `Change`.

**Kirby Version**
Kirby 3.1.2 and later (currently using `develop` at b448ba6d2c18ab1364a3b6d0d52c00359be7b0cf)

**Browser and OS:**
Latest Firefox on macOS Mojove.

**Additional context**
It might be possible that the similar fields for pages and files show the same behaviour – I haven't tested that.

**Comment by distantnative** [comment]
@bastianallgeier has this been solved with your recent changes? https://github.com/getkirby/kirby/commit/5cd4391fbd5c28ebf937c8a474a974a82d9af76f (I assume from looking at the code at least 1. - probably not 2.)

**Comment by bastianallgeier** [comment]
1. ) is definitely fixed. 

I think it would be good to rewrite this ticket and convert it to an idea as it's no longer a bug.

**Comment by distantnative** [comment]
Added an idea issue for this: https://github.com/getkirby/ideas/issues/259

**Comment by nilshoerrmann** [comment]
@distantnative: Thanks!
