### ISSUE TITLE
[Panel] Browsing through files wrong ordering without specifying sort

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1675]
**Describe the bug**
In the files details view it is not possible to navigate to next and previous file when sorting is not explicitly set in all the .txt files. When trying to access the previous file I end up in a endless loop of only to files and the button to the next file is disabled all the time.

**To Reproduce**
1. Upload multiple files to a page through the panel
2. Make sure no sort field in is set in the .txt files (eg. `sort: 1`)
3. Go to the files details page
4. Try to navigate to the next file or previous file.

**Expected behavior**
It should be possible to browse through all the files in the order they are displayed in the overview without having to explicitly sort them.

**Kirby Version**
3.1.2

**Desktop**
 - OS: e.g. macOS
 - Browser: chrome, safari, firefox

**Comment by afbora** [comment]
I can't reproduce on Windows machine with Chrome. Is it a MacOS specific issue or I did misunderstand?

![macos](https://user-images.githubusercontent.com/3393422/65819400-cc8cf280-e224-11e9-8c32-c39b3a5fb407.gif)

Tested on 3.1.2 and 3.2.5 versions without `sort` field

**Comment by qwerdee** [comment]
Thanks for getting back on this and yes you understood it correctly. I just tested it again with a fresh 3.2.5 install on Mac and Ubuntu and it is still like I described. In your recording it is correct, however when I do the exact same steps (fresh starter kit, add new album page, upload same images in the panel) I get the correct alphabetic order in the overview but in the details view it is different... (dumbo.jpg > abba.jpg > bird-reynolds.jpg)

**Comment by afbora** [comment]
> but in the details view it is different... (dumbo.jpg > abba.jpg > bird-reynolds.jpg)

I realized that issue (only 3.2.5) and i'll check it soon.

> when I do the exact same steps (fresh starter kit, add new album page, upload same images in the panel) I get the correct alphabetic order in the overview but in the details view it is different... (dumbo.jpg > abba.jpg > bird-reynolds.jpg)

To understand better; In the last case then the navigation is working but the order is wrong, is it correct? Or did you run this second test on a Windows machine?

**Comment by qwerdee** [comment]
> To understand better; In the last case then the navigation is working but the order is wrong, is it correct? 

Exactly. When I open the details view of abba.jpg I can navigate left to to dumbo.jpg or right to bird-reynolds.jpg.

> Or did you run this second test on a Windows machine?

Unfortunately I don't have a windows machine to test it. But in your recording it seemed to be working fine.

**Comment by afbora** [comment]
> Exactly. When I open the details view of abba.jpg I can navigate left to to dumbo.jpg or right to bird-reynolds.jpg.

Great. You mentioned in the first message that navigation was not working. We have now confirmed that navigation is working but there is an issue in the order.

> Unfortunately I don't have a windows machine to test it. But in your recording it seemed to be working fine.

That video was shot in version 3.2.4. The error only appears in 3.2.5.

**Comment by qwerdee** [comment]
You're right. I just compared 3.2.4 and 3.2.5. on mac. In 3.2.4 the navigation is broken, I can only navigate left and end up in an endless loop between only two images. With 3.2.5. I can now navigate to every image and only the order is wrong.

**Comment by bastianallgeier** [comment]
✅
