### ISSUE TITLE
Improved language file handling

### ISSUE THREAD

**Issue by mzur** [getkirby/kirby#168]
Currently the files containing the language variables in `site/languages/` are identified by the language code (`de.php`, `en.php`) so there is only a single file for all variables of a language.

I think the situation would be improved if there could be *multiple* files for each language (`*.de.php`, `*.en.php`) in addition to the "default" language files (for backwards compatibility). This would be very useful if multiple plugins are in use that each provide their own set of language variables. Every plugin then would simply add new files to the `languages/` directory or even better, links to git submodules of the plugins.

A workaround for this would be the use of `include_once` in the "default" language file but I think builtin support would be much more convenient. What do you think?

**Comment by lukasbestle** [comment]
In my opinion, plugins should rather store and load their own variables for languages (as manually copying a language definition file for each plugin makes it a bit complicated for users).

Another advantage of this approach is that each plugin can have its own set of available languages, which makes it possible to fall back to the best language for each plugin individually (or to easily add the language to the plugin using a pull request).

### Implementation example

A new plugin named `exampleplugin` wants to define language variables. The main file of the plugin (`exampleplugin.php`) contains the following code to load the plugin language file in a subdirectory of the plugin:

```php
$code = null;
if(site()->multilang()) {
  // actual language
  $code = site()->language()->code();
} else {
  // use a config option for single-language sites
  $code = C::get('exampleplugin.language', 'en');
}

// check if the language file exists
if(is_file(__DIR__ . DS . 'languages' . DS . $code . '.php')) {
  require_once(__DIR__ . DS . 'languages' . DS . $code . '.php');
} else {
  // fallback language
  require_once(__DIR__ . DS . 'languages' . DS . 'en.php');
}
```

The plugin has now included a language file that works just like the general language files: It uses the `L` class to set variables.

**Comment by mzur** [comment]
@lukasbestle Sounds like a better solution, thanks :-)

**Comment by mzur** [comment]
@lukasbestle Unfortunately I have to reopen this issue. I have tried to implement loading the language file as you suggested but encountered a problem. At the time the plugin is loaded `site()->language` is not yet set because `site()->visit()` (which [sets](https://github.com/getkirby/kirby/blob/dd6ef0afc10fda431a91990cf56f83df79f072cf/branches/multilang/site.php#L161) the current language) is [called](https://github.com/getkirby/kirby/blob/ca4564f886eb15de395d7f40e60426e266400042/kirby.php#L576) *after* [loading the plugins](https://github.com/getkirby/kirby/blob/ca4564f886eb15de395d7f40e60426e266400042/kirby.php#L559). Is this a bug? I believe a plugin should be able to access the current language.

**Comment by bastianallgeier** [comment]
All plugins are intentionally loaded before the router is being run. Thus plugins have a chance to set their own routes. This also means that you don't have access to the current language in the plugin unless you create a plugin function which is launched in a controller or template. In that function you can easily get access to the language and then load any custom language file depending on it.

**Comment by mzur** [comment]
But this would result in the language file being loaded every time the plugin function is called on the page, right?

**Comment by lukasbestle** [comment]
You could check if `l::get('yourkey')` returns a value. If it does, you know the language variables have already been set.

**Comment by mzur** [comment]
That sounds a bit hacky to me. I'll think about this some more. Thank you both again :-)
(maybe you could check out my [comment here](https://github.com/getkirby/panel/pull/281#issuecomment-69049108); that's another thing I'm stuck at)
