### ISSUE TITLE
Deleting a group of pages doesn't work.

### ISSUE THREAD

**Issue by kgevaert** [getkirby/kirby#1681]
**Deleting a group of pages doesn't work**

@texnixe
more info https://forum.getkirby.com/t/deleting-a-group-of-pages-fails/13771/9

**How to reproduce:**
1. Download the latest version of Startkit
2. Implement code on home.php template

```
<?php
$kirby = kirby();
$kirby->impersonate('kirby');

$notes=page('notes')->children();
foreach($notes as $note){
  echo $note->title().'<br/>';
  $note->delete(true);
}

$photography=page('photography')->children();
foreach($photography as $item){
  echo $item->title().'<br/>';
  $item->delete(true);
}
?>
```
3. Run the homepage
4. Result:
The photography-pages are deleted except 1 (the second in the list ‘trees’ has not been deleted)
For the notes are successfully deleted page 1, 3, 5 and 7. (note 2, 4 and 6 are not deleted).

**Expected behavior**
All subpages should be deleted

**Comment by distantnative** [comment]
@kgevaert I think @bastianallgeier mentioned something in an older issue in that regard:

>Second: we have a bit of a problem here with a weird behavior of PHP's iterators. The $page->delete() method unsets the element from the parent collection while you are still looping through it. That way the loop will skip some elements.
>
>You can avoid this by looping through the original data array instead.
>
> ```php
> 'page.changeStatus:after' => function ($newPage, $oldPage) {
>    if($newPage->intendedTemplate() == 'project' && $newPage->status() == 'unlisted') {
>         foreach($newPage->drafts()->data() as $phase) {
>                 $phase->delete();
>             }
>         }   
>     }
> }
> ```

So not as solution but maybe as quick fix, you could try:

```php
foreach($page('notes')->children()->data() as $note){
  echo $note->title().'<br/>';
  $note->delete(true);
}
```

**Comment by kgevaert** [comment]
@distantnative 

This code doesn't work if you want to delete the 'photography-items' on a hook in the starterkit. This removes only 1 item.

```
 'hooks' => [
  'page.changeStatus:after' => function ($newPage, $oldPage) {
     if($newPage->intendedTemplate() == 'about' && $newPage->status() == 'unlisted') {
        foreach( page('photography')->children()->data() as $item){
	   $item->delete(true);
        }
    }
  }
]
```

**Comment by afbora** [comment]
It seems really hard to achieve but i have an idea. 
Let's create a new method (`deleteChildren()`) to the `PageActions` class and use @bastianallgeier method. 

For example, something like that:

```php
public function deleteChildren(bool $drafts = false): bool
{
    $pages = $drafts === true ? $this->drafts() : $this->children();
    
    if($pages->count() > 0) {
        foreach($pages->data() as $page) {
            $page->delete();
        }
        
        return true;
    }
    
    return false;
}
```

And usage:

```php
$notes = page('notes');
$notes->deleteChildren();
echo $notes->title();
```

So we can delete the subpages while **keeping the main page**. 
As you know, when we use the `delete()`, method, the page itself is deleted along with the subpages.

Do you think it makes sense and works? 🤔 

And related/duplicated issue: https://github.com/getkirby/kirby/issues/1232

**Comment by bastianallgeier** [comment]
This the same issue: https://github.com/getkirby/kirby/issues/1232

**Comment by texnixe** [comment]
@afbora What would be the correct way to delete multiple pages now, because it still doesn't seem to work:

https://forum.getkirby.com/t/deleting-multiple-pages-from-frontend/16424

**Comment by afbora** [comment]
@texnixe I have tested now on 3.3.0 starterkit and works perfect for `notes` pages. Here my test:

**Request URL:**

> notes?removeItems[]=across-the-ocean&removeItems[]=a-night-in-the-forest&removeItems[]=in-the-jungle-of-sumatra

**/controllers/notes.php**

````php
return function ($page, $kirby) {
    $kirby->impersonate('kirby');
    
    if (isset($_GET['removeItems'])) {
		$items = $_GET['removeItems'];
		foreach ($items as $item) {
			if ($page->children()->find($item)) {
				$itemRemoved = $page->children()->find($item)->delete();
			}
		}
        
		if (isset($itemRemoved)) {
			echo "Success";
		} else {
            echo "Failed";
        }
	} else {
        echo "Not found!";
    }
    
    exit;
};
````

**Comment by afbora** [comment]
@texnixe maybe I didn't fully understand the problem?

**Comment by texnixe** [comment]
Ok, using this code from the home template in a fresh Starterkit, results in all notes children to be deleted.

```
$kirby->impersonate('kirby');
foreach (page('notes')->children() as $child) {
  $child->delete();
}
$kirby->impersonate();
```

Using the same code, but this time trying to delete the children of the `photography` page, results in only one item to be deleted per page reload:

```
$kirby->impersonate('kirby');
foreach (page('photography')->children() as $child) {
  $child->delete();
}
$kirby->impersonate();
```

As soon as I remove the manual sorting numbers from the `photography` page's children, those subpages all get deleted as expected as well.

**Comment by texnixe** [comment]
Should I reopen this issue or create a new one?

**Comment by distantnative** [comment]
@texnixe Could you open a new one, but reference this one? Thanks.
