### ISSUE TITLE
Language Switch misses entries when before navigation loop and css() function

### ISSUE THREAD

**Issue by RastaTux** [getkirby/kirby#1682]
**Describe the bug**
The language switch just shows the default language when the $kirby->languages() foreach loop is before the css() function and navigation $pages->listed() loop.

**To Reproduce**
1. Install fresh copy of starterkit
2. Enable two languages in the admin panel (german as default and english f.e.)
3. Move the [language switch type B](https://getkirby.com/docs/guide/languages/switching-languages) **BEFORE** the navigation loop.
4. Remove css() function.
5. On the german default homepage, both languages are shown. When changing to english, just german is shown the english selection is removed.

**Expected behavior**
Both languages should been always in the output. This works if you leave the css() function or the navigation menu before the language switch.

**Kirby Version**
Newest (3.1.2.), tested on 3.1.1. as well.

**Desktop (please complete the following information):**
 - OS: [Linux of course ;)]
 - Browser [chrome]
 - Version [latest and greatest]

**Additional context**
This bug was proved by texnixe in [this forum thread](https://forum.getkirby.com/t/english-does-not-show-up-when-activated/13754).
The problem could be the same or similar to [this one ](https://github.com/getkirby/kirby/issues/1163), however its marked as solved here.

**Comment by bastianallgeier** [comment]
✅

**Comment by RastaTux** [comment]
So will this be introduced in the version 3.1.4?

**Comment by distantnative** [comment]
Yes.
