### ISSUE TITLE
Smartypants not working with kirbytext() method

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1686]
**Describe the bug**
Setting the `smartypants` option to true like described [in the docs ](https://getkirby.com/docs/guide/content/text-formatting#smartypants) throws a type error

>TypeError thrown with message “Argument 3 passed to Kirby\Cms\App::{closure}() must be of the type array, boolean given

Obviously, it expects an array. So when I add an array of options and call the `smartypants()`method on a field (`$page->text()->smartypants()` or `$page->text()->kirbytext()->smartypants()`), it works as expected. However, calling `kirbytext()` only has no effect.

**Expected behavior**
It should be possible to enable Smartypants generally via the config while at the same time allowing to set an array of option.

**Kirby Version**
3.1.2

**Comment by judbd** [comment]
The general option is expected to work on `->kirbytext()` and `->kirbytextinline()` as well.

**Comment by distantnative** [comment]
✅
