### ISSUE TITLE
Special characters encoding problem on browser source code

### ISSUE THREAD

**Issue by byybora** [getkirby/kirby#169]
In website source code, some special characters seen like following:

**On browser source code:**
````
T&uuml;rkçe Website
````

**Frontend as normal seen:**
````
Türkçe Website
````

**On kirby panel:**
````
Türkçe Website
````

Only browser source code characters are broken. I tried following proceses:

1. Be sure file encoding as utf8
2. htaccess AddDefaultCharset UTF-8
3. Be sure meta charset between <head>

But the issue still continue.

**Comment by lukasbestle** [comment]
Hm, for me, the text in the frontend and in the Panel look totally equal to me.
What exactly is the problem?

**Comment by byybora** [comment]
You will see the issue when you look into browser source code with CTRL +
U, not F12.

ı ıı ııı ahmetıbora ı webdeveloper
4 Oca 2015 22:58 tarihinde "Lukas Bestle" <notifications@github.com> yazdı:

**Comment by byybora** [comment]
**Frontend:**
![1](https://cloud.githubusercontent.com/assets/3393422/5610418/f220d2bc-94bf-11e4-8e89-0771802132db.jpg)

**Original codes in browser source code:**
![2](https://cloud.githubusercontent.com/assets/3393422/5610419/f2239c36-94bf-11e4-97eb-b24f3c428c68.jpg)

**Comment by lukasbestle** [comment]
Could you please describe the problem in a bit more detail? What exactly does not work? What would you expect, what does Kirby do instead?

**Comment by byybora** [comment]
![1](https://cloud.githubusercontent.com/assets/3393422/5611535/75d2e9e6-94d0-11e4-9e8e-de94b6e2b917.jpg)

In above screenshot as normal seen is perfect!

![2](https://cloud.githubusercontent.com/assets/3393422/5611536/75eec436-94d0-11e4-9d14-c9d8562ca948.jpg)

But in browser source code (CTRL+U), there is a issue about encoding. It should be `Türkçe Website` too in source code instead of `T&uuml;rkçe Website`

**Comment by lukasbestle** [comment]
What you see there are HTML entities. This is not actually an issue, but totally valid.

If you really want these entities to be UTF8 chars, could you please post the line of your header snippet/template where this title is generated?

**Comment by byybora** [comment]
`````
	<?php if($page->isHomePage()): ?>
	   <title><?php echo $site->title()->html() ?> </title>
	<?php elseif($page->meta_title() != ''): ?>
	   <title><?php echo $page->meta_title()->html() ?></title>
	<?php else: ?>
	   <title><?php echo $site->title()->html() ?> | <?php echo $page->title()->html() ?></title>
	<?php endif ?>
	
	<?php if($page->meta_description() != ''): ?>
	   <meta name="description" content="<?php echo $page->meta_description()->html() ?>" />
	<?php else: ?>
	   <meta name="description" content="<?php echo $site->description()->html() ?>" />
	<?php endif ?>

	<?php if($page->meta_keywords() != ''): ?>
	   <meta name="keywords" content="<?php echo $page->meta_keywords()->html() ?>" />
	<?php else: ?>
	   <meta name="keywords" content="<?php echo $site->keywords()->html() ?>" />
	<?php endif ?>
````

My `header.php` snippet file and it has utf8 w-bom encoding.

**Comment by lukasbestle** [comment]
You currently use the `->html()` field method for all of your fields. This method is responsible for converting non-ASCII chars to their entities.

If you don't want to have entities in your source code (it doesn't really matter, because both variants are totally equal), simply remove the `->html()` part from the code.

**Comment by byybora** [comment]
I didnt know `html()` funtion what for. Thanks, it worked!
