### ISSUE TITLE
[Panel] Pagination Broken on Pages Section When Using `page:` Setting

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1693]
**Describe the bug**
When specifying a `page: ` attribute of Pages Section in a Blueprint, the pagination buttons functionally don't do anything.

I assume this is a bug (that specifying a page merely is what page should be loaded first).

If this is intentional, then I treat this as a feature enhancement that the arrow buttons and page specifier (when you click on the pagination information) should be disable.

**To Reproduce**
1. Have a `pages` section (not field) in a Blueprint
2. Specify a page, like `page: 2`
3. Load the page in the panel and attempt to navigate to another page in that Pages section

**Expected behavior**
You can still navigate to other pages.

**Screenshots**
<img width="211" alt="Screen Shot 2019-04-16 at 2 45 49 PM" src="https://user-images.githubusercontent.com/417182/56246287-6f2a2e00-6056-11e9-8445-be22ad0f18b1.png">

**Kirby Version**
`3.1.3-rc.1`

**Comment by bastianallgeier** [comment]
✅
