### ISSUE TITLE
$page->update() not working in multilang setup

### ISSUE THREAD

**Issue by georgobermayr** [getkirby/kirby#1698]
**Describe the bug**
I'm implementing a route for content migrations in a mulitanuage site. For that I use the `$page->update()` method. The fields I want to change are rightly changed, however the rest of the content in a translated content file is reseted to the content of the default language. 

**To Reproduce**
Steps to reproduce the behaviour:
I have a route like this: 
```
return [
  'pattern' => 'migrations/products/83XPWtsPYN9XuMWK/headline',
  'action'  => function () {
    kirby()->impersonate('kirby');

    // Get all pages
    $products = site()->index();

    foreach ($products as $product) {
      foreach ($product->translations() as $language) { 
        $languageCode = $language->code();

        // Upate page
        $product->update([
          'headline' => '', 
        ], $languageCode);

        echo 'Updated product ' . $product->title() . ' in language ' . $languageCode . PHP_EOL;
      }
    }
  },
  'method' => 'POST'
];
```

The content files: 
content.de.txt **before** calling the route
```
Headline: German Headline

----

Descriptionshort: German Description
```
content.en.txt **before** calling the route
```
Headline: English Headline

----

Descriptionshort: English Description
```

content.de.txt **after** calling the route
```
Headline:

----

Descriptionshort: English Description
```
content.en.txt **after** calling the route
```
Headline: 

----

Descriptionshort: English Description
```
So the change to the headline field was performed correctly, but the english description is copied to the german text file. 

Of course I would except the german fields I didn't update to stay the same as before

**Kirby Version**
3.1.2-rc.1

**Additional context**
I did a bit of digging and I think the issue is somewhere in the `update` function of `ModelWithContent` class: 
```
        $form = Form::for($this, [
            'input'          => $input,
            'ignoreDisabled' => $validate === false,
        ]);
```
This returns the english text merged with the german update content.

**Comment by bastianallgeier** [comment]
✅
