### ISSUE TITLE
Modifying a structure field value causes an error with no stack trace

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1700]
**Describe the bug**
Manually turning a structure value from string into array causes an error with no stack trace.

**To Reproduce**
1. [Download the Kirby Starterkit](https://getkirby.com/try)
2. Modify `content/3_about/about.txt` from:
    ```
    -
      platform: Twitter
    ```

    ...to

    ```
    -
      platform:
        - Twitter
    ```
3. Open the homepage
4. You should see the following error:

    ![977ac3cc39fb23827e5287ae093b72517de38afa](https://user-images.githubusercontent.com/5570098/56433464-a2302400-62d9-11e9-8aeb-4f8b6e167a8b.png)

**Expected behavior**
A stack trace telling you where the error came from.

**Kirby Version**
3.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 73.0.3683.103 (Official Build) (64-bit)

**Comment by distantnative** [comment]
For me there is a stack trace:
<img width="372" alt="Screenshot 2019-05-10 at 17 07 09" src="https://user-images.githubusercontent.com/3788865/57537214-17759e80-7346-11e9-8fb2-d0571510a2cc.png">
