### ISSUE TITLE
Markdown Extra Breaks When Including a `<script>` Tag

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1701]
**Describe the bug**
When Markdown Extra is enabled, including something like a `<script>` tag causes everything after that to be excluded from the parsed HTML.

**To Reproduce**
1. Use latest StarterKit
2. Add the following to the `/config/config.php`
```php
    'markdown' => [
        'extra' => true,
    ],
```

3. Go to one of the content pages in the panel (such as `http://localhost:8000/panel/pages/notes+exploring-the-universe`)
4. Add _either_ of the following to the middle of the text.

```
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">See the world through a sea cave at Apostle Islands National Lakeshore. Pic by Michael DeWitt (<a href="https://t.co/7u0uZGuWtK">https://t.co/7u0uZGuWtK</a>) <a href="https://twitter.com/hashtag/Wisconsin?src=hash&ref_src=twsrc%5Etfw">#Wisconsin</a> <a href="https://t.co/2WeJNXqbDW">pic.twitter.com/2WeJNXqbDW</a></p>— US Department of the Interior (@Interior) <a href="https://twitter.com/Interior/status/1119256441343369216?ref_src=twsrc%5Etfw">April 19, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

or

```
<blockquote>A quote.</blockquote> <script></script> 
```

The real qualifier is that the `<script></script>` must be on the same line as the `<blockquote></blockquote>`.

**Expected behavior**
The content _after_ the `<script>` should still be there. Not sure if omitting the `<script>` is intentional or not.

**Screenshots**

Markdown Extra Disabled:
<img width="751" alt="Screen Shot 2019-04-19 at 10 11 46 AM" src="https://user-images.githubusercontent.com/417182/56434942-9289ee80-628b-11e9-89f6-e50281e6fbc5.png">

Markdown Extra Enabled:
<img width="749" alt="Screen Shot 2019-04-19 at 10 10 50 AM" src="https://user-images.githubusercontent.com/417182/56434960-9f0e4700-628b-11e9-89d3-9cbd810b6deb.png">

**Kirby Version**
`3.1.2` (StarterKit)

**Comment by neildaniels** [comment]
This is probably related: if you upload an image and use an `(image: )` tag on the start of a paragraph of text, the image will appear but absolutely no content after the image.

Again, this issue only occurs when Markdown Extra is enabled.

For example:

```
(image: image1.jpg) The Big Oxmox advised her not to do so, because there were thousands

She packed her seven versalia, put her initial into the belt and made herself on the way.
```

will render just the image.

**Comment by lukasbestle** [comment]
This is an issue in Parsedown Extra, the library we use to render the Markdown Extra format. I have reported it at https://github.com/erusev/parsedown-extra/issues/130. I will let you know once I get a reply over there. :)

**Comment by lukasbestle** [comment]
We will switch to a different Markdown parser in 3.3.0. I will check that your code example will work with the new parser we choose. :)

**Comment by lukasbestle** [comment]
Closing this in favor of #1961.
