### ISSUE TITLE
[Panel] Cannot Select Hour/Minute of Time Field (Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1702]
**Describe the bug**
When creating a new page with a `time` field, it is completely impossible to select an hour/time on a 24 hour notation field, and the 12 hour notation field requires you to pick AM/PM first.

This started occurring with `3.1.3-rc.1`. I cannot reproduce with the `3.1.2` StarterKit.

**To Reproduce**
1. Add a time field to a Blueprint, with no default value
2. Create a new page with that template
3. The time field should appear with no set values
4. Try to set the hour field
5. An error is shown, varying by browser

**Screenshots**
Before selection:
<img width="291" alt="Screen Shot 2019-04-19 at 3 05 10 PM" src="https://user-images.githubusercontent.com/417182/56445922-8cf4ce80-62b4-11e9-9399-2b9520a62e14.png">

Safari:
<img width="298" alt="Screen Shot 2019-04-19 at 3 00 55 PM" src="https://user-images.githubusercontent.com/417182/56445844-2a9bce00-62b4-11e9-8020-41a7eb194a05.png">

Chrome:
<img width="263" alt="Screen Shot 2019-04-19 at 3 01 57 PM" src="https://user-images.githubusercontent.com/417182/56445848-3091af00-62b4-11e9-8ce8-3c7ea4585ace.png">

**Kirby Version**
`3.1.3-rc.1`

**Console output**
Safari:
```
[Error] TypeError: null is not an object (evaluating 'this.meridiem.toUpperCase') — app.js:1:107120
	errorCaptured (app.js:1:153579)
	re (vendor.js:41:11632)
	oe (vendor.js:41:11899)
	n (vendor.js:41:13650)
	oe (vendor.js:41:11764)
	$emit (vendor.js:41:26569)
	onInput (app.js:1:87619)
	onInput
	oe (vendor.js:41:11764)
```

Chrome:
```
app.js:1 TypeError: Cannot read property 'toUpperCase' of null
    at a.onInput (app.js:1)
    at a.setMinute (app.js:1)
    at oe (vendor.js:41)
    at a.n (vendor.js:41)
    at oe (vendor.js:41)
    at a.t.$emit (vendor.js:41)
    at a.onInput (app.js:1)
    at input (app.js:1)
    at oe (vendor.js:41)
    at HTMLSelectElement.n (vendor.js:41)
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Safari 12.1 (14607.1.40.1.4)
 - Chrome 73.0.3683.103

**Additional context**
If you use the `notation: 12` variant of the `time` field, if you select AM/PM before an hour or minute, the field works correctly.

**Comment by bastianallgeier** [comment]
✅
