### ISSUE TITLE
PanelPlugins: Unit test fails locally

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1704]
[This unit test](https://github.com/getkirby/kirby/blob/3.1.3-rc.1/tests/Cms/PanelPluginsTest.php#L94-L103) consistently fails on my machine because the CRC32 that gets generated only has 9 characters (the generated number is only 9 figures long and not 10 as expected).

According to [the PHP docs](https://www.php.net/manual/en/function.crc32.php), the `crc32()` function can not by relied on for consistent results. As far as I can tell, this is not actually an issue when actually using the code (as the ID only needs to be consistent on the same machine, not with other machines), but that the test fails is a bit annoying.

Two options:

1. Make the test less strict and make it also accept 9 character IDs.
2. Use `hash('crc32', $value)` instead, which outputs a hex representation that is guaranteed to be always 8 bytes long. It's not a number though but a string, but I assume this should be fine as the `PanelPlugins::id()` method returns a string anyway.

**Comment by bastianallgeier** [comment]
✅
