### ISSUE TITLE
Installation of Kirby... comes with attached :80 to URL

### ISSUE THREAD

**Issue by chrisgwynne** [getkirby/kirby#171]
Hey, so I've installed Kirby, set it all up fine and running well (for me).

In my sites panel, the URL is listed as xxxx.co.uk:80 - all url's when viewed in source come attached with :80 as well. How do I go about removing this? It seems to be causing problems for people viewing the website, they're not able to load the website up.

**Comment by lukasbestle** [comment]
That is a bug of the current version that is fixed in the `develop` branch.
You can use [these commands](https://gist.github.com/bastianallgeier/8d0979055a3cb5ada517) to checkout the latest development version until the next official version is out.

**Comment by chrisgwynne** [comment]
This looks like it's solved it, many thanks @lukasbestle
