### ISSUE TITLE
Long Blueprint Tab Titles Don't Have Padding and Don't Stay Centered

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1711]
**Describe the bug**
When a Blueprint tab has a long title, there is no padding to the left or right of the text. If the content is so long to require wrapping, the text is just looks sloppy being left-aligned.

**Expected behavior**
I would expect text to always be center-aligned and have at least some padding on the left and right edges.

**Screenshots**
```
    label: Some Long Blueprint Tab Title
```
<img width="298" alt="Screen Shot 2019-04-22 at 2 19 28 PM" src="https://user-images.githubusercontent.com/417182/56532089-05080200-650a-11e9-8768-7a58400c456c.png">

```
    label: Some Long Blueprint Tab Title That Wraps
```
<img width="285" alt="Screen Shot 2019-04-22 at 2 19 40 PM" src="https://user-images.githubusercontent.com/417182/56532095-0802f280-650a-11e9-853e-47596acd841e.png">

**Kirby Version**
`3.1.3-rc.1`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Safari 12.1 (14607.1.40.1.4)
 - Chrome 73.0.3683.103

**Comment by bastianallgeier** [comment]
✅
