### ISSUE TITLE
Subsites not accessible with Hiragana TLD .みんな

### ISSUE THREAD

**Issue by toschku** [getkirby/kirby#1713]
**Describe the bug**
Subsites in domains with Hiragana character TLD みんな not 

**To Reproduce**
1. Buy domain with .みんな TLD
2. Install newest starterkit
3. Try to access any subsite like /panel

**Expected behavior**
All subsites accessible.

**Kirby Version**
3.1.3? (The newest one on April 23. 2019)

**Console output**
Not possible.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version: newest on April 23. 2019

**Smartphone (please complete the following information):**
 - Device: iPhone7 plus
 - OS: iOS 12.2
 - Browser stock browser

**Comment by lukasbestle** [comment]
I made myself a `.みんな` test site locally based on Kirby 3.1.3 and was able to access and use the Panel just fine.

What is the exact error message you get? If there is a tracelog, please post that too.

**Comment by distantnative** [comment]
@MacBoeck I will close this for now. Please re-open if you still encounter the problem and provide the information as asked for by Lukas. Thanks.
