### ISSUE TITLE
Can't register Kirby and keep logout on production environment

### ISSUE THREAD

**Issue by jesuismaxime** [getkirby/kirby#1714]
I try to register a production installation through the top-admin-bar. Enter the correct key and email then clic Register. The form close, the green notice appear on top but no sign of the language selector (api/system response for register return `{"status":"ok"}`). Hit refresh and this is when the issue happens. Half time the 'Register / Buy a licence' buttons are back and the other half I got logout. When I login again, the 'Register / Buy a licence' buttons are also back.

The other part of the issue : even if a didnt try to register the installation, if I hit 'Refresh' I'm log out.

I double check, the prod and dev (which is ok) and the setup are the same (PHP version and extensions. The only difference is the htaccess force-SSL. But even if I remove this part bellow, the issues keep happening.

```
# Force SSL
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]

# Safe redirect to non-www (with SSL)
RewriteCond %{HTTPS} on
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ https://%1/$1 [R=301,L]
```

Is there a way to create a file manually like Kirby2 in the `/config` directory or something ?

EDIT: I look into my `/config` directory and the `.licence` file has been created, so its not about it.

**Kirby Version**
3.1.2

**Console output**
If you are working with the panel, please check the browser console for errors and send the output.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: test with Safari and Chrome
 - Version: lastest versions

**Comment by lukasbestle** [comment]
Please try clearing your browser cache and your session cookie and then try again.

**Comment by lukasbestle** [comment]
Oh, I see there's already a forum thread about this. Closing this here.
