### ISSUE TITLE
[Uri] No localization in multilang setup

### ISSUE THREAD

**Issue by mxdvl** [getkirby/kirby#1716]
**Lang parameter doesn’t change anything**
Compare the result of `$page->uri()` and `$page->url()`:

     $page->uri('en') = nouvelles
     $page->url('en') = https://example.com/en/nouvelles

     $page->uri('fr') = nouvelles
     $page->url('fr') = https://example.com/nouvelles   

**Expected behaviour**
URI should behave as URL [as per the docs](https://getkirby.com/docs/reference/objects/page/uri).

**Kirby Version**
3.1.1

**Additional context**
The site is powered using Laravel Valet and PHP 7.3.3.

**Comment by texnixe** [comment]
The `uri()` returns the translated ID, if you are not using translated language slugs, you won't see a difference. So it works as expected?

Assuming that my English page is called `news` and my German version  has `Slug: neuigkeiten`, `$page->uri('en')` returns `news` and `$page->uri('de')` `neuigkeiten`.

Or should the language code be part of the `uri` in the future?

**Comment by distantnative** [comment]
I'm closing this for now as it doesn't seem to be a bug as described by @texnixe.
Feel free to reopen it again if you disagree and have additional information. Thanks.

**Comment by mxdvl** [comment]
Understood. What I was trying to achieve was a canonical and alternate URL for my header. Using url would defeat as it would use the staging subdomain, suggesting duplicate content. Maybe I’m going at this wrong.
