### ISSUE TITLE
Mutliselect api doesn't support non-string fields

### ISSUE THREAD

**Issue by Jayshua** [getkirby/kirby#1720]
**Describe the bug**
Mutliselect using an API as the options type doesn't allow using an int field as the text or value.

**To Reproduce**
1. Create a multiselect field with an endpoint that returns an int for one of its properties.
2. Set that property as the title or value of the multiselect
3. Notice that the int field isn't loaded

**Expected behavior**
I expected to be able to use int fields (particularly an id field) as the multiselect's value.

**Kirby Version**
3.1.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 

I fixed this by chainging Cms/Nest.php:28 to

```
} elseif (is_string($value) === true || is_int($value) === true || is_bool($value) === true) {
```

I'd like to submit a pull request for it, but I'm not sure about the whole testing thing in the contributing guidelines. Would I add some more functions to test/Cms/NestObjectTest.php and NestCollectionTest.php?

**Comment by distantnative** [comment]
@Jayshua Thanks for spotting this - would you want to open the PR? If you are unsure about the tests, don't worry about it and only open the PR. We will add tests if necessary before merging then. Thanks!

**Comment by distantnative** [comment]
✅
