### ISSUE TITLE
[API/Panel]: Loading Panel Page with Query Syntax is Slow Because it Unnecessarily Evaluates Query

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1721]
**Describe the bug**
If you have a page blueprint that includes something like a `tags` or `checkboxes` field that is using a `query:`, when the Panel (via the API) loads that page, it actually try to evaluate the query, even though the result is never actually returned in that API call.

The effect of this is dramatic for things that have "slow" query calls. Because the initial API call merely provides the blueprint to the Panel, when that's slow to load, it's slow to dispatch the field sections (which will also take a long time to load).

The query should only be parsed when it's actually used.

<img width="1024" alt="Screen Shot 2019-04-25 at 10 32 52 PM" src="https://user-images.githubusercontent.com/417182/56785441-12431c00-67aa-11e9-9199-d44cc0a9de81.png">

**To Reproduce**

1. Have a blueprint with something like:
```yaml
title: Post

fields:
  related:
    type: tags
    options: query
    query: page.someSlowRelation()
```

2. The Model Class for this template should have a call that is consistently slow, or use:
```php
public function someSlowRelation() {
    sleep(1);
    return $this->siblings();
}
```

3. Create a page if necessary.
4. Open up your browser debugger and refresh the page to see how long the initial API call takes.
For example, loading something at `news/test-post-2` has an initial API call of
```
http://localhost/api/pages/news+test-post-2?view=panel
```

Even making a bare-bones API call to the non-panel variant is slow, even though its response doesn't have any relationship to the `tags` field.

```
http://localhost/api/pages/news+test-post-2
```

**Expected behavior**
This should be a relatively quick call.

**Screenshots**

**Kirby Version**
`3.1.3`

**Comment by neildaniels** [comment]
I dug into this a little more, and narrowed it down to these two Panel view fields that are penalized for the query. They are executed separately, so the `sleep(1)` is actually called twice, making the call Panel API call take at least 2 seconds.

https://github.com/getkirby/kirby/blob/c9dcfb5a79af7951a6be6dcecd202d9c8a01b28e/config/api/models/Page.php#L127-L128

The Default view only includes `content`, so it is only penalized by 1 second.

The `content` field from the API call resembles this:
```json
        "content": {
            "related": [
                {
                    "text": "Test Post 3",
                    "value": "news/test-post-3"
                }
            ],
            "title": "Test Post 2",
        },
```

The `text` part of the `related` entries is driven by the query, so I understand _why_ it's running for that. (It would be completely unnecessary if there were no saved values though.) However, those text/value pairs are _also_ provided in the following API call:
```
http://localhost/api/pages/news+test-post-2/sections/main-fields
```

```json
{
    "status": "ok",
    "code": 200,
    "name": "main-fields",
    "type": "fields",
    "errors": [],
    "fields": {
        "related": {
            "accept": "all",
            "autofocus": false,
            "default": [],
            "disabled": false,
            "errors": [],
            "icon": "tag",
            "invalid": false,
            "label": "Related",
            "name": "related",
            "options": [
                {
                    "text": "Test Post 1",
                    "value": "news/test-post-1"
                },
                {
                    "text": "Test Post 2",
                    "value": "news/test-post-2"
                },
                {
                    "text": "Test Post 3",
                    "value": "news/test-post-3"
                }
            ],
            "query": "page.someSlowRelation()",
            "required": false,
            "separator": ",",
            "signature": "abd1a5827aaeb2fa1ba57c2298dc8977",
            "strict": true,
            "translate": true,
            "type": "tags",
            "width": "1/1"
        }
    }
}
```

I suspect that the convenience of having the `text` portion in the initial API call isn't actually worth slowing down the entire Panel page.

I'm not sure what the `errors` API response field is actually doing, but commenting that line out sheds 1 second.

**Comment by distantnative** [comment]
This is tricky, basically your argument is for lazy-loading the options. Or maybe we can find a way to better cache them.

To explain those two calls:
1. `content` has the field value represented. Since the field saves the value only, we need to transform it again to a text-value object as the user should be presented with the text. For this of course we need all the options to match the values against.
2. The second call is to retrieve the options list to build the actual field - of course we need this information to build the DOM elements. 

I think your question is why not doing the matching of step 1 in the JS part of the Panel, instead of in the backend as now. The problem I see with this is that our API would then not return full value information for anyone else to use it (missing the text part).

**Comment by neildaniels** [comment]
Yeah, I think you captured my intent correctly. However, I'd like to highlight few specific notes:
- In the scenario where there are no saved values, the cost to calculate the options seems entirely unnecessary. There are literally no values to match against.
- Better caching should at reduce the extra time for whatever the `errors` field is doing in the first call.
- I agree this change inherently makes that API call less useful, but I think applying it only to the `?view=panel` variant should be acceptable. I don't expect the `panel` view to be intended for general use (or even be API-stable across releases).

**Comment by distantnative** [comment]
1. Agreed. Easy fix.
2. `errors` returns something if a validation failed.

Thinking more about it, the real issue is our architecture where we have API calls separately for the values and for the sections information (field definition) etc. It works great in most cases, but here we need to fetch the options twice – in unrelated calls, so caching doesn't work either.
