### ISSUE TITLE
Multiselect breaks on non-comma separators

### ISSUE THREAD

**Issue by Jayshua** [getkirby/kirby#1723]
**Describe the bug**
When using a separator other than ',' the multiselect still splits on the comma character.

**To Reproduce**
1. Create a multiselect field using a separator other than ','. For example, a vertical bar: '|'. Include an option that itself contains a comma.
2. Enter some values, notice how all appears to work fine.
3. Save the page
4. Notice how upon retrieving the saved data the multiselect splits along commas even though the separator is defined as a vertical bar.

**Expected behavior**
The multiselect should split along the defined separator.

**Screenshots**
Before saving:
![image](https://user-images.githubusercontent.com/1654103/56828773-a30c0d00-6827-11e9-99a3-f905695f5c72.png)

After saving:
![image](https://user-images.githubusercontent.com/1654103/56828796-aef7cf00-6827-11e9-9b48-1ae82a3b3172.png)

**Kirby Version**
3.1.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 66.0.3

**Additional context**
Pretty sure the problem is in tags.php, line 78. Str::split should specify the separator.

**Comment by distantnative** [comment]
✅ Thanks for spotting and providing the dead-on hint!
