### ISSUE TITLE
Can't access kirby() from the config file

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1724]
**Describe the bug**

If `kirby()` (or any object depending on it) is called from within `config.php`, Kirby runs into an endless loop as it seems to load the config file over and over.

**To Reproduce**

Use the following `config.php`:

```php
<?php

kirby();

return [
  // empty
];
```

**Expected behavior**

The `kirby()` object should already be accessible from the config.

**Kirby Version**

Kirby 3.1.3

**Additional context**

Forum thread: https://forum.getkirby.com/t/out-of-memory-with-config-variable/13946?u=lukasbestle

**Comment by bastianallgeier** [comment]
I have to disagree. The site object relies on the config to be loaded. That's why it cannot be available there.

**Comment by lukasbestle** [comment]
That's right, but I think we could solve it like this:

- When Kirby is initialized for the first time, already set the singleton and initialize the site object with the default options.
- Then load the config and overwrite the options in the site object with those returned from the config.

That way, the site object would already be available from the config, but with the default options (there's no other way anyway).

**Comment by lukasbestle** [comment]
Another argument for this from Slack (https://getkirby.slack.com/archives/C2UTAQAN4/p1556627527330800): Sometimes it can be useful to access `$kirby->roots()` from the config, e.g. to build a path to an SQLite DB. As the roots don't depend on the config values, that should be possible.

**Comment by bastianallgeier** [comment]
Yes, but we need another way to do this. I.e with additional callbacks. We can't make the Kirby instance available in the config.php

**Comment by lukasbestle** [comment]
Why not?

**Comment by distantnative** [comment]
Do we want this? Can we do this?
Or shall we close it in favor of: https://github.com/getkirby/kirby/issues/1538?

**Comment by bastianallgeier** [comment]
IMHO we should close this in favour of the lazy loaded extension types.

**Comment by lukasbestle** [comment]
This is a feature that gets requested a lot in the forum (accidentally because people try it intuitively and it doesn't work).

To be honest, I still don't really understand what's the issue with initializing the Kirby object earlier. Wouldn't my suggestion above work?

Also I don't know exactly what you mean with lazy-loaded extensions. @distantnative Could you please explain that a bit more?

**Comment by distantnative** [comment]
Lazy-oases might not be the perfect term, but it’s what Bastian and I have used when talking about it: basically turning more extensions into callbacks (optional), like the routes one. That callback can be called when the app is actually ready for the extension type and can pass the correct app instance then.

To your suggestion: I’m asking myself if it might be more confusing for developers that they get an instance but with different behavior then their usual
setup (since only with the defaults, not their config).

I think for most cases having hooks at all plugins loaded, at config loaded and at app completely loaded might be more suitable. What do you think?

**Comment by lukasbestle** [comment]
That makes sense! But what about the use-case of configuring a database path with `$kirby->roots()`? We'd need to support callbacks for config options as well.

**Comment by distantnative** [comment]
I think the most common case for the wish to have $kirby in config and/or plugins is about paths. So yeah, why not allow a callback for options as well that receives the root directory.

**Comment by distantnative** [comment]
Or more granular: allow a callback for the database option.

**Comment by lukasbestle** [comment]
Yeah, that would be useful. The callback would probably not even need a param as it's possible to use `kirby()->roots()` after the Kirby object has been initialized.

**Comment by distantnative** [comment]
Well, I don't think we can pass an initialized object to a callback that is meant to provide config options... isn't that the crux, that we need the options to initialize Kirby, so we can't use any fully initialized object to set up the options in the first place.

**Comment by lukasbestle** [comment]
Wouldn't the callback only need to be called when the database (in this case) is accessed? And that would happen after the Kirby object has been initialized, so it wouldn't be a problem.

**Comment by bastianallgeier** [comment]
@distantnative @lukasbestle here's an idea. The Kirby instance is ready as soon as the __constructor has reached the end. (before `Config::$data = $this->options`)

What we could do is to offer an additional `ready` callback in the config, which can be used to dynamically inject options, once everything else is ready. 

```php
// config.php
return [
    'debug' => true,
    'ready' => function ($kirby) {
        return [
            'db' => [
                'database' => $kirby->root('site') . '/db/database.sqlite',
                'type' => 'sqlite'
            ]
        ];
    }
];
```

Those additional options would then be merged `last-minute`
The config.php would still be responsible for the initial values that are needed before plugins are loaded for example. But the ready callback can be used with full access to the instance.

**Comment by distantnative** [comment]
Sounds good. Just wondering whether `ready` is the right term if it happens before plugins are loaded.

**Comment by bastianallgeier** [comment]
No, it happens after plugins are loaded. Pretty much at the second to last line in the constructor.

**Comment by bastianallgeier** [comment]
Here: https://github.com/getkirby/kirby/blob/9b033622f786fb3a35f9c1ed8ecaec1976334fda/src/Cms/App.php#L131

**Comment by distantnative** [comment]
👍

**Comment by bastianallgeier** [comment]
✅

**Comment by lukasbestle** [comment]
Awesome solution! 👍
