### ISSUE TITLE
Panel does not support locale arrays 

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1725]
**Describe the bug**
When creating languages from the settings view, it creates them with a locale array:
```php

return [
    'code' => 'it',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        6 => 'it_CH'
    ],
    'name' => 'Italian',
    'translations' => [    ],
    'url' => NULL
];
```

However the **language edit dialog** does not support showing arrays (it expects a string).

**To Reproduce**
1. Install plainkit `composer create-project getkirby/plainkit your-project` 
2. Enable languages in config.php
```php 
<?php
return [
    'languages' => true
];
```
3. Install panel and create some languages in the settings view
4. See the language edit dialog. 

**Expected behavior**
The dialog should either support showing the full array, or just show the LC_ALL value of it. 

**Screenshots**
![panel_settings](https://user-images.githubusercontent.com/6684137/56866285-bf4eac00-69d7-11e9-862b-b10fd662b202.png)

**Kirby Version**
3.1.3

**Comment by lukasbestle** [comment]
@distantnative I‘m afraid I can‘t really help with this.
See #1668.

**Comment by lukasbestle** [comment]
Added info: Making the field read-only won‘t work unfortunately as newly created languages will have an array by default. We probably need a structure field for this that will be converted to the key value array when saving.

**Comment by rasteiner** [comment]
Just for the "regression" part of the issue... 

I don't think the array is useful for the frontend, isn't it enough if the Language model transforms the array into its LC_ALL string? 

Like rewrite https://github.com/getkirby/kirby/blob/master/config/api/models/Language.php#L20 to 

```php
return $language->locale(LC_ALL);
```
?

But maybe I'm not getting something

**Comment by lukasbestle** [comment]
Ah, that could be an option! Basically only the “default” locale would be configurable in the Panel and all the others would only be configurable manually.

@bastianallgeier Would that be alright?

**Comment by bastianallgeier** [comment]
The dialog does now show an info field when the locale has a special setup. As long as we don't have a full-blown language editor with a configurator for all translations, it doesn't make sense in my opinion to handle all this in the dialog. It's better to keep on modifying such special set ups directly in the language file.

**Comment by lukasbestle** [comment]
@bastianallgeier Newly created languages are created with the array by default (with only `LC_ALL` set though), so your change will apply to all languages, even ones that have been created in the Panel. A better check would be "if object and more than one element". If object but just one element, that element should be displayed in the text field and then set to the object again when saving.

**Comment by bastianallgeier** [comment]
✅
