### ISSUE TITLE
Content representations don't work without default template

### ISSUE THREAD

**Issue by s3ththompson** [getkirby/kirby#1726]
**Description**

My templates are as follows:
- `default.php`
- `default.json.php`
- `about.json.php`

Navigating to `https://mysite.com/about.json` returns the template `default.json.php` unless I create a dummy `about.php`. Intuitively, `https://mysite.com/about.json` should match `about.json.php` regardless of whether other content representations for `about` exist.

**Kirby Version**
3.1.2

**Comment by bastianallgeier** [comment]
✅
