### ISSUE TITLE
Asset not copied to media folder

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1728]
**Describe the bug**
Using the Kirby\Cms\Asset class with images together with a custom file::version component the images are not copied to the media folder. 

**To Reproduce**
```php
'components' => [
    'file::version' => function (App $kirby, $file, array $options = []) {
        // no image
        if ($file->isResizable() === false) {
            return $file;
        }

        return new FileVersion([
            'modifications' => $options,
            'original'      => $file,
            'root'          => $file->root(),
            'url'           => $file->mediaUrl()
        ]);
    }
]
```

```php
(new Kirby\Cms\Asset('assets/images/logo.png'))->mediaUrl()
``` 
returns the intended media url. Calling that url in the browser ends in a 404 error. On disk no folders / files are generated in the media folder.

For images not using the Asset class the folders are created and images copied into the media folder. e.g.
```php
$field->value()->toFile()->mediaUrl()
```

**Expected behavior**
Asset images should be copied to the media folder magically

**Kirby Version**
3.1.3

**Additional context**
A temporary solution is:
```php
'components' => [
    'file::version' => function (App $kirby, $file, array $options = []) {
        // no image
        if ($file->isResizable() === false) {
            return $file;
        }

        if (get_class($file) === "Kirby\Cms\Asset") {
            F::copy($file->root(), $file->mediaRoot());
        }

        return new FileVersion([
            'modifications' => $options,
            'original'      => $file,
            'root'          => $file->root(),
            'url'           => $file->mediaUrl()
        ]);
    }
]
```

**Comment by distantnative** [comment]
If you overwrite the `file::version` logic and leave out the whole part about creating the `.jobs` files for the magic media file copying/creating, it seems to me that this isn't a bug but a problem with your custom component (see `config/components.php` lines 56-75 for which you miss any equivalents).

**Comment by mullema** [comment]
My `file::version` component works with "page images" but not with asset images. For "page images" more magic happens somewhere else so that they get copied to the media folder. 
```html
// does work
<?php if($image = $page->image()->toFile()): ?>
    <img src="<?=$image->url() ?>" />
<?endif?>

// does not work 
<img src="<?=(new Kirby\Cms\Asset('assets/images/logo.png'))->url() ?>" />
```

I would expect eighter both to work or both to fail.

**Comment by mullema** [comment]
Could it be the difference in the [config/routes.php](https://github.com/getkirby/kirby/blob/master/config/routes.php#L120)?

The `Media::thumb` method is called directly for Assets
```
[
   'pattern' => $media . '/assets/(:all)/(:any)/(:any)',
   'env'     => 'media',
   'action'  => function ($path, $hash, $filename) use ($kirby) {
      return Media::thumb($path, $hash, $filename);
   }
]
```

But for all other files/images `Media::link()` is called, which handles copying of original files and calls thumb if required.
```
[
   'pattern' => $media . '/pages/(:all)/(:any)/(:any)',
   'env'     => 'media',
   'action'  => function ($path, $hash, $filename) use ($kirby) {
      return Media::link($kirby->page($path), $hash, $filename);
   }
],
```

Why make a difference here?

**Comment by distantnative** [comment]
@bastianallgeier your brain needed here

**Comment by bastianallgeier** [comment]
Ugh, I need to dig a bit deeper to understand this myself. It looks like the Media::thumb method really is to blame here, but I first need to find out why I implemented it that way.

**Comment by distantnative** [comment]
Closing this for the newer #2467 with current discussion

**Comment by distantnative** [comment]
@mullema 
Having looked into this, indeed a `->mediaUrl()` on an unmodified asset object will return a path where no file is available.
One could copy over those files without modifications but that could also bear the risk of exposing files through the media folder that weren't meant to be exposed.

I think the other workaround would rather be to use `->url()` instead of `->mediaUrl()` for asset objects.
