### ISSUE TITLE
Custom panel css/js without timestamp

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1729]
**Describe the bug**
It is not possible to cachebust [custom panel css/js](https://getkirby.com/docs/reference/system/options/panel#custom-panel-css).

**To Reproduce**
```php
'panel' => [
    'css' => 'assets/css/custom-panel.css'
  ]
```
Go to yourdomain.com/panel and find in the source code:
```html
<link rel="stylesheet" href="https://yourdomain.com/assets/css/custom-panel.css">
```
All other css/js files are copied to a media/fingerprint folder. 

**Expected behavior**
Copy custom panel assets to the media/fingerprint folder.

**Kirby Version**
3.1.3

**Comment by bastianallgeier** [comment]
✅
