### ISSUE TITLE
SelectField is broken in MS Edge

### ISSUE THREAD

**Issue by bchan009** [getkirby/kirby#1730]
The template selector drop-down is broken in MS Edge.

In other browsers the dropdown menu works as expected.  However in Edge, the FIRST MENU OPTION will be used regardless of what the user has selected.

<img width="389" alt="dropdown" src="https://user-images.githubusercontent.com/35556639/57009181-182e6800-6bc3-11e9-92ae-47dfc60e35ff.png">

The above image should create a new page with the content file 'error.txt'.  The 'error' template has been chosen from the menu and is displayed as having been selected. 

If the Edge browser is used, Kirby will not create 'error.txt' but will instead create 'default.txt', because in this instance 'default' happens to be the first template in the list.  **I have removed/added various templates from the list and no matter what the user selects the first template in the list is always applied when using Edge.**

There is something weird with how Edge is interpreting the UI dropdown.  For whatever reason it is not really passing on the user's choice.

**Comment by bastianallgeier** [comment]
✅
