### ISSUE TITLE
Default text not correctly set in Html::a()

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1733]
**Describe the bug**
At [this section of the source](https://github.com/getkirby/kirby/blob/master/src/Toolkit/Html.php#L67), `$text` is set to `$href` if `$text` is empty. I think it should be:

```php
$text = $attr['href'] ?? '';
```

...because if you overwrite the `$href` with `$attr`, the old href will be shown as text.

**Comment by distantnative** [comment]
I guess if it should be

```
$text = $attr['href'];
```

cause the link will need a text, so a fallback to an empty string doesn't seem useful to me.

Then, I'm curious, in what cases do you want to overwrite `$href` in `$attr` - instead of simply setting the `$href` parameter?

**Comment by distantnative** [comment]
✅ Added `$text = $attr['href'];`

**Comment by yandodov** [comment]
It's also an option to make the method have two arguments - `$attr` and `$text`. If `$attr` is a string, assume it's the `href`. If it's an array, then it's an attributes list and `href` should be a part of it. It can be kind of weird to specify `href` separate from the rest of the attributes since it _is_ one. The other option is to specify them all in `$attrs`, and leave the first argument `null`, which is also kind of clumsy. This way, the method would also have a different API from `mailto` and `tel`. At first glance this can be unwanted, but I think it makes sense since they function differently. In `a`, you specify `href`, in `email` and `tel`, you specify an email or phone number, which are _used_ to form the `href`.

Anyway, those are details. Thank you for the fix!
