### ISSUE TITLE
Html::a() Invalid URL scheme: mailto

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1734]
**Describe the bug**
While I agree that `mailto` and `tel` are not valid URL schemes, they _are_ valid `href` values. If you try to output a link with such schemes via `Html::a()`, you get an error:

![image](https://user-images.githubusercontent.com/5570098/57086019-0b665d00-6d06-11e9-85b9-140065676f3b.png)

**Comment by texnixe** [comment]
There are separate methods for email and tel: `Html::email` and `Html::tel()`?

**Comment by yandodov** [comment]
Didn't know about those. I see, then. That's a bit confusing since `email` and `tel` _are_ `<a>` tags. When a method called "`a`" is invoked, it can be expected that it generates those tags as well. Perhaps a more fitting name for `Html::a()` would be `Html::url()` or `Html::link()`.

**Comment by bastianallgeier** [comment]
✅
