### ISSUE TITLE
[Panel] Date Field "Today" Button Doesn't Actually Set Date/Time To Now

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1736]
**Describe the bug**
When clicking on the "Today" button in a `date` field calendar, I fully expected the value in the field to be changed to today (or now, if using a time field as well).

Is this intentional? I can't really seem to think of a compelling use case for wanting this behavior.

**To Reproduce**
1. Open a date picker on a panel page
2. Select some date a couple months from now
3. Open up the calendar picker and click "Today"

**Expected behavior**
I would expect the calendar view and value to be set to today. Instead, it currently just changes the calendar view to focus on this month.

**Screenshots**
<img width="301" alt="Screen Shot 2019-05-02 at 12 47 43 PM" src="https://user-images.githubusercontent.com/417182/57102496-7e58df00-6cd8-11e9-8ad9-9266c51679d7.png">

**Kirby Version**
`3.1.3`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Chrome 74.0.3729.131
 - Safari 12.1 (14607.1.40.1.4)

**Comment by distantnative** [comment]
I think this is a similar discussion as the month arrows: does navigating (in this case today navigates you back to the current month/day) in the calendar dropdown directly updates the field value. Or do you need to click explicitly no the day for that... While with the arrows I was convinced that the current implementation is correct, with this one I am much more torn.

**Comment by distantnative** [comment]
Pushing this to 3.3.0 as I feel this will give us bit more breathing room to think about the date field in general.

**Comment by moritzebeling** [comment]
I would think: When clicking on `Today`, the user is not moving the timeframe to select from, but instead is already deciding for one single day. Consequently the field should react in the same way, just as one would have clicked on one of the other days (field gets filled, calendar disappears).

If the other reaction feels more natural, the button should be called `Show current month`.

**Comment by distantnative** [comment]
> When clicking on Today, the user is not moving the timeframe to select from, but instead is already deciding for one single day.

We have heard very different perspectives on this. It isn't as clear cut as you put it. Some do as you describe, some do as it is implemented right now.

However, I actually like the suggestion to just rename it to "Current month" which avoids communicating differing expectations.

**Comment by bastianallgeier** [comment]
✅
