### ISSUE TITLE
[Panel] File Upload Allows Periods . in Filename But Rename Modal Does Not

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1738]
**Describe the bug**
When uploading a file to a Page in the panel, if the filename has periods `.` it will not be automatically renamed. However, if you make any change using the Rename modal, the periods `.` will be stripped out.

This is very annoying because if you don't know this, it's impossible to restore the original filename without re-uploading the file.

The rename panel should allow for periods to exist. I've never ran into issues with a file upload having periods in it using Kirby.

If there is a technical reason why this shouldn't be allowed, then the file should be renamed immediately on upload.

**To Reproduce**
1. Go to a page in the Panel that allows for file uploads
2. Upload a file with periods in the name, such as `screen-shot-2019-05-02-at-11.38.01-am.png`
3. Open the Rename panel
4. Type a character at the end

**Expected behavior**
The original part of the filename should be untouched.

**Screenshots**
<img width="578" alt="Screen Shot 2019-05-02 at 3 07 44 PM" src="https://user-images.githubusercontent.com/417182/57110063-19a77f80-6cec-11e9-8add-8d7b37b7f98d.png">
<img width="559" alt="Screen Shot 2019-05-02 at 3 07 59 PM" src="https://user-images.githubusercontent.com/417182/57110066-1b714300-6cec-11e9-9426-1e60a940b35c.png">

**Kirby Version**
`3.1.3`

**Desktop (please complete the following information):**
 - OS: macOS 12.1 (14607.1.40.1.4)
 - Safari 12.1 (14607.1.40.1.4)
 - Chrome 74.0.3729.131

**Comment by distantnative** [comment]
There have been quite a few issues in v2 with dots in filenames if I remember correctly. So since we want Kirby to run in many different environments, I think it makes sense to remove them. But you are right that this should then happen on upload as well.

**Comment by neildaniels** [comment]
My most compelling reason to retain the periods would be for filenames such as
- `words.txt.zip`
- `some-archive.tar.gz`

I don't think anyone would expect the periods to be stripped and linking/referring to them seems very awkward:
- `wordstxt.zip`
- `some-archivetar.gz`

(The actual unarchiving of the files should be unaffected by the rename though.)

**Comment by distantnative** [comment]
I'll move it to 3.2.0 actually, since this would have implications for https://github.com/getkirby/kirby/pull/1697

**Comment by bastianallgeier** [comment]
✅
