### ISSUE TITLE
[Panel] TextareaField toolbar glitches on narrow browser window

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1739]
**Describe the bug**
<img width="1050" alt="Screenshot 2019-05-03 at 10 15 30" src="https://user-images.githubusercontent.com/3788865/57118274-7bb7c180-6d8c-11e9-8717-52cf7a20f98c.png">

**Kirby Version**
3.1.3

**Browser**
Chrome and Safari on Mac OS

**Comment by bastianallgeier** [comment]
✅
