### ISSUE TITLE
Re-direct to a child page from parent using link.txt

### ISSUE THREAD

**Issue by Hofstede** [getkirby/kirby#174]
Hey all.

In the last version of Kirby you could route a menu item to load any specific child by renaming the text file in the parent link.txt and using 

eg. Link: parent/my-child 

in the file. It doesn’t work anymore. Is there a new way to do this easily?

Ta.

**Comment by bastianallgeier** [comment]
That was actually never built in. You always needed a template for it. But the template is super straight forward: 

```php
<?php 

go($page->link());

?>
```

**Comment by Hofstede** [comment]
*facepalm*
