### ISSUE TITLE
Ditch widgets and fields folder

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#174]
Since the extension registry came out, it's used by a majority of the developers to have fields and widgets as plugins. Nowdays almost everything is a plugin, even if it's a widget or a field.

The old `fields` and `widgets` folders are almost not used at all nowdays, at least not what I've seen. When they are used it often generates a question in the forum, because they are not sure if it's a plugin or a field. It can create confusion that a field can both be a field in the fields folder or a plugin in the plugins folder.

To make the process totally streamlined, my suggestion is to let everything be a plugin.

Fields and widgets from Panel 2 will not work in Panel 3 anyway, so that way it's a breaking change no matter what.

**Comment by bastianallgeier** [comment]
That’s one of things on my list to clean up the parts in v2 that got too confusing and diverse. We will not reintroduce those folders in v3 anymore. Everything will just be a plugin. Same for models btw
