### ISSUE TITLE
view components aren't globally registered 

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1742]
**Describe the bug**
Panel view components aren't globally registered.
This makes it harder to add / inject functionality into them from plugins. 

**Expected behavior**
Views could be registered [here](https://github.com/getkirby/kirby/blob/master/panel/src/config/components.js) and then loaded into the router via `Vue.component('k-viewname-view')`

**Kirby Version**
3.1.3

**Additional context**
A slack thread here: https://getkirby.slack.com/archives/C2UTAQAN4/p1556870559362300

**Comment by lukaskleinschmidt** [comment]
On the same note. It would also be awesome if any currently registered subcomponents would be registered globally. I had this problem in the [App.vue](https://github.com/getkirby/kirby/blob/master/panel/src/App.vue#L43) for example with the `k-search` component.
