### ISSUE TITLE
FilterBy with Boolean not working 

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/kirby#1747]
**Describe the bug**
Using FilterBy with a field that sets true / false (like the toggle field) in file metadata does not work like it should do.

Does not work unless you wrap the true in single quotes. Double do not work.

```
query: site.children.listed.images.filterBy("splash", 'true')
```

If the true is not wrapped in qoutes, it ignores the filterby part of the query, and lists all images. I wonder if there is a way to warn that there was an error with the filter, rather then just silently ignoring it.

**To Reproduce**
1. Set a toggle field in a file meta 
2. Add a bunch of images to the page
3. Toggle some of them to true
4. Use a files field on another page to pull them in with the query language by filtering on the true status of the toggle

**Expected behavior**

Should work like this, as described in the docs:

```
query: site.children.listed.images.filterBy("splash", true)
```
**Kirby Version**
3.1.3

**Additional context**
Forum thread - https://forum.getkirby.com/t/query-language-query/14055

**Comment by neildaniels** [comment]
I don't think this is even specific to the query language. I'm pretty sure I've noticed inconsistencies when doing this directly in PHP (with something like filterBy or findBy, can't remember).

**Comment by HashandSalt** [comment]
Yes, your right..... as per the forum thread, the equivalent php in a template does not work either, you have to do this...

```
$site->children()->listed()->images()->filterby("featured", 'true')
```

**Comment by bastianallgeier** [comment]
✅
