### ISSUE TITLE
[Panel] Number field removes decimal values when they are 0.

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1748]
**Describe the bug**
When a number field is set to decimal values using the step option:

```
fields:
  price:
    label: Price
    type: number
    step: .01
```
and you select a number where the decimals are zero, e.g. 15,00, the zeros are removed when saving or reloading, also the number is stored without the decimals.

**To Reproduce**
1. Add above field in any blueprint
2. Visit page in panel and add number,  e.g 15,00
3. Save and reload
4. See zeros vanishing. They are also not stored.

**Expected behavior**
Zeros should be stored in the content file and not disappear.

**Kirby Version**
3.1.3

https://forum.getkirby.com/t/decimal-number-fields-dont-allow-00-anymore/14066

**Comment by distantnative** [comment]
I have tried several attempts. With the native HTML number field this is not possible as it seems.
I agree that in the Panel it owuld be nicer if it always has the same amount of decimals as in the step.

It should not matter how it is stored in the content file though. If the frontend needs it displayed with a certain number of decimals, then this should be ensured by frontend code. 

I am closing this for now as I don't think we can achieve this - @bastianallgeier .

**Comment by bastianallgeier** [comment]
I think I just found a solution! Check out the PR!

**Comment by distantnative** [comment]
@bastianallgeier just proved me wrong XD ✅

**Comment by RastaTux** [comment]
@bastianallgeier @distantnative This still doesn't work for the backend - See this example: https://youtu.be/GgKWI1qDvPY
This did somehow work in kirby 2.x
