### ISSUE TITLE
File deletion is broken in panel

### ISSUE THREAD

**Issue by bchan009** [getkirby/kirby#1749]
Fresh install of Kirby Starterkit on Cloudways cloud hosting.

1) Upload starterkit
2) Create user
3) Try to delete an image (I tried to delete peter-fox.jpg) using the panel
4) Get kicked out of panel with 'unauthenticated' error.

All Kirby 3 installs (starterkit and custom sites) crash me out of the panel when trying to delete a file.  

- Files can be uploaded and renamed with no issues. 
- Pages can be created/edited/removed with no problems.  
- Deleting a page deletes the files belonging to the page with no problems.  

The issue only occurs when trying to delete or replace a specific file when using the panel. Issue occurs in multiple browsers.

Kirby 2 sites run perfectly on the same servers.  Kirby 3 incompatibility?

**Comment by bastianallgeier** [comment]
What kind of error do you get when you delete a file? Is there anything in your browser console?

**Comment by bchan009** [comment]
I get a popup that says 'unauthenticated' and am booted to the panel login almost immediately.  I had to screen capture the error and go frame by frame just to see what the window said.

Browser console says `GET https://(file url) 403` `app.js: 1`

<img width="415" alt="Annotation 2019-05-06 125704" src="https://user-images.githubusercontent.com/35556639/57241243-8bd6d780-6ffe-11e9-81d8-57c0bf575795.png">

Fresh application set up on Cloudways server.  Fresh Kirby install of starter kit.

**Comment by bastianallgeier** [comment]
Which kind of server do you use? Apache with the default htaccess?

**Comment by bchan009** [comment]
Default .htaccess file.

Cloudways uses a stack that I believe has both Apache and Nginx.

https://support.cloudways.com/which-base-packages-are-deployed-with-cloudways-server/?utm_source=Platformkb&utm_medium=kbsearch

**Comment by bchan009** [comment]
Default .htaccess file.

Cloudways uses a stack that I believe has both Apache and Nginx.

https://support.cloudways.com/which-base-packages-are-deployed-with-cloudways-server/?utm_source=Platformkb&utm_medium=kbsearch

**Comment by bchan009** [comment]
> Which kind of server do you use? Apache with the default htaccess?

Default .htaccess file.

Cloudways uses a stack that I believe has both Apache and Nginx.

https://support.cloudways.com/which-base-packages-are-deployed-with-cloudways-server/?utm_source=Platformkb&utm_medium=kbsearch

**Comment by bchan009** [comment]
> Which kind of server do you use? Apache with the default htaccess?

Default .htaccess file.  On some sites I have added these lines to the .htaccess file:

`RewriteCond %{ENV:HTTPS} !on`
`RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`

But it doesn't seem to make a difference whether they are there or not.

Cloudways uses a stack that I believe has both Apache and Nginx.

https://support.cloudways.com/which-base-packages-are-deployed-with-cloudways-server/?utm_source=Platformkb&utm_medium=kbsearch

<img width="841" alt="Annotation 2019-05-08 122856" src="https://user-images.githubusercontent.com/35556639/57391618-e43bdf80-718c-11e9-8885-5d3be13acd16.png">

**Comment by bastianallgeier** [comment]
Oh, it could mean that they use some caching that breaks those requests. I already have an idea how to solve that.

**Comment by bastianallgeier** [comment]
I just committed a fix, which will be in the rc next Tuesday. It would be great if you could test it afterwards and see if it's fixed. Feel free to reopen if not.

**Comment by lukasbestle** [comment]
Not fixed in 3.1.4-rc1, see #1775.

**Comment by bastianallgeier** [comment]
I have absolutely no idea what's happening here :( @bchan009 would there be a chance to make some tests on the server? It's extremely hard to debug this remotely: support@getkirby.com

**Comment by bastianallgeier** [comment]
I'm closing this. Seems to be a server setup issue.
