### ISSUE TITLE
headings get not parsed

### ISSUE THREAD

**Issue by jtByt-Pictures** [getkirby/kirby#175]
The new version of parsedown has fixed the link issue of #165, but now all headings are broken.
All Headings marked up by one or multiple hashes get parsed as paragraph only with the hashes as normal text. This is not how it should work.

    ##heading

leads to

    <p>##heading</p>

I´ve seen that this error even exists at the parsedown website´s demo.

**Comment by bastianallgeier** [comment]
Yikes :( I already submitted a issue for this: https://github.com/erusev/parsedown/issues/265

**Comment by jtByt-Pictures** [comment]
This also breaks your beautiful comlumn plugin, which now repeats the last paragraph of the last column another time after the columns, but inside the container (row) div.

I think I must step back some commits by now.

**Comment by bastianallgeier** [comment]
oh man! That sucks big time! I don't additionally test new versions of Parsedown as I suppose they already do. Maybe I need to write my own tests for it now :( Probably need to revert as well.

**Comment by bastianallgeier** [comment]
It's already fixed!! :) I guess I need to check out the columns plugin though and see what's going wrong there.

**Comment by bastianallgeier** [comment]
The discussion around this is pretty interesting btw: https://github.com/erusev/parsedown/issues/265
