### ISSUE TITLE
Use only one syntax for routes?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#175]
To me routes is one of the most confusing parts of Kirby. It's simple to use routes, but hard to know what syntax to use.

https://forum.getkirby.com/t/which-router-syntax-should-i-use/4494

```php
c::set('routes')
kirby()->routes()
$kirby->set('route')
$router->register()
```

In the forum there are some good replies on which route syntax to use where, but in a perfect world I wish that there was only one syntax.

If you are doing a cleanup of things, maybe you are looking into this as well?

**Comment by bastianallgeier** [comment]
We will have exactly two:

1. In the config, to be able to set site/project specific routes

2. in Plugins with $kirby->set() for plugin specific routes.
