### ISSUE TITLE
HTTP Basic auth - Error Typo

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#1750]
**Describe the bug**
Enable, basic HTTP Basic auth in config.php, outputs wrong path in error message.
 
**To Reproduce**
1. Setup HTTP Basic auth in config, as described in the docs #3
2. Add custom route to test access
3. Open route in chrome without correct auth
4. System shows error path in file:

<img width="588" alt="Bildschirmfoto 2019-05-05 um 11 07 15" src="https://user-images.githubusercontent.com/5121132/57191478-84dc9600-6f26-11e9-8f4b-1df64bf1393e.png">

<img width="326" alt="Bildschirmfoto 2019-05-05 um 11 13 08" src="https://user-images.githubusercontent.com/5121132/57191498-c79e6e00-6f26-11e9-9a6c-a1a3880c4170.png">

**Kirby Version**
3.1.1

**Console output**
file: "irby/config/api/authentication.php", missing "K"

**Comment by lukasbestle** [comment]
We changed some things regarding Exception handling recently, so please first upgrade to 3.1.3.

Unfortunately I can't reproduce this on my machine. Please send me the value of your `$_SERVER['DOCUMENT_ROOT']` variable for further testing.

PS: Please post code snippets with the Markdown code syntax in the future – this makes it a lot easier for us to reproduce issues as we can copy-paste your code.

**Comment by findthebug** [comment]
I think i found the problem with the path's...  (3.1.3, php7.3):

**vagrant/scotchbox local:**
```
($_SERVER['DOCUMENT_ROOT'])
/var/www/mapbackend.test/app
-> file: "irby/src/Http/Router.php",
-> 1 folder to vhost
```
 
**online testsever:**
```
($_SERVER['DOCUMENT_ROOT'])
/home/httpd/vhosts/example.ch/be/mapbackend/app"
-> file: "y/src/Http/Router.php",
-> 4 folder to vhost
```

if you have kirby installed directly on the vhost-dict without folders, the path is correct. per path to vhost, one char is removed.

The problem seems to be here:
```
Kirby/src/Api/Api.php line (538)
'file' => ltrim($e->getFile(), $_SERVER['DOCUMENT_ROOT'] ?? null),
```

getFile and DOCUMENT_ROOT returns correct values, but after ltrim is performed, php is cutting the path.

the app itself seems to work as expected, but maybe this can be a problem in other situations if similar code is used in core-stuff.

**Comment by lukasbestle** [comment]
I cannot reproduce this. The line you linked to only affects Exceptions that are not Kirby internal ones (which the `PermissionException` is). I have improved that code path anyway now since I agree that the code was not optimal.

The Exception implementation was refactored for 3.2.0 (which is currently on the `features` branch). Could you please check if that version fixes it for you?

**Comment by findthebug** [comment]
confirm it's fixed with the changes, thanks! tested local and also on our testserver.

**Comment by lukasbestle** [comment]
Great, thanks for confirming. :)
