### ISSUE TITLE
Files Field with translate:false opens dialog

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1752]
**Describe the bug**
In a multilanguage setup, a files field with `translation: false` in the blueprint does open the select dialog when clicking on the "empty field" placeholder in a secondary language.

**To Reproduce**
1. Multilanguage setup
2. add a Field with blueprint:
```
fields:
   images:
      type: files
      translate: false
```
3. go to a secondary language
4. click on the "no files selected yet" placeholder

**Expected behavior**
No dialog should open.

**Screenshots**
![translate](https://user-images.githubusercontent.com/46723734/57239776-2bab5a00-702d-11e9-8d6e-c3a8452612ec.gif)

**Kirby Version**
3.1.3

**Comment by distantnative** [comment]
✅
