### ISSUE TITLE
Str::split() Incorrectly Trims Strings with Multiple-Character Separator

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1753]
**Describe the bug**
If you use `Str::split()` with a separator string that has multiple characters (e.g. `---`), it will incorrectly trim the first and last elements.

**To Reproduce**
```php
$str = <<<EOT
-abc-
---
-def-
EOT;

print_r(Str::split($str, '---'));
```

Outputs:
```
Array
(
    [0] => abc-
    [1] => -def
)
```

**Expected behavior**
```
Array
(
    [0] => -abc-
    [1] => -def-
)
```

**Kirby Version**
`3.1.3`

**Additional context**
The `Str::split()` function uses the php `trim()` function like so:
https://github.com/getkirby/kirby/blob/c9dcfb5a79af7951a6be6dcecd202d9c8a01b28e/src/Toolkit/Str.php#L802-L803

However, [`trim()`](https://www.php.net/manual/en/function.trim.php) uses the separator parameter as a pool of characters, not as a fixed string. This behavior differs from [`explode()`](https://www.php.net/manual/en/function.explode.php)'s behavior, which works on fixed strings.

In cases where `$separator` is a single character, the current behavior should always be fine. 

In multi-character cases though, it should probably check if the input has a prefix/suffix of the separator and remove it based on string lengths?

**Comment by distantnative** [comment]
The `trim` line could be replaced with a `preg_replace`:

```php
$string = preg_replace('/^' . $separator . '\s?|\s?'. $separator . '$/', '', (string)$string); 
```

**Comment by lukasbestle** [comment]
Do we even need to trim the string at all? There's an empty value detection right below the `explode()` call anyway. I'd say the RegEx uses more processor time than the foreach loop.

**Comment by distantnative** [comment]
You are right, I didn't check the code that follows. Removing the trim line should have no effect at all (or only the one that the issue is solved but no other side effects).

**Comment by distantnative** [comment]
✅
