### ISSUE TITLE
[Panel] Bug when changing slugs in non default languages

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1755]
**Describe the bug**
When I change the slug in a non default language in a multilang installation the **open** link will not update to the new location. The default language works just fine. After a page refresh on the non default language the open link points to the correct location.

**To Reproduce**
1. Create a multilang site (e.g. `en` and `de`)
2. Update the slug in the not default language (`de`)
3. Click on the open link

**Expected behavior**
The **open** link should point to the correct location.

**Kirby Version**
3.1.3

**Desktop**
 - Windows 10
 - Firefox 67

**Comment by distantnative** [comment]
✅

**Comment by distantnative** [comment]
I think now I found a fix for all setups ✅
