### ISSUE TITLE
Return value of Kirby\Cms\StructureObject::isLast() must be of the type boolean, object returned

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1756]
**To Reproduce**
1. Loop a structure and call `isLast()` on an item inside the loop:

    ```php
    foreach ($page->myfield()->toStructure() as $item) {
      echo $item->isLast();
    }
    ```

    ![image](https://user-images.githubusercontent.com/5570098/57372039-253bf000-719d-11e9-97ca-bf66474a93ce.png)

**Expected behavior**
Shouldn't throw an error.

**Kirby Version**
3.1.3

**Comment by distantnative** [comment]
✅
