### ISSUE TITLE
[Panel] Page sections fall back to index if page is not found or draft

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1757]
**Describe the bug**
When defining a pages section **without a template option** and setting the parent to a non-existing or draft page, the parent is ignored and the complete index displayed instead.

Example section:

```
sections:
  type: pages
  headline: Notes
  parent: site.find("notes")
  info: "{{ page.date.toDate('d.m.Y') }}"
  empty: No notes yet
```

**To Reproduce**
1. Put the above example section into a blueprint, e.g. `site.yml`
2. The section should show up with a list of notes children
3. Change the status of the notes page to draft
4. See how the section now displays all pages

**Expected behavior**
If the parent page does not exist, the panel should probably show an empty section or some sort of message that the parent doesn't exist or is in draft state.

While it would be possible to prevent the above by using

```
 parent: site.childrenAndDrafts.find("notes")
```

for cases where the parent is in draft state, I wonder if showing the complete index for non-existing pages is the desirable behavior.

**Comment by bastianallgeier** [comment]
A section with an invalid parent now throws a proper error.
