### ISSUE TITLE
excerpt() with complete words

### ISSUE THREAD

**Issue by servicethinker** [getkirby/kirby#176]
I think it would be very cool to give some more options to excerpt() like generating an excerpt with complete words. For example if you call `page()->text()->excerpt(80, array('words' => true))` you would get an excerpt with minimum 80 words and + about 3-5 chars to get a complete word in the end (*sry, hard to describe in english words*).

What do you think?

**Comment by bastianallgeier** [comment]
This is a fantastic idea, so I had to implement it :) It's now available in the develop branch and will be in the next stable release.

**Comment by lukasbestle** [comment]
I think what he meant is a mode in which you still pass a maximum count of *characters*, but the last word is not getting cut in the middle of the word.

**Comment by bastianallgeier** [comment]
Ok, that would be another valid option. Since I now introduced a new "mode" parameter it could be easily a next mode. But I think I leave it like this for now. I find it quite helpful to extract a certain number of words from a text, or what do you think?

**Comment by lukasbestle** [comment]
Yep, the new `words` mode is definitely a helpful mode as well. I think that you should reopen the issue though.
