### ISSUE TITLE
Rendering breaks at the end of a paragraph with opening tag, but no closing tag

### ISSUE THREAD

**Issue by fitzage** [getkirby/kirby#177]
I have a blog article that I was given in HTML format and didn't feel like converting everything.

All paragraphs have an opening tag, but not a closing tag. While this bugs the heck out of me, it's apparently valid code. At least some people think it is. List item tags are the same way.

Previously, it rendered fine. You can even see the unclosed paragraph tags when viewing source. (see here https://www.joyent.com/blog/predicteria-2015)

That same article in 2.0.6 renders the first paragraph and nothing else. Once it hits that second opening paragraph tag without the first one being closed, it stops rendering. (see this screenshot of the same article on localhost http://d.pr/i/1dkSl)

If I remove all the opening paragraph tags and replace them with line breaks, the unclosed list item tags later in the article still render fine as list items.

**Comment by bastianallgeier** [comment]
Well I think this is pretty much an edge case. As far as I know the parsedown guys try to be more strict about standards (CommonMark and HTML) and so it's probably causing this problem because of the updated parsedown version. To be fair, I'm not sure if it would make sense to ask them to still accept unclosed tags in their parser. Instead it might be more straight forward to either add a html flag to the article text file and simply don't call kirbytext() in the template in such a case, or close the tags, or run something like tidy. What do you think?

**Comment by fitzage** [comment]
Well, I did some research and unclosed paragraph tags is valid in HTML5, so it would seem to me that the best thing would be for parsedown to fix it, because it should recognize valid HTML.

"A p element’s end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, dir, div, dl, fieldset, footer, form, h1, h2, h3, h4, h5, h6, header, hr, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is not an a element."

http://www.w3.org/TR/html-markup/p.html

Personally, I'm open to any solution, but since it's actually valid HTML I think it's fair that parsedown should parse it. Indeed, it feels like a bug since list items are still parsed without having to be closed.

**Comment by bastianallgeier** [comment]
@fitzage oh, I actually didn't know that. Would you mind posting an issue on the parsedown extra repo? http://github.com/erusev/parsedown-extra/issues/ I get on there nerves so regularly that it is good when you write them with more details about this case :)

**Comment by fitzage** [comment]
Will do.

**Comment by bastianallgeier** [comment]
Awesome! Thank you for your help, Matt!

**Comment by bastianallgeier** [comment]
I think it's safe to say that they are not going to fix it. But fortunately the latest version on the develop branch finally has the option to set your own markdown parser in the options and use the old Markdown Extra class instead. Let me know if you want to use that and need help with the setup.
