### ISSUE TITLE
[Panel] Changes are deleted on ID change

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1770]
**Describe the bug**

If the ID (URL) of a model is changed, the local changes in LocalStorage are cleared.

**To Reproduce**

1. Make changes to a model (here: page)
2. Don't save
3. Change the ID of the model
4. The changes are gone.

**Expected behavior**

The changes should be automatically transferred to the new ID.

**Kirby Version**

`features` branch @ d7cd044

**Additional context**

We should also check if the lock for the model is transferred correctly as well.

**Comment by distantnative** [comment]
Wondering if it wouldn't be safer/cleaner to require no unsaved changes for changing the slug - @bastianallgeier, @lukasbestle?

**Comment by lukasbestle** [comment]
Would be fine too, at least for the initial implementation. We could add a change migration feature later if requested.

**Comment by bastianallgeier** [comment]
✅
