### ISSUE TITLE
Files are returned in alphabetical order, not "sort"

### ISSUE THREAD

**Issue by chpio** [getkirby/kirby#1772]
**Describe the bug**
* calling for example `$page->image()` will return the first file in alphabetical order, not in "sort" order.
* Panel is also showing the first image in alphabetical order for a page.

somewhat related to #1498 and #1584

**To Reproduce**
1. upload two imgs to a page
2. sort them manually by drag and drop in panel
3. look at the output order in panel (the "cover" image shown on the parent page) or api
4. change order in panel
5. the output order hasn't changed

**Expected behavior**
Files should be ordered by "sort".

**Kirby Version**
v3.1.3

**Comment by bastianallgeier** [comment]
This is a difficult topic. `$page->image()` always takes the first image in alphabetical order. It doesn't care about sorted images at all. That's the same with $page->images() or $page->files() etc. Those collections are also not sorted by the sort field by default. You have to implement this manually in your templates. When we change this behaviour it will have massive effects on all Kirby sites. What's your opinion on this @distantnative, @lukasbestle ?

**Comment by texnixe** [comment]
If I may, I give my 2ct as well: Since this is also a performance issue, I think the current implementation should be the default.

**Comment by distantnative** [comment]
I agree with @texnixe - and we you said changing this would break so many Kirby sites that rely on the current way. Plus the aim of this issue can be easily solved with using something like `$page-> images()->sortBy(‘sort’)->first()`

**Comment by bastianallgeier** [comment]
Yep, performance is the main reason why this is the default.

**Comment by bastianallgeier** [comment]
But we could introduce something like `$page->images()->sorted()->first()` to simplify this a bit more.

**Comment by texnixe** [comment]
Hm, yet another method? It's not really much shorter than `$page-> images()->sortBy(‘sort’)->first()`

**Comment by chpio** [comment]
my main issue with this is actually the sorting in the backend.

**Comment by bastianallgeier** [comment]
@chpio that's a problem we have in a few places, where the templates need to reflect what is configured in the panel. If we would want to fix this, the architecture of Kirby would need to be very different and it would no longer be possible to use the system without the panel at all. I know that it's sometimes leading to confusion :/

**Comment by distantnative** [comment]
I’m with @texnixe, let’s not add another method that does the same as existing ones with being only barely shorter.

**Comment by bastianallgeier** [comment]
It wasn't just about being shorter. I think sortBy('sort') looks super weird to be honest. My hope was to, introduce a more human-readable method that creates a closer link to what happens in the panel. But of course we should not just throw new methods around like crazy.

**Comment by texnixe** [comment]
It might look weird because of the naming, but it also creates a mental link to the fact that you  are in fact sorting by a field in the content file.

**Comment by bastianallgeier** [comment]
@texnixe that's true. I give up :)

**Comment by lukasbestle** [comment]
I agree that the default behavior should stay as it is. Maybe we should document this more clearly in all places where collections of files are explained.

**Comment by distantnative** [comment]
Closing this for the above mentioned reasons.
