### ISSUE TITLE
[Panel] Inconsistent handling of special character in slug input

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1776]
**Describe the bug**
When entering some invalid characters into the slug field, these characters are not removed until the user clicks "OK". There is no visual clue, that the entered characters are invalid or that the slug has been sanitized while saving. Note, that the Left Double Quotation Mark `“` (U+201C) gets filtered out before saving, but many other quotation marks, like Double Low-9 Quotation Mark `„` (U+201E) are only filtered out after saving.

**To Reproduce**
1. Change the slug of a page and try to enter invalid characters into the text input.

**Expected behavior**
The slug field should either filter out invalid characters while typing, so the user cannot attempt to save an invalid value at all or display an error message, instead of silently sanitizing the field’s value.

**Screenshots**
![Bildschirmfoto 2019-05-14 um 18 01 53](https://user-images.githubusercontent.com/395617/57713734-515ee180-7673-11e9-903a-2aed4ae2a0ba.png)

**Kirby Version**
3.1.3

**Desktop (please complete the following information):**
 - OS: macOS 14.4.4
 - Browser: Firefox 66.0.5

**Comment by lukasbestle** [comment]
Have you tested this with the new implementation for 3.2.0 (see https://github.com/getkirby/kirby/pull/1697)? It should be a lot more robust regarding stuff like this.

**Comment by fabianmichael** [comment]
@lukasbestle Sorry, not yet. But also won’ be able to do that before next week. If you got 3.2.0 at hand, maybe you can just paste `Hello-„World“` as title when creating a new page and if that works fine, there’s nothing further to do.

**Comment by distantnative** [comment]
@fabianmichael Like this?
<img width="710" alt="Screenshot 2019-05-17 at 13 25 38" src="https://user-images.githubusercontent.com/3788865/57925086-4b514680-78a7-11e9-9c75-0b9183661f99.png">

**Comment by bastianallgeier** [comment]
LGTM! Feel free to reopen if it's as expected.
