### ISSUE TITLE
Inconsistent Tab focus styling in Panel.

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1779]
Tabbing around through the Panel works very well, which makes editing content super fast (great job!). However I noticed two inconsistencies in the appearance that bother a little.

1. On the table overview of structured fields the focus styling for actions are missing so there is no visual indication which action is currently focused. The thumbnails of file fields use default focus styling but the remove buttons doesn't have any at all.

![Bildschirmfoto 2019-05-15 um 11 36 24](https://user-images.githubusercontent.com/18071758/57765684-38ebd700-7706-11e9-84a0-5016fcf0bb5f.png)

2. The appearance of focused button is different depending on whether the button belongs to files/pages section or to a files/pages field.

Files Section:
![Bildschirmfoto 2019-05-15 um 11 29 00](https://user-images.githubusercontent.com/18071758/57765153-32a92b00-7705-11e9-9a35-7c633b834fe4.png)

Files Field:
![Bildschirmfoto 2019-05-15 um 11 29 08](https://user-images.githubusercontent.com/18071758/57765201-42287400-7705-11e9-9c5e-8fe2762e52bb.png)

**Kirby Version**
3.1.3

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome, safari

**Comment by yoanmalie** [comment]
Hello, 
can you please provide a blueprint for this ? I will give a look.
Thank

**Comment by distantnative** [comment]
@bastianallgeier That isn't yet fixed by https://github.com/getkirby/kirby/commit/b3b06bbd608c3a23c1d4ba5ff887ae35e4763621 correct?

**Comment by bastianallgeier** [comment]
The focus outline is fixed, but there are still padding issues.

**Comment by bastianallgeier** [comment]
We are really sorry that we didn't manage to solve this issue for such a long time. This will be an ongoing issue that we will tackle over time, when we work on components. But not with a high priority. I'm closing this issue here, but feel free to create a new one if you find other focus style issues that are affecting the accessibility of the Panel.
