### ISSUE TITLE
File select in textareas

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1780]
**Describe the bug**
I'm still investigating this issue but wanted to post it right away because it affects the current release candidate: selecting files from within a textarea is broken in different ways:

1. First of all, it's not possible to filter shown images a described in the docs, see https://getkirby.com/docs/reference/panel/fields/textarea#file-upload-and-select: the selector will always present the user with a list of all files independend of the applied filter, e. g. `files: page.images.template("image")` won't work.
2. When the file selector loads, it displays small thumbs. All good so far, but the "small" thumbs are actually all images in their original size, 1200 by 2000 pixels and so on instead of 100 by 100 pixels.
3. Something is wrong with the context in structure fields as well, see https://forum.getkirby.com/t/parent-images-for-textareas-files/14065.

**To Reproduce**
```yaml
fields:
  text:
    label: Text
    type: textarea
    size: large
    files: page.images.template("image")
    uploads: image
```

**Expected behavior**
- the file list should be configurable using the query syntax
- thumbs should be real thumbs
- textareas in structure fields should work as usual

**Kirby Version**
I'm currently testing 3.1.4-rc1 but haven't checked the current stable release.

**Comment by nilshoerrmann** [comment]
I checked this morning and all issues are also present in the current stable release 3.1.3.

**Comment by nilshoerrmann** [comment]
This is partly related: https://github.com/getkirby/kirby/issues/1520#issuecomment-495512848

**Comment by bastianallgeier** [comment]
All issues are gone since 3.2.0
