### ISSUE TITLE
JPEG 2000 Images Don't Have Dimensions

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1782]
**Describe the bug**
If you upload a "JPEG 2000" file, Kirby doesn't report dimensions for it in the Panel.

**To Reproduce**
1. Upload a `.jp2` file.
2. View it in the panel

**Screenshots**
<img width="795" alt="Screen Shot 2019-05-16 at 4 18 30 PM" src="https://user-images.githubusercontent.com/417182/57893037-41233f80-77f6-11e9-8ac9-0d0db9f7e68e.png">

**Kirby Version**
`3.1.3` and `3.1.4-rc.1`

**Comment by bastianallgeier** [comment]
✅
