### ISSUE TITLE
Can't set preview option for site blueprint

### ISSUE THREAD

**Issue by pju-** [getkirby/kirby#1784]
**Describe the bug**
When I try to set a custom preview link in my site.yml, nothing happens.
It works for all other blueprints  though.

**To Reproduce**
1. Set the preview option in your site.yml: 
```yml
options:
  preview: https://preview.mysite.com
```
2. Go to /panel/site
3. Check the url of the preview button 
4. It's the root of the installation instead of a custom link

**Expected behavior**
The link should be customizable as on any other page.

**Kirby Version**
3.1.3

**Comment by bastianallgeier** [comment]
✅
