### ISSUE TITLE
Panel: Sections don't load async in page routes

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1787]
**Describe the bug**
One difference between fields and sections is according to the [docs](https://getkirby.com/docs/reference/plugins/extensions/sections#vue-component__section-data) that sections are loaded asynchronously. This works for sections in a site / user / file route but not for pages.

A section with long loading time blocks the panel rendering for pages.

**To Reproduce**
1. Create a custom section with a long loading time

```php
// index.php
Kirby::plugin('mullema/test', [
    'sections' => [
        'test' => [
            'computed' => [
                'something' => function(){
                    sleep(2);
                    return "something";
                }
            ]
        ]
    ]
]);
```
```javascript
// index.js
panel.plugin('mullema/test', {
    sections: {
        test: {
            data: function () {
                return {
                    something: null
                }
            },
            created: function () {
                this.load().then(response => {
                    this.something = response.something;
                });
            },
            template: `
                <div>{{ something }}</div>
             `
        }
    }
});
```

2. add this section to a page blueprint
```yaml
title: Some Page
sections:
  testbed:
    type: test
```

3. open this page in the panel
4. See that panel rendering is blocked 2s
5. before the section is loaded

**Expected behavior**
The page should load without blocking and then call the section asynchronously.

**Kirby Version**
3.1.3

**Additional context**
`api/pages/somepage?view=panel` blocks the panel

also when I want to change the status of that test page I run in to the blocking here:
`api/pages/somepage?select=id,status,num,errors,siblings,blueprint`

The panel asks for data from sections in different requests. This also means that the props / computed properties methods run twice. If they are cpu or time intensive it can become a performance problem.
Looking at fields which are not expected to be async, the same seems to happen. A fields computed property is requested 3 times on panel pages and 2 times on other routes.

**Comment by bastianallgeier** [comment]
This is caused by the errors check. To evaluate errors, all sections need to be validated, including all their props. It was a stupid mistake that the errors check is done when the page is loaded. This is not needed at all and I just removed that. But we cannot do anything about this when the status is being changed. The panel needs to find out if the status can be switched from draft to listed or unlisted.
