### ISSUE TITLE
kirbytext() doubling content

### ISSUE THREAD

**Issue by alkaest2002** [getkirby/kirby#179]
after having updated to kirby 2.0.6, the following code:

    <?php echo $page->text()->kirbytext() ?>

with text() retrieving the following content field:

    <p>Se vuoi fare i test <b><span class="color">risky</span></b> e partecipare così alla raccolta dei dati scrivi a (email:info@risky-b.com)</p>

spits out this (it basically doubles the content):

![schermata 2015-01-18 alle 11 29 51](https://cloud.githubusercontent.com/assets/1260048/5792074/597361ce-9f05-11e4-9437-b5a210297d21.png)

**Comment by servicethinker** [comment]
Are you sure that you don't have it twice in your code?

**Comment by lukasbestle** [comment]
No, that's actually a bug that appeared several times already. See getkirby/plugins#10.

**Comment by alkaest2002** [comment]
@servicethinker: yep, I double-checked the code and can confirm that it is not written twice

**Comment by alkaest2002** [comment]
I found a possible solution: in my content I had some <br> elements. I transformed them in <br/> and the problem was gone. Not sure why.

**Comment by puckey** [comment]
Encountering this problem too..

**Comment by puckey** [comment]
When I turned on Markdown Extra in the config it stopped happening:

c::set('markdown.extra', true);

**Comment by bastianallgeier** [comment]
Could you check the latest version from the develop branch? The latest parsedown version included there should fix this.

**Comment by puckey** [comment]
That fixed it for me. Thanks!

**Comment by peterbinks** [comment]
@bastianallgeier so is this going into the next release of kirby? I'm having this doubling effect as well.

**Comment by bastianallgeier** [comment]
@peterbinks yes, it's already in the nightly build.
