### ISSUE TITLE
Collection: Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1790]
We found this error multiple times in our server logs:

    PHP Fatal error: Nesting level too deep - recursive dependency? in /www/kirby/src/Toolkit/Collection.php on line 922

The mentioned line is sorting the collection, see https://github.com/getkirby/kirby/blob/develop/src/Toolkit/Collection.php#L922. I cannot provide any deeper info why and when this happened but Sonja noted this on the forum:

> I think a similar error has come up several times in different contexts and I’m pretty sure I’ve seen it recently but can’t find it at the moment.

> This was the issue I was thinking of: [Change status/Delete page: Error = Nesting level too deep - recursive dependency?](https://forum.getkirby.com/t/change-status-delete-page-error-nesting-level-too-deep-recursive-dependency/14083)
>
> But that happened in the Panel and it seems to appear in different contexts, I’ve actually seen this error message myself recently, so it seems to have different causes.

See https://forum.getkirby.com/t/collection-nesting-level-too-deep-recursive-dependency/14270/2.

This is happening on Kirby 3.1.4 RC1 but might have occured before, too.

**Comment by adis-me** [comment]
I have the same issue. I have installed the latest Kirby version 3.1.4.

I only get the error when I want to publish my new content called `Recipe`. So basically my blueprints work fine when not published, but soon as I publish it, I see the error. Interested in a sample project to reproduce?

**Comment by distantnative** [comment]
@adis-me Yes, a sample project would help a lot.

**Comment by adis-me** [comment]
@distantnative Sorry, but I really assume I am misconfiguring the blueprints, but attached a sample project. You can log in with demo@example.com as username and pwd.

[nesting-level-too-deep.zip](https://github.com/getkirby/kirby/files/3211524/nesting-level-too-deep.zip)

In this project I have this error when I publish the `Recipes` page to status `Unlisted`.

**Comment by texnixe** [comment]
@adis-me Both your `sections/pages.yml` and your `sections/recipes.yml` are missing the `parent`option.

**Comment by adis-me** [comment]
> @adis-me Both your `sections/pages.yml` and your `sections/recipes.yml` are missing the `parent`option.

Is this a mandatory option? Will it fix my error? Hmm, questions questions.. Why my blog setup works and this not. It is based on the Blog configuration as provided on the [website](https://getkirby.com/docs/reference/panel/samples/blog#blog__predefined-section-for-reusage).

**Comment by texnixe** [comment]
I have to correct myself. The problem is not the missing parent option but setting the `sortBy` option to `date` for all children (which would then be children of site), you have the problem that the sorting is messed up.

**Comment by adis-me** [comment]
> I have to correct myself. The problem is not the missing parent option but setting the `sortBy` option to `date` for all children (which would then be children of site), you have the problem that the sorting is messed up.

Strange that the `sortBy` is causing this error. All my pages - including child pages - have a valid date. Either way, I can confirm that removing `sortBy` is for me fixing this error message. Thanks for your help @texnixe

**Comment by texnixe** [comment]
Not in the example you provided. You are using this section in `site.yml`, so pages are the children of `site`: home, blog, recipes and error. None of these pages has a date field to sort by.

**Comment by distantnative** [comment]
Is this solved? Was it a blueprint error?

**Comment by nilshoerrmann** [comment]
No, we still don‘t know why this happened on our site.

**Comment by distantnative** [comment]
@nilshoerrmann Without any reproducible setup this will be hard to debug. Could you provide this?

**Comment by nilshoerrmann** [comment]
No, sadly I can‘t. Would it ne possible to enhance the error message for now? Without knowing which collection causes this, it‘s hatd to find the source of the issue.

**Comment by lukasbestle** [comment]
That's unfortunately not possible as it's an internal PHP error.

**Comment by nilshoerrmann** [comment]
In this case let‘s close this issue and reopen it as soon as we have more context.

**Comment by texnixe** [comment]
Just came across this issue again in the forum, where sorting by date with identical dates caused the issue: https://forum.getkirby.com/t/sorting-pages-via-query-in-blueprint-throws-error-nesting-level-too-deep-recursive-dependency/14507/7

**Comment by nilshoerrmann** [comment]
I can confirm that this also happens on a site where we sort by date and have duplicate dates.

**Comment by afbora** [comment]
I reproduced on 3.2.3-RC.1 with following blueprint:

```
customSection:
    type: pages
    sortBy: anyField asc
```

> Nesting level too deep - recursive dependency?

But `title` field works

`sortBy: title asc`

I realized that issued with same values as @nilshoerrmann said

**Comment by bastianallgeier** [comment]
I'm really sorry, but I cannot reproduce this at all :( Nor with duplicate dates neither with the undefined field.

**Comment by distantnative** [comment]
Me neither. E.g. adding the following to the `notes` blueprint in the Starterkit:

```
customSection:
        type: pages
        sortBy: author asc
```

Works flawless for me.

If it still causes troubles for you, could you please provide a step-by-step guid to reproduce this with the Starterkit? Thanks.

**Comment by afbora** [comment]
Here reproduce blueprint with Kirby 3.2.3 Starterkit:

**/site/blueprints/sections/notes.yml**

```
type: pages
headline: Notes
info: "{{ page.date.toDate('d.m.Y') }}"
empty: No notes yet
sortBy: date desc
```

I don't know why, but issue with `parent` and `template` properties. When you remove that properties, you will get the error.

**Comment by distantnative** [comment]
```yaml
title: Notes
icon: 📖

columns:
  - width: 1/2
    sections:
      customsection:
        type: pages
        headline: Custom section
        info: "{{ page.date.toDate('d.m.Y') }}"
        empty: No notes yet
        sortBy: date desc
```

works for me on current `master` branch (so 3.2.3):

<img width="1180" alt="Screen Shot 2019-08-09 at 16 45 42" src="https://user-images.githubusercontent.com/3788865/62787521-2bf04100-bac5-11e9-84d7-9889fae6c58c.png">

**Comment by bastianallgeier** [comment]
Could that be a problem with different PHP versions, OS or anything else? Let's compare PHP versions, operating systems and servers.

PHP 7.2.10
macOS: Mojave
server: Apache
MAMP

**Comment by distantnative** [comment]
PHP 7.2.13
macOS Catalina beta
server Apache
Valet+

**Comment by afbora** [comment]
Apache 2.4.37 x86
PHP 7.2.15 x86
Windows 10 x64
EasyPHP

I'll test in live centos server

**Comment by bastianallgeier** [comment]
Might it be a Windows thing? @nilshoerrmann what are you using?

**Comment by afbora** [comment]
Failed on live server too

Apache 2.4
PHP Version 7.3.8
CentOS 6.10

**Comment by bastianallgeier** [comment]
And it's really just the starterkit? No modifications other than the blueprint? That's soooo weird!

**Comment by texnixe** [comment]
No problem:

PHP 7.2.13
macOS Mojave
server Apache
Valet

**Comment by afbora** [comment]
> And it's really just the starterkit? No modifications other than the blueprint? That's soooo weird!

Yes, just starterkit without modifications. I'll track this down.

**Comment by afbora** [comment]
In fact, the cause of the error appears in the console:

```
code: 1
details: null
exception: "Whoops\Exception\ErrorException"
file: "\EasyPHP\eds-www\test\kirby\1790\kirby\src\Toolkit\Collection.php"
line: 948
message: "Nesting level too deep - recursive dependency?"
status: "error"
```
https://github.com/getkirby/kirby/blob/master/src/Toolkit/Collection.php#L948

Issue with `array_multisort()` function and when i remove this line, error gone.

Btw, i have tested without `spread operator` like `array_multisort($params)`, error gone too but sort wrong.

**Comment by nilshoerrmann** [comment]
Did you all make sure to have two pages published on the same day before testing? And I‘m not sure if the pages that are referenced in the section needed to have `num:date` in their blueprint.

I‘m using MAMP on MacOS Mojave. Can post the version numbers next week.

**Comment by texnixe** [comment]
Even with same dates (and times) I don't get the error.

**Comment by nilshoerrmann** [comment]
I‘ll check on my machine next week.

**Comment by afbora** [comment]
Other reproduce blueprints for starterkit `site.yml`

```
customSection:
    type: pages
    sortBy: status asc
```

```
customSection:
    type: pages
    templates: 
        - about
        - home
        - default
        - photography
        - notes
    sortBy: status asc

```
```
customSection:
    type: pages
    templates: 
        - about
        - notes
        - photography
    sortBy: status asc
```

**Comment by afbora** [comment]
Live example while changing page status: "notes `unlisted` to `listed`"

```
type: pages
templates: 
    - about
    - notes
    - photography
sortBy: status asc
```

![section](https://user-images.githubusercontent.com/3393422/62797139-9a43fc00-bae3-11e9-82a7-3e01a45d65e0.gif)

**Comment by neildaniels** [comment]
I've come across this error (or something very similar) previously. And, to be honest, it was an issue in Kirby 2 as well.

I've never seen it in the panel, but I have seen it when I had custom Page Models/custom `StructureObject`s that were being sorted (via `->sortBy()`).

I haven't seen it in a while, but he were informal observations I made when I ran into these issues:
- When Pages/StructureObjects were being sorted by a key that wasn't very unique (i.e., if you were sorting by something like `name asc`, if multiple items had the exact same name it would often throw this error). Sorting by something "guaranteed" to be unique like `uid`/`uri` would make the error go away.
- If I was sorting things that had instance properties (see below) to cache data, those could potentially be issues. My code _did not_ do anything on `clone()` to account for that, so that might have been an issue. Removing the instance property and having the value be computed each time would normally make the issue go away.

```php
<?php

class ExamplePage extends Page {
    protected $cachedData = [];

    public function foo() {
        return $cachedData['foo'] = $cachedData['foo'] ?? $this->something();
    }
}
```

**Comment by bastianallgeier** [comment]
✅ We finally have a solution. Thanks to @afbora and @lukasbestle for taking care of it! 👏

**Comment by nilshoerrmann** [comment]
Which branch do we have to check out to test the solution?

**Comment by distantnative** [comment]
@nilshoerrmann it's on the `develop` branch - keep in mind that you need to build the assets on that branch yourself (though for this specific bug not necessarily since only PHP code changed).

**Comment by nilshoerrmann** [comment]
Thanks for the reminder regarding the assets – I often forget about that.
