### ISSUE TITLE
Plugin options not availabe in api routes

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1791]
**Describe the bug**
If I try to add a custom api endpoint in a plugin I can't access the defined default options.

**To Reproduce**
1. Add following plugin
```php
<?php

Kirby::plugin('your/plugin', [
    'options' => [
        'endpoint' => 'endpoint',
    ],
    'api' => [
        'routes' => function ($kirby) {
            $endpoint = $kirby->option('your.plugin.endpoint');
            
            dump($endpoint); // expected 'endpoint'
            die();
            
            return [
                [
                    'pattern' => $endpoint . '/action',
                    'method'  => 'ALL',
                    'auth'    => true,
                    'action'  => function () {
                        //
                    }
                ]
            ];
        },
    ],
]);
```
2. Open any route

**Kirby Version**
3.1.3

**Additional context**
The problem seems to be the order extensions are loaded in. Have a look [here](https://github.com/getkirby/kirby/blob/master/src/Cms/AppPlugins.php#L32). Moving the [options](https://github.com/getkirby/kirby/blob/master/src/Cms/AppPlugins.php#L44) before the `api` will fix this issue. But not sure if there are any other implications I'm not aware of by doing so except than screwing up the alphabetical order 😉.

**Comment by bastianallgeier** [comment]
✅
