### ISSUE TITLE
[Panel] Clear changes in localStorage on explicit logout

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1792]
If the user logs out of the Panel explicitly using the logout button, the Panel should clear the localStorage to provide a clear slate if other users log in and also to ensure that no private data is leaked.

The localStorage should *not* get cleared on session expiry to avoid data loss.

**Related issues:**

This could be combined with the unsaved changes indicator in https://github.com/getkirby/kirby/pull/1789 so that users get warned about their unsaved changes before logging out.

**Comment by DanielRivers** [comment]
Question, not clearing on session expiry potential security issue?  Any data remaining in storage when not logged in surely isn't ideal?

**Comment by lukasbestle** [comment]
We have discussed this in the team and came to the conclusion that data loss is far more risky. If any confidential data needs to be protected, it is possible to lock out explicitly (which is also the only way to ensure an immediate effect).

After all, localStorage can only be cleared on the next visit after the expiry, so it would be possible to circumvent the deletion by disabling JS first and then grabbing a snapshot of localStorage.

**Comment by bastianallgeier** [comment]
✅
