### ISSUE TITLE
[Panel] Page Image Previews in Panel Can't Use Asset Objects

### ISSUE THREAD

**Issue by luxlogica** [getkirby/kirby#1793]
**Describe the bug**
The `image:` settings of Page sections don't seem to be able to accept `Asset` objects - they only accept `File` objects. 

**Use-Case**
We are using a Page Model to specify a 'main' image for a page. The model tries to find an existing image in the page folder, but if it can't, it should return a 'default' image from the `assets` folder. 

The panel should be able display the page's 'main' image as its preview.

**To Reproduce**
1. Create a page section to display our special page -  note the image query:

```
site_areas:
  type: pages 
  headline: Default Pages 
  status: all
  layout: cards
  size: small
  image:
    query: page.main_img
```

2. Create the page model for the page, defining 'main_img':

```
<?php
class MyPage extends Page {

    public function main_img() {
        if ($this->images()->findBy('template','preview_image')) {
            return $this->images()->findBy('template','preview_image');
        } elseif ($this->images()->count() > 0) {
            return $this->image();
        } else {
            return new Asset("assets/default.jpg");
        }
    }

}
```

3. Add a page
4. See that in the panel, no preview image is displayed - the panel will display a page icon instead.

**Kirby Version**
3.1.3

**Comment by bastianallgeier** [comment]
✅
