### ISSUE TITLE
Translate description strings for the default roles

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#1796]
**Describe the bug**
In the panel, with the language set to German, there are two tiny issues: one in the 'Registrieren' modal and one in the users 'Rolle' modal.

**To Reproduce**
1. Go to 'Panel'
2. Click on 'Registrieren' (no license has to be entered yet)
3. Read 'Den Lizenzcode findest du in der Bestätigungsmai zu deinem Kauf.'
4. At the end of 'Bestätigungsmai' the L is missing.
5. Go to 'Benutzer'
6. Click on 'Rolle'
7. Read 'The admin has all rights'.
8. The text is in English

**Expected behavior**
First: It should read 'Bestätigungsmail'.
Second: It should be translated to something like 'Der Administrator hat alle Berechtigungen'.

**Screenshots**

![Bildschirmfoto 2019-05-22 um 20 48 29](https://user-images.githubusercontent.com/50926857/58202038-e34f9580-7cd6-11e9-88c2-8b25e3198dcc.png)

![Bildschirmfoto 2019-05-22 um 20 48 10](https://user-images.githubusercontent.com/50926857/58202056-ecd8fd80-7cd6-11e9-9b2b-5535e865a1d8.png)

**Kirby Version**
3.1.4

**Comment by lukasbestle** [comment]
Thanks for letting us know.

I have fixed the first typo in the registration dialog.

The role description is currently not translated, you can however create your [own user blueprints](https://getkirby.com/docs/reference/panel/blueprints/user) with a custom description.
@distantnative Do you think we should translate the default descriptions?

**Comment by distantnative** [comment]
I think we should: https://github.com/getkirby/kirby/blob/56b208ef955f0a6e156fe6d6becef2da911c6d24/src/Cms/Role.php#L55

**Comment by Pandorrrrrra** [comment]
I just came across two other English descriptions in the German panel, this time in error messages. So maybe it's a more general question then if all descriptions should be translated? I think for editors it would be more consistent – but maybe it's also more a "cosmetic" thing : )

![Bildschirmfoto 2019-05-23 um 21 30 38](https://user-images.githubusercontent.com/50926857/58283117-d5b61080-7da7-11e9-8826-a649473c1333.png)

![Bildschirmfoto 2019-05-23 um 21 53 35](https://user-images.githubusercontent.com/50926857/58283131-db135b00-7da7-11e9-945e-def7abf0d02f.png)

**Comment by lukasbestle** [comment]
They should, yes. Most of them are translated, but for some errors it's difficult to do for technical reasons. This is something we want to improve over time though.

**Comment by bastianallgeier** [comment]
@Pandorrrrrra could you please create a new ticket for the file upload messages?

**Comment by bastianallgeier** [comment]
✅

**Comment by Pandorrrrrra** [comment]
@bastianallgeier I just created a new ticket.
