### ISSUE TITLE
Duplicate appendix in German

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1799]
Using the `features` branch, when duplicating a page and using the German panel translation, I get the following appendix for my copy's name:

> Seitentitel-kopieren

My guess is that in English it would be `page-title-copy` which should translate to `Seitentitel-Kopie` in German in this case. So copy the verb and copy the noun are conflicting in the language string selection – not sure how this works internally but this needs to be differentiated.

**Comment by bastianallgeier** [comment]
✅
