### ISSUE TITLE
Panel: User website not needed by default?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#18]
For the user view, I saw no blueprints for it. Is the website field always there?

I don't think it needs to be there by default. The rest of the things are important and needed I think, but not a website field. Maybe the admin can add it with a blueprint or something instead?

**Comment by bastianallgeier** [comment]
The custom fields for users will definitely come back and I agree that the website field might not be something we need by default.

**Comment by distantnative** [comment]
Will be part of the next release.
