### ISSUE TITLE
Improve usability for first time usage - registration process is misinterpretable

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1802]
My first Kirby 3 installation was a short time fail because I did a major mistake: When I followed the admin registration process, I interpreted "name" as the username and typed in some random email address because it was a local set up for testing. Of course, afterwards I wasn't able to log in because there was no way to sign in via name but only via email address. It should be made more clearer that the email address is used for the sign in and that you have to remember it/store it somewhere safely. Otherwise you have to delete the admin account as like as I had to do.

**Comment by bastianallgeier** [comment]
Good point! Thanks for the insight!

**Comment by distantnative** [comment]
Moving this to 3.3.0 as an enhancement to keep 3.2.4 focused on bug fixes.

**Comment by bastianallgeier** [comment]
✅
