### ISSUE TITLE
Symlink to kirby-folder throws error

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1805]
**Describe the bug**
I placed the kirby folder and index.php out of the document root and created symlinks to them in the document root.
If a load the page every seconad or third load produces the kirby error "This page is currently offline due to an unexpected error". On some loads it works, on some not.
Can't find anything on the PHP error log.

**To Reproduce**
1. Place kirby folder and index.php out of document root, create symlinks to them
2. Load the page a few times
3. See error

**Kirby Version**
3.1.4

**Comment by bastianallgeier** [comment]
This is not how you should solve this. You can configure the location of your Kirby folder and any other folder in the index.php: https://getkirby.com/docs/guide/configuration#custom-folder-setup

**Comment by bavarianbytes** [comment]
Tried it like this:
``` 
require __DIR__ . '/kirby/bootstrap.php';

$kirby = new Kirby([
	'roots' => [
		'kirby'		=> '../master/kirby',
	]
]);

echo $kirby->render();
```
But that doesn't work. Cause of the require statement before the configuration of the roots?

If symlinks would work by the way, it would be easy handle kirby installations with shell scripts and co. Like centralizing code for multiple instances, copying instances, adapting symlinks via shell scripts etc.

**Comment by lukasbestle** [comment]
Is `__DIR__ . '/kirby'` a symlink to the `../master/kirby` folder? If so, have you tried this:

```php
$kirbyRoot = realpath(__DIR__ . '/kirby');

require $kirbyRoot . '/bootstrap.php';

$kirby = new Kirby([
	'roots' => [
		'kirby' => $kirbyRoot,
	]
]);

echo $kirby->render();
```

**Comment by bavarianbytes** [comment]
Hey Lukas,
thx, that works! Great!

But you have to set some other roots too, otherwise kirby doesn't find the content (content root) or the panel refers you to the installer (index root).

My code which works:
```
<?php

$kirbyRoot = realpath(__DIR__ . '/kirby');

require $kirbyRoot . '/bootstrap.php';

$kirby = new Kirby([
	'roots' => [
		'index'		=> __DIR__,
		'content'	=> __DIR__ . '/content',
		'kirby'		=> $kirbyRoot,
	]
]);

echo $kirby->render();
```

**Comment by lukasbestle** [comment]
Since all other roots are based on the `index` root by default, the following should work as well:

```php
<?php

$kirbyRoot = realpath(__DIR__ . '/kirby');

require $kirbyRoot . '/bootstrap.php';

$kirby = new Kirby([
	'roots' => [
		'index' => __DIR__,
		'kirby' => $kirbyRoot
	]
]);

echo $kirby->render();
```

**Comment by bavarianbytes** [comment]
Tried it, of cause you are right! Thanks.
