### ISSUE TITLE
Sizes attribute missing for images on cards

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1807]
**Describe the bug**
Following the discussion in #1520, the panel now provides a `srcset` of images to allow for crisp image display across viewports. This is great! Nevertheless, I noticed that my browser was still loading the largest possible image source even if images were displayed on cards in a small column.

The missing piece for fixing this is [adding a `sizes` attribute to the `img` element](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Resolution_switching_Different_sizes). I've not worked with the `sizes` attribute myself so I hope someone can double check the following: 

Below a viewport width of 1040 pixels, the panel layout is linear and images have a maximum width of 793 pixels. This can be covered easily by adding `sizes="(max-width: 1039px) 793px"` to the image element. For viewports equal to or wider than 1040 pixels things get complicated because images need different settings depending of the column context they are in (the maximum width possible in that column matters). This would have to be calculated for each column separately: `sizes="(max-width: 1039px) 793px, (min-width: 1040px) {$maximum-width-in-current-column}"`.

**Expected behavior**
The browser should only load the image that best fits the actual display dimensions. Smaller viewports might require larger images than wider viewports due to the switch between linear and grid layouts.

**Kirby Version**
This affects the current `features` branch only and is an issue across devices and browsers.

**Additional context**
This does only affect images in card layouts. List images work as they should because resolution conditions have already been added (`1x`, `2x` etc.).

**Comment by nilshoerrmann** [comment]
Maybe `sizes="(max-width: 1039px) 100vw"` is a better definition for the linear layout as this makes sure the browser download smaller images on small viewports.

**Comment by luxlogica** [comment]
We have to deal with each image in a layout on a case-by-case basis, as there is no 'one-size-fits-all' solution. In general, you will find that your images will fit into one of 3 use-cases:

## CASE 1: Image Takes Up Full Viewport Width
This is often the case when you're using images as section backgrounds, or on full-screen slideshows. In this case, you **do not need a `sizes` attribute**. That is because by default all browsers assume that the image is going to take up _the entire viewport_. So, just use your `srcset`, and the browser will automatically pick the best image to fit based solely on the image width.

## CASE 2: Image Not Full-Viewport, But Always a Set Size
This is the case when the image is a **set percentage** of the viewport width, or a set size in pixels - and doesn't need to change that measurement in different devices. You may find images like this  inside media cards, or on a layout where the image is always `33vw`, or `50%`, or `300px`. The key here is that the image in these cases does not change its measurement in different devices - ie., it does not use media queries.

In these cases, you use `sizes` with a single measurement, to let the browser know that this image is *not* expected to be shown in full-screen width, but at a different, set size - eg;, `sizes="33vw"`.

## CASE 3: Image Is Presented at Different Sizes in Different Devices
Last of all, there will be cases when an image will be presented at different sizes, depending on the viewport size itself. Maybe, when the viewport is large - e.g., 960px or larger - we use a 2-colum layout, and our image needs to be `50vw`. But when the viewport is smaller, our 2 columns are going to stack, and the image will need to take up the entire viewport width. In this case, we need to specify the different measurements of our image, in the `sizes` attribute, just like we would specify them in media queries. In this example, it would look like this: `sizes="(min-width: 960px) 50vw, 100vw"`. Note that the _last_ measurement in our sizes list is the _'default'_ that is used when nothing else applies.

----

In your specific example above, you mention that in larger screen sizes, your layout splits into columns. This is a very common situation, which you should indeed be able to cover with `sizes`. Your layout is adding/removing columns at certain breakpoints. At these breakpoints, your images have to change size. So, your `sizes` attribute has to match the same breakpoints you are using in your layout.

Here is an example: let's say that I have a layout that progressively splits itself into columns as the viewport gets wider. In this case, let's say that on smaller devices (below 770px wide) we are going to use one single column. On these devices, our image should be 85vw (leaving space for margins). On medium sized devices (below 1200px) we are going to use 2 columns, and we've worked out that the largest the image will need to be is about 500px. Last of all, for very large devices over 1200px wide, we'll use 4 columns. In these devices, we've worked out that our images only need to be about 300px wide. In this situation, our `sizes` attribute would look like this:

`sizes="(min-width: 1200px) 300px, (min-width: 770px) 500px, 85vw"`

**Comment by bnomei** [comment]
i know its not a barebones solution or [a guide](https://ericportis.com/posts/2014/srcset-sizes/) but in most cases i just throw [the lazysizes js lib](https://github.com/aFarkas/lazysizes) at the problem.

if you use `data-sizes="auto"` and make sure the css is loaded and applied (read no css and js in async) before the lib does its job everything will be fine. but there are lots of tips at the github readme worth checking out.

**Comment by distantnative** [comment]
Just before this discussion heads into that direction: for the Panel, we wouldn't want to include any js library.

**Comment by nilshoerrmann** [comment]
@luxlogica, thanks for your write-up!

As this is really about the layout present in the panel, we don't have any cases from category 1 as the panel doesn't feature full screen images. 

We have images in the category 2: those are the images Kirby used to display sections in list mode. This is already correctly handled using conditions for the resolution like so: `srcset="image-38x382.jpg 1x, image-76x76.jpg 2x, image-152x152.jpg 3x"`.

This is really about images in the category 3:

Wide panel layout:

![Bildschirmfoto am 2019-05-28 um 12 09 56-fullpage](https://user-images.githubusercontent.com/25466/58470261-925df800-8141-11e9-91d8-71bc85343a43.png)

Small, linear layout:

![Bildschirmfoto am 2019-05-28 um 12 10 10-fullpage](https://user-images.githubusercontent.com/25466/58470264-9427bb80-8141-11e9-96b7-b5f503f8b6d8.png)

We need a correct `sizes` definition for these cards because currently – on retina desktop for instance – always the largest image in loaded (2048 pixels in width).

**Comment by nilshoerrmann** [comment]
> Just before this discussion heads into that direction: for the Panel, we wouldn't want to include any js library.

I don't think we need a library at all. We know the column setup exactly and just have to figure out two things:

1. Which are the correct `sizes` settings for the panel (we are talking about a limited number of cases)?
2. How can the correct `sizes` attribute be added to the card's images the most effectively?

**Comment by distantnative** [comment]
So we have for sections:
> The following widths are available when defining columns:
> 1/2, 1/3, 1/4, 2/3, 2/4, 3/4

Those defined as 
https://github.com/getkirby/kirby/blob/master/panel/src/components/Layout/Column.vue

And our breakpoints defined here
https://github.com/getkirby/kirby/blob/master/panel/src/main.scss#L114-L121

**Comment by distantnative** [comment]
Since the `srcset` definition is tied to the page or file, I currently don't see how we could factor in the section width in which it is shown. Then defining `sizes` isn't really viable, is it?

**Comment by nilshoerrmann** [comment]
We don’t know the column when creating the image, is that what you mean? 

Hm, yeah, if we cannot pass that information down to the image template that sounds like a problem.

**Comment by distantnative** [comment]
The column does know it sizes, but the section isn't aware in what column it is... tricky.

**Comment by luxlogica** [comment]
Could you use some Vue bubble-up magic to have the section grab its required width info from the column? - and then, have the image grab its required width from the section?...

**Comment by distantnative** [comment]
Actually I think I just thought of a way - previously I thought we have to get it into the backend, where we also generate thte scrset information. But I think the sizes information could be generated directly in the Card Vue component. Writing this down mostly so I don't forget myself:

Pass down the column width to section components:
https://github.com/getkirby/kirby/blob/features/panel/src/components/Sections/Sections.vue

Map that to the data from the API in:
https://github.com/getkirby/kirby/blob/features/panel/src/components/Sections/FilesSection.vue and
https://github.com/getkirby/kirby/blob/features/panel/src/components/Sections/PagesSection.vue

Gets passed through collection... until Card. Calculate sizes attribute based on the column width:
https://github.com/getkirby/kirby/blob/features/panel/src/components/Layout/Card.vue

Add sizes prop to image component:
https://github.com/getkirby/kirby/blob/features/panel/src/components/Misc/Image.vue

**Comment by nilshoerrmann** [comment]
# Breakpoints

Okay, here we go:

- `1em = 16px` (browser default)
- `px` = CSS pixels

## Linear layout

**< 30em / 480px:**

- padding: `1.5rem * 16px = 24px`
- maximum image width: `479px - 2 * 24px = 383px`

**< 65em / 1040px:**

- padding: `3rem * 16px = 48px`
- maximum image width: `1039px - 2 * 48px = 943px`

## Column layout

**>= 65em / 1040px:**

**1 column:**

- maximum `.k-page-view` width: `100em × 16px - 2 × 96px = 1408px`
- maximum image width: `1408px`

**1/2 column:**

- maximum image width: `1408px / 2 = 704px`

**1/3 column:**

- maximum image width: `1408px / 3 = 470px`

**1/4 column:**

- maximum image width: `1408px / 4 = 352px`

**2/3 column:**

- maximum image width: `1408px * 2 / 3 = 939px`

**2/4 column:**

- maximum image width: `1408px * 2 / 4 =  704px`

**3/4 column:**

- maximum image width: `1408px * 3 / 4 = 1056`

# Sizes

**1 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 1408px, 383px" />
```

**1/2 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 704px, 383px" />
```

**1/3 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 470px, 383px" />
```

**1/4 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 352px, 383px" />
```

**2/3 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 939px, 383px" />
```

**2/4 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 704px, 383px" />
```

**3/4 column:**

```html
<img sizes="(min-width: 30em) 943px, (min-width: 65em) 1056px, 383px" />
```

**Comment by nilshoerrmann** [comment]
Or – alternatively – in `em`:


# Sizes

**1 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 88em, 24em" />
```

**1/2 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 44em, 24em" />
```

**1/3 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 30em, 24em" />
```

**1/4 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 22em, 24em" />
```

**2/3 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 59em, 24em" />
```

**2/4 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 44em, 24em" />
```

**3/4 column:**

```html
<img sizes="(min-width: 30em) 59em, (min-width: 65em) 66em, 24em" />
```

**Comment by nilshoerrmann** [comment]
The above `em` values are approximated and based on the pixel values in the first calculation. This makes sure we have a 1 pixel base for the images and not a 16px pixel base (1em = 16px).

**Comment by nilshoerrmann** [comment]
And just to point this out: of course, the `img` elements also need a `src` and `srcset` in order to work :)

**Comment by distantnative** [comment]
> And just to point this out: of course, the img elements also need a src and srcset in order to work :)

haha, thanks - I know I haven't shown my strongest suit with this yet. Could you explain for me why we should use e.g. 479px as maximum image width and not 480px? Is that 1px that signifcant here?

**Comment by nilshoerrmann** [comment]
Well, 497 pixels is the exact maximum size for that breakpoint and no browser resizing needed. It helped me getting the logic right but you can of course use 480 pixels, too. 🤷‍♂️

**Comment by distantnative** [comment]
@nilshoerrmann please have a look: https://github.com/getkirby/kirby/pull/1816

**Comment by nilshoerrmann** [comment]
Will do on Monday :+1:

**Comment by distantnative** [comment]
Just thinking, probably the current reset sizes don't make so much sense then, do they?

**Comment by nilshoerrmann** [comment]
> Could you explain for me why we should use e.g. 479px as maximum image width and not 480px? Is that 1px that signifcant here?

I though about your comment over the weekend, @distantnative, and you are totally right that this "precision" doesn't make a lot of sense. While it reflects my process of understanding the panel styles it is actually not that precise at all when we consider device pixels that are fractions of CSS pixels: there are situations where browsers might render at 479.5 pixels and not at 479 pixels while still fitting into the 480 pixel maximum. So sticking to the round numbers in `em` actually makes sense. Thanks for putting me back on track here.

So let's forget about the pixels and lets stick to the round `em`-based numbers:

```js
getSizes(width) {
  switch (width) {
    case "1/2":
    case "2/4":
      return "(min-width: 30em) 59em, (min-width: 65em) 44em, 27em";
      break;
    case "1/3":
      return "(min-width: 30em) 59em, (min-width: 65em) 29.333em, 27em";
      break;
    case "1/4":
      return "(min-width: 30em) 59em, (min-width: 65em) 22em, 27em";
      break;
    case "2/3":
      return "(min-width: 30em) 59em, (min-width: 65em) 58.667em, 27em";
      break;
    case "3/4":
      return "(min-width: 30em) 59em, (min-width: 65em) 66em, 27em";
      break;
    default:
      return "(min-width: 30em) 59em, (min-width: 65em) 88em, 27em";
      break;
  }
}
```

> Just thinking, probably the current reset sizes don't make so much sense then, do they?

Regarding the provided image set, what about the following:

```php
// for cards
$settings['cards'] = [
    'url' => $image->thumb([
        'width'  => 352
    ])->url(true),
    'srcset' => $image->srcset([
        352,
        432,
        704,
        864,
        944,
        1056,
        1408,
        1888,
        2112,
        2816
    ])
];
```

These image sizes are based on the layout breakpoints (`em` multiplied by 16) and consider non-retina and retina resolutions. I removed the exact sizes for the 1/3 and 2/3 columns which are very close to the next bigger image width.

Does this make sense?

**Comment by nilshoerrmann** [comment]
@distantnative, I've tested the latest changes in the `panel-srcset-sizes` branch and the panel does not apply the correct sizes: I've got a 1/3 column that gets default sizes values.

**Comment by nilshoerrmann** [comment]
It looks like `image.column` isn't defined inside the Card component.

**Comment by nilshoerrmann** [comment]
We have named columns in our blueprint like so:

```yml
columns:
  primary:
    width: 2/3
  secondary:
    width: 1/3
```

Not like this:

```yml
columns:
  - width: 2/3
  - width: 1/3
```

Might that be related?

**Comment by nilshoerrmann** [comment]
Okay, the error occurs with and without named columns. It looks like the section is the last component to know about the correct column context.

**Comment by nilshoerrmann** [comment]
To summarize: everything works in general (cool!) but the column width is not passed down correctly to the Card component (d'oh!).

**Comment by distantnative** [comment]
I'm a bit confused why...
we are passing it here to the sections:
https://github.com/getkirby/kirby/blob/0ac68e832eba88cebc894b8e991948c3673b2ffa/panel/src/components/Sections/Sections.vue#L12

But yea... this feature is really giving me grey hair.

**Comment by nilshoerrmann** [comment]
I'm not totally sure how these things work in Vue, but is it possible that the collection component is the problem? There seems to be a mixin and and a template …

**Comment by nilshoerrmann** [comment]
So, the Card component is calling `getSizes(image.column)` but there isn't a `column` key inside `image`. There is only a attribute `column` with the needed value.

**Comment by nilshoerrmann** [comment]
Testing this with a files section by the way.

**Comment by nilshoerrmann** [comment]
In a pages section, `image.column` also doesn't exist. There is a `column` attribute, too, but in this case it is undefined (while it should be `2/3`).

**Comment by nilshoerrmann** [comment]
Files section:

<img width="2048" alt="grafik" src="https://user-images.githubusercontent.com/25466/58864442-fe49de80-86b4-11e9-8607-a94902a6a24d.png">

Pages section:

<img width="2048" alt="grafik" src="https://user-images.githubusercontent.com/25466/58864469-0efa5480-86b5-11e9-8a48-df115935637e.png">

**Comment by nilshoerrmann** [comment]
`KPagesSection` is trying to set

```js
        page.column   = this.width;
```

but I think this should be 

```js
        page.column   = this.column;
```

At least there is a `column` prop populated with the correct value.

**Comment by distantnative** [comment]
@nilshoerrmann I think that's it XD thanks

**Comment by nilshoerrmann** [comment]
I'm trying to test this: how do I have to change `getSizes(image.column)` to make it use the attribute `column` instead of the `image` prop?

**Comment by bastianallgeier** [comment]
I fixed the column issue in the Pages Section and also used a transparent gif as placeholder to not load two images. I think we should go with this for the first RC today and then see how we can optimize it further.

**Comment by nilshoerrmann** [comment]
I think this line is not correct yet:
https://github.com/getkirby/kirby/blob/57382459212ad136e9835037d26cfe0d5dd66994/panel/src/components/Layout/Card.vue#L10

The correct value is in the `column` attribute (not sure how to access `$attrs`).

**Comment by nilshoerrmann** [comment]
@bastianallgeier: Here are the missing pieces to make this work:

- add `column: String` to the props of Card
- change `getSizes(image.column)` to `getSizes(column)` in Card

**Comment by bastianallgeier** [comment]
I just changed this, but I'm still not sure it's working correctly. I always end up with the 944px version, no matter what I do.

**Comment by nilshoerrmann** [comment]
I'll check it in a minute.

**Comment by nilshoerrmann** [comment]
I checked the latest changes and first of all:

1. source sets are generated correctly 
2. sizes attributes are generated correctly

🎉

The decision which image to use is up to the browser, so we don't know exactly how images are chosen, but on my desktop Mac I also noticed that the full width image is always chosen even for the smaller columns. That's either the way the browser chose or the media queries for the sizes are not correct (the largest image is defined in the first `(min-width: 30rem)`. Maybe we need a `max-width` here, too. Let me check this in a second.

**Comment by nilshoerrmann** [comment]
Let's do it like that:

```js
    getSizes(width) {
      switch (width) {
        case '1/2':
        case '2/4':
          return '(min-width: 30em) and (max-width: 65em) 59em, (min-width: 65em) 44em, 27em';
        case '1/3':
          return '(min-width: 30em) and (max-width: 65em) 59em, (min-width: 65em) 29.333em, 27em';
        case '1/4':
          return '(min-width: 30em) and (max-width: 65em) 59em, (min-width: 65em) 22em, 27em';
        case '2/3':
          return '(min-width: 30em) and (max-width: 65em) 59em, (min-width: 65em) 27em, 27em';
        case '3/4':
          return '(min-width: 30em) and (max-width: 65em) 59em, (min-width: 65em) 66em, 27em';
        default:
          return '(min-width: 30em) and (max-width: 65em) 59em, (min-width: 65em) 88em, 27em';
      }
    }
```

Phew, I've been learning a lot today about responsive images 😅

**Comment by bastianallgeier** [comment]
Done! Thanks for your help!!

**Comment by nilshoerrmann** [comment]
You're welcome! 
Thank you and @distantnative for actually implementing this 🥳

**Comment by nilshoerrmann** [comment]
Okay, there is one thing we forgot when calculating the `sizes` attribute: it's not only the column size that determines the maximum possible image size, it's also the card size. See https://forum.getkirby.com/t/thumbnail-sizes-for-file-cards-in-panel/14510/5.

**Comment by manuelmoreale** [comment]
@bastianallgeier can we reopen this? Because the issue is definitely still there. The browser is still loading huge images even when the card size is set to tiny

![Screenshot 2020-03-04 at 15 49 49](https://user-images.githubusercontent.com/1738077/75891226-c16f6b80-5e2f-11ea-8e33-07fd72c0566d.png)

I see 1400+ px images when the cards are not even 250px wide

**Comment by distantnative** [comment]
Better to open a new issue (I think there actually is one already, but I might be mistaken)

**Comment by manuelmoreale** [comment]
@distantnative Couldn't find anything in the current open issues so I created a new one.
