### ISSUE TITLE
Refactor stores and $events bus

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1809]
- [ ] `languages` store: add getter for specific language
- [ ] Go through all events, refactor and add more where needed

**Comment by bastianallgeier** [comment]
@distantnative Do we have a proper plan for this? Is this necessary for 3.3.0?

**Comment by distantnative** [comment]
@bastianallgeier we wanted to use 3.3 to refactor these things and make them more developer friendly. I think the remaining stores might only need a few changes but mainly documentation. Our event bus however still feels a bit unsystematic to me.

**Comment by bastianallgeier** [comment]
Yes, I remember :) I just don't remember what we wanted to fix in addition to the content store stuff. Maybe we should document them first and then see what seems unclear.

**Comment by distantnative** [comment]
Agreed. I'll close it for now and we can open individual issues for stores or the event bus when we realize what needs to be changed during writing docs.
