### ISSUE TITLE
[Panel] Array to string conversion in validation modal for files field

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#1811]
**Describe the bug**

Error modal says "Array to string conversion" instead of human readable message 

**To Reproduce**

1) Add a field somewhere

````yaml
mypictures:
  label: Bilder
  type: files
  min: 3
````

2) Open in panel, select less than 3 images and hit save.

**Expected behavior**

Expecting a human readable error message

**Screenshots**

![array_to_string](https://user-images.githubusercontent.com/6228942/58545476-9f432000-8203-11e9-905a-220cf60136e1.png)

**Kirby Version**

3.1.4

**Console output**

```
{
  "status": "error",
  "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)",
  "exception": "Kirby\\Exception\\InvalidArgumentException",
  "message": "Invalid form with errors",
  "key": "error.invalidArgument",
  "file": "y/src/Cms/ModelWithContent.php",
  "line": 423,
  "details": {},
  "code": 400
}
```

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Firefox]
 - Version [67.0]

**Comment by bastianallgeier** [comment]
✅
