### ISSUE TITLE
Panel: Error messages are not translated

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#1814]
(new ticket for error messages in issue #1796)

**Describe the bug**
If you get error messages while uploading files in the panel with the language set to German, they are not translated to German.

**To Reproduce**
1. In the panel (language set to German) go to a page with two files sections
2. Upload a file to the first files section
3. Upload the same file to the second files section
4. See error message 'The file exists and cannot be overwritten' in English instead of German
5. Upload a big file (here for example a PDF with 8.8MB) with standard MAMP settings in php.ini
6. See error message 'No uploaded files'

**Expected behavior**
The messages should be in German.

**Screenshots**
![58283117-d5b61080-7da7-11e9-8826-a649473c1333](https://user-images.githubusercontent.com/50926857/58632187-2f0ccb00-82e5-11e9-90dd-d9cc2fe361e2.png)

![58283131-db135b00-7da7-11e9-945e-def7abf0d02f](https://user-images.githubusercontent.com/50926857/58632217-40ee6e00-82e5-11e9-9484-fa1de903bb32.png)

**Kirby Version**
3.1.4

**Additional context**
This is probably related to more error messages; I just came across these two.

**Comment by bastianallgeier** [comment]
✅
