### ISSUE TITLE
Relative links broken in kirbytext

### ISSUE THREAD

**Issue by philsp** [getkirby/kirby#1815]
**Describe the bug**
Relative links in kirbytext are not correctly converted to absolute links

**To Reproduce**
1. Go to some subpage in panel i.e. "/sub/page"
2. Create text with kirbytag "(link: relative)"
3. Save and open page
4. Link points to "page.com/relative"

**Expected behavior**
Link should point to "page.com/sub/relative/"

**Kirby Version**
3.1.4

**Comment by distantnative** [comment]
@philsp I think for relative links it needs to be `(link: ./relative)`.

**Comment by bastianallgeier** [comment]
This is an intended behavior. Use @distantnative's version for relative links.
