### ISSUE TITLE
Access to $site in hooks

### ISSUE THREAD

**Issue by sebastianberns** [getkirby/kirby#1826]
I’m trying to dynamically pre-define the values of some page fields. While there may be other approaches, I tried to solve this with a `page.create:after` hook. In this setup it would be useful to have access to the kirby objects, [just like in a controller](https://getkirby.com/docs/guide/templates/controllers#accessing-kirby-objects-in-your-controller).

```php
# site/config/config.php
return [
  'hooks' => [
    'page.create:after' => function ($page, $site) {
      if($page->intendedTemplate() == 'home-item'){
        $ref = $page->content()->get('ref');
        $itempage = $site->find($ref); // returns null
        $page->save([
          'text' => $itempage->title() // not possible
        ]);
      }
    }
  ],
];
```

**Comment by texnixe** [comment]
You can access the objects like this

```
$kirby = kirby();
$site = site(); // or $kirby->site() or $page->site()
```

Such questions are actually better asked in the [forum](https://forum.getkirby.com)...
