### ISSUE TITLE
[Panel] Switching between tabs hides content of structure field

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#1827]
**Describe the bug**
https://getkirby.slack.com/files/U7P99HGVD/FKB0YKVGW/screen_recording_2019-06-04_at_16.33.44.mov

When switching between tabs, the contents of a structure field get hidden. Refreshing the page brings them back.

**Expected behavior**
Content should always be visible

**Kirby Version**
3.2-RC1

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Browser [e.g. chrome, safari] Chrome

**Comment by jakobploens** [comment]
Not only structure fields, but all fields seem to be empty after switching tabs in 3.2.0-rc.1

**Comment by bastianallgeier** [comment]
✅
