### ISSUE TITLE
Empty default value in position dropdown (3.2.0-RC1)

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#1828]
Screen attached.
Looks like the default option in the "Select Position" dropdown is missing a value and as a result the field looks visually squashed 

This happens in `3.2.0-RC1`

![Screenshot 2019-06-04 at 16 52 43](https://user-images.githubusercontent.com/1738077/58889630-8ba72600-86e9-11e9-8c73-49671d76ca6e.jpg)

**Comment by bastianallgeier** [comment]
✅
