### ISSUE TITLE
Fix / Improvement for request URI handling

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#1830]
**Describe the bug**
Kirby 3 stops working at all under Apache's `VirtualDocumentRoot`-configuration (Kirby 2 is OK). The reason is the handling of the `requestUri`-Variable in `kirby/src/Cms/App.php`. 

In a mass hosting environment using `VirtualDocumentRoot`-configuration the output of `$this->request()->url()->path()` contains the hostname, too. Therefore kirby is unable to detect the proper requested URI and results in a "Not found" on every single page of the whole site. That means Kirby 3 does not work under `VirtualDocumentRoot`-configurations at all.

**To Reproduce**
1. Go to https://forum.getkirby.com/t/kirby-3-bug-with-virtualdocumentroot/14480
2. Setup Kirby 3 a virtualhost with the example configuration 
3. Try to open up any page in Kirby

**Expected behavior**
Detect the correct request URI by changing one line of code, see below.

**Kirby Version**
3, including 3.2-rc1

To fix this behavior patch one line in `kirby/src/Cms/App.php`:

```
<         $requestUri  = '/' . $this->request()->url()->path();
---
>         $requestUri  = '/' . str_replace($_SERVER['HTTP_HOST'],"",$this->request()->url()->path());

```

**Comment by bastianallgeier** [comment]
Would you be able to send me the output of $_SERVER['REQUEST_URI'] for your virtual setup? We need to solve this in a different location.

**Comment by andreasotto** [comment]
This prints out the hostname from the ```Host:```-Header together with the scheme, like this:

```
string(17) "http://ktest.loc/"
```
Or this if i use another URI:

![Mægazine | Error](https://user-images.githubusercontent.com/2129515/59114276-1fc1f900-8947-11e9-9f6b-928cea1cda01.jpg)

For me that means you have to strip ```$_SERVER['HTTP_HOST']``` from the ```request()->url()->path()```. Whenever i can test this, i'd do it quickly.

**Comment by bastianallgeier** [comment]
Thanks! That's super helpful!

**Comment by bastianallgeier** [comment]
This should be fixed in the RC 3 tonight. Could you please give it a try and let me know if it actually works for you?

**Comment by bastianallgeier** [comment]
I'll close this. Reopen it if it's not fixed as expected.
