### ISSUE TITLE
KirbyTag gets escaped twice when using escape()

### ISSUE THREAD

**Issue by dgsiegel** [getkirby/kirby#1832]
**Describe the bug**

When using `escape()` on a KirbyText, KirbyTags get escaped twice.

**To Reproduce**

Given a field text with a textarea and the following content:

```
foo & bar

(link: http://example.com text: foo & bar)
```

In my template/snippet I am using the following line:

`<?= $page->text()->escape()->kirbytext() ?>`

The output is the following:

```
<p>foo &amp; bar</p>
<p><a href="http://example.com">foo &amp;amp; bar</a></p>
```

**Expected behavior**

The KirbyTag Link shouldn't be escaped twice.

**Kirby Version**
3.1.4

**Comment by dgsiegel** [comment]
I currently use this hook to remove the first escape, as all KirbyText's are escaped anyways:

```
'hooks' => [
  'kirbytags:before' => function ($text, $data, $options) {
    return html_entity_decode($text, ENT_COMPAT, 'utf-8');
  },
],
```

Another option would be to overwrite the affected KirbyTags, e.g.

```
'tags' => [
  'link' => [
    'attr' => Kirby\Text\KirbyTag::$types['link']['attr'],
    'html' => function($tag) {
      return Html::a(
        html_entity_decode($tag->value, ENT_COMPAT, 'utf-8'),
        html_entity_decode($tag->text, ENT_COMPAT, 'utf-8'),
        [ 
          'rel'    => $tag->rel,
          'class'  => $tag->class,
          'role'   => $tag->role,
          'title'  => $tag->title,
          'target' => $tag->target,
        ]);
    }   
  ],
],
```

**Comment by lukasbestle** [comment]
Chaining the `->escape()` and `->kirbytext()` won't work as they both encode HTML entities.

Your workaround with the hook therefore leads to the same result as not using the `->escape()` method in the first place (as you will undo the changes the `->escape()` method made).

What is your use-case for chaining these two methods?

**Comment by dgsiegel** [comment]
> Your workaround with the hook therefore leads to the same result as not using the `->escape()` method in the first place (as you will undo the changes the `->escape()` method made).

True, that's why I posted the second alternative.

> What is your use-case for chaining these two methods?

I was looking for ways to escape KirbyText, to prevent XSS.

**Comment by lukasbestle** [comment]
Ah, alright.

You could create a custom field method in a plugin for that use-case:

```php
Kirby::plugin('your/plugin', [
    'fieldMethods' => [
        'kirbytextEscaped' => function ($field) {
            // first escape everything
            $field = $field->escape();

            // then unescape just &amp; (keeps other escaped entities)
            $field->value = str_replace('&amp;', '&', $field->value);

            // finally run KirbyText
            $field = $field->kirbytext();

            return $field;
        }
    ]
]);
```

I have not tested all edge-cases, but it should be a good starting point. Please let me know if it worked for you, we might add it to the core in a later release. :)
