### ISSUE TITLE
[Panel] Image field causes TypeError when changing translation

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1833]
**Describe the bug**
A Image field with `translate` set to false causes a TypeError and the panel to freeze when switching between translations. This issue appeared with kirby 3.1.4. 

**To Reproduce**
1. In a multilang setup add following field to a blueprint:
```
    fields:
      testfield:
        type: files
        translate: false
````
2. In the Panel navigate to a page using the blueprint
3. Try to switch back and forth between translations using the language toggle.

**Kirby Version**
only 3.1.4

**Console output**
![Bildschirmfoto 2019-06-05 um 16 15 26](https://user-images.githubusercontent.com/18071758/58963281-2b79b800-87ad-11e9-8c78-1be89eaf6bee.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 74

**Comment by bastianallgeier** [comment]
✅
