### ISSUE TITLE
"Duplicate Page" Dialog Has "Copy files"/"Copy pages" Options When They Are Irrelevant

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1834]
**Describe the bug**
When a page has no files or subpages, I would not expect the "Copy files" or "Copy pages" toggles to appear, because they are functionally useless in this case.

**To Reproduce**
1. Open a page that has no files and/or no subpage
2. Click on Settings > Duplicate

**Expected behavior**
I would only expect to see "Copy files" if there are files to be copied. I would only expect "Copy pages" if there are subpages to be copied.

**Screenshots**
<img width="510" alt="Screen Shot 2019-06-05 at 10 01 29 AM" src="https://user-images.githubusercontent.com/417182/58975066-e50a6600-8778-11e9-8694-a9a43af64739.png">

**Kirby Version**
`3.2.0-rc.1`

**Comment by bastianallgeier** [comment]
✅
