### ISSUE TITLE
[Panel] Load icons from svg sprite instead of individual ajax requests

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#184]

**Comment by jenstornell** [comment]
What about plugin support? Will plugins use the sprite as well or single icons? If plugins will use the sprite I guess it needs to contain every icon to be useful and it would probably be a big file.

So it's sprite for the panel and individual icons for plugins then?

**Comment by bastianallgeier** [comment]
I think it would be perfect to have a sprite for all the default icons, that we ship with the panel and load additional plugin icons dynamically, like we do now.

**Comment by distantnative** [comment]
✅
