### ISSUE TITLE
Bug: Kirby outputs https links in non-ssl nginx server

### ISSUE THREAD

**Issue by dcorb** [getkirby/kirby#184]
I just downloaded kirby for the first time, put it on my local virtual machine nginx-enabled server, and I see in the source code of the html that assets are loaded with https
http://monosnap.com/image/np3rYj138x9EhRAGviSx0tnMIMW5S7 (updated link)
Clicking the "panel" link didn't work neither.
Is there any nginx configuration that you recommend ? I didn't see anything in the docs

**Comment by shoesforindustry** [comment]
There is, it is just hard to find :) try:
https://gist.github.com/bastianallgeier/c2e1f1e519f5f2943ec4

I combined the above with some more stuff from the h5bp server configs:
https://github.com/h5bp/server-configs-nginx

Hope this helps.

**Comment by dcorb** [comment]
Thanks for the reply!

I see that the panel link doesn't work because of the http -> https redirection.

I still don't understand why is defaulting to https, when ssl option is off

**Comment by shoesforindustry** [comment]
Sorry, I'm not quite sure I understand, are you saying you are switching the panel to HTTPS or are you switching your whole site to use HTTPS? Panel doesn't automatically default to HTTPS, at least not on my sites. What else is in you nginx configuration, maybe something else is doing this?

**Comment by dcorb** [comment]
Yes, I explain myself better:

I'm testing for the first time kirby just in my local machine (under a virtualbox, where I have Drupal, wordpress, static sites, etc, etc all running without problems)

I don't have SSL configured and I don't need https, but kirby forces everything to be https. Don't know why. Including CSS, JS, images, and internal links as you see, breaks everything and internal links don't work:
http://monosnap.com/image/5t1mHLN1xDhU4CI8rphq2JyzCP7jrw

**Comment by shoesforindustry** [comment]
If you just create a basic `index.html` page and put it on your server, so Kirby does not process it, and then view this page in your browser, does that change to HTTPS?

**Comment by dcorb** [comment]
If I copy the source HTML of what kirby outputs. Make a string replace "https" for "http", and save that as index.html, then it loads nicely, CSS, images, and
Also I had to change nginx to give index.html preference over index.php:
<code>"server index.html index.php"</code>

**Comment by shoesforindustry** [comment]
OK, so you are saying straight HTML loads without nginx chaning it to HTTPS, so what is in your Kirby config?

**Comment by dcorb** [comment]
I found the root cause. See the link above with the fix

**Comment by shoesforindustry** [comment]
Odd, I've never had that problem, but I'm glad it is fixed for you.

**Comment by bastianallgeier** [comment]
I just fixed this in the develop branch of the toolkit. it will be in the next stable release! Thanks :)
