### ISSUE TITLE
[Panel] Time Field Lets You Deselect Just AM/PM (3.2.0-rc.2 Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1844]
**Describe the bug**
When using time with a the `date` field, it lets you deselect just the AM/PM portion. It shouldn't be possible to have an "incomplete" date/time.

In Kirby 3.1.4, this was impossible to do because "—" wasn't listed as an option. See screenshot at the end.

```yaml
created:
  label: Published Date
  type: date
  time:
    step: 1
    notation: 12
```

**To Reproduce**
1. Have a filled in date/time
2. Click on the 'AM/PM' portion
3. Select "—"

**Expected behavior**
Either keep the Kirby 3.1.4 behavior and prevent this from happening, or clear the entire date field ("—").

**Screenshots**
<img width="322" alt="Screen Shot 2019-06-10 at 10 37 27 AM" src="https://user-images.githubusercontent.com/417182/59214609-44e38100-8b6c-11e9-9903-f4295eb8e9c0.png">
<img width="259" alt="Screen Shot 2019-06-10 at 10 45 59 AM" src="https://user-images.githubusercontent.com/417182/59214956-f71b4880-8b6c-11e9-82dd-53591fef3a64.png">
<img width="304" alt="Screen Shot 2019-06-10 at 10 37 32 AM" src="https://user-images.githubusercontent.com/417182/59214612-4745db00-8b6c-11e9-8e58-5d335620812c.png">

**Kirby Version**
`3.2.0-rc.2`

**Console output**
If you are working with the panel, please check the browser console for errors and send the output.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Safari 12.1.1

**Additional context**
In Kirby `3.1.4`, the AM/PM field didn't even have a "—" option. See screenshot:
<img width="308" alt="Screen Shot 2019-06-10 at 10 42 47 AM" src="https://user-images.githubusercontent.com/417182/59214746-95f37500-8b6c-11e9-92bf-547a30f9890f.png">

**Comment by neildaniels** [comment]
Simple time fields have this regression.

**Comment by bastianallgeier** [comment]
✅
