### ISSUE TITLE
Title Rename Dialog on iOS Safari is Hard To Use

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1845]
**Describe the bug**
On iOS Safari, trying to move the text cursor on the Page Title Rename dialog is really difficult to use.

**To Reproduce**
1. Open a page (with a long title) on Safari on an iPhone
2. Page settings > Rename
3. Try to move the cursor around the text field

**Expected behavior**
It would be infinitely more helpful if this title field **wrapped to multiple lines**.

Currently, trying to move the cursor around the title field is very cumbersome. Most of the unwanted behavior seems to be a native iOS Safari thing, unfortunately.

**Screenshots**
Here's a video: 
[RPReplay_Final1560209121.MP4.zip](https://github.com/getkirby/kirby/files/3274145/RPReplay_Final1560209121.MP4.zip)

**Kirby Version**
`3.1.4` and `3.2.0-rc.2`

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.4
 - Safari

**Comment by distantnative** [comment]
Difficult to switch from an iput field to a textarea based on browser width. Not sure if we should go down this road - seems to me that this is rather a downside of the OS/browser.

**Comment by distantnative** [comment]
I will close this for now as I don't think it's a shortcoming of the browser that we cannot reasonably fix.
