### ISSUE TITLE
Unable to return additional data for the template

### ISSUE THREAD

**Issue by puleddu** [getkirby/kirby#185]
Using the method documented here: http://getkirby.com/docs/advanced/routing#returning-a-page-with-additional-data-for-the-template

I'm trying to send some additional data, but – on the template side – I receive an empty array.

```php
array(
    'pattern' => 'customers/(:all)/textonly',
    'action'  => function($customerUID) {
      
      $customer = page(c::get('content.folder.customers') . $customerUID);
      $data = array(
          'foo' => 'bar'
        );
      return array('customers/textonly-email', $data);
    },
    'method' => 'GET'
  )
```

In my template `textonly.php` 

```php
dump($data);
```

Which is just printing: 

```
Array
(
)
```

Is it an issue or I'm just doing something wrong? Any suggestion to debug this problem?

**Comment by alberteddu** [comment]
Looks like variables passed are extracted from the array. Following your example, you can use `$foo`.

**Comment by puleddu** [comment]
Thanks! It worked. :)
