### ISSUE TITLE
multiple drop images in textarea results only in one tag

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1850]
when dropping multiple images from finder into an textare they get uploaded into the files file of the blueprint correctly. however only a single kirbytag for the first image (sorted by name) is created. intended behavior or not?

kirby 3.1.4

**Comment by distantnative** [comment]
What would be the expected behavior - multiple Kirbytags (one for each) with/without line breaks?

**Comment by bnomei** [comment]
i expected multiple kirby tags. with linebreaks to reflect the fact that images are wrapped in figure elements which are block elements by default.

**Comment by distantnative** [comment]
As I just spotted, it's not essentially a bug but explicitly set:
https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Input/TextareaInput.vue#L175-L181

**Comment by distantnative** [comment]
Or more specifically this one for the inserted text:
https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Input/TextareaInput.vue#L154

**Comment by bnomei** [comment]
thanks @distantnative for the related code. i still do not understand why its limited to one file.

**Comment by distantnative** [comment]
Wasn't meant as an explanation - just pointers for me to also keep track of where this happens. @bastianallgeier implemented it, so if there wa a reasoning only he knows atm.

**Comment by bastianallgeier** [comment]
✅
