### ISSUE TITLE
Can No Longer Pass Pages Object Into `new Pages()` (3.2.0-rc.2 Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1852]
**Describe the bug**
An `array` type was added to the signature for the Collection constructor. This breaks previously "permitted" behavior of creating a new Pages object from another Pages object.

For example:
```php
$fooCollection = new Pages($somePage->children()->listed());
```

I suspect any place that does this could be revised to be `$fooCollection = clone $somePage->children()->listed();`, but to me it was very intuitive to say "I want a new Pages object and it should start out with the contents of this other Pages object".

Could the type hint be `iterable` instead of array? Nothing in that function seems to inherently _need_ an array.

**Kirby Version**
`3.2.0-rc.2`

**Additional context**

**Kirby 3.1.4:**
https://github.com/getkirby/kirby/blob/0885e295788aadac1bd11fbbd28502d3119d2959/src/Cms/Collection.php#L58

**Kirby 3.2.0:**
https://github.com/getkirby/kirby/blob/2c46d0cce0e471ed6bae38f29c998df2197a67eb/src/Cms/Collection.php#L59

**Comment by bastianallgeier** [comment]
✅
