### ISSUE TITLE
Unsaved Changes Lists Same Page Multiple Times

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1857]
**Describe the bug**
I can easily run into a situation where the same page with unsaved changes is listed multiple times in the new "Unsaved Changes" list in the Panel.

I'm not exactly sure what causes it, and refreshing the page can cause the list to be re-ordered and with a different set of duplicates.

**To Reproduce**
1. Edit a page in the Panel (but don't save)
2. Navigate to a different page
3. Press Refresh in your browser
4. Click on the "Unsaved Changes" icon in the Panel toolbar

**Expected behavior**
A page should only be listed once in the list.

**Screenshots**
<img width="874" alt="Screen Shot 2019-06-11 at 12 39 26 PM" src="https://user-images.githubusercontent.com/417182/59301658-f8b93f00-8c46-11e9-97e6-0bd6f08c4b4a.png">
<img width="858" alt="Screen Shot 2019-06-11 at 12 39 46 PM" src="https://user-images.githubusercontent.com/417182/59301663-fb1b9900-8c46-11e9-9034-07fc088a8f54.png">
<img width="274" alt="Screen Shot 2019-06-11 at 12 46 40 PM" src="https://user-images.githubusercontent.com/417182/59301668-fce55c80-8c46-11e9-8390-92f1b46a0c81.png">

**Kirby Version**
`3.2.0-rc.2`

**Console output**
None

**Desktop (please complete the following information):**
 - OS: 10.14.5 (18F132)
- Chrome 75.0.3770.80
 - Safari 12.1.1 (14607.2.6.1.1)

**Comment by distantnative** [comment]
We encounter some more issues with the form indicator while investigating this issue. Therefore, we have postponed the feature to 3.3.

**Comment by distantnative** [comment]
Will be solved with the FormIndicator refactoring.
