### ISSUE TITLE
Delete Confirmation Dialog Does Not Clear Text Field on Cancel

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1858]
**Describe the bug**
If you attempt to delete a page that has subpages via the "…" button on a `pages` section, type something in the box, then click "Cancel" the text you entered will still be there if you try to delete the same page or even a different page later on.

**To Reproduce**
1. Go to somewhere in the Panel with a `pages` section
2. Click on '…' next to a page with subpages
3. Click Delete
4. Type something in the text field
5. Click Cancel
6. Attempt to delete a different page with subpages

**Expected behavior**
Text field should be empty, instead it currently keeps old text.

**Screenshots**
<img width="499" alt="Screen Shot 2019-06-11 at 12 57 02 PM" src="https://user-images.githubusercontent.com/417182/59302264-6a45bd00-8c48-11e9-9b7e-34516bd9b14f.png">

**Kirby Version**
`3.1.4` and `3.2.0-rc.2`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5 (18F132)
 - Safari 12.1.1 (14607.2.6.1.1)

**Comment by zvaehn** [comment]
it's also not cleared when you delete multiple parent pages at once without a page reload ;)

![Screenshot 2019-06-24 at 14 01 16](https://user-images.githubusercontent.com/5555821/60017305-b7824f80-9688-11e9-842f-1bff97af3f63.png)

**Comment by bastianallgeier** [comment]
✅
