### ISSUE TITLE
[Panel/Cms] Unbeatable default values, they are always there

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#186]
Since on blur field refresh their data, fields with a default value cannot be left empty anymore.

**Comment by bastianallgeier** [comment]
This is no longer an issue with the new form handling.

**Comment by distantnative** [comment]
@bastianallgeier It still ist. If I delete the default value to leave the field empty on purpose, as soon as I hit "save" the default value gets added again.

**Comment by bastianallgeier** [comment]
Ahhh, shit!

**Comment by bastianallgeier** [comment]
I think I really solved it this time :D

**Comment by distantnative** [comment]
I can confirm that :D

**Comment by bastianallgeier** [comment]
🎉
