### ISSUE TITLE
Wrong type hint (string) for parameter $text in Kirby\Toolkit\Html::email

### ISSUE THREAD

**Issue by crealistiques** [getkirby/kirby#1860]
**Describe the bug**
In https://github.com/getkirby/kirby/blob/88d84f4df9738e285247a942f1f5cfce48949235/src/Toolkit/Html.php#L165

the parameter $text uses string type hinting, but should be a mixed type according to method parameter annotation at https://github.com/getkirby/kirby/blob/88d84f4df9738e285247a942f1f5cfce48949235/src/Toolkit/Html.php#L161

**To Reproduce**
Eg. call Kirby\Toolkit\Html::a with an array value for parameter $text in order to prevent encoding, and a mailto: type value for $href. An error then occurs at https://github.com/getkirby/kirby/blob/88d84f4df9738e285247a942f1f5cfce48949235/src/Toolkit/Html.php#L65
because $text is expected to be a string, but is an array.

**Kirby Version**
3.2.0-rc.2

**Comment by bastianallgeier** [comment]
Thanks for the detailed bug report! I just fixed it :)
