### ISSUE TITLE
[Panel] Query language in headline not working

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1862]
**Describe the bug**
According to the documentation it should be possible to use query language in section headlines:

> The headline for the section. This can be a simple string or a template with additional info from the parent page.

However, a section definition like this displays just a literal string:

```
drafts:
  headline: "Articles for {{ page.title }}"
```

**To Reproduce**
1. Add the above headline to a section in a blueprint
2. Open a page with this blueprint in the Panel

**Expected behavior**
The query template should be resolved.

**Kirby Version**
All Kirby versions up to 3.2rc2

**Comment by bastianallgeier** [comment]
✅
