### ISSUE TITLE
[Panel] No validation while creating a new language

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1863]
You can complete this dialog with incomplete input and end up with broken files in your Kirby 3 installation. No validation happens on saving.

Kirby 3.20 rc2

![grafik](https://user-images.githubusercontent.com/6271057/59425353-051fd200-8dd6-11e9-9b34-7a767ea2c1a2.png)

**Comment by bastianallgeier** [comment]
✅
