### ISSUE TITLE
Field property: image - breaks the panel when using type:pages

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1870]
**Describe the bug**
Inside my **site.yml** I display three different sections where each of them uses the field `type: pages`. I also used the field property: `image: false` to show the blueprint icon instead the first image from each page. After updating to the latest release candidate the panel throws an error: 
`The section "jobs" could not be loaded: Argument 1 passed to Kirby\Cms\Page::panelIcon() must be of the type array, null given, called in `

**site.yml**

```
title: Site

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            image: false
            template:
              - home
              - default
              - about
              - contact
              - jobs

          footer:
            headline: Meta Pages
            type: pages
            image: false
            template: 
              - metapage
              - error
            create: metapage

      - width: 1/2
        sections:
          jobs:
            headline: Current Opportunities
            type: pages
            image: false
            parent: site.find("jobs")
            status: unlisted
            info: "posted on {{ page.dateposted.toDate('d.m.Y') }}"
            empty: No current job opportunities.
```

**To Reproduce**
1. Add the `image:false` option to a field with `type: pages`
2. Add an emoji as an icon to a page blueprint.
3. See error
4. If I delete the option `image:false` it works as expected but the first image from that page is shown. (see screenshots)

**Expected behavior**
It should display the icon and ignore the first image under each page.

**Screenshots**
`image: false`:

![Capture](https://user-images.githubusercontent.com/11317959/59756392-e912a980-9289-11e9-8a43-a77226abb265.PNG)

`without image option`:

![Capture2](https://user-images.githubusercontent.com/11317959/59756538-342cbc80-928a-11e9-892d-bd812ff14dd1.PNG)

**Kirby Version**
3.2.0-rc.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - latest version

**Comment by distantnative** [comment]
That was just fixed yesterday - see https://github.com/getkirby/kirby/issues/1864 :)

**Comment by flokuek** [comment]
Ups, must have missed that :)
