### ISSUE TITLE
[Panel] Duplicate page function ignores max property

### ISSUE THREAD

**Issue by foxacid** [getkirby/kirby#1871]
**Describe the bug**
When using the 'duplicate' function introduced in `3.2.0` it is possible to exceed the limit set via the `max` property in a pages section.

**To Reproduce**
1. Set up a blueprint with a pages section
2. Set the pages section‘s `max` property to `1`
3. Create a new page using the 'Add' button
4. Open the options for the newly created page and duplicate it

**Expected behavior**
The duplicate function should be disabled when the number of pages has reached the parent pages section‘s `max` limit.

**Kirby Version**
`3.2.0-rc.2`

**Comment by distantnative** [comment]
I think this is connected to https://github.com/getkirby/kirby/issues/1306

Cause basically you could have different pages sections with distinct max values... very difficult to say what should happen then.

**Comment by bastianallgeier** [comment]
I wonder if we need global validation rules per page type that always kick in, no matter if the individual max of a section is lower.

**Comment by distantnative** [comment]
We won't be able to solve this in Kirby 3, but noted it as an aspect to consider for future developments after that.
