### ISSUE TITLE
Video tag width/height not correctly assigned

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1875]
**Describe the bug**
When embedding a video via the `(video: somevideo width: 900 height: 800)` Kirbytag and setting a width and height attribute, the output is:

```
<figure class="video" height="800" width="900"><iframe allowfullscreen="" src="https://youtube.com/embed/lLuc6rtWkrM"></iframe></figure>
```

However, the output should be:

```
<figure class="video" style="height:800px; width:"900px"><iframe allowfullscreen="" src="https://youtube.com/embed/lLuc6rtWkrM"></iframe></figure>
```

so that the iframe can then be set to 100% width and height of the container.

Or the width and height applied to the iframe like in the Kirby 2 YouTube tag.

**To Reproduce**
1. Insert the above video tag into a textarea field
2. Open the page in the browser

**Expected behavior**
The tag should apply inline styles to the figure tag instead of using image-style width and height attributes.

Tested with Kirby 3.2.0-rc4.

**Comment by bastianallgeier** [comment]
✅ The width and height attributes are now assigned to the iframe
