### ISSUE TITLE
[Panel] Empty label, placeholder etc. translations when language is not defined

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1876]
**Describe the bug**
When defining translation for field labels, info field text, info section text for multiple languages and the user selects a language that is not defined, the property either remains empty (label, placeholder, info section text) or throws an error (info field text)

Info field:
```
        fields:
          info:
            type: info
            label:
              de: Super wichtige Info
              en: Super important info
            text:
              de: Hier Info text
              en: Here info text
```
If the logged in user doesn't use one of the defined languages, this throws the following
error: 
> Return value of Kirby\Cms\ModelWithContent::toString() must be of the type string, null returned

(the `toString()` method was introduced in 3.2, the error could be prevented by making the required string return value optional, but it would still result in an empty field).

If we use an info section instead of an info field in the example above, there is no error message but the info section remains empty.

Similar behaviour happens in case of translated labels, placeholders and probably other properties I haven't tested. The result seems to be always null in those cases. For example, without a label set, Kirby usually falls back to the field key. However, once you define translations and the user selected translation does not exist, Kirby just returns null, not even falling back to the field key.

**To Reproduce**
1. Create the above field (or an info section) in a blueprint, e.g. `site.yml`
2. Visit the site in Panel.

**Expected behavior**
One solution could be to always require an English translation in the blueprint and then fall back to English (this was required in Kirby 2).

A second option would be to always fall back to the first defined language.

In case of field labels, falling back to the field key could also be an option.

**Screenshots**

**Kirby Version**
3.2.0-rc4.

**Additional context**

**Comment by bastianallgeier** [comment]
I cannot reproduce the string error. In my case, with your blueprint setup, I only get empty labels. I will move it to 3.2.1

**Comment by texnixe** [comment]
Hm, strange, today I can't reproduce the error either, can't even find this `toString()` method anymore.. Maybe it was a cache thing after all. I edited the issue headline.
Anyway, the empty labels etc. could do with some sort of fix.

**Comment by bastianallgeier** [comment]
✅
