### ISSUE TITLE
Uploads from files fields should prevent selecting wrong MIME types

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#1877]
**Describe the bug**
As in files sections, uploads though files fields should make wrong MIME types opacified/disabled instead of displaying error.

**Expected behavior**
Like the files sections.

**Screenshots**
<img width="815" alt="Capture d’écran 2019-06-25 à 10 46 35" src="https://user-images.githubusercontent.com/4832038/60083756-95dfa180-9736-11e9-8f97-2f581edda8d2.png">
<img width="481" alt="Capture d’écran 2019-06-25 à 10 46 53" src="https://user-images.githubusercontent.com/4832038/60083760-95dfa180-9736-11e9-9149-83bd8e54604d.png">

**Kirby Version**
3.2

**Comment by neildaniels** [comment]
Related: https://github.com/getkirby/kirby/issues/1783

**Comment by bastianallgeier** [comment]
✅
