### ISSUE TITLE
Panel jumps to top of page during file upload in textarea

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#1879]
**Describe the bug**
While uploading a file in the bottom part of a textarea that contains a lot of text (so you have to scroll down first), the panel jumps to the top of the page to select the file, after selection down again.

**To Reproduce**
1. Go to the Panel
2. Create a textarea with a lot of text, so you have to scroll down the panel to reach the bottom
3. Upload a file in the bottom part of the textarea with the "file" button
4. Panel jumps up to top of the page

**Expected behavior**
It would be practical if the panel stays in the same position, so one can see the text/context while selecting the image. This would help if there are still decisions to be made choosing the image or if one forgott what image one wanted to upload.

**Kirby Version**
2.3.0 

**Desktop:**
 - OS: macOS Sierra 10.12.6
 - Browser: Firefox
 - Version: 67.0.4

**Comment by Pandorrrrrra** [comment]
Just realised that the Panel actually also always jumps to the bottom of the textarea after an upload in the textarea with the "file" button.

**Comment by bastianallgeier** [comment]
✅
