### ISSUE TITLE
Trim kirbytext tag attributes

### ISSUE THREAD

**Issue by puckey** [getkirby/kirby#188]
When you use the following kirbytext tag (note the space after : ):
(sometag: test.jpg)

And then access it in code:
$tag->attr('sometag')

It returns a string with a leading space:
' test.jpg'

I would expect it to trim out the spaces.. (this has lead me to scratch my head a few times already)

**Comment by bastianallgeier** [comment]
This is extremely weird, because in fact attribute values are trimmed to avoid exactly this. If not, all the tests would fail, that I have written for Kirbytext. Could you maybe paste a bit more code about it here.

**Comment by puckey** [comment]
In that case, I will look into my code once more to see if I am doing something wrong. I will get back to you soon.

**Comment by puckey** [comment]
This was my mistake - sorry about that.
