### ISSUE TITLE
snippet within plugin breaking on 3.2.x Illegal offset type

### ISSUE THREAD

**Issue by carstengrimm** [getkirby/kirby#1883]
as discussed here: 
https://forum.getkirby.com/t/snippets-breaking-changes-on-3-2/14735?u=carstengrimm

on V3.2. it seems that snippets within a plugin seem to break the whole thing.
one-page style setup with running though snippets via ```$page->template()``` as snippet name seem to fail:

```
<?php foreach($page->children()->listed() as $p): ?>
        <?php snippet($p->template(), ['data' => $p]); ?>
<?php endforeach ?>
```

![Kirby_CMS_Debugger_-_Brave_2019-06-27_02-08-59](https://user-images.githubusercontent.com/5014509/60246312-b9355880-98be-11e9-99e7-1651dd587f01.jpg)

**Comment by bastianallgeier** [comment]
✅
