### ISSUE TITLE
[Panel] Font weight in date selectors

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1884]
**Describe the bug**
If you double-click one of the input fields of the date field, the dropdown will be displayed in bold whereas it is displayed in normal font weight when only clicking once.

**To Reproduce**
Double-click the year input of the date field. Might be necessary to select one of the other fields first.

**Expected behavior**
Font weight should always be normal.

**Screenshots**
<img width="467" alt="grafik" src="https://user-images.githubusercontent.com/25466/60252278-403bfe00-98ca-11e9-94da-2f98c92cab0e.png">

**Kirby Version**
Kirby 3.2, latest Firefox on macOS Mojave.

**Comment by bastianallgeier** [comment]
✅
