### ISSUE TITLE
Implement drafting & publishing of pages

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#189]
- [x] Implement _drafts folder storage
- [x] Implement draft publishing workflow
- [x] Fix sibling selection when sorting drafts
- [x] Remove sorting number when a listed page is being converted to a draft
- [x] Implement draft previews
- [x] Implement drafts on main content level 
- [x] Remove the drafts folder if no longer needed

**Comment by bastianallgeier** [comment]
✅
