### ISSUE TITLE
User models not working as expected

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1892]
**Describe the bug**

I created a new User model like described in the docs (ok, ok, I added it there myself):

In `/site/plugins/usermodels/index.php`
```
<?php
class EditorUser extends User
{
    public function sayhello() {
        return 'Hello';
    }
}

Kirby::plugin('texnixe/usermodels', [
    'userModels' => [
        'editor' => 'EditorUser'
    ],
]);

```

The I created a user with the `Editor` role in `/site/blueprints/users/editor.yml` and tried to make this user say hello:

```
if ($user = $kirby->user('myeditoruseremail')) {
  echo $user->sayhello();
}
```

But the output from the above user model method is nothing. Also, the user is still a `/Kirby/Cms/User` object, not an `EditorUser`.

The same happens with FileModels.

**To Reproduce**
1. Create a new user role, e.g. `Editor` in `/site/blueprints/users/editor.yml`
2. Create a new user with this role.
3. Create a plugin with the user model as above
4. Try to echo the `sayhello()` method.
5. See nothing

**Expected behavior**
The user model should work based on the user role (and the file models based on the file template) in the same way as Page models.

**Kirby Version**
3.2.0

**Comment by distantnative** [comment]
@texnixe Could you please check if it works for you with this change?
https://github.com/getkirby/kirby/commit/8e41af47345752cee38df6328ea42cb193db476b

**Comment by afbora** [comment]
@distantnative I've tested https://github.com/getkirby/kirby/commit/8e41af47345752cee38df6328ea42cb193db476b on 3.2.2, failed. (_Replaced only Users::load() method_)

**Comment by texnixe** [comment]
@afbora Please test with the dev branch there have been some other changes in the meantime, user models now work for me, file models still don't.

**Comment by afbora** [comment]
@texnixe as your said dev branch works properly for user models 👍

**Comment by bastianallgeier** [comment]
User models are now fixed. I create a separate issue for file models.

**Comment by afbora** [comment]
I have detailed tested user models with 3.2.3 RC1 and i have an issue.
I didn't feel the need to open a new issue (I can open new if necessary)

If i use `kirby()->user()` in plugin anywhere, user models not working:

```
<?php

class AdminUser extends User
{
    public function sayHello() {
        return "Hello " . $this->name();
    }
}

Kirby::plugin('my/plugin', [
    'userModels' => [
        'admin' => 'AdminUser'
    ],
]);

$user = kirby()->user(); // Use anywhere in plugin
```

I traced the issue and found that:

Standart plugin without using user method, working order is:

1. AppPlugins::extendUserModels()
2. User::model()

If `kirby()->user()` used in plugin, working order is:

1. User::model()
2. AppPlugins::extendUserModels()

https://github.com/getkirby/kirby/blob/release/3.2.3-rc.1/src/Cms/AppPlugins.php#L452-L455

https://github.com/getkirby/kirby/blob/release/3.2.3-rc.1/src/Cms/User.php#L485-L496

So when we use `kirby()->user()` method in plugin, userModels cant overwrite it.

I hope I can tell..

**Comment by distantnative** [comment]
Could you please open a new one for this? That sounds like a separate issue. Thanks.

**Comment by lukasbestle** [comment]
Actually I think this is not an issue, but a current limitation that will be fixed by https://github.com/getkirby/ideas/issues/23.

**Comment by afbora** [comment]
@lukasbestle Not exactly. I'm using `kirby()->user()` method  (to use user based settings/dashboard) in/for plugin, not after plugin loaded. For example currently using like that:

```
Kirby::plugin('custom/plugin', [
    'blueprints' => [
        'site' => kirby()->roots()->blueprints() . '/site.' . kirby()->user()->role() . '.yml'
    ]
]);
```

**Comment by lukasbestle** [comment]
We can't fix that unfortunately. We can only load user models after all plugins have been loaded. You could potentially define the blueprint later in the process (`$kirby->extend()`), but that again will be possible with https://github.com/getkirby/ideas/issues/23.

**Comment by afbora** [comment]
You know better than I do: "**Kirby always has a solution**" 😎

This name is "**Kirby Power!"** 🚀

To help developers in need:

```
<?php

if ($userId = kirby()->session()->get('user.id')) {
    $user = new \Kirby\Cms\User(['id' => $userId]);
    Kirby::plugin('custom/plugin', [
        'blueprints' => [
            'site' => kirby()->roots()->blueprints() . '/site.' . $user->role() . '.yml'
        ]
    ]);
}
```
