### ISSUE TITLE
Subpage error after 3.2.0 update

### ISSUE THREAD

**Issue by cvalues** [getkirby/kirby#1893]
**Describe the bug**
This messages is shown after updating to 3.2.0: (The parent for the query “site.find(“products”)” cannot be found in the section “listed”), in the subpages area.
I have a multilanguage setup with two languages. After switching to the second language and reload page, the subpages will be shown.

**To Reproduce**
https://forum.getkirby.com/t/error-after-update-to-3-2-0-with-the-subpages/14783

**Expected behavior**
Subpages should be shown

**Screenshots**
![screen](https://user-images.githubusercontent.com/45170500/60441885-37c02c00-9c18-11e9-8dc0-7dde4bdd7f09.png)

**Kirby Version**
3.2.0

**Console output**
{status: "error", exception: "Exception", message: "The parent for the query "site.find("products")" cannot be found in the section "unlisted"", file: "", line: 23, …}

also for listed and draft

**Comment by bastianallgeier** [comment]
This only happens if you use the parent option with `site.find()` and the page does not exist or is a draft. You can use `kirby.page()` instead to avoid problems with drafts.
