### ISSUE TITLE
Panel refuses German Umlauts in email addresses

### ISSUE THREAD

**Issue by saschabregenhorn** [getkirby/kirby#1895]
When adding panel users, the PHP email validator refuses email addresses with German Umlauts.

![panel-add-user](https://user-images.githubusercontent.com/2510090/60581853-f64e8e80-9d87-11e9-9391-b268671d83a7.png)

**Comment by distantnative** [comment]
I fear `FILTER_VALIDATE_EMAIL` doesn't care about umlaute...
https://github.com/getkirby/kirby/blob/master/src/Toolkit/V.php#L273

**Comment by bastianallgeier** [comment]
✅
