### ISSUE TITLE
[Panel][FR] Translatable "custom locale set up" text

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1897]
![FireShot Capture 689 - Ayarlar - PixelShop - http___localhost_pixelshop_panel_settings](https://user-images.githubusercontent.com/3393422/60598341-35df9f80-9db5-11e9-93be-501e7c5da3b5.png)

https://github.com/getkirby/kirby/blob/master/panel/src/components/Dialogs/LanguageUpdateDialog.vue#L32

> You are using a custom locale set up. Please modify it in the language file in /site/languages

When language locale set as array[] like below, above non-translated text shows:

```
return [
    'code' => 'tr',
    'default' => true,
    'direction' => 'ltr',
    'locale' => [
        LC_COLLATE  => 'tr_TR.utf-8',
        LC_MONETARY => 'tr_TR.utf-8',
        LC_NUMERIC  => 'tr_TR.utf-8',
        LC_TIME     => 'tr_TR.utf-8',
        // LC_MESSAGES => 'tr_TR.utf-8',
        LC_CTYPE    => 'en_US.utf-8'
    ],
    'name' => 'Türkçe',
    'translations' => [],
    'url' => NULL
];
```

**Comment by bastianallgeier** [comment]
✅
