### ISSUE TITLE
[Panel] CMD-L should not override browser's default behaviour

### ISSUE THREAD

**Issue by samnabi** [getkirby/kirby#1898]
**Describe the bug**
When focused in a `textarea` field, <key>CMD</key>+<key>L</key> activates the `Link` button. Kirby should use <key>CMD</key>+<key>K</key> for this purpose instead, and let the browser keep default behaviour of <key>CMD</key>+<key>L</key>.

<key>CMD</key>+<key>K</key> has been traditionally used for adding hyperlinks in email clients and WYSIWYG editors.

**To Reproduce**
Press <key>CMD</key>+<key>L</key> while inside a `textarea` field.

**Expected behavior**
Focus on the browser's address bar (default browser behaviour)

**Kirby Version**
3.2.0

**Comment by afbora** [comment]
Is this for MacOS? I cant reproduce on Windows 10 and Chrome browser with `CTRL + L`.
Btw i didn't work any shortcuts (Bold, Italic, etc). Is there a list of these shortcuts? I didn't see it in the documents.

**Comment by bastianallgeier** [comment]
✅
