### ISSUE TITLE
Title option for site blueprint doesn't work

### ISSUE THREAD

**Issue by sashtown** [getkirby/kirby#1899]
**Describe the bug**
The `title` option to overwrite the "Site" label in the main menu of the Panel as described [here](https://getkirby.com/docs/reference/panel/blueprints/site#title) is being ignored.

**To Reproduce**
Create `site.yml` with:
```yaml
title: Hohmpedsch
```

**Expected behavior**
"Site" label in the main menu should be overwritten with "Hohmpedsch".

**Kirby Version**
3.2.0

**Comment by distantnative** [comment]
✅
