### ISSUE TITLE
Content Lock crashes with virtual pages

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#1900]
![screenshot_2019-07-04_at_14 04 16](https://user-images.githubusercontent.com/3788865/60665630-48b1ad00-9e65-11e9-90d4-8b4796919edf.png)

**Comment by distantnative** [comment]
In case someone stumbles upon this before we have a fix:
You can deactivate content locking completely via this plugin  https://github.com/distantnative/passport/tree/master/site/plugins/tmp-lock

**Comment by bastianallgeier** [comment]
✅
