### ISSUE TITLE
widont() method wont insert space character when last word contains dash

### ISSUE THREAD

**Issue by scsskid** [getkirby/kirby#1902]
**Describe the bug**
`widont()` method wont insert space character when last word contains dash `-`

**To Reproduce**

1. insert `ihrem Fördergeschäft, sondern auch auf EU-Ebene` into a text field
2. echo in template with `$page->field()->kt()->widont()`

**Expected behavior**
should render 'ihrem Fördergeschäft, sondern auch auf&nbsp;EU-Ebene'

**Screenshots**

**Kirby Version**
3.1 

**Desktop (please complete the following information):**
 - macOS
 - Chrome

**Comment by bastianallgeier** [comment]
✅
