### ISSUE TITLE
URL slugs are not properly converted from Cyrillic

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1903]
**Describe the bug**
If I create a page with title `Нашата история`, the suggested slug is `n-sh-t-ist-rija`. The letters `a` and `o` are not properly converted.

**Expected behavior**
The suggested slug should be `nashata-istorija`.

**Kirby Version**
3.2.0

**Comment by texnixe** [comment]
Have you set the `slugs` option in your config? For me it works if I set

```
'slugs' => 'ru',
```
or
```
'slugs' => 'bg',
```

**Comment by yandodov** [comment]
Initialy, I didn't have it set, but after your comment, I added it and it still wouldn't work. I tried both `ru` and `bg`. Here's my full config:

```php
return [
  'debug' => true,
  'slugs' => 'ru',
  'languages' => true,
  'date.handler'  => 'strftime'
];
```

By the way, is `slugs` documented anywhere? I'm pretty sure I haven't seen it before.

**Comment by texnixe** [comment]
In a multi-language environment, you have to set the locale in your language files, not in the config.

Yes, `slugs` is [documented](https://getkirby.com/docs/reference/system/options/slugs), it's a new feature introduced in v3.2.0

https://getkirby.com/docs/guide/languages/slug-rules

**Comment by afbora** [comment]
@texnixe I have same issue. 

I didn't use `slug` and `slugs` option. It was working special turkish characters (_Ç,Ğ,İ,Ö,Ş,Ü_) except just `İ` letter. I added `slug` option but still `İ` not working.

Input Title: **İstanbul**
Output Slug: **i-stanbul**

```
return [
    'code' => 'tr',
    'default' => true,
    'direction' => 'ltr',
    'locale' => [
        LC_COLLATE  => 'tr_TR.utf-8',
        LC_MONETARY => 'tr_TR.utf-8',
        LC_NUMERIC  => 'tr_TR.utf-8',
        LC_TIME     => 'tr_TR.utf-8',
        LC_CTYPE    => 'en_US.utf-8'
    ],
    'name' => 'Türkçe',
    'translations' => [],
    'url' => '/',
    'slug' => 'tr',
    'slugs' => [
        'İ' => 'i'
    ]
];
```

And i tried with `Str::$language = []` but not working:

```
Str::$language = [
    '/Ç/' => 'C',
    '/ç/' => 'c',
    '/Ğ/' => 'G',
    '/ğ/' => 'g',
    '/İ/' => 'I',
    '/ı/' => 'i',
    '/Ö/' => 'O',
    '/œ|ö/' => 'o',
    '/ö/' => 'o',
    '/Ş/' => 'S',
    '/ş/' => 's',
    '/Ü/' => 'U',
    '/ü/' => 'u'
];
```

**Comment by texnixe** [comment]
Hm, I haven't tested with a multilang installation yet.
@afbora Your setup is not quite correct:

With no languages defined, your setup should look like this:

in config.php
```
return [
  'slugs' => 'de' // "slugs" not "slug"
];

Str::$language = [
  'ß' => 'sz' 
];
```

In a multilanguage Installation, e.g. `de.php`
```
<?php

return [
  'code' => 'de',
  'default' => false,
  'direction' => 'ltr',
  'locale' => 'de_DE',
  'name' => 'Deutsch',
  'slugs' => [
    'ß' => 'sz' 
  ]
];
```
I.e. no `slug` option, because the `code` property is used to determine the correct language file.

Apart from that, your `İ`character converted to `i` for the first letter, but then each additional one is preceded by a dash, which is strange.

**Comment by afbora** [comment]
@texnixe I checked and tried all actions your said as correctly but still not working.

All special characters works great except `İ`. 

New examples:

**Input**: İYİYİM
**Output**: i-yi-yi-m

**Input**: İyiyim
**Output**: i-yiyim

**Input**: Ben İyiyim
**Output**: ben-i-yiyim

**Comment by texnixe** [comment]
@afbora Yes, that's what I meant, it converts the special character alright, but at the same time inserts a dash. I got the same result. That's definitely not correct.

**Comment by afbora** [comment]
@texnixe Yes, you right. In fact, convert is success. But adding dash unknown reason.

Which source does Panel use for create slug, `Kirby\Toolkit\Str`?

---

I did a few tests:

https://github.com/getkirby/kirby/blob/master/src/Toolkit/Str.php#L84-L85

I removed lines (84,85) in `ü` letter, convert failed as `s-per` for `Süper`. OK!

https://github.com/getkirby/kirby/blob/master/src/Toolkit/Str.php#L62-L63

Then i removed above lines (62,63) in `İ` letter but convert still continue as `i-stanbul` for `İstanbul`. Why?

So as if panel using another convert library for `İ` 🤔

**Comment by afbora** [comment]
@texnixe @distantnative 

I traced to slug action and found the line that made the incorrect slug convert: `slug.js#L25`

https://github.com/getkirby/kirby/blob/master/panel/src/helpers/slug.js#L25

Then I have tested with rendered javascript on JSFiddle and you can see the issue on line 20:

https://jsfiddle.net/byybora/a6q8sbgz/18/

You'll see properly works when you remove the line.

**Comment by distantnative** [comment]
Ok, I got the first part down:
@hdodov those letters were actually missing from our ASCII conversion table

**Comment by distantnative** [comment]
And @afbora:
The string gets first converted to lowercase, so we are left with `i̇` which also has not been included in our conversion table. Here my problem is, I try to add it but it's still not matched :/

**Comment by afbora** [comment]
@distantnative  `i` is already a normal letter, why are we trying to convert again?

**Comment by distantnative** [comment]
Look closer, the one that I wrote isn't a normal `i` but `i̇`.

**Comment by afbora** [comment]
@distantnative Ohh really, it was different 🤔  

But works for me like append:

`'/ì|í|î|ï|ĩ|ī|ĭ|ǐ|į|ı|и|i̇/' => 'i',`

Last `i̇` after `и`

**Comment by distantnative** [comment]
It does not for me... maybe I have to try a different editor 😱

**Comment by afbora** [comment]
@distantnative You right! With PHPStorm worked, Notepad++ failed.

**Comment by distantnative** [comment]
That happens if I enter that character via TextEdit:
<img width="304" alt="Screen Shot 2019-08-01 at 15 14 37" src="https://user-images.githubusercontent.com/3788865/62296322-1ea4d800-b46f-11e9-8777-69373c4ac027.png">

I think we might have stumbled upon a hybrid character...

**Comment by afbora** [comment]
I have tested again following IDEs and anyone failed:

- **PHPStorm**: Works
- **Notepad++:** Works
- **Atom**: Works
- **Android Studio:** Works
- **Notepad2**: Works
- **Visual Studio**: Works

**Comment by distantnative** [comment]
@afbora But you don't get the weird behavior I posted when inserting it with these editors?

**Comment by afbora** [comment]
@distantnative Absolutely yes, looks like this in Notepad++

![Untitled-1](https://user-images.githubusercontent.com/3393422/62363193-7737ac00-b527-11e9-82c9-71fdccb85c1b.png)

**Comment by distantnative** [comment]
I think I spotted a stupid mistake on my side. When adding the weird i in text edit, I also added a `|` by mistake. Let's see if it works now all.

**Comment by distantnative** [comment]
Positive, thanks for the help, @afbora!

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
@distantnative This issue still continue on 3.2.4 RC.1

**Input**: İstanbul
**Output**: i-stanbul

I found the breaking commit: https://github.com/getkirby/kirby/commit/ee16a531c773f7e9e8fb5f62a396df00f51ae14a
It works when I undo this update.

**Comment by afbora** [comment]
There's another problem on multilangual website:

**en.php**

```
return [
    'code' => 'en',
    'default' => true,
    'direction' => 'ltr',
    'locale' => [
        'en_US'
    ],
    'name' => 'English',
    'translations' => [],
    'url' => NULL
];
```

**tr.php**

```
return [
    'code' => 'tr',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'tr_TR'
    ],
    'name' => 'Türkçe',
    'translations' => [],
    'url' => NULL
];
```

When i switch to Turkish language on Panel, slugs doesnt respect to language locale (tr_TR).

**Input**: Üsküdar
**Output**: sk-dar

If I were using single language as Turkish, the output would be `uskudar`.

**Comment by distantnative** [comment]
Hmm but we need that escpae since without it other characters break the Panel (I think e.g. `+`)

**Comment by afbora** [comment]
I understand your concern, but I couldn't understand how this error would occur with the escape method. Do you have an idea?

---

https://github.com/getkirby/kirby/blob/ee16a531c773f7e9e8fb5f62a396df00f51ae14a/panel/src/helpers/slug.js#L28

I tracked this down.
Before the 28. line, `İs` converted to `ìs`
On 28.line, `is` converted to `i-s`

I have tested following inputs:

**With locale config**:

```
return [
    'locale' => 'tr_TR'
];
```

Failed
**Input**: Üsküdar
**Output**: sk-dar

Failed
**Input**: İstanbul
**Output**: i-stanbul

**With slugs config**

```
return [
    'slugs' => 'tr',
    'locale' => 'tr_TR'
];
```

Success
**Input**: Üsküdar
**Output**: uskudar

Failed
**Input**: İstanbul
**Output**: i-stanbul

When i rollback this update, works with only `locale` config like following (no need slugs config)

Success
**Input**: Üsküdar
**Output**: uskudar

Success
**Input**: İstanbul
**Output**: istanbul

**Comment by afbora** [comment]
We've added this commit to 3.2.4, but now this commit not working properly 🤔

**Comment by bastianallgeier** [comment]
@afbora I think it got reopened during the RC and I missed to remove it from the changelog.

**Comment by afbora** [comment]
I wonder why we're escaping `regex` characters? `RegExp.escape(regex)`

https://github.com/getkirby/kirby/blob/ee16a531c773f7e9e8fb5f62a396df00f51ae14a/panel/src/helpers/slug.js#L13-L16

We already limit a few lines below only to the allowed characters: 
https://github.com/getkirby/kirby/blob/ee16a531c773f7e9e8fb5f62a396df00f51ae14a/panel/src/helpers/slug.js#L25

I could not find an alternative solution 😞

**Comment by distantnative** [comment]
@afbora I added this as characters like `+` caused problems... but mazbe I was mistaken.

**Comment by afbora** [comment]
I don't know what problem it's causing. 
We only use these characters to match and replace them, right?

**Comment by lukasbestle** [comment]
My build setup is currently broken, but I have an idea: What if we provide the `u` flag (for Unicode support) in line 16:

```js
string = string.replace(new RegExp(RegExp.escape(regex), "gu"), ruleset[rule]);
```

Does that change anything?

**Comment by afbora** [comment]
@lukasbestle Doesn't work for me :(

**Comment by afbora** [comment]
@distantnative I guess found the solution 🎉 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes

We need use `\p` start of escape pattern, like that:

````js
RegExp.escape = s => s.replace(/\p[-/\\^$*+?.()|[\]{}]/g, '\\$&');
````

Can you test it, please?

---

**Test Online JSFiddle**:
https://jsfiddle.net/byybora/52s9zfjw/51/

**Input**: üsküdar
**Expected**: uskudar

**Comment by afbora** [comment]
Glad to see that fixed on 3.2.5 🔥

**Comment by bastianallgeier** [comment]
@afbora I just created a PR for it. https://github.com/getkirby/kirby/pull/2112

**Comment by afbora** [comment]
@bastianallgeier Thank you so much 🎉 

I'm sure you tested it, but we're sure it won't cause another problem, right? 🤔

**Comment by bastianallgeier** [comment]
@afbora I tested it briefly, but we don't have unit tests for it for the frontend to make sure it works for all the other cases. We need to fix this during the RC phase.

**Comment by bastianallgeier** [comment]
✅

**Comment by illycz** [comment]
I also have problem within cyrillic.
When I'm using string `Компания` as a Page title, the slug is `kompaniya` but when I'm using slug methon in blueprint like this: `{{ arrayItem.value.slug }}` I'm getting `kompanija`.

And when I'm using `Str::slug()` in template, I'm getting `kompaniya`.
So there is two results.

Where is the problem?

Thanks

**Comment by afbora** [comment]
@illycz Which version do you use?

**Comment by illycz** [comment]
@afbora 3.2.5

**Comment by illycz** [comment]
@afbora the problem is multilingual setup. I'm getting `kompaniya` on RU pages and `kompanija` on others. Do you know how to solve it that results are consistent throu languages?

Thanks

**Comment by afbora** [comment]
Hmm i guess found the issue.

Str class converting `я` to `ja`
https://github.com/getkirby/kirby/blob/master/src/Toolkit/Str.php#L102-L103

i18n RU slug rules converting `я` to `ya`
https://github.com/getkirby/kirby/blob/master/i18n/rules/ru.json#L50

@illycz Which is right? `ja` or `ya`?

@bastianallgeier will help about this issue.

**Comment by illycz** [comment]
@afbora thanks for your investigative work :) I don't know which version is right because I'm not Russian...

**Comment by illycz** [comment]
@afbora wiki says `ya`: https://en.wikipedia.org/wiki/Ya_(Cyrillic)

**Comment by distantnative** [comment]
Ya for Russian, ja for all other Cyrillic based languages as it seems. So our current implementation might be correct.

**Comment by distantnative** [comment]
See https://en.wiktionary.org/wiki/%D1%8F

**Comment by illycz** [comment]
@distantnative Yes, looks correct. But it's problematic when I create slug value in panel (for multiselect field) and generate related param in template. I asked also in forum: https://forum.getkirby.com/t/different-values-slug-method/15925

**Comment by distantnative** [comment]
I haven’t really been able to wrap my head around it but isn’t it working that you get the ya when you are in your russian translation  and ja when you are in your other translations?

Maybe you need to explain it bit more what you are trying to do where language-specific slugs are not working.

**Comment by illycz** [comment]
I define group of tags from which users select in article. Slug generated in panel is different from slug which I generate for filter in template. Is this explanation enough? I'm bad in english :)

**Comment by distantnative** [comment]
Just saw the forum link: if you create urls from it, are you translating that field or are you using `translate: false`? I would assume the tags are all the same independent of translation language of the page.

**Comment by illycz** [comment]
No, tags are translated too. And reasigned in each article

**Comment by illycz** [comment]
If the `я` is the only one problematic letter I can remapped it to ja in language option. This would be good enough for me. But it's strange that slug for page generate different value than for panel field...

**Comment by distantnative** [comment]
As for as I understand you are calling the slug method in the context of different languages. So it’s not really weird, different language translate special characters differently to ascii. I am thinking you would need to pin the slug generation to one language in all situations to avoid this problem for you. I don’t think we offer that feature, let me check.

**Comment by illycz** [comment]
There is `slugs` option but I think that this is not working in multilingual setup.

**Comment by distantnative** [comment]
I would have to test this myself. Could you provide your blueprints (for the page of the multi select as well as the new page) as well as your front end code (Templates and controllers if used) as well as your language setup?

**Comment by illycz** [comment]
Field for defining tags for articles:
```
tags:
  label: All categories
  type: tags
  required: true
```

Filed for select tag in article:
```
tags:
  label: Category
  type: multiselect
  options: query
  query:
    fetch: site.find("news").tags.split
    text: "{{ arrayItem.value }}"
    value: "{{ arrayItem.value.slug }}"
```

controller (I need to translate also ):
```
<?php

return function($page) {

    // fetch all tags
    $tags = $page->children()->listed()->pluck('tags', ',', true);

    // fetch the basic set of pages
    $articles = $page->children()->listed()->flip();

    // add the tag filter
    if($tag = param('tag')) {
        $articles = $articles->filterBy('tags', $tag, ',');
    }

    // apply pagination
    $articles   = $articles->paginate(12);
    $pagination = $articles->pagination();

    return compact('articles', 'tags', 'tag', 'pagination');

};
```

template for tags filter:
```
<?php foreach($page->tags()->split(',') as $tag): ?>
    <?php if($page->children()->listed()->filterBy('tags', Str::slug($tag), ',')->count() > 0): ?>
        <li class="-mb-1 mx-15">
            <?php if($tag == kirby()->request()->params()->tag()): ?>
                class="inline-block pb-10 border-b border-blue-light"><?= html($tag) ?></span>
            <?php else: ?>
                <a class="inline-block pb-10 border-b border-transparent text-blue-light" href="<?= url($page->url(), ['params' => ['tag' => Str::slug($tag)]]) ?>"><?= html($tag) ?></a>
            <?php endif ?>
        </li>
    <?php endif ?>
<?php endforeach ?>
```

language setup:
only `'languages' => true` in config and basic:
```
'code' => 'ru',
'default' => false,
'direction' => 'ltr',
'locale' => 'ru_RU',
'name' => 'Русский',
```

Is it enough for you?

**Comment by distantnative** [comment]
What other languages do you have set up?

**Comment by illycz** [comment]
Default is EN and others are: DE, RU, ES, CS and CN

**Comment by afbora** [comment]
@distantnative Did you get a chance to look?

**Comment by distantnative** [comment]
I haven't figured it out so far :/

**Comment by afbora** [comment]
@illycz I have tested like your setup.

For `Компания` input and all success

1. `Str::slug('Компания')` output is `kompanija` on frontend for default and other languages 
2. Create page dialog slug output `kompanija` for default and other languages
3. Edit page slug on RU language output `kompaniya` and others `kompanija` as successfull
4. Tags select multiselect field output is `Компания (kompanija)` for default and other languages

If there's nothing I've missed, I haven't found a bug/issue so far 🤔

**Comment by illycz** [comment]
@afbora the problem is when tag slug (in multiselect) is generated like `kompanija` and on template the filter param is in RU languge generate as `kompaniya`. So when I check which posts list by compare tag slug and param in URL, the string is not same... Sorry for my english.

**Comment by illycz** [comment]
> Str::slug('Компания') output is kompanija on frontend for default and other languages

1. `Str::slug('Компания')` in RU language is generated as `kompaniya `.

**Comment by illycz** [comment]
I don't say that this is bug. I only need solution how to use tags in multilingual setup. That's all

**Comment by texnixe** [comment]
Why do you have to store the sluggified value, why not the original string? Then you would avoid this problem completely, I think. And if you translate those slugs in different languages, the problem shouldn't arise in the first place?

**Comment by illycz** [comment]
> Why do you have to store the sluggified value, why not the original string? Then you would avoid this problem completely, I think.

Can you be more specific, I do not insist on a solution within `Str::slug()`.

Thanks a lot

**Comment by texnixe** [comment]
What I meant is that you use `  value: "{{ arrayItem.value.slug }}"` to store a slug of the string instead of the string itself. Why?

**Comment by illycz** [comment]
because I didn't know how to do it differently :)

**Comment by afbora** [comment]
> 1. `Str::slug('Компания')` in RU language is generated as `kompaniya `.


```
var_dump($kirby->language()->locale());
array(1) {
  [0]=>
  string(5) "ru_RU"
}

echo Str::slug("Компания")
kompanija
```

Not for me.

**Comment by illycz** [comment]
@afbora Which Kirby version?

**Comment by afbora** [comment]
@illycz 3.2.5 Stable

![FireShot Capture 778 - Settings - Mægazine - http___localhost_test_kirby_1903_panel_settings](https://user-images.githubusercontent.com/3393422/66833142-eee07900-ef63-11e9-9c21-48975dc5566d.png)

**Comment by texnixe** [comment]
I also get the same result as @afbora, btw.

**Comment by distantnative** [comment]
> Why do you have to store the sluggified value, why not the original string? Then you would avoid this problem completely, I think. And if you translate those slugs in different languages, the problem shouldn't arise in the first place?

I think @texnixe has it right here.  Try using:

```
tags:
  label: Category
  type: multiselect
  options: query
  query:
    fetch: site.find("news").tags.split
    text: "{{ arrayItem.value }}"
    value: "{{ arrayItem.value }}"
```

**Comment by texnixe** [comment]
I already suggested it [here](https://forum.getkirby.com/t/different-values-slug-method/15925/2?u=texnixe) and then to `urlencode()` and `urldecode()` the tags.

**Comment by illycz** [comment]
> I also get the same result as @afbora, btw.

Strange
`Str::slug("Компания")` returns `kompanija`
`url($page->url(), ['params' => ['tag' => Str::slug($tag)]])` returns `.../tag:kompaniya-sobytiya`

> I already suggested it here and then to urlencode() and urldecode() the tags.

Calmly yes, but I don't know how to rewrite this filter in controller:
```
if($tag = param('tag')) {
    $articles = $articles->filterBy('tags', $tag, ',');
}
```

**Comment by texnixe** [comment]
```
if($tag = urldecode(param('tag'))) {
    $articles = $articles->filterBy('tags', $tag, ',');
}
```

And when you create your url, your `urlencode()` the tag.

```
url($page->url(), ['params' => ['tag' => urlencode($tag)]])
```

(Although that looks quite ugly, I must admit)

**Comment by illycz** [comment]
> (Although that looks quite ugly, I must admit)

But this URL don't work :(

`/ru/novosti/tag:Компания%2FСобытия` and I get

```
Not Found
The requested URL /ru/novosti/tag:ÐšÐ¾Ð¼Ð¿Ð°Ð½Ð¸Ñ/Ð¡Ð¾Ð±Ñ‹Ñ‚Ð¸Ñ was not found on this server.
```

**Comment by illycz** [comment]
@texnixe is it possible in blueprint use structure field value? When I create Tags multiselect from structure fields, where item have Name and Slug, this would solve my problem.

**Comment by distantnative** [comment]
@illycz yes you can: https://getkirby.com/docs/reference/panel/fields/multiselect#options-from-other-fields__options-from-structure-field

```
category:
  label: Category
  type: multiselect
  options: query
  query:
    fetch: site.contactoptions.toStructure
    text: "{{ structureItem.name }}"
    value: "{{ structureItem.twitter }}"
```

**Comment by illycz** [comment]
@distantnative great!

@texnixe @afbora I investigate about different output of `Str::slug("Компания")` and I get it!
It returns `kompanija` before first use of `t()`. Than returns `kompaniya`.

**Comment by illycz** [comment]
OK solved throu structure field where I define Name and Slug for Tags which is in Article generated as multiselect.

> @texnixe @afbora I investigate about different output of Str::slug("Компания") and I get it!
It returns kompanija before first use of t(). Than returns kompaniya.

But I think this is bug, don't you think?

Thanks to all!

**Comment by texnixe** [comment]
@illycz  Well, I can't reproduce your issue. Where are you using the `t()` helper with the slug? Maybe I'm missing something? Could you provide your project or a stripped down version of it for testing?

**Comment by illycz** [comment]
@texnixe Try output:

```
<?php
echo Str::slug("Компания");
echo t('something');
echo Str::slug("Компания");
?>
```

In RU language I get:
```
kompanija
translation of something
kompaniya
```

**Comment by distantnative** [comment]
I feel like the issue could be that the language rules only get added in the `I18n::$load` callback: https://github.com/getkirby/kirby/blob/master/src/Cms/AppTranslations.php#L41-L42

But don't know yet where better to do that.

**Comment by illycz** [comment]
I think that two parts are problematic:

1. Different output before and after `t()` function.
2. Different output from page slug and `Str::slug()`

**Comment by afbora** [comment]
@distantnative Should we take this bug and open it new issue?

**Comment by distantnative** [comment]
Probably the best, yes.
