### ISSUE TITLE
Call to a member function isAdmin() on null” when trying to install the Panel

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1909]
**Describe the bug**
When trying to install the first Panel user, after clicking on "Install", the above mentioned error message appears and it is not possible to install the first user.

**To Reproduce**
1. Download a fresh 3.2.1 Starterkit
2. Go to `yourdomain.com/panel`
3. Enter credentials for the first user
4. Click on "Install"
5. See error

It's caused in this line:

```
 if ($role === 'admin' && $user->kirby()->user()->isAdmin() === false) {
```
Should probably be
```
 if ($role === 'admin' && $user->isAdmin() === false) {
```

**Expected behavior**
The first user should be installed without error.

**Screenshots**

**Kirby Version**
3.2.1

**Console output**
```
code: 500

exception: "Error"

file: "/Users/sonja/public_html/321/kirby/src/Cms/UserRules.php"

line: 108

message: "Call to a member function isAdmin() on null"

route: "system/install"

status: "error"
```
**Desktop (please complete the following information):**
 -  macOS
 -  Safari

**Smartphone (please complete the following information):**

**Additional context**
Log in is possible after throwing in a user account from another project.

**Comment by GiantCrocodile** [comment]
Tried to reinstall my plainkit with v3.2.1 and got the same error.

Tested your fix and it worked in file `kirby/src/Cms/UserRules.php`.

**Comment by bastianallgeier** [comment]
I'm really sorry for this :( That's my fault. 
The fix looks a bit different though. I just created a new branch for it: https://github.com/getkirby/kirby/tree/release/3.2.2 

Please give it a try and let me know if this fixes it for you as well. 
We will launch it later today.

**Comment by GiantCrocodile** [comment]
I replaced the lines with the new code from the branch and deleted my previously created user. After accessing the panel again, I was successfully able to create a new user. Seems to work!

**Comment by bastianallgeier** [comment]
✅
