### ISSUE TITLE
cache weirdness

### ISSUE THREAD

**Issue by puleddu** [getkirby/kirby#191]
When the cache is activated, the pagination in the blog does not work for me.

Kirby simply serves the first page even if I click on the 'Previous' link (and the URL actually changes, giving the impression that we are changing page).

**Comment by bastianallgeier** [comment]
This should be fixed in 2.0.6 Which version do you currently use? You can find it in kirby/kirby.php

**Comment by puleddu** [comment]
You are right, I was using 2.0.5 – Thanks.
