### ISSUE TITLE
[Panel] Unable to edit account

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1910]
I got this error on `/panel/account` and when any input on type throw console error and reset form.

I tried to edit any users and myself, no errors. I only see that page.

**To Reproduce**
1. Normal installation
2. Click on "Your account" and go to `/panel/account`

**Screenshots**

![issue](https://user-images.githubusercontent.com/3393422/60964825-0385f300-a31d-11e9-98c8-a02beefe4a7c.jpg)

![issue2](https://user-images.githubusercontent.com/3393422/60965704-244f4800-a31f-11e9-8096-e2453ba5514d.jpg)

**Kirby Version**
3.2.0, 3.2.1, 3.2.2

**Console output**
> {status: "error", route: "(.*)/lock", exception: "Kirby\Exception\InvalidArgumentException", message: "Invalid file model type", key: "error.invalidArgument", …}

**Desktop**
 - Windows 10 
 - Chrome 75.0.3770.100

**Comment by GiantCrocodile** [comment]
Yep, I have to agree: I got one or two different places where locking fails with errors but I didn't find out what causes these errors. They don't occur all time. It was related to accounts and to pages.

**Comment by afbora** [comment]
This is about following lines:
https://github.com/getkirby/kirby/blob/release/3.2.2/src/Cms/Api.php#L121-L123

No `account` models.

**Comment by bastianallgeier** [comment]
I just fixed this and added unit tests for the method. Will be in 3.2.2 in a couple minutes.
