### ISSUE TITLE
[Panel] Setting file template

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1915]
**Describe the bug**
It's not possible to set the template of a file in the panel.

**To Reproduce**
Upload a file in a section without template restrictions.

**Expected behavior**
1. There should be a setting in the file settings menu to change the template.
2. There should be an `upload` settings for files sections to set the default template or – alternatively – there should be a pop-up similar to the one for page after selecting files that lets the user select the template.

**Kirby Version**
All Kirby version.

**Notes**
I'm posting this as a bug and not as an idea deliberately because I consider this a serious workflow issue because it can result in "lost" (hidden or unselectable) files depending on the general panel and frontend setup. This can be very hard to debug when client encounter this issue ("I uploaded a file, but it's not showing up …").

**Comment by texnixe** [comment]
I think this is a bit tricky. Depending on its settings, a file template cannot just be assigned wildly to any file. What's the use of having a template that restricts uploading of files to certain types when you then assign it to any type of file?

**Comment by nilshoerrmann** [comment]
Maybe a usecase helps understanding our issue because I agree that "assigning files to any type" doesn't make sense. But in our case we have a specific set of templates but are not able to apply them correctly:

The files we are dealing with are images only. We are using different templates to specify the area of application, like cover image, gallery image, profile image and the like. We are _not_ using it to separate different media types like PDF and video files. Our site uses a modular setup where multiple pages store their file assets in another page called `contents` – the setup is similar to what Thomas describes in this article: https://medium.com/@medienbaecker/kreatives-unternehmertum-website-relaunch-with-kirby-3-c15579ba2e5. The different pages either use file fields or sections and assign their templates correctly. But we also display a kind of "show all" section on the `contents` page to give the authors an overview of the available media files and also to offer a place to upload a bunch of files for later use across the associated pages. Because this section has no file template specified (you can specify a single one but not multiple), all newly uploaded files will have no template at all. And this is where the problem starts: the files are not shown in other areas of the panel where correct template filtering is applied to the file sections. And, furthermore, there is no method inside the panel to fix the missing template associations.

![Bildschirmfoto am 2019-07-16 um 09 45 56-fullpage](https://user-images.githubusercontent.com/25466/61275961-5c3b0d00-a7af-11e9-8ff1-027f75134e7a.png)

**Comment by distantnative** [comment]
Trying to spark some progress here again - it needs good ideas for sure…

How about:
- you can set multiple templates for upload in files sections 
- if more than one template for upload is set, the upload dialog shows a select for each file with those templates as options
- to prevent orphan files (without templates), on upload the first template is already assigned, written to content file and pre-selected in select field
- if any other template is selected for a file and the upload dialog closed/saved, that new template gets applied

I couldn't think of any way for changing the template in the file view. It's hard to know what templates to show for selection then.

**Comment by lukasbestle** [comment]
I wonder if this is truly necessary. The alternative would be to disable file uploads in the general media section using `max: 0` (so that this section becomes read-only). This way the user can never accidentally upload files without template.

Advantages:
- Already possible with our current options
- Better UX for the user as it's easy to memorize to always upload files directly to the section where they belong.

**Comment by distantnative** [comment]
@lukasbestle Long time, I know, but revisiting this I do agree with you.

It's a design question of how Kirby handles file templates. My suggestion on file upload doesn't seem to work great - a "Change template" option would be difficult as it would expose a way for users to mess up many systems (choosing a template that is actually not intended/supported in the blueprint context). So most developers would probably want to disable it again right away.

I don't see a way forward that truly improves the situation - only ones that fix one aspect by introducing other problems. I'm leaning towards closing this as "not to be solved in v3".

**Comment by lukasbestle** [comment]
I agree TBH. What do you think @nilshoerrmann? Is the idea to use `max: 0` in the general media section an alternative for your use case?

**Comment by nilshoerrmann** [comment]
No, it‘s essentially the section where you would drop everything in.

Similar to the pages section, I would have expected the files section to have a list of allowed templates (it‘s a single template right now if I remember correctly). So on upload a dialog could ask the user to select from this list of templates.

**Comment by distantnative** [comment]
@nilshoerrmann if you use one main section to upload all files and just others to show (and semi-choose what goes where), why don't you use a section to upload and then files fields for the placements?

**Comment by nilshoerrmann** [comment]
It was a multilingual setup which complicated things. It made a lot of sense to do it the way we did – but I‘d have to dig into my old notes to give you any further details as I cannot recall everything from memory right now. But I agree that this is not a usual setup.

But besides conceptual problems at our end, the issue is that Kirby allows for the creation of template-less files without offering a way to change this. And this becomes problematic because the system usually expects a template association. So the users might run in a dead end where they uploaded a file but cannot access it inside other fields or sections. We could solve this for us because we had file system access – an option an normal editor does not have.

**Comment by nilshoerrmann** [comment]
@distantnative & @lukasbestle:

I thought about this a bit more and this is a very specific issue that you might just close for now. 

I'd take this report as a starting point for the further long term development of sections and section items, bringing sections to the next level. Looking at this issue again, for me there are two main points of interest:

1. **Sections:** All section types should have the same feature set. This would make sections easier for developers to use, it also would make the panel more resilient to complex use cases especially on content-heavy sites. E. g. pages sections have an `templates` property (plural) while files sections have a `template` propery (singular). There is no reason to limit the later this way but it requires a dialog to select the template as soon as multiple templates are defined. I understand the added complexity – still it should be a valid use case in a versatile system.
2. **Section items:** Actions on section types should be bidirectional. E. g. in this case, the files section allows the user to apply a file template (none in our case, but technically that's also a choice). But currently there is no way to change this later on which might especially be needed during site development when content is created first time. So if a section gives the options to apply something to an item, the item itself should offer options to change this as well. Preventing some actions should be in the hand of the developer in my eyes, using permissions (via the blueprint options for example).

Both of these two points are nothing for short term releases, both points might also be controversial. So I think we are more in the category of feature requests.

**Comment by nilshoerrmann** [comment]
PS: Regarding a template selection dialog, this could also be interesting for pages sections in the case of the reintroduction of drag and drop between sections that we had in early Kirby 3 alpha version. I also know about the hurdles of drag and drop but still it's a thing that would really elevate the use cases and usability of sections. But it's another reason to think of this as a long term enhancement.

**Comment by bvdputte** [comment]
For a general "files" section I resorted to using Sonja's [filedisplay section](https://github.com/texnixe/k3-filesdisplay-section) plugin. You can't upload files here, but you can display them etc.

I have also came across the fact that I needed to add templates to files that were not there because during dev I had hand-dropped them into the folders via Finder. It's really annoying if you forget to add a template afterwards and the editor can't work with the file as foreseen. 
Maybe having the option to add a template to file if it has none yet (via the panel) could be a thing?

**Comment by lukasbestle** [comment]
Thanks for the explanation and for your suggestions. Could you please add them to https://feedback.getkirby.com? We can't promise an implementation at this point, but at least we won't forget about them that way.

**Comment by distantnative** [comment]
Will be in v4
