### ISSUE TITLE
<k-dialog> overflow problem with date field

### ISSUE THREAD

**Issue by steirico** [getkirby/kirby#1918]
**Describe the bug**

While composing a custom dialog using `<k-dialog>` I face the fact that the bottom part of the date field's calendar widget is hidden behind the dialog's buttons:

![Jul-13-2019 18-41-50](https://user-images.githubusercontent.com/10421363/61186851-6bfd0900-a66a-11e9-860f-076a539f56d9.gif)

I would have expected it to be on top of the dialog, not inside and cut off by the bottom of the dialog.

Overriding the css class `k-dialog-body` as follow solved the issue in my case:
```css
.k-dialog-body {
  overflow: visible;
}
```
Not sure about any side effects or regressions (e.g. https://github.com/getkirby/kirby/issues/1126) and if the panel should be changed accordingly. 

**Kirby Version**
 3.1.3 and 3.2.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: latests chrome, firefox and safari

**Comment by bastianallgeier** [comment]
This is not as simple as it seems. The scrolling container needs to have overflow hidden to make sure that long links etc. don't break the container. I'm not exactly sure how to fix this without regressions. For now it's usable as it is. It's just not perfect.

**Comment by bastianallgeier** [comment]
We are really sorry that we didn't manage to solve this issue for such a long time. Unfortunately, we currently don't see a possible solution and will close this issue for now. Please create a new issue if this is still an urgent problem that affects your work/projects.
