### ISSUE TITLE
[Panel] Change role dialog still has option to change role to admin for non-admin users

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1920]
**Describe the bug**
When as a non-admin user I try to change the role of another non-admin user, I'm still presented with an option to make this user an admin although that option should not pop up. 

I can't change the role to any of the roles presented, but that's another story.

**To Reproduce**
1. Log in as non-admin user
2. Click on change role to change the role of another non-admin user
3. The change role dialog still has the admin option

**Expected behavior**
The option to select the Admin role should not show in the dialog.

**Screenshots**

<img width="483" alt="Bildschirmfoto 2019-07-14 um 19 41 06" src="https://user-images.githubusercontent.com/5312492/61187232-7241b400-a66f-11e9-8f32-3079167161de.png">

**Kirby Version**
3.2.2

**Additional context**

Somehow related: https://github.com/getkirby/kirby/issues/1917

Different story, but also related to user permissions:  https://github.com/getkirby/kirby/issues/1919

**Comment by moritzebeling** [comment]
> **Expected behavior**
> The option to select the Admin role should not show in the dialog.

Or be inactive/grey

**Comment by bastianallgeier** [comment]
✅
