### ISSUE TITLE
Unable to login on the panel from China

### ISSUE THREAD

**Issue by WalterRobin** [getkirby/kirby#1921]
**Bug**
The website has been made for a Chinese designer but she's unable to login in the back office. She can sucessfully access the panel page, she enters her login and password then connection fails. I've been able to login to the back office from my computer in France / United Kingdom. It sounds like this is an issue liked to the fact that the person connecting is in China (even by bypassing it with a VPN).

**Screenshots**
<img width="1245" alt="WechatIMG25" src="https://user-images.githubusercontent.com/30924717/61206946-21c06a00-a6f4-11e9-9154-0d5b6513b7b8.png">

** Kirby Version**
Kirby 3.0.0

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome, safari, firefox]

**Comment by afbora** [comment]
![ss](https://user-images.githubusercontent.com/3393422/61213281-44ab4800-a70d-11e9-8de6-7256673d7a10.jpg)

When you said can't login even with VPN, I wanted to try it
And I have tested with VPN/China on Kirby 3.0.0 and 3.2.2 as last version in my live server. 
I logged the panel successfully and cant reproduce this issue.

**Comment by WalterRobin** [comment]
Thank you for testing it out! I will once again empty the session cookies to reset the CSRF token.
