### ISSUE TITLE
[Panel] UX: Better checkbox for file select (especially when only one file is allowed)

### ISSUE THREAD

**Issue by thathoff** [getkirby/kirby#1922]
When there’s a files field and there is only one file allowed then checkbox icons in the file list look a lot like radio boxes. I often noticed that people try to select another image and wonder that nothing happens before they realise they need to first deselect the previously selected file and then select the new one.

<img width="480" alt="Screenshot 2019-07-15 at 15 01 52" src="https://user-images.githubusercontent.com/797760/61218342-1c721800-a712-11e9-8a1d-c03b9e5babbe.png">

Maybe a style which looks more like a checkbox would solve the problem.

<img width="479" alt="Screenshot 2019-07-15 at 15 06 09" src="https://user-images.githubusercontent.com/797760/61218348-2267f900-a712-11e9-9884-7a259a23337a.png">

Or a message should show up that i’ts only possible to select one file.

**Comment by distantnative** [comment]
I'd think that the visuals like radio buttons are correct for the case of max 1...
But clicking on another file, should probably switch the selection over to that one only.

**Comment by thathoff** [comment]
Yeah, that sounds like an even better solution… 👍

**Comment by bastianallgeier** [comment]
I think it's actually a bug that it doesn't switch to the other file.

**Comment by bastianallgeier** [comment]
✅
