### ISSUE TITLE
Duplicated page seems not properly indexed when page.duplicate:after hook is triggered

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1923]
**Describe the bug**
When duplicating a page through the panel, the newly created copy seems not to be added to the internal index. This causes problems in the page.duplicate:after hook.

```php
'page.duplicate:after' => function (Page $page) {
    // evaluates to null
    $this->site()->findPageOrDraft($page->id()); 

    // doesn't list $page and its subpages
    $this->site()->index(true)
}
```
**Expected behavior**
The new page should be indexed correctly before page.duplicate:after hook is triggered.

**Kirby Version**
3.2.2

**Comment by qwerdee** [comment]
I wanted to update the content of pages fields to change references to child pages to the duplicated child pages, e.g. `original/some-child` to `original-copy/some-child`. Currently that is not working in the page.duplicate:after hook and my guess is, that kirby prevents you from updating pages fields with ids that are not indexed(?)

**Comment by bastianallgeier** [comment]
✅
