### ISSUE TITLE
Photos uploaded via panel from iOS display with incorrect rotation on other platforms

### ISSUE THREAD

**Issue by Splendorr** [getkirby/kirby#1926]
**Describe the bug**
When I take a photo on my iPhone and upload it to Kirby via the "File" link in a panel textarea (inserting it directly into the textarea, to be displayed as KirbyText in a template), it will often have an incorrect rotation when displayed in a macOS browser such as Firefox or Safari.

**To Reproduce**
1. Take a photo with the iOS Camera app, particularly in landscape mode with the volume buttons facing up (though multiple orientations have shown this behavior).
2. Go to a Kirby panel on the iPhone, in mobile Safari.
2. Create a new Kirby page that includes a `textarea` field.
3. Tap to move the cursor into the `textarea` field.
4. Tap the paperclip "File" button above the `textarea`.
5. Tap "Upload a photo."
6. Select the photo from the picker and upload it.
7. Save the page and view it (list or unlisted doesn't seem to make a difference). Viewing it on the iPhone will show the photos in the expected rotation.
8. Now open the same page in Firefox on a desktop/laptop (I'm using macOS). The photo may be upside-down or sideways.
9. Go back to the panel on your desktop and click the photo in the Files list. The orientation problem is also visible here.
10. However, if you then click the file preview to open the file directly in the browser, it seems to rotate correctly.

**Expected behavior**
Expect to upload a photo and have its rotation correct everywhere.

**Screenshots**
You can look at an example post on my site [here](http://splendorr.com/posts/not-the-kind-of-person). The image is just displayed with an (image:) tag in the textarea, which is being rendered with `->kirbytext()` in the template. 

This is what it looks like in Safari on my iPhone:

![IMG_1916](https://user-images.githubusercontent.com/150489/61312813-2c97ff00-a7c7-11e9-9dc5-490b3902f09d.PNG)

While this is the same page in Firefox on macOS:

<img width="1440" alt="Screen Shot 2019-07-16 at 12 22 36 PM" src="https://user-images.githubusercontent.com/150489/61312895-57825300-a7c7-11e9-901f-0c1caf8d19e0.png">

Here's the page in the panel:

<img width="1368" alt="Screen Shot 2019-07-16 at 12 44 01 PM" src="https://user-images.githubusercontent.com/150489/61312943-6e28aa00-a7c7-11e9-97f5-d5a343de3c56.png">

Here's what I see when I click the top image in the files list:

<img width="1435" alt="Screen Shot 2019-07-16 at 12 26 13 PM" src="https://user-images.githubusercontent.com/150489/61312966-7a146c00-a7c7-11e9-9109-87d27c21c021.png">

But then the image displays right side up if I click the thumbnail to see the file itself:

<img width="1440" alt="Screen Shot 2019-07-16 at 12 26 26 PM" src="https://user-images.githubusercontent.com/150489/61312997-8b5d7880-a7c7-11e9-995d-03911b369d15.png">

**Kirby Version**
3.1.1

This is a pretty standard installation, I think; I started with the plainkit, and tried to add minimal things on the way. I don't have the site itself in a public repo at the moment, but I could share a private repo if that would be helpful.

**Console output**
Console isn't giving me any messages, either in the panel or on the page itself.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Firefox or Safari
 - Version: Firefox 67.0.4 (64-bit), Safari 12.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 12.3.1
 - Browser: Safari
 - Version: whichever one is installed with iOS 12.3.1

**Additional context**
Presumably this has something to do with EXIF data; I can find examples from recent years about iPhone photos relying on EXIF rotation data to display rather than actually rotating the images. I'm running Kirby on a DigitalOcean Droplet with Ubuntu 16.04.5 LTS, PHP 7.2, and the exif.so installed.

<img width="768" alt="Screen Shot 2019-07-16 at 12 38 02 PM" src="https://user-images.githubusercontent.com/150489/61312542-9d8ae700-a7c6-11e9-8cd2-538a571b4fe1.png">

<img width="792" alt="Screen Shot 2019-07-16 at 12 38 12 PM" src="https://user-images.githubusercontent.com/150489/61312549-a11e6e00-a7c6-11e9-8659-710d9db0447b.png">

Thanks for your help!

**Comment by lukasbestle** [comment]
Does this only occur when uploading images via the Panel or also when you manually place such a photo into the page directory?

We had the same problem with thumbs from iOS photos before (now fixed), but in your example the image is never modified (or should at least never be modified) by Kirby. So what Kirby does is to copy the file 1:1 to the `media` directory and serve it to the browser from there. Meaning: This is a browser bug that can't really be solved by Kirby.

What we *could* do is to rotate the image on upload if it comes from an iOS device, but I think that this is quite a hack.

@distantnative What do you think?

**Comment by distantnative** [comment]
Only could imagine that somewhere the meta information, which rotates it right, gets stripped... but no real clue how/where.

**Comment by lukasbestle** [comment]
I don't think so. I have found several posts about the issue on StackOverflow that are not about any CMS at all but just about the issue "iOS photo embedded in a web page is displayed rotated in some browsers". So it looks like some browsers ignore the EXIF metadata. To work around that, Kirby would need to rotate the pixel data on upload and simultaneously delete the EXIF rotation metadata, basically to "hardcode" the correct rotation into the image. But that means that uploaded images get modified by Kirby without any intervention by the dev, so I'm not sure about that.

**Comment by Splendorr** [comment]
Thanks for looking into this. Here's a bit more info:

@lukasbestle I just tested, and this occurs whether uploaded via the panel or placed directly into the directory and then adding to a textarea via the panel.

Here's a direct link to a photo that definitely exhibits this issue. It should be portrait, with the big yellow area in the bottom half. https://www.dropbox.com/s/chx51fuoc9eowqh/IMG_1711.JPG?dl=0

I see this in Chrome, Firefox, and Safari on my Mac.

Here's something: if I manually fetch the $page->images() and then apply the resize() function, the result is rotated properly!

```
<?php foreach($page->images() as $image): ?>
  <?php $image = $image->resize(1000); ?>
  <figure>
    <a href="<?= $image->url() ?>">
      <img src="<?= $image->url() ?>" alt="">
    </a>
  </figure>
<?php endforeach ?>
```

This is without applying resize():
<img width="742" alt="Screen Shot 2019-07-19 at 4 37 01 PM" src="https://user-images.githubusercontent.com/150489/61564085-9b818c00-aa43-11e9-930c-cd65657bcefd.png">

And this is with resize(1000):
<img width="794" alt="Screen Shot 2019-07-19 at 4 37 08 PM" src="https://user-images.githubusercontent.com/150489/61564098-a2100380-aa43-11e9-8c5b-482a5bdb5a80.png">

So... Kirby already has the mechanism built-in to fix this. Is there some way to easily invoke resize with the (image:) Kirby tag from a textarea, preferably to resize to the original size at 100% quality? Or to make the (image:) tag default to some resize() settings across the site? I haven't been able to find this in the docs yet.

**Comment by Splendorr** [comment]
I did another search for plugins now that I know more about what's happening, and [Kirby-Autoresize](https://github.com/medienbaecker/kirby-autoresize) uses a hook to resize images above a certain width on upload, using Kirby's thumb() method, which results in an image with the correct orientation.

I could use this for now to fix a majority of my issues, but it won't work if I upload a cropped image beneath the global threshold (defaults to 2000px wide, probably fine for most use cases). This also results in losing the original image quality; since I'm running my own server with plenty of storage, I'd rather keep the max resolution files in the page directory, and then generate a thumb to display to users to save bandwidth + ensure proper orientation.

So, my optimal solution still looks like applying resize() to uses of the (image:) Kirby tag, if that's possible?

**Comment by lukasbestle** [comment]
Thanks for the additional information.

> This also results in losing the original image quality; since I'm running my own server with plenty of storage, I'd rather keep the max resolution files in the page directory, and then generate a thumb to display to users to save bandwidth + ensure proper orientation.

That's what I think as well and is the reason why we probably shouldn't implement any "magic" in the Kirby core here. What we *could* do is just to rotate the image at the original dimensions (= no image data is lost), but that still recompresses the image and changes file metadata, which is not always desired.

Running the resize operation on output in the template is therefore indeed the best way.

What you could do is to [override the default `image` KirbyTag with your own implementation](https://getkirby.com/docs/reference/plugins/extensions/kirbytags#overriding-default-kirbytags) that runs thumb operations according to your needs in the template.

If you like, you can base your code on the [default implementation](https://github.com/getkirby/kirby/blob/3.2.2/config/tags.php#L79-L144) to get the features that are supported by default as well.

I'm closing this issue now as it's not something we can solve in the core.

**Comment by Splendorr** [comment]
Thanks, @lukasbestle! I'll try extending the default `image` tag!

**Comment by Splendorr** [comment]
Just in case this is helpful to someone else in the future, here's how I solved this for myself. 

My goals were:

1. Ensure that every image displayed to visitors gets re-encoded with `thumb()` and `'autoOrient' => true`, to make sure image orientation is fixed when delivered.
2. Save bandwidth by giving images a maximum width. In my site, the widest an image will reasonably be displayed is 1400px at 2x. Building in a little wiggle room, I set the default maxwidth to 2000px. Narrower images will be re-encoded at their original size.

I created a new plugin as described [here](https://getkirby.com/docs/reference/plugins/extensions/kirbytags#overriding-default-kirbytags) that overrides the normal `(image:)` kirbytag. I copied everything from the standard implementation. I added some config options for maxwidth and quality, as well as a maxwidth option that can be used in the tag itself, just in case I want to get picky.

```php
Kirby::plugin('splendorr/imagetag', [
  'options' => [
    'maxwidth' => 2000,
    'quality' => 90,
  ],
```

As in the standard tag, images with external src will just be displayed. However, if the image is a file saved in Kirby, I process the image with `$tag->file->thumb()` and pass in the options determined by a little conditional logic.

```php
'html' => function ($tag) {
        if ($tag->file = $tag->file($tag->value)) {
          $maxwidth = $tag->maxwidth ?? option('splendorr.imagetag.maxwidth');
          $thumb = $tag->file->thumb([
            'width' => $maxwidth,
            'autoOrient' => true,
            'quality'    => option('splendorr.imagetag.quality'),
          ]);
          $tag->src     = $thumb->url();
```

The rest of the tag code is the same as usual.

Here's the full code, just in case:

```php
Kirby::plugin('splendorr/imagetag', [
  'options' => [
    'maxwidth' => 2000,
    'quality' => 90,
  ],
  'tags' => [
    'image' => [
      'attr' => [
        'alt',
        'caption',
        'class',
        'height',
        'imgclass',
        'link',
        'linkclass',
        'maxwidth',
        'rel',
        'target',
        'text',
        'title',
        'width'
      ],
      'html' => function ($tag) {
        if ($tag->file = $tag->file($tag->value)) {
          $maxwidth = $tag->maxwidth ?? option('splendorr.imagetag.maxwidth');
          $thumb = $tag->file->thumb([
            'width' => $maxwidth,
            'autoOrient' => true,
            'quality'    => option('splendorr.imagetag.quality'),
          ]);
          $tag->src     = $thumb->url();
          $tag->alt     = $tag->alt     ?? $tag->file->alt()->or(' ')->value();
          $tag->title   = $tag->title   ?? $tag->file->title()->value();
          $tag->caption = $tag->caption ?? $tag->file->caption()->value();
        } else {
          $tag->src = Url::to($tag->value);
        }
        $link = function ($img) use ($tag) {
          if (empty($tag->link) === true) {
            return $img;
          }
          
          if ($link = $tag->file($tag->link)) {
            $link = $link->url();
          } else {
            $link = $tag->link === 'self' ? $tag->src : $tag->link;
          }
          return Html::a($link, [$img], [
            'rel'    => $tag->rel,
            'class'  => $tag->linkclass,
            'target' => $tag->target
          ]);
        };
        $image = Html::img($tag->src, [
          'width'  => $tag->width,
          'height' => $tag->height,
          'class'  => $tag->imgclass,
          'title'  => $tag->title,
          'alt'    => $tag->alt ?? ' '
        ]);
        if ($tag->kirby()->option('kirbytext.image.figure', true) === false) {
            return $link($image);
        }
        // render KirbyText in caption
        if ($tag->caption) {
          $tag->caption = [$tag->kirby()->kirbytext($tag->caption, [], true)];
        }
        return Html::figure([ $link($image) ], $tag->caption, [
          'class' => $tag->class
        ]);
      }
    ],
  ]
]);
```

Thanks again for your help! Y'all helped me figure out where to look to meet my needs. I could see this being useful to others, but I'm also not sure how to universalize it without adding complexity for people who don't need it. Some global options that default to false, which could enable this little code path to re-encode all images displayed with `(image:)`? Either way, it works for me. Cheers!

**Comment by Splendorr** [comment]
Annnnnd just because it's the first plugin I've made for Kirby, I created [a Github repo](https://github.com/Splendorr/kirby-splendorr-imagetag), too.

**Comment by lukasbestle** [comment]
Awesome, thanks for sharing!

A bit of feedback:

- The check whether the image size is smaller than the thumb width shouldn‘t be required as thumbs won‘t get upscaled by default (meaning: the resulting size is automatically limited to the input size).
- I know your plugin is more for your own use, but to make installation by other users more straightforward, take a look at our [Pluginkit docs](https://getkirby.com/docs/guide/plugins/plugin-setup-basic). It‘s not required at all, but maybe helpful for future plugins. :)

**Comment by Splendorr** [comment]
@lukasbestle Thanks! For the width argument to thumb(), you're saying if I call thumb() with width 2000 on an image that's only 1000px wide, it will still get processed, but output at 1000px? That makes sense, and would simplify the code path. I'll try it out.

And I'll look at the Pluginkit docs! I copied another plugin's files, but it looks like they didn't follow the guidelines, either.

**Comment by Splendorr** [comment]
@lukasbestle I tested and see that I didn't need that if statement! I also brought my repo into alignment with the Pluginkit docs. I'm not going to submit it to Packagist or the official Kirby plugin repo since it's such a specific use case without an obvious selling point, but now I know how to do it. Thanks again!
