### ISSUE TITLE
Panel Plugin updated from Webpack to Parcel does not load anymore

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1927]
**Describe the bug**
A clear and concise description of what the bug is. Parcel does not add a `!` at the beginning of `index.js` which seems to be the problem.

[janitor plugin issue](https://github.com/bnomei/kirby3-janitor/issues/9)

**To Reproduce**
1. install janitor plugin 1.3.0 for webpack build. works.
2. upgrade janitor to 1.4.0 for parcel build. stops working.

**Expected behavior**
not break even if `1` is missing.

**Slack dicussion**
https://getkirby.slack.com/archives/C2UTAQAN4/p1563462205279000

**Comment by rasteiner** [comment]
related? https://github.com/getkirby/ideas/issues/135

**Comment by bastianallgeier** [comment]
✅ The bundler now takes care of it.
