### ISSUE TITLE
PHP 7.2 - Declaration error

### ISSUE THREAD

**Issue by abroess** [getkirby/kirby#193]
Fatal error: Declaration of Kirby\Cms\PageStore::id() must be compatible with Kirby\Cms\PageStoreDefault::id(): string in /kirby/src/Cms/PageStore.php on line 10

Sorry for bugging you again :)

**Comment by bastianallgeier** [comment]
I'm actually very happy about you bugging us! I will finally setup Travis CI for the two repositories, so we can avoid such simple issues.

**Comment by bastianallgeier** [comment]
Should be fixed now.
