### ISSUE TITLE
[Panel] Structure field columns property with illegal value should throw a more informative error

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/kirby#1930]
I had a structure with 
```
columns:
  title:
    width: 1
```
... that prior to 3.2.2 (I think) did not throw an error, but now shows `t.split is not a function` in the panel. Something the likes of 'Illegal value for columns property' instead would have saved me some time :-)

**Comment by distantnative** [comment]
Does this still appear in 3.2.4?
Or was it maybe related to the same plugin bug mentioned in https://github.com/getkirby/kirby/issues/2045?

**Comment by philipmarnef** [comment]
@distantnative  Went back to check.
- It's not related to #2045, the K3 site where the bug occurred doesn't have the markdown-field plugin installed
- just updated to 3.2.4 and it's stil there. If the `width` is set to `1/1` all is fine, if I set it to `1` and the structure field shows the `t.split` error

**Comment by distantnative** [comment]
✅
