### ISSUE TITLE
[Plugins] Add separating semicolon when bundling plugins' index.js

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1931]
given the 2 following plugins:

first:
```js
panel.plugin('bla/blah', {
  //stuff
})
```

second (immediately invoked function expression - result of a build step)
```js
(function() {
  panel.plugin('foo/bar', {
    //stuff
  })
)()
```

both are valid plugins when installed alone. 

When installed together, they become:
```js
panel.plugin(/**/)
(function() { /**/ })()
```
which javascript interprets as if the return value of `panel.plugin(/**/)` should be a function (because it's followed by parentheses), therefore it throws an error like `undefined is not a function`. 

It's kinda the fault of plugin author 1, he should have ended his plugin with a semicolon. But in JS semicolons are optional, and it's only a problem because of the concatenation Kirby does. 

It would therefore be kinda nice if Kirby would add that missing semicolon when bundling. 
It could either just blindly append one (at worst, if there is already one, it becomes `;;` which does no harm), or check if the final semicolon is missing (the plugins code seems to be loaded into memory anyway).

**Comment by bastianallgeier** [comment]
✅
