### ISSUE TITLE
API error response "file" property is getting lost

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1937]
**Describe the bug**
The `file` specified in the JSON response is `""`:
![image](https://user-images.githubusercontent.com/5570098/61616866-3eb7e880-ac72-11e9-9f88-cf26c0b0c9f9.png)

**Expected behavior**
The problematic file should be specified in the error response.

**Screenshots**
![image](https://user-images.githubusercontent.com/5570098/61616805-16c88500-ac72-11e9-9517-ed89fcc3f478.png)

**Kirby Version**
3.2.0

**Additional context**
As you can see in the debug console (screenshot), `$e->getFile()` correctly returns the file where the error occurred. However, after the `DOCUMENT_ROOT` check, `$file` is now `""`. Here's some evaluated code in the debug console after this check:

```
$file
""
$e->getFile()
"C:\xampp\htdocs\kirby\site\plugins\exporter\src\Formatter.php"
$_SERVER['DOCUMENT_ROOT']
"C:/xampp/htdocs"
```

**Comment by yandodov** [comment]
This also happens in other cases where the error is not a Kirby exception:

![image](https://user-images.githubusercontent.com/5570098/63827556-3d15ca80-c96c-11e9-9baa-9887061bcbee.png)

In this case, execution when through the other conditional block at line 544 and after it exited, the `$file` was empty again.

---

It would be great if we can get some sort of hotfix for the time being because you need to alter the core every time a new release is out in order to debug properly.

**Comment by yandodov** [comment]
I've currently fixed it by adding this:

```php
if (isset($e) && is_array($result)) {
    $result['file'] = $e->getFile();
}
```

After the try-catch block, i.e. after this line:

https://github.com/getkirby/kirby/blob/03d6e96aa27f631e5311cb6c2109e1510505cab7/src/Api/Api.php#L567

**Comment by bastianallgeier** [comment]
✅

**Comment by yandodov** [comment]
Wow, you did quite a bit of refactoring. Thanks! It's been a small bug, but quite annoying.

**Comment by bastianallgeier** [comment]
I think it was really worth it! Especially for the Spaghetti code in the Api class.
