### ISSUE TITLE
Error needed when parent in files section is a collection

### ISSUE THREAD

**Issue by moritzebeling** [getkirby/kirby#1938]
I think it is great, that the `files` section can display not only files from one single `page`, but also all the files from multiple `pages`. Like:
```
all_uploads:
  type: files
  headline: All uploads
  parent: site.index
```

The problem appears when uploading a file to a section like that: `No route found for path: "files" and request method: "POST"`, probably because it doesn’t know where to upload the new `file`.

A solution could be to:
1. add a `upload` option, that can be set to `false` to disable the upload functionality to this section. Or:
2. add a `upload` option where a single(!) `page` can be specified, to where a newly uploaded file should be moved to

**Comment by texnixe** [comment]
In this case the bug is that the section doesn't throw an error because the parent is only supposed to be a single page, not multiple pages.

The upload option would be nice to have, but in this case the missing upload functionality is not the bug but a side effect.

**Comment by distantnative** [comment]
Agreed, there are quite a few other problems/things to consider when `parent` could be a pages collection. I don't think we are there yet, so the correct behavior would be to check that it is a `page`, `site` or `user` object - and throw an error with anything different.

**Comment by moritzebeling** [comment]
Thanks for looking into it. I already assumed, that, at this point, `parent` is not expected to be a `pages` collection. I’ll file an [Idea](https://github.com/getkirby/ideas/issues/360) for that to be added in the future.

**Comment by bastianallgeier** [comment]
✅
