### ISSUE TITLE
`Str::template` does not work with placeholder containing a dot

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1939]
**Describe the bug**
When a placeholder like `{{ company.name }}` contains a dot, the `template()` method regards this as a query and returns no result.

Example code to reproduce the issue:

1. Hook in plugin
```
    'hooks' => [
        'kirbytags:after' => function ($text, $data, $options) {
            $translations = $this->language()->translations();
            return Str::template($text, $translations);
        }
    ]
```

In text file:

```
{{ company.name }} is the best company in the world.
```

In language file, e.g. `site/languages/en.php`

```
    'translations' => [
        'company.name' => 'Supercomp Ltd.'
    ],
```

Result: no string replacement takes place. The code works, however, with placeholders without the dot.

**Expected behavior**
Placeholders with dots should be replace because using dots is quite common to structure language variables.

**Additional context**
@distantnative proposed the following change in the `template()` method:

```
return (new Query($match[1], $data))->result() ?? $data[$query] ?? $fallback;
```

https://forum.getkirby.com/t/handling-translations-via-panel-and-publishing-single-language/15015/14?u=texnixe

**Comment by bastianallgeier** [comment]
✅
