### ISSUE TITLE
Default Panel language not respected in language selector on install screen/user create dialog

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1940]
**Describe the bug**
When the default Panel language via the config is set to anything but English in the config like this

```
return [
    'panel' => [
      'language' => 'de'
    ]
];
```
this setting should be reflected in the preselected language select on the installation screen as well as in the user create dialog. Currently English is always the preselected language.

**To Reproduce**
1. Set Panel language to a language other than English in the config
2. Visit the Panel installation screen (before new users are created)
3. See English preselected in language select field.
4. Alternatively, if there are already accounts, create a new user. 

**Expected behavior**
The config Panel language should be respected when creating users.

**Screenshots**
<img width="483" alt="Bildschirmfoto 2019-07-22 um 13 29 17" src="https://user-images.githubusercontent.com/5312492/61629337-d7576400-ac84-11e9-9591-0465d9c401bf.png">

**Kirby Version**
Tested with 3.2.2 but I guess it's not a new issue.

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
![FireShot Capture 760 - Installation - Mægazi_ - http___localhost_test_kirby_3 2 5_panel_installation](https://user-images.githubusercontent.com/3393422/65057401-3d0d5700-d97b-11e9-8222-5278771ad0fa.png)

Language required but not selected. This is normal?
I expected as selected english, If no setting default panel language.

**Comment by distantnative** [comment]
That's weird.

For me, when I have set a default language in config, it is preselected correctly and there is no empty option (the one with the dashes present.

<img width="692" alt="Screen Shot 2019-09-17 at 18 57 16" src="https://user-images.githubusercontent.com/3788865/65062773-12240280-d97d-11e9-9e79-981c9a8334c1.png">
<img width="685" alt="Screen Shot 2019-09-17 at 18 57 23" src="https://user-images.githubusercontent.com/3788865/65062774-12bc9900-d97d-11e9-9481-2dbdb8e91bbb.png">

When I remove the config, the same only that English is preselected.

**Comment by afbora** [comment]
Hmm try to access `/panel` not `/panel/installation` without setting

**Comment by distantnative** [comment]
Oh wow, that shouldn't make a difference 🤯

**Comment by afbora** [comment]
I realized that doesn't work even if default panel language defined when accessing `/panel` address

**Comment by distantnative** [comment]
Yea, the problem does not seem to be the change per se, but rather that some Vuex calls (or watchers) aren't activated the same way.

**Comment by bastianallgeier** [comment]
✅ It was pretty simple to fix. The watched translation prop needed to be evaluated immediately when the component is created.

**Comment by afbora** [comment]
We made corrections to the RC. Can you render the source files so we can test them again?

**Comment by bastianallgeier** [comment]
@afbora I will release a new RC with new dist files in a few minutes.
