### ISSUE TITLE
KirbyText Line Spacing Format

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#1943]
In converting from Kirby 2 to Kirby 3 several of my Kirbytext (Markdown) tags were showing unformatted on the pages. I dug into it and found that any markdown such as headers or bold tags need a space between them otherwise formatting fails when there is a previous html tag or even a markdown image tag. Two examples are below. 

```
<script src="https://xxxxxxxxxxxxxx.com/assets/integration/v1/sdk.js"  type="text/javascript"></script>
###Improved Fraud Alerts
```

Yields `###Improved `Fraud Alerts on the page, but if I give it a space between the two it works fine.

It also seems to happen if there is a file just above the text.

```

(image: shutterstock_1424238572.jpg)
**Test**
```

Kirby forum post - https://forum.getkirby.com/t/kirbytext-line-spacing-format-issue/15027

**Comment by distantnative** [comment]
Related as it seems: https://github.com/getkirby/kirby/issues/1482

**Comment by texnixe** [comment]
Seems to be a Parsedown problem: https://forum.getkirby.com/t/kirbytext-line-spacing-format-issue/15027/16?u=texnixe

**Comment by lukasbestle** [comment]
For some reason it works on the [Parsedown demo page](https://parsedown.org/demo). 🤔

**Comment by texnixe** [comment]
Yes, I know, I tested on that demo page first, but the example I posted in the thread above doesn't work. Maybe a different Parsedown version?

**Comment by texnixe** [comment]
With the lastest stable version tested outside of Kirby (Parsedown 1.7.3) the example works as well. I assume that is the one used on the demo page. While the 1.8.0-beta-7 we are using doesn't work. But I guess we are using this version for a reason because it fixes some problems of the stable release.

**Comment by lukasbestle** [comment]
Yep, we need the beta because of several other parsing improvements. But it's unfortunate that it has this regression.

I have reported this issue over at the Parsedown repo (see https://github.com/erusev/parsedown/issues/721). Closing this issue as we unfortunately can't fix it directly. Please upvote/comment on the issue over there, that would help a lot. :)

**Comment by lukasbestle** [comment]
The Parsedown team has already replied to the issue. Main takeaways:

- Markdown formatting in the line directly after a `<script>`, `<style>` or `<pre>`element should work. This is a bug in Parsedown that is fixed in the current development version. We are checking if we can upgrade to that already.
- That Markdown doesn't render after *different* HTML tags is intended behavior (you can read more at https://github.com/erusev/parsedown/issues/721#issuecomment-514782612).

**Comment by ghost** [comment]
So what is happening with the example where we have an image above the text? That was actually the case that broke my site more than having HTML tags above text.

**Comment by lukasbestle** [comment]
The same. :)

The `(image:)` KirbyTag generates HTML which will then be skipped by the Markdown parser when parsing the Markdown code in the next step.

Your example looks like you want an image caption. A cleaner and a lot more semantic solution would be a proper `<figure>` tag, which you can generate like so:

```
(image: shutterstock_1424238572.jpg caption: Test)
```

**Comment by ghost** [comment]
I use captions in some places, that tag is pretty handy, but this was a different case. Anyway, I get the issue and was able to correct it with the space, but I guess when it comes to it for usability purposes this isn't ideal. Especailly when it wasn't an issue in previous versions. Hopefully there will be some way around that spacing in the future. 

Thanks!

**Comment by ghost** [comment]
Just to circle back around again as I just ran into this. I can't even do something like this inline.

`**(link: https://pay.google.com/about/ text: Get the Google Pay App)**`

Shouldn't this bold the link?

**Comment by texnixe** [comment]
> Shouldn't this bold the link?

No, I don't think so. You could bolden the text attribute or apply a class.

**Comment by ghost** [comment]
Ok, I'll stop tagging on to this, it just seems like the previous version allowed it and the whole spacing thing wasn't an issue in the previous Kirby iterations, which hampers usability in my opinion. Thanks for investigating.

**Comment by texnixe** [comment]
@Threadgill You can replace the markdown parser with another component, either the current stable Parsedown version or the 2.0 beta or a completely different parser in a plugin. But keep in mind that the older Parsedown version has other bugs that were fixed in the 1.8.0 beta.

**Comment by lukasbestle** [comment]
> Especailly when it wasn't an issue in previous versions. Hopefully there will be some way around that spacing in the future.

As I wrote, this is the behavior of the Markdown reference implementation and therefore apparently intended – it's not for us to decide. The previous behavior was a bug, not the current one. In any way, it is not a bug in Kirby but in the Markdown parser, which you can [replace](https://getkirby.com/docs/reference/plugins/components/markdown) like @texnixe wrote.

> Just to circle back around again as I just ran into this. I can't even do something like this inline.
> 
> `**(link: https://pay.google.com/about/ text: Get the Google Pay App)**`
> 
> Shouldn't this bold the link?

For me that produces the following output:

```html
<p><strong><a href="https://pay.google.com/about/">Get the Google Pay App</a></strong></p>
```

So it works like intended.

**Comment by ghost** [comment]
Yes, it does render that if a new line is present. Inline it does not. I mean I understand all this but just as a usability thing for say a client updating his/her website that may not know about these caveats it's not the most ideal.

**Comment by ghost** [comment]
I'll look into replacing the parser. Thanks for the replies!

**Comment by lukasbestle** [comment]
Please let us know in case you find a PHP Markdown parser that works better. We did some research a while ago but couldn’t find one. They all had other issues (e.g. code quality, parsing errors, performance, code size etc.).
