### ISSUE TITLE
Setting the `api.csrf` option prevents the user from logging in

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1944]
**Describe the bug**
I wanted to disable API authentication for development purposes. After looking at the source, I found out I can kind of disable it by using the undocumented [`api.csrf`](https://github.com/getkirby/kirby/blob/master/src/Cms/Auth.php#L46) option. If I set it to `null` obviously nothing happens, but if I set it to `''`, I can log in and make requests to the API (from the browser where I have logged in) without a CSRF token.

This works as expected if I specify the option in `config.php` like this:

```php
'api' => [
    'csrf' => ''
]
```

But it works weirdly if I specify it like this:

```php
'api.csrf' => ''
```

By "weirdly" I mean that I can still request the API with no CSRF, but the tab where I've logged in the panel starts refreshing endlessly, redirecting me from `/panel/login` to `/panel/site` and back, with the "Unauthenticated" error on both of them. If I delete my session cookie, I can no longer request the API (I get the "Unauthenticated" error there as well), the panel redirection loop stops, I land on the "/panel/login" page, and I can no longer log in, even with the correct credentials.

**To Reproduce**
Add this in config.php:

```php
return [
    'api.csrf' => ''
];
```

And do as I've said above.

**Expected behavior**
Specifying options both ways should work identically.

**Kirby Version**
3.2.0

**Edit:** I think this happens due to [this line of code](https://github.com/getkirby/kirby/blob/master/src/Cms/Panel.php#L96). It expects `options['api']` to be an array. If that's the case, other options used in the same manner would likely result in unexpected behavior.

**Edit 2:** Yep, I can confirm. Changing the following in _Panel.php_ from:

```php
'csrf' => $kirby->option('api')['csrf'] ?? csrf(),
```

to:

```php
'csrf' => $kirby->option('api.csrf') ?? csrf(),
```

Solves the problem.

**Comment by lukasbestle** [comment]
Hm, interesting that we even have that option. I think we should remove it entirely actually as it could be a security risk. Or have I missed anything here @distantnative @bastianallgeier? What was the reason for the option when it was implemented?

**Comment by distantnative** [comment]
I think we have it for our development setup. If I recall the FSRF token would not work if the site and API are reached via `kirby.test` while the Panel runs at `localhost:8080`.

**Comment by yandodov** [comment]
@lukasbestle I think it's needed. Otherwise how would you make requests to the API from plugins' front-end? Actually, the panel itself uses the API too, so it also needs to provide the token?

**Edit:** I'm talking about the presence of the CSRF token in `window.panel.csrf`, which might be a different thing, now that I look at it.

**Comment by lukasbestle** [comment]
@distantnative Ah, that makes sense. Then the fix proposed by @hdodov is probably the way to go.

@hdodov Yes, I was only talking about the option in the Kirby config. Right now it defaults to the dynamic CSRF from the session if not set.

**Comment by yandodov** [comment]
@lukasbestle if my fix is the way to go, you should search the codebase for similar issues. `$kirby->option('panel')['search']['limit']` is used in that same file.

**Comment by bastianallgeier** [comment]
@hdodov's fix is the way to go. We probably have similar issues in other places.

**Comment by distantnative** [comment]
I searched all files with `\$kirby->option\(.*\)\[` regex, can only find those 2 occurrences. Will fix them.

**Comment by bastianallgeier** [comment]
✅
