### ISSUE TITLE
Cannot Use Custom Slug Rules With Single-Language Installation

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1945]
**Describe the bug**
I would like to use the [custom slug rules](https://getkirby.com/docs/guide/languages/slug-rules) for our single-language site (which happens to be in English).

However, the presence of a file such as `/site/languages/en.php` cause the Panel to break (because it seemingly thinks all content has not been translated).

**To Reproduce**
1. Set up your config as:
```php
return [
    'languages' => false, // this the default value, but listing for clarity
];
```
2. Create a file at `/site/languages/en.php` with:
```php
<?php

return [
  'code' => 'en',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'en_US',
  'name' => 'English',
  'slug' => [
    'foo' => 'bar',
  ],
];
```
3. Open Panel

**Expected behavior**
I should still be able to use the Panel as if it was a single-language site. Instead, it currently thinks all existing content is untranslated.

**Kirby Version**
`3.2.2`

**Additional context**

**Comment by texnixe** [comment]
Did you rename your text files after making the change? In a multi-lang installation–even with only a single language–the language code must be part of the file name. Kirby takes care of renaming all files if you create your languages through the Panel. If you create the language files manually, you have to take care of that yourself. It's how Kirby works, not a bug.

Having said that, you don't need a language installation to be able to use custom slugs.
https://getkirby.com/docs/reference/system/options/slugs

**Comment by neildaniels** [comment]
Gotcha. I did not rename the files, but I also expected that this _wouldn't_ become a multi-language site because of the presence of `'languages' => false`. I would have assumed _that_ would force this to remain a single-language site.

But https://getkirby.com/docs/reference/system/options/slugs works for me. Sorry I didn't catch that in the documentation.

**Comment by texnixe** [comment]
No, `languages: false` only disables creating languages through the Panel.
