### ISSUE TITLE
Custom Slug Rules Fail With `+` Symbol

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1946]
**Describe the bug**
When attempting to set [custom slug rules](https://getkirby.com/docs/reference/system/options/slugs), an error is given if trying to do something like:

```php
Str::$language = [
    '+' => 'plus',
];
```

> Invalid regular expression: nothing to repeat

Alternatively, something like the following does not error, but also doesn't have any effect:
```php
Str::$language = [
    'ESPN+' => 'espn-plus',
];
```

**Screenshots**
<img width="377" alt="Screen Shot 2019-07-24 at 3 31 27 PM" src="https://user-images.githubusercontent.com/417182/61833092-1f62bc00-ae28-11e9-80ec-327261005364.png">

**Kirby Version**
`3.2.2`

**Comment by lukasbestle** [comment]
I'd say that's because the `+` sign is a special character in the RegEx language so it needs to be escaped. Same for the backend implementation probably (although if I remember correctly we use `str_replace()` there so it wouldn't be an issue in the backend).

**Comment by distantnative** [comment]
We should use
https://github.com/getkirby/kirby/blob/master/panel/src/helpers/regex.js

and need to extend it e.g. along th elines of
https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex

**Comment by bastianallgeier** [comment]
✅
