### ISSUE TITLE
[Panel] Only show changeRole option when there are multiple roles, not based on number of users

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1948]
**Describe the bug**
If you have only 1 user, you are not able to press `Change role` on the users list and in the view of an individual user.

If you have > 1 users, you can change the users role, even if there is just one (admin) role.

**To Reproduce**
1. Go to users list
2. Click on any user
3. Check the `Change Role` option
4. Create a new user (2nd user)
5. Repeat steps 1 to 3 and compare the behavior of change role on the users list and in an individual user view.

**Expected behavior**
1. No possibility to change role if there is only one role.
2. Same behavior regardless how many users are in the system.

**Kirby Version**
3.2.2

**Desktop (please complete the following information):**
Windows 10, latest Firefox

**Additional context**
- multi-language setup with just 1 language
- WAMP setup

**Comment by texnixe** [comment]
Also: https://github.com/getkirby/kirby/issues/1920

**Comment by bastianallgeier** [comment]
✅
