### ISSUE TITLE
Better standard preset for Thumb jpg quality

### ISSUE THREAD

**Issue by puckey** [getkirby/kirby#195]
Out of the box the Thumb class uses 100% quality for jpg compression - this leads to unnecessarily large files..

AFAICS IM uses 92% as a default value - GD uses 75% as a default.. Perhaps the default could be changed to something in between those values? Or even leave out the quality when not specified by the user, and leave the default quality up to the library?

**Comment by bastianallgeier** [comment]
The 100% setting is indeed not the best solution for everyone. But this can easily be changed like this: 

```php
thumb::$defaults['quality'] = 90;
```
The best place to put it is in the config.

**Comment by puckey** [comment]
I did exactly this after wondering why the jpegs being produced were so large.

I don't think the default value makes much sense as a default... Compressing jpegs with 100% leads to unnecessarily large files with hardly any advances in quality in comparison to 85% - 90%.

**Comment by bastianallgeier** [comment]
You might be right. My thinking was not to set any negative quality effects by default. But blowing up the size is not ideal either. I think setting the quality to 90 sounds about right. The 75 percent from GD lib has definitely visible effects in some images.

**Comment by bastianallgeier** [comment]
Ok, it's now in the develop branch and will be in the next stable release.
