### ISSUE TITLE
Site index also lists old version of page in page.changeSlug:after hook

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1952]
**Describe the bug**
When hooking into the `page.changeSlug:after` hook the site index lists two versions of the page, one with old id and one with new id.

```php
'page.changeSlug:after' => function() {
  // lists two versions of the page, one with old and one with new id
  $this->site()->index();
 },
```
**Expected behavior**
In the moment of triggering the hook the index should only list valid pages, therefore not the version of the page with an old id.

**Additional context**
Might be related to #1923

**Kirby Version**
3.2.2

**Comment by texnixe** [comment]
The hook function has two parameters ($oldpage, $newpage), so I would expect the two objects to be still available.

**Comment by qwerdee** [comment]
Right, however as the old page model is passed as a parameter, I see no need to have it also present in the index collection. I still expect this to represent the valid state of the site after the slug change happened. 
My fix for now is to manually remove the old page from the collection.

**Comment by bastianallgeier** [comment]
✅
