### ISSUE TITLE
content() method returns old data after update()

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1959]
**Describe the bug**
When I call `$page->update()` and then call `$page->content()`, I get the old page data without my newly added modifications. This makes it very hard to write tests for plugins that write content.

**To Reproduce**
Put the following in _default.php_ template:

```php
$num = rand();
$kirby->impersonate('kirby');
$page->update([
    'num' => $num
]);

echo ('expected ' . $num . '<br>');
echo ('actual ' . $page->content()->num()->value());
```

On the first run, you would get:

```
expected 970377139
actual 
```

Even though the `num` is saved in the txt file (check it), the returned value from `content()->num()->value()` does not reflect that.

If you reload the page, you get:

```
expected 1604594463
actual 970377139
```

A new value is saved, but the old one is returned.

**Expected behavior**
The `content()` method should return up-to-date page content. I.E.

```
expected 970377139
actual 970377139
```

**Kirby Version**
3.2.2

**Additional Context**
This bug occurs with translations too. I tried `$page->update(..., 'bg')` then `$page->content('bg')`. I also tried updating the page with `writeContent()` instead of `update()`. Same result.

**Comment by afbora** [comment]
I can reproduce with 3.2.3-RC.1 too. 

I realized that works with only `content()` method like that:

```
$page->content()->update([
   'num' => $num
]);
```

> expected 1428897874
> actual 1428897874

**Comment by texnixe** [comment]
You have to assign the updated page to a new variable for this to work:

```
<?php 

$num = rand();
$kirby->impersonate('kirby');
$newPage = $page->update([
    'num' => $num
]);

echo ('expected ' . $num . '<br>');
echo ('actual ' . $newPage->content()->num()->value());
?>
```
You cannot change the page object after it is created.

**Comment by yandodov** [comment]
@texnixe thanks for the response, but that doesn't make much sense from a logical point of view. If you call an `update()` method on an object, you expect that object to be updated. You don't expect to get a clone of the object with the new data while the initial object is left intact? A method name like `recreate()` or `refresh()` might be more suitable?

@afbora I also discovered that, but if I recall correctly, calling `content()->update()` doesn't actually save anything in the txt file.

**Comment by bastianallgeier** [comment]
@hdodov we keep most stuff in v3 immutable, which makes a lot of internal parts more clear and better testable. This is why the update method returns the modified object, but doesn't mutate the original. You can use this to compare date afterwards and do all sorts of additional things.

**Comment by yandodov** [comment]
@bastianallgeier I get that, my issue then is with naming/documentation. It's just confusing that the method's name is `update()`. It implies that it modifies the original object.

I guess that renaming such a core method might be very problematic, but you could maybe document it better [here](https://getkirby.com/docs/reference/objects/page/update).

Adding something like:

>**Note:** The original `$page` object is not modified. A clone is returned instead, so you need to do: [...]

would be very helpful.

You could maybe change the example too. From:

```
try {

  page('mypage')->update([
    'title'        => 'A new title',
    'text'         => 'Some text',
    'anotherfield' => 'Some more data'
  ]);

  echo 'The page has been updated';

}
```

to:

```
try {

  $newPage = page('mypage')->update([
    'title'        => 'A new title',
    'text'         => 'Some text',
    'anotherfield' => 'Some more data'
  ]);

  echo 'The page has been updated:<br>';
  var_dump($newPage->content());

}
```

**Comment by bastianallgeier** [comment]
I agree, that we should fix the docs here!

**Comment by texnixe** [comment]
Was going to after this issue here anyway.

**Comment by yandodov** [comment]
Actually, I had a slightly different issue initially. I have a plugin that updates the page content and I'm writing tests for it. I want to test the updated content, but I don't have access to the new page returned by `update()`. So my issue is more like this:

```php
$pluginStuff = function ($input) use ($kirby, $page)
{
    $kirby->impersonate('kirby');
    $page->update([
        'title' => $input
    ]);
};

$num = rand();
$pluginStuff($num);
echo ('expected ' . $num . '<br>');
echo ('actual ' . $kirby->page('home')->content()->title());
```

Here, I update the `home` page `title` and I want to obtain the new value outside of `pluginStuff()`. By using `$kirby->page('home')`, I expect to get the new, updated page. However, I get the same issue as discussed above.

How am I supposed to get the new page when I don't have access to the object returned by `update()`?

---

Aside from plugin testing, this could be problematic in general as well. What if you update a page somewhere in a snippet, query it somewhere else in another file, and expect the new value? It would be pretty bad to have to store the new page from `update()` somewhere and move it all over the place.
