### ISSUE TITLE
Switch to a different Markdown parser

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1961]
https://github.com/cebe/markdown looks promising.

Needs:

- [ ] Performance testing
- [ ] Parser testing with the getkirby.com content

---

Related/Should be solved with this:

- #1912
- #1943
- #1701

**Comment by afbora** [comment]
@lukasbestle `cebe/markdown` Wouldn't it be risky for the future if it was last developed 8-10 months ago? 🤔 

> Latest commit eeb1bf6  on 10 Dec 2018

Commits graph of `cebe/markdown`:  2 commits in last years.

![FireShot Capture 721 - Commit Activity · _ - https___github com_cebe_markdown_graphs_commit-activity](https://user-images.githubusercontent.com/3393422/62292247-adfdbb80-b46e-11e9-8fb2-7b84c56b76d9.png)

**Comment by distantnative** [comment]
Stumbled upon https://github.com/thephpleague/commonmark

**Comment by afbora** [comment]
`thephpleague/commonmark` more promising:

![FireShot Capture 722 - Commit Activity · thephpleague_common_ - https___github com_thephpleague_co](https://user-images.githubusercontent.com/3393422/62293841-2619b080-b472-11e9-9b67-6a1b3f6cc203.png)

**Comment by lukasbestle** [comment]
That one definitely ticks the "well maintained" and "built as a real and fast parser" boxes, but we'd still need to check syntax (it follows the CommonMark spec, which is different from both original Markdown and even more different from Markdown Extra -> breaking change) and also its extension API reminds me of Composer's (quite a bit overengineered, but maybe in a good way this time – we'll see).

**Comment by nilshoerrmann** [comment]
Have you ever thought about freezing the state of the Markdown parser and deprecate it for an alternative `toMarkup()` method based on CommonMark? The good thing about CommonMark it‘s a spec so things should not vary across implementations.

**Comment by lukasbestle** [comment]
That's true. I agree that CommonMark would be the better long-term solution. If parsing issues occur, they can clearly be tracked down to the spec (= intended behavior) or to the implementation – unlike with our current parsers, where parsing results are pretty ambiguous when discussing them with the parser devs.

 We can't really offer both unfortunately, as we have field methods for both `markdown()` as well as `kirbytext()` – the latter always needs to use just one parser implementation, otherwise it would get messy.

The goal with the parser switch is also a more deep integration of KirbyTags parsing into the Markdown parser to increase parsing performance and reliability. We want to do this by implementing a parser extension for KirbyTags. That also won't really work when we keep both parsers in the core.

What we *could* do however is to switch to CommonMark entirely (= Markdown Extra would be removed entirely and Markdown would be replaced with CommonMark). For projects that rely on the old parser behavior, we could offer an official Kirby plugin that comes with Parsedown and Parsedown Extra and behaves just like before by overriding the `markdown` component. What do you think @bastianallgeier @distantnative?

**Comment by bastianallgeier** [comment]
I'm skeptical of the CommonMark project. It has been developed by completely excluding Gruber as the inventor of Markdown, which I find a very very weird decision. 

I had a CommonMark parser running once and was totally put off by its strictness. I don't know if all CommonMark parsers follow this so closely. But it even stopped parsing headlines when you forgot to put a space after the #. This is just user unfriendly for the sake of following a made-up standard in my opinion. 

Ditching Markdown Extra entirely after all those years feels super weird to me. Many switch it on and rely on it for their blog posts or other content - especially for features like footnotes or tables. Having to replace that with a plugin is also user unfriendly from our end.

**Comment by lukasbestle** [comment]
Those are all very valid points!

You are right about the strictness – that's actually something I dislike about CommonMark as well. It's great in theory to avoid parsing ambiguities, but especially non-techy editors will run into errors or weird parser results all the time. It really doesn't feel like it should live in the Kirby home if I think about it. :)

Unfortunately I couldn't find any really promising library in my research.

Again, here are our requirements in order of importance:

- very fast (based on a parser, *not* on regular expressions)
- support for Markdown and Markdown Extra syntaxes
- good code quality
- extensible with custom parser extensions (for KirbyTag parsing)
- large install base, reasonably well maintained

Unfortunately https://github.com/cebe/markdown isn't as fast as it claims (at least on my machine measured with https://github.com/kzykhys/Markbench):

```
Runtime: PHP7.2.11
Host:    Darwin ... 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
Profile: Basic markdown content with all official syntax / 1000 times
Class:   Markbench\Profile\DefaultProfile

+----------------------+---------+---------+---------------+----------+--------------+
| package              | version | dialect | duration (MS) | MEM (B)  | PEAK MEM (B) |
+----------------------+---------+---------+---------------+----------+--------------+
| erusev/parsedown     | 1.7.3   |         | 6991          | 14680064 | 14680064     |
| michelf/php-markdown | 1.8.0   |         | 10433         | 14680064 | 14680064     |
| cebe/markdown        | 1.2.1   |         | 10569         | 14680064 | 14680064     |
| cebe/markdown        | 1.2.1   | gfm     | 12241         | 14680064 | 14680064     |
| michelf/php-markdown | 1.8.0   | extra   | 12603         | 14680064 | 14680064     |
| kzykhys/ciconia      | v1.0.2  |         | 21980         | 14680064 | 14680064     |
| kzykhys/ciconia      | v1.0.2  | gfm     | 23862         | 14680064 | 14680064     |
+----------------------+---------+---------+---------------+----------+--------------+
```

Also the Markdown Extra implementation of cebe/markdown isn't fully complete. :(

We'd love to get some more input on other parsers we could use. If you know any that fulfill our criteria, please let us know – that would help a lot.

**Comment by lukasbestle** [comment]
PS: I ran the benchmark on a few more candidates and also updated Parsedown to the versions we are using to ensure a fair comparison. The results are pretty surprising:

```
+------------------------+---------------+---------+---------------+----------+--------------+
| package                | version       | dialect | duration (MS) | MEM (B)  | PEAK MEM (B) |
+------------------------+---------------+---------+---------------+----------+--------------+
| michelf/php-markdown   | 1.8.0         |         | 14234         | 14680064 | 14680064     |
| cebe/markdown          | 1.2.1         |         | 14509         | 14680064 | 14680064     |
| erusev/parsedown       | v1.8.0-beta-6 |         | 16354         | 14680064 | 14680064     |
| erusev/parsedown-extra | 0.8.0-beta-1  |         | 17084         | 14680064 | 14680064     |
| cebe/markdown          | 1.2.1         | gfm     | 17361         | 14680064 | 14680064     |
| michelf/php-markdown   | 1.8.0         | extra   | 17742         | 14680064 | 14680064     |
| kzykhys/ciconia        | v1.0.2        |         | 30592         | 14680064 | 14680064     |
| kzykhys/ciconia        | v1.0.2        | gfm     | 32689         | 14680064 | 14680064     |
| league/commonmark      | 1.0.0         |         | 55052         | 16777216 | 16777216     |
+------------------------+---------------+---------+---------------+----------+--------------+
```

The results are generally worse because of the parallel test run BTW (more tests are run concurrently, which makes all of them slower). But the relation between the results should be alright.

Parsedown has become a lot slower in the latest beta version and CommonMark is completely off the charts.

**Comment by neildaniels** [comment]
I'm genuinely worried about our large collection of previous articles/posts that make extensive use of Markdown Extra syntax. If there's a risk that there's breakage, I'd delay upgrading for a while.

It would be helpful/reassuring if this process had one/some of these fallbacks:
- Keep using the old parser (and accept the seemingly few bugs it has).
- Have some kind of site-wide migration assistant that would compare the rendered HTML of existing pages using the old and new Markdown parser to help detect parsing failures (probably very tricky, as I doubt the output HTML is identical for non-trivial uses)
- Be able to pick which parser is used on a field-by-field/post-by-post basis. (For example, it would be interesting for me to say "all posts with a date older than xx-xx-xxxx get old parser" and and all other posts get the new parser.)

**Comment by lukasbestle** [comment]
Valid points! I'm not sure what the best implementation would be, but we will try to make the migration/backwards-compatibility as smooth as possible. What do you think @bastianallgeier?

**Comment by bastianallgeier** [comment]
@neildaniels please don't worry. We won't make this step when it's going to break existing content.

**Comment by lukasbestle** [comment]
The question is: How do we ensure that? There are a lot of edge-cases and since the Markdown standard (unlike CommonMark) isn't clearly defined, there will definitely be parsing differences for some of them (hopefully only for the more exotic ones).

We will most likely only see that once issues start rolling in after the release.

**Comment by bastianallgeier** [comment]
There are two things we can do: 

1. build our own test suite around markdown features. (we should do this anyway)
2. extensive tests with real world projects. Of course this needs the help from the community.

**Comment by russdb** [comment]
Most of the markdown stuff doesn't seem to work for my users at all, such as bolding, bullet points, etc.

**Comment by bastianallgeier** [comment]
@russdb that sounds strange. We only have markdown parsing issues in very extreme edge cases. Could you send over some of the markdown that's not working for your clients?

**Comment by lukasbestle** [comment]
@bastianallgeier Which Markdown parser from those we have tested do you prefer at the moment?

**Comment by bastianallgeier** [comment]
@lukasbestle I'm not sure. let's move this decision to 3.4.0.

**Comment by colinodell** [comment]
> and CommonMark is completely off the charts

Author of the PHP CommonMark library here. We've done a bit of performance improvement since 1.0.0 - it's definitely still the slowest one in relative terms, but not in absolute terms:

![image](https://user-images.githubusercontent.com/202034/72112739-78f27080-330c-11ea-873c-203c2529bf7f.png)

14ms isn't all that bad, especially given the flexibility and security it provides.  But then again I'm also a bit biased :stuck_out_tongue: Let me know if you have any questions about the library that I can help answer!

**Comment by colinodell** [comment]
Further update: the 2.0 release (due out later this summer) will be significantly faster:

![image](https://user-images.githubusercontent.com/202034/82764997-201a0500-9de1-11ea-806a-437fed15801e.png)

We also have full support for Github-Flavored Markdown (per [the official GFM spec](https://github.github.com/gfm/))

**Comment by distantnative** [comment]
Actionable steps:
- [ ] Create test suite around markdown and markdown extra features
- [ ] Add tests for the known issues with Parsedown
- [ ] Evaluate libraries

If we find a library that's performant enough and passes the tests, there could be two way:
- it really passes all the tests, same output as with Parsedown and Parsedown Extra => replace Parsdown with it
- it passes the basic tests, but not Markdown Extra features. However it passes tests for issues that Parsedown currently fails => we introduce a new option for markdown parser, default is `parsedown`. We bundle Parsedown and this other library. So that people who encounter issues with Parsedown can switch to the other library (in trade of not getting markdown extra features).

**Comment by lukasbestle** [comment]
My expectation is that finding a library that supports all Markdown features and supports them correctly won't be difficult. As we have discussed already, the difficulty is that Parsedown itself has quirks and (by accident) "supports" weird syntax that isn't in the Markdown spec. As other libraries won't have these quirks (at least not the same ones), a switch to any other library will break existing sites that relied on the quirks. There's not much we can do about that, which is why this issue is open for so long.

**Comment by distantnative** [comment]
Ok, let me re-phrase: finding a library that is the closest to Parsedown output, except the identified issues and without its own issues.

And as I suggested in regard to the breaking change:
Let's bundle both libraries and add a `markdown.parser` option - that either defaults to `parsedown` (no breaking change, option for those how experience issues with Parsedown to switch) or to the new library (breaking change, but easy to fix for developers, adding one line in their config).

**Comment by bastianallgeier** [comment]
I think we should close this. I no longer see a potential switch in v3
