### ISSUE TITLE
download() creates broken images

### ISSUE THREAD

**Issue by ian-cox** [getkirby/kirby#197]
http://getkirby.com/docs/cheatsheet/file/download

Using ``download()`` and ``f::download()``, Html files download correctly but image files, (jpg and png) become corrupted.

```
c::set('routes', array(
  array(
    'pattern' => 'download/(:any)',
    'action'  => function($folder) {
      page($folder)->files()->last()->download();
      //return false;
    }
  )
));
```

![screen shot 2015-02-11 at 8 43 29 pm](https://cloud.githubusercontent.com/assets/4325127/6160294/f8418394-b22e-11e4-822e-bd9e42554e18.png)

**Comment by lukasbestle** [comment]
Could you please try opening the image in a text editor to check what the file contents are? Maybe the "downloaded" file is actually an error.

**Comment by ian-cox** [comment]
Thanks for taking a look,

I've attached the downloaded image. I don't see any errors.
I have error reporting turned on.

![web-ahhon53zbt](https://cloud.githubusercontent.com/assets/4325127/6171628/cb1533b8-b2a9-11e4-
9db0-bc8b56a444f2.jpg)


![screen shot 2015-02-12 at 11 25 42 am](https://cloud.githubusercontent.com/assets/4325127/6171649/e886dc4e-b2a9-11e4-9183-62045348cc08.png)

![screen shot 2015-02-12 at 11 30 57 am](https://cloud.githubusercontent.com/assets/4325127/6171747/a56d352e-b2aa-11e4-8ba1-164a33d6fee8.png)

**Comment by lukasbestle** [comment]
Your editor is trying to open the file as binary. You need to switch to UTF-8 to make the actual bytes visible.

**Comment by ian-cox** [comment]
hmm, was going to put the output on pastbin but I cant seem to copy these NULL characters.

![screen shot 2015-02-12 at 11 58 04 am](https://cloud.githubusercontent.com/assets/4325127/6172401/8f7afa0e-b2ae-11e4-9f3e-0e9abe878cac.png)

**Comment by ian-cox** [comment]
Here's the downloaded jpg if that is helpfull. http://drop.iancox.com/files/jpeg.zip

**Comment by lukasbestle** [comment]
Hm, that actually looks like a JPEG (you can find the magic number `JFIF` in there, also it's binary and contains information about the image), so there doesn't seem to be any evidence of reading or transmitting issues.
Have you verified that the original image is not already corrupted?

**Comment by ian-cox** [comment]
I've tried it with both JPG's and PNG's. The original file before upload opens fine, the file can be rendered to the page in my template as an image as well as be cropped using kirby's thumb() utility. I can drag the image from the web back to my desktop and it behaves normally. Its only after it is downloaded via forced headers that the image breaks. ``f::download`` or ``download()`` Thanks for your insight!

**Comment by lukasbestle** [comment]
Hm, that's a difficult problem. I'm afraid I can't find the issue right now.

**Comment by ian-cox** [comment]
No problem, I'm going to do some more digging around. Thanks for your help.

**Comment by bastianallgeier** [comment]
@ian-cox @lukasbestle I was thinking that it could maybe be an issue of some hidden characters being included somewhere. Do you have any plugins or third party tags included in the project? I just recently saw issues related to some weird commenting going on in a tags file, which broke sessions because of generating unwanted output.

**Comment by ian-cox** [comment]
On Wed, Feb 18, 2015 at 7:54 AM,  Bastian Allgeier <notifications@github.com> wrote:            @ian-cox @lukasbestle I was thinking that it could maybe be an issue of some hidden characters being included somewhere. Do you have any plugins or third party tags included in the project? I just recently saw issues related to some weird commenting going on in a tags file, which broke sessions because of generating unwanted output.

**Comment by ian-cox** [comment]
WOW, I don't know why I didn't think of this sooner.
The MinifyHTML plugin I've been playing with is minifying the output before headers are sent and before the file is downloaded effectively destroying the image.

Seems so obvious now!!
Also makes sense as to why the HTML file downloaded and opened fine.

Apologies, I should have seen that coming. :)

Thanks!
