### ISSUE TITLE
[Panel] Behavior of files sorting to switch to upload in Edge browser

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1973]
You can't hold and drag the picture in Chrome. However, you need to click on the `handle` (#icon-sort) for sort.

But you can drag and drop the picture on the Edge and when you drop it, it loads a file in the `.url` extension.

**To Reproduce**

1. Download starterkit
2. Login panel with Edge Browser
3. Enter an album `/panel/pages/photography+sky`
4. Drag (over the image, not from handle) any image and drop same field area

**Screencast (8.07MB)**

![dragdrop](https://user-images.githubusercontent.com/3393422/62474907-9b57ef00-b7ac-11e9-8773-3a954ae0f650.gif)

**Kirby Version**
3.2.2

**Console output**
No any error.

**Desktop**

 - Windows 10
 - Microsoft Edge 44.17763.1.0
 - Microsoft EdgeHTML 18.17763

**Comment by bastianallgeier** [comment]
✅
