### ISSUE TITLE
Repeatable fields feature

### ISSUE THREAD

**Issue by byybora** [getkirby/kirby#198]
Does `Repeatable Fields` feature is considered in the next versions or v2.1? It would be better!

**Something like that:**

![screenshot-details-repeatable-reordered-fields](https://cloud.githubusercontent.com/assets/3393422/6173804/4d3cc826-b2f3-11e4-8195-a6369fa15d7d.png)

**Comment by lukasbestle** [comment]
What do you mean by that?

**Comment by byybora** [comment]
Somethink like that:

![screenshot-details-repeatable-reordered-fields](https://cloud.githubusercontent.com/assets/3393422/6173804/4d3cc826-b2f3-11e4-8195-a6369fa15d7d.png)

Example usage areas: Todo list, listing for everything, features, etc...

**Comment by lukasbestle** [comment]
Hm, couldn't that be implemented using the structure field already?

**Comment by byybora** [comment]
I thought that structure field type is static. I looked deeply again, exactly what I'm looking :+1: 

Thanks @lukasbestle

**Comment by lukasbestle** [comment]
You are welcome! :)
