### ISSUE TITLE
page.changeStatus:before hook position param issue on drafts and unlisted

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1982]
https://getkirby.com/docs/reference/plugins/hooks/page-changestatus-before

```
return [
    'hooks' => [
        'page.changeStatus:before' => function ($page, $status, $position) {
            // your code goes here
        }
    ]
]
```

If you try to use `page.changeStatus:before` hook like in the document, you will get following error on changed page status to `draft` or `unlisted`

> Too few arguments to function Kirby\Cms\App::{closure}(), 2 passed and exactly 3 expected

Because draft and unlisted pages have no `position` and doesnt send this param as you can see following methods:

https://github.com/getkirby/kirby/blob/80b69380e672565a849037232c9951d1e32774c8/src/Cms/PageActions.php#L178

https://github.com/getkirby/kirby/blob/80b69380e672565a849037232c9951d1e32774c8/src/Cms/PageActions.php#L219

**Kirby Version**
3.2.3

---

We can solve this issue with two ways:

**1. Update the document with position variable assigned null param like that:**

```
return [
    'hooks' => [
        'page.changeStatus:before' => function ($page, $status, $position = null) {
            // your code goes here
        }
    ]
]
```

_This seems sufficient, but if you want to have a standard in parameters, check out the second option._

**2. Send position param as null while trigger the event:**

```
$page = $this->commit('changeStatus', [$this, 'draft', null], function ($page) {
    return $page->unpublish();
});

$page = $this->commit('changeStatus', [$this, 'unlisted', null], function ($page) {
    return $page->publish()->changeNum(null);
});
```

**Comment by bastianallgeier** [comment]
✅
