### ISSUE TITLE
Pressing Spacebar in a Multiselect Panel Search Box Clears Search

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1983]
**Describe the bug**
In a Blueprint's `multiselect` field, if you have results like `Foo Example` and you search for `foo` then press the `spacebar` key, the search field will be cleared out.

Happens in Safari and Chrome.

**Kirby Version**
`3.2.3`

**Desktop (please complete the following information):**
 - OS: macOS 10.15 Beta (19A526h)
 - Safari 13.0 (15608.1.37)
 - Chrome 76.0.3809.100

**Comment by bastianallgeier** [comment]
✅
