### ISSUE TITLE
[Panel] Redirect to parent page does not work for deleting page with depth > 2

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1984]
https://github.com/getkirby/kirby/issues/861 Still continue the issue with wrong redirect path.

**Describe the bug**
When you delete the last of the pages with 3 depth does not return to the parent.

**To Reproduce**

1. Create pages with 3 depths
    - Level 1
      - Level 2
        - Level 3
     
2. Delete the Level 3 page
3. Redirecting to panel dashboard instead of parent.

**Expected behavior**
Redirecting to parent page as Level 2.

**Kirby Version**
3.2.3

**Console output**
No console output.

**Comment by bastianallgeier** [comment]
✅
