### ISSUE TITLE
Problem with Translating URLs

### ISSUE THREAD

**Issue by adrianolaru** [getkirby/kirby#199]
I'm working at a multi-language site and i think there's a problem with the way the the URL are working. For example, let's say we have 2 languages, en and de, and en is the default one. 

In code we're using things like page('projects') where 'projects' is the '/projects' url for en, the default language. We can easily change the url for de language, because that automatically ads an Url-Key and the name of the directory is still 'projects' so the code works.

But, if we change the projects url for default language ('en') that automatically changes the directory name, and our code breaks because page('projects') no longer works.

Is there something I can do to overcome this issue?

Thanks.

**Comment by bastianallgeier** [comment]
That's actually not a bug, but how Kirby works in general. You can consider the directory path within the content folder the id of a page. If you change that and the path/id is somewhere hard coded in your templates, you have to change it there as well.

**Comment by adrianolaru** [comment]
Bastian, 

I think the problem is that the id of the page == url page for default language. 

Let me give you an example. Let's say we have a "projects" page. If I want to show a few projects on the home page (latest projects") I need to get to the "projects" page somehow, so I'll use the id of the page which is, in our case "projects".

```
page("projects")->files ...
```

But because the id is also the url of the page for default language, the user of the panel, can easily change it from Change the URL link in the panel. And that will brake the code.

Is there another way to get to the "projects" page?

**Comment by lukasbestle** [comment]
Unfortunately not directly. That's just how Kirby works.
What you can do is the following:

- Create a new field for that projects page (let's assume you name it `role`) and set it to `projects`.
- Don't try to find the projects page by UID but instead by querying for this field: http://getkirby.com/docs/cheatsheet/pages/findBy (example: `pages()->findBy('role', 'projects')`)
- No matter what the page UID is, you will find the page.

**Comment by bastianallgeier** [comment]
Making the URL of the standard language translatable as well does not make much sense in my opinion, but I think the Panel definitely needs a way to block the option to change the URL in general. I think I even have this on my todo list somewhere :) But I'll move it further up now.

**Comment by adrianolaru** [comment]
IMO, blocking the option of changing the url for the default language because of a technicality is a bit too much. 

Maybe a better way is to use the directory name as the ID of the page, and use the "url-key" for the url itself, which by default, will be the same as the id. If the user changes the url, it changes the url-key.

**Comment by lukasbestle** [comment]
So you say that the user should be able to set a "language-specific" URL for the default language as well and if that exists, Kirby should use that?

That's a great idea in general, but very complicated for sites without multi-language support. In this scenario, the Panel would always need to present access both "types" of URLs to the user, which is not that great given that the current approach is very DRY (nothing is defined at two places) and simple to understand.

What about the possible solution I posted? Does that work in your situation and solve your specific problem?

**Comment by adrianolaru** [comment]
It solves my problem but creates another. The client can't change the url. :(



—
Adrian

**Comment by lukasbestle** [comment]
What do you mean by that? Using this approach, the client will be able to change the URL.

**Comment by adrianolaru** [comment]
Sorry Lukas, my bad. Yes, your solution works. Thank you.




P.S. I've replied from my phone's email client and I was ref to Bastian's solution.






—
Adrian

**Comment by lukasbestle** [comment]
> I've replied from my phone's email client and I was ref to Bastian's solution.

Ah, alright.

> Yes, your solution works. Thank you.

You are welcome. :)
