### ISSUE TITLE
Translation for `error.access.view` missing

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1997]
**Describe the bug**
When trying to access the `users` view or a subview via URL, the error message `error.access.view` pops up. It has abviously no translations into any languages.

**To Reproduce**
1. Log in to Panel with a user without access to the `users` view.
2. Call `$user->panelUrl()` from a template or enter the Url to the users view or a single user manually

**Expected behavior**
A proper error message should be shown

**Screenshots**

**Kirby Version**
Tested with 3.2.3.

The error message is thrown here (`/kirby/panel/src/config/auth.js`

```
    if (access[to.meta.view] === false) {
      store.dispatch("notification/error", {
        message: Vue.i18n.translate("error.access.view")
      });

      return next("/");
    }
```

**Comment by distantnative** [comment]
Should be `error.access.panel`:

```json
  "error.access.panel": "You are not allowed to access the panel",
```

**Comment by bastianallgeier** [comment]
✅
