### ISSUE TITLE
[Panel] Tabs are displayed full width

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1999]
**Describe the bug**
Tabs in the Panel are displayed full width instead of left aligned.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/25466/62857668-80c7cd80-bcf8-11e9-8868-4b3683aad50c.png)

**Kirby Version**
Kirby 3.2.3

**Comment by bastianallgeier** [comment]
✅
