### ISSUE TITLE
Content locking stalling local dev server

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#2000]
**Describe the bug**
For testing purposes I had a lot of panel tabs open and the sheer amount of lock requests was stalling my local dev server.

In a test on my machine I had around 15 panel tabs open. At this time the response time was around 3-5s. After closing all tabs (red line) except one the response time dropped to around 400-500ms.

![62860120-71984e00-bcff-11e9-8740-eb4082fd29c1](https://user-images.githubusercontent.com/10027897/62862040-811a9580-bd05-11e9-92cc-5d3d4d93c41b.png)
Since this is probably just an edge case in local development a simple config setting could suffice to disable the locking mechanism.

Another idea would be to make use of the [visibility api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API?redirectlocale=en-US&redirectslug=DOM%2FUsing_the_Page_Visibility_API) to enable or disable the lock polling depending on the tab visibility. But this could potentially cause other issues.

**Kirby Version**
3.2.2

**Desktop**
 - Windows 10
 - Local PHP Server
 - Firefox

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
I get error about content locking while change the page slug:

![image](https://user-images.githubusercontent.com/3393422/65079143-2846b880-d9a7-11e9-9dcc-ed8b92937152.jpg)

> code: 500
> details: []
> exception: "Error"
> file: "/test/kirby/3.2.5/kirby/src/Cms/PageActions.php"
> key: null
> line: 103
> message: "Call to a member function remove() on null"
> route: "pages/([a-zA-Z0-9\.\-_%= \+\@\(\)]+)/slug"
> status: "error"
> __proto__: Object
> 

https://github.com/getkirby/kirby/blob/3.2.5-rc.1/src/Cms/PageActions.php#L103

Also we need check out:
https://github.com/getkirby/kirby/blob/3.2.5-rc.1/src/Cms/FileActions.php#L55
https://github.com/getkirby/kirby/blob/3.2.5-rc.1/src/Cms/FileActions.php#L218

**Comment by distantnative** [comment]
@afbora Can you create a new issue for that. I think it's not directly related. Thanks
