### ISSUE TITLE
Bug with initial translated content

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#2001]
**Describe the bug**
Under certain conditions translated content files contain not translatable fields.

**To Reproduce**
1. Install the startkit
2. Add a second language
3. Make some fields not translatable (e.g. the `date` and `author` field in the `note` blueprint)
4. Navigate to a note in the panel and switch to the secondary language
5. Edit the `title` **or** change the `slug`
6. The created content text file will include both the `date` and `author` field

As far as I can tell this bug only occurs if you just change the `title` or `slug` of a not yet created translation. As soon as you save any "real" fields the content file gets sanatized as expected.

**Expected behavior**
The `date` and `author` field should not end up in the translated content file.

**Kirby Version**
3.2.3

**Desktop (please complete the following information):**
 - Windows 10

**Comment by distantnative** [comment]
Initial thought: sounds like the non-translatable field values still end up in the Vuex store and are written as content file anyways, when triggering changeTitle or changeSlug.

**Comment by lukaskleinschmidt** [comment]
Actually I don't think this is a vue problem at all. As far as I remember the problem I found was that the content only gets sanatized when editing content fields (using the `update()` and in the end the `save()` method with `$overwrite = true`).
The `changeSlug()` or `changeTitle()` methods don't handle sanatization at all and so the not translated fields end up (do net get sanatized afterwards) in the content file when the file gets created.

**Comment by bastianallgeier** [comment]
✅
