### ISSUE TITLE
Image tag doesn't include path to file when uploading to a different page in textarea

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2003]
**Describe the bug**
Consider a textarea definition like this:

```
text:
  type: textarea
  uploads:
    parent: page.parent
```

The files are uploaded to the parent page correctly, but the resulting image tag only contains the filename, not the needed path to the file, resulting in wrong image URLs.

**To Reproduce**
1. Add the above field to a subpage blueprint, e.g. `album.yml` in the Starterkit.
2. Open a page with this blueprint in the Panel
3. In the textarea field, upload an image.
4. See how the image tag only contains the filename.

The same happens when selecting a file from another page, while the path is inserted correctly when dragging & dropping a file from a files section.

**Expected behavior**
The image tag should include the path to the file.

**Kirby Version**
Tested with 3.2.3

**Comment by distantnative** [comment]
So the expected behavior would be relative image name when on the same page, but full URL for images-files not on the same page. Correct?

**Comment by texnixe** [comment]
When on the same page, the filename as is currently the case is correct. The expected behaviour is to have the same result as when you drag and drop an image from a files section. I.e. the ID of the file, not the URL.

**Comment by bastianallgeier** [comment]
✅
