### ISSUE TITLE
Plugins media files returns a 404

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#2005]
**Describe the bug**
In the panel, the plugins `index.js` and `index.css` files return a 404 resulting in the code not being interpreted by the browser. Accessing the URLs directly properly returns the files content though.

Apparently this is caused by the files not existing on the disk at `media/plugins/index.(js,css)`. Creating these files manually fix the issue.

**To Reproduce**
Please ask me accesses to the website on Slack.

**Expected behavior**
The panel plugins media files should be written on the disk when accessed for the first time.

**Screenshots**
Here you can see the requests returning a 404 but the actual response content being correct:

<img width="1313" alt="requests" src="https://user-images.githubusercontent.com/793344/63151169-28027880-c009-11e9-97af-03521404f247.png">

**Kirby Version**
3.2.3

**Console output**
No errors in the console.

**Desktop:**
 - OS: MacOS
 - Browser: Firefox
 - Version 68

**Additional context**
- Nginx
- Multilingual
- Custom folder structure (in a `public` directory):

```php
<?php

include '../vendor/autoload.php';

$kirby = new Kirby([
  'roots' => [
    'index'    => __DIR__,
    'base'     => $base = dirname(__DIR__),
    'content'  => $base . '/content',
    'site'     => $base . '/site',
    'storage'  => $storage = $base . '/storage',
    'accounts' => $storage . '/accounts',
    'cache'    => $storage . '/cache',
    'sessions' => $storage . '/sessions',
  ]
]);

echo $kirby->render();
```

This bug follows #1901 which was supposed to be fixed in 3.2.3

**Comment by bastianallgeier** [comment]
As we discussed on Slack it was a server config issue.

**Comment by LeBenLeBen** [comment]
Yes, indeed, thanks again!

The location block causing the error was:

```
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }
```

Modifying it like this fixed the issue:

```
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";

        try_files $uri $uri/ /index.php$is_args$args;
    }
```
