### ISSUE TITLE
Switching pages causes select/checkbox/radio fields to briefly highlight as invalid

### ISSUE THREAD

**Issue by helllicht** [getkirby/kirby#2007]
### Describe the bug
When switching pages in the panel (for example by using the left/right navigation to switch between sibling pages or by navigation to parent or child page) all fields of type radio/checkbox/select are highlighted as "invalid" just before the pages switches. So it's only there for a brief moment. 

Important to mention that this happens **although** the fields are not required and filled out.
Also, when switching away and back to the page, the fields will still not show up as invalid – because they aren't. The "flashing" only appears in the split second before switching away.

### To Reproduce
1. Add any field with the afflicted field types (select / checkbox / radio) to a page blueprint
2. Navigate away from the page, e.g. to a sibling page with same blueprint
3. See "flashing" of afflicted fields with "error" style (see screenshot above)

### Expected behavior
Prior to Kirby 3.2.(3) switching pages did not result in the behavior described above. The fields should not validate as "invalid" if they aren't.

### Screenshots
![Bildschirmfoto 2019-08-16 um 13 48 27](https://user-images.githubusercontent.com/3918898/63165771-a91f3700-c02c-11e9-956d-644e02ccc7d7.png)

### Kirby Version
3.2.3

**Comment by bastianallgeier** [comment]
✅
