### ISSUE TITLE
unrolling nonexisting options yields parent

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#2008]
**Describe the bug**
unrolling an option that does not exist seems to yield last valid parent.

**To Reproduce**
1. create a plugin with options
2. do **not** add option `alexander.the.great`
3. do add option `'alexander' => 'not great yet'`
4. in template call `$alexander = option('alexander.the.great');`

**Expected behavior**
i expected `is_null($alexander) == true` but it return the string `not great yet`.

**Kirby Version**
3.2

**Comment by afbora** [comment]
I tracked this down and this issue about following 96. line of A class:

https://github.com/getkirby/kirby/blob/master/src/Toolkit/A.php#L96-L98

```
if (isset($array[$currentKey]) === true) {
    return static::get($array[$currentKey], implode('.', $keys), $default);
}
```

Index exists but it's not array just value. So always returns founded last value. 

We can solve this checking founded index is array with the `is_array()` method that i have tested:

```
if (isset($array[$currentKey]) === true && is_array($array[$currentKey])) {
    return static::get($array[$currentKey], implode('.', $keys), $default);
}
```

**Comment by bnomei** [comment]
@afbora i am not sure about using `and` in php is such a good idea unless you know exactly what it does. it is not the same as `&&` [in all cases](https://stackoverflow.com/questions/4502092/php-and-or-keywords).

```
// --------------------
// "&&" has a greater precedence than "and"

// The result of the expression (true && false) is assigned to $g
// Acts like: ($g = (true && false))
$g = true && false;

// The constant true is assigned to $h before the "and" operation occurs
// Acts like: (($h = true) and false)
$h = true and false;
```

**Comment by afbora** [comment]
@bnomei Absolutely, you right!

**Comment by bastianallgeier** [comment]
✅
