### ISSUE TITLE
Send email with transport props

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2009]
In my application, the transport values are updated from the panel by the user. 
So I'm dynamically sending transport values.
But the transport values are overwritten without checking the index. 

Can we fix this?

```
$kirby->email([
  'template' => 'media',
  'data' => [
    'name' => 'Peter',
    'text' => 'welcome to our wonderful email list'
  ]
], [
    'transport' => [
        'type' => 'smtp',
        'host' => 'smtp.server.com',
        'port' => 465,
        'security' => true,
        'auth' => true,
        'username' => '...',
        'password' => '...',
    ]
]);
```
Related line: https://github.com/getkirby/kirby/blob/master/src/Cms/Email.php#L43

Just to give an idea, it might look like this:

```
// Check transport option exists
if (isset($this->props['transport']) === false) {
    $this->props['transport'] = $this->options['transport'] ?? [];
}
```

**Comment by distantnative** [comment]
I consider this a minor bug. We should indeed first check if  the prop isn't set directly before using the option.

**Comment by bastianallgeier** [comment]
✅
