### ISSUE TITLE
Turn off coveralls result posts on PRs

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#202]

**Comment by distantnative** [comment]
Should be turned off now.

**Comment by distantnative** [comment]
Nope, still getting the comments.

**Comment by bastianallgeier** [comment]
Weird! The setting is definitely off. It's not a big deal though. I can always pass the check.

**Comment by distantnative** [comment]
I just find it a little annoying with Github notifications and spamming the Github Slack channel.

**Comment by bastianallgeier** [comment]
That's true. I just don't really know how to switch it off :(

**Comment by distantnative** [comment]
Apparently we both did not hit save XD

**Comment by bastianallgeier** [comment]
Really? LOL!
