### ISSUE TITLE
New created user cannot be impersonated

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#2021]
**Describe the bug**
After creating a new user, the internal users cache is not updated. This makes is impossible to impersonate as the new user, until the page has been reloaded.

**Example plugin code**
```php
$user = $kirby->users()->create([
    'name'  => 'Super User',
    'email' => 'superuser@getkirby.com',
    'password' => md5(microtime(true)),
]);

$kirby->impersonate('superuser@getkirby.com');
```

**Expected behavior**
Kirby should impersonate as the new user and the user should appear in the collection, when calling `$kirby->users()`.

**Kirby Version**
3.2.2

**Console output**
A `Kirby\Exception\NotFoundException` is thrown, when trying to impersonate as the new user.

**Comment by bastianallgeier** [comment]
✅
