### ISSUE TITLE
`fnmatch` not available on all systems

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2024]
**Describe the bug**
It seems that the `fnmatch()` function used in `/kirby/src/Toolkit/Mime.php` in the `isAccepted()` method is not available everywhere, see forum post: 

https://forum.getkirby.com/t/call-to-undefined-function-kirby-toolkit-fnmatch-on-image-upload-remote-not-local/15351/3

Question is if we add this as a requirement to the docs or replace it with `preg_match()`like in this [Drupal issue](https://www.drupal.org/project/drupal/issues/2620576).

**Comment by lukasbestle** [comment]
To be honest I think that replacing `fnmatch()` with an implementation based on `preg_match()` really isn't worth it – it will most likely have edge-cases that don't work, so it doesn't make much sense to have it for the very few cases where Kirby is used on a non-POSIX system. Also it is possible to polyfill this with a plugin.

Like @bastianallgeier suggested, we should probably add the following to the requirements section in the docs:

> - server operating system with support for POSIX (e.g. Linux)
