### ISSUE TITLE
Thumbnail hook

### ISSUE THREAD

**Issue by puckey** [getkirby/kirby#203]
I want to sync the thumbnail images created by Kirby to Amazon S3 in order to use their CloudFront CDN service. I have written this as a little plugin using Amazon's PHP SDK.

My only problem is that I have to be able to tell if a new thumbnail was created or not, in order to know whether I should upload it to S3.

As far as I can see there isn't a way for me to hook into this, or is there?

I see the Thumb class has the isThere() function which is used to check whether their was already a thumbnail, but since the thumbnail is already created in the constructor, my code could never tell if the thumbnail was there or not.

Is there any chance we could have something like a wasThere() function?

**Comment by bastianallgeier** [comment]
I think the best way for now would be to extend the Thumbnail class and write your own cdnThumb() helper or something like that. It would of course not work in the panel, but for all frontend stuff. I will try to make the class more flexible in the first place in future versions.

**Comment by puckey** [comment]
Sounds like a plan - thanks!
