### ISSUE TITLE
Option to define smartypants on a per language basis missing?

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2037]
**Describe the bug**
I would have expected that it is possible to set smartypants on a per language basis in the language configuration files:

```
<?php

return [
    'code' => 'de',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'de_DE'
    ],
    'name' => 'Deutsch',
    'translations' => [

    ],
    'url' => NULL,
    'smartypants' => [
        'doublequote.open' => "start",
        'doublequote.close' => 'stop',
    ],
];
```

But this doesn't have any effect, it only works when configuring smartypants in the config, but then obviously without language specific settings.

**Expected behavior**
It should be possible to define language-specific smartypants options. Wrong syntax or not possible. Studying the source code it looks as if this feature is not implemented.

**Kirby Version**
Tested with 3.2.3

**Comment by bastianallgeier** [comment]
✅
