### ISSUE TITLE
Non-admin user cannot create any other users anymore if there is no other role but admin role

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2038]
**Describe the bug**
When creating a new Editor role (but no other roles) without any settings, this user cannot create new users.

In this case the role radio does not show up and trying to create a user fails. I assume that the default role in this case falls back to admin, making it impossible to create new users. When I add a second role, the role selector reappears and creating users with any of those roles becomes possible again.

**To Reproduce**
1. Create a new Editor role without any settings
2. Create a new user with this role.
3. Log in to the Panel with this user
4. Try to create a new user
5. See error message ("You are not allowed to create this user").

**Expected behavior**
While it makes sense that the role selector is not shown when there is only one non-admin role, the role should be set to this non-admin role by default and the user created.

<img width="481" alt="Bildschirmfoto 2019-08-25 um 21 28 45" src="https://user-images.githubusercontent.com/5312492/63654805-835a0680-c77f-11e9-9cdd-f0391a6df579.png">

**Kirby Version**
Tested with 3.2.3 and 3.2.4-rc1

**Console output**

<img width="577" alt="Bildschirmfoto 2019-08-25 um 21 29 10" src="https://user-images.githubusercontent.com/5312492/63654795-6e7d7300-c77f-11e9-9753-ce34173386e4.png">

**Additional context**

**Comment by texnixe** [comment]
See also:

https://github.com/getkirby/kirby/issues/1917

**Comment by bastianallgeier** [comment]
✅
