### ISSUE TITLE
Image Preview in Structure Field uses full image size

### ISSUE THREAD

**Issue by thathoff** [getkirby/kirby#2039]
When using images in a structure the preview uses the original file instead of the resized image (eg. used in the files list). So creating structures with a some large images (eg. 10mb, 4000x6000 pixels each) will make the panel very slow.

Maybe I haven’t found the right option but event settings the `image` property with the option ` size: tiny` for this column the panel still uses the large image.

**Comment by texnixe** [comment]
You could create your own files field preview as a workaround: 

https://getkirby.com/docs/reference/plugins/extensions/field-previews

**Comment by thathoff** [comment]
Yes I've thought about this, too (sorry for not mentioning it in the issue). Maybe we’ll fix it this way until it’s fixed in Kirby. Thank you!

**Comment by bastianallgeier** [comment]
✅
