### ISSUE TITLE
$collection->sortBy() does not sort by 'desc' by default

### ISSUE THREAD

**Issue by puckey** [getkirby/kirby#204]
According to the cheatsheet, calling $collection->sortBy('property') sorts in descending direction. As far as I can tell it orders in ascending direction.

I would propose to change the documentation, since sorting alphabetically (which most people need to do) should happen ascending.

The docs are here: http://getkirby.com/docs/cheatsheet/files/sortBy

**Comment by bastianallgeier** [comment]
I moved this to the site issues: https://github.com/getkirby/getkirby.com/issues/145
