### ISSUE TITLE
Range Field Has Unexpected Display with Missing Value

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2044]
**Describe the bug**
In the Panel, the `range` field surprised me with the way it handles having no value set (like if creating a new page without a default value, or adding the field to an existing page).

For example,
```yaml
ratingValue:
  label: Rating Value
  type: range
  min: 0
  max: 5
  tooltip:
    after: '★'
  width: 1/3
```

Looks like this when there's no saved value:
<img width="292" alt="Screen Shot 2019-08-28 at 11 19 59 AM" src="https://user-images.githubusercontent.com/417182/63882207-63486400-c986-11e9-84a3-a586b074fd58.png">

**Expected behavior**
If `0` is part of the possible range of values, I would expect the range slider to _appear_ to be positioned where 0 would be (but still display the `-` dash).

My rationale: I assume most uses of a range value involve `->toInt()` or `->toFloat()` and an empty value would mean it's returning `0` or `0.0`. In the example above, it looks like the default value is "3".

However, if `0` isn't within the allowed range, then I suppose sticking the slider in the exact middle is as valid as any other place.

Regardless of placement: maybe the knob itself should be semi-transparent to indicate that it's not "really" set to the value at that spot.

**Kirby Version**
`3.2.3`

**Desktop (please complete the following information):**
 - OS: macOS 10.15 Beta (19A536g)
 - Safari 13.0 (15608.2.2)

**Comment by bastianallgeier** [comment]
✅
