### ISSUE TITLE
Using .split in an options query shows a brief error when saving in the panel

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/kirby#2045]
I have some select fields that query a tags field on site.yml with `query: site.categories.split`. When I save or reload the panel page, these fields briefly show the error `Cannot read property 'split' of null`. It has no impact otherwise, but it puzzles my clients.

**Comment by afbora** [comment]
Could you share reproduce blueprint and Kirby version?
I have tested tags field with null data and non exists property but no error.

**Comment by philipmarnef** [comment]
To be clear: it's not a persistent error: it only shows briefly while updating the panel vue components and only when that process takes longer than microseconds.
I can't reproduce it immediately, I'll update when I have more specifics. 

But I'm thinking now it's got nothing to do with the tags query but with panel columns, because column widths are parsed with split. And I remember getting a 'split' error with wrongly formatted column width properties once.

**Comment by distantnative** [comment]
@philipmarnef Would still be helpful if you could share the whole blueprint then :)

**Comment by philipmarnef** [comment]
@distantnative Definitely, but I'm not sure _which blueprint_ yet — haven't been able to reproduce it since...

**Comment by philipmarnef** [comment]
Update: could finally reproduce it and it's the markdown plugin field, ~~so I'll file an issue there~~ [there already is an issue](https://github.com/sylvainjule/kirby-markdown-field/issues/81).

Sorry for the false alarm.
