### ISSUE TITLE
$field->toStructure() throws an exception when the field value is invalid

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2046]
The error I'm getting is:

>Argument 1 passed to Kirby\Cms\StructureObject::setContent() must be of the type array or null, string given, called in C:\xampp\htdocs\ikarov\kirby\src\Toolkit\Properties.php on line 138

In the debugger, I saw this came from a `toStructure()` call:

![image](https://user-images.githubusercontent.com/5570098/63957759-b529e080-ca91-11e9-9204-b8189a50b64f.png)

This was very tricky to debug because `toStructure()` is called by a plugin. When you save the default translation, the plugin syncs the structure data with all other translations. Each entry had an `options` field of type `tags` which is a comma-separated string. When I changed the blueprint of that field to `structure`, this error began to appear because the saved value was not a YAML-encoded structure.

**To Reproduce**
1. Have a _site.txt_ with arbitrary string as content.
2. Run `$site->title()->toStructure()`

**Expected behavior**
Whenever `toStructure()` is called with invalid data, it should return an empty structure. Then, when the value is saved, whatever invalid value existed before would be replaced with a valid one.

**Kirby Version**
3.2.3

**Comment by bastianallgeier** [comment]
✅
