### ISSUE TITLE
Textarea Spellcheck Now Disabled by Default (3.2.4-rc.1 Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2047]
**Describe the bug**
In 3.2.4-rc.1, a spellcheck option was added to `textarea` fields. However, it defaults to `false` which feels like a regression to `3.2.3` and before because browsers would enable spellcheck by default.

I honestly think spellcheck should be enabled by default for `textarea` fields. I assume most use cases for `textarea` are for passages of text that editors would assume should be spellchecked.

I'm not thrilled to have to go through all my Blueprints and add `spellcheck: true` to every `textarea` field.

**Expected behavior**
Either:
- Spellcheck enabled by default
- This feature saved for a major release
- A global option to enable spellcheck for all `textarea` fields

**Kirby Version**
`3.2.4-rc.1`

**Desktop (please complete the following information):**
 - OS: macOS 10.15 Beta (19A546d)
 - Safari 13.0 (15608.2.5)

**Comment by bastianallgeier** [comment]
I agree that this is a regression. I'm already working on a fix.

**Comment by bastianallgeier** [comment]
✅
