### ISSUE TITLE
Media files not found in multisite setup (or possibly when moving them, not tried)

### ISSUE THREAD

**Issue by bcevc** [getkirby/kirby#2048]
**Describe the bug**
When running a multisite setup, Kirby still only searches for Javascripts and other files located in the media folder in the root directory media folder, thereby generally breaking the panel (possibly more, unknown).

**To Reproduce**
1. Start with plainkit
2. Setup a multi site setup according to https://getkirby.com/docs/cookbook/setup/multisite and move the plainkit's content, media and site folders to a subdirectory in accordance with the documentation mentioned
3. Open the panel, the page loads but stays white as the javascripts do not load (in my setup, when opening the javascript URLs, the browser displays kirby's error page.

**Expected behavior**
All media files should be loaded from the folder set in index.php.

**Screenshots**
not applicable

**Kirby Version**
3.2.3

**Console output**
`The script from “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/plugins.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
The script from “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/vendor.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
The script from “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/app.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
The script from “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/vendor.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
Loading failed for the <script> with source “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/vendor.js”. site:440:1
The script from “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/plugins.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
Loading failed for the <script> with source “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/plugins.js”. site:439:1
TypeError: panel.plugin is not a function
index.js:1:268337
The script from “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/app.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
Loading failed for the <script> with source “https://example.com/media/panel/594663875f34563eccad2ac626416af8/js/app.js”.`

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser Firefox 68.0.2

**Smartphone (please complete the following information):**
not tested

**Additional context**

There are two forum discussions (one describing exactly my case and another one possibly related):
https://forum.getkirby.com/t/multi-page-setup-and-issues-with-panel/15451/4
https://forum.getkirby.com/t/cant-load-panel-of-multi-site-setup-after-upgrading-to-3-2/15411
https://forum.getkirby.com/t/multi-page-setup-and-issues-with-panel/15451/4

**Comment by texnixe** [comment]
@bcevc beat me to it: https://github.com/getkirby/kirby/issues/2049

**Comment by bastianallgeier** [comment]
The problem is actually not in the code, but in the cookbook article. Everything in the media folder has to be accessible at `DOCUMENT_ROOT/media`. If that's not the case, like in this setup, the URL has to be adjusted as well. I.e. 

```php
$kirby = new Kirby([
  'roots' => [
    'media' => __DIR__ . '/media/test'
  ],
  'urls' => [
    'media' => 'http://yourdomain.com/media/test'
  ]
]);
```
