### ISSUE TITLE
[Cms] Clean up packages (Toolkit, Util etc.)

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#205]
What do we really need? What packages have to be finished before release? Which ones could be excluded from 3.0 but included in e.g. 31., 3.2?

- [x] Port all useful Dir methods
- [x] Write tests for the new F class
- [x] Refactor F class and Mime class types definition into one
- [x] Move everything back into the Toolkit namespace and get rid of the Util namespace (that was a stupid decision)
- [x] Create aliases for the most important Toolkit classes (A, Str, F, Dir)

**Comment by bastianallgeier** [comment]
- [ ] Port all useful Dir methods
- [ ] Write tests for the new F class
- [ ] Refactor F class and Mime class types definition into one
- [ ] Move everything back into the Toolkit namespace and get rid of the Util namespace (that was a stupid decision)
- [ ] Create aliases for the most important Toolkit classes (A, Str, F, Dir)
