### ISSUE TITLE
mulitlang/page::slug() returns different values when $lang is given and when it is not given resulting in wrong urls

### ISSUE THREAD

**Issue by luksurious** [getkirby/kirby#205]
I was just helping a friend with an issue and his multilang setup with kirby:

He had specified the `URL-Key` value for the english translation as "the_page".
When switching from German to English, the generated slug would be returned as "the-page", and a 404 is thrown.
When opening a link to the same page from a different page while being on the English page already, it would be returned as "the_page" as specified in the content file, and the page content is shown.

The reason for that is, as far as my short research has shown, that the function `multilang/Page::slug()` behaves different depending on whether `$lang` is provided or not.

If `$lang` is not provided, the `url_key` is simply returned:
```
// around line 63
      // geth the translated url key if available
      $key = (string)a::get((array)$this->content()->data(), 'url_key');

      // return the translated slug or otherwise the uid
      return (empty($key)) ? $this->uid() : $key;
```

However, when `$lang` is provided, the `str::slug()` function is invoked, which cleans the slug from any non `[A-z0-9]`:
```
// around line 85
        if($slug = a::get((array)$content->data(), 'url_key')) {
          // if available, use the translated url key as slug
          return str::slug($slug);
        }
```

IMO the function should return the same value for both cases.
As the current implementation suggests, it should not clean the slug, because if it cleans the slug, and a different `URL-Key` is provided, a 404 error is thrown.

You might want to consider DRYing that part so that both cases use more common functionality.

**Comment by bastianallgeier** [comment]
It took a while but it's finally fixed on the develop branch and will be in the next release. Thanks for your help.
