### ISSUE TITLE
[Panel] "Change Status" Dialog Loads Siblings When Unnecessary (Automatic Numbering)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2052]
**Describe the bug**
When opening a "Change Status" dialog in the Panel, it sometimes takes seconds to load. Looking at the API responses happening, I suspect its because it's loading every sibling, even though for the specific template in question, siblings seems completely unnecessary.

**To Reproduce**
1. Have a template that uses automatic numbering in the Blueprint, such as:
```yaml
num: '{{ page.created.toDate("YmdHi", "now") }}'
```
2. Within a `pages` section, click on a status change button to bring up the dialog.

The Panel loads an AJAX call such as:
```
https://thestreamable.com/api/pages/news+test-post?select=id,status,num,errors,siblings,blueprint
```

This response has hundreds of siblings (for our site). Normally the siblings would be used to indicate where the post in question should be ordered into. However, because numbering is set to automatic, the siblings are never displayed on this page are seemingly unneeded.

I think the burden of loading almost ~1500 pages is too strenuous in this situation. Can there be an optimization to exclude siblings when they're not needed? Or, at least somehow speed it up (by maybe avoid reading the text fields for actual title content).

**Kirby Version**
`3.2.4`

**Comment by distantnative** [comment]
**Developer's note:**
I tried to split the API call into two: an initial one without siblings and when `page.blueprint.num === "default"` sending a second request to get the siblings. However, I ran into problems with reactivity where either I would get an error cause `this.siblings` wasn't set yet or the UI would not update and display an empty dropdown.

**Comment by bastianallgeier** [comment]
I solved it. The problem with the select input is connected to the other open issue we have, but when you set the options before opening the dialog, it works.

**Comment by distantnative** [comment]
👍
