### ISSUE TITLE
Language locales not available in Panel Vuex store

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2054]
**Describe the bug**
I'm working on a panel plugin that needs to know all languages and their locales. Everything is present except for the `locale` value. I get the `code` value, but it doesn't work for me. I need the locale specifically.

**Expected behavior**
All data automatically generated by Kirby when a new language is created should be available in the panel, in my opinion. Everything is there except for the `locale` and `url` property (which could also be useful for some routing plugin, I guess).

**Screenshots**
![image](https://user-images.githubusercontent.com/5570098/64320264-cd848880-cfc6-11e9-8f4b-dea16797cd58.png)

**Kirby Version**
3.2.3

**Comment by afbora** [comment]
We have encountered this problem before. 
Maybe the solution way helps:

https://github.com/distantnative/retour-for-kirby/issues/91

**Comment by distantnative** [comment]
Yea I worked around that, but maybe we can actually solve this problem in the core.

**Comment by yandodov** [comment]
Well, that's not exactly a solution, I think. My plugin needs the site languages and their specified locales. If a new language is added, it should appear in my plugin with its correct locale. Yes, I could add an option to specify the locales for my plugin in `config.php`, but they're not really options. They _must_ match the site languages' locales. This would become nothing but a maintenance issue.

Currently, there is other important language information like `direction` and `name` in the Vuex store. Adding the `locale` should be just one more line of code?

**Comment by bastianallgeier** [comment]
✅
