### ISSUE TITLE
"template: image" has disappeared from files field options

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#2057]
**Describe the bug**
It was possible before to do :
```
files:
   type: files
   template: image
```
This would restrict selectable elements to only 'image' template files.
But this doesn't work anymore in the last version.
Even if we can convert this to `query: page.files.template('image')`, there should be a fallback for this deprecated option.

**Expected behavior**
This would restrict selectable elements to only 'image' template files.

**Kirby Version**
3.2.4

**Comment by afbora** [comment]
I can't reproduce on 3.2.4 with Starterkit:

**YML**:
https://github.com/getkirby/starterkit/blob/master/site/blueprints/pages/album.yml#L23-L32

```
 images:
    type: files
    layout: cards
    template: image
    info: "{{ file.dimensions }}"
    image:
        ratio: 5/4
        cover: true
    min: 1
    size: small

```

**Panel**:

![FireShot Capture 742 - Animals - Mægazine_ - http___localhost_test_kirby_2057_p](https://user-images.githubusercontent.com/3393422/64355915-b2d40300-d00a-11e9-874e-b6d7e62b5ed3.png)


**And same options with you:**

```
files:
    type: files
    template: image
```

![FireShot Capture 743 - Animals - Mægazine_ - http___localhost_test_kirby_2057_p](https://user-images.githubusercontent.com/3393422/64356620-d21f6000-d00b-11e9-9429-305c37db71ed.png)

**Comment by tristantbg** [comment]
Thank you for testing !

I just tried with the StarterKit and I get the problem.

To test :
1) Go to animals in content folder
2) Duplicate abba.jpg >>> abba2.jpg
3) Duplicate abba.jpg.txt >>> abba2.jpg.txt
<img width="774" alt="Capture d’écran 2019-09-05 à 18 28 21" src="https://user-images.githubusercontent.com/4832038/64360716-486f9280-d00b-11e9-89ec-20a26f9d6122.png">
4) Change abba2.jpg.txt with a different template than image
<img width="642" alt="Capture d’écran 2019-09-05 à 18 28 30" src="https://user-images.githubusercontent.com/4832038/64360734-59200880-d00b-11e9-9729-7089fabaa338.png">
5) Try to select an image in the panel, you can see the abba2 image and it shouldn't.

**Comment by afbora** [comment]
Now I understand the problem you're trying to explain.
But Kirby doesn't have a feature like you said.
I have tested on 3.0.3 and 3.2.4.
We could ask @texnixe for that.

----

There are 2 different elements named `files`. One [sections](https://getkirby.com/docs/reference/panel/sections/files) and other [field](https://getkirby.com/docs/reference/panel/fields/files).

1. Files field has not an option named as `template`.
2. Files section has `template` option `to listing` having template and working properly.

So you need to use `query` in `files field` as your said: `query: page.files.template('image')`

**Comment by texnixe** [comment]
@afbora is right:
A files section has a template option and it works as expected.
A files field has a query option, it never had a template option.

**Comment by tristantbg** [comment]
Alright, that makes sense.

**Comment by tristantbg** [comment]
Maybe it is confusing to use `template: image` in the starterkit on a files field if it has no effects.

**Comment by afbora** [comment]
Could you share which file or path on Starterkit?

**Comment by texnixe** [comment]
There is no files field with `template: image` in the Starterkit.

**Comment by tristantbg** [comment]
You are right... I guess I lost myself in my own mistakes.
Closing the issue, thank you all for the explanations.

**Comment by texnixe** [comment]
Well, you are not alone, the difference between sections and fields with their similar options is in fact irritating for other users as well, so it's not your fault.
