### ISSUE TITLE
[Panel] Error message when file size bigger than the upload limit

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2061]
**Describe the bug**
When file bigger than upload limit, panel throw error:

![FireShot Capture 745 - Sky - Mægazine - http___localhost_test_kirby_2058_panel_pages_photography+sky](https://user-images.githubusercontent.com/3393422/64528530-6130be80-d311-11e9-90d7-99ae05c27633.png)

**Console**

> Failed to load resource: the server responded with a status of 400 (Bad Request)

**To Reproduce**
1. Go to panel
2. Edit any page
3. Try to upload a big file (sure file size bigger than `upload_max_filesize` limit)

**Expected behavior**
The cause of the problem should be more clearly stated.

**Related issue**
https://github.com/getkirby/kirby/issues/1812

**Kirby Version**
3.2.4

**Comment by bastianallgeier** [comment]
✅
