### ISSUE TITLE
[Panel] Long empty state placeholders overflow container borders

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#2065]
**Describe the bug**
If the text for an empty state (in structure fields or pages sections) is too long, it overflows the containers borders.

<img width="483" alt="Bildschirmfoto 2019-09-09 um 18 07 25" src="https://user-images.githubusercontent.com/1512805/64547590-28064780-d32d-11e9-9a6f-939a747bb80d.png">

**To Reproduce**
1. Create a blueprint with a `structure` field.
2. Add a long text for the `empty`.

**Expected behavior**
I’d expect the empty states to work well even with multi-line texts (as displayed in the following screenshot):

<img width="484" alt="Bildschirmfoto 2019-09-09 um 18 07 13" src="https://user-images.githubusercontent.com/1512805/64547643-44a27f80-d32d-11e9-8c43-601f260061b1.png">

**Kirby Version**
`3.2.4`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 68.0.2 (64-Bit)

**Comment by bastianallgeier** [comment]
✅
