### ISSUE TITLE
[Kirby] Implement hooks

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#207]
- [x] Implement the Hooks class
- [x] Add hooks class to App class
- [x] Connect Hooks class with the App registry
- [x] Trigger all hooks in the right places (see table)

**Comment by bastianallgeier** [comment]
https://airtable.com/shrIgnrJaG8ExTSv2

**Comment by jenstornell** [comment]
Maybe you are already aware, but there are some issues around hooks, that can be of interest when reimplement hooks:

https://github.com/getkirby/panel/issues/1116
https://github.com/getkirby/panel/issues/904
https://github.com/getkirby/panel/issues/839
https://github.com/getkirby/panel/issues/1110

**Comment by bastianallgeier** [comment]
@jenstornell thanks for listing them here again. It looks like we should get all of your stuff covered with the current plan. Make sure to check out the airtable list.

**Comment by bastianallgeier** [comment]
I also planned to allow throwing exceptions in hooks and they will end up stopping the execution of whatever comes afterwards and will also produce nice errors in the panel. I think this will hugely benefit the usefulness — especially of all the :before hooks.

**Comment by jenstornell** [comment]
Crap!! Github just linked back here from the Kirby 2 issues. I removed the comment but it's still there. This repo is not official right?

How can we get rid of these reference!? :sweat:

**Comment by bastianallgeier** [comment]
Ha, I think we can't do much about it. I can't delete issues either. I guess that's why there are private repos :) Don't worry though. I think there won't be much traffic through those references, and if there's still someone finding this, than it's ok.
