### ISSUE TITLE
<k-select-field> not working

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2075]
**Describe the bug**
The select field doesn't appear at all unless you provide `type` and its `options` seem to not be reactive.

**To Reproduce**

1. Grab the [docs demo](https://getkirby.com/docs/reference/plugins/ui/select-field) for the select field and put it in a panel view component:

```vue
<template>
  <div>
    <k-select-field
      v-model="value"
      :options="options"
      :required="true"
      label="Select"
      name="select"
      help="This is a select field"
      @input="input"
    />
  </div>
</template>

<script>
export default {
  data () {
    return {
      value: null,
      options: [
        { value: 'a', text: 'Option A' },
        { value: 'b', text: 'Option B' }
      ]
    }
  },
  methods: {
    input () {}
  },
  created () {
    setTimeout(() => {
      this.options = [
        {value: 'new1', text: 'Hello'},
        {value: 'new2', text: 'World'}
      ]
    }, 300)
  }
}
</script>
```
2. Open the panel view and the following markup will greet you:

![image](https://user-images.githubusercontent.com/5570098/64766892-6c712d80-d54f-11e9-9e35-0a397f8130a1.png)

3. Add `type="select"` to `<k-select-field>` to make it work
4. Notice how we mimic an API call that updates the options in `create()`. Well, they are not updated. Using the Vue debug tool we can see:

`<k-input>` gets the updated options:
![image](https://user-images.githubusercontent.com/5570098/64767161-e4d7ee80-d54f-11e9-8d01-2eab27b7ed59.png)

But `<k-select-input>` inside of it doesn't:
![image](https://user-images.githubusercontent.com/5570098/64767256-105ad900-d550-11e9-9748-b56e6ff73e9b.png)

**Expected behavior**
Should work as the docs say it should and it should be reactive all the way.

**Kirby Version**
3.2.3

**Comment by yandodov** [comment]
The reactivity problem seems to stem from `<k-input>` because if I use this instead:

```vue
<k-input v-model="value" :options="options" type="select" theme="field" />
```

The result is the same - `<k-input>` receives the updated values, `<k-select-input>` inside doesn't.

**Comment by yandodov** [comment]
The `type` attribute problem doesn't seem to be limited to the select field. `<k-toggle-field>` has the same issue. `<k-text-field>` works fine, though.

**Comment by yandodov** [comment]
It doesn't work even in an `<k-form>` component where Kirby handles the field creation itself. I've currently hacked it by adding `v-if` on the form and showing it only when all data is present. I guess that `options` are simply not passed down from `<k-input>` to `<k-select-input>` in [Input.vue](https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Input.vue#L18)

**Comment by yandodov** [comment]
>The select field doesn't appear at all unless you provide `type`

It's the same for `<k-checkboxes-field>` too. You have to set `type="checkboxes"`. Unlike the select field, checkboxes' options are reactive.

**Comment by distantnative** [comment]
Let"s try the sokution proposed in: https://github.com/getkirby/kirby/issues/2181

**Comment by distantnative** [comment]
✅
