### ISSUE TITLE
collection's append() and prepend() behave differently when only one argument is provided

### ISSUE THREAD

**Issue by plagasul** [getkirby/kirby#2078]
**Describe the bug**

_Note: this issue discusses append() and prepend() methods of collection class, BUT, when following code links from the $page->append() and $page->prepend() reference pages, one leads to 'kirby/src/Cms/Collection.php' while the other leads to 'kirby/src/Toolkit/Collection.php'. I do not know the implications of this, but I assume it is correct, and those are the methods we are using when we do $pages->append($page) or prepend($page)_

The methods append() and prepend() from the collection class behave differently when only one argument (for example a page via $pages->append($page)) is provided.

append() checks if the provided element is an object, and if it is, it looks for the object's ID and uses it as key when adding the object to the data array; while prepend() uses array_unshift() effectively adding the element (object or not) without a key, so the key becomes zero (0).

[kirby/src/Cms/Collection.php](https://github.com/getkirby/kirby/blob/3.2.4/src/Cms/Collection.php#L102)

```
    /**
     * Appends an element to the data array
     *
     * @param  mixed $key
     * @param  mixed $item
     * @return Kirby\Cms\Collection
     */
    public function append(...$args)
    {
        if (count($args) === 1) {
            if (is_object($args[0]) === true) {
                $this->data[$args[0]->id()] = $args[0];
            } else {
                $this->data[] = $args[0];
            }
        } elseif (count($args) === 2) {
            $this->set($args[0], $args[1]);
        }
        return $this;
    }
```

[kirby/src/Toolkit/Collection.php](https://github.com/getkirby/kirby/blob/3.2.4/src/Toolkit/Collection.php#L709)
```
    /**
     * Prepends an element to the data array
     *
     * @param  mixed       $key
     * @param  mixed       $item
     * @return self
     */
    public function prepend(...$args)
    {
        if (count($args) === 1) {
            array_unshift($this->data, $args[0]);
        } elseif (count($args) === 2) {
            $data = $this->data;
            $this->data = [];
            $this->set($args[0], $args[1]);
            $this->data += $data;
        }
        return $this;
    }
```

**To Reproduce**
1. Append a page to a $pages object, without providing a key, and dump
2. Prepend a page to a $pages object, without providing a key, and dump
3. Compare the dumps
4. Notice in append's dump the key is the page's ID, while in prepend's dump. the key is zero (0)

**Expected behavior**
Either both work in the same way, checking for an object and looking for its key if it not provided, or neither do, and then possibly throw an Exception, as I believe K2 did.

A possible rewrite of prepend() (bear with my low php skills, please) :

```
public function prepend(...$args)
{
    if (count($args) === 1) {
        if (is_object($args[0]) === true) {
            $this->prepend($args[0]->id(), $args[0]);
        } else {
            array_unshift($this->data, $args[0]);
        }
    } elseif (count($args) === 2) {
        $data = $this->data;
        $this->data = [];
        $this->set($args[0], $args[1]);
        $this->data += $data;
    }
    return $this;
}
```

Alternatively this difference could be explained in the reference page of the methods. Right now this difference is not visible unless one checks the code, and it already confused other people than myself, see [here](https://github.com/getkirby/kirby/issues/1653).

**Kirby Version**
"3.1.2-rc.1" but the quoted code is the same in the last version in this repo

**Desktop (please complete the following information):**
 - OS: Linux Mint cinnaon 19.2

**Additional context**
[Related forum question.](https://forum.getkirby.com/t/pages-add-vs-append-and-prepend/15608/8
)

**Comment by lukasbestle** [comment]
Your findings regarding the two different implementations in the two different classes are correct. It looks like we implemented a custom `Cms` implementation for the `append()` method, but forgot (?) to do the same for `prepend()`.

Your possible solution looks pretty good already, but I think I will do some refactoring to always use the `set()` method while I'm at it. This also needs some more unit tests.

**Comment by bastianallgeier** [comment]
✅
