### ISSUE TITLE
Image skewed

### ISSUE THREAD

**Issue by dinko** [getkirby/kirby#208]
On some occasions, images in the file list appear unproportional.

![bildschirmfoto 2015-03-02 um 16 31 35](https://cloud.githubusercontent.com/assets/61015/6443784/b30665a4-c0f9-11e4-8d58-6dced339a717.png)

**Comment by bastianallgeier** [comment]
Looks like your thumb folder is not writable. There should normally be a thumbnail generated for it.

**Comment by dinko** [comment]
Ah! Thanks for the hint. It's not the folder, but something else (missing library on the live server). Thx for the lightning reply!

**Comment by bastianallgeier** [comment]
you are welcome :)
