### ISSUE TITLE
Changelog for crucial/breaking changes from v2 to v3

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#209]
Maybe you are already doing it, but on release I think most of us would need a really big changelog of every function that has changed in behavior, name or arguments.

The most important for this changelog is the core I think, because it will probably be hard to spot the changes right away. There seems to be many small changes here and there.

Because the panel is completely rewritten I don't find the changelog as important there. In the panel case I think pure docs will be the most helpful. Maybe hooks is the only feature that stick around from Kirby 2.

There will be content changes as well, especially when it comes to naming of files. Also if there was a change in how/where images will be stored.

**Comment by distantnative** [comment]
Copie dover to website/docs repo: https://github.com/k-next/getkirby.com/issues/30
