### ISSUE TITLE
'placeholder' string is removed on kirbytag parsing

### ISSUE THREAD

**Issue by puleddu** [getkirby/kirby#209]
Creating a Kirby tag to generate a form element (input text) that uses the `placeholder` attribute, results in something like the following: 

```html
<input type="text" name="email" ="Email address" />
```

Probably due to this: https://github.com/erusev/parsedown-extra/blob/master/ParsedownExtra.php#L509 
Any suggestion to get around this?

**Comment by bnomei** [comment]
yes it really does.
my hack is to add PH="Email address" and replace PH with 'placeholder' using jquery.

**Comment by bastianallgeier** [comment]
Yes, I'm afraid it's a bug in parsedown extra: https://github.com/erusev/parsedown-extra/issues/53

**Comment by maxfenton** [comment]
Note: looks like a fix will be coming soon: https://github.com/erusev/parsedown-extra/issues/53#issuecomment-148518509

**Comment by bastianallgeier** [comment]
I just added the new parsedown extra version to the develop branch and it seems to be fixed. \o/
