### ISSUE TITLE
Panel: Unsaved data indicator

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#21]
We don't know when the data is saved, if it's saved. I think an orange indicator of some kind would solve the problem. It could turn green when the content is saved and no new edits are done.

```
[Saved at 2017-11-15, 13.33]
```

or

```
[You have unsaved changes. Last save 2017-11-15, 13.33]
```

**Google Drive**

![image](https://user-images.githubusercontent.com/927011/32836705-099c58fc-ca0b-11e7-9a52-aeb8a4e5947b.png)

**Comment by distantnative** [comment]
For reference: https://github.com/k-next/panel/pull/243

**Comment by distantnative** [comment]
Ties into https://github.com/k-next/starterkit/issues/189 – I'm closing this to keep our issues focussed, but this will go into our thoughts implementing the broader feature (and GitHub will create a link over in the other issue to this one, so nothing gets lost).
