### ISSUE TITLE
Models for hyphenated blueprints

### ISSUE THREAD

**Issue by adamcbrewer** [getkirby/kirby#211]
I have a blueprint file named `project-video.php` and have created a model called `ProjectVideoPage` which extends `Page`, but the new methods aren't available. 

![screen shot 2015-03-09 at 15 51 53](https://cloud.githubusercontent.com/assets/423310/6558454/2c3babf8-c674-11e4-926c-1954081a4285.png)

Is there perhaps a different scheme of naming hyphenated blueprints/filenames?

**Comment by lukasbestle** [comment]
That's a bug. As you can see in [kirby.php](https://github.com/getkirby/kirby/blob/master/kirby.php#L363) where the models are loaded, the file name directly results in the class name. So in your case it looks for `project-videopage`, which is [not possible in PHP](http://php.net/manual/en/language.oop5.basic.php).

The mentioned line should be changed to remove punctuation.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.

**Comment by adamcbrewer** [comment]
Awesome, thanks @bastianallgeier
