### ISSUE TITLE
Simplified controllers

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#211]
In my new (yet unreleased) plugin I needed custom controllers. I simplified them similar to the config file in the patterns plugin. What I noticed was that I can use arguments without the need to declare them inside every controller.

## Old (current) controllers

Because it's a bit to write, I always copy/paste it from the docs. To make it work we need two returns, one function, one array and the arguments `$site`, `$pages` and `$page`.

```php
return function($site, $pages, $page) {
  return [
    'foo' => 'my first template variable ' . $page->title(),
    'bar' => 'my second template variable'
  ];
};
```

## New controllers

Only the returned data as array is needed.

```php
return [
  'foo' => 'my first template variable ' . $page->title(),
  'bar' => 'my second template variable'
];
```

In both examples above, I've added `$page->title()` to show that `$page` and other arguments can be sent to them.

### In the core

For the new controller to work in the core, we simply need to add some variables before the required file. Then the controller magically is aware of them.

```php
$site = site();
$page = page('about');
$pages = $page->children();

$values = require_once $controller_path;
```

What do you think?

**Comment by bastianallgeier** [comment]
We have already implemented an even better way IMHO. Automagic dependency injection! You can define what you need in the controller and Kirby will automatically pass the right objects: 

No object at all
```php
return function () {
  // super simple controller without dependencies
};
```

Just a single object
```php
return function ($page) {
  // do something with the page
};
```

Multiple objects
```php
return function ($page, $site, $kirby) {
  // do something with the page, site and kirby
};
```

Order doesn't matter
```php
return function ($site, $page, $kirby) {
  // do something with the page, site and kirby
};
```

**Comment by jenstornell** [comment]
With your new solution it would look like this?

```php
return function($page) {
  return [
    'foo' => 'my first template variable ' . $page->title(),
    'bar' => 'my second template variable'
  ];
};
```

The good thing with it is that we can see where `$page` comes from. We also can only use what arguments we need and in what order we want, which is really nice. It's also backward compatible.

What I still like more about my suggestion is that it does not need two `return` and has a dead simple syntax. No function wrapper needed. Just return the array, that's it.

```php
return [
  'foo' => 'my first template variable ' . $page->title(),
  'bar' => 'my second template variable'
];
```

You closed it so I guess you have already made up your mind about it. Maybe there are some other hidden pros with your solution that I can't see yet.

**Comment by fvsch** [comment]
@jenstornell I find that using a function is a bit cleaner, because theoretically you might need to call it for each page in a series of pages (which is kinda what I’m doing in StaticBuilder).

**Comment by jenstornell** [comment]
@fvsch I see. In my plugin that I'm making I've adapted to how controllers in Kirby works, not my shorthand version.

The controller as function is a nice kind of wrapper around it that does not let anything slip through. With my array version, any variables declared before the `require_once` will be accessable in the controller, which is not a good thing.

```php
$controller_path = 'My path';

$site = site();
$page = page('about');
$pages = $page->children();

$values = require_once $controller_path;
```

In the example above the array controller will have access to `$site`, `$pages` and `$page` which is good. But it will also have access to `$controller_path` which is not as nice as it's not expected.

So yes, I tend to have changed my mind about it. The function approach is a bit less slippery somehow.
