### ISSUE TITLE
[Panel] Textarea shortcuts not working on Windows

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2113]
**Describe the bug**
Textarea shortcuts not working on Windows

**To Reproduce**

1. Go to panel on Windows
2. Edit any page that have textarea field
3. Try to use shortcuts like that: `CTRL + B`, `CTRL + I`
4. See nothing happened

**Expected behavior**
Shortcuts should work as works in MacOS

@texnixe Tested on MacOS and working
https://forum.getkirby.com/t/textarea-shortcuts-not-working-on-windows/15665

**Kirby Version**
3.2.4

**Console output**
No output

**Desktop**
 - Windows 10
 - Chrome, Firefox, Edge (Latest)

**Comment by distantnative** [comment]
I am seeing we are using the Vue key `meta` modifier: https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Input/TextareaInput.vue#L37

On a mac that is the comand key, on windows this maps to the windows key.

**Comment by afbora** [comment]
When pressing `Win + L` as  always use in texarea, windows locking 😱

**Comment by distantnative** [comment]
Yea, I am not sure having the windows key involved is such a great idea

**Comment by afbora** [comment]
Please have a look: https://github.com/vuejs/vue/issues/4843

**Comment by distantnative** [comment]
Just read it, sadly no solution.

**Comment by afbora** [comment]
Worked with `CTRL + WIN + B` to bold, not at all useful 😞 

Can't we add a property like [checkCmdOrCtrl()](https://github.com/vuejs/vue/issues/4843#issuecomment-277030811)? 
I don't think users can use `CTRL + WIN + X` because I see it for the first time.

**Comment by distantnative** [comment]
I think we had them first on ctrl as well but that was blocking something else - not sure. @bastianallgeier might remember. Otherwise yea, we could bind both `meta` and `ctrl`.

**Comment by afbora** [comment]
Let's solve it or not, it would be nice to put a link to the bottom of the textarea or panel that opens the relevant or all shortcuts dialog for end users.

**Comment by bastianallgeier** [comment]
Related: https://github.com/getkirby/kirby/issues/1898

**Comment by bastianallgeier** [comment]
Maybe it's better to bind them to CTRL only?

**Comment by lukasbestle** [comment]
I think `Cmd` makes sense on macOS – it's convention and as long as we use the keys that are used in other apps for the purpose, it's probably the best solution. `Ctrl` would be very confusing.

On Windows we should however support `Ctrl`, so I *support* (haha) the idea of supporting both.

**Comment by afbora** [comment]
Btw `CTRL + S` working perfect and i'm already using this shortcut

**Comment by distantnative** [comment]
True, cause in our global events keydown bus we are alreay using both: https://github.com/getkirby/kirby/blob/master/panel/src/config/events.js#L59-L61

So I think the straightforward way is to add ctrl in Textarea as well.

**Comment by afbora** [comment]
> Let's solve it or not, it would be nice to put a link to the bottom of the textarea or panel that opens the relevant or all shortcuts dialog for end users.

### GitHub Style
https://github.com/getkirby/kirby/network

**Bottom of page**

![FireShot Capture 763 - Network Graph · getkirby_kirby - https___github com_getkirby_kirby_network](https://user-images.githubusercontent.com/3393422/65170163-bd51bc00-da50-11e9-9f66-de1cbc3ac054.png)

**Shortcuts modal**

![image (1)](https://user-images.githubusercontent.com/3393422/65170176-c3e03380-da50-11e9-91e1-5cbfe847cbe1.jpg)

**Comment by afbora** [comment]
✅
