### ISSUE TITLE
<k-bar> not working

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2114]
**To Reproduce**
Copy-paste the `<k-box>` example from [the docs](https://getkirby.com/docs/reference/plugins/ui/bar):

![image](https://user-images.githubusercontent.com/5570098/65025108-c2bee180-d93e-11e9-8774-8c172825b034.png)

**Expected behavior**
The box should appear.

**Comment by afbora** [comment]
Did you mean `k-bar` instead of `k-box`?

**Comment by distantnative** [comment]
And if you want to provide content for a slot it's  rather `<template slot="left">foo</template>`

**Comment by bastianallgeier** [comment]
The docs are wrong. The bar is working as expected but you cannot use the slots like this. @distantnative's example is right.

**Comment by bastianallgeier** [comment]
I just fixed the example in the docs.

**Comment by yandodov** [comment]
I've had a major brainfart when I opened this one. You obviously don't use slots like that... I can confirm it works and this was a docs issue. Thanks!
