### ISSUE TITLE
No options when using youtube()

### ISSUE THREAD

**Issue by dorb4n** [getkirby/kirby#2118]
**Describe the bug**
I don't get the parameters in the youtube url (iframe) when setting the $options in the youtube() function.

https://getkirby.com/docs/reference/templates/helpers/youtube

**To Reproduce**
In my Template i use the youtube() function with the $options to hide the controlls:

`
youtube($myVideoUrl, array("controlls" => 0))
`

**Expected behavior**
I want to get an iframe with the parameter _controlls_, like: 

<iframe allowfullscreen src="https://www.youtube.com/embed/123456789?controlls=0"></iframe> 

But the _?controlls=0_ is missing.

**Kirby Version**
3.2.4

**Console output**
No Output

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 69

**Additional context**
https://github.com/getkirby/kirby/blob/3.2.4/src/Toolkit/Html.php#L439
Is _$options['youtube']_ right? With _$options_ it works.

html::youtube() works perfectly.

**Comment by bastianallgeier** [comment]
✅
