### ISSUE TITLE
t.userLanguage is undefined - critical user error

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2119]
When I click on an username in the panel - either via user field or via user list - an `t.userLanguage is undefined` error is thrown as a popup in the user interface.

```
TypeError: "t.userLanguage is undefined"
    ym http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/app.js:1
    _render http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
    r http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
    get http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
    run http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
    Zn http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
    ye http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
    le http://localhost/kirby/media/panel/5bcc1ba569f5e8b59d2e8aa50650e617/js/vendor.js:41
app.js:1:283537
```

I'm unable to edit the user anymore. New users don't work too.

Kirby 3.2.5-rc.1 with multilang support (only 1 lang defined)

**Comment by distantnative** [comment]
I take the blame. Have to find out why/when `this.$store.state.languages.all.filter(x => x.code === this.user.language)[0]` is undefined.

**Comment by afbora** [comment]
When i try access to own account or any user:

> TypeError: Cannot read property 'name' of undefined
    at a.ym (app.js:1)
    at a.t._render (vendor.js:41)
    at a.r (vendor.js:41)
    at or.get (vendor.js:41)
    at or.run (vendor.js:41)
    at Zn (vendor.js:41)
    at Array.<anonymous> (vendor.js:41)
    at le (vendor.js:41)

**Comment by distantnative** [comment]
✅
