### ISSUE TITLE
Lazy loaded no dimensions specified info on console

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2120]
**Describe the bug**

The information comes from the console, is it important?

> [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323

**To Reproduce**

1. Go to panel
2. Check out `console`

**Kirby Version**
3.2.5-RC.2

**Console output**
If you are working with the panel, please check the browser console for errors and send the output.

**Desktop:**
 - Windows 10
 - Chrome

**Comment by bastianallgeier** [comment]
I removed lazy loading again. We need to implement it properly with the right dimensions.
