### ISSUE TITLE
[Panel] Search user by name not working

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2122]
**Describe the bug**
I can't find users when I search by name

**To Reproduce**

1. Go to panel
2. Be sure different user name and email who that you'll search (For ex: Mark Otto - john@doe.com)
3. Click search icon top, switch to users and enter `mark`
4. See no results

**Expected behavior**
When we search by name, the result should come.

**Kirby Version**
3.2.5

**Desktop:**
 - Windows 10
 - Chrome 77.0.3865.75

**Comment by bastianallgeier** [comment]
✅
