### ISSUE TITLE
[Panel] Call to a member function remove() error on some page and file actions

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2123]
**Describe the bug**
I get error about content locking while change the page slug, delete page and delete file.

**To Reproduce**
1. Go to panel
2. Be sure content locking false
3. Try this actions: `delete page that have file`, `change page slug`, `delete a file`

**Screenshots**
![image](https://user-images.githubusercontent.com/3393422/65079143-2846b880-d9a7-11e9-9dcc-ed8b92937152.jpg)

**Kirby Version**
3.2.5-RC.1

**Console output**
> code: 500
> details: []
> exception: "Error"
> file: "/test/kirby/3.2.5/kirby/src/Cms/PageActions.php"
> key: null
> line: 103
> message: "Call to a member function remove() on null"
> route: "pages/([a-zA-Z0-9\.\-_%= \+\@\(\)]+)/slug"
> status: "error"
> __proto__: Object

**Desktop:**
 - Windows 10
 - Chrome 76.0.3809.132

**Issue related lines**

https://github.com/getkirby/kirby/blob/3.2.5-rc.1/src/Cms/PageActions.php#L103
https://github.com/getkirby/kirby/blob/3.2.5-rc.1/src/Cms/FileActions.php#L55
https://github.com/getkirby/kirby/blob/3.2.5-rc.1/src/Cms/FileActions.php#L218

**Comment by distantnative** [comment]
I can't do any changes or check them myself right now, but I think the fix should be as easy as:

```php
// remove the lock of the old page
if ($lock = $oldPage->lock()) {
    $lock->remove();
}
```
The same for the other occasions. And maybe we need to do another global search to see if I missed any other spots where we call `ModelWithContent::lock` without an if statement.

**Comment by afbora** [comment]
![image](https://user-images.githubusercontent.com/3393422/65129766-adac8600-da04-11e9-9c7b-2079feefe91f.jpg)

LGTM, we have already used it in some place like this in `config\api\routes\lock.php`.
Only 3 of the same features appear (Not source that included tests, etc..)

**Comment by bastianallgeier** [comment]
Wouldn't it be better to have some sort of DisabledLock class that still offers the same methods, but simply does nothing?

**Comment by distantnative** [comment]
@bastianallgeier What would be the benefit? We still need the check for virtual pages that opt out of supporting content locking.

**Comment by bastianallgeier** [comment]
You are right!

**Comment by bastianallgeier** [comment]
✅
