### ISSUE TITLE
[Panel] "Content locking not supported"

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2125]
When content locking is disabled in the config, the following warning is thrown in the browser console:

> Content locking not supported for {{ path.to.page }}

First, I think the copy of the message is misleading: it's not that the browser lacks a feature to support content locking, it's just disabled on the server. It's also nothing wrong with that specific page that disables this feature, it's just disabled on the server.

Second, after understanding that this is just a reaction to my config setting, I asked myself why this message is shown in the console at all? The feature was deactivated deliberately (I'm the only user on my localhost) and it's nothing Kirby has to warn me about.

So, I'd expect there to be no message at all :)

**Comment by distantnative** [comment]
It is currently shown as this could also be the result of using custom page models without supporting content locking in them (mainly virtual pages). In that case it is a good hint for a developer to know why this is not happening. But maybe we have to revise this.

**Comment by distantnative** [comment]
Mayeb we just remove that line https://github.com/getkirby/kirby/blob/03d6e96aa27f631e5311cb6c2109e1510505cab7/panel/src/components/Forms/FormButtons.vue#L162

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
@distantnative I didn't think about virtual pages in this context. That's actually a case where the message makes sense! Maybe the API could pass a response message in these cases in addition to setting `response.supported` to `false`?
