### ISSUE TITLE
[Panel] Class 'I18n' not found

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2128]
**Describe the bug**
Sections and some fields throw error following:

> "albums" bölümü yüklenemedi: Class 'I18n' not found

**As english translation**

> The section "albums" could not be loaded: Class 'I18n' not found

Error in "website" field
Error in "author" field
Error in "gallery" field
...
...
> Class 'I18n' not found

**To Reproduce**

1. Go to panel users
2. Edit own account
3. Change to language as `Turkish`
4. Try these actions: Go to dashboard, edit any page, edit any user
5. See error

**Kirby Version**
3.2.5-RC.2

**Console output**
```
code: 500
details: []
exception: "Error"
file: "/kirby/config/sections/mixins/empty.php"
key: null
line: 9
message: "Class 'I18n' not found"
route: "site/sections/([a-zA-Z0-9\.\-_%= \+\@\(\)]+)"
status: "error"
```

**Desktop:**
 - Centos 6
 - Chrome 77

**Additional context**
This issue is about locale `LC_CTYPE` constant (starting file/class names with `I` letter) and it was working by default in 3.2.4.

When we want to use `locale` as turkish, we use it like following, not just for Kirby.
https://getkirby.com/docs/reference/system/options/locale#detailed-settings

Even if we want to use custom locale, the error continues.
I would expect it to work without error, even if we didn't use custom locale as before versions, 

**Note**:

When i add `use Kirby\Toolkit\I18n;` to top of files that have error fields/sections, error gone 🤔

**Comment by lukasbestle** [comment]
I first thought this was because of our PHP CS Fixer changes (so that a `use` declaration was removed by accident), but actually we [haven't touched that at all](https://github.com/getkirby/kirby/commits/develop/config/sections/mixins/empty.php), it has always been without the `use` declaration.

I'm surprised that this worked at all in the past. 🤔

**Comment by bastianallgeier** [comment]
The I18n class has an alias. I really don't understand why it breaks.

**Comment by afbora** [comment]
This error only appears in the Turkish language.
This means that the error is related to `LC_CTYPE` i think.

**Comment by afbora** [comment]
Causing commit i think: https://github.com/getkirby/kirby/commit/4dbaad9a82a095deb356dfff83d46462147fa8f3

I have no idea how we can find a general solution.
But following development can give you an idea that works properly.

```php
// provide some variants as fallbacks to be
// compatible with as many systems as possible
setlocale(LC_ALL, [
    $locale,
    $locale . '.UTF-8',
    $locale . '.UTF8',
    $locale . '.ISO8859-1',
    setlocale(LC_ALL, 0) // fall back to the previously defined locale
]);

if ($user->language() == "tr") {
    setlocale(LC_CTYPE, 'en_US.UTF-8');
}
```

https://github.com/getkirby/kirby/blob/release/3.2.5/src/Api/Api.php#L159-L203

**Comment by lukasbestle** [comment]
Maybe the alias isn‘t loaded for some requests for some reason. I think we should explicitly import the class even if it has an alias.

**Comment by afbora** [comment]
I noticed something new interesting. 
It also works with the lowercase letter `i` as `i18n`.

````php
'empty' => function ($empty = null) {
    return i18n::translate($empty, $empty);
}
````

Note that in Turkish language:

**Means**
Lowercase: `ı`
Uppercase: `I`

Lowercase: `i`
Uppercase: `İ`

**Result**
Lowercase: `i18n`
Uppercase: `İ18n` (Not `I18n`)

So `I18n` class not found.

Thats why we use `LC_CTYPE` with `en_US.UTF-8`

**Comment by lukasbestle** [comment]
That lead was pretty amazing – you found the core of the issue. 😮👍

Your discovery that it works with lowercase `i18n` made me think about our alias loading. The issue lies in [this line](https://github.com/getkirby/kirby/blob/3.2.5-rc.2/config/setup.php#L19). So the issue really is the locale that breaks the alias lookup.

I have fixed this as well as the missing `use` declaration in #2131. Could you please test if that fixes it for you?

**Comment by afbora** [comment]
Great! Works properly now 👍 

I wonder that there are other files that we use `I18n::translate()` but missing `use` declaration _(config/fields/url.php, config/fields/email.php, etc)_. Why didn't just this work? _(At least we've seen so far)_

**Comment by lukasbestle** [comment]
Oh, you are right. I will add the `use` declarations to the other `config` files as well.

> Why didn't just this work?

Probably because your blueprint setup in particular only needed that specific file.

**Comment by afbora** [comment]
> Probably because your blueprint setup in particular only needed that specific file.

Now everything is clear

**Comment by bastianallgeier** [comment]
Holy shit, guys! This was amazing team work again. I would have never found that issue.
