### ISSUE TITLE
Built-in fingerprinting for assets.

### ISSUE THREAD

**Issue by iksi** [getkirby/kirby#213]
It would be nice to have built-in fingerprinting for assets. Built-in as it’s not possible to overwrite or extend the existing `js()` and `css()` functions. I’ve written a fingerprint plugin (https://github.com/iksi/KirbyFingerprint) in which I had to copy and slightly alter the built-in `css()` and `js()` functions to be able to fingerprint template specific files (using `@auto`).

More on fingerprinting: http://guides.rubyonrails.org/v3.2.8/asset_pipeline.html (see ‘1.2 What is Fingerprinting and Why Should I Care?’).

@bastianallgeier do you think such a feature would nice to have built-in? In that case I’ll set up a pull request.

**Comment by lukasbestle** [comment]
IMHO this should not be part of the core. It's great to have and very useful (although I use query-strings for that), but it's an "advanced" feature not everyone will understand and want to use.

What about some kind of hook for the CSS and JS functions that lets you modify the passed input URL and output markup of the helpers? As @bastianallgeier [wants to implement a hook system anyway](https://github.com/getkirby/kirby/issues/120#issuecomment-74864235), this might be another feature of that system when it exists.

**Comment by iksi** [comment]
I’ll probably wait for a hook, the reason that I posted this issue is because the code duplication feels so inefficient.

**Comment by shoesforindustry** [comment]
Hmmm, lukasbestle if we are talking about cache busting here, then surely it must be a core feature. Users can use as normal, no real extra effort and set long expiry and have a much better website without the technical knowledge. Although I appreciate iksi comment that this might not be the best way to do it at present.

**Comment by lukasbestle** [comment]
Not everything can be a core feature.
When I first saw Kirby, I was amazed by its simplicity. It had every feature I could ever need, but nothing more. Everything was very easy to understand. I personally hate CMSs that do some kind of magic like injecting markup into my pages without my explicit agreement or managing assets by moving, copying and minifying files automatically even though I already have my own structure.

I think that this feature is very well-suited for a plugin. If you know what it does, you can simply drop it into your `plugins` folder and it does its thing. And if you don't need or want it, that's fine.

**Comment by iksi** [comment]
I agree fully with https://github.com/lukasbestle that it should be avoided to make things too bloated. Closing this issue.
