### ISSUE TITLE
Panel Pages Section: Clicking Status Icon Says Being Edited by `{email}`

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2134]
**Describe the bug**
When a draft is locked because another user is editing it, if I click on status icon (red circle) from a Pages section in the panel, I get a dialog that literally says "The page is currently being edited by {email} and cannot be changed."

The "{email}" part is not resolved to say who is actually editing it.

**Screenshots**
<img width="386" alt="Screen Shot 2019-09-23 at 10 34 26 AM" src="https://user-images.githubusercontent.com/417182/65448613-14a7b180-ddee-11e9-8074-f9bd2d4317ce.png">

**Kirby Version**
`3.2.4`

**Comment by bastianallgeier** [comment]
✅
