### ISSUE TITLE
[Panel] e.nextSibling.focus is not a function on multiselect field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2135]
**Describe the bug**  
Error occured when navigate right (no next siblings) selected options on multiselect field

**To Reproduce**  
1. Go to panel
2. Add multiselect field with options to any page
3. Edit page and select some options
4. Navigate selected options with `right` arrow

**Screenshots**  
![siblings](https://user-images.githubusercontent.com/3393422/65509824-164fa300-dedc-11e9-8751-b0d078af862f.gif)

Screenshot actions: TAB + RIGHT + LEFT + RIGHT + RIGHT

**Kirby Version**  
3.2.5 Stable

**Console output**  
```
app.js:9365 TypeError: e.nextSibling.focus is not a function
    at a.navigate (app.js:4900)
    at n.nativeOn.keydown (app.js:4698)
    at oe (vendor.js:41)
    at HTMLSpanElement.n (vendor.js:41)
    at HTMLSpanElement.Ni.i._wrapper (vendor.js:41)
```

**Desktop**  
 - Windows 10
 - Chrome 77

**Additional context**  
 - Left arrow key working properly when no prev siblings
 - Left and right arrow actions working properly on tags fields

**Comment by bastianallgeier** [comment]
✅
