### ISSUE TITLE
Panel: "Invalid regular expression: nothing to repeat" with Custom Slug Rules Containing `+` (3.2.5 Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2138]
**Describe the bug**  
When creating a new page in the Panel, as you type in the Title field, an error is displayed that says "Invalid regular expression: nothing to repeat"

It appears the regression has to do with a custom slug override that includes a `+`. This was previously fixed with https://github.com/getkirby/kirby/issues/1946, but seems to have been reverted?

In my `config.php`, for example:
```php
Str::$language = [
    '+' => '-plus',
];
```

**To Reproduce**  
1. Have custom slugs defined like above
2. Click on a "Create" button in a Pages section
3. Type a character of a title

**Screenshots**  
<img width="531" alt="Screen Shot 2019-09-25 at 11 54 49 AM" src="https://user-images.githubusercontent.com/417182/65631054-908b3080-df8b-11e9-8c3f-10a2cdb51604.png">

**Kirby Version**  
`3.2.5`

**Console output**  
None

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: Version 13.0.1

**Additional context**  
No issues on `3.2.4`

**Comment by afbora** [comment]
I can reproduce too. This issue about this PR: https://github.com/getkirby/kirby/pull/2112

We added `\p` unicode property to work stable for unicode languages and works great!
But we missed `+` sign as @distantnative worried on RC tests 

So when we enable unicode support, `+` does not work 🤔 
Maybe to give you an idea to make better solution, it works with `escape` like following

````php
Str::$language = [
    '\+' => '-plus',
];
````

**Comment by bastianallgeier** [comment]
I'm really sorry! I added all sorts of unit tests after the change, but I forgot to test the plus sign replacement: https://github.com/getkirby/kirby/blob/master/panel/tests/unit/Helpers/Slug.spec.js

**Comment by bastianallgeier** [comment]
✅
