### ISSUE TITLE
Registry has duplicates

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#215]
In the airtable not all of the old Kirby 2 registry extensions are there.

## Page method example

For example `page::method` is not there (yet at least).

**The old syntax for that was:**

```php
$kirby->set('page::method', ['linktag', 'lt'], function($page) {...});
```

or

```php
page::$methods['linktag'] = function($page) {
  return '<a href="' . $page->url() . '">' . $page->title()->html() . '</a>';
};
```

In this case we have two different ways to setup page methods. Here are some reasons why I think there should only be one:

- As a plugin developer it gets confusing. Which one should I use? Which one is most correct? When should I use one or the other?
- A plugin can end up using a mix of these different syntaxes (by confusion) which is not as state of the art.
- The crew (you) need to maintain two versions of the same things. Better to spend the time on one thing and make that great.

## Skeleton

**Personally I really liked what I saw on Journal:**

```php
$kirby->set([
    'collection' => [
        'articles' => function () {
            return page('blog')->children();
        }
    ],
    'controller' => [
        'blog' => function ($kirby) {
            return [
                'articles' => $kirby->collection('articles');
            ];
        }
    ],
    'blueprint' => [
        'blog'    => __DIR__ . '/blueprints/blog.yml',
        'article' => __DIR__ . '/blueprints/article.yml'
    ],
    'template' => [
        'blog'    => __DIR__ . '/templates/blog.php',
        'article' => __DIR__ . '/templates/article.php'
    ],
    'hook' => [
        'page.delete:before' => function () {
            throw new Exception('You cannot delete any pages');
        }
    ]
]);
```

It shows that all these things have a similar syntax and can even be grouped like this. Then we could just chain on the page method there as well.

So, should we keep `page::$methods` or `$kirby->set('page::method')`? By what I've stated here I like the skeleton `$kirby->set` better.

(I'm full of energy this morning :fire: )

**Comment by distantnative** [comment]
The syntax is the unified one and page methods will be back in the same way: #358
