### ISSUE TITLE
Error messages in Hooks are not displayed in Panel

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2155]
**Describe the bug**  
With 3.2.5 messages of exceptions thrown in hooks are not shown in the panel any more.

**To Reproduce**  
1. Add [Hooks with Errors](https://getkirby.com/docs/reference/plugins/extensions/hooks#error-handling
) like this:
```php
    'hooks' => [
        'page.update:after' => function (Page $page) {
            throw new Exception('somethings wrong');
        },
    ]
```
2. Update any field in panel
3. See error modal

**Screenshots**  
Result in 3.2.5
<img width="371" alt="3 2 5" src="https://user-images.githubusercontent.com/18071758/65871897-ae87d500-e37f-11e9-936a-16cb6f3a717f.png">

Result in 3.2.4
<img width="376" alt="3 2 4" src="https://user-images.githubusercontent.com/18071758/65871911-b6e01000-e37f-11e9-92ad-eeff90fd255d.png">

**Kirby Version**  
3.2.5

**Comment by bastianallgeier** [comment]
✅
