### ISSUE TITLE
Panel not work in Safari

### ISSUE THREAD

**Issue by pfrlv** [getkirby/kirby#2160]
Panel not work in Safari.
Kirby Version: 3.2.5

<img width="849" alt="Screenshot 2019-10-01 at 02 39 50" src="https://user-images.githubusercontent.com/10477149/65924418-4c69b700-e3f5-11e9-86da-24ad71c0e903.png">

 - OS: MacOS
 - Browser: Safari
 - Version: 13.0.1 (14608.2.11.1.11)

**Comment by lukasbestle** [comment]
That looks like a browser extension doing strange things TBH. The Panel doesn‘t use that domain or WebSockets in general.

**Comment by bastianallgeier** [comment]
I agree with @lukasbestle. This must be an issue with one of your extensions.

**Comment by nilshoerrmann** [comment]
I've just noticed this in my console:

> Firefox kann keine Verbindung zu dem Server unter ws://localhost:64924/ aufbauen.

In my case the error was caused by the Editor plugin and referred to something parcel-related:

     var ws = new WebSocket(protocol + '://' + hostname + ':' + "64924" + '/')

**Comment by nilshoerrmann** [comment]
This is the line: https://github.com/getkirby/editor/blob/24c62279c7bb64c14cc406cf3cdcce980de343da/index.js#L26611

But it seems to be fixed in with today's latest commit.

**Comment by bastianallgeier** [comment]
@nilshoerrmann that happens when I forget to build the latest dist files. With the core, we never have this issue. With the editor, I still have to setup a proper process.

**Comment by nilshoerrmann** [comment]
Yeah, that's the way the cookie crumbles :)
I just wanted to point to the source of the issue and that it's not caused by a browser extension. 
Automatic dist file building would still be neat though ("Nightlies").

**Comment by bastianallgeier** [comment]
In your case it's not a browser extension, but the websocket connection in @pfrlv's screenshot does not seem to come from a plugin at all.
