### ISSUE TITLE
order of list items of changeTemplate is ignored

### ISSUE THREAD

**Issue by j3ll3yfi5h** [getkirby/kirby#2161]
**Describe the bug**  
```
options:
  changeTemplate:
    - b_template
    - a_template
    - c_template
```

The ordering in the template selection dropdown is alphabetical instead of the defined order. 

**To Reproduce**  
1. Add a blueprint
2. Define changeTemplate with at least two different templates in a specific order (not alphabetical)
3. Add a page, set a template
4. Change template and notice, that the order in the blueprint is ignored

**Expected behavior**  
Order of templates should be as defined in the blueprint.

**Screenshots**
![Bildschirmfoto 2019-10-01 um 13 48 56](https://user-images.githubusercontent.com/6337411/65959471-5d94e100-e452-11e9-88b4-0c2234db6e54.jpg)

**Kirby Version**  
3.2.5

**Comment by afbora** [comment]
I don't know if this is a bug, but the line that cause it:

https://github.com/getkirby/kirby/blob/develop/src/Cms/Page.php#L263

**Comment by j3ll3yfi5h** [comment]
@afbora It works with `create`, but not with `changeTemplate`, shouldn't it have the same behaviour on both places?

**Comment by afbora** [comment]
@j3ll3yfi5h You right and works for me. Just comment the `asort` line to try.

![image (2)](https://user-images.githubusercontent.com/3393422/65969691-e66d4600-e46d-11e9-83e2-213c63416840.jpg)

**Comment by j3ll3yfi5h** [comment]
@afbora yes, that's it!

**Comment by lukasbestle** [comment]
I think the sorting is only there to ensure that the current template (which is always included in the list) gets inserted at the correct position in the list. But I think it would be fine to add the current template at the end (which will happen if we remove the `asort()` line) as this only affects cases where the `changeTemplate` option doesn't include the current template. If it's already included, the custom position would be respected.

**Comment by distantnative** [comment]
I would agree that we could get rid of the sorting - it is not important that the current template it inserted alphabetically. However, I would suggest to add the current template at the top instead of the bottom, @lukasbestle. Would work better with the select dropdowns.

**Comment by bastianallgeier** [comment]
✅
