### ISSUE TITLE
[Panel] "Throw new Exception()" in hooks displays “Please fix all form errors…” message

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#2165]
**Describe the bug**  
When I use `throw new Exception('my message)` in a hook, Kirby displays a pop-up with the message “Please fix all form errors…” instead of my message exception.

**To Reproduce**  

I can reproduce this issue in the starterkit (Kirby 3.2.5) by adding this in the config file:
```
return [

    'debug' => true,

    'hooks' => [
    	'page.update:after' => function ( $newPage , $oldPage ) {

    		throw new Exception('Page Updated');

    	}
    ]
];
```

**Expected behavior**  
`throw new Exception('my message)` should display a pop-up with the message "my message"

**Screenshots**  

**Kirby Version**  
3.2.5

**Console output**  

**Desktop (please complete the following information):**  
 - OS: Linux Ubuntu
 - Browser: Firefox
 - Version: 69.0.1 (64-bit)

**Smartphone (please complete the following information):**  
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afbora** [comment]
Fixed the issue https://github.com/getkirby/kirby/issues/2155
