### ISSUE TITLE
DateField: day changes when changing year

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2172]
**Describe the bug**  
When changing the year, the day changes as well:
![Screen Recording 2019-10-05 at 15 41 22](https://user-images.githubusercontent.com/3788865/66255675-ccda4000-e786-11e9-9a21-076527a02611.gif)

**Comment by afbora** [comment]
I can't reproduce the issue on 3.2.5

![date](https://user-images.githubusercontent.com/3393422/66255804-cf419780-e790-11e9-9a37-1b5d0bb4a7ce.gif)

**Comment by distantnative** [comment]
I tested on the `develop` branch. Does that change it for you?

**Comment by afbora** [comment]
I have tested now on develop branch directly and built with `npm run build`, both work properly 🤔 Btw i tried without any settings on Starterkit with Chrome.

**Comment by distantnative** [comment]
Seems to be caused by https://github.com/getkirby/kirby/issues/1813#issuecomment-538677633 - still had the extension active.
