### ISSUE TITLE
Can't delete pages programmatically in hook "page.duplicate:after" if pages has subpages

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#2175]
**Describe the bug**  
Can't delete pages programmatically in hook "page.duplicate:after" if pages has subpages by using this code:

```
'page.duplicate:after' => function ( $duplicatePage ) {
            
         if ( $duplicatePage->template() == 'campaign' ) :

            // delete proposals pages (and all subpages, sub-subpages)
            $proposals  = $duplicatePage->childrenAndDrafts()->filterBy( 'template', 'proposal' );
            foreach ( $proposals as $proposal ) :
                $this->impersonate('kirby');
                $proposal->delete( true );
            endforeach;

        endif;

    },
```
This code works used in a template page.

This issue has been discussed in the forum with Sonja:
https://forum.getkirby.com/t/may-i-delete-a-page-programmatically-if-it-has-subpages/15854/6

Maybe related with issue #1681 and #1232

**To Reproduce**  
1. Duplicate pages (with subpages, sub-subpages)
2. The user choose to replicate subpages (Copy pages = On)
3. The app delete subpages programmatically in hook "page.duplicate:after" 

**Expected behavior**  
The page is duplicated but all its subpages are deleted

**Screenshots**  

**Kirby Version**  
3.2.5

**Console output**  

**Desktop (please complete the following information):**  
 - OS: Linux Ubuntu
 - Browser: Firefox
 - Version: 69.0.2 (64-bit)

**Smartphone (please complete the following information):**  
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by bastianallgeier** [comment]
This is the same issue: https://github.com/getkirby/kirby/issues/1232
