### ISSUE TITLE
[Panel] Empty sections and pagination conflict

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2180]
**Describe the bug**  
Empty sections throw this error using latest `develop` code:

>  Pagination page 1 is out of bounds, expected 0-0 

**To Reproduce**  
Update to `develop`.

**Expected behavior**  
No error, displaying an empty section.

**Screenshots**  
![Bildschirmfoto am 2019-10-08 um 16 54 14](https://user-images.githubusercontent.com/25466/66407670-e5985f00-e9ed-11e9-8952-cf8328868186.png)

**Comment by nilshoerrmann** [comment]
Regarding the error message, if this is about a non-existent page, what about: 

> Pagination error, page 6 does not exist, expected 0–5

(guessing that `0-0` was a placeholder for the actual possible page range)

**Comment by bastianallgeier** [comment]
✅
