### ISSUE TITLE
Panel: k-input $props and $attrs not reactively passed to child component

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#2181]
I am pretty new to Vue, if the wording is wrong you're welcome to help me out:

**Describe the bug**  
When updating the options of a k-select-field the new value gets stuck in the k-input component and is not passed to it's child components.

**To Reproduce**  
1. create a custom field:
```js
panel.plugin('my/test', {
   fields: {
    'test': {
      props: {
        value: String,
        label: String
      },
      data() {
        return {
          options: [
            {text: 'A', value: 'A-value'},
            {text: 'B', value: 'B-value'},
          ]
        }
      },
      methods: {
        updateme() {
          this.options = []
        }
      },
      template: `
        <section>
           <a @click="updateme()">[click me update]</a>
          <k-select-field :label="label" type="select" theme="field" :options="options" :value="value">                             
        </section>
        `
    }
  }
});
```
```php
<?php
Kirby::plugin('my/test', [
    'fields' => [
        'test' => []
    ]
]);
```

2. add it to a blueprint 
```yml
fields:
  test:
    type: test
    label: my Test
```

3. click in the panel on the text [click me update]
4. see that the select input is not changing
5. find in the Vue debug console that the attributes/props are passed along until k-input but never into k-select-input

**Expected behavior**  
The select input should change (all options should be gone)

**Kirby Version**  
3.2.5

**Additional context**  
When I followed the attrs/props along the child components it showed that the last reaction on them happens in the k-input component. 
[here](https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Input.vue#L54) the attrs and props are combined into a inputProps variable
```js
  data() {
    // ...
      inputProps: {
        ...this.$props,
        ...this.$attrs
      }
    };
  },
```
which seems to be not reactive.

Making inputProps a computed property solves the problem:
```js
  computed: {
    inputProps() {
      return {
        ...this.$props,
        ...this.$attrs
      }
    }
  },
```

**Comment by mullema** [comment]
ah haven't seen this one: https://github.com/getkirby/kirby/issues/2075

**Comment by bastianallgeier** [comment]
I will close this in favor of: https://github.com/getkirby/kirby/issues/2075
