### ISSUE TITLE
Wrong fallback for sortBy('sort')

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2183]
**Describe the bug**  
When uploading files to a files section, the files will be sorted alphabetically by filename. No matter if `sortable` is set to `true` or `false`. Unfortunately using something like `$page->files()->sortBy('sort')` in the template does not produce the same order. It produces a seemingly random order.

**To Reproduce**  
1. Upload multiple files to a files section
2. Do **not** sort them
3. Sort them via `->sortby('sort')` in the template
4. Compare the order in the front- and backend

**Expected behavior**  
I'd expect `->sortby('sort')` to have the same fallback as the files section. Otherwise the order will be totally random until someone sorts them. Then the order will be totally different again.

**Kirby Version**  
3.2.5

**Additional context**
I **think** the fallback order has something to do with the numbers used here — between the page and filename: `localhost/media/pages/test/632340091-1570570356/filename.ext`

![cats 2019-10-08 23_11_31](https://user-images.githubusercontent.com/7975568/66434659-4b530e00-ea23-11e9-86a1-db4f8ba65af8.gif)

**Comment by afbora** [comment]
If I understand it correctly, fixed the issue #2152  and will be release in 3.3.0

And you need to fallback to sort properly files that haven't sort field like that:

    ->sortBy('sort', 'asc', 'filename', 'asc');

**Comment by medienbaecker** [comment]
@afbora You're right! Setting the sort value will synchronize the panel and frontend — perfect! 👏
