### ISSUE TITLE
$page->purge() and $site->purge() actions do not clear cached translations

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2189]
**Describe the bug**  
The methods `$page->purge()` and `$site->purge()` resets the models content attribute but not translations in a multilang setup. 
If the content was already used before, the cached (and potentially stale) content from the translations collection get's into the model.

**Expected behavior**  
The cached translations should also be reset to allow the model to rebuild the content fresh from the file system.

**Comment by bastianallgeier** [comment]
✅
