### ISSUE TITLE
filterBy filename with a dot in it, fails match

### ISSUE THREAD

**Issue by shoesforindustry** [getkirby/kirby#219]
For example

1. This fails: 'car1.thumb.png'
```php 
$page->images()->filterBy('filename','*='.thumb')
```

2. This works: `car1-thumb.png`
```php 
$page->images()->filterBy('filename','*=','-thumb')
```

I wouldn't mind but this used to work with the old Kirby Thumb plugin and we have a lot of images named as such. (We pre-generate our thumbs.)
See also the forum post ['How to use pre-generated thumbnails in K2?'](http://forum.getkirby.com/t/how-to-use-pre-generated-thumbnails-in-k2/501/4)

**Comment by bastianallgeier** [comment]
Did you try: 

```php
$page->images()->filterBy('filename','*='\.thumb')
```
?
