### ISSUE TITLE
[Cms] Kirby::plugin lazy-loading

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#220]
If a Kirby::plugin namespace does already exists, it can't be setup again.

I really like the new plugin "ring" but it does not work well in all cases. Many plugins I have created set something up directly and some things later depending on some conditions. A common condition can be if a user is logged in or not.

So if the namespace already exists, it could be useful to feed it afterwards. Add things to it.

If the skeleton we have now is the only way,..

**I only see two ways for a plugin developer to solve it:**

1. The plugin developer would need to change the namespace (name) on every new Kirby::plugin call that is set up. It would be quite ugly.
1. The plugin developer would need to try to prepair everything, every route, every snippet, every template, every possible extends we would need, into arrays. A giant prepair.

In my latest plugin that may be released this week, I have a separation between core and the tool. The idea is that the tool should be totally separated from the core. Both the core and the tool have different setup of routes, snippets, templates, controllers and blueprints. So in that plugin I can't use the same namespace for both parts. It could probably work by using different names for different parts like `jens/my-plugin-core` and `jens/my-plugin-tool`, but is that the way to go here?

```php
<?php
Kirby::plugin([
    'name' => 'my-name/hello-world',
    'extends' => [
        'routes' => [
            [
              'pattern' => 'jens',
              'action'  => function() {
                  echo 'Hello world';
              }
            ]
        ]
    ]
]);

if(1 == 1) { // If the user has been logged in, add another route
    Kirby::plugin([
        'name' => 'my-name/hello-world',
        'extends' => [
            'routes' => [
                [
                    'pattern' => 'sweden',
                    'action'  => function() {
                        echo 'Hello sweden';
                    }
                ]
            ]
        ]
    ]);
}
```

**Comment by jenstornell** [comment]
I think this one is important for 3.0, at least figure out if you want to tackle this issue or not and if so to what version.

What is holding me back from porting many of my plugins is this issue. It has to do with how we can/should build our plugins.

**Comment by distantnative** [comment]
For your example it could work like this:

```php
<?php
$plugin = [
    'routes' => [
        [
          'pattern' => 'jens',
          'action'  => function() {
              echo 'Hello world';
          }
        ]
    ]
];

if(1 == 1) { // If the user has been logged in, add another route
    $plugin = array_merge_recursive($plugin, [
        'routes' => [
            [
                'pattern' => 'sweden',
                'action'  => function() {
                    echo 'Hello sweden';
                }
            ]
        ]
    ]);
}

Kirby::plugin('my-name/hello-world', $plugin);
```

And if you have two complete separate parts in a plugin, it might make sense to also treat them separately when registering, don't you think?

**Comment by lukasbestle** [comment]
Routes are maybe not the best example for this as we have route filters for that, so I don't really see why we need to support this conditional plugin registration in the core (if you really need to do it, do it like Nico proposed, but you are most likely overcomplicating it and there may be a simpler solution like the route filters for routes).

Is there any other part of your plugin you need to register conditionally?

**Comment by jenstornell** [comment]
## Separated parts

I had a problem when rewriting [Kirby Component Kit](https://github.com/jenstornell/kirby-component-kit) (the rewrite is not online), where I register multiple snippets. In that case I wanted to completely separate my tool from my core to be more independent. Therefor the snippets was registered directly in different places. I guess in this case I could have used different namespaces for my tool and my core in this case.

Anyway, I've solved it by some rewrites so be able to register all at once.

## Different scopes and levels

A more theoretically case is when we would need to register things in different scopes. I can't give a good example so I'll give a bad one... Let's say we really need to register a snippet inside a route or a kirbytext tag. Then we would need lazy loading, or somehow buffer the array to build it and then register it when at the lowest level.

## Different parts in different places

Let's say we have 10 classes. All of them will at some point register a snippet depending on conditions. To use the plugin ring, these classes can't do that. Instead they need to buffer them and at some later point register them all at once.

## Comes down to a buffer

I see now at the time of writing that a solution to all this would be to have some kind of memory to buffer stuff. Something like this:

```php
$plugin = [
    'routes' => [
        [
          'pattern' => 'jens',
          'action'  => function() {
              echo 'Hello world';
          }
        ]
    ]
];

buffer::add('my/namespace', $plugin);

// Inside a class, another scope or at a later point of time
if(1 == 1) {
    $plugin = [
        'routes' => [
            [
                'pattern' => 'sweden',
                'action'  => function() {
                    echo 'Hello sweden';
                }
            ]
        ]
    ];
    buffer::add('my/namespace', $plugin);
}

// At a later point of time, where the $plugin variable has been forgotten
Kirby::plugin('my/namespace', buffer::get('my/namespace'));
```

As seen above, I don't change anything to the `Kirby::plugin` call, I just build the array up without the need to care about if I still got access to `$plugin`. Behind the scenes the `buffer::add` would probably use `array_merge_recursive` and maybe be called `buffer::merge`.

So what do you think?

**Comment by lukasbestle** [comment]
Hm, that all sounds very complex. To be honest, I still think you are overcomplicating it.

Registering further resources at a later point in time is not going to be reliable, so that won't work. That leaves registering further resources from a class. But can't you instantiate the class from your main plugin file and get the array of resources from it directly *before* registering your plugin?

**Comment by jenstornell** [comment]
Yes. You know what, I don't have a real case for this now so I'm no longer sure about how big of an issue this will be when creating plugins from scratch.

Therefor I'll close this issue for now. If I get into trouble and this is a real nag somehow, I can just reopen it and give you a great case at that point.
