### ISSUE TITLE
toString() and toJson() doesnt working

### ISSUE THREAD

**Issue by byybora** [getkirby/kirby#220]
Hi,

I tried to create array from pages like.

### First Way
````
page('skills')->children()->toJson();
````

I got looped following error:

> Warning: json_encode(): recursion detected in
Warning: json_encode(): recursion detected in
Warning: json_encode(): recursion detected in
Warning: json_encode(): recursion detected in
...

### Second Way

````
foreach(page('skills')->children() as $page)
{
	$skills[($page->uid()->toString()] = $page->title()->toString();
}
````

I got following error:

> Fatal error: Call to a member function toString() on a non-object in

### Solution
I try with `foreach` and `string` cast:

````
foreach(page('skills')->children() as $page)
{
	$skills[(string)$page->uid()] = (string)$page->title();
}
````

But `toString()` and `toJson()` function doesnt working properly.

**Comment by bastianallgeier** [comment]
I improved those methods on the develop branch. They will be in the next stable release.

**Comment by byybora** [comment]
@bastianallgeier Awesome!
