### ISSUE TITLE
[Panel] Prevent tab navigate fields on locked page

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2204]
**Describe the bug**  
The user cannot click on the fields on the locked page with the mouse but can navigate with the tab.

**To Reproduce**  
1. Go to panel
2. Enter any page that locked
3. Navigate fields with tab key

**Expected behavior**  
It doesn't make sense to navigate between fields that are not allowed to update.

**Kirby Version**  
Develop branch of 3.3.0

**Comment by distantnative** [comment]
✅
