### ISSUE TITLE
[Panel] Click on settings when not saved does not trigger dropdown

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#221]
I was in Project A, writing a headline. When it's valid but not saved I clicked on settings. It says "Saved" but the settings dropdown did not drop down. Like the save message block the dropdown from appearing.

The same thing seems to happend on every dropdown.

**Comment by distantnative** [comment]
I don't think the notification is blocking the click (cause when I trigger one via Cmd+S I can click the dropdown without problems), but rather the blur/change from the TextField somehow also triggers a close all dropdowns event, which cancels out the opening immediately.

**Comment by bastianallgeier** [comment]
This seems to be fixed with the latest changes to the forms.
