### ISSUE TITLE
[Cms] Scrollbar on modals

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#222]
![scrollbar](https://user-images.githubusercontent.com/927011/37270284-7d3f7126-25ce-11e8-8d04-1631889e562a.jpg)

![modal2](https://user-images.githubusercontent.com/927011/37270692-0ad824f0-25d0-11e8-9dba-6181d9c6393d.jpg)

In Windows, Google Chrome.

**Comment by bastianallgeier** [comment]
Fixed on the drafts branch. Will make it into the develop branch tomorrow.
