### ISSUE TITLE
Title attribute in required <abbr> tag should be translated

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2227]
Currently, the title attribute is hard-coded:

```
<abbr v-if="required" title="This field is required">*</abbr>
```

in `/kirby/panel/src/components/Forms/Field.vue`

**Comment by bastianallgeier** [comment]
@distantnative before you start, I've already fixed it. PR is coming in a minute :)

**Comment by bastianallgeier** [comment]
Ok, I merged it immediately. The change is too small for a PR.

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
@bastianallgeier What about following lines?

https://github.com/getkirby/kirby/blob/develop/panel/src/components/Sections/FilesSection.vue#L7
https://github.com/getkirby/kirby/blob/develop/panel/src/components/Sections/PagesSection.vue#L6

**Comment by bastianallgeier** [comment]
@afbora thanks for solving this!
