### ISSUE TITLE
[Panel] Pagination dialog goTo() method issue

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2228]
**Describe the bug**  
It's kind of complicated :)) You can view the steps and screenshots.

**To Reproduce**  
1. Go to panel
2. Paginate any section
3. Click on pagination to open dialog
4. Do not change page number
5. Click angle-up icon
6. Now click right angle to change page number
7. Going to last page instead of 2nd page

**Expected behavior**  
Should go to the next page.

**Screenshots**  
![pagination](https://user-images.githubusercontent.com/3393422/67146181-341ce780-f291-11e9-81e3-c2d9966a6b1c.gif)

**Kirby Version**  
3.2.5 & Develop Branch

**Additional context**  
This error occurs only when the current page and the page number entered are the same.

**Comment by bastianallgeier** [comment]
✅
