### ISSUE TITLE
[Cms] Wrong png mime type

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#223]
In upload error file modal:

>Upload errors
logo_sv.png
Invalid mime type

It's a working png file.

**Comment by bastianallgeier** [comment]
Do you have the file available so I can give it a try? Which browser was this?

**Comment by jenstornell** [comment]
I mailed it to you now. I hope you got it. It was Google Chrome on Windows but I bet it works the same on a Mac.
