### ISSUE TITLE
Issue about loading translation rules

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2230]
This bug details are in comments after this: https://github.com/getkirby/kirby/issues/1903#issuecomment-541344389

```
<?php
echo Str::slug("Компания");
echo t('something');
echo Str::slug("Компания");
?>
```

In RU language I get:
```
kompanija
translation of something
kompaniya
```

See difference `j` to `y`

**Comment by bastianallgeier** [comment]
✅
