### ISSUE TITLE
Setting API locale does not work for many locales

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2233]
This https://github.com/getkirby/kirby/blob/master/src/Api/Api.php#L178-L199 does not work for locales without `_` where the first and second part are not equal, e.g. `en_US` from `en`.

Maybe we should add something like:
https://github.com/peterkahl/country-to-locale

**Comment by afbora** [comment]
I just saw this component, maybe we can use it: `Symfony Locale Component`

https://github.com/symfony/Locale
https://symfony.com/doc/2.1/components/locale.html

**Comment by lukasbestle** [comment]
The Symfony component is long deprecated, we can‘t use that. It points to the “more capable” PHP Intl extension, but that one doesn’t provide this feature... 😫

@distantnative Doesn’t your suggestion convert the wrong way around? We’d need the opposite of “language to locale”.

Maybe a simple but manual solution could be to have a new `locale` key in our translation files that could then be manually filled with the correct locale for each Panel translation.

**Comment by afbora** [comment]
> Maybe a simple but manual solution could be to have a new locale key in our translation files that could then be manually filled with the correct locale for each Panel translation.

I agree. How can I set the locale of our site as we want from the config file, the locale value of the user should also be updated. For example, there are dozens of locales in English.

To get all the locales, we could use `ResourceBundle::getLocales()`, a class like the following for the default locale.

And how about we create a new `Locales` class and get it from an array containing the default locale values of the languages? 🤔 

````php
<?php

class Locales {
    $locales = [
        ...
        'ar' => 'ar_SA',
        'en' => 'en_US',
        'de' => 'de_DE',
        'tr' => 'tr_TR',
        ...
    ];
    
    public function get(string $language) {
        ...
    }
    
    public function locales(string $language) {
        return $this->locales;
    }

    public function all(string $language) {
        return ResourceBundle::getLocales('');
    }
}
````

**Comment by lukasbestle** [comment]
As I said, I think we should manually include the locales in the [`i18n/translations` files](https://github.com/getkirby/kirby/tree/3.2.5/i18n/translations) as a translation key.

The code in question works on the user language. The user language can only be one of the available Panel languages, so it's easy to map between the language and locale that way without having to guess.

**Comment by distantnative** [comment]
Sounds good, @lukasbestle

**Comment by bastianallgeier** [comment]
✅
