### ISSUE TITLE
Sql.php creates invalid SQLite query when using primary key

### ISSUE THREAD

**Issue by danielbuechele** [getkirby/kirby#2234]
**Describe the bug**  
I want to create a table using the SQLite functions shipped with kirby. The problem I am experiencing is, it creates invalid queries.

**To Reproduce**  

```php
$_CHARGE = [
  "id"   => [ "name" => "id" ,  "type" => "text", "null" => false, "key" => "PRIMARY KEY" ],
  "time" => [ "name" => "time", "type" => "int",  "null" => false ],
  "card" => [ "name" => "card", "type" => "text", "null" => false ],
];

$db = new Database(array(
  'type'     => 'sqlite',
  'database' => './logs.sqlite'
));

$result = $db->createTable($tableName, $_CHARGE);
```

**Versions**  
PHP version: 7.3.7
SQLite: 3.24.0
Kirby: 3.2.3

**Actual output**  

This is the query that is created:
```sql
CREATE TABLE "transactions" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "time" INTEGER NOT NULL,
  "card" TEXT NOT NULL,
  PRIMARY KEY ("id")
)
```
Which causes an error executing in SQLite:
`Query 1 ERROR: table "transactions" has more than one primary key`

The primary key can not be defined with the column and at the end of the query.

**Comment by lukasbestle** [comment]
Thanks for letting us know. I think we'll switch to defining primary keys just at the end of the query as that syntax works for both single as well as combined primary keys at the same time.

Until this is fixed, you can use the `$database->execute()` method with a raw query. If the table name is dynamic, you can escape it with `$database->sql()->quoteIdentifier($tableName)`.

**Comment by lukasbestle** [comment]
We have decided to refactor the database classes and fix this bug in the process. I think it is much more useful to build a solid a foundation than to fix a bug and create another one with the fix. :)

As refactorings often lead to small breaking-changes, we need to move this to the next minor release, 3.4.0. Thanks for your understanding.

**Comment by bastianallgeier** [comment]
✅
