### ISSUE TITLE
[Panel]: "Maximum call stack size exceeded." with empty Structure `fields` parameter

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2236]
**Describe the bug**  
If you specify a `structure` field with an empty `fields` parameter, the Panel will display a "Maximum call stack size exceeded." error when you try to add an item to the Structure.

**To Reproduce**  
1. Add a structure field to a Blueprint, but leave the `fields` property empty
```yaml
recommendations:
  type: structure
  fields:
```
2. Open the page in the Panel
3. Click the "Add" button for the structure

**Expected behavior**  
I would expect a more user-friendly error message saying that that the `fields` parameter is empty.

For example, if you completely omit the `fields` parameter, it gives a proper Blueprint error saying "Please provide a value for “fields”".

**Screenshots**  
<img width="356" alt="Screen Shot 2019-10-21 at 1 12 47 PM" src="https://user-images.githubusercontent.com/417182/67239643-7dda0f00-f404-11e9-93df-a032657f7e17.png">

**Kirby Version**  
`3.2.5`

**Console output**  
```
[Warning] RangeError: Maximum call stack size exceeded. — app.js:1:65982 (app.js, line 1)
```

**Desktop (please complete the following information):**  
 - OS: macOS 10.15
 - Browser: Safari 13.0.2
 - Browser: Chrome 77.0.3865.120

**Comment by bastianallgeier** [comment]
✅
