### ISSUE TITLE
[3.3.0 RC 1] Multilingual routing broken 

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2237]
Routing on a multilingual install of 3.3.0 RC 1 is broken and all request are redirected to the error page. The install is running in a subfolder on localhost, e. g. `http://localhost:8888/example.com`. @afbora discovered on Slack that this might be the culprit.

**Comment by nilshoerrmann** [comment]
This issue first occured with the changes in https://github.com/getkirby/kirby/commit/13aced5485fcfc1b5b3fd2136e329161ee9ec919.

**Comment by afbora** [comment]
In my tests, I noticed that it no longer works in the subfolder

**Comment by afbora** [comment]
@bastianallgeier The line that caused the error is as follows. The if condition always returns false if app run in subfolder and the language routes never load.

https://github.com/getkirby/kirby/blob/release/3.3.0/src/Cms/LanguageRoutes.php#L26-L29

**Comment by nilshoerrmann** [comment]
I'm not sure if it'll help solving this issue but during the 3.0 alpha we had issues with the session handling on subfolder installs: https://github.com/getkirby/kirby/issues/472. This got resolved somehow.

**Comment by bastianallgeier** [comment]
I think I solved it. Could you give it a try once RC2 is here later today? Feel free to reopen, if it still happens.

**Comment by nilshoerrmann** [comment]
Updating to https://github.com/getkirby/kirby/commit/0ef8b56f8195f376ecaa27d62b0381e266483071 doesn't solve the issue for me. All pages still return a `404` error 😕

PS: I cannot reopen the issue.

**Comment by bastianallgeier** [comment]
Ok, there's another fix. It's working for @afbora. @nilshoerrmann could you try again?

**Comment by nilshoerrmann** [comment]
Yes, the above change fixes the issue!
