### ISSUE TITLE
[RC1][Panel] Cannot use 'in' operator to search for 'changes' in undefined

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2238]
> Cannot use 'in' operator to search for 'changes' in undefined

**Describe the bug**  
I'm getting above error on trying to change user email address

**To Reproduce**  
1. Go to panel
2. Go to users list
3. Click to change email address of any user
4. Do not change anything
5. Click to change button
6. See error

**Note**: If not, repeat the process after refreshing the page

**Screenshots**  
![FireShot Capture 784 - Users - Mægazine - http___localhost_test_kirby_3 3 0_panel_users](https://user-images.githubusercontent.com/3393422/67302039-f02c1b80-f4f8-11e9-95d9-de285e05a7cc.png)

**Kirby Version**  
3.3.0 RC-1

**Console output**  
No output

**Comment by afbora** [comment]
I found that the following line is causing the error. I think this error has occurred because I tried to make changes without entering the user's page.

https://github.com/getkirby/kirby/blob/release/3.3.0/panel/src/store/modules/content.js#L156

**Comment by bastianallgeier** [comment]
✅
