### ISSUE TITLE
[3.3.0RC1][Panel] Undefined is not an object (evaluating 'e.id')

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#2242]
**Describe the bug**  
Clicked on the new changes history icon in the top left on the panel's home page.
Got this modal as a result.

![Screenshot 2019-10-22 at 18 29 46](https://user-images.githubusercontent.com/1738077/67308318-303fce00-f4fa-11e9-96fc-5df265ae3a01.png)

**To Reproduce**  
1. Go to panel homepage
2. Make a change
3. Click the icon in the top right

**Kirby Version**  
3.3.0-RC1

**Console output**  
![Screenshot 2019-10-22 at 18 33 19](https://user-images.githubusercontent.com/1738077/67308438-654c2080-f4fa-11e9-8a73-1f127b8ecb53.png)

**Additional context**  
This is in Safari 13.0.2
I simply updated my personal site to the latest rc and tried the new feature.

**Comment by afbora** [comment]
@manuelmoreale I can't reproduce this issue. Can you try again after clearing cookies and caches? Do you have a chance to try with another browser please?

**Comment by manuelmoreale** [comment]
@afbora Cleared cookie/cache/local storage.
Error still there.

Tried on FF 71.0b2 (64-bit)
![Screenshot 2019-10-23 at 09 50 26](https://user-images.githubusercontent.com/1738077/67370287-ab48c900-f57a-11e9-9d93-5fe2c01b459c.png)

**Comment by bastianallgeier** [comment]
Ahh, it doesn't happen on the home page, but when you make changes to the site.

**Comment by bastianallgeier** [comment]
✅
