### ISSUE TITLE
[Panel] New Page Dialog Gives Unclear Error When Missing URL Appendix

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2243]
**Describe the bug**  
When trying to create a new page in the panel, if the "URL appendix" field is empty (either because the slug rules leave it empty or you manually clear it), clicking the "Create draft" button shows this error: "A page draft with the URL appendix "" already exists"

**To Reproduce**  
1. Click "Add" button in panel
2. Type in a title
3. Clear out the "URL appendix" field
4. Click "Create draft"

**Expected behavior**  
Should say that a URL appendix is required

**Screenshots**  
<img width="498" alt="Screen Shot 2019-10-22 at 2 55 38 PM" src="https://user-images.githubusercontent.com/417182/67337630-4343a580-f4dc-11e9-9089-de24d5ccc393.png">

**Kirby Version**  
`3.2.5` and `3.3.0-rc.1`

**Console output**  
```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (children, line 0)
[Error] {status: "error", message: "A page draft with the URL appendix \"\" already exists", code: 400, exception: "Kirby\\Exception\\DuplicateException", key: "error.page.draft.duplicate", …}
	(anonymous function) (app.js:1:260019)
	(anonymous function) (app.js:1:255723)
	promiseReactionJob
```

**Desktop (please complete the following information):**  
 - OS: macOS 10.15
 - Browser: Safari
 - Version: 13.0.2

**Comment by bastianallgeier** [comment]
✅ The slug is now validated at first and a better error message is sent.
