### ISSUE TITLE
[3.3.0RC1] Lock conflict on pages with unsaved changes

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2245]
**Describe the bug**  
On a page with unsaved changes the panel throws three consecutive errors in the console. The save bar is disfunctional and doesn't react to clicks. Panel navigation still works.

**To Reproduce**  
1. Update to 3.3.0 RC 1.
2. Go to a page with unsaved changes.

**Expected behavior**  
No errors and a functional save bar.

**Kirby Version**  
Kirby 3.3.0 RC 1.

**Console output**  
```
{
	status: "error", 
	message: "An error occurred", 
	code: 501, 
	exception: "Kirby\\Exception\\Exception", 
	key: "error.lock.notImplemented", 
	file: "/hananils.2019/kirby/config/api/routes/lock.php", 
	line: 34, 
	details: [], 
	route: "(.*)/lock" 
}
```
```
{ 
	status: "error", 
	message: "An error occurred", 
	code: 501, 
	exception: "Kirby\\Exception\\Exception", 
	key: "error.lock.notImplemented", 
	file: "/hananils.2019/kirby/config/api/routes/lock.php", 
	line: 48, 
	details: [], 
	route: "(.*)/lock" 
}
```
```
uncaught exception: Object
```

**Desktop (please complete the following information):**  
 Firefox 70 on macOS Catalina.

**Additional context**  
Content locking is disabled, this is a multilingual install. I'm not sure if this is a routing issue that might be connected to #2237 but for some reasons this does only happen on pages with changes.

Not sure if this is relevant but all changes stored in local storage were made before updating. The widget that displays pending changes globally doesn't display all changes stored in local storage.

**Comment by afbora** [comment]
I can't reproduced this issue with `subfolder`, `multilang` and `content.locking` enabled or disabled.

**Comment by nilshoerrmann** [comment]
Hm, not sure which info to provide for further debugging …

**Comment by distantnative** [comment]
Could you provide some more information on the page type? Just standard, one with a page model, virtual page?

**Comment by nilshoerrmann** [comment]
It's a standard page, one blueprint extending the other. Content coming from the `content` folder.

**Comment by nilshoerrmann** [comment]
I'm just asking myself if this might have to do with the Editor field. I see that the object in local storage flags my `text` field as changed. There are no changes I know of. So I deleted the entry in local storage and reloaded the page. And the entry in local storage gets restored.

**Comment by distantnative** [comment]
The error messages you are getting should not be connected to that directly - the exception gets thrown when content locking is deactivated but should be caught and the Panel should react properly.

**Comment by nilshoerrmann** [comment]
I see, thanks.

**Comment by thathoff** [comment]
I have seen a similar behaviour but also on v3.2.5. I’m not sure this is exactly the same problem because I did not manage to get the console logs but the described behaviour is exactly the same: You have unsaved changes but the Save button is greyed out and not clickable. After reloading the page everything is fine (thanks to local storage all changes are still there) and you can hit save again.

**Comment by afbora** [comment]
I can reproduce this issue when refresh the unsaved page 👍 

![image (3)](https://user-images.githubusercontent.com/3393422/67383211-76973a80-f597-11e9-891c-850662ee2b60.jpg)

**Comment by afbora** [comment]
This error from `/lock` PATCH request before `/lock` GET request that get `supported` option. So system still thinks that the `supported` / `content.locking` option is enabled.

**Comment by bastianallgeier** [comment]
✅
