### ISSUE TITLE
[3.3.0RC1][Panel] Minor CSS glitch in save bar

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#2246]
**Describe the bug**  
Minor css glitch on the save button.
This is in safari 13 on mac.

![ezgif-4-41db499f1d21](https://user-images.githubusercontent.com/1738077/67370582-35912d00-f57b-11e9-9532-24f2a3fa8f09.gif)

**Comment by bastianallgeier** [comment]
✅
