### ISSUE TITLE
[Panel] Searching in users field

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2247]
This is not really a bug because technically, everything is working. But the users field's search is misleading. We have the following user list:

![Bildschirmfoto am 2019-10-23 um 15 10 45](https://user-images.githubusercontent.com/25466/67396117-53748700-f5a7-11e9-94dc-d1749cd8044f.png)

1. Searching for `hana` doesn't change the result list. I expected to get the user `hana+nils` only.
2. Searching for `+` returns nothing. I expected to get the user `hana+nils`.

Finally, I understood that the search doesn't look at the names but at the e-mail addresses only. Now the results make sense because:

1. All e-mail addresses contain `hananils.de`.
2. None of the e-mail addresses contains a `+`.

### Expected behaviour

The user search should take user name an e-mail address into account. If would be great if the e-mail address was visible as well on the user items so that the editors can make sense of the result lists.

**Comment by GiantCrocodile** [comment]
The list of indexed user fields for the search should be configurable to support custom fields, especially if the users are getting less dependent on the email account provided.

**Comment by bastianallgeier** [comment]
It's not exactly a bug as you said. I think it's correct that email address and names are matched. "+" is removed from the search string as a non-word character. That's why the email addresses always match. We should work on enhanced matches, but that's tricky. I will remove the 3.3.0 milestone. We cannot fix this for this release.

**Comment by nilshoerrmann** [comment]
If the user search is matching e-mail addresses **and** names already, I'm owing my search results to unfortunate circumstances. Let's close this issue.

**Comment by nilshoerrmann** [comment]
We can gather concepts for improved searching in the ideas issue tracker.
