### ISSUE TITLE
[3.3.0-rc.2][Panel]: null is not an object (evaluating 'i.api')

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2249]
**Describe the bug**  
When I load the Panel, I get the following error:
> null is not an object (evaluating 'i.api')

Happens in Safari, but doesn't seem to happen in Chrome.

**To Reproduce**  
1. Open the Panel in Safari

**Screenshots**  
<img width="392" alt="Screen Shot 2019-10-25 at 1 43 12 PM" src="https://user-images.githubusercontent.com/417182/67603606-4504a780-f72e-11e9-8a3a-17826e139cf6.png">

**Kirby Version**  
`3.3.0-rc.2`

**Console output**  
```
[Error] TypeError: null is not an object (evaluating 'i.api')
(anonymous function) — app.js:1:245005
forEach
init — app.js:1:244905
(anonymous function) — vendor.js:17:5564
(anonymous function) — vendor.js:17:6871
created — app.js:1:267012
oe — vendor.js:41:11776
zn — vendor.js:41:29223
(anonymous function) — vendor.js:41:34586
$r — vendor.js:41:35313
56d7 — app.js:1:266863
o — app.js:1:526
(anonymous function) — app.js:1:1521
o — app.js:1:526
n — app.js:1:390
(anonymous function) — app.js:1:1486
Global Code — app.js:1:1490

	(anonymous function) (app.js:1:261043)
	ie (vendor.js:41:11984)
	re (vendor.js:41:11698)
	oe (vendor.js:41:11899)
	zn (vendor.js:41:29223)
	(anonymous function) (vendor.js:41:34586)
	$r (vendor.js:41:35313)
	56d7 (app.js:1:266863)
	o (app.js:1:526)
	(anonymous function) (app.js:1:1521)
	o (app.js:1:526)
	n (app.js:1:390)
	(anonymous function) (app.js:1:1486)
	Global Code (app.js:1:1490)
```

**Desktop (please complete the following information):**  
 - OS: macOS 10.15
 - Browser: Safari
 - Version: 13.0.2

**Comment by distantnative** [comment]
@bastianallgeier maybe that is from also loading the old form store entries?

**Comment by neildaniels** [comment]
@distantnative Could be. I don't get the error when loading the Panel in Private Browsing mode in Safari.

**Comment by foobartel** [comment]
I do see this issue in Chrome, but only when reloading the panel, not when navigating. 

```
TypeError: Cannot read property 'api' of null
    at app.js:1
    at Array.forEach (<anonymous>)
    at h.init (app.js:1)
    at Array.<anonymous> (vendor.js:17)
    at h.dispatch (vendor.js:17)
    at h.dispatch (vendor.js:17)
    at $r.created (app.js:1)
    at oe (vendor.js:41)
    at zn (vendor.js:41)
    at $r.t._init (vendor.js:41)
z.a.config.errorHandler @ app.js:1
ie @ vendor.js:41
re @ vendor.js:41
oe @ vendor.js:41
zn @ vendor.js:41
t._init @ vendor.js:41
$r @ vendor.js:41
56d7 @ app.js:1
o @ app.js:1
0 @ app.js:1
o @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1

```

**Comment by bastianallgeier** [comment]
I think I fixed it, but I wasn't able to reproduce it in the first place. Could you give it a try. Feel free to open if it still exists in 3.3.0-rc.3
