### ISSUE TITLE
Support Redis as a cache driver

### ISSUE THREAD

**Issue by jancbeck** [getkirby/kirby#225]
http://redis.io/documentation
https://github.com/nrk/predis

**Comment by fnkr** [comment]
+1

**Comment by jancbeck** [comment]
I have tried my implementation of Predis but I have failed to properly include it into Kirby. Perhaps someone else wants to try:
https://gist.github.com/jancbeck/83acdfe8dd0e92fe2c56

**Comment by lukasbestle** [comment]
You need to add `use Predis\Client;` at the top to make the Predis library available in the file.

**Comment by jancbeck** [comment]
@lukasbestle it's not just that but the whole integration into toolset and vendor/composer that I struggled with.

**Comment by nblackburn** [comment]
I have a rough implementation of this working, i might send a PR once i have something more refined.

**Comment by lukasbestle** [comment]
Sure, go ahead. :)

**Comment by lukasbestle** [comment]
See getkirby/toolkit#229.

**Comment by jancbeck** [comment]
Great. I'll close this one.
