### ISSUE TITLE
[Cms] Define DS even if we don't use it

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#225]
I tried one of my older plugins:

```php
require_once __DIR__ . DS . 'lib' . DS . 'ga.php';
```

So I guess there is a replacement for DS?

>Notice: Use of undefined constant DS - assumed 'DS' in D:\projects\kirby\3.0-alpha-4\site\plugins\kirby-ga\index.php on line 2

**Comment by bastianallgeier** [comment]
We don’t need it internally anymore. The separator thing doesn’t seem to be an issue on Windows anymore. But it would make sense to define it anyway for compatibility reasons.

**Comment by bastianallgeier** [comment]
✅

**Comment by bnomei** [comment]
not done in beta-3. will this be done at all?
