### ISSUE TITLE
Unsaved changes icon not visible when license not registered

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2250]
**Describe the bug**  
As the title says.

**To Reproduce**  
1. Go to unregistered Panel.
2. Make some changes
3. See how the unsaved changes icon does not show up
4. Register license.
5. See icon

**Expected behavior**  
The feature should also work for non-registered versions.

**Kirby Version**  
3.3.0 rc-2

**Comment by lukasbestle** [comment]
This was discussed in #1980 before.

@distantnative Did you do it that way deliberately because there isn't enough room for all the buttons at once or is this just a current limitation?

**Comment by texnixe** [comment]
I thought it might have been a deliberate decision, but that doesn't make sense for people evaluating Kirby or for people who use a staging server. Checked issues but not PR discussions before posting.

**Comment by distantnative** [comment]
There simply isn’t enough space on smaller screens, that’s why.

**Comment by texnixe** [comment]
🤔 That doesn't sound Kirby-like to me...

**Comment by GiantCrocodile** [comment]
I think it is more likely that someone faces this issue now. A non-registered or staging/dev server is most likely more common than a too small screen (and I had a small screen for many years). I support @texnixe point of view here and I'm not positively sure what this decision will mean for future issues like that.

**Comment by distantnative** [comment]
Sorry, I wrote my last comment while on the way somewhere. Just realized how strongly worded it was, not my intention. It's simply a matter of a better solution, so let's bring on ideas :)

**Comment by GiantCrocodile** [comment]
What about stacking Register and Buy a License? If that's not possible, what about removing the buy a license option or merge it into the red text as a link? I doubt that it increases the sales.

**Comment by texnixe** [comment]
I was about to suggest the same as @GiantCrocodile, we do that for the path, why not for the license stuff on mobile.

**Comment by bastianallgeier** [comment]
The license notice is very important for us and it definitely increases sales. I got dozens of support emails already from clients that realised with v3 for the first time that they don't have a license at all and need one. It's not just about intentionally pirating Kirby, but about not noticing that it needs a license at all or not realising that an installation is not registered yet. 

I will try to find a solution.

**Comment by bastianallgeier** [comment]
✅ ok, the changes are now always visible. It takes more space together with the registration notice, but as your feedback shows that's more acceptable than hiding it.
