### ISSUE TITLE
[3.3.0-rc.3][Panel]: null is not an object (evaluating 'i.api')

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2253]
**Describe the bug**
Reopening #2249. Still present in 3.3.0-rc.3. Additional information in reproduction steps. Seems like a Local Storage value of `null` causes the issue.

When I load the Panel, I get the following error:
> null is not an object (evaluating 'i.api')

**To Reproduce**  
1. Have something like the following in Local Storage for the domain that the Panel is loaded on:
**Key:** `kirby$form$test/foo/logo.svg`
**Value:** `null`
2. Load the Panel in Safari

**Screenshots**  
<img width="392" alt="Screen Shot 2019-10-25 at 1 43 12 PM" src="https://user-images.githubusercontent.com/417182/67603606-4504a780-f72e-11e9-8a3a-17826e139cf6.png">

**Kirby Version**  
`3.3.0-rc.3`

**Console output**  
```
[Error] TypeError: null is not an object (evaluating 'i.api')
(anonymous function) — app.js:1:245056
forEach
init — app.js:1:244975
(anonymous function) — vendor.js:9:71506
(anonymous function) — vendor.js:9:72813
created — app.js:1:267143
oe — vendor.js:17:11862
zn — vendor.js:17:29309
(anonymous function) — vendor.js:17:34672
$r — vendor.js:17:35399
56d7 — app.js:1:266994
o — app.js:1:526
(anonymous function) — app.js:1:1521
o — app.js:1:526
n — app.js:1:390
(anonymous function) — app.js:1:1486
Global Code — app.js:1:1490

	(anonymous function) (app.js:1:261174)
	ie (vendor.js:17:12070)
	re (vendor.js:17:11784)
	oe (vendor.js:17:11985)
	zn (vendor.js:17:29309)
	(anonymous function) (vendor.js:17:34672)
	$r (vendor.js:17:35399)
	56d7 (app.js:1:266994)
	o (app.js:1:526)
	(anonymous function) (app.js:1:1521)
	o (app.js:1:526)
	n (app.js:1:390)
	(anonymous function) (app.js:1:1486)
	Global Code (app.js:1:1490)
```

**Desktop (please complete the following information):**  
 - OS: macOS 10.15
 - Browser: Safari
 - Version: 13.0.2

**Comment by bastianallgeier** [comment]
That's super helpful! Thank you @neildaniels

**Comment by foobartel** [comment]
I can confirm the above. If Local Storage is cleared, it doesn't show the error. If you add a null value as described above, the error re-appears.

**Comment by bastianallgeier** [comment]
✅  Ok, one more try :)
