### ISSUE TITLE
[Panel] Mailto link to null on email field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2254]
**Describe the bug**  
You can click the email icon in the license registration window (this is all about the email field)
The link is also incorrect when there are empty or invalid emails.

**To Reproduce**  
1. Go to panel
2. Click on Register top navbar
3. Click on envelope/email icon
4. See weird linking to null mail

Or 

1. Go to panel
2. Edit any page/user that have empty email field
3. Click on envelope/email icon
4. See weird linking to null mail

**Expected behavior**  
1. It didn't make sense to link to `mailto:null` or own email address in this dialog.
2. The link on the icon can be removed according to the usage.
3. Only the link should be given when the email field is filled.

**Screenshots**  
![image](https://user-images.githubusercontent.com/3393422/67707727-1146ad80-f9cc-11e9-9aad-38577ef9595e.jpg)

**Kirby Version**  
3.2.5+

**Comment by bastianallgeier** [comment]
✅
