### ISSUE TITLE
Draft page and siblings

### ISSUE THREAD

**Issue by maxackerman** [getkirby/kirby#2258]
```$page->siblings()``` does not work for draft pages.

kirby version: 3.2.5

---

If a page is in draft mode, ```$page->siblings()``` does not work as expected. I would think it would act like an unlisted page and return the siblings, but instead it throws an error: **Call to a member function url() on null**

```$page->parent()->children();``` works, and seems like a workaround to get the siblings.

**Comment by texnixe** [comment]
I can't reproduce this in 3.3.0-rc3; if you call`$page->siblings()` on a draft page, it returns all other draft siblings, but not listed or unlisted siblings.

**Comment by maxackerman** [comment]
I expected ```$page->siblings()``` on a draft page to return the listed and unlisted sibling pages. But maybe that is wrong.

**Comment by afbora** [comment]
This is not wrong. As the document says: `Drafts are only accessible when you are logged in.` Therefore `siblings()` method returns `drafts` if the page status is draft or children (listed/unlisted) if it is not as @texnixe said

````php
protected function siblingsCollection()
{
    if ($this->isDraft() === true) {
        return $this->parentModel()->drafts();
    } else {
        return $this->parentModel()->children();
    }
}
````

https://github.com/getkirby/kirby/blob/release/3.3.0/src/Cms/PageSiblings.php#L193-L200

But you can solve it in many different ways. I can give one example;

````php
$page->childrenAndDrafts()->not($page);
````
