### ISSUE TITLE
[3.3.0-rc.3][Panel] Using "Prev"/"Next" Button on Structure Doesn't Update `number` Sub-Fields

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2259]
**Describe the bug**  
If you have a `structure` field with a `number` sub-field, when you click "Prev" or "Next" while the values for `number` field don't get update.

**To Reproduce**  
1. Have a `structure` field like:
```yaml
test:
  type: structure
  fields:
    mynum:
      type: number
```
2. In the Panel, create like 3 items in structure field, with values such as `1`, `2`, `3`
<img width="267" alt="Screen Shot 2019-10-29 at 4 19 12 PM" src="https://user-images.githubusercontent.com/417182/67816638-dd20ca80-fa67-11e9-8ede-fc745e78fbce.png">
3. Open the 2nd item (`2`)
<img width="1045" alt="Screen Shot 2019-10-29 at 4 17 39 PM" src="https://user-images.githubusercontent.com/417182/67816589-a64ab480-fa67-11e9-936a-b1c0e48ecb82.png">
4. Click on the "next" button
<img width="1021" alt="Screen Shot 2019-10-29 at 4 20 07 PM" src="https://user-images.githubusercontent.com/417182/67816691-03df0100-fa68-11e9-9285-39a8141173ef.png">

**Expected behavior**  
The number in the field should change to 3. Instead, it stays as 2.

**Screenshots**  
[Screen Recording 2019-10-29 at 4.14.56 PM.zip](https://github.com/getkirby/kirby/files/3786174/Screen.Recording.2019-10-29.at.4.14.56.PM.zip)

**Kirby Version**  
`3.3.0-rc.3`. (Works fine on `3.2.5`.)

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.2

**Comment by bastianallgeier** [comment]
✅
