### ISSUE TITLE
[Panel] Nothing appears when empty site title

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2261]
**Describe the bug**  
1. When the site title is left blank, a warning is given in red but it is allowed to be saved blank.
2. If the blank is saved, there are no marks in the panel to edit the site title.

**To Reproduce**  
1. Go to panel
2. Edit site title as empty
3. See nothing about site title

**Screenshots**  
![FireShot Capture 790 -  - http___localhost_test_kirby_3 3 0_panel_site](https://user-images.githubusercontent.com/3393422/67853225-2122d680-fb1f-11e9-8fba-47223b6dbd6c.png)

**Expected behavior**  
![FireShot Capture 789 - mark@otto com - http___localhost_test_kirby_3 3 0_panel_users_5fzl5pcb](https://user-images.githubusercontent.com/3393422/67853240-27b14e00-fb1f-11e9-9336-20969713afc1.png)

The site title must be requiered or if left blank, a placeholder should appear like the username.

**Kirby Version**  
3.3.0 (I guess on older versions)

**Comment by bastianallgeier** [comment]
✅
