### ISSUE TITLE
Clicking on the language in the Settings should open the edit dialog

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2264]
**Describe the bug**  
Any other field is editable by clicking on it. Only the language in Settings is not editable on click. This should be changed to improve the usability by a more uniform system behavior. Right now, nothing happens if you click it. You have to use the three dots on the right side of the entry and choose edit.

**To Reproduce**  
1. Go to Settings
2. Click on any language like the default language

**Expected behavior**  
Clicking on the language opens the edit dialog.

**Kirby Version**  
3.3.0 rc4

**Comment by afbora** [comment]
Collection ui kit `<k-collection>` wants to `link` property for each item to click. 
However, since language editing is in the dialog, it needs to be done in a slightly different way :innocent: For example manual listing items instead of using `<k-collection>` like following:

````vue
<k-list>
   <k-list-item></k-list-item>
   <k-list-item></k-list-item>
</k-list>
````

**Comment by GiantCrocodile** [comment]
Sounds like it is still an easy issue, although it has to be implemented a bit different :)? I'm glad that you dig through my issues and work on so many issues actively. Great work @afbora!

**Comment by bastianallgeier** [comment]
✅ fixed on the develop branch. Will be in 3.3.2
