### ISSUE TITLE
`site.yaml` leads to 500: "Call to a member function options() on null"

### ISSUE THREAD

**Issue by Akkora** [getkirby/kirby#2265]
**To Reproduce**  
1. Go to 'site/blueprints'
2. Rename file from site.yml to site.yaml

**Expected behavior**  
site.yaml and site.yml should be working

**Kirby Version**  
3.2.5

**Screenshots**  
![image](https://user-images.githubusercontent.com/10886924/67955254-9b705b00-fbf2-11e9-8725-95871b10d374.png)

**Network Tab output**  
```
Request URL: https://my.kirbywebsite.test/api/site?view=panel
Request Method: GET
Status Code: 500 
Remote Address: 127.0.0.1:443
Referrer Policy: no-referrer-when-downgrade
{
  "status": "error",
  "message": "Call to a member function options() on null",
  "code": 500,
  "exception": "Error",
  "key": null,
  "file": "ModelPermissions.php",
  "line": 32,
  "details": [],
  "route": "site"
}
```

**Additional context**  
The change of the file extension was already discussed and should be supported: https://github.com/getkirby/kirby/issues/1447

**Comment by distantnative** [comment]
We have an idea issue here: getkirby/ideas#150

**Comment by bnomei** [comment]
@distantnative same error will show up if there the yaml in the site.yml can not correctly be parsed by kirby. like wrongly indented field etc.
