### ISSUE TITLE
[Panel] date field using "today" button gives "dayjs is not defined"

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#2266]
**Describe the bug**  
Using the "today" button in a date field in the panel hides the field and displays the message "dayjs is not defined".

**To Reproduce**  
1. Create a date field
2. Go to the field in the panel
3. Click on the calendar icon
4. Click on the "Today" button
4. See error "dayjs is not defined"

**Expected behavior**  
Fill the field with todays date.

**Screenshots**  
![Bildschirmfoto 2019-10-31 um 22 25 15](https://user-images.githubusercontent.com/50926857/67987415-9b418100-fc2d-11e9-962b-d734f3b81cc9.png)

**Kirby Version**  
3.3.0-rc.4

**Desktop (please complete the following information):**  
 - OS: macOS Sierra 10.12.6
 - Browser: Firefox
 - Version: 70.0

**Comment by distantnative** [comment]
✅
