### ISSUE TITLE
Add youtube-nocookie.com to video tag

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2273]
The domain `youtube-nocookie.com` should be recognized by the YouTube helper and video tag.

**Comment by lukasbestle** [comment]
It should already be. Could you please post your code so that I can reproduce the issue?

**Comment by GiantCrocodile** [comment]
This does work within my Kirby 3 textfield:

`(video: https://youtu.be/9vq7W7W9JPA?t=388 class: embed-responsive embed-responsive-16by9 caption: Gronkh's Borderlands 3 Video)`

while

`(video: https://youtube-nocookie.com/9vq7W7W9JPA?t=388 class: embed-responsive embed-responsive-16by9 caption: Gronkh's Borderlands 3 Video)`

doesn't. The video is not being embedded. In my template I do use this:

`$page->text()->html()->kirbytext()`

**Comment by GiantCrocodile** [comment]
Oh give me a second ... seems I was wrong.

**Comment by GiantCrocodile** [comment]
`(video: https://youtube-nocookie.com/embed/9vq7W7W9JPA?t=388 class: embed-responsive embed-responsive-16by9 caption: Gronkh's Borderlands 3 Video)`

works. I did a mistake with the URL structure required (I suspected that if the URL is wrong, I would see some embed error like when I open the URL in the browser).
