### ISSUE TITLE
[Toolkit\File] Option to disable base64 encoding in `dataUri()` method

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#2276]
The `dataUri` method is quite handy, especially for inlining small resources like icons etc. The `dataUri` method always uses Base64 encoding, even if the file’s format is a plaintext format (e. g. SVG).

In those cases, encoding the file using Base64 wouldn’t be necessary. That’s not a severe problem, but it’s inefficient. Encoding using Base64 adds an [overhead of ~33 percent in file size](https://stackoverflow.com/questions/4715415/base64-what-is-the-worst-possible-increase-in-space-usage). Additionally, Base64-encoded data might [reduce the efficiency of gzip compression](https://csswizardry.com/2017/02/base64-encoding-and-performance/#gzip-saves).

I’d propose to disable Base64 encoding for plaintext formats or, alterantively, add an option to the `dataUri` method to disable it manually. As there are [some edge cases](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris) where it might be required or otherwise sensible to encode plaintext data, I think the latter would be best.

**Comment by lukasbestle** [comment]
I like the idea of a new param like `$file->dataUri(bool $base64 = true)` that makes it easy to control the behavior. The default would be backwards-compatible as well.

**Comment by distantnative** [comment]
✅
