### ISSUE TITLE
The text property on users fields is not working

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2278]
**Describe the bug**  
Setting the `text` property on a users field has no effect, neither with a string nor with a query. The username is displayed instead.

**To Reproduce**  
1. Define a users field like
```
fields:
  users:
    type: users
    text: "{{ user.email }}"
    info: "{{ user.email }}"
```
2. Select a user in the panel and see the result
![image](https://user-images.githubusercontent.com/18071758/68211455-e49c2280-ffd7-11e9-8498-b2e176d85201.png)

**Expected behavior**  
The text property should work like it does on pages fields

**Kirby Version**  
3.2.5, 3.3.0

**Comment by afbora** [comment]
Because of binded to `user.username` instead of `user.text`:

https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Field/UsersField.vue#L28

**Comment by bastianallgeier** [comment]
✅
