### ISSUE TITLE
sortBy in structure broken

### ISSUE THREAD

**Issue by gerricom** [getkirby/kirby#2279]
**Describe the bug**  
Kirby 3.3.0 breaks the `sortBy` property of a structure field. The panel prints 

> t.items is undefined

**To Reproduce**  
1. Get the starterkit
2. Edit `about.yml` and add `sortBy: platform asc` in the social-structure-field
3. Look at the panel - structure not usable

**Expected behavior**  
The structure should be sorted by the choosen value.

**Screenshots**  
![2019-11-05_16-04-30](https://user-images.githubusercontent.com/459469/68219242-f7b5ef00-ffe5-11e9-88c6-814410b3a15e.png)

**Kirby Version**  
3.3.0

**Console output**  
```
TypeError: "e.$helper is undefined"
TypeError: "t.items is undefined"
```

**Comment by bastianallgeier** [comment]
✅
