### ISSUE TITLE
Links with anchors are not handled correctly on multi language sites

### ISSUE THREAD

**Issue by fblome** [getkirby/kirby#2280]
**Describe the bug**  
If a link on a content page does contain an anchor, Kirby does not generate language correct links.

**To Reproduce**  
- A link like (link: /path/to/a/page text: something) works fine. 
- A link like (link: /path/to/a/page#target text: something with an anchor) does not works fine. In this case a language redirection does not happen but is expected.

**Affected Kirby version**  
- Found in Kirby 3.2.5

**Comment by distantnative** [comment]
Can reproduce this.

**Comment by bastianallgeier** [comment]
✅
