### ISSUE TITLE
Page changes are no longer saved with keyboard shortcut command+s

### ISSUE THREAD

**Issue by luxuryluke** [getkirby/kirby#2281]
**Describe the bug**  
Problem: Saving changes on the page via Command+S keyboard command no longer works.
Now Safari asks if I'd like to save a webarchive instead.

**To Reproduce**  
1. Edit an entry in Panel
2. Try the keyboard shortcut for "Save": Command+S
3. Browser attempts to save the page like any other website

**Expected behavior**  
The changes are saved.

**Kirby Version**  
3.3

**Desktop (please complete the following information):**  
 - OS: 10.14.6
 - Browser: Safari Desktop
 - Version: 13.03

**Comment by bastianallgeier** [comment]
This is extremely weird. We haven't really changed the keyboard shortcut for it and it still works fine on my end. I will investigate.

**Comment by texnixe** [comment]
Works fine for me as well, but still on Safari 12, OS: 10.14.3

**Comment by luxuryluke** [comment]
It worked for my prior to upgrading to K3.3, so I'm hunting down errors and bad code formatting.

**Comment by afbora** [comment]
@luxuryluke Could another plugin be causing this issue?  Are you getting this issue on fresh starterkit?

**Comment by luxuryluke** [comment]
Okay, I removed the Editor plugin, then I restarted the browser, and saving works via the shortcut now, but now it puts focus on the other field on the page (the multiselect field for Person) while the caret in the textarea blinks like I'm editing:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/57873/68241207-21115380-ffc3-11e9-8861-80c52cd260c3.png">

This was already noted in an Editor issue (https://github.com/getkirby/editor/issues/149) I filed this morning, **but now that Editor is no longer installed**, this could be a K3.3 issue, …or my code, which, will take time to review… :(

Rename this ticket or let's duplicate it into a new ticket specifically for this problem, if you like.

**Comment by afbora** [comment]
> but now it puts focus on the other field on the page (the multiselect field for Person) while the caret in the textarea blinks like I'm editing:

@luxuryluke Multiselect focus issue is related to #2295 and this issue may transfer to editor repository.

**Comment by luxuryluke** [comment]
@afbora Ahmet, I highlighted a part of my last comment that may be important to your response: The issue continued to happen after the Editor was uninstalled, FYI.

**Comment by afbora** [comment]
> this could be a K3.3 issue, …or my code, which, will take time to review

@luxuryluke Could you track down or review your codes?

**Comment by luxuryluke** [comment]
Just coming back to this now, I don't think I have any code implemented that would affect this bug. I just double checked, and I could be wrong, but this looks like either a K3.3 bug or a bug when using @sylvainjule 's Markdown plugin in K3.3 which is what I'm using now, …without Editor installed.

**Comment by bastianallgeier** [comment]
✅
