### ISSUE TITLE
Page slugs are no longer created correctly

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2282]
**Describe the bug**  
https://forum.getkirby.com/t/page-slug-not-generated-correctly/16186

**Comment by afbora** [comment]
I found the source of the issue.

**Here's our escape pattern in helper**:
````regex
/[\p{L}]|[-\/\\^$*+?.()|[\]{}]+/u
````

**After rendering**: /media/panel/xxx/app.js

````regex
/[Lp\{\}]|[\$\(-\+\x2D-\/\?\[-\^\{-\}]+/
````

https://github.com/getkirby/kirby/blob/master/panel/src/helpers/regex.js

When i update with original pattern in **app.js**, working properly. Any idea about rendering issue @bastianallgeier ?

**Comment by afbora** [comment]
Using the `u` flag single or with `g` (`/gu`), disrupts the pattern when rendering and removes the `u` flag 🤔

**Comment by bastianallgeier** [comment]
✅
