### ISSUE TITLE
[Panel] Number Field Does Not Save Empty Value After Losing Focus (3.3.0 Regression)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2288]
**Describe the bug**  
If you attempt to clear a `number` field in the Panel, it will only save the "empty" value if you save the page while the number field still has typing focus. If you click on another field, the "empty" value will never actually be saved (even if you click back into the original field).

I suspect there's something wrong with savings values in general, but can only reliably produce this "empty value" scenario as described.

**To Reproduce**  
1. Have the following Blueprint `test-template.yml`
```yaml
title: Test Template

fields:
  foo:
    type: number
    width: 1/2
  bar:
    type: number
    width: 1/2
  text:
    type: textarea
    width: 1/2
```
2. Have the following template `test-template.php`
```php
<html>
    <body>

Foo: <?= $page->foo()->html() ?>

<br><br>

Bar: <?= $page->bar()->html() ?>

<br><br>

Text: <?= $page->text()->html() ?>
```
3. Create a page in the Panel with this template type
4. Fill in values such as `2`, `4`, and `some text`.
<img width="1020" alt="Screen Shot 2019-11-06 at 2 27 14 PM" src="https://user-images.githubusercontent.com/417182/68343390-889dd080-00a1-11ea-8345-aad65e637852.png">

5. Save that in the Panel and view the page.
<img width="167" alt="Screen Shot 2019-11-06 at 2 26 49 PM" src="https://user-images.githubusercontent.com/417182/68343376-7a4fb480-00a1-11ea-91dc-4628dbb85a9e.png">

6. Go back to the Panel page and clear both number field _then_ change the text field to `other text`. **Save the page with Command-S**

<img width="1018" alt="Screen Shot 2019-11-06 at 2 28 03 PM" src="https://user-images.githubusercontent.com/417182/68343437-a66b3580-00a1-11ea-8202-dba6a3cf3025.png">
7. Re-load the rendered page.
<img width="155" alt="Screen Shot 2019-11-06 at 2 28 35 PM" src="https://user-images.githubusercontent.com/417182/68343473-b8e56f00-00a1-11ea-902f-b65d0b9f0cfc.png">
8. Go back to the Panel and re-load the page. You'll see that the original `2` and `4` values return.

**Kirby Version**  
`3.3.0`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Safari 13.0.3 (15608.3.10.1.4)
 - Chrome 78.0.3904.87

**Comment by bastianallgeier** [comment]
✅
