### ISSUE TITLE
nothing to repeat error in tags field with 3 asterisks

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2293]
**Describe the bug**  
When you type `***` into a tags field an error will be thrown: `nothing to repeat error in tags field`.

**To Reproduce**  
1. Edit a page with a tags field
2. insert three asterisks into it, one by one

**Expected behavior**  
No result or showing all results. I tried to use `*` as a placeholder value.

**Screenshots**  
This is what the field looks like afterwards:
![grafik](https://user-images.githubusercontent.com/6271057/68385057-420bad00-0159-11ea-8d15-607097b9a3ac.png)

**Kirby Version**  
3.3.0

**Console output**  
SyntaxError: "nothing to repeat"
    search http://localhost/kirby/media/panel/593ed86d9e989b97a31fa84858ccd5a0/js/app.js:1
    type http://localhost/kirby/media/panel/593ed86d9e989b97a31fa84858ccd5a0/js/app.js:1
    input http://localhost/kirby/media/panel/593ed86d9e989b97a31fa84858ccd5a0/js/app.js:1
    oe http://localhost/kirby/media/panel/593ed86d9e989b97a31fa84858ccd5a0/js/vendor.js:41
    n http://localhost/kirby/media/panel/593ed86d9e989b97a31fa84858ccd5a0/js/vendor.js:41
    _wrapper http://localhost/kirby/media/panel/593ed86d9e989b97a31fa84858ccd5a0/js/vendor.js:41

**Additional context**  
multilang site

**Comment by afbora** [comment]
This issue related `RegExp.escape()` method and #2282 issue. It will fix with that issue.
