### ISSUE TITLE
[Panel] Clicking anywhere jump to multiselect field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2295]
**Describe the bug**  
When you click anywhere, this field is selected automatically because the tabindex value of the multiselect field is 0. So this is related #2137 PR. I don't remember there was such a error in that PR. Another commit may be causing this error.

**Forum Discussion**: 
https://forum.getkirby.com/t/multiselect-field-problem-in-3-3-0/16240

**Kirby Version**  
3.3.0

**Comment by ticoraap** [comment]
Two of our clients experienced this issue, took us a while to figure out.
Glad it is on the 3.3.1 milestone.

**Comment by afbora** [comment]
@verbindingsfout We're really sorry about that. We will try to release the fixed version as soon as possible.

**Comment by bastianallgeier** [comment]
✅
