### ISSUE TITLE
Blueprints encoded with ISO 8859-1 break the API backend

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2299]
**Describe the bug**  

If a blueprint option that gets displayed in the Panel contains ISO 8859-1 chars, the API response that would contain that blueprint option is an HTTP 200 response with empty response body.

**Example blueprint**

```yaml
fields:
  text:
    label: Täxt
```

**To Reproduce**  

1. Save the example blueprint as `site/blueprints/default.yml`.
2. Ensure the file is saved with encoding ISO 8859-1.
3. Open a page in the Panel that uses the default blueprint.
4. Error "The JSON response from the API could not be parsed. Please check your API connection."

**Expected behavior**  

The API should still return the response like normal, be it with ISO 8859-1 chars. The frontend needs to deal with encoding.

**Kirby Version**  

3.3.0

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 78

**Additional context**

Also see #2286.

**Comment by bastianallgeier** [comment]
To be honest, I would close this. We cannot do anything about it. The same happens with the wrong encoding in content files. It even happens when you put the wrong encoding in a database table column. We have to add this to the docs and then it's a potential bug introduced by the developer that we cannot fix.

**Comment by lukasbestle** [comment]
Yes, but I‘d like to know why it happens. This looks like a bug in the core to me.

**Comment by afbora** [comment]
I guess, this issue about `JSON.parse()` method with special characters:
https://github.com/getkirby/kirby/blob/master/panel/src/api/request.js#L35-L39

This issue not about just `ISO 8859-1`. For example; following sample breaks the API with `UTF-8` file.
![image (9)](https://user-images.githubusercontent.com/3393422/72687053-7a414b80-3b0b-11ea-8d79-a1d65e3018c3.png)


May be we should ensure the ouput always encoded as `UTF-8` while files load 🤔 
I tried following with `mb_convert_encoding()` and working properly. Maybe it can give you an idea:

````php
public static function read(string $file)
{
    return mb_convert_encoding(@file_get_contents($file), 'UTF-8', 'auto');
}
````

https://github.com/getkirby/kirby/blob/master/src/Toolkit/F.php#L514-L517

**Comment by lukasbestle** [comment]
Thanks for pointing me into the right direction!

It turns out that the PHP `json_encode()` function only supports UTF-8. If an array or string in a different encoding is passed to `json_encode()`, PHP won't do anything with it and will instead return `false` – in this case the whole API response will be empty, which will then cause the parse error in the frontend.

Unfortunately the suggestion to re-encode every loaded file as `UTF-8` will probably have more downsides than advantages though:

- The performance of the whole CMS will drop
- The `auto` value actually means "test for all possible encodings of the current 'national language setting' in the `php.ini`". We can't rely on that and therefore the results will be all over the place.

But now that I know that this issue comes from `json_encode()` and not our code, I think we can safely close this. As @bastianallgeier explained, this is in the end an issue that needs to be fixed by the site dev.
