### ISSUE TITLE
[Cms & Panel] File sorting via drag'n'drop

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#230]
If I am right the only way to re-sort pages currently is opening the page > Click on Public/Private > Select a new position in the combo box? This is quite hidden and very tedious for many pages which is why I think both the cards- and the list-layout of pages should be sortable by drag'n'drop. In the UI this could be indicated by the characteristic three bars grab icon. There could also be an option in the blueprints to disable this behavior for sensitive data which shouldn't be reordered by accident.

Sorry if this is already on your agenda. Couldn't find it.

Dennis

**Comment by distantnative** [comment]
Related: https://github.com/k-next/starterkit/issues/216

**Comment by bastianallgeier** [comment]
✅
