### ISSUE TITLE
[Panel] [Reference] "Multiselect: fix focus on close" commit issue

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2302]
**Describe the bug**  

https://github.com/getkirby/kirby/commit/0f4f79240b4edaac69379720fe52161d8ba7fec1 This commit that "**Multiselect: fix focus on close**" causing following issues/bugs:

1. #2295
2. #2290
3. #2287
4. #2281 (partially)

Wherever you click, the `close` event is triggered and the multiselect field focuses itself always. 
I tried to solve it, but I didn't succeed.  When we solve this issue, these 4 issues will be solved.

**Kirby Version**  
3.3.0

**Comment by bastianallgeier** [comment]
✅
