### ISSUE TITLE
Using KirbyText on info section in one line doesn't work

### ISSUE THREAD

**Issue by CydGoblin** [getkirby/kirby#2304]
**Describe the bug**  
Using KirbyText on info section in one line doesn't work.

**To Reproduce**  
1. Create an info section on a blue print. Using [example in the docs](https://getkirby.com/docs/reference/panel/sections/info#example):
```
title: Default Page
sections:
  info:
    text: Check out the (link: help text: help pages) for details
```
2. Check your panel on a page with that blue print
`Too many keys: Check out the (link: help text: help pages) for details`

**Expected behavior** 
You can avoid this issue doing it as a Multi-line text. But the example in the docs shows it can be done in one line
```
sections:
  info:
    text: |
      Check out the (link: help text: help pages) for details
```

**Kirby Version**  
3.3.0

**Console output**  
![image](https://user-images.githubusercontent.com/4932347/68714504-3820ea00-055d-11ea-9de8-bc10630d5d01.png)

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 78.0.3904.97

**Comment by texnixe** [comment]
I've fixed the example in the docs. This is not a Kirby issue.

**Comment by afbora** [comment]
We have another issue about `Spyc` Yaml that #1308 
I think these issues will be solved when we switch to `Symfony Yaml Component`.
