### ISSUE TITLE
Number field auto-removes decimals if step option is not set.

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2306]
**Describe the bug**  
If you enter a decimal value into a number field that has no decimals defined, as soon as the field is no longer focused, the decimals are cut off without an further hint that there was something wrong with the data. Shouldn't the field validate the entered value?

**To Reproduce**  
1. Define a number field without the step option
2. Go to the Panel and enter a number with decimals and save.
3. See as when you leave the field, the decimals are removed without any explanation, but the save bar pops up again.

**Expected behavior**  
Maybe the field should come up with a warning rather than popping up the save bar and auto-removing the decimals as the current behavior is somewhat confusing.

**Kirby Version**  
Tested with Kirby 3.3.0.

**Comment by bastianallgeier** [comment]
✅
