### ISSUE TITLE
[Hooks] "Saved" Notification when throwing an Exception in page.update:before

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#231]
Hey,
I just tried @bastianallgeier's example from slack (https://getkirby.slack.com/files/U2UTMUKN3/F9LNVBD4Z/hooks.mov) with `page.update:before` and it shows the green "Saved" notification instead of the exception. If I reload the page nothing has been saved (like expected).

**Comment by bastianallgeier** [comment]
I will look into it!

**Comment by bastianallgeier** [comment]
I just tested it and it works for me. Could you send me your plugin?

**Comment by wottpal** [comment]
Hmm I tried it again in Alpha 5 and it seems to work now (It prevents saving) but it still doesn't display a red notification which says "Nope".

```php
Kirby::plugin([
  'name' => 'wottpal/hooktest',
  'extends' => [
    'hooks' => [
      'page.update:before' => function () {
        throw new Exception('Noope');
      }
    ]
  ]
]);
```

**Comment by wottpal** [comment]
Also debugging hooks (or plugins at all) is so hard that it doesn't really make fun developing them. I am not able to log nor var_dump anything :( Or is there any way to do this? If not maybe a "developer version" of the panel would be nice which collects all sorts of php errors/outputs somewhere.

**Comment by jenstornell** [comment]
I'm not sure about this one but, will these config values (example from Kirby 2) affect the exception in any way?

```php
c::set('whoops', false);
c::set('debug', true);
```

**Comment by wottpal** [comment]
> I'm not sure about this one but, will these config values (example from Kirby 2) affect the exception in any way?

My config file now looks like:

```php
return [
    'license' => 'K3-alpha',
    'whoops' => false,  // whatever this means
    'debug' => true
];
```

And no, still no exception is displayed in panel. But saving is successfully blocked.

**Comment by lukasbestle** [comment]
The best way to debug hooks (and also other code) is a proper debugger like [Xdebug](https://xdebug.org). It requires some getting used to when switching from the "put a `var_dump()` statement somewhere and see what it outputs" approach, but it is well worth it.

**Comment by bastianallgeier** [comment]
It's solved! I was catching exceptions when updating fields, which is kind of exactly what I didn't want to do anymore :)
