### ISSUE TITLE
Kirby 2.1 beta: Pagination ignores URL parameter

### ISSUE THREAD

**Issue by dennisfrank** [getkirby/kirby#231]
I am working on a site where articles can be [filtered by tag](http://getkirby.com/docs/solutions/blog/tags) or [searched with Kirby˚s built-in search](http://getkirby.com/docs/solutions/search). Under Kirby 2.0 [pagination](http://getkirby.com/docs/solutions/blog/pagination) works as expected. After the 2.1 beta update parameters in the URL get ignored by `$pagination->prevPageUrl()` and `$pagination->netxPageUrl()`on paginated pages.

#### Pagination with tag filter:

First page: `http://example.com/blog/articles/tag:exampletag`
Second page Kirby 2.0: `http://example.com/blog/articles/tag:exampletag/page:2` :+1:
Second page Kirby 2.1: `http://example.com/blog/articles/page:2` :shit:

#### Pagination with search query:

First page:`http://example.com/blog/articles?q=keyword`
Second page Kirby 2.0: `http://example.com/blog/articles/page:2/?q=keyword` :+1:
Second page Kirby 2.1: `http://example.com/blog/articles/page:2 `:shit:

---

Kirby 2.1 Beta, Panel 2.1 Beta, OS X 10.10.2, PHP 5.5.14, PHP web server

**Comment by bastianallgeier** [comment]
Just fixed it on the develop branch.
