### ISSUE TITLE
URL Field not parsing weird url correctly

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#2312]
**Describe the bug**
Panel not parsing correctly a valid url  

**To Reproduce**  
1. Create an URL field in the panel
2. Paste in this url http://t--b--a.com/
3. Try save the page

**Expected behavior**  
The page gets saved

**Screenshots**  
![Screenshot 2019-11-19 at 16 47 33](https://user-images.githubusercontent.com/1738077/69162159-7fbeed00-0aec-11ea-8613-7cad62fdad6e.png)

**Kirby Version**  
3.3.1-RC1

**Comment by manuelmoreale** [comment]
@distantnative you gonna love this issue then since you're a fan of changing regex 😄

**Comment by afbora** [comment]
@lukasbestle This is about hype issue that won't fix:

https://github.com/getkirby/kirby/blob/develop/tests/Toolkit/VTest.php#L419-L420

**Comment by lukasbestle** [comment]
Last time we changed the validator was [this commit](https://github.com/getkirby/kirby/commit/45dfdfca39e80933e1f0b8d76745ad084ca3f463#diff-0851f16ef2b0e3ede5589e3d1789375d), which was first in 3.3.0.

I currently can't test this myself, but have you @manuelmoreale verified that this bug was not already in 3.3.0?

**Comment by afbora** [comment]
@lukasbestle I have tested and not working in 3.2.5 too

**Comment by manuelmoreale** [comment]
Thanks for checking that @afbora 🙏

**Comment by afbora** [comment]
@manuelmoreale I don't think it can be fixed for now.

**Comment by manuelmoreale** [comment]
@afbora I "solved" it by simply updating the txt file on the server manually so it's not an issue. It's one of those very rare edge case so definitely low priority.

**Comment by bastianallgeier** [comment]
I've updated the title so it's not being confused as a RC issue.

**Comment by distantnative** [comment]
I still think we are using the best URL regex that is out there:
https://mathiasbynens.be/demo/url-regex

We might have to let this one go...

**Comment by lukasbestle** [comment]
I've stumbled across the implementation in [Uberspace's Paternoster tool](https://github.com/Uberspace/paternoster/blob/v3.0.0/paternoster/types/__init__.py#L9-L118) recently.

It's a lot more complex though as it looks like a simple regex won't be perfect no matter how hard you try. But the question is whether this complexity is worth it for our validator...

**Comment by manuelmoreale** [comment]
Personal 2c: just add somewhere a list of edge cases and maybe a short explanation on why there are edge cases at all. I don't think it's worth losing sleep on this bug since it will come up maybe once every few years. The current implementation works 99.9% of the time so I say it's good enough.

I posted 2500+ different urls in the past few years and had this issue once. Took me 20 seconds to simply add it manually to the text file.

Just document this somewhere and let people know that they could, very rarely, encounter an edge case and show how to work around it.

**Comment by lukasbestle** [comment]
I have added a note in https://getkirby.com/docs/reference/system/validators/url and https://getkirby.com/docs/reference/panel/fields/url.
