### ISSUE TITLE
[3.3.1RC1][Panel] "Invalid identity" error

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#2313]
**Describe the bug**  
While I was creating a page to reproduce another bug I stumbled on this error:

![Screenshot 2019-11-19 at 16 46 20](https://user-images.githubusercontent.com/1738077/69162721-62d6e980-0aed-11ea-93f9-6befc31d2c89.png)

Happens every time I try to type anything into the title field.

**To Reproduce**  
1. Create a new page
2. Admire the error

**Expected behavior**  
No errors 😅

**Comment by distantnative** [comment]
@bastianallgeier @afbora i feel like all the changes to the regex escape from the last versions always only fix one issue while adding others :/

**Comment by afbora** [comment]
@manuelmoreale I can't reproduce on single or multilangual 🤔

**Comment by manuelmoreale** [comment]
@afbora weird, I even double checked and cleared cache/media folder and the bug was still there

**Comment by afbora** [comment]
@manuelmoreale Using on fresh install or existing application? Anything custom settings or plugins?

**Comment by afbora** [comment]
@distantnative You right. This issues about the commits that try to fix escape unicode chars but we have to.

**Comment by manuelmoreale** [comment]
@afbora no that's on a site I'm working on. Happens on Firefox Dev. I'm just now double checking to see if it happens on other browsers.

**Comment by manuelmoreale** [comment]
@afbora doesn't happen on safari so maybe it's browser related?

Same thing on Safari Nightly.

**Comment by afbora** [comment]
@manuelmoreale I can reproduce Firefox now, Chrome works perfect 🤔

**Comment by afbora** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1361876

Firefox does not support 😭 

Browser support list:
https://caniuse.com/#search=Unicode%20property%20escapes

**Comment by afbora** [comment]
@bastianallgeier @distantnative What do you think about that?

**Comment by bastianallgeier** [comment]
What a nightmare! Can we find a workaround for this? Otherwise I'm afraid we have to revert that.

**Comment by afbora** [comment]
They suggested this plugin as a solution on the Internet. I don't get it, but can you take a look?

**XRegExp**
The one of a kind JavaScript regular expression library
http://xregexp.com/

**Comment by bastianallgeier** [comment]
@afbora as far as I understand the problem, this issue is caused by \p{L} in the regex.js helper, right? And \p{L} stands basically for this character set: 

```
a-zA-ZáàâäãåçéèêëíìîïñóòôöõúùûüýÿæœÁÀÂÄÃÅÇÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝŸÆŒ
```

Couldn't we just replace it with the hard coded set?

**Comment by afbora** [comment]
@bastianallgeier Yes, the issue about `\p{L}` that escape unicode support. 
Yes we can replace and i thought of writing by manual, but I thought it would be too hard code :)

So if we do as you say, i'm curious about that can we dynamically get the whole `Str::$ascii` array keys into escape pattern to for all to work properly?

**Comment by bastianallgeier** [comment]
✅
