### ISSUE TITLE
[Hooks] Is $oldUser actually different?

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#232]
Hey I've played with hooks a bit. I created a new plugin and wrote a `user.update:after` hook which just pastes the content of the `street` field into the `country` field but only when the street value has changed. 

```php
Kirby::plugin([
  'name' => 'testname/testplugin',
  'extends' => [
    'hooks' => [
      'user.update:after' => function ($newUser, $oldUser) {

        $newStreet = $newUser->street()->toString();
        $oldStreet = $oldUser->street()->toString();

        // Only continue if street has changed
        if (strcmp($newStreet, $oldStreet) !== 0) {
          $newUser->update([
            'country' => $newStreet
          ], false);
        }

      }
    ]
  ]
]);
```

But unfortunately it seems the code in the if-clause never gets executed. If I remove the if-clause the `country` field gets update but it obviously causes an infinite recursion of hooks.

Dennis

**Comment by bastianallgeier** [comment]
- [x] write test to check bug

**Comment by bastianallgeier** [comment]
The old models are now cloned and passed correctly. But that doesn't really solve your issue with the nested update so far. I will try to come up with a good solution for that in one of the next releases. The old loop breaker code in v2 wasn't really good.

**Comment by wottpal** [comment]
Maybe an additional argument for `update` to skip hooks? 🤷‍♂️

**Comment by jaro-io** [comment]
hey everyone, seems like i am late to the party 🥳 but i am also looking for a way to skip hooks when programmatically updating a user.. any ideas @bastianallgeier, @distantnative?

i am using the `user.update:after` hook to send an email. but i also have a janitor plugin button to update some user information. now each time i press the button, the information updates, but also an email is sent. the thing is, i only want to send an email when manually updating the user through the panel, not when clicking the button.

i can think of plenty of workarounds. but nothing seems to be really smart.

**Comment by lukasbestle** [comment]
@jaro-io I think of all workarounds, using  `$model->save()` instead of `$model->update()` is probably the most solid. Keep in mind though that this method is much more low-level (no validations, no permissions). So it only works if you can ensure correct data and user permissions in other ways.

**Comment by jaro-io** [comment]
@lukasbestle thank you so much. like always, great tip! 🙏🏻 ✨
