### ISSUE TITLE
Smartypants doesn't play along with Markdown link titles

### ISSUE THREAD

**Issue by philgruneich** [getkirby/kirby#232]
In my `config.php`:

````.php
c::set('smartypants', true);
c::set('markdown.extra', true);
````
Attempting to create a Markdown link with title, like this:

````.markdown
[Kirby 2.1](http://forum.getkirby.com/t/kirby-2-1-beta-is-here/660 "Kirby 2.1 is Awesome")
````

Parses this, *ipsis litteris*:

````.markdown
[Kirby 2.1](http://forum.getkirby.com/t/kirby-2-1-beta-is-here/660 “Kirby 2.1 is Awesome”)
````

The issue is causes by Smartypants converting regular quotes into curly quotes. Turning off Smartypants fixes the links, however, would be appreciated to keep it (:

[Reference](http://forum.getkirby.com/t/kirby-2-1-beta-is-here/660/16?u=phil)

**Comment by jolantis** [comment]
Smartypants in Kirby 2.1 also breaks tables (Markdown extra syntax). Turning off Smartypants fixes the output of the Markdown extra table syntax.

![screen shot 2015-05-22 at 14 14 24](https://cloud.githubusercontent.com/assets/68627/7770272/dff168ca-008c-11e5-9f05-f4d5bbbe0980.png)

**Comment by andi1984** [comment]
:+1:

**Comment by jolantis** [comment]
Anyone with a (temporarily) solution yet? It's a pity to have to disable smartypants to be able to output (only some) tables with Markdown Extra syntax… thanks.

**Comment by bastianallgeier** [comment]
I finally got a fix for this on the develop branch! Sorry for the delay guys.
