### ISSUE TITLE
Missing sorting from PageSibling's methods

### ISSUE THREAD

**Issue by UTurista** [getkirby/kirby#2321]
**Describe the bug**  
According to documentation: [has-prev-listed](https://getkirby.com/docs/reference/objects/page/has-prev-listed), [has-next-listed](https://getkirby.com/docs/reference/objects/page/has-next-listed), [next-listed](https://getkirby.com/docs/reference/objects/page/next-listed) and [prev-listed](https://getkirby.com/docs/reference/objects/page/prev-listed) can receive 2 additional arguments to sort the page's siblings before returning the next/previous one. 
However, the returned sibling is always following the default sorting and not the custom one. 
Additionally, the [code it self ](https://github.com/getkirby/kirby/blob/3.3.0/src/Cms/PageSiblings.php#L77)doesn't show these overloads.

**To Reproduce**  
1. Create 3 pages eg: 1_A, 2_B and 3_C
2. All pages have field X with a date value where C < A < B
3. C's #nextlisted("X', "asc") should be A but is none
4. C's #prevlisted("X", "asc") should be none but is B
5. etc

**Expected behavior**  
Siblings should be sorted before calculating the next/previous one.

**Kirby Version**  
Version 3.3.0
Commit: 3175afe

**Comment by distantnative** [comment]
Indeed that’s not implemented in v3. I’m afraid the docs might be from v2 still.

The enhancement could be very handy though.

**Comment by bastianallgeier** [comment]
✅
