### ISSUE TITLE
File Upload modal: "Ok" button without a function

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#2327]
**Describe the bug**  
When uploading a file to a files section, a modal window pops up showing an "Ok" button – but clicking "Ok" doesn't do anything.

**To Reproduce**  
1. Go to a files section
2. Upload a file
3. Click on "Ok"

**Expected behavior**  
I would expect the modal to disappear when clicking "Ok", performing the upload in the background while I continue my work. If this is not possible, I would expect "Cancel" to be the only available option (and omitting the "Ok" button).

**Screenshots**  

<img width="543" alt="grafik" src="https://user-images.githubusercontent.com/149678/69545251-b6d04b00-0f91-11ea-825f-4f3fdda3bde4.png">

**Kirby Version**  
3.3.0

**Console output**  
–

**Desktop (please complete the following information):**  
 - OS: macOS Catalina
 - Browser: Firefox
 - Version: 70.0.1

**Comment by bastianallgeier** [comment]
✅
