### ISSUE TITLE
Error on Structure field with pattern validation since I update to 3.3.1 from 3.1.1

### ISSUE THREAD

**Issue by jesuismaxime** [getkirby/kirby#2331]
**Description**  
When I click to add a new entry, I got a `negative` error in the panel "Cannot read property 'length' of null" where the `handle` field is supposed to be.

**GIF reproducing the error**
[https://recordit.co/OGv8fdPWBM](https://recordit.co/OGv8fdPWBM)

**My structure field**  
```
site_colors:
	label:
		en: Site Colors
		fr: Couleurs du site
	type: structure
	width: 1/2
	translate: false
	empty:
		en: No color yet
		fr: Pas encore de couleur
	fields:

		autoid:
			type: hidden
			translate: false

		name:
			label:
				en: Name
				fr: Nom
			type: text
			width: 1/3

		handle:
			label:
				en: Handle
				fr: Identifiant
			type: text
			width: 1/3
			pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
			help:
				en: "Format: my-color"
				fr: "Format : ma-couleur"

		color:
			label:
				en: Color
				fr: Couleur
			type: color
			width: 1/3
			editableAlpha: false
			default: "#FFFFFF"
```

**Kirby Version**  
3.3.1

**Console output**  
```
TypeError: Cannot read property 'length' of null
    at a.e (app.js:1)
    at a.runRule (vendor.js:12)
    at a.run (vendor.js:12)
    at or.get (vendor.js:41)
    at or.evaluate (vendor.js:41)
    at a.run (vendor.js:41)
    at a.proxy (vendor.js:12)
    at or.get (vendor.js:41)
    at or.evaluate (vendor.js:41)
    at a.proxy (vendor.js:41)
```

**Comment by afbora** [comment]
Also it did not work in version 3.2.5 and this is about `pattern` property.

**Comment by jesuismaxime** [comment]
@afbora I notice that the old way to write a pattern did not work anymore/at all (wrap it between `/` like that : `pattern: "/^[a-z0-9]+(?:-[a-z0-9]+)*$/"`. That how I find this issue, you can see more on this [Kirby Forum topic](https://forum.getkirby.com/t/got-a-validation-error-pattern-since-i-update-to-3-3-1-from-3-1-1/16480/7).

**Comment by bastianallgeier** [comment]
✅
