### ISSUE TITLE
.lock files sometimes do not get removed resulting in editors being unable to edit pages

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2333]
**Describe the bug**  
Just posting this here for reference because not sure if this is a bug or some handling error.

There have been several  user reports, where editors were no longer able to edit individual pages due to `.lock` files not being removed by the system. The result was that all characters entered into a field were immediately removed again.

**To Reproduce**  
I wasn't able to reproduce such a situation myself.

**Kirby Version**  
?

**Console output**  
See link below.

**Additional context**  
I guess in some cases, lock files might have been deployed by accident, but we have also seen this happening on localhost.

Last issue report on forum: https://forum.getkirby.com/t/i-cant-add-any-text-or-file/16510

**Comment by lukasbestle** [comment]
What's weird is that the old lock is not already respected when loading the Panel page. The state that the form is active while the page is still locked shouldn't exist... :thinking:

**Comment by yandodov** [comment]
I had a similar problem today. I talked about it on Slack:

>I got a very strange issue where I can't put data in the panel on one certain page. I tried refreshing, even opening a Private window. The problem won't go away.

> A lock file was causing the issue. However, I am working locally and I closed all tabs when I started troubleshooting. I was the only logged in user.
>
> Before I switched to the page that had the problem, I used the sibling page navigation in the top right. It took some time to change the page due to thumbnail creation, but I thought I didn't click properly, so I clicked again. When the thumbnails loaded, I quickly jumped over that second page and went to the third.
>
> I'm guessing that some race condition caused content locking to lock myself. Probably due to the page being changed so quickly.

I think that changing pages too quickly may be causing the problem.

**Comment by afbora** [comment]
I can reproduce the issue with following steps:

1. Login with MarkOtto
2. Edit any page without save and logout
3. Login with JohnDoe
4. Delete the MarkOtto account
5. Try to edit the page that edited by MarkOtto
6. See the issue

The issue is that the locked page cannot find its user.

**Comment by bastianallgeier** [comment]
✅
