### ISSUE TITLE
URL Slugs are not properly converted from Japanese

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#2334]
**Describe the bug**  

<img width="531" alt="Screenshot 2019-11-29 at 11 16 27 1" src="https://user-images.githubusercontent.com/1738077/69954861-a1f93780-14fc-11ea-852d-9765b9e09f32.png">

**To Reproduce**  
1. Create a page using Japanese characters for the title
2. Watch nothing happen

**Additional context**  

There's a few pages on the topic on Wiki

https://en.wikipedia.org/wiki/Nihon-shiki_romanization
https://en.wikipedia.org/wiki/Romanization_of_Japanese

Pinging @distantnative since I think he's the one that was working on this one.

**Comment by afbora** [comment]
We can solve this issue with;
1. Adding Japanese characters to `Str::$ascii` in Kirby core
https://github.com/getkirby/kirby/blob/master/src/Toolkit/Str.php#L32

2. Defining on `Str::$language` in user application dynamicly
https://getkirby.com/docs/reference/system/options/slugs

**Comment by distantnative** [comment]
@afbora no need for that. We simply have no japanese rule set in `i18n/rules`. We will have to create one and then all will be working.

**Comment by afbora** [comment]
@distantnative I tried to add it, but the Japanese alphabet was very complicated 😅

**Comment by manuelmoreale** [comment]
@afbora who would have thought ahah
Jokes aside, if there's anything I can to to help you guys out let me know.

**Comment by PaulMorel** [comment]
I guess this would be easy with hiragana and katakana. Would it be even possible for kanji? 

Each kanji character has multiple readings depending on the context or definition used.
For example, 山 is often read and romanized as _yama_ or _san_. Kirby would have to be able to understand the context of your page title to write an accurate slug.

Note I know very little japanese, so take what I say with a grain of salt, but as a developer I see this as a potential road block.

**Comment by distantnative** [comment]
@manuelmoreale @PaulMorel 
There is a PR now adding conversion for japanese: https://github.com/getkirby/kirby/pull/2350

@PaulMorel 
I am aware of these problems. No slug algorithm will be able to cater to that complexity. I still think it's good to add some basic conversion rules, so that the slug field does not remain blank. Manual corrections might still be necessary for editors, that is true.

**Comment by bastianallgeier** [comment]
✅
