### ISSUE TITLE
Opening a page/file picker dialog from another dialog breaks backdrop

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#2336]
**Describe the bug**  
I wrote some custom editor extension, that make use of the `<k-dialog>` component to display settings, just as the included image block. For some of these blocks, I need to display a file or page picker inside of the settings dialog. As soon, as dialogs are nested and the second dialog is closed (page/file picker), the backdrop of the first dialog (settings popup) does not cover the whole page any more.

On longer pages, this causes confusion, as the dialog may become invisible until the user scrolls up. Clicking anywhere on the page outside of the dialog itself (e.g. in the invisible parts of the backdrop) will cause the settings window to close without saving.

**To Reproduce**  
1. Open a dialog that contains an element, that could open another dialog.
2. Open a file picker dialog from another dialog (one that contains a `<k-form>` in my case)
4. Close the picker dialog.
5. The backdrop of the first dialog does not cover the whole body any longer and the page can be scrolled, despite the dialog is still open.

**Expected behavior**  
Dialogs and their backdrops should strack on each and behave in a consistent manner, even is nested.

**Screenshots**  
<img width="967" alt="Bildschirmfoto 2019-12-04 um 11 47 10" src="https://user-images.githubusercontent.com/395617/70136582-950b4e00-168c-11ea-9ded-dea21c43fea6.png">

**Kirby Version**  
3.3.1

**Console output**  
–

**Desktop (please complete the following information):**  
 - OS: macOS 10.14.6
 - Browser: Mozilla Firefox
 - Version:  70.0.1 (64-Bit)

**Comment by bastianallgeier** [comment]
I'm afraid I have to close this. We can't support stacked dialogs at this point.
