### ISSUE TITLE
[Panel] Do not delete non-translatable fields

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#2337]
**Describe the bug**
Currently, if you mark a field as non-translatable using `translate: false`, contents in translations will be deleted the next time the page is saved.

**To Reproduce**  
1. Create a new page blueprint and add a text field.
2. Add some content in the default language.
3. Open the page in the Panel and translate the text field.
3. Set the `translate` property of the text field added in 1) to `false`.
4. Open the page in the Panel.
5. Switch to the secondary language.
6. Change the pages title (or any other content field).
7. Save the changes.
8. The non-translatable text field still shows the translated contents. However, on disk, the translation has been removed from the content file.
9. Reload the Panel. The displayed field value now show the value in the default language.

**Expected behavior**  
The translation of the text field should not be removed, even though the field is marked as translated.

This would also be in line with the Kirby’s current behaviour when a content file contains „outdated“ fields (i. e. fields not present in the blueprint). In those cases, the outdated fields are kept in the content file in order to prevent the risk of accidentally deleting data.

**Kirby Version**  
3.2.5

**Additional context**
From what I can see, this has been introduced in e10aa88bf in response to #2001.

**Comment by distantnative** [comment]
Bundling different issue discussions around this topic here: https://github.com/getkirby/kirby/issues/2362
