### ISSUE TITLE
New `Kirby\Data\Xml` class

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2338]
Needs the refactored `Kirby\Toolkit\Xml` class and therefore needs to be in 3.4.0.

**Comment by GiantCrocodile** [comment]
Support for XML handling would be great.

**Comment by lukasbestle** [comment]
@GiantCrocodile There are already PRs for this you can try out:

https://github.com/getkirby/kirby/pull/2400
https://github.com/getkirby/kirby/pull/2401

**Comment by bastianallgeier** [comment]
✅
