### ISSUE TITLE
Option array notation does not work for plugin options

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2343]
**Describe the bug**  

```
'distantnative' => [
    'retour' => [
        'option' => 'value'
    ]
]
```

![CleanShot 2019-12-04 at 16 29 20](https://user-images.githubusercontent.com/481362/70155817-3f966780-16b3-11ea-985b-de571f6ef4f4.png)

Those options are not actually available via `option('distantnative.retour.ignore')`

if I use the dot notation in flat array, it works:

```
'distantnative.retour.option' => 'value'
```

**Kirby Version**  
3.3.1

**Comment by afbora** [comment]
I did a few tests, but more extensive development is needed than I expected. 
I just thought it would be resolved with a simple update in the `AppPlugins` class, but I think the A/Array class needs to be refactored to support the dot notation in config while getting and setting options.

**Comment by yandodov** [comment]
@afbora I'm not familiar with the internals much, but in my opinion, options should be stored as arrays at all times, always. Dot notation should be just a simple function that explodes a path by `.` and traverses those arrays. Similar to [`lodash.get()`](https://lodash.com/docs/#get). It should just be "syntax sugar" for avoiding this:

```php
$opt = option('my.plugin')['foo']['bar']['baz'] ?? null;
```

...and simply using this:

```php
$opt = option('my.plugin.foo.bar.baz`);
```

**Comment by bastianallgeier** [comment]
✅
