### ISSUE TITLE
Incorrect Dutch translation of "unlisted" page status

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/kirby#2348]
The `unlisted` page status is translated in Dutch as "Unpublished". This is incorrect in my opinion because only a draft is unpublished. Unfortunately there is no one on one translation in Dutch of "unlisted". 
I propose "Niet geregistreerd" (Unregistered) but other possible translations are "Niet geordend" (Unordered) or "Niet in het menu" (Not in the menu). I'm not 100% sure what the best solution is here, so Dutch speaking Kirby users: please comment.

**Comment by bvdputte** [comment]
I don't like "not in the menu", as it's meaningless when there's no obvious "menu".

- draft: Klad
- unlisted: Verborgen (?)
- listed: Gepubliceerd

**Comment by philipmarnef** [comment]
If there is no menu, then listed pages are equally "Verborgen" (Hidden), no?

The problem is that the `listed` option might mean many things, depending on how you use it. I often use the `num` option to pre-sort pages by date for instance, not to list them in a menu.

So I feel something like "Ongeordend" (Unordered), "Ongenummerd" (Not numbered), "Niet geregistreerd" (Unregistered) or "Niet ingedeeld" (Not classified) is more accurate...

**Comment by bvdputte** [comment]
> If there is no menu, then listed pages are equally "Verborgen" (Hidden), no?

Depends. Sometimes they are listed as cards or some other component (which hasn't the appeal of a menu. Then, an editor can expect the "pages" (which can be any kind of content type) to not show up there neither. The only way to visit them directly, is via a "hidden" link.

**Comment by bvdputte** [comment]
Also: you know you can label these statuses based on context via blueprints: https://getkirby.com/docs/reference/panel/blueprints/page#statuses__extended-example ?

(I have not tested if you can translate those though)

**Comment by philipmarnef** [comment]
> Also: you know you can label these statuses based on context via blueprints

I do, and I've done that. But I was working on a new site today with just the draft & unlisted options on a page and found it really confusing.

**Comment by bvdputte** [comment]
It might also be cumbersome to repeat that on each blueprint (unless there's a setting to set that globally).

TBH I never change the language of the panel to anything else then English 🙈.

**Comment by distantnative** [comment]
@philipmarnef @bvdputte can this be closed?

**Comment by philipmarnef** [comment]
@distantnative There's no resolution. I'll try posting it on the forum to see if we can get more input, it still bugs me.

**Comment by distantnative** [comment]
I will close this for now then as there is an ongoing discussion whether this is an issue or not at all.
