### ISSUE TITLE
UI improvement: add “grab” cursor to sorting handles

### ISSUE THREAD

**Issue by VIPStephan** [getkirby/kirby#2354]
When I used Kirby the first time and checked out the starter kit I was wondering about the purpose of these six small squares on the image cards in the panel. Now I know that these are the handles to drag and re-order the cards but it could be a lot more intuitive if the `cursor: grab` CSS property would be added to `.k-sort-handle`; that would give the user an indication that this can be grabbed and moved.

**Comment by distantnative** [comment]
This is an actual issue, as this should be happen already, but is broken for non-webkit browsers.

**Comment by bastianallgeier** [comment]
✅
