### ISSUE TITLE
Tag with space not working

### ISSUE THREAD

**Issue by fanningert** [getkirby/kirby#236]
Creating of tag with space working. But when I click on a tag then no content is visible. Tags without space are working.

*Example:* "Bad Kleinkirchheim"
*URL:* .../location:bad%20kleinkirchheim

**Used Kirby version:** Develop-Branch (2015/04/12)

**Comment by texnixe** [comment]
If you use the tagcloud, url encoding and decoding is done by the plugin. If not, you need to urlencode and urldecode the tag.

**Comment by fanningert** [comment]
Thanks now it is working.
