### ISSUE TITLE
Existing values for `translate: false` - keep or delete?

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2362]
There seem to be conflicting views on what should happen when values in non-default language content files exist for fields with `translate: false`:

- https://github.com/getkirby/kirby/issues/1859
- https://github.com/getkirby/kirby/issues/2337

Moreover, it seems that we are not very coherent at the moment: Some actions keep the values around, others remove them.

Opening this issue to tie the discussions together.

**Comment by moritzebeling** [comment]
Vote delete :)

Any secondary language content stored in a field that is `translate: false` is invalid by definition. The panel should not accept invalid content and consequently clear it.

**Comment by nilshoerrmann** [comment]
I'm for deletion as well but like to point out again that the UI should notify the user about the issue:

> The panel knows about this without any user interaction. So I'd expect two things in the panel:
>
> 1. Either there should be an error message stating that there is a translation for an untranslatable field offering a way to dismiss this translation.
> 2. Or the panel should just display the correct version from the default language and display the unsaved changes bar so that the translation is erased after hitting save.

See https://github.com/getkirby/kirby/issues/1859#issuecomment-542096208

**Comment by moritzebeling** [comment]
Agree, the user would have to manually save that edit.
I think, a little red modal could inform the user that content is invalid (same as when changing templates) and that saving the page would solve that. But still, the user could refuse and go back without saving.

**Comment by mrflix** [comment]
I'm also pro deletion. I wonder why @tillprochaska want's to keep content thats not editable in the panel around as described in #2337. For me it only happens as an error that I forget to set a field to `translatable: false` and then have to dig into the txt to remove the value (the same thing that happens to Nils and Bruno).
