### ISSUE TITLE
Blueprint extends with caching?

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#2364]
If many fields are extended by blueprint extends (as is often the case with the builder field by Tim Ötting) the Kirby backend becomes very slow. Even if no data is called up and is available and the field is completely empty, the process takes from about 5 seconds to the server timeout. Bastian talks about a way to cache the extends.

More information about the problem here:

https://forum.getkirby.com/t/asynchronous-files-access-for-blueprint-extension/16520

**Comment by bastianallgeier** [comment]
✅
