### ISSUE TITLE
Number field cuts of decimal places

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2372]
To my surprise the number field doesn't work any more if more then 4 decimal places are used.

**Working:**

```
                lat:
                    label:        Breitengrad
                    type:         number
                    step:         0.0001
```

**Not working anymore:**

```
                lat:
                    label:        Breitengrad
                    type:         number
                    step:         0.00001
```

If you try with 5 or more decimal places, all decimal places are silently dropped (you loose everything following the comma, making the field an integer-only field).

If this is expected, it doesn't make sense to me, because decimal numbers are not limited to 4 decimal places. In some situations - like with latitudes or longitudes - we need more then 4 decimal places in the numbers. What is the best way to store such numbers, if not in the numbers field?

**Comment by afbora** [comment]
Strange, if step have 5 or more decimal places with starts with zero, step property return as `0` always.

@andreasotto You can use `0,000001` with comma as workaround. That works!

**Comment by afbora** [comment]
I have tracked the issue and this is about PHP `float` type, here few examples:

    (float)Str::float(0.0001)   // 0.0001
    (float)Str::float(0.00001)  // 0
    (float)Str::float(0.000001) // 0
    (float)Str::float(0.00005)  // 0.0001

Comment on this issue:
https://www.php.net/manual/tr/function.floatval.php#120730

**Comment by lukasbestle** [comment]
Workaround: Define the `step` property as a string, not as a float:

```yml
lat:
  label: Breitengrad
  type:  number
  step:  "0.00001"
```

Maybe we should actually document that. Seems like we can't really fix this in the code when floats are used.

**Comment by bastianallgeier** [comment]
✅
