### ISSUE TITLE
kirbytext() renders `p` tags in each `li` when 2 lists are placed directly after each other 

### ISSUE THREAD

**Issue by mcbrwr** [getkirby/kirby#2378]
**Describe the bug**  
When two lists are placed after eachother, a `p` tag is rendered in each `li`.

**To Reproduce**  
Create a page with this data:
```
----

Text:

- lorem
- ipsum

- dolor
- sit 
```

 Render it on the page with `$page->text()->kirbytext()`.

it outputs:

```
<ul>
<li><p>lorem</p>
<li><p>ipsum</p>
</ul>

<ul>
<li><p>dolor</p>
<li><p>sit</p>
</ul>
```

**Expected behavior**  
expected output should not contain p tags: `<li>Listitemcontent</li>`

**Kirby Version**  
3.3.2

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: chrome
 - Version: 79.0.3945.88

**Comment by afbora** [comment]
I'm not sure this is a bug.
This issue about empty line break and line break means paragraph.

You can use with any seperator like that: for example **headlines**

````
Text:

- lorem
- ipsum

# headline
- dolor
- sit 
````

**Comment by lukasbestle** [comment]
The actual output I get is the following:

```html
<ul>
<li>
<p>lorem</p>
</li>
<li>
<p>ipsum</p>
</li>
<li>
<p>dolor</p>
</li>
<li>
<p>sit</p>
</li>
</ul>
```

To be honest, that's also not what I would expect as there's just one line break in the input, not one between each item. And even then, I'd expect something like this instead:

```html
<ul>
<li>lorem</li>
<li>ipsum</li>
</ul>

<ul>
<li>dolor</li>
<li>sit</li>
</ul>
```

However this is a bug in the underlying Markdown parser https://github.com/erusev/parsedown. We are looking to replace the Markdown parser (see #1961), but until then we unfortunately can't fix this. :(
