### ISSUE TITLE
[Panel] Implement System view

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#238]
Only for admins

- Version info
- License info 
- “Health” checks
- Custom Test Checks (maybe?)

**Comment by jenstornell** [comment]
What do you mean with "health checks"?

Here are some ideas for that (which do not need to land on v3.0).

https://github.com/jenstornell/kirby-security-checklist

## Check if the active php version is green

http://php.net/releases/active.php
http://php.net/supported-versions.php

Also print PHP version +  Apache version.

## Check if htaccess protects the locations it should

We can use a custom folder setup. It's easy to forget to also change the htaccess file.

## Folder listening disabled

This option should be disabled for security reasons on the hosting provider.

https://github.com/jenstornell/kirby-security-checklist/blob/master/security-checklist/template.php#L5

## SSL/HTTPS enabled

Nowdays every domain should have SSL/HTTPS.

https://github.com/jenstornell/kirby-security-checklist/blob/master/security-checklist/template.php#L2
