### ISSUE TITLE
If there is only one admin user, this admin cannot change the role of non-admin users to admin

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2380]
**Describe the bug**  
As it says in the title.

**To Reproduce**  
1. Create a new user role, e.g. client.
2. Create a user with this role.
3. Then, try to change the role of this user to `admin`.
4. The `changeRole` dialog in this case doesn't offer any other roles to change to apart from the current role.

**Expected behavior**  
It should be possible to change the role of an existing user to `admin`. 

**Additional context**
Note that it is possible to create new admin users. It is also possible to change the role of a non-admin user to `admin` if you create a second admin user first.

**Kirby Version**  
Tested with 3.2.2

**Comment by bastianallgeier** [comment]
✅
