### ISSUE TITLE
Roles::load(): Only try to load files, skip directories

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2383]
**Describe the bug**  

If the `site/blueprints/users` directory contains a subdirectory (for some reason), Kirby will try to load that subdirectory as a role file.

**To Reproduce**  

1. Create a directory `site/blueprints/users/.something`
2. Try to log in to the Panel
3. Error `Missing handler for type: "something"`

**Expected behavior**  

Kirby should check `is_file()` here:

https://github.com/getkirby/kirby/blob/3.3.2/src/Cms/Roles.php#L120

**Kirby Version**  

3.3.2

**Comment by lukasbestle** [comment]
Forum link: https://forum.getkirby.com/t/panel-installation-missing-handler-for-type-dav/16777/21?u=lukasbestle

**Comment by bastianallgeier** [comment]
✅
