### ISSUE TITLE
Normalize `grayscale` thumb option

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2384]
Currently, calling the thumb option with `greyscale` or `bw` fails.

Works:
```
echo $page->image()->thumb(['width' => 250, 'grayscale' => true]);
```
Doesn't work:
```
echo $page->image()->thumb(['width' => 250, 'greyscale' => true]);
```
Doesn't work either:
```
echo $page->image()->thumb(['width' => 250, 'bw' => true]);
```
However, there is a method `bw`, and in the filename `grayscale()` method, these option values are normalized.

It would probably make sense to allow using those alternatives in the thumbs options as well.

A screenshot from our own confusion in the docs (now fixed):

<img width="647" alt="Bildschirmfoto 2020-01-05 um 13 07 44" src="https://user-images.githubusercontent.com/5312492/71779994-0193a880-2fbd-11ea-8e6e-ffca44ce784a.png">

**Comment by bastianallgeier** [comment]
✅
