### ISSUE TITLE
Remove user-specific patterns from .gitignore

### ISSUE THREAD

**Issue by silllli** [getkirby/kirby#2386]
According to the git docs, only project related file patterns should be put into the .gitignore file of a project. Things like files created by your editor of choice should be put in a global (local) gitignore file.

> Which file to place a pattern in depends on how the pattern is meant to be used.
> 
> Patterns which should be version-controlled and distributed to other repositories via clone (i.e., files that all developers will want to ignore) should go into a .gitignore file.
> 
> Patterns which are specific to a particular repository but which do not need to be shared with other related repositories (e.g., auxiliary files that live inside the repository but are specific to one user’s workflow) should go into the $GIT_DIR/info/exclude file.
> 
> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

 See the official git documentation for this: https://git-scm.com/docs/gitignore

**Comment by distantnative** [comment]
I'm not sure I understand what patterns exactly from our `.gitignore` you think should be moved (and where to exactly). Could you elaborate it bit? That would be super helpful - thanks!

**Comment by afbora** [comment]
@gitsilvan mean editors section that?

````
# editors
*.sublime-project
*.sublime-workspace
/.vscode
/.idea
````

**Comment by distantnative** [comment]
But that is in the `.gitignore` in the `kirby/` folder... so this one basically only applies to the Kirby team when we are developing. Or how does it create a problem for you @gitsilvan using Kirby as a site developer? Git is sometimes so mysterious, is there a conflict?

**Comment by afbora** [comment]
@distantnative I don't think there's a conflict, either.

I was read an article about that:
https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore

**Comment by silllli** [comment]
> @gitsilvan mean editors section that?
> 
> ```
> # editors
> *.sublime-project
> *.sublime-workspace
> /.vscode
> /.idea
> ```

You were faster than me. These are the ones I was thinking about. Also this one: 

> .DS_Store

> But that is in the .gitignore in the kirby/ folder... so this one basically only applies to the Kirby team when we are developing. Or how does it create a problem for you @gitsilvan using Kirby as a site developer? Git is sometimes so mysterious, is there a conflict?

There is no conflict. I just learned about the global gitignore setting myself and stumbled across the .gitignore in Kirby. I thought it makes perfect sense not to clutter a repository's .gitignore with user or OS specific patterns (because everybody uses different editors and OSs) and was always wondering about why to ignore my editor's files in there and not EVERY editor's files (which, of course, is impossible).

These patterns can also, at least partially, be found in the plain and starter kit which are intended to be used by Kirby users.

**Comment by bastianallgeier** [comment]
While it might be best practice not to have them in the .gitignore, it definitely helps us as a team to make sure we don't have them in the kirby repo by accident. 

It's a completely different story in the starterkit or plainkit. We should stick to best practices there. Feel free to open another issue in those repos.

**Comment by silllli** [comment]
I just got back to this and since https://github.com/getkirby/plainkit is a template (and not a regular repository), I can’t open an issue there.

Still the first thing I do after installing the `plainkit` is removing the `.editorconfig` file and update `.gitignore` by removing all lines that are not project / Kirby specific.
