### ISSUE TITLE
Search not working in textarea files picker

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2388]
**Describe the bug**  
As in the title.

**To Reproduce**  
1. In a Starterkit, go to one of the album pages and try to pick a file in the decription textare field.
2. Enter something in the search bar.
3. The list is not filtered as it should

**Expected behavior**  
The file list should be filtered like in a files field etc.

**Kirby Version**  
Tested with 3.3.2.

**Comment by bastianallgeier** [comment]
✅
