### ISSUE TITLE
Composer warning: Package zendframework/zend-escaper is abandoned

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#2390]
Using the plainkit installed with Composer, on `composer install` this warning is printed:

> Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.

It looks like the Zend Framework was migrated to the Linux Foundation under a new project name, Laminas, and most packages were migrated.

Packages such as `zendframework/zend-escaper` won't receive updates, so ideally it's better to use the new package, but I doubt it's urgent. If anyone wants to pick it up as a small PR ;)

I’ve seen only one use in the codebase, in `src/Toolkit/Escape.php`.

**Comment by lukasbestle** [comment]
Thanks for letting us know!

**Comment by bastianallgeier** [comment]
✅
