### ISSUE TITLE
[Panel] Site title not changing in breadcrumb/topbar

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2396]
**Describe the bug**  
Site title not changing in breadcrumb/topbar.
It only changes if the site title is updated but it still remains constant.

**To Reproduce**  
1. Go to panel
2. Enable multilanguage and add secondary language
3. Change site title for each language
4. Switch language and see topbar site title still same

**Expected behavior**  
Site title in topbar should change for each language.

**Screenshots**  
![sitetitle](https://user-images.githubusercontent.com/3393422/72510934-5a83fc00-385b-11ea-95c1-b43bb3eb717d.gif)

**Kirby Version**  
3.3.2

**Console output**  
No any output

**Desktop:**  
 - Windows 10
 - Chrome 79

**Comment by bastianallgeier** [comment]
✅
