### ISSUE TITLE
Markdown - nested lists

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#2397]
**Markdown - Nested List**
It should be possible to create nested list in the markdown editor. Right now its not possible to do list list like:

```Markdown
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
4. Fourth item
```

```HTML
<ol>
<li>First item</li>
<li>Second item</li>
<li>Third item
<ol>
<li>Indented item</li>
<li>Indented item</li>
</ol>
</li>
<li>Fourth item</li>
</ol>
 
```

https://www.markdownguide.org/basic-syntax

**Comment by distantnative** [comment]
What is the result you are getting?

**Comment by distantnative** [comment]
We are using Parsedown as library which supports nested listes, so it should work: https://parsedown.org/tests/deeply_nested_list

Make sure to use exactly 4 more spaces for each indentation level.

**Comment by findthebug** [comment]
Okay, it seems the plugin "kirby-builder" have an issue with the nested list. the example you have provided works in a blueprint textarea but not in a textarea within a builder field. so i think i have to move this to the kirby-builder repo. 

in the builder blueprint, the list is just rendered as 1 level.
