### ISSUE TITLE
sortBy() behaviour changes from 3.2.4 -> 3.3.2

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#2398]
**Describe the bug**  
When using `sortBy()` on a set of pages that have a manually set order this seems to be discarded and defaults back to alphabetical sorting. This wasn't the case with Kirby 3.2.4, but seem to be in 3.3.2 -> is this a regression?

**To Reproduce**  
See: https://forum.getkirby.com/t/sortby-behaviour-changes-from-3-2-4-3-3-2/16903 for more info.

**Expected behavior**  
Honour the set order

**Screenshots**  
- n/a

**Kirby Version**  
3.3.2

**Console output**  
- n/a

**Desktop (please complete the following information):**  
- n/a

**Smartphone (please complete the following information):**  
- n/a

**Additional context**  
-

**Comment by distantnative** [comment]
When you are using sortBy isn’t it sorted by what you specify in sortBy? 🤔

**Comment by bvdputte** [comment]
Yes I think so, but it worked differently before, and I couldn't find out why and didn't find anything in the changelogs about that neither.

**Comment by afbora** [comment]
Fixed collection sorting error  https://github.com/getkirby/kirby/pull/2020

**Comment by bvdputte** [comment]
Wow Ahmet, that seemed like a nasty bug to find _and_ fix.

Anyway, I can work around the "regression" by using `$collection->sort("num", "asc")->sortBy("field", "asc");`. 👍

**Comment by lukasbestle** [comment]
@bvdputte It‘s indeed unavoidable to change behavior with such a fix.

Regarding your example: The following code will have a much better performance and also reliability:

```php
$collection->sortBy("field", "asc", "order", "asc")
```
