### ISSUE TITLE
[Panel] Prev/Next arrows hover missing

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#24]
@malvese wrote about this first. Anyway, when hovering the navigation arrows there is nothing that tells us where I will land. There is no hover title attribute and Chrome does not write the url at the bottom (probably because it's not a real url).

**Comment by distantnative** [comment]
Also related to https://github.com/k-next/starterkit/issues/4

**Comment by distantnative** [comment]
✅  "real" url/`a` tag now. So the target is shown in the status bar on hover.
