### ISSUE TITLE
Backspace key in empty tags field makes it lose focus

### ISSUE THREAD

**Issue by plagasul** [getkirby/kirby#2403]
**Describe the bug**  

Within a tag field, hitting backspace when the field is empty de-focuses it.

**To Reproduce**  
1. Create a tags field.
2. Add some tags. (optional)
3. Press backspace until the field is empty and then once more.
4. Field loses focus.

**Expected behavior**  
Expected behaviour would be the field remains focused. AFAIK no other field behaves like that. I found myself having to switch to mouse to focus the field again many times. 

**Kirby Version**  
Version
3.3.1

**Desktop (please complete the following information):**  
 - OS: linux mint cinnamon 19.2
 - Browser: chrome
 - Version: Versión 79.0.3945.130 (Build oficial) (64 bits)

**Comment by afbora** [comment]
This issue from following line. I couldn't fully understand why the `blur()` method was there. @distantnative  can help us.

https://github.com/getkirby/kirby/blob/master/panel/src/components/Forms/Input/TagsInput.vue#L283

**Comment by distantnative** [comment]
It's in there for when you have some tags already and you are in the input, you can use the arrow keys to select existing tags. For that we have to do some magic and leave the input. Solution could maybe be to add another if clause to check that there are any tags (0 !== tags.length).

**Comment by afbora** [comment]
@distantnative I mean, when we remove the `blur()` method, the arrow and backspace keys work perfectly.  I wonder if it is necessary to run `blur()` method again when running `focus()` for a tag?

Btw your solution is definitely working:

````js
if (0 !== this.tags.length) {
    e.target.blur();
}
````

But i found another issue about deleting item. No problem if you start deleting it from the end. But if you do the deletion with the `backspace` and it doesn't start from the last one (not in order), the input focus goes.

![tags](https://user-images.githubusercontent.com/3393422/72797614-7ff57900-3c52-11ea-8092-1be4a4d28032.gif)

**Comment by distantnative** [comment]
✅ Will be fixed in 3.3.4
