### ISSUE TITLE
$kirby->users()->current() always returns a user.

### ISSUE THREAD

**Issue by frankrausch** [getkirby/kirby#2407]
**Describe the bug**  
`$kirby->users()->current()` returns a user object, even if I am not logged in (and even from a different browser).

Additionally, `$kirby->users()->current()->isLoggedIn()` does not return anything.

**To Reproduce**  
1. Download a fresh Kirby instance (I can reproduce both in my project and in a fresh Plainkit)
2. Create a user.
3. Log out from the panel, use private mode, or switch to a different browser.
4. Paste this in `site/templates/default.php`:
```php
<?php
dump ($kirby->users()->current());

echo ($kirby->users()->current()->isLoggedIn());
```

**Expected behavior**  
a. I should only get a handle on a user if I’m logged in via the panel.
b. I should be able to retrieve the login status from the current user when I’m logged in.

**Kirby Version**  
3.3.2, 3.3.3

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox, Safari, Chrome

**Comment by afbora** [comment]
You are using the wrong method. Use following method to get logged user;

````php
dump ($kirby->user()); // get current/logged user
````

`$kirby->users()->current()`: This line means bring me the current/first of the users collection not about logged users.

**Comment by frankrausch** [comment]
Wow, that was quick help. Thanks! It works.
And yes, I’ve found the warning in the docs now.
