### ISSUE TITLE
Handling of upper- and lowercase characters for languages with diacritics

### ISSUE THREAD

**Issue by gearsdigital** [getkirby/kirby#2408]
**Describe the bug**  
Panel Search results aren't working as expected for languages with diacritics like Czech.

**To Reproduce** 
1. Create a page with title: Školní jídelna
2. Click on the top right search icon
3. Enter "škol" (**note the lowercas**e Š)
4. Nothing happens

**Expected behavior**  
The Page "Školní jídelna" is visible in search results even if searched with lowercase letters-

**Screenshots**  
![Bildschirmfoto 2020-01-23 um 09 44 17](https://user-images.githubusercontent.com/965069/72969013-fa460a80-3dc4-11ea-8a04-6b1d4922064f.png)
![Bildschirmfoto 2020-01-23 um 09 44 28](https://user-images.githubusercontent.com/965069/72969014-fadea100-3dc4-11ea-855e-84dc5d3cf148.png)

**Kirby Version**  
3.3.3

**Desktop (please complete the following information):**  
 - OS: macOS 10.15.2
 - Browser: Firefox
 - Version: 72.0.2

**Additional context**  
This issue was initally reported by [@janherman](https://github.com/janherman) here: https://github.com/gearsdigital/enhanced-toolbar-link-dialog/issues/5

**Comment by distantnative** [comment]
✅ Will be fixed in 3.3.4
