### ISSUE TITLE
[Cms] Implement draft preview authentication

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#241]
Depends on @lukasbestle's new Session class

**Comment by lukasbestle** [comment]
Does it? I thought we currently already have a user implementation that works with JWT.

**Comment by lukasbestle** [comment]
Oh, I see. It currently only works for the API and not the frontend as the JWT isn’t transmitted as a cookie but only per request, right?

**Comment by bastianallgeier** [comment]
Yes that was the reason. But I just thought that we could also implement it on post requests only for now and send the token as header like the rest of the API.

**Comment by bastianallgeier** [comment]
✅
