### ISSUE TITLE
Pages dialog/modal breaking layout

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2415]
**Describe the bug**  
The pages dialog/modal layout breaks when you have longer page titles or use some kind of `info` text. Especially on smaller screens this issue is easy to encounter.

**To Reproduce**  
1. Add a `pages` field to your blueprint
2. Either use long page titles or for example display the page template in the `info`
3. Open the modal by clicking on the "Select" button
4. Resize your window if necessary

**Expected behavior**  
The modal should be max 100% in width so it fits into the viewport.

**Screenshots**  
![modal](https://user-images.githubusercontent.com/7975568/73339733-a4b4a680-4279-11ea-99e6-0e2ba9618fa5.gif)

**Kirby Version**  
3.3.3

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome, Mobile Safari (probably every browser)

**Smartphone (please complete the following information):**  
 - Device: iPhone 7
 - OS: iOS13.3
 - Browser: Mobile Safari
 - Version: 

**Additional context**  
I don't understand why the width of `k-dialog-box` is set to a fixed width. Just use `width: 100%` and a `max-width` and it's fixed. Ideally something wider than 30rem.

![2020-01-29 09-42-11 2020-01-29 09_44_06](https://user-images.githubusercontent.com/7975568/73340964-f8c08a80-427b-11ea-968d-d22a460a6fad.gif)

**Comment by afbora** [comment]
You're right, could be fix with using media query:

````css
@media screen and (max-width: $breakpoint-medium) {
    //
}    
````

**Comment by medienbaecker** [comment]
@afbora I don't think you even need a media query for this. Just use `max-width` instead of `width` and set `width` to `100%` for `.k-dialog-box`.

**Comment by nilshoerrmann** [comment]
Looking at the screenshots, it would be interesting to also look into removing some (all?) padding inside the dialog box to give the actual content more space. It would also be good to make longer lines break instead of trucating them.

**Comment by afbora** [comment]
@medienbaecker Are you sure? 😄 This issue is only a problem on small screens.

![FireShot Capture 019 - Exploring the universe - Mægazine - localhost](https://user-images.githubusercontent.com/3393422/73342574-e3555b80-428f-11ea-9476-3b46823e2062.png)

**Comment by medienbaecker** [comment]
@afbora Of course you need to set a `max-width` as I mentioned in my issue.

@nilshoerrmann I agree, but maybe we should open a separate issue for that?

Edit: I added an idea issue over here: https://github.com/getkirby/ideas/issues/469

**Comment by afbora** [comment]
@medienbaecker Hmm, `max-width` really worked 😅

**Comment by afbora** [comment]
@distantnative Can we get this to 3.3.5?

**Comment by distantnative** [comment]
I haven't had a chance to look at this myself... my first guess would be that it is an easy fix

**Comment by distantnative** [comment]
`max-width` doesn't work as we the width defines the different dialog sizes (defined via option: `small`, `medium` etc.). Using `max-width` the dialog doesn't really take the width...

But probably wrapping with a media query could help.

**Comment by medienbaecker** [comment]
@distantnative Setting `width` to `100%` and using the `max-width` to set the dialog size from the option doesn't work?

**Comment by distantnative** [comment]
No, apparently the content doesn't really push the dialog to its max-width.

What seems to work:
<img width="372" alt="Screen Shot 2020-02-15 at 12 22 59" src="https://user-images.githubusercontent.com/3788865/74587029-ee2d2180-4fed-11ea-910a-40dd3244f189.png">

I'll open a PR in a second. Would be great if you could test it, @afbora.

**Comment by bastianallgeier** [comment]
✅
