### ISSUE TITLE
[Cms] Implement drafts for published pages

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#242]

**Comment by bastianallgeier** [comment]
✅

**Comment by REHvision** [comment]
@bastianallgeier could you please elaborate how this has been implemented or how to do this?

I don't see an option to edit published pages **without making the changes go live directly or taking them back offline** (i.e. set it back to draft and republish it again after my changes).

I propose to either or both:
- have another status option like **redraft** which applies automatically whenever any published page gets edited and saved. So changes or a new version of a page would only be visible to logged in users while the previously published version stays online (and unchanged until you publish the redraft again).

- always offer two different save options in the status bar: **save draft** and **publish**.
This way the editor can decide on every content change/edit how to treat it.

*PS: I also tried to manually copy a listed page to the _drafts folder to see if I can have those two versions of a page at the same time. Of course this works without Panel but not within it (it even messes up things and throws error...)*
