### ISSUE TITLE
Plugin Asset Resolver Always Redirects to Same URL on First Call (Creating symlink)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2422]
**Describe the bug**  
I noticed that when trying to load plugin assets, such as `http://localhost/media/plugins/my-test-org/test-plugin/foo.js`, the first response from the server is `302` redirect to the same URL. The second time the URL is hit, the file is returned.

https://github.com/getkirby/kirby/blob/4c5e2c1feb1b9052902f8ad7d6e8248dc1eaafb7/src/Cms/PluginAssets.php#L59-L80

What seems to happen is: the symlink is created, and a redirect is returned to (presumably) the same file. It's then up to the server (Apache or NGINX) to supply the file contents.

It totally makes sense for the symlink to happen and have NGINX pick up on that for subsequent calls, but it means the _first_ request for the plugin asset never returns the actual file.

Would it make more sense to avoid having a redirect altogether and let Kirby return the file contents itself? It just seems odd to have a server return a 302 redirect to the same URL it's requesting.

**Kirby Version**  
`3.3.3`

**Comment by lukasbestle** [comment]
I agree that it's most likely faster to serve the file directly than requiring another roundtrip to the server.

@bastianallgeier Was there a non-obvious reason why the current implementation redirects?

**Comment by bastianallgeier** [comment]
✅  It's great to finally fix an issue from Feb 2020 😅
