### ISSUE TITLE
Panel: Creating a Language Does Not Use Displayed Placeholder "PHP locale string"

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2427]
**Describe the bug**  
When creating a language in the Panel, the dialog gives the very strong impression that if the "PHP locale string" is left unfilled, it will use `en_US` (not sure if this displayed value is dependent on some other configuration).

However, the language file that is created will actually use the value supplied for "Code". 

**To Reproduce**  
1. Create a language in the Panel with values such as:
<img width="508" alt="Screen Shot 2020-02-04 at 3 32 31 PM" src="https://user-images.githubusercontent.com/417182/73797399-ca9fe680-4764-11ea-988f-b58a96d9f70c.png">

2. Inspect the created language file

**Expected behavior**  
The `locale` should be `en_US` as suggested by the dialog. Instead, the value will look like:
```php
<?php

return [
    'code' => 'en-us',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        6 => 'en-us'
    ],
    'name' => 'English (US)',
    'translations' => [

    ],
    'url' => NULL
];
```

**Kirby Version**  
`3.3.3`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.5 (15608.5.11)

**Comment by afbora** [comment]
I can't see a problem here either.
If the local setting is empty, it gets the `code` value. 
I think this is correct process. Indeed, the placeholder of `en_US` is not exactly a suggestion i think, but a representation of the format.

https://github.com/getkirby/kirby/blob/3.3.3/src/Cms/Language.php#L500-L513

But as an improvement to your use, we can parse/replace it if hype is used, something like that:

````php
$this->locale = [LC_ALL => str_replace('-', '_', $this->code)];
````

@lukasbestle will give us an idea on this matter.

**Comment by nilshoerrmann** [comment]
Maybe it's not the best use of a placeholder here. Why don't you:

a) add the format hints as help texts?
b) autofill the PHP locale string with the correct value based on the code?

**Comment by afbora** [comment]
@nilshoerrmann Vote A for your solutions as a simple way 👍

**Comment by nilshoerrmann** [comment]
If you switch to help texts, it would also be possible to make those texts translatable so that a user with English panel sees `en_US` for instance and a user with German panel sees `de_DE`. This would make you feel more at home. But maybe that's even how it works right now – I have to admit I don't know :)

**Comment by lukasbestle** [comment]
+1 for help texts!

**Comment by neildaniels** [comment]
Help text would definitely be an improvement here.

But bonus points if this was a dropdown field that let you pick from a list of all the locales that the system supported. (Or, multiple dropdowns. One to select language, one to select country, and maybe one for the characterset and it just builds the PHP locale string from those values.)

**Comment by distantnative** [comment]
@neildaniels I searched a bit but as far as I can see there is no good way to get a list of the system's supported locales.

**Comment by bastianallgeier** [comment]
✅
