### ISSUE TITLE
Uncaught Error: Class ‘Whoops\Util\Misc’ not found

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2429]
**Describe the bug**  
We found this in the logs of a live site:  

``` 
PHP Fatal error:  Uncaught Error: Class 'Whoops\Util\Misc' not found in /kirby/vendor/filp/whoops/src/Whoops/Run.php:302
#0 /kirby/vendor/filp/whoops/src/Whoops/Run.php(353): Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#1 /kirby/vendor/composer/ClassLoader.php(444): Whoops\Run->handleError(2, 'include(/home/p...', '/home/xyz/p...', 444, Array)
#2 /kirby/vendor/composer/ClassLoader.php(444): include()
#3 /kirby/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/xyz/p...')
#5 /kirby/vendor/filp/whoops/src/Whoops/Run.php(375): spl_autoload_call('Whoops\\Util\\Mis...')
   in /kirby/vendor/filp/whoops/src/Whoops/Run.php on line 302
```  

This has been discussed here:
https://forum.getkirby.com/t/uncaught-error-class-whoops-util-misc-not-found/16985

It's not clear why the class could not be loaded.
Please note that we suffered from a DDOS attack around the same time so the issue might well be caused by that.

**Comment by lukasbestle** [comment]
Does the file `kirby/vendor/filp/whoops/src/Whoops/Util/Misc.php` or `vendor/filp/whoops/src/Whoops/Util/Misc.php` exist on the server?

**Comment by nilshoerrmann** [comment]
Yes, the file exists.

**Comment by lukasbestle** [comment]
Which installation method did you use on the server (Composer, Git submodule, simple download)?

If Composer and the issue still occurs, try running `composer dump-autoload -o`.

If the issue does not currently occur, I‘d wait until it comes up again. Maybe it was a temporary issue that was fixed with your new deployment.

**Comment by nilshoerrmann** [comment]
We are using Git submodules.

**Comment by lukasbestle** [comment]
Then it shouldn‘t be an autoloader issue.

Does the issue still occur?

**Comment by nilshoerrmann** [comment]
No, it doesn't. Bastian wanted to investigate nonetheless:

> Hm, it’s still weird why the class could not be loaded to be honest. Let’s create the ticket anyway and maybe you can add a note about the DDOS attack to it.

**Comment by lukasbestle** [comment]
To be honest, I think we now have investigated what we could. If the file exists and you use Git submodules, I don’t see where the issue could come from. Please let us know if it happens again.
