### ISSUE TITLE
[Panel] Implement blueprint extensions

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#243]
Extensions are half-implemented from a few weeks ago, but need to be polished. This is what we need:

- [x] Blueprint extensions 
- [x] Tab extensions (site/blueprints/tabs)
- [x] Section extensions (site/blueprints/sections)
- [x] Field extensions (site/blueprints/fields)

**Comment by jenstornell** [comment]
Will plugins be able to register a whole tab set of fields? That would be great for example Kirby Seo etc.

**Comment by bastianallgeier** [comment]
@jenstornell yes. You will be able to do something like this: 

```php
Kirby::plugin([
    'name' => 'seo/tab',
    'blueprints' => [
        'tabs/seo' => __DIR__ . '/seo.yml'
    ]
]);
```

Or you can even do that with an array

```php
Kirby::plugin([
    'name' => 'seo/tab',
    'blueprints' => [
        'tabs/seo' => [
            'label' => 'SEO',
            'icon'  => 'search',
            'columns' => ...
        ]
    ]
]);
```

**Comment by bastianallgeier** [comment]
✅
