### ISSUE TITLE
`I18n::translateCount()` doesn't replace {{ count }} for single-string values

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2431]
**Describe the bug**  
If you give `I18n::translateCount()` a translation key that only has a single value, it will not replace `{{ count }}` with the passed value.

For a language like Chinese, there isn't a concept of a "plural form" that varies because of the number. So it's `0 天`, `1 天`, `2 天`, `3 天`, etc.

That makes creating translation strings for a language lie Chinese unnecessarily verbose by listing the same string 3 times.

**Kirby Version**  
`3.3.3`

**Comment by bastianallgeier** [comment]
✅
