### ISSUE TITLE
[Panel] Language name input not required when editing

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2436]
**Describe the bug**  
The name of the language must be entered as mandatory when adding a language, but when editing it, it can be saved even though highlighted with red.

**To Reproduce**  
1. Add language
2. Edit the added language
3. Leave empty language name and save

**Expected behavior**  

**Screenshots**  
![FireShot Capture 025 - Settings - Mægazine - localhost](https://user-images.githubusercontent.com/3393422/74138697-1f2ee000-4c03-11ea-9c84-0640d7b43231.png)

![FireShot Capture 024 - Settings - localhost](https://user-images.githubusercontent.com/3393422/74138564-e68f0680-4c02-11ea-9b8d-84ba5c31c90d.png)

**Kirby Version**  
3.3.3

**Console output**  
No output

**Desktop (please complete the following information):**  
 - Windows 10
 - Chrome 79

**Comment by bastianallgeier** [comment]
✅
