### ISSUE TITLE
Language code suffix duplicated when new language added

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2437]
**Describe the bug**  

When we create a new language from panel, language code is added at the end of the content files like `photography.en.txt`. But if the language code already exists end of content filenames, it repeats like `photography.en.en.tr.txt`. I do not know exactly whether it is bug but I think it will be more stable if we check and correct it before adding language.

**To Reproduce**  
1. Add a language from panel
2. Delete `/site/languages` folder manually
3. Add a language from panel again
4. Check content files and see error

**Kirby Version**  
3.3.3

**Comment by lukasbestle** [comment]
If you manually delete the languages folder, the Panel thinks that the site is single-language and assumes that the content file names are supposed to be template names.

If you only create and delete languages in the Panel, the conversion works properly.

So I’d say this is not a bug.

**Comment by afbora** [comment]
I know, therefore, I'm not sure this is exactly a bug.

In fact, would anyone be experiencing this problem when moving content from one site to another? :thinking:

**Comment by afbora** [comment]
I thought again, may be it is a very rare situation. 
For this, there is no need to turn the core into a complex structure.
Thank you @lukasbestle
