### ISSUE TITLE
When choosing a different/no icon for the tags field it is not reflected in the dropdown

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2438]
**Describe the bug**  
As the title says, when you set `icon: false` or `icon: someicon` and use tag options in combination with a query, the dropdown still shows a tag icon before the selectable value. It would be useful if the chosen icon option was reflected in the dropdown.

**To Reproduce**  
1. Create a new tags field with an options query.
2. Set `icon: false` or a different icon than the standard `tag` icon.
3. See how the dropdown always shows a tag icon.

**Expected behavior**  

**Screenshots**  

<img width="522" alt="Screenshot 2020-02-10 at 21 15 34" src="https://user-images.githubusercontent.com/5312492/74186284-989df100-4c4a-11ea-8103-aa2efbf3e90e.png">

**Kirby Version**  
Kirby 3.3.3

**Comment by bastianallgeier** [comment]
✅
