### ISSUE TITLE
Relative links and multi language

### ISSUE THREAD

**Issue by tweh** [getkirby/kirby#244]
This question came [form the forum](http://forum.getkirby.com/t/relative-links-and-multi-language/519) and we’re not sure if this is really a bug, but since the behaviouve change form v1 to v2 it seems not unlikely at least. So thats the problem:

I try to move my multi language homepage from kirby1 to kirby2. Almost everything works fine. The selected language remains while using the menu for navigating.
Unfortunately, the kirbytext - relative links do not work anymore as supposed. Here the url() is build always without $language->code(), so that I always get redirected to the right content but the default language.

Imagine the following structure:

    content/home/
        home.de.txt
        home.fr.txt
        home.it.txt
        home.en.txt
    content/contactform/
        contactform.de.txt
        contactform.fr.txt
        contactform.it.txt
        contactform.en.txt

I placed a relative link to the contact form on all four home's, like this:

     (link: contactform/contactform)

With __Kirby v1__:
calling this link from `home.de`, it got translated to: `server/de/contactform/contactform`
calling this link from `home.en`, it got translated to: `server/contactform/contactform` (english is default)

With __Kirby v2__:
calling this link from `home.de`, it gets translated to: `server/contactform/contactform`
calling this link from `home.fr`, it gets translated to: `server/contactform/contactform`
calling this link from `home.en`, it gets translated to: server/contactform/contactform`

_(written by jsc and slightly changed by me)_

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.

**Comment by iamvdo** [comment]
I have a similar issue with Kirby 2, let me explain:

I want relative URLs, with multi language pages.
If I set:

```php
c::set('url', '/');
```

With languages:

```php
c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'English',
    'locale'  => 'en_US',
    'url'     => '/en',
  ),
  array(
    'code'    => 'fr',
    'name'    => 'Français',
    'default' => true,
    'locale'  => 'fr',
    'url'     => '/',
  ),
));
```

I get correct URLs for english part. French part URLs are messed up cause URLs started with `//`.

I tried to remove `/` from `c::set('url', '');` or `c::set('languages', array('code': 'fr', 'url': ''))` with no luck

**Comment by tweh** [comment]
I got no problem with nearly the same config, exempt that my default language comes first (and that it is `de` instead of `fr`):

```php
c::set('languages', array(
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'default' => true,
    'locale'  => 'de_DE',
    'url'     => '/',
  ),
  array(
    'code'    => 'en',
    'name'    => 'English',
    'locale'  => 'en_US',
    'url'     => '/en',
  ),
));
```

Did you tried to set change the order?

**Comment by iamvdo** [comment]
Same problem. Pretty weird.

**Comment by distantnative** [comment]
Snd you use the most current version from the develop branch?

**Comment by iamvdo** [comment]
No. I use the Kirby starter kit from master branch, as mentioned in docs.

**Comment by iamvdo** [comment]
I find that replacing line 132 of file `branches/multilang/page.php` from

```php
return $this->parent->url($lang) . '/' . $this->slug($lang);
```

to

```php
return (($this->parent->url($lang) == '/') ? '' : $this->parent->url($lang)) . '/' . $this->slug($lang);
```

resolve my problem.

Maybe a contributor can check ?

**Comment by distantnative** [comment]
Hmm, then I might just quote @bastianallgeier (the developer of Kirby) commenting on this issue/bug:

> I just fixed this on the develop branch.

Ergo, this isn't fixed on any master branch, but on the develop branch of the kirby repo.

**Comment by iamvdo** [comment]
>this isn't fixed on any master branch, but on the develop branch of the kirby repo

No I don't think so. develop branch has been merged to master and fix was released on May 21st. 

But, I need to explain more. The problem isn't with the link tag, but with the classic `$page->url()`. That's why I started with:

>I have a similar (follow up?) issue

Maybe I have to open another issue, to keep clarity?

**Comment by texnixe** [comment]
What exactly is your problem @iamvdo? Are you saying that you get double slashes in the url if you try to echo `$page->url()`? But you are right, fix #244 is in the master release.

**Comment by iamvdo** [comment]
>Try removing this setting or setting it to false (which is the default anyway).

I want relatives URLs, not absolute ones. That's why I set this option this way (as mentioned in Kirby 1's config). 

The problem is: in homepage, I list all pages/subpages with a link to each page. In EN, all links are well generated, eg `/en/blog/link-to-the-article`.
In FR, links are badly generated, eg `//blog/link-to-the-article`.

In browsers, URLs that start with `//` are considered absolute, using the current protocol.

**Comment by texnixe** [comment]
Well, I was just wondering if this setting from Kirby 1 is still valid for Kirby 2; when I tried to add your setting to the config file of a brand new Kirby 2 langkit installation, it broke the whole site.

**Comment by iamvdo** [comment]
Yes, I'm also wondering. There's no mention anymore in Kirby 2, so how are we suppose to manage relative URLs?

**Comment by texnixe** [comment]
May I ask why you want to force relative URLs?

**Comment by iamvdo** [comment]
- Easy to test (live site, dev site), less server config
- I use CSS based on relatives/absolutes link. I add an icon to external (absolute) links
- This used to work in Kirby 1

I know things can me made differently, but I don't want to create a brand new site, only update it ;)

**Comment by texnixe** [comment]
Maybe someone else knows a way to achieve relative URLs but there are certainly good reasons to prefer absolute URLs over relative ones.

> Easy to test (live site, dev site), less server config

 since you can work with relative links internally which are just converted to absolute urls, there should be no need for server configurations?
> I use CSS based on relative/absolute links. I add an icon to external (absolute) links:  

I don't know your implementation but I guess there is a way to solve that.

> This used to work in Kirby 1

Yeah, but unfortunately, some things don't work anymore, but the great news is that Kirby 2 is so much more powerful:)

**Comment by iamvdo** [comment]
There's always solutions to solve problems. :)
I started update based on http://getkirby.com/docs/installation/upgrade but it's more painful than it looks.
