### ISSUE TITLE
[Panel] Translate error page title

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2441]
**Describe the bug**  
If you leave empty page title while page creating, getting `Please enter a title` error for all languages.

Related issue line:
https://github.com/getkirby/kirby/blob/3.3.3/panel/src/components/Dialogs/PageCreateDialog.vue#L113

**To Reproduce**  
1. Go to panel
2. Change user language that no english
3. Try to create page with empty title

**Kirby Version**  
3.3.3

**Comment by bastianallgeier** [comment]
✅
