### ISSUE TITLE
Overflow with long filename in file delete dialog

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2449]
<img width="788" alt="Screen Shot 2020-02-13 at 08 59 11" src="https://user-images.githubusercontent.com/3788865/74413409-a23c7a00-4e3f-11ea-8b5d-de8b1e4a9510.png">

**Comment by afbora** [comment]
@distantnative you removed `easy` label but i can fix with `word-wrap: break-word;` this issue and filename header in files detail page?

**Before**:
![FireShot Capture 010 - Trees - Mægazine - localhost](https://user-images.githubusercontent.com/3393422/74607781-c40e5900-50ec-11ea-8f04-96161bc18635.png)

**After**:
![FireShot Capture 011 - Trees - Mægazine - localhost](https://user-images.githubusercontent.com/3393422/74607796-f1f39d80-50ec-11ea-8c5b-a9515c629d50.png)

**Before**:
![FireShot Capture 008 - monster_trees_in_the_fog_monster_trees_in_the_fog_monster_trees_in_th_ - localhost](https://user-images.githubusercontent.com/3393422/74607742-519d7900-50ec-11ea-80fc-b3468de5ec6a.png)

**After**:
![FireShot Capture 009 - monster_trees_in_the_fog_monster_trees_in_the_fog_monster_trees_in_th_ - localhost](https://user-images.githubusercontent.com/3393422/74607772-a214d680-50ec-11ea-8526-7bb3b739353e.png)

**Comment by bastianallgeier** [comment]
✅
