### ISSUE TITLE
Language editor in the Panel: Empty locale not validated

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2455]
Originally reported by @afbora in #2435:

---

Saving empty locale issue as a second problem steps to reproduce:

1. Add a language
2. Edit language
3. Leave blank locale input
4. Save language
5. See issue as language config like:

````php
'locale' => [
    'LC_ALL' => ''
]
````

You can also enter a space from panel and config saving like that:

```php
'locale' => [
    'LC_ALL' => '    '
]
```

---

I think we should fix this by:

- removing surrounding whitespace from the input by trimming
- setting the locale to the language code if empty (like the Panel already does it when creating languages)

**Comment by bastianallgeier** [comment]
✅
