### ISSUE TITLE
Users’ content in wrong language on virtual pages

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#2458]
**Describe the bug**  
In a multilingual environement, when you fetch a user in a **virtual** page and display some of its content, this content does not respect Kirby's current language but instead goes for the default. This issue seems to work properly in "real" pages though.

**To Reproduce**
*Note that the following instructions have been summarized from my own setup which is much more complicated, sorry in advance if I've made a typo somewhere.*

Setup Kirby with at least 2 languages
Add a custom translated field on your users (site/blueprints/users/default.yml):

```yaml
fields:
  biography:
    label: Biography
    type: textarea
```

Create a user with the userame "testuser" in the panel and fill-in a different biography in each language.

Create a route for the virtual page in config.php:

```php
return [
  'routes' => [
    'pattern' => 'virtual',
    'language' => '*',
    'action' => function($language) {
      site()->visit('virtual', $language->code());
      $page = new VirtualPage([
        'slug' => 'virtual',
        'template' => 'virtual'
      ]);
      return $page;
    }
  ],
]
```

Create the following page model (site/models/virtual.php):

```php
class VirtualPage extends Page {
  public function __construct(array $props)
  {
    parent::__construct($props);
    $this->user = kirby()->users()->findBy('username', 'testuser');
  }
}
```

Display the biography in the template (site/templates/virtual.php):

```php
<?= $page->user()->biography()->kirbytext() ?>
```

Visit the page at `/virtual`

Whatever the language you visit the page in, it displays the default language biography.

**Expected behavior**  
The user "content" fields should return data based on the currently used locale.

**Kirby Version**  
3.3.3

**Comment by afbora** [comment]
I think there is an issue similar to #2428

**Comment by LeBenLeBen** [comment]
For anyone coming accross this issue and looking for a work around, you can grab the data through the content getter with the current language hard-coded:

```php
$page->user()->content(kirby()->language()->code())->biography()->kirbytext()
```

**Comment by afbora** [comment]
I have tested the issue and this is same with  #2428 
I can fix  with use `setCurrentLanguage()` in route.
The other one that #2428  was solved using `setCurrentTranslation()`.

````php
return [
    'debug' => true,
    'languages' => true,
    'routes' => [
        [
            'pattern' => 'virtual',
            'language' => '*',
            'action' => function($language) {
                // Fix for translations of requested language
                kirby()->setCurrentTranslation($language);

                // Fix for current language
                kirby()->setCurrentLanguage($language);

                ...
                ...
                ...
            }
        ]
    ]
];
````

**Comment by afbora** [comment]
I'm closing the issue because it is the same with other about setting language on routing issue.
