### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#2463]
This might not be related to Kirby but to webserver settings or it might be impossible to do. I am not sure but multiple people had same problem when mentioned on Slack.

**Describe the bug**  
Upload progress bar has only two states 0 and 100%. When the state changes the bar transitions but it is not same as actual progress. Progress becomes very useful when uploading multiple bigger files.

**To Reproduce**  
Upload any files. On localhost it looks right because upload is almost instant and transition makes it seem like progress bar is working.

**Expected behavior**  
Progress bar should show percentage of uploaded data.

**Screenshots**  
![Screen Shot 2020-02-18 at 13 17 36](https://user-images.githubusercontent.com/4954323/74737109-73b20b00-5254-11ea-9378-f35330b39964.png)

**Kirby Version**  
3.3.3

**Console output**  
No output

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox 72.0.2, Chromium 79.0.3945.130

**Comment by bastianallgeier** [comment]
✅
