### ISSUE TITLE
pages section parent query support "page()"

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#2466]
**Describe the bug**  
setting the parent only works when starting the query with`kirby.` or `site.` objects but no built in helpers like `page()`.
https://getkirby.com/docs/reference/panel/sections/pages#filtering-pages

**To Reproduce**  
```yaml
parent: page('events')
```

**Expected behavior**  
i expected the `page()` helper to work in queries.

**Comment by distantnative** [comment]
Not a bug. The query language has to start with one of the objects you mentioned, it can’t start from nowhere. Use `site.page()`
