### ISSUE TITLE
Check if Folder exists Method

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#2468]
For files, there exists F::exists() Method but for Folders not. Wouldn’t it make sense to have Dir::exists()? According to this Thread

https://forum.getkirby.com/t/check-if-folder-exists/17357

**Comment by Werbschaft** [comment]
Of course there are possibilities to do this directly in PHP. But for many users, the Kirby methods are much clearer and easier to understand.

I feel the same way. Otherwise you could also remove `F::write()` because there are `file_put_contents`. And so on. I think it makes sense to get these abbreviations because they are often clearer and simpler than their PHP counterparts.

It should always be borne in mind that not everyone is an absolute PHP professional like the people discussing here. Especially since these are mostly the main programmers at Kirby.

If the discussion goes in that direction, you might as well question the purpose of each framework and each function or method.

Why use so many symfony? Why use bootstrap, for example? Anyone can create buttons, input fields, headings by hand using native CSS methods. The whole point is that a framework is faster and is already more well thought out. And this is what the Kirby methods and helpers done.

**Comment by lukasbestle** [comment]
You are right about that: Remembering all the function names of PHP functions and their quirks is something not everyone wants to do.

So I think we could introduce the `Dir::exists()` method as an alias for `is_dir()`. We should also reconsider why the current implementation of `F::exists()` is that complex. @bastianallgeier Why doesn't that method just use `is_file()`?

**Edit:** I know why: It supports the `$in` param of `F::realpath()`. So we need to keep that as it is. We can still introduce the `Dir::exists()` method.

**Comment by bastianallgeier** [comment]
✅
