### ISSUE TITLE
Using (file:file.jpg) with path doesn’t work

### ISSUE THREAD

**Issue by tweh** [getkirby/kirby#247]
There seems wo be a bug in the `file` tag, when I try to link to a file which is not in the same content folder as the text file.

While `(image:downloads/file.jpg)` and `(link:downloads/file.jpg)` work fine, `(file:downloads/file.jpg)` doesn't create a link. Please see the [discussion in the forum](http://forum.getkirby.com/t/how-can-link-to-a-file-form-another-subpage-with-file/1087?u=tobiasweh) for more information.

**Comment by bastianallgeier** [comment]
This will be fixed in 2.1 and is already available on the develop branch.
