### ISSUE TITLE
Kirbytag helper function not working as expected

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#2474]
**Describe the bug**  
Right now it is not possible to pass a page (`parent`) reference to the helper function.

```php
// does not work
echo kirbytag('image', 'some-image.jpg', [
  'parent' => $page,
]);

// using the kirbytags helper works though
echo kirbytags('(image: some-image.jpg)', [
  'parent' => $page,
]);
```

After some digging I probably found the issue. I can't tell if this is by design or just an oversight but the `Kirby\Cms\App` uses the `Kirby\Text\KirbyTag` class instead of the extended `Kirby\Cms\KirbyTag` one. I think that this is indeed a bug and not a feature 🙂  
So deleting this line fixes the issue:

https://github.com/getkirby/kirby/blob/3.3.4/src/Cms/App.php#L15

**Kirby Version**  
3.3.3

**Comment by afbora** [comment]
@lukaskleinschmidt Great caught! 👍

**Comment by bastianallgeier** [comment]
✅
