### ISSUE TITLE
Modal page creation appear under a page section with a sticky column  

### ISSUE THREAD

**Issue by doriansimeha** [getkirby/kirby#2477]
When I click on a page section which is inside a column with a sticky position to add a page, the modal for create the page appear under another column's page section.

![Capture d’écran 2020-03-01 à 22 44 53](https://user-images.githubusercontent.com/39616961/75634569-62331080-5c0f-11ea-9a30-178afb0676df.png)

The column that is sticky is the left one.

![Capture d’écran 2020-03-01 à 22 45 20](https://user-images.githubusercontent.com/39616961/75634571-665f2e00-5c0f-11ea-8845-e676eb796ced.png)

There is no problem without the sticky options.

**Comment by bastianallgeier** [comment]
✅
