### ISSUE TITLE
[Panel] Reset/Forgot password

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#248]

**Comment by lukasbestle** [comment]
Can be built on top of the new session implementation once that is ready.

**Comment by lukasbestle** [comment]
Leaving this note here in case anyone wants to implement this feature as a plugin or in case we later decide to implement this in the core:

The new session implementation supports creating sessions in "manual mode", which means that the session token won't be sent to the current visitor in the HTTP response. This feature can be used to generate a unique link that can be sent to the user via email. If you want to implement password reset and want to learn more about the implementation I described above, please get in touch. :)
