### ISSUE TITLE
changeStatus: "Failed to open stream: Too many open files"

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2481]
**Describe the bug**  
While importing data from an external site we noticed that after a few hundred imported pages, we were getting the following error: 

> Failed to open stream: Too many open files

After digging for a while, we found out that publishing the pages after the import was the culprit:

```php
$page->changeStatus('listed');
```

It doesn't matter if the published pages should be sorted (numeric or date-based) or if they should just feature a zero-based index: somehow the publishing process seems to open/read a lot of files without closing those connections later on. 

**To Reproduce**  
This is a simplified version of our import script:

```php
$export = file_get_contents('path/to/export.xml');
$xml = simplexml_load_string($export);

foreach ($xml->data->entry as $entry) {
    $data = [
        'template' => 'document',
        'draft' => false,
        'content' => [
            'title' => $entry->titel,
            'text' => $entry->text
        ]
    ]

    try {
        $page = page('something')->createChild($data);
        $page->changeStatus('listed');
    } catch (Exception $e) {
        echo $e->getMessage();
    }
}
```

Removing `$page->changeStatus('listed');` will make the error go away but then there is no way to bulk-publish those pages.

**Expected behavior**  
Bulk-publishing should be possible (it's a nightmare to do this by hand for hundreds of pages).

**Kirby Version**  
3.3.4

**Comment by nilshoerrmann** [comment]
When setting the new page number manually everything works without an issue, e. g.:

```php
$page->changeNum(0);
```

It works as well when using a date-based index or when setting a sorting number directly. So something in the way Kirby determines the correct index is causing this issue.

**Comment by afbora** [comment]
I can't reproduce the issue with 1000 children creation:

````php
try {
    for($i = 0; $i < 1000; $i++) {
        $page = page('test')->createChild([
            'template' => 'document',
            'draft' => false,
            'content' => [
                'title' => $i
            ]
        ]);

        $page->changeStatus('listed');
    }
} catch (Exception $e) {
    echo $e->getMessage();
}
````

**Quote on [SO](https://stackoverflow.com/a/14749074/1769465):**

> This can be a limitation on the server where the code is running. Every operating system only allows for a certain number of open files/handles/sockets. This limit is usually further reduced when the server is virtualized. On a Linux server you can check the current limit with ulimit -n, if you have root access you can increase it with the same command. I assume there is a method for Windows server as well. Otherwise there is not much you can do about it (except ask your hoster or administrator to increase it).

**Comment by nilshoerrmann** [comment]
Yes, I‘ve read that on StackOverflow as well. Still: why are the files kept open?

**Comment by afbora** [comment]
Hmm, if I could reproduce the issue, I would try something like that with `Connection: close` 🤔

````php
public static function read(string $file)
{
    $context = stream_context_create(array('http' => array('header'=>'Connection: close\r\n')));
    return file_get_contents($file, false, $context);
}
````

https://github.com/getkirby/kirby/blob/3.3.4/src/Toolkit/F.php#L514-L517

**Comment by nilshoerrmann** [comment]
Sadly, I'm not able to share my original data because it's highly sensitive (addresses, birthdays and such). But here is a bit of context that might help: this issue happens locally on macOS Catalina using Laravel Valet.

What I could share privately with the team is my import script in case that's the cause.

**Comment by nilshoerrmann** [comment]
I remember [this comment about using `file_get_contents`](https://github.com/getkirby/kirby/issues/2330#issuecomment-564573940):

> Also, there's an issue where your server configuration might not allow file_get_contents() fetching remote urls. Perhaps curl would be a better option here.

I don't know about the impact of such change but would that help in my context?

**Comment by afbora** [comment]
> Sadly, I'm not able to share my original data because it's highly sensitive 

@nilshoerrmann When I couldn't reproduce the issue, I meant your chance to try the modified `read()` method with `Connection: close`.

**Comment by afbora** [comment]
@lukasbestle I can't reproduce but do you have an idea about what happened?

**Comment by lukasbestle** [comment]
To be honest I have no idea why the `changeStatusToListed()` method in particular would cause this, especially when zero-based indexing is used (which doesn't need to determine the sorting number from the siblings or resort the siblings after publishing).

This is very hard to debug unfortunately, even if we would be able to reproduce it.

@nilshoerrmann Another alternative would be to pass the `num` directly in the `$data` array when calling `createChild()`. This will also have a better performance as each page will only need to be touched once.

**Comment by nilshoerrmann** [comment]
`createChild` doesn‘t allow for setting `num` manually. But as I‘ve found a workaround and I have not the knowledge how to debug the issue let‘s just close it.

Thanks for your support!
