### ISSUE TITLE
User.txt session refresh issue after $user->update

### ISSUE THREAD

**Issue by hroma** [getkirby/kirby#2486]
Passing $user = $user->update… to a template is working as expected but
when a user edit his data (user.txt) in the frontend, change stored (in a session?) aren't updated (snippet for my case).

CASE SCENARIO:
LoggedIn user can subscribe (true) or unsubscribe (false) to a newsletter on a toggle basis:
```
$user = $kirby->user('user@email.com');
$currentStatus = $user->newsletter();
echo 'Old value: '.$currentStatus.'<br>';
$variable = ($currentStatus == 'true' ? 'false' : 'true');
$user->update(['subscribe' => $variable]);
echo 'New value: '.$user->newsletter();
```
RESULT:
Old value: false
New value: false 

EXPECTED:
Old value: false
New value: **true**

Did I miss Something to update the User globally or it is a bug?
Hope it helps making Kirby even better

**Comment by distantnative** [comment]
It should be

```php
$user = $user->update(['subscribe' => $variable]);
```

Kirby objects are immutable but return the altered object. So you have to put it back in your variable.

**Comment by hroma** [comment]
Ok, but then my snippet / included in the default template returns

Whoops \ Exception \ ErrorException (E_NOTICE) 
Undefined variable: user

in the snippet 
`<?php $user = kirby()->user(); ?>`

how to update kirby()->user(); itsef?

**Comment by afbora** [comment]
@hroma Can you share all the codes in snippet?  I think you have diffrent problem.

**Comment by hroma** [comment]
Thank you for investigating the issue. 
Snippet simplified (without all html stuff and form to sumbit "true" or "false"):
```php
$user = kirby()->user(); 

if ($user->subscribe() == 'true') {  
    echo 'true';
} else { 
    echo 'false';
}
```

Controller:
```php
return function ($site, $pages, $page) {
    $kirby = kirby();
    if ($kirby->request()->is('POST')) {
        $variable = get('newsletter'); 
        $user = $kirby->user('user@email.com');
        $user = $user->update(['newsletter' => $variable]);
    }
    return array('user' => $user);
}
```

Template:
```php
echo $user->newsletter().' - ';
snippet('subscribe.php');
```

Result:

1) for true = true - false
2) for false = false - true


Expected:
1) true - true
2) false - false


If you refresh the browser (F5)…???:
1) true - true
2) false - false

**Comment by afbora** [comment]
Yes now I can reproduce the issue. 

After updating the user, the `user` variable in the `Auth` class comes from the cache in during request.

**Comment by afbora** [comment]
We need to override `update()` method in `UserActions` like that:

````php
trait UserActions
{    
    public function update(array $input = null, string $language = null, bool $validate = false)
    {
        $user = parent::update($input, $language, $validate);

        // set auth user data only if the current user is this user
        if ($user->isLoggedIn() === true) {
            $this->kirby()->auth()->setUser($user);
        }

        return $user;
    }
}

**Comment by hroma** [comment]
Great. It is working well now. Thank you for your fast support

**Comment by afbora** [comment]
@hroma I have updated the code on above comment: https://github.com/getkirby/kirby/issues/2486#issuecomment-594847916

However, I recommend not using it production website unless PR is approved.

**Comment by bastianallgeier** [comment]
✅
