### ISSUE TITLE
[Panel] Middle click not working on all actions

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#25]
I don't know if there is a scroll wheel on Mac but we have that on Windows. When clicking it, a new tab is opened.

If I middleclick on "Users" in the sidebar for example, I expect to open the users view in a new tab. It does not work. It's because it's not a link, it's a button.

The big question is, can it be turned as a link or is it too much work? I think it's the only way it could work.

**Comment by bastianallgeier** [comment]
We definitely need to revisit our button component to create correct links wherever possible.

**Comment by bastianallgeier** [comment]
✅
