### ISSUE TITLE
Database joins error

### ISSUE THREAD

**Issue by ronaldtorres** [getkirby/kirby#2501]
**Describe the bug**  
When you use innerJoin, leftJoin or rightJoin methods on a query, you will get an `InvalidArgumentException` with the message 'Invalid join type INNER|LEFT|RIGHT'.

**To Reproduce**  
1. Execute a query as:
   ```php
   Db::table('my_table')->select('*')
        ->innerJoin('other_table', 'my_table.id = other_table.id')
        ->all();
   ```
2. See error

**Expected behavior**  
The query result(s)

**Kirby Version**  
3.3.3

**Desktop (please complete the following information):**  
 - OS: Mac OS
 - Browser: All browsers
 - Version: All

**Comment by distantnative** [comment]
Proposed solution from @ronaldtorres: https://github.com/getkirby/kirby/pull/2502

**Comment by bastianallgeier** [comment]
✅
