### ISSUE TITLE
Panel access is not possible when api access is disabled

### ISSUE THREAD

**Issue by rzschoch** [getkirby/kirby#2508]
It is not possible to access the panel when the api config option is set to false.

**To Reproduce**  
1. Edit '/site/config/config.php':

```php
return [
  'panel' => true,
  'api' => false,
];
```
2. See error while trying to access the panel

**Expected behavior**  
I would expect to not have api access but I should be able to access the panel.

**Kirby Version**  
3.3.4

**Comment by lukasbestle** [comment]
That is intended behavior – the Panel also uses the API internally and won't work if the API is disabled. I have [added a note about this to the docs](https://getkirby.com/docs/reference/system/options/api#disable-the-api).
