### ISSUE TITLE
Kirby code warnings in two files ($this can not be used in static methods)

### ISSUE THREAD

**Issue by rzschoch** [getkirby/kirby#2509]
Not sure if this is the right place for it. This is not really a bug as kirby is working fine but I wonder if there is an opportunity to improve code quality?

VScode marks several code issues in two files with `$this can not be used in static methods` :

```
kirby/src/Form/Field.php (e.g. line 186)
kirby/src/Cms/LanguageRoutes.php (line 43)
```
**Kirby Version**  
3.3.4

**Comment by distantnative** [comment]
The code quality is actually fine. The problem is rather on the quality of those parsers which are too limited to properly interpret the context of which the code parts will be used in.

**Comment by lukasbestle** [comment]
To explain why your linter marks those lines as errors even though the code quality is fine: Those are anonymous closures (callbacks) that are dynamically bound to a `$this` value in some other part of the code. The linter cannot statically test if that will happen, so it will report a false-positive error. The only way around that would be dynamic linting (checking while the code runs), but that's not viable for a code style checker.
