### ISSUE TITLE
Pagination extends beyond the range

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#251]
**maxfenton (https://github.com/maxfenton) wrote:**
> Consider this page http://getkirby.com/blog/page:6 which is (at the moment) the last page of the Kirby blog. If you change the url to http://getkirby.com/blog/page:7 you get the same page instead of a 404. There is no 7th page of results. Similarly, http://getkirby.com/blog/page:99 shows the same page instead of an error.
>
>Is there a way to limit $pagination to showing valid pages, and returning an error on page:n if ( n * limit > total posts ) ?

**Comment by bastianallgeier** [comment]
This is now fixed in the develop branch.
