### ISSUE TITLE
Downloads are cached in chrome

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2513]
**Describe the bug**  
With current headers responses created with `Response::download()` are cached by chrome. The response uses an invalid Expires header to prevent caching, which seems to be not respected by chrome.

**Kirby Version** 
3.3.4

**Desktop (please complete the following information):**  
 - OS: mac/windows
 - Browser: Chrome
 - Version: 80

**Additional context**  
I suggest replace replacing `Expire: 0` with `Cache-Control: no-cache`.

https://github.com/getkirby/kirby/blob/3175afeac359524da0896c4671cc9cffb08eb3e7/src/Http/Header.php#L303
https://github.com/getkirby/kirby/blob/3175afeac359524da0896c4671cc9cffb08eb3e7/src/Http/Response.php#L172

**Comment by bastianallgeier** [comment]
✅
