### ISSUE TITLE
Duplicating a page also duplicates .lock file

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2514]
**Describe the bug**  
When duplicating a page in the Panel, it also duplicates the `.lock` file.

**To Reproduce**  
1. Go to a page in the Panel (it should have images to offer the "copy files" option)
2. Make some changes to content fields, but **do not save** the page
3. Settings > Duplicate
4. Leave slug with `-copy` as is
5. Enable "Copy files"
6. Click "Duplicate"

**Expected behavior**  
The resulting content folder should be free of any `.lock` file.

Instead, the `.lock` files gets copied and the id in the file is of the original page, not the renamed one. (In other words, there's not `-copy` in the file.)

**Kirby Version**  
`3.3.3` and `3.3.5-rc.1`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.5

**Additional context**  
Not sure if it's relevant, but this is on a multi-language setup.

**Comment by afbora** [comment]
We can fix with adding lock file as default.

````php
$ignore = [
    $this->kirby()->locks()->file($this)
];
````

https://github.com/getkirby/kirby/blob/3.3.4/src/Cms/PageActions.php#L359

**Comment by bastianallgeier** [comment]
✅
