### ISSUE TITLE
Duplicating a page on a multi-language setup creates content files for untranslated languages

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2515]
**Describe the bug**
If you have a multi-lang setup and duplicate a page that only has a content file for the primary language, the newly created page will undesirably have content files for all the other languages. 

**To Reproduce**  
1. Assume you have a multi-lang setup with `en` (primary), `fr`, `es`
2. Go to an existing page that only has the primary `en` content filled in. (On disk, this page has no `fr` or `es` content files.)
3. Duplicate the page (if relevant, assume "copy files" is also enabled)
4. The newly created page will have files for `en`, `fr`, and `es`
5. (Interestingly, content meta files for images will not have extra versions.)

**Expected behavior**  
I would expect it to only duplicate content files for languages that actually exist.

This current behavior is extremely undesirable and non-obvious.

**Kirby Version**  
`3.3.3` and `3.3.5-rc.1`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.5

**Comment by afbora** [comment]
We can fix with checking translation is exists:

````php
if ($language->isDefault() === false && $copy->translation($language)->exists() === true) {
    $copy = $copy->save(['slug' => null], $language->code());
}
````

https://github.com/getkirby/kirby/blob/3.3.4/src/Cms/PageActions.php#L378-L380

**Comment by bastianallgeier** [comment]
✅
