### ISSUE TITLE
Cannot Replace a File With The Same Extension But Different MIME Type on File Details Page

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2519]
**Describe the bug**  
This is basically a duplicate of #1783, but specially while on a file details page.

#2359 fixed the issue within a Files section, but seems to not have fixed replacing the file while on the "details page" for a given file.

**Screenshots**  
<img width="470" alt="Screen Shot 2020-03-13 at 6 55 44 PM" src="https://user-images.githubusercontent.com/417182/76672754-41967f00-655c-11ea-96ce-0404fa859423.png">

**Kirby Version**  
`3.3.5-rc.1`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.5

**Comment by bastianallgeier** [comment]
✅
