### ISSUE TITLE
[Panel] Tags field isn't "auto-saved"

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#252]
And since there is no save button, I don't know how to persist this.

**Comment by jenstornell** [comment]
When does autosave accur? Only on blur or also after a time interval? When in a textarea a time interval may be important to not lose a whole article of written text.

**Comment by distantnative** [comment]
Currently only on blur, but I just added a PR to fire the auto-save on every change (add, remove, sort).

**Comment by bastianallgeier** [comment]
:check: Auto-saving is now done in local storage and solves this issue as well.
