### ISSUE TITLE
Custom page models are loaded after plugins

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2530]
**Describe the bug**  
If you use `page($id)` in a plugin, that page will be an instance of `Page` even if there's a custom model for it in `site/models`.

I have a custom logic for the routing of a certain page and I've put it in a class (and a plugin):

```php
$router = new BlogRouter(page('blog'));

App::plugin('my/plugin', [
	'routes' => [
		$router->getRoute()
	]
]);
```

I also have a custom model for that `blog` page. However, because I call `page()` in that plugin, the page is initialized as a regular `Page` object because custom models are not yet loaded by Kirby. Then, in my template, it's the same object.

**To Reproduce**  
1. Create a plugin
1. Create a page `blog/blog.txt`
1. Create a model `blog.php` with a `BlogPage` class
1. Add `page('blog')` in that plugin's `index.php`
1. Create a template `blog.php`
1. See the class of `$page` in the template

**Expected behavior**  
The page instance should be created using the custom model.

**Kirby Version**  
3.3.4

**Additional context**  
The problem is in this line:

https://github.com/getkirby/kirby/blob/master/src/Cms/App.php#L122

It's executed **after** `extensionsFromPlugins()`, meaning that the plugin creates an instance of the page before custom models are loaded. I think that line should be moved after `extensionsFromProps()`.

**Comment by distantnative** [comment]
We first have to load plugins and then models otherwise custom models could not overwrite models added by plugins.

**Comment by yandodov** [comment]
I see. I've previously had a similar problem when extending translations in this [thread](https://forum.getkirby.com/t/workaround-for-a-plugin-setting-before-the-plugin-is-initialized/16846).

I guess we could translate this to the ideas repo, but perhaps we should have a hook that allows a plugin to apply extensions _after_ other plugins are loaded and _after_ user components are loaded as well. In other words, those "final" plugins would apply configuration right before Kirby is ready to rock.

In my original comment in this issue, I want to get the `blog` page with its final model. I don't care if that model came from a plugin or if the user made it. With a `ready` hook similar to the [`ready` config option](https://getkirby.com/docs/reference/system/options/ready), I'd be able to do:

```php
App::plugin('my/plugin', [
  'ready' => function () {
    $router = new BlogRouter(page('blog'));

    return [
      'routes' => [
        $router->getRoute()
      ]
    ];
  }
]);
```

This would also fix the problem I had in the forum thread. In general, I think something like this could be very useful because you can extend stuff without worrying about the order in which Kirby loads configuration.

**Comment by lukasbestle** [comment]
@hdodov We have the hook [`system.loadPlugins:after`](https://getkirby.com/docs/reference/plugins/hooks/system-loadplugins-after), which should do pretty much exactly what you need. It gets called after all extensions have been loaded, including the ones from the `site/models` folder.

**Comment by yandodov** [comment]
@lukasbestle yes, I know about it, but I can't extend the config from within it, which is what I'm trying to do. In the code above, I'm returning a route that should be added to the config. With the `loadPlugins:after` hook I can run some code, but not provide further configuration.

**Comment by lukasbestle** [comment]
@hdodov Sorry for the late reply.

I have built an example plugin that should do what you need based on the `system.loadPlugins:after` hook. Please let me know if this works for you:

```php
Kirby::plugin('my/plugin', [
    'hooks' => [
        'system.loadPlugins:after' => function () {
            $router = new BlogRouter(page('blog'));

            kirby()->extend([
                'routes' => [
                    $router->getRoute()
                ]
            ], kirby()->plugin('my/plugin'));
        }
    ]
]);
```

**Comment by lukasbestle** [comment]
@hdodov Does the example I wrote for you cover your use-case?

**Comment by yandodov** [comment]
@lukasbestle sorry for the late reply. Yes, that does it! So is that the correct way to extend configuration that depends on other configuration, e.g:

```php
App::plugin('my/plugin', [
	'options' => [
		'pages' => ['blog', 'foo']
	],
	'hooks' => [
		'system.loadPlugins:after' => function () {
			$routes = [];

			foreach (option('my.plugin.pages') as $slug) {
				$routes[] = new BlogRouter($slug);
			}

			kirby()->extend([
				'routes' => $routes
			], kirby()->plugin('my/plugin'));
		}
	]
]);
```

If yes, please, add it to the docs for future reference. ♥

**Comment by lukasbestle** [comment]
Good point! I have added this to the docs [here](https://getkirby.com/docs/guide/plugins/plugin-basics#extensions__dynamic-extensions) and [here](https://getkirby.com/docs/reference/plugins/hooks/system-loadplugins-after). ✅
