### ISSUE TITLE
[Panel] Overflow issue with long filenames

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#254]
<img width="1239" alt="screen shot 2018-03-18 at 14 02 35" src="https://user-images.githubusercontent.com/24532/37589756-7a833d30-2b66-11e8-992d-37859a2403ef.png">

<img width="836" alt="screen shot 2018-03-18 at 14 32 40" src="https://user-images.githubusercontent.com/24532/37589836-a81fda8c-2b66-11e8-9f41-63a444ef1005.png">

**Comment by ralfgoeke** [comment]
just stumbled over another place where this bug appears. (in Firefox)

![long-filename-bug](https://user-images.githubusercontent.com/6228942/37708268-41d6c2e4-2d06-11e8-9acd-946bd91c6d5a.png)

**Comment by bastianallgeier** [comment]
✅
