### ISSUE TITLE
Nested plugin options don't overwrite fallback

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2540]
**Describe the bug**  
When setting plugin options via nested arrays, `option()` always returns the fallback value .

**To Reproduce** 

Step 1: Add a plugin with options:
```php
<?php
Kirby::plugin('my/plugin', [
  'options' => [
    'myOption' => 2000,
  ]
]);
```
Step 2: Set the option in `config.php` by using an array:
```php
'my.plugin' => [
  'myOption' => 1000,
],
```
Step 3: Return the option anywhere:
```php
<?php dump(option('my.plugin.myOption')) ?>
```

**Expected behavior**  
Kirby should return the option value set in the config: `1000`. Instead it will return `2000`.

**Kirby Version**  
3.3.5

**Comment by afbora** [comment]
I guess same issue with #2343

**Comment by medienbaecker** [comment]
@afbora You are right. The issue didn't contain a single word I used for my search 😅

**Comment by afbora** [comment]
@medienbaecker Almost all in my mind 😅

**Comment by texnixe** [comment]
I didn't find it either before I asked @medienbaecker to create an issue...
