### ISSUE TITLE
go() function conflict with swoole

### ISSUE THREAD

**Issue by crnogaj** [getkirby/kirby#2548]
Kirby won't start if swoole PHP module is active because of `go()` function conflict.
Full error looks like this:
`PHP Fatal error:  Cannot redeclare go() in /var/www/html/kirby/kirby/config/helpers.php on line 221`

I assume there is a small chance to change function name but it would be useful to mention this in official docs.

**Comment by lukasbestle** [comment]
We've had the same issue with our `dump()` helper (which conflicts with Symfony's VarDumper). You can read more about this here: https://github.com/getkirby/kirby/pull/2341

I have added a paragraph to our [Troubleshooting guide](https://getkirby.com/docs/guide/troubleshooting/installation#php-cannot-redeclare-error).
