### ISSUE TITLE
Create root-relative URLs

### ISSUE THREAD

**Issue by SonicHedgehog** [getkirby/kirby#255]
Currently, `$page->url()` generates an absolute URL like `http://localhost:8000/about`. It would be nice if you could create root-relative URLs like `/about`. For example, [Rails provides this with its `_url` and `_path` methods](http://stackoverflow.com/a/4511800).

This would make accessing a development server using [ngrok](https://ngrok.com) or using a different device on the same network a lot easier.

**Comment by bastianallgeier** [comment]
You can already set that in your config with:

```php
c::set('url', '/');
```
But for individual page urls you can do. `'/' . $page->uri()`

**Comment by SonicHedgehog** [comment]
Thanks, that’s working great. I’d suggest adding that option to [the docs](http://getkirby.com/docs/advanced/options).

**Comment by Madeck** [comment]
@bastianallgeier, I have had issues with `c::set('url', '/');`, as all links would forgo the "http://example.com/" part, but the following seemed to work:

`c::set('url', './');`

Hope this helps!
