### ISSUE TITLE
Nested structure fields won't save unless you click on each "OK" button

### ISSUE THREAD

**Issue by jnetzlr** [getkirby/kirby#2550]
Having multiple structure fields inside each other won't save unless you click on each "OK" button in order.

Shortcut cmd+s works most of the time but sometimes it just closes the structure field and there is no save button for the page. In this scenario you have to reopen the structure field and click on "OK" and then the save button will appear.

**Comment by afbora** [comment]
I had tested this issue before and was reproduced but I couldn't unable to reproduce the issue in 3.6.0-Beta.1.

**Comment by afbora** [comment]
✅
