### ISSUE TITLE
Markdown and Smartypants components accept `$text = null`, but underlying classes don't

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2551]
The `Markdown` and `Smartypants` classes are more strict about their `parse()` method signature than the [components](https://github.com/getkirby/kirby/blob/3.3.5/config/components.php#L114-L157), which also accept `null` for the `$text` argument.

We should check what the reason is why the components accept `null`. If there is a valid reason, either the underlying classes should accept `null` as well (potentially not very clean) or the default value if `$text` is not given should be an empty string instead of `null`.

---

Related issue: https://github.com/getkirby/kql/issues/9

**Comment by bastianallgeier** [comment]
I already fixed this a while ago.
