### ISSUE TITLE
"this.load is not a function" when using Parcel for section plugin development

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2552]
**Describe the bug**  
When you initially load the panel and your custom section within it - everything works. However, when you make a change in your section's source code and Parcel re-compiles it - HMR kicks in, replaces the section, and you get this error:

![image](https://user-images.githubusercontent.com/5570098/78103092-a2470800-73f4-11ea-82e6-cfb83512bf1a.png)

**To Reproduce**  
1. Set up [the pluginkit](https://github.com/getkirby/pluginkit/tree/4-panel)
2. Create a section as per [the Kirby docs](https://getkirby.com/docs/reference/plugins/extensions/sections#vue-component__section-data)
3. `npm run dev`
4. Load the section plugin in the panel
5. Make a change in the source
6. See the error

Here's my section component:

```vue
<template>
  <section>
    <k-headline>{{ headline }}</k-headline>
  </section>
</template>

<script>
export default {
  data: () => {
    return {
      headline: null
    }
  },
  created () {
    this.load().then(response => {
      this.headline = response.headline
    })
  }
}
</script>
```

**Expected behavior**  
Perhaps sections could receive the `response` as a prop, instead of having to `load().then()`?
If `response === null`, the API call is in progress. If it's not `null` - it has returned.

**Kirby Version**  
3.3.5

**Comment by bastianallgeier** [comment]
Parcel is no longer a viable option. We suggest the new kirbyup setup by @johannschopplich

**Comment by johannschopplich** [comment]
@hdodov https://github.com/johannschopplich/kirbyup#usage
