### ISSUE TITLE
Panel: Text Field loses content written while a save is in progress

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2554]
**Describe the bug**  
In the Panel, if you're writing content in a text field, save the page (Command-S), and keep writing, the content you write _while_ the save is in progress will likely be lost.

Once the save action is complete, the text field seemingly reverts to what was actually saved (i.e.: as it existed when you hit Command-S).

**To Reproduce**  
1. Go to a page with a text field
2. Write something like "The quick brown"
3. Save the page with a keyboard shortcut (Command-S)
4. Continue writing, such as "jumped over the lazy dog"
5. If the save took long enough, at some point the text field will have reverted to "The quick brown"

In the screen recording below, you can see that the "fox" effectively disappears.

**Expected behavior**  
Fields modified _while_ the save is occurring should _not_ be overwritten when the save is complete.

**Screenshots**  
Screen recording:
[Screen Recording 2020-04-01 at 11.04.15 AM.zip](https://github.com/getkirby/kirby/files/4416893/Screen.Recording.2020-04-01.at.11.04.15.AM.zip)

**Kirby Version**  
`3.3.5`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.1 (15609.1.20.111.8)

**Comment by distantnative** [comment]
I think the fail-safe way would be to disable interactions while the Panel is in any in-between loading state.

**Comment by neildaniels** [comment]
Yes, that'd be fail-safe, but I know most of our editors instinctively Command-S while they're writing. If the Panel was completely locked out for a second, it'd be incredibly disruptive for them.

Sometimes the save latency can last for a couple seconds. If the Panel was locked during that time, it'll feel like a very primitive web interface.

**Comment by distantnative** [comment]
A couple of seconds? That sounds like something else is wrong

**Comment by lukasbestle** [comment]
Well, on slow connections this can happen. I've seen multi-second latency when travelling in good old Deutsche Bahn trains.

But I agree with @distantnative that we would probably need to lock the editing interface during save operations. Otherwise changes that are made by hooks won't be reflected in the local state of the Panel and you would be overwriting those changes again by continuing to type. By waiting until the state is updated, those kinds of race-conditions can be prevented.

**Comment by distantnative** [comment]
Ok yes horrible connections can of course result in this times. But it sounded like @neildaniels experiences these on a common basis.

**Comment by lukasbestle** [comment]
Yeah, that should never happen of course.

**Comment by neildaniels** [comment]
I think it really depends on the Blueprint and server load. For the most trivial Blueprints, they'll usually save in under a second. But for more complex Blueprints, slowness is almost inevitable.

For example, if the Blueprint has a `tags`/`multiselect` field that's powered by a `query:` then every save response needs to:
1. Parse the query
2. Fetch the pages in that query (or structures)
3. Fetch the text and value for each option (e.g. page title and id)

If there's a few of `tags`, `multiselect`, `select`, `checkboxes`, etc. then a "simple" save can easily become a very heavy call.

To add onto that, there are other things that add time:
- If you're viewing a multi-lang, it might have to try and load the selected language _and_ default (even for the parent pages, to get the breadcrumbs right).
- `page.update:before` and `page.update:after` hooks need to be executed.

Obviously there's lot of variability to all of this, but I don't think the assumption should be that "saving a page in the Panel is fast". I think it's only "reliably" fast if you have a good connection, simple Blueprints, only a few plugins, and a relatively fast server.

**Comment by distantnative** [comment]
Fair point. I wasn't trying to argue for relying on a fast safe - it should work for fast and slow scenarios. I was just surprised to hear that it takes so long for you, but valid points.

**Comment by lukasbestle** [comment]
@neildaniels Given the constraints that sometimes slow saving is inevitable, would you be fine with the UI being read-only while the save operation is in progress? As I described above, there's probably no way around that to ensure that no data gets lost.

**Comment by neildaniels** [comment]
When it comes down to it: yes, locking the UI while the save is happening is more ideal than having data loss.

But, I think the effort would be _much better_ spent on keeping track of which fields have been **modified during the save operation** and skip them during the content "refresh." That solves the data loss and keeps the Panel fully interactive.

**Comment by lukasbestle** [comment]
But what would happen if exactly this field was modified by a hook in the meantime?

**Comment by neildaniels** [comment]
Assume there was a hook that appended `@` to the field value.

Here is the sequence of events today: 
0. Assume a text field with an empty value (e.g. `''`) on a completely saved page.
1. Type `The quick brown fox` [orange save bar appears]
  a. Clicking "Revert" at this point would restore the value to `''`
2. Save the page [orange save bar still visible, but not clickable]
3. Continue typing `jumped over` [orange save bar still visible and still not clickable]
4. Saving completes. Panel field reverts to `The quick brown fox@`. [orange save bar disappears]
5. On disk, the value is `The quick brown fox@`

What I'm proposing is:
0. Assume a text field with an empty value (e.g. `''`) on a completely saved page.
1. Type `The quick brown fox` [orange save bar appears]
  a. Clicking "Revert" at this point would restore the value to `''`
2. Save the page [orange save bar still visible, but not clickable]
3. Continue typing `jumped over` [orange save bar still visible]
4. Saving completes. Panel field **remains as** `The quick brown fox jumped over`. [orange save bar visible and clickable]
  a. Clicking "Revert" would cause the Panel field to change to `The quick brown fox@`
5. On disk, the value is `The quick brown fox@` at this point.
6. The orange save bar is still visible at this point, with the field being `The quick brown fox jumped over`.
7. Saving the page again, but make don't keep typing.
8. Saving completes. The field updates to `The quick brown fox jumped over@`. [orange save bar disappears]
9. On disk, the value is `The quick brown fox jumped over@`.

**Comment by distantnative** [comment]
But editors would not even know that on disk it is `The quick brown fox@` and they could back to this clicking Revert. They would think clicking revert gets them `The quick brown fox` while they already have typed `The quick brown fox jumped over`.

**Comment by nilshoerrmann** [comment]
Ignoring the side effects, I just wanted to point out that you are throwing away the advantages of a client-side app by just blockIng interactions on save. That‘s like classic server-side rendered web, waiting for the page to reload after a post.

@neildaniels proposes a more natural workflow that is less interrupting.

**Comment by neildaniels** [comment]
@distantnative  Sure. But I think that's more of a labeling issue than anything. Kirby's "Revert" is (today even) akin to a typical editor's "Revert to Saved" command.

<img width="276" alt="Screen Shot 2020-04-05 at 1 19 59 AM" src="https://user-images.githubusercontent.com/417182/78470126-c1d37e80-76db-11ea-9a12-0183c325efc7.png">

The side effects of a page action (such as a `page.update` hook) _are_ part of the saving process. Even today, "Revert" _always_ goes back to a post-hook version of a page.

(I think the exact intricacies of the hook scenario are more academic than anything. I'm struggling to think of a realistic hook scenario where the proposed behavior would have grave consequences. Usually these are minor things like doing text transforms. They'll be re-applied on a final save anyways.)

**Comment by lukasbestle** [comment]
> Usually these are minor things like doing text transforms. They'll be re-applied on a final save anyways.

That's correct. To be honest, I also can't make up a scenario where the modifications made by the hook are needed for further editing. After all the editor could have not saved the page and continued editing to save everything at the end.

Also the user sees that the page is still being saved by the "unsaved changes" bar still being there. If the user wants to wait for the save operation, they can wait until the "unsaved changes" bar disappears.

The only other cause for updates in the meantime – other users – are not an issue either as we have content locking. The only thing we would need to verify is that the lock is not cleared for a moment while the page is being saved. The ideal locking implementation would work like this:

1. The user edits a page. The Panel locks that page to that user.
2. The user hits "Save". The lock is still kept.
3. The backend updates the content and confirms the save to the Panel.
4. Only now that the save was confirmed, the Panel releases the lock. If another edit occurred in the meantime, the Panel would *not* release the lock. This ensures that at no point another user can get a lock themselves when the original user continues editing.

@distantnative Does the current implementation work that way? Or is the lock already released when saving?

Regarding this issue I'd say that we should remove that the Panel reloads the content from the backend after a save, which would make the Panel behave exactly like @neildaniels describes.

**Comment by neildaniels** [comment]
> Regarding this issue I'd say that we should remove that the Panel reloads the content from the backend after a save, which would make the Panel behave exactly like @neildaniels describes.

To be clear, I'm fine with the Panel "reloading" content after a save—just not when there are pending edits. In the contrived `@` example, the `@` would show up after a save was issue and no further edits were made.

Originally, I thought _only_ skipping the reloads for the modified fields was important. Now, I think skipping the entire "reload" if there are _any_ pending modifications would be totally acceptable. It's not _as_ "smart", but would probably be easier to engineer and easier to reason about as a user.

**Comment by lukasbestle** [comment]
> To be clear, I'm fine with the Panel "reloading" content after a save—just not when there are pending edits.

You are right! :)

**Comment by neildaniels** [comment]
Not stale.

**Comment by lukasbestle** [comment]
After reading through this again, I think we should do it like Neil and Nils proposed.

## Summary

When the user hits "Save", the following would happen with the new implementation:

1. The Panel sends the content to the backend.
2. The backend runs all hooks and stores the content in the content file. The lock for the current user is kept for now.
3. The backend returns the new content to the Panel frontend.
4. The Panel stores that new content in an internal, separate "backend state".
5. The Panel checks for each field if it was modified since the "Save" button was hit.
  a. If no, the field is updated with the new content from the backend (from the separate internal "backend state").
  b. If yes, the field content is *not* overridden and the user-modified content is kept.
6. If any field was modified (= if any field hit number 5b.), the changes bar and the lock are kept. Otherwise (if all fields have been set to the "backend state"), the changes bar is hidden and the Panel sends a request to the backend to release the lock.

Does that sound right?

**Comment by distantnative** [comment]
Honestly this sounds like quite the headache to implement - any additional store has proven always to be quite the nightmare to handle. I know some might hate this, but can't we just disable all fields until the Panel received the response from the backend?

**Comment by lukasbestle** [comment]
We can do this, but I agree with Nils that the UX of that wouldn't be good. In basically every app you can hit save and keep typing.

Regarding the extra store: The store can be thrown away after step 6. It's just needed during the content reloading from the backend.

**Comment by distantnative** [comment]
Yes, but it also has a reason why this hasn't been touch for more than 2 years: it's a lot of pain, a lot of edge cases, a lot of things that can go wrong for a rather edge cases. To be honest, I don't see the benefit paying off all the costs for such a solution.
