### ISSUE TITLE
Change title dialog closes on mouseup

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2557]
**Describe the bug**  
When you select text in the title field and you release the mouse button while out of the dialog, the dialog closes. This is the wrong behavior:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5570098/78423787-8603cf00-7671-11ea-86cd-c8a23c17746a.gif)

This also happens on other dialog boxes as well, e.g. the Duplicate page dialog. I think it's an issue with the dialog component itself.

**Expected behavior**  
The text should be selected and the dialog should remain open.

**Kirby Version**  
3.3.5

**Comment by distantnative** [comment]
✅ fix included in refactored dialogs - will be part of 3.4
