### ISSUE TITLE
Objects updated from controller are outdated in templates/snippets

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2559]
**Describe the bug**  

If an object is updated from a controller:

```php
return function($kirby, $page) {
    $kirby->impersonate('kirby');
    $page = $page->update(['test' => uniqid()]);

    return [
        'page' => $page
    ];
};
```

the updated `$page` is not available in the template and in snippets as Kirby [overrides the returned object with the original `$page`](https://github.com/getkirby/kirby/blob/3.3.5/src/Cms/Page.php#L347).

**Expected behavior**  

The updated `$page` should be provided to the template and snippet. It would be awesome if this would automatically happen even if `$page` is not manually returned from the controller.

**Kirby Version**  

3.3.5

**Additional context**  

Original discussion in https://github.com/getkirby/kirby/issues/2555.

**Comment by bastianallgeier** [comment]
✅
