### ISSUE TITLE
Plugin option array is flattened

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2570]
**Describe the bug**  

When you specify options for a plugin, you do it with an array:

```php
App::plugin('me/plugin', [
	'options' => [
		'foo' => 1,
		'bar' => 'baz'
	]
]);
```

When users overwrite those options in their `config.php`, I expect them to provide an array as well:

```php
return [
	'my.plugin' => [
		'foo' => 64
	]
];
```

However, that wouldn't work. The final options will be:

```php
[
	'me.plugin.foo' => 1,
	'me.plugin.bar' => 'baz',
	'me.plugin' => [
		'foo' => 64
	]
]
```

If I were to call `option('me.plugin')`, I'd get an array containing only `'foo' => 64`. The default option `bar` that was defined in the plugin config will be left out. So even though I have `me.plugin.bar` **nowhere** in my codebase, that's the final option that Kirby loads and I'd have to make checks for it instead. That's confusing.

The docs themselves [show](https://getkirby.com/docs/reference/system/options/cache) the use of arrays. And it makes sense - arrays are cool and we should use them. It's way more easier to do this:

```php
[
	'me.plugin' => [
		'foo' => 64,
		'bar' => 'baz',
		'hello' => 'world'
	]
]
```

...rather than this:

```php
[
	'me.plugin.foo' => 1,
	'me.plugin.bar' => 'baz',
	'me.plugin.hello' => 'world'
]
```

Translation variables have the same problem too. I think it would be much better if Kirby used one format and stuck with it. I'm a very actively working with Kirby and even I get often confused...

# Proposal

Kirby uses the `vendor/plugin-name` format everywhere. I think options should follow. You have `App::plugin('vendor/name', ...)`, you have `panel.plugin('vendor/name', ...)`, the plugin has `vendor/name` in Packagist... Doesn't it make sense to have:

```php
return [
	'vendor/name' => [
		'foo' => 1,
		'bar' => 'baz'
	]
];
```

...for options as well?

I know this is probably the "expected" behavior, but this lack of consistency is confusing and leads to fragile code. I can't see how it helps either plugin developers _or_ plugin users.

It would be much simpler if everyone everywhere defines options with arrays and then Kirby recursively merges them one on top of the other.

**Kirby Version**  
3.3.5

**Comment by afbora** [comment]
Duplicated https://github.com/getkirby/kirby/issues/2343
