### ISSUE TITLE
Self-check for blocked HTTP methods

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2573]
The issue where specific HTTP methods (like `PATCH` or `DELETE`) are blocked by the server or a client proxy has now occurred the third time I know of, and each time it was pretty hard to debug this.

I propose that there should be a self-check in the Panel that verifies that each method works. It could work like this:

1. Add an API route `/api/system/method-test` that accepts any HTTP method and just returns `HTTP 200` with the request method printed back in the body.
2. When the Panel is loaded, next to querying `GET /api/system`, also send requests to `PATCH /api/system/method-test`, `PUT /api/system/method-test` and `DELETE /api/system/method-test`.
3. If any of those requests returns a status other than `HTTP 200` or if the requested method doesn't match the output from the route, a modal error message should be triggered in the UI:

> The following HTTP methods are not supported by your server: [LIST OF FAILED METHODS]

Ideally there would be link to our [troubleshooting guide](https://getkirby.com/docs/guide/troubleshooting/panel#panel-error-messages__the-following-http-methods-are-not-supported-by-your-server) with more information on how to debug this.

**Comment by distantnative** [comment]
What if the API isn't available due to some other problems? Wouldn't the error message be misleading?

But such a API self test in general would be great, I think!

**Comment by lukasbestle** [comment]
@distantnative We also have the request to `GET /system` that would still run in parallel. If that fails as well, the error message could be a different one. If the `GET` request succeeds but any other request fails, we know it's the request method issue.

**Comment by lukasbestle** [comment]
Also see: https://forum.getkirby.com/t/edits-made-in-kirby-panel-not-saving-persisting/17854/19?u=lukasbestle

**Comment by bastianallgeier** [comment]
I don't think we need the self-test any longer. Our own API client uses the method override now by default, because those errors kept on creeping up so often and it's unfortunately more stable to use POST and pretend to be DELETE or PATCH. I guess this is why rails and other frameworks do the same.

**Comment by lukasbestle** [comment]
@bastianallgeier So we only use `GET` and `POST` now?

**Comment by distantnative** [comment]
@lukasbestle Yes

```js
    // adapt headers for all non-GET and nob-POST methods
    if (options.method !== 'GET' && options.method !== 'POST') {
      options.headers["x-http-method-override"] = options.method;
      options.method = 'POST';
    }
```
