### ISSUE TITLE
Using `$page->blueprint()->sections()` in a hook breaks the frontend

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2575]
**Describe the bug**  
Using `$page->blueprint()->sections()` in e.g. a `route:after` hook breaks all kind of things in the frontend. For example it corrupts the translations and corrupts the page's `children()`.

**To Reproduce**  
Add something like this to the `site/config/config.php`:
```php
'hooks' => [
  'route:after' => function ($route, $path, $method, $result) {
    $uid = explode('/', $path);
    $uid = end($uid);
    $uid = str_replace('+', '/', $uid);
    $page = kirby()->page($uid);
    if (!$page) {
      $page = site()->homePage();
    }
    $test = $page->blueprint()->sections();
  }
]
```
All I'm doing is putting the sections of the page blueprint in to a `$test` variable. Somehow it breaks all kinds of stuff instead:

![hook-bug](https://user-images.githubusercontent.com/7975568/79321749-1b258400-7f0c-11ea-9fd2-e77a80440e0b.gif)

**Expected behavior**  
Nothing but a variable with the blueprint sections.

**Kirby Version**  
3.3.5

**Additional context**  
I made a plainkit with a simple plugin so you can test the issue: [Hook-Bug.zip](https://github.com/getkirby/kirby/files/4480251/Hook-Bug.zip)

**Comment by afbora** [comment]
After two years 😱 I've tracked the issue and I've an clue about the issue.

When call the `$page->blueprint()->sections()` code, following line running and broke the translation.

````php
$content  = $this->model->content()->toArray();
````
https://github.com/getkirby/kirby/blob/3.6.3/config/sections/fields.php#L15

### Possible solution/idea

As workaround I've fixed the issue with passing current language. I'm not sure about stable solution but this may be give you an idea about solution.

````php
$lang     = $this->model->kirby()->language() ?? null;
$content  = $this->model->content($lang)->toArray();
````

**Comment by bastianallgeier** [comment]
@afbora you are a genius :)

**Comment by distantnative** [comment]
Sounds indeed like a good fix. Can we get it in a PR? Ideally we would be able to come up with a unit test that reproduces the buggy behavior before and passes with the fix, but maybe that's hard to do.

**Comment by bastianallgeier** [comment]
Looking at it again, it should be: 

```php
$lang = $this->model->kirby()->languageCode();
$content = $this->model->content($lang)->toArray();
```

**Comment by afbora** [comment]
Do you want to me create a PR with this solution?

**Comment by bastianallgeier** [comment]
✅
