### ISSUE TITLE
Untranslatable fields are overly sensitive to Blueprint field's key capitalization

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2577]
**Describe the bug**  
Programmatically updating a model with untranslatable fields can lead to unwanted results if your code specifies a different key case from those in a Blueprint.

**To Reproduce**  
1. Start with a Blueprint with a field like:
```yaml
SOMEID:
  type: text
  translate: false
```
2. Programmatically create a page with content resembling:
```php
[
  'someid' => 'myidentifer'
]
```
3. Programmatically update the content for a non-default language
```php
$page->update(`['foo' => 'bar'], 'fr-fr);
```
4. The resulting translation's content will resemble:
```php
[
  'someid' => 'myidentifier',
  'foo' => 'bar',
  'SOMEID' => null,
]
```

**Expected behavior** 
I would expect the resulting content to _not_ include `'myidentifier'`. 
```php
[
  'someid' => null,
  'foo' => 'bar',
]
```

**Kirby Version**  
`3.3.5`

**Comment by bastianallgeier** [comment]
✅
