### ISSUE TITLE
String template language as a separate function

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#258]
You wrote on Slack that the new string template language could possibly be used in Kirbytext tags like this:

```text
(image: {{ site.find("projects").children.first.images.shuffle.first.url }})
```

As an addition to that, I think it would be really great if we could use the string template language anywhere in our plugins.

**Something like this:**

```php
echo template::language('site.find("projects").children.first.images.shuffle.first.url');
```

A real example of where it could be used is here: https://github.com/jenstornell/kirby-shortcode

There are probably more cases where a function like this may be helpful.

**Comment by bastianallgeier** [comment]
That is already possible! You can use the Tempura class in your own plugins like this: 

```php
use Kirby\Cms\Tempura;

$template = new Tempura('{{ site.find("projects").children.first.url }}', [
  'site' => site(),
]);

echo $template->parse();
```
You have to pass anything in the array that should be usable in the query. 

If you don't need the template parser you can run a simple string query like this:

```php
use Kirby\Cms\Query;

$query= new Query('site.find("projects").children.first.url', [
  'site' => site(),
]);

var_dump($query->result());
```

We will probably move this over to the Str class at a later point to simplify it.

```php
Str::template()
Str::query()
```

**Comment by jenstornell** [comment]
How awesome! All of it. ☺

Maybe just add it to the docs somewhere.
