### ISSUE TITLE
.png brakes files list in page

### ISSUE THREAD

**Issue by w4nderlust** [getkirby/kirby#258]
If i upload a .png image the visualization of the files brakes. I attach a visual example.

![schermata 2015-06-22 alle 18 20 52](https://cloud.githubusercontent.com/assets/349256/8286723/796a5e30-190b-11e5-81db-7ff77571589d.png)

**Comment by distantnative** [comment]
Looks very similar to this problem, maybe the same solution helps? https://github.com/getkirby/panel/issues/482

**Comment by w4nderlust** [comment]
You were right, updating to the newer version of php (5.6.9) works just fine, thank you.
