### ISSUE TITLE
Expose user files via the account route

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2580]
**Describe the bug**  
Currently, if a user role doesn't have access to the `users` (permissions => access => `users: false`) view, they cannot access files uploaded to their account, because these files live under the `panel/users/userid/files/` URL, not the `account` URL.

**To Reproduce**  
1. Create a user role files with access to users view limited and a files section
2. Go to user account and upload a file
3. Click on file to access it
4. See `You are not allowed to access this part of the panel` error message

**Expected behavior**  
Users should be able to view files uploaded to their account even if they don't have general access to the Users view.

**Kirby Version**  
3.3.5

I thought I'd come across this before, but couldn't find any related issue, so forgive me if this is a duplicate.

**Comment by bastianallgeier** [comment]
✅
