### ISSUE TITLE
Nested structure card does not close / update when moving to next/prev parent structure entry.

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#2583]
**Describe the bug**  
Let's say you have a structure field nested within a structure field and have the parent as well as the child open for editing. If you then, on the parent structure use the next/prev arrows to slide to the parent's next/prev structure entry, the opened child entry stays in place, even though the associated structure entry is not opened anymore.

That means you now have a (parent) structure entry open, which display a (different parent's) child entry, which is potentially dangerous as users might not be aware of that bug and then make incorrect edits.

**Expected behavior**
I guess the most user friendly behavior would be to slide to the next/prev parent structure entry and display that with all child entries closed. The question is, what happens if you have unsaved changes in the open child entry? Maybe in this case the prev/next arrows get disabled until the user either saved or cancelled his child entry edits?

**Kirby Version**  
3.3.5

**Desktop (please complete the following information):**  
 - OS: macOS 10.13.6
 - Browser: Chrome, but I guess any?
 - Version: 75

**Comment by distantnative** [comment]
✅ This will be fixed in 3.4 (mainly cause editing structure fields will have a different UI)
