### ISSUE TITLE
Number field accepts letters in Firefox (but doesn't save them)

### ISSUE THREAD

**Issue by hannesherold** [getkirby/kirby#2594]
**Describe the bug**  
In Firefox, I can enter letters into the number field. After clicking "save", the letters remain in the number field. However, they are not being saved. There's no entry in the .txt file and the string disappears on page refresh.

No such issues in Chrome, though. Here the number field accepts digits only (as expected).

**To Reproduce**  

1. Install fresh plainkit and create a standard number field in the blueprint.

```
title: Default Page
preset: page
fields:
  number:
    type: number
```

2. Use Firefox Browser, login to the panel, navigate to the page (or create new) and enter letters into number field.

**Expected behavior**  
Number field should accept digits only on input.

**Kirby Version**  
3.3.6

**Console output**  
None. But when I open the inspector on the number field, the page gets locked and the orange save-bar appears.

**Desktop (please complete the following information):**  
 - OS: Windows 8.1
 - Browser: Firefox
 - Version: 75.0 (latest)

**Comment by distantnative** [comment]
We are using the native `<input type="number" />` element. This is a Firefox issue: https://stackoverflow.com/questions/49923588/input-type-number-with-pattern-0-9-allows-letters-in-firefox

There are hacks to align the behavior to other browsers: https://blogs.sap.com/2019/01/16/making-number-input-accept-only-numbers-in-edgefirefox/

My opinion is that these hacks are not really worth it.
Opinions, @lukasbestle @texnixe?

**Comment by lukasbestle** [comment]
I agree that we shouldn’t use too many hacks. It is fine that people can enter non-numeric characters.

However I‘d say the number field should at least behave like other fields on validation: It should prevent saving if the input is invalid. The current behavior is quite confusing.

**Comment by texnixe** [comment]
I agree with @lukasbestle.

**Comment by distantnative** [comment]
Ok I had a first look (I do agree with you) at it and this will be a bit tricky:
Firefox keeps firing the `input` event whenever something is typed, but as soon as alphabetic characters are entered, the fired value is empty - which makes it hard to distinguish from when the input actually is empty.

**Comment by bastianallgeier** [comment]
Ugh, I agree that it would be perfect to validate that. But if the number field does not send the value to the server, we can't really handle it at all. I don't want to add some hacky validation to the frontend part.

**Comment by bastianallgeier** [comment]
We are about to remove immediate inline validation anyway with one of the next releases. It leads to too much confusion.

**Comment by distantnative** [comment]
Given that we are going to remove the immediate inline validation anyway and that any short-term fix would be too complicated IMO, I will close this issue.
