### ISSUE TITLE
Panel: Notifications missing

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#26]
I'm not sure how it's intended to work but on many places I get a message that something is done successfully, which is nice.

In the user view when I upload a picture for example, I don't get the message "The picture was successfully uploaded". I was waiting for it, but it did not appear. Would it be good to have a message like that?

There are more places, I think, where a message does not appear.

**Comment by distantnative** [comment]
@jenstornell If you find more places, please just add them in a comment and I will try to keep this list updated:

- [ ] Avatar uploaded
