### ISSUE TITLE
Update Toolkit submodule

### ISSUE THREAD

**Issue by JonasDoebertin** [getkirby/kirby#260]
The toolkit submodule has commits to the master branch since the commit that is referenced as the submodule currently. This leads to a dirty `kirby` submodule when using:

```bash
git submodule foreach --recursive git checkout master
git submodule foreach --recursive git pull
```
```diff
kirby

- Subproject commit d806fbd23684fafbcf73c5ce532b85c3e277dc98
+ Subproject commit 411a62308329b3f4ac68789cbab80767ad184da6-dirty
```

So, could you update the toolkit submodule?

**Comment by lukasbestle** [comment]
Updating the submodules for every commit to the Toolkit, Panel and the core does not make much sense, as new features in the Toolkit first have to be tested with the core.

You shouldn't use the commands you posted but instead the following:

```sh
git submodule update --init --recursive
```

This updates the submodules to the currently referenced commit.

**Comment by JonasDoebertin** [comment]
> Updating the submodules for every commit to the Toolkit, Panel and the core does not make much sense, as new features in the Toolkit first have to be tested with the core.

Isn't that what's the `develop` branch is for? Historically, everything on `master` is production ready.

> You shouldn't use the commands you posted but instead the following […] This updates the submodules to the currently referenced commit.

I have a repository with `panel` and `kirby` as direct submodules. Initializing them (recursively) isn't the problem. Updating these is the problem. How do I update both main submodules and the "sub-submodule" accordingly (so the `toolkit` submodule of the `kirby` submodule is checked out on the referenced commit within `kirby` instead of the latest available commit)?

**Comment by lukasbestle** [comment]
> Isn't that what's the `develop` branch is for? Historically, everything on `master` is production ready.

The `master` branch of the Toolkit contains stable *Toolkit* code. But that's not necessarily also stable *Kirby* code.

> How do I update both main submodules and the "sub-submodule" accordingly?

Ah, alright. Untested, but the following should work:

```bash
git submodule foreach git checkout master
git submodule foreach git pull
git submodule update --init --recursive
```

The first two commands only apply to the `kirby` and `panel` submodules, the third to their dependencies.

**Comment by JonasDoebertin** [comment]
Well, that leaves me with this output (from the last command):

```
Submodule path 'kirby': checked out 'd806fbd23684fafbcf73c5ce532b85c3e277dc98'
Submodule path 'panel': checked out 'b828f24ea7e009cd12442232f1600e70fbf58c6d'
```

This is far away from the current release.

**Comment by JonasDoebertin** [comment]
Ok, I guess I found the solution:

```bash
git submodule foreach git checkout master
git submodule foreach git pull
git commit -a -m "Update submodules"
git submodule update --init --recursive
```

The trick is to do a commit before (re-) initializing the submodules. Seems to work fine this way.

**Comment by lukasbestle** [comment]
Oh yes, that's true. Otherwise `git` reverses the update to the upper-level repos immediately. :D
Glad you found a solution. :)

**Comment by JonasDoebertin** [comment]
Thanks a lot for your help!
