### ISSUE TITLE
Umlauts in email field cause 'The JSON response from the API could not be parsed'

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2600]
**Describe the bug**  
When you try to enter a domain with umlauts in the user email field, it will throw an error.

**To Reproduce**  
1. Go to panel
2. edit an user
3. set its email address to one with an umlaut like `test@exämple.com`
4. you get an error on saving:

```
The JSON response from the API could not be parsed. Please check your API connection.
```

**Expected behavior**  
Changes saved without an error.

**Kirby Version**  
3.3.6

**Console output**  
![grafik](https://user-images.githubusercontent.com/6271057/81024460-cbcfd500-8e73-11ea-8f17-3951cdc8ecd8.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Firefox
 - Version: 75

**Additional context**  
Related issue which was fixed in the past: #1895

**Comment by GiantCrocodile** [comment]
When I did refresh the page, I found out that the changes were saved, regardless of the error message. On log out, I got an error that user.role (or something like that) is undefined. Logging in with the new email address fails due to:

```
code: 404
details: Array []
exception: "Kirby\\Exception\\NotFoundException"
file: "/kirby/kirby/src/Cms/Auth.php"
key: "error.user.notFound"
line: 269
message: "Der Benutzer \"test@exämple.com\" wurde nicht gefunden"
route: "auth/login"
status: "error"
```

In the `index.php` of the user the email address is correctly stored. Changing the email address in the plain file fixes the issue with the log in.

**Comment by bastianallgeier** [comment]
✅
