### ISSUE TITLE
Firefox 76+: Cookie “kirby_session” will be soon rejected ...

### ISSUE THREAD

**Issue by WebMechanic** [getkirby/kirby#2601]
This is not an active bug, but a "heads up" notice I recently ran into.
**Describe the bug**  
Firefox Developer (76) and Nightly (77) display a warning if one logs into the Panel, see **Console output** below.
This indicates that login into the Panel might be broken in upcoming versions of Firefox.
_It might only affect ``http`` connections._

**To Reproduce**  
1. launch Firefox Developer or Nightly Edition (currently on version 76/77)
2. open DevTools (F12), activate Console and **enable "Warnings"**
3. navigate to a Kirby panel login screen and login over **http** (e.g. localhost)
4. See warning in browser console

**Expected behavior**  
no warning :)

**Kirby Version**  
3.3.4

**Console output**  
> Cookie “kirby_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

**Desktop (please complete the following information):**  
 - OS: Win10-pro
 - Browser: Firefox
 - Version: 76 and 77

**Comment by WebMechanic** [comment]
EDITED post (accidently hit Enter)

**Comment by lukasbestle** [comment]
@WebMechanic Thanks for the heads-up! 👍
We will fix this immediately to make sure that it won't cause problems later. It's also the right thing to do anyway to use `SameSite`.

**Comment by bastianallgeier** [comment]
✅

**Comment by guidoferreyra** [comment]
I’m getting this on Firefox 82.0 macOs 10.14.6. Any idea?
