### ISSUE TITLE
"KB", not "kB" in F::niceSize

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#2607]
Hello :)

**Describe the bug**  
"kilobytes", in the context of memory, should be abbreviated as 'KB', currently it's 'kB'. (Or alternatively Kirby should use 1000 as a base for the math).

**Additional context**  
AFAIK: conventionally **1kB = 1000 bytes** and **1KB = 1024 bytes**. 
The nicesize function [is using 1024 as a base](https://github.com/getkirby/kirby/blob/3175afeac359524da0896c4671cc9cffb08eb3e7/src/Toolkit/F.php#L505). 
The "standard" for the "power of two units" would actually be "KiB", "MiB", "GiB", etc. While I personally don't know anyone that actually uses those, the lowercase "k" seems to explicitly mean `1000`.

See also https://en.wikipedia.org/wiki/Kilobyte and also https://en.wikipedia.org/wiki/Kibibyte

PS: I don't mean to sound pedantic.

**Comment by lukasbestle** [comment]
You are right! At first I thought "hm, I have never seen KB being used anywhere", but I've just never noticed it. Will be fixed. :)

**Comment by bastianallgeier** [comment]
✅
