### ISSUE TITLE
Error page always rendered in default language

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2609]
**Describe the bug**
Error pages will always render in the default language.
Only when directly accessed by e.g. `example.com/de/error` it will be in another language.

**To Reproduce**  
1. Enable ~~multitasking~~ multilanguage.
2. Considering `de` is a non-default language, visit a non-existing page like `example.com/de/waldo`.
3. The error page will be in the default language.

**Expected behavior**  
The error page should be translated.

**Kirby Version**  
3.3.5

**Comment by distantnative** [comment]
> Enable multitasking.

😜

**Comment by medienbaecker** [comment]
> > Enable multitasking.
> 
> 😜

Seems like my brain forgot to enable multitasking 🤪

But I hope you can reproduce the issue and it wasn't caused by _multitasking_.
It actually seems like it worked like expected in Kirby 2.

**Comment by texnixe** [comment]
I just tested this because of the same issue here: https://forum.getkirby.com/t/error-page-is-shown-in-wrong-language/18084/6, and can reproduce it with a fresh Starterkit.

**Comment by bastianallgeier** [comment]
✅

**Comment by juliencharette** [comment]
Sorry to reopen, but I think I have found a bug regarding this.

### Scenario to reproduce:

Have 2 languages:
- French (default), with `"url" => "/"`
- English (secondary), with `"url" => "en"`

If you visit `/en/asdf`, the url is right, but the content is not translated (appears in default language).
If you visite `/asdf`, the url is right and the content is translated.

Fix:
If I set the french `url => "fr"`, it works as intended. Both "/" and "/en" are displaying the right locale.
If I set the english as default, with `url => "/"`, it works as intended.

This means I cannot have French as default language with `url => "/"`.

Same issue as this user: https://forum.getkirby.com/t/error-page-is-shown-in-wrong-language/18084/9
