### ISSUE TITLE
Calling site()->title() or site()->content() in a plugin option leads to a multilanguage bug

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#2611]
**Describe the bug**  
Calling `site()->content()` or `site()->title()` (which also calls the `content()` method) in a plugin option breaks the panel language switcher on `site` level, even when calling it after Kirby is fully loaded.
(related to: [this issue](https://gitlab.com/kirbyzone/sitemapper/-/issues/4) + [this forum post](https://forum.getkirby.com/t/multi-language-site-yml-issue/18151))

**To Reproduce**  
1. Create a new starterkit
2. Enable multilanguage and create 2 languages (english and french in my case)
3. Edit `site/blueprints/site.yml` for it to display a text field:

```yml
title: Site

fields:
  test:
    type: text
```

4. Set the value of this field to `English` in EN language, and `Français` in FR language. Go to the panel index / site level. At this point, the language switcher of the panel works fine.
5. Create a new plugin, with this in the `index.php`, the language switcher still works fine.
```php
Kirby::plugin('multi/bug', [
    'hooks' => [
        'system.loadPlugins:after' => function() {
            kirby()->extend([
                'options' => [
                    'test' => site()->url(),
                    // 'test' => site()->title(),
                ]
            ], kirby()->plugin('multi/bug'));
        }
    ],
]);
```
6. Now change `site()->url()` above for `site->title()`. The language switcher breaks.

**Expected behavior**  
The language switcher not breaking. 😬

**Kirby Version**  
3.3.6

**Console output**  
Console is empty.

**Comment by bastianallgeier** [comment]
I have to defend Kirby here :) This is quite understandably leading to a bug. Kirby initialises its multi-language setup during routing, because then it knows for the first time, which language should be loaded. What you are trying here happens too early in the process.

**Comment by sylvainjule** [comment]
Got it. So, in order to achieve this in a plugin, best way would be to register an option for the user to still be able override it, but echo it as a `siteMethod` where we call `$site->title()` as a fallback, to have access to the multi-language content ?

**Comment by afbora** [comment]
Related with #2703

**Comment by bastianallgeier** [comment]
Going back to this, it's simply not solvable. I'm sorry.
