### ISSUE TITLE
route:before hook login automaticly

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#2616]
**Bug/Feature?**
Use of impersonate() in route:before hook leads to autologin via /panel. 

```
  'hooks' => [
    'route:before' => function ($route, $path, $method) {
      $kirby = $this;
      $this->impersonate('kirby');
    }
  ],
```
After this configuration, anyone can login via /panel without user/password. In theory this should be correct, but i think this is dangerously because of hijacking the admin user? Is this a bug or an intended feature? 
  
-  Kirby 3.3.4
 - OS: osx 10.15.3
 - Browser:  chrome 81 mac

**Comment by lukasbestle** [comment]
Thanks for the heads-up.

Using `impersonate()` inside the hook is not supported or recommended, but we will still fix this in the next release as it’s an easy way to shoot yourself in the foot.

What was your original use-case for this?

**Comment by distantnative** [comment]
Maybe we should highlight more the use case of resetting impersonation after you have done what you wanted with the almighty user

https://getkirby.com/docs/reference/objects/kirby/impersonate

**Comment by findthebug** [comment]
Im using kirby as a backend solution, frontend is a vue application. im creating pages/entries in a custom kirby api-route via PUT from the vue frontend.
all those entries have to go into a parent-page which is organised like "2020-05-12" which respresents the current day. so there will be a folder for every day like.

-2020-05-12
--entry1
--entry2

-2020-05-13
--entrya
--entryb

in the hook, im testing if the page/folder like "2020-05-12" is existing, if not create it. 
because the hook is called before the api route, i can then put the entries from the api inside the current day-folder.

this is just prototyping and there are diffent solution for this. but right now im using impersonate for creating pages in hook and routes.

**Comment by findthebug** [comment]
set impersonation to null after the task is finished solves the panel issue.

**Comment by bastianallgeier** [comment]
✅
