### ISSUE TITLE
Support Quality for srcset() crops.

### ISSUE THREAD

**Issue by thomasverleye** [getkirby/kirby#2622]
Hi,

I think this is rather a bug then a feature. I was using the srcset presets to crop my image to different sizes. But when I've added the `'quality' => 80` as mentioned in the docs, the images wouldn't crop but actually resize.

Removing the quality settings fixed my problem but ofcourse, I would like to have control over the quality of my srcsets.

I've also tried and set the [default quality](https://getkirby.com/docs/reference/system/options/thumbs#quality) which didn't work either.

These we're my settings which disabled my images from cropping:

```php
	'thumbs' => [
		'srcsets' => [
			'carousel' => [
				'768w' => ['width' => 768, 'height' => 432, 'quality' => 80, 'crop' => 'center'],
				'1080w' => ['width' => 1080, 'height' => 608, 'quality' => 80, 'crop' => 'center'],
				'1620w' => ['width' => 1620, 'height' => 911, 'quality' => 80, 'crop' => 'center'],
				'2160w' => ['width' => 2160, 'height' => 1215, 'quality' => 80, 'crop' => 'center'],
			],
			'carousel-square' => [
				'320w' => ['width' => 320, 'height' => 320, 'quality' => 80, 'crop' => 'center'],
				'375w' => ['width' => 375, 'height' => 375, 'quality' => 80, 'crop' => 'center'],
				'414w' => ['width' => 414, 'height' => 414, 'quality' => 80, 'crop' => 'center'],
				'640w' => ['width' => 640, 'height' => 640, 'quality' => 80, 'crop' => 'center'],
				'750w' => ['width' => 750, 'height' => 750, 'quality' => 80, 'crop' => 'center'],
				'828w' => ['width' => 828, 'height' => 828, 'quality' => 80, 'crop' => 'center'],
			],
		],
	],

```

**Comment by distantnative** [comment]
Trying to test it, but for me the crop doesn't even seem to work without the `quality` setting either. Weird.

**Comment by lukasbestle** [comment]
Indeed very weird as `FileModifications::srcset()` uses the basic `thumb()` method and passes it the whole array of options. Which is exactly what `FileModifications::crop()` does as well.

**Comment by distantnative** [comment]
Exactly - reading the code I would think it has to work just fine. But trying it, somehow it didn't for me :/

**Comment by afbora** [comment]
If I understood correctly, I've tested 3.5.7.1 and 3.6.0-beta.2 and cropping works great with `quality` option. Is it the same for you?

**Comment by bastianallgeier** [comment]
I'm closing this. I cannot reproduce it either. Feel free to reopen if you run into it again.
