### ISSUE TITLE
Queries fail silently when a page is missing

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2624]
**Describe the bug**  
When you query a page that doesn't exist, the rest of the instructions carry on using the previous result.

**To Reproduce**  
1. Create a pages field with the query `site.page("foo").children.flip`
2. Make sure a page `foo` doesn't exist
3. You will see the _site_ children flipped

**Expected behavior**  
Since the page doesn't exist, it's expected that the query fails and throws an error. If I create the page `foo`, it works as expected. However, if that page doesn't exist, the query is interpreted as `site.children.flip`, which can lead to unexpected results.

**Kirby Version**  
3.3.6

**Comment by bastianallgeier** [comment]
✅
