### ISSUE TITLE
Exceptions in kirbytext rendering are catched but not handled

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2625]
**Describe the bug**  
Kirbytags only are rendered when there is now error thrown inside. All Errors that occure are caught but not handled. While it is good to ensure editors are not able to break the page with kirbytags, this makes it really hard to develop and debug kirbytags.

https://github.com/getkirby/kirby/blob/21ebebda6bdde9aee62140f81f658f0852ea4e60/src/Text/KirbyTags.php#L26-L30

**To Reproduce**  

Throw an exception:
```php
Kirby::plugin('my/custom-tag', [
    'tags' => [
        'test' => [
            'html' => function (KirbyTag $tag) {
                throw new Exception('something happened');
            },
        ],
    ],
]);
```

In Content:
```
(test: 123)
```

**Expected behavior**  

Perhaps bubble exceptions when debug is set to true.

**Kirby Version**  
3.3.6

**Comment by lukasbestle** [comment]
✅
