### ISSUE TITLE
$pages->listed() should return drafts when logged in

### ISSUE THREAD

**Issue by nexx512** [getkirby/kirby#2628]
Right now the draft elements used in the One Pager sample are not shown even when logged in. Therefore it is not possible to preview content elements that are implemented as children of a page for example like this:
```
<main>
  <?php foreach ($page->children()->listed() as $part) : ?>
    <section class="<?= $part->intendedTemplate() ?>">
      <?php snippet($part->intendedTemplate(), compact('part')) ?>
    </section>
  <?php endforeach ?>
</main>
```
It is also not possible to see draft pages in a menu if the menu is programmed with the $pages->listed() function.

I couldn't find a solution for this in the docs.

**Comment by nilshoerrmann** [comment]
While this might be desired in your context, I don't think this is good idea in general. Kirby knows three separate page statuses: listed, unlisted and draft. It doesn't make sense semantically and logically to mix those three. A draft isn't necessarily an unreleased listed page, it might also be an unlisted page or just a draft in the sense of a note.

Have you tried something like this to achieve your goal?

```php
<?php
$parts = $page->children()->listed();

// Check if user is logged in
if ($kirby->user()) {
  // Add drafts to parts
  $parts = $parts->add($page->drafts());
}
?>
<main>
  <?php foreach ($parts as $part) : ?>
    <section class="<?= $part->intendedTemplate() ?>">
      <?php snippet($part->intendedTemplate(), compact('part')) ?>
    </section>
  <?php endforeach ?>
</main>
```

In case you don't need to check for listed pages (vs. unlisted pages) there is also `$page->childrenAndDrafts()`: https://getkirby.com/docs/reference/objects/page/children-and-drafts.

**Comment by nexx512** [comment]
Oh, I see.

thats definitely a better way of doing it. I totally agree that a semantic mixup wouldn't be a good idea. I just ran out oft ideas how to solve it.

So thanks for the hint. I will try that.

**Comment by lukasbestle** [comment]
I agree with @nilshoerrmann – implementing this in Kirby by default would break other setups and would make the methods more confusing.

@nexx512 Also try this, which should work as well:

```php
$parts = $parts->merge('drafts');
```
