### ISSUE TITLE
$cacheId isn't consistent ?

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby/kirby#263]
`$page->cacheId()` returns `sha1($this->id());` 
But the cache is actually set with `$cacheId = md5(url::current());`

Is this on purpose or ? ..i don't get it

**Comment by bastianallgeier** [comment]
The cacheId() method for pages is actually crap. I made a mistake there and forgot about optional parameters in the URL, which need to be cached as well. I should probably remove the cacheId() method in general or rename it.

**Comment by lukasbestle** [comment]
I just saw that the [cheatsheet controller of the getkirby.com site](https://github.com/getkirby/getkirby.com/blob/master/site/controllers/cheatsheet.php) still depends on that method.

Also the multilang version of `Page` still has this method. I think this should either be removed in both versions or reimplemented to return the correct cache ID.

**Comment by distantnative** [comment]
Still looks like this could/should be deleted: https://github.com/getkirby/kirby/blob/master/branches/multilang/page.php#L27-L35 (not part anymore of the non-multilang branch)

**Comment by lukasbestle** [comment]
Yes, that was what I was referring to. I think this method is now obsolete in the multilang branch.

BTW: The Kirby site has been fixed in the meantime.
