### ISSUE TITLE
Panel: tab title is not updated when navigating to a plugin's page

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#2631]
**Describe the bug**

When the Panel navigates in JS to a plugin's page, the page's `document.title` doesn't seem to be updated and ends up stale, showing the title for the previous route.

**To Reproduce**

Tested using the [Retour](https://distantnative.com/retour) plugin by @distantnative. I suspect other plugin pages show the same issue, but haven't confirmed yet.

1. When logged out, load `/panel/plugins/retour` -> get redirected to `/panel/login`.
2. Log in -> get redirected to `/panel/plugins/retour`.

Or:

1. When logged in, load `/panel/settings`.
2. Then use the main menu and click the plugin's entry -> navigates to `/panel/plugins/retour`.

**Expected behavior**

In both cases, when on the plugin's page, the tab's title would say something like:
`"<Plugin name> | <Site name>"`.

**Actual behavior**

The tab's title is the title of the previous page.

**Screenshots**  

When coming from the Login page:

![Screenshot](https://user-images.githubusercontent.com/243601/83846963-c3391b80-a70b-11ea-95a5-63f8a37b19cf.png)

When coming from the Settings page:

![Screenshot](https://user-images.githubusercontent.com/243601/83846969-c502df00-a70b-11ea-9963-a1c5be6a6fd4.png)

**Kirby Version**  

Kirby version: 3.3.6
Retour version: 2.3.1

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox
 - Version: 79 (Nightly)

**Comment by lukasbestle** [comment]
For a plugin I'm currently working on, I manually fixed it like this:

```html
<script>
export default {
  mounted() {
    this.$store.dispatch("title", this.$t('view.example'));
  }
};
</script>
```

I agree that the Panel should do that automatically.

**Comment by distantnative** [comment]
✅ Will be part of 3.4
