### ISSUE TITLE
Force trailing slash

### ISSUE THREAD

**Issue by thomasverleye** [getkirby/kirby#2638]
**Describe the bug**  
I'm was trying to force trailing slash on my kirby website.
As suggested in some [forum discussions](https://forum.getkirby.com/t/routes-and-trailing-slashes/15408) I should be using .htaccess for that.

The bug or problem I'm getting is that after I add the rule there are 2 outcomes depending on where i'm adding them in the file:

1. The trailing slash doesn't work
2. The trailing slash does work but panel gives multiple errors and I'm not even able to log in or out of the panel.

I've tried and tested non-trailing slash and this works perfectly fine for me. Which is great, I'd just wanted to enforce the use of one of them.

But this seems to me like a bug or at least a behaviour which should be documented in the docs if this was as intended. Maybe, it would even be better to just add the force non-trailing slash in the .htaccess for SEO/crawling purposes. 🤷‍♂️

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to open .htaccess file
2. Add following code beneath line 37 in a regular kirby install
```
# force trailing slash
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*[^/])$ /$1/ [L,R=301]
```
3. Reload or start your panel and try to login
4. You'll get the invalid login error (yes, I'm 💯 sure I'm using the correct credentials)

But: when I paste the code beneath line 44 (the code which "make site links work") the panel will work but the force trailing slash won't.

**Kirby Version**  
`3.3.3`

**Console output**  
```
Object { status: "error", message: "No route found for path: \"auth/login\" and request method: \"GET\"", code: 404, exception: "Exception", key: null, file: "/kirby/src/Http/Router.php", line: 153, details: [], route: null }
```

**Desktop:**  
 - OS: macOS
 - Browser: Chrome
 - Version: 83.0.4103.97

**Additional context**  
It's maybe important to note that I'm running a multi-language site here. And on my local I'm not running on https.

**Comment by lukasbestle** [comment]
This is not a bug as custom `.htaccess` rules are outside of Kirby's scope. But I'll try to help you with this anyway. :)

Placing your custom rule in line 37 of the `.htaccess` was correct, because if you try to put it below line 44, it will never have any effect (the `[L]` flag of the rule above will prevent Apache from applying any further rules).

However you need to exempt the API and the Panel from the rule to avoid breaking the Panel:

```apache
# force trailing slash
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !^/api
RewriteCond %{REQUEST_URI} !^/panel
RewriteRule ^(.*[^/])$ /$1/ [L,R=301]
```

I have not tested this as I currently don't have a local Apache setup at hand for testing, so please let me know in case it doesn't work.

**Comment by thomasverleye** [comment]
> This is not a bug as custom `.htaccess` rules are outside of Kirby's scope. But I'll try to help you with this anyway. :)

I agree, was hesitating where to put this. Thank you for your time!
Maybe this could be added in the docs?

The API and Panel exempt from the rule fixed it for me. 😁

**Comment by lukasbestle** [comment]
Thanks for confirming that it works. I have created an [idea issue for a new cookbook article](https://github.com/getkirby/getkirby.com/issues/973) about this.
