### ISSUE TITLE
[Panel] No "Saved" Notification when form has an error but saving

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#264]
When I open for example *Projects / Project B* in the panel in Alpha 5 there is one validation-error within the headline field (**The field is required**) which is of course totally legit. When I now edit any other field than headline and press `CMD+S` and reload the page they were successfully saved and the content-file got changed. But there was no Save-Notification! When the headline-field has some valid content and I press `CMD+S` the notification appears like expected.

Also you removed the Autosave-Notifications (after leaving an input field) from Alpha 4, right? (Update: This could be a duplicate of #200)

Somehow related #231 

Please let me know if my issues become more nitpicky than helpful. I just want Kirby 3 to be perfect 🤩

**Comment by distantnative** [comment]
I think you are mixing a few things up, but when I understand your issue correctly, it is mainly about getting more precise feedback when the fields have been saved. Closing this issue in favour of https://github.com/k-next/starterkit/issues/269 which directly relates to improving this aspect.

And feedback is always welcome and helpful 😉
