### ISSUE TITLE
page models not loading after initializing toolkit

### ISSUE THREAD

**Issue by SQbiz** [getkirby/kirby#264]
I'm using a PHP script to get some search results. I'm trying to call a custom function from my page models, and it's not working. The same custom functions *do* work fine when I'm using them within the 'normal' site context. (i.e. in a template)

search script:
```
<?php
define('DS', DIRECTORY_SEPARATOR);
require($_SERVER["DOCUMENT_ROOT"] . DS . 'kirby' . DS . 'bootstrap.php');
$site = kirby()->site();
echo $site->pages()->find('writers')->children()->first()->test();
// returns nothing
```

page model:
```
<?php
class WriterPage extends Page {
  public function test() {
    return "test";
  }
}
```

**Comment by bastianallgeier** [comment]
You need to load them specifically: 

```php

$kirby = kirby();
$kirby->models();
$site = $kirby->site();

```
