### ISSUE TITLE
DB::delete ignores SQL Foreign Key cascade

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#2642]
**some SQLite magic**  
Db::delete() ignores Foreign Key ON DELETE cascade functionality

in kirby
`Db::delete('base_user', 'id = "5" '); `

similar to query:
`DELETE FROM base_user WHERE id="5"`

is deleting the correct DB entry, but ignores "triggering" the ON DELETE cascade functionality defined in the corresponding table.

 
**tables**
base_user / row -> id (Foreign Key ON DELETE cascade (user_detail ) id)
user_detail / row -> id  (Unique Key id)

e.g.
**base_user**
findtheug, id=5
ethbug, id=10
...

**user_detail**
cool, id=5  
cooler, id=5
tester, id=10
...

because i defined the **Foreign Key ON DELETE cascade** in SQL all entries form user_detail should be automatically deleted if i delete the user with the id=5. if i run the SQL statement per hand, it will triggers the cascade and deletes beside the user also the entries. 

if i run the delete function with DB:delete() in kirby the entry will be removed but the foreign key entry is ignored. so all user_detail will remain.

because SQL is handling the cascade magic, i think the implementation of DB:delete is not complete or i miss something but the docs just accept 2 parameters.
 
**Expected behavior**  
DB:delete() should also accept or trigger Foreign Key ON DELETE cascade functionality.
  
**Version**  
- Kirby 3.3.6
- sqlite 3
 
**Desktop**  
 - macOS catalina

**Comment by findthebug** [comment]
Same situation if i using Db::insert(). e.g. in the example with the user above. if i add a user_detail but there is no base_user in the table, sql is not allowing adding an entry because of the Foreign Key option. if i run the this via kirby, i can add the entry. of course, kirby should throw an error because of not valid SQL statement.

**Comment by lukasbestle** [comment]
What is the code you used to run the queries by hand? Kirby uses PHP's PDO class under the hood, which handles all the magic of the database connection – Kirby doesn't need to care about triggers as they are handled by the database and PDO. So to find out where the issue is coming from, we need to make sure that it works with naked PDO.

**Comment by findthebug** [comment]
it's just a generic delete statement like. `DELETE FROM  user WHERE id=5` and i run this SQLiteStudios for mac.
 
as you ask, i did a test with PDO to find the problem with foreign key's, and i found it.
 
```php5
 
    $db = new PDO("sqlite:" . "db.sqlite");
    $db->exec('PRAGMA foreign_keys = ON;');
    $sql = 'DELETE FROM user WHERE id=?';
    $q = $db->prepare($sql);
    $response = $q->execute(array("88"));
```
 
the user 88 is deleted and also all connected entries in other tables which are connected with the foreign key property. 

```php5
$db->exec('PRAGMA foreign_keys = ON;');
```
did the trick. i guess this is a security related setting you have to set in any statement, if you wish SQL should/check foreign relations. the editor im using, enables this by default.

i guess this setting is missing in the kirby-wrapper. probably this is not just related to DELETE but is probably releated to any statement with foreign keys defined.

proposal for enable/disable per statement:

```php5
Db::delete('base_user', 'id = "5" ')->("foreign_keys", ON);
```

proposal for global setting:
```php5
 'db' => [
        'type'     => 'sqlite',
        'foreign_keys' => 'ON',
        'database' => 'db.sqlite'
    ],
```
so at the end this is not a bug, but there should be a setting to enable this feature.

**Comment by lukasbestle** [comment]
You can already run custom queries like this:

```php
Db::execute('PRAGMA foreign_keys = ON');
Db::delete('base_user', ['id' => 5]);
```

So it's not necessary to add new arguments to each database method.

**Comment by findthebug** [comment]
thanks. works.
