### ISSUE TITLE
invisible pages URLs should go to 404 not the page.

### ISSUE THREAD

**Issue by Slgoetz** [getkirby/kirby#265]
When a page in invisible it should not allow you to navigate to that page.

**Comment by texnixe** [comment]
An invisibile page does not necessarily need to be inaccessible. Visible and invisible are just flags for sorting or filtering and stuff. However, you can use a redirect in your templates or use a router to redirect such pages to your error page.

**Comment by Slgoetz** [comment]
Thank you
