### ISSUE TITLE
[Starterkit] Access to .env file needs to be blocked

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#265]
The "invisible" `.env` file is currently accessible via HTTP (at least in Apache as it only blocks access to files that start with `.ht*`).

I don't think that blocking access via `.htaccess` is going to cut it either (it would fail if users use a different `.htaccess` or an entirely different web server). We need another solution...

**Comment by bastianallgeier** [comment]
We probably need to allow env files only in a setup where it is lying above the document root. 
Maybe we should switch it off entirely by default.

**Comment by bastianallgeier** [comment]
As a first fix I moved the env file into the site directory. We already have a access blocker to any file within site so that would be a first good fix. In fact the config.php is another security risk if that blocker isn't working correctly. We should probably add a blocker check to the panel at some point.

**Comment by lukasbestle** [comment]
The issue isn't as bad with `config.php` as PHP files are interpreted, so the source code is not sent to the browser. Directly accessing the file is therefore not leaking much information.

Is `.env` going to be an official feature that can be used for plugins or other custom site configuration? Or is it actually being used by the core itself?

**Comment by bastianallgeier** [comment]
Simple solution: env support is gone. It makes more trouble than it really helps us. We have our custom host config anyway and if someone needs env support, they can create a plugin.
