### ISSUE TITLE
CURLOPT_SSL_VERIFYPEER disabled in Remote::fetch()

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2653]
Hello,

I just took a look at `Remote::fetch()` due to some forum question and I noticed that `CURLOPT_SSL_VERIFYPEER` is set to `FALSE` by default. Is there a reason why this security feature is disabled by default? I would have expected SSL cert validation to be enabled by default or to find some information why this is disabled but I found nothing about this.

See this line: https://github.com/getkirby/kirby/blob/6bd14bc8099d6c9dbe67ef0582b8c0a2d4c0888c/src/Http/Remote.php#L152

I'm sorry if this should have been posted in the forum or if it's an obvious misunderstanding on my side.

Best Regards,

**Comment by bastianallgeier** [comment]
✅
