### ISSUE TITLE
content kirbytext does not transform umlaute to html

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#2657]
**Describe the bug**
i had `Künstler` in my editor text but got
```html
<p>Künstler</p>
```

**To Reproduce**
in any snippet
```php
$content->kirbytext()
```

**Expected behavior**
print `&uuml;` but not `ü`
```html
<p>K&uuml;nstler</p>
```

**Comment by lukasbestle** [comment]
@bnomei Hm, to be honest I don't see this as a bug. Entities are only required for HTML syntax characters (`<>"'&`), all other entities are pretty much there for historical reasons only because some environments only supported ASCII.

What is your use-case for the entity conversion?

**Comment by bnomei** [comment]
i guess my problem was that it cause a wrong char to be use in font because it was not the right `ü`. but i get your point that `kirbytext` should not html encode al but special chars.
