### ISSUE TITLE
[Cms] s as shortcut for snippet?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#266]
I often use `u` which is a shortcut for `url`:

https://getkirby.com/docs/cheatsheet/helpers/u
https://getkirby.com/docs/cheatsheet/helpers/url

When creating a site, probably the most common function is `snippet`:

https://getkirby.com/docs/templates/snippets

When sending arguments to the snippets, especially with some data, it can be a bit long sometimes.

Maybe we could introduce a shortcut for `snippet` as `s`.

```php
function s($name, $data = [], $return = false) {
    $snippet = snippet($name, $data, $return);
    if($return) return $snippet;
}
```

...or even shorter...

```php
function s($name, $data = [], $return = false) {
  return snippet($name, $data, $return);
}
```

In the template we could write:

```php
s('header', ['favicon', 'my-icon']);
```

**Comment by distantnative** [comment]
I'm honestly not a big fan of such meaningless one letter helper/alias methods. Also not of the existing ones, but they are there and we should have them for better compatibility. But I wouldn't like to see more added. They do not save you a lot of code. It's not like the current code wouldn't be short already, you don't have to write something as `Kirby\Output\Template\Subtemplate\Snippet::loadSnippetFromFileAndRenderWithData()`, it's already just `snippet()`. But what all these abbreviation and 1-2 letter aliases result it is code that is harder to read, much harder to understand. That's my opinion.

**Comment by lukasbestle** [comment]
I think so too. Kirby 1 had even more of those and some were really obscure. Every time I saw them in other people’s code (or my own code from a while back), I had to look up what they meant.

**Comment by bastianallgeier** [comment]
I totally agree with @lukasbestle and @distantnative. The goal should be less aliases and better readable code.
