### ISSUE TITLE
Locked-Notification gets displayed only for the first TAB of a page

### ISSUE THREAD

**Issue by nimi09** [getkirby/kirby#2662]
**Describe the bug**
Locked page notification for pages with TABs will only be displayed for the first TAB.

**To Reproduce**  
1. Go to a page (which includes TABs) with user1 and edit it -> don't save the changes
2. login a second user2
3. got to the same page (a lock notification gets displayed)
4. open the second TAB on this page -> no locked-notification is displayed
5. open again the first TAB of the page => now the locked-notification is gone

**Expected behavior**  
User2 should see the locked-notification on all TABs

**Kirby Version**  
Kirby version: 3.3.6

**Comment by bastianallgeier** [comment]
✅
