### ISSUE TITLE
3.4.0-rc.1: Pages section "info" line handles query parameters differently

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2664]
**Describe the bug**  
For some pages sections, I have a an `info` line that formats a field as a date. In `3.3.x`, if the underlying field was empty, the resulting info string would be empty. In `3.4.0-rc.1`, it now falls back to showing the literal query string.

```yaml
type: pages
info: '{{ page.created.toDate("M j, Y") }}'
```

<img width="278" alt="Screen Shot 2020-06-30 at 3 34 33 PM" src="https://user-images.githubusercontent.com/417182/86183585-33f30e00-bae7-11ea-8b0d-f31a20dbc137.png">

This might be caused by https://github.com/getkirby/kirby/pull/2309 or https://github.com/getkirby/kirby/pull/2639.

If it's https://github.com/getkirby/kirby/pull/2309, I don't think there's any way to specify a "fallback" parameter (of an empty string) from the Blueprint level, but I think `info` and `text` would be good candidates to opt into the prior behavior.

**Kirby Version**  
`3.4.0-rc.1`

**Comment by neildaniels** [comment]
Note, if I don't opt for `.toDate()`, then empty/missing fields are correctly reduced to an empty string:

```yaml
type: pages
info: '{{ page.created }}'
```

<img width="193" alt="Screen Shot 2020-06-30 at 3 41 27 PM" src="https://user-images.githubusercontent.com/417182/86184044-2e49f800-bae8-11ea-9227-5cdb5ce19d1e.png">

**Comment by bastianallgeier** [comment]
✅
