### ISSUE TITLE
[3.4.0-rc.1] NavigationDuplicated Issue

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2665]
**To Reproduce**  
1. Go to panel
2. Click to title on top bar menu (for ex: Mægazine for site dashboard)
3. Check browser console

**Screenshots**  

![NavigationDuplicated](https://user-images.githubusercontent.com/3393422/86212956-9d275f80-bb81-11ea-9059-61dc28c57f80.gif)

**Kirby Version**  
3.4.0-rc.1

**Console output**  
````json
{
  _name: "NavigationDuplicated",
  name: "NavigationDuplicated",
  message: "Navigating to current location ("/users") is not allowed",
  stack: "Error↵    at new e (http://localhost/test/kirby/3.…73a113207524b12ced5e281e78/js/vendor.js:23:13600)"
}
````

**Desktop:**  
 - OS: Windows 10
 - Browser: Chrome 83.0.4103.116

**Comment by afbora** [comment]
#2666 I'm not sure, but I think the source of these two issues is the same.

**Comment by bastianallgeier** [comment]
✅
