### ISSUE TITLE
[3.4.0-rc.1] Uncaught (in promise)

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2666]
**To Reproduce**  
1. Go to panel
2. Search anything from global
3. Click to any result
4. Check browser console and see error

**Screenshots**  
![Uncaught](https://user-images.githubusercontent.com/3393422/86213677-c1377080-bb82-11ea-8e99-c035b228ca6d.gif)

**Kirby Version**  
3.4.0-rc.1

**Console output**  
> Uncaught (in promise)

**Desktop:**  
 - OS: Windows 10
 - Browser: Chrome 83.0.4103.116

**Comment by bastianallgeier** [comment]
This is also caused by the duplicate routing issue.
