### ISSUE TITLE
[3.4.0-rc.1] Duplicate action not saving on structure field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2667]
**To Reproduce**  
1. Go to panel
2. Edit any page that have structure field
3. Duplicate any row
4. You wont see save bar
5. Then edit other field
6. Duplicated item disappear (i think, duplicated item not stored to localStorage data)

**Expected behavior**  
Duplicate action should work properly

**Screenshots**  
![Multiselect](https://user-images.githubusercontent.com/3393422/86214435-dcef4680-bb83-11ea-8178-ca9c5d6bea01.gif)

**Kirby Version**  
3.4.0-rc.1

**Console output**  
No errors

**Desktop:**  
 - OS: Windows 10
 - Browser: Chrome 83.0.4103.116

**Comment by bastianallgeier** [comment]
✅
