### ISSUE TITLE
[3.4.0-rc.1] Missing OK button on files/pages select dialog

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2670]
**To Reproduce**  
1. Go to panel
2. Try to select files/pages on files/pages field
3. Can't see OK button 

**Screenshots**  
![screen-capture-131-Trees - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/86234019-fe116080-bb9e-11ea-8ec9-1e23aacfd461.png)

**Kirby Version**  
3.4.0-rc.1

**Comment by bastianallgeier** [comment]
✅
