### ISSUE TITLE
[3.4.0-rc.1] Url Component for Extensions Has Breaking Change

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2673]
**Describe the bug**  
The `url` component for extensions has a breaking signature change. If this is intentional, is there a suggested migration procedure?

**3.3.6:**
https://github.com/getkirby/kirby/blob/fa549aae38d5555e297b1870071418c5bb4a95f1/config/components.php#L219-L230

**3.4.0-rc.1**
(Side note: the comments for this function still list the removed `Closure $originalHandler`.)
https://github.com/getkirby/kirby/blob/eafb118fe4a221fbf1c684e0b87bcf1c51549376/config/components.php#L323-L372

**Kirby Version**  
`3.4.0-rc.1`

**Additional context**  
An example of a 3.3.x usage of a `url` component extension: https://github.com/getkirby/getkirby.com/blob/master/site/plugins/keycdn/index.php

**Comment by bastianallgeier** [comment]
I just fixed it and it's no longer a breaking change. But the $originalHandler argument is now deprecated. We have introduced a great new way to access the original code for each component, which is often useful if you want to fall back to that. 

Here's an example how to use that in the URL component: 

```php
'url' => function ($kirby, $path, $options) {
    if ($path === 'something') {
        return 'https://custom-url.com';
    }

    return $kirby->nativeComponent('url')($kirby, $path, $options);
}
```

This is now the preferred way to handle such fallbacks. We will phase out the $originalHandler argument eventually, but not in this release.
