### ISSUE TITLE
[3.4.0-rc.1] Textarea: Missing OK Button of File Select Modal

### ISSUE THREAD

**Issue by crisgfx** [getkirby/kirby#2676]
**Describe the bug**  
When choosing file selection in the textarea, the OK Button of the select Modal is missing.

**To Reproduce**  
1. Create a textarea field
2. Click on File-Button of the textarea field

**Expected behavior**  
A button to hit ok

**Screenshots**  
<img width="1550" alt="kirby-fileselect" src="https://user-images.githubusercontent.com/16305374/86346052-a89b8900-bc5c-11ea-817a-9c14f0ca7af8.png">

**Kirby Version**  
3.4.0-rc.1

**Desktop (please complete the following information):**  
 - OS: macOS 10.15
 - Browser: Chrome 83

**Comment by afbora** [comment]
Thanks for report 👍 This is known issue as #2670 and will be fixed on RC-2.

**Comment by crisgfx** [comment]
@afbora Uh, sorry, didn't see that one. Thanks! :)
