### ISSUE TITLE
A lot of UI problems in Panel on Russian Language

### ISSUE THREAD

**Issue by mrvicis** [getkirby/kirby#2678]
**Describe the bug**  
A lot of UI problems in Kirby Panel 3.4.0 rc2

**To Reproduce**  
1. Change panel language to Russian

**Expected behavior**  
Upload fields on top of the panel, buttons floats on labels, etc (see screenshot)

**Screenshots**  
<img width="1293" alt="Screen Shot 2020-07-02 at 15 45 31" src="https://user-images.githubusercontent.com/15743822/86361746-f6c08480-bc7c-11ea-9b38-b4dfbb1d8a20.png">

**Kirby Version**  
3.4.0 rc2

**Console output**  
nothing

**Desktop:**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.1.1

**Comment by afbora** [comment]
Thanks for reporting! This is about wrong translation on `direction` and that should be `ltr`. The issue will be fixed on next RC or stable version. Pinging @bastianallgeier to fix the line.

https://github.com/getkirby/kirby/blob/release/3.4.0/i18n/translations/ru.json#L375

**Comment by bastianallgeier** [comment]
I just fixed this on Transifex.
