### ISSUE TITLE
Chrome issue when selecting link in modal from "link" button in textarea field

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#2681]
**Describe the bug**  
In chrome (and brave), when you paste a URL into the "link" popup from the textarea field and you want to select it and drag (while selecting the text) out of the modal and then release the mouse, the entire popup is closed.

In Firefox this works fine.

This happens for textarea fields AND editor field (which probably reuses this logic).

**To Reproduce**  
1. go to a page with a textarea field and the link button
2. click the link button
3. modal opens
4. paste in a link (or type it in)
5. select what you've just typed, but "drag" outside the popup before releasing the mouse
6. popup is closed

**Expected behavior**  
Popup should not close, but text should be selected. In Firefox this is works as expected.

**Kirby Version**  
3.3.5

**Console output**  

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: chrome, brave

**Comment by bastianallgeier** [comment]
✅
