### ISSUE TITLE
c::set locale does not change output of date('D')

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/kirby#269]
I tried to have some dates with the day of the week in front, like this:
```
Mo, 13.07.2015
```
by calling this method on an page
```php
$page->date('D, d.m.y')
```

This works fine, but only in english. I tried to set the locale to `de_DE.UTF8` by this line in the config.php
```php
c::set('locale', 'de_DE.UTF8');
```
but it seems to change nothing.
Is this a bug, or have I missed something?

**Comment by lukasbestle** [comment]
This is a "bug" in PHP, as the [`date()`](http://php.net/manual/en/function.date.php) function does not support locale-based formatting. [`strftime()`](http://php.net/manual/en/function.strftime.php) *does* support locales, but uses a completely different syntax (inherited from the C libraries, which have subtle differences between OSs).

If you want to use `strftime`, you can set `c::set('date.handler', 'strftime')`. Keep in mind you will have to change the output syntax everywhere you use `$page->date()`!

**Comment by jbeyerstedt** [comment]
Ok, thank you. I´ll close this issue.
