### ISSUE TITLE
$kirby->request()->query() return type confusion

### ISSUE THREAD

**Issue by moritzebeling** [getkirby/kirby#2692]
**Describe the bug**  
When I call
```php
$kirby->request()->query()
```
I get a `Kirby\Http\Request\Query` object type instead of a `Kirby\Http\Query` object as the documentation suggests:
https://getkirby.com/docs/reference/objects/request/query

The difference is, that [`Kirby\Http\Query`](https://github.com/getkirby/kirby/blob/3.3.6/src/Http/Query.php) offers some helpful methods (e.g. `isEmpty()`, ...), that [`Kirby\Http\Request\Query`](https://github.com/getkirby/kirby/blob/3.3.6/src/Http/Request/Query.php) doesn’t.

**To Reproduce** 
Read the docs https://getkirby.com/docs/reference/objects/request/query and then call
```php
dump( $kirby->request()->query() );
```

**Expected behavior**  
Either
- this should return a `Kirby\Http\Query` instead of the current `Kirby\Http\Request\Query`
- or code and documentation should clarify what kind of object should actually be returned
- or both objects need to be identical
- or one of them has to be eliminated in favor of the other

or any wild combination of the above.

**Kirby Version**  
3.3.6

**Comment by bastianallgeier** [comment]
✅
