### ISSUE TITLE
Search words option does not work

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2698]
**Describe the bug**  
The `words` option does not have any effect on search results: https://forum.getkirby.com/t/words-true-not-affecting-search-results/18620

**To Reproduce**  
Compare 
```php
$pages->search('special', ['words' => false]);
```
with
```php
$pages->search('special', ['words' => true]);
```

**Expected behavior**  
The second example should not return search results with the word `especially`. The first one should. Both do.

**Kirby Version**  
Happens with every Kirby version I tested.

**Comment by afbora** [comment]
Related lines about the issue:

https://github.com/getkirby/kirby/blob/3.4.0/config/components.php#L222-L226

**Comment by bastianallgeier** [comment]
✅
