### ISSUE TITLE
Capitalisation of units in niceSice()

### ISSUE THREAD

**Issue by tweh** [getkirby/kirby#270]
According to https://en.wikipedia.org/wiki/Metric_prefix the capitalization of the units generated by `niceSice()` area wrong. As far as I can see the array should be

    $unit = array('B','kB','MB','GB','TB','PB', 'EB', 'ZB', 'YB');

instead of all lowercase letters.

If you don’t want to change the method you may like to add `nicerSize()` …

----

Btw. How can I make my own `nicerSice()` working in `echo $file->nicerSize`?

**Comment by byybora** [comment]
`strtoupper` function didnt work?

````
echo strtoupper($file->niceSize()); // 1.2 MB
````

**Comment by tweh** [comment]
It would work exempt for `kB` … “Kilo” needs a small _k_.

Although there are lots of workarounds I’d correct this in the core …

**Comment by bastianallgeier** [comment]
I just fixed this in the toolkit on the develop branch.
