### ISSUE TITLE
Original Page missing in page.duplicate.after hook 

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2705]
**Describe the bug** 
With v3.4.0 the model of the original page is removed from page.duplicate:after hook function. I guess this was not intentional?

```php
// previosly:
'page.duplicate:after' => function ($duplicatePage, $originalPage) {
    // ...
}

// with 3.4.0:
'page.duplicate:after' => function ($duplicatePage) {
    // ...
}
```

**Comment by bastianallgeier** [comment]
Nope, it looks like a bug/regression to me.

**Comment by afbora** [comment]
Also we should write unit tests for all hooks

**Comment by lukasbestle** [comment]
That's indeed kind of a regression. The second argument was [never documented](https://getkirby.com/docs/reference/plugins/hooks/page-duplicate-after), so I didn't implement it in 3.4.0 either. But you are right that it was passed before 3.4.0, so we should also pass it now. I have fixed this in #2706.

@afbora It's a bit difficult to retrofit hook tests into the `Cms` package tests at the moment as some of these test classes don't follow a clear structure. I have added this to my list to implement when we will refactor the tests.

**Comment by afbora** [comment]
@lukasbestle Actually, I started adding missing hooks locally. 
In the beginning, I would put all the hooks into the array and automate them, but as you said, this was very difficult. 
I also do it by separating it into separate methods.

Yes, no need if tests are to be refactored. What do you think, should i continue to write missing hooks test?

**Comment by lukasbestle** [comment]
@afbora If you have already started writing the tests and if you have found a place where they would fit, feel free to send a PR. :)

**Comment by afbora** [comment]
@lukasbestle Now all hooks have unit tests #2707

**Comment by bastianallgeier** [comment]
✅
