### ISSUE TITLE
Setting rewrite to false does not work on multi-language setup

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#271]
While I can remove the htaccess file and set rewrite to false on a site without language settings enabled, this does not seem to work on a site where the multi-language settings are enabled. With the htaccess-file removed when you try to call another page but the start page of the default language, this results in a not-found error. If I manually add "index.php" to the URL, I can access the page, but not via the navigation links.

I'm not sure this is a bug or expected behavior, but the fact that I can set rewrite to false suggests it is a bug, otherwise the option would be unnecessary?

**Comment by lukasbestle** [comment]
Ah, that's the problem. I found the issue (it's a bug, not a feature) and fixed it in #272.
