### ISSUE TITLE
Register license for a different domain

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2710]
# Problem

We usually have a staging server where we test a site before launching it. We also like to register the license prior to launch so we know that absolutely everything is ready and there's nothing left to do once the site goes live.

However, if we register the site at `example.test`, the resulting `.license` file is made to work for `example.test` only, meaning that when we upload the site live and the domain is different, e.g. `example.com` - you get the message that Kirby is unlicensed.

# Solution

First of all, I think that the domain in `.license` should always point to the actual domain that the license is associated with. It doesn't make sense to use the domain on which the registration is performed.

Next, if you've registered a license for `example.com` and you're not on `example.com`, but there is a `.license` file, instead of seeing the red warning:

>This is an unregistered demo of Kirby

...you should maybe see an orange warning:

>This domain is not covered by the license

When you click on that, you can see what domain the license covers.

The whole experience is:

1. You see "This is an unregistered demo of Kirby"
2. On `example.test`, you register the domain
3. You see "This domain is not covered by the license"
4. Later, on `example.com`, you see no warning

**Comment by distantnative** [comment]
Moved to Nolt for now: https://kirby.nolt.io/126
