### ISSUE TITLE
Icon not showing in k-list

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2723]
**Describe the bug**  
The 3.4.0 release didn't warn about breaking changes in the UI Kit. However, there were, apparently. In my Git plugin, list items suddenly have no icons:

![image](https://user-images.githubusercontent.com/5570098/87880575-5f3c8f00-c9fb-11ea-813f-d2789e96b151.png)

It worked fine in 3.3.6.

**To reproduce**

```vue
<k-list-item :icon='{ type: "file", back: "black" }'></k-list-item>
```

The icon will not appear.

**Kirby Version**  
3.4.0

**Comment by afbora** [comment]
Now you need pass `image` property https://github.com/getkirby/kirby/pull/2686 https://github.com/getkirby/kirby/pull/2358

I haven't tested but should work like that

````vue
<k-list-item :icon='{ type: "file", back: "black" }' image="icon"></k-list-item>
````

_Edited: true to icon_

**Comment by distantnative** [comment]
@afbora can't test it right now myself, but shouldn't it be
```vue
<k-list-item :icon='{ type: "file", back: "black" }' image="icon"></k-list-item>
```

@hdodov I know this syntax now is a it add. It's one of the pieces that suffered a bit from our big UI refactoring not making it into 3.4.0.

In the refactored UI kit we are already working with a new `preview` option that combines the current `image` and `icon` options. Feels so much better, trust me. Still, we have added a fallback for this new `preview` option so that it still works if the old `image` and `icon` are defined.

This just as background why the current syntax maybe is not totally ideal.

**Comment by afbora** [comment]
@distantnative Ahh, yes you right, @hdodov already wants to show icon 👍

**Comment by afbora** [comment]
The same issue happened before on slack. 

@distantnative What if we put a default setting if the `image` property is never defined? We can remove it only if the user has defined custom as `image: false` to avoid break change on custom ui usages.

**Comment by yandodov** [comment]
@distantnative I thought that the [monstrous Storybook revert](https://github.com/getkirby/kirby/commit/8a38b8443f2a25a4e84dc4e322799892c113f58c) was probably the cause of this regression. I've got no problem waiting for the new UI Kit stuff to come so I can release a new version of the plugin. I just wanted to open this issue so you can know about it. The 3.4.0 release brought some changes that were not mentioned in either the release changelog or [the docs](https://getkirby.com/docs/reference/plugins/ui/list-item).

**Comment by afbora** [comment]
Documentation about new `image` option  already on list but not yet done https://github.com/getkirby/getkirby.com/issues/954

**Comment by distantnative** [comment]
@hdodov it‘s not a regression per se. We added the feature that you can disable the image/icon completely. Does my code suggestion work for you?

The rest was just giving you a little insight what will come ahead. We are currently at a little place in between the old feature set and what will come syntax-wise.

Docs will be finished this week.

**Comment by distantnative** [comment]
And if you thought the revert was monstrous, you have no idea how huge the actual storybook branch differs by now 😅🙈

@afbora yes I think we should think of sensible defaults. I think we thought of them on the level of the actual sections but it would be good to add some to the UI components themselves

**Comment by bastianallgeier** [comment]
I consider this outdated. Please reopen if you feel different about it.
