### ISSUE TITLE
Weird errors on panel login - gmagick lib driver?

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#2727]
**Describe the bug**  
Since 3.4.0 i got some weird errors in the panel after login with an admin account. either a section can not loaded properly or a request to site/unlock is failing. 

**section not found:**
_The JSON response from the API could not be parsed. Please check your API connection._

<img width="754" alt="Bildschirmfoto 2020-07-19 um 19 53 24" src="https://user-images.githubusercontent.com/5121132/87881437-86925c80-c9f9-11ea-85ff-e9b80fac848b.png">
<img width="738" alt="Bildschirmfoto 2020-07-19 um 19 53 21" src="https://user-images.githubusercontent.com/5121132/87881439-885c2000-c9f9-11ea-9b75-0846aa9e5176.png">

**unlock not found:**
 <img width="801" alt="Bildschirmfoto 2020-07-19 um 19 58 39" src="https://user-images.githubusercontent.com/5121132/87881548-441d4f80-c9fa-11ea-9571-b96533bcd62f.png">

 
Tried to rename the section(s) but the problem seems to be somewhere else. there is no logic which section fails, its kind of random.  As the messages describes, the is a problem with parsing in general.

**but this stuff leads to the next issue, and maybe thats the core of the problem:**
 
**Did you guys changes something in 3.4.0 regarding library loading?** Beside that weird stuff above i have also an issue with loading i guess image driver. frontend and in the panel. the error message is kind of the same in panel or frontend:
  
 `
 {"status":"error","exception":"Whoops\\Exception\\ErrorException","code":32,"message":"PHP Startup: Unable to load dynamic library 'gmagick.so' (tried: \/usr\/lib\/php\/20190902\/gmagick.so (\/usr\/lib\/php\/20190902\/gmagick.so: cannot open shared object file: No such file or directory), \/usr\/lib\/php\/20190902\/gmagick.so.so (\/usr\/lib\/php\/20190902\/gmagick.so.so: cannot open shared object file: No such file or directory))","details":null,"file":"Unknown","line":0}
`

<img width="1100" alt="Bildschirmfoto 2020-07-19 um 20 02 00" src="https://user-images.githubusercontent.com/5121132/87881614-bf7f0100-c9fa-11ea-8c9c-fbb059927a40.png">

 
**Kirby Version**  
3.4.0
PHP 7.4.6 - vagrant - debian - apache

**Note:**
I see, this can be an issue with vagrant or php, but i just noticed this after updating. in 3.3.6 i ran the exact same vagrant and php, so i think there is some stuff changed in 3.4.0 which reacts different.

**Comment by lukasbestle** [comment]
Kirby doesn't use the Gmagick library. The error is generated by PHP on startup and therefore not directly triggered by Kirby.

To debug this, we need to know if the change from Kirby 3.3.6 to 3.4.0 was indeed the reason for the issue. Could you please do the following (and only the following!) to test this:

- Replace the `kirby` directory with a fresh copy of Kirby 3.3.6.
- Delete the `media/panel` directory.
- Do not make any other changes to your site.
- Verify whether the issue persists.

**Comment by findthebug** [comment]
okay guess what... did all this and got same issues...
now... i just deleted manually all gmagick libs (in rage), in vagrant and that solved the issue at all. im pretty sure i screw something up during updating, probably apt updater.

nevertheless: i will install Gmagick library again with a proper version and test what happens in kirby to make sure there is no other issue with this.
