### ISSUE TITLE
Smartypants and custom replacements

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2729]
**Describe the bug**  
Following the documentation I added these rules to my config to get German quotes using Smartypants:

```php
return [
    'smartypants' => [
        'doublequote.open' => '&#8222;',
        'doublequote.close' => '&#8220;',
        'singlequote.open' => '&#8218;',
        'singlequote.close' => '&#8216;'
    ]
];
```

And while using `$page->title()->smartypants()` applies transformations, it still uses the default English quotes.

**Expected behavior**  
Quotes should use „German notation“.

**Kirby Version**  
Kirby 3.4

**Additional context**  
This is happening on a standard install without any language definitions.
Forum discussion: https://forum.getkirby.com/t/smartypants-and-custom-replacements/18830/5

**Comment by afbora** [comment]
I've checked the issue and reproduced. This is related dot notation option issue https://github.com/getkirby/kirby/issues/2697

**Comment by nilshoerrmann** [comment]
Anything I can change in the notation to make this work again?

**Comment by afbora** [comment]
I have tried all the different versions but the only solution seems to be updating the core codes 😞 Now we are waiting for @lukasbestle to solve this issue.

**Comment by nilshoerrmann** [comment]
Alright, thanks!

**Comment by lukasbestle** [comment]
@nilshoerrmann Workaround: Use the following line in your `config.php` *before* the `return` line:

```php
Kirby::$nestIgnoreOptions[] = 'smartypants';
```

We will fix this in 3.4.1.

**Comment by nilshoerrmann** [comment]
@lukasbestle Am I correct that using the `develop` branch will also fix the problem?

**Comment by distantnative** [comment]
@nilshoerrmann no, the fix isn’t yet on develop

**Comment by bastianallgeier** [comment]
✅
