### ISSUE TITLE
Auto-convert `filterBy()` values to strings?

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#273]
Once again, [I tripped over the detail that `$pages->filterBy()` only accepts string values](http://forum.getkirby.com/t/dynamically-how-posts-based-on-category/1654/3), not field values or other objects. Is there any point against casting the values to strings automatically before letting the collection (parent class of Pages) filter? The attributes of pages are basically all strings anyway.

**Comment by bastianallgeier** [comment]
Good idea! I actually ran into this myself a couple times. Just added it to the develop branch.
