### ISSUE TITLE
File cannot be found – uploading Mac OS Screenshots doesn't work

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#274]
Seems like the filename does not get properly sluggified on upload:
<img width="699" alt="screen shot 2018-03-23 at 08 17 38" src="https://user-images.githubusercontent.com/3788865/37816285-d53f3ad0-2e72-11e8-8f73-77c7386e5c1d.png">

**Comment by bastianallgeier** [comment]
✅
