### ISSUE TITLE
Kirby Panel: Some API request URLs have double-slashes in their path

### ISSUE THREAD

**Issue by damiendart** [getkirby/kirby#2740]
### Describe the bug

When saving changes to pages in the Panel, some of API request URLs have double-slashes in their path (e.g. ` https://www.example.com/api//pages/test-page`). This isn’t a problem in itself, but I’ve set up Apache to clean up any URLs with extraneous double-slashes with a 301 redirect (mainly for SEO purposes), which unfortunately causes these requests to be stripped of their bodies and not update anything.

I’ve managed to fix this by changing [line 35](https://github.com/getkirby/kirby/blob/3.4.0/panel/src/api/request.js#L35) of _panel/src/api/request.js_ to:

````
return fetch(api.config.endpoint + (path.charAt(0) === "/" ? '' : “/") + path, options)
````

Another solution would be to use [308 redirects](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) instead, but I was wondering if it’s worth accounting for this in the Panel codebase to make things a little easier for those who run into a similar situation in the future? I’m happy to create to a pull-request.

I understand that this is a bit of an edge-case, so please feel free to ignore this!

### To Reproduce
1. Edit a page in Panel
2. Save changes
3. Open the _Network_ tab in your browser’s web developer tools and check for any requests made to the API (e.g. `https://www.example.com/api//pages/test-page`).

### Kirby Version
3.4.0

### Desktop:
 - OS: macOS
 - Browser: Firefox
 - Version: 78.0.2

**Comment by bastianallgeier** [comment]
✅
