### ISSUE TITLE
Get() does not support arrays

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#275]
http://forum.getkirby.com/t/get-does-not-support-arrays/1514

This function is really helpful. However it cannot handle arrays.

http://getkirby.com/docs/cheatsheet/helpers/get

When using $_POST for example you can have a little bit more complex forms with arrays. It would be helpful if this function could support arrays as well.

**Comment by bastianallgeier** [comment]
I moved this to the toolkit: https://github.com/getkirby/toolkit/issues/149
