### ISSUE TITLE
Plain text emails: template parser "eats" EOL, unless there's a trailing character

### ISSUE THREAD

**Issue by adamkiss** [getkirby/kirby#2750]
**Describe the bug**  
If you use an email template, like this (`site/templates/emails/email1.php`):

``` html
# Hey, <?= $name ?>

This is just me, <?= $job ?>
I am also <?= $third ?>
```

the resulting email sent looks like this, clearly missing `\n` after every php output:

```
# Hey, Adam Kiss
This is just me, Testing Kirby emailsI am also Just saying hi!
```

If I add trailing character - any trailing characters, even space works - the newline is preserved

``` html
# Hey, <?= $name ?>,

This is just me, <?= $job ?>.
I am also <?= $third ?>!
```

``` html
# Hey, <?= $name ?>_

This is just me, <?= $job ?>_
I am also <?= $third ?>_
```

**To Reproduce**  
Any plaintext email will do. I have a plainkit site with only emails added, if you can't reproduce.

**Expected behavior**  
```
# Hey, Adam Kiss

This is just me, Testing Kirby emails
I am also Just saying hi!
```
**Kirby Version**  
3.4.0

**Comment by adamkiss** [comment]
Update: `3.4.1-rc1` has the same behaviour

**Comment by medienbaecker** [comment]
What happens when you rename the file to `site/templates/emails/email1.text.php`? 🤔

**Comment by afbora** [comment]
I don't think this is a Kirby issue. I think it looks like a PHP related situation that you'll see on following test:

**index.php**

````php
<?php  
    $name = 'Adam';
    include 'test.php';
?>
````

**test.php**
````php
# Hey, <?= $name ?>

This is just me, Testing Kirby emails
I am also Just saying hi!
````

**Output**

```
# Hey, Adam
This is just me, Testing Kirby emails
I am also Just saying hi!
```

---

**Note that**

I guess this issue about php variables that end of line 🤔 If you use `# Hey Adam` instead of php variable like `# Hey, <?= $name ?>`, works great.

**Comment by adamkiss** [comment]
@medienbaecker Tested that as well. If no `*.html.php` file is present, the very same happens. If it is, I can't test the plain test version :D

@afbora Yes, and trailing space also changes output, so it's basically the same.

I'd say at least a note in the docs would be in order, then?

**Comment by adamkiss** [comment]
I still sort of consider it a bug, because it's not what I expect to happen, but I can see how this is out team Kirby's hands, especially since any possible solution would probably involve rewriting the email generation logic.

**Comment by afbora** [comment]
@adamkiss This is not just about email. This is all about file loading `F::load` that includes files (template rendering). IMO it's difficult to solve.

**Comment by lukasbestle** [comment]
Unfortunately @afbora is right – this is something that is baked into PHP, so there is no way for Kirby to prevent this from happening, even if we would rewrite the email classes. The only way would be to use a custom template language like Twig or our own query language. As all other templates use plain PHP, I'm however not sure if this is viable.

Possible workarounds are:

- Place a space after the closing tag if the closing tag is at the end of the line. The space will be in the output, but it's not as bad as a missing newline. However many text editors strip trailing whitespace.
- Manually enter an additional newline after the closing tag (however this will produce even more confusing templates).
- Use `<?= $job . "\n" ?>` to enforce the newline directly in the code. You need to do this for every variable that is printed at the end of a line.

I have added an issue to the site repo for documentation: https://github.com/getkirby/getkirby.com/issues/1003

**Comment by adamkiss** [comment]
@lukasbestle i personally think 1 is the best solution, it’s just a way of having this documented.

I did 2 (add another newline manually) in another project and it was confusing as hell.

When you work with html, you kind of expect the volatility of white space, I just didn’t expect it in the emails.

I’ll just note - in regards to the templating language - that there are places like the blueprints where we already have simple templating (info, text and other blueprint keys), so having the option of parsing a simple mustache style would be nice. I think specifically with emails, I’d prefer it, but that’s only my opinion, of course.

**Comment by lukasbestle** [comment]
Yes, our own query language could be an option for emails. The default would be PHP, but the query language would be available.

**Comment by afbora** [comment]
We can close the issue with create new one to ideas repo or transfer to there as feature.

**Comment by adamkiss** [comment]
Your call. I now sufficiently understand wtf is going on with my newlines 😄

**Comment by bastianallgeier** [comment]
I'm also for closing this as an issue and opening an idea issue instead.

**Comment by lukasbestle** [comment]
I have opened an idea issue in https://github.com/getkirby/ideas/issues/589.
