### ISSUE TITLE
Topbar breaks layout with long site title in Chrome

### ISSUE THREAD

**Issue by kraftner** [getkirby/kirby#2755]
**Describe the bug**  

If your site has a very long site title the title breaks out of the viewport in the topbar on Chrome.

**To Reproduce**  
1. Create a new site
2. Change the site title to something long, e.g. "Kirby Demo has a very long title and breaks the layout"
3. Open the Panel in Chrome (Mobile or Device Inspector on Desktop)

**Expected behavior**  

The site title doesn't break out of the topbar and messes with the viewport.

**Screenshots**  

![viewport_breakout](https://user-images.githubusercontent.com/2428517/89053717-eec93280-d357-11ea-9eea-e097805f7da8.png)

**Kirby Version**  

3.3.6, 3.4.0

**Console output**  

**Desktop (please complete the following information):**  
 - OS: Ubuntu
 - Browser: Chromium / Chrome 
 - Version: 84.0.4147.105

**Smartphone (please complete the following information):**  
 - Device: 
 - OS: Android 10
 - Browser: Chrome
 - Version: 83.0.4103.106

**Additional context**

**Comment by yoanmalie** [comment]
Hello,

I can give a look on this. What's the best behaviour is expected here?
Is applying `overflw-y: hidden` on the `.k-topbar-wrapper` element could be efficient ?

**Comment by distantnative** [comment]
To be consistent we should truncate the text with ellipsis when the length exceeds the available space.

**Comment by bastianallgeier** [comment]
✅
