### ISSUE TITLE
Changing template doesn't change template, changes title

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#2758]
**Describe the bug**  
When changing the template of a page in a Kirby 3.4.1 Panel, the template doesn't change. Instead the filename of the blueprint file (e.g. "alternative" for `site/blueprints/pages/alternative.yml`) is set as the title.

I reproduced the issue in a 3.4.1 Plainkit. It works in a 3.4.0 Plainkit.

**To Reproduce**  
1. Add the [changeTemplate option](https://getkirby.com/docs/reference/panel/blueprints/page#options) to a page
2. Change the template

**Expected behavior**  
Until Kirby 3.4.0 the template changed correctly, which would be the expected behavior.

**Screenshots**  
![changetemplate](https://user-images.githubusercontent.com/7975568/89527679-07b76500-d7ea-11ea-87cf-afada22738ae.gif)

**Kirby Version**  
3.4.1

**Comment by afbora** [comment]
I couldn't find the exact source of the issue but it seems to be caused by updates on the Panel UI(Vue) side in my tests.

**Comment by bnomei** [comment]
changetitle is written like this:
https://github.com/getkirby/kirby/blob/194fe296a45328b9e45eeb7bd8a956689963306e/panel/src/components/Dialogs/PageRenameDialog.vue#L56

but changetemplate is just "template"
https://github.com/getkirby/kirby/blob/194fe296a45328b9e45eeb7bd8a956689963306e/panel/src/components/Dialogs/PageTemplateDialog.vue#L69

maybe thats causing this?

i see only
https://github.com/getkirby/kirby/blob/194fe296a45328b9e45eeb7bd8a956689963306e/panel/src/api/pages.js#L34

**Comment by bnomei** [comment]
@afbora wow an alias table. did not know that one.

**Comment by afbora** [comment]
@bnomei I found the issue when you pointed out the methods in `pages.js`. Thank you 👍

**Comment by bastianallgeier** [comment]
That's a really stupid mistake. I'm sorry :/ We should not only fix the aliases but actually use the desired method names instead of the deprecated ones.

**Comment by bastianallgeier** [comment]
✅
