### ISSUE TITLE
Creating new pages doesn't update the $page->childrenAndDrafts() collection

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#2767]
**Describe the bug**  

With the following code:

```php
$collection = site()->find('a-page')->childrenAndDrafts();

$collection->parent()->createChild([
  'slug'     => 'a-new-article',
  'template' => 'article',
  'content' => [
    'title'  => 'A new article',
    'author' => 'Homer Simpson'
  ]
]);
```

the `$collection` object is not updated after the page has been created, which means that the newly created page is not appended to the `$collection`.

The same thing likely happens when a page is modified (`changeSlug`, `delete` etc.).

Originally reported by @andreasotto [in Slack](https://app.slack.com/client/T2URU1Z6X/D5CU7RZM5/thread/C2UTAQAN4-1596969667.198200).

**Expected behavior**  

The existing `$collection` should automatically contain the newly created page.

**Kirby Version**  

3.4.2

**Additional context**  

We [already update the `drafts()` or `children()` collection](https://github.com/getkirby/kirby/blob/3.4.2/src/Cms/PageActions.php#L453-L458), but not the `childrenAndDrafts()` collection. This one is merged on the fly, but merging the collections clones the data array, so because only the individual collections are updated, the combined collection that has already been merged won't be updated automatically.

The only way to fix this would be to cache the `childrenAndDrafts()` collection as a property in the `HasChildren` trait (just like `$children` and `$drafts`). Then we could also update this collection once a new page is created, modified or deleted. However this would increase memory usage.

**Comment by lukasbestle** [comment]
@getkirby/kirby-staff What do you think about the suggested solution in "additional context" above? To be honest, I feel like a bit higher memory usage is better than a reliability bug.

**Comment by distantnative** [comment]
I agree - on first hand doesn't seem like a no go. Would be interesting to see though if this would cause problems with large numbers of children pages, e.g. a page with 2000 children, would having them basically twice cached in memory a problem for those projects?

**Comment by lukasbestle** [comment]
The `Pages` collection object is basically just the `$data` array that contains the page IDs as keys and the page objects as values. The page objects don't need any additional memory, they are only pointers. So if I understand it correctly, it's only about the ID strings for the array keys plus a bit of array boilerplate. Also the cache would only be created once `$pages->childrenAndDrafts()` is actually first requested. Not all sites need it at all.

**Comment by distantnative** [comment]
Sounds sensible 😄

**Comment by distantnative** [comment]
@lukasbestle Will you take over? I'd then removed the discussion label and assign the issue to you

**Comment by bastianallgeier** [comment]
✅
