### ISSUE TITLE
Don't require title in the blueprint

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#277]
http://forum.getkirby.com/t/dont-require-title-in-the-blueprint/1360

Now I'm forced to set the `title` in the blueprint. I don't think it should be forced.

## Use the slug if title is missing

If a there is no title, show the slug (folder name) wherever you need, for example in the panel SEO title, or the navigation.

The same when using

    echo $page->title();

If the title is missing, show the slug (folder name) or show nothing.

**Comment by bastianallgeier** [comment]
I moved this to the panel issues: https://github.com/getkirby/panel/issues/650
