### ISSUE TITLE
[Panel] User page section can't create new page (no route)

### ISSUE THREAD

**Issue by mrflix** [getkirby/kirby#2771]
**Describe the bug**  
When adding a pages section to a user blueprint, adding a new page using the add button results in the following error:

> No route found for path: "users/VDjIQ5/children/blueprints" and request method: "GET"

**To Reproduce**  
1. Add a pages section to a user blueprint
2. Open the user page in the panel
3. Click on the +

**Expected behavior**  
That page creation works from within the user area in the panel.

**Screenshots**  
![image](https://user-images.githubusercontent.com/60777/89765440-a1d32200-daf6-11ea-898b-ae022541c692.png)

**Kirby Version**  
3.4.2

**Console output**  
"No route found for path: "users/hoa3biYu/children/blueprints" and request method: "GET""

**Additional context**  
Initially reported in the forums on [May 5th](https://forum.getkirby.com/t/blueprint-section-in-user-page/18136) by user Perry and reproduced by texnixe.

**Comment by bastianallgeier** [comment]
✅

**Comment by strukturart** [comment]
thx *~*

**Comment by mrflix** [comment]
Cool that was fast – thanks a lot Ahmet and Bastian!
