### ISSUE TITLE
Humongous whoops ?

### ISSUE THREAD

**Issue by plagasul** [getkirby/kirby#2774]
**Describe the bug**  

Sudden increase of font-size on whoops page, when receiving a 'Nesting level too deep - recursive dependency?' exception

Only part of the whoops screen is oversized (see screenshot).

Browser's zoom is 100%. 

It does seem whoops is affected by the site's build.css rules :open_mouth: as modifying these rules on devtools, specifically `section>div.artists` target, modifies the oversized whoops.

**To Reproduce**  

I am unsure how to reproduce it.

After thinking about it, it could be that the part of the html+php code that the whoops quotes on-screen is affected by the same rules than on the site itself. Perhaps it is relevant that the rule that is affecting the whoops is particularly `section>div.artists`

**Expected behavior**  

Regular font-size of course

**Screenshots**  
![image](https://user-images.githubusercontent.com/13966673/89832581-d9c27f80-db5f-11ea-8332-045159c0453a.png)

**Kirby Version**  

3.4.0

**Console output**  

No related console output

**Desktop (please complete the following information):**  
 - OS: Linux Mint
 - Browser: Chrome
 - Version: Versión 84.0.4147.105 (Build oficial) (64 bits)

**Comment by yandodov** [comment]
Maybe it's caused by a Chrome extension? Does it happen in incognito mode as well?

**Comment by lukasbestle** [comment]
@plagasul If you happen to reproduce this issue, could you please save the Whoops page as an HTML file and send that to me (either as a link in this issue or via email to lukas at getkirby)? Thanks!

**Comment by plagasul** [comment]
Thanks both, I had to move on with the code on that one. I will try to reproduce the behaviour ASAP. In case I run into it again I'll make sure to try deactivating all extensions (I use a few) and saving the page for further inspection.

thank you

**Comment by distantnative** [comment]
@plagasul If you can reproduce it again and provide further insight, please let us know! until then I'm closing this issue for now.

**Comment by nilshoerrmann** [comment]
I've seen this, too. I think it first happened in Kirby 3.4. And I noticed that behind the Whoops UI my own website was partly rendered (= there was markup, not just CSS). So maybe it has to do with errors that happen when the output has already started? 

I'm using Firefox on macOS (but I don't think this is browser-related).
