### ISSUE TITLE
Inconsitent - Fields vs Tags

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#278]
http://forum.getkirby.com/t/inconsitent-fields-vs-tags/1429

In both field methods and kirbytext tags we can get the page object which is important for many cases. However I find them inconsistent with each other.

## Differences

**In kirbytext::$tags**

    echo $tag->page()->title();

**In field::$methods**

    echo $tag->page->title();

Do you spot the difference? With kirbytext tags it's called like a nested function. With field method it's a... I don't know, something else.

## Why bother?

When I first tried field methods I used echo `$field->page()->title()` but that failed because it does not work like in the template.

Today, I could not find the docs right away when trying out kirbytext tags, so I tried echo `$tag->page->title()` because I remembered how I did with field methods. That also failed because it does not work like the field method.

To be inutiative I think they need to be "in sync".

## Prefered version

I like how kirbytext tags works. Always use page() as a function, because that is how it also work in the template.

I think field method is the not so good one here.

**Comment by bastianallgeier** [comment]
This is already fixed. You can now use $field->page() as well.
