### ISSUE TITLE
widont() not working when code block at the end of paragraph

### ISSUE THREAD

**Issue by ammonj** [getkirby/kirby#2781]
The widont() helper replaces the last space character of a paragraph with a non break space (&nbsp;) to prevent the browser from breaking the line before the last word. If a code block is placed at the end of a paragraph and therefore the last space character is inside the code block, the non break space is not displayed correctly by the browser, but instead, the characters & n b s p ; are displayed. 

1. In Panel, write a paragraph and end it with a code block with at least one space character in it
2. Use the widont() helper in your template to show the content in frontend

**Expected behavior**  
In my opinion, the non break space character should be rendered normally and NOT show the html entity instead.

**Screenshots**  
<img width="1053" alt="Screenshot 2020-08-14 at 00 32 34" src="https://user-images.githubusercontent.com/19238550/90193654-ada83800-ddc5-11ea-92be-670e8348d5b8.png">

**Kirby Version**  
3.4.1

 - OS: < macOS
 - Browser: Firefox, Chrome, Safari
 - Version: Firefox 79

**Comment by afbora** [comment]
I have no idea how we should show the `&nbsp;` entity in the code block or what we can use as an alternative to `&nbsp;` 🤔

**Comment by afbora** [comment]
I've tested with following text and works great. Am i missing something to reproduce the issue?

**Sample text**

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie, sapien non euismod faucibus, eros tortor auctor arcu, sit amet scelerisque elit nulla et orci. Proin tempus pellentesque dui ut varius. Aliquam id faucibus dui, a molestie metus: `dies ist ein test`

**End of code block**

    `dies ist ein test`

**Template**

    <?= $page->text()->kt()->widont(); ?>

**Output**

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie, sapien non euismod faucibus, eros tortor auctor arcu, sit amet scelerisque elit nulla et orci. Proin tempus pellentesque dui ut varius. Aliquam id faucibus dui, a molestie metus: <code>dies ist ein&nbsp;test</code></p>

**Screenshot**

![screen-capture-193-Mægazine - Exploring the universe-localhost](https://user-images.githubusercontent.com/3393422/90238956-779f9e00-de2f-11ea-9f07-4f16b6a8619f.png)

**Comment by nilshoerrmann** [comment]
Is it possible that you are double-encoding your content?

**Comment by ammonj** [comment]
I compared my code with yours and indeed had applied it in the wrong order, i guess:

`<?= $page->text()->widont()->kirbytext(); ?>`

I changed it, so the widont() will be applied last:

`<?= $page->text()->kt()->widont(); ?>`

… and it works fine. Thank you for your help, and sorry for reporting it as an issue.
