### ISSUE TITLE
Progress bar styling inconsistent

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#2784]
**Describe the bug**  
The progress bar component is not styled in firefox. In Chrome and Safari I noticed that if the width of the progress indicator is less then it's height the border radius gets smaller and it overflows the bar.

**Screenshots**

Firefox:
<img width="422" alt="Bildschirmfoto 2020-08-18 um 23 15 54" src="https://user-images.githubusercontent.com/18071758/90566472-d440e700-e1a8-11ea-89e8-59695d085657.png">

Chrome:
<img width="422" alt="Bildschirmfoto 2020-08-18 um 23 15 59" src="https://user-images.githubusercontent.com/18071758/90566459-ce4b0600-e1a8-11ea-87c4-53cbc98260b6.png">

**Kirby Version**  
3.4.2

**Comment by bastianallgeier** [comment]
✅
