### ISSUE TITLE
Using toBool() on a non-exisiting field returns false instead of throwing an error

### ISSUE THREAD

**Issue by till-kammertoens** [getkirby/kirby#2786]
**Describe the bug**  
Converting a non-existing field to boolean using the toBool() method returns false instead of throwing an error.

**To Reproduce**  
1. in a page template, use <?php if (!$page->nonexistingField()->toBool()) echo "I shouldn't be here"; ?>

**Expected behavior**  
I would expect $page->nonexistingField()->toBool() to throw an error thrown rather than evaluating to false.

**Kirby Version**  
v3.4.2

**Comment by afbora** [comment]
I'm not sure if error throwing is the right thing to do. One solution might be for you to [check the existence](https://getkirby.com/docs/reference/templates/field-methods/exists) of the field beforehand:

````php
if ($page->nonExistingField()->exists() === true) {
    if ($page->nonExistingField()->toBool() === true) {
        echo "to do when field is true";
    } else {
        echo "to do when field is false";
    }
} else {
    echo "to do when non exists";
}
````

**Comment by bastianallgeier** [comment]
I agree with @afbora here. I don't consider this a bug. `toBool` also interprets an empty field as false and doesn't throw an error. It's a decision that I still think is more practical than throwing errors and as @afbora pointed out, there's a good workaround if you want more strict tests.
