### ISSUE TITLE
Panel: Inconsistency in drop-down menu of files section

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#2787]
**Describe the bug**  
The drop-down menu for items in a Files section is inconsistent with the drop-down menu of Pages sections. This causes irritation, as to the Panel user they appear identical visually and should hence work consistently. Access to the file's Panel page is opaque, as it cannot be reached via the drop-down (only by clicking on the item in the files list).

**To Reproduce**  
1. Go to any Panel page with a Files section
2. Click on the `...` icon to open the menu
3. Click on "Open"
4. Instead of opening the Panel page for this file (as it works with Pages sections), the file itself is opened in the browser

**Expected behavior**  
The drop-down menu of a files section behaves similarly to that of a pages section: the first item in the list equals the action of clicking on the item in the section's list view.

While the first option in the Panel dropdown commonly doubles the action of clicking onto the list item itself (e.g. in a pages section, clicking the list item opens the page view as does the first “Open” option in the dropdown), the files section works differently - and “Open” here refers to “View the file” rather than “Open the according panel page”.

To be consistent, the Files section's drop-down should probably have this order:

1. “Open” > leads to the file’s panel page
2. probably a spacer line, to remain consistent with other sections
3. “View” > opens the file (the functionality currently labeled as “Open”)
4. “Rename”
5. “Replace”
6. another spacer line, to remain consistent with other sections
7. “Delete”

**Screenshots**  
Files section on the left, Pages section on the right - they look exactly the same but behave differently:
![1](https://user-images.githubusercontent.com/6355217/91039780-7b8ca680-e60d-11ea-8554-875920d13032.png)

**Kirby Version**  
3.x

_Issue created based on a [Forum thread](https://forum.getkirby.com/t/starting-point-for-customising-dropdown-menu-in-panel/19152)._

**Comment by bastianallgeier** [comment]
I added logical separators to the file dropdown to keep it more consistent with the page dropdown. If we add an additional view or edit button we break out of the consistency again and would need to do the same for the page dropdown. I'm not sure if we really need this because the main click on the item already leads to the file or page view. We could still open a separate issue for this though.
