### ISSUE TITLE
Support dot in the panel username

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#279]
http://forum.getkirby.com/t/support-dot-in-the-panel-username/1201

As username I always have...

    jens.tornell

One of the few places I can't use that is KirbyCMS. Only jens-tornell is a valid username.

My suggestion is to make dot available and maybe even @ for using an email-adress as username.

Thoughts?

**Comment by bastianallgeier** [comment]
I'm sorry but I have to strict here because of the files being stored. I might be switching to a different way of storing user data, but that's something for a future release.
