### ISSUE TITLE
Usage of space and abbreviations in pages dialogs

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2791]
**Describe the bug**  
The pages dialog has a fixed width and thus unnecessarily limited space to display its content. As the pages lists cut off longer titles with an ellipsis, the dialog will get unusable in certain conditions:

![Bildschirmfoto am 2020-08-28 um 11 11 02](https://user-images.githubusercontent.com/25466/91544277-c9602200-e91f-11ea-9dea-6f07bd7766d5.png)

**To Reproduce**  
Use longer page titles.

**Expected behavior**  
1. The pages dialog should not just cut off text but properly wrap (best) or allow the user to scroll the row (slightly better).
2. The pages dialog should make better use of the actual screen size (which would have been wide enough in my case to display everything without wrapping).

This interface could be more responsive in general (CSS) and more deductive (this is an JavaScript app, everything is known about the window context and its dimensions).

**Kirby Version**  
3.4.1

**Additional context**  
Please do not cut off texts inside the panel at all. You can't predict how Kirby is used in projects and thus defining a maximum width doesn't make sense in the first place.

**Comment by nilshoerrmann** [comment]
I cannot provide any additional information but content shortening (`overflow: ellipsis;`) has been causing issues on most of the sites we have been working on so far. This problem is not limited to the dialog but also occurs in sections and tables.

**Comment by lukasbestle** [comment]
I agree that an ellipsis is not optimal, but TBH I don't think the possible alternatives are much better:

- Horizontal scrolling inside the row: What would that look like? The way I imagine it wouldn't have a great UX because of all the scroll bars.
- Wider dialogs would create a pretty long line length. I have tried that locally and the overview and readability is significantly reduced. We *could* base the width on the actual content and only use a larger width if the text is actually too long, but then the dialogs would no longer be the same size consistently, which hurts muscle memory in hitting buttons.
- Wrapping the text is IMO the only real alternative. But with super long text that spans three or more lines in the worst case, the UI will be pretty spread out, which again reduces the overview.

**Comment by distantnative** [comment]
Wouldn't custom CSS make most sense here - cause I also see that for very different edge cases different of these solutions would be preferable, while others of these solutions could be even more. Targeting custom CSS on the specific field with the edge case could achieve the best solution for the specific case.

**Comment by lukasbestle** [comment]
Great idea, I fully agree. We cannot really find a one-size-fits-all approach here because each approach has its disadvantages.

**Comment by texnixe** [comment]
I also agree, the use case above is rather an edge case, I think.

**Comment by distantnative** [comment]
For the picker dialogs, it would be good eventually to also allow customizing the text - then one could also customize the list to show shorter custom strings (e.g. from a custom page method).

**Comment by nilshoerrmann** [comment]
This sounds like an easy solution, but sadly it's not. It's often very hard to target the panel markup with custom CSS because outer classes are missing (on the parents of a component for instance). Also you have to work on paddings and margins to get multiline text working. And this for something that I'd expect to work. 

While I agree that the given example with the street names is extrem because of the repetitive text, please reconsider this issue. We often see text cut of in the interface and it's really bad UX. This is about content being handled by a content management system. Just hiding long content is easy but it's not a good solution.

**Comment by lukasbestle** [comment]
We considered it and I have explained why each alternative also has disadvantages...
If you have a specific solution in mind, a specific example or mockup would help a lot.
