### ISSUE TITLE
Missig support for .mjs files from plugin assets

### ISSUE THREAD

**Issue by crisgfx** [getkirby/kirby#2792]
**Describe the bug**  
Loading `.mjs` files fails when loading them from the plugin assets folder via the js helper.

**To Reproduce**  
```php

<?=
  # This works:
  js(['/media/plugins/superwoman/superplugin/build/js/pluginApp.es5.min.js'],['nomodule' => true]);
  
  # This doesn't:
  js(['/media/plugins/superwoman/superplugin/build/js/pluginApp.min.mjs'],['type' => 'module']);
?>

````

**Kirby Version**  
3.4.2

**Console output**  
```
net::ERR_ABORTED 404 (Not Found)
```

I'm not sure, if this is rather a bug or feature request, but I think `.mjs` files should be supported.
Thanks for reading! :)

**Comment by crisgfx** [comment]
Now that I've taken a closer look at the js helper component,
I'm not sure, if this can be solved easily, since all dynamically imported modules must be symlinked to the media folder as well, am I right?

**Comment by bastianallgeier** [comment]
Yep, this is complicated. I think we need to find a better way to support dynamic imports in general for plugins. So far we can only recommend to put everything into a single js file.
