### ISSUE TITLE
[Panel] Fields buggy on mobile/responsive

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#28]
I'm using Chrome. I created `width: 1/3` on three columns in a row. The width of the screen here is around 1090px.

![image](https://user-images.githubusercontent.com/927011/32229110-5d1af5b8-be50-11e7-9337-6d353b612263.png)

**Comment by bastianallgeier** [comment]
@jenstornell could you check if that happens after today's version is out?

**Comment by bastianallgeier** [comment]
I think we can close this one.

**Comment by jenstornell** [comment]
I didn't have the time to test it and I also saw many other responsive bugs, so I kind of waited it out. I'll be back if I experience it again.
