### ISSUE TITLE
Checking if field key extsts in field method?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#280]
http://forum.getkirby.com/t/checking-if-field-key-extsts-in-field-method/1323

A field method can look like this:

```php
field::$methods['my_method'] = function( $field ) {
     echo $field->key;
};
```

It contains the `$field->key`.

**In my content I have this...**

```php
My first field:
```

...and this...
```php
 
```

The field "My first field" is empty. "My second field" is not even set, that is why the above line is empty.

As far as I know `$field->key` does not know the difference.

## Question

How do I know if the field is empty OR not set? For me, if the field is set, it is known and empty. If the field does not even exist, it is unknown and has no value, not even empty. How can I know the difference without ugly workarounds? Possible?

## Silly workaround

I have a workaround that I don't like.

**Template**

```php
global $fields;
$fields = $page->content()->toArray();

$page->my_second_field()->my_method();
```

**Field method**

```php
field::$methods['my_method'] = function( $field ) {
     global $fields; // This does the "magic"
     if( array_key_exists( $field->key, $fields ) ) {
          echo 'Field key exist, but can be empty';
     } else {
          echo 'Field key does not exist';
     }
};
```

**Comment by bastianallgeier** [comment]
You are right, that this is quite messy. I just uploaded a new version to the develop branch which makes it a lot easier: 

```php 
field::$methods['my_method'] = function( $field ) {
     if($field->exists()) {
          echo 'Field key exist, but can be empty';
     } else {
          echo 'Field key does not exist';
     }
};
```
