### ISSUE TITLE
Broken pagination and role filter in Users Panel section

### ISSUE THREAD

**Issue by mrvicis** [getkirby/kirby#2801]
**To Reproduce**  
1. Go to Users section /panel/users
2.1 Add more than 20 users
2.2 Add one more user role
3. Try to filter users by user role or go to next page
4. See nothing changed

**Kirby Version**  
3.4.2, checked on Demokit

**Desktop:**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.1.2

**Comment by afbora** [comment]
@bastianallgeier The `api.users.list()` method has been converted to `GET` when working with `POST`. API get method doesn't support mapping [nested object](https://github.com/getkirby/kirby/blob/3.4.2/panel/src/components/Views/UsersView.vue#L108-L114) on [request.js](https://github.com/getkirby/kirby/blob/3.4.2/panel/src/api/request.js#L77-L97) and calling following endpoint when filter role

> /api/users?paginate=[object%20Object]&sortBy=username%20asc&filterBy=[object%20Object]

**v3.4.0**

https://github.com/getkirby/kirby/blob/3.4.0/panel/src/api/users.js#L8-L10

**v3.4.2**

https://github.com/getkirby/kirby/blob/3.4.2/panel/src/api/users.js#L43-L45

---

Old `POST` request still working on last release:

````js
async list(query) {
  return api.post(this.url(null, "search"), query);
},
````

**Comment by bastianallgeier** [comment]
✅
