### ISSUE TITLE
Override content type in content representation

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2803]
**Describe the bug**  
If a content representation is of a type not recognized by the `Mime` class, it is served as `text/html`. Setting a custom type via `$kirby->response()->type()` is ignored although that method allows for custom types unknown to Kirby as long as they contain a slash.

**To Reproduce**  
Set up a content representation of the type `geojson`, e. g. by creating a controller and a template `places.geojson.php`. GeoJSON is unknown to Kirby. Try to set the content type in your controller by adding `$kirby->response()->type('application/geo+json');`

**Expected behavior**  
Kirby should take the custom set type instead of the default `text/html`. 

**Screenshots**  

**Kirby Version**  
Kirby 3.4.

**Comment by nilshoerrmann** [comment]
On a more general level, I just noticed that it's not possible to override the content type of a representation at all. So it doesn't matter if I have a unrecognized representation like GeoJSON or a recognized one like JSON: overriding the auto-detected type seems not to be possible.

**Comment by bastianallgeier** [comment]
✅
