### ISSUE TITLE
Contrast of read-only fields

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2807]
We are using virtual pages to display database content in the panel. Updating is disabled via the blueprint options resulting in the following view:

<img width="1462" alt="grafik" src="https://user-images.githubusercontent.com/25466/92377967-44d28800-f105-11ea-93bc-2ca9c55a4fb9.png">

This is barely readable which is problematic because reading is the only purpose of these pages. 
Generally, in my eyes, there is no reason to dim the label of the fields. Additionally, I'd wish for a higher text–background contrast and a different highlighting of the read-only mode.

Removing the opacity might help already:

<img width="1462" alt="grafik" src="https://user-images.githubusercontent.com/25466/92377912-31bfb800-f105-11ea-9e7e-73db5de8e3d0.png">

**Comment by nilshoerrmann** [comment]
<img width="1087" alt="grafik" src="https://user-images.githubusercontent.com/25466/92378268-d641fa00-f105-11ea-9a9c-f0e22ab61509.png">

https://jxnblk.github.io/colorable/demos/text/?background=%23efefef&foreground=%23979899

**Comment by afbora** [comment]
Agree with @nilshoerrmann The opacity is too much and almost unreadable 😵

**Comment by bastianallgeier** [comment]
@afbora this is probably an easy fix. Would you like to take care of it?

**Comment by afbora** [comment]
@bastianallgeier Of course, do we prefer high opacity (like `opacity: .7;`, current `.4`) or complete removal?

**Comment by bastianallgeier** [comment]
If an opacity of .7 leads to a good contrast, I think it would be good to go this way.

**Comment by bastianallgeier** [comment]
✅
