### ISSUE TITLE
People like - Version notice in the panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#281]
http://forum.getkirby.com/t/update-core-from-the-panel/1239

Version number + update notice in the panel. Should probably be optional by config. Maybe an info lightbox for version numbers and license key other and info.

**Comment by bastianallgeier** [comment]
Versions are now mentioned in the panel and I am still not entirely sure about the update notification. I'm closing this for now. In general please make sure to add issues to the right repository. In this case it would belong to the panel repo.
