### ISSUE TITLE
Query templates do not work for default values in non-textarea fields

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2814]
**Describe the bug**  
According to the[ release notes of Kirby 3.2.5](https://github.com/getkirby/kirby/releases/tag/3.2.5), it should be possible to use query templates in blueprints in labels, default etc. However, turns out that trying this doesn't really work, at least not in current versions, see this issue in the forum for details: https://forum.getkirby.com/t/query-number-field-of-parent/19303/4

**Expected behavior**  
Query templates should work as promised ;)

**Screenshots**  

**Kirby Version**  
I actually tested with 3.3.6, but should be the same in recent versions.

**Comment by afbora** [comment]
Because the fields that do not work are processing/overriding the default value on `computed` method.

**Comment by distantnative** [comment]
We added some more in recent years, but it's not fully supported everywhere yet. Moving this though as feature request over to https://feedback.getkirby.com/655 to keep a better overview.
