### ISSUE TITLE
Cannot redeclare dump()

### ISSUE THREAD

**Issue by mattlenz** [getkirby/kirby#2816]
Using [Psy Shell](https://psysh.org/) with Kirby is proving super useful for admin tasks, migrations and general debugging.

However because psy defines it's own function named `dump` (used for inspecting variables/objects in the REPL), we run into an error when trying to bootstrap kirby inside the shell.

```
Psy Shell v0.10.4 (PHP 7.4.10 — cli) by Justin Hileman
>>> require 'kirby/bootstrap.php'
PHP Fatal error:  Cannot redeclare dump() (previously declared in phar:///usr/bin/psysh/vendor/autoload.php:21) in <snipped>/kirby/config/helpers.php on line 147
```

I can get around this by commenting out the `dump` function declaration in `/kirby/config/helpers.php` temporarily. But I wonder if this could be solved by wrapping that declaration in `if(!function_exists('dump')) {}`.

Is this something worth changing? `dump` is the only globally defined function that causes such a conflict.

**Comment by texnixe** [comment]
We have had this discussion before, because other have run into this as well: see https://github.com/getkirby/kirby/pull/2341#issuecomment-562938549

**Comment by mattlenz** [comment]
Thanks for pointing that out @texnixe - I can see this has been brought up before so feel free to close if there is still no intention to address this.

A bit disappointed to read that a fix isn't on the cards, but I can just workaround it on this end! :)

**Comment by bastianallgeier** [comment]
It's good that this comes up again. I think it's easy to fix and I don't know why we shouldn't do it.

**Comment by bastianallgeier** [comment]
✅
