### ISSUE TITLE
Pages Extension Ignores Parents for Nested Pages (Wrong ID/URL)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2817]
**Describe the bug**  
When using the [Pages extension](https://getkirby.com/docs/reference/plugins/extensions/pages) type with a "nested" page, the resulting page will have no `parent` property set.

**To Reproduce**  
```php
Kirby::plugin('my/plugin', [
    'pages' => [
        'blog/new-page' => new Page([
            'slug'     => 'new-page',
            'template' => 'virtual',
            'content'  => [
                'title' => 'Hello'
            ]
       ])
    ]
]);
```

The resulting page incorrectly thinks it has no parent, thus it reports that it's `id()` is `new-page` instead of `blog/new-page` (and that the `url()` is `example.com/new-page`).

**Expected behavior**  
The resulting page is available at `blog/new-page` and should report that it's `id()` is `blog/new-page`.

**Kirby Version**  
`3.4.2`

**Additional context**  
Because Kirby isn't fully loaded, you **cannot** do something like:
```php
Kirby::plugin('my/plugin', [
    'pages' => [
        'blog/new-page' => new Page([
            'slug'     => 'new-page',
            'parent' => page('news'), // Kirby not fully loaded; this cannot be used
            'template' => 'virtual',
            'content'  => [
                'title' => 'Hello'
            ]
       ])
    ]
]);
```

But, as a workaround, you **can** use:
```php
Kirby::plugin('my/plugin', [
    'hooks' => [
        'system.loadPlugins:after' => function () {
            kirby()->extend([
                'pages' => [
                    'blog/new-page' => Page::factory([
                        'slug' => 'new-page',
                        'parent' => page('news'),
                        'template' => 'virtual',
                        'content'  => [
                            'title' => 'Hello'
                        ]
                    ]),
                ],
            ]);
        }
    ],
]);
```

**Comment by distantnative** [comment]
I assume from your example, a page `blog` with actual pages (content file based, not virtual) exists - and you are trying to insert a virtual page alongside the normal pages via the extension. Did I get this right?

**Comment by neildaniels** [comment]
In the example, yes, `blog` is a real page with real subpages of its own.

I am _not_ trying to "insert" a virtual page as a child; in other words, I do not want it to show up in an iteration of `for (page('blog')->children() as $child)`.

But, I do want it to be **nested** and returned if someone goes to `example.com/blog/new-page`. In the current code, I believe something like `page('blog/new-page')` will also return the page. (Side note: `page('blog')->children()->get('new-page')` would not work, even though I would expect it to.)

https://github.com/getkirby/kirby/blob/c77ccb82944b5fa0e3a453b4e203bd697e96330d/src/Cms/Pages.php#L309-L320

The crux of this issue is that extension-defined pages seemed to never account for the idea that they would be nested beyond a top-level page.

**Comment by distantnative** [comment]
It sounds to me that you are trying to achieve something inherently conflicting:
- virtual page should not be a child of, e.g. `blog`
- virtual page should be nested inside e.g. `blog` as `blog/test-a`

I don't think this will work as Kirby isn't designed to allow for nested pages that aren't children. Kirby assumes that children are nested and all nested are children.

**Comment by neildaniels** [comment]
They do seem somewhat conflicting, but I thought this was the intended functionality of the extension-defined pages.

For example, even if I defined a top-level `foo` page in an extension, it wouldn't appear in `site()->children()`. In other words, it's _not_ a child of the site, but the site _is_ a parent to the page.

I wouldn't against having virtual pages be legitimate children of a parent, but that would actually be a departure from current behavior. (The "not actually a child" behavior has been helpful for me to create one-off pages that I don't have to worry about being treated as normal pages that would normally get included in my sitemap, for example.)

**Comment by distantnative** [comment]
I think that's rather an unintended behaviour - @lukasbestle and @bastianallgeier, your thoughts?

**Comment by lukasbestle** [comment]
> I don't think this will work as Kirby isn't designed to allow for nested pages that aren't children. Kirby assumes that children are nested and all nested are children.

I agree. I think it's really difficult to do this as Kirby relies on this structure.

Possible alternative: The virtual page could be made a draft so it doesn't show up in `$site->children()`. Or of course it's always possible to use filters, e.g. in a Kirby [collection](https://getkirby.com/docs/guide/templates/collections).
