### ISSUE TITLE
[Cms + Panel] Implement blueprint page icon

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#282]

**Comment by bastianallgeier** [comment]
It might be a massively stupid idea, but how about emojis instead of icons? I actually really like them in Notion and feel like they are adding a nice touch and would probably be easy to implement. I'm just not sure if it's too hipsterish or not serious enough for a VERY SERIOUS system.

**Comment by distantnative** [comment]
I'd be in for also emojis, but not only. I think in most of my own projects, I'd prefer simple flat white icons on dark background instead of emojis. And the customers too.

**Comment by bastianallgeier** [comment]
Ok, then let's take emojis as an extension to the icon set.

**Comment by bastianallgeier** [comment]
I found a pretty cool idea how to create a vue icon system in their cookbook btw: https://vuejs.org/v2/cookbook/editable-svg-icons.html

**Comment by distantnative** [comment]
But didn't we want not to have inline svg icons, so they can be cached?

**Comment by bastianallgeier** [comment]
@distantnative we should probably go for an svg sprite. But that should be in another issue and more like part of the beta.
