### ISSUE TITLE
Front page button missing in the panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#282]
http://forum.getkirby.com/t/where-is-the-front-end-button-in-the-panel/1272

Panel - It's great to have "Open preview" on the page you are editing.

**Front end - Always one click away**

I would suggest that when in the panel, the front end should always be only one click away. Maybe just a house icon on the top.

**Comment by bastianallgeier** [comment]
I moved this to the panel issues: https://github.com/getkirby/panel/issues/649
