### ISSUE TITLE
files section is above the gray-transparent blocking layer of a blocked panel page

### ISSUE THREAD

**Issue by nimi09** [getkirby/kirby#2821]
**Describe the bug**  
A panel page is blocked for a second user because an other user is currently entering data. the panel page consist of two columns, the second column has two sections, first a fields section and a second files section.

Everything is hidden behind a gray layer to indicate that entering content is blocked, except the files section on the second column, it floats above the gray transparent layer, and it seams that it would be possible to add files -> and it actually is possible to add files!

**To Reproduce**  
use the following blueprint:

columns:
  - width: 2/3
    fields:
      text:
        type: textarea

  - width: 1/3
    sections:
      sidebarfields:
        type: fields
        fields:
          cover:
            label: Cover
            type: files

      files:
        label: Files
        type: files

1. login in with a user and enter some text to the page, but don't save the content
2. login with an other user and try to edit the same page
3. Scroll down to so that you can see the files section
4. See error => the files section should float above the gray-transparent blocking-layer and should be able to accept files, which than will be uploaded

**Expected behavior**  
I expect all sections of all columns to be behind the gray transparent "block"-layer, and that it is not possible to upload files to a blocked panel page.

**Screenshots**  

**Kirby Version**  
Kirby 3.4.0

**Console output**  

**Desktop (please complete the following information):**  
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by distantnative** [comment]
Why would it not be possible to edit or add files?
The lock is about the content file that is currently edited by another user. So all fields will be disabled (grayed out) but pages and files sections can still operate as they are not tied to what the other user is editing.

**Comment by nimi09** [comment]
Although it looks wrong for a normal editor that a blocked user can manipulate files, I could understand that it could be possible to add files and that this could be useful for a collaborated workflow.

But if the content accepts a selectable cover image (like in the submitted blueprint), which the second user (the blocked user) can delete from the files section, than the displayed content would be broken.

For me it would feel more coherent if a panel page is blocked completely for a second (blocked) user.

**Comment by bastianallgeier** [comment]
I get why it might seem weird, but you have to think about it also from a navigation perspective. When we block files and pages sections as well, you are no longer able to navigate to files views or to subpages. That's quite a big issue.
