### ISSUE TITLE
DB where Callback Bug

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#2831]
**Describe the bug**  
Using a callback in the where clause takes on everything defined in the query.
```php
$query->where('id', 1);
$query->where(fn ($q) => $q->where('status', 0));
```
Will produce something like this:
```sql
WHERE id = :value_1
AND (
    id = :value_1
    AND status = :value_2
)
```
The problem is that the binding is cloned as well and PDO allows a binding to be used only once.
Following error will be thrown `SQLSTATE[HY093]: Invalid parameter number: parameter was not defined`.

The reason for that is probably the clone [here](https://github.com/getkirby/kirby/blob/7525553b8d9976d6ed08b702f62fc3d368116777/src/Database/Query.php#L970). Not sure if this should simply be a new query instance or if there is actually some stuff that needs be cloned.

**Kirby Version**  
3.3.5

**Comment by lukasbestle** [comment]
✅
