### ISSUE TITLE
Users blueprint field main text attribute not working in the modal add dialog

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2832]
When you add a `users`-field to your blueprint, you can use the `text:`-attribute to configure what the main text for each item should like like. For example, you can say `text: {{ user.name }} {{ user.email }}` to show both values, name and email, as the item's text. So far, so good. 

What is not working: When you click the Add-Link and the modal dialog appears to select an user item, it doesn't show you the item text as specified by the `text:`-attribute. In fact, the `text:`-attribute is ignored, and just the user's name is displayed. This is not consistent and from my point of view, a bug. 

In my case i have a site where there are 1.000+ users and we have the first users with identical (common) names. I need to use the `text:`-attribute to be able to see who is who.

Example of the Add dialog:

![image](https://user-images.githubusercontent.com/2129515/93490479-cf3a9900-f908-11ea-847f-eb02f8c0e3e4.png)

Please, make the add dialog use the same setting from the `text:`-attribute.

Trying with the `info:`-attribute is the same problem. In the main view `text:` and `info:` is working, but both are ignored in the add-view.

**Comment by afbora** [comment]
if I understand it correctly: what about using `info` property?

```yaml
text: {{ user.name }} 
info: {{ user.email }}
```

**Comment by afbora** [comment]
We can use `ìnfo` property for this.

**Comment by andreasotto** [comment]
Like said, the `info` property is not working, too. Both `info` and `text` properties are **not working** in the **add dialog**. 

From my point of view, it's not an enhancement but a bug. There is no possible workaround.

**Comment by bastianallgeier** [comment]
✅
