### ISSUE TITLE
Bug: User profile picture upload shows an error if you change the file format.

### ISSUE THREAD

**Issue by philekiert** [getkirby/kirby#2834]
Hi guys, I've noticed that uploading a profile picture that's a different format that the previous image produces an error, succeeds in uploading the new image but doesn't refresh the page so it looks like it hasn't worked.

**Steps to reproduce the behavior:**
1. Go to 'Your account' page on the panel.
2. Try to upload a new image that's a different file format to the current image.
4. You'll see the error: "File not found: /home/.../kirby/media/users/dBF6s24C/6a3df49f0a-0/profile-512x.png".

Confirmed by a second user [here](https://forum.getkirby.com/t/file-not-found-home-blablabla-profile-512x-jpg-when-changing-profile-picture-format/19349).

**Expected behavior**  
Any functional image should work without this error.

**Kirby Version**  
3.4.2. Bug is present in unmodified plainkit.

**Console output**  
app.js:1 POST http://#.#.#.#:8000/api/users/dBF6s24C/avatar 400 (Bad Request)

**Comment by bastianallgeier** [comment]
✅
