### ISSUE TITLE
Verry slow loading times of the panel

### ISSUE THREAD

**Issue by N247S** [getkirby/kirby#2836]
**Describe the bug**  
I am struggling with the verry slow loading times of the panel. So I decided to do a clean install and check what the time would be for loading the panel when its (sort of) empty. So here are the results/data in an attempt to create a clear view of what the issue might be.

Without any modifications it takes around 15-20 seconds to fully load the panel on a local server run by the vsc-plugin _'PHP Server'_ by _Brais Piñeiro_

**To Reproduce**  
1. Clean install of Kirby (using the 'plain kit')
2. run the kriby installation on a local server with vsc-plugin _'PHP Server'_ by _Brais Piñeiro_
3. login to the panel, and wait

**Expected behavior**  
At least a little bit faster load time since its verry frustrating to navigate through pages (as they have to be loaded first before you can click them for further navigation).

**Screenshots**  
![image](https://user-images.githubusercontent.com/10078398/93664700-29ef0480-fa71-11ea-9d5f-54c7303b4585.png)

**Kirby Version**  
Kirby version: 3.4.3
PHP version: 7.4.3
VSCode version: 1.49
PHP Server plugin version: v3.0.1
OS: Windows 10
Browser: google Chrome

**Console output**  
None in browser, none in server logs

Any ideas in solving this are welcome.
If additional information is required, feel free to ask

**Comment by lukasbestle** [comment]
It definitely shouldn't be that way – on my machine the Panel takes about 100-300 ms to load completely.

Unfortunately it's hard to debug this issue as we cannot reproduce this without your exact setup. Have you tried using a different local server like XAMPP etc. to rule out the VSCode plugin you are using?

**Comment by bastianallgeier** [comment]
I also think that this is an issue of the VSCode plugin. I also recommend to use MAMP or XAMPP as an alternative.

**Comment by N247S** [comment]
Funny enough, I clean installed the latest version of PHP [7.4.10] (in preperation to install XAMPP). That seems to fix this issue... So either some config was messed up in the _PHP.ini_, or there was a bug in that specific PHP version.

Thanks for hinting to MAMP/XAMPP btw. When I got time I'll try it out!
