### ISSUE TITLE
$dst = $template

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/kirby#2839]
Hey there,
it might be hard to understand looking at the core `thumb` method that by calling `Filename`, we want it to return a path string (the destination path), but pass `$dst` as second parameter - this should actually be `$template`, if I am not mistaken .. maybe I just don't get it ;)

https://github.com/getkirby/kirby/blob/7525553b8d9976d6ed08b702f62fc3d368116777/config/components.php#L316

**Comment by bastianallgeier** [comment]
You mean it would help to rename the variable for the sake of clarity?

**Comment by S1SYPHOS** [comment]
Yeah, I guess I do - clarity's a good thing when it comes to code you're not greatly familiar with!

**Comment by bastianallgeier** [comment]
✅  I just fixed this
