### ISSUE TITLE
Links with same URL as text in markdown are badly generated

### ISSUE THREAD

**Issue by iamvdo** [getkirby/kirby#284]
Markdown sample:

```md
This is a link to [http://google.fr](http://google.fr)
```

Kirby 1 generates: `This is a link to <a href="http://google.fr">http://google.fr</a>`
Kirby 2.1 generates: `This is a link to <a href="http://google.fr"></a><a href="http://google.fr">http://google.fr</a>`

I know I should use `This is a link to <http://google.fr>`, but I don't get why there is a difference between Kirby 1 & 2.

**Comment by lukasbestle** [comment]
The difference is that Kirby 2 uses a completely different Markdown parsing library (Parsedown).

There is already a very similar issue over at the [Parsedown repo](https://github.com/erusev/parsedown/issues/167). It was closed but it seems like the same issue still exists. Please post a comment over there.

But yeah, using the `<http://google.fr>` syntax is simpler anyway. ;)
