### ISSUE TITLE
Non-image files show broken dimensions and orientation info in Panel

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2842]
**Describe the bug**  
Dimensions and orientation are displaying nonsense:
<img width="1119" alt="Screen Shot 2020-09-24 at 09 19 19" src="https://user-images.githubusercontent.com/3788865/94108008-34c9e080-fe47-11ea-97e8-117209a75959.png">

**Comment by bastianallgeier** [comment]
✅
