### ISSUE TITLE
Error when saving email address: Navigating to current location (\"/users/<user_id>\") is not allowed

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2845]
**Describe the bug**  
Changing the email address of an users causes an error.

**To Reproduce**  
1. Go to any admin user
2. Change email address and confirm the dialog
3. See Firefox browser console:

```
Uncaught (in promise) 
{…}
​_name: "NavigationDuplicated"
message: "Navigating to current location (\"/users/<user_id>\") is not allowed"
name: "NavigationDuplicated"
```

**Expected behavior**  
No error thrown.

**Kirby Version** 
updated Kirby v3.4.0 to v3.4.3

**Console output**  

**Desktop (please complete the following information):**  
Windows 10, latest Firefox, WAMP

**Additional context**  
multilang setup with just 1 language.

**Comment by bastianallgeier** [comment]
The good news: this is just a stupid warning from the Vue router that can be safely ignored. 
But we should still catch it.

**Comment by bastianallgeier** [comment]
@afbora I don't think it's a regression. It's not breaking anything. Vue router is acting very stupidly here (see many complaints in their issues) and this shouldn't be a warning at all. Why would navigating to the same URL be an error??

**Comment by GiantCrocodile** [comment]
@bastianallgeier I think it is a regression somehow because I didn't see this warning in the past and I updated my Kirby installation. So maybe not a regression of Kirby itself but some dependency in its core.

**Comment by bastianallgeier** [comment]
✅
