### ISSUE TITLE
API endpoints do not return drafts

### ISSUE THREAD

**Issue by pwaldhauer** [getkirby/kirby#2846]
**Describe the bug**  

- `GET /api/pages/:id/children` does only return listed and unlisted pages 
- `GET/POST /api/pages/:id/children/search` does only return listed and unlisted pages and it's not possible to get drafts via `filterBy`

**Expected behavior**  

- The endpoints should have another query parameter that instructs them to return draft posts

**Kirby Version**  
all

**Additional context**  

(Maybe I should submit this as a feature request? But... it could also be a bug, because I think the expected behaviour would be to also return drafts 😓 )

**Comment by afbora** [comment]
I agree. The route can be modify like this. 

    /api/pages/:id/children/(:status?)

If you need a temporary solution, you can try querying on the sections: `/api/pages/notes/sections/drafts` 🤔

**Comment by bastianallgeier** [comment]
I think it's fine to add this as a bug.

**Comment by bastianallgeier** [comment]
It would be great to get your feedback on the implementation. There are two ways this could be done: 

### Multiple endpoints
```
/api/pages/:id/children/
/api/pages/:id/drafts/
/api/pages/:id/children-and-drafts/
```
This would replicate what we have as PHP methods. 


### A single endpoint
```
/api/pages/:id/children/?status=listed
/api/pages/:id/children/?status=unlisted
/api/pages/:id/children/?status=published (listed + unlisted)
/api/pages/:id/children/?status=draft
```

**Comment by afbora** [comment]
I think it would be great if both.

**Comment by pwaldhauer** [comment]
@bastianallgeier I think I'd like the second, single endpoint one better -- assuming that it will also include a `?status=all` that returns listed, unlisted and draft (like the children-and-draft endpoint above). But I'll also be fine with multiple endpoints. Thanks for your quick support!

**Comment by bastianallgeier** [comment]
3.4.4 has a new status query param for `site/children` and `pages/$pageId/children` now. The status can be (all, listed, unlisted, published, drafts)

**Comment by lukasbestle** [comment]
@bastianallgeier Shouldn't it be `draft` (singular)?

**Comment by lukasbestle** [comment]
Ah, I see it supports both. 👍

**Comment by bastianallgeier** [comment]
I couldn't decide, so I thought it's good to have both.

**Comment by mmahler2** [comment]
https://getkirby.com/docs/reference/api/pages/children-list
Should update the docs when you get around to it! This had me stumped for quite a while.
