### ISSUE TITLE
FileView: search results from other parent model lead to console error

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2849]
**Describe the bug**  
If I am on a FilewView with parent page A and I search for files and click on a file with parent page B, I'll get a console error

**Screenshots**  
![2843](https://user-images.githubusercontent.com/3393422/94178835-4d1c1880-fea4-11ea-9917-2e1f08c27d0c.gif)

**Kirby Version**  
3.4.3

**Console output**  
Failed GET to http://localhost:8080/api/pages/portfolio+projects+ocean/files/desert-tree.jpg/sections/content 404 (Not Found)

» the model id in this URL is already of the target page, the file id still of the previous/current file

**Comment by bastianallgeier** [comment]
✅
