### ISSUE TITLE
Tags with accents are not recognized

### ISSUE THREAD

**Issue by inacho** [getkirby/kirby#285]
Tags with accents are not recognized.
Example:

**/site/tags/atencion.php**
```php
kirbytext::$tags['Atención'] = array(
    'html' => function($tag) {
        return '<div class="uk-alert uk-alert-warning">Atención: ' . $tag->attr('Atención') . '</div>';
    }
);
```

**Comment by bastianallgeier** [comment]
To be honest I would prefer to keep it that way. Tags are for me more in a spirit of variables or other method/function names and accents or other special characters are not allowed there either. I think this would decrease the performance of the regular expression and it would also leave room for additional encoding issues. Therefor I'd prefer to not solve it this way. Thanks for your pull request though!
