### ISSUE TITLE
Open site - Is it the correct icon?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#286]
The "Open site" icon is an eye. It make sense now, but if you implement a live preview switcher later, that eye icon could be perfect for that instead?

Maybe a link or external link icon for "Open site" could be more future proof?

![image](https://user-images.githubusercontent.com/927011/37838696-e48eced8-2eb8-11e8-95b7-3acf97431885.png)

**Comment by distantnative** [comment]
That was a bug, fixed in Alpha 7. ✅
