### ISSUE TITLE
Display Bug in GUI in checkboxes field

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2866]
3.4.3 
I have a `checkboxes`-Field which has 833 entries.
The first part looks okay, but suddenly the rows are overlapping each other resulting in this view.

The last lines are all printed on top of each other. The HTML Code is OK (`<li>` items).

![image](https://user-images.githubusercontent.com/2129515/94574512-845b4280-0273-11eb-821e-1ec75343164b.png)

**Comment by distantnative** [comment]
Could you please provide some info on your browser, OS...? Thanks!

**Comment by andreasotto** [comment]
MacOS Catalina 10.15.7 (current)
Chrome Version 85.0.4183.121 (current)

**Comment by afbora** [comment]
I can reproduce too on last two rows for 1000 entries. You can see 999 and 1000 are on same row. I tested 750 items, the issue does not appear.

![screen-capture-315-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/94672443-f25c4400-031d-11eb-8555-a75bc3ea9318.png)


Windows 10
Chrome 85.0.4183.121

**Comment by bastianallgeier** [comment]
This must have been a browser bug. I can no longer reproduce it in Chrome 94

**Comment by afbora** [comment]
I can still reproduce on Chrome 94.0.4606.81 (3.6.0-beta.1)

**Comment by bastianallgeier** [comment]
Then it is a Chrome bug in Windows. I have no idea how we should be able to fix this. I also think it's a very rare edge case. I'd argue that a checkbox field should not have 800+ entries in the first place. The multi-select field would be a better choice here.

**Comment by afbora** [comment]
Actually you're right. I can't reproduce on Firefox and Windows 10.
