### ISSUE TITLE
[Cms] Add `page.loading:before` hook

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#287]
Could be an alternative to a site controller (#212), e.g. for #224

**Comment by jenstornell** [comment]
The hooks would need to move from the panel repo to the Kirby repo, because some hooks would run no matter if the panel is used or not. Correct?

If we go with this approach I think we need access to the page object in the hook.

**Comment by distantnative** [comment]
All hooks run in the Cms not the panel. All hooks are triggered also by the API or if you do something in a controller etc.

**Comment by jenstornell** [comment]
@distantnative Good.

When thinking more about it, I think both a **site controller** and a page.loading:before **hook** would be good to have for different things.

The site controller would be good for sending like global variables to the templates. The hook would be good for doing something on conditions, like redirect a page if `date > now` for example.

So I think both have their own purpose. Therefor I hope to see both in the future.

**Comment by bastianallgeier** [comment]
✅ The new `route.before` hook solves this.
