### ISSUE TITLE
Pull from session

### ISSUE THREAD

**Issue by Vinze** [getkirby/kirby#287]
Instead of doing the following:

```php
if ($value = s::get('key')) {
    s::remove('key');
   // do stuff
} else {
    // do something else
}
```

Wouldn't it be cleaner and easier to be able to do the following?

```php
if ($value = s::pull('key')) {
   // do stuff
} else {
    // do something else
}
```

The pull function will first return the value by key (if any), and then remove it from the session.

**Comment by bastianallgeier** [comment]
Is this a common task? I can't think of a single use case right now, but maybe I am missing something.

**Comment by Vinze** [comment]
I'm using it in my contact forms like this:
```php
// contact controller:
s::set('email_send', true);
go('thanks-for-contacting-us');

// config.php (routes):
array(
	'pattern' => 'thanks-for-contacting-us',
	'action'  => function() {
		if (s::get('email_send')) {
			s::remove('email_send');
			return page('thanks-for-contacting-us');
		} else {
			go('contact');
		}
	}
),

```

And now I'm building a wizard with multiple steps, and I keep retrieving and removing data from the session. Not that it's a big problem, but it saves a line of code and I think it's cleaner. [Laravel](http://laravel.com/docs/4.2/session) has a similar function and I use it quite often.

**Comment by bastianallgeier** [comment]
Now I get it :) I just added it to the toolkit and the core (develop branch)

**Comment by Vinze** [comment]
Awesome, thanks!
