### ISSUE TITLE
Extending $isViewable (inside FileFoundation)

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/kirby#2870]
As another follow-up to #2840, shouldn't we at least include some new formats as being viewable in the panel? Or rather as a question: what does that mean, being viewable - isn't it more of a browser thing?

Cheers,
S1SYPHOS

**Comment by distantnative** [comment]
We need `isViewable` to know whether we can display a preview in the Panel (e.g. via `<img>` tag) or not, e.g. for a `.docx` file So it's not really a decision by the browser cause it also matters first how we put out the markup for the respective file.

So for now we only mark formats as `isViewable` that are widespread supported by all browsers the Panel supports. I'm not sure about the experience if we add those new formats and they are rendered in the Panel but then viewed in a browser that doesn't support them.

**Comment by S1SYPHOS** [comment]
> (...) So for now we only mark formats as `isViewable` that are widespread supported by all browsers the Panel supports.

Which boils down to being 'a browser thing' :fox_face: 

> I'm not sure about the experience if we add those new formats and they are rendered in the Panel but then viewed in a browser that doesn't support them.

I will apply some experiments and get back at you - I'll check `j2k`, `jp2` & especially `avif`. Thanks for your time & effort, Nico!

**Comment by distantnative** [comment]
> Which boils down to being 'a browser thing' 🦊

I understood this as "a thing the browser can decide on its own" - and that's not true for all file formats (e.g. `docx` - there we need to make the call beforehand what the Panel should "try to view")

**Comment by distantnative** [comment]
If you can do these experiments and report back especially what happens if you add `avif` to `isViewable` and then try to see it in a browser that doesn't support it - that would help loads!

**Comment by S1SYPHOS** [comment]
You know what time it is .. positive feedback time!

## Test
Testet with v3.4.4.rc1

### AVIF

**Firefox**
AVIF not enabled: no image, no dimensions, wrong MIME and no placeholder image
![Screenshot_2020-10-03 fundevogel avif Site Title](https://user-images.githubusercontent.com/12161504/94991399-38fea800-0583-11eb-91e0-ed5cc472eead.png)

AVIF enabled: image, no dimensions, wrong MIME and no placeholder image
![Screenshot_2020-10-03 fundevogel avif Site Title(1)](https://user-images.githubusercontent.com/12161504/94991398-37cd7b00-0583-11eb-97fe-4b65b56156be.png)

**Chrome < 85**
Same as disabled FF

**Chrome 85**
Same as enabled FF

### J2K
no image but data placeholder, no dimensions, wrong MIME, no placeholder
![image](https://user-images.githubusercontent.com/12161504/94998016-4762b900-05af-11eb-94aa-3038cf853109.png)

### JP2
no image, correct dimensions, correct MIME, no placeholder
![image](https://user-images.githubusercontent.com/12161504/94998007-387c0680-05af-11eb-9798-a545f54a770f.png)

## Conclusion
Safe for early birds who want to work with AVIF / J2K / JP2, imho.

Maybe we can replace PHP's `getimagesize` in order to provide better results regarding dimensions?

**Comment by S1SYPHOS** [comment]
@distantnative I added further information, as requested. Nothing too serious .. people using AVIF know what they are doing/viewing ..

**Comment by distantnative** [comment]
@S1SYPHOS just to confirm: those are the results after you added all three formats to `isViewable()`?

**Comment by S1SYPHOS** [comment]
Well, I'm an idiot .. I forgot to add `j2k` and `jp2` - adding them results in no placeholders, no image just like AVIF

 // Update: I replaced the false information!

**Comment by distantnative** [comment]
:D ok that makes more sense then to me :D

Ok I'm torn, on the one hand I think it would be better to show the preview icon instead of a broken image element.  On the other hand do people who upload AVIF files probably know what the are doing, using a browser that supports it ...

**Comment by S1SYPHOS** [comment]
Right now `avif` files are progressive enhancement. With Chrome 85 we will see 70/80% coverage within a short time frame. I get that only AVIF will get there; the other two might never be viewable :confused: 

That being said, as they are recognized and get a placeholder, that's alright. AVIF should at some point be added, though. And since there's no harm, why not now? I'm already running Chrome 85 and AVIF works just fine.

**Comment by S1SYPHOS** [comment]
Your call!

**Comment by lukasbestle** [comment]
✅
