### ISSUE TITLE
[Text] Round Brackets in Kirby Tags

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/kirby#288]
From time to time I run into the problem that round brackets are not possible in Kirby Tags.

Two *common* examples:

`(image: simpsons.jpg caption: Marge (mother), Homer (father))`
=> `Marge (mother`

`(link: file.pdf text: Download (PDF))`
=> `Download (PDF`

Would it be possible to optionally put text into quotes which then outputs everything between the quotes? Like so:

`(link: file.pdf text: "Download (PDF)")`
=> `Download (PDF)`

**Comment by jenstornell** [comment]
It looks like a good solution to that problem.

If you run into this problem a lot now, you can try out https://github.com/jenstornell/kirby-shortcode in the meantime. It uses brackets `[]`, so the parentheses does not collide.
