### ISSUE TITLE
Sortable Files Section Should Set "Sort" Automatically for New Files

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2886]
**Describe the bug**  
When I files section is sortable, I find it odd that a "sort" num isn't automatically set for files on upload. 

**To Reproduce**  
1. Have a sortable files section in a Blueprint
2. Upload a file called `foo.jpg`
3. Upload a file called `bar.jpg`

**Expected behavior**  
The upload files have no `sort` value, so the Files section reverts to the sorting them by filename. Thus, the order of files in the section shows as:
1. `bar.jpg`
2. `foo.jpg`

I would have expected the first file (`foo.jpg`) to be first.

**Kirby Version**  
`3.4.4`

**Additional context**  
If you already have pre-sorted files, newly uploaded files appear at the beginning of the files section (effectively like their "sort" num is `0`). If you uploaded multiple new files, they'll be sorted by filename (as described above), but still before previously sorted files.

I can certainly see some people prefer "new" files to be added at the beginning of a files section, but that should be accomplished by a setting that forces new files to get a `1` sort value (and re-numbering the other files). I would expect the default behavior to to be: new files receive a sort num of 1 _higher_ than the previous highest sorted file.

**Comment by nilshoerrmann** [comment]
We noticed on an install that while the panel showed newly uploaded files in alphabetic order, the server seemed to return files in upload order if no sorting number was stored. This can be very strange if you upload multiple files in bulk and the individual upload times determine the sorting.

We expected panel and server side to work the same in this context and also prefered the immediate storage of sorting numbers on upload.

**Comment by bastianallgeier** [comment]
✅
