### ISSUE TITLE
Structure Element: wrong items gets deleted (3.4.4)

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2887]
In a structure list with several pages the wrong item is deleted!

To reproduce:

Switch to the second or third page and delete an item from the list. Result is: The item get's not deleted, but instead an item from the first(!) page disappeared.

**Comment by afbora** [comment]
I can't believe this isn't working. I tried it up to 3.3.3 and it really doesn't work :hushed:. 

The source of the issue; If there is pagination, it deletes it independent of the page number.

**Comment by bastianallgeier** [comment]
Wow! I can't believe that @andreasotto is the first to report this.

**Comment by bastianallgeier** [comment]
✅
