### ISSUE TITLE
Locale option doesn't work if array and key string for single language 

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2893]
**Describe the bug**  
`locale` option doesn't work if array and key string for single language.

I don't think this is a bug. Because it works without string (`LC_ALL` constant works great). This place doesn't seem to work because we support strings (with auto convert) in the other part that `Language` class. We can also enhance this part.

**To Reproduce** 

Single language app

````php
// /site/config.php
'locale' => [
    'LC_ALL' => 'tr'
]
````

But same `locale` option works for multilingual app

````php
// /site/languages/tr.php
'locale' => [
    'LC_ALL' => 'tr'
]
````

**Screenshots**  
![screen-capture-384-Kirby CMS Debugger-localhost](https://user-images.githubusercontent.com/3393422/95676110-8bb01380-0bc4-11eb-87b9-8eeb4fb2d9ae.png)

**Kirby Version**  
3.3.3+ & 3.4.x

**Comment by bastianallgeier** [comment]
✅
