### ISSUE TITLE
Email: `security: true` doesn't work since Kirby 3.4.0

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2896]
Sending email to a remote server (not localhost) fails since version 3.4.0 and above. Kirby 3.3.6 is working with the same settings without any problems.

Settings:
```
return [
  'email' => [
    'transport' => [
      'type' => 'smtp',
      'host' => 'remote.server.de',
      'port' => 465,
      'security' => true,
      'auth' => true,
      'username' => 'theUsername',
      'password' => 'secretpassword',
    ]
  ]
];
```

When git submodule switching between 3.3.6 (working) and 3.4.0 up to current 3.4.4. you can see the difference.

The error is:

After a long timeout (between 1 or 2 minutes) the following error occurs: 
```
PHPMailer \ PHPMailer \ Exception
SMTP Error: Could not authenticate.
```

in 3.4.4:
```
PHPMailer\PHPMailer\Exception 
…/vendor/phpmailer/phpmailer/src/PHPMailer.php2035
```
![image](https://user-images.githubusercontent.com/2129515/95846792-238c3980-0d4c-11eb-87ac-0fd4700901f4.png)

Switching back to 3.3.6 fixes the problem and the mail is sent without any delays.

Sending mails to smtp localhost is no problem in any version. So it seems that only sending mails to a remote smtp server is buggy starting after 3.3.6.

**Comment by afbora** [comment]
Have you looked at this thread before?

https://forum.getkirby.com/t/kirby-email-smtp-error-timeout/19054

**Comment by andreasotto** [comment]
Switching to `'security' => 'ssl'` seems to solve the problem. That is a breaking change from 3.3.6+ versions (with 3.3.6 it works with `'security' => true`. I think it should work with the same settings in newer versions, too. The documentation from PHPMailer and Kirby contains that setting.

**Comment by lukasbestle** [comment]
I checked the changes between 3.3.6 and 3.4.0. The only thing we changed regarding email handling is to upgrade the PHPMailer library from 6.0.7 to 6.1.6.

What's weird is that the [PHPMailer reference](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#property_SMTPSecure) says that the `SMTPSecure` option (which is behind our `security` option) only supports an empty string (= off), `ssl` or `tls`. So `true` is not supported by them. Unfortunately I couldn't track down if this was different before and when it was changed.

But in any case, the question is how to fix this:

- Automatically translating `true` to one of the supported values will not work as there are two options (`ssl` and `tls`) and it's unclear which of them PHPMailer used before the change when `true` was passed. Also it would be confusing in the long run.
- In any case we need to update the docs to reflect the possible values.

**Comment by afbora** [comment]
This issue about phpMailer version. Because i have used before old phpMailer version as 6.0.7 on 3.4.x, worked great. There was a break between 6.0.7 and 6.1.6.

But I couldn't see an explanation or update too in the [phpMailer changelog](https://github.com/PHPMailer/PHPMailer/releases) that could cause this issue.

**Comment by andreasotto** [comment]
If there is no better technical criteria for a decision, what `true` should be translated to, there are maybe some "soft facts":

SSL has originally been developed by Netscape in 1995 and was implemented in many of the popular email clients at the time. Four years later, a new standard – TLS – was introduced, offering a more reliable security profile. I'd vote for choosing `tls` as the default fallback if `true` is found in the config. At the same time the documentation should be changed to make clear that there is no option `true`.

**Comment by distantnative** [comment]
Let’s not make a magic assumption here if there could be two options. Just makes it harder to track down problems for the ones using SSL.

We need to change docs. And then I’d add an Exception that clearly tells the developer to set it to either TSL or SSL

**Comment by GiantCrocodile** [comment]
There's not much to decide: SSL has been officially deprecated by RFC 7568 and violates industry standards and GDPR requirements. That's even partially true for older TLS standard versions. So you shouldn't (read: can't) use it anymore anyway.

**Comment by lukasbestle** [comment]
I agree with the two steps proposed by @distantnative!

**Comment by afbora** [comment]
> Automatically translating true to one of the supported values will not work as there are two options (ssl and tls) and it's unclear which of them PHPMailer used before the change when true was passed. Also it would be confusing in the long run.

@lukasbestle @distantnative I'm asking because I don't know very well.

Can't we automatically detect the `true` option? After all, this break has already happened. At least I think we can make the transition easier by convert it automatically.

Would it work if it was done this way on `security => true` cases? 🤔 

> If port is 465 use SSL
> If port is 587 use TLS
> Else throw exception

**Comment by lukasbestle** [comment]
@afbora That would work, yes! I'm not 100 % sure if the ports are only ever used with the respective protocol version (SSL or TLS), but in edge-cases it would still be possible to configure it explicitly with `'ssl'` or `'tls'`.

So I think this is a good step together with updated docs on this behavior and the `'ssl'` and `'tls'` values.

**Comment by afbora** [comment]
This is great news, thank you 🎉 

I did some research. In all the codes I have seen in many different sources, 465 for SSL and 587 for TLS are used. But I have read in a few articles that TLS and 465 port can be used together. But I guess it (port 465) was something like the sub / secondary port.

These usages are not the default, but I think they are almost near default. At least it's better than having a break. 

Even if the port is not specified (`port is null with security is true`), we can set the more reliable TLS as default?

I guess what I think is something like this:

````php
if ($secure === true) {
  if ($port === null || $port === 587) {
    $secure = 'tls';
    $port = 587;
  } elseif ($port === 465) {
    $secure = 'ssl';
  } else {
    // throw an exception or just pass it
    throw new Exception('You should set secure and port option!'); 
  }
}
````

**Comment by lukasbestle** [comment]
Yes, that logic sounds great! 👍

**Comment by bastianallgeier** [comment]
@afbora @lukasbestle looks like a great default to me as well.

**Comment by bastianallgeier** [comment]
@afbora could you take care of a PR for this?

**Comment by afbora** [comment]
Sure, but I guess @lukasbestle working on now?

**Comment by bastianallgeier** [comment]
Oh, right, I completely missed that he self-assigned him :)

**Comment by bastianallgeier** [comment]
✅
