### ISSUE TITLE
Updating a Page Breaks Snippets

### ISSUE THREAD

**Issue by Jayshua** [getkirby/kirby#2897]
**Describe the Bug**
Calling `$page->parent()->update()` during the rendering of a page causes snippets to no longer work.

**Steps to Reproduce**
1. Create a template which calls `->update()` on a page whose blueprint has a `num: '{{page.something}}'` declaration.
2. Notice that a `snippet()` call placed after the `->update()` does not have access to any of the standard `$site`, `$kirby`, etc. variables. If it tries to reference them, there is a "Call to a member function _______ on null" exception.

**My diagnosis**
After a bit of debugging I've found that `\Kirby\Cms\App->clone()` empties the `App` singleton's `data` property for some reason, which is what `App` [uses to populate the standard template variables](https://github.com/getkirby/kirby/blob/7525553b8d9976d6ed08b702f62fc3d368116777/src/Cms/App.php#L1364).

I have some code that calls `$page->parent()->update()` *occasionally* during the rendering of a page. (`$page`, in this case, is a virtual page with a custom model. But I don't think that makes a difference.) The parent being updated has a `num: '{{page.property}}'` declaration, which causes the `PageActions::createNum` method to be called during update, which in turn takes the [`default:` path in the switch statement and calls `$this->kirby()->clone()`](https://github.com/getkirby/kirby/blob/7525553b8d9976d6ed08b702f62fc3d368116777/src/Cms/PageActions.php#L548). After that call, the `data` property on the `\Kirby\Cms\App::instance()` singleton is empty. If I remove the `->clone()` bit, the `data` property remains as expected.

Working theory is that the `$data` property is populated somewhere other than the `__construct` method, which the `->clone()` method uses to create a clone. Since the `__construct` method also sets the `static::$instance` property, the new instance which will now be returned by a call to `App::instance()` doesn't have anything in its `$data` property.

**Kirby Version**  
3.3.6 and 3.4.4

**Comment by Jayshua** [comment]
Upon further thought I'm not sure it makes sense to `->clone()` the `\Kirby\Cms\App` instance because it's a singleton? So maybe the `->clone()` bit should just be removed completely?

**Comment by afbora** [comment]
This is known issue as #2555 and hope will be fix with https://github.com/getkirby/kirby/pull/2894

**Comment by lukasbestle** [comment]
As @afbora wrote, we have a fix for this upcoming that will be in Kirby 3.5.0. I'm therefore closing this issue as a duplicate.

@Jayshua It would help us tremendously if you could throw the code from #2894 at your local test installation to verify if it indeed fixes the bug. Thank you!

**Comment by Jayshua** [comment]
@lukasbestle The code from fix/2555-app-clone appears to fix this bug!
