### ISSUE TITLE
js()-helper does not set async option for arrays

### ISSUE THREAD

**Issue by danielbuechele** [getkirby/kirby#290]
I am using the `js()`-helper to create my JavaScript imports. The first parameter is an array of paths, the second is set to `true`. However, on the rendered page the `async`-attribute is not set.
See https://github.com/danielbuechele/kulturspektakel/blob/deploy/site/snippets/header.php#L41 for the implementation.

**Comment by lukasbestle** [comment]
The problem is [this line](https://github.com/getkirby/kirby/blob/master/kirby.php#L155) in `kirby.php`. The second attribute doesn't get passed recursively if the first attribute is an array.

**Comment by bastianallgeier** [comment]
I just fixed this on the dev branch. Thanks for the pull request, but in this case it needs to be written a bit different.
