### ISSUE TITLE
[Panel/Cms] API endpoints for plugins 

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#290]
- [ ] API endpoints defined by plugins in the backend
- [ ] extend Javascript API part for the frontend through plugins (e.g. adding to it via `panel.api(name, object)`

**Comment by distantnative** [comment]
@bastianallgeier I would postpone this to 3.x (for 3.0 plugin routes could still work) and then also see that plugins can easily extend the JS Api part etc. What do you think?

**Comment by bastianallgeier** [comment]
I agree! Let's move it to the backlog.

**Comment by bastianallgeier** [comment]
✅
