### ISSUE TITLE
[Request] page:2 vs page;2 inconsitancy on Windows

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#291]
Depending on the environment we can use `page:2` or `page;2`.

Maybe there is a way to have one single unified syntax for it?

Sometimes it can be confusing to know which url to use where.

(The "danish" guy is back :wink: )

**Comment by jenstornell** [comment]
To give a real example on this. I'm working on a site where I use a database but at the same time is using Kirbys pagination.

**Here is my current ugly hack:**

```php
$separator = ($_SERVER['REMOTE_ADDR'] == '::1') ? ';' : ':';
```

Then  I can use the `$separator` to build the url that I need.

**Comment by bastianallgeier** [comment]
We have ditched params in URLs entirely. They were causing too many issues. Pagination is now using query strings.
