### ISSUE TITLE
3.5 beta - Time field display is updated to include date and messes up input

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#2911]
If I use the time field in the new blocks branch that includes the date changes *within a structure field* and I refresh the page, the current date is suddenly included in the display of the time. Now when I want to edit the time again, the hour is set to `20` (I guess because it tries to load the 2020-11-etc date into the field somehow) and the minutes are not set.

The time in the content text file remains set correctly, however the field becomes quite confusing and unusable with that bug.

Before reload:
![20201101-160337_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/97858368-58622f80-1cff-11eb-8ed8-d916914ce8da.png)

After reload:
![20201101-160346_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/97858370-58fac600-1cff-11eb-95b3-614cfa6f773a.png)

On input (after reload):
![20201101-160353_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/97858372-59935c80-1cff-11eb-81f8-7b4d4617b2eb.png)

This can be reproduced with the most simple of blueprints:

```yaml
title: Termine

fields:
  termine:
    type: structure
    fields:
      time:
        type: time
```

**Comment by distantnative** [comment]
Thanks for the report. I created a PR with fixes: https://github.com/getkirby/kirby/pull/2928

There have been two issues here:
- Time field/input was expecting the stored value to also be formatted `Y-m-d H:i:s`. Which was implemented for all values from content files - but unsaved changes would be in the old format and would throw off the parser. This regression should be fixed. Time field now communicates in only `H:i:s` again and the time input should not be thrown off anymore by either format.
In general, the content file formats have been improved a bit. For date fields without time, the `00:00:00` does not get saved anymore.
- The new fields switch to a more robust internal value passing by always passing it as `Y-m-d H:i:s`. In a structure fields that raw value would be display - that's what you see. Which of course isn't ideal. I added two new field previews therefore which show the date or time as it is defined by the `display` option of the field (so now even better than before).

The changes aren't on the `features` branch yet. I need to do more testing if I didn't break anything else.
If you want you can try it by using this branch: https://github.com/getkirby/kirby/tree/fix/2911-date-time-fields
Would be helpful to know if it really fixes your issue.

**Comment by distantnative** [comment]
Will be fixed once PR is merged.
