### ISSUE TITLE
[Panel] A non-admin user cannot create new users because no role can be specified

### ISSUE THREAD

**Issue by PaulRaschke** [getkirby/kirby#2914]
**Describe the bug**
When trying to create a new user while logged in with a non-admin user who has the permission to create users, no roles appear for selection in the user create dialog. Clicking `Create` even though no role is selected fails due to the following error: `error.user.create.permission`.

**To Reproduce**

1. Setup the [plainkit](https://github.com/getkirby/plainkit)
2. Create a new user role with `users.create` permissions
3. Create a new user with this role and log in to the panel with this user
4. Try to create a new user via the panel

**Expected behavior**
All roles except admin should be selectable for a non-admin user when creating a new user.

**Probable cause**
The method [`Roles->canBeCreated()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/Roles.php#L53) only returns the admin role if a non-admin user is logged in, because `$newUser->permissions()->can('create')` returns false for all other roles. This happens because of the following code in [`UserPermissions->canCreate()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/UserPermissions.php#L45)

```php
// users who are not admins cannot create admins
if ($this->model->isAdmin() === false) {
    return false;
}
```

with the following changes everything works as expected

```php
// users who are not admins cannot create admins
if ($this->model->isAdmin() === true) {
    return false;
}
```

This has been changed with d83a9582a0463acd8d13b2e028e60cef55ccf43e. Was this accidental or intended and I missed something?

**Screenshots**
![](https://user-images.githubusercontent.com/28190977/98009451-d6a0fd80-1df5-11eb-8b67-dc3476475056.JPG)

**Kirby Version**
3.4.4

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 19042.572
- Browser: Firefox
- Version: 82.0.2 (64-Bit)

**Comment by afbora** [comment]
This is my fault, I directed the @bastianallgeier 🙈 https://github.com/getkirby/kirby/pull/2838#issuecomment-696033405

Should be revert the commit like:

````php
// users who are not admins cannot create admins
if ($this->model->isAdmin() === true) {
    return false;
}
````

**Comment by bastianallgeier** [comment]
✅
