### ISSUE TITLE
Bad validation error message for toggle fields

### ISSUE THREAD

**Issue by eXpl0it3r** [getkirby/kirby#2917]
## Describe the bug
When a `toggle` field is defined as `required: true` and the user tries to save a page with the toggle set to `off`, the page is not saved and the user is shown an odd validation error message.

## To Reproduce
- Grab the starterkit
- Edit the `about.yml` blueprint and add the lines from below
- Open the `About us` page in the panel
- Toggle the new toggle field on and off again
- Click save the page
- The form validation fails, as the only valid state of a toggle in Kirby 3, is the active state.

```yml
      certain:
        label: Are you sure?
        type: toggle
        default: false
        required: true
        text:
          - "No"
          - "Yes"
```

## Expected behavior
There are multiple options to deal with this issue:

- Show a more descriptive validation error, explaining which field it relates to and what value it expects
- Remove the option to set the `toggle` field as required, because what's exactly the point of requiring a toggle field, if the only valid state is to have it set to `on`?
- Change the validation rule, but not exactly sure to what?

## Screenshots
![image](https://user-images.githubusercontent.com/920861/98438984-9d66d700-20ee-11eb-91d2-417979a80401.png)

## Kirby Version
3.4.4

## Console output
HTTP 400 (Bad Request) response from the API endpoint

```json
{
    "status": "error",
    "message": "Invalid form with errors",
    "code": 400,
    "exception": "Kirby\\Exception\\InvalidArgumentException",
    "key": "error.invalidArgument",
    "file": "\/kirby\/src\/Cms\/ModelWithContent.php",
    "line": 771,
    "details": {
        "certain": {
            "label": "Are you sure?",
            "message": {
                "required": "Invalid argument \"-\" in method \"-\""
            }
        }
    },
    "route": "pages\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
}
```

## Desktop (unrelated)
 - OS: Windows
 - Browser: Chrome
 - Version: 86.0.4240.183

## Additional Information
Related [forum post](https://forum.getkirby.com/t/bad-error-when-saving-required-toggle-field/19950)

**Comment by afbora** [comment]
The `Exception` class cannot find (`field.required`) its equivalent in the language file because it adds a prefix `error.`: so  converting `error.field.required`

I did not know whether it is more useful to add the same statement to the language file (`field.required` will copy as `error.field.required`) or to be able to override the prefix in the `Exception` class 🤔

**Comment by bastianallgeier** [comment]
I think it's better to fix it in the language class. We should check if we use `field.required` anywhere else as a translation string and change the key there.

**Comment by afbora** [comment]
Two parts are about this translation.

#### Uses `form.field.required`
https://github.com/getkirby/kirby/blob/features/config/fields/toggle.php#L63

In fact, there are no `form.field.required` and `error.form.field.required` lines.

#### Uses `field.required`
https://github.com/getkirby/kirby/blob/features/panel/src/components/Forms/Field.vue#L12

I guess we should use it as `error.form.field.required`.

**Comment by bastianallgeier** [comment]
✅
