### ISSUE TITLE
Controller dependencies?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#292]
On the site I'm building I have some code that should fit perfectly into a site controller. There is also another case...

I have 5 controllers out of 7 in total that would need a common controller. A global controller would not be a good fit and repetetive code would not be that good.

Maybe we can somehow extend the controller? This will **not** work but will show what I mean:

```php
return function($site, $pages, $page) extends Pagination {
  echo $pagination['count'];
  return [
    'title' => $page->title()
    'pagination' => $pagination
  ];
}
```

**Another approach:**

This could probably work. `$pagination` could be the name of the controller to "extend". The pagination controller would then be similar to a global blueprint definition that is used by the controller.

```php
return function($site, $pages, $page) use ($pagination) {
  echo $pagination['count'];
  return [
    'title' => $page->title(),
    'pagination' => $pagination
  ];
}
```

I don't have a final solution, but I know what the problem is and I hope you can see what I aiming for here.

**Comment by distantnative** [comment]
You could define a pagination method in a plugin file which you then simply can call wherever needed. We shouldn't overengineer things that are rather edge cases and actually have pretty simple solutions, IMHO.

**Comment by jenstornell** [comment]
I don't think the additional controller data belongs in the plugins folder, but that's my personal opinion. 

Instead I have (in Kirby 2) solved it with additional controller folders like this:

```php
<?php
return function($site, $pages, $page) {
  $root = kirby()->roots()->components();

  $global_controller = include $root . '/global/controller.php';
  $archive_controller = include $root . '/archive/controller.php';

  return array_merge($global_controller, $archive_controller);
};
```

I have not deceded if it's going to be the final syntax, but I'll do for now.

By the way, I'll keep your plugin approach in mind.

## Update

I have listened and made a plugin that looks like this:

```php
<?php
function controllers($page, $data = [], $dependencies = []) {
    $site = site();
    $root = kirby()->roots()->components();
    $addons = [];

    foreach($dependencies as $dependence) {
        $buffer = include $root . '/' . $dependence . '/controller.php';
        $addons = array_merge($addons, $buffer);
    }
    return array_merge($addons, $data);
}
```

My controller now looks like this:

```php
return function($site, $pages, $page) {
  $data = ['title' => 'Hello world'];

  return controllers($page, $data, ['global', 'archive']);
}
```

**Comment by distantnative** [comment]
👍
