### ISSUE TITLE
Umlauts not displayed in tab labels (panel)

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/kirby#2922]
When using Umlauts in a tab label, they are not shown correctly.

Exhibit A: "Bücher"

![image](https://user-images.githubusercontent.com/12161504/98587621-ae6c3f80-22ca-11eb-8518-7f02365ab095.png)

It seems to be a font issue.

**Comment by afbora** [comment]
I can't reproduce the issue in v3.4.4. Which language do you use in panel?

![screen-capture-441-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/98588251-6eae5380-22dc-11eb-8edd-ad98401bb8fb.png)

**Comment by S1SYPHOS** [comment]
I'm deeply sorry for wasting your time. It happens because of the shitty system font that doesn't include Umlauts :facepalm:
