### ISSUE TITLE
Using .php in URLs can lead to unwanted content representations

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#2924]
**Describe the bug**  
When you add .php to the path of a page and the slug is the same as the template (i.e. /blog.php and the template is blog.php) Kirby will load the HTML code of the blog.php template and send a content type that will force the browser to show the result. 

We should disable content representations for .php entirely.

**Comment by afbora** [comment]
Is it better to prevent it completely and open an error page or redirect the page to its original (redirect `/notes` with 302 header for `/notes.php` request)? 🤔

**Comment by bastianallgeier** [comment]
I think we should render the error page.

**Comment by lukasbestle** [comment]
I haven't tested it yet, but it sounds like a weird bug to me.

I don't think we should disable content representations for `.php` in general, but fix this specific bug instead. The response should behave like any other representation that wasn't defined by the dev.

**Comment by bastianallgeier** [comment]
@lukasbestle hahaha, I just started typing that I have no idea what a useful case for a .php representation could be until I realised that you could indeed send the output of `serialize()` in such a presentation, which could be useful. Ok, then let's fix the bug instead of disabling it.

**Comment by lukasbestle** [comment]
Or maybe you have a PHP blog that explains coding concepts and you want to provide the example code.

**Comment by distantnative** [comment]
✅
