### ISSUE TITLE
Panel page icons not centered in Firefox (regression?)

### ISSUE THREAD

**Issue by pReya** [getkirby/kirby#2943]
**Describe the bug**  
The page icons in the panel in 3.4.4 are not visually centered (they moved a little to the left) in Firefox 83. In 3.4.2 they were centered. Not sure what the reason for this change was, but it seems that this is what broke it: https://github.com/getkirby/kirby/commit/2ee6f19ad99fec39ffc4679f86560850c904e106#diff-b3660f1567ea5cae8696c50ecd3901dbdb5c8f1b13f235a9af8697c99462afa1.

**Screenshots**  
Firefox:
![Screenshot 2020-11-22 at 17 29 37](https://user-images.githubusercontent.com/4677417/99909360-5f6dd380-2ce8-11eb-88ff-72ebbe25a378.png)

Chrome:
![Screenshot 2020-11-22 at 17 29 51](https://user-images.githubusercontent.com/4677417/99909362-61379700-2ce8-11eb-9c6b-d09d6cf5a550.png)

**Kirby Version**  
3.4.4

**Desktop (please complete the following information):**  
 - OS: macOS 10.15.7
 - Browser: Firefox 83

**Comment by pReya** [comment]
I might try and create a PR to fix this. @bastianallgeier can you tell me, what the reason for this change was? What problem did you try to solve?

**Comment by bastianallgeier** [comment]
@pReya it's a bit like playing cat and mouse. The icons were no longer centered in Chrome before the fix. Now they are no longer centered in Firefox 🙈

**Comment by afbora** [comment]
@pReya I've fixed the issue and you can test with #3028 PR.

**Comment by bastianallgeier** [comment]
✅
