### ISSUE TITLE
Flipped slug rules on multilingual site

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2944]
We're working on a multilingual site with German and English translations. When using the `slug` field method or `Str::slug` in a snippet, umlaut rules are flipped.

### Input

`Büro für Gestaltung`

### Output

German:  → `buro-fur-gestaltung`
English:  → `buero-fuer-gestaltung`

### Expected

German:  → `buero-fuer-gestaltung`
English:  → `buro-fur-gestaltung`

Interestingly, when I output the current language in the same snippet, Kirby returns the correct language settings, e. g. for German:

```php
Kirby\Cms\Language Object
(
    [code] => de
    [default] => 1
    [direction] => ltr
    [locale] => Array
        (
            [0] => de_DE.uft-8
        )

    [name] => Deutsch
    [rules] => Array
        (
            [Ä] => AE
            [Ö] => OE
            [Ü] => UE
            [ß] => ss
            [ä] => ae
            [ö] => oe
            [ü] => ue
        )
)
```

**In comparison, the behaviour in the panel is as expected, using the expected rules per language.**

---

In our config, languages are defined like this:

```php
return [
    'languages.detect' => true
];
```

These are the language definitions:

```php
<?php

return [
    'code' => 'de',
    'default' => true,
    'direction' => 'ltr',
    'locale' => ['de_DE.uft-8'],
    'name' => 'Deutsch',
    'translations' => [
        …
    ],
    'url' => '/',
    'smartypants' => [
        'doublequote.open' => '&#8222;',
        'doublequote.close' => '&#8220;',
        'singlequote.open' => '&#8218;',
        'singlequote.close' => '&#8216;'
    ]
];
```

```php
<?php

return [
    'code' => 'en',
    'default' => false,
    'direction' => 'ltr',
    'locale' => ['en_US.uft-8'],
    'name' => 'Englisch',
    'translations' => [
        …
    ],
    'url' => null
];
```

This is happening on Kirby 3.4.4 as well as the predecessors until 3.2.0 (couldn't test below because the site uses methods not available in those older versions).

Related forum thread: https://forum.getkirby.com/t/flipped-slug-rules-on-multilingual-site/20127

**Comment by afbora** [comment]
I think this issue fixed with #2880 PR by @distantnative 

@nilshoerrmann Could you try with `features` branch? I have tested and working as expected 👍

**Comment by nilshoerrmann** [comment]
Thanks, @afbora, I didn't notice that PR.
Does the `features` branch bundle up-to-date assets or do I have to build those first?

**Comment by afbora** [comment]
@nilshoerrmann You don't need to build to test it in frontend.

**Comment by nilshoerrmann** [comment]
You're right! Time to call it a day :D 
I'll check that out tomorrow – thanks for your help!

**Comment by nilshoerrmann** [comment]
The `features` branch indeed fixes this. Thanks for the pointer!
