### ISSUE TITLE
Url functions mistake some paths with colon (:) as Param

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2948]
**Describe the bug**  
For URLs that have a colon and then a slash, the resulting URL (or path part) will be missing part of the URL.

It would seem like the URLs are getting treated as if they had "Kirby params" (e.g.: `/page:2`).

Would it make more sense to only attempt to parse/extract Params when they're the last part of the URL's path? Or, could there be a better way to reconstruct the URL to match the original order?

**To Reproduce**  
```php
    $foo = 'https://en.wikipedia.org/wiki/Template:/test';
    
    $path = Url::path($foo);
    echo $path; // `wiki/test`
    //   Expected: `wiki/Template:/test`
    
    echo "\n<br>\n<br>\n";
    
    $uriObject = Url::toObject($foo);
    echo $uriObject; // `https://en.wikipedia.org/wiki/test`
    //        Expected: `https://en.wikipedia.org/wiki/Template:/test`
```

An alternative version, which looks more like a real "Kirby param" has the URL re-arranged:
```php
    $foo = 'https://en.wikipedia.org/wiki/Template:example/test';
    
    $path = Url::path($foo);
    echo $path; // `wiki/test`
    //   Expected: `wiki/Template:example/test`
    
    echo "\n<br>\n<br>\n";
    
    $uriObject = Url::toObject($foo);
    echo $uriObject; // `https://en.wikipedia.org/wiki/test/Template:example`
    //        Expected: `https://en.wikipedia.org/wiki/Template:example/test`
```

**Kirby Version**  
`3.4.4`

**Comment by lukasbestle** [comment]
Maybe there should be an option to disable Kirby param parsing for specific URLs entirely. This would be safest for external URLs that don't use Kirby params.

**Comment by afbora** [comment]
I've tested @neildaniels codes. I'm getting output as expected on v3.5.1. Am I missing something?

**For example**
````
Input:
https://getkirby.com/search/page:2?q=page

Output `->path()`:
search/page:2

Output: `->toObject()`:
https://getkirby.com/search/page:2?q=page
````

**Comment by neildaniels** [comment]
@afbora It only affects parameters that have "empty" values.

In this example `Template` is "empty":
`https://en.wikipedia.org/wiki/Template:/test`

But, when it has a value, such as here (where `Template` is set to `example`):
`https://en.wikipedia.org/wiki/Template:example/test`

The first example should fail to be reconstructed.

**Comment by afbora** [comment]
@neildaniels I tested already your inputs. I'm getting following outputs. Is that wrong?

**Input**
https://en.wikipedia.org/wiki/Template:/test

**path()**
wiki/Template:/test

**toObject()**
https://en.wikipedia.org/wiki/Template:/test

Windows 10
Apache 2.4
PHP 7.3.26

**Comment by neildaniels** [comment]
@afbora Params are parsed differently on Windows—they use `;` instead of `:`

https://github.com/getkirby/kirby/blob/551e2f427eaf18e471df1c304552ab3de35e37c6/src/Http/Params.php#L93-L113

I'm using macOS/Linux setups, but I would assume you see a similar issue if you adjust the input url to the following on Windows:
`https://en.wikipedia.org/wiki/Template;/test` (note the semicolon)

**Comment by afbora** [comment]
Ahh thank you for directions, now i can see 👍 😅

**Comment by bastianallgeier** [comment]
✅
