### ISSUE TITLE
PHP8: Deprecation warning for required parameter after optional parameters

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#2956]
- **Kirby version:** 3.5.0-rc.2
- **PHP version:** 8.0.0 (stable)

When rendering a page with Kirby, a few warnings get printed out in the HTML output:

```
Deprecated: Required parameter $type follows optional parameter $string in vendor/getkirby/cms/src/Toolkit/Str.php on line 960
Deprecated: Required parameter $key follows optional parameter $parent in vendor/getkirby/cms/src/Cms/Field.php on line 99
Deprecated: Required parameter $value follows optional parameter $parent in vendor/getkirby/cms/src/Cms/Field.php on line 99
Deprecated: Required parameter $type follows optional parameter $string in vendor/getkirby/cms/src/Data/Data.php on line 82
Deprecated: Required parameter $type follows optional parameter $data in vendor/getkirby/cms/src/Data/Data.php on line 94
Deprecated: Required parameter $hook follows optional parameter $bind in vendor/getkirby/cms/src/Cms/Event.php on line 160
Deprecated: Required parameter $action follows optional parameter $method in vendor/getkirby/cms/src/Http/Route.php on line 96
```

On a second page load, these warnings disappear.

I’m not sure why they’re disappearing. Is that a feature of PHP? Or were the warnings due to some in-memory cache of the PHP files that got updated after that page load (and thus not actually an issue in 3.5.0-rc.2)? Or something else.

The relevant change in PHP8 seems to be:
https://github.com/php/php-src/pull/5067

I‘m not sure what PHP linters exist that could find all the affected functions.
Could be that the list above is complete for `getkirby/cms`, according [to this article](https://php.watch/versions/8.0/deprecate-required-param-after-optional):

> The deprecation notice is triggered at the compile time, and it will be raised even if it is not called.

**Comment by fvsch** [comment]
Found another one on a different page:

```
Deprecated: Required parameter $callback follows optional parameter $arguments in vendor/getkirby/cms/src/Cms/UserActions.php on line 143
```

So I guess it would require a linter to find them all.

**Comment by lukasbestle** [comment]
@fvsch Thanks for testing! I have been able to track all instances of this warning down with the following shell script:

```sh
for f in $(find . -type f -name "*.php"); do
  php -l $f
done
```

PHP support is added by the PR #2957.

**Comment by bastianallgeier** [comment]
✅
