### ISSUE TITLE
3.5-rc: missing structure field previews

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2958]
e.g. for writer field:

<img width="780" alt="Screen Shot 2020-11-29 at 21 18 51" src="https://user-images.githubusercontent.com/3788865/100552586-80a26700-3288-11eb-99bd-4ddedf876f51.png">

**Comment by bastianallgeier** [comment]
✅ 

![field-previews](https://user-images.githubusercontent.com/24532/100871153-15cb7880-34a0-11eb-8218-56aecddc9a72.png)
