### ISSUE TITLE
`Call to undefined method S::regenerateId()` in panel/ subroot under PHP5.6.12

### ISSUE THREAD

**Issue by anselmh** [getkirby/kirby#296]
Hey, 

I guess it’s related to a PHP upgrade on my local machine but since today I get this error on the panel (`http://localhost:8080/panel/`):

```
Fatal error: Call to undefined method S::regenerateId() in /projecthost/kirby/core/user.php on line 173
```
The reason I post this issue here is that the bug seems to be in the core, not in panel code. All other pages work fine btw.

I have PHP 5.6.12 installed on my machine.

Any idea or advice?

**Comment by lukasbestle** [comment]
Please check whether the version of the Kirby Toolkit is 2.1.1. The mentioned method has been [added two weeks ago](https://github.com/getkirby/toolkit/commit/111ef6846ce24f5d503336dad3f47965129bb627), so it seems like you are still using an older version that isn't compatible with the latest Panel version.

**Comment by anselmh** [comment]
Oh, I missed that toolkit is a submodule of kirby.git. Thanks for your quick help, this fixed it.
