### ISSUE TITLE
Display Range field default value on load in tooltip

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#2960]
When setting a default value for a Range field, I expect that default value to be displayed in the tool tip when the page is loaded. The slider position is updated but the value isn't displayed.

![image](https://user-images.githubusercontent.com/5200901/100615526-f16f7080-32d4-11eb-8c28-448d597508da.png)

![image](https://user-images.githubusercontent.com/5200901/100615468-e1f02780-32d4-11eb-8f49-440d971efa45.png)

**Comment by afbora** [comment]
Actually, this is a known case. If you have added this field to an existing page, the value will not appear.  The default values for new pages creation for all fields.

> Default number that will be saved when a new page/user/file is created

https://getkirby.com/docs/reference/panel/fields/range

**Comment by distantnative** [comment]
@afbora are we sure the default value is displayed for newly created pages?

**Comment by afbora** [comment]
@distantnative I'm sure. The statement written for default in all fields in the documents:

> Default value for the field, which will be used when a page/file/user is created

https://getkirby.com/docs/reference/panel/fields/text#field-properties
https://getkirby.com/docs/reference/panel/fields/range#field-properties
https://getkirby.com/docs/reference/panel/fields/select#field-properties
...
...
etc

**Comment by afbora** [comment]
@distantnative Lets flashback 😅  https://github.com/getkirby/kirby/issues/1396#issuecomment-491313762

**Comment by HYR** [comment]
@afbora Why does it happen on page creation? Why not on page load if no value is stored already?

**Comment by afbora** [comment]
@HYR That's a great question 😅 The answer to this will be more descriptive by other team members.

But I think the purpose of this is to protect the data of existing pages. If you give a default value and even if it is not required, the data will be saved as the default value is assigned. 

If you want the default value to be loaded on existing pages, you should use the `required: true` option 👍 

````yaml
max_width:
  type: range
  default: 100
  required: true
````

**Comment by bastianallgeier** [comment]
This is an ongoing issue that we are fighting with since Kirby 2. 

When we always automatically inject the default value when a field is empty, the field can no longer be empty. We had that and it felt like a pretty invasive bug. We would probably need another global field option called something like fallback to achieve that.

**Comment by nilshoerrmann** [comment]
We have been running into this issue regularly with newly added fields on existing pages. I'm not sure, if you see this difference in the Vue layer, but we'd have expected the default value to always kick in when the value is not set in the content file vs. an empty string in the content file.

E.g. with default value for `newfield`: 

```
Text: My text
```

And without default value for `newfield`:

```
Text: My text

---

Newfield:
```
