### ISSUE TITLE
Block text.php missing ?>

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#2963]
https://github.com/getkirby/kirby/blob/features/blocks/text/text.php 
This is curious.

**Comment by afbora** [comment]
@iskrisis You might want to have a look.

> The closing tag of a block of PHP code automatically implies a semicolon; you do not need to have a semicolon terminating the last line of a PHP block. The closing tag for the block will include the immediately trailing newline if one is present.

> The closing tag of a PHP block at the end of a file is optional, and in some cases omitting it is helpful when using include or require, so unwanted whitespace will not occur at the end of files, and you will still be able to add headers to the response later. It is also handy if you use output buffering, and would not like to see added unwanted whitespace at the end of the parts generated by the included files.

https://www.php.net/manual/en/language.basic-syntax.instruction-separation.php

**Comment by bastianallgeier** [comment]
It's actually even a bit "safer" to not add the end tag, because you don't accidentally have invisible characters after your PHP block that will be rendered. In this case I could even remove the semicolon as @afbora posted.

**Comment by bastianallgeier** [comment]
LOL, my explanation is even in the text. Maybe I should read a bit more before posting comments :)

**Comment by iskrisis** [comment]
I am not sure if this is not being maybe too smart. I know about the ending tag. But this is a template and one that many people just take and wrap their stuff around it. That was how i found it in first place. This being echo shorthand (i've never seen that) makes it more confusing.

But thats why i said its curious not a bug. Up to you guys just user experience.

**Comment by bastianallgeier** [comment]
@iskrisis that makes total sense. I even added it to the docs like that for exactly that reason. https://getkirby.com/v35/blocks/block-types/text#default-snippet

It might indeed be better to change it in the core then as well.

**Comment by bastianallgeier** [comment]
✅

**Comment by bastianallgeier** [comment]
Damn, our coding standards (CS fixer) doesn't like the "clearer" version. I had to revert it and we currently don't have a fix without breaking our own standards. I'll keep it with end tag in the docs, but without in the core.

**Comment by iskrisis** [comment]
@bastianallgeier its not important. I feel bad that i managed to put you in this rabbit hole with such small issue. People who are copying directly from kirby/blocks will know how to fix this. 

Cheers!
