### ISSUE TITLE
[Blocks] Group labels doesnt support multi-language

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2964]
Issue reported by @tobimori from Discord.

![screen-capture-513-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/100909610-01a66c00-34de-11eb-9a0f-502b4f6a8419.png)

**Kirby Version**  
3.5.0-RC.3

**Comment by bastianallgeier** [comment]
✅
