### ISSUE TITLE
Create lifetime cookie returns a error

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#2968]
I have made a Cookie consent solution by my own with Kirby Cookies. However, when I use this:
```php
<?php Cookie::forever('consent', 'all'); ?>
```
It works on localhost, but not on the hosting for the customer (Host Europe), I get this error:
```
Argument 1 passed to Kirby\Http\Cookie::lifetime() must be of the type int, float given, called in .../kirby/src/Http/Cookie.php on line 45
```
But this works.
```php
<?php Cookie::set('consent', 'all'); ?>
```
As reference, please check this thread at the forum. Is there a way to avoid this? Not sure if this is a bug or only a slow hosting problem. However, if I use the forever function, the site will not work.

https://forum.getkirby.com/t/create-lifetime-cookie-fails/20228/4

**Comment by bastianallgeier** [comment]
@lukasbestle any idea how this is even possible? Looking at the cookie code, I have no idea how the lifetime can become a float.

**Comment by afbora** [comment]
@bastianallgeier This issue caused from following line:
https://github.com/getkirby/kirby/blob/master/src/Http/Cookie.php#L107

`253402214400` is exceeds the maximum integer value at 32 bits and it's float on 32-bit. 

I think, it should be like that:

    $options['lifetime'] = PHP_INT_MAX;

_Note: @texnixe has already found the source of the issue on the forum 😅_

**Comment by Werbschaft** [comment]
Is this the End of the Unix Timestamp in 2038 (Y2K38)? I think the robots will take over the world anyway, so why don't we put it on that date? 🤯

**Comment by lukasbestle** [comment]
I think it should be this so we can keep the nice 9999-31-12 date on 64-bit machines:

```php
$options['lifetime'] = min(253402214400, PHP_INT_MAX); // 9999-12-31 if supported (lower on 32-bit servers)
```

**Comment by Werbschaft** [comment]
@afbora @lukasbestle I have tested both methods on a 32 bit system and both work. It is up to you which solution seems to be the better one. @lukasbestle very elegant solution for both cases!

**Comment by bastianallgeier** [comment]
> Is this the End of the Unix Timestamp in 2038 (Y2K38)? I think the robots will take over the world anyway, so why don't we put it on that date? 🤯

🤣

**Comment by lukasbestle** [comment]
Let's hope there aren't any 32-bit servers by 2038. 😅

**Comment by bastianallgeier** [comment]
@lukasbestle wait! You live in Germany too, right? You really believe there won't be any 32-bit severs by 2038?

**Comment by afbora** [comment]
I guess there will be no need for this 😄 Because [Linux 5.10 solves the year 2038 problem till year 2486](https://www.youtube.com/watch?v=JgBfDN1_5Lg)

Source: https://www.phoronix.com/scan.php?page=news_item&px=XFS-Linux-5.10

Related PR: https://lore.kernel.org/lkml/20201014205059.GD9837@magnolia/

**Comment by Werbschaft** [comment]
New name suggestions, maybe better words for forever
```php
Cookie::untilCollapse(string $key, string $value, array $options = [ ]): bool

Cookie::untilTheEndOfTheWorld(string $key, string $value, array $options = [ ]): bool

Cookie::asLongAsYourOperatingSystemRuns(string $key, string $value, array $options = [ ]): bool
```

**Comment by lukasbestle** [comment]
✅
