### ISSUE TITLE
Rewriting the pagination object

### ISSUE THREAD

**Issue by labo-css** [getkirby/kirby#297]
As seen here : https://github.com/sashtown/baseblog/issues/12#issuecomment-135297844
And here : https://github.com/sashtown/baseblog/issues/8

How i can make pagination like page:2 work on windows ? It will be getting patched ? Can i change the : with a - for example and make it work without breaking the website in the next update ?

Thanx for your work.

**Comment by bastianallgeier** [comment]
This is finally fixed on the develop branch and will be in 2.2.
