### ISSUE TITLE
[Blocks] Nested blocks k-drawer-body overflow

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#2971]
![Screen Shot 2020-12-06 at 15 30 08](https://user-images.githubusercontent.com/4954323/101283000-69a7cb80-37d8-11eb-956d-800f576c883d.png)
There is `overflow: auto;` on `k-drawer-body` probably for a reason but it cuts of writer inline popups.

It should be
![Screen Shot 2020-12-06 at 15 35 15](https://user-images.githubusercontent.com/4954323/101283080-b8edfc00-37d8-11eb-8a0b-94a84d7e1514.png)
If it doesn't break something else it could be just deleted?

**Comment by bastianallgeier** [comment]
The body has an overflow setting to start scrolling if there's not enough vertical space available.

**Comment by bastianallgeier** [comment]
✅
