### ISSUE TITLE
Content is not deleted when you empty a list field

### ISSUE THREAD

**Issue by efavaro** [getkirby/kirby#2976]
**Describe the bug**  
Content is not deleted when you empty a list field.

**To Reproduce**  
1. Fill in a list field
2. Save
3. Delete the contents of a list field
4. There remains one empty list item (see screenshot) and residual content in txt: `exampleField: <ul><li><p></p></li></ul>`

**Expected behavior**  
The content of the field in the txt should remain empty so that you can, for example, make certain content appear only if _->isNotEmpty()_.

**Screenshots**  
![imagen](https://user-images.githubusercontent.com/6424076/101416481-b9fe5680-38c8-11eb-81e1-7b3521e6c4fc.png)

**Kirby Version**  
3.5.0-rc.4

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox
 - Version: 83

**Comment by bastianallgeier** [comment]
✅

**Comment by bastianallgeier** [comment]
Will be fixed in the next RC
