### ISSUE TITLE
[Blocks] Accessing content produces invalid output

### ISSUE THREAD

**Issue by DanielRivers** [getkirby/kirby#2978]
**Describe the bug**

When accessing content over Kirby API get malformed response 

**To Reproduce**

`article.json.php`

```
<?php
$data = [
  'title' => $page->title()->value(),
  'text'  => $page->text()->blocks()
];

echo json_encode($data);
```

returns

```
{"title":"The Rohingya and Indian Muslims : The latest in the history of scapegoats","text":{"data":{"_sVs12suXo":{},"_ilsfem71j":{},"_1wp1fqxij":{},"_TKoU93lHC":{},"_szVBFCGHr":{},"_lUSwH4YsM":{},"_EMgmp0p9Z":{},"_inx7S9k2J":{},"_vJqICVDRp":{},"_P6hwG9eG8":{},"_v9mBq4Hg0":{},"_7d8MPz8Zz":{},"_1EpBfBriJ":{},"_feaxaxX3o":{}}}}
```

example article attached - [article.txt](https://github.com/getkirby/editor/files/5328558/article.txt)

**Expected behavior**

Return content markup

**Screenshots**

**Kirby Version**

**Console output**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by bastianallgeier** [comment]
Good news: it's easy to fix for the new blocks field: 

```php
<?php

$data = [
  'title' => $page->title()->value(),
  'text'  => $page->text()->toBlocks()->toArray()
];

echo json_encode($data);
```
