### ISSUE TITLE
[Panel] History back and performance issue on larger site

### ISSUE THREAD

**Issue by hannesherold** [getkirby/kirby#2987]
Not sure if it’s just me, but the panel of the RCs seems to have a performance issues. I’m testing a larger site with 6500 pages total, biggest parent holds 2000 children. 

In the panel, on first go, all the standard pages sections that hold many children load pretty slow, and cog wheel turns forever. It feels almost as if a cache needs to get built, but caching is not enabled in config.php. Then, after the first go, pages sections seem to load at normal pace.

But history back doesn’t work as expected: the URL in the browser bar does change, but the panel page just stays the same. Navigation via breadcrumb menu works as expected.

I experience this in local development as well as on dev server. First encountered with RC4, same with RC5. 

**Kirby Version**
3.5 RC4, RC5

**Console output**  
Nothing, sorry.

**Desktop**  
 - macOS
 - Chromium, Safari, Firefox

**Comment by bastianallgeier** [comment]
@hannesherold did this really just appear in RC4 and didn't happen in RC3 for example? We are currently trying to find the problem. Would it be possible to get access to the site somehow?

**Comment by hannesherold** [comment]
I haven't tested RC3, but can do that if it helps.

I made some more tests and found a console message, but probably it's not related. On the panel login page:

```
/panel/login:1 
Autofocus processing was blocked because a document already has a focused element.

```
Now when I run the site locally through Code Kit, there’s more. After successful panel log in when I jump back and forth between the pages sections:

```
site:20 
CodeKit tried to sync a click event from another browser on the following element, but a handler in the event-bubbling chain canceled the event: body > div > main > div > div > div:nth-of-type(2) > div > section:nth-of-type(1) > div > ul > li > a > span:nth-of-type(2) > em

```
But there’s no other browser open.

The history-back-issue seems to put Code Kit into trouble. The app sometimes looses connection, saying:

```
site:20 CodeKit has not sent a message in over 15 seconds. The connection *might* have failed or your network could be laggy. Auto-refreshing may be slow and unreliable. You can try manually reloading the page to reset the connection.
(anonymous) @ site:20
setInterval (async)
i @ site:20
g.onopen @ site:20
```

Finally, in rare cases, Firefox brings up a modal and this error message in the console:

```
sTypeError: t is undefined
    codeMode http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/app.js:1
    get http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/vendor.js:23
    evaluate http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/vendor.js:23
    hr http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/vendor.js:23
    canToggle http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/app.js:1
    get http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/vendor.js:23
    evaluate http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/vendor.js:23
    hr http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/vendor.js:23
    An http://MacBookPro.fritz.box:5757/media/panel/21e7f67ad0a1940dfb3cab8fcffc9fd3/js/app.js:1
app.js:1:335273
```

Hope this helps. You can also send me an email or contact me on Discord.

**Comment by lukasbestle** [comment]
@hannesherold The first message is indeed fine. I cannot say anything about the CodeKit messages, but I don't think they are related to Kirby. The last message is from a bug that was fixed in RC 5.

We have discussed the problem internally and have an idea which change might have caused the performance hit. Could you please test the [`fix/media-performance` branch](https://github.com/getkirby/kirby/tree/fix/media-performance) (first delete your `media` folder, test with RC 5 and then replace the `kirby` folder with the new branch and delete your `media` folder again)? Thanks!

**Comment by hannesherold** [comment]
Ok, sure.

**Comment by hannesherold** [comment]
Excellent! Issue solved.
You guys are amazing. Outstanding support, Kirby team. Thank you! 

Here’s the protocol.

- All test on macOS Catalina
- Localhost using Laravel Valet
- Dev server on Überspace

### Test 1: RC5 on localhost
Deleted media folder

**Chromium, Safari, Firefox:**
- No significant performance issues
- History back issue: panel page doesn’t change whereas URL does. 

**Opera**
- No significant performance issues
- On first go: History back issue. After that: no issues, even when deleting media folder again. 


### Test 2: media performance fix on localhost
Deleted media folder

**Opera, Chromium, Safari, Firefox:**
- No significant performance issues
- No history back issue 

### Test 3: RC5 on dev server
Deleted media folder

**Opera**
- Massive performance issues, gateway timeout on really large parents
- No history back issue.

**Safari, Firefox, Chromium**
- Decent performance but history back issue. 

### Test 4: media performance fix on dev server
Deleted media folder

**Opera, Chromium, Safari, Firefox:**
- No significant performance issues. It might be only subjective impression, but pages section now even feels faster than in Kirby 3.4!
- No history back issue.

**Comment by lukasbestle** [comment]
@hannesherold Thank you very much for testing. Glad that this fixed it. ❤️
