### ISSUE TITLE
Twig support incoming?

### ISSUE THREAD

**Issue by shash7** [getkirby/kirby#299]
Are there any plans to add support for twig templating in the future or is there a plugin for that?

**Comment by lukasbestle** [comment]
There are plans to add a template API so that you can integrate any templating engine you want.
However, that's probably not something you can expect in the near future (@bastianallgeier, what's the current state of this?).

But there is a plugin specifically for Twig: https://github.com/matthewspencer/kirby-twig-plugin
I haven't tested it, but it looks quite good.

**Comment by shash7** [comment]
Sounds good! I'll give it a go.

**Comment by JimmyRittenborg** [comment]
:+1: and i really like the idea of a template API so that it's not being tied to a specific templating engine.
There's many great flavors of templating like Blade from Laravel, twig, heck even a PHP port of Shopify's Liquid.

**Comment by namaless** [comment]
https://gist.github.com/namaless/469b04b9cbb0356e03cb

This working very well in the past, is a snippet and is simple to used. Documentation in the phpdoc.

**Comment by philgruneich** [comment]
I learned everything I know of PHP from Kirby and only due to [this article](http://getkirby.com/blog/php-templates) by Bastian. I learned to love this philosophy and I'd be displeased to see it undone.

**Comment by bastianallgeier** [comment]
@philgruneich don't worry! It's never going to replace the default PHP template engine. There's just going to be an option to plug your own template engine on top of it. So this could be Twig or Jade or whatever you prefer. 

But I think there's a big advantage to keep the minimal approach at the core. I think especially feedback like yours shows that this is not so much about the template engine/language itself, but about getting started with PHP. I'm still convinced that it's much more beneficial to learn the basics of PHP by using it for templating, than to learn the basics of Twig. And I'm also convinced that it will always help to keep Kirby's APIs more polished, when clean templates depend on them directly.

**Comment by texnixe** [comment]
@bastianallgeier Absolutely :+1

**Comment by bnomei** [comment]
@bastianallgeier: +1

**Comment by krisak** [comment]
@bastianallgeier +1 I can give one unusual nice reason for this: with twig.js you can render the same thing as with twig in php. You can use this to create dynamic websites. The biggest pain there is the views. Yes you still have to get the data in js and do the routing, but that is ususaly minimum compared to duplicating stuff on server and js.

**Comment by fvsch** [comment]
I wrote a plugin for Twig support, making use of the new component architecture in 2.3 (beta).
https://github.com/fvsch/kirby-twig

Using it seems a bit more straightforward than the other solutions mentioned in this post (pre-2.3). You don’t have to write a PHP template that calls your Twig template, you can just have a Twig template and it works.

**Comment by jenstornell** [comment]
I think this issue should be closed. @fvsch has proven that the new component feature of 2.3 enables Twig support with a plugin. Case solved? Issue closed?
