### ISSUE TITLE
Parts of new Date field (w/ Time) get cut off when not wide enough

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2992]
**Describe the bug**  
When the date field is not wide enough (e.g. width of 1/4), then part of the time portion gets obstructed by the time.

**Expected behavior**  
Although not totally ideal, the way that Kirby 3.4.5 handled this was much less confusing.
<img width="302" alt="Screen Shot 2020-12-10 at 4 08 57 PM" src="https://user-images.githubusercontent.com/417182/101844797-18fae000-3b02-11eb-9916-8ff73a7e087b.png">

**Screenshots**  
<img width="242" alt="Screen Shot 2020-12-10 at 4 07 07 PM" src="https://user-images.githubusercontent.com/417182/101844807-20ba8480-3b02-11eb-945c-c8c6bb9bd2a8.png">
<img width="300" alt="Screen Shot 2020-12-10 at 4 07 10 PM" src="https://user-images.githubusercontent.com/417182/101844812-231cde80-3b02-11eb-888e-9ea0ed8aca2f.png">

**Kirby Version**  
`3.5.0-rc.6`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 14.0.1 (16610.2.11.51.8)

**Comment by nilshoerrmann** [comment]
What about making this field span two rows when the space is too narrow (time below the date)?

**Comment by distantnative** [comment]
We need something better indeed.

As background:
This gets composed by two input elements. Which are just horrible to control in terms of with.

**Comment by nilshoerrmann** [comment]
If you set a min-width on both inputs (or their respective wrappers) couldn't you use `display: flex` in combination with `flex-wrap: wrap`? So that the browser put everything in one single line when there is enough space but breaks it on narrow viewports?

**Comment by distantnative** [comment]
The issue is setting a `min-with` when the `display` option can be configured freely (and thus the required width differs vastly).

**Comment by johannschopplich** [comment]
Would the `ch` CSS unit come in handy? Maybe to break lines if the character's width would exceed the outer width?

**Comment by distantnative** [comment]
So, with `min-width` in `ch` and `flex-wrap: wrap` the inputs wrap immediately:
<img width="360" alt="Screen Shot 2020-12-12 at 11 07 45" src="https://user-images.githubusercontent.com/3788865/101981050-524e5f80-3c6a-11eb-9e1e-2c238864cfcf.png">

Using `width` instead of `min-width` cuts off the inputs:
<img width="370" alt="Screen Shot 2020-12-12 at 11 08 50" src="https://user-images.githubusercontent.com/3788865/101981058-6f832e00-3c6a-11eb-97a6-63a2ad8278d7.png">

**Comment by nilshoerrmann** [comment]
Have tried not specifying a width at all and pushing the inputs apart using `space-between`? I think wrapping should work in that case. You‘d have to make sure the flex wrapper is full width though.

**Comment by distantnative** [comment]
@nilshoerrmann the problem is that input elements have an inherit width. If I set no width, it actually ends up with a width of 183px that wraps the inputs immediately if I add `flex-wrap: wrap` or without pushes the icon outside the field:
<img width="768" alt="Screen Shot 2020-12-12 at 13 02 20" src="https://user-images.githubusercontent.com/3788865/101983270-4a96b700-3c7a-11eb-98ee-aaea4ba8b346.png">

**Comment by nilshoerrmann** [comment]
In that case, setting `flex-basis` might help as it is taking precedence over the width. But I think the most interesting settings like `min-content` are not widely supported yet. Complex situation that is …

**Comment by distantnative** [comment]
> But I think the most interesting settings like min-content are not widely supported yet. 

I also think this wouldn't apply to the input's content but to the input itself - which is supply fixed.

**Comment by neildaniels** [comment]
This has gotten much worse in `3.6.2-rc.2`.

<img width="293" alt="Screen Shot 2022-01-25 at 9 51 48 AM" src="https://user-images.githubusercontent.com/417182/151032260-0d1c620d-bd89-4199-9486-6e9dd68d37fb.png">

<img width="314" alt="Screen Shot 2022-01-25 at 9 55 24 AM" src="https://user-images.githubusercontent.com/417182/151032310-3f9582ec-55bd-48e0-9530-61191fec0828.png">

**Comment by distantnative** [comment]
@bastianallgeier we already define min sizes for the time input, looks like the same is needed for the date input part

**Comment by sebastiangreger** [comment]
I, too, use the date field with times in 1/3 width in a 2/3 column and this appears to be fixed for good in 3.6.2-rc.3 …Holy Albatross to the rescue :sunglasses:

At least in my scenarios the field neatly wraps into two rows when there's not enough space ("neatly" in a technical sense; aesthetically I might still redesign my panel to provide more space for the date field to not wrap, but that's ofc unrelated to this bug).

**Update:** I just tried to reconfigure my panel and it the "wrap into two rows" rule seems a tad overzealous to kick in:
![Screenshot from 2022-01-29 11-39-25](https://user-images.githubusercontent.com/6355217/151657883-58637608-dad8-4b10-877b-ad7de3acfb3b.png)
…in this scenario, there would be plenty of space to accommodate both in one row

**Comment by bastianallgeier** [comment]
This is one of those issues that ate way too much time. Wrapping something into a full width and still setting a max width for when it does not wrap is impossible without JS as far as I could find out. That extra space is there to make sure the fields still have enough room when the Display Setting needs more space or a before/after Text is set. It's not perfect but the most perfect solution I could find without throwing JS at it

**Comment by bastianallgeier** [comment]
I really hope that we will see container queries soon. This would be so easy to fix.

**Comment by sebastiangreger** [comment]
@bastianallgeier I feel your pain, and I was pretty sure this is intentional (i.e. a compromise). As I write above, it's perfectly fine for me …wanted to report just-in-case, and since that's what an RC is for :slightly_smiling_face:

**Comment by distantnative** [comment]
Closing this for now - we can revisit it once container queries are sufficiently supported.
