### ISSUE TITLE
Layout improvement in nested blocks

### ISSUE THREAD

**Issue by chrfickinger** [getkirby/kirby#2994]
When using nested blocks in Kirby 3.5, the last nested block (```<div class="k-block-container">```)
requires ```margin-bottom: 1.5em``` for better recognizability of the element. (see screeshot)

Kirby Version: 3.5RC5

![screenshot](https://user-images.githubusercontent.com/91317/101773162-b0553880-3aec-11eb-9ae8-f256c35f56c4.jpg)

**Comment by bastianallgeier** [comment]
No problem. I just transferred the issue.

**Comment by bastianallgeier** [comment]
✅
