### ISSUE TITLE
[3.5.0-rc.6] Date field weird behaviors

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2997]
**Describe the bug**  
![date-time-2](https://user-images.githubusercontent.com/3393422/101875649-07fead00-3b9c-11eb-9b7d-575d8728194f.gif)

1. When we click on an empty place in the calendar or on the navigation, it deletes the date (I think the focus error appears after resolving)

2. There is a delay when we select the time and change the date from the calendar. You will notice that it first deletes the input and then refills it. Also this causes the savebar to disappear momentarily and come back again (when input empty). (Not seen in this video)

**Kirby Version**  
3.5.0-rc.6

**Comment by distantnative** [comment]
Hi @afbora, trying to narrow some of these issues down.

1. I am not able to reproduce this in Chrome. Are you using another browser?

2. Seems to me that this isn't happening with only a date field, but when the time part is added to (so a date time input is used). Can you confirm this from your side?

**Comment by afbora** [comment]
1. This happened in Chrome but after I made a small change to fix the focus problem. If you solved it differently, this error may also be resolved 👍

I updated the `toNearest()` method params in the `DateInput` file as follows.

    toNearest(dt, unit = this.step.unit ?? 'day', size = this.step.size)

2. I tested it in a little more detail. This issue occurs only with time and step:

````yaml
created:
  label: Published Date
  type: date
  translate: false
  time:
    step: 1
````

**Comment by distantnative** [comment]
I couldn't reproduce (1) without any fixes. But maybe you have a different blueprint?

**Comment by distantnative** [comment]
Is it the same for you when using https://github.com/getkirby/kirby/tree/fix/date-field ?

**Comment by afbora** [comment]
@distantnative Almost done. Both issues fixed on your branch 🎉 
But i have found new two problems unrelated with first two issues.

1. Sets empty when you select date with enter
2. Time with notation still doesn't works (i guess there is an issue about that)

````yaml
  created:
    type: date
    time:
        notation: 12
````

**Comment by afbora** [comment]
@distantnative My bad, i've tested again. Works all.

**Comment by afbora** [comment]
But I think I noticed a small problem

1. Open calendar and select today
2. See date and time is correct
3. Save the content
4. Refresh the page
5. See time is not correct

````yaml
  created:
    type: date
    time: true
````

**Comment by HYR** [comment]
I should've checked before I posted but I'm having similar issues this morning.

https://github.com/getkirby/kirby/issues/3000

**Comment by distantnative** [comment]
I went through all these issues again, can't reproduce them anymore with the PR.
Can you confirm, @afbora?

**Comment by afbora** [comment]
@distantnative ✅
