### ISSUE TITLE
Panel: Save button is missing

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#3]
There is no save button on the pages. CTRL + S however work. Should there be no save button?

**Comment by bastianallgeier** [comment]
We decided that this will always be missing. We will switch entirely to auto-saving and have some nice ideas how to combine that with different versions of a page.

**Comment by jenstornell** [comment]
Alright. That is working for Google Drive so I guess it will work here as well.

What I think is extremly important now is to always present the state of the page. Is the page saved or not right now?

```
[Saved at 2017-11-15, 13.33]
```

or

```
[You have unsaved changes. Last save 2017-11-15, 13.33]
```

If I have no information if the page is saved or not I can't trust the panel. If I can't trust the panel that the page is really saved, I might not dare to logout for example.

**Google Drive**

![image](https://user-images.githubusercontent.com/927011/32836676-ebb0b036-ca0a-11e7-945d-7d45e0f85f28.png)


**Related**

https://github.com/k-next/starterkit/issues/21

**Comment by distantnative** [comment]
Since we have the unsaved indicator idea also over here (https://github.com/k-next/starterkit/issues/21), I will close this one.
