### ISSUE TITLE
3.5.0-RC.6: Date/Time cleared when hitting return after tabbing through.

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#3000]
**Describe the bug**  
When typing out a date and then tabbing to the time, it creates a base time which is find but when i hit enter to accept the the date and time it gets cleared out.

**To Reproduce** 
Type in date by hand and tab to time and hit return.

Video: https://cln.sh/JgKY2VWaDjBTRMZZWn7m

**Expected behavior**  
I expected it to save the date and the default time upon enter or tabbing out.

**Kirby Version**  
3.5.0-RC.6

**Comment by distantnative** [comment]
Fixed with https://github.com/getkirby/kirby/pull/2999.
Will be in the next RC and/or release.
