### ISSUE TITLE
[3.5.0-rc.6] Blocks navigation breadcrumbs issue

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3003]
**Describe the bug**  
I have posted the steps and screencast of the issue below.
I think this problem is not resetting the breadcrumbs because the page exits before the drawer closes.

**To Reproduce**  
1. Go to blocks field
2. Add image block
3. Upload a image and select from field
4. Click the image in image block
5. Go back to blocks field
6. Open any block
7. See breadcrumbs issue

**Screencast**  
Deleted the client website screencast

**Kirby Version**  
3.5.0-rc.6

**Comment by bastianallgeier** [comment]
I know where the issue is coming from. I will try to fix it today.

**Comment by bastianallgeier** [comment]
✅
