### ISSUE TITLE
Panel: Date's calendar pop-over z-index "probably broken" when inside structure field

### ISSUE THREAD

**Issue by renestalder** [getkirby/kirby#3004]
**Describe the bug**  

I noticed the date field's calendar pop-over in v3.5.0-rc.6 is not on the correct z-level when inside the structure field and thus other fields with lower z-index might collide with the calendar (see screenshot of the locator plugin).

I can only give reporducing steps for the Locator plugin which seems to apply a z-index of 3 to it's field container, which is the same as the structure field. But I would assume other conflicts also exist as I will describe further down in the additional context.

**To Reproduce**  
1. Install [locator plugin](https://getkirby.com/plugins/sylvainjule/locator)
2. Add a `structure` field with a `date` field as child.
3. Add a `locator` field after the structure field.
4. Now test inside the panel by trying to add a date via the calendar UI. The calendar UI will now be under the locator input field.

**Expected behavior**  
Date field calendar pop-over should always be top most.

**Screenshots**  

![Screenshot from 2020-12-14 16-43-37](https://user-images.githubusercontent.com/105358/102105810-21b82280-3e30-11eb-9db2-9800276cffa7.png)

**Kirby Version**  

v3.5.0-rc.6

**Console output**  

**Desktop (please complete the following information):**  
 - OS: Linux, Ubuntu
 - Browser: Firefox Developer Edition
 - Version: Latest

**Additional context**  

The `structure` fields use a z-index of 3. The locator field is also using the same z-index, so they set the same base level.

Now, the calendar widget inside the structure field has a z-index of 800, but my assumption without further debugging is, this gets broken due to one of the parents having a z-index of 3.

This might lead to problems with other fields too, not only necessarily with the locator plugin. Of course if a plugin author decides to go higher than 800 in the z-index, this will break naturaly. But breaking a z-index of 3 seems pretty trivial.

**Comment by afbora** [comment]
Now I have looked at the issue again. In the panel, we generally used z-index 1-2-3. It might be better if the Locator plugin uses `z-index: 2` instead of Kirby's side changes?

**Comment by distantnative** [comment]
Does setting `.k-locator-input` to `z-index: 2` or `z-index: 1` in the developer tools solve it?

If so, I would agree with @afbora that this should probably rather be fixed on the plugin side. Of course we could raise all z-indexes but this is just a game where the next plugin developer comes around and assume another higher number and it's broken again - so not really a fix but more something plugins need to adapt to the general setup IMO.

**Comment by afbora** [comment]
@distantnative Yes seems working for me on following line: `z-index: 3;` to `z-index: 2;`

https://github.com/sylvainjule/kirby-locator/blob/master/src/assets/css/styles.scss#L27

Pinging @sylvainjule that author of plugin.

**Comment by renestalder** [comment]
I wonder if maybe not using 1, 2, 3 indexes but 10, 20, 30 would make it easier for plugin implementations to work around these issues? As from my experience at least, placing an element between 10 and 20, makes it easy to guess where my element will be. Trying to place it over z-index 2 but under 3 sounds rather like it will work in some circumstances, and in others not, whether my element is lower in the document tree order, so probably pure luck.

**Comment by sylvainjule** [comment]
I am pretty confident didn't come up with 3 out of the blue and there was a conflict with 2 somehow, but this was ages ago and I didn't document it, so I'll change it in the plugin and if there an issue, it'll be brought up soon enough :)

**Comment by afbora** [comment]
I'm closing this issue as the plugin author will update the plugin. If it comes up, we can proceed with a new issue.
