### ISSUE TITLE
Odd "Revert" behaviour with content converted from Editor to Blocks

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3008]
**Describe the bug**  
When opening content created with the Editor plugin, some blocks register a content change on focus and a revert action is not possible.

**To Reproduce**  
1. Open a page with Editor field data in the Panel (Editor content is correctly displayed as Blocks content)
2. Click on a block to set the cursor in it but do not edit the content (the "Revert/Save" footer appears)
3. Click outside of the block to take focus away from the block.
4. Click on "Revert" and confirm in the pop-up modal.

The pop-up closes, but the "Revert/Save" footer remains; no revert takes place. Interestingly, after navigating to another page and back to this page in the Panel (or after reloading the Panel page with F5), the "Revert" action is actually possible.

This happens at least when focusing the `text` and `quote` blocks; the `headline` and `image` block don't even trigger the "Revert/Save" footer on focus.

**Expected behavior**  
The "edits" (in this case the automated conversion of the Editor content?) are reverted and the confirmation footer disappears.

**Kirby Version**  
3.5.0

**Console output**  
No console output.

**Desktop (please complete the following information):**  
 - OS: Linux Mint 19.3
 - Browser: Firefox
 - Version: 83.0

**Comment by afbora** [comment]
Related or same with #3126

**Comment by afbora** [comment]
@sebastiangreger Can you confirm that this issue persists in 3.5.5 or 3.5.6? It may have been fixed with #3126

**Comment by sebastiangreger** [comment]
@afbora Sorry to report, I am still unable to revert in the scenario mentioned with 3.5.6.

**Comment by afbora** [comment]
@sebastiangreger Thank you for testing again 🙏 I hope we fix it as soon as possible.

**Comment by afbora** [comment]
@bastianallgeier By the way, will we still support switching from Editor plugin to Block field in 3.6? We might even consider removing the editor migration in 3.6. What do you think?

**Comment by bastianallgeier** [comment]
@afbora let's do that in 3.7. No need to rush this in my opinion. But I wonder if we should actually still fix the revert issue to be honest. It can be fixed by saving the changes. That's why it has a pretty low priority if you ask me.

**Comment by afbora** [comment]
You're right. Only 1 major version would be a bit too fast. 3.7 is OK.

Saving changes is a bit of a hassle. Because the default rel anchor only appears when you click on an block with a link. After pasting, it is necessary to manually click on each block with a link in it.

**Comment by bastianallgeier** [comment]
But the revert bar only appears when you click into one of them, right? So if you don't click, you don't have to do anything. I think that's fine.

**Comment by bastianallgeier** [comment]
But maybe we can check if it's possible to always add the same attributes to the links anyway.

**Comment by afbora** [comment]
> But the revert bar only appears when you click into one of them, right? So if you don't click, you don't have to do anything. 

This is true. But when the user clicks on a block with a link in it, the savebar will appear. But user is sure that doesn't changed anything yet. It will click to revert but fail. This is quite confusing. It seems to be a frequent issue, especially after the new copy/paste.

**Comment by bastianallgeier** [comment]
I found a solution! See the PR above.

**Comment by bastianallgeier** [comment]
✅
