### ISSUE TITLE
Panel brand depending on environment (local, development, production)

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#301]
Often there is a version on localhost and a live version. The only way to see where you are is to look at the url which can be missed.

For Kirby 2 I developed https://github.com/jenstornell/kirby-panel-brand

![image](https://user-images.githubusercontent.com/927011/38013446-7526525e-3265-11e8-909c-7e014b53b8eb.png)

The problem with it is that it's kind of a hack. It uses panel css. If the Kirby 2 panel css will be updated, this plugin could easily "crash". Also the "Panel brand" text is not linkable because javascript is not allowed. The "branding" needs to be on all panel pages like dashboard, pages and files etc.

1. If you think there is a need for branding the panel by environment, maybe feature it in the core. Settings like `panel.environment.color`, `panel.environment.favicon`, `panel.environment.sitename` etc.
1. If you don't like the idea and it's up to the plugin developers, how can we approach this in a non hacky way? If there will be no better way than a panel.css I would stick with that.

**Comment by distantnative** [comment]
I think this would be an ideal case for a future usage of CSS vars: https://github.com/k-next/starterkit/issues/409
