### ISSUE TITLE
Additional keyboard shortcuts for Blocks

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3010]
Following up from a [conversation on Discourse](https://discord.com/channels/525634039965679616/761608160565133343/788736539340570644):

> Bastian Allgeier: more power shortcuts are definitely planned! We've already implemented Alt+Shift+Up & Alt+Shift+Down to add keyboard support to sort blocks and I'm more than happy to add more of them.

@bastianallgeier suggested to open this ticket as a place to collect/discuss ideas for useful Blocks keyboard shortcuts.

**Comment by sebastiangreger** [comment]
Ideas:
* pressing some key combination (whatever is deemed an appropriate shortcut cross-platform) and the **"Add block below"** modal pops up, user can use arrow keys and Enter to choose the next block and continue writing almost uninterrupted (maybe even a separate key combination to "Add block *of same type* below"?
* **"Open drawer"** could be convenient; in particular for blocks where the drawer contains additional fields
* **"Duplicate current block"**

**Comment by adamkiss** [comment]
For mac, this translates to "Ctrl + shift + up/down", and up works okay, but down stops working (somehow deselects/defocuses the block selected) after one press. Should that be additional issue, or is this for all shortcuts?

**Comment by adamkiss** [comment]
To add to the discussion; For now, and after experiencing both editor and blocks (and Notion, and other such editors), these are implementations I enjoyed previously (a bit different from @sebastiangreger 's ideas for new blocks)

- `Ctrl+Enter / Alt+Enter / []+Enter`: create new [default: text] block
- `Backspace` in empty block: delete it and focus previous block if possible
- Switching type of block based on first X character in empty text block:
  - `- ` switches to List type
  - `# ` switches to Heading type
  - `> ` switches to Quote
  
These are of course from Markdown and other editors; Perhaps blocks could define their own "Power sequence" to switch from paragraph (default) block, this would help making it a systemic option.

I admit, that's quite a bit from having defined "key combination" for "block type XYZ" or "duplicate block", and my ideas/hope stem mostly from Power User's editing fluidity.

**Comment by bastianallgeier** [comment]
Can we move this discussion to Nolt, please? We are currently trying to get back in control of our issues. I hope you understand.

**Comment by sebastiangreger** [comment]
↦ https://kirby.nolt.io/351
