### ISSUE TITLE
[Panel] PageSection with `status: all`

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#302]
As an idea. Would still be nice sometimes to only include one page section in a blueprint that shows all subpages. Of course features as sorting would have to be disabled, but the add button could always add a page as a draft to that section for example.

**Comment by distantnative** [comment]
Related to #303

**Comment by wottpal** [comment]
Good Morning ☀️

Why does sorting have to be disabled? 🤔Can't just unlisted- & draft-pages be highlighted as that and still be within the sorting flow? They would be ignored anyway when only `->listed()` pages are chosen in a template and the sorting of them stays the same. Imo it seems to be a quite common scenario in a "simple" publishing workflow to not have extra tables for each publishing-state.

**Comment by texnixe** [comment]
I think this is feature that should really be re-implemented. It just doesn't make sense to have multiple sections for each blueprint. I'd expect to be able to add a page even if I only want to show the currently   published pages.

**Comment by bastianallgeier** [comment]
✅
