### ISSUE TITLE
[SECURITY] .htaccess default configuration can be insecure

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#302]
PhoenixPeca on the Kirby forum [posted a security issue with the default .htaccess](http://forum.getkirby.com/t/very-important-security-issue-most-kirby-website-could-be-vulnerable-to-this-attack/2108?u=lukasbestle).

The reason why the issue is only present on some servers could be that some servers need the `RewriteBase` setting to work properly.
Maybe this should be written more directly in the docs or even activated by default in the .htaccess. I know that the `RewriteBase` is currently commented out because of subdirectory installations, but that could also be made more clear in the docs.

**Comment by bastianallgeier** [comment]
I just fixed this in all kits by activating the RewriteBase setting by default. I will write a blog post about it now.

**Comment by lukasbestle** [comment]
Enabling the `RewriteBase` setting alone will probably not fix this issue on all servers. See the discussion [in the forum](http://forum.getkirby.com/t/very-important-security-issue-most-kirby-website-could-be-vulnerable-to-this-attack/2108?u=lukasbestle).

I think you should prepend a slash in front of `error` as well.

**Comment by bastianallgeier** [comment]
I might just have found a better solution, which could fix

**Comment by lukasbestle** [comment]
I think that this is a great solution. Because if that fails, all other pages fail as well, which means that users will notice a misconfiguration quite early.

I think you should also implement a route in the Kirby core that always uses the error page when a matching request is found to make sure that existing pages with these URIs don't get displayed (this can be quite confusing).
This route should be based on custom directory settings.

**Comment by bastianallgeier** [comment]
I'm super sorry, but I totally don't get the second half of your answer :)

**Comment by lukasbestle** [comment]
Let's say a user has created a page `site/whatever`. Until now, this page wasn't accessible at all, because access was blocked by the `RewriteRule` (or not, but at least requests didn't get through to Kirby). After this change, the page would be accessible, which is a breaking change.

I think that it can be confusing if some requests to the blocked directories are passed to Kirby and some are served directly from the directories by Apache (the non-blocked ones like files). So if you have a page `content/whatever.txt`, it won't work and the user will wonder why. The solution would be to block rendering of these pages completely.

**Comment by bastianallgeier** [comment]
You are right! Now I got it. But that's definitely a fix that is not that urgent. The Rewrite fix has to come first — even without the additional routes — in order to get this out of the way.

**Comment by lukasbestle** [comment]
Yes, definitely. This is more a feature than a security fix.

**Comment by malvese** [comment]
The change in .htaccess, from error to index.php, works for me (tested on OVH shared hosting). I didn't have to activate the RewriteBase.

Note: if anyone tries it, remember to empty your cache and perhaps cookies after the change.

**Comment by bastianallgeier** [comment]
Ok, I made some more tests and this solution seems to be by far the best and most reliable. I already added it to all kits and downloads and just posted an article with instructions: http://getkirby.com/blog/check-your-rewrite-base
