### ISSUE TITLE
FEATURE: Blocks field - Change Type blueprint option

### ISSUE THREAD

**Issue by mynameisfreedom** [getkirby/kirby#3024]
It would be useful to add the Change Type option to the Blocks field.
So, we could make it `changetype: false`
Especially needed for complex blocks.

**Comment by distantnative** [comment]
@mynameisfreedom Since this is a feature suggestion, could you please move this to https://feedback.getkirby.com? This would help us to better keep track of ideas and would also let other users upvote your idea.
