### ISSUE TITLE
Files section pagination breaks on multiple lines when long help text is used

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#3027]
**Describe the bug**  
I have a files section with a lengthy help text. The pagination buttons wrap on multiple lines:

![image](https://user-images.githubusercontent.com/5570098/102870168-525a1680-4445-11eb-958c-b20aab7f64e7.png)

This can be fixed by adding `flex-shrink: 0;` to `.k-collection-pagination`:

![image](https://user-images.githubusercontent.com/5570098/102870140-4706eb00-4445-11eb-8bc6-9225306c7c10.png)

**Kirby Version**  
3.4.2

**Comment by afbora** [comment]
I've reproduce the issue on 3.5.0 too and you suggestion works great 👍

**Comment by bastianallgeier** [comment]
✅
