### ISSUE TITLE
Cannot Upload or Replace .json File in Panel ("Invalid file type: code")

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3031]
**Describe the bug**  
In Kirby 3.5.0, I cannot replace existing .json files in the Panel. I get the following 400 response:
```
{
    "status": "error",
    "message": "Invalid file type: code"
}
```

**To Reproduce**  
1. Have a `files` section
```yaml
        sections:
          files:
            type: files
```
2. Try to upload any `.json` file

**Screenshots**  
<img width="502" alt="Screen Shot 2020-12-23 at 2 08 45 PM" src="https://user-images.githubusercontent.com/417182/103040476-63c81f00-4528-11eb-971a-ccd56e01c935.png">

**Kirby Version**  
`3.5.0`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari Version 14.0.2 (16610.3.7.1.9)

**Additional context**  
Works fine in `3.4.5`

**Comment by afbora** [comment]
@neildaniels Can you take a look at this issue? I think it's the same situation. Related issue: https://github.com/getkirby/kirby/issues/3030

**Comment by neildaniels** [comment]
Yep, same situation. Adding `accept: true` works.

I think offering a "Replace" menu item for something that will knowingly fail should be treated as a bug in this situation. Based the "default" Blueprint, JSON files shouldn't be accepted, but one already existed and is displayed.

If replacements aren't going to be fully allowed (and thus an "exemption" from the rule), then that menu item should probably just be grayed out.

<img width="190" alt="Screen Shot 2020-12-23 at 2 24 36 PM" src="https://user-images.githubusercontent.com/417182/103041320-ece05580-452a-11eb-8279-7d755cd969e4.png">

**Comment by afbora** [comment]
Yes, it would be more correct to have the menu item disabled. But actually, you are experiencing this situation because this file is already uploaded. This file wouldn't be uploaded unless it was on the allow list anyway. But I don't know if an improvement needs to be done for manually uploaded situations. @lukasbestle will provide the information on this subject.

**Comment by lukasbestle** [comment]
I agree that this is a bug. The "Replace" option should be disabled (grayed out) if the file wouldn't be accepted when being replaced with itself.

**Comment by bastianallgeier** [comment]
✅
