### ISSUE TITLE
`flag` prop of k-card and k-list-item is broken

### ISSUE THREAD

**Issue by steirico** [getkirby/kirby#3033]
**Describe the bug**  
Commit 7ded08b89ef6066beafb243cf86bc23e0a129cce introduced a non-documented breaking change to the `flag` prop of `k-card` and `k-list-item` components.

The bug prevents using the `flag` prop in a generic manner as described [here](https://getkirby.com/docs/reference/plugins/ui/card#props) and [here](https://getkirby.com/docs/reference/plugins/ui/list-item#props). Instead, the `flag` prop is restricted/dedicated to page status indication since the generic `k-button` component has been replaced by the new and very specific `k-status-icon` component.

**To Reproduce** / **Expected behavior** 
A Vue component as the following one will not display the `trash` icon instead, the `circle` icon appears because of https://github.com/getkirby/kirby/blob/master/panel/src/components/Misc/StatusIcon.vue#L37.
```js
<k-list>
  <k-list-item key="item-a"
    :icon="{type:'calendar', back:'white'}
    :text:"Closer"
    :info:="28.02.2021"
    :flag="{icon: 'trash'}"
  />
</k-list>
```
![image](https://user-images.githubusercontent.com/10421363/103177242-10800480-4879-11eb-8960-3e3a9b28a347.png)

**Kirby Version**  
3.5.0

**Comment by bastianallgeier** [comment]
✅
