### ISSUE TITLE
V::email validation helper not working as expected

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#3036]
**Describe the bug**  
Validation via helper V::email is not working as expected. E-Mail with one domain suffix is counted as valid.

**To Reproduce**  
```
if (V::email('fancy@getkirby.com')) {
       // .com - ok - 3 chars
}
if (V::email('fancy@getkirby.ch')) {
      // .ch - ok - 2 chars
}
if (V::email('fancy@getkirby.c')) {
     // .c - not ok - 1 char
}
```

The validation is not checking the domain suffix length. A valid E-Mail address should have at least 2 characters in the domain suffix. The validator should not accept domain suffix less than 2 chars.

**Kirby Version**  
3.5

**Comment by afbora** [comment]
Kirby uses [filter_var()](https://www.php.net/manual/en/function.filter-var.php) function in `V::email` and the e-mail address entered using this method seems valid.

    filter_var('fancy@getkirby.c', FILTER_VALIDATE_EMAIL);

**Comment by findthebug** [comment]
Seems to be a general issue with FILTER_VALIDATE_EMAIL because e.g. localhost@localhost could also be a valid domain/ email in a local network.

maybe an option would be nice, which checks the length of the TLD.

V::email($email, $tld = true)

**Comment by afbora** [comment]
I think it is a very special need. Let's ask the @getkirby/kirby-staff

**Comment by findthebug** [comment]
I currently have the problem that users sometimes enter a wrong TLD like. c instead of .ch or .d instead of .de. ….for some reasons.

because of this e.g. password reset request, sending emails, and so on.... can cause issues. In real world scenarios, there is no email with just on TLD char. For me this looks like a simple fix, just to test the TLD length. At the end, i can do this by myself but it would be cool to see this in the V::validator.

**Comment by lukasbestle** [comment]
I like the idea of a second parameter that would be `true` by default:

```php
'email' => function ($value, bool $validateTld = true): bool {
```

We can only introduce this in the next major release (3.6.0) though because of the breaking-change.

**Comment by bastianallgeier** [comment]
@lukasbestle do you already have a solution to validate the TLD? Would we only check for the length or do a real network call to check the validity?

**Comment by lukasbestle** [comment]
I looked at the code again. Considering we use PHP's `filter_var()` helper (which is a total blackbox), we cannot easily implement this ourselves. The general idea would be "if `$validateTld === true`, do it like before, otherwise be lax about it". But how would we implement the lax validation? We would need to reimplement `filter_var()` ourselves.

In any case I wouldn't actually look up the DNS name. This could be abused for attacks.

**Comment by distantnative** [comment]
If we don't want to validate TLD, could we replace the tld with `.com` and pass it to the `filter_var()`?

**Comment by lukasbestle** [comment]
Sorry, I misread the issue before. It should be the other way around: `false` is the current behavior, `true` would be an additional validation.

To be honest I wonder if we should actually implement this in the core. It's quite complex to get right. Basically we would need to ship Kirby with a list of all valid TLDs.

Maybe it's better to implement this in a plugin.

**Comment by afbora** [comment]
True tld checking would be a really massive and complex development. What if it was just simple length control?

**Comment by bastianallgeier** [comment]
I feel like we are running into a typical case here, were we try to solve an unsolvable issue and instead we risk to add more issues than we actually solve. It's similar to a 100% solution to validate URLs. It simply does not exist. We build on top of the most solid solution in PHP land and that's kind of where we have to leave it. This issue is the main reason why pretty much all sign ups include an email activation link to verify the email address.

**Comment by afbora** [comment]
> We build on top of the most solid solution in PHP land and that's kind of where we have to leave it. This issue is the main reason why pretty much all sign ups include an email activation link to verify the email address.

💯 

At the same time, in such cases, developers can add as much complicated validation as they want with custom validators:

https://getkirby.com/docs/reference/plugins/extensions/validators

**Comment by lukasbestle** [comment]
I agree with Bastian and Ahmet. We cannot easily solve this in the core unfortunately.

@findthebug Your best bet would be to use two validators: The core `email` validator for a basic check for general validity and in addition a second custom validator that just validates the TLD to your needs (length or even an allowlist). As validators are treated as AND conditions, Kirby won't allow values where either validator fails.

**Comment by findthebug** [comment]
what about regex as an parameter?

**Comment by lukasbestle** [comment]
You can use our `match` validator to validate against a regex: https://getkirby.com/docs/reference/system/validators/match
