### ISSUE TITLE
Panel: Date field not possible to close within structure

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3037]
**Describe the bug**  
Normally, when opening the date picker in a date field, a mouse click outside the date picker or focussing on another field closes it. This is not possible within a structure field (only way to close the date picker without picking a date is to close the structure item entirely).

**To Reproduce**  
1. Create a blueprint with a structure field that contains a date field and some other (e.g. text) field
2. In the panel, choose "Add" for the structure
3. Click on the date field; the date picker opens
4. Now click on the text field or elsewhere within the structure area
5. The date picker remains open and cannot be closed

**Expected behavior**  
The date picker should close when moving focus away from it.

**Kirby Version**  
3.5.0, but this also applies on 3.4.5

**Console output**  
No console output.

**Desktop:**  
 - OS: Linux Mint 19.3
 - Browser: Firefox
 - Version: 84.0.1

**Additional context**  
Potentially related to #3004 ?

**Comment by distantnative** [comment]
✅ Will be fixed in upcoming 3.6.2
