### ISSUE TITLE
API cache unlink error

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#3039]
**Describe the bug**  
Strange bug in the api cache, which happens from time to time. I can't figure out what the problem is. My project uses a lot of api caches, which i use inside the template, route or controller. I can just provide screenshots to report the issue, not sure how i can log this? Because the issue is super rare(1 of 100), i can just post what my setup is and the steps to try to reproduce this.
 

**To Reproduce**  
1. Setup a basic api cache, like from the cookbook or take this one. this is located in the home template. 

```php
$named = "y_day_1";
$apiCache = $kirby->cache('api');
$apiDataSave = $apiCache->get($named);
if ($apiDataSave === null) {
    $query = // whatever you wanna store
    $apiDataSave = $query;
    $apiCache->set($named, $apiDataSave, 720);  // 60 = 1h
}
$yoohExists = $apiDataSave;
?>
```

2. On both, first load, and second load the data are loaded/stored properly. In this one i using a 1 day cache time, but this does not matter. I have the same problem with 30min and 1min caches.  Not sure yet this error happens if i deactivate the cache time at all. 

3. You can reload the page as many times you like. As long as the data is served via the cache no issues. The problem is, when the cache is expired and you load the page again, so the api has to rebuild the file and cache.

4. Now, the error happens maybe 1 of 100 times, if step 3 come into play.
5. Error happens -> Error screen
6. Cache file are deleted, and rebuild.
7. Page reload -> Page with new data appears.
8. Everything works except that kirby displays the message with the unlink.

As far as i can tell, the error has nothing todo with the kind of what you caching or the cache time, it's more about how Kirby is handling the check of unlink the file. 

**Additional context**  
Im running all of this inside a vagrant box.

**First guess:**
Maybe it has something todo how vagrant is syncing the files between host and guest system, and when kirby is deleting the new file, vagrant guest is maybe 1ms behind get confused when the unlink is performed? But beside this i have no idea. 
 
 
**Version**  
Kirby 3.5.0
Vagrant debian / PHP 7.4.8
OSX 10.15.7
Safari and Chrome
 

**Screenshots**  
1.
<img width="1343" alt="error_1" src="https://user-images.githubusercontent.com/5121132/103405517-ba9cac80-4b57-11eb-8eec-bfc656df5686.png">
2.
<img width="2048" alt="error_2" src="https://user-images.githubusercontent.com/5121132/103405548-ce481300-4b57-11eb-8806-9fb01ac01859.png">
3.
<img width="1246" alt="error_3" src="https://user-images.githubusercontent.com/5121132/103405559-d607b780-4b57-11eb-9652-67566c488d16.png">

1.-> same error but with another api-cache.
<img width="2012" alt="error_other_one" src="https://user-images.githubusercontent.com/5121132/103405654-17986280-4b58-11eb-9980-fe8cd528a07c.png">

**Comment by afbora** [comment]
Actually `F class` [checks if the file exists](https://github.com/getkirby/kirby/blob/3.5.0/src/Toolkit/F.php#L678-L680) before deleting it but I guess the issue might be related to vagrant. I have tested it in a few different ways in my local, the issue does not appear for me 🤔

**Comment by findthebug** [comment]
What env do you use to run kirby?

**Comment by afbora** [comment]
Kirby 3.5.0
- Centos 6.9 & PHP 7.3.25
- Windows 10 & PHP 7.3.14

---

My guess is the same as yours @findthebug . It is a issue that can occur due to a very small delay (as your said like 1ms) or when there are many instant requests. May be we can handle this error slightly with suppress or empty try/catch block.

**Comment by findthebug** [comment]
Is there a way to log this error if i disable debug mode? i have a proper server(not vm) i can test this.

**Comment by afbora** [comment]
No, as far as I know 🤔 You can try logging manually?

**Comment by findthebug** [comment]
I will try something.

**Comment by afbora** [comment]
@findthebug Did you test it?

@lukasbestle How about we suppress all unlinks?

**Comment by findthebug** [comment]
Im still try to log this in production. no issues so far and the project is live for 3 weeks now. i think the filesync in vagrant cause the issue. if vagrant filesync is just some mS behind the host filesystem is not up to date and php gets not proper state of the demanded file.

**Comment by afbora** [comment]
Then if you want, let's close the issue, if it recurs, let's reopen it, is it okay?

**Comment by sjaq** [comment]
Running into this exact problem as well. But reading the flow of the code it makes total sense that the `unlink()` call can fail when there's two requests simultaneously accessing the same cache value. Simply wrapping the `unlink()` call in a `try { } catch () {}` block would fix this? 

For now I'm simply wrapping all my cache access in a similar way to work around this problem.

**Comment by bastianallgeier** [comment]
✅

**Comment by sjaq** [comment]
Nice thanks!
