### ISSUE TITLE
Consistent TODO comments

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3040]
Currently we use both `TODO:` and `@todo`.
Would be good if we could agree on one style. Or at least one style per language (if we think we need to have different ones for JS and PHP).

Lukas is voting for `@todo` (at least for PHP).
I have been using `TODO:` but open for change.

@afbora @bastianallgeier what would be your preferences?

**Comment by afbora** [comment]
I think both are the correct use. `TODO` in comment lines, `@todo` in docblocks.

````php
/**
 * @todo The locale magic should no longer be
 */
public static function encode($data): string
{
    // TODO: The locale magic should no longer be
}
````

If we only choose one, I would write in detail what to do in the method in `@todo` in docblock.

Also `PhpStorm IDE` default pattern finds both uses.

**Comment by lukasbestle** [comment]
I really like @afbora's proposal to differentiate between docblocks and single-line comments. That totally makes sense.

**Comment by distantnative** [comment]
I agree, that sounds good. https://github.com/getkirby/kirby/pull/3042
