### ISSUE TITLE
Workflows: only run when certain files changed

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3041]
We could restrict our workflows to only run when specific files changed, e.g.
- PHPUnit, Psalm etc. only if any `.php` file has been changed
- Vue/JS unit tests and linting, only when `.js` or `.vue` file has been changed

**Comment by lukasbestle** [comment]
@distantnative

As far as I can tell, the only way to do this properly is to split our CI workflow up into two workflows, one for the frontend and one for the backend.

Advantage: The workflow files would be shorter and easier to scan.  
Disadvantage: In the GitHub Actions UI, there would be two different workflow runs to click through (meaning up to four for PRs). However, all checks are still going to end up in one list in the PR.

What do you think?

Also, as we discussed previously, I'd only limit CI execution on PR, but always run all tests on push. This avoids that we miss problems in edge-cases.

The general question is: Do we really need to limit test execution? Our tests are not that resource and time hungry as they are done in just a few minutes – and all tests run in parallel. I think it would really make a lot of sense if our tests ran for an hour or longer (which they do in some projects). But for Kirby this whole change would only really complicate the setup. So I'm actually leaning towards not doing any changes to CI execution at all.

**Comment by distantnative** [comment]
If splitting up the workflows is trouble, let's leave it then. If it becomes a bigger problem (lot longer runtimes once we actually use Cypress tests), let's return to the issue then.
