### ISSUE TITLE
Uppercase letters and untranslatable fields issue

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#3045]
**Describe the bug**  
As per @lukasbestle instructions i'm opening a new issue related to #2599
I finally found the cause of this odd issue.

Uppercase letters inside fields keys are messing with the expected behaviour when duplicating pages with untranslatable fields.

Attached there's a video that will show you what the bug is and it's pretty self explanatory.

https://user-images.githubusercontent.com/1738077/103525976-64de4200-4e80-11eb-82d2-506caafffc2c.mp4

**Kirby Version**  
Bug still there in 3.5.0

**Comment by afbora** [comment]
@manuelmoreale First of all, thank you for your detailed reporting 👍 

This is a known issue #2577 and it will be fixed in v3.6 as there will be breaking changes.

**Comment by manuelmoreale** [comment]
@afbora ah excellent. I didn't check for new issues because my old one was still marked as a bug.
Good to know it's a known issue. Luckily the workaround is to simply use lowercase letters so all good.

And happy new year ;)
