### ISSUE TITLE
Support for Hebrew and Arabic letters in slugs

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#3049]

**Comment by mrflix** [comment]
I'm currently migrating a Wordpress installation to Kirby and I encounter this limitation, that slugs can't contain arabic letters. What's the challenge with that?

My example: https://gsbtb.org/opinion/%D8%B1%D8%B3%D8%A7%D8%A8%D8%A9-%D8%AD%D8%A8-%D9%84%D9%84%D9%84%D8%BA%D8%A9-%D8%A7%D9%84%D8%BA%D8%B1%D8%A8%D9%8A%D8%A9-love-letter-to-arabic/

Which turns into a beautiful arabic url in the browser:
<img width="386" height="40" alt="Image" src="https://github.com/user-attachments/assets/c0ecb42e-dce1-4688-a10d-ff7a738c6350" />

When I try to paste the arabic slug as the folder name it turns the whole string right-to-left:
<img width="740" height="98" alt="Image" src="https://github.com/user-attachments/assets/ac5d185c-8eab-4f05-990e-ae849e451394" />

Ok, challenge.
