### ISSUE TITLE
Bootstrap Jumbotron slider issue

### ISSUE THREAD

**Issue by shannongmclean** [getkirby/kirby#305]
Has anyone tried using bootstrap's jumbotron slider with kirby? I don't have a problem pulling the images from the active page directory but with the following code:

<?php foreach($page->files()->shuffle() as $image): ?>

    <div class="active item">
      <div class="fill" style="background-image:url('<?php echo $image->url() ?>');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('<?php echo $image->url() ?>');"></div>
    </div>
 <?php endforeach ?>

It's obvious to see I will repeat each image twice, when I want to show each image in a ABCDEF.. sequence. 
Let me know if this needs further explanation.

With appreciation,
Shannon

**Comment by distantnative** [comment]
So why do you include the image twice and not just the following?

```php
<?php foreach($page->files()->shuffle() as $image): ?>

<div class="item">
  <div class="fill" style="background-image:url('<?php echo $image->url() ?>');"></div>
</div>
<div class="item">
  <div class="fill" style="background-image:url('<?php echo $image->url() ?>');"></div>
</div>
<?php endforeach ?>
```

**Comment by shannongmclean** [comment]
Bootstrap requires an "active" class to begin the slideshow. If I repeat "<?php echo $image->url() ?>" I'll be starting from the same image in the active class. That's why I tried to "shuffle()", but that's only on pageload.

**Comment by texnixe** [comment]
You can use a helper variable together with an if-statement:
```php

<?php $i= 0;
foreach($page->files()->shuffle() as $image): ?>
    <div class="<?php if($i = 0) {echo 'active'; } item">
      <div class="fill" style="background-image:url('<?php echo $image->url() ?>');"></div>
    </div>
 <?php $i++; endforeach ?>
```
