### ISSUE TITLE
Collection name is already in use

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#306]
When I was trying to get up and running with [Alpha 6](https://www.notion.so/Alpha-6-dfd8dcbd327d46f88fc243eac6953a79) I got the following error:

`Fatal error: Cannot use Kirby\Collection as Collection because the name is already in use in /Users/…/kirby/kirby/src/Collection/Finder.php on line 6`

I removed `use Kirby\Collection;` and everything went smoothly.

```
<?php

namespace Kirby\Collection;

use Exception;
use Kirby\Collection;
```

It might be something related to the setup since I did not see any complaints on Slack and no issues here… but better to be safe then sorry

- Apache/2.4.28
- PHP 7.1.13

🤷‍♂️

**Comment by bastianallgeier** [comment]
✅
