### ISSUE TITLE
Text field: No autocomplete/spellcheck by default

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3063]
**Describe the bug**  

The `TextInput.vue` sets `autocomplete=off` and `spellcheck=off` by default.

**Expected behavior**  

The `spellcheck` attribute should default to being not set (so the browser's default will be used). The `autocomplete` attribute is probably subjective and depends on the use-case. But it should be added to the docs and it should be explained how the default browser behavior can be enabled.

**Kirby Version**  

3.5.0

**Comment by bastianallgeier** [comment]
This turns out to be way more challenging than expected. I will move it to 3.7 for our general form changes.

**Comment by distantnative** [comment]
@bastianallgeier i think this was falsely closed?

**Comment by afbora** [comment]
Yes 3.6 doesn't include related commit changes. I guess because `Fix #3063` is mentioned in the commit description, it was closed automatically when 3.6 was released.
