### ISSUE TITLE
api/translations/:code does not return custom language variables

### ISSUE THREAD

**Issue by renestalder** [getkirby/kirby#3064]
**Describe the bug**  

As [previously discussed in the forum](https://forum.getkirby.com/t/improve-documentation-for-translations-api-endpoints/20654), the [`api/translations/:code`](https://getkirby.com/docs/reference/api/translations/get) endpoint returns all translations, including plugins, but doesn't return custom language variables as defined in the translations field of e.g. `site/languages/de.php`.

**To Reproduce**  
1. Define custom language variables in one of your translation files, e.g. `site/languages/de.php`:  
    ```php
    <?php
    
    return [
        'code' => 'de',
        'default' => true,
        'direction' => 'ltr',
        'locale' => [
            'LC_ALL' => 'de'
        ],
        'name' => 'Deutsch',
        'translations' => [
            'labelname' => 'Name',
            'labelemail' => 'E-Mail',
            'labelresidence' => 'Wohnort',
            'labelquestion' => 'Frage stellen',
            'labelquestionsubmit' => 'Frage einsenden'
        ],
        'url' => ''
    ];
   ```
2. Query the `api/translations/de` endpoint

**Expected behavior**  
The result set of the API request to include the custom language variables.

**Screenshots**  
–

**Kirby Version**  

3.5.0

**Console output**  

**Desktop (please complete the following information):**  
Not relevant

**Smartphone (please complete the following information):**  
Not relevant

**Additional context**  
–

cc @distantnative

**Comment by bastianallgeier** [comment]
✅

**Comment by renestalder** [comment]
:cool: :cool: :cool:

Looking forward to that. Already had to write a copy and parser task that moves the translations from the Kirby PHP project over to the decoupled front-end to work around it.

Very appreciated that this already went through the pipeline. Thank you.
