### ISSUE TITLE
Block readme.md in .htaccess

### ISSUE THREAD

**Issue by thilotanner** [getkirby/kirby#307]
I suggest to block the readme.md in the .htaccess as well (like content, site and others). Developers tend to use the readme.md to document potentially confidential information concerning setup, environment etc. in this file. Using .htaccess as-is makes it possible for everyone to download the readme.md.

Thanks!

**Comment by maxfenton** [comment]
Good point.

**Comment by bastianallgeier** [comment]
Very good point indeed! Here's my current concept for the rewrite rules for the next release. Any comments appreciated!! 

```
# block access to all unbrowsable files
RewriteRule ^.*\.(txt|md|mdown|yaml|yml|json|xml|svn.*|git.*)$ - [NC,R=404]

# block access to all site and kirby files
RewriteRule ^(site|kirby|panel/app|panel/test)/.*$ - [NC, R=404]

# make panel links work
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^panel/(.*) panel/index.php [L]

# make site links work
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) index.php [L]
```

**Comment by lukasbestle** [comment]
Looks great! I'd add a check for existing files for the first rule though. Otherwise pages that end with `.xml` for example (like sitemaps handled by Kirby) won't work anymore.

**Comment by maxfenton** [comment]
Yeah, I'd omit xml and json from that first piece, for sitemaps and data. Trying to think of a JSON example -- just seems like something to leave open for the future.
