### ISSUE TITLE
Replacing files fails on iOS 14

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#3077]
**Describe the bug**  

Replacing files on iOS 14 leads to a page reload. 

**Kirby Version**  
3.5.0 

**Smartphone (please complete the following information):**  
 - Device: iPhone 
 - OS: iOS 
 - Browser: Safari
 - Version: 14

**Comment by afbora** [comment]
I did not understand exactly how it gave an error because it works fine for me on IOS 14.3 and Safari 🤔

**Comment by bastianallgeier** [comment]
@afbora I got this report via support email. I didn't have time to test it yet myself.

**Comment by afbora** [comment]
@bastianallgeier Can you direct the person who posted the report here for more information?

**Comment by bastianallgeier** [comment]
@afbora unfortunately he does not have a Github account. I just tested your instance and it's working perfectly for me. I guess it's a problem on his end. I will get in contact with him again.
