### ISSUE TITLE
404's being cached too?

### ISSUE THREAD

**Issue by puckey** [getkirby/kirby#308]
I noticed that my cache directory contained many 404 error pages - shouldn't Kirby ignore the caching of these?

**Comment by bastianallgeier** [comment]
You are absolutely right. They shouldn't be cached at all. I just fixed this on the develop branch.

**Comment by puckey** [comment]
Thanks for this and the other fixes. We are very happy customers.

**Comment by bastianallgeier** [comment]
I'm very glad to hear that :) Thanks for your ongoing support!!
