### ISSUE TITLE
[Blocks] UI: Context menu obscured by Revert/Save bar

### ISSUE THREAD

**Issue by foxacid** [getkirby/kirby#3080]
**Describe the bug**  
The orange revert/save bar overlaps the context menu for the last block element on a page. This makes it impossible to delete the block without saving or reverting changes. 

**To Reproduce**  
1. Add a bunch of blocks to a page
2. Make a change so the orange revert/save bar appears at the bottom of the page
2. Click on the ··· context menu icon of the last block item

**Expected behavior**  
Expected behaviour would be a bottom margin that prevents the context menu from sitting underneath the bar so the delete/trash icon is accessible.

**Screenshot**  
![image](https://user-images.githubusercontent.com/12812201/104137241-acdaf880-539b-11eb-959b-487221223191.png)

**Kirby Version**  
3.5.0

**Comment by bastianallgeier** [comment]
Can you scroll down to reveal the rest of the menu?

**Comment by foxacid** [comment]
Nope. That's the problem...

**Comment by bastianallgeier** [comment]
Which browser and OS?

**Comment by foxacid** [comment]
Oh, sorry for not having posted that earlier. 

macOS 10.14.6
Firefox 84.0.2 (64-bit)

Just checked Chrome - same behaviour.

**Comment by foxacid** [comment]
There's a `margin-bottom: 6rem` on `.k-dropdown-content` but that doesn't have any effect as the element is absolutely positioned from the top.

**Comment by johannschopplich** [comment]
Same issue here on macOS Catalina with latest Firefox.

**Comment by afbora** [comment]
I can reproduce the issue. Source of error is `z-index` between `main.k-panel-view` and `nav.k-form-buttons` . But I have no idea for a solution.

**Comment by bastianallgeier** [comment]
Ah, I was just able to reproduce it as well. Weirdly, we have fixed this before and I actually thought we had it solved for good, which doesn't seem to be the case :(

**Comment by MikeHarrison** [comment]
Hi - I am sure this is being worked on, but just had a client hit this issue. Is there a way of hacking a fix using some custom CSS in the meantime?

**Comment by bastianallgeier** [comment]
✅
