### ISSUE TITLE
site()->index(true) returns no drafts in specific circumstances

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3082]
**Describe the bug**  
The collection returned by `site()->index(true)` does not include drafts (as it should as per specification) if it is called by a `page.update:after` hook for a page whose blueprint includes an option query that makes use of `index`.

**To Reproduce**  
1. Install a plain Starterkit
2. Add the following to `site/config.php`:

```php
'hooks' => [
    'page.update:after' => function ($newPage, $oldPage) {
        print_r(site()->index(true));
        die;
    }
]
```

3. Open a note in the panel and edit some text.
4. After pressing "Save", the JSON debugger screen shows a Pages Object with 22 pages (incl. `notes/in-the-jungle-of-sumatra` which is a draft page). So up to here, everything works as it should.
5. In `site/blueprints/note.yml`, replace `tags: true` with:

```yml
tags:
  type: tags
  label: Tags
  options: query
  query: site.index.pluck("tags", ",", true)
```

6. Open the same note as before in the panel and edit some text.
7. After pressing "Save", the JSON debugger screen again shows a Pages Object, but only with 20 pages (two drafts, incl. `notes/in-the-jungle-of-sumatra`, are no longer returned). 
8. Replace `query: site.index.pluck("tags", ",", true)` with `query: site.children.pluck("tags", ",", true)` or anything else that does not contain `index` and try again -- now the returned collection contains drafts again.

**Expected behavior**  
`site()->index(true)` should always return a Pages Collection that contains all pages incl. all drafts of the entire site.

**Kirby Version**  
3.5.0

**Additional context**  
Documentation of the original discovery of the bug here: https://forum.getkirby.com/t/in-some-contexts-site-index-true-returns-no-drafts/20776

**Comment by lukasbestle** [comment]
I'm pretty sure this is because the [`$pages->index()` method caches the resulting collection](https://github.com/getkirby/kirby/blob/3.5.1/src/Cms/Pages.php#L334-L336), but doesn't check whether the  `$drafts` value matches between the cache and the method call. So we need separate caches for the draft mode and for the normal mode.

**Comment by bastianallgeier** [comment]
✅
