### ISSUE TITLE
[Panel] Date field inside structure field not closing on unfocus/blur

### ISSUE THREAD

**Issue by foxacid** [getkirby/kirby#3084]
This issue relates to `date` fields inside `structure` fields. When clicking on a `date` field inside a `structure` field, the calendar overlay can only be closed by selecting/confirming a date or by clicking outside of the structure, which closes the whole structure. Clicking right next Also see related issue: https://github.com/getkirby/kirby/issues/3083

**Blueprint**

```
label: Events
type: structure
fields:
  date:
    type: date
```

**Video**

https://user-images.githubusercontent.com/12812201/104510440-7e535c80-55eb-11eb-8c08-f5e303a570ae.mov

**Expected behavior**  

The calendar overlay should close when clicking anywhere but the overlay itself (just like a HTML select box).

**Kirby Version** 

3.5

**Desktop** 

Mac OS 10.14.6, Firefox 84.0.2

**Comment by afbora** [comment]
Duplicated issue https://github.com/getkirby/kirby/issues/3037
