### ISSUE TITLE
List Items get saved with p-Tags in List-Block

### ISSUE THREAD

**Issue by seehat** [getkirby/kirby#3086]
When I Input the following list into a list field:

```
- One
- Two
  - Sub Two
- Three
```

the following get's saved into the content file:

```
<ul><li><p>One<\/p><\/li><li><p>Two<\/p><ul><li><p>Sub Two<\/p><\/li><\/ul><\/li><li><p>Three<\/p><\/li><\/ul>
```

The p-tags in every listitem result in the following output with a prose class to style the list:

![99947162-d7370f00-2d77-11eb-9d17-1a6941f7a9ec](https://user-images.githubusercontent.com/818248/104587711-9963b200-5667-11eb-85d4-21680a923a35.png)

Is this the expected behaviour to generate those p-Tags?

I think, that lists with no p-Tags are easier to style and that this is also the behaviour of markdown lists getting converted to html.

It seems that this is a prosemirror bug and I add it here to track the status: 
https://discuss.prosemirror.net/t/removing-the-default-paragraph-p-inside-a-list-item-li/2745/8

**Comment by texnixe** [comment]
Was already reported in the old repo: https://github.com/getkirby/blocksfeedback/issues/71

**Comment by bastianallgeier** [comment]
✅

**Comment by bastianallgeier** [comment]
✅
