### ISSUE TITLE
Image block: src label missing translation

### ISSUE THREAD

**Issue by johannschopplich** [getkirby/kirby#3087]
**Describe the bug**  

https://github.com/getkirby/kirby/blob/0d2751af7cb478df14f30fac47fe9a2cd3b38114/config/blocks/image/image.yml#L24

The translation string is missing here.

**To Reproduce**  

Not applicable.

**Expected behavior**  

Seeing a translated field value.

**Screenshots**  

Not applicable.

**Kirby Version**  

3.5.0 and 3.5.1-RC.1

**Console output**  

Not applicable.

**Desktop (please complete the following information):**  
 - OS: `blank`
 - Browser: `blank`
 - Version: `blank`

**Smartphone (please complete the following information):**  
 - Device: `blank`
 - OS: `blank`
 - Browser: `blank`
 - Version: `blank`

**Comment by bastianallgeier** [comment]
✅
