### ISSUE TITLE
[Panel] Blocks context menu not fully accessible with unsaved changes / can't remove last block with mouse

### ISSUE THREAD

**Issue by renestalder** [getkirby/kirby#3090]
**Describe the bug**  
_That was a difficult one to search for existing issues. I'm sorry if this is a duplicate issue._

The context menu to e.g. remove a content block, is not fully accessible when there are unsaved changes (when the "save" banner is visible) and the user tries to remove the last block in a layout.

This makes it probably impossible to remove the last block with the mouse/touch when there are unsaved changes, as the delete action flows under the "save" banner. The workaround is to save the changes first.

**To Reproduce**  
1. Create a page with layout fields for the panel
2. Create a couple of blocks in the layout fields, enough to make the viewport scroll.
3. Open the context menu for the last block

**Expected behavior**  
Either the context menu z-index to be over the "save"-banner or the save banner adding enough margin to the panel content so the context menu stays in view.

**Screenshots**  

![Screenshot from 2021-01-15 16-33-50](https://user-images.githubusercontent.com/105358/104746864-bf608380-5747-11eb-8f82-b29777db7ef5.png)

*The screenshot shows a panel view with blocks inside layouts, scrolled completely to the bottom of the page, with unsaved changes*.

**Kirby Version**  

3.5.0

**Console output**  
–

**Desktop (please complete the following information):**  
 - OS: Linux, Pop_OS (Ubuntu)
 - Browser: Firefox
 - Version: 85.0b8

**Smartphone (please complete the following information):**  
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afbora** [comment]
Thanks for report. Duplicated issue with https://github.com/getkirby/kirby/issues/3080
