### ISSUE TITLE
Date Field w/Time: "Today" button inserts wrong time (probably timezone related)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3094]
**Describe the bug**  
This is basically a re-opening of #3005. This issue actually seemed to be fixed in `3.5.1-rc.1` (thanks to #3075), but was reintroduced with #3092 reverting that.

**Kirby Version**  
`3.5.1`

**Comment by distantnative** [comment]
✅ This should be solved with the upcoming release of 3.6.2 - if the issue remains, please get in touch. Thank you!
