### ISSUE TITLE
Error when overwriting layout tabs

### ISSUE THREAD

**Issue by ronaldtorres** [getkirby/kirby#3095]
Before update Kirby this code work normally. I extend a blueprint layout from another blueprint and when I want to remove a tab I simply replace its content with a false, but now, this is throwing a JS error.

This is my user layout blueprint:
```yaml
tabs:
  # Info
  pages:
    label: Pages
    icon: page
  info:
    label: Profile
    icon: user
    columns:
      left:
        width: 3/4
      right:
        width: 1/4
```

This is my user blueprint:
```yaml
title: Admin
description: God access
extends: layouts/user.layout


tabs:
  pages: false
  info:
    columns:
      left:
      width: 1/1
        sections:
          info:
            extends: sections/users/user.info
          notes:
            type: fields
            fields:
              note:
                type: info
                text:  ''

      right: false
```

When I load the user profile page on panel I get:
![CleanShot 2021-01-19 at 16 38 30@2x](https://user-images.githubusercontent.com/44304163/105096336-e800ba00-5a74-11eb-869d-25bc884e2a99.png)

And when I remove or comment `pages: false` from the user layout the fields don't load:
![CleanShot 2021-01-19 at 16 41 23@2x](https://user-images.githubusercontent.com/44304163/105096575-4b8ae780-5a75-11eb-86f9-3589235eff5a.png)

EDIT:
When I inspect the browser console the error is produced in this line:
https://github.com/getkirby/kirby/blob/551e2f427eaf18e471df1c304552ab3de35e37c6/panel/src/components/Layout/Header.vue#L41

**Current Kirby Version**  
3.5.1

**Previous Kirby Version**  
3.4.4

**Console output**  

**Desktop (please complete the following information):**  
 - Browser: Safari 14.0.2

Hope you can understand it.

**Comment by afbora** [comment]
I can reproduce the issue. As workaround to avoid getting error dialog you can use following hidden fields instead `right: false`

````yaml
  right:
    sections:
      hidden:
        type: fields
        fields:
          gap:
            type: gap
````

**Comment by ronaldtorres** [comment]
@afbora Thank you. This temporary solution don't works for me :(

**Comment by afbora** [comment]
@ronaldtorres It worked for me, I can help if you send the full blueprint setup.

**Comment by tjabbe** [comment]
I am encountering the same issue on a project after upgrading from 3.4.x to 3.5. 

Edit: figured it out, had an old plugin laying around which had the column/sections bug, my bad! The method mentioned higher in the comment works.

**Comment by ronaldtorres** [comment]
@afbora Your solution works. I format correctly my blueprint as the property "width" was being recognized as a column and in the user json this was empty.

Thank you.

**Comment by bastianallgeier** [comment]
✅
