### ISSUE TITLE
[Panel] Add new page, with a clean slate

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#31]
When creating a page, now and in the past we need to add a title first in a modal box.

I think the perfect way to create a page is to click the "Add" button and then jump directly to a clean page without anything at all, not even a title, template or slug.

The panel url for the page could be like "temporary-page" until a slug is added. After the slug is added we could pick a template of our choice, still on the same page. When a template is selected, all the fields are loaded below it. It would be a very natural workflow.

About the template switching when a page already exists, then it's more complex and may need a new view, but not on creation.

**Comment by bastianallgeier** [comment]
We actually had exactly that in place already and only removed it temporarily because of some logic issues that needed too long to solve for the first alpha.
