### ISSUE TITLE
[Panel] DateField default does not get saved

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#310]
I was trying to figure it out what the `num` does in the `article.yml`.

I presupposed that it controls the "prefix" for the folder, like for the example folders `20160802.extending-kirby`

But the date field is not saved when creating the article. I guess this is why I ended up with `0.post-post` when creating an article with "Post Post" title

Here is the recording: [date-field-article.mp4.zip](https://github.com/k-next/starterkit/files/1859582/date-field-article.mp4.zip)

**Comment by ghost** [comment]
![screen shot 2018-03-29 at 13 21 28](https://user-images.githubusercontent.com/19433935/38084069-2b9c784e-3354-11e8-92cc-c7e0bdf9abce.png)

It seems the `date` it not sent

![screen shot 2018-03-29 at 13 23 35](https://user-images.githubusercontent.com/19433935/38084168-796cb962-3354-11e8-9aa0-ca73788fff87.png)

… and not saved in the Local Storage

**Comment by distantnative** [comment]
The bug seems to be that default selected dates do not get saved. If you do the same but select a date manually, it works.

**Comment by distantnative** [comment]
Depends on: #320

**Comment by ghost** [comment]
Just to complete

It does work when changing using the calendar picker, but the date is saved like this:

`Date: 2018-03-29T01:00:00+03:00` in the file.

Changing with the select input does not work.

**Comment by distantnative** [comment]
The saved format is correct. You can change it by defining the `format` option for the field.
But I am also working at refactoring the whole date & time fields and inputs right now, so Alpha 8 should have that fixed.

**Comment by ghost** [comment]
> The saved format is correct. You can change it by defining the format option for the field.

Got it. Thanks.

It was strange for me because the date format for the predefined blog pages have a simple `Y-m-d` format.

**Comment by distantnative** [comment]
✅ – This has been fixed on the `date-time` branch and will most likely make it into the next alpha.
