### ISSUE TITLE
The `info` on section blueprint cannot be translated

### ISSUE THREAD

**Issue by salimromadhon** [getkirby/kirby#3109]
**Describe the bug**  
I can't set `info` into multiple languages like I do on `headline`.

**To Reproduce**  
1. Install fresh starterkit
2. Open `site/blueprints/section/albums.yml`
3. Change `info`:
    ```
    info:
      *: "{{ page.images.count }} image(s)"
      id: "{{ page.images.count }} gambar"
    ```
4. Visit the panel using user with Bahasa Indonesia language set, you will see the error notice:  Invalid value for "info"
5. If you do the same way to `headline`, it works

**Expected behavior**  
It should works like `headline`.

**Additional context**  
The [documentation here](https://getkirby.com/docs/guide/blueprints/translations#text-of-headline-info-or-help-text) doesn't help.

Thanks.

**Comment by afbora** [comment]
This usage for fields, not sections. But we can add this improvement in later versions.

**Comment by bastianallgeier** [comment]
✅
