### ISSUE TITLE
Empty writer field leaves `<p></p>`, isNotEmpty() won't work

### ISSUE THREAD

**Issue by jnetzlr** [getkirby/kirby#3115]
**Describe the bug**  
When an empty writer field (without inline: true) is saved it leaves `<p></p>`. Thus, methods such as isNotEmpty() won't work.

**To Reproduce**  
1. Type something in a writer field, save the page.
2. Remove text from the field, save page.
3. Content file will now have `<p></p>`.

**Kirby Version**  
3.5.1

**Desktop:**  
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Version: 88

**Comment by bastianallgeier** [comment]
✅
