### ISSUE TITLE
$collection->filter('asin', 'bar') can be misinterpreted to use global `asin()` function

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3117]
**Describe the bug**  
In Kirby 3.5.0, `$collection->filterBy()` was consolidated with `$collection->filter()` which makes the following scenario more obvious:

If you want to filter by a field name that _also_ happens to be the name of a global function, the `$collection->filter()` method will prefer the global function instead of filtering by the field name.

**To Reproduce**  
1. Attempt to filter a collection with something like `$collection->filter('asin', '!=', '')`

Because `asin()` exists as a global PHP function, you'll receive an error like:
> asin() expects parameter 1 to be float, object given

**Expected behavior**  
Should filter items that have a non-empty `asin` field value.

**Screenshots**  
<img width="1081" alt="Screen Shot 2021-01-27 at 5 22 47 PM" src="https://user-images.githubusercontent.com/417182/106076377-4ad10180-60c4-11eb-8730-3617cefb63c7.png">

**Kirby Version**  
`3.5.1`

**Comment by bastianallgeier** [comment]
✅
