### ISSUE TITLE
[Panel] Improve StructureField "UX"

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#312]
I have some minor comments regarding the structure field.

1) It is possible to open an item by clicking anywhere on the row

This is nice - I think, but it does not work the other way around. Now it is only possible to close it by click on the 🔼 icon/button

I usually expect the things to work other way around. I close the door the same way as I open it.

2) The blue highlight

![image](https://user-images.githubusercontent.com/19433935/38084915-5a3e0688-3357-11e8-80a4-a9b141b79f28.png)

I find this rather odd for multiple reasons:

- I don't *feel* that it adds any emphasis. It is rather clear that the item is open without the blue
- That blue just does not "click" with the color scheme in general
- But the most disturbing part is the 🗑 icon being highlighted

3) Clicking on the 🗑 button/icon

It opens up the modal with the confirmation but it also trigger the action to show the fields. Maybe this is intended or just some actions happening in the same time, **but** when I cancel the modal action I do not want the row open. I did not click on the delete *necessarily* to edit the row. 

4) Keyboard navigation

I am using the TAB a lot. It is quite easy to navigate over the field and open up rows.

However I would definetly skip the drag button from the tabindex. I can't perform any action for the drag or at least I dod not figure it out how to. If an action can't performed lets just skip from the normal tabbing flow.

![image](https://user-images.githubusercontent.com/19433935/38085361-e8d22158-3358-11e8-83dd-4fefc73b3f18.png)

*This is my opinion* - I am not an UX expert in any way

**Comment by ghost** [comment]
Feel free to break my comments up in seperate issues if they are relevant :).

**Comment by wottpal** [comment]
Related #261

**Comment by bastianallgeier** [comment]
We fixed everything except the keyboard navigation issue for sorting. I will create another ticket for that.
