### ISSUE TITLE
list field: some properties don't work

### ISSUE THREAD

**Issue by crisgfx** [getkirby/kirby#3122]
I've noticed, that the following list-field [properties](https://getkirby.com/docs/reference/panel/fields/list#field-properties)
don't work: `after`, `before`, `icon`, `placeholder`, `required`.
I didn't check `translate` and `autofocus` and 
I don't use the field inside a blocks field, if this should make any difference.

–––––
kirby-version: 3.5.1

**Comment by afbora** [comment]
- [ ] `after`: will remove
- [ ] `before`: will remove
- [ ] `autofocus`: will fix
- [x] `icon`: fixed on 3.5.2
- [x] `placeholder`: fixed on 3.5.2
- [x] `required`: fixed on 3.5.2
- [x] `translate`: works

**Comment by crisgfx** [comment]
Thank You! =)

**Comment by crisgfx** [comment]
I'm having another issue with this field.
If I focus a new, empty field, the unsaved changes dialogue pops up right away.
Shouldn't it only appear, as soon as I enter a value?
Again, thanks for having a look into this and let me know, if it's worth opening a new issue. 

**Edit**: I've opened another issue, since this also happens with the writer field

**Comment by bastianallgeier** [comment]
✅
