### ISSUE TITLE
Impossible to delete block

### ISSUE THREAD

**Issue by chrfickinger** [getkirby/kirby#3123]
Currently is it not possible to delete the last block in a block list, if the page content is too long for browser window and orange toolbar is displayed.

**See screenshot:**

<img width="829" alt="sc01" src="https://user-images.githubusercontent.com/91317/106287987-c3ac9680-6247-11eb-90a6-90a271e209d3.png">

**Comment by afbora** [comment]
Thanks for report but there is an issue already #3080

**Comment by chrfickinger** [comment]
Sorry, I overlooked that.
