### ISSUE TITLE
Writer-Field: Whole content gets wrapped in one html-tag if field starts with disallowed marks

### ISSUE THREAD

**Issue by crisgfx** [getkirby/kirby#3125]
**Describe the bug**  
If the first character of a writer field starts with markdown, that's not in the available [marks list](https://getkirby.com/docs/reference/panel/fields/writer#field-properties) (e.g. `#`, `-`)
The whole content gets rendered in that html-tag.

**To Reproduce**  
1. Add a writer field to an existing blueprint
2. Begin the first line with a `#` or `-`
3. Add some more text and paragraphs
4. Save, go to frontend page

**Expected behavior**  
Markdown that's not in the allowed HTML formats list, shouldn't be rendered

**Kirby Version**  
3.5.1

**Desktop (please complete the following information):**  
 - OS: 11.1
 - Browser: Chrome
 - Version: 88

**Comment by afbora** [comment]
This issue fixed on 3.5.2, you can test on [3.5.2.RC-1 release](https://github.com/getkirby/kirby/releases/tag/3.5.2-rc.1).
Also you should use `nodes` prop instead `marks`.
Of course we should add to the documents this prop.

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
@bastianallgeier I was thinking of adding the missing `nodes` prop, should we include it in 3.5.2?

https://github.com/getkirby/kirby/blob/release/3.5.2/config/fields/writer.php

**Comment by crisgfx** [comment]
> Also you should use `nodes` prop instead `marks`.
> Of course we should add to the documents this prop.

Thanks so much Ahmet! 🙌🏼
Yes, would be great to have it in the docs. I wasn't aware of that prop.
