### ISSUE TITLE
Writer- & List-Field:  Impossible to revert after focusing a new field

### ISSUE THREAD

**Issue by crisgfx** [getkirby/kirby#3126]
**Describe the bug**  
The saving dialogue immediately appears, when focusing a writer- or list field that hasn't been saved before.
It's impossible to revert.

**To Reproduce**  
1. Add a writer- or list field to an existing blueprint
2. Focus the field (the saving dialogue pops up)
3. Try delete all changes (not possible)

**Expected behavior**  
The saving dialogue should only appear, after a value has been entered
or reverting should be possible.

**Kirby Version**  
3.5.1

**Desktop (please complete the following information):**  
 - OS: 11.1
 - Browser: Chrome
 - Version: 88

 **Additional context**  
 It's not of a big deal, but consider you have already made changes to another field 
 that you don't want to keep.
  
- Probably related to [issue#3115](https://github.com/getkirby/kirby/issues/3115).
- The same behaviour seems to occur with the [list-field](https://github.com/getkirby/kirby/issues/3122#issuecomment-769901705)

**Comment by bastianallgeier** [comment]
✅
