### ISSUE TITLE
[Panel] PHP locale string is incorrect

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#3129]
**Describe the bug**  
Just created my first (default) language in the Panel: English.

_PHP locale string_ is set to `en_US` by default, so I changed it to `en_GB`. The new locale string is set correctly in the file `site/languages/en.php`, but after reloading the Panel, _PHP locale string_ is reset to `en_US` (only there, not in the file).

**To Reproduce**  
1. Enable languages in `site/config/config.php`
2. Go to the Panel > Settings
3. Create the first language: English (all fields automatically fill in corresponding values, including `en_US`)
4. Change `en_US` to `en_GB` and add the language
5. Edit the newly created language, it says `en_US` now.
6. Go to `site/languages/en.php`, the value `LC_ALL` is set to `en_GB`.

**Expected behavior**  
The Panel should display the correct locale string.

**Screenshots**  
![Panel](https://user-images.githubusercontent.com/65500696/106357176-c3260580-6304-11eb-928b-bd621f723d2a.png)
![File](https://user-images.githubusercontent.com/65500696/106357177-c4573280-6304-11eb-9a22-fe7c67985085.png)

**Kirby Version**  
3.5.1

**Console output**  
No output.

**Desktop**  
 - OS: macOS
 - Browser: Safari
 - Version: 14.0

**Comment by bastianallgeier** [comment]
✅
