### ISSUE TITLE
Inconsistent return types between Query class insert method and shortcut Db::$queries['insert'] 

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3140]
**Describe the bug**  
Not sure if this is already part of the ongoing refactoring, but while the method in the Query class returns either the ID of the inserted row or false, the shortcut always returns an integer. Is that on purpose?

**To Reproduce**  
```
$wrongData= [
  'name'    => 'moe',
  'lastnam' => 'moellers'
];

// returns 0
$id = Db::insert('users', $wrongData );

// returns false
$id = Db::table('users')->insert($wrongData);
```
**Expected behavior**  
The return values should be consistent.

**Kirby Version**  
3.5.1

**Comment by bastianallgeier** [comment]
✅
