### ISSUE TITLE
Date field calendar icon overlaps time at certain window width

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3141]
**Describe the bug**  
An picture says more than a thousand words:

**Screenshots**  
<img width="339" alt="Bildschirmfoto 2021-02-05 um 18 48 46" src="https://user-images.githubusercontent.com/5312492/107070126-2c18ec00-67e3-11eb-9450-32ce550c9daf.png">

**Expected behavior**  
Icon should not overlap date/time

**Kirby Version**  
3.5.1

**Desktop (please complete the following information):**  
MacOS  11.0.1 with Firefox 85.0

**Comment by distantnative** [comment]
Duplicate of https://github.com/getkirby/kirby/issues/2992?

**Comment by texnixe** [comment]
Yep, wonder why it didn't show up in my search.
