### ISSUE TITLE
Panel Translation error

### ISSUE THREAD

**Issue by beebmx** [getkirby/kirby#3149]
**Describe the bug**  
There is a problem in the panel with the translation (not all languages).
If you set (por example) spanish it throw an error
`Undefined array key "es"` 

**To Reproduce**  
1. Download a plainkit project.
2. Create config/config.php
3. Enable languages with `'languages' => true`
4. Create a language file `site/languages/es.php`

```php
<?php

return [
    'default' => true,
    'code' => 'es',
    'direction' => 'ltr',
    'locale' => 'es_MX',
    'name' => 'Español',
    'url' => '/',
    'translations' => [
        'lang' => 'Español',
    ]
];
```

5. Go to <url>/panel
6. An empty page will show

Note: If the `translations` key is empty the no error will show.

**Expected behavior**  
The panel page (installation) should be shown

**Screenshots**  

**Kirby Version**  
The version affected is `3.5.2` in the `3.5.1` and below worked as expected.

**Console output**  
<img width="692" alt="image" src="https://user-images.githubusercontent.com/2191576/107589053-bdfd6c00-6bca-11eb-9a02-5847d77331a1.png">

**Desktop (please complete the following information):**  
 - OS:  macOS 11.2.1
 - Browser: Chrome, Safari
 - PHP: 7.3, 7.4, 8.0

**Additional context**  
There is no problem with the templates, this issue only affect to the panel.

**Comment by afbora** [comment]
✅
