### ISSUE TITLE
Block field content empty array not treated as empty by isEmpty() method

### ISSUE THREAD

**Issue by scsskid** [getkirby/kirby#3153]
**Describe the bug**  
Block field content empty array not treated as empty by isEmpty() method

**To Reproduce**  
save a page with an empty block field, write condition $field->isEmpty() 

**Expected behavior**  
field method isEmpty should return 1/true, but returns ''/false because content of field is string of empty array `[]`

**Kirby Version**  
3.5.2RC1

**Comment by scsskid** [comment]
workaround

```php
if ($page->text()->isNotEmpty() && $page->text()->toString() !== '[]')  :

...

if ($page->text()->isEmpty() || $page->text()->toString() === '[]')  :
...
```

**Comment by scsskid** [comment]
same thing with saved empty block, but I think the empty array is more pressing

**Comment by afbora** [comment]
Did you try with `->toBlocks()` method?

````php
if ($page->text()->toBlocks()) {
  //
}
````

or

````php
if ($page->text()->toBlocks()->isNotEmpty()) {
  //
}
````

**Comment by afbora** [comment]
May be we should add `'[]'` empty array for string data like json 🤔

https://github.com/getkirby/kirby/blob/3.5.3/src/Form/FieldClass.php#L176-L179

````php
public function isEmptyValue($value): bool
{
    return in_array($value, [null, '', '[]', []], true);
}
````

**Comment by scsskid** [comment]
> Did you try with `->toBlocks()` method?
> 
> ```
> if ($page->text()->toBlocks()) {
>   //
> }
> ```
> 
> or
> 
> ```
> if ($page->text()->toBlocks()->isNotEmpty()) {
>   //
> }
> ```

Thank you, This works, so I consider my issue not a bug, feel free to reopen though

**Comment by mrflix** [comment]
Ran into the same problem – expected `isEmpty` to work on the blocks field. TIL `toBlocks()->isEmpty()`.

**Comment by trych** [comment]
Sorry, could this maybe reopened?

I absolutely consider this issue a bug. If I do not add any blocks to the panel, the method should totally return `true` for `isEmpty()`. What happens right now is not the expected behaviour IMHO.

**Comment by lukasbestle** [comment]
If you call `isEmpty()` directly on the field, Kirby doesn't know the field type yet, so it can't know it's a blocks field. This would require loading the blueprint, which would be a performance issue.

The alternative @afbora suggested above to always treat the `"[]"` value as empty would work for blocks, but it would also mean that simple text fields that contain these characters would be treated as empty as well, which would be quite unexpected.

I'm reopening this issue for discussion, but to be honest I feel like this is unsolvable.

**Comment by afbora** [comment]
Is it possible to save the data of the field whose data is JSON as an empty string as `""` instead `"[]"` ?

**Comment by lukasbestle** [comment]
Great idea! 👍

**Comment by afbora** [comment]
Great! So do you think this development will lead to a breaking change?

**Comment by lukasbestle** [comment]
I don't see any breaking change. The `toBlocks()` method and the field itself already support an empty string (they automatically treat it as an empty array). We should still add tests for the `toBlocks()` method and the field to ensure compatibility (if we don't already have tests).

We should also make the same change to the layouts field.

**Comment by afbora** [comment]
✅

**Comment by trych** [comment]
Nice, thanks!

**Comment by scsskid** [comment]
great
