### ISSUE TITLE
Handling of fatal Exceptions

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#3154]
I couldn't find how to get to thrown Exception when using custom fatal template. https://getkirby.com/docs/reference/system/options/fatal
If this line 
https://github.com/getkirby/kirby/blob/317f494ee5166f36e32f9acf286f69786de30512/src/Cms/AppErrors.php#L86
passed $exception to the callback
```php
echo $fatal($this, $exception);
```
This would allow to easily integrate error tracking and notifications. Example with honeybadger
```php
    'debug' => false,
    'fatal' => function($kirby, $exception) {
        $honeybadger = Honeybadger\Honeybadger::new();
        $honeybadger->notify($exception);

        include kirby()->root('kirby') . '/views/fatal.php';
    }
```

I couldn't find my way around it because Whoops seems to always overwrite my set_error_handler/set_exception_handler so only way how to replace whoops is to set `debug => true` and `whoops => false` which is mostly bug and gets you to dead end so you can't render fatal template.

**Comment by lukasbestle** [comment]
✅
