### ISSUE TITLE
Widont could be improve on sentences ending with spaced punctation marks

### ISSUE THREAD

**Issue by arnaudjuracek** [getkirby/kirby#3155]
On some languages using spaces betwen words and punctation marks (namely, French), `Str::widont()` only appends a `&nbsp;` between the last word and the final punctuation mark, where we expect the `&nbsp;` to be placed between the last two words instead:

###### Current behavior in Kirby 3.5.0
```php
echo Str::widont("Omelette du fromage");
// Omelette du&nbsp;fromage

echo Str::widont("Omelette du fromage ?");
// Omelete du fromage&nbsp;?
```

###### Expected behavior
```php
echo Str::widont("Omelette du fromage");
// Omelette du&nbsp;fromage

echo Str::widont("Omelette du fromage ?");
// Omelete du&nbsp;fromage ?
```

## Fix
For now I am fixing the issue by modifying the RegExp in [`\Kirby\Toolkit\Str::widont`](https://github.com/getkirby/kirby/blob/317f494ee5166f36e32f9acf286f69786de30512/src/Toolkit/Str.php#L1145-L1155):

```diff
    public static function widont(string $string = null): string
    {
-        return preg_replace_callback('|([^\s])\s+([^\s]+)\s*$|u', function ($matches) {
+        return preg_replace_callback('|([^\s])\s+([^\s]+\s*[?!:]?)$|u', function ($matches) {
            if (static::contains($matches[2], '-')) {
                return $matches[1] . '&nbsp;' . str_replace('-', '&#8209;', $matches[2]);
            } else {
                return $matches[1] . '&nbsp;' . $matches[2];
            }
        }, $string);
    }
```

It is not perfect because it only handles `?`, `!` and `:` marks, but it is good enough for my use case. It would be great if some RegExp expert could improve it.

**Comment by afbora** [comment]
I'm not sure, but aren't the punctuation marks at the end of the sentence adjacent to it? I think it will not be a problem when you write adjacent: `Omelette du fromage?` 🤔

**Comment by distantnative** [comment]
I thought the same, but then I also read that in French it seems to be quite common to use a space between the last word and the ?

**Comment by arnaudjuracek** [comment]
In French, and probably in some other languages I am not aware of, the correct way of punctuating a sentence is by using a space before and after the punctuation mark.

So `Omelette du fromage?` will be correct in English, but in French will need to be written `Omelette du fromage ?`.
Note that when using a monospace font, french graphic designers often use English orthotypograhy rules.

See https://en.wikipedia.org/wiki/French_orthography#Punctuation

The link above mentions using a non-breaking space between punctuations marks and adjacent words, so the RegExp used in my fix is probably not that great.

**Comment by lukasbestle** [comment]
Probably there should be *both* a no-break space between the last word and the punctuation mark *and* between the last two words if I understand it correctly, right?

**Comment by arnaudjuracek** [comment]
> Probably there should be _both_ a no-break space between the last word and the punctuation mark _and_ between the last two words if I understand it correctly, right?

Yes!

**Comment by bastianallgeier** [comment]
✅
