### ISSUE TITLE
Too long field's `before` makes it impossible to input field

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3156]
**Describe the bug**  

If the `before` prop of a field is too long for the field's width, the input value cannot be seen and it's hard to edit it

![screenshot](https://user-images.githubusercontent.com/91317/106116967-d1ccbb00-6152-11eb-982b-21caaa6c8236.jpg)

More info:
https://github.com/distantnative/retour-for-kirby/issues/222

**Comment by lukasbestle** [comment]
What would be a good general solution for the core? I don't think we can generally abbreviate the text as we don't know the format.

**Comment by bastianallgeier** [comment]
I agree that this one is difficult. We could only make sure that the "before" text never gets longer than 50% of the input. But I don't know if that is a lot better. What happens when you even combine a long before and after text? I think those are the kind of edge cases that take a lot of time to get right when the main question is probably if those options should actually be used with such long text.

**Comment by nilshoerrmann** [comment]
Have you thought about adding `flex: wrap` to the field container and setting a input's span to – let's say – `flex-basis: 75%`? This way the field would switch between single and multiline layout:

<img width="302" alt="grafik" src="https://user-images.githubusercontent.com/25466/108367127-6c239a00-71f9-11eb-9a73-6edf022d8968.png">

**Comment by bastianallgeier** [comment]
Ok, I tried different things and this is one of the issues that's way harder than it seems. Every solution lead to new side effects. The before and after elements have no vertical padding and no line-height. This helps to make them work better with any type of input styling. But if we want to wrap the elements, they need that. This leads to additional padding issues with the input wrapper. It's a mess :(

**Comment by bastianallgeier** [comment]
I'm closing this. After my experiment I'm pretty sure that this is one of the issues that takes forever to build and test and will still always cause issues.

**Comment by nilshoerrmann** [comment]
While I understand the notion, I'd very much prefer imperfect styling with visible content then the current situation where the actual content just gets hidden. This is a situation where the panel gets unusable :(

**Comment by bastianallgeier** [comment]
We are currently facing a situation as a team where more than 90 issues are still open. Some of them for more than a year. We try to make everyone happy and end up with such huge amounts of work that nobody really is happy in the end. 

There are issues that definitely need to be solved at some point, but we also have to be honest and give some clearer replies  on issues that we either consider unsolvable or not "important" enough. We'd love to have a Panel without bugs, but you know how this stuff works. 

This issue has many problems. 

- A perfect solution would only exist with element queries 
- Finding a decent temporary solution is taking ages and causing a rats tail of related issues, which would all turn up as bugs here again. 
- There are multiple workarounds available for users to avoid the problem – shorter after/before labels + more detailed help text, custom panel CSS, custom field plugins. This means that the pressure is not as high as it is for other issues. 

I therefor think that the only honest way to tackle this is to close this in favour of more pressing problems. We also really hope for more PRs from the community to help us with such problems.

**Comment by nilshoerrmann** [comment]
> I therefor think that the only honest way to tackle this is to close this in favour of more pressing problems. We also really hope for more PRs from the community to help us with such problems.

I like your honesty, honestly :) :+1:

We'd like to provide a pull request but currently it's not clear to us what needs to be covered in this specific case. You mentioned side effects like additional padding so for us it would be helpful if you specified the requirements: which cases need to be covered? Maybe you could share a blueprint to test against? Thanks!

**Comment by bastianallgeier** [comment]
The main issue is a correct styling for before and after elements that includes the correct padding before and after the main input element when the elements don't wrap but also looks nice when they wrap. In addition line height is an issue. You would basically need to test various scenarios

single line before + multi line input + single line after
multi line before + single line input + multi line after 
etc.
