### ISSUE TITLE
Routing problems since 3.5.2

### ISSUE THREAD

**Issue by SamuelRiversMoore** [getkirby/kirby#3157]
I'm encountering this issue since v3.5.2.
If a page has the same `id` as another page (but of course not the same parent), the displayed page can be the wrong one (so it doesn't match with the route / url).

The problem seems to be related to this line : https://github.com/getkirby/kirby/blob/dbd8d2216eeec429d0f19ebea430de8347e7f073/src/Cache/FileCache.php#L71

Which has been modified by this pull request : #3143

**Comment by distantnative** [comment]
Can confirm. That explains an issue I had yesterday with my own website. I had no clue what was going on, but this issue is exactly what happened to me too.

**Comment by bastianallgeier** [comment]
Yikes. That's not good. We will patch this as soon as possible.

**Comment by afbora** [comment]
Then it is enough just to clear the relative path signs (`../`, `./`) instead use `basename()`?

**Comment by bastianallgeier** [comment]
@afbora I think so, yes.

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
We have to patch a live site: is it save to pull `develop` or should we just apply the changes from #3158?

**Comment by afbora** [comment]
@nilshoerrmann will release patch version today.

**Comment by nilshoerrmann** [comment]
Great, thanks!
