### ISSUE TITLE
kirby 2.2 beta: $page->date() does not return an integer, but only a string

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/kirby#316]
I have some code, which relies on the functionality of the old `date()` method, but this is currently not possible with the current develop version of kirby.

In kirby 2.1.x `date()` will return the unix timestamp as integer. In the new update, `date()` returns an Field object, but there´s no method to convert the timestamp integer value stored in it to an integer. There´s only something for the automatic conversion to a string in `core/field.php`.

Please add something to get pure integer values from the field object too (or point me to another solution).

**Comment by distantnative** [comment]
Have you tried `$page->date()->int()`?

**Comment by jbeyerstedt** [comment]
This works well, Thank you.
I tried `(int)$page->date()`, because explicit casting to string work the same way. But that gave me the same php errors.

**Comment by distantnative** [comment]
I think it'd be `(int)$page->date()->value` then.

**Comment by jbeyerstedt** [comment]
I think `$page->date()->int()` is easier to read.
I will close this issue then, but will there be a document with compatibility issues between kirby 2.1 and 2.2?

**Comment by distantnative** [comment]
There will definitely be a changelog for the 2.2. I'm not sure what Bastian's exact plans are for the changelog. If it doesn't fit for the changelog to go into details on compatibility issues, I will for sure post something additional on the forum.
