### ISSUE TITLE
[blocks] modal panel UI issues

### ISSUE THREAD

**Issue by SkidX** [getkirby/kirby#3164]
**Describe the bug**  
I think there are several UI issues related with the choice of opening a custom block editing inside a modal panel.

1. The Revert / Save bar is now covered by the overlay, therefore inaccessible.
2. It is not possible anymore to drag & drop images and files from sidebars inside textarea editors, since those sidebars are now covered by the overlay.
3. As far as I can see, the size and the position of the modal panel is not controllable, making the UI customization way worse than having the fields in the normal page flow.

**To Reproduce**  
Use a blocks field with custom blocks and try to edit them

**Expected behavior**  
Well, I would like it to work like before, so not inside the modal panel, but in the normal page flow, keeping all the nice features available in the panel, like drag & drop, and so on, or at least having an option to opt-out from the modal view.

**Screenshots**  
![Screenshot 2021-02-19 184926](https://user-images.githubusercontent.com/4333679/108541972-64d8bb00-72e3-11eb-9aa2-f30ab7b8514a.png)

**Kirby Version**  
3.5.0

**Comment by bastianallgeier** [comment]
Sorry, but this is not a bug report. There are many reasons why we went this way. Blocks can get very complex and inline editing often leads to a worse UX in our experience with many of the old Builder setups. But it's of course always a balance between priorities. We need to make sure to come up with a solution that works for 99% of all cases and the drawer is more future-proof in that part. 

Feel free to post this on our feedback platform though: https://feedback.getkirby.com

**Comment by SkidX** [comment]
Yes, clearly one part of the topic is related to a design decision and I don't consider it a bug as well, was more like a "opinion" about it.
On the other side I still consider a bug the fact that I can interact with the "save" feature using the keyboard shortcut but at the same time I'm not able to click it.
I put them together in the same ticket because I thought the topic was the same, sorry if I framed this in the wrong way.
