### ISSUE TITLE
Pasting text into the writer field doesn't remove unsupported html tags

### ISSUE THREAD

**Issue by moevbiz** [getkirby/kirby#3169]
Pasting text into the writer field doesn't remove unsupported html.

**To Reproduce**  
1. in a starterkit, go to i.e "panel/pages/photography+trees" and paste some formatted text into the `text` field. for example, just copy the headline "Welcome to Kirby's Starterkit" from the landing page.

**Expected behavior**  
The writer field should strip all unsupported tags.

**Screenshots**  
<img width="403" alt="Screenshot 2021-02-22 at 14 19 40" src="https://user-images.githubusercontent.com/38008341/108713790-03019680-7519-11eb-9366-dc249b0d0b4c.png">

**Kirby Version**  
3.5.3

**Desktop (please complete the following information):**  
 - OS: mac os big sur
 - Browser: chrome v 88.0.4324.150

related feature request:
https://kirby.nolt.io/249

**Comment by distantnative** [comment]
I tried, but the ProseMirror in the writer field is too much black magic for me - @bastianallgeier will be needed.

**Comment by afbora** [comment]
We can close the issue and keeping as feature/idea in Nolt.

**Comment by distantnative** [comment]
I think the idea in Nolt is about a dedicated button for clearing supported formatting. While this issue is about that on paste unsupported tags aren't removed - I think this can indeed be considered as bug.

**Comment by bastianallgeier** [comment]
The tags should be properly removed when the node is not available. I think it's a problem that the headline nodes are still slumbering in our write field by default.
