### ISSUE TITLE
File cache: naming ambiguous

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#3171]
**Describe the bug**  
While using Kirby's built-in file cache for pages, we noticed that the cache file naming is based on page slugs and not on their ids which makes the cache ambiguous. For instance, the pages `texts/test` and `projects/test` will have the same cache file created:

- `texts/test` → `test.de.html.cache`
- `projects/test` → `test.de.html.cache`

**To Reproduce**  
Enable file cache for pages:

```php
<?php

return [
    'cache' => [
        'pages' => [
            'active' => true
        ]
    ]
];
```

Create two pages with the same slug but different parents. Visit the frontend to initialise the cache. A cache file will only be created for the first visited page, the second one will serve the same content as the first.

**Expected behavior**  
The cache should be unambiguous and use the id instead of the slug:

- `texts/test` → `texts.test.de.html.cache`
- `projects/test` → `projects.test.de.html.cache`

**Kirby Version**  
3.5.2, multilingual install

**Comment by afbora** [comment]
Thanks for reporting. This is [known issue](https://github.com/getkirby/kirby/issues/3157) and will be fixed on 3.5.3.1
