### ISSUE TITLE
Blocks field inconsistent `max` items behaviour

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#3179]
**Describe the bug**  
Is it expected for a blocks field that has a `max`  specified I can still "add" an item via the UI top right? I can't save it (I get an error then), but it seems inconsistent with other `max`-ui that hides the "add" functionality when the threshold is reached

**To Reproduce**  
1. Add a blocks field with e.g. `max: 3`
2. Login to the panel and try to add 4 items
4. No notification when trying to add 4th item

**Expected behavior**  
After the 3rd block is added I'ld expect the "add" Ui to be hidden.

**Kirby Version**  
3.5.3

**Desktop:**  
 - OS: macOS
 - Browser: Firefox 85.0.2

**Comment by bastianallgeier** [comment]
✅
