### ISSUE TITLE
[Panel] Open Link Modal button in textarea not visible

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#318]
https://github.com/k-next/panel/blob/master/src/Ui/Forms/Fields/TextareaField/TextareaField.vue#L58

the button for openLinkModal doesn't seem to be rendering correctly. Instead, for some strange reason I don't understand, it contains a copy of the whole html document:

![image](https://user-images.githubusercontent.com/6684137/38100664-4ac2ecec-337e-11e8-8c3f-c80b38f3a06d.png)

**Comment by distantnative** [comment]
✅
