### ISSUE TITLE
Blocks field: delete button inside the drawer

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#3180]
**Describe the bug**  
How do I "cancel" the addition of a block to the blocks field?

**To Reproduce**  
When I click "add", the drawer opens but I cannot cancel it? When I click away from the drawer; the drawer is closed; but an empty block is added. 

**Expected behavior**  
Add an obvious "cancel" link, (maybe als add a listener to the "ESC" key) which closes the drawer without adding an empty block.

**Kirby Version**  
3.5.3

**Desktop:**  
 - OS: macOS
 - Browser: Firefox 85.0.2

**Comment by afbora** [comment]
The drawer will already close when you press the escape key while the drawer is open. But when the escape key is pressed, IMO we cannot know if this is to `close` or `cancel`. Maybe a delete button can be added on the drawer 🤔

**Comment by bastianallgeier** [comment]
In the blocks field, a new block is already fully created once you click on the selected type. I like @afbora to still offer a good way to directly delete the block inside the drawer instead of "cancelling" the new block.

**Comment by bastianallgeier** [comment]
✅
