### ISSUE TITLE
`Files` Field Selection Broken on Mobile

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3183]
**Describe the bug**  
When attempting to make a selection for a `files` field on Safari on an iPhone (not sure about other devices/browsers), the Panel either reloads itself or goes to a browser error page.

This is reproducible on my own installation as well as the Kirby Demo server.

**To Reproduce**  
1. On an iPhone: Go to the Panel of a Kirby Demo instance (https://getkirby.com/try)
2. Go to Blog > "In the jungle of Sumatra" draft
3. Remove the existing "Cover" image
4. Click the "Add" button
5. Click "Select"

For reference, here is what the Demokit uses for the image field:
```yaml
      cover:
        type: files
        max: 1
        uploads:
          template: blog-article-image
```

**Expected behavior**  
You should see a Kirby image picker to select an already uploaded image

**Screenshots**  

https://user-images.githubusercontent.com/417182/109186998-56a4f780-7746-11eb-8996-5255a4e62758.MP4

**Kirby Version**  
`Kirby 3.5.3.1`

**Console output**  
I didn't see any console output via Safari's remote web inspector.

**Smartphone (please complete the following information):**  
 - Device: iPhone 11 Pro
 - OS: 14.4 (18D46), 14.5 (18E5154f)
 - Browser: Safari

**Additional context**  
This does **not** reproduce on desktop Safari in "Responsive Design Mode."
It _is_ reproducible in Xcode's iOS Simulator though.

**Comment by afbora** [comment]
Also I can reproduce with Chrome browser and IOS 14.4.

**Comment by Werbschaft** [comment]
I have had this problem as well. With the latest StarterKit this also happens. Interesting might be that it throws up the error "Unauthenticated" for a fraction of a millisecond. At least on the first try. On the 2nd try, Safari brings me that an error has occurred repeatedly on the page.

![RPReplay_Final1629709698](https://user-images.githubusercontent.com/2178466/130422970-3738f3a1-95d2-4d19-9cae-6d68ed35da8d.gif)

**Comment by lukasbestle** [comment]
> Also I can reproduce with Chrome browser and IOS 14.4.

Chrome on iOS also uses WebKit under the hood, so apparently this issue is specific to WebKit on iOS.

**Comment by lukasbestle** [comment]
I can also reproduce the issue with Safari on iOS 14.7.1. Sadly also nothing in the remote dev console. :(

**Comment by Werbschaft** [comment]
I was already confronted with something like this in places, is there still nothing reasonable to debug iOS? Have also tried various ways to get info about the error but unfortunately without success.

**Comment by lukasbestle** [comment]
Well, there is the remote web inspector you can access from Mac Safari when the iOS device is connected to a Mac. This generally has a full blown console and inspector, but unfortunately it doesn't display anything for this particular issue.

**Comment by neildaniels** [comment]
I cannot seem to reproduce this issue on the latest iOS 15.0 developer beta (build 19A5337a).

If this was purely a WebKit issue, it seemingly is fixed.

Anyone else using the betas?

**Comment by afbora** [comment]
I've tested it on BrowserStack and several similar tools. I was able to reproduce the issue but unfortunately there is no output to the IOS debugger console.

**Comment by afbora** [comment]
@neildaniels I guess missed your last comment. I've tested on IOS 15.0.2 with Chrome/Safari and I can't reproduce the issue either 🎉 

Please let us know if anyone still facing the issue.
