### ISSUE TITLE
EmailChallenge: Invalid default sender address for sites in subdirs

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3185]
See https://forum.getkirby.com/t/email-sending-address-for-2fa-and-login-methods/21376.

The error is introduced by this line:

https://github.com/getkirby/kirby/blob/0a4a11405079b1e37adaa70db7fd621b42e2e964/src/Cms/Auth/EmailChallenge.php#L59

**Comment by lukasbestle** [comment]
I'm still in the process of implementing this for 3.5.5. Almost done, ETA Monday evening. :)

**Comment by bastianallgeier** [comment]
✅
