### ISSUE TITLE
Pages section: markup and entities

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#3188]
**Describe the bug**  
Pages sections allow for setting custom `text` and `info` values. While `info` accepts markup and entities, `text` does not.
 
For styling purposes it might be helpful to add markup to the `text` in order to highlight certain pages. Disallowing entities might proof problematic if content is pulled in using the query languages and thus might contain formatted text already.

**To Reproduce**  
Create a pages section:

```yml
section:
  type: pages
  text: '<strong>a&nbsp;test</strong>'
  info: '<strong>a&nbsp;test</strong>'
```

**Expected behavior**  
Both fields should display the text "a test" in bold including a non-breaking space.

**Screenshots**  
This is how a list item of the section will look like currently:
![Bildschirmfoto am 2021-03-03 um 13 07 49](https://user-images.githubusercontent.com/25466/109803677-a17cae80-7c21-11eb-8728-8fab2820f2c9.png)

**Kirby Version**  
All Kirby versions as far as I'm aware.

**Comment by bastianallgeier** [comment]
✅
