### ISSUE TITLE
[Cms] Page::modified() always returns null

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#319]
Not sure if it's a bug or simply a no longer implemented leftover from a previous version... 

[$page->modified()](https://github.com/k-next/kirby/blob/6aa877ed6adcf666e20562dac753089ff2be8654/src/Cms/Page.php#L558) seems to always return NULL. 

Probably because `$page->content()->get('modified')` is empty. 

## How to reproduce

add the following code to a template

    <?php 
      var_dump($page->modified())       
    ?>

### What is expected
a string containing the timestamp of the last edit. (passing NULL as $format to toDate() returns a timestamp)

### What happens
`NULL` is printed.

**Comment by distantnative** [comment]
In my opinion instead of 

```php
    public function modified(string $format = null)
    {
        return $this->content()->get('modified')->toDate($format);
    }
```

it should be 

```php
    public function modified(string $format = 'U')
    {
        return date($format, $this->store()->modified());
    }
```

And `PageStore::modified` something like
```php
    public function modified()
    {
        return filemtime($this->base()->root());
    }
```

**Comment by rasteiner** [comment]
I think PageStore::modified would be:

```php
    public function modified()
    {
        return filemtime($this->base()->storage());
    }
```

**Comment by bastianallgeier** [comment]
✅
