### ISSUE TITLE
Writer field emptied when changing URL

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3192]
1. Use the demo kit
2. Go to `pages/portfolio+projects+animals`
3. Text field (`typ: writer`) has content
3. Change the URL
4. See unsaved changes bar plopping up
5. Text field is empty

**Comment by afbora** [comment]
@distantnative My steps are wrong? 

When I change the URL, the `localStorage` value gets `null`, but I couldn't see the issue.

![change-url](https://user-images.githubusercontent.com/3393422/110101093-39120680-7db4-11eb-9c16-41c9a5e899bf.gif)

**Comment by distantnative** [comment]
Maybe a browser thing?
Just reset my setup again: develop branch, nom run serve... doing the steps outlined above (in Chrome), I end up with:
<img width="1277" alt="Screen Shot 2021-03-06 at 13 41 49" src="https://user-images.githubusercontent.com/3788865/110207086-bf484e80-7e81-11eb-92c7-81d8ad0e23df.png">

**Comment by afbora** [comment]
I wonder about your `localStorage` value when you change the URL without making any changes 🤔

**Comment by afbora** [comment]
@texnixe @lukasbestle @bastianallgeier Do you have the same issue or can reproduce?

**Comment by bastianallgeier** [comment]
I have never seen this issue before.

**Comment by texnixe** [comment]
Can't reproduce this, at least not with the online demo nor with a freshly downloaded demo kit.

**Comment by distantnative** [comment]
Still existing for me. Running `demokit` in sandbox with `npm run dev`:


https://user-images.githubusercontent.com/3788865/122651946-4b823700-d13c-11eb-951b-38c9050bf0dd.mov

`localStorage` right after submitting URL change dialog is for `kirby$content$pages/portfolio/projects/animals`:
<img width="735" alt="Screen Shot 2021-06-19 at 20 25 48" src="https://user-images.githubusercontent.com/3788865/122651988-8dab7880-d13c-11eb-8359-d24e7f7adeab.png">

**Comment by lukasbestle** [comment]
@distantnative I can also reproduce this on trykirby.com with Safari 14.1.1 as well as locally with a standard setup of the demokit. I then tried swapping in the `kirby` dir of 3.6.0-alpha.1 and now the writer field stays populated, but I still get the "unsaved changes" bar that cannot be reverted. But saving the changes after the URL change is possible and produces the following diff:

```diff
Title: Animals

----

- Text: <p>Vestibulum id ligula porta felis euismod semper. Sed posuere consectetur est at lobortis. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Nullam id dolor id nibh ultricies vehicula ut id elit. </p><p>Etiam porta <strong>sem</strong> malesuada magna mollis euismod. Donec id elit non mi porta gravida at eget metus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Maecenas faucibus mollis interdum. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
+ Text: <p>Vestibulum id ligula porta felis euismod semper. Sed posuere consectetur est at lobortis. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Nullam id dolor id nibh ultricies vehicula ut id elit.</p><p>Etiam porta <strong>sem</strong> malesuada magna mollis euismod. Donec id elit non mi porta gravida at eget metus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Maecenas faucibus mollis interdum. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>

----

Description: What does the fox say?
```

(one space at the end of a paragraph is removed)

**Comment by bastianallgeier** [comment]
No longer happening in beta-1
