### ISSUE TITLE
Missing <hr> separator block

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#3197]
**Describe the bug**  
I'm migrating from Kirby Editor to Blocks and there's no horizontal rule block. After the data is converted to Blocks JSON, the `hr` block is still there:

![image](https://user-images.githubusercontent.com/5570098/110235542-3d1b6100-7f39-11eb-84e1-1d904db5e049.png)

...but there's no default snippet for it and it also doesn't render as a separator in the panel:

![image](https://user-images.githubusercontent.com/5570098/110235555-5b815c80-7f39-11eb-8d05-37b18f47dc57.png)

**To Reproduce**  
1. Create a page with the Editor field
2. Put an `hr` block in that field
3. Convert the Editor field to Blocks field as described in the [docs](https://getkirby.com/docs/reference/panel/fields/blocks#editor-migration)

**Expected behavior**  

1. You should see a separator in the Kirby Panel
2. There should be an `<hr />` tag in the rendered HTML

**Kirby Version**  
3.5.3.1

**Comment by afbora** [comment]
@bastianallgeier how do you think the solution should be? Should we create a new block type named `hr/gap/separator/line` or put `<hr>` inside the text block? By the way, `<hr>` does not work in the text block (writer field) for some reason, it also throws it into the paragraph `<p><hr></p>`. Alternatively, we can use the `markdown` block. What do you think?

**Comment by bastianallgeier** [comment]
I think it would make sense to add a new line block. This would open new options to add custom styling for such gaps/lines.

**Comment by bastianallgeier** [comment]
✅
