### ISSUE TITLE
 sortBy() does not work with umlauts or accents

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#320]
Moved from here: https://github.com/bastianallgeier/kirby/issues/36

**Comment by lukasbestle** [comment]
I think this is because `array_multisort` is not UTF-8 ready. We might need to use the [Collator](http://php.net/manual/de/class.collator.php) class, but I think it doesn't support the `multisort` syntax.

**Comment by lukasbestle** [comment]
This is now fixed by converting the values to ASCII before sorting. See the commit message for more details.
This fix is included in Kirby 2.3.2.
