### ISSUE TITLE
FilePreview: File URL links to the media folder directly

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3201]
The `Url` link in the FilePreview component currently displays the "public" URL (`/path/to/page/file.jpg`), but links to the media folder (because that's what the default `file::url` component returns). If users [now copy that link](https://forum.getkirby.com/t/adjusting-the-media-hash-generation/21456?u=lukasbestle), the link will contain the media hash and will therefore not be permanent.

I think the link target should always be the public URL of the file. But of course this could break setups with a custom `file::url` component. What do you think?

**Comment by distantnative** [comment]
Is this another case where we shouldn't copy the image over to `media` anyways without modifications? And just always keep files without modifications in their original location?

**Comment by lukasbestle** [comment]
No, this is not about where the image is actually stored. If the link target is the public file URL, Kirby will dynamically redirect to the current media URL. So it's just about the link that's displayed in `FilePreview`.

For content files we do need to store a copy in `media` as files within `content/` are blocked in the default `.htaccess` for security.

**Comment by distantnative** [comment]
I'm trying to make up my mind... but somehow both feels right and wrong.
Maybe the others have better judgement :D

**Comment by lukasbestle** [comment]
I looked into the code again: Even if the `file::url` component is overridden, it would still work after the change: Accessing a file with its public URL (`/path/to/page/file.jpg`) will always trigger a redirect to the `mediaUrl()` of the file (handled by `$app->io()`). So linking to the public URL should always work with the advantage of creating a permanent URL that can be copied.

**Comment by lukasbestle** [comment]
Wait, it's the other way around probably. Our default `file::url` component uses the `mediaUrl`, but a custom one could link to wherever and this wouldn't be reflected.

But I think we should solve this by fixing the redirect in `$app->io()` to use `file::url` internally, not `mediaUrl`.

**Comment by distantnative** [comment]
Eventually, we will have to tackle the `file::url` and `file::verison` muddle

**Comment by lukasbestle** [comment]
Yeah, to be honest I don't fully grasp how it all interconnects at the moment.

**Comment by bastianallgeier** [comment]
While the file::url file::version horror definitely needs to be fixed, this one is really easy to solve in the Panel. We should indeed use the shortcut URL to avoid such copy issues.

**Comment by bastianallgeier** [comment]
✅
