### ISSUE TITLE
`Remote::get()` always returns indexes from arrays without keys

### ISSUE THREAD

**Issue by PaulMorel** [getkirby/kirby#3203]
I'm building a site that uses the [Transistor.fm API](https://developers.transistor.fm). I'm trying to fetch shows with the API and the endpoint accepts [sparse fieldsets](https://developers.transistor.fm/#endpoints), as detailed in [one of their examples](https://developers.transistor.fm/#shows).

Here's my request: 
```php
$response = Remote::get('https://api.transistor.fm/v1', [
  'headers' => [
	  'X-API-KEY' => env('TRANSISTOR_FM_API_KEY')
  ],
  'data' => [
	  'pagination' => [
		 'per' => 3
	  ],
	  'fields' => [
		  show' => [
			 'title',
			 'description'
		  ]
	  ]
  ]					
]);
```

This is the resulting URL and query:
```
https://api.transistor.fm/v1/shows?pagination[per]=3&fields[show][0]=title&fields[show][1]=description
```
## Expected behavior
So what I'm expecting 3 shows with only the title and descriptions as meta fields. What I get is 3 shows with no meta fields.

The problem comes from the `fields[show]` array. As the values of the array have no keys set, the underlying `http_build_query()` function uses their indexes instead. However, the API is not expecting this form of query. It's expecting empty square brackets. 

This query works:
```
https://api.transistor.fm/v1/shows?pagination[per]=3&fields[show][]=title&fields[show][]=description
```

The only difference being the array indexes were manually removed from the query.

---

**This might be an an issue with their API**, however, I'm wondering if there's a need for a "keyless array value index stripping" feature or optional parameter to the `Remote::get` method.

If this could be a relevant improvement to the `Remote` class, I could very much tackle this and submit a PR.

**Comment by bastianallgeier** [comment]
I think we should first find out what's the "correct" way to do it. My feeling is that the numeric keys should indeed just be omitted and that the behaviour of http_build_query is wrong. But I'm not familiar with the standards here.

**Comment by lukasbestle** [comment]
I've also only seen the `[]` syntax so far, the numeric indices are weird. The PHP documentation on `http_build_query()` has quite a few comments on this behavior as well.

The question is if it's really viable to replace `http_build_query()` with our own implementation. This can get super complex super quickly and there may be possible vulnerabilities hidden inside edge-cases we don't think about. Especially if we try to solve it with `preg_replace()` or similar to strip out the numbers.

To be honest, such complex query strings are too much of a special case IMO.

@PaulMorel You can circumvent this by passing the `fields` data manually like so while still passing additional custom data that will be appended automatically:

```php
$response = Remote::get('https://api.transistor.fm/v1/shows?fields[show][]=title&fields[show][]=description', [
  'headers' => [
	  'X-API-KEY' => env('TRANSISTOR_FM_API_KEY')
  ],
  'data' => [
	  'pagination' => [
		 'per' => 3
	  ]
  ]					
]);
```

Is this an option for you or do you need dynamic data for the queried fields?

**Comment by PaulMorel** [comment]
@lukasbestle Yes, that works for me. It's a bit less "clean", but what's truly important is that it works. My current workaround is to call `http_build_query()` myself and strip the indices with `preg_replace()` then feed the query string directly to `Remote::get()`. It works too.

I agree with both of you that making changes to Kirby for this would be premature due to the possible vulnerabilites and edge-cases.

As a side note, I wanted to check other CMS to see if they had different implementations.

[Craft CMS](https://github.com/craftcms/cms/blob/77b9a07ed2e4afa8ccc9884611a33b70e6d21bfb/src/helpers/UrlHelper.php#L73-L92), [Drupal](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21UrlHelper.php/function/UrlHelper%3A%3AbuildQuery/8.2.x), [WordPress ](https://developer.wordpress.org/reference/functions/_http_build_query/ )seems to have their own implementation of a query string building function or helper, however they all effectively seem to act the same as `http_build_query()`. Not sure why they decided to make their own function.

**Comment by lukasbestle** [comment]
My current feeling is that we should close this issue. Please let me know if you disagree.
