### ISSUE TITLE
Editor → Blocks conversion of paragraph lacks <p>

### ISSUE THREAD

**Issue by mrflix** [getkirby/kirby#3204]
**Describe the bug**  
I'm migrating an editor field to a blocks field. With the editor field, the paragraphs got wrapped in `<p>`s when rendering. In the initial migration the `<p>` are missing and only when I touch the field they get added.

**To Reproduce**  
Before migration:

```
{
    "attrs": [],
    "content": "Cupidatat commodo magna elit aliquip id ut cillum occaecat officia.",
    "id": "_mlf4hvnxv",
    "type": "paragraph"
}
```

After migration:

```
{
    "content": {
        "text": "Cupidatat commodo magna elit aliquip id ut cillum occaecat officia."
    },
    "id": "2a16f47d-3f3a-48c6-a2d1-571992bc2fd8",
    "isHidden": false,
    "type": "text"
}
```

After touching the field:

<pre><code>{
    "content": {
        "text": "<strong>&lt;p&gt;</strong>Cupidatat commodo magna elit aliquip id ut cillum occaecat officia.<strong>&lt;\/p&gt;</strong>"
    },
    "id": "2a16f47d-3f3a-48c6-a2d1-571992bc2fd8",
    "isHidden": false,
    "type": "text"
}</code></pre>

**Expected behavior**  
I'd expect the html paragraph to be added in the migration step.

**Kirby Version**  
3.5.3.1

**Possible Solution**
`BlockConverter.php:222` from:

```php
'text' => $params['content']
```

to :

```php
'text' => '<p>'. $params['content'] .'</p>'
```

I'm not sure if the content could include `<p>`s. I looked through editor paragraphs: it appears that "paragraphs" where created using `<br>`s. So possibly this solution should solve it.

**Comment by afbora** [comment]
Since the editor keeps each paragraph in a separate block, it does not include the `<p>` tag. So I think your solution is correct in my opinion. Let's take @bastianallgeier's opinion.

**Comment by bastianallgeier** [comment]
You are right. This needs to be fixed.

**Comment by bastianallgeier** [comment]
✅
