### ISSUE TITLE
Wrong error message on empty URL appendix

### ISSUE THREAD

**Issue by salimromadhon** [getkirby/kirby#3205]
I'm on Firefox and get this error when the URL appendix is empty:

![image](https://user-images.githubusercontent.com/4891012/110961366-4e71cc80-8382-11eb-880e-270024a2f338.png)

I also get the same result when trying on trykirby.com. Yeah it's very minor but has to be fixed. :)

**Comment by lukasbestle** [comment]
@salimromadhon What would be the expected behavior for you?

**Comment by texnixe** [comment]
Maybe a misunderstanding, because it's rather unclear what a URL appendix is supposed to be? And the field is called `URL appendix` whereas the error messages says `prefix`. I think the field should really be called slug,  or even folder name, then it's also clearer why it must be required?

**Comment by lukasbestle** [comment]
@texnixe Yes, both points make a lot of sense!

**Comment by bastianallgeier** [comment]
The only reason why I went for URL appendix was the weirdness of the term slug. I also have zero idea how to translate that to German for example. Folder name is also kind of weird when editors often don't have any knowledge about the underlying file system and that Kirby is just renaming folders.

**Comment by lukasbestle** [comment]
Slug has pretty much become an established term, even in German. If we do decide to stay with "URL appendix" (which would be fine for me as well), we just need to fix the error message to be consistent. I think that's what @salimromadhon meant.

**Comment by texnixe** [comment]
I think we really need to unify our wording more:

- changeUrl
- changeSlug()
- URL appendix
- $page->slug()
- URL prefix

**Comment by salimromadhon** [comment]
> And the field is called `URL appendix` whereas the error messages says `prefix`.

Yep that's what I mean. The error message should says `URL appendix` as well.

Yeah translating technical things sometimes goes tricky as not every term has its "as is" corresponding meaning. I'm OK with "slug" or "URL appendix". Both of them can't be directly translated into Indonesia, even strictly translating it can lead to confusing rather than leaving it untranslated.

For this case I prefer "URL appendix" where can be more meaningfully translated into Indonesia as "Akhiran URL". It's mixed language Indonesia-English. But I think it's OK as Google does the same way in translating their products, especially for Indonesia.

**Comment by afbora** [comment]
✅
