### ISSUE TITLE
Bug in invalid helper when trying to validate date

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3208]
**Describe the bug**  
When trying to validate a date from a form input, a date doesn't validate. Consider the following example:

```
<?php

$data = [
  'datum'  => '2021-03-31',
];

$rules = [
  'datum'  => ['date'],
];

$messages = [
  'datum'  => 'Wrong date: '.$data['datum'],
];
if($invalid = invalid($data, $rules, $messages)) 
{
  dump($invalid);
}
````
// Array
(
    [datum] => Wrong date: 2021-03-31
)

While the validator validates the date correctly

```
dump(V::date('2021-03-31')); // 1
```

the `invalid()` helper passes an array like this to the validator

```
Array
(
    [0] => 2021-03-31
    [1] => date
)
```

and consequently fails on the condition 

https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Toolkit/V.php#L265

**Expected behavior**  
A date should be correctly validated

**Screenshots**  

**Kirby Version**  
3.5.3.1

**Comment by afbora** [comment]
Actually, there was a general issue already. Sends wrong parameters to all validations that do not have options that `email`, `date`, `integer` etc..

**Comment by bastianallgeier** [comment]
✅
