### ISSUE TITLE
Pasting list into a writer field brings up additional marks option.

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3211]
**Describe the bug**  
When a list is copy-pasted into a writer field, you all of a sudden get an additional marks option with a dropdown to select between different heading levels and list styles.

**Expected behavior**  
No more marks then actually defined should appear.

**Kirby Version**  
3.5.3.1

**Additional context**  
More information see forum post:  https://forum.getkirby.com/t/writer-field-anomaly-or-a-dream-come-true/21624

**Comment by afbora** [comment]
@bastianallgeier, can we close after the PR about the headings?

**Comment by bastianallgeier** [comment]
@afbora I wonder if the default list of nodes should be changed and only include paragraphs. Otherwise this problem isn't really fixed in my opinion.

**Comment by afbora** [comment]
Frankly, I didn't quite understand what you meant. All unsupported nodes are already converting to paragraph, am I wrong?

**Comment by bastianallgeier** [comment]
@afbora sorry for the delay. I mean that the writer field currently has headings, bulletList and orderedList enabled by default. Before our changes, none of the formats were active before. So I wonder if we should only allow paragraphs by default and you have to activate headings, bulletList and orderedList in the blueprint if you want them.

**Comment by afbora** [comment]
I get it now. I think if we just allow the paragraph then the breaking change will happen. Because unknowingly, heading and lists were working when the text was pasted. It just wasn't showing the buttons. In 3.6 we actually just revealed the hidden buttons.

IMO, I think we can close this issue.
