### ISSUE TITLE
Duplicate a page with empty URL appendix returns 500 error

### ISSUE THREAD

**Issue by salimromadhon** [getkirby/kirby#3214]
**Describe the bug**  
When I duplicate a page and URL appendix is empty then 500 error is returned.

**To Reproduce**  
1. Go to the Panel
2. Click duplicate a page
3. Empty the URL appendix
5. This is when duplicate a top level page
    ![image](https://user-images.githubusercontent.com/4891012/111576816-c6f1e680-87e3-11eb-9a08-9cad5cea841f.png)
6. And this is when try duplicate a sub-page
    ![image](https://user-images.githubusercontent.com/4891012/111576210-99f10400-87e2-11eb-9045-f1fb0e654e93.png)

**Expected behavior**  
A proper error message that says that field is required.

**Kirby Version**  
3.5.3.1

**Additional context**  
The 500 error also happens on trykirby.com but showing different message.

![image](https://user-images.githubusercontent.com/4891012/111577471-ea696100-87e4-11eb-83d2-500bab409f93.png)

**Comment by bastianallgeier** [comment]
✅
