### ISSUE TITLE
[Panel] Browser back button updates URL, but not view

### ISSUE THREAD

**Issue by renestalder** [getkirby/kirby#3216]
**Describe the bug**  
I use the browser back button quite often. And I noticed that every time I want to go back to the parent page by using the browser back, the URL in the panel changes, but not the view.

**To Reproduce**  

I can reproduce it on at least two Kirby CMS installs

1. Go to the panel
2. Click on a page
3. Hit the browser back button

**Expected behavior**  
The Browser correctly navigates to the last page in the browsing history.

**Screenshots**  
–

**Kirby Version**  
3.5.3.1

**Console output**  
There is no output in the console

**Desktop (please complete the following information):**  
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 86.0.1

**Smartphone (please complete the following information):**  
Not tested

**Additional context**  
Can't tell if that is always or was always the case.

**Comment by afbora** [comment]
I can confirm that. Does not happen everytime. I did not create an issue because I could not find the exact conditions under which this error occurred.

**Comment by renestalder** [comment]
Yep, was the same for me. First it seemed like occasionally when changing to a page or image that was referenced in a page field, image field. But then I opened another CMS instance and could immediately reproduce it after every click.

**Comment by bastianallgeier** [comment]
I wonder if this is an issue in Vue router or in our implementation. We basically just follow their examples how to use routes and I don't really know where we could even be doing something wrong here.

**Comment by afbora** [comment]
I've done few tests and this issue appeared with 3.5.0. No issue for 3.4.5.

I also found the conditions for you to test, follow these steps:

1. Login to panel
2. Clear Local Storage & Session Storage & Cookies (from application tab in browser console )
3. Get back to panel, you'll redirect to login when you refresh
4. Login panel again
5. Click any page and try to go back with "browser back button"
6. See issue

**Comment by lukasbestle** [comment]
In 3.5.0 we updated `vue-router` from `v3.1.6` to `v3.4.9`. I found this in their issue tracker: https://github.com/vuejs/vue-router/issues/3245

**Comment by igregson** [comment]
I've noticed this, too. 

Specifically, I see it after logging into the panel. Once I do a full page refresh while being logged in (and on a panel page) the issue is gone (i.e. the back button then works as expected). This makes me wonder if the issue is connected to the redirect method used after logging in.

**Comment by alancwoo** [comment]
I've written in the forum: https://forum.getkirby.com/t/panel-back-doesnt-work/21947/5

I noticed this seems to happen after logging in. If I am already logged in, open a new tab/window and use the panel, it doesn't seem to occur.

Kirby v3.5.3.1 and in both firefox 88.0b8 and Chrome 89.0.4389.128

https://imgur.com/a/Ok4Rakk

**Comment by bastianallgeier** [comment]
✅
