### ISSUE TITLE
Page::title implementation has incorrect PHPDoc, returns Field|string

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#3218]
Using Kirby 3.5.3.1.

The Page::title implementation at:
https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Cms/Page.php#L1424-L1432

has an incorrect return type in the PHPDoc comment. Looking at the code, and from my experience a couple days ago, it can return a string if the page doesn't have a 'title' field or has an empty title field.

1. Page has an non-empty title field: returns a `Field`
2. Page has no title field or an empty title field: returns a `string` (from `$page->slug`).

Two possible solutions:

1. Update the PHPDoc to `@return \Kirby\Cms\Field|string`
2. Update the implementation to always return a Field, perhaps constructing a new Field with the slug value?

```php
$field = $this->content()->get('title');
if ($field->isEmpty()) return $field->value($this->slug());
return $field;
```

**Comment by fvsch** [comment]
One thing I’m wondering is whether the `Content::get` method could have a second parameter to inject a fallback value into the returned Field:

```php
$title = $page->content()->get('title', $page->slug());
```

Or maybe it could be a new method on Field that takes a string:

```php
$title = $page->content()->get('title')->withFallback($page->slug());
```

Or maybe we shouldn't listen to me when it comes to API design, because I’m the one who proposed the `Field::or` method back in the Kirby 2 days, and that method allows returning either a Field object or a scalar value semi-randomly, which is a source of actual bugs I’m running into somewhat regularly. So clearly, I can’t be trusted with this. 😭

**Comment by distantnative** [comment]
Would it be the better fix to just always return a Field object from `->or()` as well?

**Comment by lukasbestle** [comment]
To be honest I cannot reproduce this. `Field::or()` already makes sure that its return value is always a field object, not the literal string value it gets passed. If I dump `$page->title()` on a page that doesn't have a title, I still get a field object with the slug as the value.

**Comment by fvsch** [comment]
Okay this is embarrassing. 🙈
Indeed this bug is invalid.

I was so sure the `->or()` implementation was returning the fallback value as is that I didn’t check it, and I probably conflated this with other “is it a Field or a scalar value?” issues I’ve had.

Sorry for the noise!

**Comment by lukasbestle** [comment]
@fvsch Don't worry, thanks for your quick reply. :)
