### ISSUE TITLE
Undescriptive crash clientside when extending non-existing fields

### ISSUE THREAD

**Issue by N247S** [getkirby/kirby#3219]
**Issue**
Not sure if it is a 'breaking change' or a mis-informative error.
Basically an exception is thrown clientside when a panel-field plugin tries to extend a non-existing field.

Extending non-existing fields was ignored before the latest version (tested on 3.4.4), but is currently breaking the entire panel (tested on 3.5.3.1)

example code for the plugin (only index.js for brevity)

```javascript
panel.plugin('my/plugin',
{
	fields:
	{
		myField:
		{
			extends: "non-existing-field",
		}
	}
}
```

Current view of the error clientside (for reference)
![image](https://user-images.githubusercontent.com/10078398/111885889-b8b1ef00-89ca-11eb-892e-ce4d65020d4f.png)

**Kirby Version** 
tested on version 3.5.3.1

**Comment by distantnative** [comment]
✅ will be fixed with 3.6.0
