### ISSUE TITLE
Move file methods to the classes they belong to

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3233]
From a [discussion in Discord](https://discord.com/channels/525634039965679616/827138504646721586/829321125707513886) with @distantnative:

> All files are Kirby\Cms\File, no matter if PDFs, images... Kirby\Image\Image is a class to take care of image conversions etc. Will need some more time thinking why these methods ended up there.
>My gut feeling is that it actually should be three things: Kirby\Cms\File for file objects in the Kirby sense, Kirby\Something\File for everything that is related to it as an actual file in the filesystem and Kirby\Image\Image for everything specific to images.

> That Kirby\Something\File already exists as Kirby\Toolkit\File. I fully agree that we should move methods around between the classes at some point.

> Indeed, we should proxy then first Kirby\Toolkit\File for all files and only for images Kirby\Image\Image as well. Or maybe it would be even better to convert the methods from Kirby\Toolkit\File into a trait that can be added directly to Kirby\Cms\File as well (since it already has to extend Kirby\Cms\ModelWithContent).

**Comment by distantnative** [comment]
✅
