### ISSUE TITLE
Writer field: Gender Star issue

### ISSUE THREAD

**Issue by mrflix** [getkirby/kirby#3235]
When I type a sentence with two words containing the [Gender Star](https://en.wikipedia.org/wiki/Gender_star), the text between the two stars turns italic:
![Screenshot 2021-04-09 at 09 55 37](https://user-images.githubusercontent.com/60777/114148436-08c10900-991a-11eb-9923-5cfca54f35a0.gif)

**Comment by CrisGraphics** [comment]
This is markdown which will be converted and stored as html (i.e `*text*` to `<em>text</em>`).
You need to either escape the  `\*` or turn off marks in the field properties, but this will also convert special characters to HTML entities (i.e. `<em>text</em>` to `&lt;em&gt;text&lt;/em&gt;`) .

**Comment by mlthrk** [comment]
Duplicate of #3138

**Comment by afbora** [comment]
@mlthrk You're right.

**Comment by mrflix** [comment]
Right! And there is a solution for it. Thanks for pointing it out @mlthrk
