### ISSUE TITLE
Shop page order

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#324]
I just installed the Alpha 8.

I am trying to order the pages in the Kitchensink/Shop.

I am getting the following error:

![image](https://user-images.githubusercontent.com/19433935/38138723-065072f2-3435-11e8-8c08-108b920b7dae.png)

This is kinda weird considering that it seems that all pages seem to be listed:

![image](https://user-images.githubusercontent.com/19433935/38138748-2349cc00-3435-11e8-93f7-c10dfb121b2d.png)

**Comment by ghost** [comment]
OK… I think I am wrong. I forgot that now the published/listed page are prefixed with a number and a `.` and not with `-`.

But the error is still a bit odd.

Not sure what would be the proper way to handle this scenario.

Currently I don't have any way to tell which are listed/unlisted without actually checking out all pages.

Completely confused 🤷‍♂️  😄

**Comment by distantnative** [comment]
I think your problem/confusion would be solved by #304, since the panel wouldn't let you try to order them in the first place. Making this reference in the other issue and i'd close this one, so we don't have duplicates. Let me know if you think differently.

**Comment by ghost** [comment]
👍 Thanks!
