### ISSUE TITLE
Session: Disable cache on active sessions

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3242]
Kirby should automatically disable the built-in page cache if the session is accessed from the controller or template. Also Kirby should set appropriate HTTP response headers to prevent caching by intermediate caches.

I‘m thinking of a new option `session.cacheHeaders` that accepts either an array of headers or a callback function that returns such an array. If not defined, it would have a sane default [like PHP](http://www.php.net/manual/en/function.session-cache-limiter.php).

**Comment by neildaniels** [comment]
Tangentially related: https://github.com/getkirby/ideas/issues/487

**Comment by bastianallgeier** [comment]
@lukasbestle I think it's important to get this done for 3.5.5 Will you be able to work on it until Tuesday, or should I take over?

**Comment by lukasbestle** [comment]
@bastianallgeier I will make sure to implement this by Monday.

**Comment by lukasbestle** [comment]
@neildaniels Ha, that's amazing! I totally forgot about that discussion, but somehow I must have still remembered it subconsciously: https://github.com/getkirby/kirby/pull/3246

**Comment by bastianallgeier** [comment]
✅
