### ISSUE TITLE
Dir::copy recursive not honoring $ignore

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#3243]
When using `Dir::copy` in recursive mode the $ignore option is lost after first recursion. I am not sure this is not intentional for some performance reasons but it makes that function pretty unpredictable.

It's this line 
https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Toolkit/Dir.php#L72

**Expected behavior**  
I would expect $ignore to function everywhere. Fix is simply passing the ignore into the recursion aswell.
```php
static::copy($root, $target . '/' . $name, true, $ignore);
```

**Comment by bastianallgeier** [comment]
✅
