### ISSUE TITLE
Leftover translation blueprint issues

### ISSUE THREAD

**Issue by pine3ree** [getkirby/kirby#3247]
**Describe the bug**  
I enabled the multilanguage feature and then removed it. After that the blueprints for existing pages stopped working.

**To Reproduce**  
1. Go to your content folder with a standard non multilang website
2. Add an extra translation txt file for a file/image (e.g. my-picture.jpg.de.txt for my-picture.jpg)
3. Go to the panel and try to edit this page
4. The default blueprint is used instead of the custom blueprint
5. If a pages field is using a template filter, that page does not show up anymore in the list 

**Kirby Version**  
3.5.3

**Desktop (please complete the following information):**  
 - OS: Linux MInt xenial based
 - Browser: Chrome 89 and FF 87

kind regards

**Comment by afbora** [comment]
If I understand it correctly;
You have enabled the multi-language feature and added a new language. Did you delete all languages from the panel before disabled from config file?

**Comment by pine3ree** [comment]
Hello @afbora,
Yes...but now all language are disabled (and their php files removed) and the config is:
```php
<?php
// site/config.php
return [
    'debug' => true,
    'panel' => [
        'install' => true,
    ],
    // 'languages' => true,
    // 'languages.detect' => true,
    'date.handler'  => 'strftime',
];
```

**Comment by afbora** [comment]
Frankly, I could not understand exactly where you were having trouble.

> Add an extra translation txt file for a file/image (e.g. my-picture.jpg.de.txt for my-picture.jpg)

Why do you add a language suffix even though you have removed all languages or multilanguage is not enabled? 🤔

**Comment by pine3ree** [comment]
Hello @afbora ,

after removing the multilanguage features there were a few leftover file txt translations. I did not add them myself after removing the languages. I only suggested how to reproduce the issue I encountered. Either way, why is the presence of a single file translation affecting the page blueprint not being used? the config settings `'languages' => false` (or its absence) should be enough to discard any translation. Were You able to reproduce the issue following my steps?

kind regards

**Comment by texnixe** [comment]
If you have content files with a language code extension while the multi-lang feature is disabled, blueprints stop working. In the same way that can happen when you have any other leftover text files, for example if you manually delete images without deleting the meta data files.

That why you should always remove languages via the Panel (then the content text files are automatically renamed/removed) or you have to rename them manually if you manually remove the language definition files. This is explained in the documentation. So this is not a bug but they way Kirby works.

**Comment by pine3ree** [comment]
Hi @texnixe , thanks for the clarification! kind regards!
