### ISSUE TITLE
[Panel] Emoji page icons not working

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#325]
I just can't find a good title for this issue 🙃 

The biggest problem is that I can't see the emojis! 🐴 

Instead I get this:

![image](https://user-images.githubusercontent.com/19433935/38139378-d14b3972-3437-11e8-8cc6-6cf34b814421.png)

![image](https://user-images.githubusercontent.com/19433935/38139483-3e380588-3438-11e8-9b5a-dd65c3a14643.png)

**Comment by distantnative** [comment]
Could you please provide your blueprint, so we can test ourselves? Thanks!

**Comment by ghost** [comment]
Default Alpha 7. I just installed it 🙃

**Comment by distantnative** [comment]
What system, browser, version etc. … is this happening?

**Comment by ghost** [comment]
macOS 10.12.6
Apache 2.4.28
PHP 7.1.13
Chrome 65.0.3325.181

**Comment by distantnative** [comment]
Part of it is #321 and for that we have found a first fix.

However, sadly I cannot reproduce this problem, to examine why our `isEmoji()` test seems to fail. Given from the URL requests, your browser wants to load the emojis as svg files instead to just display the emojis.

**Comment by wottpal** [comment]
Same problem in both latest Safari and latest Chrome.

macOS 10.13.4
PHP 7.2.4
Apache 2.4.33

[kirby.local-1522751100318.log](https://github.com/k-next/starterkit/files/1871114/kirby.local-1522751100318.log)

**Comment by bastianallgeier** [comment]
✅
