### ISSUE TITLE
Layout-Editor: Link Title deleted when leaving page and coming back.

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#3255]
**Describe the bug**  
Using the Layout Editor causes a problem with the title of a link in a textblock. It gets lost when you leave the page in the panel and start editing later again. Tested in my local project and a fresh and clean starterkit from github.

**To Reproduce**  
1. Open a page in the panel.
2. Create a demo-text in the layout.
3. Add a link to a word or sentence and add a title to the link
3. Save the changes
4. Leave the page in the panel and open it again.
5. Check the earlier created link. The link-url is still there, the title tag is lost.

**Expected behavior**  
Title Tag expected to be stored correcty.

**Kirby Version**  
3.5.3.1

**Comment by bastianallgeier** [comment]
✅
