### ISSUE TITLE
Video block does not show domain-restricted clips in Panel

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3257]
As the Panel sets a `same-origin` referrer policy for privacy/infosec reasons,

https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/views/panel.php#L20

the iframe embed of the video block correctly does not communicate the referrer domain to Vimeo and the embedded page hence shows a *"Sorry, Because of its privacy settings, this video cannot be played here."* error rather than the video (as [brought up on Discord](https://discord.com/channels/525634039965679616/761608160565133343/833639343347859456)).

This should be possible to fix — analogous to the solution [discussed on the forum](https://forum.getkirby.com/t/vimeo-embed-in-panel/21226) and [in the related kirby-embed plugin's issue](https://github.com/sylvainjule/kirby-embed/issues/5) — by adding a `referrerpolicy="strict-origin-when-cross-origin"` attribute to the iframe code at:

https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/panel/src/components/Blocks/Types/Video.vue#L11

**Comment by bastianallgeier** [comment]
✅
