### ISSUE TITLE
[Form] Date: validate format to be supported by strtotime

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#326]

**Comment by bastianallgeier** [comment]
? What do you mean exactly here?

**Comment by distantnative** [comment]
Currently, when saving a date we write it to the file in style of our `format` option:

```php
    protected function dateToString($value): string
    {
        if ($date = strtotime($value)) {
            return date($this->format(), $date);
        }

        return '';
    }
```

However, when we read it from the file, we just run it through `strtotime`:
```php
    protected function dateFromInput(string $value = null)
    {
        if ($value !== null && $date = strtotime($value)) {
            return date(DATE_W3C, $date);
        }

        return null;
    }
```

Which is why the `format` option must always be in a format which is supported by `strtotime`. And this can have some pitfalls:

> Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed. If, however, the year is given in a two digit format and the separator is a dash (-), the date string is parsed as y-m-d.

**Comment by bastianallgeier** [comment]
phew, but how would we validate that?

**Comment by distantnative** [comment]
Yea, maybe we can't. But then we should put a notice box in our docs to make sure people use it right.

**Comment by bastianallgeier** [comment]
Yes, we already had the same issue in v2
