### ISSUE TITLE
Using dynamic Query Language values for blueprint API options URLs fails

### ISSUE THREAD

**Issue by simon-hayden** [getkirby/kirby#3260]
**Describe the bug**  
Using dynamic Query Language values for blueprint API options `url` at the end of URL value causes
`Invalid options format in file: kirby/src/Form/OptionsApi.php line: 132` which is where the OptionsAPI checks if the field is an array. My JSON response is [1] valid, [2] an array of `key:value` pairs, and [3] the route definitely returns the JSON I’m expecting.

My API response 

**To Reproduce**  
Steps to reproduce the behavior in a simple test:
1. Create an API endpoint route that returns JSON, such as https://www.mydomain.com/product/(:all). 
_For testing, you can reproduce this without doing anything with the dynamic param on the route, and return the same JSON array regardless of the param, but the actual use case would typically be that you want different repsonses based on the param supplied._
```
[
   {"title":"Product A"},
   {"title":"Product B"},
   {"title":"Product C"},
   {"title":"Product D"}
]
```
2. Create option based field (checkboxes, select, multiselect etc.) to query that endpoint.
```
my_field:
  options: api
  type: multiselect
  label: My Field
  api:
    url: "{{ site.url }}/product/{{ page.uid }}"
    text: "{{ item.title }}"
    value: "{{ item.title }}"
```
    
3. If you hardcode the `url` value it will work:
```
api:
  url: "https://www.mydomain.com/product/my-page-id" ✅
  ```
  If you use dynamic values at the start of the url, it will work:
  ```
api:
  url: "{{ site.url }}/product/my-page-id" ✅
  ```
4. If you use dynamic values at the end of the URL, it will give `Invalid options format in file: kirby/src/Form/OptionsApi.php line: 132`
```
api:
  url: "{{ site.url }}/product/{{ page.uid }}" ❌
  ```
  OR
```
api:
  url: "https://www.mydomain.com/product/{{ page.uid }}" ❌
  ```
**Expected behavior**  
Using dynamic values - e.g. `{{ page.uid }}, {{  page.autoid }}` - at the end of the query URL queries the processed string as constructed

**Kirby Version**  
Version 3.5.3.1

**Console output**  
None

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari, Chrome
 - Version: Safari 14.0.3, Chrome 90.0.4430.85

**Other comments**
See my [Kirby Forum post](https://forum.getkirby.com/t/multiselect-field-options-api-returning-invalid-options-format-in-file/21925) for related context.

**Comment by afbora** [comment]
I haven't test yet but i just wonder your page title? Did you try 'uid'?

    api:
      url: "{{ site.url }}/product/{{ page.uid }}"

**Comment by simon-hayden** [comment]
> I haven't test yet but i just wonder your page title? Did you try 'uid'?
> 
> ```
> api:
>   url: "{{ site.url }}/product/{{ page.uid }}"
> ```

Good point. Yes, in practice I was actually using `autoid` from the AutoID plugin, but didn't want to reference plugins in the example as they're not core; but just the presence of a dynamic value at the end of the URL causes the error; it doesn't actually matter what the dynamic value is referencing. 

I will update my Issue as `{{ page.title }}` would have spaces in it etc.

**Comment by bastianallgeier** [comment]
✅

**Comment by simon-hayden** [comment]
Did this fix go into 3.5.5? Seems like it did from the merged PR, but it's not on the 3.5.5 Change Log

**Comment by afbora** [comment]
@simon-hayden It already exists in changelog:
https://github.com/getkirby/kirby/releases/tag/3.5.5

![screen-capture-1073-Release 3 5 5 · getkirby_kirby-github com](https://user-images.githubusercontent.com/3393422/118630983-be179400-b7d7-11eb-9cba-90facbfa51ca.png)

**Comment by simon-hayden** [comment]
Doh! Was looking for #3273 from the PR number 🙈

**Comment by afbora** [comment]
If a PR has a related issue, it is indicated with the issue number in the changelog. Otherwise, it is indicated by the PR number.
