### ISSUE TITLE
Blocks: max 1 is not prevented by 'Plus' button

### ISSUE THREAD

**Issue by alancwoo** [getkirby/kirby#3261]
**Describe the bug**  

A blocks field with `max: 1` can still have multiple blocks added using the circular `+` button. `Insert before/after` is disabled, but the `+` still works from both the field dropdown and block toolbar.

**To Reproduce**  
1. Setup a blocks blueprint with `max: 1`
2. Create a page in the panel and add multiple blocks via the `+` button

**Expected behavior**  

The `+` buttons should be disabled

**Screenshots**  

Incorrectly enabled add buttons:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/1481890/115740625-4e0c1e80-a38f-11eb-8c20-35b59276a89e.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/1481890/115740652-55332c80-a38f-11eb-90f0-e2e1148bdfe8.png">

Correctly disabled Insert before/after buttons:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/1481890/115740687-5e23fe00-a38f-11eb-9932-2f7f308977de.png">

**Kirby Version**  

3.5.3.1

**Console output**  

**Desktop (please complete the following information):**  
 - OS: Mac OS 11.2.3
 - Browser: Firefox
 - Version: 88.0b9 (64-bit)

**Additional context**  

I imagine it has to do with the hardcoded `isEmpty` computed property: https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/panel/src/components/Forms/Field/BlocksField.vue#L70

Versus: https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/panel/src/components/Blocks/Blocks.vue#L131

**Comment by afbora** [comment]
Duplicated with #3179?

**Comment by alancwoo** [comment]
Ah correct, I'm sorry. Thank you for closing the other one.
