### ISSUE TITLE
Video block does not save caption writer fields formats

### ISSUE THREAD

**Issue by Lieblingstyp** [getkirby/kirby#3264]
As said in the title: The video blocks does not save the marks inside the caption field and you're unable to style the caption outside the drawer.

**Comment by afbora** [comment]
I know this is about missing `:caption-marks` prop. 
@bastianallgeier `Image` block have this prop but `Video` block not. 
Is this intended or missing?

https://github.com/getkirby/kirby/blob/3.5.3.1/panel/src/components/Blocks/Types/Image.vue#L4

**Comment by bastianallgeier** [comment]
It's not intended

**Comment by afbora** [comment]
✅

**Comment by Lieblingstyp** [comment]
Thanks :)
