### ISSUE TITLE
Date field with array for time throws error in plugin Vue component

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3266]
**Describe the bug**  
When we created the Commentions plugin about a year ago (i.e. before the update of the date/time field components), the `date` field with a timestamp in one-minute steps in the "Edit comment" dialog ([source code](https://github.com/sebastiangreger/kirby3-commentions/blob/de8e85bb1ee24e96e524bd3c6aa434b4eefb719f/src/components/Dialogs/EditDialog.vue#L60)) worked fine; users could change the date and time of a submitted comment.

Recently, this field does no longer appear to work; instead the following error is displayed:

![Screenshot from 2021-03-05 09-03-45](https://user-images.githubusercontent.com/6355217/110085862-ea537500-7d91-11eb-8ed9-044d8a84f516.png)

Above screenshot is from Firefox; in Chromium, the error message is **"Cannot read property '$invalid' of null"**.

Did the API change, requiring changes in our Vue component, or is this a bug?

**To Reproduce**  
1. Create a Vue component that includes the following:
```
  computed: {
    fields() {
      return {
        timestamp: {
          label: "Date and time",
          type: "date",
          required: true,
          time: {step: 1},
        },
```
2. Open the view in the panel and see the error
3. Remove the line `time: {step: 1},` and the field is shown as intended, but with the default 5-minute precision

**Expected behavior**  
The Panel view would display an input field for date and time, with the ability to enter the time with one-minute precision.

**Kirby Version**  
3.5.3

**Console output** 

in Chromium:
```
app.js:1 TypeError: this[w.p(...)] is not a function
    at p.d.get (vendor.js:12)
    at a.toNearest (app.js:1)
    at a.toFormat (app.js:1)
    at a.data (app.js:1)
    at a.<anonymous> (vendor.js:23)
    at lr (vendor.js:23)
    at ur (vendor.js:23)
    at sr (vendor.js:23)
    at a.t._init (vendor.js:23)
    at new a (vendor.js:23)
errorCaptured @ app.js:1
app.js:1 TypeError: Cannot read property '$invalid' of null
    at a.onInvalid (app.js:1)
    at a.mounted (app.js:1)
    at oe (vendor.js:23)
    at Bn (vendor.js:23)
    at Object.insert (vendor.js:23)
    at T (vendor.js:23)
    at a.__patch__ (vendor.js:23)
    at a.t._update (vendor.js:23)
    at a.r (vendor.js:23)
    at or.get (vendor.js:23)
errorCaptured @ app.js:1
```

**Desktop (please complete the following information):**  
 - OS: Linux Mint 19.3
 - Browser: Firefox 86.0.1 / Chromium 89.0

**Additional context**
- Bug tracked in our plugin's repo at https://github.com/sebastiangreger/kirby3-commentions/issues/102
- Potentially related to https://github.com/getkirby/kirby/issues/3107 ?

**Comment by distantnative** [comment]
I am sorry that I didn't see this before - I was looking in the totally wrong places 🙈

Can you check if it works when you do `time: {step: { size: 1, unit: "minute"})`?

**Comment by sebastiangreger** [comment]
> Can you check if it works when you do `time: {step: { size: 1, unit: "minute"})`?

Yes, that works indeed.

**Comment by distantnative** [comment]
I'll see if I can add something to the Vue refactoring for date fields to throw a better error here. 
When moving from PHP to Panel, we transform shorthand blueprint options such as `step: 1` automatically. The Vue components need more specific input but should at least yell when passed something else.

**Comment by distantnative** [comment]
✅ Ok from 3.6.2 onwards, I made sure to see
<img width="797" alt="Screen Shot 2021-12-19 at 14 16 18" src="https://user-images.githubusercontent.com/3788865/146676176-06097455-710d-4974-82e7-41a6550f67cf.png">

**Comment by sebastiangreger** [comment]
Great this was so easy to "fix". Merci beaucoup!

**Comment by distantnative** [comment]
I am really sorry that I overlooked this syntax problem foremost 8 months, always thought it's an issue way down in the messy components.
