### ISSUE TITLE
API debug exception error only returns filename (not file path) when DOCUMENT_ROOT differs from site folder

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3267]
**Describe the bug**  
In situations where an installation's `$_SERVER['DOCUMENT_ROOT']` is set to a secluded folder that is separate from the Kirby installation (and `site` folder), API exceptions do not return a helpful file path.

**To Reproduce**  
1. Set document root to something like `/var/www/html/website/public`
2. Have a plugin in a folder like `/var/www/html/website/site/plugins/example-plugin/index.php`
3. Enable debug mode.
4. Do something in a hook that would throw an exception.

**Expected behavior**  
The JSON API error would say a helpful file path where the error occurred. Instead, you only get the filename.

_Actual_
```json
{
    "status": "error",
    "message": "Kirby\\Cms\\Site::TheStreamable\\ExamplePlugin\\{closure}(): Argument #1 ($foo) must be of type Object, string given",
    "code": 500,
    "exception": "TypeError",
    "key": null,
    "file": "index.php",
    "line": 122,
    "details": [],
    "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
}
```

_Expected_
```json
{
    "status": "error",
    "message": "Kirby\\Cms\\Site::TheStreamable\\ExamplePlugin\\{closure}(): Argument #1 ($foo) must be of type Object, string given",
    "code": 500,
    "exception": "TypeError",
    "key": null,
    "file": "/var/www/html/website/site/plugins/example-plugin/index.php",
    "line": 122,
    "details": [],
    "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
}
```

(The expected file path could be truly relative, with something like `../site/plugins/example-plugin/index.php`, but I don't really care much either way.)

**Kirby Version**  
`3.5.3`

**Additional context**  
Relavant Kirby line:
https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Api/Api.php#L689

It seems that `F:: relativepath()` handles the scenario that `$file` is not a descendant of `$in` by just returning the filename, which seems like an odd choice to me.

https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Toolkit/F.php#L646-L661

**Comment by lukasbestle** [comment]
✅
