### ISSUE TITLE
[Panel] Refactor Date/Time fields and inputs

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#327]
- [x] Refactor & dumb-down DateInput
- [x] Refactor & dumb-down CalendarInput
- [x] Refactor & dumb-down TimeInput
- [x] Refactor DateField
- [x] Refactor DatetimeField
- [x] Refactor TimeField
- [x] Throw out custom Dates library. Use luxon.
- [x] Throw out custom Times library. Use luxon.
- [x] Support localization through luxon

**Comment by bastianallgeier** [comment]
✅
