### ISSUE TITLE
Select-field fetching from api throws timeout on localhost (plugin)

### ISSUE THREAD

**Issue by Adaphath** [getkirby/kirby#3281]
**Describe the bug**  
I can't fetch a route (localhost/*) in a select field from my installed plugin.
External URLs are perfectly working.

**To Reproduce**  
1. Create a select field in a blueprint:
```formSelect:
    label: Select
    type: select
    options: api
    api:
      url: http://127.0.0.1:8000/forms
```
2. Have a route setup in a plugin:
```
return [
      [
        'pattern' => 'forms',
        'action' => function () {
          return '{"userId": 1,"id": 1,"title": "delectus aut autem","completed": false}';
        }
      ]
    ];  
  }
```
3. Try to edit page with the field
4. See error: `Operation timed out after 10001 milliseconds with 0 bytes received in file: /....../kirby/src/Http/Remote.php line: 281`

**Expected behavior**  
Fetching the json text as it does at the external api (http://jsonplaceholder.typicode.com/todos/1) and make it available in the text field

**Kirby Version**  
3.5.4

**Comment by afbora** [comment]
Shouldn't the uri start with the `/api`? 🤔 

    http://127.0.0.1:8000/api/forms

**Comment by Adaphath** [comment]
Currently tried it with a "normal" route.
I can access the url with my browser and get the json content.
But Kirby is not able to do so.

**Comment by afbora** [comment]
Hmm I get it. Now I have tested it like your setup but it worked successfully. I can see dropdown items. 
It may be related to your local setup 🤔 
Lets asking @texnixe who has a lot of experience about that.

**Comment by lukasbestle** [comment]
@Adaphath We had similar issues with cURL not being able to send requests or receive responses from `localhost` before. With your URL (IP and port) it should work, but just to make sure: Could you please try `localhost:8000` instead?

Also check if you have a local firewall running that could block this request. Maybe you need to allowlist your PHP executable.

**Comment by Adaphath** [comment]
I'm still getting the `Operation timed out after 10001 milliseconds with 0 bytes received in file:`.

But if @afbora got it working locally I assume that it is indeed an issue with my local setup.
