### ISSUE TITLE
[Panel] update npm packages

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#329]
Take advantage of their bugfixes from the last 6 months

**Comment by bastianallgeier** [comment]
LOL

**Comment by distantnative** [comment]
@bastianallgeier after spending 15 minutes on a bug, I realized that it had been fixed in luxon... and that luxon is on 1.0.0 now, while we were still at 0.2 🤦‍♂️

**Comment by bastianallgeier** [comment]
I installed greenkeeper to help us with this. We just need to enable CI to get it running.

**Comment by bastianallgeier** [comment]
✅
