### ISSUE TITLE
[Panel] Allow more image file types

### ISSUE THREAD

**Issue by malvese** [getkirby/kirby#33]
Not sure it is temporary during the alpha, so writing it down here.

**Comment by bastianallgeier** [comment]
Yes, it's temporary. What I actually want to do is to accept gif, png and jpegs again, but store them all as jpg. It solves quite a lot of logic around the different file formats and I'm not sure why we would need different ones, except maybe a couple kb of file size savings.

**Comment by malvese** [comment]
But then if we use these avatars, in blog posts or an about page, crisp PNGs (say, like my own avatar) may end up blotched with jpeg artifacts
So, if size is not an issue, what about doing the opposite: store them as PNGs so image quality never suffers?

**Comment by bastianallgeier** [comment]
You are right. Compromising quality doesn't sound so good. I will rethink this.

**Comment by jenstornell** [comment]
Is this for all images or just for the user picture. If it's for anything, I think it's dangerous to convert everything to jpg all the time.

The reason for that is that jpg is not transparent for example and in some cases a transparent image is needed (png is transparent).

Another reason could be an animated gif. It would be lost during a conversion to jpg.

**What I do want to see is the feature I added here:**
https://github.com/jenstornell/superthumbs

```php
echo thumb($page->image(), array('width' => 300, 'quality' => 80, 'format' => 'jpg'));
```

An option to select an output format. If it's not that format, convert it.

**Comment by distantnative** [comment]
@jenstornell converting to jpg is/was a thought only applying to user avatars

**Comment by bastianallgeier** [comment]
@jenstornell format conversion for thumbnails would be cool, but also increase the logic behind it again.

**Comment by luxlogica** [comment]
A request here to please accept SVG files as well.

**Comment by luxlogica** [comment]
It may be easier to simply treat avatars as *any other image*. Kirby should perhaps simply store whatever image file is uploaded, and then internally use `thumb()` to display it in the Panel interface as required. 

If developers want to use the avatar image in their frontend, they should treat it like *any other image* - i.e., apply `thumb()` if any conversion or resizing is needed before displaying it. 

In my use-case, we want to upload SVG LOGO FILES to use as avatars in a client's site - which ensures optimal display at any size and screen resolution. So it would be more useful to have access to the unaltered avatar image file, than to have it auto-converted or resized. Perhaps the Panel could check the file type, and if it is an svg, leave it alone?

**Comment by bastianallgeier** [comment]
✅
