### ISSUE TITLE
FontAwesome 4.5

### ISSUE THREAD

**Issue by AhoyLemon** [getkirby/kirby#330]
This is a tiny, silly niggle, but I wanted to point it out anyway...

If I view the source of panel.min.css, I can see that Kirby is using [FontAwesome](https://github.com/FortAwesome/Font-Awesome) 4.4.0, the only reason I noticed is because between versions was the Google rebranding and so the Google and Google+ icons are the old lowercase g.  (also I guess you might want the `edge` or `product-hunt` icons... maybe?)

**Comment by bastianallgeier** [comment]
I just moved this to the panel issue section: https://github.com/getkirby/panel/issues/690
