### ISSUE TITLE
User account email addresses with uppercase letters cause issues

### ISSUE THREAD

**Issue by VIPStephan** [getkirby/kirby#3305]
**Describe the bug**  
If I change the email address of a user account to contain uppercase letters (e. g. Test@example.com) I have observed two issues:

1. this user account will not be saved in a users field anymore
2. login to the panel with this user account isn’t possible anymore (says user account doesn’t exist)

**To Reproduce**  

For issue 1:
1. Create a page blueprint with a users field
2. Go to “Accounts” in the admin panel
3. Click on a user account
4. Change account email address to e. g. Test@example.com
5. Go to the page with the users field
6. Add the user whose email has been changed in step 4
7. Save the page
8. Reload the page
9. User disappeared from the users field

For issue 2:
1. Follow steps 1 to 4 from the previous list
2. Log out
3. Log in as the user with email Test@example.com
4. Login is not possible

**Expected behavior**  

1. The user should be saved properly and still be visible after reloading the page
2. It should be possible to log in

**Kirby Version**  

3.5.4

 - OS: macOS Catalina
 - Browser: Firefox
 - Version: 88.0.1

**Comment by afbora** [comment]
I agree, there is no consistency on user email when creating, updating and logging in users.

**Comment by lukasbestle** [comment]
The question is: Should we:

1. treat user emails case-insensitively throughout the system (which would be a performance issue for sites with a large number of users) or
2. should we treat the email address as case-sensitive (with negative UX implications) or
3. should we convert all email addresses to lowercase automatically (which would be safest, but can be unexpected)?

I'm currently leaning towards option 3, what do you think?

**Comment by bastianallgeier** [comment]
I'm also leaning towards 3. We have the same problem on the license server. People register with mixed case addresses and then try to login with lowercase versions for some reason later and get rejected.

**Comment by afbora** [comment]
I also think that the best way is the 3rd option 👍. We already used `strtolower` when creating a user (`User::create()`), but we didn't use it while updating.

**Comment by lukasbestle** [comment]
OK, then it's a low-hanging fruit to consistently lowercase the email address on update as well.

**Comment by bastianallgeier** [comment]
✅
