### ISSUE TITLE
Images larger than 4000px wide not generating thumbnail

### ISSUE THREAD

**Issue by tijngoessaert** [getkirby/kirby#331]
When I upload an image wider than 4000px kirby doesn't generate a thumbnail, what could be the problem? Smaller images do generate a thumbnail. This issue only occurs to me in Kirby 2.2.

**Comment by shoesforindustry** [comment]
Could this be the server running out of memory? We've had some problems on some cheap shared servers we use for testing, where they fail with much smaller images.

**Comment by tijngoessaert** [comment]
I don't think so, I have an older version of kirby running on the same server and there the issue doesn't occur.

**Comment by bastianallgeier** [comment]
Since Kirby 2 large images are not being generated when GD lib is activated. Too many users where running into memory issues. You can fix this by switching to imagemagick: 

```php
c::set('thumbs.driver', 'im');
```
