### ISSUE TITLE
Dead code: CSS classes

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3314]
I think these CSS classes never got and still don't get applied: https://github.com/getkirby/kirby/blob/develop/panel/src/components/Layout/Header.vue#L14

It's basically dead code which we could remove.

**Comment by lukasbestle** [comment]
These classes were already there in the first code version in this repo, so we cannot tell why they were added. Maybe just for testing or before refactoring and then we forgot to remove them again.

It could only be that plugins use the classes for custom styling or something.

**Comment by distantnative** [comment]
> It could only be that plugins use the classes for custom styling or something.

No, I checked, they don't actually end up in the output (neither before nor after the recent PR). That's why I call them dead code. They're in the source files but applying to a `slot` doesn't lead to them being applied to the slot content.

I imagine when creating this in the first place, we thought it would be good to have CSS classes there. But never realized that it isn't working this way.

**Comment by lukasbestle** [comment]
Right! `<slot>`s are not real elements, so Vue ignores every "normal" HTML attribute. Then we can easily remove them.

**Comment by lukasbestle** [comment]
✅
