### ISSUE TITLE
Link overlay of writer field not being translated

### ISSUE THREAD

**Issue by silllli** [getkirby/kirby#3316]
**Describe the bug**  

When adding or editing a link in a writer field, the labels in its overlay are not being translated.

**To Reproduce**  
1. Set up a writer field.
2. Add a link.
3. Look at the overlay.

**Expected behavior**  

The overlay being translated to the current panel language.

**Screenshots**  

![Bildschirmfoto 2021-05-10 um 18 37 49](https://user-images.githubusercontent.com/9334305/117693932-d4619680-b1be-11eb-8c42-ff700599fbb0.png)

**Kirby Version**  

3.5.5-rc.1

**Console output**  

No errors in the console.

**Desktop (please complete the following information):**  
 - OS:  macOS
 - Browser:  Chrome
 - Version:  90.0.4430.93

**Comment by afbora** [comment]
Related file that hard coded translation:

https://github.com/getkirby/kirby/blob/3.5.5-rc.1/panel/src/components/Writer/Dialogs/LinkDialog.vue#L25-L43

**Comment by afbora** [comment]
✅

**Comment by afbora** [comment]
Its solution will move to 3.5.6 (cherry-picking)

**Comment by lukasbestle** [comment]
✅
