### ISSUE TITLE
Panel / List Block / field content value "out of sync"

### ISSUE THREAD

**Issue by jangoedde** [getkirby/kirby#3320]
**Describe the bug**  
Adding and editing default list block in the panel seems broken since 3.5.5
Seems like field content value in panel is "out of sync" between overlay and page.

**To Reproduce**  
1. Add default list block in panel
2. Edit list field in overlay or page by adding content
3. Field value "out of sync" and could partially not be saved

**Expected behavior**  
Field value in overlay should be same value like field value in page and vice versa.

**Kirby Version**  
3.5.5

Tested on macOS in Chrome, Safari and Firefox

**Comment by afbora** [comment]
List field works great but not in drawer.
`v-model="list"` prevents to emit on drawer and when removed works as expected.
@distantnative Do you have an idea? I am really a beginner in this matter.

Related line:
https://github.com/getkirby/kirby/blob/3.5.5/panel/src/components/Forms/Input/ListInput.vue#L4

**Comment by Werbschaft** [comment]
Just wanted to open an issue as well before I found that one. Here is a short video about what exactly it is about

![list-bug](https://user-images.githubusercontent.com/2178466/118356941-d25d5600-b577-11eb-9c86-76f7684c5486.gif)

**Comment by bastianallgeier** [comment]
✅
