### ISSUE TITLE
Files without a blueprint show outdated info to setup blueprint.

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#3322]
If a file has no blueprint, I see the following in the panel:

![20210512-143415_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/117976028-9768e180-b32f-11eb-943f-c79517e45cc6.png)

The hint should rather communicate to create this file in `/site/blueprints/files/default.yml` instead.

**Comment by afbora** [comment]
This should be fixed from the Transifex:

https://github.com/getkirby/kirby/blob/develop/i18n/translations/en.json#L266

**Comment by afbora** [comment]
This issue coming from two places:
- Translation string
https://github.com/getkirby/kirby/blob/master/i18n/translations/en.json#L266
- Default file blueprint name that named `File` instead `template`
https://github.com/getkirby/kirby/blob/master/config/blueprints/files/default.yml

**Comment by lukasbestle** [comment]
The blueprint name is correct, but the injected `{template}` variable is incorrect.

**Comment by afbora** [comment]
I did some work on the issue. `blueprint.template` value returns `null`. Only the `name` and `title` value are filled.

Therefore, I could not solve the issue as it is a little deeper.

**Comment by lukasbestle** [comment]
It's probably one of those issues that becomes easier to solve when Fiber is merged. Then we can pass the required information from the backend more easily.

We seem to have the same issue with missing page blueprints at the moment:

![Bildschirmfoto 2021-05-30 um 13 29 30](https://user-images.githubusercontent.com/1595007/120102399-15f4ba00-c14b-11eb-8243-a6f77eeb15a8.png)

Open todos:

- [ ] Update `file.blueprint` translation to use the path `/site/blueprints/files/{template}.yml`
- [ ] Update `page.blueprint` translation to use the path `/site/blueprints/pages/{template}.yml`
- [ ] Pass the raw template name as the `{template}` placeholder in `FileView` and `PageView`

**Comment by bastianallgeier** [comment]
✅
