### ISSUE TITLE
More `Filesystem` cleanup

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3329]
As discussed in https://github.com/getkirby/kirby/pull/3285:

- Move `F` and `Dir` classes into `Filesystem` namespace
- Check if `Toolkit\File` can be moved into `Filesystem` as well (conflicts with the already existing `Filesystem\File`)

**Comment by distantnative** [comment]
I would say if we move `F` and `Dir`, we really should not leave `Toolkit\File` behind. However `Toolkit\File` and `Filesystem\File` can't easily be merged - so what do we do there?

**Comment by distantnative** [comment]
I still haven't found a good idea what to do with `Filesystem\File` and `Toolkit\File`. We don't use `Toolkit\File` ourselves (if I didn't make a mistake) besides for extending `Filesystem\File`. So one way could be to copy all methods over to `Filesystem\File` (the ones who aren't overwritten anyways) and not extend `Filesystem\File` anymore.

And then a question would be if developer are using `Toolkit\File` or if we could deprecate it slowly.

**Comment by lukasbestle** [comment]
The only methods of `Toolkit\File` that are overridden in `Filesystem\File` are:

- `__construct()` (but they are compatible)
- `modified()` (added support for the `date.handler` option, the different handler default value would be a breaking change for non-CMS use-cases, but OK within the CMS)
- `toArray()` (returns additional attributes)

So everything considered, I think we can throw the methods together into `Filesystem\File` without any major issues and then we can alias `Toolkit\File` to `Filesystem\File` for compatibility.

**Comment by iskrisis** [comment]
Wont this break many plugins? I use `F` and `Dir` quite often. Or there is going to be some kind of Facade?

**Comment by distantnative** [comment]
@iskrisis we add class aliases for the full namespaces and redirect the shorthand class aliases
