### ISSUE TITLE
[Panel] Loading indicator fallback

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#333]
Some browsers e.g. Safari do not show a native progress cursor. We should have a replacement/fallback to still show that the page is still loading.

Alternatively, dim the view content until finished loading.

**Comment by bastianallgeier** [comment]
Hm, that's weird. Safari actually supports the progress cursor: https://developer.mozilla.org/de/docs/Web/CSS/cursor It seems to be a different issue in that case.
