### ISSUE TITLE
[3.6.0] `k-dropdown-content` background color broken

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3337]
**Describe the bug**  

`k-dropdown-content` background color broken and might be related new `.k-dropdown-content[data-align=right]` class.

**To Reproduce**  
1. Go to panel
2. Click any three dots to open dropdown content
3. See error

**Screenshots**  

![screen-capture-1067-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/118379020-3d427780-b5e0-11eb-9af7-cf8e32423cdc.png)

**Kirby Version**  
develop branch of 3.6.0

**Comment by bastianallgeier** [comment]
This is fixed on our inertia branch.
