### ISSUE TITLE
[Cms] Implement t() translation helper

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#334]

**Comment by bastianallgeier** [comment]
✅

**Comment by jenstornell** [comment]
Doesn't this go against what was said here?

https://github.com/k-next/starterkit/issues/266#issuecomment-376282166

>I'm honestly not a big fan of such meaningless one letter helper/alias methods [...] But what all these abbreviation and 1-2 letter aliases result it is code that is harder to read, much harder to understand.

>I think so too. Kirby 1 had even more of those and some were really obscure. Every time I saw them in other people’s code (or my own code from a while back), I had to look up what they meant.

>I totally agree with @lukasbestle and @distantnative. The goal should be less aliases and better readable code.

**Comment by bastianallgeier** [comment]
Yes and no :) 

Nico and I just discussed how we want to unify the translation methods. Our Vue translation plugin has a `$t()` function. In your panel plugins you can translate anything in js templates with `$t('something')` so we wanted to keep it the same on the PHP side. We already had a `Kirby::translate()` method. That would need to be called like this: `$kirby->translate()` or even like this `Kirby::instance()->translate()` if `$kirby` is not already available. That is quite a mouthful. We already had a one-character helper in v2 called `l()` so it seemed like a good idea to move that to `t()` and keep an `l()` alias. 

T for translate seems a lot better than l for language in my opinion as it describes the action.
