### ISSUE TITLE
Password reset: email should include site name not "Kirby Panel"

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3343]
Currently the email reads

> You recently requested a password reset code for the Kirby Panel.

I think most users won't know what Kirby is. So making it `sitename Panel` or something like this would be better.

**Comment by lukasbestle** [comment]
Yep, sounds good. I think we should move the site title logic from here to a method in `Site` or `System`:

https://github.com/getkirby/kirby/blob/b6cad90/config/api/models/System.php#L55-L61

Then we can use the same logic for the email text for password reset and login codes (both are affected the same way).

**Comment by distantnative** [comment]
@lukasbestle sounds good, probably `System::site()` could work well? Do you want to get onto it since you're also more familiar with all the email templates for those auth methods?

**Comment by lukasbestle** [comment]
What about `System::siteName()`? I think `System::site()` is too unspecific.

**Comment by distantnative** [comment]
Then it should be `siteTitle` or even just `title`

**Comment by bastianallgeier** [comment]
I like `System::title()`

**Comment by bastianallgeier** [comment]
✅
