### ISSUE TITLE
[3.6.0] Xdebug has detected a possible infinite loop

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3347]
> Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames

When uploading an avatar in the Panel.
Likely due to `Filesystem` changes

**Comment by lukasbestle** [comment]
I can reproduce this. The error doesn't happen on upload directly, but once a user has an avatar. I could track the issue down to `Cms\FileVersion::__call()`.

**Comment by lukasbestle** [comment]
Ah, I was able to track down why: `FileFoundation` had an `exists()` method that was removed in `IsFile`. So [this line](https://github.com/getkirby/kirby/blob/2970a28/src/Cms/FileVersion.php#L40) now triggers a call to `__call()` again, which results in an infinite loop.

**Comment by lukasbestle** [comment]
✅
