### ISSUE TITLE
[3.6.0] Demokit: The section "pages" could not be loaded: Xdebug has detected a possible infinite loop

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3353]
On `site` screen/blueprint in the Panel of the demokit with the current `develop` branch

> The section "pages" could not be loaded: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames

```
api.js:21 
Object
code: 500
details: []
exception: "Error"
file: "App.php"
key: null
line: 617
message: "Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames"
route: "site/sections/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
status: "error"
```

**Comment by distantnative** [comment]
I could narrow it down to this

```yaml
image:
  query: page.cover
  ratio: 4/3
  cover: true
```

more specific the line `query: page.cover` in `site/blueprints/sections/home/examples.yml` of the Demokit.

**Comment by distantnative** [comment]
Digging deeper:
If we change `cover` in this https://github.com/getkirby/demokit/blob/main/site/models/agency.php#L10 and this https://github.com/getkirby/demokit/blob/main/site/models/blog-article.php#L7 line to something else, the error disappears (but of course the images are also then missing)

**Comment by distantnative** [comment]
Checked again, the demokit does work on `master` for me, not on `develop`.
@afbora @lukasbestle can anyone confirm this, so I can exclude a local setup issue at least?

**Comment by afbora** [comment]
I've tested demokit with develop branch and i couldn't login:

<img width="1680" alt="Ekran Resmi 2021-05-24 21 42 23" src="https://user-images.githubusercontent.com/3393422/119393072-29ca9700-bcd9-11eb-8105-107c5589290d.png">

**Comment by distantnative** [comment]
@afbora can you check the Network tab to see what the API response was that could not be parsed? (maybe reveals more about the problem and if it's the same or a different one)

**Comment by afbora** [comment]
@distantnative I deleted `demo@getkirby.com` account and installed Kirby with new user, login error gone.

But i can confirm the sections loading issue:

> The section "pages" could not be loaded: The JSON response from the API could not be parsed

I tracked down and source of issue is `keycdn` plugin's `file::url` component registration. You can take a closer look here.

> Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /htdocs/test/kirby/demokit/kirby/src/Filesystem/IsFile.php on line 123

https://github.com/getkirby/demokit/blob/main/site/plugins/keycdn/index.php#L66-L78

**Comment by distantnative** [comment]
Ah ok I think `isFile` also needs its own `type()` method

**Comment by bastianallgeier** [comment]
✅
