### ISSUE TITLE
Panel access with `nobody` role broken

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3354]
**Describe the bug**  
User with role `nobody` logging into the Panel (via normal login or password reset) leads to endless loading loop in Panel on `panel/undefined`.

Not sure if regression or never worked properly.

Tested with starterkit in sandbox.

**Version**
3.5.5

**Comment by afbora** [comment]
What should anyone who logs in to the panel with the `nobody` role be able to do? Is it just being able to navigate?

**Comment by lukasbestle** [comment]
We discussed it here internally: https://discord.com/channels/525634039965679616/525637437494657024/846397533139370004

**Comment by distantnative** [comment]
I think Bastian has already worked on making sure that this will be fixed with the Fiber PR.

**Comment by distantnative** [comment]
✅
