### ISSUE TITLE
Empty writer field removes list item immediately while typing

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#3365]
When I try to create a list note in a writer field, it starts to create the bullet point and then disappears. Seems to only happen when there's no existing text in the field. If I try to do it when there is text the bullet point shows up and sticks around.

**To Reproduce**  
1. Start with empty `writer` field
2. type `[dash][space]`

The list item is created and then disappears.

**Expected behavior**  
I expect a list item to be created and allow me to continue typing out the text for the first list item.

**Screenshots**  
Adam created a quick demo video and posted it in discord:
https://discord.com/channels/525634039965679616/525641819854471168/846803260777693218

**Kirby Version**  
3.5.5

**Comment by bastianallgeier** [comment]
✅
