### ISSUE TITLE
[3.5.6-rc.1] [Panel] I.a.$t is not a function

### ISSUE THREAD

**Issue by crydotsnake** [getkirby/kirby#3376]
**Describe the bug**  

https://user-images.githubusercontent.com/39345336/119807364-5fdb6700-bee3-11eb-98a3-51ff0203fcf5.mov

**To Reproduce**  
1. Click on a Page or on a note:
2. Double click on content inside the text editor

**Kirby Version**  
3.5.6-rc.1

**Console output**  
No Console Output

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by bastianallgeier** [comment]
Yikes. That's definitely a bug. @afbora could be related to the toolbar translations.

**Comment by crydotsnake** [comment]
Wish i could help fixing this..

VSCode told me there is an error in `kirby/src/Cms/LanguageRoutes.php` in line 44.

![Bildschirmfoto 2021-05-27 um 12 17 02](https://user-images.githubusercontent.com/39345336/119809478-7387cd00-bee5-11eb-82ab-a5ace27b141e.png)

Could the error come from there?

**Comment by bastianallgeier** [comment]
That's fine. The LanguageRoutes class is not the cause here.

**Comment by crydotsnake** [comment]
The bugs listed here are fixed, could not find them in version 3.5.6-rc.1 #3320 #3216 :)

I found that when I edit the caption on an image, the error I described in this issue does not appear.

**Comment by crydotsnake** [comment]
Also, when i create a new page, put some content in there, saved the page, go back to the panel, click on the new page that i have created, the error described here does not appear.

https://user-images.githubusercontent.com/39345336/119813506-a764f180-bee9-11eb-8acf-ded8b241cfd9.mov



The error reappears only with newly created notes.


https://user-images.githubusercontent.com/39345336/119813452-95834e80-bee9-11eb-92c7-85d34c142c47.mov

**Comment by bastianallgeier** [comment]
Thanks for your help. I'm sure we will be able to fix this quickly.

**Comment by crydotsnake** [comment]
> Thanks for your help. I'm sure we will be able to fix this quickly.

😊  🙌🏼

**Comment by afbora** [comment]
✅
