### ISSUE TITLE
$value is an uncountable object error in V::size validator when calling filterBy with `between`

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3382]
**Describe the bug**  

Example code that causes the error `$value is an uncountable object in kirby/src/Toolkit/V.php on line 478`.
```
<?php dump($page->children()->filterBy('height', 'between', [2, 7])); ?>
```
The error occurs because `$value` is a field object in this case.

**Kirby Version**  
Tested with 3.5.5 and 3.5.6-RC-1

**Comment by afbora** [comment]
✅
