### ISSUE TITLE
Inconsistency: `Str::isUrl()` and `V::url()`

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3386]
Why aren't we using `V::url()` in `Str::isUrl()` - or in general: why do we need two different methods which say to do the same but do it differently?

**Comment by bastianallgeier** [comment]
To be honest, I didn't even remember that we have a Str::isUrl method. I totally agree that they should behave the same.

**Comment by distantnative** [comment]
I think we only use it here: https://github.com/getkirby/kirby/blame/develop/src/Toolkit/Html.php#L308

So maybe we could change it to just return the result of `V::url()`. Mark it as deprecated. Throw warnings in 3.7, remove it in 3.8.

**Comment by distantnative** [comment]
✅
