### ISSUE TITLE
Escaping out of block drawers jumps to the top of the page

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#3387]
**Describe the bug**  
If I have a blocks field and have a block's drawer open and escape out of it (close it with the Escape key), I jump back to the top of the page. This is super annoying especially when I have many blocks, as I will have to scroll back down the page to find the part that I was editing / looking at. This seems to happen for most blocks, but in a quick test, the markdown block did not behave like that.

**Expected behavior**  
Have the page stay in place, when I escape out of a block's drawer. Just like it does when I use the OK button. 

**Kirby Version**  
3.5.5

**Desktop (please complete the following information):**  
 - OS: macOS 10.13.6
 - Browser: Chrome, possibly others

**Comment by afbora** [comment]
I can confirm the issue that ongoing since 3.5.0.

**Comment by afbora** [comment]
✅
