### ISSUE TITLE
Panel: Date / Time fields in nested structure don't save their updated content when I hit save

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#3388]
**Describe the bug**  
In a structure field that is in a block (not sure if this goes for all nested structure fields, i.e. also for those that are nested within another structure field), when I have a date field or a time field and type something into this type field and then hit save (cmd + S), as I typically do to save my changes, the structure field will be closed as expected, but the value jumps back to what it previously was. If I instead click away from the field first or click on the OK button this does not happen.

**To Reproduce**  
1. Create a block that contains a structure field that contains a date and/or time field.
2. Go to the panel to add such a block.
3. Edit the date / time field of the block by typing into the text field.
4. Hit cmd + S to save.
5. Check the fields value, it should be set to what it previously (before editing) was (most likely back to empty with a new block).

**Expected behavior**  
Hitting save should save the newly entered value, as it does within date fields in non-nested structure fields (I just double checked, this works for me).

**Kirby Version**  
3.5.5

**Desktop (please complete the following information):**  
 - OS: macOS 10.13.6
 - Browser: Chrome 90.0 (most recent one)

**Additional context**  
Possibly related to #3037.

**Comment by distantnative** [comment]
✅ Will be fixed in upcoming 3.6.2
