### ISSUE TITLE
[Cms] Implement custom Exceptions in Kirby\Cms

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#339]
- Convert all existing Exceptions to our custom Exceptions (see https://github.com/k-next/kirby/pull/71)
  - [x] Mixins
  - [x] Tags
  - [x] App.php
  - [x] AppCaches.php
  - [x] AppHooks.php
  - [x] AppOptions.php
  - [x] AppPlugins.php
  - [x] Avatar.php
  - [x] AvatarActions.php
  - [x] AvatarRules.php
  - [x] AvatarStore.php
  - [x] AvatarStoreDefault.php
  - [x] Base.php
  - [x] Blueprint.php
  - [x] BlueprintCollection.php
  - [x] BlueprintConverter.php
  - [x] BlueprintFieldsSection.php
  - [x] BlueprintFilesSection.php
  - [x] BlueprintObject.php
  - [x] BlueprintOptions.php
  - [x] BlueprintPagesSection.php
  - [x] BlueprintSection.php
  - [x] BlueprintTabs.php
  - [x] Children.php
  - [x] ChildrenFinder.php
  - [x] Collection.php
  - [x] Collections.php
  - [x] Component.php
  - [x] Config.php
  - [x] Content.php
  - [x] ContentField.php
  - [x] Email.php
  - [x] EmailTemplate.php
  - [x] Extend.php
  - [x] File.php
  - [x] FileActions.php
  - [x] FileBlueprint.php
  - [x] FileBlueprintOptions.php
  - [x] Filename.php
  - [x] FileRules.php
  - [x] Files.php
  - [x] FilesFinder.php
  - [x] FileStore.php
  - [x] FileStoreDefault.php
  - [x] Form.php
  - [x] HasChildren.php
  - [x] HasContent.php
  - [x] HasFiles.php
  - [x] HasModel.php
  - [x] HasSiblings.php
  - [x] HasSingleton.php
  - [x] HasStore.php
  - [x] HasTemplate.php
  - [x] HasThumbs.php
  - [x] HasUnknownProperties.php
  - [x] Hooks.php
  - [x] Ingredients.php
  - [x] Locale.php
  - [x] Locales.php
  - [x] Media.php
  - [x] Model.php
  - [x] Nest.php
  - [x] NestCollection.php
  - [x] NestObject.php
  - [x] Page.php
  - [x] PageActions.php
  - [x] PageBlueprint.php
  - [x] PageBlueprintOptions.php
  - [x] PageDraft.php
  - [x] PageRules.php
  - [x] Pages.php
  - [x] PagesFinder.php
  - [x] PageStore.php
  - [x] PageStoreDefault.php
  - [x] Pagination.php
  - [x] Panel.php
  - [x] Permissions.php
  - [x] Plugin.php
  - [x] Query.php
  - [x] Resource.php
  - [x] Resources.php
  - [x] Response.php
  - [x] Role.php
  - [x] Roles.php
  - [x] Roots.php
  - [x] Site.php
  - [x] SiteActions.php
  - [x] SiteBlueprint.php
  - [x] SiteBlueprintOptions.php
  - [x] SiteRules.php
  - [x] SiteStore.php
  - [x] SiteStoreDefault.php
  - [x] Snippet.php
  - [x] Store.php
  - [x] Structure.php
  - [x] StructureObject.php
  - [x] System.php
  - [x] Template.php
  - [x] Tempura.php
  - [x] Upload.php
  - [x] Url.php
  - [x] Urls.php
  - [x] User.php
  - [x] UserActions.php
  - [x] UserBlueprint.php
  - [x] UserBlueprintOptions.php
  - [x] UserRules.php
  - [x] Users.php
  - [x] UsersFinder.php
  - [x] UserStore.php
  - [x] UserStoreDefault.php

- [x] Convert all Exception tests to check for type and key code

**Comment by bastianallgeier** [comment]
✅
