### ISSUE TITLE
Plain json output of blocks field inside structure when pretty option set to true

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3395]
**Describe the bug**  
When using a blocks field inside a structure field and setting `pretty: true`, the output on the frontend is rendered as plain JSON. Works fine without this setting.

**To Reproduce**  
See example here: https://forum.getkirby.com/t/blocks-in-structures/22495/4

**Expected behavior**  
Should properly render blocks 

**Screenshots**  

**Kirby Version**  
3.5.5

**Comment by afbora** [comment]
This is same issue with #1308 and i guess unsolvable with `pretty: true` 🤷‍♂️

**Comment by afbora** [comment]
Here output of blocks field in structure field with `pretty` enabled:

````txt
----

References:

- 
  text: |
    [
    {
    "content": {
    "level": "h2",
    text": "123
    },
    "id": "f4bfa879-1a44-489b-a66b-34dc7b400847",
    "isHidden": false,
    type": "heading
    }
    ]
    
----
````

**Comment by afbora** [comment]
I guess we are having this issue because it converts the structure field data to YAML. If we convert the structure field from YAML to JSON, this issue will also be fixed. Related issue about that https://github.com/getkirby/kirby/issues/2876

**Comment by texnixe** [comment]
Yes, I thought so too, that saving the structure field as JSON will eliminate this problem.

**Comment by bastianallgeier** [comment]
I will close this in favour of #2876

**Comment by medienbaecker** [comment]
I don't have access to #2876 ("This issue has been moved to a repository you don't have access to.") and I've run into the exact same issue with my plugin.

Is there something I can do to fix this? I see the blocks field still has the same issue.

**Comment by medienbaecker** [comment]
@afbora Would you happen to know what's in the issue I don't have access to? I'd appreciate any information about this issue. Thanks!

**Comment by bastianallgeier** [comment]
@medienbaecker it went into our backlog because we did not find the time to work on that option. I think the main problem with switching the structure field to JSON is to get toStructure working afterwards with both - yaml and json.

**Comment by medienbaecker** [comment]
Thanks for the reply, @bastianallgeier. Makes sense, so it's currently not possible to fix.
