### ISSUE TITLE
[3.6.0] Refactor `Panel\Panel` class

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3404]
As discussed in https://github.com/getkirby/kirby/pull/3327#pullrequestreview-676808165:

- Move `page`, `file` and `user` methods to a new class (maybe `Cms\Finder`?)
- Convert `Panel` class to a singleton that takes the `$kirby` object

Should be done in Kirby 3.6.0 as the new foundation can then be built upon in future releases. If we only do this later, it would be a breaking change.

**Comment by bastianallgeier** [comment]
✅
