### ISSUE TITLE
[3.6.0] Unit tests for the remaining Fiber changes

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3406]
From the Codecov diff in #3327:

- [ ] `src/Panel/Panel.php` (at 97.82 %)
- [x] `config/areas/settings.php` (at 100 %)
- [ ] Verify that the whole Panel namespace has specific unit tests by only running these test classes (not the areas, which also cover the `Panel` namespace)

**Comment by afbora** [comment]
#3390 outdated?

**Comment by distantnative** [comment]
I think this one has the newer status/info, so I closed mine.

**Comment by afbora** [comment]
The license line in the `config/areas/settings.php`  file actually looks untestable becasue of need an actual license. So I guess it should be ignored: `@codeCoverageIgnore`

https://github.com/getkirby/kirby/blob/develop/config/areas/settings.php#L15

**Comment by bastianallgeier** [comment]
@afbora I agree. I was thinking if we could fake the license somehow. But this would mean that it's also fakeable in a real installation.

**Comment by bastianallgeier** [comment]
✅
