### ISSUE TITLE
Page/File write methods work differently between code branches

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#341]
Example: The default branch `File::update` method flushes the cache while the multilang one does not. Also applies to other methods (in different ways) and the `Page` classes.

**Comment by bastianallgeier** [comment]
I just fixed it for the file::update method. Do you have more details about the other methods?

**Comment by lukasbestle** [comment]
I just checked again. I thought there were at least two differences, but I found only one remaining now:

`FileAbstract::rename()` checks if `$name` is not empty, `File::rename()` (multilang) does not.
