### ISSUE TITLE
[3.6.0] Panel always redirecting root domain (doesn't work subfolder)

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3413]
**Describe the bug**  

When i enter  `http://localhost/test/kirby/3163/panel`, always redirecting to `http://localhost/panel/site` on `develop` branch.

**Screenshots**  

![image (12)](https://user-images.githubusercontent.com/3393422/121340637-801a1580-c928-11eb-8fb7-cc7fa9f886ea.png)

**Kirby Version**  

`develop` branch

**Comment by afbora** [comment]
I've updated priority as high because I can't test it 🔥

**Comment by bastianallgeier** [comment]
I fixed it directly on the develop branch. It works for me now in subfolders.

**Comment by afbora** [comment]
@bastianallgeier Thank you, works like a charm 🎉
