### ISSUE TITLE
Error uploading standard Garmin GPX tracks

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3433]
**Describe the bug**  
This error looks closely related to #3424 (the error returned by the API can be traced back to the new `Sane/Xml.php`, and this worked fine up to 3.5.3), but with GPX files; adding it as a separate issue to keep apart SVG-related validation errors and a potentially overzealous XML filter.

**To Reproduce**  
1. Go to a page with a Files section configured to accept `mime: text/xml, application/gpx, application/gpx+xml`
2. Upload a GPX file directly downloaded from a Garmin device (I can provide a test file if required, pls ping me)
3. See error

Garmin GPX files with recorded tracks start with a bunch of metadata:

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxx="http://www.garmin.com/xmlschemas/WaypointExtension/v1" xmlns:gpxtrx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" creator="Dakota 20" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 http://www8.garmin.com/xmlschemas/WaypointExtensionv1.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd"><metadata><link href="http://www.garmin.com"><text>Garmin International</text></link><time>2021-06-13T14:34:41Z</time></metadata><trk>
```

...after the `<trk>` tag follows the GPX track itself, consisting of further XML tags.

**Expected behavior**  
It should be possible to upload an unaltered GPX track file as exported directly from a Garmin device.

(...i.e. a GPX file with a standard metadata of `<metadata><link href="http://www.garmin.com"><text>Garmin International</text></link><time>2021-06-13T14:34:41Z</time></metadata>` should not fail with a "The URL is not allowed in attribute: href (line 1)" error ...or such test should be possible to override via config for setups deemed safe by the site admin.)

**Screenshots**  
![Screenshot from 2021-06-13 19-59-13](https://user-images.githubusercontent.com/6355217/121817458-e0d78400-cc81-11eb-9abb-fc183aeb8796.png)

**Kirby Version**  
3.5.6

**Desktop (please complete the following information):**  
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 89.0

**Comment by sebastiangreger** [comment]
Upon a further look into the core code: maybe this is not so much a bug, but an omission in the docs?

Above error is caused by the presence of an XML tag with a `href` attribute that points to a URL that has not been allowlisted (if-clauses in [L205 ff. of Sane/Xml.php](https://github.com/getkirby/kirby/blob/6b3cf988a6e773fd1d744045f3a0ab64b5ab129b/src/Sane/Xml.php#L205)). While this wholesale approach of denying any href attributes except a few hardcoded exceptions like localhost is understandable from a security point-of-view, embedded device links in Garmin files are probably not the only issues that may arise with this strict validation of XML files.

This boils down to the list of allowed domains in links being empty in the class (`public static $allowedDomains = [];`). Is there an easy way to configure this array to contain e.g. the garmin.com domain, or could that be arranged in a future version? That would solve this particular problem and would be a reasonable override at least for the use case at hand where only Garmin GPX files are used (not sure how versatile this solution may be with other XML sources).

**Update:** Configuration question solved https://forum.getkirby.com/t/possible-to-modify-a-static-property-of-kirby-core/22589 -- remains the question whether this is intentional and if this configuration trick could be documented somewhere?

**Comment by lukasbestle** [comment]
@sebastiangreger The default behavior is intended for highest possible security as explained by Bastian in https://github.com/getkirby/kirby/issues/3424#issuecomment-859354100.

We made the config properties in the `Sane` classes `public` for exactly the reason so you can override or extend them for your custom requirements. It's best to use `Kirby\Sane\Xml::$allowedDomains[] = '...'` syntax so you don't delete values that have been added from elsewhere.

You can also create a fully custom validator class for GPX files and register it in `Kirby\Sane\Sane::$handlers`.

Alternatively, if you don't want any validation of GPX files, you can add their MIME type to `Kirby\Toolkit\Mime::$types` so Kirby doesn't confuse the file for an XML file only based on its content.

Because we needed to get that security release out as soon as possible, there wasn't time for developer docs. I will see if I can create a guide page on this, might take a while though. :)

**Comment by bastianallgeier** [comment]
@lukasbestle I wonder if it makes sense to add such domains of popular formats to a default list. Do you see any risk there?

**Comment by lukasbestle** [comment]
Hm...

To be honest I feel like the true solution should be to validate and sanitize GPX files as GPX files, not as XML files. In this particular file format, the URLs are valid, but that IMO doesn't mean we should add them to the global allowlist. There are thousands of XML-based file formats, each with their unique requirements.

What we could do however is to set `$allowedDomains` to `true` (= any domain) for XML files in `DomHandler.php`. In the SVG and HTML handlers we could however be strict as before by overwriting that prop with the `[]` value.

**Comment by distantnative** [comment]
> To be honest I feel like the true solution should be to validate and sanitize GPX files as GPX files

How many other file formats like this exists  probably many, right? Would be hard to add support/a handler for each of them.

**Comment by lukasbestle** [comment]
We certainly cannot write handlers for every XML-based format in the Kirby core. There are thousands of them.

I'll think about it again and write a summary.

**Comment by lukasbestle** [comment]
✅
