### ISSUE TITLE
Plugin assets sourcemaps .map

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#3436]
**Describe the bug**  
Sourcemaps for assets - extension .map are not allowed. Only `css|gif|js|jpg|png|svg|webp|woff2|woff`

**To Reproduce**
Make .map file in plugin/assets

**Expected behavior**  
I am not sure this is disallowed for some security reason but it can be handy in debugging. And if plugin publishes .map files it's their choice.

**Kirby Version**  
All

**Proposed change**
Add map extension in here https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/config/routes.php#L62

**Comment by afbora** [comment]
Except for the `map` extension;

Some javascript plugins have `json` language files. I had this problem before with an editor plugin. Do you think it would be a problem if we add the `json` extension as well?

**Comment by iskrisis** [comment]
`json` for sure. Maybe there some other media that would make sense to add while this change is going to happen. 
`avif` is general upcoming one. Also `mjs` for JS module. It's not required to use .mjs for modules to work but i've seen most people to use it so it's obvious its module to be imported not normal js file.

To sum up
`map|json|avif|mjs`
are the ones comming to my mind.

**Comment by afbora** [comment]
New extensions come to mind when I think about it 🙂 

- less
- scss

@getkirby/kirby-staff Which ones should we include?

**Comment by bastianallgeier** [comment]
@afbora less and scss don't make sense to me. They need to be processed first and end as css files. The rest sounds good to me.

**Comment by bastianallgeier** [comment]
✅
