### ISSUE TITLE
Unexpected behaviour of home page url

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#344]
https://forum.getkirby.com/t/about-site-homepage-uri/2826

**Both of these urls gives status 200 ok:**

```
http://localhost/kirby (200)
http://localhost/kirby/home (200)
```

- When setting home as home page it's not expected that the old url to still exist.
- In SEO it's called duplicate content and can make results filtered or punished by search engines.
- In Kirby we are used to not have so much magic. Instead do it ourselves. In this case it means, if the page changes into a home page we redirect the old page url ourselves.
- I think it's rare that the home page changes.
- It feels like Kirby is leaking when adding urls that we did not ask for.

**Expected would be**

```
http://localhost/kirby (200)
http://localhost/kirby/home (404)
```

...or 301 if it's redirected.

**Comment by lukasbestle** [comment]
As I wrote in the forum, I prefer a 307 redirect. It will redirect to the right URL, but when changing the homepage, the redirection result won't be cached.

**Comment by bastianallgeier** [comment]
You are right, this page should be redirected. I think Lukas' idea with the 307 is great. So I implemented it that way.
