### ISSUE TITLE
Dir::make() emits E_WARNING, if a file with the same name exists

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#3442]
**Describe the bug**  
The `Kirby\Toolkit\Dir::make()` has some sanity checks for preventing errors, e.g. checking the directory already exists and throws an exception, if it cannot be created. But if a file with the same name exists, where the directory should be created, these checks don’t work with the current implementation.

**To Reproduce**  
1. Enable debugging mode
2. Create an example directory with a file in it: `media/example/testfile`
3. Call `Dir::make('media/example/testfile')`
4. The method will emit an `E_WARNING` level error (see <https://www.php.net/manual/en/function.mkdir.php#refsect1-function.mkdir-errors>)

**Expected behavior**  
Other checks are throwing an `Exception`, so I guess as directory creation also fails in this case, it should also throw an Exception instead of emitting an error.

**Kirby Version**  
3.5.6

**Console output**  
```
Warning: mkdir(): File exists
```

**Additional context**  
PHP 8.0.7 on some Linux server

**Comment by distantnative** [comment]
Adding a check like this should be sufficient, right?
```php
 if (is_file($dir) === true) {
    throw new Exception(sprintf('A file with the name "%s" already exists', $dir));
 }
```

**Comment by bastianallgeier** [comment]
✅

**Comment by fabianmichael** [comment]
@distantnative @bastianallgeier I think the check is fine, I just hope that this has no notable performance implications. But as the method is not used too often on regular page loads, it should be fina this way.

**Comment by lukasbestle** [comment]
@fabianmichael I think it will use PHP's stat cache, so the same path only needs to be queried once.

**Comment by bastianallgeier** [comment]
I'm also really not worried about performance issues in this case. The check will improve error handling a ton though. I think it's great.
