### ISSUE TITLE
Autoloading config files

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#345]
Fields, plugins, methods are autoloading except **config** files.

**My `site/config/` folder structure:**

![files](https://cloud.githubusercontent.com/assets/3393422/11834681/4b8a4672-a3d7-11e5-8a44-0c1db282f509.jpg)

And loading with:

````php
require_once('db.php');
require_once('languages.php');
require_once('users.php');
require_once('global.php');
require_once('email.php');
require_once('routes.php');
require_once('plugins.php');
require_once('options.php');
require_once('paypal.php');
require_once('hooks.php');
````

All files that in `/config/` folder could be load init?

Or manual like that:

````php
c::set('autoload', array('db', 'languages', 'users'));
````

**Comment by lukasbestle** [comment]
You mean `site/config/`, right?

Autoloading won't work, because the convention is that the other config files [are per host](http://getkirby.com/docs/advanced/options#multienvironment-setup). Since manual loading works, I think we should keep it that way.

**Comment by afbora** [comment]
thanks @lukasbestle yes, `site/config/` folder.

Hmm, i will try loading with `glob()`

May be @bastianallgeier hava an idea? :smile:

**Comment by bastianallgeier** [comment]
I'm against autoloading as well, to be honest. I think requiring them manually is not too hard to do and also more clear. Sometimes it's also important to have a different order than the one that is given by the filenames.
