### ISSUE TITLE
Finish work on new `Str::template()` implementation

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3456]
**Can only be done once the `3.5.7` branch is merged back into `develop` (avoids merge conflicts because of changes in the implementation).**

- Add deprecation warning for `$fallback` string, `$start` and `$end` ✅
- Add tests for callback feature as well as `OptionsApi` escaping inside queries ✅

Related PRs: https://github.com/getkirby/kirby/pull/3279 https://github.com/getkirby/kirby/pull/3454

**Comment by afbora** [comment]
✅
