### ISSUE TITLE
Str::contains() does not accept an empty needle

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#3459]
Possibly more of an improvement than a bug, but it would make sense in my eyes. If you use the `Str::contains()` method to query a field and it is empty, you get a PHP error with `strstr(): Empty needle`.

We use for example quite often:

```php
if ( Str::contains('Buzzword',$page->myfield()) ) {
  echo 'found';
}
```

But since `$page->myfield()` is for example a checkbox field it can also be empty, so the method fails. Therefore it would make sense if it would also work with an empty string.

**Comment by afbora** [comment]
- `Str::contains('Buzzword', '')` Have you tested like this? I couldn't reproduce the error? Which version Kirby and PHP do you use?
- There may be another bug in this method: needle and haystack cannot be null but our method accepts haystack as `null`.

**Comment by Werbschaft** [comment]
Yes I have tested. It's Kirby 3.5.1 with PHP 7.3.28. You think I should update Kirby to the newest version? Was there made a change in this method?

**Comment by afbora** [comment]
Actually there was no change but I just thought maybe you could use a so old version.

Ohh, i can reproduce the issue with PHP 7.3 (strpos method either) but works great for PHP 8.0.

I guess we need to empty control before call the method for empty string and null.

**Comment by Werbschaft** [comment]
Ah ok, yes we are currently not using PHP 8 yet

**Comment by lukasbestle** [comment]
@Werbschaft I'm a bit confused about your code example. Was it really intended to search for the field content in the string `Buzzword`? Or was your plan to check if your field contains the word `Buzzword`? In this case you need to swap the arguments (the second argument – the needle – being what you search in the haystack string).

**Comment by afbora** [comment]
From Discord to remind:

- `Str::contains` method `haystack` accepts null but method strpos/strstr does not.
> I think we should explicitly cast the haystack with (string)$haystack.
Edit: No, wait. If the haystack is empty, it cannot contain anything, right? In this case the return value should probably always be false. Except the needle is also empty. :thinking:

- Sending needle as empty string to `Str::contains` method gives an error in PHP 7.3, works in PHP 8.
> I think an empty needle should explicitly throw an InvalidArgumentException. The value true is theoretically correct but strange. But this would indeed make it a breaking change.

- When we send an empty string or null, should the response return `true` or `false`? (Returns `true` when sending empty string in PHP 8.)

**Comment by Werbschaft** [comment]
@lukasbestle @afbora I have a filter in the frontend that is based on a checkboxes field. This is stored comma separated. Therefore it seemed to make sense to me to simply check the string for my buzzword (needle) instead of a foreach logic or similar. But if the string is empty an error appears which seems illogical to me. If I now use the following everything works fine, but I consider the query in advance as a bit pointless (line 2-4) because this could also be covered by the function right?

```php
$needle = $partner->partner_filter();
if ( $needle->isEmpty() ) {
  $needle = 'NONEEDLE';
}
if ( Str::contains('Buzzword',$needle) ) {
  echo 'found';
}
```

Or do I not quite understand the meaning of the function here?

**Comment by lukasbestle** [comment]
@Werbschaft As I said, you need to swap the arguments. You are passing the `Buzzword` as the haystack, not as the needle. So if the field is empty, you are essentially checking if the `Buzzword` contains an empty string, which is not what you want.

Try this:

```php
Str::contains($page->myfield(), 'Buzzword')
```

**Comment by Werbschaft** [comment]
Ah damn, such a small error with such a big impact! The strange thing was that it worked despite all that. But after a few considerations I now understand why!

**Comment by Werbschaft** [comment]
So I think this can be closed!

**Comment by afbora** [comment]
I think error throwing should be avoided when `null` and empty string are sent.

**Comment by Werbschaft** [comment]
Would of course be better instead instead of throwing an error

**Comment by distantnative** [comment]
@afbora I am not sure if we should change that. It's quite consistent with other methods in the `Str` class, e.g. `before`, `after`, `position`, `startsWith`. All their `$needle` parameters are mandatory.

**Comment by afbora** [comment]
@distantnative But this is unexpected. Even though the PHP method doesn't accept null or empty text, it doesn't make much sense for us to accept it and throw an error. We will not change the parameters. If null or empty text param is sent, it will be enough to prevent it from throwing an error.

**Comment by distantnative** [comment]
Ah sorry, I forgot empty string... cause `null` shouldn't actually be allowed to pass with our parameter definition.

**Comment by lukasbestle** [comment]
I looked through all `Str` methods that use a `$needle` param:

1. `after`, `before`, `from`, `position`, `until`: Uses `mb_strpos()`; empty needle = "Warning: mb_strpos(): Empty delimiter"
2. `contains`: Uses `strpos` or `stripos`, which have inconsistent behavior with empty needles as discussed above
3. `endsWith`, `startsWith`: Explicit behavior to return `true` for empty needles

I think group 1 should really throw an explicit `InvalidArgumentException` (the position of an empty needle cannot be determined at all). Group 2 should IMO also throw an explicit exception – much better than inconsistent behavior that's hard to debug. I'm unsure about group 3 – a return value of `true` is weird. I mean yes, every string ends or starts with an empty string, but does this really make sense in practice?

**Comment by distantnative** [comment]
@lukasbestle I agree with your summary.

Regarding group 3, it makes sense and it doesn't, right? But maybe we leave this group as is for not causing a breaking chang e- it's not really wrong currently either. But group1 & 2 sounds like a good suggestion.

**Comment by lukasbestle** [comment]
We could also handle group 2 like group 3 (return `true`). Then it would at least be consistent, also with native PHP 8 behavior.

**Comment by bastianallgeier** [comment]
@distantnative @lukasbestle can one of you take care of it?

**Comment by bastianallgeier** [comment]
✅
