### ISSUE TITLE
[3.6.0] Panel view flickering/appearing when browser back button usage

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3469]
**Describe the bug**  

Panel view flickering/appearing when click back button after logout.

**To Reproduce**  
1. Go to panel
2. Login to panel
3. Logout from panel
4. Click browser back button
5. See issue

**Expected behavior**  

If user no permission, user should redirect without flicker or view the page that have no access.

**Screenshots**  

![flicker](https://user-images.githubusercontent.com/3393422/123954910-a411c980-d9b1-11eb-9b87-b12e719c8a6a.gif)

**Kirby Version**  

3.6.0 develop branch

**Console output**  
````
code: 403
details: []
exception: "Kirby\\Exception\\PermissionException"
file: "/test/kirby/develop/kirby/config/api/authentication.php"
key: "error.permission"
line: 26
message: "Unauthenticated"
route: "site/sections/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
status: "error"
__proto__: Object
````

**Comment by afbora** [comment]
It revealed another issues:

1. Renders page as JSON:

**To Reproduce**  
Steps to reproduce the behavior:
1. Go to panel
2. Login to panel
3. Click browser back button twice
4. Click browser forward button
5. See JSON output

![screen-capture-1102--localhost](https://user-images.githubusercontent.com/3393422/123959040-65cad900-d9b6-11eb-8e8c-134772d3b067.png)

2. Site title changed but view not when browser back (especially after logout)

**Comment by distantnative** [comment]
Right now, for me in Google Chrome the forward button gets disabled immediately after clicking the back button.

I would imagine this is due to the simplification @bastianallgeier made: https://github.com/getkirby/kirby/blob/develop/panel/src/config/fiber.js#L204

**Comment by afbora** [comment]
I didn't realize browser buttons because I always use mouse back/forward buttons 🙂

**Comment by distantnative** [comment]
Ok back/forward buttons now work, but yes seeing the JSOn responses.

I think on back/forward buttons we need to do a full reload.

**Comment by distantnative** [comment]
Just tried to debug it and test... but now back button works again, but instead the forward button gets disabled immediately.

**Comment by bastianallgeier** [comment]
I think it's a problem that we modify the history again in the reload method. We should have a way to reload the state without changing the history again.

**Comment by bastianallgeier** [comment]
I would like to close this in favour of a new issue. 

The flickering does no longer happen. But now the forward button does not work at all.
