### ISSUE TITLE
Multiline placeholder in writer field renders as single line

### ISSUE THREAD

**Issue by plagasul** [getkirby/kirby#3470]
**Describe the bug**  

Multiline placeholder string in the writer field declaration, renders as single line placeholder string.

**To Reproduce**  
1. Include a writer field in you yaml file as such (other fields for comparison only)

```
writer:
  type: writer
  placeholder: |
    blah
    blah
    blah
text:
  type: text
  placeholder: |
    blah 
    blah
    bleh          
textarea:
  type: textarea
  placeholder: |
    blah 
    blah
    bleh
```
2. Open panel page, and see that writer's placeholder is single line, like text field (which is single-line by default), unline textarea field.

**Expected behavior**  
A multiline yaml string placeholder  should show as multiline when rendering the field in the panel.

**Screenshots**  
![image](https://user-images.githubusercontent.com/13966673/124002824-8014af00-d9d6-11eb-8fde-439ede85134e.png)

**Kirby Version**  
Version
3.5.6

**Additional context**  
As explained in [this forum post.](https://forum.getkirby.com/t/multi-line-placeholder-in-writer/22722/2)

**Comment by bastianallgeier** [comment]
✅
