### ISSUE TITLE
Date field error in Kirby 3.5.7-rc.1

### ISSUE THREAD

**Issue by foxacid** [getkirby/kirby#3471]
**Describe the bug**  
When focusing on a date field in Kirby 3.5.7-rc.1 it turns into error message `this.$el.querySelector(...) is null`. In 3.5.6 all works OK.

**Platform**  
macOS, FF 89.0.2

https://user-images.githubusercontent.com/12812201/124032816-5d47c200-d9f9-11eb-8fb9-33a999f235ed.mov

**Comment by afbora** [comment]
Thanks for report 🙏 This is known issue and fixed on #3467
