### ISSUE TITLE
[3.5.7-rc.1] Date field error

### ISSUE THREAD

**Issue by crisgfx** [getkirby/kirby#3473]
**Describe the bug**  
The date field throws an error in 3.5.7-rc.1 (tested with a fresh starter-kit)
`this.$el.querySelector(...) is null`

**To Reproduce**  
1. add a date field to the blueprint
2. in panel try to change the date
3. Error `this.$el.querySelector(...) is null` is shown

<img width="512" alt="datefield-error" src="https://user-images.githubusercontent.com/16305374/124101303-800cc180-da5f-11eb-8ab1-0c31e54d2706.png">

**Comment by afbora** [comment]
Thanks for report 🙏 This is known issue and fixed on #3467

**Comment by crisgfx** [comment]
Damn, I should have checked better before... Sorry for the duplicate! ✌🏼

**Comment by CrisGraphics** [comment]
Damn, I should have checked better before... Sorry for the duplicate! ✌🏼

**Comment by afbora** [comment]
Don't worry! Since the details of the error are not the same, it is normal that you cannot find it 👍
