### ISSUE TITLE
`tc()` helper pretends to accept array as first argument, but internal I18n::translateCount() only accepts string

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3474]
**Describe the bug**  
According to the [documentation](https://getkirby.com/docs/reference/templates/helpers/tc), the first argument can be either a string or an array, but the internally used `I18n::translateCount()` method only accepts a string as first argument. So issue should be fixed in the doc block/parameter typing of the `tc()` helper.

**Kirby Version**  
3.5.6+

**Additional context**  
https://forum.getkirby.com/t/question-regarding-the-use-of-tc-helper/22739

**Comment by afbora** [comment]
✅
