### ISSUE TITLE
[Panel] PageSection publication error: list which errors

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#348]
Would be great to also see here already what errors exist:
<img width="846" alt="screen shot 2018-03-31 at 14 39 44" src="https://user-images.githubusercontent.com/3788865/38163257-755fdfa4-34f1-11e8-97c2-a06f9a7ee46a.png">

- [x] Implement error details in page view
- [x] Implement error details in site view
- [x] Implement error details in user view
- [x] Implement error details in file view

**Comment by bastianallgeier** [comment]
✅ 

![bildschirmfoto 2018-03-31 um 18 24 13](https://user-images.githubusercontent.com/24532/38165243-c32b4240-3510-11e8-8c40-4b610ba4c062.png)

**Comment by distantnative** [comment]
Not completely – still not shown outside of PageView ;)

**Comment by bastianallgeier** [comment]
Hm, difficult. The other views (site, file, user) don't really have a publishing action, so I'm not sure if we should show it whenever the form is saved. That's somehow inconsistent.

**Comment by distantnative** [comment]
No, but within `PageSection.vue::sort` we should

**Comment by bastianallgeier** [comment]
AHHHHH!!! Right :)

**Comment by bastianallgeier** [comment]
✅ I think I really got it this time.

**Comment by distantnative** [comment]
Confirmed 👍
