### ISSUE TITLE
3.6 - plugins compatibility

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3485]
Let's collect a list of plugins we know 3.6 will break (and where we could send PRs or give tips how to update):

### Done
- [x] **[Trevor](https://github.com/rasteiner/k3-trevor-view)**
https://github.com/rasteiner/k3-trevor-view/pull/16
- [x] **[Modules](https://github.com/medienbaecker/kirby-modules)**
https://github.com/medienbaecker/kirby-modules/releases/tag/2.2.1
- [x] **[Versions](https://github.com/lukasbestle/kirby-versions)**
https://github.com/lukasbestle/kirby-versions/pull/6
- [x] **[Pagetable](https://github.com/sylvainjule/kirby-pagetable)**
https://github.com/sylvainjule/kirby-pagetable/pull/69
- [x] **[Komments](https://github.com/mauricerenck/komments)**
Custom Panel view
`feature/kirby-3-6` branch is compatible with 3.6: https://github.com/mauricerenck/komments/tree/feature/kirby-3-6
- [x] **[Commentions](https://github.com/sebastiangreger/kirby3-commentions)**
`develop` branch is compatible with 3.6: https://github.com/sebastiangreger/kirby3-commentions/tree/develop
- [x] **[Navigation](https://github.com/chrisbeluga/kirby-navigation)**
https://github.com/chrisbeluga/kirby-navigation/releases/tag/2.1.0
- [x] **[Pages Display Section](https://github.com/rasteiner/k3-pagesdisplay-section)**
https://github.com/rasteiner/k3-pagesdisplay-section/issues/9
- [x] **[Files Display Section](https://github.com/texnixe/k3-filesdisplay-section)**
https://github.com/texnixe/k3-filesdisplay-section/pull/4
- [x] **[Backups](https://github.com/sylvainjule/kirby-backups)**
https://github.com/sylvainjule/kirby-backups/pull/4
- [x] **[Image Clip](https://github.com/mullema/k3-image-clip)**
`develop` branch: https://github.com/mullema/k3-image-clip/tree/develop
- [x] **[Kirby Uniform](https://github.com/mzur/kirby-uniform)**
https://github.com/mzur/kirby-uniform/issues/219
- [x] **[Help section](https://github.com/amteich/kirby-helpsection)**
https://github.com/amteich/kirby-helpsection/releases/tag/2.0.0
- [x] **[Reporter](https://github.com/gearsdigital/kirby-reporter/)**
https://github.com/gearsdigital/kirby-reporter/pull/32
- [x] **[Kirby 3 Mailjet](https://github.com/bnomei/kirby3-mailjet)**
https://github.com/bnomei/kirby3-mailjet/pull/8
- [x] **[Kirby Podcaster](https://github.com/mauricerenck/kirby-podcaster)**
- [x] **[Kirby autopublish](https://github.com/bvdputte/kirby-autopublish)**
https://github.com/bvdputte/kirby-autopublish/issues/8
- [x] **[Custom Add Fields](https://github.com/steirico/kirby-plugin-custom-add-fields)**
2.0.0 is compatible with 3.6: https://github.com/steirico/kirby-plugin-custom-add-fields/releases/tag/v2.0.0
- [x] **[Bouncer](https://github.com/sylvainjule/kirby-bouncer)**
Hooks into `vue-router` and store modules heavily
- [x] **[Retour](https://github.com/distantnative/retour-for-kirby)**
Beta with 3.6 support: https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1
- [x] **[Markdown Field](https://github.com/sylvainjule/kirby-markdown-field)**
  sylvainjule/kirby-markdown-field#116 The next branch is compatible with 3.6 but still under development

Please feel free to edit this post, so we have the full list always on top.

**Comment by MaluNoPeleke** [comment]
[Komments](https://github.com/mauricerenck/komments) and [Commentions](https://github.com/sebastiangreger/kirby3-commentions) need to be added as well.

**Comment by lukasbestle** [comment]
Thanks, I added them to the list above.

**Comment by mynameisfreedom** [comment]
[Image Clip](https://github.com/mullema/k3-image-clip) also.

**Comment by afbora** [comment]
@mynameisfreedom Thanks, added to list.

**Comment by MaluNoPeleke** [comment]
These two as well:

https://github.com/rasteiner/k3-pagesdisplay-section/issues/9
https://github.com/texnixe/k3-filesdisplay-section/issues/3

**Comment by afbora** [comment]
@MaluNoPeleke Added to list.

**Comment by MaluNoPeleke** [comment]
> These two as well:
> 
> [rasteiner/k3-pagesdisplay-section#9](https://github.com/rasteiner/k3-pagesdisplay-section/issues/9)
> [texnixe/k3-filesdisplay-section#3](https://github.com/texnixe/k3-filesdisplay-section/issues/3)

These have been fixed and Commentions and Komments have already updated branches for 3.6 (but not released yet officially).

**Comment by afbora** [comment]
I've updated the list.

**Comment by bnomei** [comment]
my mailjet plugin as some views as well but can be considered low priority (if any):
https://github.com/bnomei/kirby3-mailjet/tree/master/src/components

**Comment by afbora** [comment]
Added to list.

**Comment by mauricerenck** [comment]
I am still working on this: https://github.com/mauricerenck/kirby-podcaster
- The base functionality is working (feed and panel setups). 
- The stats view currently doesn't show data

**Comment by PaulMorel** [comment]
As someone who has just released [a custom panel view plugin](https://github.com/PaulMorel/kirby3-fathom-analytics), is it going to break in 3.6? I'm assuming this is related to the new Fiber system?

Edit: Maybe I should just go test it myself  😅

**Comment by afbora** [comment]
@PaulMorel Unfortunately yes: https://getkirby.com/releases/3.6/breaking-changes#panel__custom-panel-views

**Comment by PaulMorel** [comment]
@afbora Is it feasible to have my plugin compatible with both 3.6 and older versions? Or is this a headache waiting to happen?

**Comment by afbora** [comment]
@PaulMorel You can use releasement. For example: v0 is `<=3.5`, v1 is `>=3.6`

**Comment by lukasbestle** [comment]
@PaulMorel I have just worked on an update for my Versions plugin, which also uses a view.

You *can* actually both register the view in the frontend for older versions and register an area in the backend for 3.6+. 3.6 will ignore the view defined in the frontend and 3.5 and previous versions will ignore the area. Unless your code runs into other breaking changes, you can make an update to your plugin that supports both scenarios.

**Comment by mullema** [comment]
image-clip (develop branch) works now with beta2

**Comment by afbora** [comment]
@mullema Great! I've updated the list.

**Comment by Daandelange** [comment]
Report : [SimpleStats](https://github.com/Daandelange/kirby3-simplestats/tree/kirby-3.6) works with the new develop 3.6 branch. :)

Note: I came trough an undocumented (3.6) breaking change (namespace issue) : `is_a($page, 'Page')` returns `false` after updating from `3.5.?` to `3.6-beta-3`.  
Fix: `is_a($page, 'Kirby\Cms\Page')`

**Comment by afbora** [comment]
@Daandelange I've tested `is_a($page, 'Page')` returns `true` for homepage on 3.6.0-beta.3. Can you share more detailed information please?

**Comment by ralfgoeke** [comment]
I just stumbled over an incompatibility in Uniform Plugin: https://github.com/mzur/kirby-uniform/issues/219

**Comment by afbora** [comment]
@ralfgoeke Thanks, I've added to list.

**Comment by Daandelange** [comment]
@afbora [My use case](https://github.com/Daandelange/kirby3-simplestats/commit/00cc567d6e7948939c12c457f8a8adc3469d4830) is in a `route::after` hook, while visiting a Page object.
Same result printing it in a page template. Using php 7.4.2 locally on os x.
```php
// use Kirby\Cms\Page; <-- Result with namespace declaration : bool(true) bool(true) bool(false) bool(true)
App::plugin('daandelange/simplestats', [
    'hooks' => [
        'route:after' => function ($result) {
            var_dump( is_a($result, 'Kirby\Cms\Page'), $result instanceof Kirby\Cms\Page, is_a($result, 'Page'), $result instanceof Page, $result);
            die();
        }
    ]
]);
```
Result: `bool(true) bool(true) bool(false) bool(false) object(Kirby\Cms\Page)#584 (15) [...]`

**Comment by mzur** [comment]
Is there a way to detect the Kirby version in a plugin? As Kirby 3.6 is a "minor" release, I'd like to keep compatibility for all 3.x versions. My plugin will break with the new `Str::template` arguments and all I would need to do is use different arguments for <=3.5 than >=3.6.

**Comment by afbora** [comment]
@mzur You can use `Kirby::version()` to get installed version.

**Comment by mzur** [comment]
Thanks. You can move Uniform to "Done" now.

**Comment by seehat** [comment]
The Helpsection Plugin now works fundamentally. 
https://github.com/amteich/kirby-helpsection/releases/tag/2.0.0

I would like to integrate routing for the subpages. Can anybody show me how or create a pullrequest? 

Can somebody help me with integrating this Babel Plugin to make syntax highlighting work fully again: https://github.com/mAAdhaTTah/babel-plugin-prismjs?

**Comment by steirico** [comment]
Hi

there is work in progress for the `Custom Add Fields Plugin` at https://github.com/steirico/kirby-plugin-custom-add-fields/tree/feature/kirby-3.6

**Comment by MaluNoPeleke** [comment]
Here is another one WIP that could need some support: https://github.com/flokosiol/kirby-translations/tree/kirby3

**Comment by PaulMorel** [comment]
> 
> 
> @PaulMorel I have just worked on an update for my Versions plugin, which also uses a view.
> 
> You _can_ actually both register the view in the frontend for older versions and register an area in the backend for 3.6+. 3.6 will ignore the view defined in the frontend and 3.5 and previous versions will ignore the area. Unless your code runs into other breaking changes, you can make an update to your plugin that supports both scenarios.

Thanks @lukasbestle, That's exactly what I ended up doing. Registering the area for 3.6+ worked fine and I had very little changes to do for it to still work in 3.5.

**Comment by MaluNoPeleke** [comment]
Can you pease add this plugin to the list?

https://github.com/bvdputte/kirby-autopublish/issues/8

**Comment by afbora** [comment]
@MaluNoPeleke I've added to the list.

**Comment by sebastiangreger** [comment]
Markdown Field: https://github.com/sylvainjule/kirby-markdown-field/issues/116 (issue refers to the `next` branch in active development; haven't tested the current stable version with 3.6, yet)

**Comment by sebastiangreger** [comment]
Just for completeness, updating the info in the original post on top: Commentions is now 3.6-compatible in newly released versions on both the stable branch ([v1.0.5](https://github.com/sebastiangreger/kirby3-commentions/releases/tag/v1.0.5)) and the WIP v2.0 branch ([v2.0-beta.4](https://github.com/sebastiangreger/kirby3-commentions/releases/tag/v2.0-beta.4)).

**Comment by mauricerenck** [comment]
Komments latest release (and main branch) is now 3.6 compatible and 3.5 "backward" compatible.

**Comment by mauricerenck** [comment]
Kirby Podcaster now works with 3.6

**Comment by MaluNoPeleke** [comment]
> Can you pease add this plugin to the list?
> 
> [bvdputte/kirby-autopublish#8](https://github.com/bvdputte/kirby-autopublish/issues/8)

Can be removed as I cannot reproduce anymore after latest plugin update

**Comment by thathoff** [comment]
Trying to migrate my [OAuth Plugin](https://github.com/thathoff/kirby-oauth) to 3.6. I hooked into the Vue Router to prevent a redirect to the install view so you can still login with a valid OAuth user even when there is no user created yet.

```js
// always route back to panel home when trying to access installation view
if (panel?.app?.$route?.path === "/installation") {
  panel.app.$go("/");
}

// prevent routing to the installation view (e.g. like the login view does)
panel?.app?.$router?.beforeEach((to, _, next) => {
  if (to.path !== "/installation") next();
});
```
https://github.com/thathoff/kirby-oauth/blob/kirby-3.6/src/index.js#L12

Any hints on how to accomplish this with Kirby 3.6?

**Comment by MaluNoPeleke** [comment]
> Komments latest release (and main branch) is now 3.6 compatible and 3.5 "backward" compatible.

I always get a error 500 after installing it on Kirby 3.6 RC.3 without any additional information (debugging turned on).

**Comment by mauricerenck** [comment]
> > Komments latest release (and main branch) is now 3.6 compatible and 3.5 "backward" compatible.
> 
> I always get a error 500 after installing it on Kirby 3.6 RC.3 without any additional information (debugging turned on).

Would you be so nice and create an issue in the komments github repo? This is more in my focus, I will have a look at it. Maybe with some additional info about your setup. That would be nice.

**Comment by MaluNoPeleke** [comment]
Done: https://github.com/mauricerenck/komments/issues/24

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-pagetable I've merged the 3.6 support into the latest release

I'm looking into the bouncer plugin next week!

**Comment by MaluNoPeleke** [comment]
Can you add [this plugin](https://github.com/mciszczon/kirby-editor-lite-youtube-embed) and maybe offer support to make it compatible with Kirby 3.6 again?

**Comment by texnixe** [comment]
@MaluNoPeleke This plugin has nothing to do with the changes introduced in 3.6, it wasn't compatible with 3.5 either. Let's not mix things up.

**Comment by MaluNoPeleke** [comment]
Oh, sorry, sure.
