### ISSUE TITLE
[3.6.0] Custom Panel areas disabled in menu

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3487]
If no access has been specified, the access to custom Panel areas should be granted:
https://github.com/getkirby/kirby/blob/develop/src/Panel/View.php#L325

(maybe need different handling between native and custom areas?)

**Comment by distantnative** [comment]
Actually, even for native areas the default should be `true`

> You don't have to set all permissions for each role. Each permission is set to true by default, if not specified otherwise.

https://getkirby.com/docs/guide/users/permissions

**Comment by bastianallgeier** [comment]
✅
