### ISSUE TITLE
sortBy removes sorting number from folders when sorting by "sort" field

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#349]
https://forum.getkirby.com/t/subpages-change-to-hidden-when-accessing-a-page/2878

**Comment by lukasbestle** [comment]
This issue only comes up when sorting by the `sort` field, which will call `Page::sort()`. This method will then "sort" the page and without a sorting number passed as argument will *remove* the sorting number.

The following code in the Toolkit class `Collection` beginning at line 326 can be used to "fix" this, but unfortunately this code will bypass custom model functions, so it can't be used as a fix for this:

```php
${"param_$i"} = array();
foreach($array as $index => $row) {
  if(is_array($row)) {
    $value = str::lower($row[$param]);
  } else if(is_a($row, 'Page')) {
    $value = str::lower($row->content()->$param());
  } else if(is_a($row, 'File')) {
    $value = str::lower($row->meta()->$param());
  } else {
    $value = str::lower($row->$param());
  }
  
  ${"param_$i"}[$index] = $value;
}
```

I think there is nothing Kirby can do to fix this. If you have this issue: Don't use the `sort` field for sorting.

**Comment by distantnative** [comment]
Fixing indeed seems hard to do. But I'm wondering if we could prevent damages on the side of the `sort()` method. Instead of just removing the number if no value for the parameter `$num` is passed, we could change it to not do anything if nothing is passed. And to remove the number (make a page invisible) something would need to be passed explicitly. What do you think?

**Comment by lukasbestle** [comment]
Hm...
This would introduce a function call that doesn't do anything. I think that would be quite WordPress-like.

**Comment by distantnative** [comment]
Or just returning `$num`? At the moment we have calls to the same function that actually intend/expect different outcomes. One which wants to get the sort number returned, one that sorts the page to num/position `null` – doesn't sound ideal to me either.

**Comment by lukasbestle** [comment]
Yes, that's a great idea! Basically an alias for `$page->num()`. Sounds good.

**Comment by lukasbestle** [comment]
But the question is: What should be passed to remove the sorting number? `null`? Or `false`? Until now, both worked and in the future only one of them will.

**Comment by distantnative** [comment]
As I just realized, we already have `$page->hide()` as well. So if Kirby is at the moment calling `$page->sort()` without passing a parameter to hide a page, we should change this anyways to rather use `$page->hide()`. And then I would change the `sort` method to:

```php
  public function sort($num = null) {
    if(!$num) return $this->num();
    if($num === $this->num()) return true;

   …

  }
```

**Comment by lukasbestle** [comment]
Yes, I realized that as well and deleted my comment.

Your solution looks good. The current implementation that doesn't check the param is a bug and should be fixed anyway.

**Comment by distantnative** [comment]
Added a PR. If it gets implemented, we really need to check before any release that the core and the panel never call `page::sort` without any parameters to hide a page.

**Comment by bastianallgeier** [comment]
This is no implemented.
