### ISSUE TITLE
[3.6.0] Dropup falsely triggered, menu hidden

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3491]
When the browser window is very narrow (e.g. developer tools are open), drop gets triggered - which makes it worse than normal dropdown partially hidden.

<img width="511" alt="Screen Shot 2021-07-05 at 16 25 02" src="https://user-images.githubusercontent.com/3788865/124486296-bd4db800-ddad-11eb-88d8-14616f4e1982.png">

**Comment by afbora** [comment]
As a solution; Then if the dropdown content is greater than the height of the window or so close, the dropup will not enabled.

**Comment by distantnative** [comment]
Probably rather: (dropdown content height + offset top of dropdown) > window height

**Comment by afbora** [comment]
> Probably rather: (dropdown content height + offset top of dropdown) > window height

Actually we are using already this calculation to show correctly wherever the dropdown is on the page.
https://github.com/getkirby/kirby/blob/master/panel/src/components/Navigation/DropdownContent.vue#L147-L148

I have a solution for this issue. I'll create a PR.

**Comment by distantnative** [comment]
Ah true. We would need:
"AND dropdown height < scroll top"

**Comment by afbora** [comment]
@distantnative Currently dropup feature broken with `.k-panel-view` changed to static position from absolute in #3492 🙂

**Comment by distantnative** [comment]
Oh sorry that I broke it. Why doesn't it work with a static positioned view?

**Comment by afbora** [comment]
`.k-panel-view` was working on getting visible window height. Currently returns whole page height not visible. Maybe this could be my mistake in implementation. I've changed the `dropup` implementation on getting visible window height.

**Comment by bastianallgeier** [comment]
✅
