### ISSUE TITLE
[3.6.0] add a few more icons

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3493]
- [ ] export (https://kirby.nolt.io/231)

Maybe we should collect some urgent ideas on Discord. We shouldn't add too many more but another 5-10 crucial ones maybe?

**Comment by bastianallgeier** [comment]
- [x] mobile/phone, 
- [x] tablet
- [x] desktop/screen/display
- [x] analytics / trend graph
- [ ] money / coin
- [x] sitemap
- [x] music / sound / audio
- [x] paypal
- [x] grid/layout icons
- [ ] ticket
- [x] weather
- [x] basket / cart
- [x] layout grids
- [x] play
- [x] info
- [x] faq - question / answers
- [x] flag
- [ ] announcement / loud speaker
- [ ] pdf
- [x] checklist
- [ ] slideshow
- [x] crop
- [x] color picker
- [x] table
- [ ] euro sign or dollar
- [x] tiktok logo
- [x] about foods/restaurant
- [x] empty star & heart
- [x] headings (h1-h6)
- [x] alignments (left, right, justify, etc..)
- [x] print
- [x] images (layered)
- [x] server (db)
- [ ] truck
- [x] qr code
- [x] shuffle
- [x] sorting (global, alpha-asc, alpha-desc, numeric-asc, numeric-desc, etc..)
- [x] filter
- [x] photo
- [ ] chopsticks
- [x] location pin / map-marker / location marker

**Comment by bastianallgeier** [comment]
✅
