### ISSUE TITLE
Panel: missing padding on date field

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#35]
Reported by @texnixe

**Comment by bastianallgeier** [comment]
@texnixe which browser? IMHO It looks good in Chrome

![bildschirmfoto 2017-10-31 um 16 50 06](https://user-images.githubusercontent.com/24532/32233804-92ab1176-be5b-11e7-83e0-158366e3cf26.png)

**Comment by texnixe** [comment]
Strange, looks ok now. Don't know what was wrong yesterday then (I swear I didn't have any drinks…:innocent:)

**Comment by bastianallgeier** [comment]
🍻
