### ISSUE TITLE
[Cms] changeStatus: "The file "/default.txt" does not exist"

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#350]
When changing the status:
- Listed > Draft
- Listed > Unlisted
- Unlisted > Draft 

the following error appears:
<img width="437" alt="screen shot 2018-03-31 at 14 50 30" src="https://user-images.githubusercontent.com/3788865/38164137-0659d240-3500-11e8-95ac-fbc7acd94b15.png">

I have narrowed it down to e.g. `PageActions::changeStatusToDraft()` where the returned `$page` object seems to be not complete. Seems like cloning the page does not work properly and the returned Page object is missing data, e.g. `diruri`.

@bastianallgeier Maybe for it makes click, what is going wrong when cloning the object.

**Comment by bastianallgeier** [comment]
Phew, it took a while but I fixed it! The children of the parent page are cached and when the tags query tries to load tags from children it hits the non-existing draft and tries to read the content file. That was messed up.

**Comment by distantnative** [comment]
Wow ! <3 And as always: once you hear what the problem was, it's pretty logical, but I was biting my nails off trying to find the root of the bug as well

**Comment by bastianallgeier** [comment]
I think it took me around 2hrs to find it. So nothing to feel bad about :)

**Comment by bastianallgeier** [comment]
We now have a new $page->purge() method, which removes such internal caches. Let's try to not forget it for the next issue like this :)
