### ISSUE TITLE
Output of language variables plain text in the resulted HTML

### ISSUE THREAD

**Issue by jlnostr** [getkirby/kirby#350]
If you setup Kirby to handle multiple languages and add the `languages` property to your config file like the code block below, the content of the `../site/languages/{language-code}.php` is inserted at the start of the "rendered" html file.

**Configuration**
```php
c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'English',
    'default' => true,
    'locale'  => 'en_US',
    'url'     => '/',
  ),
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'locale'  => 'de_DE',
    'url'     => '/de',
  ),
));
```

**Sample file** (path: `../site/languages/en.php`)
```
l::set('imprint', 'Imprint');
l::set('privacy-policy', 'Privacy policy');
```

**Output HTML**
```html
l::set('imprint', 'Imprint');
l::set('privacy-policy', 'Privacy policy');<!DOCTYPE html>
<html lang="en">
…
</html>`
```

You can reproduce the issue with the starterkit, simply perform the following steps:
1. Download the starterkit
2. Create the folder `../site/languages` and add a file called `en.php` with *any* content to it.
3. Copy & paste the config setting I mentioned earlier to the `config.php`
4. Open up the browser and you'll see the text of `en.php`

**Comment by texnixe** [comment]
Did you forget to wrap your code in opening and closing php tags?
```php
<?php
l::set('imprint', 'Imprint');
l::set('privacy-policy', 'Privacy policy');
?>
```

**Comment by jlnostr** [comment]
Well, that was it. I could've figured it out by myself. Maybe it should be added to the [`l::get()` help page](http://getkirby.com/docs/cheatsheet/helpers/l)

Thank you and happy holidays! :christmas_tree:
