### ISSUE TITLE
Bug: list items contain <p> tags in writer field

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#3506]
This issue was resolved in the _List_ block but is not resolved in the _Writer_ field.

The Problem:
List items within a writer field contain paragraph…
```
<ul>
   <li><p>…</p></li>
   <li><p>…</p></li>
   <li><p>…</p></li>
</ul>
```

Expected:
```
<ul>
   <li>…</li>
   <li>…</li>
   <li>…</li>
</ul>
```

**Comment by afbora** [comment]
This is a ProseMirror issue. If ProseMirror develops a solution for this issue, we will move it to Kirby. But for now it is unsolvable.
