### ISSUE TITLE
`options: status: false` not working yet

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#351]
I can change the blogs publishing state. (Alpha 7)

From `blog.yml`:
```yml
options:
  status: false
```

**Comment by bastianallgeier** [comment]
Are you logged in as the admin user?

**Comment by bastianallgeier** [comment]
I double-checked and this really just happens with the admin, which is intended. The admin can always do anything.

**Comment by wottpal** [comment]
> The admin can always do anything.

Okay I didn't know about that because thats not the case in Kirby 2, right? Changing the pages status is imo often not related to permissions. For example you want to hide the *Imprint* from the main-nav *by design*, then `status: false` prevents unexperienced users from thinking "Oh no the imprint should not be invisible" and changing it to visible.

Also: If I have single-person clients I of course give them an admin account and that's in almost every case their only account. 

I would love to get these power back, because less options for the user doesn't always mean less control but better control.

**Comment by distantnative** [comment]
All your examples really cry out for creating another non-admin account anyways. The admin account should in my view always only be used by someone with the proper knowledge/understanding.

**Comment by wottpal** [comment]
Good to know! I will try to change my habits ;)
