### ISSUE TITLE
PHP `t()` helper inconsistent with JS `$t()`

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3514]
The JS helper returns the key if the i18n string cannot be found, the PHP helper just null.

**Comment by afbora** [comment]
Which one is correct? Returning `null` or key?

**Comment by bastianallgeier** [comment]
I tend to prefer returning null. But we have to be careful in both ways that we don't break something important. At least in the backend there are parts that depend on t() returning null.

**Comment by afbora** [comment]
If we'll go for `null`, php `js()` helper doesn't affected but vue i18n `$t()` helper will affected. We can add new fallback param to `$t()` helper.

**Comment by distantnative** [comment]
✅
