### ISSUE TITLE
Users sort order

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#3515]
**Describe the bug**  
On the accounts page in the panel, users are sorted alphabetically by their `username`. Using the previous/next user navigation on a single user view doesn't reflect this sorting but seems to be based on the user's `id`. This makes browsing users very confusing.

**Expected behavior**  
The previous/next navigation and the account overview should follow the same sorting rules.

**Kirby Version**  
3.5.7

**Comment by afbora** [comment]
This issue already fixed in 3.6. You can try on 3.6.0 Alpha.1 ✅
