### ISSUE TITLE
`panel.favicon` option

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3516]
See https://github.com/getkirby/getkirby.com/pull/1418#issuecomment-881358264.

**Idea:**

```php
'panel.favicon' => [
  'apple-touch-icon' => 'assets/apple-touch-icon.png',
  'icon'             => ['url' => 'assets/favicon.svg', 'type' => 'image/svg+xml'],
  'alternate icon'   => ['url' => 'assets/favicon.png', 'type' => 'image/png']
]
```

The keys would be the `rel` attributes and the values would be converted to additional attributes (except `url`, which will run through the `url()` helper and be passed as `href` attribute). The `nonce` attribute would be added automatically to each tag (although I think it is ignored for `link` as it's only supported for `script` and `style`).

**Comment by afbora** [comment]
What about multiple sizes for same rel? Nested array? 🤔 

````html
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
````

**Comment by lukasbestle** [comment]
I think it would get too complex very quickly. 😅

Maybe we could support passing a string with the raw HTML. But for the first version I think it's fine without it. To be honest I feel like the `sizes` attribute isn't much in use nowadays – screens have so many DPI that a separate low-fi image isn't really needed in most cases.

**Comment by afbora** [comment]
Right 👍  If we accept strings, developers can be set what they want. Otherwise array will be converted to HTML output.

**Comment by lukasbestle** [comment]
I'd go without the string support for the first version. It can be really clumsy to write all the HTML in a string. Snippets would be too slow (run on each request, even for the frontend or API). And it could be a security issue if it's possible to inject malicious HTML somehow.

**Comment by distantnative** [comment]
@lukasbestle any reason that the keys differ slightly from our existing usage https://github.com/getkirby/kirby/blob/develop/src/Panel/Document.php#L69-L80 ? (existing might be wrong?)

**Comment by lukasbestle** [comment]
@distantnative Ah, I looked on the `master` branch, where the tags are hard-coded in the Panel HTML. There must have been a reason why we changed it with Fiber, so I‘d leave the defaults you linked to.

**Comment by bastianallgeier** [comment]
✅
