### ISSUE TITLE
[3.6.0-alpha.1] `Invalid form with errors` dialog missing

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3519]
**Describe the bug**  

When there is an error in the form, I can see the error in the console, but the alertbox where we can see the error detail is no longer visible.

**To Reproduce**  
1. Go to panel
2. Save any page that not valid form
4. Form error alert dialog is not appear

**Kirby Version**  

3.6.0-alpha.1 & develop branch

**Console output**  

````
code: 400
details: {text: {…}}
exception: "Kirby\\Exception\\InvalidArgumentException"
file: "/test/kirby/3.6.0.alpha.1/kirby/src/Cms/ModelWithContent.php"
key: "error.invalidArgument"
line: 598
message: "Invalid form with errors"
route: "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
status: "error"
__proto__: Object
````

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome latest

**Comment by distantnative** [comment]
✅
