### ISSUE TITLE
Can't sort Kitchensink/Testimonials by Drag'n'Drop

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#352]
It says the site has listed and unlisted pages which is not true:
<img width="370" alt="screen shot 2018-04-03 at 00 12 34" src="https://user-images.githubusercontent.com/3930150/38218923-baafbca8-36d3-11e8-9f7d-9bd0d2115e11.png">

Bye the way: If I don't want pages to be sortable by drag'n'drop how would I do that? And if yes is there any indication to the panel-user if a section is sortable or not?

**Comment by ghost** [comment]
@wottpal I think this is a related issue I openned: https://github.com/k-next/starterkit/issues/324

**Comment by distantnative** [comment]
Exactly, duplicate of #324 
Attempts to make that clearer and improve the possibilities are #304 and #302
