### ISSUE TITLE
[3.6.0] Blueprint placeholder shows `null.yml`

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3533]
I think it's the case when a file doesn't have a template

<img width="1344" alt="Screen Shot 2021-07-17 at 20 00 48" src="https://user-images.githubusercontent.com/3788865/126045933-c5e8d3da-9a36-4704-a9d8-d6d4af0e07d1.png">

**Comment by afbora** [comment]
Related regression commit https://github.com/getkirby/kirby/commit/e0fb84c51d3a520a09757dc8f9849bf96b4d394d

**Comment by distantnative** [comment]
Likely this line https://github.com/getkirby/kirby/commit/e0fb84c51d3a520a09757dc8f9849bf96b4d394d#diff-f48d01ff6f4c25f3c2e8f1a34251e92010823474044243852b1654a8f6b97497R271

**Comment by distantnative** [comment]
✅
