### ISSUE TITLE
Running unit tests only for `Toolkit` namespace fails

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3544]
While they pass when we run all unit tests

**Comment by lukasbestle** [comment]
For me it's `Toolkit\VTest` in particular that has two failing tests:

```
1) Kirby\Toolkit\VTest::testInput with data set #1 (array('test'), array(array('email')), false, 'The "email" validation failed...email"')
Failed asserting that exception message 'Please enter a valid email address for field "email"' contains 'The "email" validation failed for field "email"'.

2) Kirby\Toolkit\VTest::testValueFails
Failed asserting that exception message 'Please enter "b"' contains 'The "same" validation failed'.
```

**Comment by distantnative** [comment]
Exactly, for me too. But when running all namespaces together, they pass just fine.

**Comment by afbora** [comment]
For me too. To give you an idea; when you remove the `testSize()`, all unit tests passes. So why? I don't know 🙂 Tracking down..

**Comment by afbora** [comment]
New clue: this is related [my commit](https://github.com/getkirby/kirby/pull/3384/files) that unit test for `Supports countable field objects`

**Comment by lukasbestle** [comment]
Pretty sure this is because of `new Page()`, which brings in a CMS dependency into the test but without a global `$kirby` object.

**Comment by afbora** [comment]
But still working with only `new Page()` lines and without field tests, like below:

```php
$page = new Page(['slug' => 'a', 'content' => ['foo' => 2]]);
// remove assert lines
$page = new Page(['slug' => 'a', 'content' => ['foo' => 'hello']]);
// remove assert lines
```

**Comment by afbora** [comment]
@lukasbestle I've created `MockObject` that extends `\Kirby\Cms\Page` on locally and seems works great. What do you think?

**Comment by lukasbestle** [comment]
What does that `MockObject` do differently?

**Comment by afbora** [comment]
I just tried 🙈 

**MockObject structure**

````php
use Kirby\Cms\Content;
use Kirby\Cms\Page;

class MockObject extends Page
{
    protected $value;
    
    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function content(string $languageCode = null)
    {
        return new Content([
            'foo' => $this->value
        ]);
    }
}
````

**Running tests**

````php
$page = new MockObject(2);
$this->assertTrue(V::size($page->foo(), 2));

$page = new MockObject('hello');
$this->assertTrue(V::size($page->foo(), 5));
````

**Comment by lukasbestle** [comment]
It‘s a good solution!

But I think we could solve it even simpler without a mock: I think we could actually just instantiate a field object and pass that to `V::size()`. For the method it doesn‘t matter if there is a model behind the field, does it?

**Comment by afbora** [comment]
Exactly! Great solution 💯

**Comment by afbora** [comment]
I found the issue. This issue fixed when #3542 (due to deprecated param) and #3547 (due to Page class) get merged 😅

**Comment by afbora** [comment]
@distantnative Related two PRs merged and works for me. Could you try again on develop branch please?

**Comment by distantnative** [comment]
✅
