### ISSUE TITLE
[3.6.0] Files field structure preview misses new "back" setting

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#3551]
**Describe the bug**  
I'm using a files field inside of a structure field. The latest stable version allowed me to set `back: red` and I added a CSS style for `[data-back="red"]`. Now with 3.6.0 it's possible to define a color directly and it's a really great feature but the structure preview doesn't know the new setting as it seems.

**To Reproduce**  
1. Create a structure field with a files field
2. Set the background: https://getkirby.com/releases/3.6/features/image-options

**Expected behavior**  
I'd expect the same background color as in the single entry view.

**Screenshots**  

![Screenshot-20-07-2021_15-13-03@2x](https://user-images.githubusercontent.com/7975568/126330374-47db0cc5-2cc0-4244-865d-3b15cbde84cc.png)
![Screenshot-20-07-2021_15-14-36@2x](https://user-images.githubusercontent.com/7975568/126330424-28b2c148-2e28-45b8-91be-667d8c50f3dc.png)

**Kirby Version**  
3.6.0-alpha.2

**Comment by bastianallgeier** [comment]
✅
