### ISSUE TITLE
[3.6.0-alpha.2] Pages, files and users field not sortable, no drag handle

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#3553]
**Describe the bug**  
While pages **sections** have a drag handle, I can not sort the selected pages in a pages **field**.

**To Reproduce**  
1. Add a files field
2. Select files and try to sort them

**Expected behavior**  
A drag handle so I can sort the pages.

**Kirby Version**  
3.6.0-alpha.2

**Desktop (please complete the following information):**  
 - OS: macOS Big Sur 11.4
 - Browser: Chrome 
 - Version: 91.0.4472.114

**Comment by bastianallgeier** [comment]
✅
