### ISSUE TITLE
[3.6.0-alpha.2] Dropdown open three-dots overflows form-buttons

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3554]
![FireShot Capture 016 - Exploring the universe - Mægazine - localhost](https://user-images.githubusercontent.com/3393422/126388229-866acfe5-ddb3-43bf-863f-7cdc7b74386a.png)

**Comment by afbora** [comment]
Because navigation (form buttons) z-index value less than dropdown's.
 
```css
  --z-dropdown: 700;
  --z-navigation: 300;
````

**Comment by distantnative** [comment]
I would think @bastianallgeier might set it like this because of dropdown in a drawer (drawer has 600)... otherwise I am not sure why dropdown should have such a high z-index.

**Comment by lukasbestle** [comment]
If it's because of the drawer, we can solve it by overriding the `z-index` of components inside drawers specifically instead of globally.

**Comment by bastianallgeier** [comment]
✅
