### ISSUE TITLE
[3.6.0-alpha.2] Language direction broken

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3559]
**Describe the bug**  

`app` props (`app.$languages`, `app.$system.multilang`, etc..) in direction.js not working but `window.panel.$..` is working.
https://github.com/getkirby/kirby/blob/3.6.0-alpha.2/panel/src/helpers/direction.js

**To Reproduce**  
1. Go to panel
2. Add RTL language
3. Edit any page
4. See error that direction attribute is not appear

**Kirby Version**  

3.6.0-alpha.2

**Comment by distantnative** [comment]
✅
