### ISSUE TITLE
[Panel] Change "Site" in Topbar

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#356]
...by changing the `title` in `site.yml`. It could be useful to write the website-name there instead.

But only if manually intended through the blueprint. Simply taking the sites name from `site.txt` would result in way to large strings in many cases.

**Comment by HYR** [comment]
I like this idea. :)

**Comment by bastianallgeier** [comment]
I would keep this idea for later but not 3.0

**Comment by luxlogica** [comment]
This seems like a very easy way to add a little BRANDING to the Panel, without too much effort.
