### ISSUE TITLE
Kirby trigger() method seems bugged

### ISSUE THREAD

**Issue by SkidX** [getkirby/kirby#356]
Hi, 
I think that the kirby trigger() method is not working properly, it avoids to call more than one hook callback in a single request due to a wrong implementation with the static $triggered array.

On lines 830 - 032 of /kirby.php you have:
```php
if(in_array($key, $triggered)) continue;

$triggered[] = $key;
```
so if you have registered a panel.page.move hook and a panel.page.update hook (so both at first position of their respective hook array), the triggering of one will avoid the trigger of the second because you have already stored the key 0 inside $triggered.

I would suggest to replace those rows with these:
```php
if(array_key_exists($hook, $triggered) && in_array($key, $triggered[$hook])) continue;

$triggered[$hook][] = $key;
```

Cheers

**Comment by bastianallgeier** [comment]
Thanks for pointing this out. I just fixed it on the develop branch.
