### ISSUE TITLE
Implement `$pages->children()`

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#358]
I often see people using `$pages->children()`, which makes sense but does not work (only for `$children->children()`).
Maybe this should be implemented by returning a collection of all children of all pages in the current `Pages` collection (just like `index()` but without recursion).

**Comment by texnixe** [comment]
I just edited my post in the forum, my test on the starterkit showed my that `$pages->children()` does in fact work. I created 2 folders on the main level with the same template and could fetch their children without any problem.

**Comment by lukasbestle** [comment]
Yes, you are right. It seems like basically every `$pages` object is actually a `Children` object, so the method is there.
