### ISSUE TITLE
[3.6.0-alpha.2] File source url broken on draft pages

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3587]
**To Reproduce**  
1. Go to panel
2. Edit any pages that have files
3. Change status page to draft
4. Go to file details
5. Click to file to see source
6. See issue

**Kirby Version**  

`develop` branch

**Additional context**  

This issue only for draft pages and file url like `/photography/trees/last-tree-standing.jpg` instead `/media/pages/photography/trees/..`

**Comment by distantnative** [comment]
@lukasbestle this is caused by us changing the URL to the public permanent URLs... for drafts those won't work. Should we switch back? Try to differentiate (maybe tricky)?

**Comment by lukasbestle** [comment]
I think the cleanest solution would be token support for file URLs in draft pages. Basically like with the preview URLs for pages, Kirby would add a `?token=` query param.

**Comment by bastianallgeier** [comment]
✅

**Comment by distantnative** [comment]
Looks like Bastian decided to go the simple way :D

**Comment by bastianallgeier** [comment]
Including the token in the URL wasn't as trivial as I thought. The token method is protected and making it public didn't seem a good decision just to fix this. I also think it can be expected that the URLs of files in drafts are not permanent.
