### ISSUE TITLE
Manual files sorting via changePosition not working correctly in 3.6-alpha2

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3589]
**Describe the bug**  
Changing file sorting manually via "Change position" doesn't work as expected.

**To Reproduce**  
1. In a 3.6-alpha2 Starterkit, go to an album page
2. Make sure all images are sorted
3. Use "Change position" to move the last image to first position. Everything ok.
4. Then apply "Change position" again on the last image and move to first position. The image is correctly moved to first postion, but the last first image is now moved again to last position.

**Expected behavior**  
At step 4, the formerly first image should now be on position 2.

**Kirby Version**  
3.6-alpha2

**Desktop (please complete the following information):**  
Mac OS 11.2.2 with Firefox 89.0.2 (64-bit)

**Additional context**  
Files sorting also mixed up in 3.5.7.1
https://forum.getkirby.com/t/files-gallery-change-position-doesnt-update-and-resets-manual-sorting/22984/2

**Comment by afbora** [comment]
I've tested on 3.5.7.1 and 3.6.0-alpha.2:

**In 3.5.7.1**
Different bug was exists (selected file wasn't appear on list). The good news is it was fixed in 3.6.

**In 3.6.0-alpha2**
This bug different from 3.5.7.1. I can reproduce too.

**Comment by bastianallgeier** [comment]
✅
