### ISSUE TITLE
[3.6.0-alpha.3] Drag handle icon not centered

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#3595]
The drag handle icon is off center by one pixel. The wrapper is 16px wide and the icon is 9px wide. Is there an award for most nitpicky issue ever?

![Screenshot-27-07-2021_16-58-49@2x](https://user-images.githubusercontent.com/7975568/127177701-6c70274d-14ab-4325-84e8-ec12cd14c0b9.png)

**Kirby Version**  
3.6.0-alpha.3

**Desktop :**  
Chrome 92.0.4515.107

**Comment by bastianallgeier** [comment]
We've just created it for you 😜  You won!

**Comment by bastianallgeier** [comment]
✅
