### ISSUE TITLE
Panel: visibility status of pages not immediately visible

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#36]
Reported by @texnixe

**Comment by bastianallgeier** [comment]
@texnixe could you add a bit more information for this? I'm not entirely sure what you mean :)

**Comment by texnixe** [comment]
In Kirby 2 pages widget or sidebar, I could immediately see the page status (date or number or dash). In page collections now, it is not immediately obvious, unless I use different filtered collections.

**Comment by bastianallgeier** [comment]
We already have a subheadline prepared for cards and I wanted to introduce an optional "information" text for lists as well. They could be filled with whatever you want to display. num, uid, id, date, etc. and also with mime, size, dimensions or anything else for files.

**Comment by distantnative** [comment]
By now implemented.
