### ISSUE TITLE
mysql_ depercated in PHP7

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#360]
Maybe change the database class so it will work with PHP7? I'm using it in my current project and I hope it will not just stop working.

http://stackoverflow.com/questions/34946406/try-catch-with-php-generate-error

"Please dont use the mysql_ database extension, it is deprecated (gone for ever in PHP7) Especially if you are just learning PHP, spend your energies learning the PDO or mysqli_ database extensions"

**Comment by bastianallgeier** [comment]
The database class is already built around PDO. The old mysql_ extension is not in use.

**Comment by jenstornell** [comment]
Great news (for me), thanks!
