### ISSUE TITLE
Page status dialog: pre-select position 1 for only public page

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3609]
More detailed description: https://kirby.nolt.io/290

**Comment by afbora** [comment]
@distantnative I've tested on develop branch. I guess this is fixed with Fiber 🎉 

![image (23)](https://user-images.githubusercontent.com/3393422/128595087-c459bb0d-6d4c-4e1e-af69-b7e4fb3279ad.png)

**Comment by nilshoerrmann** [comment]
Couldn‘t the select even be hidden in this case? Users might be irritated what to do with it in this case.

**Comment by bastianallgeier** [comment]
✅
