### ISSUE TITLE
Implement a specific `$files->not()` like with `$pages->not()`

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#361]
`$files->not()` currently falls back to the collection method, which won't support file objects and IDs in uppercase.

See [this topic in the forum](https://forum.getkirby.com/t/files-with-uppercase-chars-in-name-messes-up-the-not-function/3132?u=lukasbestle).

**Comment by bastianallgeier** [comment]
Good point! I just added it to the develop branch.
