### ISSUE TITLE
[3.6.0-alpha.3] InvalidArgumentException: Panel area "todos" must be defined as a Closure

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3617]
**Describe the bug**  

https://getkirby.com/releases/3.6/fiber/dropdowns#in-your-plugin

I've tried fiber dropdowns like example in plugin:

> InvalidArgumentException: Panel area "todos" must be defined as a Closure

**Kirby Version**  

3.6.0-alpha.3

**Comment by afbora** [comment]
I guess it's an error with the definition in this example. I think I figured it out in this PR: https://github.com/getkirby/getkirby.com/pull/1454

**Comment by bastianallgeier** [comment]
Yep, it's not a bug itself but a bug in the docs. Your PR is correct.
