### ISSUE TITLE
[3.6.0-alpha.3] Missing main top navigation bar on custom areas

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3618]
**Describe the bug**  

https://getkirby.com/releases/3.6/fiber/areas#area-definition

I've tried custom area definetion like above example, but panel main top navigation bar is missing.

**index.js**

````js
panel.plugin('yourname/todos', {
  components: {
    'k-todos-view': {
      props: {
        todos: Array
      },
      template: `
          <k-view class="k-todos-view">
            <k-header>
                Todos
            </k-header>
          </k-view>
        `
    }
  }
})
````

**Screenshots**  

![screen-capture-1138-Theme Options - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/128614804-d7c5b592-b58c-4720-8844-a6e0b36db1a2.png)

**Kirby Version**  

3.6.0-alpha.3

**Comment by distantnative** [comment]
You have to wrap your custom view with `<k-inside>`

**Comment by afbora** [comment]
Ahh, working now! But this information should be clearly in `Custom Panel Views` section of [breaking changes page](https://getkirby.com/releases/3.6/breaking-changes#panel__custom-panel-views)

**Comment by afbora** [comment]
Related PR https://github.com/getkirby/getkirby.com/pull/1454

**Comment by distantnative** [comment]
👍
