### ISSUE TITLE
[3.6.0-alpha.3] Cannot read property 'componentInstance' of null

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3619]
**Describe the bug**  

I'mi getting following error in console when i try to set template as view file

> TypeError: Cannot read property 'componentInstance' of null

**index.js**

````js
import View from "./components/View.vue";

panel.plugin('yourname/todos', {
  components: {
    'k-todos-view': {
      props: {
        todos: Array
      },
      template: View
    }
  }
})
````

**View.vue**

````vue
<template>
  <k-view class="k-todos-view">
    <k-header>
      Todos
    </k-header>
  </k-view>
</template>

<script>
export default {};
</script>
````

**Kirby Version**  

3.6.0-alpha.3

**Comment by distantnative** [comment]
Are you using a bundler?

**Comment by afbora** [comment]
I guess, using `parcel`: `parcel build src/index.js --no-source-maps --experimental-scope-hoisting -d ./`

**Comment by afbora** [comment]
Inline template codes `template: '<template>...</template>'` working but as view not working `template: View`

**Comment by bastianallgeier** [comment]
Your setup is not correct.

It should look like this: 

```js
import View from "./components/View.vue";

panel.plugin('yourname/todos', {
  components: {
    'k-todos-view': View
  }
})
```

```html
<template>
  <k-view class="k-todos-view">
    <k-header>
      Todos
    </k-header>
  </k-view>
</template>

<script>
export default {
  props: {
    todos: Array
  }
};
</script>
```

**Comment by afbora** [comment]
Ohh, my incompetence 🙈 Thanks
