### ISSUE TITLE
[Panel] Combine PATCH requests

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#362]
Instead of each section sending one PATCH request, send one combined PATCH request with the changes already stored in `$cache` (to avoid race conditions).

Also check if other requests could be combined in a similar way (e.g. GET data for field sections).

**Comment by distantnative** [comment]
I think we could indeed also combine all GET requests into a single one for page/site/file/user. And in addition on a per-field-basis.

**Comment by bastianallgeier** [comment]
:check:
