### ISSUE TITLE
[3.6.0-alpha.4] `sort` attribute on upload for files field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3625]
**Describe the bug**  

If you drop a file to  sortable files section, `sort` attribute exists in content file, but you drop to files field (new feature), `sort` attribute not exists.

**Related PRs**
- https://github.com/getkirby/kirby/pull/3593
- https://github.com/getkirby/kirby/pull/3603

**Comment by lukasbestle** [comment]
@afbora Both related PRs were merged. Can this issue be closed?

**Comment by afbora** [comment]
No, the issue is; The PR added by Bastian does not include the feature in the PR that I added.

**Comment by lukasbestle** [comment]
Ah, now I understand: You mean that #3603 doesn't implement #3593, correct?

**Comment by afbora** [comment]
Yes, exactly!
