### ISSUE TITLE
[3.6.0-alpha.4] Panel areas label, title, breadcrumb translations

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3626]
**Describe the bug**  

Need to translate for some areas attributes like following:

````php
Kirby::plugin('yourname/todos', [
    'areas' => [
        'todos' => function () {
            return [
                'label' => [
                    'en' => 'Todos',
                    'tr' => 'Yapılacaklar',
                ],
                'breadcrumbLabel' => function () {
                    return [
                        'en' => 'Todos',
                        'tr' => 'Yapılacaklar',
                    ];
                },
                'views' => [
                    [
                        'pattern' => 'todos',
                        'action'  => function () {
                            return [
                                'title' => [
                                    'en' => 'Todos',
                                    'tr' => 'Yapılacaklar',
                                ],
                                'breadcrumb' => function () {
                                    return [
                                        [
                                            'label' => [
                                                'en' => 'Buy some milk',
                                                'tr' => 'Biraz süt satın al',
                                            ],
                                            'link'  => '/todos/123'
                                        ]
                                    ];
                                },
                            ];
                        }
                    ]
                ]
            ];
        }
    ]
]);
````

**Kirby Version**  

3.6.0-alpha.4

**Comment by distantnative** [comment]
I think we need to add `I18n::translate()` for this in a few places. Let's collect:

- https://github.com/getkirby/kirby/blob/develop/src/Panel/Panel.php#L38
- https://github.com/getkirby/kirby/blob/develop/src/Panel/Panel.php#L40
- https://github.com/getkirby/kirby/blob/develop/src/Panel/View.php#L438

Not too sure yet how to handle those options with callback functions. For these, maybe the developer would need to already use `I18n::translate()` inside the callback function.

**Comment by afbora** [comment]
Yes, currently `I18n::translate()` method doesn't support callback.

**Comment by distantnative** [comment]
It would also be not efficient. We use callbacks in these places to only resolve them once needed. If `I18n::translate()` resolves them right away, that benefit is wasted. So I think for all callbacks, the developers have to take care of it themselves inside the closure.

**Comment by afbora** [comment]
You mean, developers should return array directly, instead array in closure like below example? (Of course after implements `I18n::translate()` to areas)

**Correct**

````php
'breadcrumbLabel' => [
    'en' => 'Todos',
    'tr' => 'Yapılacaklar',
]
````

**Wrong**

````php
'breadcrumbLabel' => function () {
    return [
        'en' => 'Todos',
        'tr' => 'Yapılacaklar',
    ];
},
````

**Comment by distantnative** [comment]
No, I think we need to keep closures for better performance - that's why Bastian implemented them in the first place.

What I mean is this:

```php
'breadcrumbLabel' => function () {
    return I18n::translate([
        'en' => 'Todos',
        'tr' => 'Yapılacaklar',
    ]);
},
```

**Comment by bastianallgeier** [comment]
I wonder if we should really encourage the translation arrays here at all, or try to get developers to use `t()` instead and register the matching translation strings.

**Comment by afbora** [comment]
Can we translate arrays inside the Closure? We can leave that to the developer if it makes it complicated.

**Comment by bastianallgeier** [comment]
We use t() for all our stuff and I would think it's the most straight forward way for plugin developers as well. 

A plugin could look something like this: 

```php
Kirby::plugin('your/plugin', [
    'translations' => [
        'en' => [
            'todo' => 'Todo',
        ],
        'de' => [
            'todo' => 'Aufgabe',
        ]
    ],
    'areas' => [
        'todos' => function () {
            return [
                'label' => t('todo),
                ...
            ];
        }
    ]   
]);
```

**Comment by afbora** [comment]
In this case, the developer can translate in 2 different ways. With `I18n::translate()` and `t()`. I don't think any further development is needed for this, right?

**Comment by bastianallgeier** [comment]
Turns out `t()` is just a shortcut for `I18n::translate()` 🤣

So this should be working as well: 

```php
'label' => t([
    'en' => 'Todos',
    'tr' => 'Yapılacaklar',
])
```

**Comment by distantnative** [comment]
I'd suggest to close this issue and make a note for when we write the docs to include an example.

**Comment by bastianallgeier** [comment]
I've added it to the docs: https://getkirby.com/releases/3.6/fiber/areas#translating-labels-titles-etc
