### ISSUE TITLE
[3.6.0-alpha.4] Custom sections doesn't working

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3627]
**Describe the bug**  

> The section type "modified" is not valid

I'm getting above error when i try to implement custom sections like following sample. Btw I've tested on 3.6.0-alpha.1 and doesn't working too. But working on 3.5.7.1.

````php
Kirby::plugin('yourname/modified', [
    'sections' => [
        'modified' => [
            'props' => [
                'headline' => function ($headline) {
                    return $headline;
                }
            ]
        ]
    ]
]);
````

**Kirby Version**  

3.6.0-alpha.4

**Comment by afbora** [comment]
Source of this issue is [pagetable plugin](https://github.com/sylvainjule/kirby-pagetable) with following error. Also this issue brokes other plugins load. I added to broken list https://github.com/getkirby/kirby/issues/3485

> Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined

**Comment by afbora** [comment]
@distantnative @bastianallgeier  I've tracked down the issue and found the source of issue.
We started to use `<script type="module">` [in Panel 3.6.0](https://github.com/getkirby/kirby/blob/develop/views/panel.php#L60) and parcel doesn't support that: https://github.com/parcel-bundler/parcel/issues/2833
Should I open a separate issue? Seemed like a big problem to me.

**Comment by distantnative** [comment]
Yes please. That could be a big issue indeed. As far as I know we need type module for vite to work.

**Comment by afbora** [comment]
I've created new issue about that https://github.com/getkirby/kirby/issues/3628
