### ISSUE TITLE
[3.6.0] Parcel bundler doesn't support `<script type="module">`

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3628]
**Describe the bug**  

While I try to [pagetable plugin](https://github.com/sylvainjule/kirby-pagetable) on 3.6.0, I'm getting an error. I tracked down and since we started to use `<script type="module">` [in Panel 3.6.0](https://github.com/getkirby/kirby/blob/develop/views/panel.php#L60) and parcel doesn't support that: https://github.com/parcel-bundler/parcel/issues/2833

**Console output**  

> Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined

**Kirby Version**  

3.6.0

**Comment by bastianallgeier** [comment]
✅

**Comment by danburzo** [comment]
@afbora just so I can get a mental model of how things fit together, how is Parcel involved here?  Is it that Parcel can’t produce a JS file that can be loaded as an ES module inside the Kirby Panel?

**Comment by afbora** [comment]
@danburzo Sorry! @distantnative will answer your question better. Not my specialty :)

**Comment by distantnative** [comment]
@afbora I'm not sure 😂 this was your issue: but yes my guess is that Parcel was used here in a plugin to generate/compile the plugin's HS file but wasn't capable to produce something the Panel would support

**Comment by danburzo** [comment]
Thanks! :D
