### ISSUE TITLE
Unexpected behaviour multilanguage default value

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#363]
I tried to add a multilanguage setup.

**This is what I was trying to setup:**

- Swedish language in the root.
- Defaults to english when the page is not translated.

The swedish page preview from the panel gives 404. That probably depends that I don't have `default` on the same language as the url is `/`.

En english url still works with this setup.

```php
c::set('languages', array(
	array(
		'code'    => 'sv',
		'name'    => 'Swedish',
		'locale'  => 'sv_SE',
		'url'     => '/',
	),
	array(
		'code'    => 'en',
		'name'    => 'English',
		'locale'  => 'en_US',
		'url'     => '/en',
		'default' => true,
	),
));
```

Moving `default => true` to swedish language work, but then I will always endup having swedish as fallback.

**Comment by distantnative** [comment]
For which pages are you getting a 404 when clicking the panel preview link? Would be great if you could provide some URLs that do work, that do not work and some context explanation.

In my setup, all panel preview links seem to work. However, I cannot access `home` in Swedish (or in my case German) as it will always redirect me to the default English `home`. For subpages both languages seem to work.

**Comment by jenstornell** [comment]
I tried it on a clean installation and could not recreate the problem. Closing it. Opening it again if can isolate the problem later.
