### ISSUE TITLE
[3.6.0-alpha.4] - writer field does not save title with email mark

### ISSUE THREAD

**Issue by garethworld** [getkirby/kirby#3630]
**Describe the bug**  
Writer field does not save links

**To Reproduce**  
1) Create a mailto link in an writer field
2) Save
3) Come back to the page - link is removed.

**Expected behavior**  
Link is saved

**Screenshots**  

**Kirby Version**  
3.6.0-alpha.4

**Desktop **  
 - OS: macO
 - Browser: Chrome,
 - Version: 92.0.4515.131

**Comment by garethworld** [comment]
Sorry just realised there is a new email mark, but could the old behaviour for links still remain as this will break mailto links in existing sites?

**Comment by afbora** [comment]
I do not think so. If you've noticed, links that start with `mailto:` are opened with an automatic email mark dialog. But there is a bug about getting email title.

**Comment by bastianallgeier** [comment]
✅
