### ISSUE TITLE
[3.6.0-alpha.4] `k-panel-view` bordering on page refresh

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3632]
**Describe the bug**  

**To Reproduce**  
1. Go to panel
2. For ex; go to settings page
3. Click to  version text
4. Refresh page (For ex F5 for Windows)
5. See black border

**Screenshots**  

![bordering](https://user-images.githubusercontent.com/3393422/129105994-bc1c1f62-1da9-4734-b65a-e5383ff1d42c.gif)

**Kirby Version**  

3.6.0-alpha.4

**Additional context**  

This issue occur only on focus to `k-panel-view`.

**Comment by bastianallgeier** [comment]
✅
