### ISSUE TITLE
Request method option for update helper cannot be overwriten

### ISSUE THREAD

**Issue by ronaldtorres** [getkirby/kirby#3634]
**Describe the bug**  
I can't overwrite the `method` property of this helper, you set it to POST by default, but you don't use the `method` property inside of the file [update.js](https://github.com/getkirby/kirby/blob/c77ccb82944b5fa0e3a453b4e203bd697e96330d/panel/src/helpers/upload.js#L64).

**Kirby Version**  
3.5.7.1

**Comment by distantnative** [comment]
Good catch, easy to fix!

**Comment by distantnative** [comment]
✅
