### ISSUE TITLE
No results with GraphiQL [Chrome]

### ISSUE THREAD

**Issue by modufolio** [getkirby/kirby#364]
<img width="918" alt="graphiql" src="https://user-images.githubusercontent.com/18153996/38297590-430d039a-37f5-11e8-9f3b-f0dbc00a8375.png">

Getting no results with GraphiQL

**Comment by lukasbestle** [comment]
We switched to a REST API a while back. You can find a list of endpoints [in Airtable](https://airtable.com/shrOLaojXslrVelUs).
