### ISSUE TITLE
Helper function `timestamp` returns invalid dates.

### ISSUE THREAD

**Issue by tickHub** [getkirby/kirby#3642]
When converting a date with the `timestamp` helper function (in kirby/config/helpers.php) and using the rounder feature,  the returned date becomes invalid.

**To Reproduce**  
echo timestamp('2021-08-18 10:59:00', 5); // => 2021-08-18 10:60:00 and strtotime('2021-08-18 10:60:00') becomes false

**Expected behavior**  
output should be: 2021-08-18 11:00:00

**Kirby Version**  
3.5.7.1

**Comment by distantnative** [comment]
Digging into this, there seem to be a number of cases where `timestamp()` completely falls flat on its face 🙈

**Comment by distantnative** [comment]
✅ will be fixed in 3.6.2
