### ISSUE TITLE
[Panel] Move "Open" to last position...

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#365]
I think `open` should be the last option shown in the page menu.
1. I keep accidentally clicking it because for some reason my mind treats it as a back button (don’t ask me why)
2. I think it’s the last thing I’ll do, not the first thing. Plus having the status right below the title makes it quick and easy to see the status of this page.

![image 1](https://user-images.githubusercontent.com/5200901/38314762-3b89428e-37e4-11e8-9771-c606b46c7b56.png)

**Comment by distantnative** [comment]
I have to say that I'd find it very unintuitive for me to have the Settings not as the last option but somewhere in the middle. Also moving from v2 to v3, Open was the first option in v2 too – only now we are laying it out horizontally not vertically.

**Comment by wottpal** [comment]
I also like to see to become "Open" the last item but mainly because imo the publishing-state is the only item in this row which provides actual information and should be immediately visible to the editor. But maybe that's only about personal taste 🤷‍♂️

**Comment by distantnative** [comment]
I think so far having it in its current place has proven to work quite well. We might be reconsider during the public beta if we see that it causes confusion for a larger part of the users.
