### ISSUE TITLE
[3.6.0-alpha.4] Fiber search does not respect `read: false`

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#3650]
**Describe the bug**  
The new Fiber search does not seem to respect setting `read: false` in page blueprints. The respective pages still appear.

**To Reproduce**  
1. Add `read: false` to a page blueprint
2. Search for the page in the Panel

**Expected behavior**  
I expect the page to not appear in the search. This works fine fine in 3.5.7.1.

**Screenshots**  
<img width="518" alt="Screenshot-25-08-2021_17-06-12@2x" src="https://user-images.githubusercontent.com/7975568/130816486-1f073a48-b479-47a1-b725-a687bb39809d.png">
```yml
title: Startseite
options:
  read: false
```

**Kirby Version**  
3.6.0-alpha.4

**Comment by bastianallgeier** [comment]
✅
