### ISSUE TITLE
[3.6.0-alpha.4] Drawer sets body to `overflow: hidden`, doesn't get removed on navigation

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#3651]
**Describe the bug**  
When opening a drawer, the body gets an inline style for `overflow: hidden` to prevent scrolling the content behind the drawer. This style does only get removed when closing the drawer. The issue is you can navigate via the browser back buttons or click on links like files/pages in files/pages fields and it won't be removed.

**To Reproduce**  
1. Open a drawer
2. Click on e.g. a file/page in a files/pages field or use the browser back button
3. Try to scroll

**Expected behavior**  
I'd expect the `overflow: hidden` to be cleared on navigation.

**Kirby Version**  
3.6.0-alpha.4

**Comment by lukasbestle** [comment]
Sounds like the `close` method in `Overlay.vue` isn't triggered on navigation events. @distantnative?

**Comment by distantnative** [comment]
Might be a Fiber effect? Could probably be solved by checking in the `destroyed()` Vue lifecycle hook for the drawer component if it's actually still open and call the `close` method in that case.

**Comment by medienbaecker** [comment]
I just noticed it's not only the drawer. Try removing a layout, the `overflow: hidden` remains, too. It does get removed when removing a block.

**Comment by distantnative** [comment]
I'd think all of these cases are handled by the overlay component where the issue needs to be solved.

**Comment by bastianallgeier** [comment]
✅
