### ISSUE TITLE
Changing template of a page on a multi-language setup creates content files for untranslated languages

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3674]
**Describe the bug**  
This seems very similar to #2515, but relevant to changing templates (as opposed to duplicating).

If you have a multi-lang setup and change the template of a page that only has a content file for the primary language, the newly created page will undesirably have content files for all the other languages.

**To Reproduce**  
1. Assume you have a multi-lang setup with `en` (primary), `fr`, `es`
2. Go to an existing page that only has the primary `en` content filled in. (On disk, this page has no `fr` or `es` content files.)
3. Change the page template
4. The adjusted page will have files for `en`, `fr`, and `es`

**Expected behavior**  
I would expect it to only duplicate content files for languages that actually exist.

This current behavior is extremely undesirable and non-obvious.

**Screenshots**  

**Kirby Version**  
`3.5.4`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.2
 
**Additional context**

**Comment by bastianallgeier** [comment]
✅
