### ISSUE TITLE
Manual Sorting Confusion

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#368]
![image 2](https://user-images.githubusercontent.com/5200901/38314932-9aaa0046-37e4-11e8-929c-ebe78dd12cda.png)

What does this mean to the user? When I drag and drop them I thought I was sorting it manually. The message doesn't make it clear to me what I'm doing wrong. Not sure what action to take.

Also, uses the terms "listed" and "unlisted" while I haven't seen "listed" used in the statuses in this alpha release.

**Comment by bastianallgeier** [comment]
We fixed this today and it will be in Alpha 8
