### ISSUE TITLE
image modified with date format don't work as expected

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#369]
```php
<?php echo $p->image( $filename )->modified('Y-m-d'); ?>
```

It should give me a formatted date but it gives me this string:

`Y-m-d`

**Without date format it works like expected:**

```php
<?php echo $p->image( $filename )->modified(); ?>
```

It gives:

```
1455184220
```

which is expected.

**Docs**

It does only say that date format works for files but it should work the same for thumbs.

https://getkirby.com/docs/cheatsheet/file/modified

**Ugly workaround**

This work but has more code and does not work the Kirby way:

```php
<?php echo date('Y-m-d', $p->image( $filename )->modified() ); ?>
```

**Comment by texnixe** [comment]
This is generally the case, I think, if the date field is not called date, see [this forum post ](https://forum.getkirby.com/t/use-page-date-format-false-field-date-with-form-field-not-called-date/1978/2)

**Comment by distantnative** [comment]
@texnixe: Shouldn't be related to the date field as this concerns the modified date of a file.

**Comment by distantnative** [comment]
Can't reproduce your error, @jenstornell – works for me as expected:

```php
<?= $page->image('forrest.jpg')->modified('Y-m-d') ?>
```

in the starterkit project page echos `2015-12-09` for me.

**Comment by jenstornell** [comment]
I looked into it and yes, I add this into config.php:

```php
c::set('date.handler', 'strftime');
```

I can't remember the reason to why I swtiched, but it's in the [docs](https://getkirby.com/docs/languages/setup).

So, is it expected for it to print out `Y-m-d` instead of the date in this case?

**Comment by lukasbestle** [comment]
Yes, if you use the `strftime` handler, you need to use [`strftime` syntax](http://php.net/manual/en/function.strftime.php#refsect1-function.strftime-parameters): `%Y-%m-%d`

**Comment by distantnative** [comment]
If you use `strftime`, you also need to use its placeholders: http://php.net/manual/en/function.strftime.php

E.g. I think it should be `%Y-%m-%d`
