### ISSUE TITLE
[Cms & Panel] Remove unused routes and methods

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#370]
**Frontend:**
- [x] Api
  - [x] file/update
  - [x] page/update
  - [x] page/children
  - [x] page/files
  - [x] site/children
  - [x] site/blueprint
  - [x] site/blueprints
  - [x] site/update
  - [x] roles/get
- [x] components
  - [x] App
    - [x] `FileView:: updateFilename()` – not used anymore, handled by dialog

**Backend:**
- [x] Routes (see above, remove corresponding)
- [x] `BlueprintFieldSection`
  - [x] `patchField` and `patchAll` routes
  - [x] `updateField()` and `updateAll()` methods

**Comment by bastianallgeier** [comment]
Good point! We should have a refactoring label.

**Comment by bastianallgeier** [comment]
We actually shouldn't be removing those who make sense for general API access and maybe consider to move back to them with our sections. The less specific we get the more the API becomes useful for other applications.

**Comment by bastianallgeier** [comment]
✅
