### ISSUE TITLE
Plugin as bundles

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#370]
With some plugins and themes, which are getting more complex, we see them more and more struggling with install/update instructions. Cause you might not only have to drop a holder into `site/plugins` but also to add some blueprints, snippets, assets...

It would be great if themes and plugins could be bundled together. So there is just one folder to copy/update.

**Comment by afbora** [comment]
/themes/default/snippets/
    /themes/default/plugins/
    /themes/default/methods/

Like that? I think, would be great! +1

**Comment by jenstornell** [comment]
Is this feature added or just closed?

**Comment by lukasbestle** [comment]
Added, but [in a different way](https://github.com/getkirby/kirby/commit/8084f156b772e3876d7a3bfd04abe5e28382125a). There will be a `Registry` in the next release.
