### ISSUE TITLE
Repeated cookie headers when using `$site->user()` in a template

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#371]
See [this topic](https://forum.getkirby.com/t/redundant-cookie-settings-in-http-headers/3318?u=lukasbestle).

**Comment by distantnative** [comment]
Pontential fix:

`toolkit/lib/cookie.php` - make sure to only set empty cookie (to actually unset it) if it exists in the first place:

```php
public static function remove($key) {
    if(static::exists($key)) {
      unset($_COOKIE[$key]);
      return setcookie($key, null, -1, '/');
    } else {
      return true;
    }
  }
```

**Comment by bastianallgeier** [comment]
Just fixed this on the develop branch of the toolkit.
