### ISSUE TITLE
[Panel] Click to edit page title in-line

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#372]
It'd be nice to edit the title in-place by just clicking the title, when in a page, and just typing a new title out.

<img width="647" alt="pasted_image_4_4_18__10_59_am" src="https://user-images.githubusercontent.com/5200901/38322342-59881e00-37f7-11e8-89af-1a753c248c44.png">

**Comment by distantnative** [comment]
@HYR Since Alpha 7 was our easter release, there are some easter eggs hidden. Try double click on the title (not that it answers your whole suggestion, but maybe you haven't spotted that one yet) 😉

**Comment by HYR** [comment]
@distantnative Ahh! No I didn't catch that. It's funny, I rarely double-click anything, so it never would've crossed my mind to try it! It's definitely helpful since I wouldn't want to have to go to the settings dropdown to rename the page frequently. I still like the idea of it being in-place editing but this definitely helps. Maybe auto-selecting the text would be a nice touch too to save you the step when renaming it. 😁

**Comment by bastianallgeier** [comment]
Auto-select is now implemented. We need to make it clearer that you can edit titles with a double-click. But that's something for later :)
