### ISSUE TITLE
Way to extend file objects

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#372]
See [this post in the forum](https://forum.getkirby.com/t/documentation-for-page-image-html-missing/3205/4?u=lukasbestle).

Two approaches:

- Like field methods: An array of functions where users can add their own to use globally for all files
- Like page models: Methods specific to the template of the file's page.

**Comment by distantnative** [comment]
I just added a PR that implements custom file methods the same way as custom field methods. Not so sure about specific file models - would they be based on the template of the site they belog to? Or rather the document type?

**Comment by lukasbestle** [comment]
Very good question. I thought about basing it on the template of the page, but using file types would make sense as well. Maybe your implementation like with field methods is simpler and easier to understand.

**Comment by distantnative** [comment]
Just wondering if custom `pages` and `files` methods would make sense as well?
