### ISSUE TITLE
Field info/help text

### ISSUE THREAD

**Issue by meszarosrob** [getkirby/kirby#374]
I was wondering if there will be an option to add some kind of info/help text for individual fields?

Like so:

![image](https://user-images.githubusercontent.com/6097856/38365281-59c320a2-38e4-11e8-8bf4-6560154438ef.png)

**Comment by distantnative** [comment]
This already exists. And as you have guessed right, the option is `help`:

<img width="657" alt="screen shot 2018-04-05 at 17 39 21" src="https://user-images.githubusercontent.com/3788865/38376185-5bb8923e-38f8-11e8-8869-b6c6acc42f1d.png">

<img width="610" alt="screen shot 2018-04-05 at 17 39 12" src="https://user-images.githubusercontent.com/3788865/38376189-5e05b206-38f8-11e8-906f-4d1641bd9855.png">

**Comment by meszarosrob** [comment]
Thanks 🥇
