### ISSUE TITLE
[Panel] Refetch sections with mixed status pages after status change

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#376]
Consider I have a draft section and an all status section of pages (maybe I shouldn't but I can). The draft is then shown in both sections. If I drag the draft page manually into a different position. within the mixed section, it becomes a published page. However, the page remains in the draft section until I refresh the page.

**Comment by distantnative** [comment]
@bastianallgeier this would call for refetching all page sections on an emitted page.changeStatus event or so. But then we are running again in a lot of calls.

Maybe we should also establish some kind of API call bus. First section requires data for page Y from our store on the first load. Store doesn't have it, sends out an API call to load it. If a second section wants the data for the same parent, store has it already can return it. When event page.changeStatus is triggered, store refetches data from API, then sends event out for subscribed sections to refetch it from the store.

**Comment by bastianallgeier** [comment]
✅ 

Even though we have the extra requests, we have to go that way. The bus can come later.
