### ISSUE TITLE
Inconsistent function name to get content in images

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#380]
https://forum.getkirby.com/t/force-switch-language-to-image-field/3335/4

**To be consistant both of these would work:**

```php
echo $page->content()->get('text'); // A page
echo $image->content()->get('text'); // An image
```

The page content work. The image content does not.

**Instead this work:**

```php
echo $images->meta()->get('text');
```

**Why to use a consistant function:**

- The more consistant the API is, the less we need to learn.
- The question at the top would not have been needed to be asked.
- Both are content. File content and image content.

**For backword compability:**

If there is a need to keep the meta function around, add the content function as a helper, like u() works for url().

**Comment by distantnative** [comment]
I actually just spotted the reason for naming it `meta()`:
The `File`class extends the `Media` class which features its own `content` method for actually setting and getting the file contents. So overwriting this would not be ideal.

**Comment by bastianallgeier** [comment]
Haha, I didn't even think about this :)
