### ISSUE TITLE
[Panel] Improve sorting pages via drag'n'drop

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#380]
1. Completely disable dragging of row-/card-items when `sortBy` is set in the blueprint. It would also make sense to give a visual clue to the user which section is sortable and which not. Maybe a subtle grab-icon. If you think this is too distracting for all rows it could also be placed outside the item.

![artboard](https://user-images.githubusercontent.com/3930150/38446593-38ee3f5e-39f9-11e8-9f8a-31cb1163583f.png)

2. The new `status: all` option is a real improvement compared to Alpha 7. But nonetheless I'm not completely sold on sorting unlisted/draft pages at the bottom. Why shouldn't they be in the normal sorting-flow? Then I could completely prepare my new post/person/project or whatever and also its position before publishing. This somehow feels right to me. But if you keep the current way imo it's unintuitive that dragging these items upwards automatically changes their status. The UX should be improved by a confirmation-dialog and maybe a dark-gray separation line in the pages table between the different publishing states.

**Comment by distantnative** [comment]
✅
