### ISSUE TITLE
[Panel] FileView: Large image preview in modal

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#381]
In the file view we see a small preview of the image.

Clicking on the image could bring a modal with a larger version of the image.

**Comment by distantnative** [comment]
Could you explain a bit what you see as the advantages of a modal solution?
I'd argue that the current version has its benefits on the site of complete native support of keyboard shortcuts etc. and allows us to provide the full resolution original to the user (e.g. for download).

**Comment by jenstornell** [comment]
Yes, your solution is good for downloading the image.

Often we don't want to download it, just see it in a larger version. To leave the current panel view, or need to download the file, just to see a large version of the image is not a very good user experience, I think.

Anyway, no matter what approach you choose, I think the image should be clickable.

**Comment by distantnative** [comment]
My point here is that the full original image in a new tab is a much better experience to see a large version: you can zoom in without problems, it fills the maximum of what your browser windows has to offer and I can dismiss the tab very easily. All because of native browser support. Achieving this with a modal is hard and in my experience rarely happens – pictures in a modal often look nice on the first look but can be very inexpedient regarding what you actually wanted to be able to do.

**Comment by jenstornell** [comment]
I understand your point of view. What I think is sad is that a new tab is needed.

## My modal

I've developed an image modal for my new site. It looks like what I had in mind for the Panel.

**Click the teddy bear:**

https://nallepresent.se/products/nalle-svante-90cm-teddykompaniet/24

**Pros:**

- I'm always in the same tab, even when I click around on images.
- I'm in control of how the modal works and looks.
- It fills the maximum of what the browser window can hold, all the way to the edges.

**Cons:**

- I can't zoom in on non mobile devices, as I use `max-width: 100%`. [More info](https://stackoverflow.com/questions/15800449/how-to-enable-zoom-in-images-set-to-100-width-in-css).

**Comment by distantnative** [comment]
From all the troubles with modals in the past, I think we are better off using native browser support here.
(As always @bastianallgeier please disagree if you do :D)

**Comment by jenstornell** [comment]
@distantnative  You got me convinced, no modal is much simpler.

I still think that the image should be clickable, not just the download button. Maybe it is now, not tested.

**Comment by bastianallgeier** [comment]
Yes, it’s clickable since a couple versions.
