### ISSUE TITLE
Implement $pages->create() in multilang branch

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#381]
When trying to import pages in English and German from a database, using `$page->children()->create()`, I found that it is impossible to create both language versions. The pages are always created in the default language only.

**Comment by bastianallgeier** [comment]
The page has to be created in the default language first. That's an internal requirement so there will always be the default content first. But you can instantly run the update method for the other language afterwards. 

```php
$newPage = $page->children()->create(…);
$newPage->update(array(…), 'en');
```

**Comment by texnixe** [comment]
Ok, I didn't know that. Will make a note to include this in the docs.
