### ISSUE TITLE
Empty structure values not clickable everywhere

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#382]
When using the structure field with some empty values I notices that I could not click on the empty value to edit it.

When trying again it worked. I inspected it and it's because only the blue area is clickable. The green is not.

Make the whole td:s clickable, always.

![image](https://cloud.githubusercontent.com/assets/927011/13073053/0ec0f870-d49d-11e5-98fe-48075a43c3eb.png)

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch of the panel. Please report panel issues only in the panel repository.

**Comment by jenstornell** [comment]
Opps sorry! I often get it right. Butterfingers...
