### ISSUE TITLE
[Api] Move all response data into a separate data JSON property

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#383]
Collections already have a `data` property with the actual data so that the `pagination` can be on the top-level next to it.

For consistency and to accommodate for stuff like the session token, all responses should have their data in a top-level `data` property.

**Comment by bastianallgeier** [comment]
👍 

We should add the status to the global response wrapper as well: 

```
{
  status: "ok",
  data: {},
}
```

**Comment by lukasbestle** [comment]
+1 for that. :)

**Comment by bastianallgeier** [comment]
✅
