### ISSUE TITLE
[Api] Handle session token changes in Authorization header mode

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#384]
If the session token is transmitted in the `Authorization` request header, changes to the session token (especially when the token is automatically renewed in the background) are not currently transmitted to the client.

The API needs to call `$session->needsRetransmission()` and if the result is `true`, the `$session->token()` needs to be set as a top-level JSON response property `token`.

Depends on #383.

**Comment by distantnative** [comment]
@lukasbestle So the prerequisite has been finished - can you help me to understand how to move forward here?

**Comment by lukasbestle** [comment]
Thanks for letting me know. I will send a PR in the next few days.

**Comment by lukasbestle** [comment]
Hm, unfortunately the current structure of the `Api` package doesn't make this easy to implement without hacking my way around the `Api\Api` class.

What I basically need is to modify the [`Api::call()`](https://github.com/k-next/kirby/blob/3.0.0-beta-5/src/Api/Api.php#L71-L77) method so that the session token (`$app->session()->token()`) gets injected into every API response whenever `$app->session()->needsRetransmission()` returns `true`. So far so simple as the entire logic for that is already implemented in the `Session` class. The code would basically be:

```php
$output = $result->action()->call($this, ...$result->arguments());

if (is_object($output) === true) {
    $output = $this->resolve($output)->toResponse();
}

if ($app->session()->needsRetransmission() === true) {
    $output['token'] = $app->session()->token();
}

return $output;
```

But I see the following issues:

- The `Api` class doesn't know about the `$session` and/or `$app` at all. The session is currently part of the API config as a `data` property like any other property and we can therefore not depend on that in the class (the `$app` variable in my example above is currently not defined there). We somehow need to make the `$session` and/or `$app` a first-class citizen of the API config.
- The `Api` class currently just returns what the route returns (or the model in case the route returns an object). The structure of the returned API response is therefore never guaranteed. Currently we are using a consistent response with top-level `code` and `status` everywhere, so it would be possible to add a response property `token` there. But it's not very clean to assume that in the `Api::call()` method as the actual response *could in theory* be of a different structure and may not even be an array.

What do you think?

**Comment by bastianallgeier** [comment]
@lukasbestle do we still need this?

**Comment by lukasbestle** [comment]
What is the current state of API authentication? I remember that we discussed changing the authentication with HTTP Basic auth in the `Authorization` header. If that way of authenticating is still possible, we still need this change, otherwise API clients won't know when the session token changes (which can happen at any time when the session is renewed or a privilege change occurs).

**Comment by bastianallgeier** [comment]
What we have right now is the following setup: 

1. default authentication is session based with csrf token checks. If you want to make use of that in your client you need to send the csrf token in a x-csrf header. That header has to match whatever is stored in the session. 
2. you can switch to basic auth, but only over https. In that case session auth is completely ignored and you have to send a basic auth authorization header with email:password on every request.

**Comment by lukasbestle** [comment]
OK, then we don't need this. We'd only need it if there would be an option to transmit a session token via Basic auth (which could be useful for use-cases like API tokens). But as it's incredibly complex because of this issue, it's probably better to restrict it to the two current methods. They should work fine for most use-cases. 👍
