### ISSUE TITLE
[Panel] Cannot publish draft if form fields have errors, but can if file section has error

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#386]

**Comment by bastianallgeier** [comment]
I cannot reproduce this

**Comment by bastianallgeier** [comment]
I'm closing this, to keep better track of left tickets. Feel free to open if you can still reproduce it.

**Comment by distantnative** [comment]
Steps to reproduce:
1. Go to any published project
2. Delete the cover, so that there is no file in that section (error occurs on that section)
3. Type anything, e.g. in the tags field
4. Hit cmd + S 
5. Result is that the changes get saved

Is that intended or shouldn't it be enforced that a file gets added? I know we enforce this when publishing from draft to listed/unlisted. But since this project is already published, it does not happen.

**Comment by bastianallgeier** [comment]
Ahhh, now I get it. But how would we fix this? Not saving the form in that case seems weird to me, because the form might not have errors at all so you can at least fix stuff on the published page except the missing cover.

**Comment by distantnative** [comment]
True, maybe the visual warning is already enough (error in the section).
