### ISSUE TITLE
[Panel] Field errors not shown underneath field (only in modal on saving)

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#387]
Not on-the-fly, neither when saving (but then the modal tells you there is an error).

<img width="554" alt="screen shot 2018-04-07 at 16 45 44" src="https://user-images.githubusercontent.com/3788865/38456269-352f676e-3a83-11e8-9585-e48a1bd60361.png">

**Comment by distantnative** [comment]
@bastianallgeier Of course this happens when we save to localStorage, so we do not get the errors from the backend. Question is if the fields themselves should handle such requirements (required, min etc.) as well?

**Comment by bastianallgeier** [comment]
We don't have that many validation checks, so it might really be a good idea.

**Comment by bastianallgeier** [comment]
Maybe we could just tap into this: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity
