### ISSUE TITLE
Method extensions for $pages, $files, $page

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#390]
Idea that came up here: #373 

How to deal with potential conflicts e.g. between method extensions and page models?

**Comment by lukasbestle** [comment]
In that case, a method defined in the page model would override the general extension. Actually it has to because the `__call()` method won't be called if a page model defines the method.

**Comment by distantnative** [comment]
Right. I also like the idea. Having general page extensions as a good way for plugins to offer page methods, but if a page model define a method for a specific template, that will override the general one. And if we implement it the same way, those extensions could also never block a core page method.

**Comment by lukasbestle** [comment]
Yes, exactly.

**Comment by texnixe** [comment]
That's a good idea.

**Comment by jenstornell** [comment]
+1

**Comment by distantnative** [comment]
I actually think, we already have this implemented for `$pages` :laughing: https://github.com/getkirby/kirby/blob/master/core/pages.php#L25-L34

**Comment by bastianallgeier** [comment]
Plans for already implemented features FTW!!

**Comment by bastianallgeier** [comment]
Yay, it's done :)

**Comment by jenstornell** [comment]
Missing in docs how to use it?

**Comment by bastianallgeier** [comment]
Yes, but we have to add the new ones now anyway.

**Comment by distantnative** [comment]
@jenstornell Please understand that things do not pop up immediately in the docs if they only just got created in the development process ;)

**Comment by jenstornell** [comment]
@distantnative I understand that. It was just a reminder, because for most people the docs are as important as the features. Without docs, we can't use the features anyway.

But I'll skip the reminders from now on. Seems like you are on top of things anyway. :)

Over and out...
