### ISSUE TITLE
[Kirby] Add code-style linting for PHP files

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#391]
I think we should introduce a code-style checker/fixer to make sure that our PHP files all follow a consistent code-style based on PSR-2. It should be included in the Travis build and make it fail if there are any issues.

Some tools I found:

- http://cs.sensiolabs.org
- https://github.com/php-fig-rectified/psr2r-sniffer

There are also some others, but those seem to be the most popular ones. The first one looks good to me because of the many options and good documentation. We still need to test and evaluate it though.

**Comment by distantnative** [comment]
✅
