### ISSUE TITLE
[Cms/Panel] Add license code both with a config option and with the panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#392]
I think you talked about it on a live stream, but I also thought about it for a long time. The possibility to add the license code with the panel.

When all code is done for a project and we have released it, we may need to buy a license for it if we don't have any licenses left. At that point we probably don't want to fiddle around with the code again to get the license code in.

On my latest project I've added such a text field myself connected to the license option.

## Magic solution

Panel site options is controlled by a blueprint. If the field key `license` is discovered, use that as license code. There are two cons with it. Then the key `license` can't be used for anything else that the user might want. Another thing is that the user still need to add the license field which is probably easy forgettable.

## Locked solution

In this solution, no matter what's in the blueprint, put a license code field in panel site on admin roles. The con here would be if the admin prefer to add the license with config option code. To fix the con, make a check. If license code is in a config option, don't show license code field in the panel.

I think the last solution is quite brilliant.

**Comment by texnixe** [comment]
I don't think adding the license code in a content file is a good idea at all. You can't put the site.txt into .gitignore after all because it needs to be there. Chances are, your license ends up in a public repo without you being aware of it. Such data doesn't belong in content.

**Comment by jenstornell** [comment]
What about a `license.txt` file?

Add it manually when coding the site, or later through the panel, with a text field.

**Comment by texnixe** [comment]
We will have the possibility to use .env files with Kirby 3. Also, there were some thoughts about license files, but I currently I don't have any information what has become of that idea.

**Comment by bastianallgeier** [comment]
✅ We already implemented the license file upload. The format of the license file will probably change again, but otherwise I think this is the best solution.
