### ISSUE TITLE
[Panel] Manually sorting pages affects post status

### ISSUE THREAD

**Issue by Targoran** [getkirby/kirby#393]
If you manually try to sort pages/items in the **"site"** view, the post status will be reset to `published`.

Just change the status to anything else than `published`, then drag + drop sort the item and it's status will be set to `published`. This only happens in the "mixed" sections apparently.

**EDIT**
Didn't think about this before, but the way sorting in Kirby works is that a number prefix is added to the content folder of the page. This *only applies to published pages**, this is how Kirby distinguishes between published/unlisted.

So this is not really a bug, but rather a design/UX problem: For the user it's not necessarily clear that sorting the pages in the panel affects the pages visibility. 

The easiest solution that comes to mind is to **alert** the user with a modal that sorting an unlisted/draft icon will result in publishing it.

Additionally the lists could automatically be sorted by **status** in the mixed sections, so published (and sorted) items on top, then unlisted and drafts at the end.

**Comment by distantnative** [comment]
> Additionally the lists could automatically be sorted by status in the mixed sections, so published (and sorted) items on top, then unlisted and drafts at the end.

That already happens.

Regarding the comments to visualize the status and sort logic better, we will have a closer look at this again towards the beta. There are a lot of other issues in that direction already, which I will close this to keep our focus on track. But it is not forgotten.
