### ISSUE TITLE
[Panel] Flip "Published" Status Icon?

### ISSUE THREAD

**Issue by Targoran** [getkirby/kirby#394]
Currently the status icons for `unlisted` and `published` look quite similar, only inverted, but generally they both look like they've been turned **"off"**.

In my eyes it would make more sense to flip the `published` icon so the switch points to the right side, making it more obvious that it's **on/published**

I know it's only a small detail, but at first glance – if you don't see both states side-by-side, I was confused on what status it resembled.

**Comment by REHvision** [comment]
Yes, they look like being deactivated and actually, they should reflect the possible state of being "deactivated" (i.e. when setting permissions to `status: false`).

This is not yet reflected in list-views (only in the dropdowns).
They should look like they look now when it is not allowed or possible to change the status.
But they should also be really deactivated and not open the dialog box for the status in this case.

If the status can be changed I expect the icons to open the dialog like now but to be visually darker, see attached image:

![status icons](https://user-images.githubusercontent.com/2584674/42001741-3f2a2a98-7a65-11e8-9d6b-c3e38429f5bb.jpg)

**Comment by distantnative** [comment]
The icon has been flipped as suggested. I moved the opacity request to its own issue: https://github.com/k-next/starterkit/issues/539

**Comment by bastianallgeier** [comment]
✅
