### ISSUE TITLE
[Panel] Error when trying to switch page status

### ISSUE THREAD

**Issue by Targoran** [getkirby/kirby#395]
_This is a very specific bug which I couldn't reproduce anywhere else but in this one particular case:_

In the **site** view, I changed the status of the **Contact** page to `draft`. 
But after that, the panel always throws an error when clicking on the **status icon**. The same happens directly on the About page when either clicking the Icon here or selecting "change status" from the settings.

Here is the error from the console:

```console
GET http://mylocalpath/api/pages/contact?select=id,status,num,errors,siblings,blueprint 500 (Internal Server Error)
```

Checking the network tab, here's the output from that 500

```console
{"status":"error","exception":"Error","message":"Call to a member function children() on null","file":"\/Users\/philipp\/Documents\/Websites\/kirbyalpha\/kirby\/config\/api\/models\/PageDraft.php","line":15,"code":500}
```

Happens in the current Alpha 8

**Comment by bastianallgeier** [comment]
✅
