### ISSUE TITLE
[Panel] automatically sorted page items in a section should not be draggable

### ISSUE THREAD

**Issue by Targoran** [getkirby/kirby#396]
I was quite confused when I tried to manually sort a blogpost on the `site` page, because while drag & drop works, the order won't change at all, as they are automatically sorted by date. 

I think in these cases the pages **shouldn't be able** to be dragged around.

**Comment by distantnative** [comment]
The reason behind this right now is that you would not be able to drag pages between sections either when you have multiple sections (e.g. as on `projects`).

**Comment by Targoran** [comment]
@distantnative Ha, didn't think about that.
Maybe it's possible to restrict the sorting to *other* sections then? So you can only move an item from these kinds of sections *out*, but not internally? But this might be over-engineering at this point :)

Or maybe it could help to indicate to the user that a certain section is *automatically sorted*.

**Comment by distantnative** [comment]
✅
