### ISSUE TITLE
[Panel] CSS Grid "auto-fit" messes up kirby-cards

### ISSUE THREAD

**Issue by Targoran** [getkirby/kirby#397]
**Problem:** In some cases, the kirby cards – especially with thumbnail  (see the projects on `pages/home` as an example) will get blown up to fill up the whole width of the page. This looks especially bad when the thumbs get blown up to 500% size and take up a lot of space.

The reason for this is that the CSS grid for this uses the `auto-fit` property, which will force it's item to always try to expand to the whole available space – so for only one item this will enlarge it to 100% width.

**Possible solution**: Switch to `auto-fill` – at least if there are thumbnails in the cards. This way the cards won't take up more space than they should

**Comment by distantnative** [comment]
Yea, plus it gets weird results with pagination, showing different sizes:
<img width="1160" alt="screen shot 2018-04-09 at 18 53 44" src="https://user-images.githubusercontent.com/3788865/38511133-69e1f094-3c27-11e8-86a1-5326b79be2b5.png">
<img width="1159" alt="screen shot 2018-04-09 at 18 53 51" src="https://user-images.githubusercontent.com/3788865/38511138-6bf9a598-3c27-11e8-9fcd-04a54016e732.png">
(a reminder again that paginated sections should fill the last page with blanks to prevent layout jumping around)

**Comment by Targoran** [comment]
@distantnative Jep, that's what happened to me with only 1 item on the last page. Initially thought it was broken.

Like I said, `auto-fill` will take care of filling the unused columns with "empty" space. Could do the trick ;-)

**Comment by bastianallgeier** [comment]
✅
