### ISSUE TITLE
`$page->update()` field callback

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#397]
See [this post](https://forum.getkirby.com/t/simple-like-feature/3492/19?u=lukasbestle).

Useful to increment a counter etc.

**Comment by bastianallgeier** [comment]
So the field callback would only return the string value and not the field object? Is that why it would be useful?

**Comment by lukasbestle** [comment]
The example in the forum describes it quite well. The callback gets the current value and returns the new one. That way you can modify the existing value pretty easily.

**Comment by bastianallgeier** [comment]
This is now implemented on the develop branch together with two awesome new surprises :) 

```php
$page->increment('likes');
$page->increment('likes', $by = 10);
$page->increment('likes', $by = 10, $max = 1000);

$page->decrement('likes');
$page->decrement('likes', $by = 10);
$page->decrement('likes', $by = 10, $min = 0);
```

**Comment by lukasbestle** [comment]
Looks awesome! :)
