### ISSUE TITLE
[Session/Panel] Client-side request retry after session renewal

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#398]
The current session implementation keeps the old session alive for 30 seconds after a renewal. This is a temporary solution that needs to be replaced by client-side retry in the long-term.

From https://github.com/k-next/panel/pull/315:

> Maybe I should explain why removing encryption makes the automatic renewing less secure or less reliable to give you some context:
> 
> When a session is renewed, the old session is kept for 30 seconds so that overlapping requests don't fail (e.g. the session is renewed in the response to request A, which re-generates the session token, but request B was already sent with the old token).
> It works by storing the new token in the old session file. If the old session token is passed in the request, my class simply follows that link to the new session.
> 
> If we remove encryption, an attacker could simply read the old session and get the new token for free, which makes all token regeneration useless. That's unacceptable. So to make it secure, we need to remove the link to the new session, which means that overlapping requests will fail.
> 
> That's not a huge issue, but the plan was to avoid all reliability issues (of which we had a ton in v2) completely with this implementation.
> 
> If we accept that overlapping requests may fail in those renewing edge-cases, we can safely get rid of encryption, which decreases the response time by about 3 ms. But then we need to handle this edge-case in the API client by retrying failed requests after all currently open requests have been completed. That's actually the better solution with better performance and also improved security, but shifts the complexity to the client.

- [ ] Build a "request manager" in the API client that keeps track of all currently pending requests by adding new requests to a `pending` array and removing them once a response (be it an error or success) is available. Dreamcode: `requestManager.handle(myFetchRequest).then(...).catch(...)`.
- [ ] Make that request manager catch every request that fails with either an "Unauthenticated" or network error and add those requests to a separate `retry` array. Set a timeout with a delay of one second for retry.
- [ ] On every successful request and every failed request with an error that is not "Unauthenticated" or network, retry all of the requests in the `retry` array by moving them back to the `pending` array (because in this situation there is no need to wait one second). Also add a flag to all currently `pending` requests to retry those immediately should they fail (because the chances of success are quite high now that there was a successful response).
- [ ] If a retried request fails again, don't retry a second time. Instead display the error to the user like in the current implementation.
- [ ] Once the request manager works, remove the dynamic session expiry feature in the backend `Session` class (@lukasbestle has already prepared that).

**Comment by distantnative** [comment]
Maybe I am mistaken, but this sounds rather complex. Maybe more for 3.1 or 3.0.x?

**Comment by lukasbestle** [comment]
I have prepared the backend changes (getting rid of the encryption and stuff) already and the performance increase is quite significant: Reading from a session now only takes around 3 ms instead of 7 ms.

I actually like that backend implementation without the automatic "keep old session" feature better as it is slightly *more* secure and also faster. So I think it would be great to put this into the initial v3 release.

But we'll see if we'll find the time. I'm pretty sure my explanation is more complex than the feature actually is. The Promise API of fetch is pretty good for stuff like that. :)

**Comment by distantnative** [comment]
If it increases performance, that'd be a big reason to implement it asap. Because currently the switch to the new sessions has really slowed down the panel. We are trying to tackle this with looking at request bundling etc. but of course if the session class could get more performant, that would be good.

**Comment by lukasbestle** [comment]
Have you measured the performance with JWT and sessions?

According to my measurements, reading the session takes 7 ms at the moment. Subtract 1.5 ms of JWT verification time from that and you get a total slowdown of only 5-6 ms. I wouldn't say that counts as "really slowed down", except it's way different on your machine. :)

**Comment by distantnative** [comment]
Not the Session class on its own. But loading the panel, especially `site` cause it sends a lot of requests, on my machine it feels remarkably longer to load. I think @bastianallgeier is experiencing similar things. I can’t really measure it since I only got older versions without Vue-cli. And it seems that Vue-cli helped to speed it up quite a bit

**Comment by lukasbestle** [comment]
Yes, you are right. I'm experiencing the same. The Panel is currently not as snappy as in Kirby 2. It's probably one of those issues where all the tiny little performance issues add up. So I agree that we should shave off as much as we can wherever we can.

I have updated the checklist in the first post of this issue with a simpler solution that is hopefully easier to understand and to implement.
