### ISSUE TITLE
[Cms] Support returning a Response object from the template

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#399]
If you want to print a JSON response in your template, the content type header is now swallowed as it is overwritten with `text/html` once the response that was captured from the template is printed. The same applies to other custom response types.

I think it would be awesome if you could simply return a response object from the template and it would be used as the response instead of the output from the template:

```php
return new Response(...);
```

Also: Is it currently possible to properly set the response type from the template by accessing the response object?

**Comment by bastianallgeier** [comment]
Actually way more complex than I thought. I'm no longer sure if we should do it at all.

**Comment by lukasbestle** [comment]
Oh, interesting. What makes it complex?

**Comment by lukasbestle** [comment]
I think we should reconsider this or at least try to find another way.

I've just had a discussion on Slack about content representations. It turns out that it is no longer possible to create an RSS representation because Kirby doesn't know what the MIME type of `.rss` is and therefore sends `text/html`. Unlike v2, there is no way to override that from the template.
