### ISSUE TITLE
[Panel] Refactor Vuex usage

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#404]
We are using Vuex totally wrong :) I found a good description on SO, that makes a lot more sense than what we do at the moment: https://stackoverflow.com/a/40393742

Basically it goes like this: 

1. Never use commit outside of the store (in components etc.). Only use dispatch
2. We only need commit when we need mutate some more complex stuff. Otherwise we should be fine by "just" directly mutating the state in actions
3. We probably need to think of store actions more like reusable interfaces that our plugin devs can use too. So we need to make sure they look good and are easy to understand.

**Comment by distantnative** [comment]
✅ I think we solved this, @bastianallgeier: no changes to state outside of the store, not calls to mutations from outside the store, mutations only for more complex changes, otherwise using actions. Let me know if you feel like there should be more refactoring.
