### ISSUE TITLE
Improve accessibility for kirbytag images (alt attribute)

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#405]
Hi, I started a discussion and provided some background information about this topic here: https://forum.getkirby.com/t/improve-accessibility-for-kirbytag-images/3579.

tldr: if no alt attribute has been set via the image kirbytag, it should result as `alt=""` in the rendered HTML.

**Comment by jenstornell** [comment]
I agree as w3 validator require an alt tag:

>An img element must have an alt attribute, except under certain conditions.

An empty alt attribute is fine by me.

**Comment by texnixe** [comment]
I also agree, it would only make sense to read out the filename if the filename was descriptive of the image. But in many cases this is not the case, and it is especially not useful if you use the same image with the same filename in multi-language environments.

**Comment by JimmyRittenborg** [comment]
I agree on this one, it seems to be the best way to go about it.

* http://alistapart.com/blog/post/on-alt-text
* https://davidwalsh.name/accessibility-tip-empty-alt-attributes
* https://yoast.com/image-seo-alt-tag-and-title-tag-optimization/
* http://line25.com/articles/10-html-tag-crimes-you-really-shouldnt-commit

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch
