### ISSUE TITLE
$file->title()->html() weird behavior when title is not set

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/kirby#409]
I noticed, that one of my plugins has a weird behavior in the current develop branch version of kirby. I have an image file `$image` and this code:
```
echo $image->title()->html()
```
But my title field of that image is not set to anything. Up to version 2.2.3 this method echoes an empty string, if the title field is not set. But in the current beta, `$image->title()` returns the file name. Converting this with `html()` to valid html results in an `img`-tag.
I use the code mentioned above in my `alt`-attribute. But an image in the alt attribute results in invalid html.

I dont’t think, that getting an empty title field of a file should return the file system path of the file.

**Comment by JimmyRittenborg** [comment]
I think this, in some point relates to #405

**Comment by texnixe** [comment]
It looks rather as if the field, if it does not exists, is completely ignored and the `$file->html()` method applied, which create the image tag.

**Comment by jbeyerstedt** [comment]
I also don't think, that this is related to the issue JimmyRittenborg mentioned.

If the filed does not exist, it seems to be, that the toString method returns the full file system path of the file. It's not even the url.
I didn't checked a var_dump of `file->title()` but only echoing it.

**Comment by texnixe** [comment]
If you do a var_dump, you get an object of type field if the title is present, and an object of type file if the title does not exist.

**Comment by JimmyRittenborg** [comment]
I'm sorry, I thought it was a kirby behaviour, related to that issue - I didn't look into it any further :grin:

**Comment by jbeyerstedt** [comment]
> If you do a var_dump, you get an object of type field if the title is present, and an object of type file if the title does not exist.

But is this an intended behavior, that calling an non existing field returns the file path? And why has the behavior changed in the latest version?

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
