### ISSUE TITLE
[Cms] Implement custom Exceptions in Kirby\Form

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#410]
- **Convert all existing Exceptions to our custom Exceptions:**
    - Form/Exceptions
    - [x] Form/Mixins
      - [x] Form/Mixins/Autocomplete.php
      - [x] Form/Mixins/BooleanValue.php
      - [x] Form/Mixins/Converter.php
      - [x] Form/Mixins/Counter.php
      - [x] Form/Mixins/Date.php
      - [x] Form/Mixins/Email.php
      - [x] Form/Mixins/Fields.php
      - [x] Form/Mixins/Help.php
      - [x] Form/Mixins/Icon.php
      - [x] Form/Mixins/Label.php
      - [x] Form/Mixins/Layout.php
      - [x] Form/Mixins/Length.php
      - [x] Form/Mixins/Max.php
      - [x] Form/Mixins/MaxLength.php
      - [x] Form/Mixins/Min.php
      - [x] Form/Mixins/MinLength.php
      - [x] Form/Mixins/MinMax.php
      - [x] Form/Mixins/Model.php
      - [x] Form/Mixins/Multiline.php
      - [x] Form/Mixins/Options.php
      - [x] Form/Mixins/Pattern.php
      - [x] Form/Mixins/Placeholder.php
      - [x] Form/Mixins/Prefix.php
      - [x] Form/Mixins/Required.php
      - [x] Form/Mixins/Separator.php
      - [x] Form/Mixins/Spellcheck.php
      - [x] Form/Mixins/Step.php
      - [x] Form/Mixins/Text.php
      - [x] Form/Mixins/Time.php
      - [x] Form/Mixins/Url.php
      - [x] Form/Mixins/Value.php
    - [x] Form/CheckboxesField.php
    - [x] Form/CheckboxField.php
    - [x] Form/Component.php
    - [x] Form/DateField.php
    - [x] Form/DateTimeField.php
    - [x] Form/EmailField.php
    - [x] Form/Field.php
    - [x] Form/Fields.php
    - [x] Form/Form.php
    - [x] Form/HeadlineField.php
    - [x] Form/HiddenField.php
    - [x] Form/InfoField.php
    - [x] Form/LineField.php
    - [x] Form/NumberField.php
    - [x] Form/OptionsApi.php
    - [x] Form/OptionsQuery.php
    - [x] Form/RadioField.php
    - [x] Form/RangeField.php
    - [x] Form/SelectField.php
    - [x] Form/StructureField.php
    - [x] Form/TagsField.php
    - [x] Form/TelField.php
    - [x] Form/TextareaField.php
    - [x] Form/TextField.php
    - [x] Form/TimeField.php
    - [x] Form/ToggleField.php
    - [x] Form/UrlField.php
    - [x] Form/UserField.php

- [x] Replace **Kirby\Form\Exceptions**

**Comment by bastianallgeier** [comment]
✅
