### ISSUE TITLE
Problem saving content with translate=false (in multi language site)

### ISSUE THREAD

**Issue by pkaso** [getkirby/kirby#411]
Hi,
I found a bug with multilanguage site setup. The field with option translate=false in blueprint is filled with default language content when saving in Panel on non-default language.

**There is how to repeat this bug:**
1. have a multilanguage site, let say with EN (default) a CZ
2. have a blueprint with title, etc and one FIELD with option translate=false
3. create page with EN language, set content of FIELD to "A"
4. change language to CZ (FIELD is disabled, which is OK)
5. _to this point everything is all right_
6. now save that CZ version of page and the CZ content file will have a FIELD with value "A"
7. if you switch the language back to EN, change FIELD to "B" and save, the CZ version is still set to "A"

**Now you have a wrong value in non-default language.**

I hack it ugly, but will be nice to have it fixed properly.

	  kirby/branches/multilang/page.php
	  
	  public function update($data = array(), $lang = null) {
	  	$data = array_merge($this->content()->toArray(), $data);
	  	
	  	// I FIXED IT HERE
	  	if($this->site->language->code != $this->site->defaultLanguage->code) {
	    	$data = $this->clearUntranslatable($data);
	  	}
	
	   ...
	
	  }
	  
	  protected function clearUntranslatable($data) {
	  	$blueprintFields = $this->blueprint()->fields($this);
	  	foreach ($data as $key=>$value) {
	  		$field = $blueprintFields->get($key);
	  		if ($field->translate == false) {
	  			unset($data[$key]);
	  		}
	  	}
	  	return $data;
	  }

Thanks,
Martin

**Comment by texnixe** [comment]
This should be fixed on the development branch
