### ISSUE TITLE
2.3 beta: Call to undefined method Kirby\Component\JS::render()

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#413]
First thing that broke after installing 2.3 beta was my javascript included using the js() helper:

```
<?= js(array(
    'assets/js/jquery.js',
    'assets/js/app.js'
   )); 
?>
```
> Call to undefined method Kirby\Component\JS::render() in /Applications/MAMP/htdocs/focus-infocom/kirby/kirby/component/js.php on line 29

A single tag like this `js('assets/js/app.js')` works, though.

**Comment by distantnative** [comment]
Same for CSS.

On both files on line 29, you have to change `this->render()` to `$this->tag()` to fix it.
