### ISSUE TITLE
New Thumb API - issue with old syntax

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/kirby#414]
I have a really weird issue with the 2.3.0 beta and the "old" version of generating thumbs.
My code is something like this:
```php
echo thumb($img, array('width'=>400, 'class'=>"card-img-top"));
```
My template executes this code several times for different images. But the first time, there is no thumb generated!
So the output is:
```html
<img src="http://localhost/content/3-projects/project-foo/Slider_Bilder-005.jpg" alt="Slider_Bilder-005" class="card-img-top"> 
<img src="http://localhost/thumbs/projects/project-foo/2014_03-028@w=400&q=90.jpg" alt="2014_03-028@w=400&q=90" class="card-img-top">
```
 Why is this only working the second time and later?

**Comment by lukasbestle** [comment]
Also the alt tag looks strange in the second image tag.

**Comment by texnixe** [comment]
I tested this in the nightly build starter kit and had the same result, the new syntax works fine, with the old syntax, the thumb for the first image is not generated, the following are ok.

**Comment by bastianallgeier** [comment]
I moved away from the API. I will write more about it soon. But this should be fixed by the move back.
