### ISSUE TITLE
[CMS] Redirecting to homepage appends /home to URL

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#416]
when redirecting to home using `go($site->url());` or `go($page->homepage());` the new browser URL is `http://mypage.com/home`. what i expected was `http://mypage.com`.

**Comment by distantnative** [comment]
You should be able to do `go('/')`.

**Comment by bnomei** [comment]
ok that works. but another weird issue appeared. maybe its related to my MAMP Pro but removing the `go('/')` statement does not seem to stick. even restarting apache and chrome did not help.

**Comment by distantnative** [comment]
I am not sure if I understand your problem completely. What do you mean with "it does not stick"?

**Comment by bnomei** [comment]
1) i added `go('/')` to my template. refreshed browser. got redirected to `/`. OK.
2) **removed/uncommented** `go('/')` from my template. still got redirected to `/`. Not OK.
3) ran composer on plugin (since template is in plugin). restarted MAMP app and apache service and chrome. Still getting redirected to `/`.

edited: well it's just happening in chrome. clearing cache helped. firefox dev seems fine.
