### ISSUE TITLE
Kirby 2.3 - Thumbnail 404

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#417]
https://forum.getkirby.com/t/kirby-2-3-thumbnail-404/3821

**Comment by bastianallgeier** [comment]
Could you send me a copy of your site to test this with?

**Comment by jenstornell** [comment]
I've sent a mail to bastian@getkirby.com with a link to a ZIP file.

I forgot to empty the `thumbs` folder. For this issue it probably does not matter, but for the other thumb issues it might.

**Comment by bastianallgeier** [comment]
Should be fixed by the move to the old way of generating thumbs
