### ISSUE TITLE
[Plugins] loading order of plugins

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#419]
how to make one plugin require another being loaded? and how to trigger load if it has not been loaded? in K2 that was possible.

**Comment by jenstornell** [comment]
Yes. It was an undocumented feature in Kirby 2. Maybe make it more official this time. Maybe even improve it, like setting dependecies in the plugin call?

**Comment by bastianallgeier** [comment]
Let's merge this with the other composer / plugin ticket: https://github.com/k-next/kirby/issues/762
