### ISSUE TITLE
Hardcoded extension in AbstractPage::intendedTemplateFile

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#420]
I’m writing a template component and by defining the `file` method most template-related methods from `AbstractPage` seem to be behaving correctly, except `AbstractPage::intendedTemplateFile`.

My code:

```php
class TwigComponent extends Kirby\Component\Template {
	public function file($name) {
		$base = $this->kirby->roots()->templates() . DS . str_replace('/', DS, $name);
		$twig = $base . '.twig';
		$php  = $base . '.php';
		if (is_file($twig)) return $twig;
		elseif (is_file($php)) return $php;
		return $twig;
	}
}
```

This gives me the expected result for all of those methods of `AbstractPage`:

- `template`
- `templateFile`
- `templateData` (not exactly sure what it does, always returns an empty array?)
- `intendedTemplate`
- `hasTemplate`

But not for this one, which hardcodes the implementation in `AbstractPage`:

- `intendedTemplateFile`

**Comment by bastianallgeier** [comment]
It's now fixed on the develop branch
