### ISSUE TITLE
New Thumbs API - Respect option "thumbs.filename"

### ISSUE THREAD

**Issue by mbecher** [getkirby/kirby#421]
In v2.3 beta it looks like the filename of thumbs is hardcoded in 'kirby/component/thumb.php' with the query string appended and the option "thumbs.filename" ignored. I prefer having the filename under control.

**Comment by jenstornell** [comment]
+1

**Comment by bastianallgeier** [comment]
I have changed the behavior how the filenames are generated. The pattern is now for example: 

```
thumbs/some/page/myimage-w300-h200-q80.jpg
```

I think in general thumbs should be stored in the most readable way and also with the new structure they are now better connected to their original source and can be detected/deleted by the panel etc. 

In this scenario, the filename option would be quite tricky to implement. What would you want to change with it?

**Comment by jenstornell** [comment]
Sorry about mentioning WordPress again, but I like their shorter more readable syntax.

**Kirby**
```
image-w300-h200-q80.jpg
```

**WordPress**

```
image-300x200.jpg
image-300.jpg
```

The last one is only resized by width.

1. If it's `300x200` most people understand that the first is width and the second is height. At least WordPress users does.
1. Do we really need quality in the filename?

I really like that the thumbs are generated in a page folder structure. It has many benefits. I also think it was wise to go back to the old thumb generation in general.

**thumbs.filename**: I don't think it's that important to keep this option. What I do think is important is to think about the generated filename a few times, to get the syntax really perfect so there is no need to change it too much during time in future versions.

**Comment by mbecher** [comment]
Personally, I store thumbs at `/some/page/img/myimage_w300.jpg`. I just need the width here for serving different sizes in the srcset attribute of an `img` tag. In a client gallery with about 80 images, this saves quite a few bites, since in every `img` tag there are at least 5 image sources. Also I need the thumbnails to be stored within the pages folder, so they are protected by that pages .htaccess file.

More generally, I do think it is just convenient to have that option and keep with it, as others might have their reasons to rely on these, too.

To be straight to the point, I do store thumbnails like this:

```
c::set('thumbs.destination', function($thumb) {

    if (trim($thumb->source->filename()) != false ) {

        $width    = $thumb->options['width'];
        $page     = $thumb->source->page();
        $filename = $thumb->source->name()
                    .'_'. $width .'w.'
                    . $thumb->source->extension();
        $root     = $thumb->options['root']
                    .DS. $page->uri() .DS. 'img'
                    .DS. $filename;
        $url      = $thumb->options['url']
                    .DS. $page->uri() .DS. 'img'
                    .DS. $filename;

        dir::make(dirname($root));
        return new Obj(array('url'=>$url, 'root'=>$root));

    }

});
```

which just broke, when I tried the beta …

**Comment by bastianallgeier** [comment]
@jenstornell for once I agree with Wordpress :) I just changed the filenames again. Having the width and height entirely in the filename has a second benefit of being able to strip out the crop param and find better matches. 

@mbecher I see. This is pretty edge-casey though. It will still be possible by adding your own thumb component. It's not as straight forward as an option, but in this case I really believe it's better to not offer the option anymore.

**Comment by mbecher** [comment]
@bastianallgeier Sorry for being edge-casey, but that would be a minor version bump, which would break a valid setup. Am I right?

**Comment by bastianallgeier** [comment]
@mbecher sorry for being a bit rude about this. Of course you are right with the version. We try to stick to the general idea of semver for version numbers, but it turns out to be really tough for Kirby, when we want to move on with features without bumping Kirby to major version 45. So far we handled it internally like this: 

{major release}.{features}.{patches}

where new features can potentially lead to breaks. Especially with all the possible configurations, server setups, plugins and extensions, we weren't 100% able to avoid them so far. 

In this case I thought it's not a big deal, because you can simply use the component to get what you want, but of course it leads to extra work. I will try to find a solution that makes the upgrade painless.

**Comment by mbecher** [comment]
@bastianallgeier sounds good. Thanks for taking care of it. Don't get me wrong, I really like the idea of the new thumbs API. I just wanted to chime in and say "please, don't go to fast with this, somebody is here who cares about this option". I really like kirby for what it does and -- especially -- what I can do with it. I'm also looking forward to the new API.

Let me know, if I can help …

**Comment by bastianallgeier** [comment]
I just reimplemented both. 

@mbecher you could do me a favor by pulling the latest version from the develop branch and test it with your setup.

**Comment by mbecher** [comment]
@bastianallgeier unfortunately it does not work.

With my custom `tags/image.php` I get just the raw kirby image tag in html.

To simplify, if I remove that custom image handling and put the following line in my template:

```
<?= thumb($page->image('image.jpg'), array('width' => '116'))->url(); ?>
```

I'll get:

```
Fatal error:  Uncaught exception 'Exception' with message 'Thumbnails cannot be modified further' in {path}/library/system/kirby/traits/image.php:23
Stack trace:
#0 {path}/library/system/helpers.php(322): FileAbstract-&gt;thumb(Array)
#1 {path}/library/templates/home.php(10): thumb(Object(File), Array)
#2 {path}/library/system/toolkit/lib/tpl.php(22): require('{path}/...')
#3 {path}/library/system/kirby/component/template.php(85): Tpl::load('{path}/...', NULL, true)
#4 {path}/library/system/kirby.php(618): Kirby\Component\Template-&gt;render(Object(Page), Array)
#5 {path}/library/system/kirby.php(606): Kirby-&gt;template(Object(Page), Array)
#6 {path}/library/system/kirby/component/response.php(29): Kirby-&gt;render(Object(Page))
#7{path}/li in /library/system/kirby/traits/image.php on line 23
```

**Comment by bastianallgeier** [comment]
Would it be possible to get a copy of your project? bastian@getkirby.com

**Comment by mbecher** [comment]
Just sent you a zip file …

**Comment by jenstornell** [comment]
I hope these old kept options does not prevent the future Kirby development in any way. If it does, I don't think it's worth keeping them.

**Comment by bastianallgeier** [comment]
Don't worry. It won't affect it. I just pimped the default component to support it again. Since the components can have/support totally diffferent options, it doesn't mean that thumb plugins have to support them again. For example if you want to write an Imgix plugin, it wouldn't make any sense at all to support the destination and filename options for thumbnails which will be generated on an imgix server anyway.
