### ISSUE TITLE
New Thumbs issue: & vs. &amp;

### ISSUE THREAD

**Issue by gerritvanaaken** [getkirby/kirby#422]
On my local MAMP server, all is fine. The generated thumb can be delivered as:

`http://localhost/thumbs/my_folder/my_file@w=300&q=90.jpg`

However, on our demo web server the URL has to be

`http://localhost/thumbs/my_folder/my_file@w=300&amp;q=90.jpg`

to work correctly. But this is not how the image url being rendered.

**Comment by lukasbestle** [comment]
Hm, actually this should be an HTML issue, not an issue with the server, so I'm surprised that it works with one but not the other server.
How are you generating the thumbnail? Are you manually echoing the thumb URL inside the `src` attribute?

**Comment by gerritvanaaken** [comment]
Interestingly, on our demo server, the actual physical filename looks like this:
```slider1@w=1600&amp;q=90.jpg```

These files are being generated by the following command in the "home.php" page template:
```<?= $site->find('home')->files()->find('slider1.jpg')->width(1600)->url() ?>```

**Comment by gerritvanaaken** [comment]
Somewhere in the file writing process, there must be an ampersand encoding function involved. That would not be a problem if the requested image url was the same as the physically generated image on the file system.

**Comment by bastianallgeier** [comment]
I moved back to generating thumbs without the API. It made too many problems. There's still the improved way of storing files in 2.3.0 and a couple new thumb methods. I will write more about it soon. But this should fix the ampersand issue as well.
