### ISSUE TITLE
Set controller site does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#423]
Kirby 2.3

```php
$kirby->set('controller', 'site', __DIR__ . DS . 'site.php');
```
>
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'You are not allowed to set the site controller' in D:\xampp\htdocs\nightly\kirby\kirby\registry\controller.php:38
Stack trace:
#0 [internal function]: Kirby\Registry\Controller-&gt;set('site', 'D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\nightly\kirby\toolkit\helpers.php(270): call_user_func_array(Array, Array)
#2 D:\xampp\htdocs\nightly\kirby\kirby\registry\entry.php(68): call(Array, Array)
#3 D:\xampp\htdocs\nightly\kirby\kirby\registry.php(100): Kirby\Registry\Entry-&gt;call('set', Array)
#4 [internal function]: Kirby\Registry-&gt;set('controller', 'site', 'D:\\xampp\\htdocs...')
#5 D:\xampp\htdocs\nightly\kirby\kirby.php(136): call_user_func_array(Array, Array)
#6 D:\xampp\htdocs\nightly\site\plugins\test\test.php(4): Kirby-&gt;set('controller', 'site', 'D:\\xampp\\htdocs...')
#7 D:\xampp\htdocs\nightly\kirby\kirby.php(435): include_once('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\nightly\kirby\kirby.php(405): Kirby-&gt;plugin('test', 'dir')
#9 D:\xampp\htdocs\nightly\kirby\kirb in <b>D:\xampp\htdocs\nightly\kirby\kirby\registry\controller.php</b> on line <b>38</b><br />

**Comment by lukasbestle** [comment]
What is your use-case for this? The issue here is that there can currently be only one controller per template, so only one plugin (or the `site/controllers` directory) can set a controller.

But unless I've missed something here, we could maybe actually allow multiple controllers here. @bastianallgeier, what do you think?

**Comment by jenstornell** [comment]
I do not need it anymore. The new pages methods are better for my case.

I agree we could have more than one site controller or any other but what will happend If two exists? One is overwritten by the other or will it merge them?

**Comment by lukasbestle** [comment]
As I said, they would merge. If they define different variables, all of them will be available and if they define the same variable, they will overwrite each other.

**Comment by bastianallgeier** [comment]
I don't think this is a good idea. How would you decide which one comes first and what happens with the merged data. You could never be sure of the outcome.

**Comment by jenstornell** [comment]
@bastianallgeier 

Because there is no global controller that is not a just a fallback I needed to create this:
https://github.com/jenstornell/kirby-pre-controller

A really simple case that is much harder to solve than it first seems.

>How would you decide which one comes first and what happens with the merged data.

Like plugins, overwrite them in the order they come in. It would probably work well when plugins prefix their controller data to prevent collisions.

```php
return function($site, $pages, $page) {
  return array(
    'splitview_token' => 'ABC123',
    'splitview_field_key' => 'shredder',
  );
};
```

**Comment by lukasbestle** [comment]
We should discuss merging controllers in general in this issue: #429
