### ISSUE TITLE
[Cms] Transfer translations from v2

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#424]
- [x] Remap Transifex language keys (https://airtable.com/tbl0f9q7zEYNArNkU/viwfXrrMUMnmBXZeL)
- [x] Add remapped translation files
- [x] Setup Transifex for v3

**Comment by distantnative** [comment]
@bastianallgeier If I understand Transifex correctly, remapping language keys will not work. If a source key is not exactly as before, it will get added as new. Old resource strings not present in the new translation, will be removed (but still preserved in the Translation Memory). And Transifex does not seem to accept that we manually remap other language's file. It only accepts the source language file and will work accordingly.

Only thing it their Translation Memory that supposedly will help to easily add back same/similar translations from before. If they are an exact match, even automatically:
<img width="918" alt="screen shot 2018-04-14 at 13 42 48" src="https://user-images.githubusercontent.com/3788865/38767874-30b4d1c6-3fea-11e8-9f51-05f320499e99.png">

But I am hesitant to test it. Too afraid to ruin/loose the previous translations.

https://docs.transifex.com/projects/updating-content/#what-happens-when-you-update-files

**Comment by lukasbestle** [comment]
We could create an entirely new Transifex project and reimport our manually remapped translations.

**Comment by distantnative** [comment]
Started to match v2 and v3 keys: https://airtable.com/tbl0f9q7zEYNArNkU/viwfXrrMUMnmBXZeL

**Comment by distantnative** [comment]
Gotta correct myself: We can upload our manually updated language files. So all easy.

**Comment by bastianallgeier** [comment]
✅
