### ISSUE TITLE
Site models

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#424]
Just like site controllers, add site models, where `site.php` is for the whole site.

**Comment by lukasbestle** [comment]
We have added "page methods" to the 2.3 beta, see #212. You can set global methods that will be called if neither the default `Page` class nor the template-specific model has a method. There's already documentation for this, but it is not yet live.

**Comment by jenstornell** [comment]
After some testing I needed pages methods and it worked great even when having a controller on top.

**Comment by dweidner** [comment]
The advantage of a site model, would be, that implemented methods would be only accessible from the site instance. I find myself frequently adding fields to the site blueprint, like a structure for the primary and secondary menu. It would be nice to cleanup my templates by providing methods that make these menu entries accessible. Currently I have to add the logic to the template file or to  a separate helper function.

**Comment by lukasbestle** [comment]
You can set page methods on the site class directly, then they should only apply to the site object.

**Comment by dweidner** [comment]
Yes, that is indeed a workaround I haven't thought of.
