### ISSUE TITLE
Kirby 2.3 – Omit file_exists() checks in registry

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#425]
The registry class in Kirby 2.3 currently checks for the existance of files and directories when calling registry functions like `$kirby->set('snippet', 'pagination', 'snippets/pagination.php')`. To reduce file system calls (to increase performance), I think those checks should only be activated in debug mode. What do you think?

```php
if(c::get('debug') && file_exists($path)) {
  return static::$templates[$name] = $path;
}
```

**Comment by lukasbestle** [comment]
I agree with you here. The check should happen when the file is requested, not when it is registered.

However the code needs to be:

```
if(!c::get('debug') || file_exists($path)) {
  return static::$templates[$name] = $path;
}
```

Otherwise the if condition would always equal `false` if debug mode is not enabled.

**Comment by fabianmichael** [comment]
Oops! You’re right, thanks for the correction & addition.

**Comment by bastianallgeier** [comment]
I just fixed this in all components
