### ISSUE TITLE
[Cms] Page 10 shows after Page 1

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/kirby#428]
The sorting seems to be broken if there are more than 10 pages.
The 10th page (`10.project-10/`) shows after the 1st page (`1.trees-and-stars-and-stuff/`).

Tested wit MAMP (PHP 7.1.8, Apache)

<img width="1440" alt="bildschirmfoto 2018-04-17 um 07 00 33" src="https://user-images.githubusercontent.com/1524319/38849590-1366c6c2-420d-11e8-879a-21e358b0dfb9.png">

<img width="329" alt="bildschirmfoto 2018-04-17 um 06 49 14" src="https://user-images.githubusercontent.com/1524319/38849484-7e1601fa-420c-11e8-9156-ec63db6278ec.png">

**Comment by bastianallgeier** [comment]
✅
