### ISSUE TITLE
site.php controller: Merge variables with the ones of custom controllers

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#429]
Currently the site.php controller is just a fallback if no template-specific one exists. I think we could instead merge the variables from the site.php controller with the template-specific one so that the specific one can overwrite variables from the site controller.

Also see [this post](https://forum.getkirby.com/t/kirby-pre-controller/3902/5?u=lukasbestle).

**Comment by texnixe** [comment]
Yes, please.

**Comment by jenstornell** [comment]
+100

**Comment by texnixe** [comment]
```
$i = 1;
while ($i <= 100) {
    $jens = new Jens();
    $newClone = clone $jens;
}
```

**Comment by lukasbestle** [comment]
From Bastian in the other issue:

> I don't think this is a good idea. How would you decide which one comes first and what happens with the merged data. You could never be sure of the outcome.

**Comment by texnixe** [comment]
That is a good point and probably the reason why it was implemented otherwise in the first place.

It would only work if the specific controller overwrites the general controller, in case the same variables are used. But I can imagine that it can get tricky.

**Comment by bastianallgeier** [comment]
As a quite good compromise you should be able to do this with the new architecture: 

```php 
return function($site, $pages, $page) {

  $base = kirby()->get('controller', 'base');
  $data = $base($site, $pages, $page);

  // add some custom data
  $data['custom'] = 'yay';

  return $data;

};
```

**Comment by lukasbestle** [comment]
That's a great idea! I think this is quite flexible and can't be used by accident. So in my opinion: Issue solved.

**Comment by jenstornell** [comment]
I'm not sure what this does.

1. What is a base controller? Is it any custom controller or some built in thing?
1. Can plugins register global controller data with it?

**Comment by bastianallgeier** [comment]
1. The base controller could be something you create on your own, or a plugin provides it. It's basically just another controller. You can also use this to call one controller from another controller. 

2. Nope. You would need to specifically call it like this.

But I think what you are looking for is actually a global way to pass content to templates, which is already possible since version one with Kirby's template class: 

```php 
tpl::$data['someKey'] = 'some data';
```
This makes $someKey available in all templates, snippets, etc. 

But of course this can lead to a lot of pollution again.

**Comment by jenstornell** [comment]
I've had the same issue for so long so I will try to explain it as simple as possible...

### Inside a plugin

The code below run **before** the template on **all pages**.

```
If( $page->status() == 'unpublished' ) {
  go('error'):
}
```

After that the **template** loads.

### Problems

- Plugins when they run are not aware of the `$page` object.
- Routes are not aware of the `$page` object.
- Controllers can not be run globally, not even the site controller.

The only solution seems to be to add a function right before `doctype` in the template, which is not pretty.

My [pre-controller](https://github.com/jenstornell/kirby-pre-controller) does the same thing. I really hope some day I will not need that plugin.

**Comment by jenstornell** [comment]
Here are 6 forum posts that all relates to this. I've probably added more but it shows how often I run into this problem.

https://forum.getkirby.com/t/hook-between-init-and-template/1466
https://forum.getkirby.com/t/shared-controller/1839
https://forum.getkirby.com/t/shared-controllers/1112
https://forum.getkirby.com/t/functions-unable-to-load-the-page-object/1081
https://forum.getkirby.com/t/why-i-miss-wordpress-just-a-little-bit/2352
https://forum.getkirby.com/t/kirby-pre-controller/3902

**Comment by jenstornell** [comment]
Finally solved!

https://github.com/jenstornell/kirby-init-controller
