### ISSUE TITLE
[Panel] Support for built-in PHP server

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#43]
The current version of the Panel is not working when running the starterkit with the built in PHP server.

**Comment by bastianallgeier** [comment]
That is almost solved, except the annoying file routing issue in the PHP server. I wonder if we need to ship a router.php with it, like @fabianmichael does for the website. But I somehow would love to not do it.

**Comment by fabianmichael** [comment]
It seems that you need a custom router as soon as you want to serve …

- Any path with a dot in its filename that does not point to an existing file (I fixed the server’s default behavior of filling some `$_SERVER` variables with wrong values/omitting them as soon as the requested filename contains a dot. This is also necessary for using the content representations feature.)
- A file where PHP’s server does not know the correct mime type for given file type/extension. In this case, you have to set them manually from `router.php`.

**Comment by bastianallgeier** [comment]
✅
