### ISSUE TITLE
toURL

### ISSUE THREAD

**Issue by illycz** [getkirby/kirby#432]
If I understand right, $field->toURL() transform field value from "Some Value" to "some-value"?
But when I try this, the value is still the same. I try it within some custom fields and also within page title.

Is it possible transform text (like page url maker in panel) if I undersand this functionality bad?

Thanks for explanation...

**Comment by illycz** [comment]
Maybe like this?

<?php echo str::slug($page->title()) ?>

**Comment by lukasbestle** [comment]
The `$field->toURL()` method does the same as `url($field)`. It does not create a slug out of the value, instead it returns an absolute URL for a given URI that is stored inside the field.

You can easily define a field method that runs `str::slug` yourself. Please put this code into a file in the `site/plugins` directory:

```php
field::$methods['toSlug'] = field::$methods['slug'] = function($field) {
  return str::slug($field->value());
};
```

You can then use `$page->title()->toSlug()`.
