### ISSUE TITLE
[Panel] Left and right arrow keys throw error

### ISSUE THREAD

**Issue by seehat** [getkirby/kirby#434]
The error`t.srcElement is undefined` gets thrown when pressing the left or right arrow key on page edit screen. 

For example on the page `Content in Kirby`. On this page only the left arrow key throws this error.

This is also true if a textfield or area has focus, which makes navigating the text difficult.

**Comment by distantnative** [comment]
Could you let us know which browser/system you are using?

**Comment by seehat** [comment]
I'm using Firefox 59.0.2 on OSX 10.3.3. It's working in Chrome.

**Comment by distantnative** [comment]
✅
