### ISSUE TITLE
Kirby 2.3 – Blueprints registered by plugins

### ISSUE THREAD

**Issue by flokosiol** [getkirby/kirby#434]
A blueprint registered by a blugin like this …
```php
$kirby->set('blueprint', 'myblueprint', 'blueprints/myblueprint.yml');
```

… is not considered by pages with a setting like …
```
pages: true
```

But it works if the blueprint is assigned explicitly like …
```
pages:
  template: 
    - myblueprint
    - some
    - other
    - blueprints
```

See [forum post](https://forum.getkirby.com/t/kirby-2-3-0-beta/3809/40?u=flokosiol)

**Comment by flokosiol** [comment]
Immediately after submitting the issue, I'm not sure if https://github.com/getkirby/panel/issues would have been the better place to submit …

**Comment by lukasbestle** [comment]
I have moved this issue to getkirby/panel#840. Thanks for reporting the bug.
