### ISSUE TITLE
$content($lang)->exists() does not seem to work as expected

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#435]
https://forum.getkirby.com/t/multilingual-menu-and-tagclouds/3961/2

Or maybe this is not supposed to work with the language code? If so, I need to change the docs (again)

Edit: I tested this again by removing everything from a content folder, but the method still returns true, even without a language code.

So it seems the methods of the content class do not return what they should return, e.g. `$page->content()->root()` does return the content folder instead of null or false if the content file is missing; `page->content()->name()` the name of the folder if the folder is empty.

**Comment by bastianallgeier** [comment]
You are right. It was totally borked. I just fixed it on the develop branch.
