### ISSUE TITLE
[Cms] Core components collisions

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#435]
I've mentioned it before somewhere with Kirby 2.

Let's say we have two plugins that are using the same component for example `response`.

They can't.

Instead one of the plugins will run, but not the other.

Before I've heard from any of you that such scenario is so small, it's almost non existing.

I run into this issue again, today.

**I use two of the most brilliant Kirby plugins on the web (if you ask me):**

- https://github.com/jenstornell/kirby-time-cache
- https://github.com/jenstornell/kirby-html-minifier

But no. The can't be used at the same time. Both are using the `response` component.

## Possible solution

Hooks can be used anywhere and if we could use hooks in the components to filter the data on common used places it would open up some new possibilities.

With filter I mean something like this:

```php
$kirby->set('filter', 'responseOutput', function($filter) {
  return $filter . ' bye bye';
});
```

Then there is always the "order of things" problem but the first loaded plugin gets to filter first. At least as long as we can't decide the order of the plugins.

## Question

I'm aware that you often say no to solve complex problems like this, but if it will not be solved, how should we deal with it? What could I do in my case, that is not a hack?

**Comment by jenstornell** [comment]
Because I needed to solve this issue now, I hacked together a solution that will work for now.

I removed the core components (response) from the plugins completely. Then I created a new plugin.

## kirby-component-filters.php

In a more solid solution I should have put the `$kirby-set` part in an own plugin as it's unique for each project.

```php
<?php
// Should not be needed if it would be a core feature

include 'filter.php';
include 'response.php';

// If it was a core feature, then a single filter in each plugin could be used.
// The next plugin could filter it as well as it falls down.
// Then there would be no need to register a core component in this case.

$kirby->set('filter', 'response', function($html, $format = null) {    
    // Skip JS and CSS files
    if(in_array($format, ['js', 'css'])) return $html;

    // Skip if no HTML is present
    if(empty($html)) return '';

    // Minify HTML
    if(c::get('plugin.html.minifier.active', true)) {
        $html = TinyMinify::html($html, c::get('plugin.html.minifier.options', []));
    }

    // Cache page
    if(c::get('time.cache.pages', true)) {
        $TimeCache = new TimeCache();
    }

    // Get cache filepath
    $relative_url = str_replace(url::index(), '', url::current());
    $filepath = $TimeCache->filepath($relative_url);

    // Add cache comments
    if(c::get('time.cache.pages.comments', false)) {
        $text = "<!--Cached " . date('Y-m-d H:i:s') . "-->";
    }

    // Cache page
    $html = time::cache($relative_url, function() use ($html, $text) {
        return str_replace('</html>', "\n" . $text . "\n</html>", $html);
    }, c::get('time.cache.pages.expires', 86400));

    return $html;
});
```

## filter.php

```php
<?php
namespace Kirby\Registry;

class Filter extends Entry {
	protected static $entries = [];

	public function set($response, $path) {
		static::$entries[$response] = $path;
	}
	public function get($response = null) {
		return static::$entries[$response];
	}
}
```

## response.php

```php
<?php
class FilterResponse extends Kirby\Component\Response {
    public function make($response) {
        if(is_string($response)) {
            return $this->filter($this->kirby->render(page($response)));
        } else if(is_array($response)) {
            return $this->filter($this->kirby->render(page($response[0]), $response[1]));
        } else if(is_a($response, 'Page')) {
            return $this->filter($this->kirby->render($response), $response->format());
        } else if(is_a($response, 'Response')) {
            return $this->filter($response);
        } else {
            return null;
        }
    }

    private function filter($html, $format = null) {
        global $kirby;
        return call($kirby->get('filter', 'response'), $html, $format);
    }
}

$kirby->set('component', 'response', 'FilterResponse');
```

## Pitfalls

There are some pitfalls with my solution, because I made it very quickly.

1. I can't use `$kirby->set` in the config file. Therefor a `c::set('filterResponse', function() {})` may be better in some scenarios.
1. I can't set `$kirby->set('filter')` more than one time else it will be overwritten. Therefor I have put all things that should happen in a single filter.

To make it a useful core feature I think both of the above needs to be solved.

## Summery

You can probably see what the code does already. I use this code to filter the response html:

```php
$kirby->set('filter', 'response', function($html, $format = null) {
    return 'Hello ' . $html;
}
```

A dream would be to just do like the code above inside each plugin to filter the data without hijacking the core component completely and leaving it for the next plugin to continue to filter.

**Comment by bastianallgeier** [comment]
I think we solved the only situation where this really makes sense with the route.before and route.after hooks. But otherwise I don't think it makes sense to overcomplicate the core components with the option to run multiple plugins there at once.
