### ISSUE TITLE
site.yml does not see plugin section blueprints anymore

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#436]
I am using develop branch of kirby and panel. 

I have a plugin registering a section blueprint and it is used in `site.yml`. the `site.yml` is not provided by the plugin. about a week ago the `site.yml` did find the section blueprint from the plugin. today it does not anymore and the following error is displayed.

```
The mixin "sections/my-section" could not be found
```

Edited: or maybe its not loading any plugin blueprints at all. I assume the structure for the plugin config changed more than i could figure out – apart from providing the plugin name as a string before the array.

Edited 2: underestimated changes in dev branch. localisation etc seems broken as well. maybe i am missing files in `/site`. anyway reverting back to my "stable" version. feel free to close this issue if you know this issue is fixed in your workspace.

**Comment by distantnative** [comment]
The syntax how to register plugins has been simplified a bit, e.g. the first parameter now is the plugin name:

```php
Kirby::plugin('distantnative/test', [
    'blueprints' => [
        'sections/my-section' => __DIR__ . '/section.yml',
    ]
]);
```

Let me know, if it still does not work for you with this syntax.

**Comment by bnomei** [comment]
I reverted back to alpha9. will adapt my test plugin once next alpha/beta is release and report back if i can not get it to work then. but thanks for explaining.

**Comment by distantnative** [comment]
In general a good idea to stick to the alpha/beta releases – they contain enough bugs, using some in-between state from the develop branch really can kill everything. ;)
