### ISSUE TITLE
[Ui] Checkboxes headline click toggles first checkbox

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#439]
I just saw this:

https://codepen.io/bastianallgeier/pen/OZyXoM

When clicking around on the field headlines, the field sometimes gets focused which is nice.

When clicking the "Toggle" headline it does not only focus the field but also changes the value of that field. It's the only field that does this. All the other just sets focus or do nothing so I don't think this is expected behaviour.

**Comment by bastianallgeier** [comment]
It's actually the expected behavior. The toggle field is built on top of a native HTML checkbox input. Checkboxes do the same if they are triggered via a label.

**Comment by jenstornell** [comment]
Before I give up on this issue I will give it one more try. This time on the checkboxes field which has the same issue.

This is a bit strange?

![checkboxes](https://user-images.githubusercontent.com/927011/40611048-11c8eff6-6275-11e8-91a2-5a7899a62a6a.gif)

I agree that a label should connect to a checkbox, but in this case I think it's more a like a fieldset than a label. Like this:

![image](https://user-images.githubusercontent.com/927011/40611123-6051af28-6275-11e8-8aa1-0d4159962cd4.png)

Screenshot from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Using_checkbox_inputs

So for single checkboxes, a label click is fine, but on multiple checkboxes it's weird.

**Comment by distantnative** [comment]
I agree with Jens here. With multiple checkboxes, this is weird. Especially since the actual label of a checkbox is the text to the right of the checkbox.

**Comment by distantnative** [comment]
Could be solved via
<img width="807" alt="screen shot 2018-06-20 at 12 15 33" src="https://user-images.githubusercontent.com/3788865/41652552-b3c7a5fc-7483-11e8-8363-59a825900f91.png">

**Comment by bastianallgeier** [comment]
✅
