### ISSUE TITLE
Kirby 2.3 beta: Wrong MIME types for plugin assets

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#441]
In the 2.3 beta, plugin assets are delivered with a wrong MIME type.

```php
<?= css('assets/plugins/oembed/css/oembed.css') ?>
```

leads to the following error without the CSS being loaded:

```
Did not parse stylesheet at 'http://dev:8888/Kirby/testembed/assets/plugins/oembed/css/oembed.css' because non CSS MIME types are not allowed in strict mode.
```

A quick fix is to replace the following in `kirby/kirby.php`(lines 313-315):
```php
if($file->exists()) {
  $file->show();
}
```

with

```php
if($file->exists()) {
  return new Response(f::read($root), f::extension($root));
}
```

But maybe this needs rather be fixed in $file->show() etc..

**Comment by bastianallgeier** [comment]
Fixed it with your suggestion for now. Don't fully understand what's the issue with the show method. Need to double-check for the next version.

**Comment by bnomei** [comment]
i still have this issue using kirby 2.3.0.

```
[Error] Did not parse stylesheet at 'http://www.DOMAIN.de/panel/plugins/css?v=2.3.0' because non CSS MIME types are not allowed in strict mode.
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (js:1)
```
