### ISSUE TITLE
Allow site class in Kirby\Registry\Method

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#443]
I’d like adding a few methods to the `$site` object for use in templates.

This works:

```php
Site::$methods['foo'] = function(Site $site) {
  return 'bar';
};
```

but this doesn’t (in 2.3 — develop branch):

```php
$kirby->set('site::method', 'foo', function(Site $site) {
  return 'bar';
});
```

Reason is: the `Kirby\Registry\Method` doesn’t whitelist the Site class:

```php
class Method extends Entry {

  /**
   * List of allowed subtypes
   * 
   * @var array $subtypes
   */
  protected $subtypes = ['page', 'pages', 'file', 'files', 'field'];

```

Use case for methods on the `$site` object:

- Transforming data from `content/site.txt`
- Methods that use data from other $site methods
- Every time it makes more sense to add to $site rather than to $page

Me, I’m also abusing it a little because I’m using site methods to pass one or two functions to Twig templates. It still kind of make sense, like I wrote a `$site->asset()` method for cache-busting. But it’s more of an edge case.

**Comment by bastianallgeier** [comment]
Just implemented this on the develop branch
