### ISSUE TITLE
[Ui] DateTime field: visually separate date and time

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#443]
To visually better indicate the time within the DateTime- or the Time-Field I would append a localized string like "AM/PM" in the English version (if it's 12-hour mode) and "Uhr" in the German version.

<img width="740" alt="screen shot 2018-04-26 at 10 32 51" src="https://user-images.githubusercontent.com/3930150/39300975-de1bf468-494d-11e8-81c7-5e4a4347e490.png">

**Comment by nilshoerrmann** [comment]
👍 – I also think a separator between date and time might help. I would expect a comma between those two values for instance.

**Comment by distantnative** [comment]
If you set `notation: 12` you already get the "am/pm" select input. And the "Uhr" part can be solved via `after: Uhr`. Would that be sufficient for your idea?

<img width="522" alt="screen shot 2018-04-27 at 18 19 24" src="https://user-images.githubusercontent.com/3788865/39373378-b0140df8-4a47-11e8-8f89-da47ae508d3c.png">

**Comment by wottpal** [comment]
> If you set notation: 12 you already get the "am/pm" select input.

Oh I didn't know that. I think this is the place where "Uhr" should be placed in the German localization. Because any time has to have this postfix following the German grammar.


> And the "Uhr" part can be solved via after: Uhr. Would that be sufficient for your idea?

Not really because my idea is to make the UX of this field better for everyone by default. Right now (at least in the DateTime-field) date and time are not really distinguishable imho.

**Comment by distantnative** [comment]
I'm not so convinced about "Uhr" being added where you suggest. Thing is that all in this area usually belongs to the value of the field that ends up in the content file. E.g. am/pm is actual part of the defining value, "Uhr" would not be. However thinking more about how to make them better distinguishable or even to customize the input setup of the date component could be valuable.

**Comment by wottpal** [comment]
> E.g. am/pm is actual part of the defining value, "Uhr" would not be.

Oh really, I didn't know that.

> However thinking more about how to make them better distinguishable or even to customize the input setup of the date component could be valuable.

Maybe a grayed out dash `-` between both components 🤷‍♂️

**Comment by jenstornell** [comment]
In Sweden we write something like this:

>2008-03-21, 23:45
2008-03-21, 23.45

Not sure, but maybe we need some kind of template to get this right?

**Comment by bastianallgeier** [comment]
I will close this in favor of: https://github.com/k-next/kirby/issues/492
