### ISSUE TITLE
[Panel] Click does not work in the panel in Chrome

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#444]
I just tried Alpha 9. Close this if it has been reported before.

![table](https://user-images.githubusercontent.com/927011/39354819-cf8ec420-4a0b-11e8-94a2-853b11bf0286.gif)

Clicking on any page inside the panel does not work. It just gives a blink. May be a collision with drag.

**Comment by distantnative** [comment]
@jenstornell is the issue still existing? Tried it with Chrome for Mac (Version 67.0.3396.87) and could not reproduce it.

**Comment by jenstornell** [comment]
I'll test it again when the next alpha is released.

**Comment by distantnative** [comment]
Closing this in favor of https://github.com/k-next/starterkit/issues/445 – seems to be the same issue.
