### ISSUE TITLE
$image->thumb() raises an error (2.3)

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#444]
Using the `thumb` method on an image object with no parameters raises an error:

```php
echo $image->thumb()->url();
```

> Warning: Missing argument 1 for FileAbstract::thumb(), called in /Users/Florens/Sites/xyz/site/templates/test.php on line 3 and defined in /Users/Florens/Sites/xyz/kirby/kirby/traits/image.php on line 41
>
> Notice: Undefined variable: params in /Users/Florens/Sites/xyz/kirby/kirby/traits/image.php on line 46

but this works, copying the file in the thumbs folder:

```php
echo $image->thumb([])->url();
```

Also using the `thumb` helper doesn't have this issue:

```php
// Works fine without a params array
echo thumb($image)->url();
```

Looks like a bug.

**Comment by lukasbestle** [comment]
Yes, this is a bug. The param should be optional in the new `Image` trait.

**Comment by bastianallgeier** [comment]
Just fixed it on the develop branch.
