### ISSUE TITLE
[Panel] Click sometimes becomes a drag

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#445]
As Alpha 9 does not work in Chrome I tried it in Opera.

When clicking an image it sometimes becomes a drag. If I just by accident drag it 1px it's a drag and not a click. We need to be really steady on the hand for it to work all the times.

Maybe it's possible to trigger a click if I click or drag it 10px or less. After draging more than like 10px it can detach from the placeholder and be a drag. Then there would be no missed clicks and the drag would still work as before.

**Comment by jenstornell** [comment]
I was just about to add a new issue about that the buttons does not always work, but then I noticed that it's because of this "bug".

However I got a possible solution that may be better than my previous suggestion. Instead of making the whole item movable, add a handle. Then it's completely separated from the other actions.

I use alpha 10.

**Update**

Here is a screenshot that shows that it works... sometimes...

![button](https://user-images.githubusercontent.com/927011/40347022-0480a936-5d9f-11e8-822e-33b342c4a406.gif)

**Update 2**

The same here. It works... sometimes...

![projects](https://user-images.githubusercontent.com/927011/40347180-9ba326ae-5d9f-11e8-9907-57f52f1481c6.gif)

**Comment by distantnative** [comment]
The Sortable library (that vue.draggable is wrapping) has a `fallbackTolerance` option.

> Emulates the native drag threshold. Specify in pixels how far the mouse should move before it's considered as a drag. Useful if the items are also clickable like in a list of links.
>
>When the user clicks inside a sortable element, it's not uncommon for your hand to move a little between the time you press and the time you release. Dragging only starts if you move the pointer past a certain tolerance, so that you don't accidentally start dragging every time you click.
>
>3 to 5 are probably good values.

https://github.com/RubaXa/Sortable

**Comment by distantnative** [comment]
Actually, that option works horribly. Breaks dragging since you have to wait 2-3 seconds somehow until it starts. Even when setting it to `1`.

**Comment by bastianallgeier** [comment]
The more I work with the library the more I'm convinced we should try an alternative or find a new concept how to handle drag & drop / sorting. Maybe we need some separate kind of edit/sort mode like on iOS to stop enabling drag & drop by default.

**Comment by distantnative** [comment]
Yea, also not sure about its size to be worth it.

**Comment by distantnative** [comment]
Oh and a drag-and-drop mode might be worth considering. Cause then we could also disable (also visually) elements that cannot be sorted. Would make that clearer.

**Comment by lukaskleinschmidt** [comment]
I also noticed the opposite issue on win 10 firefox 62 where a drag becomes a click.
It does not happen all the time though.

![drag-click](https://user-images.githubusercontent.com/10027897/41763240-fee4565e-75fd-11e8-8e0e-a89b9f452f54.gif)

**Comment by distantnative** [comment]
We are switching to using drag handles which will solve this issues reliably. ✅
