### ISSUE TITLE
Default and named parameters for thumbs

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#445]
Given a file/image object retrieved like this: `$image = $page->image('test.jpg');`

The API I would find ideal would be having a config map for named thumb parameters:

``` php
c::set('thumb.aliases', [
  'default' => ['width' => 1000],
  'teaser-big' => ['width' => 400],
  'teaser-small' => ['width' => 260]
]);
```

That could be used like this:

``` php
// Both use the 'default' alias
echo $image->thumb()->url();
echo $image->thumb('default')->url();

// Use other aliases
echo $image->thumb('teaser-big')->url();
echo $image->thumb('teaser-small')->url();
```

And similarly:

``` php
// Both use the 'default' alias
echo thumb($image)->url();
echo thumb($image, 'default')->url();

// Use other aliases
echo thumb($image, 'teaser-big')->url();
echo thumb($image, 'teaser-small')->url();
```

(I’m using the term "alias" because it's used in at least one other tool I’m familiar with, but there might be a better name.)

**Comment by lukasbestle** [comment]
This is now implemented on the develop branch. The feature is called "thumb presets".
