### ISSUE TITLE
[Panel] Show what template is used

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#446]
Alright, I can't change the template for this page, but which template is used? It does not say.

![image](https://user-images.githubusercontent.com/927011/39355939-ece38e5e-4a0e-11e8-9d60-66d6b8e49acb.png)

I did not find any place where is says what template is used for this page.

**Comment by bastianallgeier** [comment]
✅ this has been solved as we no longer show the dialog when the template cannot be changed.

**Comment by jenstornell** [comment]
@bastianallgeier On this page, where can I see which template is used? I don't think I can. Even if I can't change it, it's still important information, especially as a developer.

![image](https://user-images.githubusercontent.com/927011/42757327-e538ba00-88ff-11e8-97b9-de5d6bfc92e4.png)

**Comment by REHvision** [comment]
Yes please! :wink:

**Comment by jenstornell** [comment]
Should we reopen this issue?
