### ISSUE TITLE
[Panel] Drag images between placeholders does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#447]
I expected to be able to drag an image between two image placeholders. That did not work.

![table2](https://user-images.githubusercontent.com/927011/39356041-519d6d88-4a0f-11e8-826a-770b5d1dcbd1.gif)

**Comment by distantnative** [comment]
The refined implementation of page sorting will not feature drag'n'drop across pages sections in 3.0. Therefore, I will close this one for now and open a separate feature request for 3.x for dragging between sections.
