### ISSUE TITLE
Kirby\Registry\Controller::get fails for more than 1 call

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#448]
I’m not sure how or where it fails exactly, but the same controller is only executed once. Related bug: https://github.com/fvsch/kirby-staticbuilder/issues/9

As an experiment I took this method:
https://github.com/getkirby/kirby/blob/master/kirby/registry/controller.php#L49-L76

… and changed all the `include_once` for `include`. That change fixes the problem for me in the StaticBuilder plugin, and doesn’t seem to break more conventional use of controllers.

Beyond that, I’m not sure what's happening exactly.

**Comment by lukasbestle** [comment]
Yes, that's definitely a bug. `include_once` has the strange behavior that it returns `true` on subsequent calls, so each controller can only be used once.

I think we should keep `include_once` here but cache the controller function in a class property array in memory. This would fix this issue.

**Comment by lukasbestle** [comment]
There is now a fix for this that will be in 2.3.1.
