### ISSUE TITLE
[Cms] Tags parse error in the panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#448]
I have not changed anything and this came up in the shop page in the panel.

![image](https://user-images.githubusercontent.com/927011/39356259-dee2490c-4a0f-11e8-9673-423d7b7056ba.png)

>Argument 1 passed to Kirby\Text\Tags::parse() must be of the type string, null given, called in D:\projects\devonera.se\kirby\config\helpers.php on line 47

**Comment by bastianallgeier** [comment]
✅
