### ISSUE TITLE
[Panel] Drag drop back does not work when only one item

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#449]
If I drag an item to a placeholder but change my mind and want to drag it back it's not possible when I only have one item. That's because there is no longer any placeholder.

![table3](https://user-images.githubusercontent.com/927011/39356640-d4692030-4a10-11e8-900f-76bcc9c3e483.gif)

**Comment by distantnative** [comment]
@nocksock could you give a short status update? just to see which milestone we should aim for here.

**Comment by bastianallgeier** [comment]
✅
