### ISSUE TITLE
[Panel] Drop area not visible enough

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#450]
I started draging items but I thought it did not work. That's because the drop area is barley visible. I was expecting the same green wide borders etc that's in the drop areas of images.

![image](https://user-images.githubusercontent.com/927011/39358093-3a4f8520-4a15-11e8-829c-438c145296ca.png)

In this image I can drop the product into the placeholder because I'm over it, believe it or not.

**Comment by distantnative** [comment]
I would see a difference between my action of dragging a file onto the browser vs. dragging some DOM element within my browser. Is that just my taste?

**Comment by jenstornell** [comment]
To me a dropzone is just an indicator that I can drop whatever I currently hold. May it be a file or an element. Different designs for different drop item types does not matter to me personally.

The important thing to me is that it's really visible. It does not have to be discreet, at least not when active. In the image above the dropzone is active, but it's not very visible because it looks almost like the rest of the page.

**I think a change of color is a great way to make an active dropzone, for example something similar to this:**

https://dribbble.com/shots/410923-Drop-Zone-UI

![image](https://user-images.githubusercontent.com/927011/41592423-d329a304-73bc-11e8-8774-0d2e2bcc125e.png)

**Comment by distantnative** [comment]
The refined implementation of page sorting will not feature drag'n'drop across pages sections in 3.0. Therefore, I will close this one for now.
