### ISSUE TITLE
[Cms] Remove duplicate functions like `folder::flush()` or `folder::clean()`

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#452]
https://getkirby.com/docs/toolkit/api/folder/flush
https://getkirby.com/docs/toolkit/api/folder/clean

Alias/duplicate often only introduces confusion. When should I use `flush` and when should I use `clean`?

I think it's more valid when using like `u()` instead of `url()`, because `u()` is shorter. There is a reason for it.

Anyway, clean up redundant functions if you havn't already. =)

**Comment by bastianallgeier** [comment]
✅
