### ISSUE TITLE
Thumbs in 2.3 with ImageMagick and thumb::$defaults['bin']

### ISSUE THREAD

**Issue by fatpixelstudio** [getkirby/kirby#453]
When upgrading to Kirby 2.3, and while using ImageMagick in the config as the default image engine, thumbs aren't generated anymore.

I am using this config variable:
`c::set('thumbs.driver','im');`

I found the problem to be this line:
`thumb::$defaults['bin'] = '/usr/local/bin/convert';`

Which I added on my local machine, [described in this thread](https://forum.getkirby.com/t/how-to-switch-from-gd-to-imagemagic-as-image-engine/679/7). When I remove this last line, thumbs are generated again. Is this something that maybe should be added to the docs? Or just an uncommon configuration issue?

I hope this is the right repo to submit this issue (or is this toolkit related)!

**Comment by lukasbestle** [comment]
The repo is correct as this is most likely related to the new component architecture.

Does it work if you use `c::set('thumbs.bin', '/usr/local/bin/convert');`?
And if that doesn't work, please verify that the file `/usr/local/bin/convert` exists and is executable.

**Comment by fatpixelstudio** [comment]
Thanks for your answer! 

Solved. The config variable you suggest works exactly like it should.
