### ISSUE TITLE
[Panel] Select boxes missing options

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#453]
The panel UI doesn't show select options. Clicking the arrow doesn't work, with a bit of luck it's possible to open an empty list of options by clicking in the upper half of the field:

<img width="534" alt="bildschirmfoto 2018-05-08 um 12 43 01" src="https://user-images.githubusercontent.com/25466/39752983-84024ee0-52bd-11e8-8041-c82b8ae10b2c.png">

The source features a `<select />` with `value` attributes on the `<option />` elements but without any text content. None of the different field options described in the Notion docs seems to work. 

---

This is Alpha 9, tested using latest Firefox and Chrome for Mac.

**Comment by bastianallgeier** [comment]
I think this should be fixed in Alpha 10. Could you check?

**Comment by nilshoerrmann** [comment]
Yes, I can confirm it's working. Thanks!

**Comment by nilshoerrmann** [comment]
I'm sorry, but I have to reopen this:

- Clicking the select box value does open the options list 😀
- Clicking the arrow of the select box does nothing 😔

**Comment by distantnative** [comment]
@nilshoerrmann but the other problems (empty lists etc.) have been solved? The "arrow click does not open dropdown" issue I can confirm.

**Comment by nilshoerrmann** [comment]
Yes, the others have been solved.

**Comment by bastianallgeier** [comment]
✅
