### ISSUE TITLE
One language in Kirby 2.3 config forcing default template on all pages

### ISSUE THREAD

**Issue by fatpixelstudio** [getkirby/kirby#454]
In our own Kirby starterkit named [Altair](https://github.com/studiodumbar/altair) we use the languages config variable with just one language. Like this:

```
c::set('languages', array(
	array(
		'default'   => true,
		'code'      => 'en',
		'name'      => 'English',
		'locale'    => 'en',
		'url'       => '/',
		'direction' => 'ltr'
	),
	// add another language
));
```

We use this to automatically set some locales in our templates, and have some code multilanguage ready (like sitemaps). This way, adding a language is really easy.

But unfortunately when updating to Kirby 2.3, every page will be served the default template.

In the previous version Kirby did not care the content files had no language code in the filename. But we found out Kirby 2.3 really wants something like page.**en**.md as a filename.

Is there any way to work around this issue, keeping one language in the config file, but use plain content filenames without language codes?

**Comment by lukasbestle** [comment]
If you want the site to be multilanguage-ready, you should also include the language code in the filenames.

Otherwise you could also set the locale using the `locale` option instead of using `languages`.

**Comment by fatpixelstudio** [comment]
Thank you, that sounds like the most sensible way indeed.

We will use the `locale` option for single-language sites and `languages` for multi-language sites.

Just to be sure, this is the right way to set a locale in the config, right? 
`c::set('locale','en_US.UTF8');`

**Comment by lukasbestle** [comment]
Yes. :)
