### ISSUE TITLE
Add a smartypants field method

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#455]
Hi everyone,

There are 3 helper functions for big text transformations:

- `markdown($text)`
- `kirbytext($text)`
- `smartypants($text)`

But only two matching field methods:

- `$field->markdown()`
- `$field->kirbytext()`

I was using `$field->smartypants()` in my code and kept wondering why it didn't work.
For the sake of consistency, it would be nice to add this method to a future release.

Cheers.

**Comment by lukasbestle** [comment]
This feature will be included in Kirby 2.3.2.
