### ISSUE TITLE
[Panel] Tabs aka Dropdowns

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#455]
I know this has been discussed in multiple places already, but having used the latest Alpha for a while I have to admit that the visual style for the tabs/dropsdown in Kirby's top bar doesn't work at all. I really enjoy the overall style of the Kirby 3 interface but this aspect constantly leaves me puzzled. My fear is: if I don't even understand it, our clients won't understand it either.

![bildschirmfoto am 2018-05-09 um 10 23 57](https://user-images.githubusercontent.com/25466/39803973-1ae4cfee-5373-11e8-98fe-8d9240fb50b7.png)

Let me try to explain my concerns:

### Naming and Behaviour

The feature to separate content into different views is called tabs in the blueprints but it looks like an active state in the UI and it behaves like dropdown. This is confusing in different ways:

1. When I set up a new tab in my blueprint and switch to the browser I don't see a new tab. I see three tabs: "Open", "Settings" and the name of my first tab. Any other "tab" is hidden in an invisible dropdown. But with the concept of a tab in mind I don't expect having to look for an option in a dropdown.
2. With me getting used to the word "tabs" because it's called that way in the blueprint, I will certainly use this name when introducing the panel to my clients. But again, this is not what they will see and this will make things harder for them because we are all used to the idea of tabs being always visible like in a register.

Of course it would be possible to rename this feature to something else like group that is not directly bound to the idea of an UI concept. This would solve the mismatch between name and behaviour. But there would still be a conceptual difference between the two dropdowns visible in the bar:

- "Settings" displays the title or label of the related dropdown. I understand that I have to click here to get to the settings.
- The tabs display the name of the visible tab which does not indicate any additional content in a dropdown because I already see the content related to that specific tab.

The way both dropdowns are labeled is inconsistent. 

### Visibility

The dropdown used for the tabs is space efficient which is good for small screens. But it hides something important: the forms editors are supposed to fill out. At first sight, it doesn't look like there are different views for the user to choose. There is a high probability of the editor to overlook subsequent tabs. In the current starter kit which labels the first tab as "pages" I would never have guessed that there are hidden tabs for "seo" and "social".

### Visual Ambiguity

When looking at Kirby's top bar, I see three "tabs" with the last one highlighted:

![bildschirmfoto am 2018-05-09 um 10 23 57](https://user-images.githubusercontent.com/25466/39803973-1ae4cfee-5373-11e8-98fe-8d9240fb50b7.png)

I'd expect the border with the arrow to be the possible highlight for all three visible items. So if I'd select "Settings" the panel would display all settings in the content area below the bar, now highlighting that "tab" with the border and arrow. 

This is of course not how the interface works as the user will notice after clicking an item. 

With the understanding that these items are dropdowns, there is still an open question: Why does one dropdown feature a border and arrow while the other one (settings) doesn't?

---

I don't have a simple solution for this issue. Maybe it would help to visually separate options ("Open"/"Settings") from tabs with a vertical line. Maybe it would help to show all tabs as long as they fit into the viewport, [adding a "More" dropdown](https://css-tricks.com/container-adapting-tabs-with-more-button/) besides the visible tabs, if the space gets too tight.

Thanks for listening :)

**Comment by distantnative** [comment]
✅ This should be solved with [Alpha 10](https://www.notion.so/getkirby/Alpha-10-45d42e49740648d48f3fd0c7af62ca15).

<img width="771" alt="screen shot 2018-05-14 at 09 52 26" src="https://user-images.githubusercontent.com/3788865/40011381-89806eee-575c-11e8-8766-6df54b1bb70d.png">

**Comment by nilshoerrmann** [comment]
Great 👍
