### ISSUE TITLE
$field->isEmpty() and $field->isNotEmpty() not working correctly on new image field

### ISSUE THREAD

**Issue by DavidUnzue** [getkirby/kirby#456]
When using the [isEmpty](https://getkirby.com/docs/cheatsheet/field-methods/isEmpty) or [isNotEmpty](https://getkirby.com/docs/cheatsheet/field-methods/isNotEmpty) methods with the [new image field](https://getkirby.com/docs/cheatsheet/panel-fields/image), I get a returned value only in one of both cases, namely when the condition is true.

`$page->headerImage()->isEmpty()` 
returns 1 if there is no headerImage (condition is true), otherwise returns nothing (when condition is false).

`$page->headerImage()->isNotEmpty()`
returns nothing if there is no headerImage (condition is false), otherwise returns 1 (condition is true).

I'm using Kirby 2.3.0

**Comment by texnixe** [comment]
That is standard behavior, false just returns nothing, you get the same result on e.g. a title field.

**Comment by lukasbestle** [comment]
For reference: The methods don't actually return `1` and `""` but `true` and `false`. You can see this by using `var_dump()` instead of `echo`.
