### ISSUE TITLE
[Toolkit] Why is a URL path trimmed of its leading and trailing slashes?

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#456]
I noticed that [`Path::get()`](https://github.com/k-next/kirby/blob/3.0-alpha-9/src/Toolkit/Url/Path.php#L33) trims all leading and trailing slashes.

I'd say they are part of the path and shouldn't be trimmed as some software distinguishes between `http://example.com/my-path` and `http://example.com/my-path/` (where one is expected to be a file and one a dir).

What was the original reason why trimming was added? In my opinion the best solution would be to get rid of it and adapt all parts of the code that currently expect a trimmed URL (e.g. my PR https://github.com/k-next/kirby/pull/84).

**Comment by bastianallgeier** [comment]
The Path class no longer exists and is replaced by the Uri builder class, that can also handle trailing slashes.

**Comment by lukasbestle** [comment]
@bastianallgeier Could you please check what the correct implementation for k-next/kirby#84 would be? I've rebased my implementation to the develop branch on the weekend and migrated to `Url::path()`, but that method has the same issue.

**Comment by bastianallgeier** [comment]
Could you paste a couple examples, what should be the result for the cookie path depending on the base site URL?

**Comment by lukasbestle** [comment]
Sure:

```
https://localhost          -> /
https://localhost/my-site/ -> /my-site/
```
