### ISSUE TITLE
Can't access /panel with exotic localisation

### ISSUE THREAD

**Issue by alienlebarge** [getkirby/kirby#458]
### Description

Last week I took part of the kirby Workshop with @bastianallgeier at btconf
When I tried to access `/panel`, it seems there's a problem with the translation.

![screenshot2018-05-09at20 28 02](https://user-images.githubusercontent.com/611234/39994493-cc66eb80-5779-11e8-8bc5-a32bc7de54dc.png)

Here's a video of the problem: https://d.pr/v/qtnjRW

### Ask

- Is there something wrong how I do it ?
- Could you fix it ?

### To Do

- [ ] Download [kirby-3-kitchensink.zip](https://github.com/k-next/starterkit/files/2000456/kirby-3-kitchensink.zip)
- [ ] Run it on a PHP server
- [ ] access `/panel`

### Additional Info

My system:
```
$ php -v
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

My browser language is `fr-CH`

**Comment by bastianallgeier** [comment]
Finally had the time to look into this. Can you try this without the built-in PHP server? We still have issues with it because of its weird routing behavior. We will need to write our own router for it.

**Comment by alienlebarge** [comment]
I've done a test using MAMP and it seems ok.
