### ISSUE TITLE
Last tab too long

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#459]
The new tabs looks awesome! You nailed it guys! =)

To have the tabs centered on a background works great. The first 3 tabs looks perfect.

But the forth tab looks a bit weird. It's all the way til the end which makes it both longer than the other ones and that way also prevent the text from being centered.

![image](https://user-images.githubusercontent.com/927011/40050463-dd27866e-5837-11e8-8b66-30c97f4d7950.png)

(I know I'm really steady on the hand with my paint brush tool)

**Comment by jenstornell** [comment]
![image](https://user-images.githubusercontent.com/927011/40345971-8589cdd6-5d9b-11e8-9f8b-96842b9fced7.png)

I think the above looks much better as the word is in the center of the tab and we see where it ends. To fix it you only need to undo this:

```css
.kirby-tab-button:last-child {
  border-right: 1px solid transparent;
}
```

**Comment by bastianallgeier** [comment]
There's a reason for this. The last and first tabs look good no matter how close you get to the outer border. But if we introduce borders to those tabs, you get a really weird visual effect when the gap is getting smaller. Sorry, but I have to close this.
