### ISSUE TITLE
Include empty media folder in starterkit or create it in installer

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#461]
I get this:

![localhost_panel_installation](https://user-images.githubusercontent.com/6684137/40241904-6f24e814-5abc-11e8-82fe-ef93169d643e.png)

when opening the starterkit the first time. It's easy to fix locally (just create an empty "media" folder in the root directory), but newcomers could be confused by that error message. 

I guess putting an empty one (or with a .gitkeep file) in the zip would be easiest. Or create the folder in the installer.

**Comment by bastianallgeier** [comment]
✅ The installer will now try to create all required folders and only show the message when one of them cannot be created.
