### ISSUE TITLE
Related Pages Bug [Pages field Method]

### ISSUE THREAD

**Issue by isaactopo** [getkirby/kirby#461]
Hi, I think there's a bug in 2.3.0 with the Pages field method if I try this:
https://getkirby.com/docs/cheatsheet/field-methods/pages
It breaks the page.

I tried to change to a lower Kirby version and it works fine. Thanks.

**Comment by lukasbestle** [comment]
Do you get an error message if you enable the `c::set('debug', true);` option?

**Comment by isaactopo** [comment]
Yes, I tried the `c::set('debug', true);`   and it breaks the page with no response from the server, the code from: https://getkirby.com/docs/cheatsheet/field-methods/pages
Is OK to reproduce the problem.

**Comment by lukasbestle** [comment]
Is there anything in your PHP error log?

**Comment by texnixe** [comment]
Yes, I can reproduce it and get an error message with a very long stack trace:

> PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Applications/MAMP/htdocs/new-starterkit2/kirby/toolkit/vendors/yaml/yaml.php on line 541

**Comment by fenixkim** [comment]
I've noticed that the `pages()->find($array)` with an empty array returns an error instead of a empty collection. It is possibly that is directly related with this error.

Can anybody confirm this?

**Comment by lukasbestle** [comment]
The fix for this was actually pretty simple and will be included in Kirby 2.3.1.

@fenixkim That's a separate bug, but nonetheless a bug that is now fixed as well. Thanks for letting us know. :)
