### ISSUE TITLE
[Panel] Page section has wrong URL in page links

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#464]
In the panel of starterkit alpha 10 the first link is rendered like this: 

```html
<a href="/pages/blog" class="kirby-link kirby-list-item-content">...</a>
```

notice the href argument: that should be `pages/blog` (without the first slash) or something like `/panel/pages/blog` .

The problem with this is that opening the page in a new tab doesn't work.

**Comment by bastianallgeier** [comment]
✅
