### ISSUE TITLE
[Panel] Drag'n'drop: Escape to cancel

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#466]
I dragged an item from its placeholder and then I could not place it back because it only had one item (a bug I've added before).

Anyway when need to abort a drag drop, the escape button could come in handy. Not sure if you have escape on Mac, but for example in Windows when want to abort a drag of a file we can press the escape button to abort.

**Comment by distantnative** [comment]
The drag'n'drop library we are currently using (https://github.com/RubaXa/Sortable) sadly does not support this. We are in general not too happy with the library at the moment. But also haven't found anything better (see Slack).

**Comment by distantnative** [comment]
Will tackle this when writing our own Vue wrapper for the Sortable library - which currently is an idea for 3.1.
