### ISSUE TITLE
[Panel] precompiled field plugins falsely accused of not having a template

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#467]
The panel checks if the plugins field component has a `template` property. 
Compiled components (such as those from single file components) don't have this property. Instead, they have a `render` function. 

relevant source code line:
https://github.com/k-next/panel/blob/bfee2636c37089b214246e750b8be24b7f87ab53/src/config/plugins.js#L19

maybe we could check if there's a `template` property OR a `render` function. 
```js
if (!options.template && !options.render) {
```

In the meantime, a workaround is to just set a dummy `template` property to something like `true`:
**MyField.vue**
```vue
<template>
<!-- stuff -->
</template>

<script>
export default {
  props: {
    value: Array,
    label: String,
  },
  template: true, // <-- here
}
</script>
```

**Comment by distantnative** [comment]
✅
