### ISSUE TITLE
Debug true does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#468]
If I add the following code into `header.php` I should get an error.

```php
<?= kk ?>
```

No error is generated. Instead the whole header file is not loaded.

I use alpha 10 without any other changes. In the config debug is true (everything by default).

```php
return [
    'debug'  => true,
    'routes' => [
        [
            'pattern' => 'team/(:any)',
            'action'  => function ($hash) {
                return go('team/#' . $hash);
            }
        ],
        [
            'pattern' => 'one-pager/(:any)',
            'action'  => function ($hash) {
                return go('one-pager/#' . $hash);
            }
        ]
    ]
];
```

I don't set any options in the `index.php` file. It looks like it does by default:

```php
require 'kirby/bootstrap.php';

echo (new Kirby)->render();
```

## When changing the index file

However, if I also change the index file...

```php
require 'kirby/bootstrap.php';
$base = __DIR__;

$kirby = new Kirby([
    'options' => [
        'debug' => true,
    ],
    'roots' => [
        'site'     => $base . '/core',
    ],
]);
echo $kirby->render();
```

Then debug set to true works, but only here, for example if the roots folder does not exists. The header file still don't show debug info on error.

**Comment by bastianallgeier** [comment]
✅
