### ISSUE TITLE
Respect variable types entered in content files

### ISSUE THREAD

**Issue by ponychicken** [getkirby/kirby#470]
If I add a field of the type `number` and then try to use it in php (e.g. in the width parameter of the thumb function) php will complain, as the field will hav a string value. Suggestion: Use the types specified in the yml when generating the values

**Comment by texnixe** [comment]
Kirby does not read the blueprints, they are only used in the panel. Reading the blueprints would only slow Kirby down and tie the panel to the Kirby core.

**Comment by ponychicken** [comment]
Ok, I just realized that the values are saved into the the content file fine, it's Kirby that is casting them to strings. The docs mention this: `Fields are divided by four regular dashes ---- Each field begins with the fieldname and a colon. The content of a field can be a single or multiple lines of text. You can store plain text, HTML, JSON, YAML or anything else, which can be written in plain text in a field.` 

I think the format should be specified more precisely (in which cases it what interpreted as what).

**Comment by ponychicken** [comment]
Jekyll solves it more cleanly by having a true yml block in front: https://jekyllrb.com/docs/frontmatter/

**Comment by lukasbestle** [comment]
While a true YAML format would make sure the content is stored in the correct type, it makes the content less maintainable by hand. The current format is very easy to understand.

But even if Kirby read the values with the correct type, `$page->width()` in your case would still return a field, not an integer, so you still need to cast that.

Please use `$page->width()->int()` in your templates to get the integer value, that should work just fine.
