### ISSUE TITLE
[Panel] Tag fields and browser navigation

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#471]
When deleting content inside a tag field, the browser navigates to the previous entry in the browser history as soon as all text content was removed. Expected behaviour would be no browser navigation at all.

This issue does not occur with other input fields.

---

_Kirby 3 Alpha 10, latest Firefox on Mac._

**Comment by distantnative** [comment]
✅

**Comment by nilshoerrmann** [comment]
This still happens in Firefox using Alpha 11.

**Comment by bastianallgeier** [comment]
I'm pretty sure I fixed it this time :)
