### ISSUE TITLE
Custom kirbytag containing HTML comment confuses ->kt() parser

### ISSUE THREAD

**Issue by frankrausch** [getkirby/kirby#475]
A custom kirbytag that returns HTML ending with a comment string breaks the Kirbytext `->kt()` parser for everthing that comes after the custom tag in a field.

To reproduce, create  a custom tag with this code:

```
<?php

kirbytext::$tags['customtag'] = array(
  'html' => function($tag) {
    return '<div></div><!-- x -->';
  }
);

```

… and use it in the `text` field of a page. All subsequent Markdown/Kirbytext will be ignored by the parser, for example `*italic*` will be returned as `*italic*` instead of `<i>italic</i>` (expected behavior).

I have Kirby 2.3.0

**Comment by lukasbestle** [comment]
This is not related to Kirbytags, I get the same issue if I just put that HTML into the content file directly.

**Comment by texnixe** [comment]
Too bad, on my old website I use HTML comments to divide an article into pages; that site is still on Kirby 1, seems it wasn't an issue back then :(

**Comment by lukasbestle** [comment]
@texnixe As I wrote, comments itself work, but not if on the same line right after a closing HTML tag. Closing this as this is a Parsedown issue.

**Comment by texnixe** [comment]
Oh, alright, your edit wasn't there when I posted.

**Comment by frankrausch** [comment]
I see. Thanks.
