### ISSUE TITLE
[Panel] Page title : "Site | null"

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#476]
The page title in the panel features a suffix `| null` in Alpha 10. <del>My guess is, t</del> <ins>T</ins>his is related to an unset site name. I'd expect the suffix to be just missing in this case.

**Comment by distantnative** [comment]
✅

**Comment by alexgilbertDG** [comment]
I still got this issue on a fresh new install, the panel page title get change to only "null" in the tab.

**Comment by distantnative** [comment]
@alexgilbertDG since this issue is 2 years old, would you mind opening a new separate one and provide a bit more context (version, installed plugins, config..)? Thanks
