### ISSUE TITLE
[Panel] German translation of Site

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#477]
The main page of the panel is called "Site" in English, the German translation is "Seite" (page) which sounds wrong in my eyes.

--- 

Let me continue in German.

Mich irritiert die Benennung aus zwei Gründen: Erstens, und dies ist der erbsenzählerische Teil, entspricht das englische Wort _site_ nicht dem deutschen Begriff _Seite_. Ich weiß, dass im deutschsprachigen gerne _Webseite_ und _Website_ synonym verwendet wird, aber es sind eigentlich zwei verschiedene Dinge (eine Einzelseite im Vergleich zum gesamten Internetauftritt). 

![bildschirmfoto am 2018-05-30 um 09 10 05](https://user-images.githubusercontent.com/25466/40704731-459f8450-63e9-11e8-9b32-e994540d6a34.png)

Zweitens wird nicht klar, was dieser Menüpunkt eigentlich macht, wenn man das Panel aufruft. Denn dann steht dort einfach nur "Seite". Ich muss gestehen, dass ich unbedarft an die Sache herangehe, da ich bisher keine Seiten mit Kirby umgesetzt habe und nicht weiß, was in Kirby 1 oder 2 übliche Benennungen waren, aber eventuell wäre der Begriff "Übersicht" treffender.

---

Additionally, the dropdown menu uses a page icon for _Site_ which is a bit confusing in both languages: It works perfectly in German in this case because _Seite_ means _page_ but it doesn't make sense in the broader context as the overview/summary of the entire website.

**Comment by wottpal** [comment]
"Start" could also be used as a more generic version for a lot of languages.

**Comment by wottpal** [comment]
Related https://github.com/k-next/kirby/issues/356

**Comment by bastianallgeier** [comment]
✅ This is now solved by the title in the site blueprint.

**Comment by REHvision** [comment]
Yes, the title in the site blueprint solves it almost @bastianallgeier and it's really great :+1:
But in the dropdown Menu it stills shows "Site" (in German - Nightly 3.0.0-beta-6.26)

**Comment by bastianallgeier** [comment]
In fact the title in the blueprint should change the menu label and the breadcrumb should take the site title from the site.txt. Isn't this working for you?

**Comment by REHvision** [comment]
Ahh, thanks for the clarification - now I got it and yes that's working perfectly, too :sweat_smile:
_Didn't realize that both parts are implemented and I've had `title: Site` in my `site.yml` all the time_ :D
