### ISSUE TITLE
[Panel] Structure field summaries

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#479]
A few observations regarding structure field summaries:

### Empty fields

In collapsed mode, structure fields display a summary of the content. It seems that the panel displays an ellipsis `…` in case it cannot parse the field's content which is a great indicator for the user that there is more to look at. It also displays this ellipsis in cases where the field is empty which is misleading for the user. I'd expect a differentiation here, keeping the ellipsis for unhandled content but using a dash or just leaving the summary empty to indicate empty fields for instance.

### Overflowing summaries

![bildschirmfoto am 2018-05-30 um 10 11 25](https://user-images.githubusercontent.com/25466/40707766-ef7bfa78-63f1-11e8-88ca-3d6117f12908.png)

In cases of text overflow in summaries, the panel just cuts the content. Why not use `text-overflow: ellipsis` here? This would be consistent with the indicator mentioned above.

### Sizing

It's possible to use columns of different dimensions inside structure fields. The collapsed structure field just uses equally devided columns to summarise its content. Would it be possible to somehow make use of the nested field's dimensions here as well (it's harder as it sounds, I guess)? At least in simple layouts (using only a few fields) this would make sense as a field taking 2/3 of the space for its input will most likely contain more data than the other field using 1/3 of the width.

**Comment by bastianallgeier** [comment]
I fixed the first two issues. I will create a separate ticket for the column sizing suggestion.
