### ISSUE TITLE
Add option to avoid storing language preference in cookie

### ISSUE THREAD

**Issue by Thiousi** [getkirby/kirby#479]
`c::set('language.cookie', false)`

See: https://forum.getkirby.com/t/kirby-session-cookie/4872/19

**Comment by Thiousi** [comment]
My mistake, should use `c::get('language.cookie')` instead of `$kirby->option('language.cookie')`

**Comment by bastianallgeier** [comment]
I fixed this a bit differently. The cookie is only needed when the language is being detected. So I check for that option now.

**Comment by Thiousi** [comment]
Cool way to do it. Thanks for fixing this
