### ISSUE TITLE
[Panel] Page title width

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#480]
![bildschirmfoto am 2018-05-30 um 10 28 13](https://user-images.githubusercontent.com/25466/40708609-2d7fa390-63f4-11e8-9ac5-992afdc2f240.png)

Using the wide screen layout of the panel, page titles break quite early although there is still space available. I'd expect the title to use the whole width available in order to save vertical space.

**Comment by bastianallgeier** [comment]
✅
