### ISSUE TITLE
[Panel] Breadcrumbs: capitalisation vs. lower case

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#481]
<img width="596" alt="bildschirmfoto 2018-05-30 um 10 47 50" src="https://user-images.githubusercontent.com/25466/40709845-63eb65d8-63f7-11e8-8b70-316f122bdf7e.png">

The breadcrumbs in the topbar of the panel use a mixture of capitalised and lower case titles. My guess is that the reason is to save space because slugs are expected to be shorter? It looks strange though, especially in languages that use upper and lower case a lot.

I'd expect the topbar to use proper titles as it's easier to read and more consistent. The short, URL-friendly version is always available in the address bar (although not in all browsers by default anymore, I have to admit).

**Comment by jenstornell** [comment]
@nilshoerrmann you really are on fire today. =)

But I disagree with this issue. I think the slug is more telling than the title.

From my perspective the only weird thing is that "Site" uses uppercase, but I don't have a good solution for that.

**Comment by nilshoerrmann** [comment]
Maybe it depends on the project, if slugs or titles are preferable. 
How was this handled in earlier Kirby versions?

> From my perspective the only weird thing is that "Site" uses uppercase, but I don't have a good solution for that.

I think this inconsistency makes me think the slugs are a bug.

> you really are on fire today. =)

I hope I will not be banned for spamming reasons ;)

**Comment by jenstornell** [comment]
The old Kirby 2 panel actually uses title. I was not disturbed by it then, hmm. Now I'm confused.

![image](https://user-images.githubusercontent.com/927011/40714632-7c3a1c40-6403-11e8-9184-e4eb86a46133.png)

>I hope I will not be banned for spamming reasons ;)

I don't think so. I hope the crew think that this is pure candy. They don't need to find the bugs and nags, you do it for them. =)

I would probably crack up the issue below into three issues.

https://github.com/k-next/starterkit/issues/479

## Update

This is how Github does it:

![image](https://user-images.githubusercontent.com/927011/40715021-88ec65dc-6404-11e8-9c46-cfe941122558.png)

All slugs.

**Comment by distantnative** [comment]
We also went for the slugs as they are not shown anywhere else and this way it seems like a good way to show the slugs to the user as well.

**Comment by bastianallgeier** [comment]
While I think it's a good idea to show the slug at least once somewhere, I have to agree that it looks weird to me too. I wonder how often editors actually prefer the slug over the real page title. I'm still open to change this.

**Comment by jenstornell** [comment]
In my comment above I was a bit confused of why I wanted slugs in the breadcrumb, but now I know why.

**Look at this in Kirby 2:**

![image](https://user-images.githubusercontent.com/927011/41595309-9d1197cc-73c6-11e8-8c58-e3e9c138ed70.png)

The url / `id` here is one of the most important parts for me. It shows where the page is within the hierarchy. To fine tune it is also very beneficial for SEO and CTR. (short urls and urls with click friendly words is good for SEO and CTR in general)

If you don't like the `id` to be in the breadcrumb, I hope you can squeeze it in somewhere else.

## Idea

Now you have it within the menu bar, but if it would not have been placed there, it could have looked something like below. The best of both worlds.

>### Site > Projects > Project A
>site/projects/project-a

**Comment by bastianallgeier** [comment]
I switched back to titles and I have to say that I like it a lot more. It seems more targeted at editors and clients in general and not so technical.
