### ISSUE TITLE
[Panel] Date field select options

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#482]
When creating a new page, the date field doesn't show anything in the day select. Months and years work as expected. It's also all fine when a date is loaded from an existing page.

Generally, the year select offers a range from -10 to +10 years. 
How can I enter dates outside this year range  – e. g. birthdays. At least I'm older than 10 ;)

---

_Alpha 10, lastest Firefox for Mac_

**Comment by distantnative** [comment]
The default is to have a minimum and maximum date (in terms of year) of +/- 10 years. However, you can set a different minimum and/or maximum via the `min` and `max` option. You can set the value of these options to anything that is interpreted by PHP's `strtotime()` as a valid date (http://php.net/manual/en/function.strtotime.php)
