### ISSUE TITLE
[Panel] Deleting new pages

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#483]
Deleting a new page results in weird panel behaviour:

1. Create a new page, e. g. named "test".
2. Select `Settings` → `Delete`.
3. "Do you really want to delete **test**?"  → `Ok`.
4. Error message: "The page directory cannot be moved", the page is still displayed.

```json
{
  "code": 400,
  "details": [],
  "exception": "Kirby\\Exception\\LogicException",
  "file": "test.k3/kirby/src/Cms/PageStore.php",
  "key": "0",
  "line": 256,
  "message": "The page directory cannot be moved",
  "status": "error"
}
```

5. "Do you really want to delete **test**?"  → `Ok`.
6. Error message: "The page 'news/test' cannot be found", the page is still displayed.

```json
﻿{
  "status": "error",
  "exception": "Exception",
  "message": "The page \"news/test\" cannot be found",
  "file": "test.k3/kirby/config/api/data.php",
  "line": 44,
  "code": 500
}
```

Although the page is still displayed in the panel, it has been deleted as requested.

---

_Alpha 10, latest Firefox for Mac._

**Comment by bastianallgeier** [comment]
✅
