### ISSUE TITLE
[Panel] "Keep me logged in" checkbox has lost its function

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#485]
Followup of #472:

Checking the "keep me logged in" checkbox doesn't affect the auth request anymore. If I check it and inspect the auth request in the developer tools, I get the following HTTP body:

```
{"long":false}
```

even though the value should be `true` when the checkbox is checked.

---

Tested with Alpha 10, the issue might have been introduced earlier. The original implementation still worked and sent the correct value depending on whether the checkbox was checked or not.

**Comment by bastianallgeier** [comment]
✅
