### ISSUE TITLE
Create user roles with panel

### ISSUE THREAD

**Issue by arnvvd** [getkirby/kirby#486]
Hi ! I have a website wich list prototypes of several projects. I would like to create a custom role  for each project/client to limit the access and create different users. 

Is it possible to create role dynamically with a text field in panel on each project pages ?

**Comment by texnixe** [comment]
What exactly is your use case? You could assign user roles to individual projects to limit access from the frontend and then create users with that user role. Limiting access on the panel is currently not yet implemented, though.

**Comment by arnvvd** [comment]
I'll just use this method. Thanks a lot !
