### ISSUE TITLE
Solide with import

### ISSUE THREAD

**Issue by hannesherold** [getkirby/kirby#4865]
![Screenshot_20221114-191354.png](https://user-images.githubusercontent.com/46819942/204083470-b73ca428-43ed-418c-a613-6fcdc0b8e475.png)

https://splidejs.com/v3/guides/getting-started/

**Comment by lukasbestle** [comment]
To be honest I don't see how this relates to Kirby. Could you please explain?

**Comment by hannesherold** [comment]
Sorry! That was a clear mistake: wrong repo.

**Comment by lukasbestle** [comment]
No worries, thanks for your quick reply.
