### ISSUE TITLE
[Panel] The section "{name}" could not be loaded

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#487]
I misconfigured my blueprint (`parent: site.find("projects").filterBy('category', 'landscape')` didn't return any values) and got this message in the panel:

![bildschirmfoto am 2018-05-31 um 16 47 31](https://user-images.githubusercontent.com/25466/40789276-57983a94-64f2-11e8-82c9-e48b4299dcd6.png)

> The section "{name}" could not be loaded: Return value of Kirby\Cms\BlueprintPagesSection::data() must be an instance of Kirby\Cms\Pages, instance of Kirby\Cms\ContentField returned 

Problems:

1. The first part is missing the actual section name (`{name}`). 
    Maybe this is a result of blueprint extends.
2. The second part is just PHP jargon not understandable for the user. 

It would be better to hint what the user actually did wrong:

> The section "projects" could not be loaded. Please check your page query.

**Comment by bastianallgeier** [comment]
✅ ![bildschirmfoto 2018-06-18 um 17 05 20](https://user-images.githubusercontent.com/24532/41544895-2c13b3d6-731a-11e8-95cc-0e9a7c6c26c9.png)
