### ISSUE TITLE
Action / controller before template loads

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#487]
I don't think this have had an own issue before, but I'm fully aware that I've taked about the subject before. I'm however not sure that you fully understand the issue.

I hope you don't get mad at me for trying to explain this one (last?) time.

# Case 1

**Let's say I have these types of pages:**

- revisions
- drafts

They are only used as containers on every page on the entire site.

**The structure would look something like this:**

```
about
  drafts
  revisions
projects
  drafts
  revisions
  project-1
    drafts
    revisions
```

To be able to exclude `drafts` and `revisions` from the `$pages` object it's possible to use a [collection filter](https://getkirby.com/docs/developer-guide/objects/collections).

The problem is that there is no way to filter the `$pages` object before the template loads on all pages.

## Bad solution 1 - Models and controllers can't run on the entire site

Models and controllers are template specific. Because this action needs to take place on the whole site, it's not nice to use models or controllers. There is a site controller, but that's just a backup so it would not be reliable.

## Bad solution 2 - Mess upp the `header.php` is not looking good

It would be possible to filter the query in the `header.php` template but that would be really messy.

## Bad solution 3 - Filter every query is much work

It's also possible to filter every query on the site but that means more code and more work.

## Bad solution 4 - Use the template component

https://github.com/jenstornell/kirby-init-controller

While I think my plugin is awesome, there is a big problem with it. If I need to use the template component for something else, it's already taken because a component can only be extended once.

# Case 2

Let's say I have field that can be `published` or `unpublished`.

If the field is `unpublished`, then redirect the page to the `error` page.

It sounds really simple, but this action needs to take place on all pages and the redirect needs to take place before the template loads.

Then we have the problems of "Bad solutions 1, 2, 4" again. These are just two cases of possibly many more.

# Possible solutions

Here are some possible solutions:

1. Do it like an "init controller", just like my plugin (well tested). It's based on the Kirby controller anyway.
1. Add some kind of filter feature to be able to filter the `$pages` object before template loads.

I like the first one better because it can handle both my cases. The second one can only solve the first case.

**Comment by lukasbestle** [comment]
I understand the problem. But I don't understand in what way you are trying to filter the pages in the first case. 

You write that:

> The problem is that there is no way to filter the $pages object before the template loads on all pages.

Do you actually want to filter the pages globally so that they are simply not included in the `$pages` object anymore? How are you going to access the drafts and revisions then?

**Comment by jenstornell** [comment]
>Do you actually want to filter the pages globally so that they are simply not included in the $pages object anymore?

Yes, that is correct for case 1.

>How are you going to access the drafts and revisions then?

Not at all, on the frontend. Revisions and drafts has nothing to do with the frontend presentation. But they have a central place in the Panel.

Except drafts and revisions there can be placeholders and other stuff that are only ment for the panel.

**I also got an issue about this myself:**

>I like the idea of this plugin a lot and I'm thinking about using it, but I am to lazy to edit all my content-queries to ignore the revisions folder ;)

https://github.com/jenstornell/kirby-revisions/issues/26

**Comment by lukasbestle** [comment]
Completely excluding pages from the collections is not going to work, it will break a lot of stuff.
Explicitly whitelisting the templates in the respective loops in the template is a more reliable option and it already works.

**Comment by jenstornell** [comment]
So there will be no way to do stuff globally, just before the template loads then?

There are no other great ideas that comes to your mind about it? I mean, my possible solutions was just suggestions. Maybe there are other better ones that are not yet on the table?

Anyway, I tried my best and this issue is my last effort in this topic. I'll rest my case if nothing new comes up about it.
