### ISSUE TITLE
Content representations - Don't force redirect on every url with a dot

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#489]
https://forum.getkirby.com/t/content-representation-redirect-to-actual-url/5069

**Quote 1:**

>If I get this the about.json does not exist it will be redirected to about? Why not just throw an error like before? No need for a redirect here.

**Quote 2:**

>It puts the onus on the developer to handle these errors, rather than Kirby trying to be too smart.

**Quote 3:**

>Makes sense. We will consider it.

**Comment by lukasbestle** [comment]
This is now implemented for Kirby 2.4.
