### ISSUE TITLE
[Cms] Simplified route returns

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#489]
In Kirby 2 to return some html from the route we would do something like this:

```php
return new Response('Hello World!', 'html', 200);
```

## Simplified syntax

Html 200 is the most common case.

**I think, if the output is a string, we should be able to do this:**

```php
return 'Hello World!';
```

The above could return the exact same thing as the first one.

**Another possibility is to do something like this:**

```php 
return ['{"Hello": "World!"}', 'json'];
```

The above is an array with two arguments. In this case the default code is 200, if only two args are used.

**With 3 arguments it can look like this:**

```php
return ['Hello World!', 'html', 404];
```

**Comment by rasteiner** [comment]
I personally wouldn't like the array approach here, I find it more readable like it is now in K3:

```php
return new Response('Hello World!'); //sends a status 200 with mime type 'text/html' 
return new Json(['hello', 'world']); //sends a status 200 with mime type 'application/json'
```

if I read something like `return ['Hello World!', 'html', 404];` I would actually expect it to transform the array into JSON and send a status 200, mime type 'application/json' and body "['Hello World!', 'html', 404]"

transforming a String to an Html Response however could be nice to have...

**Comment by jenstornell** [comment]
@rasteiner Yes, I see your point.

I think that's actually a good idea, to get a nice respose from both strings an arrays.

With this new idea it would be like this...

### String

*text/html 200*

```php
return 'Hello World!';
```

### Array

*application/json 200*

```php
return ['Hello', 'World!'];
```

**Comment by bastianallgeier** [comment]
✅ The version in @jenstornell's last comment is now on the develop branch.
