### ISSUE TITLE
Multilang: Default template if text file for default lang does not exist

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#490]
See [this topic](https://forum.getkirby.com/t/default-template-problem-on-multilingual-website-since-kirby-2-3/5118?u=lukasbestle). This issue seems to have been introduced with the registry in Kirby 2.3.

**Comment by lukasbestle** [comment]
From the forum:

> 2 functions added to the "templates/default.php" :
> 
> echo $page->hasTemplate()
> answers : 1
> Cheat Sheet : "Checks if the page has its own template or if it uses the default template (return boolean)".
> 
> echo $page->content()->name()
> answers : (correct strings)
> Cheat Sheet : "Returns the name of the content file without the extension. This is being used to determine the template for the page (return string)"
> 
> ps.
> intendedTemplate() returns "default", no surprise

**Comment by lukasbestle** [comment]
Also see [this topic](https://forum.getkirby.com/t/redirect-error-with-multilanguage-setting/5239?u=lukasbestle) for a similar issue.

**Comment by bastianallgeier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multilang: Default template if text file for default lang does not exist](https://trello.com/c/ByTdHYiD/9-multilang-default-template-if-text-file-for-default-lang-does-not-exist)

**Comment by lukasbestle** [comment]
This is now fixed on the develop branch.
