### ISSUE TITLE
Composer performance when installing from GitHub

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#492]
Hello,

I’m trying out the Composer install of `getkirby/kirby`. Since it’s not published on Packagist, and neither is the `getkirby/smartypants` fork, my test `composer.json` has two VCS repositories:

```json
{
  "name": "test",
  "license": "proprietary",
  "type": "project",
  "minimum-stability": "dev",
  "require": {
    "php": ">=5.5.0",
    "getkirby/kirby": "dev-develop"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/getkirby/kirby"
    },
    {
      "type": "vcs",
      "url": "https://github.com/getkirby/smartypants"
    }
  ]
}
```

Note that the `{"type": "vcs", "url": "https://github.com/getkirby/smartypants"}` part exists in `getkirby/kirby/composer.json` (on the develop branch) but as the Composer doc states, repository declarations from dependencies are not made available to the parent project, so I have to copy this part.

Anyway, it seems like there is a small performance problem where Composer (1.2.0) spends time reading the `composer.json` of all tags in the `getkirby/kirby` repo, displaying a message such as:

```
Reading composer.json of https://github.com/getkirby/kirby (2.3.2)
Reading composer.json of https://github.com/getkirby/kirby (2.3.1)
…
```

And it goes through all 17 tags, which takes a while (like 20 seconds, probably more on a not-so-great connection). Also, since I ran this twice, the second time GitHub decided that enough was enough and I had to generate a token to be allowed to make such requests. (Thankfully Composer managed that very efficiently, giving me the right link to generate a token and a prompt to save it. A+ work would use again.)

I don’t know if something can be done on this repo's side, or if that’s a downside of not being on Packagist that can’t be easily circumvented. Any thoughts?

**Comment by lukasbestle** [comment]
Kirby will be on Packagist with the release, but 2.4 is not even in beta right now...
