### ISSUE TITLE
[Panel] The page "xxx/yyy" cannot be found

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#494]
I found this bug in my own alpha-10 test project. So maybe the bug comes from my code?

I have a first level of page called "Campagne" and subpages called "Project".
I can create a new "campagne" page but when I try to create a new "project" subpage, this message displayed:

The page "campagne-1/project-1" cannot be found

Anyway, the "project" subpage is created in the file system.

Here a sceenshot from my file system for the /content folder after creating a "campagne" page and a "project" subpage:

https://ibb.co/c1RfAo

And here a screencast:

https://streamable.com/giado

**Comment by vauvarin** [comment]
If only one project is with status "published", the other new draft projects can be found.

**Comment by bastianallgeier** [comment]
✅
