### ISSUE TITLE
[Panel] Bugs when sorting pages

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#495]
If you sort pages we observe weird behavior:

- Sorting doesn't work
- Display the page you are dragging and dropping (random behavior)
- Page status change

Screencast: https://streamable.com/6cfj5

Linux Ubuntu 18.04
Firefox Quantum 60.0.1 (64-bit)
Caddy Server (localhost)

**Comment by bastianallgeier** [comment]
I fixed the bugs around sorting in general, but the biggest problem here was a logic issue with the blueprint setup in site.yml.
