### ISSUE TITLE
[Panel] Safari 10 support

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#496]
### General issues

It's not possible to load the panel in Safari 10 due to the way translations are loaded

```js
  // Translations
  resolve(parts, "translations", (locale, strings) => {
    window.panel.plugins["translations"][locale] = {
      ...window.panel.plugins["translations"][locale],
      ...strings
    };
  });
```

> Syntax error: Unexpected token '...'. Expected a property name.

Uncommenting these lines fixes the error but remove translation support for plugins of course.

### Layout issues

The grid layout uses percentages for the gap between columns. This is not supported in Safari 10. Using `5vw` instead of `5%` works.

**Comment by bastianallgeier** [comment]
✅
