### ISSUE TITLE
Included license not recognized in site options

### ISSUE THREAD

**Issue by cchimi** [getkirby/kirby#498]
I'm using a multi-site setup which shares a single site folder and config file. In order to have licenses for each site, I've put a license.php file in each project-specific folder and I have an include in my config.php. I think this is working as it should, because when I log in to the panel I do not see the notice asking me to buy a license. However, when I go to Site Options in the panel, I do see a notice that I am using a trial version and should buy a license. Because it appears in one place but not the other, I think it is a bug and not a coding error (although I can't find a cause).

I can provide a link and temporary site login privately, if that would be helpful.

**Comment by lukasbestle** [comment]
I have moved this issue to the Panel repo, see getkirby/panel#921.
