### ISSUE TITLE
[Cms] Provide template renderers via plugins

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#499]
The documentation on Notion describes creating a plugin via a simple API:

```php
Kirby::plugin('superwoman/superplugin', [ 
    'snippets' => [ 
        'header' => __DIR__ . '/snippets/header.php' 
    ], 
    'templates' => [ 
        'blog' => __DIR__ . '/templates/blog.php' 
    ], 
    'hooks' => [ 
        'page.delete:before' => function () { 
            throw new Exception('Nope');
	} 
    ] 
]);
```

While it's possible to provide templates via a plugin, it's not possible to easily provide a different renderer (aka `Template` class, e. g. for rendering Twig, Mustache, XSLT). In order to give the user choices it would be nice to have this as an option as well.

**Comment by bastianallgeier** [comment]
That's one thing I've been working on in the last days. It will look like this: 

```php
Kirby::plugin('superwoman/superplugin', [
    'components' => [        
        'template' => function (Kirby $kirby, string $name, array $data = [], string $appendix = null) {
            return 'my template';
        }
    ]
]);
```

**Comment by nilshoerrmann** [comment]
So I could do the following?

```php
Kirby::plugin('superwoman/superplugin', [
    'components' => [        
        'template' => function (Kirby $kirby, string $name, array $data = [], string $appendix = null) {
            return new My\Cool\Renderer\Template($name, $data, $appendix);
        }
    ]
]);
```

**Comment by bastianallgeier** [comment]
The template function should simply return the rendered template as string. So in your case it should probably something like this: 

```php
Kirby::plugin('superwoman/superplugin', [
    'components' => [        
        'template' => function (Kirby $kirby, string $name, array $data = [], string $appendix = null) {
            return (new My\Cool\Renderer\Template($name, $data, $appendix))->render();
        }
    ]
]);
```

Unless your Template class is convertable to a string anyway.

**Comment by nilshoerrmann** [comment]
Großartig!

**Comment by bastianallgeier** [comment]
It's not on the develop branch like that yet. Give me a couple more minutes :)

**Comment by bastianallgeier** [comment]
It's done! But I had to do it more like in your first example. You need to extend our Template class and return an instance of that. 

```php

use Kirby\Cms\Template;

class MyTemplate extends Template { 
  public function render() {
    return 'my template result';
  }
}

Kirby::plugin('superwoman/superplugin', [
    'components' => [        
        'template' => function (Kirby $kirby, string $name, array $data = [], string $appendix = null) {
            return new Template($name, $data, $appendix);
        }
    ]
]);

```

Otherwise we can't handle template detection correctly. For something like twig it won't be useful to load our php template files. With the Template class you can also overwrite where template files are located and how they are named.

**Comment by nilshoerrmann** [comment]
This is very much appreciated. Thank you so much!
