### ISSUE TITLE
[Panel] Use expected conventions for keyboard navigation

### ISSUE THREAD

**Issue by paulrobertlloyd** [getkirby/kirby#5]
The panel already has great keyboard interaction, but you should do an audit to ensure you are using expected conventions. For example, navigating between items in a menu should be done via arrow keys, with the tab key allowing you to escape the menu and move to the next item. Currently, tab is used for both entering the menu and navigating its options; very tiring! This is a good introduction to a11y for menus: https://inclusive-components.design/menus-menu-buttons/

- [ ] Enable keyboard navigation through dropdown menus

**Comment by bastianallgeier** [comment]
✅
