### ISSUE TITLE
Fatal error: Allowed memory size...

### ISSUE THREAD

**Issue by iamtimm** [getkirby/kirby#500]
![img_2979](https://cloud.githubusercontent.com/assets/2601332/19068664/5e36985e-8a1b-11e6-9a1e-6e2605041ccb.jpeg)

Hi, i'm unsure how to solve this issue. I'm pretty sure its not an issue with kirby but I'm not sure where else to post this.

Thanks

**Comment by bastianallgeier** [comment]
You are running in to memory issues because of the image resizer in the panel. Do you know if you have imagemagick installed on the server? You could try to switch to it, which should probably fix this. Add the following to your config in order to do so: 

```php
// site/config/config.php
c::set('thumbs.driver', 'im');
```

I hope this helps.

**Comment by iamtimm** [comment]
Thanks @bastianallgeier, from what I can tell, this has solved the problem.

You do great work! 👍
