### ISSUE TITLE
composer.json - Add "/vendor" to archive.exclude?

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#501]
I’m not sure this is needed, but should the `vendor` directory, which is versioned in this repo, be added to the archive.exclude array in the `composer.json`?

```json
{
  "archive": {
    "exclude": ["/.gitmodules", "/.gitignore", "/.travis.yml",
      "phpunit.xml", "/test", "/vendor"]
  }
}
```

That way, when installing from Packagist, we'd save downloading the dependencies twice.

I don’t think Composer or Packagist exclude `"/vendor"` by default. npm does that with `"/node_modules"`, but I couldn’t find anything similar for Composer ([doc](https://getcomposer.org/doc/04-schema.md#archive)).

**Comment by bastianallgeier** [comment]
Makes sense! I just added it.

**Comment by CelineDesign** [comment]
In 2.4, the kirby/bootstrap.php file include kirby/vendor/autoload.php, so the versioned vendor directory is required, it must not be exclude.
So i don't understand why dependencies are required in kirby/composer.json if they're already in the repository.

**Comment by fvsch** [comment]
@CelineDesign When intalling with Composer, Composer will load `kirby/composer.php`, and not `kirby/bootstrap.php`. See `kirby/composer.json` (the `"autoload"` key) and the Composer documentation:
https://getcomposer.org/doc/04-schema.md#files

**Comment by CelineDesign** [comment]
@fvsch Correct.
But panel : panel/index.php requires kirby/bootstrap.php
That's confirm #46 which mention that panel isn't compatible yet with composer.
So we still need the kirby/vendor for the panel.

**Comment by fvsch** [comment]
Installing Kirby *core* (getkirby/kirby + getkirby/toolkit + dependencies) with Composer is an option, and not the default install method. If you download the Starterkit or the Plainkit, you will get a working core+panel with the usual directory structure:

```
index.php
kirby/
    bootstrap.php
    vendor/…
panel/
    index.php
```

The `archive.exclude` key in `composer.json` only applies to the (very much optional) Composer install method. The `kirby/vendor` folder is not going anywhere, it’s just excluded when installing with Composer because Composer will install the same dependencies to different locations already, so this setting avoids duplication.

**Comment by CelineDesign** [comment]
What is the official Kirby composer install method ? do you have any doc to share ?
The only one i've found is : 
https://forum.getkirby.com/t/how-to-use-composer-to-install-kirby-toolkit-panel/2850
Is it obsolete with the new Kirby 2.4 ?

**Comment by fvsch** [comment]
> What is the official Kirby composer install method ?

There isn’t one, mostly because the panel is not yet compatible with a Composer install. This might or might not be improved in the future (maybe for 2.5?).
 
Here is a `composer.json` for installing Kirby core, and the panel to the `panel` directory:
https://gist.github.com/fvsch/665147ea487a5e256762eb3db5eb1d81

There are a few limits though:
- You’ll need to tweak the `panel/index.php` to require the Composer autoloader instead.
- There isn’t a `index.php` or `.htaccess` in the components installed with Composer (those files are contained in the starterkit and plainkit repos).

I could try my hand at making a "composerkit" that has all the basic pieces for installation, that could be a fun exercise.
