### ISSUE TITLE
[Panel] Errors on upload of svg to files

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#501]
**Reported by @eighthday in https://github.com/k-next/panel/issues/339:**

After setting the mime type to: image/svg+xml I still get an error message on upload of a svg: 

> Invalid image file: path/to/file.svg

The svg does actually upload fine. 

I also get the following error when viewing the image as a cover on the parent page:

> The section "{name}" could not be loaded: Invalid image file: path/to/file.svg

A page refresh resolves this.

**Comment by bastianallgeier** [comment]
✅
