### ISSUE TITLE
[Cms] Files sorting changes on reload

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#502]
**Reported by @Jonnotie in https://github.com/k-next/panel/issues/342**

Have a look at this video: https://www.dropbox.com/s/qj01q2apob9y8b0/keepsmoving.mov?dl=0

Whenever I sort the files, and then reload the page, the files sort the opposite way. Quite frustrating when trying to sort files :)

**Comment by bastianallgeier** [comment]
✅
