### ISSUE TITLE
[Panel] New tab design looks like a drag / drop zone

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#505]
**Reported by @eighthday in https://github.com/k-next/panel/issues/345**

Very minor visual suggestion. The current tab background looks like drop zones for files, pages etc..

Current tabs:

<img width="921" alt="screen shot 2018-05-21 at 11 49 17" src="https://user-images.githubusercontent.com/4104767/40304061-2b025120-5ced-11e8-9d75-2a5a0f3202c2.png">

With no background or border:
<img width="954" alt="screen shot 2018-05-21 at 11 49 50" src="https://user-images.githubusercontent.com/4104767/40304065-2d1dd394-5ced-11e8-93f1-310666978fe5.png">

**Comment by distantnative** [comment]
@eighthday: I think your suggestion would start looking really odd once there is a third tab to the right of Thumbnail.

**Comment by jenstornell** [comment]
@distantnative I agree that the new suggestion is not a good idea. If there where many tabs and the first and second tab was not selected there would be no separation between them and the menu above. It would be harder to tell that they belong to the tabs.

I think the problem will solve itself if you first solve this one: https://github.com/k-next/starterkit/issues/450

**Comment by bastianallgeier** [comment]
I'm really happy with the current tab design, so I would rather close this. I already modified the empty box design and think this is the better path forward.
