### ISSUE TITLE
The kirbytext tag (button:) looks a bit weird

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#506]
https://getkirby.com/docs/developer-guide/kirbytext/tags

**We can do something like:**

```text
(button: Hello world!)
```

**We can also do this:**

```text
(button:)
```

In this case we may trigger a function that get a value from the current page and output that. Therefor no additional data is needed for the tag.

To me it looks weird when there is nothing after `:`.

**We can't do this:**

```text
(button)
```

When no data is added, I think that the above should be valid as well (if that tag is registered). It's not.

I also asked about it in the forum: https://forum.getkirby.com/t/empty-kirbytext-tag-possible/5411/3

Maybe this can be improved in Kirby 3.x

**Comment by bastianallgeier** [comment]
The only problem I have with this, is that it could collide with something you actually want to write. Just think about the other tags. (video) (image), etc.

**Comment by jenstornell** [comment]
Oh, I did not think about that. Very good point. And I guess you don't want to change the syntax to something like this (brackets)?

```text
[button: Hello World!]
[button:]
[button]
[video]
```

**Comment by nilshoerrmann** [comment]
Same problem here: this might be written text as well. Especially I you do scientific writing you will use square brackets to highlight omissions or changes in quotes.

**Comment by bastianallgeier** [comment]
If we wouldn't have the legacy of our () kirbytags, I would probably use something like this {{ image: }} nowadays. But that ship has sailed. We could only make it an option :)

**Comment by jenstornell** [comment]
I agree with both of you here and I see no way around it so I close this issue. Feel free to reopen if you disagree.

Also I've recently rediscovered [Kirbytext post filter](https://getkirby.com/docs/developer-guide/kirbytext/filters). Personally I've moved away from `(button:)` to `{{ button }}`. The arguments is added with panel fields instead of in the content. That way the content is a bit cleaner and I don't need to think about possible issues with Kirbytext tags.
