### ISSUE TITLE
Support for defer attribute on <script> tags

### ISSUE THREAD

**Issue by mpatzner** [getkirby/kirby#506]
"This Boolean attribute is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but before firing DOMContentLoaded."

Source: https://developer.mozilla.org/de/docs/Web/HTML/Element/script

This would be a nice-to-have feature. I currently work around this missing feature by adding a script tag manually without calling the js() helper. However, then the cachebuster plugin won't work.

**Comment by fourpixels** [comment]
Just opened this repo to report this issue :)
I've already hacked mine with something like:

```php

// kirby/kirby/component/js.php
public function tag($src, $async = false, $defer = false) {

...

return html::tag('script', '', array(
    'src'   => url($src),
    'async' => $async,
    'defer' => $defer
));
```

Works like a charm, but I wouldn't rely on hardcoding my copy, as I won't be able to properly upgrade in future. Otherwise - great job!

**Comment by lukasbestle** [comment]
This feature is now available on the develop branch. Instead of adding a third param, you can now pass an array of totally custom attributes (like `['defer' => true]`) as the second param.
