### ISSUE TITLE
Deprecated hooks syntax?

### ISSUE THREAD

**Issue by samnabi** [getkirby/kirby#507]
I have a couple hooks in the extension registry that look like this:

```php
$kirby->set('hook', 'panel.file.upload', 'shrinkLargeImages');
$kirby->set('hook', 'panel.file.replace', 'shrinkLargeImages');

function shrinkLargeImages($image) {
  ...
};
```

It looks like Kirby 2.4.0 no longer accepts a string in the 3rd argument. It threw an error at [line 768 of kirby/kirby.php](https://github.com/getkirby/kirby/blob/master/kirby.php#L768), so I had to rewrite the hooks like this:

```php
$kirby->set('hook', ['panel.file.upload','panel.file.replace'], function ($image) {
  ...
});
```

The array syntax for the 2nd argument means I can still accomplish what I want without duplicating my function, but I'm wondering why this change was made? I can't seem to find any information about this breaking change in the changelog for 2.4.0.

**Comment by lukasbestle** [comment]
The change was because of the new permissions feature. Event callbacks (= hooks and permission functions) will get the new event object bound to `$this` now and the `bindTo()` method only works with closures, not with strings pointing to functions.

I have fixed this on the develop branch.

**Comment by samnabi** [comment]
Thanks for the prompt reply!
