### ISSUE TITLE
Custom Kirbytags - HTML Tags with minus in name

### ISSUE THREAD

**Issue by Pascalmh** [getkirby/kirby#508]
site/tags/foo-bar.php
```php
kirbytext::$tags['foo-bar'] = [
    'html' => function ($tag) {
        return '<foo-bar></foo-bar>';
    }
];

```

my markdown:
```
# This headline works

Here is some text

(foo-bar:)

Here is some more text

# And a Headline that does not work
```

If however I return a `<hr>` or `<div></div>` everything works again.

**Comment by Pascalmh** [comment]
Quickfix: Use [kirbytext filters](https://getkirby.com/docs/developer-guide/kirbytext/filters). In your site/tags/foo-bar.php return the html without a dash in it `return '<foobar></foobar>'`

then in the post filter replace the non-dash-version with the dash-version:

```
kirbytext::$post[] = function($kirbytext, $value) {
    $replacements = [
        'foobar' => 'foo-bar',
    ];

    return str_replace(array_keys($replacements), array_values($replacements), $value);
};
```

**Comment by lukasbestle** [comment]
Does the same thing happen if you put the tags directly into your Markdown content? If so, it's most likely an issue with Parsedown.

**Comment by Pascalmh** [comment]
Yes, that is actually how I tested it. I did put the markdown code into **content/home/home.txt**

When I add `<foo-bar></foo-bar>` and after that a headline (`# my headline`) here <http://parsedown.org/demo> it works however

**Comment by Pascalmh** [comment]
See https://github.com/erusev/parsedown/pull/429

**Comment by lukasbestle** [comment]
Closing this as we can't fix this in Kirby.
