### ISSUE TITLE
Plugin assets

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#509]
There seems no way to provide plugin assets (styles, scripts etc).
Before Alpha 11, Kirby 3 bundled two `.htaccess` related rules:

```apache
RewriteRule ^assets/plugins/([a-zA-Z0-9\.\-_%=]+)/(.*)$ site/plugins/$1/assets/$2 [L,N]
RewriteCond $1 !^plugins/[a-zA-Z0-9\.\-_%=]+/assets/.*
```

These rules have been removed in Alpha 11 without replacement.

**Comment by bastianallgeier** [comment]
Plugin assets are now stored in the media folder and the htaccess rules are no longer required. Unfortunately I discovered that Alpha 11 has a bug in the plugin asset resolver, but otherwise you can put your plugin assets in a subfolder assets and then the following link schema will work: 

```
http://your.site/media/plugins/$pluginDeveloper/$pluginName/$assetpath
```
I.e.
```
http://your.site/media/plugins/superwoman/superplugin/css/index.css
```

**Comment by nilshoerrmann** [comment]
Thanks for the update!

**Comment by nilshoerrmann** [comment]
I've got this folder setup and all urls work but the one requesting font files:

`/site/plugins/xslt/assets/fonts/*.woff2` → `/media/plugins/hananils/xslt/fonts/*.woff2` ⛔️
`/site/plugins/xslt/assets/images/*.png` → `/media/plugins/hananils/xslt/images/*.png` ✅
`/site/plugins/xslt/assets/scripts/*.js` → `/media/plugins/hananils/xslt/scripts/*.js` ✅
`/site/plugins/xslt/assets/styles/*.css` → `/media/plugins/hananils/xslt/styles/*.css` ✅

I get a `404` for font files.
Are there any file type restrictions in place?

**Comment by nilshoerrmann** [comment]
I'm not allowed to reopen issues, but this is still an issue, @bastianallgeier.

**Comment by bastianallgeier** [comment]
✅ I added woff and woff2

**Comment by nilshoerrmann** [comment]
Cool, thanks!
