### ISSUE TITLE
Bugs with alternative tinyurl domain

### ISSUE THREAD

**Issue by jonabaptistella** [getkirby/kirby#509]
I have tested this new little feature and the hash do not end anywhere else then in the error page. I have tried to turn in the tinyurl in the config and I have tried without any tinyurl-domain. No matter what it ends in the error page. 

Also I love the idea of that you don´t need to show the tinyurl folder in the short url with the short domain. Please keep it that way.

**Comment by lukasbestle** [comment]
Please see [the docs about the feature](https://getkirby.com/docs/cheatsheet/options/tinyurl-url). You need to do the redirection yourself, otherwise Kirby wouldn't know the "actual" domain.

**Comment by jonabaptistella** [comment]
I have done so... but the hash do not lead to the page...

**Comment by jenstornell** [comment]
@jonabaptistella 

If you are not sure if you have found a bug or not the forum is a great place to get support:

https://forum.getkirby.com/

I often start there myself if I'm not sure it's an issue or if it's just me...

**Comment by jonabaptistella** [comment]
Hi @lukasbestle and @jenstornell.

I think I will call it a bug after trying all possible angels on this. But I will explain better. And the same setup without the tinyurl domain works just fine with the current 2.3.2 kirby version I use on this project.

First of all sorry for bad english in the first post here. I updated my current project in development to the new kirby version 2.4.0. I have added this to my `.htaccess`

```
RewriteCond %{HTTP_HOST} ^jonab.co [NC,OR]
RewriteCond %{HTTP_HOST} ^www.jonab.co [NC]
RewriteRule ^(.*)$ http://baptistella.dk/x/$1 [L,R=301,NC]
```
I also tried with this in the `.htaccess` and this do not work as expected but it´s what that is written in docs.
```
RewriteRule (.*) http://jonab.co/x/$1 [R=301]
```

And then I added this to the `config.php`

```
c::set('tinyurl.enabled',true); // This setting do not seem to be taking any effect on my issue.
c::set('tinyurl.url', 'http://jonab.co');
```

The result of all of this is still an error page. Also if I remove the tinyurl domain setting in the `config.php` it should work as it does with kirby version 2.3.2, correct? 
And after also just be sure that I did not mess anything up I just added `c::set('tinyurl.enabled',true);` in the `config.php` alone. And that also return `/error`.

So what is it that I don´t understand or is this really a bug, I am not sure. But it does not work as expected, based on the docs. Ideas?

**Comment by lukasbestle** [comment]
If I visit http://jonab.co/anything, I do not get redirected but get the error page. Without the redirection it can't work.

The example from the docs was intended to be used in a separate web-root for the short domain. It doesn't make sense to point the short domain to the same web-root.

**Comment by jonabaptistella** [comment]
_The domains was just meant as demo for the code, cause I have rolled back to the v2.3.2 to make the tinyurl hash work for the main domain for now, I have made a setup to show what the issue is under._ 

@lukasbestle so how should this work then if not pointed to the same web-root? Cause to me the natural use case for this feature is to point the two domains to the same web-root and use one for "easy-to-share" url with the tinyurl domain and the main site domain to maintain proper branding. But the short domain to me should be a reflection of the main domain just short.

I have setup a separate website for you to see where this offer some issues:  <http://www.vocepode.co/articles/jojo> (please look in the footer of the page, I have made that for you see the link and see where the issue is) to clarify, this is setup with both domains going to the same web-root and I rewrite the url in the `.htaccess` from `jonab.co` to `vocepode.co` as in my post over, I have just changed the main domain to be vocepode.co. It all works fine until the hash should map to the right page. So the problem is not the redirection or the two domain to one web-root. 

Even with the short domain option it should work, right?

**Comment by lukasbestle** [comment]
Your redirection is correct, it's indeed strange that http://vocepode.co/x/1nrjfgq 404s. I will look into this.

**Comment by jonabaptistella** [comment]
@lukasbestle thank you, also I discovered that it do not play nice with the multi-language on the page. Or is the language code included in the hash?

**Comment by lukasbestle** [comment]
I can't reproduce the 404 issue. What is your `tinyurl.folder` option set to on vocepode.co?

Regarding multi-language: You can add the language code at the end:

```php
echo $page->tinyurl() . '/' . $site->language()->code();
```

It's not the default though, maybe because of the link length. I don't know exactly however.

**Comment by jonabaptistella** [comment]
@lukasbestle thank you for that info. I had set it up the following way until now to keep the mostly default.

**Before**
```
c::set('tinyurl.enabled',true);
c::set('tinyurl.url', 'http://jonab.co');
//c::set('tinyurl.folder','x');
```

**Now**
Just to see make sure that there is nothing else I changed it to this:
```

c::set('tinyurl.enabled',true);
c::set('tinyurl.url', 'http://jonab.co');
c::set('tinyurl.folder','x');
```

_But I guess this will not make any difference._

**Comment by lukasbestle** [comment]
No, since `'x'` is the default. It can't be the new URL feature though. Do you have any custom routes?

**Comment by jonabaptistella** [comment]
Only the logout route:

```
c::set('routes', array(
  array(
	 'pattern' => 'logout',
	 'action' => function () {
		if ($user = site()->user()) $user->logout();
		go('login');
	 }
  )
));

```

**Comment by lukasbestle** [comment]
That shouldn't cause the problem. To be honest I don't know what could possibly cause this. Could you maybe create a reduced test case based on the starterkit and send that to me via email (lukas at getkirby)?

**Comment by jonabaptistella** [comment]
I have found what causes it @lukasbestle. It is the multi-langauge setup with the tinyurl setup. So the only thing I did not try is the one that causes the issue. Now here is my languages in my config:

```
c::set('language.detect', true);

c::set('languages', [
  [
	 'code'    => 'en',
	 'name'    => 'English',
	 'default' => true,
	 'locale'  => 'en_US',
	 'url'     => '/',
  ],
  [
	 'code'    => 'br',
	 'name'    => 'Português',
	 'locale'  => 'pt_BR',
	 'url'     => '/br',
  ],
  [
	 'code'    => 'no',
	 'name'    => 'Norsk',
	 'locale'  => 'nb_NO',
	 'url'     => '/no',
  ]
]);
```

**Comment by jonabaptistella** [comment]
@lukasbestle I really did not think about that at all. So maybe that is even related to the other issue I added here #510, not sure. I guess you will be able to reproduce this with ease now...

**Comment by jonabaptistella** [comment]
Also I added the code `echo $page->tinyurl() . '/' . $site->language()->code();` that you gave me and that do not fix anything so there is something else. Also should´t the language be a part of the hash?

**Comment by lukasbestle** [comment]
Yep, multilang was the issue. I have fixed this on the develop branch. Could you please test it again?

> Also I added the code echo $page->tinyurl() . '/' . $site->language()->code(); that you gave me and that do not fix anything so there is something else. Also should´t the language be a part of the hash?

Adding the language code at the end is no fix for the issue, it's a feature (that requires the fix of course) to redirect to the correct language version. The language can't be part of the hash because decoding the hash would get a lot slower with many languages.
