### ISSUE TITLE
Underscores in UID

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#510]
We have a page with the UID `un_seated`. This resulted in the following error in Alpha 11:

```
Argument 1 passed to Kirby\Cms\Page::setNum() must be of the type integer or null, string given, called in /Users/nilshoerrmann/Sites/branchplant.k3/kirby/src/Toolkit/Properties.php on line 126
```

**Comment by lukasbestle** [comment]
We discussed this recently in Slack. Underscores are now used for the numbering system, because they are less common in URLs than the dashes we used in Kirby 2. So underscores are now no longer allowed in UIDs, you need to change the UID.

However I think that this edge case should be handled a bit more gracefully. Especially because the part before the underscore is not even a number, it shouldn't throw an error. Or if it should (to be consistent with our "underscores are not allowed in UIDs" rule), there should be an explicit error message and not a fatal error. @bastianallgeier?

**Comment by jenstornell** [comment]
I vote for a nicer error message. Then users will adapt to the new syntax. Probably less new unexpected errors.

**Comment by nilshoerrmann** [comment]
Yes, I've read the discussion. 

I agree on the nicer error handling: personally, I'm not sure if it is necessary to disallow underscores. Maybe a "use at own risk" warning would be better. Underscores are allowed in URLs and I can think of cases where an editor would like to have an underscore in the URL on purpose. A user who is aware of the possible side effects should be allowed to use it.

Keep in mind, this change will be an issue for users upgrading from Kirby 2 to 3 because either Kirby or the users will have to update all existing pages and this will break URLs. So if Kirby will be taking care of this change on upgrade, it will also have to take care of redirection.

**Comment by lukasbestle** [comment]
We asked in Slack whether anyone uses UIDs with underscores, but if I remember correctly, no one told us that they absolutely needed it. But you are right: We need to handle the migration of pages with an underscore in their UID somehow.

Switching to underscores wasn't a light choice. We needed to get rid of the dashes as they caused a lot of issues. The whole "use at your own risk" part didn't work out as many users had issues with this. It's just not something that can be easily understood by someone who doesn't know how page directories are stored in Kirby. So Panel users were using dashes like normal and didn't realize that a number at the front wouldn't work.

We tried to replace the dash with a dot before, but that failed (which was the start of the discussion in Slack). We can only use URL-safe characters – and that only leaves the underscore and the tilde (which is pretty uncommon, but actually even *too* uncommon to be accessible to all of our users).

**Comment by nilshoerrmann** [comment]
What about a mixed approach:

- The panel disallows the creation of an UID with underscore.
- But Kirby doesn‘t throw an error if a folder contains an underscore.

The panel could show a warning in the interface in these cases.

**Comment by lukasbestle** [comment]
I think that sounds like a good compromise. :)

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch. The page can still be opened at the URL with the underscore, but you cannot create new pages or update slugs with underscores in the panel.
