### ISSUE TITLE
Broken fallback route in multilanguage setups. 

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#511]

**Comment by bastianallgeier** [comment]
@lukasbestle could you have a look at this? It's weird. If you have a multi language setup and all languages use a prefix in the URL, all URLs without a language prefix render a json error string. So for example

```
http://yourdomain.com/some-random-url
```

is not displaying the error page but the json error

**Comment by lukasbestle** [comment]
Isn't that kind of intended behavior? If Kirby doesn't know the language, it can't display an error page.

The JSON error string comes from the missing route though. We *could* fix it by adding a "fallback route for the fallback route" at the end, but I don't know what that should output/do.

**Comment by bastianallgeier** [comment]
I think the correct way to do it would be to redirect to the default/detected language's home page. What do you think?

**Comment by lukasbestle** [comment]
Yeah, that probably makes sense.

**Comment by lukasbestle** [comment]
Fixed for Kirby 2.4.1.
