### ISSUE TITLE
Exhausted if no template is found

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#512]
**To reproduce**

1. Install Kirby 2.4.0 starterkit.
1. Delete `site/templates/home.php` and `site/templates/default.php`.
1. Go to the startpage on the frontend.

>Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in C:\xampp\htdocs\kirby\2.4.0\kirby\kirby\registry\template.php on line 69

>Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in C:\xampp\htdocs\kirby\2.4.0\kirby\vendor\composer\ClassLoader.php on line 300

Because Kirby can't find a template, it's ok to have an error message here.

But in this case I don't want it to load forever and then be exhausted and run out of memory. Maybe it's an infinity loop? Instead it would be better with an if statement to check this and display this error message much quicker. With or without Woops, just don't run out of memory.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
