### ISSUE TITLE
[Panel] - Javascript error when trying to fetch users in the Form Demo page

### ISSUE THREAD

**Issue by gerardkd** [getkirby/kirby#512]
When I try to find a user in the user field on the Form Demo page on the Alpha (11 - Vaporware), a javascript error comes up. I'm on High Sierra 10.13.4 with Chrome 67.x, PHP 7.1.12 via MAMP:

<img width="355" alt="screen shot 2018-06-25 at 14 58 20" src="https://user-images.githubusercontent.com/5598068/41851508-62c84f72-7888-11e8-9e15-ff7118386359.png">

In the console:
<img width="1678" alt="screen shot 2018-06-25 at 14 59 57" src="https://user-images.githubusercontent.com/5598068/41851528-77f68814-7888-11e8-8291-99b4eeaa1df2.png">

In Safari, the error is slightly different:
<img width="350" alt="screen shot 2018-06-25 at 15 01 52" src="https://user-images.githubusercontent.com/5598068/41851634-db4207c2-7888-11e8-8bf8-9ef4aeaa7c61.png">

and the console:
<img width="1519" alt="screen shot 2018-06-25 at 15 02 18" src="https://user-images.githubusercontent.com/5598068/41851646-e1f08684-7888-11e8-87a8-ba079acc74b2.png">

**Comment by bastianallgeier** [comment]
I can't really reproduce this unfortunately. Can you tell me a bit more about the steps that lead to that error? Does it appear immediately after opening the form sandbox?

**Comment by gerardkd** [comment]
It happens when I try to type in the user field on the Form Demo page. The letter appears, but so is a error overlay. I've recorded a gif so you can see the steps. It's a clean install, with 1 user.

Step 1: go to the form Demo page,
Step 2: focus on the user field
Step 3: Type something
Step 4: error occurs

![users](https://user-images.githubusercontent.com/5598068/41900248-8ed6c35e-792e-11e8-9f63-302cc506092a.gif)

**Comment by bastianallgeier** [comment]
Thanks for the gif. That's very helpful. I will check what happens there.

**Comment by bastianallgeier** [comment]
✅
