### ISSUE TITLE
Allow plugins to register custom permissions per role

### ISSUE THREAD

**Issue by dweidner** [getkirby/kirby#513]
I am working on a plugin that basically provides the functionality of what you suggest in your cookbook recipe [Asset Firewall](https://getkirby.com/docs/cookbook/asset-firewall). I already created a nice custom field that allows users to select who is allowed to access the associated page. 

![Access Control Field](https://cloud.githubusercontent.com/assets/2363597/20177645/1e843ed2-a74e-11e6-8e1b-4f806a80b213.gif)

I would like to reduce the required code to check whether the current user has access to a frontend page to a simple function call (within the corresponding template/controller). Ideally that function call would use the same interface which is already available on the `User` object, namely `site()->user()->can('page.read', page())`. Unfortunatly I found no way to add new permissions to registered `Roles` via a plugin, as the `permissions` property on the `Role` is protected. The only workaround currently available is to implement a custom `Page` method, for example `page()->currentUserHasAccess()`,  which is half as sexy … 👎

**Comment by lukasbestle** [comment]
Changing existing roles from plugins isn't intended to ensure security. Users could add your custom plugin permissions to their role files, but without the user it won't work (maybe it will, but that would be a bug!).

What you could do: Why do you need the check in the template in the first place? Couldn't you check the permissions from your plugin and redirect directly from there?

**Comment by dweidner** [comment]
Changing the roles is not what I intended. Maybe it is nitpicking, but I would like to *extend* the rules. Kirby could for example ensure that user permissions always take precedence over plugin permissions, similar to other extensions of the Kirby core.

I would like to use the Permission API as it makes the process much more flexible. The user can himself decide whether he wants to use the provided plugin permission in one of his controllers or whether the plugin should handle all of it in a custom route.

> What you could do: Why do you need the check in the template in the first place? Couldn't you check the permissions from your plugin and redirect directly from there?

You mean via a custom route catching all requests for pages and assets? That is what I wanted to provide the user as an option, but he might only want to use that functionality for certain content types.

**Comment by lukasbestle** [comment]
I see your point, but even extending might lead to all sorts of issues. It is already possible to register full roles using the registry, but it will only work if the users don't have their own role files (custom roles will always be checked first before checking for plugins for the same security reason).

**Comment by dweidner** [comment]
I might overlook something. Could you give a small example, what kind of issues could occur? The only thing I can think of are naming collisions with other plugins.

Otherwise it should be pretty save to extend existing Roles as the Kirby core will simply ignore them when building the panel or the frontend.

**Comment by lukasbestle** [comment]
Well, let's say, the custom role only has a permission `* => false`. If you were able to *add* a permission, you could go around all of that.

One way would be to check if the custom permission is in the Kirby/Panel namespace, but such checks aren't great as they will make it all more complex.

**Comment by dweidner** [comment]
Ah, now I see what you mean. Namespacing would indeed be a solution. But as you said, that would increase the complexity. I guess that is not justifiable for a bit of syntactic sugar (at least in my use case). 

I close this for now. Would be happy to reopen this issue, if someone else is stumbling over this during plugin development.

**Comment by dweidner** [comment]
Just for reference the plugin I am working [Kirby Firewall](https://github.com/dweidner/kirby-firewall).
