### ISSUE TITLE
[Panel] - Hard to click in drag and drop zones when using a tablet pen

### ISSUE THREAD

**Issue by gerardkd** [getkirby/kirby#513]
For example: when trying to click on the `settings` icon and after that, the `rename` link, it gets recognised as a drag sometimes, which is kind of confusing. Is it possible to add some sort of treshold to the drag, to overcome this? I'm on a Mac with a Wacom Intuos (oldie) tablet with pen.

![dragdrop](https://user-images.githubusercontent.com/5598068/41852502-9bfdbbda-788b-11e8-80e4-1800ef8b91f2.gif)

**Comment by bastianallgeier** [comment]
Duplicate: https://github.com/k-next/starterkit/issues/445
