### ISSUE TITLE
Option to disable Whoops

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#514]
Personally when I echo something before the error accurs it does not show because Whoops only focus on the error. In order for it to work I need to set `die;` in the correct place and it's not always easy to know where that is.

**There are some problems related to Whoops (quotes not by me):**

https://forum.getkirby.com/t/option-to-disable-whoops/5726/8

>Whoops is currently not of any help during development. It actually makes debugging more difficult.

>Even on something silly like an 'E_NOTICE', the entire page is going down. For the visitor, it looks like the site is in maintenance mode

>this does not help your SEO either.

>There is a link that leads to getkirby.com, thus giving away that the site is running on Kirby. That actually makes things easier for attackers.

**What also makes me concerned is that people are starting to talk about hacking the core for it:**

>You can try to comment out line 218 (start the error handler) in /kirby/kirby.php but I'm not sure about any side effects this might have.

>This is the first time in my life I am messing with the core of any software, but untill there is a fix, I see no other option.

>because usually your site should be error free :slight_smile: you can also change the template for that error page in /kirby/views/fatal.php

>I messed around with the core already, but this should never have to be done

**Comment by samnabi** [comment]
I agree that there should be an option to disable Whoops, and it would also be nice to define different error levels that trigger it (i.e. enable for E_NOTICE on development server only).

**Comment by bastianallgeier** [comment]
This is now solved on the develop branch.
