### ISSUE TITLE
[Panel] Save bar contrast

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#514]
I find the text in the save bar a bit hard to read. Maybe that's something that will change anyway, but I wanted to point it out anyway.
Here's a link to the result of a color contrast checker taking the text opacity into account: https://webaim.org/resources/contrastchecker/?fcolor=313942&bcolor=81A2BE 

Maybe you could use the lighter background of `info` fields?

![savebar](https://user-images.githubusercontent.com/7975568/41858514-628c49f2-789a-11e8-8d14-aa8a917085d6.png)
![savebar2](https://user-images.githubusercontent.com/7975568/41858515-62a893dc-789a-11e8-9d38-8c1deb45597e.png)

**Comment by johannschopplich** [comment]
There is nothing to oppose the Color Contrast Checker, no question about it. Nevertheless, I am very satisfied with the darker current blue. I find it pleasant that the "Save" button does not catch the eye too much...

A highly subjective subject I guess.

**Comment by bastianallgeier** [comment]
✅ We moved to our "notice" orange. We believe that it's necessary to make it clearer that way that there's something you have to do in order to save the content. The focus blue felt too subtle.
