### ISSUE TITLE
Plugin assets can't be found

### ISSUE THREAD

**Issue by samnabi** [getkirby/kirby#516]
Sorry for the vague title. I'm not quite sure what's gone wrong, and more importantly, I'm not quite sure why a weird hack fixes it.

Let's start at the beginning...

I'm working on the next version of Shopkit, which will have [CSS assets moved to the plugin folder](https://github.com/samnabi/shopkit/issues/106). I followed the instructions on Kirby's docs page to move the CSS folder to `/site/plugins/shopkit/assets/css`, and I updated my template code with `css('assets/plugins/shopkit/css/shopkit.css')`.

Unfortunately, this breaks the site. None of the stylesheets are loading. Navigating directly to `domain.com/assets/plugins/shopkit/css/shopkit.css` gives a standard 404 error page.

At this point, I can determine that [the route at line 344 of `kirby/kirby.php`](https://github.com/getkirby/kirby/blob/master/kirby.php#L343) isn't being triggered for some reason. I'm not sure why.

So, I copy that route and [register it again through my plugin](https://github.com/samnabi/shopkit/commit/9a587d3afa5e404661dfb56f6032a9384f1c8e6d#diff-84664b09b9015c5044b148b7b71575f6). Now the plugin assets are referenced properly.

Now here comes the twist...

Even though the assets are working properly, they're not using my duplicated routes function. They're using the original one in `kirby.php`. I can verify this by removing the function code entirely from my duplicated route.

```php
$kirby->set('route',[
  // Weird hack that somehow ends up activating the route in line 344 of kirby.php
  'pattern' => 'assets/plugins/(:any)/(:all)',
  'method'  => 'GET',
]);
```

I tried to create a reduced test case for this with the Starterkit, but I wasn't able to replicate the bug. I can keep digging to try and pin this down within Shopkit, but it's hard to remove components without triggering other unrelated errors.

So I was wondering if I'm overlooking something? Does any of this make sense to someone else? This latest code has been pushed to the [`dev` branch of Shopkit](https://github.com/samnabi/shopkit/tree/dev).

All the best,

Sam

**Comment by lukasbestle** [comment]
Could you try disabling the `languages` option to disable the multilang feature? I'm pretty sure it's related to that.

**Comment by samnabi** [comment]
That's it, thanks for the hint! Now it's possible to show a reduced test case.

To replicate this issue:

1. Download the latest langkit.
2. Add a new plugin with a `custom.css` asset, using the folder structure displayed below.
3. Navigate to `domain.com/assets/plugins/testplugin/css/custom.css` -- it will show a 404 error page.

![screen shot 2016-11-20 at 22 59 48](https://cloud.githubusercontent.com/assets/1731536/20470320/6bdf4102-af75-11e6-8e71-17cde2ac5911.png)

**Comment by lukasbestle** [comment]
I have fixed this on the develop branch. Please test if it works now.

**Comment by samnabi** [comment]
Yes, that fixes it. Thanks for the prompt action!
