### ISSUE TITLE
[Panel] Save bar UX - Keep all at the bottom

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#517]
I like the idea behind the bottom bar for the save action. It keeps the top bar more free. I also have a UX problem with the current implementation.

I'll explain with some images. I put two eyes on every image to illustrate where I look when I click and after.

## Current implementation

![image](https://user-images.githubusercontent.com/927011/41891526-1d44cba0-7915-11e8-8835-3eb307b1897b.png)

![image](https://user-images.githubusercontent.com/927011/41891733-e3533bec-7915-11e8-9cf6-6dc5cce31027.png)

In this implementation I kept looking at the bottom to see the change. When I hit save, the only thing that I saw was that the bottom bar closed itself. Then later I discovered that the save was at the bottom and the save message was at the top. A bit jumpy for the eyes, expecially on large screens.

## The solution

This is what I expected/hoped would happen.

![image](https://user-images.githubusercontent.com/927011/41891526-1d44cba0-7915-11e8-8835-3eb307b1897b.png)

![image](https://user-images.githubusercontent.com/927011/41891646-9b5aa0e6-7915-11e8-8e71-d1b4fc852018.png)

- Less jumping around for the eyes.
- Less confusing when the bottom does not just close.
- You free up even more space in the top bar.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#22](https://github.com/k-next/ideas/issues/22).
