### ISSUE TITLE
mp4 mime type missing on production + not in mimes array

### ISSUE THREAD

**Issue by fourpixels** [getkirby/kirby#517]
Hey guys,
I've been using Kirby with a great of joy, but I just stumbled upon something today. I've made a simple `video` snippet, which basically prints out a html5 video tag, along with sources. Long story short, I have a `video object` (Kirby's own, got from `$page->videos->find('filename')`) on which I call `$video->mime()`.

This works just fine on localhost, running Apache with PHP 5.6.25. But going on production, LiteSpeed with PHP 5.6.28 calling `$video->mime()` returns *nothing* (""). I checked the code and ended up in `f.php`:

```php
public static function mime($file) {
...
}
```

I've debugged all the options and it turned out none are available. It goes all the way until the end of the function:

```php
return f::extensionToMime(f::extension($file));
```

But as I searched for, mp4 was not listed in the mime array. So here are a few questions:

1. Why my server cannot find the mime type - am I missing something, some configuration?
2. Is there any way I can make my server work properly finding the mime type?
3. Why is not mp4 listed in the mime types array? I'm pretty new to php, so maybe some encodings are in play or something else?
4. Is there any safe workaround, as I've currently hacked mp4 into the array with `video/mp4` value :smile:

**Comment by lukasbestle** [comment]
The mime type array is just an internal fallback in Kirby. We can't add every single extension there (and also the fallback isn't that great and reliable).

Best way to fix the PHP setup on the server in the first place by [enabling `Fileinfo`](http://php.net/manual/en/fileinfo.installation.php).

**Comment by fourpixels** [comment]
I can see in my `phpinfo();` output this:

```php
'--enable-fileinfo=shared'
```

And within the module authors section:

`fileinfo	Ilia Alshanetsky, Pierre Alain Joye, Scott MacVicar, Derick Rethans`

I think that means the file info is working?

**Comment by lukasbestle** [comment]
That's strange. What does `var_dump(function_exists('finfo_file'))` result in?

**Comment by fourpixels** [comment]
`bool(false)` :(

Here it is: http://notfabrik.com/phpinfo.php

**Comment by lukasbestle** [comment]
Hm...
To be honest I have no idea what could cause this. Please try contacting your hosting provider.

**Comment by fourpixels** [comment]
Uhm, okay, but ask what? :) As far as I can see, there is file info available, so you're saying it's just not working properly?

**Comment by lukasbestle** [comment]
Yes. If the function is not available, that means that it's not actually available.

**Comment by bastianallgeier** [comment]
I just added mp4 to our mime type translation list, but I agree with Lukas that this should be fixed on your server for a more reliable solution.
