### ISSUE TITLE
Installing the panel on LiteSpeed webserver

### ISSUE THREAD

**Issue by ghost** [getkirby/kirby#518]
Hi all

I'm running the alpha of Kirby 3 on Cyon.ch, one of Switzerland's largest webhosters. However, it seems the panel cannot be installed, probably because it cannot identify Apache, Nginx or Caddy.

<img width="395" alt="bildschirmfoto 2018-06-26 um 08 26 58" src="https://user-images.githubusercontent.com/34234200/41893418-f3341076-791b-11e8-90ce-f605e4a88c18.png">

Cyon uses LiteSpeed as a webserver, which is 100% compatible with Apache. I assume running Kirby on LiteSpeed would run without any issues. Would it be possible to adjust the panel installation to allow LiteSpeed?

Thanks & kind regards

Stefan

**Comment by bastianallgeier** [comment]
I just added LightSpeed to the whitelist of supported servers on the develop branch. Will be in the next version. If you want to give it a try already, you can replace the file kirby/src/Cms/System.php with the one from the develop branch and it should work.

**Comment by ghost** [comment]
perfect, works flawlessly now!
