### ISSUE TITLE
Generated images filename always ends with "-blur"

### ISSUE THREAD

**Issue by dionysiusmarquis** [getkirby/kirby#519]
Hi,

my generated images always end with `-blur`. I think it's because the `Thumb->options` function should check if blur is any other than `false` in the first place here:
https://github.com/getkirby/kirby/blob/master/kirby/component/thumb.php#L169

or did I miss something migrating to 2.3/2.4?

**Comment by lukasbestle** [comment]
See #515. This is fixed on the develop branch for 2.4.1.

**Comment by dionysiusmarquis** [comment]
Ah ok, thank you ✌️
