### ISSUE TITLE
youtube-nocookie.com not recognized

### ISSUE THREAD

**Issue by drhirn** [getkirby/kirby#521]
Hi,

Youtube allows to share videos in a non-cookie-mode. URLs are then like http://www.youtube-nocookie.com/embed/d9NF2edxy-M
Kirby unfortunately doesn't recognize them.

Tried changing /vendor/getkirby/toolkit/lib/embed.php. Should look like

`//http://www.youtube-nocookie.com/embed/d9NF2edxy-M`
`} elseif(preg_match('!youtube-nocookie\.com\/embed\/([a-z0-9_-]+)!i', $url, $array)) {`
`  $id = array[1];`

I think, but I'm not completely sure.
And I don't know, what to do with the `array_merge` on line 50. Especially the `src`-thing.

Maybe someone else could add `youtube-nocookie.com` please?

Thx
Stefan

**Comment by lukasbestle** [comment]
Thanks, good point. I have moved this to https://github.com/getkirby/toolkit/issues/203.
