### ISSUE TITLE
Some errors in the shop page

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#522]
I found some errors on the shop page.

![image](https://user-images.githubusercontent.com/927011/41897003-6492de64-7926-11e8-9205-c2296094d3bc.png)

**Comment by jenstornell** [comment]
Even more...

>VM33:1 GET http://localhost/kirby/3.0-alpha-11/api/auth 500 (Internal Server Error)

>app.js:1 {status: "error", exception: "Kirby\Exception\Exception", message: "Unexpected file system error", key: "error.session.filestore.unexpectedFilesystemError", file: "\projects\kirby\3.0-alpha-11\kirby\src\Session\FileSessionStore.php", …}

>shop:1 Uncaught (in promise) {status: "error", exception: "Kirby\Exception\Exception", message: "Unexpected file system error", key: "error.session.filestore.unexpectedFilesystemError", file: "\projects\kirby\3.0-alpha-11\kirby\src\Session\FileSessionStore.php", …}

The last errors appeard when I got back from lunch.

**Comment by lukasbestle** [comment]
The last two errors are from the new session handler, but are (as the name implies) unexpected errors. They should actually never occur and haven't ever occured in my quite exhaustive tests.

Two questions:

1. Do you by any chance have the rest of the error data, especially the line number of the errors?
2. Which operating system does the backend code run on?

**Comment by jenstornell** [comment]
I closed the tab and started working on other things. But if they are not fixed I probably run into them soon again.

2. Windows 10, Chrome latest, Xampp, PHP7

About the last errors. I was at lunch so I guess it's because some kind of session timeout, maybe. Leave your computer for a few hours and you may get the same error, in case it's not affected by my first two errors.

**Comment by lukasbestle** [comment]
My current guess is that it's because your backend and therefore file system runs on Windows. The errors are file system errors related to file locking, reading and writing to the session files. The same error is however thrown in different places, so the line number as well as any further details from the error object would help a lot in case you have the same issue again.

I'm pretty sure that the first two errors on the shop page are unrelated though.

**Comment by bastianallgeier** [comment]
I think I fixed the first. Let's close this. @jenstornell it would be great if you could open another ticket, when the session issues pop up again.

**Comment by lukasbestle** [comment]
@jenstornell The session-related errors should now be fixed on the develop branch (will be in Beta 1).
