### ISSUE TITLE
Textarea : inactive button with firefox

### ISSUE THREAD

**Issue by Yoh7** [getkirby/kirby#524]
Select on the headline button but the textarea is not updated.
Popup on the mail and link buttons but the textarea is not updated.
No reaction for other buttons

Everything ok on Chrome.

EasyPhp - Apache 2.4.25 - Php 7.1.3
Win 7 pro sp1
Firefox 60.0.2

**Comment by bastianallgeier** [comment]
Firefox has a bug that isn't fixed for months/years and which breaks the code we are using to insert text in the textarea. We will need a fallback for FF that won't be as good as the code we have, because it doesn't support the undo history. We will implement it as soon as possible.

**Comment by bastianallgeier** [comment]
✅
