### ISSUE TITLE
Allow colons in structured content

### ISSUE THREAD

**Issue by fitzage** [getkirby/kirby#525]
Structured content requires quote marks around any string containing a colon. I know why this is, because it's trying to parse each colon on the line as a key, and it fails because it knows it can't parse the second one. Putting the quote marks is an easy but annoying fix. Proper behavior would be for it just to ignore the second colon on the line and only stop parsing after the first one.

This is the way normal kirby fields behave. If I have a title with a colon in it, I don't have to do anything different to make it work. Kirby is just smart enough to handle it.

**Comment by lukasbestle** [comment]
Kirby uses the [YAML syntax](http://yaml.org) for structured content. Kirby can't fix this without being incompatible with the rest of the world, that's just how the standard works and there's most likely a reason for this. :)

**Comment by fitzage** [comment]
OK, well I guess YAML just sucks. But I'll deal with it.

**Comment by lukasbestle** [comment]
YAML is great, it just has a few flaws just like any other markup language. :)
