### ISSUE TITLE
[Cms] Memory error - Navigation between page

### ISSUE THREAD

**Issue by Yoh7** [getkirby/kirby#525]
I play with draft, unlisted, published then try to navigate between page with the arrows

![navigate-1](https://user-images.githubusercontent.com/40626038/41964755-2786e666-79fb-11e8-8d52-4e243e8e506d.jpg)

then

![navigate-2](https://user-images.githubusercontent.com/40626038/41964770-303cf408-79fb-11e8-8a32-24385d8d6508.jpg)

then

![navigate-3](https://user-images.githubusercontent.com/40626038/41964775-34e83706-79fb-11e8-9691-20bbca305f3a.jpg)

then

![navigate-4](https://user-images.githubusercontent.com/40626038/41964778-394d2c34-79fb-11e8-8844-69a78316734c.jpg)

on frontend : `Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1702128016 bytes) in \kirby\config\aliases.php on line 49`

**Comment by distantnative** [comment]
@Yoh7 It would be great if you could provide some information how to reproduce this. "I play with draft, unlisted, published" - what steps did you do before trying to navigate round with the arrows? Thank you.

**Comment by Yoh7** [comment]
I played a lot with the project page, changed the status of each project several times and then navigated with the arrows. The memory error has occurred several times but I can not reproduce it in a systematic way ... sorry.

win 7 sp1
esasyphp - apache 2.4.25 - php 7.1.3
firefox 60.2

**Comment by bastianallgeier** [comment]
I think it has to do with the thumbnail generation.

**Comment by bastianallgeier** [comment]
Probably related to: https://github.com/k-next/starterkit/issues/526

**Comment by bastianallgeier** [comment]
✅
