### ISSUE TITLE
[Cms] Thumb generation exceeds maximum execution time

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#526]
A page with a lot of images can easily break on first load due to the time Kirby requires to generate thumbs. This issue escalates with different image sizes defined in `srcset`. So you get timeouts a lot:

> `Whoops \ Exception \ ErrorException (E_ERROR)`
> Maximum execution time of 30 seconds exceeded

Increasing the execution time is not a good option because the site becomes unresponsive while generating the images.

1. I would expect Kirby to only generate images that are actually requested by the browser. 
2. Additionally or alternatively, I'd expect an option in the panel to generate the thumbs asynchronously when saving a page in the Panel. This could be defined the blueprint.

**Comment by bastianallgeier** [comment]
✅

**Comment by nilshoerrmann** [comment]
This works great!

**Comment by nilshoerrmann** [comment]
Okay, I spoke too soon. While this works perfectly on our localhost (error message gone, no timeout), we see a strange behaviour on our project server: instead of images the server returns JSON objects for each request, e. g.:

```json
{
    "autoOrient": true,
    "blur": false,
    "crop": "center",
    "filename": "woodlawn0148.jpg",
    "grayscale": false,
    "height": 1200,
    "quality": 90,
    "width": 1800
}
```

Both server are on PHP 7.2. We are using MAMP locally.

**Comment by bastianallgeier** [comment]
@nilshoerrmann https://github.com/k-next/kirby/issues/648
