### ISSUE TITLE
Single line breaks are transformed to <br>

### ISSUE THREAD

**Issue by FaKeller** [getkirby/kirby#526]
The following Kirby markdown text:

```md
First line.
Second line.
```

would translate to the following HTML:

```html
<p>First line.<br>Second Line.</p>
```

However, even the [original Markdown specification](https://daringfireball.net/projects/markdown/syntax#p) by John Gruber only treats blank lines as line break. Is there any option to turn off the current behavior to have the true markdown behavior? Or is this a bug?

Personally, I have the contents of the pages in a Git repository and putting every sentence in a newline improves the git diff.

**Comment by fabianmichael** [comment]
Actually, there is an option which allows you to toggle this behavior.
https://getkirby.com/docs/cheatsheet/options/markdown-breaks

**Comment by FaKeller** [comment]
I was looking through the documentation, but couldn't find the answer I was looking for. Of course, now that I opened the issue I found the answer in the docs:

https://getkirby.com/docs/cheatsheet/options/markdown-breaks

The following config setting meets my expectations:

```php
c::set('markdown.breaks', false);
```
