### ISSUE TITLE
Typo in empty search result message

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#527]
I assume this should read **Subpages** (with a b), not Supages:

<img width="521" alt="bildschirmfoto 2018-06-27 um 12 27 20" src="https://user-images.githubusercontent.com/149678/41968880-fe4eef4a-7a05-11e8-924a-f1d533396ccf.png">

`<div class="kirby-search-empty">
      No Supages
    </div>`

**Comment by bastianallgeier** [comment]
Note to ourselves: should be a translated string anyway.

**Comment by bastianallgeier** [comment]
✅
