### ISSUE TITLE
Inconsistent naming slug / URL appendix

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#529]
I have noticed an inconsistency regarding the usage of the terms "slug" and "URL appendix" in the panel. Whenever an error message shows up, the term "slug" is used – but the menu item I need to call up to change the slug is called "Change URL", the field itself "URL appendix". 

Although slug is the correct Kirby term, I find it hard to understand for a common user – and as the menu/field naming differs anyway, I would suggest to use "URL appendix" within the error messages, too.

<img width="545" alt="bildschirmfoto 2018-06-28 um 10 43 53" src="https://user-images.githubusercontent.com/149678/42023795-01d28a6c-7ac1-11e8-9424-0e926c237e8a.png">
<img width="226" alt="bildschirmfoto 2018-06-28 um 10 44 50" src="https://user-images.githubusercontent.com/149678/42023805-083141dc-7ac1-11e8-934b-2bbd43285d80.png">
<img width="536" alt="bildschirmfoto 2018-06-28 um 10 44 59" src="https://user-images.githubusercontent.com/149678/42023807-09e65cce-7ac1-11e8-9d7b-9de9f3c95b3e.png">
<img width="520" alt="bildschirmfoto 2018-06-28 um 10 45 19" src="https://user-images.githubusercontent.com/149678/42023825-13edfc68-7ac1-11e8-8432-9ce11f12de6d.png">

**Comment by bastianallgeier** [comment]
✅
