### ISSUE TITLE
Error message regarding title / slug

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#530]
When I create a new page and enter a title, this error message might show up:

<img width="545" alt="bildschirmfoto 2018-06-28 um 10 43 53" src="https://user-images.githubusercontent.com/149678/42024911-8ffc7058-7ac3-11e8-92e4-3c5ae9a0a0b3.png">

As a developer, I understand what is happening, but my clients will not: The user doesn't see that the slug is created from the title in the background, and the error message does not address that he/she needs to change the title in order to create a unique slug.

Issue #31 can solve this partly, and #529 also plays into this, but the problem remains – I enter a title and might receive an error because of another field, which is not even visible, but hidden in the top drop-down menu.

Could a possible solution be to make sure the slug is definitely unique, e. g. by automatically adding a number?

**Comment by bastianallgeier** [comment]
✅ I fixed this by showing the Url appendix field in the page creation dialog, like in v2.
