### ISSUE TITLE
[Panel] Role permissions (user blueprints)

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#531]
I really appreciate the new permissions concept implemented with user role blueprints, so I tested all available options quite thoroughly (Alpha 11). Since they are not in sync with notion I took all options actually available in the source code and want to list what's working/not working and all issues I found:

:x: does not work
:white_check_mark: does work, but with issues or unexpected behavior
:heavy_check_mark: does work as expected

## `access:`

:white_check_mark: **`panel: false`**
- [x] does work in general, redirects to the website when logging in or being logged in and trying to access the panel by URL.
- [x] but when pressing the back button of the browser after redirecting you see an empty page with the panel top bar where one can inspect the whole site structure via the search. The items are not accessible (getting redirected to the website again on enter or click) but one can still see pages or e.g. articles that are unlisted / in review. Drafts don't appear in the search at all.
- [x] when logging in as a role without panel access, there should be no alert `„You don‘t have panel access“` but just a redirect to the website. This way the panel login could be used for front-end users as well, but of course they should never see the panel at all (only the login form).

:white_check_mark: **`users: false`**
- [x] when clicking on "users" in the main menu (coming from "Site") `„error.access.view“` appears but you still end up in the users page.
- [x] without setting the other `user` options to `false` this role then can create, rename, edit, change password and delete other users (even admins), although this option should overwrite all other user-options.
- [x] coming from "my account" or any other subpage and clicking on "users" in the main menu (or going to the users page by URL) it works as expected, shows an alert and redirects to the "Site".
- [x] so in case of `users: false` the menu entry "users" should be disabled and not accessible at all.

:x: **`site: false`**
- [x] with this option one seems to have acces to the panel (not being redirected to the website) but the whole panel view is empty.
- [x] also this causes an endless loop where the laptop fans start to spin like crazy until Firefox asks to stop the page.
- [x] actually the `site: false` option does not make a lot of sense right now. As of Kirby 2 I would expect it to block the "site settings", but in Kirby 3 "site" is the main backend part and one cannot use the panel at all. Nothing is accessible except of the "users" page or "my account" if the previous option `users` is `true` and accessing it directly via URL).

## `file:`
These options as well as page options generally apply to all files/pages throughout the panel. But what if a certain user role should be allowed to create, edit and delete own pages/files but be blocked for other's files/pages? Or they should be allowed to create drafts but not publish them on their own (they would need to be reviewed by another role with the appropriate rights like Bastian mentioned in one live-stream)?

As of now, a certain role is either blocked completely from doing anything on files/pages or can even rule the foreign ones. **I think it is quite important to further differentiate those permissions** (i.e. rule them all, rule only own, or not rule at all).

Also there should be a separate rule to allow/forbid sorting of files/pages for certain roles (`sort: false`).

:white_check_mark: **`changeName: false`**
- [x] does work and blocks renaming but the modal still opens and one only knows that it is forbidden after pressing Enter or OK.
- [x] the modal should not open at all with this option.

:white_check_mark: **`create: false`** 
- [x] the "Add" button stays visible and clickable (should be deactivated and greyed out completely)
- [x] the file selecor opens on click and after selecting a file and pressing OK, the progress bar appears for a second and it looks like it actually works until `„Error: The file cannot be created“` appears.
- [x] this does not tell about missing permissions and a user would try it again since it seems to be working in general and that only something went wrong while uploading.

:heavy_check_mark: **`delete: false`**
- [x] does work and disables the option in all context menus

:heavy_check_mark: **`replace: false`**
- [x] does work and disables the option in all context menus

:heavy_check_mark: **`update: false`**
- [x] does work and disables all file (meta) fields.
- [x] but maybe they should be not greyed out as much (not very readable) and maybe text should be selectable / copyable still (no big issue though)

## `page:`

:heavy_check_mark: **`changeSlug: false`**
- [x] does work and disables the option in all context menus

:white_check_mark: **`changeStatus: false`**
- [x] does work in general and disables the option in all context menus
- [ ] but the status icon of elements in list views (overviews) is not deactivated and still clickable, although the error box appears showing `error.page.changeStatus.permission`
- [x] related to #394 and #378

:heavy_check_mark: **`changeTemplate: false`**
- [x] does work and disables the option in all context menus

:white_check_mark: **`changeTitle: false`**
- [x] does work and blocks renaming but the modal still opens and one only knows that it is forbidden after pressing Enter or OK.
- [x] the modal should not open at all with this option.

:white_check_mark: **`create: false`**
- [x] the "Add" button stays visible and clickable (should be deactivated and greyed out completely)
- [x] the new page modal opens on click and only after pressing OK `„You are not allowed to create ...“` appears.
- [x] the modal should not open at all with this option.

:heavy_check_mark: **`delete: false`**
- [x] does work and disables the option in all context menus

:x: **`preview: false`**
- [x] does not seem to have any function at all yet
- [x] one can open every page from the page view and always sees the published version of it but no preview of changes.
- [x] only if "open" is a context menu option (linke in e.g. the blog) it gets deactivated / grayed out by this.

:heavy_check_mark: **`update: false`**
- [x] does work and disables all fields.
- [x] but maybe they should be not greyed out as much (not very readable) and maybe text should be selectable / copyable still (no big issue though)

## `site:`
:white_check_mark: **`update: false`**
- [x] does work and disables all fields in the tabs of "Site".
- [x] but sorting of elements is still posible which is either part of update or should be a separate option (like mentioned above)

## `user:`
The (singular) name suggests, that user options are for the certain user role only but everything that is set to `true` here will allow the corresponding action on all users (including admins).

Actually there should be both, `user` permissions on the own user account and separately settable `users` permissions valid for other / foreign users.

E.g. a user of a certain role could be allowed to change his/her own name, language, email and password but not to change other accounts.

**Ultimately it would be great to create a hierarchy of roles and permissions**.
It should be definable in `users` which other user roles can be created, updated or deleted by this role.

E.g. an admin can do everything of course, but the redacteur should not be allowed to add, update and delete admins but authors / editors (hierarchically below them). And accordingly a author should only be allowed to change his own details but have no rights on other users.

:x: **`ChangeEmail:`**
- [ ] „Not yet implemented“

:white_check_mark: **`changeLanguage: false`**
- [x] does work and disables changing the language in all context menus.
- [x] but in a single profile view the modal opens by clicking on the language and one only knows that it is forbidden after selecting a language and pressing Enter or OK. (`„You are not allowed to change the language for the user ..."`)
- [x] the modal should not open at all with this option.

:white_check_mark: **`changeName: false`**
- [x] does work and disables renaming in all context menus.
- [x] but in a single profile view the modal opens by clicking on the name and one only knows that it is forbidden after pressing Enter or OK. (`„You are not allowed to change the name for the user ..."`)
- [x] the modal should not open at all with this option.

:heavy_check_mark: **`changePassword: false`**
- [x] does work and disables changing the password in all context menus.

:white_check_mark: **`changeRole: false`**
- [x] does work and disables changing the role in all context menus.
- [x] but in a single profile view the modal opens by clicking on the role and one only knows that it is forbidden after pressing Enter or OK. (`„You are not allowed to change the role for the user ..."`)
- [x] the modal should not open at all with this option.

:white_check_mark: **`create: false`**
- [x] does work and disables / greys out the `user.create` option.
- [x] but if set to `true` it allows to add all other user roles (even admins). This should not be an option for `user` but for `users` like suggested above.

:heavy_check_mark: **`delete: false`**
- [x] does work and disables deleting users in all context menus.

:white_check_mark: **`update: false`**
- [x] does work and disables all users fields.
- [x] but again this should be separately defineable for the own user account and others.

**Comment by bastianallgeier** [comment]
Wow! Thank you very much for the super extensive testing. This helps a lot.

**Comment by bastianallgeier** [comment]
Here's a summary of the first set of changes: 

- Most issues should be fixed
- All `page` permissions are now under `pages`
- All `file` permissions are now under `files`
- All `user` permissions are now under `users`
- There are new `user` permissions for the current account as you rightly suggested.  
- `access > site` is gone. It doesn't make sense without a dashboard view, because we can't escape to any other useful route, if access to the site is blocked
- `page > preview` is gone. Doesn't make sense either. 
- There's a new `site > changeTitle` permission to stay consistent with the rest. `site > update` only refers to content updates via forms.

I'm still working on the few missing checkboxes. Thank you again for your brilliant input.

**Comment by bastianallgeier** [comment]
I will close this and moved the last outstanding tickets to separate issues:

- https://github.com/k-next/starterkit/issues/543
- https://github.com/k-next/starterkit/issues/544
