### ISSUE TITLE
Custom Fatal-view

### ISSUE THREAD

**Issue by sebsel** [getkirby/kirby#531]
Would be nice to check `/site/views/fatal.php` first, before calling `/kirby/views/fatal.php`, so we can customise :)

or: `c::set('fatal-template', 'fatal');` (or something) and then grab `/site/templates/(...).php`.

and/or/related: fatal.php does not contain php, and probably shouldn't, so maybe better call it fatal.html?

https://github.com/getkirby/kirby/blob/master/kirby/errorhandling.php#L105

**Comment by panagiotisTB** [comment]
Hey guys, 
Any news concerning this idea?

**Comment by lukasbestle** [comment]
We haven't implemented this in Kirby 2 as it's difficult to get this right (for example what happens if the error occurs before the configuration could be loaded?). But as the feature has been requested several times, it will be in Kirby 3. :)
