### ISSUE TITLE
[Panel] User field - opens selected user profile

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#532]
When entering text in a user field it filters / searches matching users as expected, but when selecting a user from the resulting dropdown list via mouse click, it opens the user profile.
When selecting with keyboard (Enter and Tab) it works as expected.

When a user field has a user already selected, the press on the user field will also open the user's profile instead of focusing it and allowing to change the user. In this case it is not possible by keyboard either and it only works after removing the user by the x-button.

**Comment by bastianallgeier** [comment]
✅
