### ISSUE TITLE
[Panel + UX] Date field "invalid array length" and other issues

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#533]
Unfortunately, there are several bugs with the date field:

- [x] when clicking on the calendar icon of an initially empty date field (like in the "Form demo"), an `invalid array length` error occurs.
- [x] when clicking or tabbing to the empty "day" part of the date field, nothing is selectable. It feels broken when the day is the first offered part of the field (although I know that the amount of days can not be determined before selecting a month).
- [x] after selecting a month or year first, a full date becomes available imediately (but not the desired one) and the calendar dropdown becomes available. (So then I have to tab back to change the day and/or month or select it from the calendar dropdown).
- [x] the calendar dropdown works as expected (after it becomes available on selecting a month or year) and every selected date will appear correctly in the field.

I suggest to initially offer 31 days when nothing is selected and reduce the available options when selecting a month with less days.

- [x] also, if e.g. the 30th or 31th is selected but I want to change the month to a month with less days, this is not possible (could be reduced to the last day of that month).
- [x] and finally, while being able to select any offered day or year option correctly, I can only select every second month option from the dropdown or by keyboard. When I select e.g. 01 it jumps to 02 and on 03 to 04. Same happens when changing the month by down key. With the up key I can select the skipped months in between, too but it takes two key presses for each step. 01 never becomes available this way and it clears the field completely when there should be 01.

**Comment by bastianallgeier** [comment]
✅ should all be solved!

**Comment by R3D2** [comment]
After changing the date of an already saved page, date fiels are emptied.

Clicking on them to set a new date show an error : "Invalid array length"

That's what is registered on the yml files :

`
Date-start: ThuThu/OctOct/2019201920192019
`

I tried with an other page and it does exactly the same thing, regression ?
