### ISSUE TITLE
$page->update('a-field' => null) not working

### ISSUE THREAD

**Issue by sebsel** [getkirby/kirby#533]
So, if you have a field with a `-` in it, you can do:
```
$page->update([
  'a-field' => 'some value'
]);
```
And it will write out as `A-value: some value` in the .txt file. But to remove the field by setting it to `null`, you have to call `['a_field' => null]` with a `_`.

**Comment by bnomei** [comment]
great find.

using minus in fieldnames is valid yaml but a bit uncommon, right? 
since using the field with magic method does not work.

```php
echo $page->a-field(); // not valid php
```

**Comment by jenstornell** [comment]
Because of the pitfalls of using `-` as yaml keys, I suggest being even more restrictive in this case.

**Not allowed**

```php
$page->update([
  'a-field' => 'some value'
]);
```

**Allowed**

```php
$page->update([
  'a_field' => 'some value'
]);
```

As @bnomei already said `echo $page->a-field();`will not work anyway.

**Comment by Sija** [comment]
You can do `echo $page->{"a-field"}()`.

**Comment by bnomei** [comment]
this just works for kirbys field magic functions. php functions [can not have a dash](http://php.net/manual/en/functions.user-defined.php).

**Comment by Sija** [comment]
Isn't it the usecase?

**Comment by bnomei** [comment]
yaml ok. kirby ok. php not. so using dash in kirby blueprint fieldnames might not be a good idea. just my opinion.

but i agree since its valid yaml kirby should allow setting `null` without a bug.

**Comment by sebsel** [comment]
Yes, in my case, I don't use the panel, so I don't care about breaking that. (I also believe it worked fine when I did use it?) I am already treating `-` and `_` as synonyms depending on context (yaml vs php).

So I am using in the .txt file:
```
A-field: some value
```

And in php:
```php
echo $page->a_field();
$page->update(['a-field' => 'some value']);
```

In the second php line, the fieldname is within quotes, so you can use a `-`. Since Kirby allows the use of `-` when updating into a value, it should also allow `-` when updating to `null`.

I just don't like to camelCase all the things :)

**Comment by sebsel** [comment]
Note that there is also `$page->content()->get('a-field');`, when you really need to use the `-` for some reason.

**Comment by texnixe** [comment]
Note that Kirby store keys with underscores as keys with dashes in content files, anyway.

**Comment by lukasbestle** [comment]
`$page->update()` is now fixed on the develop branch.
`$page->content()->get()` was not fixed as providing field values with the field alias names might be causing chaos somewhere (field duplication).
