### ISSUE TITLE
[Panel] Pressing Enter on most form fields returns "t is undefined"

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#535]
As the title says, pressing Enter on most form fields (without or after input) returns an error `t is undefined`. This only happens on Enter, Tab and CMD+S work like in Kirby 2.

**Comment by distantnative** [comment]
I even get `Cannot read property 'preventDefault' of undefined`.

**Comment by distantnative** [comment]
@REHvision could you check the console for any other errors (sounds like the translation files are not properly loaded)? Can't reproduce this with the current state on the develop branch at the moment (using chrome on mac - maybe it's related to your setup? which browser, os?). Thanks.

**Comment by REHvision** [comment]
Indeed, it seems related to translations:

**Hosted on server with:** Apache 2.4.6 (CentOS) running PHP 7.1.19
**My OS:** Ubuntu 17.10 (64-Bit)

**With Firefox (Quantum 60.0.1)**

the console logs througout the panel (even on the login screen):
`i18n: i18n locale is not set when trying to access translations: upload.progress` in `vendor.js:1:8849`

When pressing Enter on form fields the following error details get added:
`TypeError` in `app.js:1:182051`
`columnNumber: 123345`
`fileName: "https://.../media/panel/01cc0a3070a14b5b9a343723a7fc6f07/js/app.js"`
`lineNumber: 1`
`message: "t is undefined"`
`stack:`
`@ save (app.js:1:123345)`
`@ Ie/t.prototype.$emit (vendor.js:39:16512)`
`@ submit (app.js:1:138837)`
`@ e (vendor.js:39:12707)`
`@ Ie/t.prototype.$emit (vendor.js:39:16512)`
`@ onSubmit (app.js:1:42542)`
`@ submit (app.js:1:41907)`
`@ e (vendor.js:39:12707)`
`@ fe/t._withTask (vendor.js:39:11885)`
`__proto__: Object { stack: "", … }`

**With Opera (53.0.2907.57)**

the logged error throughout the panel is the same:
`i18n: i18n locale is not set when trying to access translations: upload.progress` in `vendor.js:1`

and when pressing Enter on a form field the error message looks a bit different but seems to be the same error stack:

`TypeError: Cannot read property 'preventDefault' of undefined` in `app.js:1`
`at a.save (app.js:1)`
`at cr.Ie.t.$emit (vendor.js:39)`
`at submit (app.js:1)`
`at a.e (vendor.js:39)`
`at a.Ie.t.$emit (vendor.js:39)`
`at a.onSubmit (app.js:1)`
`at submit (app.js:1)`
`at e (vendor.js:39)`
`at HTMLFormElement.t._withTask.t._withTask (vendor.js:39)`

I hope this is helpfull :wink:
Please let me know, if you need any other information.

**Comment by bastianallgeier** [comment]
✅
