### ISSUE TITLE
Let www.example.com also check `config.example.com.php`

### ISSUE THREAD

**Issue by sebsel** [getkirby/kirby#535]
So I have different `config.php`-files for localhost and my actual domain, but now I noticed that some things where not working in the www.-version of my site... because that leads to a different config-file.

Maybe check for the www.-version of the config also?
- www.example.com > check `config.www.example.com.php` > no? check `config.example.com.php` > no? check `config.php`
- example.com > check `config.example.com.php` > no? check `config.www.example.com.php` > no? check `config.php`

So you can still have config for both, or just one file if they should be the same.

**Comment by Pascalmh** [comment]
While this seems like a good idea, there shouldn't be two versions of your page online (duplicate content). Once you "fixed" this there is no more need for checking in the order you suggested.

**Comment by jenstornell** [comment]
I agree with @Pascalmh that there should not be two versions of the site. Kirby often does not try to be smart and I think it's good to keep it that way in this case.

If there still is a need to have both versions, maybe just include one of them, something like this:

**In `config.www.example.com.php`**

```php
include __DIR__ . DS . 'config.example.com.php';
```

But you should really redirect it. Maybe this will help:

https://github.com/jenstornell/kirby-htaccess-rules/blob/master/redirect-to-https-without-www.conf

**Comment by texnixe** [comment]
I also agree with @Pascalmh and @jenstornell. If you want to keep your two versions, you can include two config files.
