### ISSUE TITLE
[Panel] Toggle field not usable via keyboard

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#536]
On Enter an `t is undefined` error occurs, with arrow keys nothing happens.

**Comment by bastianallgeier** [comment]
The toggle field is actually a checkbox in disguise. It is triggered with space. But I think it's a good idea to bind enter to it additionally.

**Comment by bastianallgeier** [comment]
✅

**Comment by REHvision** [comment]
Oh, I didn't try space! Thank you :grin:

**Comment by REHvision** [comment]
@bastianallgeier I'm sorry and afraid we were to hasty in just binding Enter to the toggle field :flushed:

When pressing Enter on a focused toggle field it also gets directly safed by that (I don't know if this is the intended behaviour but at least in a regular fields setup this is okay)

But with a toggle field inside a structure field, the state changes, the structure field collapses and the page gets saved all at once. This can lead to unwanted and accidential changes of some state without even noticing it!

Either you have to remove the keybinding to Enter for a toggle field again or the toggle field should not trigger a page save when pressing Enter (like it is now with a select field).
