### ISSUE TITLE
Allow model registry to accept file

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#537]
Now the model registry looks like this:

```php
$kirby->set('page::model', 'article', 'MyNamespace\\ArticlePage');
```

While a controller looks like this:

```php
$kirby->set('controller', 'blog', __DIR__ . '/controllers/blog.php');

// You can also pass a function directly
$kirby->set('controller', 'blog', function($site, $pages, $page) {
  // ...
});
```

With the controller it's possible to register it directly or throw it into a file. I would like the same thing for models.

For me personally I'm working with a plugin where each type (snippet, template, controller, blueprint, module) is registered as file or folder. That makes it possible to just throw the code in there. Because that's not possible with a model, I'll need to skip it for now.

**Something like this:**

```php
$kirby->set('model', 'projects', __DIR__ . DS . 'model.php');
```

**Comment by lukasbestle** [comment]
This won't work as Kirby can't know the class name that is defined inside of that file. The difference to controllers is that controller functions are returned from the file. This does not work with classes.

Solution for your plugin (if you use the same naming scheme for all of your models):

```php
$models = [
  __DIR__ . DS . 'model.php' => 'projects',
  // ...
];

foreach($models as $path => $template) {
  require_once($path);
  $kirby->set('model', $template, 'MyNamespace\\' . ucfirst($template) . 'Page');
}
```
