### ISSUE TITLE
[Panel] Extend clickable area for all buttons

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#541]
Almost all links and buttons in the panel already have a padding to extend their clickable area. But there are a few exceptions:

1. »Install« button in the panel install view:
<img width="558" alt="panel-install" src="https://user-images.githubusercontent.com/15672385/42152573-d2958c0e-7de0-11e8-9845-fe381bd14434.png">

2. »Revert« and »Save« buttons in the new save bar:
<img width="309" alt="save-bar-1" src="https://user-images.githubusercontent.com/15672385/42152586-dcc34bc6-7de0-11e8-9499-4c2e3d13683a.png">
<img width="325" alt="save-bar-2" src="https://user-images.githubusercontent.com/15672385/42152591-dee9a1de-7de0-11e8-923f-eee7547546f9.png">

3. »Today« button in the calendar:
<img width="407" alt="calendar" src="https://user-images.githubusercontent.com/15672385/42152603-ec0f6236-7de0-11e8-8bef-59601a0eb0a6.png">

**Comment by bastianallgeier** [comment]
✅
