### ISSUE TITLE
[Panel] Textarea toolbar overflows field

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#542]
If a textarea field is very narrow, the toolbar can exceed its field boundaries:

![textarea-toolbar-2](https://user-images.githubusercontent.com/15672385/42155931-fae0e2cc-7de9-11e8-9ba6-a883d744737e.jpg)

This should fix the issue:

```
.kirby-toolbar {
  flex-wrap: wrap;
}
```

**Comment by jenstornell** [comment]
Or (untested)...

```css
.kirby-toolbar {
  overflow-x: auto;
}
```

Then if the toolbar overflows, it will be scollable, else it will not.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

Which of the approaches you choose should depend on which makes the best user experience.

**Comment by bastianallgeier** [comment]
✅
