### ISSUE TITLE
error with image field after selected image file is deleted

### ISSUE THREAD

**Issue by m-artin** [getkirby/kirby#543]
It may cause an error, when an editor deletes an image file, which was selected in the image field and then does not save the page.

Steps to reproduce: 

1. Upload an image file via the panel.
2. Drag and Drop or select the image file with the image field.
3. Delete the image file via the panel. (Which is still selected in the image field.)
4. Error: Call to a member function url() on null

blueprint: 
```
coverimage:
    label: Coverimage
    type:  image
```
template:
```
  <img src='<? if($page->coverimage()->isNotEmpty()) { echo $page->bgimage()->toFile()->url(); }  ?>'>
```

**Comment by texnixe** [comment]
Apart from the fact that in the code above you are using to different fields (which is probably just a mistake), you always need to check if an image object exists before calling a method like `url()` on it:

```
<?php if($image = $page->coverimage()->toFile()) { echo $image->url(); } ?>
```

This is something you have to take care of yourself.

**Comment by m-artin** [comment]
Sorry for the small mistake in the description. 
And thanks, your method to check object existents is the better way and works.
