### ISSUE TITLE
[Docs] Kirby and Panel dependencies

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#548]
I think it can be useful to have a list of all external libraries and frameworks used in Kirby + Panel in the docs. I was missing it for Kirby 2 already, so I made an inofficial list here: https://github.com/jenstornell/kirby-secrets/blob/master/docs/dependencies.md

That list does not contain much, as I needed to go through the code to find these dependencies.

**Here they are for Kirby 2:**

- SimpleImage (for thumbs)
- Spyc (for yaml operations)
- SQLight
- jQuery
- jQuery sortable

### Why it's important

Let's say I as a plugin developer build a panel plugin. If I know that `sortable.js` is used, I may base my sort function on that instead of including my own. A real life example is my [Kirby Crop Top](https://github.com/jenstornell/kirby-crop-top) that is based on SimpleImage. If I could not find it in the core, my plugin could not have been done.

Another important aspect of it is transparency. You already very transparent.

### What should be in such a list

So every library or framework that leaves a trace in Kirby should be in such a list, I think. It would include things like `Vue`, `Gulp` (if there is a gulpfile), `Composer` (because of the composer file), `SQLight`, `Spyc` (if still used) etc etc.

**Comment by distantnative** [comment]
I think we can find a place on the new website to list these.
For the moment check out `kirby/composer.json` and `kirby/panel/package.json`.
