### ISSUE TITLE
Prevent infinity loop when snippet is calling itself

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#548]
If snippet is calling itself, it will cause an infinity loop. Prevent that with a check if it calls itself, just throw an error.

**Comment by texnixe** [comment]
I don't agree, calling a snippet recursively can actually make a lot of sense, example: a [treemenu](https://github.com/bastianallgeier/kirbycms-extensions/blob/master/snippets/treemenu/treemenu.php). I think you should take care of that yourself.

**Comment by jenstornell** [comment]
I agree. I did not think about that. We don't want to lose that possibility.
