### ISSUE TITLE
Impossible to debug when Kirby does not find the 'site' folder

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#549]
If for some reason the `site` folder is missing at the place where Kirby looks for, one will end up with the white `kirby/views/fatal.php` error page, with no possibility to see the PHP errors, set the `debug` config or the `whoops` config.

I got this issue because my folder setup is non-standard *and* I messed up the configuration in my `index.php`/`site.php`. But Kirby was indeed loaded and displayed the `fatal.php` view.

The end result is you get a "fatal" page that suggests you define `c::set('debug', true);`, you set it in your config, but the config is never included, so you're stuck with no information.

Maybe `Kirby::launch` should check that `$this->roots()->site()` exists, and die with a terse error if it doesn’t, before setting up the config and the Whoops error handler?

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch. Kirby is now raising fatal errors when the site or content directories are missing.
