### ISSUE TITLE
[Panel] Re-implement "real" placeholders for empty sections

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#551]
Now that dropping isn't a danger anymore.

**Comment by bastianallgeier** [comment]
<img width="368" alt="screenshot_2018-07-09_14 19 20" src="https://user-images.githubusercontent.com/24532/42450238-c9c1b2d0-8383-11e8-8c16-399f13a72244.png">

Great suggestion by Till on Slack to make the icon and text configurable via blueprint.

**Comment by wottpal** [comment]
The placeholder could also be a button with the "Add"-functionality so these "click the button in the upper right corner" descriptions become unnecessary.

**Comment by bastianallgeier** [comment]
This is now partly done. The configurable text and icon will happen later. I created another ticket for it. https://github.com/k-next/kirby/issues/792
