### ISSUE TITLE
[Cms] Session: Unexpected file system error

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#553]
> code: 500
details: []
exception: "Kirby\Exception\Exception"
file: "\work\www\kirby3\alpha11\kirby\src\Session\FileSessionStore.php"
key: "error.session.filestore.unexpectedFilesystemError"
line: 303
message: "Unexpected file system error"
status: "error"

Appeared on Windows 10.

**Comment by bastianallgeier** [comment]
✅
