### ISSUE TITLE
Deactivate cache on incoming POST values

### ISSUE THREAD

**Issue by gerritvanaaken** [getkirby/kirby#559]
When cache is enabled we cannot use the great Comments plugin ( https://github.com/Addpixel/KirbyComments), simply because the comment post data don’t get through.

Could it be an option that Kirby deletes the cache for a specific page if there is an HTTP request with some POST data attached? Maybe it could be a configurable option to only react to certain POST parameters.

**Comment by lukasbestle** [comment]
I think this is even a bug. The cache shouldn't be used at all for POST requests. These should go through at any time.
Once you add the comment, the cache is flushed anyway, so this would be fine. And even if it's not about creating/updating pages: You could always manually flush the cache from POST handlers.

**Comment by lukasbestle** [comment]
This is now fixed on the develop branch for the next release.
