### ISSUE TITLE
Thumb Quality Setting

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/kirby#559]
I have this setting and Kirby gives me an image with a quality of 90.

*config/config.php:*
``` config.php
<?php
return [
  'thumbs' => [
    'quality'   => 20
  ]
];
```

*snippets/project-thumb.php:*
``` php
$item->images()->first()->crop(640 + 8 * 2, 500 + 5 * 2)
```

**`image-656x510-q90.jpg`**

----

When I set the quality in the crop method it works.
``` php
$item->images()->first()->crop(640 + 8 * 2, 500 + 5 * 2, [ 'quality' => 10 ])
```

**`image-656x510-q10.jpg`**

**Comment by bastianallgeier** [comment]
✅

**Comment by PatricB** [comment]
@bastianallgeier This issue is is up-to-date again. The quality setting ("thumbs.qualtity"), as far as I can see.
