### ISSUE TITLE
simpleimage get_meta_data calling exif_read_data might fail on php versions 5.6.2.x

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#562]
while digging though another error i found that the [simpleimage get_meta_data()](https://github.com/getkirby/kirby/blob/e3d5311cad778dc30a5c3aadc980925d9ddd3fe6/vendor/getkirby/toolkit/vendors/abeautifulsite/SimpleImage.php#L1091) might cause an error using php versions 5.6.2.x. current solution of prefixing with `@` will not help. neither will using a try-clause.

`exif_read_data(SOMEFILE.jpg): Illegal IFD size` which you can [read more about here](http://stackoverflow.com/questions/37352371/php-exif-read-data-illegal-ifd-size).

**Comment by lukasleitsch** [comment]
I tested it with the PHP Version 5.6.30. In this version the function runs without an error. Do you have the possibility to test it with den current version of PHP 5.6?

**Comment by bnomei** [comment]
it a known bug in 5.6.2.x only so I assume you are right. in my case i upgraded host to php 7 – that fixed it as well. but since kirbys requirement is [php 5.4+]( https://getkirby.com/docs/installation/download) I think you should still fix it anyway.

**Comment by lukasleitsch** [comment]
In a coming version of kirby the minimum version will be 5.6+. Therefore we don't fix this issue.

**Comment by bnomei** [comment]
5.6+ mean also 5.6.2.x with the error. so this wont help at all.
