### ISSUE TITLE
[Panel] Blueprint layout issues with 1/4 and 3/4 columns

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#565]
I downloaded the Beta 1 starterkit and changed the columns in »blueprints/pages/project.yml« to:

```
columns:
  - 3/4: content
  - 1/4: cover, gallery
```
On a narrow viewport, this results in the image overflowing the column. (Tested in Chrome, Firefox and Safari on Mac)

<img width="1187" alt="grid-bug-1" src="https://user-images.githubusercontent.com/15672385/42378715-9237915c-8128-11e8-9fe1-2d86605971c5.png">

----

```
columns:
  - 1/4: content
  - 3/4: cover, gallery
```

Results in:

<img width="1183" alt="grid-bug-2" src="https://user-images.githubusercontent.com/15672385/42378731-9d8ab458-8128-11e8-9c51-a2eec32d5ecd.png">

**Comment by bastianallgeier** [comment]
✅
