### ISSUE TITLE
Buttons: `pointer-events: none` prevents `title` from being shown

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#566]
The new status-icons and their colors are a real improvement over the Alpha! I tried to hover them on the start page of the plainkit-panel but I don't get a tooltip with their `title` attribute and this is because they are set to `pointer-events: none`. You could prevent this with a wrapper like described [here](https://stackoverflow.com/a/47412524/1381666).

I know this is a minor one but it could be frustrating for new panel-user on their first visit when they try to guess the meaning of these icons.

Additionally the title could be changed from "Public" to "Public (Disabled)" in this case.

**Comment by bastianallgeier** [comment]
✅
