### ISSUE TITLE
Potential critical bug in hasRole() function

### ISSUE THREAD

**Issue by judbd** [getkirby/kirby#569]
I try to do a login based page, and all works well, except a potential critical bug.

I created roles in my local config.php (admin, editor, client) as shown in doc and filter content with:

```
<?php if($site->user()->hasRole('admin')): ?>
<?php $clientprojects = $page->children() ?>
<?php else: ?>
<?php $clientprojects = $page->children()->filterBy('hasaccess', $username) ?>
<?php endif ?>
```

Then I have uploaded my code on a live test server, forgetiing to set roles in the test server config.php file.

Despite the fact I was logged with a (non existant role) "client" account, I had access to all projects (and access to panel, but this is normal). The weird thing is my user was listed as an editor in panel, so his role was not admin but it has access to all.

I think that somewhat the default role when user role doesnt exist is set to admin or the hasRole() function is not enough strict to filter users if roles are missing in config.php.

I also tested hasRole()->isNotEmpty() for securing the condition, but it throws a php error.

**Comment by texnixe** [comment]
https://forum.getkirby.com/t/hasrole-function-potential-critical-bug/7057/6

**Comment by lukasbestle** [comment]
I just looked into this issue, but there is no easy fix.

The reason why all users are suddenly admins is that Kirby [sets the role to the default role](https://github.com/getkirby/kirby/blob/master/core/user.php#L84) if the user's custom role doesn't exist.

If *no* custom roles are defined, the standard roles are editor and admin. And if no role is the default, Kirby will [make the admin role the default](https://github.com/getkirby/kirby/blob/master/core/roles.php#L71-L74).

There are two situations that can lead to the issue you are referring to:

- Custom roles are generally defined, but the user has an invalid role. His role will fall back to the default one (which is hopefully defined by the site devs). If no default is defined, Kirby has no other way than to make admin the default, all other roles can be named by the site devs however they like and Kirby won't know which one to choose.
- There are no custom roles at all (like in your case). In this case Kirby could as well choose the editor role as default role, which is probably safer.

As you can see, Kirby can only fix the second situation (I did that on the develop branch). The first situation is tricky, so I will leave this issue open. Let me know if you have an idea.

**Comment by distantnative** [comment]
@lukasbestle How about adding a third core role with no permissions at all which Kirby would fall back to if the user's role does not exist and no default role is defined (instead of now falling back to admin)?

**Comment by lukasbestle** [comment]
That makes a lot of sense, why didn't I think of that? :D
That third role could be defined dynamically by Kirby only if there is no default role (so in [this line](https://github.com/getkirby/kirby/blob/c9cc78881b4f73dc427164c2e53f383a36ce57c2/core/roles.php#L74)). I think the editor role should still be the default if no roles are defined whatsoever.

**Comment by lukasbestle** [comment]
This is now properly fixed on the develop branch.
