### ISSUE TITLE
[Panel] Text Editor Toolbar not working in Kitchensink > SEO > Meta Description (Starterkit) 

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#570]
When I select text it outputs this error:

<img width="415" alt="bildschirmfoto 2018-07-06 um 15 43 27" src="https://user-images.githubusercontent.com/3930150/42382145-a4c137dc-8133-11e8-827f-ac20fa72a601.png">

**Comment by thumbpiano** [comment]
Related error message when selecting text of meta description:
t.$refs.toolbar is undefined

**Comment by bastianallgeier** [comment]
✅
