### ISSUE TITLE
[Panel] Idea: Do you really want to close modal?

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#571]
What do you think about a modal which asks something like "Do you really want to close this tab? You did not safe." when there exists unsaved content? I know these modals are often not very user friendly but I think in this case it can help in some scenarios. Esp. when I think about one of my clients which has a 27'' iMac and Safari is always stretched from edge to edge so he easily misses the Revert-/Save-Bar on the bottom.

<img width="1424" alt="bildschirmfoto 2018-07-06 um 15 51 42" src="https://user-images.githubusercontent.com/3930150/42382411-805f0cf6-8134-11e8-8546-2c27d8e5336e.png">

**Comment by distantnative** [comment]
But the content is still stored already. When you return the changes as well as the save/revert bar should still be there. All changes are stored in localStorage immediately. When you close the tab, come back, they are still there. And then when you hit "save" the changes stored in localStorage are actually saved to the content file.

**Comment by wottpal** [comment]
> But the content is still stored already.

Yes it is and this is great btw. But I'm not concerned about content being lost but clients who forget to save at all. In my experience esp. Mac-users tend to think everything is saved after they wrote it down because this is the philosophy in most parts of their OS.

But this functionality could be easily implemented with a plugin, right? Or it's included in the core but disabled by default if the majority dislikes it.

**Comment by wottpal** [comment]
@bastianallgeier How would I make a plugin like this that is not a field which has to be added in every blueprint?
