### ISSUE TITLE
[Panel] Revert/Save bar not in every tab

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#572]
For example when I change some content in the _Footer_ Tab on the Kitchensink in the Starterkit the Save-Bar on the bottom shows up. Now when I switch the tab to _SEO_ or _Taxonomy_ the bar stays but when I switch to _Pages_ it disappears. Is this intentional?

**Comment by distantnative** [comment]
My first thought would be that the bar does not show up because the pages tab does not contain any fields section. And I'm thinking that it might be even correct that you only see the bar for the current screen - for what's in sight. But we need an indicator on tabs: blue for unsaved changes, red for errors that prevent publishing – what do you think, @bastianallgeier?

**Comment by distantnative** [comment]
But then again, when it should work as I wrote, it shouldn't be allowed to save from the SEO tab the changes in the Footer tab either.

**Comment by wottpal** [comment]
I really like your idea of indicator-colors for tabs. 

But I'm not sure about "per-tab-saving" because only in `site.yml` tabs are semantically so different that this would make sense for me. When I take a much more common example like an event-page where in one tab is something like event-prices and in the other the event-description it all feels much more like an unit which should be savable all together. 🤷‍♂️

**Comment by bastianallgeier** [comment]
As a first step I restricted the form buttons to the tab, which has actually changed. Don't have a good idea yet, how to implement the indicator colors, but that would be up next.

**Comment by bastianallgeier** [comment]
I've created a new ticket for the indicators: https://github.com/k-next/kirby/issues/650

**Comment by wottpal** [comment]
I thought about this again, because I tend to forget to save content on other tabs/pages. Or I think I forgot it and then spend quite a while cycling through all tabs/pages checking if there is something to save.. And imo indicators not solve this issue completely (but they are helpful nonetheless).

So why not just add a **Save All** button to the savebar 🤷‍♂️ This button could appear when there is more unsaved content on the current page or the whole site. I just reopened the issue because I think it makes sense to continue the discussion in this thread.

**Comment by distantnative** [comment]
Let's close this - the discussion is still referenced in the new issues. But it helps us to keep an overview if only actionable issues are still open.
