### ISSUE TITLE
[Panel] Structure field: empty fields displayed differently

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#573]
In the Starterkit when I add an empty item in _Restaurant-Menu_ there is an ellipsis for empty fields (…) and in the _Form-Demo_ (Kitchensink) the fields are just empty when there is no content.

_(... moved to its own issue https://github.com/k-next/kirby/issues/577)_

But like always - not very important.

**Comment by distantnative** [comment]
I split it up into 2 issues: https://github.com/k-next/kirby/issues/577

**Comment by bastianallgeier** [comment]
✅
