### ISSUE TITLE
Parameters on /home URL get stripped off

### ISSUE THREAD

**Issue by samnabi** [getkirby/kirby#573]
When accessing the home page by its full URL (e.g. /home), kirby truncates the page's slug and just returns the domain name. This is fine.

But if I go to `mysite.com/home?param=value` or `mysite.com/home/param:value`, Kirby redirects me to `mysite.com` and strips away the parameters.

This is unexpected behaviour. Is it intentional?

**Comment by lukasleitsch** [comment]
You can add parameters to the url without the slug for home.

e.g. `domain.com/?parm=value` or `domain.com/parm:value`

In the home-template you have access to this parameters. Is this an option for you?

**Comment by samnabi** [comment]
There's no specific problem this is causing for me, I just thought it was odd.

**Comment by lukasbestle** [comment]
This is now fixed on the develop branch.
