### ISSUE TITLE
Add docker support in the project

### ISSUE THREAD

**Issue by skywritergr** [getkirby/kirby#574]
Hi guys, thanks for your hard work on Kirby!!

One thing that it would be lovely is to have a dockerfile in the project so we can easily and fast run kirby locally or be able to use cloud service/providers for deploy and host.

Is there enough interest in the community around that?

**Comment by krisak** [comment]
I think in php world - docker is the last thing people use :D.

**Comment by lukasbestle** [comment]
The Dockerfile would need to be in the Kirby Starterkit. And because the Starterkit is just an example site/template, it can't have every single feature. Kirby also doesn't have any specific requirements, it just needs a basic LA(M)P stack. :)
