### ISSUE TITLE
[Panel] Don't display "save" bar when content has not changed

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#574]
When I check a checkbox the Save-Bar pops up (desired behavior) but when I uncheck it again without saving before it does not disappear (undesired behavior). Same for content-changes in all other UI-elements. I would like to see the Panel checking if the content has actually changed over and over again. 

I guess you have already thought about that one and I might remember a Slack-discussion about it but I can't find it.

**Comment by lukasbestle** [comment]
The current behavior is quite common actually. If you open a file in any text editor, type in something and press backspace to get back to the original state, the file will still be marked as "unsaved".

Comparing the state of checkboxes is rather easy, but comparing every part of a complex form every time you change something (basically after each letter you type) isn't going to perform well in my opinion.

**Comment by wottpal** [comment]
> The current behavior is quite common actually. If you open a file in any text editor, type in something and press backspace to get back to the original state, the file will still be marked as "unsaved".

I am using Atom and actually it has the behavior I described.

> Comparing the state of checkboxes is rather easy, but comparing every part of a complex form every time you change something (basically after each letter you type) isn't going to perform well in my opinion.

If that's going to end in an huge computational overhead - of course the current solution is better! I am just not sure if that's the case.

**Comment by luxlogica** [comment]
Now that the Panel is using Vue, this may be doable if every field component is written to be able to tell itself whether it's (really) been modified, or not. That way, the interface doesn't have to analyse the content of *every field* on every keystroke - they just analyse themselves, and their own content. The flag could be set as a property that bubbles up to the parent view, setting up a flag at page level. So it should make the whole process quite fast - or am I missing something?

**Comment by distantnative** [comment]
The point that makes your suggestion difficult is that the fields get their `value` from either the API or later the localStorage. The field cannot tell where that value is from, so that it also has no reference to what the real value would be to compare any new inputs against it. We tried to implement it at some point in the direction you lined out, but realized there that with the current setup fields are ending up comparing new inputs against already changed values.

**Comment by rasteiner** [comment]
I don't think this should be part of the first release (really more important things missing...).

But here's my opinion worth 2 cts:
you are already serializing the whole form on each input to json (to save it in localStorage).
I don't know if comparing that string to another would be that much more overhead. 
It also shouldn't be the field's responsibility to check if its value is equal to the original, it should either be the view or the _fields section_ that compares the serialized new value with the serialized value of when the form was populated the first time.

**Comment by wottpal** [comment]
> I don't think this should be part of the first release (really more important things missing...).

👍

**Comment by distantnative** [comment]
> you are already serializing the whole form on each input to json (to save it in localStorage).
I don't know if comparing that string to another would be that much more overhead.

We are serialising only values from field where input happened, not the whole form. I do not think that fields with a pure string value would be a big problem. But we also have much more complex fields where the value is an array or even objects. We will have to look into this for 3.0.x maybe.

**Comment by rasteiner** [comment]
There seems to be a bug then, because on my pc the whole form is getting serialized. I was just saying that even complex fields, once serialized, become just strings.

![whole form serialized](https://user-images.githubusercontent.com/6684137/42421074-d342fa62-82cf-11e8-93e0-490f562b5d45.gif)


PS: it's not my intention to sound rude ;)

**Comment by distantnative** [comment]
@rasteiner Sorry my bad then, I seem to have missed when we changed that.

**Comment by bastianallgeier** [comment]
✅

**Comment by bastianallgeier** [comment]
I had to revert it. There were a couple issues I didn't see before :(

**Comment by distantnative** [comment]
✅
