### ISSUE TITLE
File fields have different default language fallback behavior than pages (multilanguage)

### ISSUE THREAD

**Issue by lord-executor** [getkirby/kirby#575]
# Steps to reproduce the issue

1. Configure multiple languages and a default language
2. Add a checkbox field to the files section of a blueprint on a multilanguage site like this
```yaml
title: Default page
files:
  fields:
    flag:
      label: Flag
      type: checkbox
      text: Do stuf
```
3. Upload a file (in the default language)
4. Set the `flag` field to checked for the default language
5. Switch to another language and uncheck the `flag` field

The content file is stored as I would expect it, but reloading the panel page in the non-default language will show the checkbox as checked again. It also returns a "1" value when accessed through the PHP field API.

# Probable cause
In the `meta` function of the file https://github.com/getkirby/kirby/blob/master/branches/multilang/file.php, the following code determines the fallback values.
```php
// replace all missing fields with values from the default content
foreach($defaultMeta->data as $key => $field) {      
  if(empty($meta->data[$key]->value)) {
    $meta->data[$key] = $field;            
  }
}
```
This results in different behavior than what the page model does with its fields and in particular it fails here because `0` is `empty` in PHP.

**Comment by texnixe** [comment]
Should probably be something like this instead:

```
  foreach($defaultMeta->data as $key => $field) {
          if(isset($meta->data[$key]->value) && $meta->data[$key]->value == "") {
            $meta->data[$key] = $field;
          }
        }
```

**Comment by lord-executor** [comment]
@texnixe Actually, it should IMO look like this

```php
if(!isset($meta->data[$key]) || $meta->data[$key]->value == '') {
```

Analogous to the multilang `Page::content` method which does:

```php
foreach($defaultContent->data as $key => $field) {
  if(!isset($content->data[$key]) || $content->data[$key]->value == '') {
    $content->data[$key] = $field;
  }
}
```

**Comment by texnixe** [comment]
Yes, you are of course right!

**Comment by lukasbestle** [comment]
This was originally fixed for pages in [this commit](https://github.com/getkirby/kirby/commit/5b9f3b9242139de0694d8ba2d9240c9f1acb69cc). The same fix is now applied to the File class.
