### ISSUE TITLE
[Panel] Revert when clicking save

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#578]
Kirby 3 beta 1, Windows 10, Xampp, Google Chrome

As you can see, when I click save, it reverts the content instead which is a quite dangerous bug.

![save](https://user-images.githubusercontent.com/927011/42400080-8b093f1e-8170-11e8-9054-69b249ac6e3f.gif)

I get no errors in Google Console.

**Comment by bastianallgeier** [comment]
It's really weird that I can't reproduce this in Chrome on a Mac. Do you get anything in the PHP error log or the browser console? Is that happening in other browsers?

**Comment by luxlogica** [comment]
Cannot reproduce on Mac using Beta 1 with the latest Safari, Chrome or Firefox - sorry...

**Comment by distantnative** [comment]
Could the bug be less rooted in the browser (so not in the JS part) but more in regards to Windows and the filesystem part of that action?

**Comment by jenstornell** [comment]
I have vacation and not sure when I can test it again.

What I can say is that I played with the revert button before trying to save. Maybe a chain of events.

**Comment by jenstornell** [comment]
I get the same issue on my phone with Android and Chrome. Even with Firefox.

**Comment by jenstornell** [comment]
Now I tried it on Windows again. It worked with both Firefox and Chrome. Really strange. I'm still sure there is a bug but not sure when it happends. Also, I got the issue both on my localhost in Windows and on a phone with a live server installation.

Nothing in the error logs or the browser console.

**Comment by bastianallgeier** [comment]
I will close this for now as we all can't reproduce it so far. Please reopen it as soon as you run into it again.
