### ISSUE TITLE
[Panel] Save bar don't appear on mobile device

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#579]
When changing content in the panel on Android with Chrome browser the save bar does not appear. I did get it to appear a few seconds randomly touching the screen but could not get it back again.

**Comment by wottpal** [comment]
Maybe this can be fixed with the link from this comment as well: https://github.com/k-next/kirby/issues/682#issuecomment-409342638

**Comment by bastianallgeier** [comment]
Duplicate: https://github.com/k-next/kirby/issues/682
