### ISSUE TITLE
prevent timing attacks

### ISSUE THREAD

**Issue by DanielRuf** [getkirby/kirby#580]
Use `hash_equals` here in the match method to compare hashes.

https://github.com/getkirby/kirby/blob/master/vendor/getkirby/toolkit/lib/password.php

**Comment by Zegnat** [comment]
`hash_equals` is only available from PHP 5.6.0, and the Kirby Toolkit still targets 5.4.0. Instead `Password::match()` should implement its own constant time comparison, maybe look at what password_compat has done for [their `password_verify()`](https://github.com/ircmaxell/password_compat/blob/dfdbc467fba0d1db4c2f51fda58e1717046f3284/lib/password.php#L225-L249).

(This should probably be an issue on [getkirby/toolkit](https://github.com/getkirby/toolkit).)

**Comment by DanielRuf** [comment]
Right but 5.4 reached EOL a while ago. At least `===` is not enough to prevent timing attacks. 

Imho future versions should drop support for old and insecure PHP versions.

I would have welcome if password_* and password_compat were used eg with Composer but it seems thirdparty dependencies are not welcome and many things are manually rewritten and implemented. At least password_compat can be easily implemented, it's just one class afaik.

What is the difference between this repo and the toolkit repo? Is toolkit part of this here (could be done as dependency or submodule)?

**Comment by krisak** [comment]
I believe Kirby devs have as little as possible philosophy. Toolkit is definitely dependency, its set of core classes that kirby depends on.

Actually i suspect some core dev explain everything here but i came to say:

 Kirby should drop 5.4.0. - Most of the people are coding plugins and stuff for 5.6.+ anyway.

**Comment by DanielRuf** [comment]
> I believe Kirby devs have as little as possible philosophy. Toolkit is definitely dependency, its set of core classes that kirby depends on.
> 
> Actually i suspect some core dev explain everything here but i came to say:
> 
> Kirby should drop 5.4.0. - Most of the people are coding plugins and stuff for 5.6.+ anyway.

I totally agree with you as this would be beneficial in many ways (easier development, less bugs, backported code and methods with workarounds, better methods, better performance and security, easier testing and so on. We can remove 5.4 (and possibly 5.5) from the Travis file and also add 7.1 (already stable and usable at many hosting providers).

Anyway, for me it seems there is just one maintainer / owner of these projects and this is Bastian so he has to decide this I guess but I think many contributors have the same opinion like you.

**Comment by samnabi** [comment]
Kirby should absolutely not drop support for PHP  5.4. It's still being used by 23% of servers.

https://w3techs.com/technologies/details/pl-php/5/all

One of the huge advantages of Kirby and other file-based CMSs  is that you can drop them into an FTP client and you're good to go. This requires compatibility with a wide range of servers, which you might not have root access to.

**Comment by DanielRuf** [comment]
Anyway, the overall security could be better, especially against specific attacks like timing attacks.

On php.net and in password_compat should be good solutions for this, for example for `hash_equals` =)

**Comment by krisak** [comment]
@samnabi Well you are not good to go if your site uses any of the popular plugins. But OK. 

I think you have it backwards though. Even the budget shared hostings ive used lately - all of them have php7 (its faster means cheaper). The only reason those sites are not running 7 is because hosting providers don't want to mess up sites of their clients if they switched globaly. 

The reason there are sites running the old php is because people just don't know or bother. But its usually just one switch in admin somewhere. 

Even Wordpress has php7 as their recomended version and tells you that you should update if you are lower because of the security issues.

Then again Bastian has this figured out im sure.

**Comment by krisak** [comment]
Oh and like @DanielRuf said - i had no idea but only 5.6 gets security updates (but its not supported). Lower versions are just dead. That is a big issue.

**Comment by texnixe** [comment]
The problem of not being able to switch to a newer version sometimes is not a matter of not caring or knowing. Sometimes, a server does not only run a website, but also other stuff. And if that other stuff is not compatible with newer versions of PHP but a company is still using it (thus sacrificing security), then there's nothing much you can do about it.

Having said that, I'm all in favor of ditching support for dead PHP versions, including 5.6. Security is more important here, and creating a modern, performant application.

**Comment by krisak** [comment]
Made too long comment. Distilled:
@texnixe maybe do poll with community. Let users decide.

> @texnixe eeeeehm i dont know. It seems like such small percantage, especially if we talk about kirby (people making custom websites). You will actually have hard time finding host for 5.4. besides most of the hosts let you use multiple versions and if its your server - you can run multiple versions without problems. 
> 
> Looking at it from the other side - not only its blocking security but... for example call_user_func_array() is used in core from time to time. As far as i know just switching this to argument unpacking makes this faster. Im sure there are lot of places core devs know about wher...... the coment is too long. Shit

**Comment by texnixe** [comment]
As I said, you don't have to convince me, @krisak! I was only talking from my own experience, where I had to touch a 10 year old PHP application to make it compatible with 7.x to be able to switch the shared hosting package to the new PHP version.

**Comment by lukasbestle** [comment]
We *are* going to drop support for PHP 5 in the next major release (meaning support for PHP7+ only), but we won't be able to drop support until then. :)

**Comment by DanielRuf** [comment]
@lukasbestle see http://php.net/manual/de/function.hash-equals.php#115635 and https://github.com/symfony/polyfill/tree/master/src/Php56

**Comment by DanielRuf** [comment]
Bump.

**Comment by lukasbestle** [comment]
We actually dropped support for PHP versions below 5.6 in our latest release 2.5.12 and fixed this issue properly, see the current state of https://github.com/getkirby/kirby/blob/master/vendor/getkirby/toolkit/lib/password.php.
