### ISSUE TITLE
Infinite redirect with query string and language.detect enabled on root URL

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#581]
I’ve noticed that when I append some query string parameters to my home page URL, I get an infinite 302 redirection. You can see it live at: https://www.metropop.ch/?hello=kirby

First I thought it was some issue with rules in Apache configuration but as soon as I disabled the `language.detect` feature it worked just fine. This bug doesn’t seem to affect any other pages.

**Comment by lukasbestle** [comment]
This is now fixed on the develop branch.
