### ISSUE TITLE
sortBy could take function as parameter

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#582]
instead of just name of field. just like `filterBy` does. that would allow one to sort by page model methods or data of defined structure.

https://forum.getkirby.com/t/pluck-structured-data/4482/4?u=bnomei

**Comment by lukasbestle** [comment]
What would that callback need to return then? The value to sort by for each element?

Please note that it should already be possible to sort by page model methods or page methods. The `sortBy()` method just calls the method on the page objects, it isn't limited to content fields. So you can actually define the method to sort by in the model or as a page method. :)

**Comment by bnomei** [comment]
@texnixe recently did an example for what you suggested. 

https://forum.getkirby.com/t/custom-sorting-of-pages/7929/6?u=bnomei
