### ISSUE TITLE
changing the content folder

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#583]
when changing the content folder to something else one should also change the htaccess. please update the docs.

https://getkirby.com/docs/developer-guide/configuration/folders#changing-the-content-folder

https://github.com/getkirby/plainkit/blob/master/.htaccess#L25

**Comment by lukasbestle** [comment]
Thanks, but please open an issue in the [getkirby.com repo](https://github.com/getkirby/getkirby.com) instead.
