### ISSUE TITLE
[Panel] Clean up content file: useful quirk from K2 lost

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/kirby#583]
Problem: Can't clean up a content file by saving in the panel to regenerate it.

Reproduce: Open a page in the panel, and the very same page in a text/code editor (I used Atom). The text file should one thats a mess, with old data in it from during development. Maybe you changed your mind about some field names and old data has got left behind.  Select all the text in the code editor and delete it. Then save that page in the panel. With K2, this regenerates the text file, with the fields in the right order, and without the redundant stuff. In K3.,you loose everything.

Solution: I guess K2 keeps a copy of the page data in ram during editing, whereas K3 seems to read directly from text file. Either switch K3 to use the same method as K2 or add a cleanup button to the panel, suggested by Jens Tornell.

**Comment by REHvision** [comment]
:+1: for a content-file cleanup button!
But probably it should only be available with `debug = true` :wink:
