### ISSUE TITLE
Error in coverimage.php on vanilla Kirby starterkit install

### ISSUE THREAD

**Issue by mykeln** [getkirby/kirby#585]
When adding a new blog post to the vanilla Kirby starterkit install, when I attempt to preview the post, it throws the following error in coverimage.php

Call to a member function url() on null

Related to this section:
```
<?php if($item->coverimage()->isNotEmpty()): ?>
  <figure>
    <img src="<?= $item->coverimage()->toFile()->url() ?>" alt="" />
  </figure>
<?php endif ?>
```

**Comment by texnixe** [comment]
This is not the right repo and looks like you are not using the latest version of the Starterkit, because the code in the repo looks like this:

```

<?php if($image = $item->coverimage()->toFile()): ?>
  <figure>
    <img src="<?= $image->url() ?>" alt="" />
  </figure>
<?php endif ?>
```
