### ISSUE TITLE
[Cms] link(): Operation not permitted

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#585]
This error only happens when I use Kirby with Vagrant.

You should be able to reproduce it like this:

1. Download the Beta 1 Starterkit and put the Vagrantfile in the root directory. You can use this [simple, publicly available Vagrantfile](https://travismaynard.com/writing/using-kirby-with-vagrant) or [my Vagrantfile](https://gist.github.com/SebastianEberlein/eb5c27b61746c2463ad9fb5a8944f0d5) I used for many Kirby 2 projects.
2. Start the VM with `vagrant up`.
3. Navigate to the »Projects« page or upload an image in the panel. You should see the following errors:

<img width="1186" alt="1" src="https://user-images.githubusercontent.com/15672385/42438877-9c08daa2-8361-11e8-8133-1324a7cba15f.png">

When I try to open the link to the requested image directly: 
<img width="1185" alt="2" src="https://user-images.githubusercontent.com/15672385/42438881-a135f852-8361-11e8-8803-dcd8445d5068.png">

Uploads in the panel throw this error. The image is uploaded to the »content« folder, but not copied to the »media« folder:
<img width="1187" alt="3" src="https://user-images.githubusercontent.com/15672385/42439032-05e81c8a-8362-11e8-9a2f-7e6cfcbf7994.png">

I already tried adjusting the permissions in Vagrant, but nothing worked so far…

**Comment by bastianallgeier** [comment]
✅ I fixed this by copying the files instead of linking.
