### ISSUE TITLE
$page->url() does not output full url in v2.5.0

### ISSUE THREAD

**Issue by olach** [getkirby/kirby#588]
As the title suggests. In Kirby 2.5.0, `$page->url()` does not output the full url anymore. I tried this on the home page in the starterkit:

In version 2.4.1 `$page->url()` outputs the full url: `http://kirby.dev` in my case.

In version 2.5.0 `$page->url()` just outputs this: `/`

Is this a new behavior? The docs [still says](https://getkirby.com/docs/cheatsheet/page/url) that the full url should be the output.

I tried to update a site to 2.5.0 but this changed behavior crashed the site so I had to revert to 2.4.1.

**Comment by texnixe** [comment]
Looks like this affects more people: https://forum.getkirby.com/t/getting-relative-urls-in-kirby-2-5/7772/4

**Comment by lukaskleinschmidt** [comment]
See here
https://forum.getkirby.com/t/getting-relative-urls-in-kirby-2-5/7772/35

**Comment by lukasbestle** [comment]
Oh, that's a nasty bug! We will definitely fix this in the next release (which is expected to be released in just a few weeks).

**Comment by Sija** [comment]
@lukasbestle Few weeks for fixing the bug which breaks basic (documented and expected) functionality? Are you sure that would be the proper timeline of events?

**Comment by lukasbestle** [comment]
Few weeks means few weeks, not few months, you can trust me. 😃

It won't be a few days however as we want to fix other bugs in 2.5.0 in the same bugfix release. We also need to ensure that our fix is a proper one. Having a short delay is better for everyone than loads of bugfix releases in a short timeframe.
If you need the features of 2.5.0 right away, please revert the changes from [this commit](https://github.com/getkirby/toolkit/commit/3834f9809e545f0d430059aa427de89d15001515) until then.

**Comment by olach** [comment]
With all respect, but I think this bug is a major one. This bug will crash a lot of sites when authors are doing the update to 2.5.0. I have a large site that was affected by this bug so I had to revert the installation to 2.4.1. 

I had a plugin (https://github.com/jenstornell/kirby-seo) that was affected by this bug that caused the site to crash. That was how I discovered the bug. But even without the plugin, the site didn't work because I had used the url function on smaller parts of the site. 

If you wait too long to fix this bug, I think you will get a lot of support tickets from users who wonder why their site doesn't work anymore after the update. Even users with fresh installations will be confused why this function does not work as excepted. 

When I first discovered this severe bug I thought that you might as well pull the 2.5.0 update until a fix is ready to protect your users. Then I understood that not all users were affected. But I still think this is a major bug that needs some priority at least.

**Comment by lukasbestle** [comment]
We have decided to revert the commit that caused this issue for now and released [Kirby 2.5.1](https://getkirby.com/changelog/kirby-2-5-1).

The release means that the bugfix that was originally meant to fix the CLI detection has been reverted, but we will look into this for 2.5.2. Fixing the URL issue was more important as many of you reported this issue.
