### ISSUE TITLE
[Cms] Bring back the dump() helper

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#588]

**Comment by bastianallgeier** [comment]
✅

**Comment by sanderdlm** [comment]
Would it be an option to include the Symfony VarDumper component as a dev dependency and use that instead of the current dump() helper?

**Comment by texnixe** [comment]
@dreadnip You can replace the `dump()` component with your own: https://getkirby.com/docs/reference/plugins/components/dump
