### ISSUE TITLE
Error when trying to add new user

### ISSUE THREAD

**Issue by dpogni** [getkirby/kirby#589]
I'm running into this error when trying to create a new user. I'm able to replicate on my server too.

```
Error: Call to a member function password() on null
Kirby Version: 2.5.1
Local PHP version via MAMP: 7.0.15
Server PHP version: 7.0
```

![screenshot 2017-06-24 20 41 26](https://user-images.githubusercontent.com/672587/27513512-9a78bf32-591d-11e7-9625-19f4d3cf764d.jpg)

**Comment by texnixe** [comment]
See here: https://github.com/getkirby/panel/issues/1064
