### ISSUE TITLE
$files->last() is not corresponding with the sorting of my files in the kirby backend

### ISSUE THREAD

**Issue by Jones-S** [getkirby/kirby#590]
If I use this 
`$last = $page->files()->last()->url();`

I am getting the url of a random image in my page, and it is not the last.
![image](https://user-images.githubusercontent.com/7059580/27640299-2c0f7f82-5c19-11e7-920a-32bf5b7a8395.png)

You see here that the last image is called 2000x800, but when I run the code I get the url of:

```
{
"last": "https://kirby.***/content/2-projects/projectname/800x800-copy.jpg"
}
```

So my question is: does the last not match the last image in my backend? Is it maybe sorted by upload timestamp or by anything else?
If so: how could I get the last image then?

Probably I am just missing a key thing here...

**Comment by samnabi** [comment]
`$page->files()` doesn't know anything about your blueprint.

So you need to use the `->sort()` method to sort that collection explicitly in your controller of template code.

**Comment by texnixe** [comment]
If you don't use `sortBy()` in your template or controller, the default sorting is based on the order of files in the filesystem, ignoring any manual sorting you might have done in the Panel. If you manually sort files in the Panel, a meta data file with the sorting number is created.

**Comment by lukasbestle** [comment]
In short, you can use this snippet of code to get the image that is the last in the Panel:

```php
$last = $page->images()->sortBy('sort', 'asc')->last()->url();
```

**Comment by texnixe** [comment]
Or rather:

```
$last = $page->images()->sortBy('sort', 'asc')->last();
if($last) {
  echo $last->url();
}
```
(otherwise you would get an error if there is not image at all)

**Comment by Jones-S** [comment]
perfect. thanks for the support
