### ISSUE TITLE
[Panel] Emoji icons for pages misaligned in latest Chrome on macOS

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#594]
Emoji icons aren’t perfectly centered horizontally (Chrome 67, macOS Sierra):
<img width="342" alt="screenshot 2018-07-09 14 42 00" src="https://user-images.githubusercontent.com/1512805/42451141-a1e43d0c-8386-11e8-8b47-22048c3a9de2.png">

Expected (Safari 11.1, macOS Sierra):
<img width="341" alt="screenshot 2018-07-09 14 45 58" src="https://user-images.githubusercontent.com/1512805/42451200-d266aa0a-8386-11e8-808a-40449a544ac8.png">

**Comment by bastianallgeier** [comment]
I'm closing this as I never ran into it and nobody else reported it.

**Comment by SirNovi** [comment]
Icons are super off center for me and apparently also smaller than they are supposed to be.

<img width="230" alt="screenshot 2019-01-17 at 16 12 41" src="https://user-images.githubusercontent.com/1991072/51328006-bcf0c380-1a72-11e9-85bc-105c4d82b667.png">

Chrome  71.0.3578.98 
macOS 10.14 (18A391)

**Comment by bastianallgeier** [comment]
I realized with my new MacBook Air that this is retina-exclusive. Doesn't happen on regular screens. Weird stuff!

**Comment by medienbaecker** [comment]
Seems like there's a bug with Emoji smaller than 26px in font size.
If you're still searching for a solution, here's what I found: https://codepen.io/faessler/pen/aRNOEY

Setting the `font-size` of the icons to 26px and then scaling them down seems to work.

**Comment by bastianallgeier** [comment]
✅ It's finally fixed on the 3.0.2 branch. @medienbaecker thanks for the link!
