### ISSUE TITLE
Undefined variable: Adapters

### ISSUE THREAD

**Issue by AdamMcquiff** [getkirby/kirby#594]
I'm attempting to update a page with the CMS. The CMS has _literally just_ been setup. I have made no changes to files or the content.

When I click 'save', I am prompted with a toast notification that states "Undefined variable: Adapters".

I managed to trace the issue to these lines in update method in the page.php file:

    $normalizer = data::$adapters['kd']['_normalizeKeys'];
    $current    = $normalizer($this->content()->toArray());
    $input      = $normalizer($input);

Due to the issue, I cannot update any content.

Kirby was being ran via XAMPP on the latest version of macOS.

**Comment by texnixe** [comment]
Hm, yes, I can reproduce this with PHP versions below 7.0

**Comment by bastianallgeier** [comment]
We just released 2.5.4, which includes a fix for this: https://getkirby.com/changelog/kirby-2-5-4 We are really sorry for the issue!
