### ISSUE TITLE
Call to undefined method KirbyPanelModelsSiteOptions::sortFiles()

### ISSUE THREAD

**Issue by AdamMcquiff** [getkirby/kirby#596]
When attempting to access a website's settings via the backend panel, I receive the error:

`Call to undefined method KirbyPanelModelsSiteOptions::sortFiles()`

![image](https://user-images.githubusercontent.com/9249853/28896993-b0fbc056-77d6-11e7-94f0-4bea91a6df76.png)

Spec: Windows 10, MAMP, PHP 5.6.0

**Comment by texnixe** [comment]
Please update to Kirby 2.5.4, the issue has been fixed.
