### ISSUE TITLE
Invalid argument supplied for foreach() in panel/pages/pagename/edit

### ISSUE THREAD

**Issue by ptbobolakis** [getkirby/kirby#597]
```
kirby: 2.5.4
toolkit: 2.5.4
panel: 2.5.4
```

After I create a page, if I go to `/panel/pages/pagename/edit`, I get the output `Invalid argument supplied for foreach()`. Also I get the same output in `Site Options`.

![screen shot 2017-08-03 at 13 44 54](https://user-images.githubusercontent.com/12424632/28920405-f95e9cb2-7851-11e7-9405-ffe3d081bbb3.png)

When I switch back to v2.5.2 the problem is not occurring anymore.

**Comment by texnixe** [comment]
This is the wrong repo and the issue already exists in the Panel repo.
