### ISSUE TITLE
[Panel] User field in a structure field not working

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#598]
> User field in a structure field:
>```participants:
>    type: fields
>    fields:
>      participant:
>        label: Participants
>        type: structure
>        fields:
>          userid:
>            label: User email
>            type: user

>The username doesn't display as a label of the structure field record and when I click on the structure field record to open it, a modal pop-up appear with the message "this.$refs.input is undefined"

**Comment by bastianallgeier** [comment]
✅

**Comment by distantnative** [comment]
@bastianallgeier 
<img width="785" alt="screenshot 2018-07-09 at 19 17 17" src="https://user-images.githubusercontent.com/3788865/42465598-bc6e4a3e-83ac-11e8-804c-b205fda71ec5.png">

When entering a page with no content for the structure field yet.

**Comment by bastianallgeier** [comment]
Shit, I was too quick :) Now it should work.
