### ISSUE TITLE
Allow absolute path with Asset class

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#599]
**Recap**

The Asset class does not support an absolute image path. The workaround I made for my site is a bit hacky:

```php
// $image_path is generated with glob
$image_path = ‘D:\domain.com\assets\images\image.jpg’;
$image_object = new Asset(str_replace(kirby()->roots()->index(), '', $image_path));
echo thumb($image_object, array('width' => 100));
```

**Suggested solution**

Allow absolute path magically or add a second param with a boolean `true` for url and `false` for path.

**Code**

https://github.com/getkirby/kirby/blob/master/core/asset.php

**Forum**

https://forum.getkirby.com/t/thumb-of-image-outside-of-content-folder-not-really-working/5367/6

**Comment by lukasbestle** [comment]
You can pass a `Media` object, Kirby will then extract the path and URL from it. But of course you need to manually construct the URL then. :)

**Comment by lukasbestle** [comment]
As @jenstornell has asked me about this again in the forum, here's an example for a plugin asset:

```php
$root  = __DIR__ . DS . 'assets' . DS . 'something.jpg';
$url   = url('assets/plugins/my-plugin/something.jpg');
$media = new Media($root, $url);
$asset = new Asset($media);
```

This example can of course be adapted for any kind of file, but as I wrote in my last post, it's not possible for Kirby to "magically" determine the URL of an absolute path. That's why you need to do it manually.

**Comment by jenstornell** [comment]
Your code was a life-saver today. I did not figure out this myself before I read your code again.

Maybe it would be neat if there was a shorter version for us dummies.

**Something like this in the Kirby core:**

`thumbnail` is not a good function name, I know.

```php
function thumbnail($filepath, $url) {
    $media = new Media($filepath, $url);
    $asset = new Asset($media);
    return $asset;
}
```

**For us site developers it would be this simple, a nobrainer:**

```php
echo thumbnail($filepath, $url)->resize(500)->url();
```

**Comment by lukasbestle** [comment]
To be honest I don't think that this is a common use-case. Could you please explain what you are trying to do?

**Comment by jenstornell** [comment]
Here is my quick and dirty snippet. You may think that I'm using the built in assets root, but I pointed it somewhere else and is using a route for it instead.

The code below works, but I thought it could be simpler with a function like that.

```php
<?php
function media($filepath, $url) {
  $media = new Media($filepath, $url);
  $asset = new Asset($media);
  return $asset;
}
?>
<page-hero>
    <page-sides>
        <hero-center>
            <hero-image>
                <?php
                $filepath = kirby()->roots()->index() . '/theme/assets/images/hero-image.jpg';
                $url = url('assets/images/hero-image.jpg');
                ?>
                <img src="<?= media($filepath, $url)->resize(500)->url(); ?>">
            </hero-image>
            <hero-text>
                <hero-title>
                    <?= $hero_title; ?>
                </hero-title>
                <hero-slogan>
                    <?= $hero_slogan; ?>
                </hero-slogan>
            </hero-text>
        </hero-center>
    </page-sides>
</page-hero>
```

**Comment by lukasbestle** [comment]
Why did you point it somewhere else?

**Comment by jenstornell** [comment]
I have a clear separation between `site` and `theme`. Both of them has their own assets path. So I have assets in two different locations. It means I can move these parts independently from each other.

To make it easier in another way would be to be able to register assets paths, which is not possible today. Now it's only possible to have one, except for plugins that have one each.

**Comment by lukasbestle** [comment]
You can create an `Asset` object like this:

```php
$asset = new Asset('theme/assets/images/hero-image.jpg');
```

Please keep in mind that the URL to the file will also be prefixed with `theme`, but that should work as that's also the actual path.

If you need the `thumbnail` helper function, you can define it in a plugin file in `site/plugins`, which automatically makes it available to all templates and snippets.
