### ISSUE TITLE
site::method and page::method with same name

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#600]
i have [created a plugin](https://github.com/bnomei/kirby-styledmap/blob/master/kirby-styledmap.php#L119) registering both `site::method` and `page::method` with same name.

when in template calling `$page->mymethod()` the site method is called instead. that's bad since i loose context of `$page` object. 

is it not possible to register a site and page method with same name?

**Comment by lukasbestle** [comment]
Could you please try registering the methods the other way around (first page, then site)?

**Comment by bnomei** [comment]
registering `page::method` before `site::method` like you suggested did the trick. removing the `site::method` altogether would work but i think i will keep the more readable implementation.

is there any way to change kirby to avoid this pitfall for other plugin devs? if not you may close this issue.

**Comment by lukasbestle** [comment]
There isn't an easy fix for Kirby, it's just not intended to have the same method for both `page` and `site` as the `site` object is a `page` itself. So I'd definitely remove the `site` method and add a comment to the `page` method about this. That's more robust for the future.
