### ISSUE TITLE
Empty images causes panel to break

### ISSUE THREAD

**Issue by 3tlam** [getkirby/kirby#601]
Heya

Not sure if this is something that Kirby needs to take care of, but I just wanted to mention it :)
We encountered a problem where an image which has been added to the panel "lost" its content (eg filesize = 0 bytes). This will then lead to the following error which can't be addressed inside of the panel, but has to be solved by manually deleting or replacing the image. 
This can be reproduced by dropping a new image into the panel.

```
get_resource_type() expects parameter 1 to be resource, null given
```
<img width="1493" alt="kirby" src="https://user-images.githubusercontent.com/6067365/29883332-43938a72-8db0-11e7-89ba-24f64f3a80f2.png">

**Comment by lukasbestle** [comment]
Hm, I can't reproduce this. What I did was:

- Create a new empty file called `test.jpg`
- Drop that into a Panel page

The empty image is listed in the sidebar and I can click on it (which displays a details page with an empty preview).

Could you please tell me a bit more about your setup? Please also try to reproduce this with the Starterkit, this makes it easier for me to reproduce it as well. Thanks!

**Comment by 3tlam** [comment]
with the latest starterkit I can't reproduce it - maybe it was just a weird thing.
I guess you can close it then :)
