### ISSUE TITLE
Structure Content not visible in Panel

### ISSUE THREAD

**Issue by ueberf** [getkirby/kirby#602]
Upgrading to **Kirby 2.5.5** broke my existing structure view. The data was still written in the content-file, but the view in the panel only showed the delete-button. 
New content could be created and was successfully written in the content-file, but also wasn't visible in the panel.

Downgrading to **Kirby 2.4.1** fixed the problem and the content was visible again.

<img width="1281" alt="screen shot 2017-09-01 at 8 49 53 pm" src="https://user-images.githubusercontent.com/19748898/29983675-4b43c2c0-8f57-11e7-906a-21550e7b89e1.png">

_Structure entries are there, but the content not visible_ 

<img width="1280" alt="screen shot 2017-09-01 at 8 50 12 pm" src="https://user-images.githubusercontent.com/19748898/29983676-4b449538-8f57-11e7-9a69-461c0d773de2.png">

_Adding new content works as usual_

**Comment by lukasbestle** [comment]
Could you please post your blueprint?
It would also help a lot to know which update introduced this issue exactly. So if you can, please test with Kirby 2.5.0 to 2.5.4 individually and tell us in which version this issue appeared first.

**Comment by ueberf** [comment]
The issue first appeared on Kirby 2.5.3
Here is the code to my blueprint:
`title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  contentInput:
    label: Content Input
    type: headline
  displayedTitle:
    label: Displayed Title
    type:  text
    width: 1/3
  year:
    label: Year
    type: text
    width: 1/3
  projectType:
    label: Project Type
    type: select
    default: private
    width: 1/3
    options: 
      private : Private
      commercial : Commercial
  abstract:
    label: Abstract
    type:  textarea
  text:
    label: Text
    type:  textarea
  firstImage:
    label: Cover Image
    type:  image
    value: "{{url}}"
    width: 2/5
  secondImage:
    label: Second Image
    type:  image
    value: "{{url}}"
    width: 2/5
  menuColor:
    label: Menu Color
    type: select
    default: black
    width: 1/5
    options: 
      white : White
      black : Black
  topColor:
    label: Top Color
    type:  color
    default: 7D88D9
    width: 1/4
  bottomColor:
    label: Bottom Color
    type:  color
    default: 7DA7D9
    width: 1/4
  shapeTopColor:
    label: Shape Top Color
    type:  color
    default: FFFFFF
    width: 1/4
  shapeBottomColor:
    label: Shape Bottom Color
    type:  color
    default: 000000
    width: 1/4
  pageContent:
    label: Page Content
    type: structure
    style: table
    entry: 
      {{entry_content}}
      {{entry_type}}
    fields:
      entry_content:
        label: Content
        type: textarea
      entry_type:
        label: Type
        type: select
        options:
          entry_type_text: Paragraph
          entry_type_image: Image
          entry_type_headline: Headline
          entry_type_video: Video
  credits:
    label: Credits
    type: textarea
  relatedProject:
    label: Related Project
    type: select
    options: query
    query:
      fetch: siblings
      value: "{{uri}}"
      text: "{{title}}"
  seoInput:
    label: SEO Settings
    type: headline
  seoTitle:
    label: Meta Titel
    type: text
    width: 1/5
    validate:
      max: 65
      maxLength: 65
  seoDescription:
    label: Meta Description
    type: text
    width: 4/5
    validate:
      max: 155
      maxLength: 155
  ogTitle:
    label: Rich Link Title
    type: text
    width: 1/5
    validate:
      max: 35
      maxLength: 35
  ogDescription:
    label: Rich Link Description
    type: text
    width: 4/5
    validate:
      max: 65
      maxLength: 65
  tags:
    label: Meta Tags
    type:  tags`

**Comment by texnixe** [comment]
The problem is due to your use of `style: table` and using the entry option, which doesn't make sense together. Nevertheless, this should not happen.

**Comment by texnixe** [comment]
This issue should be moved to the Panel repo.

**Comment by ueberf** [comment]
You're right – removing `style: table` fixed it.
Thanks for your help!

**Comment by lukasbestle** [comment]
This is not a bug as the `entry` option is used to control the displayed columns in the `table` layout since Kirby 2.5.3. See ["Configuring the displayed columns" in the docs](https://getkirby.com/docs/cheatsheet/panel-fields/structure).

**Comment by texnixe** [comment]
Maybe issue a warning if the wrong syntax is used for entries in table style layout?

**Comment by raschid** [comment]
Sorry folks,
after downgrading to kirby 2.5.5 from 2.5.7 because of Problems with strato (german shared hosting provider) i face the same problem as @ueberf :
![kirby01](https://user-images.githubusercontent.com/5807524/33883607-add71146-df3c-11e7-9a80-9c1101c67243.jpg)
my blueprint looks like this:
`title: Home

pages: false

fields:
  page-content:
    label: Seiten-Inhalt
    type: headline
    numbered: true
  title:
    label: Title
    type:  text
    required: true
    default: Home
  intro:
    label: Text
    type:  textarea
    required: true

  teasers:
    label: Teasers
    type: headline
    numbered: true
  teaser-cols:
    label: Teaser-Spalten
    type: structure
    limit: 3
    fields:
      teaser-text:
        label: teaser-text
        type: textarea
        validate:
          minLength: 10
          maxLength: 160
      teaser-img:
        label: Teaser-Bild
        type: image
        required: true
`

**Comment by texnixe** [comment]
@raschid You are not allowed to use dashes in field names.

**Comment by raschid** [comment]
wow, your fast :-)
I changed my fieldnames (see below) but the problem stays ...
[home2.txt](https://github.com/getkirby/kirby/files/1551509/home2.txt)

**Comment by texnixe** [comment]
If you remove the camelCasing as well, it should work as expected.

**Comment by raschid** [comment]
CamelCasing: you nailed it! Thank you for that one!

But the hint with 2.5.7 did not work for me. In my kirby-download, the lines in question were already changed. 

- Uploaded  kirby to a freshly created subdomain. 
- altered config.php with license and c::set('panel.install', true);
- tried with original .htaccess AND "RewriteBase /" switched on.

Still cannot access the panel :-(

**Comment by texnixe** [comment]
In 2.5.5, the unIdn function look like thsi:

```
public static function unIdn($url) {

    if(!function_exists('idn_to_ascii')) return $url;

    // disassemble the URL, convert the domain name and reassemble
    $host = idn_to_ascii(static::host($url));
    $url  = static::build(['host' => $host], $url);

    return $url;
  }
```

In 2.5.7, like this:

```
  public static function unIdn($url) {

    if(!function_exists('idn_to_ascii')) return $url;

    // disassemble the URL, convert the domain name and reassemble
    $variant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : INTL_IDNA_VARIANT_2003;
    $host = idn_to_ascii(static::host($url), 0, $variant);
    if($host === false) return $url;
    $url  = static::build(['host' => $host], $url);

    return $url;
  }
```

So the fix is to change this **back** to what it looked like in 2.5.5.

**Comment by raschid** [comment]
**Ooops, you did idt again ...**

It worked. Thanks for the help

Last thing for today: do i have to worry about this message in the panel?
![kirby02](https://user-images.githubusercontent.com/5807524/33893809-ac832dc8-df5c-11e7-9c3b-37840b32f450.jpg)

**Comment by texnixe** [comment]
To get rid of that message, revert this:

(in the same file as above)
```
  public static function idn($url) {

    if(!function_exists('idn_to_utf8')) return $url;

    // disassemble the URL, convert the domain name and reassemble
    $variant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : INTL_IDNA_VARIANT_2003;
    $host = idn_to_utf8(static::host($url), 0, $variant);
    if($host === false) return $url;
    $url  = static::build(['host' => $host], $url);

    return $url;

  }
```

to 

```
  public static function idn($url) {

    if(!function_exists('idn_to_utf8')) return $url;

    // disassemble the URL, convert the domain name and reassemble
    $host = idn_to_utf8(static::host($url));
    $url  = static::build(['host' => $host], $url);

    return $url;

  }
```

In the future, let's better discuss such stuff in the [forum](https://forum.getkirby.com/)…

**Comment by raschid** [comment]
works like a charm :-)
Last "Thank YOU" for today :-)

**Comment by raschid** [comment]
Hey texnixe,
i posted your panel-solution as a  [gist](https://gist.github.com/raschid/8bb056f6a4bf8cd97175bf95e788a518)
just so you now ...
