### ISSUE TITLE
Do not fall back to default role for $user->role() when role is `nobody`

### ISSUE THREAD

**Issue by kraftner** [getkirby/kirby#603]
Currently when you have [a default role set](https://getkirby.com/docs/panel/roles#creating-your-own-roles) and query for a user with the role set to `nobody` [you get the default role back instead](https://github.com/getkirby/kirby/blob/fb7cc905d7a47dac00ee172516d45204d1bf9965/core/user.php#L84). Same in case you [don't have a role set for a user at all](https://github.com/getkirby/kirby/blob/fb7cc905d7a47dac00ee172516d45204d1bf9965/core/user.php#L77).

So basically in that particular case

```
$user->data()['role'] != $user->role()
```

I think this is highly confusing. For example when I call `$users->filterBy('role','certain_role')` I **not** only get users with the role `certain_role` but also anybody who is a `nobody` or without any roll at all. So to achieve what one probably intends you currently need to do this:

```
$certain_role_users = site()->users()->filter( function( $user ){
	$data = $user->data();
	if( empty($data['role']) || $data['role'] === 'nobody' ) {
		return false;
	}
	return $user->role() == 'guest';
} );
```

**Comment by lukasbestle** [comment]
How can it happen that users have a role of `nobody` and `nobody` is not the default role?

The `nobody` role is only enabled by default if the developer has defined a set of roles, but made none of them the default role. So once you set a custom role to be the default role, new users won't get the `nobody` role. In this case you as the developer should clean up existing users and assign them a new valid role.

So as far as I can tell, this situation can only appear after the role configuration changes. In this case it's not a bug. If you disagree, please reopen this issue and tell me how you got into this situation. :)

**Comment by lukasbestle** [comment]
After discussing this in the team (thanks for your email!), we have decided that this is worth fixing even though the issue only appears after changes to the role definitions or when manually editing the user files.

So this issue is now fixed on the develop branch by:

- adding the `nobody` role in at all times, even if there is a valid default role
- making sure that this `nobody` role never has any permissions whatsoever
- using the `nobody` role as a fallback for invalid role definitions in user files
- making sure that a user with an invalid role can't be updated in the Panel without explicitly choosing a new valid role

Please help us testing the new implementation. Maybe we missed another edge case. Thanks! :)

**Comment by kraftner** [comment]
Conceptually from looking at the code I have some further thoughts:

- The inconsistency of $ `user->data()['role'] != $user->role()` for empty/invalid roles persists
- Why not always keep the nobody role as an option in the panel? I think it is quite handy to be able to deactivate users without deleting them. Is [https://github.com/getkirby/panel/blob/fe6ef4bc55ffe5133413e2a1c336f14c9269c096/app/forms/users/user.php#L32](this) really needed?
- Tests? :wink: 

I wanted to try this with the real world project I am working on but currently the dev branch isn't working properly due to https://github.com/getkirby/panel/commit/afebe6874fed7271006ecaf44f79fdf5e7c23d4b#commitcomment-24726784

**Comment by lukasbestle** [comment]
> The inconsistency of $ user->data()['role'] != $user->role() for empty/invalid roles persists

Well, yes. Invalid roles are now "bent" to the `nobody` role. There's no other way as every user needs to have a valid role to make the permissions work.

> Why not always keep the nobody role as an option in the panel? I think it is quite handy to be able to deactivate users without deleting them. Is https://github.com/getkirby/panel/blob/fe6ef4bc55ffe5133413e2a1c336f14c9269c096/app/forms/users/user.php#L32 really needed?

You can add your own custom role without permissions for that use-case. The `nobody` role is special and we have decided in the team that we don't want to display it to avoid confusion.

> Tests? 😉

I see your point, but that's something we can't fix in v2. v3 will have a *much* better and cleaner architecture and we will make sure that everything is tested very well. :)

> I wanted to try this with the real world project I am working on but currently the dev branch isn't working properly due to getkirby/panel@afebe68#commitcomment-24726784

That's fixed now. :)

**Comment by kraftner** [comment]
Sounds all good.

Concerning the first issue: I thought about it the other way - why not also return the "bent" role when calling `user->data()`?

**Comment by lukasbestle** [comment]
`$user->data()` fetches and returns the raw user data. We don‘t want to have any application logic in this method (very hard to find when debugging as you wouldn‘t expect it there).

Is there any special reason why it could make sense to change the role there?

**Comment by kraftner** [comment]
I understand that, but then this at least should be mentioned in the docs because right now nothing in there hints at the fact that for any `property` `user->data()['property'] != $user->property()` can be true.

**Comment by lukasbestle** [comment]
Yep, we are going to document the new behavior. :)
