### ISSUE TITLE
[Panel] If a user’s name is empty, the respective breadcrumb item won’t fallback to the user email

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#605]
How the breadcrumb looks like right now:
<img width="614" alt="screenshot 2018-07-09 22 20 58" src="https://user-images.githubusercontent.com/1512805/42474042-a96428d6-83c6-11e8-83a5-d539fd1f5299.png">
Expected:
<img width="515" alt="screenshot 2018-07-09 22 23 38" src="https://user-images.githubusercontent.com/1512805/42474078-c030ca9c-83c6-11e8-8d6e-38f02c448d07.png">

**Comment by bastianallgeier** [comment]
✅
