### ISSUE TITLE
Problem when using findByURI function

### ISSUE THREAD

**Issue by alexandre-combemorel** [getkirby/kirby#605]
Hi all,

When I try to fetch a page through `findURI($path)`, I realise that if my path in my URL is several time the name of the page, the function is still returning me the page where this path shouldn't exist.
For example, I have the page 'jobs' at the root of my website and I enter this URL: `mywebsite.de/de/jobs/jobs/jobs` (as many time as I want), then kirby will return me the 'jobs' page. 

Is it a behaviour expected or a bug ?

Thanks in advance.
Best,
Alex

**Comment by texnixe** [comment]
Interesting, but yes, I can reproduce this in a langkit. Such an URL should of course return the error page (and it does in a single language starterkit).

**Comment by alexandre-combemorel** [comment]
Alright, thanks for feedback :), should it be consider as a bug then ?

**Comment by lukasbestle** [comment]
Fixed on the develop branch.
