### ISSUE TITLE
"Fatal error: Cannot redeclare class Asset" when using a multi-language setup and use kirby() in config.php

### ISSUE THREAD

**Issue by elwin1234** [getkirby/kirby#606]
With kirby v2.5.6 this works:

*site/config/config.php*
```php
dump(kirby());
```

But this:
```php
<?php
c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'English',
    'default' => true,
    'locale'  => 'en_US',
    'url'     => '/',
  ),
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'locale'  => 'de_DE',
    'url'     => '/de',
  ),
));

dump(kirby());
```
results in
```
Fatal error: Cannot redeclare class Asset in ../kirby/branches/multilang.php on line 0
```

**Comment by lukasbestle** [comment]
I can reproduce this bug with Kirby 2.4.0 already (Kirby 2.3.2 is the last version that works). We will take a look at it for the next release. Shouldn't be too hard to fix. :)

**Comment by LeBenLeBen** [comment]
Checking out various commits in the kirby repository, the problem starts at commit 9cc028c8 for me.

**Comment by jonathan-reisdorf** [comment]
I also have to roll back kirby repo to fb7cc905d7a47dac00ee172516d45204d1bf9965 and panel to f2d8ddbc3fe48f3b69808d4ed594d47db1b97cd2 or I'm getting the same error

**Comment by lukasbestle** [comment]
Well, but as I said, I could reproduce this with Kirby 2.4.0 as well yesterday. But anyway, we will take a look at it for the next release. :)

**Comment by lukasbestle** [comment]
https://forum.getkirby.com/t/error-500-when-updating-to-kirby-2-5-6/8778?u=lukasbestle

**Comment by lukasbestle** [comment]
Unfortunately there is no way to fix this as fixing this conflicts with other bug fixes for the whole "call `kirby()` from inside `config.php`" situation.

It is just not intended to call anything from the config: Calling `kirby()` loads all kinds of stuff – and if the config is not already fully set (which means: the `config.php` file exits) Kirby will load the wrong kind of stuff.
I know that there are use-cases that are currently implemented by getting a Kirby object from inside the `config.php` file, but we can't possibly support all of those.

@LeBenLeBen You wrote that this issue also occurs without calling `kirby()`. I can't reproduce this. Please open a new issue with steps to reproduce. Thanks!

**Comment by LeBenLeBen** [comment]
The error was caused by a `site()` call in my case. My implementation was actually wrong and were able to fix it.

**Comment by lukasbestle** [comment]
Yes, `site()` also calls `kirby()` internally, so that's related. :)

**Comment by mrflix** [comment]
Its such a nice feature that its possible to show the editor invisible content in overviews and its unfortunate that caching can't be turned off for them any longer because of this issue. I hope that you'll reconsider adding a config to turn off caching for logged in users or to give us back another way of doing this ourself.

**Comment by lukasbestle** [comment]
As I wrote above, the current config architecture isn't compatible with features like this.
However we will definitely redesign the config in Kirby 3 and we will consider the use-case of getting site information while setting the config.
