### ISSUE TITLE
Language detection: changing language through URL on home redirect to default language

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#610]
With the following multiliang setup:

```
c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'English',
    'locale'  => 'en_US.utf8',
    'url'     => '/en',
    'default' => true,
  ),
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'locale'  => 'de_CH.utf8',
    'url'     => '/de',
  ),
  array(
    'code'    => 'fr',
    'name'    => 'Français',
    'locale'  => 'fr_CH.utf8',
    'url'     => '/fr',
  ),
));
c::set('language.detect', true);
```

## Problem
* I access my website at foo.lo
* I’m redirected to foo.lo/fr since my browser is in French
* For some reasons I prefer the German version, I manually change the URL in the browser to foo.lo/de
* I get a 302 Found and get redirect to foo.lo/en (the default language)

## Expected behavior
When accessing the root URL that match a language, I should stay on it and not be redirected.

## Notes
If I do the same with a language switcher, which is a link in the page, the problem doesn’t occur, probably because of the `Referer:http://foo.lo/fr` header sent.

The problem doesn’t occur on other pages, only for root routes. It also doesn’t occur if "language.detect" is disabled.

It looks like if I never visited the site, the problem occur as well. If I go to foo.lo/de directly, I’m redirected to foo.lo/en whatever my language preferences are.

**Comment by lukasbestle** [comment]
That's strange. We will look into this.

**Comment by LeBenLeBen** [comment]
You can reproduce the issue live at https://www.liip.ch/ if that can help you.
