### ISSUE TITLE
[Panel] Disabled Template-Field in Modal does not look disabled

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#610]
If only one template is choosable the input-field in the new-page-modal is disabled but it doesn't really look disabled. 

<img width="449" alt="bildschirmfoto 2018-07-10 um 11 44 59" src="https://user-images.githubusercontent.com/3930150/42502600-d21f5514-8436-11e8-8e47-2d10da836547.png">

**Comment by bastianallgeier** [comment]
✅
