### ISSUE TITLE
[Panel] Improve Error-Dialog "Please fix all form errors.."

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#615]
Why not add a list of all fields with errors? 

Wasn't this already included in a previous version? I'm not sure.

**Comment by wottpal** [comment]
Related https://github.com/k-next/kirby/issues/537

**Comment by wottpal** [comment]
I just found out the list is already generated when I try to publish pages:
<img width="368" alt="bildschirmfoto 2018-07-10 um 12 09 11" src="https://user-images.githubusercontent.com/3930150/42503874-22b84b68-843a-11e8-8cba-2f7a4e5d7450.png">

**Comment by bastianallgeier** [comment]
✅
