### ISSUE TITLE
Kirby - Changing the Page template/blueprint 

### ISSUE THREAD

**Issue by opelandia** [getkirby/kirby#615]
HI! 
Im having an issue changing the template options in my kirby panel. The option to select a template isnt even there. Im working on breaking down the Kirby example 2.5.6 to edit the code and create my site. This worked on the home page, inserting snippets, editing the text file and php tags I made from kirbys existing code, but when I moved onto the second page I cant get it to recognize my blueprint, yaml, or template. 

When I go to select a new page the template option appears in grey but locked so I cant change it. It does however recognize the second page and treat it with the default blueprint but im not sure what ive done for this kind of key function not to be working.

**Comment by texnixe** [comment]
Hi, the best place to ask such question is the Kirby forum.

If you can't select a template/blueprint in the page create modal, then the possible templates are restricted in the parent blueprint, for example, in the Starterkit's `site.yml`, possible templates are restricted to the default template, subpages of the blog page may only have subpages with the `article`blueprint etc. You would have to edit those files and either remove the restrictions or put your own in.

**Comment by lukasbestle** [comment]
I'm closing this issue. If you have any further questions, feel free to ask in the forum as @texnixe wrote above. :)
