### ISSUE TITLE
[Panel] Fix fake input buttons for forms

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#62]
@bastianallgeier 
> We use hidden input buttons to enable native form submission, which is super nasty right now. We need to remove this from all forms and replace it with something less nasty.

**Comment by distantnative** [comment]
@bastianallgeier still seems to be the way to go these days: https://alligator.io/vuejs/vue-form-handling/

**Comment by bastianallgeier** [comment]
✅
