### ISSUE TITLE
The <figure> in image tag should be optional.

### ISSUE THREAD

**Issue by ljacobs-sml** [getkirby/kirby#62]
I closed another issue because I had figured out it was user error, having not updated a custom "cdnimg" kirby tag when you updated the regular "image" tag. Upon updating that though, I realized that all my images weren't behaving the same way which, as it turns out, is because you introduced a figure wrapper around all images. This is fine and dandy I guess, but it's been requiring me to go back and review the whole site for complications across various screen sizes.

I tried doing it myself, moving the whole figure brick creation into the if $caption !empty line, and returning $image instead of $figure in an else case.. But after doing that, whenever I have an image above other markdown content, it doesn't format the markdown content correctly (displays it as plain text) unless I revert back to an old parsedown version again. A few hours later, everything seems to be okay, but I don't know if mandating the figure tag is the right way to go.

**Comment by bastianallgeier** [comment]
I forgot to close this, but the new kirbytext.image.figure option is available since last version to fix this.
