### ISSUE TITLE
Double slashes when paginating with a search parameter K257, only when switching from page 1 to page 2

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#620]
https://forum.getkirby.com/t/pagination-object-gives-double-slashes-going-from-page-1-to-page-2/9086

**Comment by lukasbestle** [comment]
I already have an idea why this is happening. We changed something with slashes in the `url::build()` method. So this is definitely a bug and I will take a look at it.

**Comment by lukasbestle** [comment]
The bug was in `url::build()` again. Looks like we are steadily improving on edge-case handling there. ;)
