### ISSUE TITLE
[Panel] Hover-Flickering in Safari

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#622]
I have this problem in literally every project and because I'm a full time Safari user I can't unsee it. Sometimes in Safari when you define a transition on hover it just flickers and looks sluggish. I saw this for example on the `kirby-sort-handle` and there is an easy fix for it. Just add:

```css
.kirby-sort-handle {
   will-change: opacity, color;
}
```

Without `will-change`:
![without](https://user-images.githubusercontent.com/3930150/42562705-ba960bc4-84fc-11e8-9b9d-b1872f347603.gif)

With `will-change` (just like in every other browser):
![with](https://user-images.githubusercontent.com/3930150/42562713-bcb0ceb2-84fc-11e8-961c-f796873f8440.gif)

Another workaround which I had to use before Safari started supporting `will-change` was adding `transform: translate3d(0,0,0);` to enable hardware acceleration for this element.

**Comment by nilshoerrmann** [comment]
This effect is also visible in Firefox.

**Comment by bastianallgeier** [comment]
✅
