### ISSUE TITLE
[Panel] Field Error

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#623]
If a query setting results in an error, the panel display this:

![bildschirmfoto am 2018-07-11 um 12 19 34](https://user-images.githubusercontent.com/25466/42565796-c1a43582-8504-11e8-81e9-635c8810a10e.png)

It's not clear which field caused this error. The name is missing in the label/headline.

**Comment by bastianallgeier** [comment]
![bildschirmfoto 2018-07-11 um 13 58 47](https://user-images.githubusercontent.com/24532/42569965-9487da46-8512-11e8-8def-17091d63305a.png)

✅

**Comment by bastianallgeier** [comment]
The full exception output is now also available in the error log

**Comment by nilshoerrmann** [comment]
Where do I find this error log?

**Comment by bastianallgeier** [comment]
It's the PHP error log. It depends on your setup where you can find it.
