### ISSUE TITLE
Link Kirbytag should not try to convert `mailto:` urls

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#623]
Hi everyone,

currently, when using a `mailto:` url in combination with the link kirbytag Kirby will try to convert it to an absolute url based on the site’s base url.

I know that there are other ways to markup email links in plain markdown as well in kirbytext, but – keeping in mind not every enduser will be familiar with this behaviour – I think it’d be a nice enhancement if there was an exception for `mailto:` links so links do not break.

```
Kirbytext:
(link: mailto:test@example.org text: Contact us!)

Output:
<a href="https://example.org/mailto:text@example.org">Contact us!</a>
```

Thanks for your ongoing work on Kirby, wish you all relaxing holidays! 🎄

**Comment by lukasbestle** [comment]
Oh, that's definitely a bug!
Actually it's a bug in `url::isAbsolute()`, which is currently quite pigheaded at detecting protocols other than HTTP. Will be fixed in the next release. :)
