### ISSUE TITLE
Enabled SSL in config should redirect with 301 instead of 302 headers

### ISSUE THREAD

**Issue by l4ci** [getkirby/kirby#624]
As of now, the config setting `ssl = true` will redirect the user with the default `301` http header status code. To pass link strength it should be a permanent redirect with status code `302`.

https://github.com/getkirby/kirby/blob/a2678c41c7f57ef176651e257840861d6c21b653/kirby.php#L703

```php
go(url::build(array('scheme' => 'https')), 302);
```

> There are different kinds of redirections. Search engines normally recommend the use of so-called permanent redirections (status code 301). Other redirects may be used, but are not recommended for the purpose of search engine optimization (for example: 302 - found) because they do not transmit link strength.

**Comment by lukasbestle** [comment]
It's the other way around: HTTP 301 is a permanent redirect ("Moved permanently"), HTTP 302 is a temporary redirect ("Found"). So actually the current implementation is already correct. Please reopen this issue if you disagree.

**Comment by l4ci** [comment]
You are right, i mixed them up in my first sentence. Still I got confused because of the docs <https://getkirby.com/docs/toolkit/api/helpers/go>
The second parameter reads as if it would default to the mentioned 302 if omitted: `go($url = '/', $code = 302)`

The real status code being used is 301 - as you mentioned: https://github.com/getkirby/toolkit/blob/183662ccabdf2ba6a83e14aaf100bd7c533c3b3a/lib/header.php#L242

You can close this again, I just wanted to clear things up in case someone stumbles upon the toolkit docs.

**Comment by lukasbestle** [comment]
I just tested this to verify – and it turns out that the `go()` function *does* default to HTTP 302, but only by accident.

I have fixed the "by accident" part on the develop branch of the Toolkit (because HTTP 302 is intended there) and also added your proposed "HTTP 301 for the HTTPS redirect" feature to the develop branch of Kirby.

**Comment by l4ci** [comment]
Oh nice, turns out I wasn't so wrong after all 😄 - thanks for the fast reply!
