### ISSUE TITLE
[Panel] Add Slug-Changed Notification Message

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#632]
When I change the URL of an page and confirm the modal this is the displayed notification:

<img width="183" alt="bildschirmfoto 2018-07-11 um 15 14 23" src="https://user-images.githubusercontent.com/3930150/42573770-4f9bcfe0-851d-11e8-85dc-2f8317b6c22e.png">

**Comment by bastianallgeier** [comment]
✅
