### ISSUE TITLE
[Panel] Improve Policy with Missing Required Files-Fields

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#633]
With Kirby & files I often had one problem: I upload a file into a page and forget to fill in required fields of the file. But this is no problem for Kirby and I can even save the page. So why not either

- Disallow saving a page and display a form-error message like with required fields of the page itself or
- keep the current behavior but highlight the files with missing fields e.g. with a red outline

**Comment by distantnative** [comment]
Duplicate of https://github.com/k-next/kirby/issues/349
