### ISSUE TITLE
[Panel] Allow filtering of page sections

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#635]
This was available in the early alphas and allows for great flexibility. There even was an option to query collections that introduced very advanced use cases.

While this kind of flexibility in section display might be irritating for longterm Kirby users, it's straight forward when you have a different background and no previous Kirby knowledge. Please reintroduce this at some point. For us, this was one of the most exceptional features in the alphas.

It might be an requirement to disable drag & drop for these custom lists to avoid random page shuffling.

**Comment by distantnative** [comment]
> it's straight forward when you have a different background and no previous Kirby knowledge.

I have to disagree. We did not disable it because it was too irritating for some users. We disabled it because it was not working reliably. Because there where a whole new dimension of edge cases and complexities that we could not handle properly. We will try to re-introduce it again but only when we can solve that complexity: both from a point of bug-free and from the point of usability (understanding what you are doing).

**Comment by nilshoerrmann** [comment]
This is actually not what I meant to say. I totally understand your point and agree. 

I just wanted to point out what a great feature this was.
Sorry for not being clearer – didn't want to sound rude.

**Comment by texnixe** [comment]
Maybe these. should be two separate issues? Sorting should be less of a problem as compared to filtering?  The current sort order by ascending date doesn't make that much sense?

**Comment by texnixe** [comment]
The current sort order by ascending date doesn't make that much sense?

**Comment by distantnative** [comment]
> Sorry for not being clearer – didn't want to sound rude.

It didn't come across as rude :) I just wanted to make sure that you or others don't have the impression that we removed it cause we thought it was too difficult to use. We removed it because it didn't work reliably so far.

**Comment by bastianallgeier** [comment]
sortBy should still be working!

**Comment by nilshoerrmann** [comment]
I cannot get sorting to work in the latest nightly.

**Comment by texnixe** [comment]
I tested sorting as well, it is even in the example blueprints but changing desc to asc doesn't have. any effect.

**Comment by johannahoerrmann** [comment]
As a first step, I would love the option to "simply" show a pages section in the panel which consists of a group of my page's children sharing a certain field value. No sorting, no "add new". This would already be *so helpful* for my client working with the panel.

**Comment by bastianallgeier** [comment]
I split this into two tickets: https://github.com/k-next/kirby/issues/647

**Comment by nilshoerrmann** [comment]
May I politely ask, if it was possible to reintroduce querying for sections again by restricting the display to read-only in order to prevent edge-cases (no add button, no sort option)?

We are really missing an option right now to create specialised overviews for large data sets (showing all featured projects of a given category and such). The only way to filter page sections right now is status-based which is very limiting in complex content scenarios.
