### ISSUE TITLE
Fields called `username` are always displayed as lowercase in the admin panel

### ISSUE THREAD

**Issue by mfrischknecht** [getkirby/kirby#635]
The kirby panel css contains the rule:

```
body:not(.login) #form-field-username {
    text-transform: lowercase;
}
```

which leads to any blueprint field with the name `username` to be displayed in lowercase. I stumbled over this because I used [this guide](https://getkirby.com/docs/cookbook/authentication) to create pages that can only be viewed by logged in users and wanted to use fields in the `login` page for the translation of the according labels (as recommended in the guide).

**Comment by lukasbestle** [comment]
Yes, this is indeed not optimal. Kirby 3 will have an entirely new frontend in the Panel, so this will probably be fixed there.
