### ISSUE TITLE
Wordpress-like image scrset with a snippet?

### ISSUE THREAD

**Issue by drivebass** [getkirby/kirby#636]
Is it a good idea/practice to build a wordpress-like image srcset with a snippet using kirby's thumb() function and use it inside templates to display responsive images? I have tested this and it works fine with the browser switching images between different screen dimensions. 

"img_build" Snippet:
```
<img src="<?= $image->url();?>" srcset="<?= $image->url();?> 1200w, <?= thumb($image, array('width' => 400))->url(); ?> 400w, <?= thumb($image, array('width' => 800))->url(); ?> 800w, <?= thumb($image, array('width' => 768))->url(); ?> 768w, <?= thumb($image, array('width' => 80))->url(); ?> 80w, <?= thumb($image, array('width' => 350))->url(); ?> 350w" sizes="(max-width: 1200px) 100vw, 1200px" data-width="<?= $image->width();?>" data-height="<?= $image->height(); ?>">
```

Template call for a slideshow field:
```
<div class="images">
    <?php foreach($page->slideshow()->yaml() as $image): ?>   
        <?php if($image = $page->image($image)): ?>
	    <?php snippet('img_build', array('image' => $image)); ?>  		    
	<?php endif ?>
    <?php endforeach; ?>
</div>
```

**Comment by lukasbestle** [comment]
Fabian Michael has published a [Kirby plugin called ImageSet](https://github.com/fabianmichael/kirby-imageset) that has a few additional features, but if you don't need those, your simple snippet is definitely fine. :)

**Comment by texnixe** [comment]
On a side note: The [forum](https://forum.getkirby.com)  is a better place to ask such questions...
