### ISSUE TITLE
[Cms] Controller not passing data to content representation

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#637]
In Notion docs it says:

> **Representation controllers**
> You can also have special controllers for each of your representations. If you create a controller with the name default.json.php, it will be used for the JSON representation of the default template. **If no special representation controller exists, the normal one (default.php or site.php) will be used instead.**

If I name the controller `controllers/default.json.php` I can access the variables in the content representation (`templates/default.json.php`).

But if the controller is named just `controllers/default.php` I can access the variables only in my normal template (`templates/default.php`), not in the content representation.

**Comment by pedroborges** [comment]
I have experienced the same issue, the default controller doesn't pass data to corresponding representation template.

**Comment by bastianallgeier** [comment]
✅
