### ISSUE TITLE
Μanual drag and drop not working (Κirby 2.5.9)

### ISSUE THREAD

**Issue by giokey** [getkirby/kirby#637]
When trying to sort the subpages with manual drag and drop in the subpage sorting panel, the subpages stick back to their original position after being moved. Same thing happened when added a new page. This happens when they exceed the number 9

**Comment by lukasbestle** [comment]
Thanks for reporting. This is a known bug (see https://github.com/getkirby/panel/issues/1138) and has been fixed on the develop branch of the Toolkit. You can already apply this fix to your installation, but of course the fix will also be included with Kirby 2.5.10.
