### ISSUE TITLE
[Panel] Search - all not just titles

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#638]
I really wish I had the possibility to search for something else than the title in the general panel search. If all I recall is another bit of information *other* than the title, I have no chance of quickly finding the entry I am looking for. This happens pretty often in a use case I have (exhibition entries with name as title, but what I remember is the related project) and it is super frustrating.

**Comment by bastianallgeier** [comment]
✅

**Comment by bnomei** [comment]
so this is using core search on `site->index()`? can i configure this? or even better hook my algolia search into this? because some of my client websites are > 1000 pages and in K2 the panel search was pretty useless then.
