### ISSUE TITLE
[Panel] Remember section pagination position

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#639]
My current page/position in the pagination of a section is not saved in the URL: when clicking on an entry and then using the browser’s back button, I’m thrown back to the beginning of the list („page 1“). This makes it very hard to navigate and work with masses of entries.

(You know, like this section:)

<img width="211" alt="bildschirmfoto 2018-07-12 um 11 23 44" src="https://user-images.githubusercontent.com/149678/42624624-17ec0228-85c6-11e8-9f64-bdd38c497dd6.png">

**Comment by bastianallgeier** [comment]
This is quite difficult to achieve with many sections as we would need multiple pagination query parameters in the URL. Would an automatically remembered last page help as a first step?

**Comment by johannahoerrmann** [comment]
Yes!
