### ISSUE TITLE
Section filter UI

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#640]
I wish there was a filter UI for sections! I mainly miss this because I would love a better overview of how many entries I am dealing with in a particular grouping (say with a certain value of a select field), to simply better find and edit entries or even to batch edit somewhere down the line. 

When thinking of a filter UI, I would wish for:

- a more tabular view with additional content columns
- the ability to sort based on columns (ascending/descending)
- the ability to search for entries (something like #478)

I can just see clients and myself really profiting from enhanced possibilities to navigate and work with entries in a section.

**Comment by nilshoerrmann** [comment]
In my eyes this filter view should be switchable on demand by the user similar to how structure fields which layout between tabular and edit view. Only that it would be reversed here: you'd switch from edit (manual sorting) to tabular mode (programmatic filtering).

**Comment by bastianallgeier** [comment]
I think this would be a perfect case for a section plugin. Maybe something called pagetable, that could focus on exactly those features as an alternative to our pages section.

**Comment by distantnative** [comment]
Copied over to plugins repo: https://github.com/k-next/plugins/issues/84
