### ISSUE TITLE
Fatal error: Cannot redeclare go() [...]

### ISSUE THREAD

**Issue by jschopplich** [getkirby/kirby#643]
I encountered the following issue:
```
Fatal error: Cannot redeclare go() in /shared/httpd/starterkit/htdocs/kirby/vendor/getkirby/toolkit/helpers.php on line 29
```

I'm using Devilbox on macOS with Kirby Starterkit, all current versions as well as a clean installation.

![screenshot-2018-5-10 http starterkit loc](https://user-images.githubusercontent.com/27850750/39895534-efd7b198-54aa-11e8-8736-91bdb2c193b3.png)

**Comment by texnixe** [comment]
Doesn't the error tell you where it was previously  declared? Also, the go function is on line 27 in an up to date toolkit. Maybe you are using some composer stuff that has already a go function somewhere.

**Comment by jschopplich** [comment]
It sure does. The thing is I just downloaded the zip file off the Kirby website. No modifications whatsoever. 

It maybe is actually Devilbox's fault, as I can run the same folder with MAMP successfully.

I'm irritated.

**Comment by texnixe** [comment]
Yes, I guess it must be a conflict with Devilbox. I'm closing this, as this is nothing we can solve.

**Comment by illycz** [comment]
@jschopplich do you solve this issue somehow? Thanks

**Comment by jschopplich** [comment]
@illycz No, sadly I couln't and just used MAMP since. So the issue still persists?

**Comment by illycz** [comment]
@jschopplich yes, still...

**Comment by jschopplich** [comment]
That's too bad. I have no idea how to fix this or even find the problem itself, so I guess there's nothing we can do.

**Comment by illycz** [comment]
I created issue on devilbox repo: https://github.com/cytopia/devilbox/issues/361
Maybe someone help...

**Comment by cytopia** [comment]
### FYI

@texnixe @illycz @jschopplich  this error is not specific to the Devilbox. The `go()` function is implemented in recent versions of the **[swoole](https://github.com/swoole/swoole-src) PHP module**. If this module is enabled, you will get the error about redeclaration.
