### ISSUE TITLE
[Cms] $file->rename() does not rename the meta .txt file

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#644]
I wanted to use $file->rename() in a `file.create:after` hook. But only the file itself was renamed, not the meta .txt file.

This also meant, that the file did not show up in the panel field after the upload.

Just calling $file->rename() in a template did not rename the meta .txt, either.
 
I used the Nightly build 2018-07-12.

**Comment by bastianallgeier** [comment]
✅
