### ISSUE TITLE
Cachebusting added twice to thumbnails in the Panel

### ISSUE THREAD

**Issue by malvese** [getkirby/kirby#646]
Looking at he new thumbnails' url in nigthly 2018-07-12, the cachebusting query string seems to be added twice:
`image.png?v=2018-07-12T18:51:54+02:00?v=2018-07-12T18:51:54+02:00`

**Comment by bastianallgeier** [comment]
This is probably in the panel somewhere. Could you let me know exactly where you saw this? I can't find it at the moment.

**Comment by malvese** [comment]
Sorry for the half-assed report! The missing information:

In the Panel, click an image in a "files" section, so you land on the "media" screen. The image at the top left has the double query string.

I checked again and it's the only place I've seen it so far. I initially thought it was the case for all thumbnails, but other thumbnails in the Panel have a different query string `?t=…`.

**Comment by bastianallgeier** [comment]
Very good one! Thanks for spotting it. I would have never found it :D It's fixed now.
