### ISSUE TITLE
$email->send() Call to undefined method Whoops\Exception\ErrorException::message()

### ISSUE THREAD

**Issue by hdodov** [getkirby/kirby#646]
I was following the [developer guide for emails](https://getkirby.com/docs/developer-guide/advanced/emails#php-mail) where this code is shown:

```
if($email->send()) {
  echo 'The email has been sent';
} else {
  echo $email->error()->message();
}
```

On localhost, I don’t have a mail server set up and I know I should be getting an error. However, it’s not echoed properly. I get:

>Error thrown with message "Call to undefined method Whoops\Exception\ErrorException::message()"
>
>Stacktrace:
>3 Error in C:\xampp\htdocs\mebeliroko\site\config\config.php:44
>2 Kirby:{closure} in C:\xampp\htdocs\mebeliroko\kirby\vendor\getkirby\toolkit\helpers.php:282
>1 call in C:\xampp\htdocs\mebeliroko\kirby\kirby.php:743
>0 Kirby:launch in C:\xampp\htdocs\mebeliroko\index.php:16

If I switch to the default Exception `getMessage()` method like this:

```
echo $email->error()->getMessage();
```

I get the expected error message:

>mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set()

**Why is that happening?** Is it a bug in Kirby, or a documentation mistake?

**Comment by lukasbestle** [comment]
That's an issue with the documentation, thanks for pointing that out!
I have moved this issue to our site repository: https://github.com/getkirby/getkirby.com/pull/384
