### ISSUE TITLE
[Panel] Grid layout bug: 1/4 and 1/3 overflow grid columns

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#649]
I used the Nightly build 2018-07-12: Columns of 1/4 and 1/3 overflow the grid columns for certain viewport widths.

![s-1](https://user-images.githubusercontent.com/15672385/42684019-3b399bea-868f-11e8-97ec-1298f6f67acb.jpg)

This is similar to issue [565](https://github.com/k-next/kirby/issues/565), which is already fixed. But this has nothing to do with `.kirby-cards`, but the grid itself:

A `.kirby-grid` with 12 columns has a `grid-column-gap: 1.5rem`. This means that the grid container has a "min-width" of 264px, because 11 grid-gaps * 1.5rem = 264px.

And this "min-width" forces a `.kirby-grid` that’s inside a 1/4 or 1/3 column to overflow:

![s-2](https://user-images.githubusercontent.com/15672385/42684074-571caaf0-868f-11e8-99e0-b90baa9b58ff.jpg)

**Comment by bastianallgeier** [comment]
✅
