### ISSUE TITLE
How to cache json content representation?

### ISSUE THREAD

**Issue by maximelebreton** [getkirby/kirby#653]
Hi all,

i'm using [content representations](https://getkirby.com/docs/developer-guide/advanced/representations) to create a custom rest api, and everything works.

For this content representation (**templates/works.php**):
```php 
<?php
  header::type('application/json');
  $data = (object)[
    'id'    => (string)$page->id(),
    'title' => (string)$page->title(),
    'uid'   => (string)$page->uid(),
    'slug'  => (string)$page->slug()
  ];
  $json = json_encode( $data );
  echo $json;
?>
```
When i call the **`/works`** urls, it returns a **.json** file as excepted.
(with the right header content-type: `application/json`)

**But when the file cache is activated, it returns an `.html` file**
(header content-type is `text/html`)

So how can I cache the content representation as a **.json** file?

Thanks!

**Comment by lukasbestle** [comment]
Do you get the (correct) JSON from the content representation with a content type of `text/html` or do you get the cached HTML from the standard template?

**Comment by maximelebreton** [comment]
Sorry if it wasn't clear.
I get the correct JSON from the content representation, but with a `text/html` content-type

**Comment by lukasbestle** [comment]
Ah, OK. I agree this is a bug, but unfortunately one we cannot fix in Kirby 2 as headers are currently not cached.

Kirby 3 will have a more robust response implementation. We will make sure that the content representation cache works properly. Sorry that there won't be a solution for Kirby 2.

**Comment by maximelebreton** [comment]
Argh, I'm about to release in production a website this monday, and can't wait for Kirby 3...

Any dirty hack solution?

**Comment by maximelebreton** [comment]
I think I've found a solution:

in **`config.php`**:
```php
c::set('headers', array(
  'works' => function($page) {
    header('Content-type: application/json; charset=utf-8');
  }
));
```

Can you confirm it will not cause some regressions?

**Comment by lukasbestle** [comment]
Your solution will send the header for every response, even for the HTML representation. If that's OK for you, then it should be fine. :)
