### ISSUE TITLE
English translation of error page

### ISSUE THREAD

**Issue by apps4research** [getkirby/kirby#654]
This is extremely minor (sorry), but for the default error message of non-existing pages, I would suggest that 

"The page **has not been** found."

is not quite grammatically correct, as it implies that at some point the page was found, but just now, it hasn't been found. I would argue, in most cases this isn't going to be true ... 

Why not simply write "Sorry, the page could not be found".

Just a suggestion. Kirby is great!

**Comment by lukasbestle** [comment]
As we have decided to move the other Starterkit changes to Kirby 3, I have fixed this issue in the Kirby 3 Starterkit as well. Again thanks for your help.
