### ISSUE TITLE
[Cms] Can't override plugin options

### ISSUE THREAD

**Issue by pedroborges** [getkirby/kirby#659]
Plugin `options` defined when it's registered are not being overridden by the same option in `site/config/config`.

The parameters order when `array_replace_recursive` [is called](https://github.com/k-next/kirby/blob/a5ddf6bed62ed41f7988c592a2d3aeab91d59086/src/Cms/AppPlugins.php#L114) are inverted.

Using `array_replace_recursive($options, $this->options)` fixes it for me.

----

There's another issue when an option is a simple array:

```php
// plugin registration
'options' => [
  'chain' => ['one', 'two']
]
```

When I try to replace it, it actually gets merged if the number of items are different:

```php
// site config
'pedroborges.plugin.chain' => ['three']
```

It becomes `['three', 'two']` instead of just `['three']`. That happens because the function replaces by the array index, but it can lead to undesired side effects. In my plugin, these options are passed as flags to a command and merging them can cause it to stop working.

**Comment by jenstornell** [comment]
+1

It looks like the issue I reported on slack a few days/weeks ago. I hope it's the same issue, because then I don't need to create another one.

Good work on finding the possible problem of the issue.

**Comment by bnomei** [comment]
+1
global config will not override value set in plugin config.

**Comment by bastianallgeier** [comment]
✅
