### ISSUE TITLE
Select multiple tags does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#660]
In the tags field we can select a tag with the mouse, but we can't select multiple tags.

**Suggestion (on Windows):**

`CTRL + mousedown` = Select one item at the time
`SHIFT + mousedown` = Select all items in an interval between two items

With the above a keypress on `delete` would delete all the selected tags.

*It does not work in Kirby 2, so you don't need to rush it.*

**Comment by distantnative** [comment]
When you delete one tag, the previous should get selected. So you could just hit delete again. Isn’t that much easier than overengineering it?

**Comment by jenstornell** [comment]
@distantnative Ahh, I see and you may be right.

The problem for me was that I had a few tags and selected the first tag and deleted it with the delete button. Then because it was the first tag, no more tag was selected so I could not delete the rest (not without stepping).

### Solution

A possible solution would be to simply check... if we delete the first tag, reselect the (new) first tag so that something is selected. I know I can step with the arrow keys to have it reselected, but it would be good UX I think.

**Comment by bastianallgeier** [comment]
I created a ticket for that fix: https://github.com/k-next/kirby/issues/new
