### ISSUE TITLE
Page can not be found on login, before it redirects

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#662]
Minor issue. When login on every version, even beta 2 I get "page can not be found" before the login form loads when going to `/panel`. It's only for a fraction of a second before I get redirected to `panel/login`.

It's enough time to wonder if there is an error. It only happends the first time so it seems the browser is caching the redirect somehow.

To get rid of this, make the `/panel` have a template with gray background, or don't make the redirect with js.

**Comment by bastianallgeier** [comment]
I saw that as well but couldn't pin it down so far. I will take a closer look at it. 👍

**Comment by bastianallgeier** [comment]
✅

**Comment by jenstornell** [comment]
I still experienced it in beta 3.
