### ISSUE TITLE
[Panel] Bug when inside a structure field and click on next page

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#666]
When inside the structure field and don't write anything it asks me if I want to discard or cancel changes. So far so good.

**Before I click outside:** I click the arrow for the next page, it goes to the next page so I got the question, but never had the time to answer it. When I go back a empty row is created.

![image](https://user-images.githubusercontent.com/927011/42778337-0c166644-893d-11e8-8913-1706bf1e7eca.png)

![image](https://user-images.githubusercontent.com/927011/42778201-9d8683b2-893c-11e8-9872-5998f432f9e6.png)

When clicking on the row again and click outside, it asks me again.

👿 #666

**Comment by bastianallgeier** [comment]
✅
