### ISSUE TITLE
[Panel] `No route found for path` after uploading image

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#667]
I guess this started with yesterdays nightly build but when I try to upload an image (fresh nightly build + beta 2 starterkit) and then click on it the following error is displayed. This seems to happen every time on each page.

<img width="488" alt="bildschirmfoto 2018-07-17 um 08 16 00" src="https://user-images.githubusercontent.com/3930150/42799850-b1bcdf18-8999-11e8-8e3a-9322c7340937.png">

**Comment by bastianallgeier** [comment]
✅ It was the @ sign in the filename
