### ISSUE TITLE
[Panel] Still some text is selected in Safari when dragging around

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#668]
![kapture 2018-07-17 at 8 17 23](https://user-images.githubusercontent.com/3930150/42799917-e3aef0a6-8999-11e8-896c-60ed5c1f6e61.gif)

**Comment by wottpal** [comment]
This is also the case for tags (btw I love to being finally able to drag them around 😍)

![kapture 2018-07-17 at 8 19 14](https://user-images.githubusercontent.com/3930150/42799984-2c9e61e8-899a-11e8-82c2-49335645d075.gif)

**Comment by wottpal** [comment]
🤷‍♂️
```js
element.addEventListener('drag-start', () => {
   document.body.style['-webkit-user-select'] = 'none';
}
element.addEventListener('drag-end', () => {
   document.body.style['-webkit-user-select'] = 'auto';
}
```

**Comment by bastianallgeier** [comment]
✅ I'm pretty sure I got it solved this time :)

**Comment by wottpal** [comment]
> ✅ I'm pretty sure I got it solved this time :)

👍 For the images
👎 For the tags
