### ISSUE TITLE
[Panel] Don't allow image-drag on itself (re-upload)

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#669]
![kapture 2018-07-17 at 8 30 30](https://user-images.githubusercontent.com/3930150/42800341-b7040724-899b-11e8-8ac9-6e6cdd4ec98b.gif)

**Comment by bastianallgeier** [comment]
Weird! I thought I already solved that. Safari?

**Comment by bastianallgeier** [comment]
✅
