### ISSUE TITLE
[Cms] Image-Paths with more than one component don't get `media/pages/` prepended

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#670]
* `(image: filename.jpg)` results in `<img alt="" src="http://kirby.local/media/pages/projects/trees-and-stars-and-stuff/filename.jpg">`
* `(image: projects/trees-and-stars-and-stuff/filename.jpg)` results in `<img alt="" src="http://kirby.local/projects/trees-and-stars-and-stuff/filename.jpg">` (**image not shown**)

This is also the reason drag'n'drop of images into textareas didn't work for me yet because this always generates the absolute path-version.

**Comment by bastianallgeier** [comment]
✅
