### ISSUE TITLE
[Panel] Layout issue when `headline` is omitted

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#672]
This happens with the `files`-section and the `pages`-field as well but I guess it happens with all fields that have an action in the upper right. Another option could be making the `headline`-field required and don't show the field if it has blueprint errors.

<img width="398" alt="bildschirmfoto 2018-07-17 um 08 42 33" src="https://user-images.githubusercontent.com/3930150/42800781-750685d4-899d-11e8-85d4-e63a2a34987b.png">

Off topic: Why did you go for `headline` in K3 and not `title` or `label`?

**Comment by bastianallgeier** [comment]
✅
