### ISSUE TITLE
[Panel] Make it clearer that created pages are Drafts

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#673]
For editors migrating from K2 the new draft-unlisted-listed paradigm is quite new so I imagine it could be helpful making it clear when created pages are **drafts**. Like in the screenshot below:

<img width="514" alt="bildschirmfoto 2018-07-17 um 08 46 07" src="https://user-images.githubusercontent.com/3930150/42801009-3a29c6be-899e-11e8-9c71-c284e43e52e1.png">

**Comment by bastianallgeier** [comment]
✅
