### ISSUE TITLE
[Panel] Add table headings to structure field

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#676]
**I added a structure field that looks like this:**

![image](https://user-images.githubusercontent.com/927011/42812311-8e24f26a-89bd-11e8-8884-1ba9d691cfb7.png)

So, what is `310` in this case? Quite hard to tell.

In this case it would make sense to add table headings.

### Fetch them from the edit form?

Maybe they can be added automatically from the edit form.

![image](https://user-images.githubusercontent.com/927011/42812429-e64c759e-89bd-11e8-8cef-beb684fc16a8.png)

**Comment by wottpal** [comment]
Thousand 👍

It could be also useful to define which fields are actually shown and in which order if there are too many. (Or is this already possible)

**Comment by bastianallgeier** [comment]
✅
