### ISSUE TITLE
[Panel] Property "title" is required, when saving an extended field in wrong folder

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#684]
I saved an extended field in `pages`. My fault of cause, but it took me a while to figure out what went wrong because of the error message I got.

![image](https://user-images.githubusercontent.com/927011/42819086-cd2f5efe-89d2-11e8-9b80-0f63906fd66c.png)

It would be much easier to track down if you also include the filename to what file caused the error.

*A sidenote: The file I put in the `pages` folder was parsed even if it was not in use.*

**Comment by bastianallgeier** [comment]
The title is no longer required. The name of the blueprint is used if no title is set.
