### ISSUE TITLE
[Panel] Placeholder not visible enough

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#687]
One of these values is a value, the rest are placeholders. A sharp eye will spot the difference here:

![image](https://user-images.githubusercontent.com/927011/42824918-2b8b597c-89e1-11e8-81b0-8c86aa938e96.png)

Let's say we only have placeholders. Then it becomes even harder to tell if these are values or placeholders.

![image](https://user-images.githubusercontent.com/927011/42825006-5ed128fc-89e1-11e8-8114-8f02d71af50b.png)

**Solution:** Make the placeholders even weaker.

**Comment by bastianallgeier** [comment]
✅
