### ISSUE TITLE
[Panel] 0 values are not displayed

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#690]
**I set 0 in a structure field:**

![image](https://user-images.githubusercontent.com/927011/42842532-bf98c8f8-8a0d-11e8-9353-b7342ab8ff0f.png)

**It's not displayed:**

![image](https://user-images.githubusercontent.com/927011/42842511-b005416e-8a0d-11e8-8a44-951b1dec268d.png)

It's probably seen as `NULL`.

**Comment by bastianallgeier** [comment]
✅
