### ISSUE TITLE
[Panel] Remove duplicated functions?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#692]
- "Rename" is not needed as we can click the title to rename it.
- "Change status" is not needed as we can click the status.

![image](https://user-images.githubusercontent.com/927011/42844070-276cd66e-8a12-11e8-9c45-fd75203373ba.png)

**Comment by bvdputte** [comment]
I kind of like having shortcuts for the same goal.
And I also like having a popup stating all possible options for this context.

**Comment by bastianallgeier** [comment]
We won't fix that. The title is only a shortcut. The options dropdown is the "real" thing. It's also more consistent, because we want to show the "Rename" option in the dropdown when you are browsing a list of pages.
