### ISSUE TITLE
[Toolkit/Panel] "White Medium Star" emoji doesn't work as page icon

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#694]
For some strange reason ["White Medium Star"](https://emojipedia.org/white-medium-star/) (⭐ - "\u2b50") isn't recognized as emoji. 

The app is building this DOM:
```html
<a href="http://localhost/panel/pages/home" class="kirby-link">
  <span class="kirby-card-icon" style="padding-bottom: 66.6667%;">
    <i aria-hidden="true" data-back="black" class="kirby-icon">
      <svg viewBox="0 0 16 16">
        <use xlink:href="#icon-⭐"></use>
      </svg>
    </i>
  </span>
</a>
```

while "Skull and Crossbones" (☠️ - "\u2620\ufe0f"), for example, is shown:
```html
<a href="http://localhost/panel/pages/home" class="kirby-link">
  <span class="kirby-card-icon" style="padding-bottom: 66.6667%;">
    <i aria-hidden="true" data-back="black" class="kirby-icon">
      <span class="kirby-icon-emoji">☠️</span>
    </i>
  </span>
</a>
```

**Comment by rasteiner** [comment]
I've made some research, and it seems that emojis are spread all over the UTF8 space, they aren't neatly packed into a few ranges, like [Str::isEmoji](https://github.com/k-next/kirby/blob/8184ac8b2e5c859e8c8f5dec3d3a3017d9291b2b/src/Toolkit/Str.php#L117) would make you think. 

Emoji ranges are listed [here](https://unicode.org/Public/emoji/11.0/emoji-data.txt); there are many codepoints that aren't in a range (like the star 0x2B50). 

From that list I've compiled a regex that matches all of them:

```php 
$emojis = '/[#*0-9©®‼⁉™ℹ↔-↙↩-↪⌚-⌛⌨⏏⏩-⏳⏸-⏺Ⓜ▪-▫▶◀◻-◾☀-☄☎☑☔-☕☘☝☠☢-☣☦☪☮-☯☸-☺♀♂♈-♓♟-♠♣♥-♦♨♻♾-♿⚒-⚗⚙⚛-⚜⚠-⚡⚪-⚫⚰-⚱⚽-⚾⛄-⛅⛈⛎⛏⛑⛓-⛔⛩-⛪⛰-⛵⛷-⛺⛽✂✅✈-✉✊-✋✌-✍✏✒✔✖✝✡✨✳-✴❄❇❌❎❓-❕❗❣-❤➕-➗➡➰➿⤴-⤵⬅-⬇⬛-⬜⭐⭕〰〽㊗㊙🀄🃏🅰-🅱🅾🅿🆎🆑-🆚🇦-🇿🈁-🈂🈚🈯🈲-🈺🉐-🉑🌀-🌠🌡🌤-🌬🌭-🌯🌰-🌵🌶🌷-🍼🍽🍾-🍿🎀-🎓🎖-🎗🎙-🎛🎞-🎟🎠-🏄🏅🏆-🏊🏋-🏎🏏-🏓🏔-🏟🏠-🏰🏳-🏵🏷🏸-🏿🐀-🐾🐿👀👁👂-📷📸📹-📼📽📿🔀-🔽🕉-🕊🕋-🕎🕐-🕧🕯-🕰🕳-🕹🕺🖇🖊-🖍🖐🖕-🖖🖤🖥🖨🖱-🖲🖼🗂-🗄🗑-🗓🗜-🗞🗡🗣🗨🗯🗳🗺🗻-🗿😀😁-😐😑😒-😔😕😖😗😘😙😚😛😜-😞😟😠-😥😦-😧😨-😫😬😭😮-😯😰-😳😴😵-🙀🙁-🙂🙃-🙄🙅-🙏🚀-🛅🛋-🛏🛐🛑-🛒🛠-🛥🛩🛫-🛬🛰🛳🛴-🛶🛷-🛸🛹🤐-🤘🤙-🤞🤟🤠-🤧🤨-🤯🤰🤱-🤲🤳-🤺🤼-🤾🥀-🥅🥇-🥋🥌🥍-🥏🥐-🥞🥟-🥫🥬-🥰🥳-🥶🥺🥼-🥿🦀-🦄🦅-🦑🦒-🦗🦘-🦢🦰-🦹🧀🧁-🧂🧐-🧦🧧-🧿⌚-⌛⏩-⏬⏰⏳◽-◾☔-☕♈-♓♿⚓⚡⚪-⚫⚽-⚾⛄-⛅⛎⛔⛪⛲-⛳⛵⛺⛽✅✊-✋✨❌❎❓-❕❗➕-➗➰➿⬛-⬜⭐⭕🀄🃏🆎🆑-🆚🇦-🇿🈁🈚🈯🈲-🈶🈸-🈺🉐-🉑🌀-🌠🌭-🌯🌰-🌵🌷-🍼🍾-🍿🎀-🎓🎠-🏄🏅🏆-🏊🏏-🏓🏠-🏰🏴🏸-🏿🐀-🐾👀👂-📷📸📹-📼📿🔀-🔽🕋-🕎🕐-🕧🕺🖕-🖖🖤🗻-🗿😀😁-😐😑😒-😔😕😖😗😘😙😚😛😜-😞😟😠-😥😦-😧😨-😫😬😭😮-😯😰-😳😴😵-🙀🙁-🙂🙃-🙄🙅-🙏🚀-🛅🛌🛐🛑-🛒🛫-🛬🛴-🛶🛷-🛸🛹🤐-🤘🤙-🤞🤟🤠-🤧🤨-🤯🤰🤱-🤲🤳-🤺🤼-🤾🥀-🥅🥇-🥋🥌🥍-🥏🥐-🥞🥟-🥫🥬-🥰🥳-🥶🥺🥼-🥿🦀-🦄🦅-🦑🦒-🦗🦘-🦢🦰-🦹🧀🧁-🧂🧐-🧦🧧-🧿🏻-🏿☝⛹✊-✋✌-✍🎅🏂-🏄🏇🏊🏋-🏌👂-👃👆-👐👦-👩👮👰-👸👼💁-💃💅-💇💪🕴-🕵🕺🖐🖕-🖖🙅-🙇🙋-🙏🚣🚴-🚶🛀🛌🤘🤙-🤜🤞🤟🤦🤰🤱-🤲🤳-🤹🤽-🤾🦵-🦶🦸-🦹🧑-🧝#*0-9‍⃣️🇦-🇿🏻-🏿🦰-🦳󠀠-󠁿©®‼⁉™ℹ↔-↙↩-↪⌚-⌛⌨⎈⏏⏩-⏳⏸-⏺Ⓜ▪-▫▶◀◻-◾☀-★☇-☒☔-☕☖-☗☘☙☚-♯♰-♱♲-♽♾-♿⚀-⚅⚐-⚑⚒-⚜⚝⚞-⚟⚠-⚡⚢-⚱⚲⚳-⚼⚽-⚿⛀-⛃⛄-⛍⛎⛏-⛡⛢⛣⛤-⛧⛨-⛿✀✁-✄✅✈-✉✊-✋✌-✒✔✖✝✡✨✳-✴❄❇❌❎❓-❕❗❣-❧➕-➗➡➰➿⤴-⤵⬅-⬇⬛-⬜⭐⭕〰〽㊗㊙🀀-🀫🀬-🀯🀰-🂓🂔-🂟🂠-🂮🂯-🂰🂱-🂾🂿🃀🃁-🃏🃐🃑-🃟🃠-🃵🃶-🃿🄍-🄏🄯🅬-🅯🅰-🅱🅾🅿🆎🆑-🆚🆭-🇥🈁-🈂🈃-🈏🈚🈯🈲-🈺🈼-🈿🉉-🉏🉐-🉑🉒-🉟🉠-🉥🉦-🋿🌀-🌠🌡-🌬🌭-🌯🌰-🌵🌶🌷-🍼🍽🍾-🍿🎀-🎓🎔-🎟🎠-🏄🏅🏆-🏊🏋-🏎🏏-🏓🏔-🏟🏠-🏰🏱-🏷🏸-🏺🐀-🐾🐿👀👁👂-📷📸📹-📼📽-📾📿🔀-🔽🕆-🕊🕋-🕏🕐-🕧🕨-🕹🕺🕻-🖣🖤🖥-🗺🗻-🗿😀😁-😐😑😒-😔😕😖😗😘😙😚😛😜-😞😟😠-😥😦-😧😨-😫😬😭😮-😯😰-😳😴😵-🙀🙁-🙂🙃-🙄🙅-🙏🚀-🛅🛆-🛏🛐🛑-🛒🛓-🛔🛕-🛟🛠-🛬🛭-🛯🛰-🛳🛴-🛶🛷-🛸🛹🛺-🛿🝴-🝿🟕-🟘🟙-🟿🠌-🠏🡈-🡏🡚-🡟🢈-🢏🢮-🣿🤌-🤏🤐-🤘🤙-🤞🤟🤠-🤧🤨-🤯🤰🤱-🤲🤳-🤺🤼-🤾🤿🥀-🥅🥇-🥋🥌🥍-🥏🥐-🥞🥟-🥫🥬-🥰🥱-🥲🥳-🥶🥷-🥹🥺🥻🥼-🥿🦀-🦄🦅-🦑🦒-🦗🦘-🦢🦣-🦯🦰-🦹🦺-🦿🧀🧁-🧂🧃-🧏🧐-🧦🧧-🧿🨀-🩟🩠-🩭🩮-🿽]/u';
```

embedding the regex this way might save some bytes (rather than building the regex runtime from string representations of codepoints), on the other hand it isn't nice to look at and I don't know if there might be encoding issues on some platforms (like ftp clients that upload "text files" as ASCII)

PS:
I've made the regex with this: https://gist.github.com/rasteiner/013ac027a25fcf1ba6002e68e8a6e8ba

**Comment by rasteiner** [comment]
a workaround for the panel could be to skip the emoji test entirely and just see on the client if there is a matching svg symbol - if not, just show the plain text whatever it is (emoji or not). 

It could actually be useful to be able to put text into the "image" part of an item. Think for example "name initials" if there is no avatar for users. (Kinda like gmail does).

**Comment by bastianallgeier** [comment]
Ha, I found an even simpler solution. We never have unicode characters in our icon names. Just checking for unicode characters is totally fine to detect emojis.
