### ISSUE TITLE
[Panel] Filenames with spaces or special characters cause issues after upload

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#695]
I used the Beta 2 Starterkit and the Nightly build 2018-07-17:

When I upload a file like »Test file.png«, the space in the filename causes errors:

1. When I click on the options button for the image, the context menu is not opened. The console shows this error:

<img width="1447" alt="1" src="https://user-images.githubusercontent.com/15672385/42870574-8083259e-8a78-11e8-88c1-68d0903c0110.png">

2. When I click on the image to open the fileview, this error is shown:

<img width="1446" alt="2" src="https://user-images.githubusercontent.com/15672385/42870583-85fd496e-8a78-11e8-8910-e32a58c23841.png">

If there’s a question mark in the filename, it seems to be recognized as a query in the file view:

<img width="960" alt="questionmark" src="https://user-images.githubusercontent.com/15672385/42929817-75bd495a-8b3b-11e8-9bd3-3e68489cd70d.png">

A tilde (~) in the filename causes this error:

<img width="956" alt="tilde" src="https://user-images.githubusercontent.com/15672385/42929876-9eabc85a-8b3b-11e8-8d63-89c623c31749.png">

**Comment by fvsch** [comment]
I think there are two separate issues:

1. The full-page file view is receiving a URL or URL fragment (file name) which is URL-encoded, but does not decode it before looking at the filesystem.
2. Uploaded file names are kept as-is, and not changed in any way to something more "web-safe".

Personally I believe the second issue is perfectly fine as-is. Kirby could come with an opinionated way to "sanitize" file names, but everyone’s opinion of which characters are okay and which are not is different. (Only ASCII? spaces or not? only lowercase? allow hyphens and/or underscores?) And I see how it could be puzzling for some clients to upload a file named one way, and then having to refer to a different name in their text fields.

I could be useful to have a way to rename the uploaded image though, enabled easily from blueprints.

**Comment by SebastianEberlein** [comment]
> Personally I believe the second issue is perfectly fine as-is. Kirby could come with an opinionated way to "sanitize" file names

I agree with you. In Kirby 2, filenames were always sanitized. This was okay for most of the time. But for one client we had to [disable »sanitize« in the blueprints](https://getkirby.com/docs/panel/blueprints/file-settings#sanitization), because they uploaded PDFs and did not like that the filename was changed to lowercase.

**Comment by bastianallgeier** [comment]
As a first measure I fixed file sanitization on uploads. I agree that we need a client-compatible renaming option again. But I don't really want to fix the white space or special character issue on our end. Those file names will always cause issues on the web and Kirby should not support those characters at all. But something like lower/upper case or other naming schemes could be possible.

**Comment by bastianallgeier** [comment]
I created a separate ticket for this and will close this one: https://github.com/k-next/kirby/issues/750
