### ISSUE TITLE
[Panel] Kirby-Card: Descenders are cut off in text element

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#696]
I used the Beta 2 Starterkit and the Nightly build 2018-07-17:

Since the `.kirby-card-text` element has `line-height: 1` and `overflow: hidden`, the descenders (the parts of letters that extend below the baseline) are cut off:

![s](https://user-images.githubusercontent.com/15672385/42871863-a6e9e7ba-8a7b-11e8-8580-8c6dcaa8f3f9.png)

**Comment by bastianallgeier** [comment]
✅
