### ISSUE TITLE
[Panel] Revert/Save dialog appears when nothing has been changed - confusing

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#697]
When you start dragging, but then reconsider and put the dragged back in its original position you get a "revert"/"save" suggestion at the bottom. This is weird, as nothing has been changed.

**Comment by bvdputte** [comment]
Hmmm, same behaviour with checkboxes. When unchecking a checked item, you get the "revert/save" footer. When you re-check the item you've just unchecked, the "revert/save"-footer persists.

Is this intended? This way I'm assuming something is changed, but actually it's still the same.

**Comment by rasteiner** [comment]
there's already an issue here: https://github.com/k-next/kirby/issues/574 with the beta 3 tag :)
