### ISSUE TITLE
[Panel] Don't display "kirby-box" when tab is empty

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#698]
`.kirby-box` is added in the tab, even if there are no fields. I wondered what that was but it seems to just be an empty container.

![image](https://user-images.githubusercontent.com/927011/42880251-fd36b734-8a93-11e8-94b1-19c192b67adb.png)

My section looks like this:

```yaml
label: My label
type: fields
```

**Comment by bastianallgeier** [comment]
This is the intended behavior: 

![bildschirmfoto 2018-07-24 um 12 07 43](https://user-images.githubusercontent.com/24532/43131798-3547c0fa-8f3a-11e8-8c02-5c557bcc0cee.png)
