### ISSUE TITLE
[Panel] Kirby-List: Better handle long title and info texts

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#699]
I used the Beta 2 Starterkit and the Nightly build 2018-07-17:

I ran into this issue where a very long page title pushes the info text to the right:

<img width="707" alt="1" src="https://user-images.githubusercontent.com/15672385/42886735-9f7fdae2-8aa4-11e8-8830-9ce48d765b94.png">

Then I also checked other edges cases and tested a few CSS adjustments in the dev tools. This is an example where I truncated both the title and the info text with ellipsis. And I also added a `min-width` to the info text so that a date is never truncated:

![v](https://user-images.githubusercontent.com/15672385/42887311-fad5ed40-8aa5-11e8-9777-0bfa294fe371.gif)

But adding a `min-width` for a specific text length was not a good idea and it also caused issues when the list was in a 1/3 or 1/4 column. 

But truncating both the title and the info text with ellipsis seems to be a okay-ish solution, although a 1/4 column might look like this…

<img width="279" alt="2" src="https://user-images.githubusercontent.com/15672385/42887611-a51dfa04-8aa6-11e8-91ee-e51ae7fd608c.png">

**Comment by bastianallgeier** [comment]
I think this is a good compromise. I added it like that.
