### ISSUE TITLE
Panel: Easier input of multiple tags in tag field type

### ISSUE THREAD

**Issue by paulrobertlloyd** [getkirby/kirby#7]
For the tag input field, it’s difficult to enter multiple tags, without tabbing out of the input and back in. I would expect typing a comma, or pressing enter, would automatically convert the last string into a tag, and allow the user to begin entering a new one.

**Comment by distantnative** [comment]
@paulrobertlloyd Just to be clear: Pressing enter at the moment should convert text input to a new tag. Is that not working for you? (typing a comma currently should not trigger anything, so that is expected, but we will consider to add this functionality form v2)

**Comment by paulrobertlloyd** [comment]
@distantnative A-ha! So, I actually thought about using enter as I created this bug, but didn’t think to check if it already worked. It does! Enter actually seems like the right solution… with comma perhaps a nice-to-have additional behaviour.

**Comment by bastianallgeier** [comment]
I'd add comma as well. It always felt nice to have it and it avoids issues when someone actually enters a comma. A tag with a comma should not be possible at all.

**Comment by distantnative** [comment]
Will be part of the next release.
