### ISSUE TITLE
[Panel] Nested fields not working

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#702]
This test works in K2.

**Added to restrant-menu.yml**
<pre>  test:
    extends: fields/test
    label: Test</pre>

**fields/test file**
<pre>
label: Tests
type: structure
fields:
  dish:
    label: Test
    type: text
    width: 1/3
  description: fields/test1
</pre>

**fields/test1 file**
<pre>label: Description
type: text
width: 1/3</pre>

Getting Error 'Illegal string offset 'name'

**Comment by bastianallgeier** [comment]
✅
