### ISSUE TITLE
[Panel] Extend tabs + tab plugins

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#703]
### Extend tabs

I have extended both sections and fields but my blueprint is really big with lots of stuff. It would make sense to be able to also extend tabs.

They could then be reused in other blueprints, but it would also be a bit simpler to only focus on one tab at the time when they contain much data.

### Tab plugins

I've read about section plugins. For larger plugins, to register tabs could also be very useful, dedicate a full tab to a plugin, where you may only need to override the tab `label`.

*Maybe this is two issues. Split them up if you want.*

**Comment by bastianallgeier** [comment]
This is now both possible. Tabs can be extended and there are presets which can also be used in tabs.
