### ISSUE TITLE
Can't save because Class 'Kirby\Cms\InvalidArgumentException' not found

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#705]
If the error message would tell me more, I could probably find the problem.

>The form could not be submitted
>Exception: Error
>Class 'Kirby\Cms\InvalidArgumentException' not found
> Ok

![image](https://user-images.githubusercontent.com/927011/43023259-844cb75a-8c6a-11e8-9276-15defba9cd40.png)

## Update

I found the cause of the error after trial and error.

I had a `checkboxes` field with `required: true` inside a tab that was unchecked when I tried to save.

A much better error message would be:

>The form could not be submitted
>Exception: Error
>The 'my_checkboxes' field is required and needs to be filled in
> Ok

***Don't close this issue! The issue is still the error message***

**Comment by bastianallgeier** [comment]
✅
