### ISSUE TITLE
route::after throws error when going to /panel/login

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#707]
**Inside a plugin:**

All this plugin does is to put the field content of the field `scheduled` in `$field`. It works fine on the site. If it exists, it got set, else it's skipped.

However I get an error in the panel.

```php
<?php
Kirby::plugin('my-name/hello-world', [
    'hooks' => [
        'route:after' => function ($route,$path,$method,$result) {
            $field = $result->scheduled();
        }
    ]
]);
```

>Error
Call to undefined method Kirby\Http\Response::scheduled()

## Solution

Skip this hook if inside the panel automatically.

**Comment by jenstornell** [comment]
I looked at the output of `$result` and it's completely different in the panel compared to outside it.

**Panel**

```php

Kirby\Http\Response Object
(
    [type] => text/html
    [charset] => UTF-8
    [code] => 200
    [headers] => Array
        (
        )

    [body]
```

**Template/snippet**

```php
Kirby\Cms\Page Object
(
    [children] => Kirby\Cms\Pages Object
        (
        )

    [content] => Kirby\Cms\Content Object
        (
            [title] => Home
        )
```

Even the classes is different.

## A workaround

```php
<?php
Kirby::plugin('my-name/hello-world', [
    'hooks' => [
        'route:after' => function ($route,$path,$method,$result) {
            if(!property_exists($result, 'content')) return; // Workaround

            $field = $result->scheduled();
        }
    ]
]);
```

**Comment by bastianallgeier** [comment]
How do you call that custom route in the panel?

**Comment by jenstornell** [comment]
I don't visit a custom route in the panel. I was surpriced that the hook was triggered at all when I tried to login to the panel.

I thought this hook only was triggered on the site and not in the panel.

**Comment by bastianallgeier** [comment]
Ahhh, now I got it. You are right. It should probably not be triggered on any API route.

**Comment by jenstornell** [comment]
@bastianallgeier Another very related problem. When I visited an url that did not exist like `this-url-does-not-work` the error page should appear. Instead it triggered whoops. That's because `$result` in that case is not set.

**So I updated my workaround:**

```php
if(!isset($result) || !property_exists($result, 'content')) return;
```

**Current state of my plugin:**

```php
<?php
Kirby::plugin('jenstornell/scheduled-pages', [
    'hooks' => [
        'route:after' => function ($route, $path, $method, $result) {
            if(!isset($result) || !property_exists($result, 'content')) return; // Workaround

            if(null !== $result->scheduled()) {
                $timestamp = strtotime($result->scheduled());
                if($timestamp != 0 && $timestamp > time()) {
                    throw new Exception('Scheduled page'); // Does not yet work very well
                    #echo new Response(':(', 'html', 404);
                    #die;
                }
            }
        }
    ],
]);
```

**Comment by jenstornell** [comment]
What do you mean with API route? If I create a custom route, you mean it should not be triggered? It's actually really helpful to have it triggered on all the pages, except for the Panel.

### All, except the panel

When using scheduled posts or want to minify the html that needs to be done on all pages. The html minifier also need to minify the html generated by the custom routes for example.

Also the name says `route:after` so we expect it to run after routes, even custom ones.

### About the error page

I wrote before about that content does not exists for the error page, but forget all about that. I deleted that comment as well.

### Solution

If you want to trigger the hook for only core page routes, maybe another hook like `page:after`.

So, right now I have two plugins that depend on that custom routes trigger this hook. In case you want to break it, I hope that you replace it with something else.

Thanks!

**Comment by bastianallgeier** [comment]
After looking at it more closely I think it could be useful in some cases to use the route:before and after hooks in the api as well and it's definitely more consistent to keep them there. But I think it's also important to be able to check in which surrounding the current request is being made. So I added a env attribute to each core route, which can be used in the hooks to check if an action should be executed or not:

```php

<?php
Kirby::plugin('my-name/hello-world', [
    'hooks' => [
        'route:after' => function ($route,$path,$method,$result) {
            if ($route->env() === 'site') {
              $field = $result->scheduled();
            }     
        }
    ]
]);

```

The different env settings are

- site
- api
- panel
- media

**Comment by jenstornell** [comment]
I just wanted to say that this looks totally fine by me. ☺ Nice work!
