### ISSUE TITLE
[Panel] Sorting pages in the One-Pager Example (Starterkit) throws an error

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#708]
<img width="381" alt="bildschirmfoto 2018-07-22 um 13 26 09" src="https://user-images.githubusercontent.com/3930150/43045121-e8896f6c-8db2-11e8-8276-c688f282dfe6.png">

I guess it has something to do with `status: all`.

**Comment by bastianallgeier** [comment]
✅
