### ISSUE TITLE
[Blueprint] Make it clear where to define subpage-templates

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#710]
@texnixe and I had the following discussion on Slack and I think the current solution will result in a lot of confusion. But I have to admit if there are multiple subpage-settings for different parents my idea to declare them in the child blueprint wouldn't work well, too. So any ideas?

<img width="484" alt="bildschirmfoto 2018-07-22 um 13 47 46" src="https://user-images.githubusercontent.com/3930150/43045291-4867e866-8db6-11e8-8b83-764ed4a7218c.png">

IMO the setting can't stay in the `pages`-section declaration because in a lot of scenarios there are multiple of them and in a lot of scenarios they will be declared without utilizing the sections-feature..

**Comment by wottpal** [comment]
Additionally: Setting this in the `pages`-section currently also hides all pages with other templates. In K2 this setting only defines which ones can be newly created, right? I often have subpages with different templates (e.g. imprint, footer, etc) and want them to be shown but not to be created once again.

**Comment by bastianallgeier** [comment]
I thought about this as well and my idea would be that each blueprint can define a list of templates, which it can be converted to. That would be a lot more stable and logic in my opinion. Something like

```
canConvertTo:
 - article
 - something
 - another-thing
```

**Comment by bastianallgeier** [comment]
✅
