### ISSUE TITLE
[Panel] Improve layout of huge cards

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#711]
Maybe increase icon/emoji size, increase text-size, vertically center text 🤷‍♂️

<img width="1271" alt="bildschirmfoto 2018-07-22 um 15 41 43" src="https://user-images.githubusercontent.com/3930150/43046178-ecdf87be-8dc5-11e8-8399-b534e66fc09f.png">

**Comment by bastianallgeier** [comment]
✅ Huge cards are gone for now. Even though I felt very smart with the layout, it's really hard to understand that the card layout changes. I think they should come back as layout option later.
