### ISSUE TITLE
[Blueprint] Allow multiple status-combinations

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#712]
Is it currently possible to add a `pages`-section which shows unlisted & listed pages but not drafts? I would suggest something like:

```yaml
status:
   - listed
   - unlisted
```

**Comment by bastianallgeier** [comment]
We already have a `status: published` option, but I think your idea is actually better.

**Comment by bastianallgeier** [comment]
I'm closing this as we already cover it with the published status.
