### ISSUE TITLE
[Panel] Enable image-replacement with different file-types

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#713]
If we embrace the paradigm of images as data-objects (instead of structure-field with image-pointer inside) it would be helpful if we could replace images with images of another file-type. Because otherwise the editor would have to completely copy all of the content over to a newly uploaded image. An additional warning like *"If you replace with this image, the URL changes."* could be displayed.

I know images can be converted but this is not a very trivial task for most editors I know.

**Comment by wottpal** [comment]
OT: #616 would also improve the UX of this paradigm

**Comment by bastianallgeier** [comment]
This is a duplicate: https://github.com/k-next/kirby/issues/37
