### ISSUE TITLE
[Panel] Improve card layout if neither `title` nor `info` is given

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#716]
<img width="268" alt="bildschirmfoto 2018-07-22 um 16 50 19" src="https://user-images.githubusercontent.com/3930150/43046854-60efd3bc-8dcf-11e8-9366-300994e855d3.png">

**Comment by wottpal** [comment]
I've also noticed that some pixels of the title are shaved off sometimes:

<img width="500" alt="bildschirmfoto 2018-07-22 um 19 10 53" src="https://user-images.githubusercontent.com/3930150/43048147-1ffc8d00-8de3-11e8-8bcf-c364f66bde59.png">

**Comment by bastianallgeier** [comment]
✅
