### ISSUE TITLE
[Panel] Don't show sort-handle for only one listed page 

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#718]
<img width="458" alt="bildschirmfoto 2018-07-22 um 16 58 48" src="https://user-images.githubusercontent.com/3930150/43046944-9bbadd6a-8dd0-11e8-848e-f4431e15682e.png">

**Comment by nilshoerrmann** [comment]
I'm not sure if it's a good idea to hide the handle in this context because its existence highlights the list's "sorting potential": if any of the other pages changes status the user will be able to sort. If this is not desired, shouldn't the pages be unsorted in the first place (`num: zero`)?

**Comment by bastianallgeier** [comment]
I agree with @nilshoerrmann here. I think it's fine like this.
