### ISSUE TITLE
[Blueprint] `preview: false` does not work

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#720]
The [docs](https://www.notion.so/Page-Blueprint-Options-d82ec29690c84ec1b150bafda5fc632c) say there is an option to disable the preview/open link for pages. But it doesn't work for me:

```yaml
options:
  preview: false
```

<img width="98" alt="bildschirmfoto 2018-07-22 um 17 11 37" src="https://user-images.githubusercontent.com/3930150/43047052-528bb734-8dd2-11e8-98f8-78307d9978a1.png">

**Comment by bastianallgeier** [comment]
✅ It's back and better than ever! You can now use the template syntax to create any kind of preview link. I.e.

```
options: 
  preview: "{{ page.parent.url }}#{{ page.slug }}"
```
