### ISSUE TITLE
[Panel] Improve structure-field add-button position when no `title` is given

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#722]
<img width="430" alt="bildschirmfoto 2018-07-22 um 17 27 22" src="https://user-images.githubusercontent.com/3930150/43047240-969bd678-8dd4-11e8-9d6b-c9894ca17ee0.png">

In comparison, this is how a `pages`-section looks without `headline` (btw please unify `title`, `label` and `headline`, nobody can remember this 😅).
<img width="433" alt="bildschirmfoto 2018-07-22 um 17 27 29" src="https://user-images.githubusercontent.com/3930150/43047241-96baae72-8dd4-11e8-8fc4-16c152d5346f.png">

**Comment by bastianallgeier** [comment]
✅
