### ISSUE TITLE
[Blueprint] `default: false` for date-field

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#724]
Currently for me the default-value for a `date` field is automatically set to today even if I've not specified that in the blueprint. Also `default: false` does not change this behavior. Shouldn't the default default (😅) be no value?

**Comment by distantnative** [comment]
Just for a bit of context info: Does that also happen when the field is not set as required?

**Comment by wottpal** [comment]
I've tested it and yes it only happens if `required: true` is set.

**Comment by distantnative** [comment]
Ok, so this is actually intended. If the date field is required, the default for `default` is `today`.

**Comment by distantnative** [comment]
First: Do you disagree with that? Second: If that's fine `default: false` should be added indeed.

**Comment by jenstornell** [comment]
@distantnative I agree that force `today` is not really optimal when field is required. I will tell you a few reasons why I think so.

**Problems**

1. If the date is already set to `today`, it's really hard to know if I as a user set that date or if it was set automatically.
1. If the date is already set, we don't get any indication that it's required. That way it can be missed.

**Solution**

Leave the field empty and indicate that this field needs to be filled in before save with a red border or whatever is used for that. Don't save the page before a date is added.

**Comment by distantnative** [comment]
Removed setting a default when the field is required. Now either the set a default or there is none - as proposed.

✅
