### ISSUE TITLE
[Panel] Optimize Sort-Handle Placement

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#728]
Esp. with smaller viewports or field-widths there is luft nach oben.

<img width="428" alt="bildschirmfoto 2018-07-22 um 18 47 34" src="https://user-images.githubusercontent.com/3930150/43047941-c173a820-8ddf-11e8-8cc6-995d2d05111e.png">
<img width="1096" alt="bildschirmfoto 2018-07-22 um 18 46 00" src="https://user-images.githubusercontent.com/3930150/43047928-a220e2a8-8ddf-11e8-839c-9d59d5bcdae7.png">

**Comment by bastianallgeier** [comment]
✅
