### ISSUE TITLE
[Panel] Weird URL-change on Localhost

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#730]
When I open the panel on localhost (Apache/2.4.33 (Unix) PHP/7.2.6) it always prepends the base-url to the path like:

<img width="240" alt="screen shot 2018-07-23 at 10 08 48" src="https://user-images.githubusercontent.com/3930150/43064939-a0723408-8e60-11e8-8b44-7c01ae31b11a.png">

This is not the case on other domains.

**Comment by bastianallgeier** [comment]
We need to debug this together some more. 

Could you create a simple test.php next to the index.php and add the following:

```php
<?php 

require 'kirby/bootstrap.php';

var_dump(Url::current());
var_dump(Url::index());

```

Let me know what the output is.

**Comment by wottpal** [comment]
`http://localhost:4041/test.php` outputs `string(33) "http://venenpraxis.local/test.php" string(24) "http://venenpraxis.local"` which might be the reason for the error. I have a local Apache installation with an vhost named `venenpraxis.local` in place which is proxied by browser-sync onto localhost during development. Is a fix possible though?

**Comment by distantnative** [comment]
@wottpal still existing in beta 5?

**Comment by bastianallgeier** [comment]
I'm closing it for now. @wottpal feel free to reopen if you run into it again.
