### ISSUE TITLE
[Panel] Textarea too small in structure-field

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#731]
![kapture 2018-07-23 at 10 12 53](https://user-images.githubusercontent.com/3930150/43065094-0cb45bc8-8e61-11e8-9a9f-2fadb386cc49.gif)

**Comment by bastianallgeier** [comment]
It should be auto-sizing. I don't know why this is happening. Never saw it before.

**Comment by johannschopplich** [comment]
@wottpal OT: In "Artzhelfer/in" hat sich ein Fehler eingeschlichen. 😉

**Comment by bastianallgeier** [comment]
@jschopplich nice meta bug report!

**Comment by bastianallgeier** [comment]
✅
