### ISSUE TITLE
[Cms] $site->index()->drafts() should be working

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#733]
In this snippet `site()->drafts()` seems to return an empty collection even though drafts definitely exist.

https://snippets.cacher.io/snippet/20d6cd459e4661201eaf

**Comment by bastianallgeier** [comment]
Well, it actually does what it is supposed to do. It returns the list of direct drafts. Comparable to `site()->children()`. We need `$site->index()->drafts()` though.

**Comment by bastianallgeier** [comment]
✅
