### ISSUE TITLE
Support null as parameter values in \Kirby\Cms\Response constructor

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#734]
Currently, something like this throws a TypeError:

```php
new Response('Body', null, null, [
  'My-Custom-Header' => 'My-Value',
]);
```

It would be quite convenient if the `Response` class would fallback to the default parameter values (e.g. 200 for status code) in this case as well. As the minimum PHP version required to run Kirby is now 7.1, this could be implemented without loosing the benefits of type hinting using [nullable type hints](http://php.net/manual/de/migration71.new-features.php#migration71.new-features.nullable-types).

**Comment by bastianallgeier** [comment]
✅

**Comment by tillprochaska** [comment]
Sorry, I think I’ve been a bit unclear in the initial issue description. Unfortunately, your commit doesn’t really solve this problem… The constructor should look like this (note the `?` preceding the parameter type telling PHP that this parameter may either be of the given type or null):

```php
public function __construct($body = '', ?string $type = null, ?int $code = null, ?array $headers = null, ?string $charset = null) {

    ...

    $this->body    = $body;
    $this->type    = $type ?? 'text/html';
    $this->code    = $code ?? 200;
    $this->headers = $headers ?? [];
    $this->charset = $charset ?? 'UTF-8';
}
```

I think it makes sense to be consistent and allow `null` for all optional parameters, otherwise it might be a bit confusing.

Also, helper methods like `json(…)` or `redirect(…)` should probably support this as well…

**Comment by bastianallgeier** [comment]
Ok, after a long break I finally fixed it :)
