### ISSUE TITLE
[Cms] Render page and return it as HTML

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#744]
For a long time I have wanted a function like this. In Kirby 3 everything has improved, so maybe it can be possible.

## The idea

The function call is really simple, yet very powerful. It should take controller etc into account.

```php
$html = render('projects/project-a', $args);
echo $html;
```

or

```php
$page = render('projects/project-a', $args);
echo pageToHtml($page);
```

## Use cases

Every time we want to get a page HTML outside the normal workflow, it can be helpful.

### Case 1

>In a route:after hook, we can't by a condition visit another page without running some custom render method and then die.

https://github.com/k-next/kirby/issues/743

Now this particular case may be solved with an option to pass the response further down.

###  Case 2

It would be helpful in the preview of template components, in Kirby Component Kit.

https://github.com/jenstornell/kirby-component-kit

### Case 3

Let's say we want to get all meta descriptions from all the pages in a list. Because they are created automatically with a complex method,  we can't just use `$page->meta_description()`, but need to use the real source. Or maybe we want to scan the whole page for HTML errors.

Using file_get_contents is possible, but it's really slow to do because new http requests is required. To instead doing it from the inside would probably be much much faster.

## Workaround in Kirby 2

In Kirby 2 I always came back to this function:

https://github.com/jenstornell/kirby-secrets/blob/master/docs/snippet.md#function-needed

**Comment by rasteiner** [comment]
[`Response::for`](https://github.com/k-next/kirby/blob/master/src/Cms/Response.php#L41) should do what you ask for.

---

edit:
actually, it's even easier. You can do `$page->render()`

Here's an example (config.php):

```php
<?php

return [
    'debug'  => true,
    'routes' => [
        [
            'pattern' => 'source/(:all)',
            'action' => function($path) {
                $html = page($path)->render();
                $html = '<html><pre>' . htmlentities($html) . '</pre></html>';
                echo $html;
            }
        ]
    ]
];
```

**Comment by jenstornell** [comment]
I can confirm that I got `echo page($path)->render();` to work. Amazing!

Thanks @rasteiner ... and @bastianallgeier 

Closing it.
