### ISSUE TITLE
plugin file(s) Methods missing

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#746]
they seem not be implemented. not working when set in a plugin config, nor does a test extist.

https://github.com/k-next/kirby/blob/e3899ba66cd26740a5ff38a8d224e7de0aadc344/tests/Cms/AppPluginsTest.php#L56

**Comment by bnomei** [comment]
related to doc: https://github.com/k-next/kirby/issues/592

**Comment by bnomei** [comment]
could use this plugin to test
https://github.com/bnomei/kirby3-fingerprint

```php
echo $page->image('ukulele.jpg')->fingerprint();
```

**Comment by bastianallgeier** [comment]
✅ should be in the latest nightly build
