### ISSUE TITLE
file.create:after hook: uploaded file not in file collection of parent page

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#747]
I have not worked with hooks too much so far, so bare with me if I overlook something.

I expect the just uploaded file to be accessible via the image collection of its parent page, since it is an :after hook.

```php
<?php

Kirby::plugin('ralfgoeke/hooks', [
    'hooks' => [
        'file.create:after' => function($file) {
          foreach($file->page()->files() as $f) {
            // the new $file is not in this collection and hence will not be renamed :(
            $f->rename(bin2hex(random_bytes(4)));
          };
        },
    ],
]);
```

Is it me doing something wrong or is this a bug?

**Comment by bastianallgeier** [comment]
I think the collection is unfortunately cached in the file's page object. It's definitely a bug.

**Comment by bastianallgeier** [comment]
✅
