### ISSUE TITLE
[Panel] Time field not populated in Safari

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#749]
Left Safari, Right Chrome

![kapture 2018-07-24 at 11 50 37](https://user-images.githubusercontent.com/3930150/43130879-fc3af270-8f37-11e8-8c40-15e4ed1f6886.gif)

Maybe related to #656

**Comment by bastianallgeier** [comment]
Is that the nightly build from yesterday?

**Comment by wottpal** [comment]
Yes. Why it's working for you?

**Comment by bastianallgeier** [comment]
I fixed exactly this. At least I thought so :( Damn, you Safari!

**Comment by wottpal** [comment]
The bug even increased in one of the last nightlies (now only one structure-field item is shown in Safari - still without time).

<img width="646" alt="bildschirmfoto 2018-08-14 um 10 55 40" src="https://user-images.githubusercontent.com/3930150/44082144-b52df970-9fb0-11e8-86d8-ac1920df55f0.png">

**Comment by bastianallgeier** [comment]
✅
