### ISSUE TITLE
[Panel] Panel not updating fields/txt file correctly

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#751]
I created a simple blueprint with a files section and a select field to select images using  the cover template from the starterkit.
<pre>
title: TEST FILE
columns:
  - 1/3: files
  - 2/3: content
sections:
  files:
    headline: Cover Files
    type: files
    template: cover
  content:
    type: fields
    fields:
      coverimage:
        label: Cover Image
        type: select
        options: query
        query: page.images.template("cover")
</pre>

1. When the image is uploaded the select field does not initially display it in the dropdown.  The browser must be refreshed. Tested with Firefox 61.0.1
2. Once the  browser is refreshed the the image is loaded to the field.
3. When the image is selected, the SAVE bar is displayed and the field is written to the txt file.
4. If the image is deleted  the image is still listed in the select field. The browser must be refreshed to remove it from the field.
5. Refreshing the browser clears the select field but the txt file still has the select field data.
6. Additionally, if default: option is used with the select field the select field is loaded with the image but no SAVE bar is displayed to let the user know it has not been saved to the txt file.

**Comment by bastianallgeier** [comment]
✅

**Comment by forestnight** [comment]
The txt file in the contents folder still contains the the field data after the image has been removed.  This could lead to an incorrect output from the php file. (See step 5 above)

**Comment by forestnight** [comment]
This content .txt file still contains the data from the select field after the image has been deleted. (See note 5 above)
