### ISSUE TITLE
[Panel] Don't truncate pasted text when maxlength is set

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#754]
When text is pasted into a textarea with set maxlength, it will be cut off to fit the set character amount.
I think this is a potential pitfall for content editors since it is easy to miss if only a few characters are being cut off silently.
Additionally I personally like to paste longer texts and tweak them until they fit into maxlength.

I think the entire text should be kept on paste. (it needs to fail on save then of course).

**Comment by bastianallgeier** [comment]
I think we don't do this on purpose, but the maxlength setting on the input field is taking care of that :(

**Comment by ralfgoeke** [comment]
Somehow related: #760

**Comment by bastianallgeier** [comment]
✅ we no longer have a hard maxlength restriction.
