### ISSUE TITLE
[Toolkit] add subresource integrity to css and js helper

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#757]
- add dom attribute
- adding CSP rule might be be devs task since merging them with others might be pain

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by bastianallgeier** [comment]
That's already possible: 

```
<?= js('dist/index.js', ['integrity' => ...]) ?>
```

```
<?= css('dist/index.css', ['integrity' => ...]) ?>
```

**Comment by bnomei** [comment]
please reopen. 
attrs only work for css but not for js helper.

https://github.com/k-next/kirby/blob/d6faf8edf1f21dc841ec57ce998bfdfd21178feb/config/helpers.php#L204

```php
echo js('assets/js/index.min.js', ['integrity' => 'hello', 'crossorigin' => 'world']);
```

```html
<script src="..." async="hello world">
```

**Comment by bastianallgeier** [comment]
Argh, sorry! I'll fix it in a second

**Comment by bastianallgeier** [comment]
✅
