### ISSUE TITLE
[Panel] Introduce "soft" maxlength feature for text inputs

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#760]
I often times wished for a "soft" maxlength feature (maybe call it softlength), where it is just clearly indicated that the recommended maxlength is exceeded, but it does not throw an error.
I pretty often need to restrict fields to a certain length, but in some edge cases it just doesn't work and some extra characters need to fit in. In that case I'd rather have my clients knowingly leaving safe territory instead of calling me to ask for more free characters. ;)

This could also work pretty well in those use cases, where it is possible to add kirbytags. Since the counter is "dumb" it counts all the kirbytext markup, but in reality less characters are used.

Any opinions on that?

**Comment by distantnative** [comment]
So for your case the counter and visual warning of the counter turning red would be sufficient? nd you would like to turn of any further validation, correct?

**Comment by ralfgoeke** [comment]
Yes, exactly! 👍

**Comment by bastianallgeier** [comment]
✅ I removed the hard maxlength from the inputs and it actually feels a lot better.
