### ISSUE TITLE
[Cms] Namespaced options as array instead of dot-notation

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#761]
In the options in `config/config.php`, currently what we do is this:

```php
return [
    'jenstornell.robots.content' => 'testing',
    'jenstornell.ga.id' => '12345',
    'jenstornell.ga.debug' => true,
];
```

It works fine, but I'm very tempted to instead write something like this:

```php
return [
    'jenstornell' => [
        'robots' => [
            'content' => 'testing'
        ],
        'ga' => [
            'id' => '12345',
            'debug' => true,
        ]
    ],
];
```

The big difference is that the last version is DRY. If the namespace or the plugin name is changed, I can just change it in one place.

Also plugins with the same author will be nicely grouped together when they use the same namespace.

**Comment by bnomei** [comment]
you do not need prefixes. just plain array like this for example
https://github.com/bnomei/kirby3-security-headers/blob/master/config.php

```php
irby::plugin('bnomei/securityheaders', [
    'options' => [
        'enabled' => true,
        'headers' => [
            "X-Powered-By"              => "", // unset
            "X-Frame-Options"           => "SAMEORIGIN",
            "X-XSS-Protection"          => "1; mode=block",
            "X-Content-Type-Options"    => "nosniff",
            "strict-transport-security" => "max-age=31536000; includeSubdomains",
            "Referrer-Policy"           => "no-referrer-when-downgrade",
        ],
        'nounces' => [],
        'hashes' => []
    ],
    'snippets' => [
        'plugin-securityheaders' => __DIR__ . '/snippets/securityheaders.php',
    ]
]);
```

**Comment by bnomei** [comment]
(removed my post since i missunderstood question) XD

**Comment by bnomei** [comment]
not totally unrelated to DRY is total length of config files. splitting them based on plugin etc. 
but rejoice – for which there is a solution:

https://github.com/k-next/plugins/issues/21#issuecomment-408519265

**Comment by distantnative** [comment]
Related https://github.com/k-next/kirby/issues/604

**Comment by omz13** [comment]
FWIW, in the latest release of my [xmlsitemap](https://github.com/omz13/kirby3-xmlsitemap) I implemented a single-level pseudo-namespace. The [readme](https://github.com/omz13/kirby3-xmlsitemap/blob/master/README.md) gives an example. The more interesting bit of code is below. With some recursion it could probably be extended to support multiple levels of namespace.

https://github.com/omz13/kirby3-xmlsitemap/blob/757b4130ce1ef5547f79c2ecf2a1a187b0618df1/src/xmlsitemap.php#L61-L78
