### ISSUE TITLE
[Panel] Automatically generated slug does not strip dots from filename

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#765]
When creating a new page in the panel and a dot is entered into the title field, it will not be stripped from the slug like other special characters.

<img width="575" alt="bildschirmfoto 2018-07-27 um 10 30 53" src="https://user-images.githubusercontent.com/395617/43310579-3dab09aa-9188-11e8-8257-c3dee68d5430.png">

**Comment by bastianallgeier** [comment]
✅
