### ISSUE TITLE
[Cms] Accept field as crop position

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#766]
I just wrote a [little plugin](https://github.com/medienbaecker/kirby-cropselect) that lets you choose the crop position of an image.

While this does work quite nicely I somehow have to add `->value()` to the field because the `->crop()` method doesn't accept the field alone.

```php
$image->crop(100, 200, $image->cropselect());
```
vs.
```php
$image->crop(100, 200, $image->cropselect()->value());
```

Is it even possible? Or is it something I can solve myself?

**Comment by bastianallgeier** [comment]
✅
