### ISSUE TITLE
[Cms] Change default behavior of `Kirby\Toolkit\Html::tag()`

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#771]
First: I know this could easily be a nice plugin but I truly believe every php-/kirby-beginner could profit of this DRY-way of writing template-code.

There is the [`tag($name, $content, $attrs)`](https://github.com/k-next/kirby/blob/master/src/Toolkit/Html.php#L372) function we can use to easily generate various tags with different attributes and content. Like the documentation says when `$content == ''` the tag is returned with not content - but it's returned. This is only useful in a very limited number of cases but often when it comes to templating you want no surrounding tag at all:

```
<?php if($page->subheading()->isNotEmpty()): ?>
<h3><?= $page->subheading() ?></h3>
<?php endif ?>
```

Implementing this behavior as a default in the `tag()` function would make so much code shorter and more readable (the `tag()`-function finally beneficial): 

```
<?= tag('h3', $page->subheading()) ?>
```
(This example also assumes there is a `tag()` shorthand for `Kirby\Toolkit\Html::tag`)

To still make the old behavior accessible there could be for example an `$allowEmpty` parameter at the end which defaults to `false`.

What do you think?

**Comment by texnixe** [comment]
I actually don't really think HTML template code should be written like this. It might be readable for developers, but probably isn't for designers and the HTML and the logic should be clearly separated.

**Comment by wottpal** [comment]
I think it's a question of taste and we should not write code with people in mind who will never read it. I think for people who spend all day writing template code this solution will be just fine and very readable.

I created a plugin for it but not with the proposed syntax but `$page->field()->tag('h2')` which looks really nice imho.

https://github.com/wottpal/kirby-field-tagger
