### ISSUE TITLE
[Panel] Add getter method for parent page/site/user/file object

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#773]
@wottpal [brought up the need](https://getkirby.slack.com/archives/CBN859614/p1532737664000039) for methods to access the page, site, user or file object to which a field belongs. It’s already possible to access it via the `data` property of `Kirby\Form\Field`.

Current workaround:
```php
'computed' => [
    'title' => function() {
        return $this->data['model']->title()->toString();
    }
]
```

Proposal:
```php
'computed' => [
    'title' => function() {
        return $this->parent()->title()->toString();
    }
]
```

**Comment by bastianallgeier** [comment]
We actually have $this->model() but I will rename it to $this->parent()

**Comment by bastianallgeier** [comment]
I decided to stick to model. That's what we use in sections and fields and which is actually a bit more accurate than just parent.
