### ISSUE TITLE
[Cms] `Collection::first()`, `Collection::last()`, `Collection::nth()` missing

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#778]

**Comment by bastianallgeier** [comment]
No, they are all there: 

- https://github.com/k-next/kirby/blob/master/src/Toolkit/Collection.php#L337
- https://github.com/k-next/kirby/blob/master/src/Toolkit/Collection.php#L407
- https://github.com/k-next/kirby/blob/master/src/Toolkit/Collection.php#L442

**Comment by wottpal** [comment]
Sorry there was another issue in my code which caused them to fail 🤦‍♂️
