### ISSUE TITLE
[Cms & Panel] Implement UI translations

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#78]
- [ ] Plan all strings in Airtable before implementing them
- [x] Finish Exception refactoring first: https://github.com/k-next/starterkit/issues/246
- [x] Implement backend translations
- [x] Implement frontend translations
- [x] Refactor App Translations
- [x] Support short and long locales

----

# Short vs long locales

See long discussion here: https://github.com/k-next/panel/issues/73

@lukasbestle summarized:
1. Only use short language codes without the region specifier. For example `en`, `de` and `sv`.
3. For languages that already have multiple Panel translations (like Portuguese and Spanish), the main region (like Spanish Spanish or Portuguese Portuguese) should have the short code and the other regions should have region-specific codes.
2. The locales can be configured both with short codes and with long codes. If the language isn't translated to that specific locale region, the Panel will fall back to the "short" locale. If the locale region is translated at a later point, it would work out of the box.

## Solution
We are going to go for short + long. Short: if no other is needed. Long: as soon as we have multiple regions/variations.

**Comment by distantnative** [comment]
@bastianallgeier your thoughts on this? At the moment we are making a change towards full locales…

**Comment by lukasbestle** [comment]
Full locales for every language? I don't think that's a good idea (as I wrote before).

**Comment by distantnative** [comment]
So far `en_US` is the only one, but that's why I pinged Bastian on this one.

**Comment by bastianallgeier** [comment]
Let's close this for now and open smaller tickets for additional fixes.
