### ISSUE TITLE
[Panel] Login-View: Allow browser autofill for email and password (Chrome)

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#780]
When I use the build-in password manager in Chrome to save my panel login, the email and password are not autofilled in the login view.

This happens because the password input has `autocomplete="new-password"`, which prevents the autofill.

After I changed the attribute in the Dev Tools (via local overrides) to ~~`autocomplete="password"`~~ `autocomplete="on"` or `autocomplete="current-password"`, the autofill worked as expected.

<img width="1055" alt="login" src="https://user-images.githubusercontent.com/15672385/43403970-b47527e2-9416-11e8-8722-533dc1213133.png">

**Comment by bastianallgeier** [comment]
✅

**Comment by SebastianEberlein** [comment]
@bastianallgeier I forgot to check the MDN docs: `autocomplete="password"` does not exist. It should be `autocomplete="current-password"`

https://developer.mozilla.org/de/docs/Web/HTML/Element/Input#attr-autocomplete

**Comment by bastianallgeier** [comment]
Just fixed it. Thanks for looking it up.
