### ISSUE TITLE
[Panel] Required option gets ignored

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#781]
The required field in blueprints/files/cover.yml is ignored

**Comment by bastianallgeier** [comment]
Duplicate: https://github.com/k-next/kirby/issues/686

**Comment by distantnative** [comment]
Happens to me as well if I set in `site.yml` a field to `required`. Styles are applied but not error gets thrown and field can be saved empty.

**Comment by bastianallgeier** [comment]
✅
