### ISSUE TITLE
Symlinks in devkit vendor folder cause ftp upload error

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#782]
uploading the devkit via ftp to webserver caused error because if symlinks.
i am no composer expert so i did some digging but not sure if it helps.

```
ls -lR ./vendor | grep ^l
=>
generate-defuse-key -> ../defuse/php-encryption/bin/generate-defuse-key

find ./vendor -type l
=>
./vendor/bin/generate-defuse-key
```

this is caused by a getkirby require
```
composer info getkirby/cms | grep defuse
=> 
defuse/php-encryption 2.2.*
```

**Comment by lukasbestle** [comment]
You can delete the `vendor/bin` directory, it is not needed for Kirby to function.

**Comment by bnomei** [comment]
ok. thats good to know. 

you could as well add a post install command for that but maybe that too much to get right for windows and osx. i would love to have a clean setup be default.
wont they come back on an fresh install anyway?

for now i will add a rule to my ftp client.

**Comment by lukasbestle** [comment]
We will get rid of that dependency in the mid-term anyway. :)
