### ISSUE TITLE
[Panel] Login-View: Login button still disabled after email and password autofill (Chrome)

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#783]
Using the nightly build from yesterday, autofill for email and password works as expected in Chrome :)

But the login button is still disabled after the autofill. I have to click or hit the enter key **twice** to login. 

I can also enable the login button just by clicking anywhere on the website:

![login](https://user-images.githubusercontent.com/15672385/43444941-527cf2ba-94a5-11e8-948e-afdbbf1c2f96.gif)

Tested in Chrome on Windows and Mac. Firefox and Safari do not seem to be affected.

**Comment by bastianallgeier** [comment]
✅
