### ISSUE TITLE
SessionCache: Migrate to new session class

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#785]
The [SessionCache](https://github.com/k-next/kirby/blob/master/src/Cache/SessionCache.php) class should be using the `$kirby->session()` instance.

**Comment by lukasbestle** [comment]
Now that I think about it: Maybe we should delete the `SessionCache` class entirely. Caching in the session doesn't make that much sense...

**Comment by bastianallgeier** [comment]
👍 I will remove it.
