### ISSUE TITLE
[Panel] Resize images on upload

### ISSUE THREAD

**Issue by seehat** [getkirby/kirby#789]
Is it possible to integrate clientside resizing on upload, configurable in the blueprint or kirby site configs?

Only the resized image would need to be transfered, which would lead to faster uploads of images and no waste of resources on the server. 

Example would be: https://stackoverflow.com/questions/10333971/html5-pre-resize-images-before-uploading

**Comment by bastianallgeier** [comment]
That's definitely something I'd love to integrate at some point.
