### ISSUE TITLE
[Panel] Toggle field has no default, not settable by other options

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#790]
Sometimes a toggle field (or checkbox) needs to be true by default (opt-out instead of opt-in).
I tried `default: true`, `default: yes`, `default: on` and with custom text `default: aktiviert`. Also I searched the Kirby folder for "toggle" and couldn't find "default" in that context.

**Bonus:** It would be great if the toggle default state could also be based on another toggle (or any field that resolves to boolean). For example a toggle in the blog would define the default state (allow/disallow comments) and each article uses this as default in it's toggle but can be individually overwritten. :grin:

**Comment by bastianallgeier** [comment]
The default value for the toggle field is now fixed. Queries in default values is a next step for 3.x
