### ISSUE TITLE
[Cms] Plugin name errors (composer)

### ISSUE THREAD

**Issue by beebmx** [getkirby/kirby#794]
There are names in the composer package that generates errors to load Kirby.
The error is:

`Fatal error: Uncaught Error: Class 'Kirby' not found in (location) config.php:3 Stack trace: #0`

The error was produced with the `devkit` repository.

To reproduce the error, I created 2 repositories with the same content, but with different names (package name in composer and in the plugin/config.php).

The [Success plugin](https://github.com/beebmx/kirby-plugin-success) has the `composer.json` in devkit like:

```json
{
  "name": "getkirby/devkit",
  "description": "Kirby Dev Kit",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/k-next/kirby"
    },
    {
      "type":"vcs",
      "url":"https://github.com/beebmx/kirby-plugin-success"
    }
  ],
  "require": {
    "getkirby/cms": "3.0.*",
    "success/test": "dev-master"
  },
  "minimum-stability": "beta"
}
```

And the [Wrong plugin](https://github.com/beebmx/kirby-plugin-wrong) has the `composer.json` in devkit like:

```json
{
  "name": "getkirby/devkit",
  "description": "Kirby Dev Kit",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/k-next/kirby"
    },
    {
      "type":"vcs",
      "url":"https://github.com/beebmx/kirby-plugin-wrong"
    }
  ],
  "require": {
    "getkirby/cms": "3.0.*",
    "abcd/test": "dev-master"
  },
  "minimum-stability": "beta"
}
```

I tried many combination of names and some creates a correct plugin but many others not.

**Comment by lukasbestle** [comment]
Probably the same issue as #762. Could you please check if requiring the CMS from your plugins fixes it?

**Comment by beebmx** [comment]
Yes, if the plugin is required without composer it works normal.
But if the plugin is required with composer and has that names creates an error related with:
`Class 'Kirby' not found in`.

**Comment by lukasbestle** [comment]
What I meant is that your *plugin* (installed via Composer) needs to require the CMS package. See the discussion in #762.

**Comment by beebmx** [comment]
Heres is the results.
Now it's working and the steps to do that was the next:
- The `"type": "kirby-plugin",` should be remove to the package.
- The plugin should be placed in the `vendor` directory and not in the `plugin` directory
- The `getkirby/cms` should be in the required section in composer.json

**Comment by lukasbestle** [comment]
I'm closing this in favor of #762. It shouldn't be necessary to remove the `kirby-plugin` type. We will look into this.
