### ISSUE TITLE
[Docs] Plugin composer requirements

### ISSUE THREAD

**Issue by beebmx** [getkirby/kirby#795]
I saw that the composer.json file requires 2 things that is missing in the documentation:

```json
{
    "type": "kirby-plugin",
    "require": {
        "composer/installers": "~1.0"
    }
}

```

The [documentation](https://nnnnext.getkirby.com/docs/guide/extending-kirby/plugin-basics#composer-support) doesn't mention them.

**Comment by lukasbestle** [comment]
Good point. Our [demo plugin](https://github.com/k-next/demo-plugin) already has those lines, but I'm pretty sure that the demo plugin's directory structure is outdated after the latest changes to the plugin API. We should probably update that and reference it from the docs. @texnixe?

**Comment by texnixe** [comment]
I'll create an issue in the docs repo to update the composer.json. But what about the directory structure, @lukasbestle?

**Comment by lukasbestle** [comment]
That‘s probably something for @bastianallgeier.

**Comment by bastianallgeier** [comment]
I'm closing this here as it's something that we need to fix on the site.
