### ISSUE TITLE
[Panel] Stay in the same tab when cycling through pages (with the arrows)

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#797]

**Comment by texnixe** [comment]
Not so sure about this, because it probably depends on the workflow. And what if the subpages do not share the same blueprint and have different tabs and similar tabs but in a different position?

**Comment by wottpal** [comment]
> Not so sure about this, because it probably depends on the workflow.

Yeah pretty sure it does, so I can only speak for myself and in almost any case in the last few weeks this would have been helpful for me. 

> And what if the subpages do not share the same blueprint and have different tabs and similar tabs but in a different position?

I would like to see the following logic to be implemented: If next/prev page has a tab with the same yaml-id then select it; if not select the first. 🤷‍♂️
