### ISSUE TITLE
[Panel] Page model breaks page in panel

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#798]
I just added a model under `models` exactly how I would have done it in K2:

`filialen.php`:

```php
<?php

class FilialenPage extends Page {

}
```

In the page everything works like a charm but when I try to open `filialen` in the panel it says: *The object "filialenpage" cannot be resolved*.

<img width="392" alt="screen shot 2018-08-02 at 09 52 00" src="https://user-images.githubusercontent.com/3930150/43570180-ed6248d0-9639-11e8-8aaa-92454e3b3733.png">

**Comment by bastianallgeier** [comment]
Already solved this yesterday night. Will be in today's nightly build.
