### ISSUE TITLE
Feature Request: $field->default() 

### ISSUE THREAD

**Issue by servicethinker** [getkirby/kirby#80]
This method call suggestion could return the default value of a field.

**Comment by distantnative** [comment]
Is this obsolete with the `->or()` method or do we really want to try to link from the Kirby core to the blueprint methods of the panel -- cause the field's default value only exists in the blueprints, which are at the moment only considered by the panel, not the core itself.

**Comment by bastianallgeier** [comment]
I want to avoid a direct link between blueprints and core methods for now, because the core always has to work as a stand-alone "product" without the panel installation.

**Comment by bastianallgeier** [comment]
BTW: I think the or method works great!
