### ISSUE TITLE
[a11y] Better use <span> instead of <i> for k-icons

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#803]
Just stumbled over it and wanted to put a quick note here.

So, `<i>` stands for _italic_ and does therefore add semantic meaning where it does not make sense. Semantically it would be better to just use good old `<span>` instead.

I don't know if it really has an impact for users relying on assistive technologies, but it certainly will prevent any potential confusion. Sure, no kitten will die by not fixing this, but it will not harm either. ;)

**Comment by bastianallgeier** [comment]
✅
