### ISSUE TITLE
[Cms] Router doesn’t work for root path, should ignore leading slash

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#806]
The router doesn’t seem to work as expected in certain edge cases:

```php
Kirby::plugin('example/plugin', [
    'routes' => [
        [
            'pattern' => 'pattern', // see below for patterns and expected behaviour
            'action' => function() {
                return 'Test';
            }
        ]
    ]
]);
```

#### Patterns matching base path, e. g.  `/(:any)`, `(:any)`, `/`, ` ` (empty string)
* Request: `GET /`
* Current behaviour: Uses Kirby’s default routes
* Expected behaviour: Return `Test`

#### Patter with leading slash, e. g. `/test`
* Request: `GET /test`
* Current behaviour: Uses Kirby’s default routes
* Expected behaviour: Return `Test`

**Comment by bastianallgeier** [comment]
✅
