### ISSUE TITLE
[Panel] Two fields with a headline

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#807]
I was not sure what to call this issue. Rename it if needed.

In my panel I have two fields next to each other. Both share the same label. That's not possible so I skipped the labels and added a headline. Ofcause it looks weird because a headline is larger than a label.

I don't know the solution, I don't even have a suggestion for the solution, but this is what it looks like:

***The "label" can be longer than this, even span over the two columns, just like a headline.***

![image](https://user-images.githubusercontent.com/927011/43641404-d79ce48e-9723-11e8-8f55-729a7f1ef03b.png)

**Comment by lukasbestle** [comment]
Hm, but why do the fields share the same label? There must be *some* difference between them.

**Comment by jenstornell** [comment]
In this case it's a year interval.

**Comment by texnixe** [comment]
But certainly it should still indicate via label that it's something from-to? Wouldn't be clear to me without the corresponding labels, let alone for screen readers.

**Comment by lukasbestle** [comment]
For example you could do something like this: "Year (from)" and "Year (to)"

**Comment by texnixe** [comment]
And you could also make this a custom group of fields like the address field in today's life stream, if you want. Then you could also add a dash in between, to visually group them a little bit more, add a small headline in addition to the labels etc.

**Comment by jenstornell** [comment]
@texnixe Your last advice is what I have in mind. Too much text everywhere for many fields looked bloated.

Thanks both!
