### ISSUE TITLE
[Panel] Width broken with Beta 4

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#808]
`width: 1/2` is broken only in the latest release.

**Nightly 2018-08-01**

![image](https://user-images.githubusercontent.com/927011/43644376-cb7b983e-972e-11e8-8837-35600ee5fedc.png)

**Beta 4**

![image](https://user-images.githubusercontent.com/927011/43644345-b512e354-972e-11e8-80df-338bf20598a6.png)

**Comment by bastianallgeier** [comment]
That's intended in narrow columns.
