### ISSUE TITLE
[Panel] Fields is required, but I can still save

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#809]
Fields is required, because I don't have any fields. Yet I can save the page. While it may be correct it feels a bit weird.

What is fields required for?

![image](https://user-images.githubusercontent.com/927011/43644497-344b6da8-972f-11e8-8804-fa5e0ea1b86e.png)

**Comment by bastianallgeier** [comment]
It just means that you setup the fields section incorrectly. The save event should probably not be triggered in that case.

**Comment by bastianallgeier** [comment]
✅
