### ISSUE TITLE
[Panel] Use specialized cursors for drag and drop actions

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#814]
When dragging elements like file, pages etc. around we see a `pointer` cursor most of the time. I think we could improve user experience by using dedicated cursors.

There are basically 2 different types of cursors, which would be suitable:

- `grab` and `grabbing`: From my point of view, these look fine and literally resembling the action of "grabbing" something to drag it around. They might seem a bit confusing for some users however, as they are often used for panning like in map web apps like Open Street Map, Google Maps or even for sliders. Those need a fallback value of `pointer` for Edge, as it does not support these cursors.
- `move`: The classical way giving users a hint that something can be moved around. Though not as sophisticated as the grabbing cursors, they might be better understandable. On the other hand, the grab cursors looks more similar to the regular `pointer` cursors than the `move` cursor and are IMHO less distractive.

See also: <https://developer.mozilla.org/de/docs/Web/CSS/cursor>

**Comment by bastianallgeier** [comment]
I actually already implemented this. It's just not working properly on cards when you hover over another card. But otherwise it's done.
