### ISSUE TITLE
Kirby::instance()->file($tag->value, $tag->parent()) returns null

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#818]
https://github.com/k-next/kirby/blob/43d09153448d74e804dcd2eff92b153d7c9076bb/config/tags.php#L99

And then we cannot set a caption on the field of the file but only inside the tag itself

**Comment by bastianallgeier** [comment]
How do you use the image tag in this case? I'm not entirely sure why it returns null for you.

**Comment by tristantbg** [comment]
I tried to create a plugin that add srcset automatically :
https://github.com/tristantbg/oracles/edit/master/www/site/plugins/oracles/index.php

**Comment by bastianallgeier** [comment]
I'm really sorry, but I still don't really understand the problem. Could you try to explain some more?

**Comment by tristantbg** [comment]
Sorry for not answering fast enough !

In fact the problem concerns the image tag itself when you try to add an image in KirbyText `(image: ...)`

You can try by adding any image in a textarea and test if `$tag->file` is null or not :

https://github.com/k-next/kirby/blob/1ee464f8219cea23db7126146d6b9564f6f11d65/config/tags.php#L99
```
$tag->file = Kirby::instance()->file($tag->value, $tag->parent());
var_dump($tag->file);
```

In my case it returns NULL all the time and I can't access the caption field of the file itself.

Hope it is more clear !

**Comment by bastianallgeier** [comment]
I finally found what the issue is all about :) Should be fixed now
