### ISSUE TITLE
[Cms] Bring `isEmpty()` and `isNotEmpty()` to collections

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#822]
This happend to me a lot when I started writing Kirby templates and even nowadays from time to time: When I want to check if a collection is empty or not I do it like `$pages->isEmpty()` / `$pages->isNotEmpty()` and then spend quite a long time debugging my code 🤦‍♂️. This is because the field-methods are so super convenient and easy to use. I think implementing the same for collections would be beneficial for PHP-/Kirby-newbies and would feel very kirbyish as well.

What do you think guys?

**Comment by bastianallgeier** [comment]
I like the idea!

**Comment by bastianallgeier** [comment]
✅
