### ISSUE TITLE
[Cms] Shorthand inverted field methods

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#825]
https://forum.getkirby.com/t/inverted-result-in-a-collection/10878

I wanted to do something like this (see the ! character):

```php
foreach(!$pages->scheduled() as $item) {
}
```

Instead of remember two methods, remember one. But by the nature of how it works, the above will not work.

I think the same thing happends in the core:

```php
$page->address()->isEmpty();
$page->address()->isNotEmpty();
```

### Solution

This idea is not mine but from Jim, but I really like it.

Maybe implement a shorthand by an argument like this:

```php
$page->address()->isEmpty();
$page->address()->isEmpty(false);
```

Instead of remember two methods, remember one.

**Example:**

```php
if($page->address()->isEmpty(false)) {
  echo 'This field contains something';
}
```

Maybe it can be used with other kind of methods as well.

### Sidenote

In my plugin I use this like in a pagesMethod like this:

```php
'pagesMethods' => [
        'scheduled' => function($match = true) {
            if($match)
                return $this->filterBy('scheduled', true);
            return $this->filterBy('scheduled', '!=', true);
        }
    ],
```

**Comment by bastianallgeier** [comment]
isEmpty returns a boolean, so `if (!$page->title()->isEmpty())` will work perfectly fine.

**Comment by jenstornell** [comment]
@bastianallgeier I see now that I shouldn't have "mixed pears and apples". Sorry about misleading it.

### A collection is different

A pagesMethod returns a collection. That's why the below does not work.

```php
foreach(!$pages->scheduled() as $item) {
}
```

Now, I don't know if you have implemented pagesMethods, but instead of the above that fails it's possible to do it like this:

```php
foreach($pages->scheduled(false) as $item) {
}
```

In my case it returns all the pages that is not scheduled. That's instead of a implementing a new `notScheduled` method.
