### ISSUE TITLE
[Cms] Port Collection::sortBy from latest toolkit version

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#832]

**Comment by lukasbestle** [comment]
Probably not from the v2 version as I made further improvements. I think that [this commit](https://github.com/k-next/kirby/blob/af16dffd098c3d15def3419559dac66845cb2c39/src/Collection/Traits/Sorter.php) should be the latest implementation.

PS: In the commit history I saw that [this commit](https://github.com/k-next/kirby/commit/458078acbd1abcc3433d14baa2e0571b5afd926f#diff-7fd8fee6163f68032ad155d4ed2548fb) reverted the change. Do you remember why that was?

**Comment by bastianallgeier** [comment]
@lukasbestle I don't remember to be honest. I now reimplemented it, but remove the toArray method call to avoid running callbacks for each item in the array. This is one of the methods that is really crucial when it comes to performance. We need to keep this in mind and see if we can further enhance it.

**Comment by lukasbestle** [comment]
Alright. :)
In case sorting breaks again, please assign the respective issue to me.
