### ISSUE TITLE
[Panel] select field not working in fieldset component

### ISSUE THREAD

**Issue by TimOetting** [getkirby/kirby#835]
I extended the address field plugin example by Bastian with a select field. 

```
panel.plugin("demo/address", {
  fields: {
    address: {
      props: {
        label: String,
        value: Object,
        required: Boolean,
      },
      data: function () {
        return {
          fields: {
            street: {
              label: "Street",
              type: "text",
            },
            zip: {
              label: "Zip",
              type: "number",
              width: "1/4"
            },
            location: {
              label: "City",
              type: "text",
              width: "3/4",
            },
            category: {
              label: "Category",
              type: "select",
              options: {
                one: "First",
                two: "Second",
                three: "Third",
              }
            }
          }
        }
      },
      methods: {
        input: function (data) {
          this.$emit("input", data);
        }
      },
      template: `
        <k-fieldset :fields="fields" v-model="value" @input="input" />
      `
    }
  }
});

```

The select field throws the error "this.options.forEach is not a function" and is not displayed correctly.

![screenshot 2018-08-06 11 44 05](https://user-images.githubusercontent.com/5142881/43710014-b06673f6-996e-11e8-923d-b473520507d1.png)

**Comment by TimOetting** [comment]
no Error message, but also not really working with an radio field:

![screenshot 2018-08-06 12 07 47](https://user-images.githubusercontent.com/5142881/43710930-6f218bbc-9971-11e8-8e84-4f63b3f08b51.png)

**Comment by TimOetting** [comment]
The date field inside a fieldset doesn't work correctly, too. Instead of starting as a blank Date field it has the current time prefilled. In another test it also did not store the date value until I manually changed it once.

**Comment by bastianallgeier** [comment]
That's not really a bug. The options need to be defined as an array of objects: 

```
category: {
    label: "Category",
    type: "select",
    options: {
        { value: "one", text: "First"},
        { value: "two", text: "Second"},
        { value: "third", text: "Third"},
    }
}
```

We sanitize this in the backend, when options are defined via blueprints, so simple arrays keep on working, but when you reuse the input components, you have to do the hard work of writing the full objects. 

The date issue could be related to a select input issue I fixed in today's nightly build.

**Comment by TimOetting** [comment]
Is there a method that takes care of the object conversion? For example, I used the `Blueprint::extend()` method in the php part of my custom field to get the extended blueprint fields working. Maybe there is something similar that I could use for all the option fields?

**Comment by distantnative** [comment]
You can use pure Javascript:

```javascript
let options = {
  one: "First",
  two: "Second",
  three: "Third",
};

let array = [];

Object.keys(options).map(function(key) {
   array.push({ text: options[key], value: key });
});
```

**Comment by bastianallgeier** [comment]
@TimOetting sorry for the massive delay, but this slipped under the carpet. 

You can use our `Options::factory()` in a field

```php
return Kirby\Form\Options::factory(
    $options,
    $fieldProps,
    $model
);
```

This will make sure that the options array ends up nicely. This will also take care of converting option queries and option api settings if you give it all the field props as second parameter and the model is correct. 

You can also have a look at kirby/config/fields/mixins/options.php for more ideas around the implementation.
