### ISSUE TITLE
[Cms] Support for multiple panel css files

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#840]
To have multiple panel css files does not work today. Something like this:

```php
return [
    'panel' => [
        'css' => [
            'panel-brand-css',
            'my-next-css-file.css',
        ]
    ],
];
```

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#41](https://github.com/k-next/ideas/issues/41).
