### ISSUE TITLE
[Panel] Files layout cover does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#842]
```text
hero:
  label: Hero
  type: files
  layout: cover
  multiple: false
```

Layout cover does not work. Instead the file/files are shown in a list.

**Comment by REHvision** [comment]
It's the same syntax as with files sections (i.e. `layout: cards`)

**Comment by jenstornell** [comment]
@REHvision Yes, you are correct. I don't know where I got `cover` from.

✔️
