### ISSUE TITLE
[Panel] Add remove icon

### ISSUE THREAD

**Issue by olach** [getkirby/kirby#844]
In the icon set we have this `add` icon:
<img width="26" alt="add" src="https://user-images.githubusercontent.com/1300644/43766321-719456b0-9a32-11e8-91cf-8c580d62b2ce.png">

I suggest we should add a complementary `remove` icon:
<img width="26" alt="remove" src="https://user-images.githubusercontent.com/1300644/43766407-a2cdf2e0-9a32-11e8-9de2-353d17184570.png">

This icon could be useful to use in some plugins. Maybe also a solution to #843?

**Comment by distantnative** [comment]
✅
