### ISSUE TITLE
[Panel] Use files field with file templates?

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#846]
Would it be a good idea to also introduce file templates in the files field (like it's now only with files sections)?

Of course the question is if the files field should assign the template to any selected file or only allow selecting of certain templates.

**Comment by bastianallgeier** [comment]
Yes, that's on the todo list.

**Comment by bastianallgeier** [comment]
Duplicate https://github.com/k-next/ideas/issues/61
