### ISSUE TITLE
[Cms] Allow setting name in PHPMailer functions like `replyTo`, `to`, `cc`,..

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#848]
In a lot of `PHPMailer`s functions you can not only set an address (like done in `Kirby\Email\PHPMailer`) but also a name as the second parameter. 

http://edd.wp-a2z.org/oik_api/phpmaileraddreplyto/

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#42](https://github.com/k-next/ideas/issues/42).
