### ISSUE TITLE
[Panel] Files field is loosing its content when changing page-url

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#849]
The selected images/files of the new files field are completely empty after changing the page-url. You need to re-select them.

**Comment by bastianallgeier** [comment]
I can't reproduce this anymore.

**Comment by christianschley** [comment]
I'm sorry that i need to tell you, that the bug is still there (watch the gif) in yesterdays nightly built.

![bug-min](https://user-images.githubusercontent.com/25037153/45764855-f3890f80-bc33-11e8-8dbf-8dccab4a4ed0.gif)

Im using this blueprint section:

header:
  type: fields
  fields:
    headerbild: 
    label: Headerbild
    type: files
    layout: cards

Google Chrome - MacOS Mojave

**Comment by bastianallgeier** [comment]
Ahhhh, that's what you meant by changing the page url. Ok, I will double-check.

**Comment by bastianallgeier** [comment]
I know what's happening. Unless you hit save, the selection is only stored in local storage with a cache id that is created by the page url. If you change that url all form changes in local storage will no longer be linked correctly. I guess we either need to automatically save the changes before you change the url, or we need to fix the links after the url has been changed.

**Comment by christianschley** [comment]
But i saved the changes (selected image) before i changed the slug

**Comment by bastianallgeier** [comment]
Urgs, that's not good.

**Comment by robinscholz** [comment]
I can reproduce the issue in a fresh install of the Beta V6 Starterkit with the following code added to `project` blueprint:

```
 cover:
    type: files
    query: page.images
```

**Comment by bastianallgeier** [comment]
✅
