### ISSUE TITLE
[Panel] Toggle Field switches back to »off« state on second save 

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#850]
I used the Beta 4 Starterkit and the latest nightly build:

A toggle field is set back to the »off« state when I save the page a **second time** via `CMD + S`. (Although there are no changes to save.)

![toggle](https://user-images.githubusercontent.com/15672385/43836116-91b0e4da-9b14-11e8-8b5a-0fe879c23b8c.gif)

**Comment by bastianallgeier** [comment]
Very likely related: https://github.com/k-next/kirby/issues/866

**Comment by bastianallgeier** [comment]
✅
