### ISSUE TITLE
[PHPMailer] Enable setting `CharSet` (important)

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#853]
I had to add the following line to `Kirby\Email\PHPMailer` to get German Umlauts work like expected:

```php
$mailer->CharSet ="UTF-8";
```

Maybe this should be the default anyway so you could just set it 🤷‍♂️

**Comment by seb-celinedesign** [comment]
Duplicate of #826 ?

**Comment by wottpal** [comment]
I guess just setting `CharSet` to `UTF-8` by default would solve all our problems. @bastianallgeier should we close one of both issues?

**Comment by seb-celinedesign** [comment]
Email with template needs also the content-type: text/html header

**Comment by bastianallgeier** [comment]
✅
