### ISSUE TITLE
[Panel] Don't show position-selector when changing status if pages are sorted with `sortBy`

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#858]
Does this make sense?

**Comment by bastianallgeier** [comment]
That's not really possible. You should use zero based sorting in this case.

**Comment by wottpal** [comment]
Silly question: How to do that? `num: zero` in the pages-section does not work and I couldn't find it in the new docs. (Related #710)

**Comment by bastianallgeier** [comment]
You can set the numbering mode per blueprint like this: 

```
num: zero
```
