### ISSUE TITLE
[Cms] $page->depth() is null

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#859]
I'm on the page `/projects/trees-and-stars-and-stuff`. On `var_dump($page->depth());` I get this:

>object(Kirby\Cms\Field)#384 (1) { ["depth"]=> NULL }

I expected it to have depth at some level.

**Comment by texnixe** [comment]
Works for me, have you tested with the latest beta 4 nightly build?

> users/me/htdocs/beta-4/site/templates/project.php:5:int 2

**Comment by jenstornell** [comment]
I thought I had, but I guess not. It works now. Thanks!
