### ISSUE TITLE
Thumb: Allow custom filename or crop values

### ISSUE THREAD

**Issue by flokosiol** [getkirby/kirby#860]
For the [Focus Plugin](https://github.com/flokosiol/kirby-focus/tree/k-next) I need to set custom thumb filenames to force a re-generation of the thumbnail when the x and y coordinates change, but all other options like width, height or quality stay the same. Filenames look like this (60 and 40 are the focus coordinates):

```
original-filename-320x640-60-40-q80.jpg
```

In Kirby 2 the `thumb()` methods has an option `filename`.  In Kirby 3 this is not possible at the moment.

## Possible solutions

1. Re-introduce the filename option like in Kirby 2

2. Don't [whitelist the anchor values](https://github.com/k-next/kirby/blob/master/src/Cms/Filename.php#L199) for the crop options in `Kirby\Cms\Filename::crop()`. This would be my preferred solution, because I could pass the coordinates as `$options['crop]` values, which would be a very clean solution, without messing around with the filename.

I's pretty should this could also be solved by overriding the `file::url` component in the plugin. But I think this will be done by other plugins, too – e.g. to use an external image optimizer. And it might lead to conflicts.

**Comment by flokosiol** [comment]
If you tell me your preferred way how to solve this, I could do it and send you a PR.

**Comment by bastianallgeier** [comment]
Sorry, it took a while to wrap my head around this. Not whitelisting the crop options is the best and simplest idea in my opinion. I just removed the code for it. You can now pass pretty much anything as crop value. The only limitation is that Str::slug is applied, but I think that should work fine for your case.

**Comment by flokosiol** [comment]
No problem. Awesome, thanks. That was the last problem to solve. 

Now it‘s time for me to migrate the ImageMagick stuff and the Focus plugin is ready for K3. 🚀💪🏼
