### ISSUE TITLE
[Http] Support streaming in Kirby\Http\Response::download()

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#862]
While the `download(…)` method works well in most cases, however is not optimal for larger files as the current implementation will read the complete file into memory before sending it to the client, likely causing the servers memory limit to be exceeded. Streaming files to the client would solve this, although I’m not sure how complicated it would be to implement this with the current setup.

**Comment by lukasbestle** [comment]
We could use PHP's [`fpassthru()`](http://php.net/manual/en/function.fpassthru.php) function, which does exactly that. Of course the `Response::download()` method would then need to return a class instance without the response body but with just a reference to the file path.
