### ISSUE TITLE
panel file rename does not allow entering minus-char

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#863]
viewing file in panel. selecting title. entering new name with `-` will strip away minus.

**Comment by bnomei** [comment]
this also seem to relate to changing the url. maybe the slug or verify method does not allow `-`?

**Comment by texnixe** [comment]
At least `Str::slug()` removes a leading dash (`-`):
```
$string = '-hallo-emmy';
echo Str::slug($string);

//result: hallo-emmy
```

**Comment by bnomei** [comment]
in `my-fancy-file-title` or `this-should-be-an-url` all `-` will be removed.

**Comment by texnixe** [comment]
Yep, I just tested `Str::slug()`, don't know yet what happens in the Panel. Guess this happens in the Panel JS

**Comment by bastianallgeier** [comment]
The leading minus is still truncated but in the latest nightly you can enter dashes everywhere else again.
