### ISSUE TITLE
[Panel] checkboxes field should ignore invalid value

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#864]
i had in my blueprint a checkboxes field with a query (filter structure from $site) and query value set to `{{ structureItem.id }}`. i edited some content pages in panel, clicking checkboxes.
then i changed my mind and with nightly build i did `{{ structureItem.title.slug }}`. and refreshed panel page in browser.  but all content pages with checkboxes that still have the `id` value stored and i am getting invalid option errors for when trying to save new slug values.

i fixed this by removing the data in the txt files manually, but i guess the panel should just silently ignore when editing and on update remove an option if it can not find it anymore in the blueprint.

**Comment by bastianallgeier** [comment]
✅
