### ISSUE TITLE
[Panel] Cards should truncate too long filenames

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#865]
... instead of breaking layout. the lists view can do that already.

![screen shot 2018-08-09 at 19 06 05](https://user-images.githubusercontent.com/3265642/43914213-7fb166bc-9c07-11e8-8175-98450bc45382.png)

**Comment by nilshoerrmann** [comment]
This issue also happens with long titles in page cards. Please don't truncate the content but allow word wrapping. Even with links it's better to force a break than to cut off characters.

**Comment by bastianallgeier** [comment]
✅ 

![bildschirmfoto 2018-08-14 um 16 07 08](https://user-images.githubusercontent.com/24532/44096696-2f73a2cc-9fdc-11e8-94a2-2fd4b20aa756.png)
