### ISSUE TITLE
[Router] Accept all HTTP methods for home page, too

### ISSUE THREAD

**Issue by mzur** [getkirby/kirby#867]
As of the beta-4, the router listens to all HTTP methods for a page [except for the home page](https://github.com/k-next/kirby/blob/7ca56c6e1a2dea7b9bc18abb7466cdc207d4741e/src/Http/Router.php#L113-L119). I don't think this is intentional as all pages should show the same behavior.

You can test this by sending a POST request to the home page. It will throw the exception "No route found for path...".

**Comment by johannschopplich** [comment]
Thanks for posting @mzur as I encountered the same problem.

For example a contact form on the index page which I use can't be submitted successfully.

**Comment by bastianallgeier** [comment]
✅
