### ISSUE TITLE
[Router] Respond with correct error codes

### ISSUE THREAD

**Issue by mzur** [getkirby/kirby#868]
I believe the router should respond with an error code 405 [here](https://github.com/k-next/kirby/blob/7ca56c6e1a2dea7b9bc18abb7466cdc207d4741e/src/Http/Router.php#L105) and with code 404 [here](https://github.com/k-next/kirby/blob/7ca56c6e1a2dea7b9bc18abb7466cdc207d4741e/src/Http/Router.php#L130). I'm happy to send a PR for this if you are ok with the idea. I'm not sure how to implement this properly, however. I tried throwing a `\Kirby\Exceptions\NotFoundException` but this did not affect the response code.

**Comment by lukasbestle** [comment]
I'm not sure about the first one. `HTTP 405` would mean that the path is correct but just the method not accepted for that path. Doesn't quite fit. But I also don't have an idea which code would fit better. 404 and 500 are both not ideal either.

Throwing one of our Exceptions should actually affect the response code. But maybe the Exception is caught somewhere else where it doesn't affect it. @bastianallgeier?

**Comment by bastianallgeier** [comment]
✅ The router is now responding with an InvalidArgumentException on the first issue. But I choose 400 as response code. The other one is a simple Exception with a 404 code.
