### ISSUE TITLE
[API] Rethink auth tokens

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#87]
@lukasbestle on this: https://github.com/k-next/kirby/issues/10

**Comment by lukasbestle** [comment]
For reference: My JSON Web Tokens idea in our private `v3` Slack channel would be a solution for this as well. But of course it's rather complex and also requires good crypto libraries (meaning: PHP 7.2+ only if we want to implement it properly).

**Comment by bastianallgeier** [comment]
@lukasbestle will work on a session solution.

**Comment by bastianallgeier** [comment]
✅
