### ISSUE TITLE
[Cms] Components in config does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#870]
### Why I did not like core components in Kirby 2

In Kirby 2, I did not like components because if one plugin used a component, it was blocked for the next plugin who wanted to use it.

### Kirby 3 seems to have solved it, almost

In Kirby 3 the structure is much different. In the config file we can very easily set up routes, hooks etc. However we can't setup components in the config file. If we could, multiple plugins could use the same component. Look at the config below.

```php
return [
    'components' => [
        'response' => function (App $kirby, $output) {
            $output = brutallyCompress($output);
            $output .= myOtherPlugin($output);
            return $output;
        }
    ]
];
```

The difference is that without touching the plugins, we can control the order of things here.

**In my Kirby Html Minifier, I want to decouple it, to not hijack the response component.**

**Comment by bastianallgeier** [comment]
This would only make sense for the response component. Not for the other components.
