### ISSUE TITLE
[Cms] $field->exists() missing

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#871]
In K2 it was possible to use isNotEmpty() to check if a toggle field existed.  This does not work in K3.  So looked for $field->exists() and it is missing.

**Comment by bnomei** [comment]
you could do a `$page->blueprint()->fields()->find('fieldname')` in theory, but if you have data in yaml thats not part of the blueprint that **might** not work.

**Comment by bastianallgeier** [comment]
✅

**Comment by distantnative** [comment]
@forestnight:
>Added this to the default.php in starterkit for the structure in the form page.  It is ignoring show() when it is set to false or the field does not exist.
show is a toggle field added to the form.yml structure.
```php
....
foreach($page->structure()->toStructure() as $pagecontent): 
echo nl2br("\nvalue of show is "), $pagecontent->show(); //no error here if does not exist.
 if($pagecontent->show()->exists() ){ //tried isNotEmpty() here with same result
 	echo nl2br("\nshow exists as "), $pagecontent->show();
 	if($pagecontent->show()->isFalse()){echo "show is false";}
}
 endforeach 
  </div>
....
```

**Comment by bastianallgeier** [comment]
✅
