### ISSUE TITLE
[Panel] New Plugin Type Page-Action

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#872]
<img width="470" alt="bildschirmfoto 2018-08-11 um 18 11 50" src="https://user-images.githubusercontent.com/3930150/43993698-0ad2570c-9d92-11e8-9f6b-2b6801a6ce43.png">

**Comment by jenstornell** [comment]
Will each plugin have an own menu or one menu for all plugins?

**Comment by wottpal** [comment]
> Will each plugin have an own menu or one menu for all plugins? 

Good question, maybe depending on the viewport width. What would speak against having them bundled in a dropdown is that would create the need for a nested dropdown if the plugin itself is a dropdown.

**Comment by bastianallgeier** [comment]
Wouldn’t it be best for users to include those actions in the settings menu?

**Comment by wottpal** [comment]
> Wouldn’t it be best for users to include those actions in the settings menu?

Yeah why not. This would have the nice side-effect to be accessible from PageSections as well.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#43](https://github.com/k-next/ideas/issues/43).
