### ISSUE TITLE
[Panel] Don't use the same favicon on the panel and on the docs

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#876]
Because of the favicon, I often having trouble to know where I am. One of the tabs is the docs and the other tab is the panel.

![image](https://user-images.githubusercontent.com/927011/44020934-bc49bc4e-9ee3-11e8-9840-3fbe7dd1e707.png)

I'm not sure if the panel icon should change or if the docs icon should change. Maybe just put a color on one of them?

**Comment by bastianallgeier** [comment]
We will have a different one for the website.
