### ISSUE TITLE
[Cms]  Issue 871 still not working

### ISSUE THREAD

**Issue by forestnight** [getkirby/kirby#877]
Added this to the default.php in starterkit for the structure in the form page.  It is ignoring show() when it is set to false or the field does not exist.
show is a toggle field added to the form.yml structure.
<pre>
....
foreach($page->structure()->toStructure() as $pagecontent): 
echo nl2br("\nvalue of show is "), $pagecontent->show(); //no error here if does not exist.
 if($pagecontent->show()->exists() ){ //tried isNotEmpty() here with same result
 	echo nl2br("\nshow exists as "), $pagecontent->show();
 	if($pagecontent->show()->isFalse()){echo "show is false";}
}
 endforeach 
  </div>
....
</pre>

**Comment by wottpal** [comment]
I guess Bastian just forgot to include some fixes here in the latest nightly :)

**Comment by distantnative** [comment]
Reopened 871 instead to have more context.
