### ISSUE TITLE
Kirby: user role blueprints for custom fields 

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#88]
Instead of `user.txt` use roles as user file names, e.g. `admin.txt`, `editor.txt`. Those can also define then which user fields blueprint has to be loaded. The default blueprint (e.g. with only email/id and language) could be `visitor.txt`.

**Comment by bastianallgeier** [comment]
I love how consistent this is with the way we handle pages!!

**Comment by distantnative** [comment]
Has been added to the `develop` branch.
