### ISSUE TITLE
[Panel] Figure out a way to be triggered by events from other fields

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#880]
**For example:** Maybe my field should be dependent of another field, or the title. When the title changes, my field should change a preview of something.

That may be possible already, but probably with a hackish approach.

**Comment by joernroeder** [comment]
looking for something similar – listening for reorder of child pages and reload my field on changes and found this issue closed without explanation. Is this already solved?

**Comment by lukasbestle** [comment]
@joernroeder See #882.

**Comment by joernroeder** [comment]
@lukasbestle thx!
