### ISSUE TITLE
[Plugins] Convenient way of editing/getting/listening values of other fields in plugins

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#882]
In my first try of the [Revisions plugin working with Git](https://github.com/k-next/plugins/issues/2) I really would like to have some more core-functionality in JS regarding other fields on the current page, esp.:

* [ ] Changing the value of another field, @rasteiner did this already by hand: https://github.com/k-next/plugins/issues/2#issuecomment-409647582
* [ ] Getting the current value of another field (the current saved value as well as the edited one)
* [ ] Listening to value changes of another field
* [ ] Get a list of all fields in the current page (https://github.com/k-next/kirby/issues/883)

**Comment by jenstornell** [comment]
Maybe related? https://github.com/k-next/kirby/issues/880

**Comment by wottpal** [comment]
> Maybe related? #880

I guess it's more than related, it's the same functionality we are look for, right? Should we keep (only) this issue as it is more general?

**Comment by bastianallgeier** [comment]
I closed @jenstornell ticket. They are the same and this one has a nice todo list :P
