### ISSUE TITLE
[Plugin] `$this->model()->blueprint()` returns empty collection in plugin

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#883]
When used in a computed property-method of a field.

**Comment by bastianallgeier** [comment]
Do you have a link to the plugin?

**Comment by wottpal** [comment]
This gives an error: `Failed to fetch`. (Btw shouldn't it be redundant to *fetch* blueprint-fields because they were just loaded by the panel)

```php
<?php

Kirby::plugin('anonymous/blueprint-not-working', [

  'fields' => [

    'blueprintFields' => [
      'computed' => [
        'blueprintFields' => function () {
          return $this->model()->blueprint()->fields();
        },
      ]
    ]

  ]

]);
```

```js
panel.plugin("anonymous/blueprint-not-working", {
  fields: {

    blueprintFields: {

      props: {
        blueprintFields: Array,
      },

      template: `
      <kirby-field>

      {{blueprintFields}}

      </kirby-field>
      `
    }

  }

});
```

**Comment by bastianallgeier** [comment]
I think you are creating an endless loop there.

**Comment by wottpal** [comment]
> I think you are creating an endless loop there.

Damn it, think you're right. A JS-only way for gathering all available fields on the current page would be totally fine as well :) Sounds like another todo for #882? 😅

**Comment by bastianallgeier** [comment]
Yep, we need a way to access the other blueprint settings for the current page. I'm closing this for now.
