### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#884]
@bastianallgeier asked on Slack to post our most annoying issues with the beta: ours is Composer.

We are working as designers and are used to a git workflow that helps us track changes on our sites. Our usage of git is design-centric: we use submodules to reuse templates, styles, scripts and share stuff we need in different projects. In other CMS, it's usually possible to include plugins as submodules as well. While I know a lot of developers who hate submodules, they have worked reliably for us over the last years.

The good thing about git is that there are different GUI, like Tower, that take away the burden to handle version control in the terminal. I know, developers swear by the terminal: but if you are a visual person, it might just not be your tool of choice.

With Composer, there is another elephant in the room: we can still track our changes in git, we can also add Kirby and its plugins as submodules. But any change we pull using git requires us to run `composer update` as well. This is nothing we should be required to do. It's convenient for developers, and it certainly has its benefits from a programmer's point of view: from our frontend designer's point of view, it's just cumbersome. I'd expect to be able to just get a version of Kirby and its plugins that just works via git without additional steps.

### Possible solutions:

1. A special branch that includes the `vendor` folder. This might work for the main Kirby install but I'm not sure all plugin developers will follow suit.
2. Kirby doing the Composer installs and updates silently under the hood without requiring any user interaction.

I know that Github also provides the option to upload bundles with releases that you can download as zip files. But this takes away the benefits of using git and isn't a good option in our eyes.

**Comment by wottpal** [comment]
For reference:

* https://getkirby.slack.com/archives/CBN859614/p1532265163000033
* https://getkirby.slack.com/archives/CBN859614/p1534204161000122

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#112](https://github.com/k-next/ideas/issues/112).
