### ISSUE TITLE
[CMS] Page in variable doesn't return reliable ->status() info.

### ISSUE THREAD

**Issue by bvdputte** [getkirby/kirby#886]
Consider:

```php
$kirby->impersonate('admin.email@domain.com'); // admin.email@domain.com is a registered admin user
$p = page('events/reasons-to');
var_dump($p->status());
if( $p->status() === "listed") {
  $p->changeStatus("unlisted");
} else {
  $p->changeStatus("listed");
}
var_dump($p->status());
var_dump(page('events/reasons-to-copy')->status());
```

returns:
```
"listed"
"listed"
"unlisted"
```
while I would've expected:
```
"listed"
"unlisted"
"unlisted"
```

Is this a "variable caching/cloning" side effect?

**Comment by bastianallgeier** [comment]
That's actually intended. Page models in Kirby 3 are immutable. That means that you need to assign it to a new variable to get the new mutated object:

```php
$kirby->impersonate('admin.email@domain.com'); // admin.email@domain.com is a registered admin user
$p = page('events/reasons-to');
var_dump($p->status());
if( $p->status() === "listed") {
  $p = $p->changeStatus("unlisted");
} else {
  $p = $p->changeStatus("listed");
}
var_dump($p->status());
var_dump(page('events/reasons-to-copy')->status());

```

**Comment by bvdputte** [comment]
I'm not familiar with "immutability", but shouldn't `changeStatus` return a new instance with the mutated state then?

**Comment by bvdputte** [comment]
I tried to wrap my head around this, and how to cope with this but I just can't figure it out.

E.g.: How do we check if a title has been changed when Page models are immutable? I've tried the following and got unexpected (for me) results:

```php
$newTitle = (string)rand();
var_dump($newTitle);
kirby()->impersonate("kirby");
$xxx = page("blog/content-in-kirby");
var_dump($xxx->title());
$xxx->changeTitle($newTitle);
var_dump($xxx->title());
$yyy = page("blog/content-in-kirby");
var_dump($yyy->title());
die;
```

And this was the output:
```
/var/www/test/sandbox.test/site/templates/events.php:5:string '2144078236' (length=10)
/var/www/test/sandbox.test/site/templates/events.php:8:
object(Kirby\Cms\Field)[289]
  public 'title' => string '1139649089' (length=10)
/var/www/test/sandbox.test/site/templates/events.php:10:
object(Kirby\Cms\Field)[289]
  public 'title' => string '1139649089' (length=10)
/var/www/test/sandbox.test/site/templates/events.php:13:
object(Kirby\Cms\Field)[289]
  public 'title' => string '1139649089' (length=10)
```

All show the "old" value. I would've expected the 2 last to reflect the changed title?
And as you said in your reply, even assigning it to a new variable as the last one didn't work? This is inconsistent to me?

Edit: 
_Just to be clear: the title is getting changed in the textfile (as expected)._

**Comment by texnixe** [comment]
If you do it like this:

```
$newTitle = (string)rand();
kirby()->impersonate("kirby");
$p = page("blog/content-in-kirby")->changeTitle($newTitle);

var_dump($p->title());
```

Or like this:

```
$newTitle = (string)rand();
var_dump($newTitle);
kirby()->impersonate("kirby");
$x = page("blog/content-in-kirby");
var_dump($x->title());
$y = $x->changeTitle($newTitle);

var_dump($y->title());
```
It works as expected. The point here is that we assign the return type of `changeTitle()`to a new variable.

**Comment by bastianallgeier** [comment]
Sorry for being a bit too technical with the immutable term. What it means is that the object is not directly modified but those actions always return a fresh new object with those changes. This helps us to avoid any side effects within the page objects and you can use those two objects separately and for example still have access to the old values from the old object. We use the same in hooks to provide old and new objects in the functions.
