### ISSUE TITLE
[Panel] Ask for name when creating new user

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#889]
If optional or mandatory doesn't matter for me but I'm pretty sure the minority of users goes to the *Users* panel-site and fills in a name afterwards. And in every plugin I have to fallback to the mail-address which looks too long and a little shabby in tables.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#44](https://github.com/k-next/ideas/issues/44).
