### ISSUE TITLE
Replace dash separator for visibility flag numbers with something else (dot?)

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#89]

**Comment by bastianallgeier** [comment]
I had the dot in a very very early version of Kirby and it always resulted in problems on Mac because the folder was afterwards interpreted as file.

**Comment by texnixe** [comment]
Hm, seems that both Grav and Statamic are using dots… don't know if they have problems with it. To me, it seems more logical to use a dot, as opposed to the dashes in the UID. So many people have problems with not being able to use titles that start with a number because of the dashes.

**Comment by distantnative** [comment]
This certainly is one of the problems of v2 that has caused a lot of discussions.

**Comment by bastianallgeier** [comment]
It would be a pretty big step if we do this. Technically it's easy, but to move from Kirby 2 to Kirby 3 would be a pretty painful process.

**Comment by distantnative** [comment]
I see that point. But then again I do not see a good alternative to avoid all the problems caused with titles starting with a number in the current system. And if we want to change the system, it should rather happen from v2 to v3 instead of 3 to 3.1 or so. What are others' perspectives on this? @texnixe @lukasbestle

**Comment by jenstornell** [comment]
I agree with @distantnative and @texnixe. If not now, when should it be changed? I don't think there is a non breaking way around it.

If there is a problem with the dot character, maybe use an underscore?

**Comment by lukasbestle** [comment]
Yep, I agree as well. There have been many questions about this and a lot of confusion in the forum with the current implementation. We should have a system that can distinguish between the sorting number and the UID correctly at all times. How that would look like is the other question.

**Comment by lukaskleinschmidt** [comment]
I think changing the way the folders are named is also not necessarily a breaking change. You could check the dirname for the chosen separator and could distinguish which naming convention is used right now.

https://forum.getkirby.com/t/visible-and-invisible-pages/5236
