### ISSUE TITLE
[Panel] Current Version Number

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#891]
It would be desirable to let the panel display the current Kirby and panel versions, e. g. in a footer or within the dropdown in the main navigation. This information helps discovering outdated installs and should be present on all panel pages (at least for admins).

**Comment by bastianallgeier** [comment]
Yep, this is definitely coming back together with the license code. We had that in v2 as well.

**Comment by nilshoerrmann** [comment]
Great, thanks!

**Comment by bastianallgeier** [comment]
✅
