### ISSUE TITLE
[Panel] Sticky labels in Structure Fields

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#892]
There was a short thread about this on Slack already: the introduction of labels in each row in the collapsed view of structure fields is causing a lot of repetition and uses way too much space in my eyes:

![bildschirmfoto am 2018-08-15 um 14 56 36](https://user-images.githubusercontent.com/25466/44149196-6fa07338-a09b-11e8-8e95-5c79d082e2f0.png)

It would be great to:

- have one sticky* header (think of this as a table)
- maybe ignoring this header if there is only one field in the structure

---

\* `position: sticky` work really well nowadays as long as you wrap it in a `@support` statement to prevent layout issues on old Android versions.

**Comment by nilshoerrmann** [comment]
To clarify this a bit:

1. Browsers without support for `position: sticky` should get the current layout. It's verbose but descriptive in a positive way.
2. Browsers with support for `position: sticky` should get a layout with a single sticky header and no extra labels.
3. Structure fields with a single field only don't need either label or header because the field name gives the needed context.

In cases 2 and 3, labels might still be needed in the markup and should only be hidden visually in order to be more accessible. Not sure about best practices and user expectations here when thinking of assistive technology.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#111](https://github.com/k-next/ideas/issues/111).
