### ISSUE TITLE
[Cms] Plugins can't override core pagesMethods

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#893]
I can create pages methods, but when creating one with the same name as the core, I can't override it.

In the below example I have two exact same pages methods where `listed` does not work but `listed2` works. If it matters, the filterBy is filtered by a page method that is also in the code.

```php
Kirby::plugin('jenstornell/schedule', [
  'pageMethods' => [
    'isScheduled' => function() {
      $timestamp = strtotime($this->content()->schedule_until());
      
      if($timestamp && $timestamp > time())
        return true;

      return false;
    }
  ],
  'pagesMethods' => [
    'listed' => function () {
      $collection = $this->filterBy('isListed', '==', true);
      $collection = $collection->filterBy('isScheduled', '!=', true);
      return $collection;
    },
    'listed2' => function () {
      $collection = $this->filterBy('isListed', '==', true);
      $collection = $collection->filterBy('isScheduled', '!=', true);
      return $collection;
    }
  ]
]);
```

Only `listed2` works as expected.

```php
print_r(page('projects')->children()->listed());
print_r(page('projects')->children()->listed2());
```

**Comment by bastianallgeier** [comment]
This is not a bug and has been the same in v2. If you really want to extend pages and overwrite existing methods, you need to use a page model. Page methods are injected with magic callers and will only kick in, if a method does not exist. It's technically not possible to solve this in another way.
