### ISSUE TITLE
[Panel] Move language switcher into top bar.

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#895]
The language switcher looks nice there but with many fields or content on panel pages it's not possible to know which language you are in or switch the language without scrolling all the way up.

I would suggest to move this back into the top bar as it was in K2.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#45](https://github.com/k-next/ideas/issues/45).
