### ISSUE TITLE
[Panel] Default file path in kirbytag needs language code to work

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#896]
When dragging an image from a files section into the text-area the kirbytag looks like
`(image: page/subpage/image.jpg)`.

But when the site uses languages the image doesn't show up on the page.

The image shows up when manually adding the language slug to the file path in the kirbytag:
`(image: en/page/subpage/image.jpg)`.

This shouldn't be necessary and I guess it's a bug.

**Comment by distantnative** [comment]
@REHvision could you test if it gets solved by adding the following lines to `kirby/config/tags.php` at line 100:

```php
if ($tag->file === null) {
    $tag->file = Kirby::instance()->file($tag->value);
}
```

So after that it should look like:

```php
$tag->src  = Url::to($tag->value);
$tag->file = Kirby::instance()->file($tag->value, $tag->parent());

if ($tag->file === null) {
    $tag->file = Kirby::instance()->file($tag->value);
}

if ($tag->file) {
    $tag->src     = $tag->file->url();
    $tag->alt     = $tag->alt     ?? $tag->file->alt()->or(' ')->value();
```

**Comment by REHvision** [comment]
Mhm, doesn't seem to work in either the main or secondary languages.
I applied the changes, cleared the media folder, removed cookies. Latest Beta 5 Nightly.

Tell me, if I can help further!

**Comment by bastianallgeier** [comment]
✅
