### ISSUE TITLE
[Cms] Upload type validation on Windows broken like in v2?

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#897]
From the v2 Toolkit repo:

> I noticed avatars weren't uploading on a Windows web server due to the "image" type not being returned despite MIME checking returning "image/***" correctly. I narrowed it down to Windows returning "*.tmp" as the filename for the upload instead of the actual filename.

We should check if there is the same issue in v3.

**Comment by bastianallgeier** [comment]
✅
