### ISSUE TITLE
[CMS] Kirbytext: (link: …) without text attribute results in two <a> tags

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#898]
I used the latest Beta and the latest nightly build:

When I add a link without a `text:` attribute like this `(link: https://getkirby.com)`, the parser creates two `<a>` tags:

![frontend](https://user-images.githubusercontent.com/15672385/44254400-035f9f00-a203-11e8-9ccd-2364c85622cf.png)

<img width="615" alt="panel" src="https://user-images.githubusercontent.com/15672385/44254404-065a8f80-a203-11e8-9d35-8f9d47bfb53a.png">

**Comment by bastianallgeier** [comment]
✅
