### ISSUE TITLE
Ui: Date field - Years should be more flexible

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#90]
Currently it is not possible to enter a year in the far past or future. Let's say we want to use the date field for something like birthdays. I think it should be possible to enter the year completely free if needed. Probably would be fine to make this option available via a setting, since this is an edge case and the current implementation is perfect for most use cases.

**Comment by distantnative** [comment]
I could imagine setting the year range displayed via blueprint (e.g. `10`for +/-10 years) with an option like `custom` (in lack of a better idea for a name) that adds a text input field instead of the select input.

**Comment by ralfgoeke** [comment]
That would do the trick I guess. :)

**Comment by bastianallgeier** [comment]
This is now implemented :D
