### ISSUE TITLE
[CMS] Multilanguage: $page->modified() error

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#900]
I used the latest Beta Starterkit and the latest nightly build:

With multiple languages set up, `$page->modified()` returns an error.

<img width="1092" alt="bildschirmfoto 2018-08-17 um 12 36 30" src="https://user-images.githubusercontent.com/15672385/44262210-7fb1ac80-a21a-11e8-9db0-3c8fc492df8f.png">

**Comment by bnomei** [comment]
`contentFile()` could take a language param to solve this quickly

**Comment by distantnative** [comment]
```php
  public function contentFile(string $languageCode = null): string
    {
        if ($languageCode !== null) {
            return $this->root() . '/' . $this->intendedTemplate() . '.' . $languageCode . '.' . $this->kirby()->contentExtension();
        }

        // use the cached version
        if ($this->contentFile !== null) {
            return $this->contentFile;
        }

        // create from template
        return $this->contentFile = $this->root() . '/' . $this->intendedTemplate() . '.' . $this->kirby()->contentExtension();
    }
```

`contentFile()` does already take a language param. Problem is that `modified` right now does not pass any on.

**Comment by bastianallgeier** [comment]
✅
