### ISSUE TITLE
[Panel] Multilanguage: Translated URL does not show up in Modal and Notification

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#901]
I used the latest Beta Starterkit and the latest nightly build:

I translated the URL `/projects` to `/projekte` and then one of the projects. But in the modal it still says `/projects`. The notification does not show the translated URL at all.

![1](https://user-images.githubusercontent.com/15672385/44262581-cfdd3e80-a21b-11e8-8513-f69640922bd1.jpg)

![2](https://user-images.githubusercontent.com/15672385/44262584-d1a70200-a21b-11e8-8204-9429404f5c99.jpg)

**Comment by bastianallgeier** [comment]
✅
