### ISSUE TITLE
[Panel] No route found for path: "pages/artiklar/smslan" and request method: "PATCH"

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#903]
![image](https://user-images.githubusercontent.com/927011/44264775-29496b80-a224-11e8-932b-72e293886a6f.png)

All of a sudden I can't save the page because of above.

**Comment by jenstornell** [comment]
I've found out the cause of this problem already. I visited the page with `/` as separator instead of `+`.

**I thought it had to do with a route collision. Maybe just enhance the error message here.**

>The page "pages/parent/child" not found.

**Comment by distantnative** [comment]
So is this actually a bug/an issue?
I think "No route found for path" is the more precise error message, since when entering a pattern that does not matches the pages route, the router doesn't even know whether you want a page or a user etc.
