### ISSUE TITLE
[Panel] Scrollbar on error modals, when not needed

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#904]
![image](https://user-images.githubusercontent.com/927011/44264862-73cae800-a224-11e8-9e77-9c46b0a3240a.png)

I use Windows, Chrome, Nightly 2018-08-15

**Comment by bastianallgeier** [comment]
Please don’t submit issues for the experimental new blueprint version. It’s buggy as hell. I only uploaded it to Slack because some people wanted to play with it.

**Comment by bastianallgeier** [comment]
You should watch the screencast first and stay with last nightly build so long

**Comment by jenstornell** [comment]
@bastianallgeier This is the "old" nightly 2018-08-15 version. I picked it from Notion, not from Slack.

**Comment by bastianallgeier** [comment]
✅
