### ISSUE TITLE
[Panel] Image field does not work as expected

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#905]
## What does not work

Examples that did not work

### Example 1

```php
$thumb = $page->hero()->toFile()->crop(200);
```

### Example 2

```php
$thumb = $page->image($page->hero())->crop(200);
```

### Saved as yaml list

Even if I've set `multiple: false` it saves the image as yaml in the content file. That's not really needed. It creates some overhead when trying to get it out.

**I would prefer:**

- Single image = `string`
- Multiple images = yaml list / `array`

### Saved with path

The filename is save as a path like `artiklar/sidan/96449.jpg` instead of just `96449.jpg`. It also make the examples above fail.

## Workaround

To get around these issues we need to do something like this for it to work:

```php
$first = Yaml::decode($page->hero())[0];
$first = basename($first);
$thumb = $page->image($first)->crop(200);
echo $thumb;
```

**Comment by rasteiner** [comment]
imho the "file**s**" field should remain a list, even when it contains only a single file. That's what I would expect from a field which type is in plural form. It's like the structure field, you expect it to have a list in any case. 

I would rather have also a "file" field, that only accepts a single file and also has a simpler UI (like a dropdown?). 

## other workaround
in a plugin:
```php
<?php

Kirby::plugin('maybe/core', [
    'fieldMethods' => [
        'toFiles' => function($field) {
            $files = array_map(function($id) {
                return [
                    'filename' => basename($id)
                ];
            }, $field->yaml());
            $collection = Kirby\Cms\Files::factory($files, $field->parent())
            return $collection->filterBy('exists', true);
        }
    ]
]);
```

in a template:

```php
<?php if ($image = $page->hero()->toFiles()->first()): ?>
  <?php echo $image->crop(200) ?>
<?php endif; ?>
```

**Comment by jenstornell** [comment]
When putting it that way, I agree with @rasteiner. A `files` should probably always contain a list. I also would not mind to have a simplified `file` field.

**Comment by jenstornell** [comment]
The solution from @rasteiner only worked in cases where the thumbnail was already generated before. It could not generate new thumbnails.

**Here is my workaround for this problem**

In a plugin:

```php
<?php
Kirby::plugin('maybe/core', [
    'fieldMethods' => [
        'toImage' => function($field) {
            $first = basename(Yaml::decode($field->parent()->hero())[0]);
            return $image = ($field->parent()->image($first));
        }
    ]
]);
```

In a snippet:

```php
<?= $page->hero()->toImage() ? $page->hero()->toImage()->crop(420) : ''; ?>
```

**Comment by rasteiner** [comment]
@jenstornell that problem [was solved](https://getkirby.slack.com/archives/CBN859614/p1534517862000100?thread_ts=1534511459.000100&cid=CBN859614) in the above snippet :) 
You probably missed that because... slack.

**Comment by jenstornell** [comment]
@rasteiner Ahh, yes I missed it, thanks!

**Comment by bastianallgeier** [comment]
✅
