### ISSUE TITLE
[Cms] Basic image optim of thumbs

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#906]
@wottpal and me discussed this in slack reacently. maybe consider making basic binary logic core. installing the binaries could still be dev task.

this seems nice btw:
https://github.com/spatie/image-optimizer

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#46](https://github.com/k-next/ideas/issues/46).
