### ISSUE TITLE
Panel: Author Field - display Name

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#91]
Currently the email is used in the author field. Guess it would be nice if it would show the name of the user instead. Could be an optional setting though, of course.

**Comment by bastianallgeier** [comment]
That field is still very MVPish. In my wildest dreams we will have a really nice autocompleter with image+name+email for each user.

**Comment by distantnative** [comment]
Let's start your "wildest dreams": https://github.com/k-next/panel/pull/246 (though I'd like your take on the design and a good way for a "clear this field" button)

**Comment by distantnative** [comment]
![kapture 2017-11-05 at 16 54 52](https://user-images.githubusercontent.com/3788865/32416488-26867f2e-c24a-11e7-8175-ac18233335af.gif)

**Comment by distantnative** [comment]
Will be in the next alpha release
