### ISSUE TITLE
[Cms] drafts in drafts

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#910]
i tried to create a tree of subpages calling `$page->createChild(...)` recursively. that fails and **removes all files (txt, images, ...)** unless parent is not a draft. seems like you can not have drafts in drafts.

**Comment by bastianallgeier** [comment]
I just checked and it works as expected for me. Could you paste the code that you used to run this?

**Comment by bastianallgeier** [comment]
@bnomei ping :)

**Comment by bnomei** [comment]
@bastianallgeier sorry busy with working on another project. i have time to try again DO or FR this week.

**Comment by bastianallgeier** [comment]
I'm closing this for now as I cannot reproduce it. Feel free to reopen if you run into it again.
