### ISSUE TITLE
[Cms] mass changing status messes up sorting number

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#912]
i wanted to list code generated drafts. but this results in incorrect sorting numbers and that messes up the `$page->visible()->count()` (expected 4, got 3). 

- maybe because i am calling `createPage` before my loop? 
- maybe files are not writen to disk yet? 
- or is just `$page->index()` not updated? (https://github.com/k-next/kirby/blob/551a97b501c4116119ffb79487f894f43f5c01d4/src/Cms/PageActions.php#L375)

```
1_test-1
2_test-2
2_test-3
3_test-4
```

```php
foreach($page->drafts() as $pchi) {
        kirby()->impersonate('kirby');
        $pchi->changeStatus('listed');
        sleep(1); // does not help
    }
```

**Comment by bnomei** [comment]
@distantnative so any idea whats wrong?

**Comment by bnomei** [comment]
i used more crptic names and made a mistake above. to this should 
```
1_test-1
2_test-2
2_test-3
3_test-3
```
EDITED: this does fix it. setting the number.

```php
    $c = $page->children()->count();

    foreach($page->drafts() as $pchi) {
        $c++;
        kirby()->impersonate('kirby');
        $pchi->changeStatus('listed', $c);
        sleep(1);
    }
```

**Comment by distantnative** [comment]
Haven't had the chance to look at it - but clearly sounds like a bug.

**Comment by bnomei** [comment]
maybe the `$page->drafts()` model/cache/index does not get updated when a page is listed. so my foreach loop finds same but now already listed page in drafts again.

**Comment by bastianallgeier** [comment]
Yep, sounds like a cache issue

**Comment by bastianallgeier** [comment]
✅
