### ISSUE TITLE
[Cms] serialization of closures (in cache)

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#914]
i tried to store a pages collction within an array into the plugin cache. but serialization of closures is not allowed. maybe wrap these like laravel does?

```php
$pluginCache->set('data', [
    'pages' => $page->index()
]);
```

https://stackoverflow.com/questions/13734224/exception-serialization-of-closure-is-not-allowed
https://github.com/jeremeamia/super_closure (uses eval() but protected)
https://github.com/opis/closure (does not use eval)

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#47](https://github.com/k-next/ideas/issues/47).
