### ISSUE TITLE
[Panel] Can't save on live server, always logged out

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#922]
When on localhost I can save. On a live server I can't.

The problem is that I get logged out instantly. I figured that out by refreshing the page. I've tried in different browsers and even on different computers (all PC), but the same issue accurs.

I'm not using any plugins that could mess this up, and it's working on localhost.

**Screenscast**

You don't see it but I click CTRL + S here for save. Mouse click does not help as I'm logged out.

**Version:** 3.0.0-beta-4.5

![save](https://user-images.githubusercontent.com/927011/44326070-d1e11080-a45a-11e8-9bc3-4e4d2b25d4be.gif)

**Comment by Alzy** [comment]
did you ever resolve this? What finally fixed the issue? I've been having this problem on my server as well

**Comment by bastianallgeier** [comment]
@Alzy that was the caching issue you mentioned in the forum, right?

**Comment by Alzy** [comment]
Yes! Turned out to be a caching issue with Siteground hosting
