### ISSUE TITLE
[Panel] I can't have an empty blueprint that is not in use

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#924]
I created an empty blueprint. I thought I'll fill it in later. Because I did not use it, I thought it was not loaded by the system. Somehow it was loaded even if not in use and I got this message:

>The section "kitchensink" could not be loaded: The property "title" is required

When I removed the empty blueprint that was not in use it worked again. What is the reason for loading a blueprint that is not used?

**Comment by bastianallgeier** [comment]
✅
