### ISSUE TITLE
[Panel] Giant list of items

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#925]
Sometimes, all of a sudden I get a giant list of items. It's not endless but it's very long. In this case my filled in two rows disappeared.

It's not the first time I see this. This time I used a structure field but I also have seen it in files section so I guess it's some hickup with Vue.

I don't know steps to reproduce, feels random.

*When I save everything goes back to normal again*

![image](https://user-images.githubusercontent.com/927011/44387729-96137d00-a526-11e8-8484-923a634a1f1c.png)

**Comment by jenstornell** [comment]
Now I got it again with files. It seems like it has something to do with the tabs. As I always need to reload the page to get the correct setup of tabs, it seems to mess it up when in a tab that does not exists, something like that.

![image](https://user-images.githubusercontent.com/927011/44388556-a9bfe300-a528-11e8-8bc2-43168af55935.png)

**Comment by bastianallgeier** [comment]
✅ I think it should be fixed. Feel free to reopen if it appears again.
