### ISSUE TITLE
[Panel] Structure outside click modal creates confusion

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#926]
We add a structure field item. Then we don't write anything into it, just click outside to cancel the operation.

### Cancel did not cancel operation

What happends is we get a modal asking us what to do. While it may be logical correct it can create confusion. The first thing I clicked on was cancel to cancel the operation. But that did not happen. Instead I cancel the modal that. Outside click again and I got the modal again.

### Discard is not dangerous

Clicking "Discard" feels very dangerous, but in fact it's not dangerous at all. That's because we have not written a single character yet.

### Not just me

I made a try to convert a site to Kirby 3. My girlfriend tried to help me move some content from Kirby 2 to Kirby 3. All of a sudden she said:

>What happened? I don't know what I did but I got an error message. What should I do? I pressed cancel, but I can't get rid of the popup. I don't want to discard anything.

So, she did the exact same mistake as I did or still do.

#### 1. Cancel if nothing enterd

If nothing has been entered in the fields and click outside, just cancel the operation.

#### 2. Add an add button

With an add button, it would be very clear that we can add the item with a click of the add button and an outside click would cancel it. Or just have buttons for both add and cancel in the item.

![modal](https://user-images.githubusercontent.com/927011/44388922-bc86e780-a529-11e8-9caa-c67ec5ac68ea.gif)

**Comment by ralfgoeke** [comment]
I personally don't like that "clicking outside to close pattern" at all. I know, that it is a de-facto standard, but I still consider this as anti-pattern. Anyone else with me?

**Comment by jenstornell** [comment]
I've been thinking more about it and the more I think about it, the more I want buttons to make it really clear what is happening. Also because we only add one element at a time, these buttons would not take up much screen space.

**I just picked a random screenshot (not Kirby) to show what I mean:**

![image](https://user-images.githubusercontent.com/927011/44644903-f64a6900-a9d5-11e8-8b4d-07c1fdf6b631.png)

Should be a cancel button as well.

**Comment by philipmarnef** [comment]
Related to this: 
- if you add an item, then discard it, the page state is still in 'unsaved changes' even though nothing changed
- if you add an item you have to hit save twice – I think the first save closes the dialog, the second saves the page.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#48](https://github.com/k-next/ideas/issues/48).
