### ISSUE TITLE
[Panel] Make all modals confirmable by keyboard

### ISSUE THREAD

**Issue by gerricom** [getkirby/kirby#927]
I have tested some of the modal popups of Kirby and they are not really consistent in submitting them via keyboard (aka pressing enter)

- [x] rename page (okay)
- [x] change url (okay)
- [x] change page status (okay)
- [x]  change page tempate (nothing happens)
- [x] delete page (modal closes, but nothing happens)
- [x] rename file (okay)
- [x] delete file (modal closes, but nothing happens)

There is issue #837 with a similar problem, but I can't reproduce it in the current nightly build. There might be other modals I missed for now...

**Comment by bastianallgeier** [comment]
✅
