### ISSUE TITLE
[Panel] decrease running before throwing error in api/request.js

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#936]
Just reading through the code and noticed that you're not decrease `this.running` [here](
https://github.com/k-next/kirby/blob/7bbacd0f7cd2f90378eaaec4b50700681694002b/panel/src/api/request.js#L27) like a couple of lines [below](https://github.com/k-next/kirby/blob/master/panel/src/api/request.js#L42).

**Comment by distantnative** [comment]
The `throw json` causes that we will jump into the `.catch()` part of the code. And in there we do decrease it. So all good. But I love how closely you look at the code 👍

**Comment by joernroeder** [comment]
ah right, i've missed that ✌️
