### ISSUE TITLE
[Cms] Roots for assets and media cannot be outside root('index') or named differently

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#937]
Using a composer-based setup (based on DevKit), I am trying to keep assets and media under site (and not the default of index), and have the following in my bootstrap:

```
$kirby = new Kirby([
    'roots' => [
        'base'     => $base    = __DIR__,
        'index'    => $index = $base . '/public',
        'content'  => $base . '/content',
        'site'     => $site = $base . '/site',
        'assets'   => $site . '/assets',
        'media'    => $site . '/media',
        'plugins'  => $site . '/plugins',
        'storage'  => $storage = $base . '/storage',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'sessions' => $storage . '/sessions',
    ]
]);
```

However, in beta5, this is not working (in previous betas, assets were under site and media were in index): 

![screen shot 2018-08-25 at 11 58 29](https://user-images.githubusercontent.com/88007/44617169-6fbf4b80-a85e-11e8-85a8-a40240101ba4.png)

And the panel is a worse:

![screen shot 2018-08-25 at 11 58 45](https://user-images.githubusercontent.com/88007/44617168-68983d80-a85e-11e8-9727-2ae572424bb0.png)

If I then move assets and media back into the default of index everything then works:
```
        'index'    => $index = $base . '/public',
        'assets'   => $index . '/assets',
        'media'    => $index . '/media',
```

And trying to call media and assets anything other than "media" or "assets", even in the index folder, does not work.

**Comment by bastianallgeier** [comment]
This is not a bug. The site folder is blocked in the htaccess for security reasons. Apache cannot access anything inside.
