### ISSUE TITLE
Call to a member function sort() on array (beta 5)

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#942]
Unable to sort pages in panel (beta 5).

**Comment by bnomei** [comment]
hotfix: comment Kirby\Cms\Page.php lines 692-694

**Comment by bastianallgeier** [comment]
When does this happen?

**Comment by nilshoerrmann** [comment]
Just try to drag around pages in a "listed" section.
Throws an error in Firefox.

**Comment by bastianallgeier** [comment]
@nilshoerrmann thanks! This helped :) Just fixed it.
