### ISSUE TITLE
[Panel] open button in headline does not open current page if is childpage (home page)

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#943]
browsing to a subpage then clicking 'open/öffen' in panel below title opens parent but not current page like expected.

**Comment by texnixe** [comment]
How can I reproduce this in a Starterkit?

**Comment by bnomei** [comment]
hm... will check later... maybe its my current devkit setup.

**Comment by bastianallgeier** [comment]
?

**Comment by bastianallgeier** [comment]
I can't reproduce this.

**Comment by bnomei** [comment]
@bastianallgeier sry i am really busy with another project. i will try this again with the project that had the problem and report back as soon as i can.

**Comment by bnomei** [comment]
problem still exists with nightly build. BUT it only happens for the 'home'-page.
 i did set `'home'  => 'projects',` in config. turning this on and off also toggle the faulty behaviour.

**Comment by bastianallgeier** [comment]
✅
