### ISSUE TITLE
[Panel] this.image is null

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#947]
After updating to beta 5 I get this error in the panel:

![bildschirmfoto am 2018-08-31 um 12 33 31](https://user-images.githubusercontent.com/25466/44907954-1f426500-ad1a-11e8-80e0-6a20743f914c.png)

**Comment by pju-** [comment]
That error appears in Beta 5 if you have set the layout to cards and not all items in the section have a suitable image available.
I've already submitted a [pull request](https://github.com/k-next/kirby/pull/945) for this

**Comment by nilshoerrmann** [comment]
Thanks @pju-, I can confirm that your fix is working.

**Comment by bastianallgeier** [comment]
✅
