### ISSUE TITLE
[Cms] Page models don't work in multi language setup

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#949]
steps to reproduce:
1. start with plainkit beta 5

2. Create a page model:
   **site/models/home.php**

   ```php
   <?php 
   use Kirby\Cms\Page; //this line's optional

   class HomePage extends Page {
     public function sayHello() {
       echo "Hello World";
     }
   }
   ```

3. use it in a template:
   **site/templates/default.php**
   ```php 
   <?php $page->sayHello(); ?>
   ```

4. Test if it works in the frontend: it works

5. Install the panel and add a language in the language manager

6. Test again: it does no longer work.

**Comment by bastianallgeier** [comment]
✅
