### ISSUE TITLE
[Panel, REST API] Pages of sorted files are displayed in the wrong order

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#951]
Sorted images are not listed in the correct order in the JSON dataset that is returned by a GET request. Instead they are sorted by filename. This leads to the file pages being displayed in the wrong order in the panel.

<img width="1440" alt="screen shot 2018-09-04 at 10 23 51" src="https://user-images.githubusercontent.com/8195463/45019697-46a47500-b02d-11e8-994a-71f62bfcdb03.png">

<img width="1440" alt="screen shot 2018-09-04 at 10 23 59" src="https://user-images.githubusercontent.com/8195463/45019699-46a47500-b02d-11e8-990a-1d836ddee405.png">

**Comment by bastianallgeier** [comment]
✅
