### ISSUE TITLE
[Panel] Card layout wrapping

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#952]
When browsing the panel on a wide screen I see the following effect:

![bildschirmfoto am 2018-09-05 um 10 25 48](https://user-images.githubusercontent.com/25466/45080862-212f6e00-b0f6-11e8-9ded-8430629b303d.png)

In this case the action bar is supposed to move to the next row.
It doesn't happen on smaller screens for some reasons.

**Comment by bastianallgeier** [comment]
Which browser? I haven't seen this happening in Chrome so far.

**Comment by nilshoerrmann** [comment]
This is on latest Firefox on Mac (62).

**Comment by nilshoerrmann** [comment]
A bit more context how the grid looks like:

<img width="1017" alt="bildschirmfoto 2018-09-17 um 19 53 18" src="https://user-images.githubusercontent.com/25466/45672032-5e005980-bb27-11e8-850e-17f71e230bdb.png">

**Comment by nilshoerrmann** [comment]
We just checked with our client: in case you need it, we can give you access to the install we are experiencing the issue on.

**Comment by bastianallgeier** [comment]
✅
