### ISSUE TITLE
[Panel] Max length indicator

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#953]
I like the idea to show a lower or equal to sign in the max length indicator:

<img width="1010" alt="bildschirmfoto 2018-09-06 um 10 07 55" src="https://user-images.githubusercontent.com/25466/45143927-ec3a1e80-b1bc-11e8-8268-a3b4d61f5859.png">

But while code editor users are used to the `<=` notation, it would be nice to have the actual `≤` character in the panel. I haven't used the min length setting but my guess is that the same applies to `>=` vs. `≥`.

Although I like the textual indicator, it is not very obvious when you've reached the limit given for the current field. If you haven't watched the input field closely you might simply miss this fact: neither the field itself nor the indicator change visually. It would be good to consider highlightings, maybe making the input's outline flash in another colour once per additional keypress and change the indicator's colour to red?

**Comment by nilshoerrmann** [comment]
I just noticed that the kind of highlighting I was seeking for is already in place _when you open a page with content **exceeding the limit already**_:

<img width="1012" alt="bildschirmfoto 2018-09-06 um 10 54 11" src="https://user-images.githubusercontent.com/25466/45146524-59e94900-b1c3-11e8-8a11-9b97e76b8d58.png">

This error handling is missing while typing.

**Comment by bastianallgeier** [comment]
I fixed the typographic part of this issue. Could you please double-check the live validation? It's working in Chrome.

**Comment by nilshoerrmann** [comment]
Live validation does work in the sense that I'm not able to type more characters than specified in the blueprint, but I don't get any live highlighting (red borders and such).

The typographic enhancements landed as promissed. 

P. S.: I had to delete the `/media/panel` folder in order to get the latest changes in the browser. Is this intended behaviour?

**Comment by bastianallgeier** [comment]
@nilshoerrmann weird! I just tried in Firefox, Chrome and Safari and live validation / highlighting works in all three of them. Which browser/version do you use? 

I forgot to bump the version number for the nightly build. That's why you had to manually delete the media folder.

**Comment by nilshoerrmann** [comment]
I just tried Chrome and it doesn't work there either.

This is my blueprint:

```yaml
      title:
        label: Title
        type:  text
        maxlength: 15
```

Anything wrong in there?

**Comment by bastianallgeier** [comment]
Thing is, that you can't really break the maxlength rule, because the input already stops you from entering too many characters. That's why the error highlighting never kicks in unless you already stored something that is too long and you add the validation afterwards. 

But you can try with the minlength to validate that it is working: 

```yaml
      title:
        label: Title
        type:  text
        maxlength: 15
        minlength: 10
```

**Comment by nilshoerrmann** [comment]
Hm, maybe we are talking about different things: 

What's working is the highlighting when the content exceeds the max lenght on load. Like when I've edited the content file directly or added the max size at a later point with content already existing.

What's missing in my eyes is a notification that I've reached the maximum length while typing. This is where I'd expect the counter to turn red and – as an idea – the input to flash (e. g. using the red border used for errors).

Currently, I have no feedback in any browser when typing across the maximum length border that this is the end. It's just that my typed characters are ignored.

**Comment by bastianallgeier** [comment]
We are talking about the same thing. It's a browser limitation/feature. If we apply the maxlength attribute on the input, there's no chance to validate if you type further, because you actually don't. The input is never happening because the input field is ignoring your input. The only option would be to remove the maxlength attribute and not let browsers stop you from typing. Then our highlighter would work again. But then you would also end up with too many characters in that case. Maybe it's still better that way. I'm not sure.

**Comment by nilshoerrmann** [comment]
Aha, that makes sense. 
Still the counter should change color as soon as the current count equals the maximum count, shouldn't it?

**Comment by bastianallgeier** [comment]
No, because it's still correct. The counter only switches to red if you are over or under the limit.

**Comment by bastianallgeier** [comment]
I removed the maxlength attributes from text inputs and textareas and I think it actually really feels more understandable for editors that way. Let me know what you think about it after tonight's build. I will close this ticket in the meantime.

**Comment by nilshoerrmann** [comment]
Okay, this makes sense. 

I still see a usabilty problem here: it's not prominent that I've reached the end.

I was typing without looking at the screen, wasn't aware of the limit and didn't notice when looking at the screen again that half of my typed words weren't recorded because there wasn't any visible feedback. Everything looked just fine because I didn't expect the interface to just cut my text and because the interface didn't indicate this fact.

**Comment by nilshoerrmann** [comment]
> I removed the maxlength attributes from text inputs and textareas and I think it actually really feels more understandable for editors that way. Let me know what you think about it after tonight's build. I will close this ticket in the meantime.

Hadn't seen this comment: this is a good change, thanks 👍
