### ISSUE TITLE
[Cms] js helper gets weird

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#955]
```php
<?= js('assets/js/script.min.js' . $time, ['async']) ?>
```

**The expected result is this:**

```html
<script src="https://example.com/assets/js/script.min.js" async></script>
``` 

**The real output is this:**

```html
<script 0="async" src="https://example.com/assets/js/script.min.js"></script>
```

If I set the `async` value to `true` it works.  Anyway, I don't see when `0="async"` is ever going to be useful.

### Solution

If just added a key, just add the attribute witout a value.

**Comment by texnixe** [comment]
Should be 

```
<?= js('assets/js/script.min.js', ['async' => true]) ?>
```
Or just put `true` for the async attribute, see the K2 docs: https://getkirby.com/docs/cheatsheet/helpers/js

**Comment by lukasbestle** [comment]
If you want the `async` attribute in particular, you can actually do this:

```php
<?= js('assets/js/script.min.js', true) ?>
```

However I agree with @jenstornell that the current behavior isn't perfect. We should detect numeric keys in the `Html::attr()` method and convert them internally.

**Comment by bastianallgeier** [comment]
I don't really see why we should make Html::attr more complex with this. If you pass the attributes as array, the array must be a key/value presentation of the attributes. That's just the basic rule for it. If we check for numeric keys just to avoid this, we make the function slower, which is used quite often.
