### ISSUE TITLE
[Cms] Return Response from Page::render()

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#958]
The [`Page::render`](https://github.com/k-next/kirby/blob/3.0.0-beta-5/src/Cms/Page.php#L1007) method says that it returns a string, but actually it returns a `Response` object, which will silently be converted to a string. I think we should change the return type, but we will need to check if anything depends on the return value being a string.

Also: I think the whole Response object should be cached including all headers, otherwise content representations won't be cached properly, also see issue 653 in the v2 core repo (not linked to avoid leaking the v3 repo).

**Comment by bastianallgeier** [comment]
I fixed the return type. Could you please create a new ticket for the cache thingy?

**Comment by lukasbestle** [comment]
See #978.
