### ISSUE TITLE
[Cms] Unhandled 404 errors on root level with multilanguage setup

### ISSUE THREAD

**Issue by danielkratz** [getkirby/kirby#963]
Steps to reproduce: 
1. Setup Kirby Beta 5 with at least two languages
2. Request e.g. localhost/kirbyproject/en/this-page-doesn-t-exist
3. See the Kirby 404 error page
4. Request e.g. localhost/kirbyproject/this-page-doesn-t-exist (without language code)
5. An Exception occurs (No route found for path)

Expected beahaviour: 
The request should be answered with some 404 page instead of generating a 500 server error.

**Comment by bastianallgeier** [comment]
✅
