### ISSUE TITLE
[Ui] Missing dialog footer wrapper when using slot

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#964]
Using the UI kit dialog component, if you set a custom dialog footer using the `footer` slot like this, the rendered markup is missing the wrapping element for the footer, leading to an incorrect display of the dialog. This is due to an incorrect nesting order in [`Dialog.vue`](https://github.com/k-next/kirby/blob/master/panel/src/ui/components/Navigation/Dialog.vue#L17-28).

Template:
```html
<k-dialog ref="dialog">
    Body

    <template slot="footer">
        Footer
    </template>
</k-dialog>
```

Rendered markup:
```html
<div class="k-dialog-box">
    <div class="k-dialog-body">
        Body
    </div>
    Footer
</div>
```

Expected:
```html
<div class="k-dialog-box">
    <div class="k-dialog-body">
        Body
    </div>
    <footer class="k-dialog-footer">
        Footer
    </footer>
</div>
```

**Comment by bastianallgeier** [comment]
✅
