### ISSUE TITLE
[Panel] Saving a new page, status not respected

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#967]
- Create a new draft.
- Add some dummy text to text.
- Its status is showing as draft... change the status to Published... the status shows as Published
- Click Save.

But, despite what is displayed, it has been saved with a status of draft, not published.

**Comment by bastianallgeier** [comment]
I just tried, but cannot reproduce this :/

**Comment by omz13** [comment]
I was running with the version from about two days ago. Perhaps the latest changes fixed it? I will test and let you know later this week (am currently on mini-holiday).

**Comment by pju-** [comment]
Might be related to [this](https://github.com/k-next/kirby/issues/944)?

**Comment by bastianallgeier** [comment]
@pju- I think this was the same issue. 
@omz13 feel free to reopen if it's not fixed after tonight's nightly build.
