### ISSUE TITLE
[Panel] Hidden Pages still available with < > navigation

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#968]
When hiding pages (such as the error page) in the panel they can still be accessed via the < > navigation:

<img width="1221" alt="screen shot 2018-09-17 at 13 47 12" src="https://user-images.githubusercontent.com/8195463/45621448-9a2caf00-ba80-11e8-80b8-04ccf7192732.png">
<img width="1232" alt="screen shot 2018-09-17 at 13 47 19" src="https://user-images.githubusercontent.com/8195463/45621450-9ac54580-ba80-11e8-9f8b-1bfd1e9088af.png">
<img width="1246" alt="screen shot 2018-09-17 at 13 47 25" src="https://user-images.githubusercontent.com/8195463/45621451-9ac54580-ba80-11e8-94a5-12a4e4a8d6b9.png">

**Comment by bnomei** [comment]
@studioscholz i would not want all `status == invisible` pages to be excluded be default. but a blueprint option to `hide` certain pages from the panel might be a good idea.

**K2 has**
https://getkirby.com/docs/panel/blueprints/page-settings#hide-page

**K3 needs**
https://nnnnext.getkirby.com/docs/guide/blueprints
```yaml
option:
  hide: true
```
and when hidden the page should not appear in the panel pages sections, arrow nav or be accessible via the search.

**Comment by bastianallgeier** [comment]
✅
