### ISSUE TITLE
[Panel] Textarea Toolbar and Markdown

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#969]
The formatting toolbar only offers Kirbytext syntax for links and image and doesn't support Markdown syntax. I'd expect this to be configurable.

**Comment by bastianallgeier** [comment]
✅ The dialogs now listen to the panel > kirbytext option and create markdown or kirbytext accordingly.

**Comment by nilshoerrmann** [comment]
Just trying to figure this out: is that "panel > kirbytext option" syntax documented anywhere?

**Comment by nilshoerrmann** [comment]
Okay, found it by trial and error: 

```php
return [
    'panel' => ['kirbytext' => false]
]
```
