### ISSUE TITLE
[Cms] Translation helper returns wrong language strings

### ISSUE THREAD

**Issue by danielkratz** [getkirby/kirby#972]
I setup a multilanguage page based on Beta 5. The language configuration contains German and English. 

```
return array (
  'code' => 'de',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'de_DE',
  'name' => 'Deutsch',
  'translations' => [
    'readmore' => 'Mehr lesen',
  ]
);
```

```
return array (
  'code' => 'en',
  'default' => false,
  'direction' => 'ltr',
  'locale' => 'en_US',
  'name' => 'English',
  'translations' => [
    'readmore' => 'Read more',
  ]
);
```

Using the translation helper in a template `<?= t("readmore") ?>` I always get the English string regardless in which language I am.

**Comment by bastianallgeier** [comment]
✅

**Comment by dpointeck** [comment]
I'm on Beta 6 and I have the same problem that my default language is german but the t() helper function defaults to english.

The problem occurs when I select ``` "url" => "/" ``` for the main language.

**Comment by texnixe** [comment]
I can reproduce this.

**Comment by bastianallgeier** [comment]
✅ I'm pretty sure I got it right this time :)
