### ISSUE TITLE
[Panel] Publishing from paginated sections

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#973]
Think of the following setup and workflow:  
(pages are content files, "pages" are paginated views of sections)

- We have a view with sections for drafts, listed and unlisted pages. 
- The unlisted pages section has three "pages". 
- We like to publish one page after the other, starting on "page 3" of the unlisted section working our way through to "page 1".

This works well until you reach the last unlisted page on "page 3". After publishing this page, the section displays an empty list of unlisted pages ignoring "page 1" and "page 2".

![bildschirmfoto am 2018-09-18 um 11 55 55](https://user-images.githubusercontent.com/25466/45679865-d112cb80-bb39-11e8-9d55-3aa5be4bb435.png)

## What I'd expect

The panel should move to the previous "page" automatically and keep the navigation visible as long as needed.

## Workaround

Manually reload the panel.

**Comment by bastianallgeier** [comment]
✅
