### ISSUE TITLE
[CMS] Implement missing pagination options

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#977]
It seems that some pagination options like `variable` are not implemented yet, but mentioned in the docs. See https://nnnnext.getkirby.com/docs/framework/cms/pages/paginate

`$page->children()->listed()->paginate(10, ['variable' => 'seite']);` throws an error:

<img width="1176" alt="error" src="https://user-images.githubusercontent.com/15672385/45699381-1b13a580-bb6a-11e8-8db2-da2907de62e2.png">

**Comment by bastianallgeier** [comment]
✅
