### ISSUE TITLE
Page::render(): Cache Response object

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#978]
The [Page::render()](https://github.com/k-next/kirby/blob/3.0.0-beta-5/src/Cms/Page.php#L1007) method currently just caches the return value of the template, but returns a `Response` object.

I think the whole `Response` object should be cached including all headers, otherwise content representations won't be cached properly, also see issue 653 in the v2 core repo (not linked to avoid leaking the v3 repo).

**Comment by bastianallgeier** [comment]
✅
