### ISSUE TITLE
[Documentation] Migration K2 > K3

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#979]
- Post ONE conversion at a time.
- Upvote 👍  if you want a conversion to be documented (sooner than others).
- add a ❤️ if you want kirbys core to try migrating this automatically

this is done to prioritize what to document for
https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2

**Comment by bnomei** [comment]
**content folder structure**

> needed since `01-` will be `01_`

**Comment by texnixe** [comment]
blueprint folder structure

> required because separate folders for different types of blueprints

**Comment by texnixe** [comment]
account folder structure

> accounts now have their own folder

**Comment by bnomei** [comment]
**disable k2 plugins so they do not break current plugin folder**

> afaik this is done by just adding a `.` before the foldername, right?

**Comment by bnomei** [comment]
**htaccess file**

> k3 has a different default htaccess file

**Comment by texnixe** [comment]
**index.php**

> K3 has a different index.php

**Comment by texnixe** [comment]
**thumbs folder > media folder**

**Comment by texnixe** [comment]
**assets/avatars folder**

> avatars are now stored in the account folder

**Comment by texnixe** [comment]
**License file instead of config setting**

**Comment by bnomei** [comment]
**site.php**

> folder setup is now done at index.php
> https://nnnnext.getkirby.com/docs/guide/configuration#custom-folder-setup

**Comment by texnixe** [comment]
**config file syntax**

> including `c::set()/c::get()`

**Comment by texnixe** [comment]
**controller syntax**

**Comment by texnixe** [comment]
**move file settings from blueprints to separate file blueprints**

**Comment by bnomei** [comment]
**no more kirby cli**

> removed in favor of composer

**Comment by texnixe** [comment]
**blueprint subpage settings now in page blueprints**

**Comment by texnixe** [comment]
**authentication for frontend stuff like creating users, pages etc. required**

**Comment by texnixe** [comment]
**some toolkit classes no longer exist or changed**

> removed e.g. database, bricks, folder
> changed, e.g. upload class (needs authentication)

**Comment by bnomei** [comment]
**kirbytags** are now defined via plugins

> `site/tags` folder

**Comment by texnixe** [comment]
**user permissions => yaml files**

**Comment by bnomei** [comment]
**no more widgets**

> `site/widgets` folder

**Comment by bnomei** [comment]
**no more subpage builder based on blueprint**

**Comment by texnixe** [comment]
**pre/post kirbytext filters now registered as hooks**

**Comment by bnomei** [comment]
**some panel fields types were removed**

**Comment by texnixe** [comment]
**Translations l class => t class**

**Comment by texnixe** [comment]
**route filters removed**

**Comment by texnixe** [comment]
**remove panel folder**

> everything in one folder now

**Comment by texnixe** [comment]
**`$site->user()` => `$kirby->user()`**

**Comment by texnixe** [comment]
**Sending email**

**Comment by texnixe** [comment]
**Dropped support for PHP < 7**

**Comment by bnomei** [comment]
**blueprint fields options**
`readonly: true` is now `disabled: true`

**Comment by bnomei** [comment]
`page('projects/child/grandchild')`-helper will not find drafts 
but `$kirby->page('projects/child/grandchild')` will do.

**Comment by bnomei** [comment]
how to setup sort of subpages using `num` in panel changed.
https://github.com/k-next/getkirby.com/issues/48

> might be part of documenting blueprint changes
