### ISSUE TITLE
[Toolkit] V::url should assert true for http://special---offer.com/

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#98]
Also: `http://localhost/test/`
See https://github.com/getkirby/toolkit/issues/255.

**Comment by distantnative** [comment]
After lot of research I came to the conclusion that there is no perfect regex for URLs so far and that we already use the "best" one out there, covering the most of all edge cases. Still leaves us with a few exceptions that we fail, but those edge cases might be rare enough to be fine with them.

**Comment by bastianallgeier** [comment]
I see it the same way!

**Comment by lukasbestle** [comment]
Have we considered using `filter_var($url, FILTER_VALIDATE_URL)` before?

If that filter is in any way well-built, it may safe us a lot of trouble. But I haven't tested how well it works with those edge-cases.

**Comment by distantnative** [comment]
That one fails all our tests including unicode characters, while the current regex gets them right.

**Comment by bastianallgeier** [comment]
In my experience filter_var is way too strict and produces a lot of false negatives.

**Comment by lukasbestle** [comment]
Well, then let's keep our regex. :)
