### ISSUE TITLE
[Panel] Errors on first page load

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#980]
I've encountered errors when first loading a page in the panel – this is the latest error I got just now:

```
{"status":"error","exception":"Whoops\\Exception\\ErrorException","message":"mkdir(): File exists","file":"by\/src\/Toolkit\/Dir.php","line":173,"code":500}
```

When reloading the page, everything works just fine. This does not happen for every first page load and I haven't quite figured out just *when* an error comes up.

**Comment by bastianallgeier** [comment]
@johannahoerrmann Does this still exist?

**Comment by johannahoerrmann** [comment]
It hasn't happened in a while, so I'm closing this.
