### ISSUE TITLE
[Starterkit] Don't overwrite reserved $page variable in Header snippet

### ISSUE THREAD

**Issue by danielkratz** [getkirby/kirby#982]
(I can't open issues in the starterkit repo. I hope it's ok to put it here.)

In the header snippet the reserved $page variable is overwritten in the foreach loop for the navigation. It's not possible to use the Kirby variable afterwards. Better change the variable name used in the loop. 
See also: https://getkirby.slack.com/archives/CBN859614/p1536659663000100

**Comment by bastianallgeier** [comment]
✅ just fixed it.
