### ISSUE TITLE
[Cms] Reimplement $site->language() functionality

### ISSUE THREAD

**Issue by danielkratz** [getkirby/kirby#983]
I couldn't find a Kirby 3 equivalent to the $site->language() method yet to access the information about the current language. This is important e.g. to get the current language code or to output a language nav like the implementation in the Kirby 2 langkit). 

Please be kind if there is a new approach to this already. :)

**Comment by bastianallgeier** [comment]
All that stuff is now available from the $kirby object, which made a bit more sense from an architectural stand point. 

```php
$kirby->language()
$kirby->languages()
$kirby->defaultLanguage()
```
