### ISSUE TITLE
[Panel] Error after dragging files into textareas

### ISSUE THREAD

**Issue by christianschley** [getkirby/kirby#984]
When i drag files per drag&drop from a files-section (in this example on the page called "home") into a textarea field there is this code generated automatically:

(file: home/filename.pdf) 

That throws the following error in the frontend:

<img width="1266" alt="bildschirmfoto 2018-09-19 um 18 21 56" src="https://user-images.githubusercontent.com/25037153/45767018-647ef600-bc39-11e8-87dc-a767d7a32c8a.png">

When i delete the foldername and just use "(file: filename.pdf)" its all working fine!

**By the way:** it works fine with images and the foldername...
(image: home/filename.png)

**Comment by christianschley** [comment]
Or is this in any way an intended behaviour and i made any mistake?

**Comment by bastianallgeier** [comment]
✅
