### ISSUE TITLE
plugin's index.css is not processed due to wrong MIME-type

### ISSUE THREAD

**Issue by TimOetting** [getkirby/kirby#985]
When in Version 3.0.0-beta-5.3 my plugin's css file under site/plugins/my-plugin/index.css file loaded by the browser but not processed.

I run the side by starting a PHP Server by running `php -S localhost:8889 kirby/router.php`

The Devtools inside Chrome say 
﻿
`projects+trees-and-stars-and-stuff:11 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8889/media/plugins/index.css".`

These are my observations so far:

- When storing the file in site/plugins/my-plugin/index.css it works with 3.0.0-beta-5 but not with 3.0.0-beta-5.3
- When storing the file in site/plugins/my-plugin/assets/index.css I have the problem with both versions
- When trying to set up a composer setup for the plugin including a config.php and the index.php with just the autoload line in it, I again get the error with both 3.0.0-beta-5 and 3.0.0-beta-5.3

**Comment by TimOetting** [comment]
I think I've found the cause of the error:

At the bottom of the constructor of the Request class (/kirby/src/Http/Response.php, line 87) it says

```
        // automatic mime type detection
        if (strpos($this->type, '/') !== false) {
            $this->type = F::extensionToMime($this->type) ?? 'text/html';
        }
```
I think the if-query should be the opposite, changing from `!==`to `===`. Then we ask "if the type has no '/' in it, generate a mime type or take 'text/html' as a fallback".

**Comment by TimOetting** [comment]
However, the problem remains if I use the index.php as my composer entry point (containing only `require_once __DIR__ . '/vendor/autoload.php';`) and put the main plugin code inside the config.php.

**Comment by bastianallgeier** [comment]
✅
