### ISSUE TITLE
html::email notice on empty string

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#986]
I sent a value to `html:email` like this:

```php
echo html::email($my_value);
```

If there is an email it works.  To get rid of errors along the way, I send an empty string if there is no email. I also did that with this function, expecting it to output nothing.

**So the result of my variable in this case would be:**

```php
echo html::email('');
```

>Notice: Undefined offset: 0 in D:\projects\testing\kirby\src\Toolkit\Html.php on line 172

Instead of a notice, just send back an empty string, similar to how snippets work when no snippet is found.

**Comment by bastianallgeier** [comment]
✅
