### ISSUE TITLE
[Panel] Disable preview button in the context menu if preview: false

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#987]
I used the latest nightly build with the new `preview: false` option:

The preview button is hidden in the page itself, but not in the context menu:

<img width="267" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/45801522-620db200-bcb4-11e8-9d2f-70916386b0b0.png">

**Comment by bastianallgeier** [comment]
✅
