### ISSUE TITLE
[Cms] Add option to customize paths to plugin assets

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#989]
Currently, the only option to load JavaScript and CSS assets for a plugin is to place an `index.js` or `index.css`, respectively, in the plugin root. That’s a sensible default especially for less complex plugins. However, when working with a more complex setup and using bundlers or pre-/postprocessors, most devs would probably want to have dist files in a separate sub directory in order to keep a clear directory structure.

**Comment by ghost** [comment]
This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) to [k-next/ideas#49](https://github.com/k-next/ideas/issues/49).
