### ISSUE TITLE
[Toolkit] Fix cli detection

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#99]
In the new toolkit classes, the cli detection has been included directly in some classes instead of introducing `r` so far. This fix should apply to them: https://github.com/getkirby/toolkit/commit/3834f9809e545f0d430059aa427de89d15001515

**Comment by bastianallgeier** [comment]
The cli detection has been moved to the Server class, which makes more sense in my opinion. Even more correct would probably be having some kind of Env class. But I don't want to introduce yet another class. The Request class has an additional cli() method, which uses the Server class method.
