### ISSUE TITLE
[Panel] Required select field in structure results in validation error on save

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#990]
I used the latest starterkit beta with the latest kirby nightly build:

I set the `icon` field in the structure field of the »Form Demo« to `required: true`.

Even though I selected an icon, there was still the error »Please fix all form errors...«.

<img width="1247" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/45821003-72d81b00-bce8-11e8-98ee-b0c93e0fc6c2.png">

**Comment by bastianallgeier** [comment]
✅
