### ISSUE TITLE
[Cms] Content-type of content representations changed

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#993]
Hey Ho,

prior to the fixes for #981 the content representation has been of content-type `application/json` correctly, now it is just `json`.

This breaks the nice beautification for JSON in Firefox. 😢

**Comment by bastianallgeier** [comment]
I'm pretty sure I fixed this yesterday :)

**Comment by ralfgoeke** [comment]
Dang, you did! Sorry for not testing the current nightly first. :-*
