### ISSUE TITLE
[Panel] Content save overwrites changed title

### ISSUE THREAD

**Issue by danielkratz** [getkirby/kirby#994]
Setup: Beta 5 Starterkit with latest Nightly (20.09.) and multilanguage setup on Xampp with PHP 7.2 on Windows 10.

Steps to reproduce: 
* Open a page in the panel (for example a news article)
* Change the title of the page
* Title gets successfully saved with a request to /title
* Now change some regular content
* Save the content changes 
* Content get's saved with a request to /sections/content
* Reload the panel page and see that the title was reset to the state when the page was previously loaded

My guess: The payload of the /sections/content request contains the old title and overwrites the new one.

**Comment by bastianallgeier** [comment]
✅
