### ISSUE TITLE
[CMS] allow collections for section parent option

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#997]
currently only a single page is allowed and its children iterated.
allowing a collection would make it more versatile.
**edited**
the collection should NOT be called rendering its `children` but used as it is.

@pju- 
> Is there any way to filter a section in the panel to only show certain entries (besides by status)?
> 
> Why this would be great:
> You could for example show ongoing events nice and big card layout and past events in a simple list overview

**idea**
`parent: site.find("blog")` =>
`parent: kirby.collection("ongoing-events")`

**Comment by pju-** [comment]
Actually I just realized that what you described is already possible. You can have the section show the children of multiple pages. It's just that my usecase is different.

I don't want the children of the collection, I want the actual items of the collection.

So two possible solutions come to my mind:

1. Give sections an additional _selection_ option:
`selection: items.filterBy(…)`

2. Give sections a collection option (though that would probably conflict with "parent"?)
`collection: kirby.collection("ongoing-events")` or `collection: site.index.filterBy(…)` or similar

**Comment by omz13** [comment]
Having a collection be a parent would be very much appreciated.

**Comment by pju-** [comment]
Aaaand I just found there is already an existing ticket for this: https://github.com/k-next/kirby/issues/635

**Comment by bnomei** [comment]
i still think having the collection instead of just allowing pages.method(s) would be better. in my case since i cache all my collections with my lapse and autoid/modifed plugins. that would also speed up the panel then.

**Comment by pju-** [comment]
Yes @bnomei  I agree that using collections is nice, but that works just fine for me with the syntax you put in your example above?
/edit – To be a bit more clear: you can have more than one parent page for the section. You can get this using a collection or using pages.methods. The thing is that parent: always expects a collection of parents, but I need a collection of the children.

It's just that it's not helpful in my usecase.

**Comment by bnomei** [comment]
like said in slack, the collection should not be called for its children to make it work (as i hoped it would). currently it is not.
