### ISSUE TITLE
[Panel] Save bar "missing" / layout issues on iOS

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#998]
There are heavy layout issues on iOS with regards to the positioning of the save bar. When you edit a page two effects might occur:

1. the save bar is visible but you cannot scroll,
2. the save bar is "invisible" because it's pushed to the very bottom of the screen outside the viewport.

This results in either an unusable interface or in situations where the user doesn't know how to save a page.

There are also possible chainings of these effects when you first change one field but switch to another field before saving: the save bar will be displayed correctly in the first step and then jump to the document's bottom in the second step. For the user it's just gone.

## Reasons and solutions

We had a similar issue in a project of ours and it took us a while to figure out how to circumvent these problems. The source of the issue is the way mobile Safari treats the viewport when the keyboard is visible. If I remember correctly, the browser doesn't recalculate the viewport height in these cases but centers the existing viewport in the space above the keyboard. This results in problems with elements sized relatively to the viewport, either by using the `vh` unit or by relying on `flex-grow` and `overflow: scroll/auto`.

In Kirby's case, all is about positioning the save bar fixed to the bottom of the screen. A rule of thumb that worked for us was to never use `overflow: scroll/auto` on an element that has a fixed element below and to rely on the main window to be scrolled. Sticky bottom positioning of an element has then to be achieved using `position: sticky`.

Sticky positioning is well supported in modern browsers, on desktop as well as on mobile. But there are a few issues on older Android versions. To handle these cases, it makes sense to originally position the element you want to position stickily in the upper part of the interface (in the case of Kirby right under the `.k-header` for example) and then use `@supports (position: sticky) {}` only in supporting browsers.

@bastianallgeier, if you need help to fix this issue I can see if I find the time to take a look at Kirby's styles. Or I can grant you access to our project where we were able to bypass this issue using the mentioned technique so you have a working example.

**Comment by bastianallgeier** [comment]
We already have a ticket for this: https://github.com/k-next/kirby/issues/682
I'm brutally closing this even though your text is quite helpful. But I need to keep an overview and I think Github is auto-magically linking tickets anyway when they get mentioned.

**Comment by nilshoerrmann** [comment]
👍
