### ISSUE TITLE
[Panel] Notify user about server-side changes

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#999]
If two users edit the same page simultaneously, one user will overwrite the changes of the other: the user saving last wins.

This is not a good situation.

I know that it's not possible to notify the two users about the conflicting work while they are editing because everything is stored locally first. But as soon as the first user saves his/her work, it would be advisable to notify the other user. 

Wouldn't it be possible to store the last modified date when loading a page in the panel and compare this to the current last modified date of the same file on the server prior saving? If the dates match, proceed a usual. If the dates do no longer match, notify the user and maybe present him with a diff view of the changes on the server.

**Comment by bastianallgeier** [comment]
I'm really sorry, but this is also a duplicate :) https://github.com/k-next/kirby/issues/250

**Comment by nilshoerrmann** [comment]
Oh, I‘m sorry. I searched but didn‘t find that one.

My solution is a bit different though as it doesn‘t require locking (which takes place before editing).
